NavelRock_Up2_MapScripts::
	.byte 0


NavelRock_Up2_EventScript_SmithNPC1::
# 5 "data/maps/NavelRock_Up2/scripts.pory"
	msgbox NavelRock_Up2_Text_SmithNPC1, MSGBOX_NPC
	end


NavelRock_Up2_EventScript_SmithNPC2::
# 14 "data/maps/NavelRock_Up2/scripts.pory"
	msgbox NavelRock_Up2_Text_SmithNPC2, MSGBOX_NPC
	end


NavelRock_Up2_Text_SmithNPC1::
# 9 "data/maps/NavelRock_Up2/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

NavelRock_Up2_Text_SmithNPC2::
# 18 "data/maps/NavelRock_Up2/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
