RustboroCity_Flat1_2F_MapScripts::
	.byte 0


RustboroCity_Flat1_2F_Text_ComingUpWithMealsIsHard::
# 5 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, it's so hard every day\p"
	.string "What's hard? You need to ask?\p"
	.string "It's trying to figure out what to make\n"
	.string "for meals every day.\p"
	.string "It really isn't easy coming up with\n"
	.string "meals every day.$"

RustboroCity_Flat1_2F_Text_HelloDoYouKnowFunnyPhrase::
# 9 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, hello! Welcome to the PEPPER\n"
	.string "household.\p"
	.string "I have a question for you. Have you\n"
	.string "ever baby-sat?\p"
	.string "You see, I'm a new father, so raising a\n"
	.string "child is all new to me.\p"
	.string "And I have a problem. My daughter WALDA\n"
	.string "doesn't laugh enough.\p"
	.string "I think she'd laugh for me if I told her\n"
	.string "something funny.\p"
	.string "Do you know of a funny word or phrase\n"
	.string "you can tell me?$"

RustboroCity_Flat1_2F_Text_BeenSayingXDoYouKnowBetterPhrase::
# 13 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "I've been saying {STR_VAR_1} to\n"
	.string "amuse her lately.\p"
	.string "Do you know of a better word or a\n"
	.string "phrase that might work?$"

RustboroCity_Flat1_2F_Text_WonderfulLetsHearSuggestion::
# 17 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, that's wonderful. So, let's hear it,\n"
	.string "your suggestion.$"

RustboroCity_Flat1_2F_Text_OhIsThatRight::
# 21 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, is that right?\p"
	.string "Well, if you come up with a good\n"
	.string "suggestion, I'm all ears.$"

RustboroCity_Flat1_2F_Text_LetsGiveItATry2::
# 25 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Ah, I see. Well, let's give it a try, shall\n"
	.string "we?$"

RustboroCity_Flat1_2F_Text_OhShesLaughing::
# 29 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "{STR_VAR_1}. {STR_VAR_1}.\p"
	.string "Oh, yes! She's laughing! Oh, I am as\n"
	.string "delighted as she!$"

RustboroCity_Flat1_2F_Text_LetsGiveItATry::
# 33 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Ah, I see. Well, let's give it a try, shall\n"
	.string "we?$"

RustboroCity_Flat1_2F_Text_ShesNotSmilingAtAll::
# 37 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "{STR_VAR_1}. {STR_VAR_1}.\p"
	.string "Hmmm She's not smiling at all. Maybe\n"
	.string "WALDA is one serious child$"

RustboroCity_Flat1_2F_Text_ThinkOfMyOwnPhrase::
# 41 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, so you don't know any good words.\n"
	.string "I'd better think for myself, then.\p"
	.string "Hmm How about {STR_VAR_1}?\l"
	.string "Let's see if that will work.$"

RustboroCity_Flat1_2F_Text_ShesNotSmilingAtAll2::
# 45 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "{STR_VAR_1}. {STR_VAR_1}.\p"
	.string "Hmmm She's not smiling at all. Maybe\n"
	.string "WALDA is one serious child$"

RustboroCity_Flat1_2F_Text_OhYouDontKnowAny::
# 49 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Oh, so you don't know any good words. I\n"
	.string "guess I'll try to amuse her with\l"
	.string "the saying I used before.\p"
	.string "Anyways, if you have a good suggestion,\n"
	.string "don't hesitate in telling me, okay?$"

RustboroCity_Flat1_2F_Text_ThankYouIllGiveYouWallpaper::
# 53 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "Thank you!\p"
	.string "Thanks to you, my darling WALDA laughed\n"
	.string "for me!\p"
	.string "Actually, I may not look all that\n"
	.string "special, but I'm one of DEVON\l"
	.string "CORPORATION's top researchers.\p"
	.string "So, how about I do something in return\n"
	.string "for you?\p"
	.string "I know, I'll add some new wallpaper\n"
	.string "patterns for the BOXES in the PC\l"
	.string "POKMON Storage System.\p"
	.string "In the wallpaper pattern menu, select\n"
	.string "FRIENDS.\p"
	.string "That will give you access to the new\n"
	.string "wallpaper patterns.$"

RustboroCity_Flat1_2F_Text_ItsAPokemonPlushDoll::
# 57 "data/maps/RustboroCity_Flat1_2F/scripts.pory"
	.string "It's a POKMON plush DOLL!$"
