MahoganyTown_House_MapScripts::
	.byte 0


MahoganyTown_House_EventScript_SmithNPC1::
# 5 "data/maps/MahoganyTown_House/scripts.pory"
	msgbox MahoganyTown_House_Text_SmithNPC1, MSGBOX_NPC
	end


MahoganyTown_House_EventScript_SmithNPC2::
# 14 "data/maps/MahoganyTown_House/scripts.pory"
	msgbox MahoganyTown_House_Text_SmithNPC2, MSGBOX_NPC
	end


MahoganyTown_House_Text_SmithNPC1::
# 9 "data/maps/MahoganyTown_House/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MahoganyTown_House_Text_SmithNPC2::
# 18 "data/maps/MahoganyTown_House/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
