Route112_CableCarStation_MapScripts::
	.byte 0


Route112_CableCarStation_EventScript_Attendant::
# 5 "data/maps/Route112_CableCarStation/scripts.pory"
	msgbox Route112_CableCarStation_Text_CableCarReadyGetOn, MSGBOX_YESNO
	end


Route112_CableCarStation_Text_StepThisWay::
# 9 "data/maps/Route112_CableCarStation/scripts.pory"
	.string "Please step this way.$"

Route112_CableCarStation_Text_RideAnotherTime::
# 13 "data/maps/Route112_CableCarStation/scripts.pory"
	.string "Please ride with us another time.$"

Route112_CableCarStation_Text_CableCarReadyGetOn::
# 17 "data/maps/Route112_CableCarStation/scripts.pory"
	.string "The CABLE CAR is ready to go up.\n"
	.string "Would you like to be on it?$"
