SevenIsland_MapScripts::
# 2 "data/maps/SevenIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_OnTransition
	.byte 0


Text_SwordsDanceTeach::
# 6 "data/maps/SevenIsland/scripts.pory"
	.string "Not many people come out here.\p"
	.string "If I train here, I'm convinced that I'll\n"
	.string "get stronger and stronger.\p"
	.string "Yep, stronger and stronger\p"
	.string "How would you like to learn a move like\n"
	.string "that? It's SWORDS DANCE.$"

Text_SwordsDanceDeclined::
# 10 "data/maps/SevenIsland/scripts.pory"
	.string "Well, that's fine, too.$"

Text_SwordsDanceWhichMon::
# 14 "data/maps/SevenIsland/scripts.pory"
	.string "All right, pick which POKMON I should\n"
	.string "teach it to.$"

Text_SwordsDanceTaught::
# 18 "data/maps/SevenIsland/scripts.pory"
	.string "If only we could keep getting stronger\n"
	.string "and stronger, eh?$"

SevenIsland_Text_IslandSign::
# 22 "data/maps/SevenIsland/scripts.pory"
	.string "SEVEN ISLAND Quest Island of Infinity$"

SevenIsland_Text_IslandsMadeInSevenDays::
# 26 "data/maps/SevenIsland/scripts.pory"
	.string "These islands are called the SEVII\n"
	.string "ISLANDS because there are seven.\p"
	.string "Or at least that's what the young\n"
	.string "people believe.\p"
	.string "The truth is, these islands are so named\n"
	.string "because they are said to\l"
	.string "have been made in seven days.$"

SevenIsland_Text_IslandVirtuallyUntouched::
# 30 "data/maps/SevenIsland/scripts.pory"
	.string "This island has been left virtually\n"
	.string "untouched in its natural state.\p"
	.string "It could be a little difficult to hike\n"
	.string "around because of that.$"
