Route110_TrickHousePuzzle3_MapScripts::
	.byte 0


Route110_TrickHousePuzzle3_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	msgbox Route110_TrickHousePuzzle3_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle3_EventScript_SmithNPC2::
# 51 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	msgbox Route110_TrickHousePuzzle3_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHousePuzzle3_Text_AlanDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_AlanDefeat$"

Route110_TrickHousePuzzle3_Text_AlanIntro::
# 9 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_AlanIntro$"

Route110_TrickHousePuzzle3_Text_AlanPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_AlanPostBattle$"

Route110_TrickHousePuzzle3_Text_JustinDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_JustinDefeat$"

Route110_TrickHousePuzzle3_Text_JustinIntro::
# 21 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_JustinIntro$"

Route110_TrickHousePuzzle3_Text_JustinPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_JustinPostBattle$"

Route110_TrickHousePuzzle3_Text_MarthaDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_MarthaDefeat$"

Route110_TrickHousePuzzle3_Text_MarthaIntro::
# 33 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_MarthaIntro$"

Route110_TrickHousePuzzle3_Text_MarthaPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle3_Text_MarthaPostBattle$"

Route110_TrickHousePuzzle3_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHousePuzzle3_Text_SmithNPC2::
# 55 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
