Route110_TrickHousePuzzle3_MapScripts::
# 2 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route110_TrickHousePuzzle3_OnResume
# 3 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHousePuzzle3_OnTransition
	.byte 0


Route110_TrickHousePuzzle3_MapScripts::
# 7 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route110_TrickHousePuzzle3_OnResume
# 8 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHousePuzzle3_OnTransition
	return


Route110_TrickHousePuzzle3_Text_WroteSecretCodeLockOpened::
# 12 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is coveted.” … … … … … … …\n"
	.string "…\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle3_Text_JustinIntro::
# 16 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I keep coming back to this same place!$"

Route110_TrickHousePuzzle3_Text_JustinDefeat::
# 20 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I'm already having trouble, and then you\n"
	.string "have to beat me? It's not fair!$"

Route110_TrickHousePuzzle3_Text_JustinPostBattle::
# 24 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "It's full of doors here! It's too small\n"
	.string "and dark in here! Help!$"

Route110_TrickHousePuzzle3_Text_MarthaIntro::
# 28 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I don't know what's going on here. I'm\n"
	.string "starting to feel sad…$"

Route110_TrickHousePuzzle3_Text_MarthaDefeat::
# 32 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "You… You're awful!$"

Route110_TrickHousePuzzle3_Text_MarthaPostBattle::
# 36 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I know I'm weak! And, I have no sense of\n"
	.string "direction!$"

Route110_TrickHousePuzzle3_Text_AlanIntro::
# 40 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I don't get it. What would anyone want\n"
	.string "with a house this bizarre?$"

Route110_TrickHousePuzzle3_Text_AlanDefeat::
# 44 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I don't get it. How did I lose?$"

Route110_TrickHousePuzzle3_Text_AlanPostBattle::
# 48 "data/maps/Route110_TrickHousePuzzle3/scripts.pory"
	.string "I don't get it. How many traps are in\n"
	.string "this house?\p"
	.string "You may be the one to solve that.$"
