Route110_TrickHousePuzzle7_MapScripts::
	.byte 0


Route110_TrickHousePuzzle7_EventScript_SmithNPC1::
# 78 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	msgbox Route110_TrickHousePuzzle7_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle7_EventScript_SmithNPC2::
# 87 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	msgbox Route110_TrickHousePuzzle7_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHousePuzzle7_Text_AlexisDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlexisDefeat$"

Route110_TrickHousePuzzle7_Text_AlexisIntro::
# 9 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlexisIntro$"

Route110_TrickHousePuzzle7_Text_AlexisPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlexisPostBattle$"

Route110_TrickHousePuzzle7_Text_AlvaroDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlvaroDefeat$"

Route110_TrickHousePuzzle7_Text_AlvaroIntro::
# 21 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlvaroIntro$"

Route110_TrickHousePuzzle7_Text_AlvaroPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_AlvaroPostBattle$"

Route110_TrickHousePuzzle7_Text_EverettDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_EverettDefeat$"

Route110_TrickHousePuzzle7_Text_EverettIntro::
# 33 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_EverettIntro$"

Route110_TrickHousePuzzle7_Text_EverettPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_EverettPostBattle$"

Route110_TrickHousePuzzle7_Text_JoshuaDefeat::
# 41 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_JoshuaDefeat$"

Route110_TrickHousePuzzle7_Text_JoshuaIntro::
# 45 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_JoshuaIntro$"

Route110_TrickHousePuzzle7_Text_JoshuaPostBattle::
# 49 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_JoshuaPostBattle$"

Route110_TrickHousePuzzle7_Text_MarielaDefeat::
# 53 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_MarielaDefeat$"

Route110_TrickHousePuzzle7_Text_MarielaIntro::
# 57 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_MarielaIntro$"

Route110_TrickHousePuzzle7_Text_MarielaPostBattle::
# 61 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_MarielaPostBattle$"

Route110_TrickHousePuzzle7_Text_PatriciaDefeat::
# 65 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_PatriciaDefeat$"

Route110_TrickHousePuzzle7_Text_PatriciaIntro::
# 69 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_PatriciaIntro$"

Route110_TrickHousePuzzle7_Text_PatriciaPostBattle::
# 73 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle7_Text_PatriciaPostBattle$"

Route110_TrickHousePuzzle7_Text_SmithNPC1::
# 82 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHousePuzzle7_Text_SmithNPC2::
# 91 "data/maps/Route110_TrickHousePuzzle7/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
