SeafloorCavern_Room9_MapScripts::
	.byte 0


SeafloorCavern_Room9_Text_ArchieHoldItRightThere::
# 5 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Hold it right there.$"

SeafloorCavern_Room9_Text_ArchieSoItWasYou::
# 9 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Fufufu So it was you, after all.$"

SeafloorCavern_Room9_Text_ArchieBeholdKyogre::
# 13 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Behold!\p"
	.string "See how beautiful it is, the sleeping\n"
	.string "form of the ancient POKMON KYOGRE!\p"
	.string "I have waited so long for this day to\n"
	.string "come$"

SeafloorCavern_Room9_Text_ArchieYouMustDisappear::
# 17 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: It surprises me, how you've\n"
	.string "managed to chase me here.\p"
	.string "But that's all over now.\p"
	.string "For the realization of my dream, you\n"
	.string "must disappear now!$"

SeafloorCavern_Room9_Text_ArchieDefeat::
# 21 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "What?! I lost to a mere child like you?!$"

SeafloorCavern_Room9_Text_ArchieWithThisRedOrb::
# 25 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Fufufu\p"
	.string "I commend you. I must recognize that\n"
	.string "you are truly gifted.\p"
	.string "But! I have this in my possession!\p"
	.string "With this RED ORB, I can make KYOGRE$"

SeafloorCavern_Room9_Text_RedOrbShinesByItself::
# 29 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "The RED ORB suddenly began shining by\n"
	.string "itself!$"

SeafloorCavern_Room9_Text_ArchieWhereDidKyogreGo::
# 33 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: What?!\p"
	.string "I didn't do anything. Why did the RED\n"
	.string "ORB\p"
	.string "Where did KYOGRE go?$"

SeafloorCavern_Room9_Text_ArchieAMessageFromOutside::
# 37 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Hm? It's a message from our\n"
	.string "members outside$"

SeafloorCavern_Room9_Text_ArchieWhatRainingTooHard::
# 41 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: Yes, what is it?\p"
	.string "Hm It's raining heavily?\p"
	.string "Good That should have happened. That\n"
	.string "is why we awakened KYOGRE,\l"
	.string "to realize TEAM AQUA's vision of\l"
	.string "expanding the sea.\p"
	.string "What?!\p"
	.string "It's raining far harder than we\n"
	.string "envisioned? You're in danger?\p"
	.string "That can't be That's just not possible\p"
	.string "Hold your position and monitor the\n"
	.string "situation!$"

SeafloorCavern_Room9_Text_ArchieWhyDidKyogreDisappear::
# 45 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: There's something wrong\p"
	.string "The RED ORB is supposed to awaken and\n"
	.string "control KYOGRE\p"
	.string "But Why? Why did KYOGRE disappear?\p"
	.string "Why?!$"

SeafloorCavern_Room9_Text_MaxieWhatHaveYouWrought::
# 49 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "MAXIE: What have you wrought?\p"
	.string "ARCHIE You've finally awoken KYOGRE,\n"
	.string "haven't you?\p"
	.string "What will happen to the world if this\n"
	.string "downpour continues for all eternity?\p"
	.string "The world's landmass will drown in the\n"
	.string "deepening sea$"

SeafloorCavern_Room9_Text_ArchieDontGetAllHighAndMighty::
# 53 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "ARCHIE: W-what?! Don't get all high and\n"
	.string "mighty with me!\p"
	.string "Wasn't it you, TEAM MAGMA, that\n"
	.string "infuriated GROUDON?\p"
	.string "So long as I have this RED ORB, I should\n"
	.string "be able to control KYOGRE\p"
	.string "I should be able to control it$"

SeafloorCavern_Room9_Text_MaxieWeDontHaveTimeToArgue::
# 57 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "MAXIE: We don't have the time to argue\n"
	.string "about it here!\p"
	.string "Get outside and see for yourself!\p"
	.string "See if what you've wrought is the world\n"
	.string "that we desired!$"

SeafloorCavern_Room9_Text_MaxieComeOnPlayer::
# 61 "data/maps/SeafloorCavern_Room9/scripts.pory"
	.string "MAXIE: {PLAYER}, come on, you have to\n"
	.string "get out of here, too!$"
