MtEmber_SummitPath_3F_MapScripts::
	.byte 0


MtEmber_SummitPath_3F_EventScript_SmithNPC1::
# 5 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	msgbox MtEmber_SummitPath_3F_Text_SmithNPC1, MSGBOX_NPC
	end


MtEmber_SummitPath_3F_EventScript_SmithNPC2::
# 14 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	msgbox MtEmber_SummitPath_3F_Text_SmithNPC2, MSGBOX_NPC
	end


MtEmber_SummitPath_3F_EventScript_SmithNPC3::
# 23 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	msgbox MtEmber_SummitPath_3F_Text_SmithNPC3, MSGBOX_NPC
	end


MtEmber_SummitPath_3F_Text_SmithNPC1::
# 9 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MtEmber_SummitPath_3F_Text_SmithNPC2::
# 18 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

MtEmber_SummitPath_3F_Text_SmithNPC3::
# 27 "data/maps/MtEmber_SummitPath_3F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
