LilycoveCity_CoveLilyMotel_2F_MapScripts::
	.byte 0


LilycoveCity_CoveLilyMotel_2F_MapScripts::
	return


LilycoveCity_CoveLilyMotel_2F_Text_ShowMeCompletedDex::
# 8 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "I'm the GAME DESIGNER.\p"
	.string "Oh, is that right? You're working on a\n"
	.string "POKéDEX?\p"
	.string "It's tough trying to complete it, but\n"
	.string "don't give up.\p"
	.string "If you do complete it, please come show\n"
	.string "me.$"

LilycoveCity_CoveLilyMotel_2F_Text_FilledPokedexGiveYouThis::
# 12 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "Wow! That's awesome! Yep, it's totally\n"
	.string "awesome!\p"
	.string "This POKéDEX is completely filled! You\n"
	.string "really must love POKéMON!\p"
	.string "I'm so impressed!\p"
	.string "Let me give you something in\n"
	.string "recognition of your feat!$"

LilycoveCity_CoveLilyMotel_2F_Text_ImTheProgrammer::
# 16 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "Me? You're talking to me? I'm the\n"
	.string "PROGRAMMER.\p"
	.string "I wonder what the SLOTS are like here.$"

LilycoveCity_CoveLilyMotel_2F_Text_ImTheGraphicArtist::
# 20 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "I'm the GRAPHIC ARTIST! Aren't the\n"
	.string "POKéMON of HOENN interesting?$"

LilycoveCity_CoveLilyMotel_2F_Text_GirlsAreCute::
# 24 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "The girl TUBERS, they're cute, hey? To\n"
	.string "battle against a cute TUBER…\p"
	.string "Whoop, it's so awesome!\p"
	.string "And the TWINS! Aren't they cute? A\n"
	.string "2-on-2 battle with TWINS…\p"
	.string "Whoop, it's unbearably fun!$"

LilycoveCity_CoveLilyMotel_2F_Text_SeaBreezeTicklesHeart::
# 28 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "The sea breeze tickles my heart. It\n"
	.string "feels wonderful here!$"

LilycoveCity_CoveLilyMotel_2F_Text_NeverLeaveWithoutGameBoy::
# 32 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "You never know when and where people\n"
	.string "will challenge you.\p"
	.string "That's why I never leave home without\n"
	.string "my GAME BOY ADVANCE.$"

LilycoveCity_CoveLilyMotel_2F_Text_SnoozingPreferBattles::
# 36 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "SCOTT: … … … … … … … … … … Zzz…\p"
	.string "… … … … … Huh?! Oh, sorry, sorry! I was\n"
	.string "snoozing!\p"
	.string "I came to check out this POKéMON\n"
	.string "CONTEST thing.\p"
	.string "I have to admit, it does look quite\n"
	.string "entertaining, but…\p"
	.string "Consider me a purist--I prefer battles\n"
	.string "and tough TRAINERS.\p"
	.string "But that's just me.\p"
	.string "{PLAYER}{KUN}, I hope you'll enjoy\n"
	.string "everything like the GYMS, CONTESTS,\l"
	.string "BATTLE TENT,\l"
	.string "the whole works!$"

LilycoveCity_CoveLilyMotel_2F_Text_ContestsDoTakeStrategy::
# 40 "data/maps/LilycoveCity_CoveLilyMotel_2F/scripts.pory"
	.string "SCOTT: I think it does take strategy to\n"
	.string "win a CONTEST.\p"
	.string "Devising CONTEST strategies is one way\n"
	.string "of becoming a better TRAINER, I'd say.$"
