Route110_TrickHouseEntrance_MapScripts::
# 2 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHouseEntrance_OnTransition
# 3 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route110_TrickHouseEntrance_OnFrame
# 4 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route110_TrickHouseEntrance_OnWarp
	.byte 0


Route110_TrickHouseEntrance_Text_YoureBeingWatched::
# 8 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "You're being watched…$"

Route110_TrickHouseEntrance_Text_ConcealedBeneathDesk::
# 12 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beneath this desk? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBehindTree::
# 16 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "behind this tree? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInDresser::
# 20 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself in\n"
	.string "this dresser? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConealedBeyondWindow::
# 24 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beyond this window? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInPlanter::
# 28 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself in\n"
	.string "this planter? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedInCupboard::
# 32 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself in\n"
	.string "this cupboard? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBehindWindow::
# 36 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "behind this window? You're sharp!$"

Route110_TrickHouseEntrance_Text_ConcealedBeneathCushion::
# 40 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Grrr…\p"
	.string "How did you know I concealed myself\n"
	.string "beneath this cushion? You're sharp!$"

Route110_TrickHouseEntrance_Text_TheyCallMeTrickMaster::
# 44 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Behold!\p"
	.string "For I am the greatest living mystery of\n"
	.string "a man in all of HOENN!\l"
	.string "They call me…\p"
	.string "The TRICK MASTER! Wahahaha! Glad to\n"
	.string "meet you!$"

Route110_TrickHouseEntrance_Text_ComeToChallengeTrickHouse::
# 48 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "You, you've come to challenge my TRICK\n"
	.string "HOUSE, haven't you?\p"
	.string "That's why you're here, isn't it? Yes, it\n"
	.string "is!\p"
	.string "Consider your challenge accepted!\p"
	.string "Enter through the scroll there, and let\n"
	.string "your challenge commence!\p"
	.string "I shall be waiting in the back!$"

Route110_TrickHouseEntrance_Text_ItsAScroll::
# 52 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "It's a scroll.$"

Route110_TrickHouseEntrance_Text_GoInHoleBehindScroll::
# 56 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "There is a big hole behind the scroll!\p"
	.string "Want to go in?$"

Route110_TrickHouseEntrance_Text_LeavingOnJourneyNote::
# 60 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "There is a note affixed to the scroll…\p"
	.string "“I am leaving on a journey. Don't look\n"
	.string "for me. TRICK MASTER”$"

Route110_TrickHouseEntrance_Text_NextTimeUseThisTrick::
# 64 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "For the next time, I'll use this trick,\n"
	.string "and that scheme, and those ruses…\p"
	.string "Mufufufu… If I may say so, it's\n"
	.string "brilliantly difficult, even for me!$"

Route110_TrickHouseEntrance_Text_InMidstOfDevisingNewChallenges::
# 68 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? What?! Oh, it's you!\p"
	.string "I'm in the midst of devising new tricky\n"
	.string "challenges!\p"
	.string "It's not too much to ask for a bit more\n"
	.string "time for me to think, is it now?\l"
	.string "You wouldn't begrudge me that?\l"
	.string "Come back in a little while!$"

Route110_TrickHouseEntrance_Text_YoureHereToAcceptReward::
# 72 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Ah, it's you! You're here to accept the\n"
	.string "reward from before, isn't that right?\l"
	.string "Yes, right I am!\p"
	.string "Here! I'll give it to you now!$"

Route110_TrickHouseEntrance_Text_DidYouNotComeToClaimReward::
# 76 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "Hah? Did you not come to claim your\n"
	.string "reward?$"

Route110_TrickHouseEntrance_Text_MechadollWhichTent::
# 80 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "MECHADOLL 5 I AM! IF REWARD IS NOT\n"
	.string "TAKEN BY YOU,\l"
	.string "THEN TRICK MASTER YOU CANNOT FOLLOW.\p"
	.string "RED TENT OR BLUE TENT, WHICH DO YOU\n"
	.string "PREFER?$"

Route110_TrickHouseEntrance_Text_ThenFarewell::
# 84 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "THEN FAREWELL.$"

Route110_TrickHouseEntrance_Text_PCFullAgain::
# 88 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "YOUR PC STATUS: FULL AGAIN. MEAN, YOU\n"
	.string "ARE.$"

Route110_TrickHousePuzzle_Text_FoundAScroll::
# 92 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "{PLAYER} found a scroll.$"

Route110_TrickHousePuzzle_Text_MemorizedSecretCode::
# 96 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "{PLAYER} memorized the secret code\n"
	.string "written on the scroll.$"

Route110_TrickHousePuzzle_Text_SecretCodeWrittenOnIt::
# 100 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "A secret code is written on it.$"

Route110_TrickHouseEntrance_Text_DoorLockedWriteSecretCodeHere::
# 104 "data/maps/Route110_TrickHouseEntrance/scripts.pory"
	.string "The door is locked.\p"
	.string "…On closer inspection, this is written\n"
	.string "on it: “Write the secret code here.”$"
