NewBarkTown_MapScripts::
	.byte 0


NewBarkTown_EventScript_Sign1::
# 6 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_Sign1, MSGBOX_SIGN
	end


NewBarkTown_EventScript_Sign2::
# 15 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_Sign2, MSGBOX_SIGN
	end


NewBarkTown_EventScript_SmithNPC1::
# 24 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_SmithNPC1, MSGBOX_NPC
	end


NewBarkTown_EventScript_SmithNPC2::
# 33 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_SmithNPC2, MSGBOX_NPC
	end


NewBarkTown_EventScript_SmithNPC3::
# 42 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_SmithNPC3, MSGBOX_NPC
	end


NewBarkTown_EventScript_SmithNPC4::
# 51 "data/maps/NewBarkTown/scripts.pory"
	msgbox NewBarkTown_Text_SmithNPC4, MSGBOX_NPC
	end


NewBarkTown_Text_Sign1::
# 10 "data/maps/NewBarkTown/scripts.pory"
	.string "NewBarkTown Sign 1$"

NewBarkTown_Text_Sign2::
# 19 "data/maps/NewBarkTown/scripts.pory"
	.string "NewBarkTown Sign 2$"

NewBarkTown_Text_SmithNPC1::
# 28 "data/maps/NewBarkTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

NewBarkTown_Text_SmithNPC2::
# 37 "data/maps/NewBarkTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

NewBarkTown_Text_SmithNPC3::
# 46 "data/maps/NewBarkTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

NewBarkTown_Text_SmithNPC4::
# 55 "data/maps/NewBarkTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
