SSAnne_2F_Room5_MapScripts::
	.byte 0


SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
# 5 "data/maps/SSAnne_2F_Room5/scripts.pory"
	.string "Have you gone to the SAFARI ZONE in\n"
	.string "FUCHSIA CITY?\p"
	.string "There are many kinds of rare POKMON.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
# 9 "data/maps/SSAnne_2F_Room5/scripts.pory"
	.string "Me and my daddy think the SAFARI ZONE\n"
	.string "is awesome!\l"
	.string "I wish we could go there again.$"
