SSAnne_2F_Room5_MapScripts::
	.byte 0


SSAnne_2F_Room5_EventScript_Gentleman::
# 5 "data/maps/SSAnne_2F_Room5/scripts.pory"
	msgbox SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone, MSGBOX_NPC
	end


SSAnne_2F_Room5_EventScript_LittleBoy::
# 10 "data/maps/SSAnne_2F_Room5/scripts.pory"
	msgbox SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome, MSGBOX_NPC
	end


SSAnne_2F_Room5_Text_HaveYouGoneToSafariZone::
# 15 "data/maps/SSAnne_2F_Room5/scripts.pory"
	.string "Have you gone to the SAFARI ZONE\n"
	.string "in FUCHSIA CITY?\p"
	.string "There are many kinds of rare\n"
	.string "POKéMON.$"

SSAnne_2F_Room5_Text_WeThinkSafariZoneIsAwesome::
# 19 "data/maps/SSAnne_2F_Room5/scripts.pory"
	.string "Me and my daddy think the SAFARI\n"
	.string "ZONE is awesome!\l"
	.string "I wish we could go there again.$"
