OneIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OneIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
# 4 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, OneIsland_PokemonCenter_1F_OnLoad
# 5 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_PokemonCenter_1F_OnFrame
	.byte 0


OneIsland_PokemonCenter_1F_Text_BillHeyThereCelio::
# 9 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Hey, there! CELIO!$"

OneIsland_PokemonCenter_1F_Text_CelioCantBelieveYouCameOut::
# 13 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: BILL! I can't believe you came\n"
	.string "out here.$"

OneIsland_PokemonCenter_1F_Text_BillHowsYourResearchComing::
# 17 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Well, absolutely! How's your\n"
	.string "research coming along?\p"
	.string "…Oh, wait a sec.$"

OneIsland_PokemonCenter_1F_Text_ThisIsMyBuddyCelio::
# 21 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER}, this is my buddy CELIO. He's\n"
	.string "one dedicated PC MANIAC!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsRisingPokemonChamp::
# 25 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO, this is {PLAYER}, a rising\n"
	.string "contender as the POKéMON CHAMP!$"

OneIsland_PokemonCenter_1F_Text_PlayerIsReigningPokemonChamp::
# 29 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO, this is {PLAYER}, the reigning\n"
	.string "POKéMON CHAMP!$"

OneIsland_PokemonCenter_1F_Text_CelioThatsReallyImpressive::
# 33 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: That's really impressive.\p"
	.string "I hate to say it, but I have zero\n"
	.string "aptitude for battling.\p"
	.string "Anyways, I'm glad to meet you.$"

OneIsland_PokemonCenter_1F_Text_BillBringMeUpToSpeed::
# 37 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: So, bring me up to speed. How's\n"
	.string "your machine running?$"

OneIsland_PokemonCenter_1F_Text_CelioPCsCantLinkWithYours::
# 41 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: It's running fine, but we're too\n"
	.string "remote out here.\p"
	.string "The PCs on this island just can't link\n"
	.string "with your PC, BILL.$"

OneIsland_PokemonCenter_1F_Text_BillLetMeHelpYou::
# 45 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Oh, yeah? Okay, let me take a\n"
	.string "look-see.\p"
	.string "…Hang on here… I think we can make it\n"
	.string "work.\l"
	.string "Let me help you, okay?$"

OneIsland_PokemonCenter_1F_Text_CanYouDeliverThisMeteoritePlayer::
# 49 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER}, can I get you to wait for me\n"
	.string "just a bit?\p"
	.string "…Actually, can I get you to do me a\n"
	.string "favor?\p"
	.string "The island next to this one's called TWO\n"
	.string "ISLAND.\p"
	.string "There's a guy there that runs a GAME\n"
	.string "CORNER.\p"
	.string "He has this thing for rare rocks and\n"
	.string "gems.\p"
	.string "We keep in touch, being fellow maniacs.\p"
	.string "So, can I get you to deliver this\n"
	.string "METEORITE to him?$"

OneIsland_PokemonCenter_1F_Text_AcceptedMeteoriteFromBill::
# 53 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} accepted the METEORITE\n"
	.string "from BILL.$"

OneIsland_PokemonCenter_1F_Text_CelioPleaseTakeThis::
# 57 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: {PLAYER}, if you are going to\n"
	.string "TWO ISLAND, please take this.$"

OneIsland_PokemonCenter_1F_Text_PassLetsYouTravelBetweenIslands::
# 61 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "It's a PASS for the ferry service\n"
	.string "serving the local islands.\p"
	.string "It will let you travel between the\n"
	.string "ISLANDS ONE, TWO, and THREE.\p"
	.string "Oh, you should have this, too.$"

OneIsland_PokemonCenter_1F_Text_ReceivedExtraPageForTownMap::
# 65 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} received an extra page for\n"
	.string "the TOWN MAP!$"

OneIsland_PokemonCenter_1F_Text_ReceivedTownMap::
# 69 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} received a TOWN MAP!$"

OneIsland_PokemonCenter_1F_Text_BillCatchYouLater::
# 73 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: I'll catch you later! Say hi to the\n"
	.string "guy for me!$"

OneIsland_PokemonCenter_1F_Text_HmmHowAboutLikeThis::
# 77 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Hmm…\p"
	.string "How about we try this like this…$"

OneIsland_PokemonCenter_1F_Text_GotPCWorkingStrollAWhileMore::
# 81 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Oh, hey, {PLAYER}!\p"
	.string "Did you see? We got the PC working!\p"
	.string "I've got a few things to show CELIO\n"
	.string "here.\p"
	.string "Can you go out on a stroll or something\n"
	.string "for a while more?$"

OneIsland_PokemonCenter_1F_Text_SorryForBeingPoorHost::
# 85 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I'm sorry for taking up so much of\n"
	.string "BILL's time.\p"
	.string "I'm also sorry for being such a poor\n"
	.string "host on your visit here.$"

OneIsland_PokemonCenter_1F_Text_UsualPCServicesUnavailable::
# 89 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "The usual PC services aren't available…$"

OneIsland_PokemonCenter_1F_Text_BillOhHeyPlayer::
# 93 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Oh, hey! {PLAYER}!$"

OneIsland_PokemonCenter_1F_Text_BillWeGotItDone::
# 97 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: What kept you so long? Been out\n"
	.string "having a good time?\p"
	.string "We got it done. The PCs are up and\n"
	.string "running!$"

OneIsland_PokemonCenter_1F_Text_CelioJobWentQuick::
# 101 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: The job went incredibly quick.\p"
	.string "BILL is one amazing guy…$"

OneIsland_PokemonCenter_1F_Text_BillYouveLearnedALot::
# 105 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: No, no! There was almost nothing\n"
	.string "left for me to do.\p"
	.string "CELIO, I have to hand it to you. You've\n"
	.string "learned a lot.$"

OneIsland_PokemonCenter_1F_Text_CelioOhReallyEhehe::
# 109 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: Oh, really? Ehehe…$"

OneIsland_PokemonCenter_1F_Text_BillWeShouldHeadBackToKanto::
# 113 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Well, there you have it. I'm\n"
	.string "finished with the job.\l"
	.string "We should head back to KANTO.\p"
	.string "CELIO, I'll be seeing you again.$"

OneIsland_PokemonCenter_1F_Text_CelioPromiseIllShowYouAroundSometime::
# 117 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: {PLAYER}, I'm really sorry that\n"
	.string "we sent you off alone today.\p"
	.string "I promise, I will show you around these\n"
	.string "islands sometime.$"

OneIsland_PokemonCenter_1F_Text_CelioImModifyingMyNetworkMachine::
# 121 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: Hello! You look awfully busy as\n"
	.string "always.\p"
	.string "How am I doing?\p"
	.string "Well, I'm modifying my Network Machine.\p"
	.string "When I get done with the machine, I\n"
	.string "hope you'll be first to use it,\l"
	.string "{PLAYER}.$"

OneIsland_PokemonCenter_1F_Text_CelioCaughtMoreMonMaybeICanBeUseful::
# 125 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: {PLAYER}, how have things\n"
	.string "been for you?\p"
	.string "Oh, is that right? You've caught more\n"
	.string "POKéMON.\p"
	.string "Do you know what? Maybe I can be useful\n"
	.string "to you.$"

OneIsland_PokemonCenter_1F_Text_YoullBeTradingFromTrainersFarAway::
# 129 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I'm modifying the Network Machine right\n"
	.string "now.\p"
	.string "I'm changing it so it can handle trades\n"
	.string "over long distances.\p"
	.string "When I get finished, you'll be trading\n"
	.string "for exotic POKéMON from\l"
	.string "TRAINERS far away.$"

OneIsland_PokemonCenter_1F_Text_NeedsSpecialGemstone::
# 133 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "But, there is a slight catch.\p"
	.string "For the link to work, the Machine needs\n"
	.string "a special gemstone.\p"
	.string "It's supposed to be on ONE ISLAND, but\n"
	.string "I haven't found one yet.\p"
	.string "Who knows where it could be.$"

OneIsland_PokemonCenter_1F_Text_TryingToFindGem::
# 137 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I was trying to find the gem even while\n"
	.string "I was studying.\p"
	.string "As a result, I've made no headway in\n"
	.string "both my search and studies…\p"
	.string "If I relied on BILL, I'm sure my research\n"
	.string "would progress.\p"
	.string "But this time, I want to try to do\n"
	.string "things by myself.$"

OneIsland_PokemonCenter_1F_Text_OhThats::
# 141 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Oh! Th-that's…$"

OneIsland_PokemonCenter_1F_Text_HandedRubyToCelio::
# 145 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} handed the RUBY to CELIO.$"

OneIsland_PokemonCenter_1F_Text_MayIAskOneMoreFavor::
# 149 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Thank you! {PLAYER}, you're simply\n"
	.string "amazing.\p"
	.string "… … … … … …\p"
	.string "Um… May I ask one more giant favor of\n"
	.string "you?$"

OneIsland_PokemonCenter_1F_Text_PleaseINeedYourHelp::
# 153 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "It… It's not anything weird. Please, I\n"
	.string "need your help.$"

OneIsland_PokemonCenter_1F_Text_AnotherGemstoneInSeviiIslands::
# 157 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "While I was studying gemstones, I\n"
	.string "discovered something important.\p"
	.string "There is another gem that forms a pair\n"
	.string "with this RUBY.\p"
	.string "That other gemstone is supposed to be\n"
	.string "in the SEVII ISLANDS.\p"
	.string "{PLAYER}, please, I need you to go\n"
	.string "find the other gem.\p"
	.string "{PLAYER}, may I have your ferry PASS\n"
	.string "and the TOWN MAP?$"

OneIsland_PokemonCenter_1F_Text_ReturnedTriPassForRainbowPass::
# 161 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} returned the TRI-PASS and\n"
	.string "received the RAINBOW PASS.$"

OneIsland_PokemonCenter_1F_Text_ObtainedExtraMapPage::
# 165 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Obtained an extra page for the TOWN\n"
	.string "MAP!$"

OneIsland_PokemonCenter_1F_Text_PassLetYouGetToAllIslands::
# 169 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "This is my own ferry PASS.\p"
	.string "It will let you get to all the SEVII\n"
	.string "ISLANDS.\p"
	.string "{PLAYER}, please, I can't do it\n"
	.string "without your help.$"

OneIsland_PokemonCenter_1F_Text_HandedSapphireToCelio::
# 173 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} handed the SAPPHIRE to\n"
	.string "CELIO.$"

OneIsland_PokemonCenter_1F_Text_ThankYouGiveMeTime::
# 177 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: So this is the gem that forms a\n"
	.string "pair with the RUBY…\p"
	.string "{PLAYER}, you've gone through a lot\n"
	.string "to get this, didn't you?\p"
	.string "You don't have to tell me. I know it\n"
	.string "wasn't easy.\p"
	.string "Thank you so much!\p"
	.string "Now it's my turn to work for you! Please\n"
	.string "give me a little time.$"

OneIsland_PokemonCenter_1F_Text_OkayThisIsGood::
# 181 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Okay, this is good…$"

OneIsland_PokemonCenter_1F_Text_LinkedUpWithLanette::
# 185 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I did it! I linked up with LANETTE!$"

OneIsland_PokemonCenter_1F_Text_ManagedToLinkWithHoennThankYou::
# 189 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER}… {PLAYER}, I did it!\p"
	.string "I've managed to link up with TRAINERS in\n"
	.string "the HOENN region!\p"
	.string "Finally, the Network Machine is fully\n"
	.string "operational!\p"
	.string "{PLAYER}, I owe it all to you!\p"
	.string "Thanks to you, my dream came true…$"

OneIsland_PokemonCenter_1F_Text_WishYouBestOfLuck::
# 193 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I… I'm not crying.\p"
	.string "That's enough about me!\p"
	.string "{PLAYER}, you're going to keep looking\n"
	.string "for exotic POKéMON, right?\p"
	.string "I wish you the best of luck!$"

OneIsland_PokemonCenter_1F_Text_CelioHearingRumorsAboutYou::
# 197 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "CELIO: Hello!\p"
	.string "{PLAYER}, I've been hearing rumors\n"
	.string "about you.$"

OneIsland_PokemonCenter_1F_Text_BillsFirstMonWasAbra::
# 201 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER}, what's your favorite kind\n"
	.string "of POKéMON?\p"
	.string "BILL is a POKéMANIAC, so he loves every\n"
	.string "kind.\p"
	.string "Apparently, the first one he caught was\n"
	.string "an ABRA.$"

OneIsland_PokemonCenter_1F_Text_BillsHometownInGoldenrod::
# 205 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "By the way, {PLAYER}, you're from\n"
	.string "PALLET TOWN, aren't you?\p"
	.string "I've heard that it's a quiet and\n"
	.string "pleasant place.\p"
	.string "BILL's hometown is GOLDENROD CITY,\n"
	.string "where his folks still live.\p"
	.string "I've heard that it's quite the festive,\n"
	.string "bustling city.\p"
	.string "I'd like to go there one day.$"

OneIsland_PokemonCenter_1F_Text_BillCantStomachMilk::
# 209 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER}, is there anything that you\n"
	.string "can't stand?\p"
	.string "Apparently, BILL simply can't stomach\n"
	.string "milk at all.$"

OneIsland_PokemonCenter_1F_Text_CameFromPalletDontKnowIt::
# 213 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Oh, you're a stranger here! Hi! Where did\n"
	.string "you come from?\p"
	.string "…PALLET TOWN? I don't know it!$"

OneIsland_PokemonCenter_1F_Text_EnormousVolcanoOnIsland::
# 217 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "On this island, there's an enormous\n"
	.string "volcano.\p"
	.string "It hasn't erupted lately, so why not\n"
	.string "enjoy a hike?$"

OneIsland_PokemonCenter_1F_Text_WishICouldTradeWithBoyfriend::
# 221 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I wish I could trade POKéMON with my\n"
	.string "boyfriend who lives far away…$"

OneIsland_PokemonCenter_1F_Text_TradedWithFarAwayBoyfriend::
# 225 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "I traded POKéMON with my boyfriend far\n"
	.string "away!\p"
	.string "Everyone's saying that we can thank\n"
	.string "you and CELIO.\p"
	.string "So, thank you!$"

OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
# 229 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Network Machine Link Level 0\p"
	.string "…POKéMON Storage System under\n"
	.string "adjustment…$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKanto::
# 233 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Network Machine Link Level 1\p"
	.string "Link established with the KANTO region.$"

OneIsland_PokemonCenter_1F_Text_MachineLinkedWithKantoAndHoenn::
# 237 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Network Machine Link Level 2\p"
	.string "Link established with the KANTO and\n"
	.string "HOENN regions.$"

OneIsland_PokemonCenter_1F_Text_ObtainedTriPass::
# 241 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Obtained the TRI-PASS!$"
