OneIsland_PokemonCenter_1F_MapScripts::
	.byte 0


OneIsland_PokemonCenter_1F_EventScript_LeaveOneIslandTriggerBottom::
	end


OneIsland_PokemonCenter_1F_EventScript_LeaveOneIslandTriggerMidBottom::
	end


OneIsland_PokemonCenter_1F_EventScript_LeaveOneIslandTriggerMidTop::
	end


OneIsland_PokemonCenter_1F_EventScript_LeaveOneIslandTriggerTop::
	end


OneIsland_PokemonCenter_1F_EventScript_NetworkMachine::
# 24 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	msgbox OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment, MSGBOX_DEFAULT
	end


OneIsland_PokemonCenter_1F_EventScript_Nurse::
	end


OneIsland_PokemonCenter_1F_Text_MachineUnderAdjustment::
# 34 "data/maps/OneIsland_PokemonCenter_1F/scripts.pory"
	.string "Network Machine Link Level 0\p"
	.string "…POKéMON Storage System under\n"
	.string "adjustment…$"
