SootopolisCity_House2_MapScripts::
	.byte 0


SootopolisCity_House2_Text_DidYouKnowAboutMtPyreOrbs::
# 5 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "MT. PYRE…\p"
	.string "At its peak are two orbs placed side by\n"
	.string "side. Did you know?$"

SootopolisCity_House2_Text_YesTwoOrbsSideBySide::
# 9 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "Yes, two orbs side by side…\p"
	.string "The sight of them together… It is\n"
	.string "somehow soothing…$"

SootopolisCity_House2_Text_OughtToVisitAndSee::
# 13 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "Is that so? Perhaps you ought to visit\n"
	.string "and see…$"
