SootopolisCity_House2_MapScripts::
	.byte 0


SootopolisCity_House2_EventScript_ExpertF::
# 5 "data/maps/SootopolisCity_House2/scripts.pory"
	msgbox SootopolisCity_House2_Text_DidYouKnowAboutMtPyreOrbs, MSGBOX_YESNO
	end


SootopolisCity_House2_Text_DidYouKnowAboutMtPyreOrbs::
# 9 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "MT. PYRE…\p"
	.string "At its peak are two orbs placed side\n"
	.string "by side. Did you know?$"

SootopolisCity_House2_Text_YesTwoOrbsSideBySide::
# 13 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "Yes, two orbs side by side…\p"
	.string "The sight of them together…\n"
	.string "It is somehow soothing…$"

SootopolisCity_House2_Text_OughtToVisitAndSee::
# 17 "data/maps/SootopolisCity_House2/scripts.pory"
	.string "Is that so?\n"
	.string "Perhaps you ought to visit and see…$"
