SilphCo_4F_MapScripts::
# 2 "data/maps/SilphCo_4F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_4F_OnLoad
	.byte 0


SilphCo_4F_Text_CantYouSeeImHiding::
# 6 "data/maps/SilphCo_4F/scripts.pory"
	.string "Sssh! Can't you see I'm hiding?$"

SilphCo_4F_Text_TeamRocketIsGone::
# 10 "data/maps/SilphCo_4F/scripts.pory"
	.string "Huh? TEAM ROCKET is gone?$"

SilphCo_4F_Text_Grunt1Intro::
# 14 "data/maps/SilphCo_4F/scripts.pory"
	.string "TEAM ROCKET has taken control of SILPH\n"
	.string "CO.!$"

SilphCo_4F_Text_Grunt1Defeat::
# 18 "data/maps/SilphCo_4F/scripts.pory"
	.string "Arrgh!$"

SilphCo_4F_Text_Grunt1PostBattle::
# 22 "data/maps/SilphCo_4F/scripts.pory"
	.string "Fwahahaha! My BOSS has been after this\n"
	.string "place!$"

SilphCo_4F_Text_RodneyIntro::
# 26 "data/maps/SilphCo_4F/scripts.pory"
	.string "My POKMON is my loyal servant.$"

SilphCo_4F_Text_RodneyDefeat::
# 30 "data/maps/SilphCo_4F/scripts.pory"
	.string "Darn! You weak POKMON!$"

SilphCo_4F_Text_RodneyPostBattle::
# 34 "data/maps/SilphCo_4F/scripts.pory"
	.string "The doors are electronically locked.\p"
	.string "It takes a CARD KEY to open the doors\n"
	.string "here.$"

SilphCo_4F_Text_Grunt2Intro::
# 38 "data/maps/SilphCo_4F/scripts.pory"
	.string "Intruder spotted!$"

SilphCo_4F_Text_Grunt2Defeat::
# 42 "data/maps/SilphCo_4F/scripts.pory"
	.string "Who are you?$"

SilphCo_4F_Text_Grunt2PostBattle::
# 46 "data/maps/SilphCo_4F/scripts.pory"
	.string "I better tell the BOSS on 11F!$"

SilphCo_4F_Text_FloorSign::
# 50 "data/maps/SilphCo_4F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 4F$"
