PokemonMansion_1F_MapScripts::
# 2 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_1F_OnLoad
# 3 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonMansion_1F_OnTransition
	.byte 0


PokemonMansion_1F_MapScripts::
# 7 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_1F_OnLoad
# 8 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonMansion_1F_OnTransition
	return

