PokemonMansion_1F_MapScripts::
# 2 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_1F_OnLoad
# 3 "data/maps/PokemonMansion_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonMansion_1F_OnTransition
	.byte 0


PokemonMansion_1F_Text_TedIntro::
# 7 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "Who are you? There shouldn't be anyone\n"
	.string "here.$"

PokemonMansion_1F_Text_TedDefeat::
# 11 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "Ouch!$"

PokemonMansion_1F_Text_TedPostBattle::
# 15 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "A key? I don't know what you're talking\n"
	.string "about.$"

PokemonMansion_1F_Text_JohnsonIntro::
# 19 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "W-w-waah! You startled me! I thought\n"
	.string "you were a ghost.$"

PokemonMansion_1F_Text_JohnsonDefeat::
# 23 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "Tch! I can't get any wins.$"

PokemonMansion_1F_Text_JohnsonPostBattle::
# 27 "data/maps/PokemonMansion_1F/scripts.pory"
	.string "I was exploring here by myself, but I\n"
	.string "feel spooked.\p"
	.string "I ought to go soon.$"
