SixIsland_GreenPath_MapScripts::
	.byte 0


SixIsland_GreenPath_Text_JaclynIntro::
# 5 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "…Huh?\p"
	.string "I was envisioning my house, but this is\n"
	.string "where I TELEPORT?$"

SixIsland_GreenPath_Text_JaclynDefeat::
# 9 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "Big boo-boo!$"

SixIsland_GreenPath_Text_JaclynPostBattle::
# 13 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "I am so scatterbrained!\p"
	.string "I need to focus so I can TELEPORT\n"
	.string "properly to my house!$"

SixIsland_GreenPath_Text_LeftRouteSign::
# 17 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "GREEN PATH PATTERN BUSH AHEAD$"

SixIsland_GreenPath_Text_RightRouteSign::
# 21 "data/maps/SixIsland_GreenPath/scripts.pory"
	.string "GREEN PATH Think Green, Keep Nature\n"
	.string "Clean!$"
