FuchsiaCity_WardensHouse_MapScripts::
	.byte 0


FuchsiaCity_WardensHouse_Text_HifFuffHefifoo::
# 5 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "WARDEN: Hif fuff hefifoo!\p"
	.string "Ha lof ha feef ee hafahi ho. Heff hee\n"
	.string "fwee!$"

FuchsiaCity_WardensHouse_Text_AhHowheeHoHoo::
# 9 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "Ah howhee ho hoo! Eef ee hafahi ho!$"

FuchsiaCity_WardensHouse_Text_HeOhayHeHaHoo::
# 13 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "Ha? He ohay heh ha hoo ee haheh!$"

FuchsiaCity_WardensHouse_Text_GaveGoldTeethToWarden::
# 17 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "{PLAYER} gave the GOLD TEETH to the\n"
	.string "WARDEN.$"

FuchsiaCity_WardensHouse_Text_WardenPoppedInHisTeeth::
# 21 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "The WARDEN popped in his teeth!$"

FuchsiaCity_WardensHouse_Text_ThanksSonGiveYouSomething::
# 25 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "WARDEN: Thanks, son! You're a real\n"
	.string "lifesaver!\p"
	.string "No one could understand a word that I\n"
	.string "said, not a one!\p"
	.string "I was too ashamed to show my face\n"
	.string "around the OFFICE, even.\p"
	.string "Let me give you something for your\n"
	.string "trouble.$"

FuchsiaCity_WardensHouse_Text_ThanksLassieGiveYouSomething::
# 29 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "WARDEN: Thank you, lassie! You're a real\n"
	.string "lifesaver!\p"
	.string "No one could understand a word that I\n"
	.string "said, not a one!\p"
	.string "I was too ashamed to show my face\n"
	.string "around the OFFICE, even.\p"
	.string "Let me give you something for your\n"
	.string "trouble.$"

FuchsiaCity_WardensHouse_Text_ReceivedHM04FromWarden::
# 33 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "{PLAYER} received HM04 from the\n"
	.string "WARDEN.$"

FuchsiaCity_WardensHouse_Text_ExplainStrength::
# 37 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "WARDEN: Inside HM04 you'll find\n"
	.string "STRENGTH.\p"
	.string "It lets POKéMON move boulders when\n"
	.string "you're outside of battle.\p"
	.string "Oh yes, did you find the SECRET HOUSE in\n"
	.string "the SAFARI ZONE?$"

FuchsiaCity_WardensHouse_Text_YouHaveTooMuchStuff::
# 41 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "なんや　にもつ いっぱいやんけ！$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
# 45 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "POKéMON photos and fossils are on\n"
	.string "display.$"

FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
# 49 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "Old POKéMON merchandise is on display.$"
