FuchsiaCity_WardensHouse_MapScripts::
	.byte 0


FuchsiaCity_WardensHouse_EventScript_DisplaySign1::
# 5 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	msgbox FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay, MSGBOX_SIGN
	end


FuchsiaCity_WardensHouse_EventScript_DisplaySign2::
# 10 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	msgbox FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay, MSGBOX_SIGN
	end


FuchsiaCity_WardensHouse_EventScript_ItemRareCandy::
	end


FuchsiaCity_WardensHouse_EventScript_PokemonJournalKoga::
	end


FuchsiaCity_WardensHouse_EventScript_Warden::
	end


FuchsiaCity_WardensHouse_Text_OldMonMerchandiseOnDisplay::
# 27 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "Old POKéMON merchandise is on display.$"

FuchsiaCity_WardensHouse_Text_MonPhotosFossilsOnDisplay::
# 31 "data/maps/FuchsiaCity_WardensHouse/scripts.pory"
	.string "POKéMON photos and fossils are on\n"
	.string "display.$"
