Route119_MapScripts::
# 2 "data/maps/Route119/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route119_OnResume
# 3 "data/maps/Route119/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route119_OnTransition
	.byte 0


Route119_Text_MayIntro::
# 7 "data/maps/Route119/scripts.pory"
	.string "MAY: {PLAYER}{KUN}! Where were you? I was\n"
	.string "looking for you!\p"
	.string "How much stronger have you gotten? Let\n"
	.string "me check for you!\p"
	.string "Ready with your POKMON? Of course you\n"
	.string "are! Go!$"

Route119_Text_MayDefeat::
# 11 "data/maps/Route119/scripts.pory"
	.string "Achah! {PLAYER}{KUN}, you're strong!\p"
	.string "I was worried that you might be\n"
	.string "struggling with your training.$"

Route119_Text_MayPresentForYou::
# 15 "data/maps/Route119/scripts.pory"
	.string "MAY: But I had absolutely nothing to\n"
	.string "worry about! Keep it up!\p"
	.string "And, here! I have a present for you.$"

Route119_Text_MayExplainFly::
# 19 "data/maps/Route119/scripts.pory"
	.string "MAY: Use FLY, and your POKMON will\n"
	.string "instantly carry you to any town you've\l"
	.string "already visited.\p"
	.string "But, to use FLY, you have to get the GYM\n"
	.string "BADGE from FORTREE CITY.\l"
	.string "That's important, so don't forget.\p"
	.string "You should FLY home and visit\n"
	.string "LITTLEROOT for a change.\p"
	.string "I bet your mom's worried about you,\n"
	.string "{PLAYER}{KUN}.\p"
	.string "Well, let's meet again somewhere!$"

Route119_Text_BrendanIntro::
# 23 "data/maps/Route119/scripts.pory"
	.string "BRENDAN: {PLAYER}! So this is where\n"
	.string "you've been looking for POKMON?\p"
	.string "Let me see how good you got. I'll test\n"
	.string "you!\p"
	.string "Now! It's a battle, so battle!$"

Route119_Text_BrendanDefeat::
# 27 "data/maps/Route119/scripts.pory"
	.string "Hmm You've gotten pretty darn decent.$"

Route119_Text_BrendanIllGiveYouThis::
# 31 "data/maps/Route119/scripts.pory"
	.string "BRENDAN: I'd say you're good enough to\n"
	.string "search for POKMON anywhere.\p"
	.string "Here, I'll give you this. Try it out.$"

Route119_Text_BrendanExplainFly::
# 35 "data/maps/Route119/scripts.pory"
	.string "BRENDAN: Use FLY, and your POKMON\n"
	.string "instantly carries you to any town\l"
	.string "you've already visited.\p"
	.string "But you need the FORTREE GYM BADGE to\n"
	.string "do that.\p"
	.string "Anyway, I have to move along.$"

Route119_Text_ScottWayToGoBeSeeingYou::
# 39 "data/maps/Route119/scripts.pory"
	.string "SCOTT: Hahahah! Way to go, {PLAYER}{KUN}!\p"
	.string "I just passed by a TRAINER riding a\n"
	.string "BIKE.\p"
	.string "You just beat that TRAINER, didn't you?\n"
	.string "It was pretty obvious that you did.\p"
	.string "The kid looked really upset with a face\n"
	.string "all red from anger.\p"
	.string "I sure seem to run into you often. Are\n"
	.string "you off to FORTREE GYM next?\p"
	.string "I expect that you'll do well at the GYM.\n"
	.string "Well, I'll be seeing you!$"

Route119_Text_ScottYouWonAtFortreeGym::
# 43 "data/maps/Route119/scripts.pory"
	.string "Beep!\p"
	.string "SCOTT: Hiya, {PLAYER}{KUN}, it's me!\p"
	.string "Just as I thought, you won at the\n"
	.string "FORTREE GYM.\p"
	.string "Your strength Perhaps you really are\n"
	.string "the TRAINER\l"
	.string "that I've been searching for.\p"
	.string "Remember, you have a fan in me. I'll be\n"
	.string "cheering from the sidelines.\l"
	.string "Keep up the great work!\p"
	.string "Click!$"

Route119_Text_StayAwayFromWeatherInstitute::
# 47 "data/maps/Route119/scripts.pory"
	.string "We're standing lookout here.\p"
	.string "Hey, you! Stay away from the WEATHER\n"
	.string "INSTITUTE. It's not safe.$"

Route119_Text_DontGoNearWeatherInstitute::
# 51 "data/maps/Route119/scripts.pory"
	.string "Lookout duty is surprisingly boring.\p"
	.string "Hey, you! Please don't go near the\n"
	.string "WEATHER INSTITUTE.$"

Route119_Text_ThoughtFlyByCatchingBirdMons::
# 55 "data/maps/Route119/scripts.pory"
	.string "I thought you FLY by catching a whole\n"
	.string "flock of BIRD POKMON, and then\l"
	.string "hanging on to them somehow.\p"
	.string "But it turns out there's an HM move\n"
	.string "called FLY!\p"
	.string "I wish I'd known about that a long time\n"
	.string "ago$"

Route119_Text_TallGrassSnaresBikeTires::
# 59 "data/maps/Route119/scripts.pory"
	.string "Tch It's a no-go\p"
	.string "The tall grass snares BIKE tires.\n"
	.string "There's no way you can cycle here.$"

Route119_Text_CanYourMonMakeSecretBase::
# 63 "data/maps/Route119/scripts.pory"
	.string "Can your POKMON use its SECRET POWER\n"
	.string "on a big pile of grass and make a\l"
	.string "SECRET BASE?$"

Route119_Text_RouteSignFortree::
# 67 "data/maps/Route119/scripts.pory"
	.string "ROUTE 119 {RIGHT_ARROW} FORTREE CITY$"

Route119_Text_WeatherInstitute::
# 71 "data/maps/Route119/scripts.pory"
	.string "WEATHER INSTITUTE$"

Route119_Text_TrainerTipsDecoration::
# 75 "data/maps/Route119/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Up to sixteen decorations and\n"
	.string "furniture items can be placed in\l"
	.string "a SECRET BASE.\p"
	.string "Pick your favorite items and create\n"
	.string "your very own SECRET BASE exactly the\l"
	.string "way you want.$"
