Route119_MapScripts::
	.byte 0


Route119_EventScript_Boy1::
# 5 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_ThoughtFlyByCatchingBirdMons, MSGBOX_NPC
	end


Route119_EventScript_Boy2::
# 10 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_CanYourMonMakeSecretBase, MSGBOX_NPC
	end


Route119_EventScript_Brent::
# 15 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_BRENT, Route119_Text_BrentIntro, Route119_Text_BrentDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_BrentPostBattle
	return


Route119_EventScript_BridgeAquaGrunt1::
# 20 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_StayAwayFromWeatherInstitute, MSGBOX_DEFAULT
	end


Route119_EventScript_BridgeAquaGrunt2::
# 25 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_DontGoNearWeatherInstitute, MSGBOX_DEFAULT
	end


Route119_EventScript_Catherine::
# 30 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_CATHERINE, Route119_Text_CatherineIntro, Route119_Text_CatherineDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_CatherinePostBattle
	return


Route119_EventScript_Chris::
# 35 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_CHRIS, Route119_Text_ChrisIntro, Route119_Text_ChrisDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_ChrisPostBattle
	return


Route119_EventScript_CyclingTriathleteM::
# 40 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_TallGrassSnaresBikeTires, MSGBOX_NPC
	end


Route119_EventScript_Dayton::
# 45 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_DAYTON, Route119_Text_DaytonIntro, Route119_Text_DaytonDefeat, Text_NotEnoughMonsForDoubleBattle
# 46 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_DaytonPostBattle
	return


Route119_EventScript_Donald::
# 50 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_DONALD, Route119_Text_DonaldIntro, Route119_Text_DonaldDefeat, Text_NotEnoughMonsForDoubleBattle
# 51 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_DonaldPostBattle
	return


Route119_EventScript_Doug::
# 55 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_DOUG, Route119_Text_DougIntro, Route119_Text_DougDefeat, Text_NotEnoughMonsForDoubleBattle
# 56 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_DougPostBattle
	return


Route119_EventScript_Fabian::
# 60 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_FABIAN, Route119_Text_FabianIntro, Route119_Text_FabianDefeat, Text_NotEnoughMonsForDoubleBattle
# 61 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_FabianPostBattle
	return


Route119_EventScript_Greg::
# 65 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_GREG, Route119_Text_GregIntro, Route119_Text_GregDefeat, Text_NotEnoughMonsForDoubleBattle
# 66 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_GregPostBattle
	return


Route119_EventScript_Hideo::
# 70 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_HIDEO, Route119_Text_HideoIntro, Route119_Text_HideoDefeat, Text_NotEnoughMonsForDoubleBattle
# 71 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_HideoPostBattle
	return


Route119_EventScript_Hugh::
# 75 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_HUGH, Route119_Text_HughIntro, Route119_Text_HughDefeat, Text_NotEnoughMonsForDoubleBattle
# 76 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_HughPostBattle
	return


Route119_EventScript_Jackson::
# 80 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_JACKSON, Route119_Text_JacksonIntro, Route119_Text_JacksonDefeat, Text_NotEnoughMonsForDoubleBattle
# 81 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_JacksonPostBattle
	return


Route119_EventScript_Kent::
# 85 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_KENT, Route119_Text_KentIntro, Route119_Text_KentDefeat, Text_NotEnoughMonsForDoubleBattle
# 86 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_KentPostBattle
	return


Route119_EventScript_Phil::
# 90 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_PHIL, Route119_Text_PhilIntro, Route119_Text_PhilDefeat, Text_NotEnoughMonsForDoubleBattle
# 91 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_PhilPostBattle
	return


Route119_EventScript_Rachel::
# 95 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_RACHEL, Route119_Text_RachelIntro, Route119_Text_RachelDefeat, Text_NotEnoughMonsForDoubleBattle
# 96 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_RachelPostBattle
	return


Route119_EventScript_RivalTrigger1::
	end


Route119_EventScript_RivalTrigger2::
	end


Route119_EventScript_RouteSignFortree::
# 108 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_RouteSignFortree, MSGBOX_SIGN
	end


Route119_EventScript_Takashi::
# 113 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_TAKASHI, Route119_Text_TakashiIntro, Route119_Text_TakashiDefeat, Text_NotEnoughMonsForDoubleBattle
# 114 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_TakashiPostBattle
	return


Route119_EventScript_Taylor::
# 118 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_TAYLOR, Route119_Text_TaylorIntro, Route119_Text_TaylorDefeat, Text_NotEnoughMonsForDoubleBattle
# 119 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_TaylorPostBattle
	return


Route119_EventScript_TrainerTipsDecoration::
# 123 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_TrainerTipsDecoration, MSGBOX_SIGN
	end


Route119_EventScript_WeatherInstituteSign::
# 128 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_WeatherInstitute, MSGBOX_SIGN
	end


Route119_EventScript_Yasu::
# 133 "data/maps/Route119/scripts.pory"
	trainerbattle_double TRAINER_YASU, Route119_Text_YasuIntro, Route119_Text_YasuDefeat, Text_NotEnoughMonsForDoubleBattle
# 134 "data/maps/Route119/scripts.pory"
	msgbox Route119_Text_YasuPostBattle
	return


Route119_Text_WeatherInstitute::
# 138 "data/maps/Route119/scripts.pory"
	.string "WEATHER INSTITUTE$"

Route119_Text_RouteSignFortree::
# 142 "data/maps/Route119/scripts.pory"
	.string "ROUTE 119 {RIGHT_ARROW} FORTREE CITY$"

Route119_Text_TrainerTipsDecoration::
# 146 "data/maps/Route119/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Up to sixteen decorations and\n"
	.string "furniture items can be placed in\l"
	.string "a SECRET BASE.\p"
	.string "Pick your favorite items and create\n"
	.string "your very own SECRET BASE exactly the\l"
	.string "way you want.$"

Route119_Text_BrentDefeat::
# 151 "data/maps/Route119/scripts.pory"
	.string "Whoopsie! I lost!$"

Route119_Text_BrentIntro::
# 155 "data/maps/Route119/scripts.pory"
	.string "We're the MIMIC CIRCLE! We MIMIC what\n"
	.string "you do!$"

Route119_Text_BrentPostBattle::
# 159 "data/maps/Route119/scripts.pory"
	.string "What's so good about mimicry?\p"
	.string "Fufufu… You'll never understand…$"

Route119_Text_CatherineDefeat::
# 163 "data/maps/Route119/scripts.pory"
	.string "Accidents happen when you're not\n"
	.string "prepared!$"

Route119_Text_CatherineIntro::
# 167 "data/maps/Route119/scripts.pory"
	.string "Oh? Look at you.\p"
	.string "For someone on an adventure, you're\n"
	.string "traveling awfully light.$"

Route119_Text_CatherinePostBattle::
# 171 "data/maps/Route119/scripts.pory"
	.string "You're traveling light but you have\n"
	.string "everything you need.\p"
	.string "You're on top of things mentally and\n"
	.string "physically, too.$"

Route119_Text_ChrisDefeat::
# 175 "data/maps/Route119/scripts.pory"
	.string "I don't have a clue about what it takes\n"
	.string "to win.$"

Route119_Text_ChrisIntro::
# 179 "data/maps/Route119/scripts.pory"
	.string "You spoke to me… So you want to\n"
	.string "challenge me!\p"
	.string "Sure! I'll try out the POKéMON I caught\n"
	.string "while SURFING!$"

Route119_Text_ChrisPostBattle::
# 183 "data/maps/Route119/scripts.pory"
	.string "Go for a SURF on my POKéMON…\p"
	.string "Then fish off its back…\p"
	.string "It's an indescribably luxuriant moment!$"

Route119_Text_DaytonDefeat::
# 187 "data/maps/Route119/scripts.pory"
	.string "You're pretty amazing! Hohoho!$"

Route119_Text_DaytonIntro::
# 191 "data/maps/Route119/scripts.pory"
	.string "Hohoho! I like kid TRAINERS! Let's have\n"
	.string "a good one!$"

Route119_Text_DaytonPostBattle::
# 195 "data/maps/Route119/scripts.pory"
	.string "Hohoho! I'll try emulating the pep of\n"
	.string "kid TRAINERS like you!$"

Route119_Text_DonaldDefeat::
# 199 "data/maps/Route119/scripts.pory"
	.string "I wish we'd never met…$"

Route119_Text_DonaldIntro::
# 203 "data/maps/Route119/scripts.pory"
	.string "So, we finally meet! My BUG POKéMON will\n"
	.string "keep you company!$"

Route119_Text_DonaldPostBattle::
# 207 "data/maps/Route119/scripts.pory"
	.string "I want to MIMIC you some more. Can you\n"
	.string "hurry up and move?$"

Route119_Text_DougDefeat::
# 211 "data/maps/Route119/scripts.pory"
	.string "Whoop, that was a great match!$"

Route119_Text_DougIntro::
# 215 "data/maps/Route119/scripts.pory"
	.string "Yep, you've finally caught me! Or were\n"
	.string "you trying to avoid me?$"

Route119_Text_DougPostBattle::
# 219 "data/maps/Route119/scripts.pory"
	.string "We're the MIMIC CIRCLE! I hope you\n"
	.string "enjoyed our performance.$"

Route119_Text_FabianDefeat::
# 223 "data/maps/Route119/scripts.pory"
	.string "You showed me who's the boss! We'll have\n"
	.string "to take the loss, oh, no!$"

Route119_Text_FabianIntro::
# 227 "data/maps/Route119/scripts.pory"
	.string "Hit me with a power chord! Victory is\n"
	.string "mine! It's our time to shine, whoa, yeah!$"

Route119_Text_FabianPostBattle::
# 231 "data/maps/Route119/scripts.pory"
	.string "Hit me with another power chord! Leave\n"
	.string "me alone! Your win you have to atone!$"

Route119_Text_GregDefeat::
# 235 "data/maps/Route119/scripts.pory"
	.string "You're pretty strong!$"

Route119_Text_GregIntro::
# 239 "data/maps/Route119/scripts.pory"
	.string "You don't know who I am, do you?\p"
	.string "But, I also don't know you. So, we'll\n"
	.string "battle!$"

Route119_Text_GregPostBattle::
# 243 "data/maps/Route119/scripts.pory"
	.string "Until you go away somewhere, we'll keep\n"
	.string "on mimicking your every move.$"

Route119_Text_HideoDefeat::
# 247 "data/maps/Route119/scripts.pory"
	.string "I bow to your superiority.$"

Route119_Text_HideoIntro::
# 251 "data/maps/Route119/scripts.pory"
	.string "To hide a tree, use a forest!$"

Route119_Text_HideoPostBattle::
# 255 "data/maps/Route119/scripts.pory"
	.string "To hide a tree, use a forest! To hide a\n"
	.string "POKéMON, use a POKéMON!\p"
	.string "There is no deep, hidden meaning to\n"
	.string "that.$"

Route119_Text_HughDefeat::
# 259 "data/maps/Route119/scripts.pory"
	.string "Down and out!$"

Route119_Text_HughIntro::
# 263 "data/maps/Route119/scripts.pory"
	.string "The vast sky holds untold promise!\p"
	.string "Nothing can compare to the sheer\n"
	.string "exhilaration of flight!$"

Route119_Text_HughPostBattle::
# 267 "data/maps/Route119/scripts.pory"
	.string "My BIRD POKéMON made my dreams of\n"
	.string "flying come true!$"

Route119_Text_JacksonDefeat::
# 271 "data/maps/Route119/scripts.pory"
	.string "I didn't have enough POKéMON know-how…$"

Route119_Text_JacksonIntro::
# 275 "data/maps/Route119/scripts.pory"
	.string "Who has the knowledge and the\n"
	.string "technique for survival?\p"
	.string "POKéMON RANGERS, that's who!$"

Route119_Text_JacksonPostBattle::
# 279 "data/maps/Route119/scripts.pory"
	.string "To break away from civilization and\n"
	.string "awaken the wild spirit within!\p"
	.string "That's our vision.$"

Route119_Text_KentDefeat::
# 283 "data/maps/Route119/scripts.pory"
	.string "I give up!$"

Route119_Text_KentIntro::
# 287 "data/maps/Route119/scripts.pory"
	.string "The MIMIC CIRCLE was formed by people\n"
	.string "who like to MIMIC.\p"
	.string "A battle starts the instant we meet!$"

Route119_Text_KentPostBattle::
# 291 "data/maps/Route119/scripts.pory"
	.string "Won't you join our MIMIC CIRCLE?$"

Route119_Text_PhilDefeat::
# 295 "data/maps/Route119/scripts.pory"
	.string "We lacked potential…$"

Route119_Text_PhilIntro::
# 299 "data/maps/Route119/scripts.pory"
	.string "I'll show you the true potential of me\n"
	.string "and my BIRD POKéMON!$"

Route119_Text_PhilPostBattle::
# 303 "data/maps/Route119/scripts.pory"
	.string "Ever since I was a little kid, I always\n"
	.string "admired BIRD POKéMON…$"

Route119_Text_RachelDefeat::
# 307 "data/maps/Route119/scripts.pory"
	.string "Oh, but… That's not fair.$"

Route119_Text_RachelIntro::
# 311 "data/maps/Route119/scripts.pory"
	.string "Wherever and whenever I may be, I\n"
	.string "always have my parasol in hand.$"

Route119_Text_RachelPostBattle::
# 315 "data/maps/Route119/scripts.pory"
	.string "You're asking if my parasol is heavy?\n"
	.string "Your BAG is filled with more junk than I\l"
	.string "ever carry around.$"

Route119_Text_TakashiDefeat::
# 319 "data/maps/Route119/scripts.pory"
	.string "You're surprisingly good!$"

Route119_Text_TakashiIntro::
# 323 "data/maps/Route119/scripts.pory"
	.string "If you're not on your guard, you're in\n"
	.string "for some pain!$"

Route119_Text_TakashiPostBattle::
# 327 "data/maps/Route119/scripts.pory"
	.string "My surprise attack ended in failure…$"

Route119_Text_TaylorDefeat::
# 331 "data/maps/Route119/scripts.pory"
	.string "But if you win, I lose…$"

Route119_Text_TaylorIntro::
# 335 "data/maps/Route119/scripts.pory"
	.string "If you step forward, we step forward.\p"
	.string "If you turn right, we turn, too…$"

Route119_Text_TaylorPostBattle::
# 339 "data/maps/Route119/scripts.pory"
	.string "I can't MIMIC you winning the match.\n"
	.string "That's just impossible… It's burning me\l"
	.string "up…$"

Route119_Text_YasuDefeat::
# 343 "data/maps/Route119/scripts.pory"
	.string "I admit defeat!$"

Route119_Text_YasuIntro::
# 347 "data/maps/Route119/scripts.pory"
	.string "To lurk in shadows, and live in\n"
	.string "darkness… That is my destiny.\p"
	.string "I emerge to challenge you!$"

Route119_Text_YasuPostBattle::
# 351 "data/maps/Route119/scripts.pory"
	.string "Those defeated in battle withdraw\n"
	.string "quietly back into the shadows. That,\l"
	.string "too, is destiny…$"

Route119_Text_BrendanIllGiveYouThis::
# 355 "data/maps/Route119/scripts.pory"
	.string "BRENDAN: I'd say you're good enough\n"
	.string "to search for POKéMON anywhere.\p"
	.string "Here, I'll give you this.\n"
	.string "Try it out.$"

Route119_Text_BrendanIntro::
# 359 "data/maps/Route119/scripts.pory"
	.string "BRENDAN: {PLAYER}! So this is where\n"
	.string "you've been looking for POKéMON?\p"
	.string "Let me see how good you got.\n"
	.string "I'll test you!\p"
	.string "Now!\n"
	.string "It's a battle, so battle!$"

Route119_Text_StayAwayFromWeatherInstitute::
# 363 "data/maps/Route119/scripts.pory"
	.string "We're standing lookout here.\p"
	.string "Hey, you! Stay away from the WEATHER\n"
	.string "INSTITUTE. It's not safe.$"

Route119_Text_ThoughtFlyByCatchingBirdMons::
# 367 "data/maps/Route119/scripts.pory"
	.string "I thought you FLY by catching a whole\n"
	.string "flock of BIRD POKéMON, and then\l"
	.string "hanging on to them somehow.\p"
	.string "But it turns out there's an HM move\n"
	.string "called FLY!\p"
	.string "I wish I'd known about that a long\n"
	.string "time ago…$"

Route119_Text_TallGrassSnaresBikeTires::
# 371 "data/maps/Route119/scripts.pory"
	.string "Tch…\n"
	.string "It's a no-go…\p"
	.string "The tall grass snares BIKE tires.\n"
	.string "There's no way you can cycle here.$"

Route119_Text_DontGoNearWeatherInstitute::
# 375 "data/maps/Route119/scripts.pory"
	.string "Lookout duty is surprisingly boring.\p"
	.string "Hey, you! Please don't go near the\n"
	.string "WEATHER INSTITUTE.$"

Route119_Text_CanYourMonMakeSecretBase::
# 379 "data/maps/Route119/scripts.pory"
	.string "Can your POKéMON use its SECRET POWER\n"
	.string "on a big pile of grass and make a\l"
	.string "SECRET BASE?$"

Route119_Text_MayPresentForYou::
# 383 "data/maps/Route119/scripts.pory"
	.string "MAY: But I had absolutely nothing to\n"
	.string "worry about! Keep it up!\p"
	.string "And, here! I have a present for you.$"

Route119_Text_MayIntro::
# 387 "data/maps/Route119/scripts.pory"
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Where were you? I was looking for you!\p"
	.string "How much stronger have you gotten?\n"
	.string "Let me check for you!\p"
	.string "Ready with your POKéMON?\n"
	.string "Of course you are! Go!$"
