Underwater_SeafloorCavern_MapScripts::
# 2 "data/maps/Underwater_SeafloorCavern/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Underwater_SeafloorCavern_OnResume
# 3 "data/maps/Underwater_SeafloorCavern/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Underwater_SeafloorCavern_OnTransition
# 4 "data/maps/Underwater_SeafloorCavern/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Underwater_SeafloorCavern_OnLoad
	.byte 0


Underwater_SeafloorCavern_Text_SubExplorer1::
# 8 "data/maps/Underwater_SeafloorCavern/scripts.pory"
	.string "“SUBMARINE EXPLORER 1” is painted on\n"
	.string "the hull.\p"
	.string "This is the submarine TEAM AQUA stole in\n"
	.string "SLATEPORT!\p"
	.string "TEAM AQUA must have gone ashore here.$"
