SaffronCity_MrPsychicsHouse_MapScripts::
	.byte 0


SaffronCity_MrPsychicsHouse_Text_YouWantedThis::
# 5 "data/maps/SaffronCity_MrPsychicsHouse/scripts.pory"
	.string "…Wait! Don't say a word!\p"
	.string "You wanted this!$"

SaffronCity_MrPsychicsHouse_Text_ReceivedTM29FromMrPsychic::
# 9 "data/maps/SaffronCity_MrPsychicsHouse/scripts.pory"
	.string "{PLAYER} received TM29 from MR.\n"
	.string "PSYCHIC.$"

SaffronCity_MrPsychicsHouse_Text_ExplainTM29::
# 13 "data/maps/SaffronCity_MrPsychicsHouse/scripts.pory"
	.string "You already know, don't you? TM29 is\n"
	.string "PSYCHIC.\p"
	.string "It's an attack that may also lower the\n"
	.string "target's special stats.$"

SaffronCity_MrPsychicsHouse_Text_YouveNoRoom::
# 17 "data/maps/SaffronCity_MrPsychicsHouse/scripts.pory"
	.string "Where do you plan to put this? You've no\n"
	.string "room.$"
