RockTunnel_B1F_MapScripts::
	.byte 0


RockTunnel_B1F_Text_SofiaIntro::
# 5 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Do you know how you can avoid getting\n"
	.string "lost in the mountains?\p"
	.string "You can bend twigs as trail markers.$"

RockTunnel_B1F_Text_SofiaDefeat::
# 9 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Ohhh! I did my best!$"

RockTunnel_B1F_Text_SofiaPostBattle::
# 13 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I want to go home!$"

RockTunnel_B1F_Text_DudleyIntro::
# 17 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Hahaha! Can you beat my power?$"

RockTunnel_B1F_Text_DudleyDefeat::
# 21 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Oops! Outmuscled!$"

RockTunnel_B1F_Text_DudleyPostBattle::
# 25 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I go for power because I hate thinking.$"

RockTunnel_B1F_Text_CooperIntro::
# 29 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "You have a POKDEX? I want one, too.$"

RockTunnel_B1F_Text_CooperDefeat::
# 33 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Shoot! I am so jealous!$"

RockTunnel_B1F_Text_CooperPostBattle::
# 37 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "When you finish your POKDEX, can I have\n"
	.string "it?$"

RockTunnel_B1F_Text_SteveIntro::
# 41 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Um Do you know about POKMON cosplay?$"

RockTunnel_B1F_Text_SteveDefeat::
# 45 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Well, that's that.$"

RockTunnel_B1F_Text_StevePostBattle::
# 49 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "POKMON cosplay is dressing up as\n"
	.string "POKMON for fun.\p"
	.string "CLEFAIRY is a favorite.$"

RockTunnel_B1F_Text_AllenIntro::
# 53 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "My POKMON techniques will leave you\n"
	.string "crying!$"

RockTunnel_B1F_Text_AllenDefeat::
# 57 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I give! You're a better technician!$"

RockTunnel_B1F_Text_AllenPostBattle::
# 61 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "In mountains, you'll often find\n"
	.string "ROCK-type POKMON.$"

RockTunnel_B1F_Text_MarthaIntro::
# 65 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I don't often come here, but I will\n"
	.string "battle you.$"

RockTunnel_B1F_Text_MarthaDefeat::
# 69 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Oh! I lost!$"

RockTunnel_B1F_Text_MarthaPostBattle::
# 73 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I like tiny POKMON. Big ones are too\n"
	.string "scary!$"

RockTunnel_B1F_Text_EricIntro::
# 77 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Hit me with your best shot!$"

RockTunnel_B1F_Text_EricDefeat::
# 81 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Fired away!$"

RockTunnel_B1F_Text_EricPostBattle::
# 85 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I'll raise my POKMON to beat yours, kid.$"

RockTunnel_B1F_Text_WinstonIntro::
# 89 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I draw illustrations of POKMON when I'm\n"
	.string "home.$"

RockTunnel_B1F_Text_WinstonDefeat::
# 93 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Whew I'm exhausted$"

RockTunnel_B1F_Text_WinstonPostBattle::
# 97 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "I'm an artist, not a fighter. I'll go home\n"
	.string "to draw.$"
