RockTunnel_B1F_MapScripts::
	.byte 0


RockTunnel_B1F_EventScript_Allen::
# 5 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_ALLEN, RockTunnel_B1F_Text_AllenIntro, RockTunnel_B1F_Text_AllenDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_AllenPostBattle
	return


RockTunnel_B1F_EventScript_Cooper::
# 10 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_POKEMANIAC_COOPER, RockTunnel_B1F_Text_CooperIntro, RockTunnel_B1F_Text_CooperDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_CooperPostBattle
	return


RockTunnel_B1F_EventScript_Dudley::
# 15 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_DUDLEY, RockTunnel_B1F_Text_DudleyIntro, RockTunnel_B1F_Text_DudleyDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_DudleyPostBattle
	return


RockTunnel_B1F_EventScript_Eric::
# 20 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_ERIC, RockTunnel_B1F_Text_EricIntro, RockTunnel_B1F_Text_EricDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_EricPostBattle
	return


RockTunnel_B1F_EventScript_Martha::
# 25 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_MARTHA, RockTunnel_B1F_Text_MarthaIntro, RockTunnel_B1F_Text_MarthaDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_MarthaPostBattle
	return


RockTunnel_B1F_EventScript_Sofia::
# 30 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_SOFIA, RockTunnel_B1F_Text_SofiaIntro, RockTunnel_B1F_Text_SofiaDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_SofiaPostBattle
	return


RockTunnel_B1F_EventScript_Steve::
# 35 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_POKEMANIAC_STEVE, RockTunnel_B1F_Text_SteveIntro, RockTunnel_B1F_Text_SteveDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_StevePostBattle
	return


RockTunnel_B1F_EventScript_Winston::
# 40 "data/maps/RockTunnel_B1F/scripts.pory"
	trainerbattle_double TRAINER_POKEMANIAC_WINSTON, RockTunnel_B1F_Text_WinstonIntro, RockTunnel_B1F_Text_WinstonDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/RockTunnel_B1F/scripts.pory"
	msgbox RockTunnel_B1F_Text_WinstonPostBattle
	return


RockTunnel_B1F_Text_AllenDefeat::
# 46 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_AllenDefeat$"

RockTunnel_B1F_Text_AllenIntro::
# 50 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_AllenIntro$"

RockTunnel_B1F_Text_AllenPostBattle::
# 54 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_AllenPostBattle$"

RockTunnel_B1F_Text_CooperDefeat::
# 58 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_CooperDefeat$"

RockTunnel_B1F_Text_CooperIntro::
# 62 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_CooperIntro$"

RockTunnel_B1F_Text_CooperPostBattle::
# 66 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_CooperPostBattle$"

RockTunnel_B1F_Text_DudleyDefeat::
# 70 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_DudleyDefeat$"

RockTunnel_B1F_Text_DudleyIntro::
# 74 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_DudleyIntro$"

RockTunnel_B1F_Text_DudleyPostBattle::
# 78 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_DudleyPostBattle$"

RockTunnel_B1F_Text_EricDefeat::
# 82 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_EricDefeat$"

RockTunnel_B1F_Text_EricIntro::
# 86 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_EricIntro$"

RockTunnel_B1F_Text_EricPostBattle::
# 90 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_EricPostBattle$"

RockTunnel_B1F_Text_MarthaDefeat::
# 94 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_MarthaDefeat$"

RockTunnel_B1F_Text_MarthaIntro::
# 98 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_MarthaIntro$"

RockTunnel_B1F_Text_MarthaPostBattle::
# 102 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_MarthaPostBattle$"

RockTunnel_B1F_Text_SofiaDefeat::
# 106 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_SofiaDefeat$"

RockTunnel_B1F_Text_SofiaIntro::
# 110 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_SofiaIntro$"

RockTunnel_B1F_Text_SofiaPostBattle::
# 114 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_SofiaPostBattle$"

RockTunnel_B1F_Text_SteveDefeat::
# 118 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_SteveDefeat$"

RockTunnel_B1F_Text_SteveIntro::
# 122 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_SteveIntro$"

RockTunnel_B1F_Text_StevePostBattle::
# 126 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_StevePostBattle$"

RockTunnel_B1F_Text_WinstonDefeat::
# 130 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_WinstonDefeat$"

RockTunnel_B1F_Text_WinstonIntro::
# 134 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_WinstonIntro$"

RockTunnel_B1F_Text_WinstonPostBattle::
# 138 "data/maps/RockTunnel_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_B1F_Text_WinstonPostBattle$"
