Route112_MapScripts::
# 2 "data/maps/Route112/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route112_OnTransition
	.byte 0


Route112_Text_LeaderGoingToAwakenThing::
# 6 "data/maps/Route112/scripts.pory"
	.string "Hey, man, is our leader really going to\n"
	.string "awaken that thing?$"

Route112_Text_YeahWeNeedMeteorite::
# 10 "data/maps/Route112/scripts.pory"
	.string "Sounds like it, yeah. But I heard we\n"
	.string "need a METEORITE to do it.$"

Route112_Text_OhThatsWhyCrewWentToFallarbor::
# 14 "data/maps/Route112/scripts.pory"
	.string "Oh, I get it now. That's why the rest of\n"
	.string "the crew went out to FALLARBOR.$"

Route112_Text_CantLetAnyonePassUntilTheyreBack::
# 18 "data/maps/Route112/scripts.pory"
	.string "You got it. And until they come back,\n"
	.string "we're not to let anyone pass, right.$"

Route112_Text_NotEasyToGetBackToLavaridge::
# 22 "data/maps/Route112/scripts.pory"
	.string "Eh, I'd like to get to MAUVILLE, but if I\n"
	.string "went down these ledges, it'd be no\l"
	.string "easy matter to get back to LAVARIDGE.$"

Route112_Text_MtChimneyCableCarSign::
# 26 "data/maps/Route112/scripts.pory"
	.string "MT. CHIMNEY CABLE CAR “A short walk {UP_ARROW}\n"
	.string "way!”$"

Route112_Text_MtChimneySign::
# 30 "data/maps/Route112/scripts.pory"
	.string "MT. CHIMNEY\p"
	.string "“For LAVARIDGE TOWN or the summit,\n"
	.string "please take the CABLE CAR.”$"

Route112_Text_RouteSignLavaridge::
# 34 "data/maps/Route112/scripts.pory"
	.string "ROUTE 112 {LEFT_ARROW} LAVARIDGE TOWN$"
