CeladonCity_Condominiums_1F_MapScripts::
	.byte 0


CeladonCity_Condominiums_1F_Text_Meowth::
# 5 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "MEOWTH: Meow!$"

CeladonCity_Condominiums_1F_Text_TryThisDrinkInstead::
# 9 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "You shouldn't spend all your money on\n"
	.string "drinks.\p"
	.string "Try this instead.$"

CeladonCity_Condominiums_1F_Text_NothingBeatsThirstLikeTea::
# 13 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "Nothing beats thirst like some hot TEA.\p"
	.string "It really is the best.$"

CeladonCity_Condominiums_1F_Text_MyDearMonsKeepMeCompany::
# 17 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "My dear POKMON keep me company. MEOWTH\n"
	.string "even brings money home!$"

CeladonCity_Condominiums_1F_Text_DaisyComesToBuyTea::
# 21 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "Oh, hello, dearie. Did you enjoy my TEA?\p"
	.string "By the way, dear. Are you, by any chance,\n"
	.string "from PALLET TOWN?\p"
	.string "A girl from PALLET TOWN, DAISY, she\n"
	.string "enjoys TEA every day.\p"
	.string "She visits the CELADON DEPT. STORE to\n"
	.string "buy some TEA.$"

CeladonCity_Condominiums_1F_Text_Clefairy::
# 25 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "CLEFAIRY: Pi pippippi!$"

CeladonCity_Condominiums_1F_Text_Nidoran::
# 29 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "NIDORAN: Kya kyaoo!$"

CeladonCity_Condominiums_1F_Text_ManagersSuite::
# 33 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "CELADON MANSION Manager's Suite$"
