CeladonCity_Condominiums_1F_MapScripts::
	.byte 0


CeladonCity_Condominiums_1F_EventScript_Clefairy::
	end


CeladonCity_Condominiums_1F_EventScript_Meowth::
	end


CeladonCity_Condominiums_1F_EventScript_Nidoran::
	end


CeladonCity_Condominiums_1F_EventScript_SuiteSign::
# 17 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	msgbox CeladonCity_Condominiums_1F_Text_ManagersSuite, MSGBOX_SIGN
	end


CeladonCity_Condominiums_1F_EventScript_TeaWoman::
	end


CeladonCity_Condominiums_1F_Text_ManagersSuite::
# 26 "data/maps/CeladonCity_Condominiums_1F/scripts.pory"
	.string "CELADON MANSION Manager's Suite$"
