FortreeCity_House2_MapScripts::
	.byte 0


FortreeCity_House2_EventScript_HiddenPowerGiver::
	end


FortreeCity_House2_Text_YouGuessedWrong::
# 8 "data/maps/FortreeCity_House2/scripts.pory"
	.string "No, too bad.\n"
	.string "You guessed wrong.$"

FortreeCity_House2_Text_ExplainHiddenPower::
# 12 "data/maps/FortreeCity_House2/scripts.pory"
	.string "HIDDEN POWER is a move that changes\n"
	.string "with the POKéMON.$"

FortreeCity_House2_Text_HiddenPowersArousedByNature::
# 16 "data/maps/FortreeCity_House2/scripts.pory"
	.string "People… POKéMON…\p"
	.string "Their hidden powers are aroused by\n"
	.string "living in natural environments…$"
