FortreeCity_House2_MapScripts::
	.byte 0


FortreeCity_House2_MapScripts::
	return


FortreeCity_House2_Text_HiddenPowersArousedByNature::
# 8 "data/maps/FortreeCity_House2/scripts.pory"
	.string "People… POKéMON…\p"
	.string "Their hidden powers are aroused by\n"
	.string "living in natural environments…$"

FortreeCity_House2_Text_CoinInWhichHand::
# 12 "data/maps/FortreeCity_House2/scripts.pory"
	.string "Let this old woman see if your hidden\n"
	.string "power has awoken…\p"
	.string "I hold a coin in my hand.\p"
	.string "Now, tell me, have I palmed it in the\n"
	.string "right hand? Or in the left?$"

FortreeCity_House2_Text_CorrectTryAgainWhichHand::
# 16 "data/maps/FortreeCity_House2/scripts.pory"
	.string "Oh! Yes, correct!\p"
	.string "We shall try again.\p"
	.string "In which hand have I palmed the coin?\n"
	.string "The right or left?$"

FortreeCity_House2_Text_CorrectTryAgainWhichHand2::
# 20 "data/maps/FortreeCity_House2/scripts.pory"
	.string "Oh! Yes, correct!\p"
	.string "We shall try again.\p"
	.string "In which hand have I palmed the coin?\n"
	.string "The right or left?$"

FortreeCity_House2_Text_YourHiddenPowerHasAwoken::
# 24 "data/maps/FortreeCity_House2/scripts.pory"
	.string "Oh! Splendid! Your hidden power has\n"
	.string "awoken!\p"
	.string "Here, take this and awaken the hidden\n"
	.string "power of your POKéMON.$"

FortreeCity_House2_Text_ExplainHiddenPower::
# 28 "data/maps/FortreeCity_House2/scripts.pory"
	.string "HIDDEN POWER is a move that changes\n"
	.string "with the POKéMON.$"

FortreeCity_House2_Text_YouGuessedWrong::
# 32 "data/maps/FortreeCity_House2/scripts.pory"
	.string "No, too bad. You guessed wrong.$"
