CeladonCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/CeladonCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeladonCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/CeladonCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


CeladonCity_PokemonCenter_1F_Text_PokeFluteAwakensSleepingMons::
# 7 "data/maps/CeladonCity_PokemonCenter_1F/scripts.pory"
	.string "A POK FLUTE awakens sleeping POKMON.\n"
	.string "You know that.\p"
	.string "It does so with a sound that only they\n"
	.string "can hear.$"

CeladonCity_PokemonCenter_1F_Text_RodeHereFromFuchsia::
# 11 "data/maps/CeladonCity_PokemonCenter_1F/scripts.pory"
	.string "I rode here from FUCHSIA.\p"
	.string "It's an uphill ride on CYCLING ROAD, so\n"
	.string "I'm exhausted.$"

CeladonCity_PokemonCenter_1F_Text_GoToCyclingRoadIfIHadBike::
# 15 "data/maps/CeladonCity_PokemonCenter_1F/scripts.pory"
	.string "If I had a BIKE, I would go to CYCLING\n"
	.string "ROAD!$"
