MauvilleCity_PokemonCenter_2F_MapScripts::
# 2 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
# 3 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
# 4 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
# 5 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
	.byte 0


MauvilleCity_PokemonCenter_2F_MapScripts::
# 9 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CableClub_OnFrame
# 10 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, CableClub_OnWarp
# 11 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
# 12 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CableClub_OnTransition
	return


MauvilleCity_PokemonCenter_2F_Text_Youngster::
# 16 "data/maps/MauvilleCity_PokemonCenter_2F/scripts.pory"
	.string "Did you know that you can link battle at\n"
	.string "the COLOSSEUM here?\p"
	.string "They put up your record on the wall for\n"
	.string "everyone to see.\p"
	.string "It's embarrassing if you lose more\n"
	.string "often than you win…$"
