PetalburgWoods_MapScripts::
	.byte 0


PetalburgWoods_MapScripts::
	return


PetalburgWoods_Text_NotAOneToBeFound::
# 8 "data/maps/PetalburgWoods/scripts.pory"
	.string "Hmmm… Not a one to be found…$"

PetalburgWoods_Text_HaveYouSeenShroomish::
# 12 "data/maps/PetalburgWoods/scripts.pory"
	.string "Hello, have you seen any POKéMON called\n"
	.string "SHROOMISH around here?\p"
	.string "I really love that POKéMON.$"

PetalburgWoods_Text_IWasGoingToAmbushYou::
# 16 "data/maps/PetalburgWoods/scripts.pory"
	.string "I was going to ambush you, but you had\n"
	.string "to dawdle in PETALBURG WOODS\l"
	.string "forever, didn't you?\p"
	.string "I got sick of waiting, so here I am!$"

PetalburgWoods_Text_HandOverThosePapers::
# 20 "data/maps/PetalburgWoods/scripts.pory"
	.string "You! DEVON RESEARCHER!\p"
	.string "Hand over those papers!$"

PetalburgWoods_Text_YouHaveToHelpMe::
# 24 "data/maps/PetalburgWoods/scripts.pory"
	.string "Aiyeeeh!\p"
	.string "You're a POKéMON TRAINER, aren't you?\n"
	.string "You've got to help me, please!$"

PetalburgWoods_Text_NoOneCrossesTeamAqua::
# 28 "data/maps/PetalburgWoods/scripts.pory"
	.string "Hunh? What do you think you're doing?\n"
	.string "What, you're going to protect him?\p"
	.string "No one who crosses TEAM AQUA gets any\n"
	.string "mercy, not even a kid!\p"
	.string "Come on and battle me!$"

PetalburgWoods_Text_YoureKiddingMe::
# 32 "data/maps/PetalburgWoods/scripts.pory"
	.string "You're kidding me! You're tough!$"

PetalburgWoods_Text_YouveGotSomeNerve::
# 36 "data/maps/PetalburgWoods/scripts.pory"
	.string "Grrr… You've got some nerve meddling\n"
	.string "with TEAM AQUA!\l"
	.string "Come on and battle me again!\p"
	.string "I wish I could say that, but I'm out of\n"
	.string "POKéMON…\p"
	.string "And, hey, we of TEAM AQUA are also after\n"
	.string "something in RUSTBORO.\p"
	.string "I'll let you go today!$"

PetalburgWoods_Text_ThatWasAwfullyClose::
# 40 "data/maps/PetalburgWoods/scripts.pory"
	.string "Whew… That was awfully close!\p"
	.string "Thanks to you, he didn't rob me of these\n"
	.string "important papers.\p"
	.string "I know, I'll give you a GREAT BALL as my\n"
	.string "thanks!$"

PetalburgWoods_Text_TeamAquaAfterSomethingInRustboro::
# 44 "data/maps/PetalburgWoods/scripts.pory"
	.string "Didn't that TEAM AQUA thug say they\n"
	.string "were after something in\l"
	.string "RUSTBORO, too?$"

PetalburgWoods_Text_ICantBeWastingTime::
# 48 "data/maps/PetalburgWoods/scripts.pory"
	.string "Uh-oh! It's a crisis! I can't be wasting\n"
	.string "time!$"

PetalburgWoods_Text_YoureLoadedWithItems::
# 52 "data/maps/PetalburgWoods/scripts.pory"
	.string "You're loaded with items. I can't give\n"
	.string "you this GREAT BALL.$"

PetalburgWoods_Text_GoBugPokemonTeam::
# 56 "data/maps/PetalburgWoods/scripts.pory"
	.string "I caught a whole bunch of POKéMON!\p"
	.string "Go, go, go! My BUG POKéMON team!$"

PetalburgWoods_Text_ICouldntWin::
# 60 "data/maps/PetalburgWoods/scripts.pory"
	.string "I have all these POKéMON, but I couldn't\n"
	.string "win…$"

PetalburgWoods_Text_ImOutOfPokeBalls::
# 64 "data/maps/PetalburgWoods/scripts.pory"
	.string "I caught a bunch of POKéMON. Now I'm\n"
	.string "out of POKé BALLS.$"

PetalburgWoods_Text_InstantlyPopularWithBugPokemon::
# 68 "data/maps/PetalburgWoods/scripts.pory"
	.string "If you take BUG POKéMON to school, you\n"
	.string "get to be instantly popular!$"

PetalburgWoods_Text_CantBePopularIfILose::
# 72 "data/maps/PetalburgWoods/scripts.pory"
	.string "I can't be popular if I lose.$"

PetalburgWoods_Text_PeopleRespectYou::
# 76 "data/maps/PetalburgWoods/scripts.pory"
	.string "If you have a big BUG POKéMON, people\n"
	.string "respect you for it.$"

PetalburgWoods_Text_IWantRematch1::
# 80 "data/maps/PetalburgWoods/scripts.pory"
	.string "I want a rematch when my BUG POKéMON\n"
	.string "grow up!\p"
	.string "I'm registering you in my POKéNAV!$"

PetalburgWoods_Text_IWantRematch2::
# 84 "data/maps/PetalburgWoods/scripts.pory"
	.string "I want a rematch when my BUG POKéMON\n"
	.string "grow up!\p"
	.string "I'm registering you in my POKéNAV!$"

PetalburgWoods_Text_MyPokemonHaveGrown::
# 88 "data/maps/PetalburgWoods/scripts.pory"
	.string "My BUG POKéMON have grown. I'll be\n"
	.string "popular again.$"

PetalburgWoods_Text_CantBePopularIfLose::
# 92 "data/maps/PetalburgWoods/scripts.pory"
	.string "I can't be popular if I lose.$"

PetalburgWoods_Text_IveBeenTrainingHard::
# 96 "data/maps/PetalburgWoods/scripts.pory"
	.string "You get to be popular if you have\n"
	.string "strong POKéMON, right?\l"
	.string "So, I've been training hard.$"

PetalburgWoods_Text_StayOutOfTallGrass::
# 100 "data/maps/PetalburgWoods/scripts.pory"
	.string "Yo, there! Your POKéMON doing okay?\p"
	.string "If your POKéMON are weak and you want\n"
	.string "to avoid battles, you should stay out\l"
	.string "of tall grass.$"

PetalburgWoods_Text_HiddenItemsExplanation::
# 104 "data/maps/PetalburgWoods/scripts.pory"
	.string "Sometimes, there are things on the\n"
	.string "ground even if you can't see them.\p"
	.string "That's why I always check where I'm\n"
	.string "walking.$"

PetalburgWoods_Text_TryUsingThisItem::
# 108 "data/maps/PetalburgWoods/scripts.pory"
	.string "Oh, neat! That's the BADGE from\n"
	.string "RUSTBORO GYM!\p"
	.string "You must be a TRAINER. You should try\n"
	.string "using this item.$"

PetalburgWoods_Text_MiracleSeedExplanation::
# 112 "data/maps/PetalburgWoods/scripts.pory"
	.string "It's a MIRACLE SEED. If a POKéMON holds\n"
	.string "that item, its\l"
	.string "GRASS-type moves become stronger.\p"
	.string "Besides MIRACLE SEED, I think there are\n"
	.string "other convenient items for POKéMON\l"
	.string "to hold.$"

PetalburgWoods_Text_TrainerTipsExperience::
# 116 "data/maps/PetalburgWoods/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Any POKéMON that appears even once in\n"
	.string "a battle is awarded EXP Points.\p"
	.string "To raise a weak POKéMON, put it at the\n"
	.string "left of the team list.\p"
	.string "As soon as a battle starts, switch it\n"
	.string "out. It will earn EXP Points without\l"
	.string "being exposed to any harm.$"

PetalburgWoods_Text_TrainerTipsPP::
# 120 "data/maps/PetalburgWoods/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "In addition to Hit Points (HP), POKéMON\n"
	.string "have Power Points (PP) that are used to\l"
	.string "make moves during battle.\p"
	.string "If a POKéMON runs out of PP, it must be\n"
	.string "taken to a POKéMON CENTER.$"
