FortreeCity_DecorationShop_MapScripts::
	.byte 0


FortreeCity_DecorationShop_EventScript_ClerkChairs::
	end


FortreeCity_DecorationShop_EventScript_ClerkDesks::
	end


FortreeCity_DecorationShop_EventScript_Girl::
# 13 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	msgbox FortreeCity_DecorationShop_Text_BuyingDeskForDolls, MSGBOX_NPC
	end


FortreeCity_DecorationShop_EventScript_PokefanM::
# 18 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	msgbox FortreeCity_DecorationShop_Text_MerchandiseSentToPC, MSGBOX_NPC
	end


FortreeCity_DecorationShop_Text_BuyingDeskForDolls::
# 22 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	.string "I'm buying a pretty desk and I'm\n"
	.string "putting my cute DOLLS on it.\p"
	.string "If I don't, when I decorate my\n"
	.string "SECRET BASE, my DOLLS will get\l"
	.string "dirty or poked with splinters.$"

FortreeCity_DecorationShop_Text_MerchandiseSentToPC::
# 26 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	.string "Merchandise you buy here is sent to\n"
	.string "your own PC.\p"
	.string "That's fantastic! I wish they could\n"
	.string "also deliver me home like that.$"
