FortreeCity_DecorationShop_MapScripts::
	.byte 0


FortreeCity_DecorationShop_Text_MerchandiseSentToPC::
# 5 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	.string "Merchandise you buy here is sent to\n"
	.string "your own PC.\p"
	.string "That's fantastic! I wish they could\n"
	.string "also deliver me home like that.$"

FortreeCity_DecorationShop_Text_BuyingDeskForDolls::
# 9 "data/maps/FortreeCity_DecorationShop/scripts.pory"
	.string "I'm buying a pretty desk and I'm putting\n"
	.string "my cute DOLLS on it.\p"
	.string "If I don't, when I decorate my SECRET\n"
	.string "BASE, my DOLLS will get\l"
	.string "dirty or poked with splinters.$"
