DragonsDen_Entrance_MapScripts::
	.byte 0


DragonsDen_Entrance_EventScript_SmithNPC1::
# 5 "data/maps/DragonsDen_Entrance/scripts.pory"
	msgbox DragonsDen_Entrance_Text_SmithNPC1, MSGBOX_NPC
	end


DragonsDen_Entrance_EventScript_SmithNPC2::
# 14 "data/maps/DragonsDen_Entrance/scripts.pory"
	msgbox DragonsDen_Entrance_Text_SmithNPC2, MSGBOX_NPC
	end


DragonsDen_Entrance_Text_SmithNPC1::
# 9 "data/maps/DragonsDen_Entrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

DragonsDen_Entrance_Text_SmithNPC2::
# 18 "data/maps/DragonsDen_Entrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
