FuchsiaCity_Mart_MapScripts::
	.byte 0


FuchsiaCity_Mart_EventScript_Clerk::
	end


FuchsiaCity_Mart_EventScript_CooltrainerF::
# 9 "data/maps/FuchsiaCity_Mart/scripts.pory"
	msgbox FuchsiaCity_Mart_Text_DidYouTryXSpeed, MSGBOX_NPC
	end


FuchsiaCity_Mart_EventScript_Gentleman::
# 14 "data/maps/FuchsiaCity_Mart/scripts.pory"
	msgbox FuchsiaCity_Mart_Text_DontTheyHaveSafariZonePennants, MSGBOX_NPC
	end


FuchsiaCity_Mart_Text_DidYouTryXSpeed::
# 19 "data/maps/FuchsiaCity_Mart/scripts.pory"
	.string "Did you try X SPEED?\n"
	.string "It speeds up a POKéMON in battle.$"

FuchsiaCity_Mart_Text_DontTheyHaveSafariZonePennants::
# 23 "data/maps/FuchsiaCity_Mart/scripts.pory"
	.string "Don't they have any pennants\n"
	.string "promoting the SAFARI ZONE?\p"
	.string "How about some paper lanterns?\n"
	.string "Aren't there even any calendars?$"
