FuchsiaCity_Mart_MapScripts::
	.byte 0


FuchsiaCity_Mart_Text_DontTheyHaveSafariZonePennants::
# 5 "data/maps/FuchsiaCity_Mart/scripts.pory"
	.string "Don't they have any pennants promoting\n"
	.string "the SAFARI ZONE?\p"
	.string "How about some paper lanterns? Aren't\n"
	.string "there even any calendars?$"

FuchsiaCity_Mart_Text_DidYouTryXSpeed::
# 9 "data/maps/FuchsiaCity_Mart/scripts.pory"
	.string "Did you try X SPEED? It speeds up a\n"
	.string "POKéMON in battle.$"
