Route16_NorthEntrance_2F_MapScripts::
	.byte 0


Route16_NorthEntrance_2F_EventScript_Aide::
	end


Route16_NorthEntrance_2F_EventScript_LeftBinoculars::
# 9 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	msgbox Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore, MSGBOX_SIGN
	end


Route16_NorthEntrance_2F_EventScript_LittleBoy::
# 14 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	msgbox Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend, MSGBOX_NPC
	end


Route16_NorthEntrance_2F_EventScript_LittleGirl::
# 19 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	msgbox Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes, MSGBOX_NPC
	end


Route16_NorthEntrance_2F_EventScript_RightBinoculars::
# 24 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	msgbox Route16_NorthEntrance_2F_Text_LongPathOverWater, MSGBOX_SIGN
	end


Route16_NorthEntrance_2F_Text_LongPathOverWater::
# 29 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "There's a long path over water far away.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
# 33 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "It's the CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
# 37 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "I'm on a relaxing ride on my new\n"
	.string "bike with my girlfriend.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
# 41 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "We're going riding together on our\n"
	.string "new bikes.$"
