Route16_NorthEntrance_2F_MapScripts::
	.byte 0


Route16_NorthEntrance_2F_Text_OnBikeRideWithGirlfriend::
# 5 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "I'm on a relaxing ride on my new bike\n"
	.string "with my girlfriend.$"

Route16_NorthEntrance_2F_Text_RidingTogetherOnNewBikes::
# 9 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "We're going riding together on our new\n"
	.string "bikes.$"

Route16_NorthEntrance_2F_Text_ItsCeladonDeptStore::
# 13 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "It's the CELADON DEPT. STORE!$"

Route16_NorthEntrance_2F_Text_LongPathOverWater::
# 17 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "There's a long path over water far away.$"

Route16_NorthEntrance_2F_Text_GiveAmuletCoinIfCaught40::
# 21 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Hi! Remember me? I'm one of PROF. OAK's\n"
	.string "AIDES.\p"
	.string "If your POKDEX has complete data on 40\n"
	.string "species, I'm supposed to\l"
	.string "give you a reward.\p"
	.string "PROF. OAK entrusted me with an AMULET\n"
	.string "COIN for you.\p"
	.string "So, {PLAYER}, let me ask you.\p"
	.string "Have you gathered data on at least 40\n"
	.string "kinds of POKMON?$"

Route16_NorthEntrance_2F_Text_GreatHereYouGo::
# 25 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "Great! You have caught or owned\n"
	.string "{STR_VAR_3} kinds of POKMON!\p"
	.string "Congratulations! Here you go!$"

Route16_NorthEntrance_2F_Text_ReceivedAmuletCoinFromAide::
# 29 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "{PLAYER} received the AMULET COIN\n"
	.string "from the AIDE.$"

Route16_NorthEntrance_2F_Text_ExplainAmuletCoin::
# 33 "data/maps/Route16_NorthEntrance_2F/scripts.pory"
	.string "An AMULET COIN is an item to be held by\n"
	.string "a POKMON.\p"
	.string "If the POKMON appears in a winning\n"
	.string "battle, you will earn more money.$"
