BattleFrontier_BattlePikeRoomWildMons_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePikeRoomWildMons_OnResume
# 3 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeRoomWildMons_OnFrame
# 4 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeRoomWildMons_OnWarp
	.byte 0


BattleFrontier_BattlePikeRoomWildMons_MapScripts::
# 8 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePikeRoomWildMons_OnResume
# 9 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeRoomWildMons_OnFrame
# 10 "data/maps/BattleFrontier_BattlePikeRoomWildMons/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeRoomWildMons_OnWarp
	return

