SafariZone_East_RestHouse_MapScripts::
	.byte 0


SafariZone_East_RestHouse_EventScript_BaldingMan::
# 5 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_TiredFromAllTheFun, MSGBOX_NPC
	end


SafariZone_East_RestHouse_EventScript_Rocker::
# 10 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_CaughtChanseyAllWorthwhile, MSGBOX_NPC
	end


SafariZone_East_RestHouse_EventScript_Scientist::
# 15 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_HowManyDidYouCatch, MSGBOX_NPC
	end


SafariZone_East_Text_TiredFromAllTheFun::
# 20 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "Whew!\n"
	.string "I'm tired from all the fun!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
# 24 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "I caught a CHANSEY!\p"
	.string "That makes this all worthwhile.$"

SafariZone_East_Text_HowManyDidYouCatch::
# 28 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "How many did you catch?\n"
	.string "I'm bushed from the effort!$"
