SafariZone_East_RestHouse_MapScripts::
	.byte 0


SafariZone_East_Text_HowManyDidYouCatch::
# 5 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "How many did you catch? I'm bushed from\n"
	.string "the effort!$"

SafariZone_East_Text_CaughtChanseyAllWorthwhile::
# 9 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "I caught a CHANSEY!\p"
	.string "That makes this all worthwhile.$"

SafariZone_East_Text_TiredFromAllTheFun::
# 13 "data/maps/SafariZone_East_RestHouse/scripts.pory"
	.string "Whew! I'm tired from all the fun!$"
