Route126_MapScripts::
	.byte 0


Route126_EventScript_Barry::
# 5 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_BARRY, Route126_Text_BarryIntro, Route126_Text_BarryDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_BarryPostBattle
	return


Route126_EventScript_Brenda::
# 10 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_BRENDA, Route126_Text_BrendaIntro, Route126_Text_BrendaDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_BrendaPostBattle
	return


Route126_EventScript_Dean::
# 15 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_DEAN, Route126_Text_DeanIntro, Route126_Text_DeanDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_DeanPostBattle
	return


Route126_EventScript_Isobel::
# 20 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_ISOBEL, Route126_Text_IsobelIntro, Route126_Text_IsobelDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_IsobelPostBattle
	return


Route126_EventScript_Leonardo::
# 25 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_LEONARDO, Route126_Text_LeonardoIntro, Route126_Text_LeonardoDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_LeonardoPostBattle
	return


Route126_EventScript_Nikki::
# 30 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_NIKKI, Route126_Text_NikkiIntro, Route126_Text_NikkiDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_NikkiPostBattle
	return


Route126_EventScript_Pablo::
# 35 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_PABLO, Route126_Text_PabloIntro, Route126_Text_PabloDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_PabloPostBattle
	return


Route126_EventScript_Sienna::
# 40 "data/maps/Route126/scripts.pory"
	trainerbattle_double TRAINER_SIENNA, Route126_Text_SiennaIntro, Route126_Text_SiennaDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route126/scripts.pory"
	msgbox Route126_Text_SiennaPostBattle
	return


Route126_Text_BarryDefeat::
# 46 "data/maps/Route126/scripts.pory"
	.string "I admit it! You win!$"

Route126_Text_BarryIntro::
# 50 "data/maps/Route126/scripts.pory"
	.string "Swimming is a full-body workout! You\n"
	.string "will get fit!$"

Route126_Text_BarryPostBattle::
# 54 "data/maps/Route126/scripts.pory"
	.string "Thanks to my daily swimming routine…\n"
	.string "Look! Feast your eyes on this physique!$"

Route126_Text_BrendaDefeat::
# 58 "data/maps/Route126/scripts.pory"
	.string "Oh, noooooh!$"

Route126_Text_BrendaIntro::
# 62 "data/maps/Route126/scripts.pory"
	.string "Hello, kiddo! Want a battle with me?$"

Route126_Text_BrendaPostBattle::
# 66 "data/maps/Route126/scripts.pory"
	.string "I love frolicking with POKéMON in the\n"
	.string "sea like this!$"

Route126_Text_DeanDefeat::
# 70 "data/maps/Route126/scripts.pory"
	.string "I was done in?$"

Route126_Text_DeanIntro::
# 74 "data/maps/Route126/scripts.pory"
	.string "This towering white mountain of rock is\n"
	.string "SOOTOPOLIS CITY.$"

Route126_Text_DeanPostBattle::
# 78 "data/maps/Route126/scripts.pory"
	.string "I can't find the entrance to\n"
	.string "SOOTOPOLIS. Where could it be?$"

Route126_Text_IsobelDefeat::
# 82 "data/maps/Route126/scripts.pory"
	.string "Ack! Why, you… Glub!$"

Route126_Text_IsobelIntro::
# 86 "data/maps/Route126/scripts.pory"
	.string "If seawater gets up your nose, doesn't\n"
	.string "it feel terrible?$"

Route126_Text_IsobelPostBattle::
# 90 "data/maps/Route126/scripts.pory"
	.string "Ooh, I choked on some water! It's\n"
	.string "bitter! It's salty!!$"

Route126_Text_LeonardoDefeat::
# 94 "data/maps/Route126/scripts.pory"
	.string "Sheesh, getting greedy didn't do a\n"
	.string "thing for me.$"

Route126_Text_LeonardoIntro::
# 98 "data/maps/Route126/scripts.pory"
	.string "I couldn't even swim last year, but now\n"
	.string "I'm a decent SWIMMER.\p"
	.string "I think I'm capable of anything now.$"

Route126_Text_LeonardoPostBattle::
# 102 "data/maps/Route126/scripts.pory"
	.string "If you practice at something, you will\n"
	.string "get better at it.\p"
	.string "You're young--don't be afraid to try all\n"
	.string "sorts of things!$"

Route126_Text_NikkiDefeat::
# 106 "data/maps/Route126/scripts.pory"
	.string "My fantasy burst as if it were a bubble!\n"
	.string "Blub, blub, blub…$"

Route126_Text_NikkiIntro::
# 110 "data/maps/Route126/scripts.pory"
	.string "Ufufufufu! I'm a mermaid!$"

Route126_Text_NikkiPostBattle::
# 114 "data/maps/Route126/scripts.pory"
	.string "You thrashed me… I want to disappear in\n"
	.string "a wave of despair…$"

Route126_Text_PabloDefeat::
# 118 "data/maps/Route126/scripts.pory"
	.string "Whoops! Too strong! Not bad! Not bad at\n"
	.string "all!$"

Route126_Text_PabloIntro::
# 122 "data/maps/Route126/scripts.pory"
	.string "Check out this sculpted body! I'm more\n"
	.string "cut than a BLACK BELT!$"

Route126_Text_PabloPostBattle::
# 126 "data/maps/Route126/scripts.pory"
	.string "Losing to you stimulated my senses! I'll\n"
	.string "train myself and POKéMON harder!$"

Route126_Text_SiennaDefeat::
# 130 "data/maps/Route126/scripts.pory"
	.string "You had more heart!$"

Route126_Text_SiennaIntro::
# 134 "data/maps/Route126/scripts.pory"
	.string "I'm throwing my whole heart into this!$"

Route126_Text_SiennaPostBattle::
# 138 "data/maps/Route126/scripts.pory"
	.string "I need to cool down now… I think I'll go\n"
	.string "for a dive.$"
