FuchsiaCity_MapScripts::
# 2 "data/maps/FuchsiaCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FuchsiaCity_OnTransition
	.byte 0


FuchsiaCity_Text_DidYouTrySafariGame::
# 6 "data/maps/FuchsiaCity/scripts.pory"
	.string "Did you try the SAFARI GAME?\p"
	.string "There are some rare POKMON that can\n"
	.string "only be caught there.$"

FuchsiaCity_Text_SafariZoneZooInFront::
# 10 "data/maps/FuchsiaCity/scripts.pory"
	.string "The SAFARI ZONE has a zoo in front of\n"
	.string "the entrance.\p"
	.string "Out back is the SAFARI GAME for\n"
	.string "catching POKMON.$"

FuchsiaCity_Text_WheresSara::
# 14 "data/maps/FuchsiaCity/scripts.pory"
	.string "ERIK: Where's SARA? I said I'd meet her\n"
	.string "here.$"

FuchsiaCity_Text_ItemBallInThere::
# 18 "data/maps/FuchsiaCity/scripts.pory"
	.string "That item ball in there Were you wanting\n"
	.string "that?\p"
	.string "Me, too! Huh? That's a POKMON?$"

FuchsiaCity_Text_CitySign::
# 22 "data/maps/FuchsiaCity/scripts.pory"
	.string "FUCHSIA CITY Behold! It's Passion Pink!$"

FuchsiaCity_Text_SafariZoneSign::
# 26 "data/maps/FuchsiaCity/scripts.pory"
	.string "POKMON PARADISE SAFARI ZONE$"

FuchsiaCity_Text_SafariGameSign::
# 30 "data/maps/FuchsiaCity/scripts.pory"
	.string "SAFARI GAME POKMON-U-CATCH!$"

FuchsiaCity_Text_WardensHomeSign::
# 34 "data/maps/FuchsiaCity/scripts.pory"
	.string "SAFARI ZONE WARDEN'S HOME$"

FuchsiaCity_Text_SafariZoneOfficeSign::
# 38 "data/maps/FuchsiaCity/scripts.pory"
	.string "POKMON PARADISE! Welcome to the\n"
	.string "SAFARI ZONE!\l"
	.string "SAFARI ZONE OFFICE$"

FuchsiaCity_Text_GymSign::
# 42 "data/maps/FuchsiaCity/scripts.pory"
	.string "FUCHSIA CITY POKMON GYM LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"

FuchsiaCity_Text_ChanseySign::
# 46 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: CHANSEY Catching one is all up to\n"
	.string "chance.$"

FuchsiaCity_Text_VoltorbSign::
# 50 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: VOLTORB The very image of a POK\n"
	.string "BALL.$"

FuchsiaCity_Text_KangaskhanSign::
# 54 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: KANGASKHAN\p"
	.string "A maternal POKMON that raises its young\n"
	.string "in a pouch on its belly.$"

FuchsiaCity_Text_SlowpokeSign::
# 58 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: SLOWPOKE Friendly and very slow\n"
	.string "moving.$"

FuchsiaCity_Text_LaprasSign::
# 62 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: LAPRAS AKA the king of the seas.$"

FuchsiaCity_Text_OmanyteSign::
# 66 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: OMANYTE An extremely rare POKMON\n"
	.string "that was\l"
	.string "regenerated from a fossil.$"

FuchsiaCity_Text_KabutoSign::
# 70 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: KABUTO An extremely rare POKMON\n"
	.string "that was\l"
	.string "regenerated from a fossil.$"

FuchsiaCity_Text_Ellipsis::
# 74 "data/maps/FuchsiaCity/scripts.pory"
	.string "$"

Text_SubstituteTeach::
# 78 "data/maps/FuchsiaCity/scripts.pory"
	.string "Aww, I wish I was a KANGASKHAN baby.\p"
	.string "I'd love to be a substitute for the baby\p"
	.string "And snuggle in the mother KANGASKHAN's\n"
	.string "belly pouch.\p"
	.string "But only POKMON can use the technique\n"
	.string "SUBSTITUTE\p"
	.string "Want me to teach SUBSTITUTE to one of\n"
	.string "your POKMON?$"

Text_SubstituteDeclined::
# 82 "data/maps/FuchsiaCity/scripts.pory"
	.string "Oh, really? SUBSTITUTE seems so fun$"

Text_SubstituteWhichMon::
# 86 "data/maps/FuchsiaCity/scripts.pory"
	.string "Which POKMON wants to learn\n"
	.string "SUBSTITUTE?$"

Text_SubstituteTaught::
# 90 "data/maps/FuchsiaCity/scripts.pory"
	.string "Boy, what I'd give to crawl inside a\n"
	.string "KANGASKHAN belly pouch$"

FuchsiaCity_Text_MyFatherIsGymLeader::
# 94 "data/maps/FuchsiaCity/scripts.pory"
	.string "My father is the GYM LEADER of this\n"
	.string "town.\p"
	.string "I'm training to use POISON POKMON as\n"
	.string "well as my father.$"
