FuchsiaCity_MapScripts::
	.byte 0


FuchsiaCity_EventScript_ChanseySign::
# 9 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_ChanseySign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_CitySign::
# 16 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_CitySign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_Erik::
# 21 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_WheresSara, MSGBOX_NPC
	end


FuchsiaCity_EventScript_FossilMonSign::
# 31 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_KabutoSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_GymSign::
# 40 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_GymSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_KangaskhanSign::
# 50 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_KangaskhanSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_LaprasSign::
# 61 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_LaprasSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_Lass::
	end


FuchsiaCity_EventScript_LittleBoy::
# 72 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_DidYouTrySafariGame, MSGBOX_NPC
	end


FuchsiaCity_EventScript_OldMan::
# 77 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_SafariZoneZooInFront, MSGBOX_NPC
	end


FuchsiaCity_EventScript_SafariGameSign::
# 82 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_SafariGameSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_SafariZoneSign::
# 87 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_SafariZoneSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_SlowpokeSign::
# 96 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_SlowpokeSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_VoltorbSign::
# 107 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_VoltorbSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_WardensHomeSign::
# 114 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_WardensHomeSign, MSGBOX_SIGN
	end


FuchsiaCity_EventScript_Youngster::
# 119 "data/maps/FuchsiaCity/scripts.pory"
	msgbox FuchsiaCity_Text_ItemBallInThere, MSGBOX_NPC
	end


FuchsiaCity_Text_VoltorbSign::
# 124 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: VOLTORB The very image of a POKé\n"
	.string "BALL.$"

FuchsiaCity_Text_KangaskhanSign::
# 128 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: KANGASKHAN\p"
	.string "A maternal POKéMON that raises its\n"
	.string "young in a pouch on its belly.$"

FuchsiaCity_Text_CitySign::
# 132 "data/maps/FuchsiaCity/scripts.pory"
	.string "FUCHSIA CITY Behold! It's Passion Pink!$"

FuchsiaCity_Text_GymSign::
# 136 "data/maps/FuchsiaCity/scripts.pory"
	.string "FUCHSIA CITY POKéMON GYM LEADER: KOGA\l"
	.string "The Poisonous Ninja Master$"

FuchsiaCity_Text_KabutoSign::
# 140 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: KABUTO An extremely rare POKéMON\n"
	.string "that was\l"
	.string "regenerated from a fossil.$"

FuchsiaCity_Text_LaprasSign::
# 144 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: LAPRAS AKA the king of the seas.$"

FuchsiaCity_Text_WardensHomeSign::
# 148 "data/maps/FuchsiaCity/scripts.pory"
	.string "SAFARI ZONE WARDEN'S HOME$"

FuchsiaCity_Text_SafariZoneSign::
# 152 "data/maps/FuchsiaCity/scripts.pory"
	.string "POKéMON PARADISE SAFARI ZONE$"

FuchsiaCity_Text_SlowpokeSign::
# 156 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: SLOWPOKE Friendly and very slow\n"
	.string "moving.$"

FuchsiaCity_Text_ChanseySign::
# 160 "data/maps/FuchsiaCity/scripts.pory"
	.string "Name: CHANSEY Catching one is all up to\n"
	.string "chance.$"

FuchsiaCity_Text_SafariGameSign::
# 164 "data/maps/FuchsiaCity/scripts.pory"
	.string "SAFARI GAME POKéMON-U-CATCH!$"

FuchsiaCity_Text_WheresSara::
# 168 "data/maps/FuchsiaCity/scripts.pory"
	.string "ERIK: Where's SARA?\n"
	.string "I said I'd meet her here.$"

FuchsiaCity_Text_DidYouTrySafariGame::
# 172 "data/maps/FuchsiaCity/scripts.pory"
	.string "Did you try the SAFARI GAME?\p"
	.string "There are some rare POKéMON that\n"
	.string "can only be caught there.$"

FuchsiaCity_Text_SafariZoneZooInFront::
# 176 "data/maps/FuchsiaCity/scripts.pory"
	.string "The SAFARI ZONE has a zoo in front\n"
	.string "of the entrance.\p"
	.string "Out back is the SAFARI GAME for\n"
	.string "catching POKéMON.$"

FuchsiaCity_Text_ItemBallInThere::
# 180 "data/maps/FuchsiaCity/scripts.pory"
	.string "That item ball in there…\n"
	.string "Were you wanting that?\p"
	.string "Me, too!\n"
	.string "…Huh? That's a POKéMON?$"
