MeteorFalls_StevensCave_MapScripts::
	.byte 0


MeteorFalls_StevensCave_MapScripts::
	return


MeteorFalls_StevensCave_Text_ShouldKnowHowGoodIAmExpectWorst::
# 8 "data/maps/MeteorFalls_StevensCave/scripts.pory"
	.string "STEVEN: Oh, wow, {PLAYER}{KUN}. I'm amazed\n"
	.string "you knew where to find me.\p"
	.string "Do you, uh…maybe think of me as just a\n"
	.string "rock maniac?\p"
	.string "No, that can't be right.\p"
	.string "We battled alongside each other at the\n"
	.string "SOOTOPOLIS SPACE CENTER.\p"
	.string "You should have a very good idea about\n"
	.string "how good I am.\p"
	.string "Okay, {PLAYER}{KUN}, if you're going to\n"
	.string "mount a serious challenge, expect the\l"
	.string "worst!$"

MeteorFalls_StevensCave_Text_StevenDefeat::
# 12 "data/maps/MeteorFalls_StevensCave/scripts.pory"
	.string "You… I had no idea you'd become so\n"
	.string "strong…$"

MeteorFalls_StevensCave_Text_MyPredictionCameTrue::
# 16 "data/maps/MeteorFalls_StevensCave/scripts.pory"
	.string "STEVEN: Come to think of it, ever since\n"
	.string "our paths first crossed in GRANITE\l"
	.string "CAVE in DEWFORD, I had this feeling.\p"
	.string "I thought that you would eventually\n"
	.string "become the CHAMPION.\p"
	.string "My predictions usually come true.\p"
	.string "And where will you go from here?\p"
	.string "… … … … … … … … … … … …\p"
	.string "Fufufu, even I couldn't tell you that.$"
