ThreeIsland_DunsparceTunnel_MapScripts::
# 2 "data/maps/ThreeIsland_DunsparceTunnel/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_DunsparceTunnel_OnTransition
	.byte 0


ThreeIsland_DunsparceTunnel_Text_ProspectingForGold::
# 6 "data/maps/ThreeIsland_DunsparceTunnel/scripts.pory"
	.string "Hey, there! How's it going?\p"
	.string "What am I doing here, you ask? Why, I'm\n"
	.string "prospecting for gold!\p"
	.string "When I strike it rich, I'm buying a house\n"
	.string "in KANTO.$"

ThreeIsland_DunsparceTunnel_Text_StruckGoldThisIsForYou::
# 10 "data/maps/ThreeIsland_DunsparceTunnel/scripts.pory"
	.string "Hey, there! How's it going? Did you\n"
	.string "hear? I've struck gold!\p"
	.string "You remembered that I was prospecting,\n"
	.string "didn't you?\p"
	.string "You can't begin to imagine just how\n"
	.string "happy I am.\p"
	.string "So, I'll show you! This is for you!$"

ThreeIsland_DunsparceTunnel_Text_ThatsANugget::
# 14 "data/maps/ThreeIsland_DunsparceTunnel/scripts.pory"
	.string "That's a NUGGET!\p"
	.string "I can't give you any nuggets of wisdom,\n"
	.string "so that'll have to do!$"

ThreeIsland_DunsparceTunnel_Text_WhoopsBagCrammedFull::
# 18 "data/maps/ThreeIsland_DunsparceTunnel/scripts.pory"
	.string "Whoops, your BAG is crammed full! I'll\n"
	.string "give this to you later.$"
