ThreeIsland_MapScripts::
# 2 "data/maps/ThreeIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_OnTransition
	.byte 0


ThreeIsland_Text_IslandSign::
# 6 "data/maps/ThreeIsland/scripts.pory"
	.string "THREE ISLAND Kin Island of Family\n"
	.string "Bonding$"

ThreeIsland_Text_IslandBelongsToUs::
# 10 "data/maps/ThreeIsland/scripts.pory"
	.string "Hyahoo!\p"
	.string "From this day on, this island belongs to\n"
	.string "us!$"

ThreeIsland_Text_GoBackToKanto::
# 14 "data/maps/ThreeIsland/scripts.pory"
	.string "We don't need you people bringing your\n"
	.string "noise and trouble here!\p"
	.string "We're asking you to go back to KANTO!$"

ThreeIsland_Text_BossIsOnHisWay::
# 18 "data/maps/ThreeIsland/scripts.pory"
	.string "Hey, go cry somewhere else. Our boss is\n"
	.string "on his way.\p"
	.string "When he gets here, we'll give you a k-rad\n"
	.string "motorbike show you won't\l"
	.string "soon forget!$"

ThreeIsland_Text_GetOffIslandNow::
# 22 "data/maps/ThreeIsland/scripts.pory"
	.string "W-what!? Not on your life! Get off the\n"
	.string "island now!$"

ThreeIsland_Text_WhosGonnaMakeMe::
# 26 "data/maps/ThreeIsland/scripts.pory"
	.string "Who's gonna make me?$"

ThreeIsland_Text_AreYouBossGoBackToKanto::
# 30 "data/maps/ThreeIsland/scripts.pory"
	.string "Are you the boss? Go back to KANTO\n"
	.string "right now!$"

ThreeIsland_Text_JustGotHerePal::
# 34 "data/maps/ThreeIsland/scripts.pory"
	.string "Hah?\p"
	.string "I just got here, pal.\p"
	.string "What's with the hostile attitude? It's\n"
	.string "mighty cold of you!$"

ThreeIsland_Text_FollowersRaisingHavoc::
# 38 "data/maps/ThreeIsland/scripts.pory"
	.string "Your gang of followers have been\n"
	.string "raising havoc on their bikes.\p"
	.string "Do you have any idea how much trouble\n"
	.string "they've caused us on the\l"
	.string "island?$"

ThreeIsland_Text_OughtToBeThankingUs::
# 42 "data/maps/ThreeIsland/scripts.pory"
	.string "No, man, I don't get it at all.\p"
	.string "Look at this place. What do you do for\n"
	.string "entertainment?\p"
	.string "You ought to be thanking us for\n"
	.string "livening up this sleepy village.\p"
	.string "But hey, if you insist, you can try\n"
	.string "making us leave.$"

ThreeIsland_Text_YouCowardsToughInPack::
# 46 "data/maps/ThreeIsland/scripts.pory"
	.string "Grr… You cowards… So tough in a pack…$"

ThreeIsland_Text_WannaMakeSomethingOfYourStaring::
# 50 "data/maps/ThreeIsland/scripts.pory"
	.string "You, what are you staring at? Don't you\n"
	.string "know it's not polite?\p"
	.string "You wanna make something of it or what?$"

ThreeIsland_Text_ThatsSmart::
# 54 "data/maps/ThreeIsland/scripts.pory"
	.string "That's smart. Keep your nose out of\n"
	.string "this.$"

ThreeIsland_Text_Biker1Intro::
# 58 "data/maps/ThreeIsland/scripts.pory"
	.string "Heh, I like your guts. You'll be losing\n"
	.string "money to me, but…$"

ThreeIsland_Text_Biker1Defeat::
# 62 "data/maps/ThreeIsland/scripts.pory"
	.string "Wha… What is this kid?!$"

ThreeIsland_Text_Biker1PostBattle::
# 66 "data/maps/ThreeIsland/scripts.pory"
	.string "Aww, man… Don't you dare laugh!$"

ThreeIsland_Text_Biker2Intro::
# 70 "data/maps/ThreeIsland/scripts.pory"
	.string "Aren't you from KANTO? You should be on\n"
	.string "our side!$"

ThreeIsland_Text_Biker2Defeat::
# 74 "data/maps/ThreeIsland/scripts.pory"
	.string "Stop fooling around!$"

ThreeIsland_Text_Biker2PostBattle::
# 78 "data/maps/ThreeIsland/scripts.pory"
	.string "What's the matter with you, getting all\n"
	.string "hot like that?\p"
	.string "Totally uncool, man!$"

ThreeIsland_Text_Biker3Intro::
# 82 "data/maps/ThreeIsland/scripts.pory"
	.string "We invited the boss out here, but you\n"
	.string "had to mess it up!\p"
	.string "You embarrassed us, man!$"

ThreeIsland_Text_Biker3Defeat::
# 86 "data/maps/ThreeIsland/scripts.pory"
	.string "… … … … … …$"

ThreeIsland_Text_Biker3PostBattle::
# 90 "data/maps/ThreeIsland/scripts.pory"
	.string "Boss, I'm telling you, you've gotta do\n"
	.string "something about this kid!$"

ThreeIsland_Text_PaxtonIntro::
# 94 "data/maps/ThreeIsland/scripts.pory"
	.string "I've been watching you, and I'd say\n"
	.string "you've done enough.\p"
	.string "What are you, their friend or\n"
	.string "something?\p"
	.string "Then I guess you'll be battling me in\n"
	.string "their place.$"

ThreeIsland_Text_PaxtonDefeat::
# 98 "data/maps/ThreeIsland/scripts.pory"
	.string "All right, enough! We'll leave like you\n"
	.string "wanted!\p"
	.string "We'll be happy to see the last of this\n"
	.string "boring island!$"

ThreeIsland_Text_PaxtonPostBattle::
# 102 "data/maps/ThreeIsland/scripts.pory"
	.string "Humph! Yeah, go right on hanging around\n"
	.string "with these hayseeds!$"

ThreeIsland_Text_ThankYouOhYourMonGotHurt::
# 106 "data/maps/ThreeIsland/scripts.pory"
	.string "Thank you! Those goons were nothing\n"
	.string "but bad trouble.\p"
	.string "Oh, look, your POKéMON got hurt on my\n"
	.string "account.$"

ThreeIsland_Text_GivenFullRestore::
# 110 "data/maps/ThreeIsland/scripts.pory"
	.string "{PLAYER} was given a FULL RESTORE.$"

ThreeIsland_Text_OhYourBagIsFull::
# 114 "data/maps/ThreeIsland/scripts.pory"
	.string "Oh? Your BAG is full.$"

ThreeIsland_Text_YouveGotImpressiveMons::
# 118 "data/maps/ThreeIsland/scripts.pory"
	.string "You've got seriously impressive\n"
	.string "POKéMON with you.$"

ThreeIsland_Text_LostelleWentOffTowardsBondBridge::
# 122 "data/maps/ThreeIsland/scripts.pory"
	.string "It'd be fantastic if someone as strong\n"
	.string "as you lived here.\p"
	.string "I hope you'll at least stay here a while.\p"
	.string "…I beg your pardon? You're looking for\n"
	.string "LOSTELLE?\p"
	.string "LOSTELLE went off towards BOND BRIDGE\n"
	.string "a while ago.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
# 126 "data/maps/ThreeIsland/scripts.pory"
	.string "THREE ISLAND is actually the most\n"
	.string "populous of the islands here.\p"
	.string "Still, it could be less sleepy.\p"
	.string "But I wouldn't want to see goons like\n"
	.string "those BIKERS here again.$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
# 130 "data/maps/ThreeIsland/scripts.pory"
	.string "I'm going to train my DODUO in the BERRY\n"
	.string "FOREST.\p"
	.string "When it evolves, I'm going to play a game\n"
	.string "on TWO ISLAND.$"

ThreeIsland_Text_Doduo::
# 134 "data/maps/ThreeIsland/scripts.pory"
	.string "DODUO: Gigiih!$"
