ThreeIsland_MapScripts::
	.byte 0


ThreeIsland_EventScript_AntiBiker1::
	end


ThreeIsland_EventScript_AntiBiker2::
	end


ThreeIsland_EventScript_BattleBikersTriggerLeft::
	end


ThreeIsland_EventScript_BattleBikersTriggerMid::
	end


ThreeIsland_EventScript_BattleBikersTriggerMidLeft::
	end


ThreeIsland_EventScript_BattleBikersTriggerMidRight::
	end


ThreeIsland_EventScript_BattleBikersTriggerRight::
	end


ThreeIsland_EventScript_Biker::
	end


ThreeIsland_EventScript_Biker6::
# 37 "data/maps/ThreeIsland/scripts.pory"
	msgbox ThreeIsland_Text_IslandBelongsToUs, MSGBOX_NPC
	end


ThreeIsland_EventScript_BikerBossIntroTrigger::
	end


ThreeIsland_EventScript_Doduo::
	end


ThreeIsland_EventScript_IslandSign::
# 50 "data/maps/ThreeIsland/scripts.pory"
	msgbox ThreeIsland_Text_IslandSign, MSGBOX_SIGN
	end


ThreeIsland_EventScript_LittleBoy::
# 55 "data/maps/ThreeIsland/scripts.pory"
	msgbox ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame, MSGBOX_NPC
	end


ThreeIsland_EventScript_Woman::
# 60 "data/maps/ThreeIsland/scripts.pory"
	msgbox ThreeIsland_Text_WouldntWantToSeeBikersHereAgain, MSGBOX_NPC
	end


ThreeIsland_Text_IslandSign::
# 65 "data/maps/ThreeIsland/scripts.pory"
	.string "THREE ISLAND Kin Island of Family\n"
	.string "Bonding$"

ThreeIsland_Text_IslandBelongsToUs::
# 69 "data/maps/ThreeIsland/scripts.pory"
	.string "Hyahoo!\p"
	.string "From this day on, this island\n"
	.string "belongs to us!$"

ThreeIsland_Text_WhenDodouEvolvesGoingToPlayGame::
# 73 "data/maps/ThreeIsland/scripts.pory"
	.string "I'm going to train my DODUO in the\n"
	.string "BERRY FOREST.\p"
	.string "When it evolves, I'm going to play\n"
	.string "a game on TWO ISLAND.$"

ThreeIsland_Text_WouldntWantToSeeBikersHereAgain::
# 77 "data/maps/ThreeIsland/scripts.pory"
	.string "THREE ISLAND is actually the most\n"
	.string "populous of the islands here.\p"
	.string "Still, it could be less sleepy.\p"
	.string "But I wouldn't want to see goons\n"
	.string "like those BIKERS here again.$"
