SlateportCity_PokemonFanClub_MapScripts::
	.byte 0


SlateportCity_PokemonFanClub_Text_MeetChairman::
# 5 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Er-hem! I am the CHAIRMAN of the\n"
	.string "POKMON FAN CLUB!\p"
	.string "Being the CHAIRMAN, I am naturally the\n"
	.string "most important!\p"
	.string "No one can best me when it comes to\n"
	.string "raising POKMON. No one!\p"
	.string "Well, let me tell you about POKMON\n"
	.string "CONTESTS.\p"
	.string "They're events where one can show off\n"
	.string "POKMON for the world to see!\p"
	.string "However, they're held in far-off towns,\n"
	.string "so I cannot participate often enough.\p"
	.string "That is why we gather here to show off\n"
	.string "our POKMON, and have others\l"
	.string "show us theirs.$"

SlateportCity_PokemonFanClub_Text_LikeToSeeEnteredContestPokemon::
# 9 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "The POKMON of a TRAINER who has\n"
	.string "entered a POKMON CONTEST\l"
	.string "That, I would like to see.$"

SlateportCity_PokemonFanClub_Text_AllowMeToExamineYourPokemon::
# 13 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Er-hem! I see you've participated in a\n"
	.string "POKMON CONTEST!\p"
	.string "Please! Allow me to examine how you\n"
	.string "have raised your POKMON.\p"
	.string "It delights me no end to see POKMON\n"
	.string "raised by other TRAINERS.\p"
	.string "The happy expressions of POKMON raised\n"
	.string "with proper care\p"
	.string "The kindly eyes of the TRAINER that\n"
	.string "nurtured and raised the POKMON\p"
	.string "The very thought fills my heart to\n"
	.string "overwhelming with joy.\p"
	.string "Oh! I do beg your pardon! Forgive me for\n"
	.string "prattling on so!\p"
	.string "Please! Allow me to examine how much\n"
	.string "your POKMON has grown!$"

SlateportCity_PokemonFanClub_Text_HowIsYourPokemonGrowing::
# 17 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "How is your POKMON growing? Allow me to\n"
	.string "examine it.$"

SlateportCity_PokemonFanClub_Text_HmHmISee::
# 21 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Hm, hm I see$"

SlateportCity_PokemonFanClub_Text_GiveMonMorePokeblocks::
# 25 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Hmmm It's not bad, but it's not good,\n"
	.string "either\p"
	.string "You, the TRAINER, must put more effort\n"
	.string "into raising this POKMON!\p"
	.string "For instance, may I suggest that you\n"
	.string "give it more {POKEBLOCK}S?$"

SlateportCity_PokemonFanClub_Text_NoSpaceForReward::
# 29 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Oh, my\p"
	.string "Your POKMON is growing quite well, so\n"
	.string "you deserve a reward.\p"
	.string "Unfortunately, you have no space for\n"
	.string "this in your BAG.$"

SlateportCity_PokemonFanClub_Text_MonMostImpressiveGiveItThis::
# 33 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Your {STR_VAR_1}, it is growing in a\n"
	.string "most impressive manner!\l"
	.string "It is one fine specimen!\p"
	.string "But! If you were to give it this, it\n"
	.string "would grow even better! Indeed!$"

SlateportCity_PokemonFanClub_Text_ExplainRedScarf::
# 37 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKMON hold that RED SCARF.\p"
	.string "Everyone will recognize the coolness of\n"
	.string "that POKMON!$"

SlateportCity_PokemonFanClub_Text_ExplainBlueScarf::
# 41 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKMON hold that BLUE SCARF.\p"
	.string "Its beauty will be accentuated much\n"
	.string "more than now!$"

SlateportCity_PokemonFanClub_Text_ExplainPinkScarf::
# 45 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKMON hold that PINK SCARF.\p"
	.string "It will draw out the cuteness of the\n"
	.string "POKMON some more!$"

SlateportCity_PokemonFanClub_Text_ExplainGreenScarf::
# 49 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKMON hold that GREEN SCARF.\p"
	.string "That will enhance the smartness of\n"
	.string "POKMON!$"

SlateportCity_PokemonFanClub_Text_ExplainYellowScarf::
# 53 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKMON hold that YELLOW SCARF.\p"
	.string "It will bolster your POKMON's toughness\n"
	.string "so much more!$"

SlateportCity_PokemonFanClub_Text_NothingElseToGiveYou::
# 57 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "I'm sorry, but I've nothing else to give\n"
	.string "you! None at all!\p"
	.string "After all, you're blessed with the gift\n"
	.string "of raising POKMON without resorting\l"
	.string "to any items!$"

SlateportCity_PokemonFanClub_Text_ShowMePokemonThatLoveYou::
# 61 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "I love seeing POKMON that love their\n"
	.string "TRAINERS.\p"
	.string "POKMON are very sensitive to the\n"
	.string "feelings of their TRAINERS.\p"
	.string "If you treat your POKMON with love and\n"
	.string "care, they'll love you back.\p"
	.string "When your POKMON grow to love you,\n"
	.string "please come show me.$"

SlateportCity_PokemonFanClub_Text_PokemonAdoresYou::
# 65 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Your POKMON really adores you.\p"
	.string "For you, a most compassionate TRAINER,\n"
	.string "a gift from the FAN CLUB!$"

SlateportCity_PokemonFanClub_Text_TreatPokemonWithLove::
# 69 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "POKMON are very sensitive to the\n"
	.string "feelings of their TRAINERS.\p"
	.string "If you treat your POKMON with love and\n"
	.string "care, they'll love you back.$"

SlateportCity_PokemonFanClub_Text_PokemonDontLikeFainting::
# 73 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "If you keep letting a POKMON faint in\n"
	.string "battle, it'll come to resent it.\p"
	.string "Soon, it will become less trusting of\n"
	.string "the TRAINER.\p"
	.string "In other words, it certainly won't like\n"
	.string "you very much.$"

SlateportCity_PokemonFanClub_Text_MonEnjoyedProtein::
# 77 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Do POKMON enjoy having items used on\n"
	.string "them?\p"
	.string "Mine acted really happy when I gave it\n"
	.string "some PROTEIN.$"

SlateportCity_PokemonFanClub_Text_Skitty::
# 81 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "SKITTY: Fffnyaaaah$"

SlateportCity_PokemonFanClub_Text_Zigzagoon::
# 85 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "ZIGZAGOON: Kyuuu$"

SlateportCity_PokemonFanClub_Text_Azumarill::
# 89 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "AZUMARILL: Marimari?$"
