SlateportCity_PokemonFanClub_MapScripts::
	.byte 0


SlateportCity_PokemonFanClub_MapScripts::
	return


SlateportCity_PokemonFanClub_Text_MeetChairman::
# 8 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Er-hem! I am the CHAIRMAN of the\n"
	.string "POKéMON FAN CLUB!\p"
	.string "Being the CHAIRMAN, I am naturally the\n"
	.string "most important!\p"
	.string "No one can best me when it comes to\n"
	.string "raising POKéMON. No one!\p"
	.string "Well, let me tell you about POKéMON\n"
	.string "CONTESTS.\p"
	.string "They're events where one can show off\n"
	.string "POKéMON for the world to see!\p"
	.string "However, they're held in far-off towns,\n"
	.string "so I cannot participate often enough.\p"
	.string "That is why we gather here to show off\n"
	.string "our POKéMON, and have others\l"
	.string "show us theirs.$"

SlateportCity_PokemonFanClub_Text_LikeToSeeEnteredContestPokemon::
# 12 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "The POKéMON of a TRAINER who has\n"
	.string "entered a POKéMON CONTEST…\l"
	.string "That, I would like to see.$"

SlateportCity_PokemonFanClub_Text_AllowMeToExamineYourPokemon::
# 16 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Er-hem! I see you've participated in a\n"
	.string "POKéMON CONTEST!\p"
	.string "Please! Allow me to examine how you\n"
	.string "have raised your POKéMON.\p"
	.string "It delights me no end to see POKéMON\n"
	.string "raised by other TRAINERS.\p"
	.string "The happy expressions of POKéMON\n"
	.string "raised with proper care…\p"
	.string "The kindly eyes of the TRAINER that\n"
	.string "nurtured and raised the POKéMON…\p"
	.string "The very thought fills my heart to\n"
	.string "overwhelming with joy.\p"
	.string "Oh! I do beg your pardon! Forgive me for\n"
	.string "prattling on so!\p"
	.string "Please! Allow me to examine how much\n"
	.string "your POKéMON has grown!$"

SlateportCity_PokemonFanClub_Text_HowIsYourPokemonGrowing::
# 20 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "How is your POKéMON growing? Allow me\n"
	.string "to examine it.$"

SlateportCity_PokemonFanClub_Text_HmHmISee::
# 24 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Hm, hm… I see…$"

SlateportCity_PokemonFanClub_Text_GiveMonMorePokeblocks::
# 28 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Hmmm… It's not bad, but it's not good,\n"
	.string "either…\p"
	.string "You, the TRAINER, must put more effort\n"
	.string "into raising this POKéMON!\p"
	.string "For instance, may I suggest that you\n"
	.string "give it more {POKEBLOCK}S?$"

SlateportCity_PokemonFanClub_Text_NoSpaceForReward::
# 32 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Oh, my…\p"
	.string "Your POKéMON is growing quite well, so\n"
	.string "you deserve a reward.\p"
	.string "Unfortunately, you have no space for\n"
	.string "this in your BAG.$"

SlateportCity_PokemonFanClub_Text_MonMostImpressiveGiveItThis::
# 36 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Your {STR_VAR_1}, it is growing in a\n"
	.string "most impressive manner!\l"
	.string "It is one fine specimen!\p"
	.string "But! If you were to give it this, it\n"
	.string "would grow even better! Indeed!$"

SlateportCity_PokemonFanClub_Text_ExplainRedScarf::
# 40 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKéMON hold that RED SCARF.\p"
	.string "Everyone will recognize the coolness of\n"
	.string "that POKéMON!$"

SlateportCity_PokemonFanClub_Text_ExplainBlueScarf::
# 44 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKéMON hold that BLUE SCARF.\p"
	.string "Its beauty will be accentuated much\n"
	.string "more than now!$"

SlateportCity_PokemonFanClub_Text_ExplainPinkScarf::
# 48 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKéMON hold that PINK SCARF.\p"
	.string "It will draw out the cuteness of the\n"
	.string "POKéMON some more!$"

SlateportCity_PokemonFanClub_Text_ExplainGreenScarf::
# 52 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKéMON hold that GREEN SCARF.\p"
	.string "That will enhance the smartness of\n"
	.string "POKéMON!$"

SlateportCity_PokemonFanClub_Text_ExplainYellowScarf::
# 56 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Let a POKéMON hold that YELLOW SCARF.\p"
	.string "It will bolster your POKéMON's\n"
	.string "toughness so much more!$"

SlateportCity_PokemonFanClub_Text_NothingElseToGiveYou::
# 60 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "I'm sorry, but I've nothing else to give\n"
	.string "you! None at all!\p"
	.string "After all, you're blessed with the gift\n"
	.string "of raising POKéMON without resorting\l"
	.string "to any items!$"

SlateportCity_PokemonFanClub_Text_ShowMePokemonThatLoveYou::
# 64 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "I love seeing POKéMON that love their\n"
	.string "TRAINERS.\p"
	.string "POKéMON are very sensitive to the\n"
	.string "feelings of their TRAINERS.\p"
	.string "If you treat your POKéMON with love and\n"
	.string "care, they'll love you back.\p"
	.string "When your POKéMON grow to love you,\n"
	.string "please come show me.$"

SlateportCity_PokemonFanClub_Text_PokemonAdoresYou::
# 68 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Your POKéMON really adores you.\p"
	.string "For you, a most compassionate TRAINER,\n"
	.string "a gift from the FAN CLUB!$"

SlateportCity_PokemonFanClub_Text_TreatPokemonWithLove::
# 72 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "POKéMON are very sensitive to the\n"
	.string "feelings of their TRAINERS.\p"
	.string "If you treat your POKéMON with love and\n"
	.string "care, they'll love you back.$"

SlateportCity_PokemonFanClub_Text_PokemonDontLikeFainting::
# 76 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "If you keep letting a POKéMON faint in\n"
	.string "battle, it'll come to resent it.\p"
	.string "Soon, it will become less trusting of\n"
	.string "the TRAINER.\p"
	.string "In other words, it certainly won't like\n"
	.string "you very much.$"

SlateportCity_PokemonFanClub_Text_MonEnjoyedProtein::
# 80 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "Do POKéMON enjoy having items used on\n"
	.string "them?\p"
	.string "Mine acted really happy when I gave it\n"
	.string "some PROTEIN.$"

SlateportCity_PokemonFanClub_Text_Skitty::
# 84 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "SKITTY: Fffnyaaaah…$"

SlateportCity_PokemonFanClub_Text_Zigzagoon::
# 88 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "ZIGZAGOON: Kyuuu…$"

SlateportCity_PokemonFanClub_Text_Azumarill::
# 92 "data/maps/SlateportCity_PokemonFanClub/scripts.pory"
	.string "AZUMARILL: Marimari?$"
