RustboroCity_Flat1_1F_MapScripts::
	.byte 0


RustboroCity_Flat1_1F_EventScript_Man::
# 5 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility, MSGBOX_NPC
	end


RustboroCity_Flat1_1F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	msgbox RustboroCity_Flat1_1F_Text_PokemonStrange, MSGBOX_NPC
	end


RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility::
# 14 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "Every POKéMON has a special ability\n"
	.string "that it can use.$"

RustboroCity_Flat1_1F_Text_PokemonStrange::
# 18 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "POKéMON are such strange creatures.$"
