RustboroCity_Flat1_1F_MapScripts::
	.byte 0


RustboroCity_Flat1_1F_MapScripts::
	return


RustboroCity_Flat1_1F_Text_EveryPokemonHasAbility::
# 8 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "Every POKéMON has a special ability\n"
	.string "that it can use.$"

RustboroCity_Flat1_1F_Text_PokemonStrange::
# 12 "data/maps/RustboroCity_Flat1_1F/scripts.pory"
	.string "POKéMON are such strange creatures.$"
