SootopolisCity_House5_MapScripts::
	.byte 0


SootopolisCity_House5_MapScripts::
	return


SootopolisCity_House5_Text_SootopolisMtPyreConnection::
# 8 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "There appears to be some connection\n"
	.string "between SOOTOPOLIS and MT. PYRE.\p"
	.string "My friends and I did some research on it\n"
	.string "at the lab where I used to work.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea::
# 12 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "My big brother used to study the sea.$"
