SootopolisCity_House5_MapScripts::
	.byte 0


SootopolisCity_House5_EventScript_Girl::
# 5 "data/maps/SootopolisCity_House5/scripts.pory"
	msgbox SootopolisCity_House5_Text_BrotherUsedToStudySea, MSGBOX_NPC
	end


SootopolisCity_House5_EventScript_Maniac::
# 10 "data/maps/SootopolisCity_House5/scripts.pory"
	msgbox SootopolisCity_House5_Text_SootopolisMtPyreConnection, MSGBOX_NPC
	end


SootopolisCity_House5_Text_SootopolisMtPyreConnection::
# 14 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "There appears to be some connection\n"
	.string "between SOOTOPOLIS and MT. PYRE.\p"
	.string "My friends and I did some research on\n"
	.string "it at the lab where I used to work.$"

SootopolisCity_House5_Text_BrotherUsedToStudySea::
# 18 "data/maps/SootopolisCity_House5/scripts.pory"
	.string "My big brother used to study the sea.$"
