FortreeCity_Mart_MapScripts::
	.byte 0


FortreeCity_Mart_Text_SuperRepelBetter::
# 5 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "SUPER REPEL lasts a long time, and it\n"
	.string "gets the job done.\p"
	.string "It's much better than an ordinary\n"
	.string "REPEL.$"

FortreeCity_Mart_Text_StockUpOnItems::
# 9 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "I always stock up on more items than I'm\n"
	.string "sure I'll need.\p"
	.string "You never know what might happen.\n"
	.string "Better to be safe than sorry!$"

FortreeCity_Mart_Text_RareCandyMakesMonGrow::
# 13 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "A RARE CANDY makes a POKéMON grow\n"
	.string "immediately by one level.$"
