FortreeCity_Mart_MapScripts::
	.byte 0


FortreeCity_Mart_EventScript_Boy::
# 5 "data/maps/FortreeCity_Mart/scripts.pory"
	msgbox FortreeCity_Mart_Text_RareCandyMakesMonGrow, MSGBOX_NPC
	end


FortreeCity_Mart_EventScript_Clerk::
	end


FortreeCity_Mart_EventScript_Girl::
# 14 "data/maps/FortreeCity_Mart/scripts.pory"
	msgbox FortreeCity_Mart_Text_StockUpOnItems, MSGBOX_NPC
	end


FortreeCity_Mart_EventScript_Woman::
# 19 "data/maps/FortreeCity_Mart/scripts.pory"
	msgbox FortreeCity_Mart_Text_SuperRepelBetter, MSGBOX_NPC
	end


FortreeCity_Mart_Text_RareCandyMakesMonGrow::
# 23 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "A RARE CANDY makes a POKéMON grow\n"
	.string "immediately by one level.$"

FortreeCity_Mart_Text_SuperRepelBetter::
# 27 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "SUPER REPEL lasts a long time,\n"
	.string "and it gets the job done.\p"
	.string "It's much better than an ordinary\n"
	.string "REPEL.$"

FortreeCity_Mart_Text_StockUpOnItems::
# 31 "data/maps/FortreeCity_Mart/scripts.pory"
	.string "I always stock up on more items than\n"
	.string "I'm sure I'll need.\p"
	.string "You never know what might happen.\n"
	.string "Better to be safe than sorry!$"
