MossdeepCity_House1_MapScripts::
	.byte 0


MossdeepCity_House1_MapScripts::
	return


MossdeepCity_House1_Text_HmmYourPokemon::
# 8 "data/maps/MossdeepCity_House1/scripts.pory"
	.string "Hmm! Your {STR_VAR_1}…$"

MossdeepCity_House1_Text_ItLikesXPokeblocks::
# 12 "data/maps/MossdeepCity_House1/scripts.pory"
	.string "It likes {STR_VAR_1}S, doesn't it?\p"
	.string "No, I'm positive of it! It definitely\n"
	.string "likes {STR_VAR_1}S!$"

MossdeepCity_House1_Text_DoesntLikeOrDislikePokeblocks::
# 16 "data/maps/MossdeepCity_House1/scripts.pory"
	.string "It doesn't appear to like or dislike any\n"
	.string "{POKEBLOCK}S.$"

MossdeepCity_House1_Text_HusbandCanTellPokeblockMonLikes::
# 20 "data/maps/MossdeepCity_House1/scripts.pory"
	.string "My husband can tell what kind of\n"
	.string "{POKEBLOCK}S a POKéMON likes at a glance.$"
