CinnabarIsland_PokemonLab_Entrance_MapScripts::
# 2 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CinnabarIsland_PokemonLab_Entrance_OnTransition
	.byte 0


CinnabarIsland_PokemonLab_Entrance_MapScripts::
# 6 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CinnabarIsland_PokemonLab_Entrance_OnTransition
	return

