CinnabarIsland_PokemonLab_Entrance_MapScripts::
	.byte 0


CinnabarIsland_PokemonLab_Entrance_EventScript_DrFujiPhoto::
# 5 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_Entrance_EventScript_MeetingRoomSign::
# 10 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_Entrance_EventScript_RAndDRoomSign::
# 15 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_Entrance_EventScript_Scientist::
# 20 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively, MSGBOX_NPC
	end


CinnabarIsland_PokemonLab_Entrance_EventScript_TestingRoomSign::
# 25 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
# 30 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB Testing Room$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
# 34 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
# 38 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB R & D Room$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
# 42 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "A photo of the LAB's founder… DR.\n"
	.string "FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
# 46 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "We study POKéMON extensively\n"
	.string "every day.\p"
	.string "People often bring us rare POKéMON\n"
	.string "for examination.$"
