CinnabarIsland_PokemonLab_Entrance_MapScripts::
# 2 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CinnabarIsland_PokemonLab_Entrance_OnTransition
	.byte 0


CinnabarIsland_Gym_Text_PhotoOfBlaineAndFuji::
# 6 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "It's a photo of BLAINE and MR. FUJI.\p"
	.string "They're standing shoulder to shoulder\n"
	.string "with big grins.$"

CinnabarIsland_PokemonLab_Entrance_Text_StudyMonsExtensively::
# 10 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "We study POKéMON extensively every\n"
	.string "day.\p"
	.string "People often bring us rare POKéMON for\n"
	.string "examination.$"

CinnabarIsland_PokemonLab_Entrance_Text_PhotoOfLabFounderDrFuji::
# 14 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "A photo of the LAB's founder… DR.\n"
	.string "FUJI?!$"

CinnabarIsland_PokemonLab_Entrance_Text_MeetingRoomSign::
# 18 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB Meeting Room$"

CinnabarIsland_PokemonLab_Entrance_Text_RAndDRoomSign::
# 22 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB R & D Room$"

CinnabarIsland_PokemonLab_Entrance_Text_TestingRoomSign::
# 26 "data/maps/CinnabarIsland_PokemonLab_Entrance/scripts.pory"
	.string "POKéMON LAB Testing Room$"
