MtMoon_1F_MapScripts::
	.byte 0


MtMoon_1F_EventScript_Iris::
# 5 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_LASS_IRIS, MtMoon_1F_Text_IrisIntro, MtMoon_1F_Text_IrisDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_IrisPostBattle
	return


MtMoon_1F_EventScript_Josh::
# 10 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_YOUNGSTER_JOSH, MtMoon_1F_Text_JoshIntro, MtMoon_1F_Text_JoshDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_JoshPostBattle
	return


MtMoon_1F_EventScript_Jovan::
# 15 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_SUPER_NERD_JOVAN, MtMoon_1F_Text_JovanIntro, MtMoon_1F_Text_JovanDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_JovanPostBattle
	return


MtMoon_1F_EventScript_Kent::
# 20 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_BUG_CATCHER_KENT, MtMoon_1F_Text_KentIntro, MtMoon_1F_Text_KentDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_KentPostBattle
	return


MtMoon_1F_EventScript_Marcos::
# 25 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_MARCOS, MtMoon_1F_Text_MarcosIntro, MtMoon_1F_Text_MarcosDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_MarcosPostBattle
	return


MtMoon_1F_EventScript_Miriam::
# 30 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_LASS_MIRIAM, MtMoon_1F_Text_MiriamIntro, MtMoon_1F_Text_MiriamDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_MiriamPostBattle
	return


MtMoon_1F_EventScript_Robby::
# 35 "data/maps/MtMoon_1F/scripts.pory"
	trainerbattle_double TRAINER_BUG_CATCHER_ROBBY, MtMoon_1F_Text_RobbyIntro, MtMoon_1F_Text_RobbyDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_RobbyPostBattle
	return


MtMoon_1F_EventScript_ZubatSign::
# 40 "data/maps/MtMoon_1F/scripts.pory"
	msgbox MtMoon_1F_Text_ZubatIsABloodsucker, MSGBOX_SIGN
	end


MtMoon_1F_Text_ZubatIsABloodsucker::
# 45 "data/maps/MtMoon_1F/scripts.pory"
	.string "Beware! ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_IrisDefeat::
# 50 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_IrisDefeat$"

MtMoon_1F_Text_IrisIntro::
# 54 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_IrisIntro$"

MtMoon_1F_Text_IrisPostBattle::
# 58 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_IrisPostBattle$"

MtMoon_1F_Text_JoshDefeat::
# 62 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JoshDefeat$"

MtMoon_1F_Text_JoshIntro::
# 66 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JoshIntro$"

MtMoon_1F_Text_JoshPostBattle::
# 70 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JoshPostBattle$"

MtMoon_1F_Text_JovanDefeat::
# 74 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JovanDefeat$"

MtMoon_1F_Text_JovanIntro::
# 78 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JovanIntro$"

MtMoon_1F_Text_JovanPostBattle::
# 82 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_JovanPostBattle$"

MtMoon_1F_Text_KentDefeat::
# 86 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_KentDefeat$"

MtMoon_1F_Text_KentIntro::
# 90 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_KentIntro$"

MtMoon_1F_Text_KentPostBattle::
# 94 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_KentPostBattle$"

MtMoon_1F_Text_MarcosDefeat::
# 98 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MarcosDefeat$"

MtMoon_1F_Text_MarcosIntro::
# 102 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MarcosIntro$"

MtMoon_1F_Text_MarcosPostBattle::
# 106 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MarcosPostBattle$"

MtMoon_1F_Text_MiriamDefeat::
# 110 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MiriamDefeat$"

MtMoon_1F_Text_MiriamIntro::
# 114 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MiriamIntro$"

MtMoon_1F_Text_MiriamPostBattle::
# 118 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_MiriamPostBattle$"

MtMoon_1F_Text_RobbyDefeat::
# 122 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_RobbyDefeat$"

MtMoon_1F_Text_RobbyIntro::
# 126 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_RobbyIntro$"

MtMoon_1F_Text_RobbyPostBattle::
# 130 "data/maps/MtMoon_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtMoon_1F_Text_RobbyPostBattle$"
