MtMoon_1F_MapScripts::
# 2 "data/maps/MtMoon_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtMoon_1F_OnTransition
	.byte 0


MtMoon_1F_Text_MarcosIntro::
# 6 "data/maps/MtMoon_1F/scripts.pory"
	.string "WHOA! You shocked me!\l"
	.string "…Oh, you're just a kid!$"

MtMoon_1F_Text_MarcosDefeat::
# 10 "data/maps/MtMoon_1F/scripts.pory"
	.string "Wow! Shocked again!$"

MtMoon_1F_Text_MarcosPostBattle::
# 14 "data/maps/MtMoon_1F/scripts.pory"
	.string "Kids like you shouldn't be wandering\n"
	.string "around here in the dark.$"

MtMoon_1F_Text_JoshIntro::
# 18 "data/maps/MtMoon_1F/scripts.pory"
	.string "Did you come to explore the cave, too?$"

MtMoon_1F_Text_JoshDefeat::
# 22 "data/maps/MtMoon_1F/scripts.pory"
	.string "Losing stinks! It's so uncool.$"

MtMoon_1F_Text_JoshPostBattle::
# 26 "data/maps/MtMoon_1F/scripts.pory"
	.string "I came all the way down here to show off\n"
	.string "to girls.$"

MtMoon_1F_Text_MiriamIntro::
# 30 "data/maps/MtMoon_1F/scripts.pory"
	.string "Wow! It's way bigger in here than I\n"
	.string "thought!$"

MtMoon_1F_Text_MiriamDefeat::
# 34 "data/maps/MtMoon_1F/scripts.pory"
	.string "Oh! I lost it!$"

MtMoon_1F_Text_MiriamPostBattle::
# 38 "data/maps/MtMoon_1F/scripts.pory"
	.string "How do you get out of here? It's so big,\n"
	.string "I may get lost.$"

MtMoon_1F_Text_JovanIntro::
# 42 "data/maps/MtMoon_1F/scripts.pory"
	.string "What! Don't sneak up on me!$"

MtMoon_1F_Text_JovanDefeat::
# 46 "data/maps/MtMoon_1F/scripts.pory"
	.string "My POKéMON won't do!$"

MtMoon_1F_Text_JovanPostBattle::
# 50 "data/maps/MtMoon_1F/scripts.pory"
	.string "I have to find stronger POKéMON. Where\n"
	.string "might they be?$"

MtMoon_1F_Text_IrisIntro::
# 54 "data/maps/MtMoon_1F/scripts.pory"
	.string "What? I'm waiting for my friends to find\l"
	.string "me here.$"

MtMoon_1F_Text_IrisDefeat::
# 58 "data/maps/MtMoon_1F/scripts.pory"
	.string "I lost?$"

MtMoon_1F_Text_IrisPostBattle::
# 62 "data/maps/MtMoon_1F/scripts.pory"
	.string "I came because I heard there are some\n"
	.string "very rare fossils here.$"

MtMoon_1F_Text_KentIntro::
# 66 "data/maps/MtMoon_1F/scripts.pory"
	.string "Suspicious men are in the cave. What\n"
	.string "about you?$"

MtMoon_1F_Text_KentDefeat::
# 70 "data/maps/MtMoon_1F/scripts.pory"
	.string "You got me!$"

MtMoon_1F_Text_KentPostBattle::
# 74 "data/maps/MtMoon_1F/scripts.pory"
	.string "I saw them! I'm sure they're from TEAM\n"
	.string "ROCKET!$"

MtMoon_1F_Text_RobbyIntro::
# 78 "data/maps/MtMoon_1F/scripts.pory"
	.string "You need to go through this cave to get\n"
	.string "to CERULEAN CITY.$"

MtMoon_1F_Text_RobbyDefeat::
# 82 "data/maps/MtMoon_1F/scripts.pory"
	.string "I lost.$"

MtMoon_1F_Text_RobbyPostBattle::
# 86 "data/maps/MtMoon_1F/scripts.pory"
	.string "ZUBAT is tough! But if you can catch\n"
	.string "one, you'll\l"
	.string "be able to count on it.$"

MtMoon_1F_Text_ZubatIsABloodsucker::
# 90 "data/maps/MtMoon_1F/scripts.pory"
	.string "Beware! ZUBAT is a bloodsucker!$"

MtMoon_1F_Text_BrockHelpsExcavateFossils::
# 94 "data/maps/MtMoon_1F/scripts.pory"
	.string "Hi, I'm excavating for fossils here\n"
	.string "under MT. MOON.\p"
	.string "Sometimes, BROCK of PEWTER GYM lends\n"
	.string "me a hand.$"
