Route211_West_MapScripts::
	.byte 0


Route211_West_EventScript_Sign1::
# 6 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_Sign1, MSGBOX_SIGN
	end


Route211_West_EventScript_SmithNPC1::
# 15 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC1, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC2::
# 24 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC2, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC3::
# 33 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC3, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC4::
# 42 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC4, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC5::
# 51 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC5, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC6::
# 60 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC6, MSGBOX_NPC
	end


Route211_West_EventScript_SmithNPC7::
# 69 "data/maps/Route211_West/scripts.pory"
	msgbox Route211_West_Text_SmithNPC7, MSGBOX_NPC
	end


Route211_West_Text_Sign1::
# 10 "data/maps/Route211_West/scripts.pory"
	.string "Route211_West Sign 1$"

Route211_West_Text_SmithNPC1::
# 19 "data/maps/Route211_West/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route211_West_Text_SmithNPC2::
# 28 "data/maps/Route211_West/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route211_West_Text_SmithNPC3::
# 37 "data/maps/Route211_West/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

Route211_West_Text_SmithNPC4::
# 46 "data/maps/Route211_West/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

Route211_West_Text_SmithNPC5::
# 55 "data/maps/Route211_West/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

Route211_West_Text_SmithNPC6::
# 64 "data/maps/Route211_West/scripts.pory"
	.string "It's the question that drives us, Neo.$"

Route211_West_Text_SmithNPC7::
# 73 "data/maps/Route211_West/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"
