LittlerootTown_MaysHouse_2F_MapScripts::
# 2 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_MaysHouse_2F_OnTransition
# 3 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_MaysHouse_2F_OnWarp
	.byte 0


RivalsHouse_2F_Text_MayWhoAreYou::
# 7 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "Huh? Who Who are you?\p"
	.string "\p"
	.string "Oh, you're {PLAYER}{KUN}. So your move was\n"
	.string "today.\p"
	.string "Um I'm MAY. Glad to meet you!\p"
	.string "I I have this dream of becoming friends\l"
	.string "with POKMON all over the world.\p"
	.string "I I heard about you, {PLAYER}{KUN}, from my\n"
	.string "dad, PROF. BIRCH.\p"
	.string "I was hoping that you would be nice,\n"
	.string "{PLAYER}{KUN}, and that we could be\l"
	.string "friends.\p"
	.string "Oh, this is silly, isn't it? I I've just\n"
	.string "met you, {PLAYER}{KUN}.\p"
	.string "Eheheh\p"
	.string "Oh, no! I forgot!\p"
	.string "I was supposed to go help Dad catch\n"
	.string "some wild POKMON!\p"
	.string "{PLAYER}{KUN}, I'll catch you later!$"

RivalsHouse_2F_Text_MayGettingReady::
# 11 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "POKMON fully restored! Items ready, and$"

RivalsHouse_2F_Text_BrendanWhoAreYou::
# 15 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "Hey! You\p"
	.string "Who are you?\p"
	.string "Oh, you're {PLAYER}, aren't you? Moved\n"
	.string "in next door, right?\p"
	.string "I didn't know that you're a girl.\p"
	.string "Dad, PROF. BIRCH, said that our new\n"
	.string "next-door neighbor is a GYM LEADER's\l"
	.string "kid, so I assumed you'd be a guy.\p"
	.string "My name's BRENDAN. So, hi, neighbor!\p"
	.string "Huh? Hey, {PLAYER}, don't you have a\n"
	.string "POKMON?\p"
	.string "Do you want me to go catch you one?\p"
	.string "Aw, darn, I forgot\p"
	.string "I'm supposed to go help my dad catch\n"
	.string "some wild POKMON.\p"
	.string "Some other time, okay?$"

RivalsHouse_2F_Text_BrendanGettingReady::
# 19 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "POKMON fully restored Items all packed,\n"
	.string "and$"

RivalsHouse_2F_Text_ItsRivalsPokeBall::
# 23 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "It's {RIVAL}'s POK BALL!\p"
	.string "Better leave it right where it is.$"

RivalsHouse_2F_Text_MayJustCheckingMyPokedex::
# 27 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "MAY: {PLAYER}{KUN}!\p"
	.string "I was just checking my POKDEX.\p"
	.string "There's still a lot of POKMON that I've\n"
	.string "seen but haven't caught.\p"
	.string "And there are many others that I think\n"
	.string "will evolve.\p"
	.string "I wonder where I should go catch some\n"
	.string "POKMON next?$"

RivalsHouse_2F_Text_MayWhereShouldIGoNext::
# 31 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "MAY: I wonder where I should go catch\n"
	.string "some POKMON next?\p"
	.string "Wouldn't it be funny if we ran into each\n"
	.string "other, {PLAYER}{KUN}?$"

RivalsHouse_2F_Text_BrendanJustCheckingMyPokedex::
# 35 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "BRENDAN: Hey, it's {PLAYER}.\p"
	.string "I was just checking out my POKDEX.\p"
	.string "There are still many POKMON that I need\n"
	.string "to catch, I know, but this\l"
	.string "is looking pretty good.\p"
	.string "Checking this POKDEX out gives me the\n"
	.string "urge to hit the road again.$"

RivalsHouse_2F_Text_BrendanWhereShouldIGoNext::
# 39 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "BRENDAN: I'm having a hard time\n"
	.string "deciding where I should catch POKMON\l"
	.string "next.\p"
	.string "Hey, {PLAYER}, if I see you while I'm\n"
	.string "out catching POKMON, I can pitch you a\l"
	.string "battle if you'd like.$"
