LittlerootTown_MaysHouse_2F_MapScripts::
	.byte 0


LittlerootTown_MaysHouse_2F_EventScript_PC::
	end


LittlerootTown_MaysHouse_2F_EventScript_RivalsPokeBall::
	end


LittlerootTown_MaysHouse_2F_EventScript_SmithNPC1::
# 33 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	msgbox LittlerootTown_MaysHouse_2F_Text_SmithNPC1, MSGBOX_NPC
	end


LittlerootTown_MaysHouse_2F_EventScript_SmithNPC2::
# 42 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	msgbox LittlerootTown_MaysHouse_2F_Text_SmithNPC2, MSGBOX_NPC
	end


RivalsHouse_2F_Text_BrendanWhereShouldIGoNext::
# 12 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "BRENDAN: I'm having a hard time\n"
	.string "deciding\n"
	.string "where I should catch POKéMON next.\p"
	.string "Hey, {PLAYER}, if I see you while I'm\n"
	.string "out\n"
	.string "catching POKéMON, I can pitch you a\l"
	.string "battle if you'd like.$"

RivalsHouse_2F_Text_MayWhereShouldIGoNext::
# 16 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "MAY: I wonder where I should go catch\n"
	.string "some POKéMON next?\p"
	.string "Wouldn't it be funny if we ran into each\n"
	.string "other, {PLAYER}{KUN}?$"

RivalsHouse_2F_Text_BrendanGettingReady::
# 20 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "POKéMON fully restored…\n"
	.string "Items all packed, and…$"

RivalsHouse_2F_Text_MayGettingReady::
# 24 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "POKéMON fully restored!\n"
	.string "Items ready, and…$"

RivalsHouse_2F_Text_MayWhoAreYou::
# 28 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "Huh?\n"
	.string "Who… Who are you?\p"
	.string "… … … … … … … …\n"
	.string "… … … … … … … …\p"
	.string "Oh, you're {PLAYER}{KUN}.\n"
	.string "So your move was today.\p"
	.string "Um… I'm MAY.\n"
	.string "Glad to meet you!\p"
	.string "I…\n"
	.string "I have this dream of becoming friends\l"
	.string "with POKéMON all over the world.\p"
	.string "I… I heard about you, {PLAYER}{KUN}, from\n"
	.string "my dad, PROF. BIRCH.\p"
	.string "I was hoping that you would be nice,\n"
	.string "{PLAYER}{KUN}, and that we could be\l"
	.string "friends.\p"
	.string "Oh, this is silly, isn't it?\n"
	.string "I… I've just met you, {PLAYER}{KUN}.\p"
	.string "Eheheh…\p"
	.string "Oh, no! I forgot!\p"
	.string "I was supposed to go help Dad catch\n"
	.string "some wild POKéMON!\p"
	.string "{PLAYER}{KUN}, I'll catch you later!$"

LittlerootTown_MaysHouse_2F_Text_SmithNPC1::
# 37 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

LittlerootTown_MaysHouse_2F_Text_SmithNPC2::
# 46 "data/maps/LittlerootTown_MaysHouse_2F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
