SixIsland_DottedHole_Entrance_MapScripts::
	.byte 0


SixIsland_DottedHole_Entrance_EventScript_SmithNPC1::
# 5 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	msgbox SixIsland_DottedHole_Entrance_Text_SmithNPC1, MSGBOX_NPC
	end


SixIsland_DottedHole_Entrance_EventScript_SmithNPC2::
# 14 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	msgbox SixIsland_DottedHole_Entrance_Text_SmithNPC2, MSGBOX_NPC
	end


SixIsland_DottedHole_Entrance_EventScript_SmithNPC3::
# 23 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	msgbox SixIsland_DottedHole_Entrance_Text_SmithNPC3, MSGBOX_NPC
	end


SixIsland_DottedHole_Entrance_Text_SmithNPC1::
# 9 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SixIsland_DottedHole_Entrance_Text_SmithNPC2::
# 18 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SixIsland_DottedHole_Entrance_Text_SmithNPC3::
# 27 "data/maps/SixIsland_DottedHole_Entrance/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
