LilycoveCity_LilycoveMuseum_2F_MapScripts::
# 2 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, LilycoveCity_LilycoveMuseum_2F_OnLoad
# 3 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LilycoveCity_LilycoveMuseum_2F_OnFrame
	.byte 0


LilycoveCity_LilycoveMuseum_2F_Text_ThisIsExhibitHall::
# 7 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "This is our special exhibit hall.$"

LilycoveCity_LilycoveMuseum_2F_Text_ExplainExhibitHall::
# 11 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "As you can plainly see, there is not a\n"
	.string "single painting on exhibit.\p"
	.string "Here, I don't wish to exhibit works of\n"
	.string "so-called classical art.\p"
	.string "Such classical works you can see on our\n"
	.string "ground floor.\p"
	.string "I wish to exhibit work that is far\n"
	.string "different from the classics.\p"
	.string "Art, after all, is not restricted to old,\n"
	.string "famous works!\p"
	.string "This exhibit hall, I wish to fill it with\p"
	.string "Modern and vibrant artworks of POKMON\n"
	.string "seemingly ready to spring\l"
	.string "forth into glorious life!$"

LilycoveCity_LilycoveMuseum_2F_Text_PleaseObtainPaintingsForExhibit::
# 15 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "I beg your pardon. I didn't intend to\n"
	.string "monopolize the conversation.\p"
	.string "Now, as you are young, and yet obviously\n"
	.string "well traveled\p"
	.string "You must encounter lively POKMON and\n"
	.string "works of art depicting them.\p"
	.string "If you were to come across such a\n"
	.string "painting, may we ask you to obtain\l"
	.string "the artist's permission to exhibit\l"
	.string "it here?$"

LilycoveCity_LilycoveMuseum_2F_Text_WishToFillExhibit::
# 19 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "I wish to fill this exhibit hall with\n"
	.string "modern and vibrant paintings of\l"
	.string "POKMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThanksAddedNewPainting::
# 23 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Thanks to you, we've added a new\n"
	.string "painting to our collection!\p"
	.string "I've heard it depicts your POKMON. Truly\n"
	.string "magnificent!\p"
	.string "Thank you so very, very much!$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYouPlayer::
# 27 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Ah! It's you! {PLAYER}!$"

LilycoveCity_LilycoveMuseum_2F_Text_PaintingsAttractedMoreGuests::
# 31 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Isn't this marvelous? This collection\n"
	.string "of paintings!\p"
	.string "Each one of them flawless! None better\n"
	.string "than another!\p"
	.string "These paintings have attracted more\n"
	.string "guests to our ART MUSEUM.\p"
	.string "Sincerely, I thank you, {PLAYER}. This\n"
	.string "is my dream come true!$"

LilycoveCity_LilycoveMuseum_2F_Text_TokenOfGratitude::
# 35 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "This is merely a token of my gratitude.$"

LilycoveCity_LilycoveMuseum_2F_Text_KeepThisForYou::
# 39 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "I will keep this for you until we meet\n"
	.string "again.$"

LilycoveCity_LilycoveMuseum_2F_Text_HonorToHaveYouVisit::
# 43 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Ah, so good to see you, {PLAYER}!\p"
	.string "It's an honor to have you visit us on\n"
	.string "your busy journeys.\p"
	.string "Please, relax and do enjoy your visit\n"
	.string "with us.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPinkPictureFrame::
# 47 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a picture frame with pink-colored\n"
	.string "adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsYellowPictureFrame::
# 51 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a picture frame with\n"
	.string "yellow-colored adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsBluePictureFrame::
# 55 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a picture frame with blue-colored\n"
	.string "adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsRedPictureFrame::
# 59 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a picture frame with red-colored\n"
	.string "adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsGreenPictureFrame::
# 63 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a picture frame with green-colored\n"
	.string "adornments.$"

LilycoveCity_LilycoveMuseum_2F_Text_ItsPaintingOfPokemon::
# 67 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "It's a painting of POKMON.$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsSurprisedMe::
# 71 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "I've been away awhile, so the new\n"
	.string "paintings up here surprised me.\p"
	.string "I wish someone would paint my POKMON\n"
	.string "this pretty.$"

LilycoveCity_LilycoveMuseum_2F_Text_NewPaintingsRatherAmusing::
# 75 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Well So this is where they show the\n"
	.string "topical POKMON paintings.\p"
	.string "I see, these new paintings are indeed\n"
	.string "rather amusing.$"

LilycoveCity_LilycoveMuseum_2F_Text_ThesePaintingsOfYourPokemon::
# 79 "data/maps/LilycoveCity_LilycoveMuseum_2F/scripts.pory"
	.string "Wow, is that right? These paintings are\n"
	.string "of your POKMON.\p"
	.string "Isn't that just the ultimate joy for a\n"
	.string "TRAINER?$"
