PokemonMansion_B1F_MapScripts::
# 2 "data/maps/PokemonMansion_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_B1F_OnLoad
	.byte 0


PokemonMansion_B1F_Text_LewisIntro::
# 6 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "Uh-oh… Where am I now?$"

PokemonMansion_B1F_Text_LewisDefeat::
# 10 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "Awooh!$"

PokemonMansion_B1F_Text_LewisPostBattle::
# 14 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "You can find stuff lying around. The\n"
	.string "residents must've left them.$"

PokemonMansion_B1F_Text_IvanIntro::
# 18 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "This place is ideal for a lab. Look at all\n"
	.string "this space.$"

PokemonMansion_B1F_Text_IvanDefeat::
# 22 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "What was that for?$"

PokemonMansion_B1F_Text_IvanPostBattle::
# 26 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "I like it here. It's conducive to my\n"
	.string "studies.$"

PokemonMansion_B1F_Text_MewtwoIsFarTooPowerful::
# 30 "data/maps/PokemonMansion_B1F/scripts.pory"
	.string "Diary: Sept. 1 MEWTWO is far too\n"
	.string "powerful.\p"
	.string "We have failed to curb its vicious\n"
	.string "tendencies…$"
