SevenIsland_TrainerTower_MapScripts::
# 2 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_TrainerTower_OnTransition
	.byte 0


SevenIsland_TrainerTower_Text_DarioIntro::
# 6 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "I sensed your approach.$"

SevenIsland_TrainerTower_Text_DarioDefeat::
# 10 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Give up…$"

SevenIsland_TrainerTower_Text_DarioPostBattle::
# 14 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "In your future, I sense that you will\n"
	.string "meet many others.\p"
	.string "I think you will be linked to each other\n"
	.string "by a strange power.$"

SevenIsland_TrainerTower_Text_RodetteIntro::
# 18 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.$"

SevenIsland_TrainerTower_Text_RodetteDefeat::
# 22 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "What an amazing TRAINER!$"

SevenIsland_TrainerTower_Text_RodettePostBattle::
# 26 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Somewhere on this island, peculiar\n"
	.string "POKéMON are sleeping.\p"
	.string "Could it be that they're waiting for\n"
	.string "you?$"

SevenIsland_TrainerTower_Text_TrainerTowerSign::
# 30 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "TRAINER TOWER ENTRANCE Rise to the\n"
	.string "Challenge, TRAINERS!$"

SevenIsland_TrainerTower_Text_TrainerTowerAhead::
# 34 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "TRAINER TOWER AHEAD$"

SevenIsland_TrainerTower_Text_LooksLikeTrainerTowerIsClosed::
# 38 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "トレーナータワーには いまは　はいれない　みたい‥$"

SevenIsland_TrainerTower_Text_TrainerTowerIsOpenLetsGoIn::
# 42 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "トレーナータワーが　あいてる！ さっそく　はいってみよう！$"
