SevenIsland_TrainerTower_MapScripts::
	.byte 0


SevenIsland_TrainerTower_EventScript_SmithNPC1::
# 5 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC1, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC2::
# 14 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC2, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC3::
# 23 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC3, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC4::
# 32 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC4, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC5::
# 41 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC5, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC6::
# 50 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC6, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC7::
# 59 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC7, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC8::
# 68 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC8, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC9::
# 77 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC9, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC10::
# 86 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC10, MSGBOX_NPC
	end


SevenIsland_TrainerTower_EventScript_SmithNPC11::
# 95 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	msgbox SevenIsland_TrainerTower_Text_SmithNPC11, MSGBOX_NPC
	end


SevenIsland_TrainerTower_Text_SmithNPC1::
# 9 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SevenIsland_TrainerTower_Text_SmithNPC2::
# 18 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SevenIsland_TrainerTower_Text_SmithNPC3::
# 27 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

SevenIsland_TrainerTower_Text_SmithNPC4::
# 36 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

SevenIsland_TrainerTower_Text_SmithNPC5::
# 45 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

SevenIsland_TrainerTower_Text_SmithNPC6::
# 54 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "It's the question that drives us, Neo.$"

SevenIsland_TrainerTower_Text_SmithNPC7::
# 63 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

SevenIsland_TrainerTower_Text_SmithNPC8::
# 72 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "I know kung fu.$"

SevenIsland_TrainerTower_Text_SmithNPC9::
# 81 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Dodge this.$"

SevenIsland_TrainerTower_Text_SmithNPC10::
# 90 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Choice is an illusion created between\n"
	.string "those with power and those without.$"

SevenIsland_TrainerTower_Text_SmithNPC11::
# 99 "data/maps/SevenIsland_TrainerTower/scripts.pory"
	.string "Hope is an illusion, Mr. Anderson.$"
