VermilionCity_PokemonFanClub_MapScripts::
	.byte 0


VermilionCity_PokemonFanClub_EventScript_Chairman::
	end


VermilionCity_PokemonFanClub_EventScript_FatMan::
	end


VermilionCity_PokemonFanClub_EventScript_Pikachu::
	end


VermilionCity_PokemonFanClub_EventScript_RulesSign1::
# 17 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	msgbox VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers, MSGBOX_SIGN
	end


VermilionCity_PokemonFanClub_EventScript_RulesSign2::
# 22 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	msgbox VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack, MSGBOX_SIGN
	end


VermilionCity_PokemonFanClub_EventScript_Seel::
	end


VermilionCity_PokemonFanClub_EventScript_Woman::
	end


VermilionCity_PokemonFanClub_EventScript_WorkerF::
	end


VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
# 39 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
# 43 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Let's all listen politely to other\n"
	.string "TRAINERS!$"
