VermilionCity_PokemonFanClub_MapScripts::
	.byte 0


VermilionCity_PokemonFanClub_Text_AdmirePikachusTail::
# 5 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Won't you admire my PIKACHU's adorable\n"
	.string "tail?$"

VermilionCity_PokemonFanClub_Text_PikachuTwiceAsCute::
# 9 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Humph!\p"
	.string "My PIKACHU is twice as cute as that\n"
	.string "one!$"

VermilionCity_PokemonFanClub_Text_AdoreMySeel::
# 13 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "I just adore my SEEL! It's so lovable!\p"
	.string "It squeals, “Kyuuuh,” when I hug it!$"

VermilionCity_PokemonFanClub_Text_SeelFarMoreAttractive::
# 17 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Oh, dear!\p"
	.string "My SEEL is far more attractive. By\n"
	.string "double, I would say.$"

VermilionCity_PokemonFanClub_Text_Pikachu::
# 21 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "PIKACHU: Chu! Pikachu!$"

VermilionCity_PokemonFanClub_Text_Seel::
# 25 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "SEEL: Kyuoo!$"

VermilionCity_PokemonFanClub_Text_DidYouComeToHearAboutMyMons::
# 29 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "I chair the POKéMON Fan Club!\p"
	.string "I raise more than a hundred POKéMON!\p"
	.string "I'm very fussy when it comes to\n"
	.string "POKéMON! I surely am!\p"
	.string "So…\p"
	.string "Did you come visit to hear about my\n"
	.string "POKéMON?$"

VermilionCity_PokemonFanClub_Text_ChairmansStory::
# 33 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Good! Then listen up!\p"
	.string "My favorite RAPIDASH…\p"
	.string "It's…cute…lovely…smart…\n"
	.string "plus…amazing…you think so?…\l"
	.string "oh yes…it's…stunning…\l"
	.string "kindly…love it!\p"
	.string "Hug it…when…sleeping…warm and\n"
	.string "cuddly…spectacular…\l"
	.string "ravishing…\l"
	.string "…Oops! Look at the time!\l"
	.string "I kept you too long!\p"
	.string "Thanks for hearing me out! I want you\n"
	.string "to have this!$"

VermilionCity_PokemonFanClub_Text_ReceivedBikeVoucherFromChairman::
# 37 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "{PLAYER} received a BIKE VOUCHER\n"
	.string "from the CHAIRMAN.$"

VermilionCity_PokemonFanClub_Text_ExplainBikeVoucher::
# 41 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Take that BIKE VOUCHER to the BIKE\n"
	.string "SHOP in CERULEAN CITY.\p"
	.string "Exchange that for a BICYCLE free of\n"
	.string "charge!\p"
	.string "Don't worry, my favorite FEAROW will FLY\n"
	.string "me anywhere I need to go.\p"
	.string "So, I have no need for a BICYCLE.\p"
	.string "I hope you like cycling!$"

VermilionCity_PokemonFanClub_Text_ComeBackToHearStory::
# 45 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Oh. Come back when you want to hear my\n"
	.string "story!$"

VermilionCity_PokemonFanClub_Text_DidntComeToSeeAboutMonsAgain::
# 49 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Hello, {PLAYER}!\p"
	.string "Did you come see me about my POKéMON\n"
	.string "again?\p"
	.string "No? Too bad!$"

VermilionCity_PokemonFanClub_Text_MakeRoomForThis::
# 53 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Make room for this!$"

VermilionCity_PokemonFanClub_Text_ChairmanVeryVocalAboutPokemon::
# 57 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Our CHAIRMAN is very vocal about\n"
	.string "POKéMON.$"

VermilionCity_PokemonFanClub_Text_ListenPolitelyToOtherTrainers::
# 61 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Let's all listen politely to other\n"
	.string "TRAINERS!$"

VermilionCity_PokemonFanClub_Text_SomeoneBragsBragBack::
# 65 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "If someone brags, brag right back!$"

VermilionCity_PokemonFanClub_Text_ChairmanReallyAdoresHisMons::
# 69 "data/maps/VermilionCity_PokemonFanClub/scripts.pory"
	.string "Our CHAIRMAN really does adore his\n"
	.string "POKéMON.\p"
	.string "But the person who is most liked by\n"
	.string "POKéMON is DAISY, I think.$"
