FuchsiaCity_House1_MapScripts::
	.byte 0


FuchsiaCity_House1_EventScript_LittleBoy::
# 5 "data/maps/FuchsiaCity_House1/scripts.pory"
	msgbox FuchsiaCity_House1_Text_BillFilesHisOwnMonData, MSGBOX_NPC
	end


FuchsiaCity_House1_EventScript_OldMan::
	end


FuchsiaCity_House1_EventScript_Woman::
# 14 "data/maps/FuchsiaCity_House1/scripts.pory"
	msgbox FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth, MSGBOX_NPC
	end


FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
# 19 "data/maps/FuchsiaCity_House1/scripts.pory"
	.string "BILL files his own POKéMON data on\n"
	.string "his PC.\p"
	.string "Did he show you?$"

FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
# 23 "data/maps/FuchsiaCity_House1/scripts.pory"
	.string "The SAFARI ZONE's WARDEN is old,\n"
	.string "but he's still very much active.\p"
	.string "All his teeth are false, though.$"
