FuchsiaCity_House1_MapScripts::
	.byte 0


FuchsiaCity_House1_Text_WardenIsOldHasFalseTeeth::
# 5 "data/maps/FuchsiaCity_House1/scripts.pory"
	.string "The SAFARI ZONE's WARDEN is old, but\n"
	.string "he's still very much active.\p"
	.string "All his teeth are false, though.$"

FuchsiaCity_House1_Text_BillIsMyGrandson::
# 9 "data/maps/FuchsiaCity_House1/scripts.pory"
	.string "Hmm? You've met BILL?\p"
	.string "He's my grandson!\p"
	.string "He always liked collecting things, even\n"
	.string "as a child!$"

FuchsiaCity_House1_Text_BillFilesHisOwnMonData::
# 13 "data/maps/FuchsiaCity_House1/scripts.pory"
	.string "BILL files his own POKéMON data on his\n"
	.string "PC.\p"
	.string "Did he show you?$"
