Route7_EastEntrance_MapScripts::
	.byte 0


Route7_EastEntrance_EventScript_Guard::
# 5 "data/maps/Route7_EastEntrance/scripts.pory"
	msgbox Route7_EastEntrance_Text_HiHowsItGoing, MSGBOX_NPC
	end


Route7_EastEntrance_EventScript_GuardTriggerBottom::
	end


Route7_EastEntrance_EventScript_GuardTriggerMid::
	end


Route7_EastEntrance_EventScript_GuardTriggerTop::
	end


Route7_EastEntrance_Text_HiHowsItGoing::
# 22 "data/maps/Route7_EastEntrance/scripts.pory"
	.string "Hi, how's it going?$"
