RustboroCity_House1_MapScripts::
	.byte 0


RustboroCity_House1_EventScript_Hiker::
# 5 "data/maps/RustboroCity_House1/scripts.pory"
	msgbox RustboroCity_House1_Text_AllSortsOfPlaces, MSGBOX_NPC
	end


RustboroCity_House1_EventScript_Trader::
	end


RustboroCity_House1_Text_AnyPokemonCanBeCute::
# 13 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Any POKéMON can be cute if you raise\n"
	.string "it with care and kindness.$"

RustboroCity_House1_Text_AllSortsOfPlaces::
# 17 "data/maps/RustboroCity_House1/scripts.pory"
	.string "In all sorts of places, there are all\n"
	.string "sorts of POKéMON and people.\p"
	.string "I find that fascinating, so I go to all\n"
	.string "sorts of places.$"

RustboroCity_House1_Text_DoesntLookLikeMonToMe::
# 21 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Huh? That doesn't look anything like\n"
	.string "a {STR_VAR_1} to me.$"

RustboroCity_House1_Text_YouDontWantToThatsOkay::
# 25 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Oh, if you don't want to, that's okay.\n"
	.string "But my POKéMON is cute, you know…$"
