RustboroCity_House1_MapScripts::
	.byte 0


RustboroCity_House1_Text_IllTradeIfYouWant::
# 5 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Huh? My POKéMON is cute? Sure, I knew\n"
	.string "that.\p"
	.string "But if you really want, I'm willing to\n"
	.string "trade it to you.\p"
	.string "I'll trade you my {STR_VAR_2} for a\n"
	.string "{STR_VAR_1} if you want.$"

RustboroCity_House1_Text_PleaseBeGoodToMyPokemon::
# 9 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Eheheh… Please be good to my POKéMON.$"

RustboroCity_House1_Text_DoesntLookLikeMonToMe::
# 13 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Huh? That doesn't look anything like a\n"
	.string "{STR_VAR_1} to me.$"

RustboroCity_House1_Text_YouDontWantToThatsOkay::
# 17 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Oh, if you don't want to, that's okay.\n"
	.string "But my POKéMON is cute, you know…$"

RustboroCity_House1_Text_AnyPokemonCanBeCute::
# 21 "data/maps/RustboroCity_House1/scripts.pory"
	.string "Any POKéMON can be cute if you raise it\n"
	.string "with care and kindness.$"

RustboroCity_House1_Text_AllSortsOfPlaces::
# 25 "data/maps/RustboroCity_House1/scripts.pory"
	.string "In all sorts of places, there are all\n"
	.string "sorts of POKéMON and people.\p"
	.string "I find that fascinating, so I go to all\n"
	.string "sorts of places.$"
