LavaridgeTown_Mart_MapScripts::
	.byte 0


LavaridgeTown_Mart_EventScript_Clerk::
	end


LavaridgeTown_Mart_EventScript_ExpertM::
# 9 "data/maps/LavaridgeTown_Mart/scripts.pory"
	msgbox LavaridgeTown_Mart_Text_XSpeedFirstStrike, MSGBOX_NPC
	end


LavaridgeTown_Mart_EventScript_OldWoman::
# 14 "data/maps/LavaridgeTown_Mart/scripts.pory"
	msgbox LavaridgeTown_Mart_Text_LocalSpecialtyOnMtChimney, MSGBOX_NPC
	end


LavaridgeTown_Mart_Text_LocalSpecialtyOnMtChimney::
# 18 "data/maps/LavaridgeTown_Mart/scripts.pory"
	.string "On MT. CHIMNEY's peak, there's a local\n"
	.string "specialty that you can buy only there.\p"
	.string "Give it to a POKéMON--it will be elated.$"

LavaridgeTown_Mart_Text_XSpeedFirstStrike::
# 22 "data/maps/LavaridgeTown_Mart/scripts.pory"
	.string "Use X SPEED to add to a POKéMON's\n"
	.string "SPEED in battle.\p"
	.string "That will help it get in the first\n"
	.string "strike--a decided advantage!$"
