CinnabarIsland_PokemonLab_Lounge_MapScripts::
	.byte 0


CinnabarIsland_PokemonLab_Lounge_EventScript_Clifton::
	end


CinnabarIsland_PokemonLab_Lounge_EventScript_Norma::
	end


CinnabarIsland_PokemonLab_Lounge_EventScript_Scientist::
# 13 "data/maps/CinnabarIsland_PokemonLab_Lounge/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon, MSGBOX_NPC
	end


CinnabarIsland_PokemonLab_Lounge_Text_FoundFossilInMtMoon::
# 18 "data/maps/CinnabarIsland_PokemonLab_Lounge/scripts.pory"
	.string "I found this most remarkable fossil\n"
	.string "inside MT. MOON.\p"
	.string "I think it's of a rare, prehistoric\n"
	.string "POKéMON.$"
