SaffronCity_CopycatsHouse_1F_MapScripts::
	.byte 0


SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
# 5 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	.string "My daughter is so self-centered. She\n"
	.string "has but a few friends.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
# 9 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	.string "My daughter likes to mimic people. It's\n"
	.string "rather vexing.\p"
	.string "Her mimicry has earned her the nickname\n"
	.string "COPYCAT around here.$"

SaffronCity_CopycatsHouse_1F_Text_Chansey::
# 13 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	.string "CHANSEY: Chaan! Sii!$"
