SaffronCity_CopycatsHouse_1F_MapScripts::
	.byte 0


SaffronCity_CopycatsHouse_1F_EventScript_Chansey::
	end


SaffronCity_CopycatsHouse_1F_EventScript_CopycatsDad::
# 9 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	msgbox SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople, MSGBOX_NPC
	end


SaffronCity_CopycatsHouse_1F_EventScript_CopycatsMom::
# 14 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	msgbox SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered, MSGBOX_NPC
	end


SaffronCity_CopycatsHouse_1F_Text_DaughterLikesToMimicPeople::
# 19 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	.string "My daughter likes to mimic people.\n"
	.string "It's rather vexing.\p"
	.string "Her mimicry has earned her the\n"
	.string "nickname COPYCAT around here.$"

SaffronCity_CopycatsHouse_1F_Text_DaughterIsSelfCentered::
# 23 "data/maps/SaffronCity_CopycatsHouse_1F/scripts.pory"
	.string "My daughter is so self-centered.\n"
	.string "She has but a few friends.$"
