VerdanturfTown_BattleTentCorridor_MapScripts::
# 2 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, VerdanturfTown_BattleTentCorridor_OnFrame
	.byte 0


VerdanturfTown_BattleTentCorridor_MapScripts::
# 6 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, VerdanturfTown_BattleTentCorridor_OnFrame
	return


VerdanturfTown_ContestHall_Text_WhichContestYouEntering::
# 10 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	.string "Which CONTEST are you entering? Want a\n"
	.string "piece of advice?\p"
	.string "In any CONTEST, for example, a CUTE\n"
	.string "CONTEST, I don't think they judge you\l"
	.string "only on cuteness in the first round.\p"
	.string "You need to work out ways for raising\n"
	.string "POKéMON better.$"

VerdanturfTown_ContestHall_Text_RaisedMonToBeCute::
# 14 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	.string "I raised my POKéMON to be cute.\p"
	.string "I found out you can put POKéMON in a\n"
	.string "CONTEST for cuteness!\p"
	.string "I'm so glad I raised my POKéMON with\n"
	.string "loving care…$"

VerdanturfTown_ContestHall_Text_MyMonRules::
# 18 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	.string "My POKéMON rules!\p"
	.string "It's cool, tough yet beautiful, cute,\n"
	.string "and smart. It's complete!\p"
	.string "I may as well go for wins in every single\n"
	.string "CONTEST.$"

VerdanturfTown_ContestHall_Text_NormalRankStage::
# 22 "data/maps/VerdanturfTown_BattleTentCorridor/scripts.pory"
	.string "POKéMON CONTESTS NORMAL RANK STAGE!$"
