PokemonTower_7F_MapScripts::
	.byte 0


PokemonTower_7F_EventScript_Grunt1::
# 5 "data/maps/PokemonTower_7F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_19, PokemonTower_7F_Text_Grunt1Intro, PokemonTower_7F_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/PokemonTower_7F/scripts.pory"
	msgbox PokemonTower_7F_Text_Grunt1PostBattle
	return


PokemonTower_7F_EventScript_Grunt2::
# 10 "data/maps/PokemonTower_7F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_20, PokemonTower_7F_Text_Grunt2Intro, PokemonTower_7F_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/PokemonTower_7F/scripts.pory"
	msgbox PokemonTower_7F_Text_Grunt2PostBattle
	return


PokemonTower_7F_EventScript_Grunt3::
# 15 "data/maps/PokemonTower_7F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_21, PokemonTower_7F_Text_Grunt3Intro, PokemonTower_7F_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/PokemonTower_7F/scripts.pory"
	msgbox PokemonTower_7F_Text_Grunt3PostBattle
	return


PokemonTower_7F_EventScript_MrFuji::
	end


PokemonTower_7F_Text_Grunt1Defeat::
# 25 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt1Defeat$"

PokemonTower_7F_Text_Grunt1Intro::
# 29 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt1Intro$"

PokemonTower_7F_Text_Grunt1PostBattle::
# 33 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt1PostBattle$"

PokemonTower_7F_Text_Grunt2Defeat::
# 37 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt2Defeat$"

PokemonTower_7F_Text_Grunt2Intro::
# 41 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt2Intro$"

PokemonTower_7F_Text_Grunt2PostBattle::
# 45 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt2PostBattle$"

PokemonTower_7F_Text_Grunt3Defeat::
# 49 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt3Defeat$"

PokemonTower_7F_Text_Grunt3Intro::
# 53 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt3Intro$"

PokemonTower_7F_Text_Grunt3PostBattle::
# 57 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_7F_Text_Grunt3PostBattle$"
