PokemonTower_7F_MapScripts::
	.byte 0


PokemonTower_7F_Text_Grunt1Intro::
# 5 "data/maps/PokemonTower_7F/scripts.pory"
	.string "What do you want? Why are you here?$"

PokemonTower_7F_Text_Grunt1Defeat::
# 9 "data/maps/PokemonTower_7F/scripts.pory"
	.string "I give up!$"

PokemonTower_7F_Text_Grunt1PostBattle::
# 13 "data/maps/PokemonTower_7F/scripts.pory"
	.string "I'm not going to forget this!$"

PokemonTower_7F_Text_Grunt2Intro::
# 17 "data/maps/PokemonTower_7F/scripts.pory"
	.string "This old guy marched right up to our\n"
	.string "HIDEOUT.\p"
	.string "Then, he starts ranting about how TEAM\n"
	.string "ROCKET's abusing POKMON.\p"
	.string "So, we're just talking it over as adults.$"

PokemonTower_7F_Text_Grunt2Defeat::
# 21 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Please! No more!$"

PokemonTower_7F_Text_Grunt2PostBattle::
# 25 "data/maps/PokemonTower_7F/scripts.pory"
	.string "POKMON are only good for making money.\n"
	.string "Why not use them?\p"
	.string "You stay out of our business!$"

PokemonTower_7F_Text_Grunt3Intro::
# 29 "data/maps/PokemonTower_7F/scripts.pory"
	.string "You're not saving anyone, kid!$"

PokemonTower_7F_Text_Grunt3Defeat::
# 33 "data/maps/PokemonTower_7F/scripts.pory"
	.string "Don't fight us ROCKETS!$"

PokemonTower_7F_Text_Grunt3PostBattle::
# 37 "data/maps/PokemonTower_7F/scripts.pory"
	.string "You're not getting away with this!$"

PokemonTower_7F_Text_MrFujiThankYouFollowMe::
# 41 "data/maps/PokemonTower_7F/scripts.pory"
	.string "MR. FUJI: Heh? You came to save me?\p"
	.string "Thank you. But, I came here of my own\n"
	.string "free will.\p"
	.string "I came to calm the spirit of CUBONE's\n"
	.string "mother.\p"
	.string "I think MAROWAK's spirit has finally\n"
	.string "left us.\p"
	.string "I must thank you for your kind concern.\p"
	.string "Follow me to my home, POKMON HOUSE, at\n"
	.string "the foot of this tower.$"
