UndergroundPath_SouthEntrance_MapScripts::
	.byte 0


UndergroundPath_SouthEntrance_EventScript_Woman::
# 5 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
	msgbox UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness, MSGBOX_NPC
	end


UndergroundPath_SouthEntrance_Text_PeopleLoseThingsInTheDarkness::
# 10 "data/maps/UndergroundPath_SouthEntrance/scripts.pory"
	.string "People often lose things in the\n"
	.string "darkness of the UNDERGROUND PATH.$"
