PokemonLeague_LancesRoom_MapScripts::
# 2 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_LancesRoom_OnResume
# 3 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_LancesRoom_OnLoad
# 4 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_LancesRoom_OnWarp
# 5 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_LancesRoom_OnFrame
	.byte 0


PokemonLeague_LancesRoom_Text_Intro::
# 9 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	.string "Ah! I've heard about you, {PLAYER}!\p"
	.string "I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.\p"
	.string "You know that dragons are mythical\n"
	.string "POKéMON.\p"
	.string "They're hard to catch and raise, but\n"
	.string "their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.\p"
	.string "Well, are you ready to lose?\p"
	.string "Your LEAGUE challenge ends with me,\n"
	.string "{PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_RematchIntro::
# 13 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	.string "Ah! So, you've returned, {PLAYER}!\p"
	.string "I lead the ELITE FOUR.\p"
	.string "You can call me LANCE the dragon\n"
	.string "TRAINER.\p"
	.string "You know that dragons are mythical\n"
	.string "POKéMON.\p"
	.string "They're hard to catch and raise, but\n"
	.string "their powers are superior.\p"
	.string "They're virtually indestructible.\n"
	.string "There's no being clever with them.\p"
	.string "Well, are you ready to lose?\p"
	.string "Your LEAGUE challenge ends with me,\n"
	.string "{PLAYER}!{PLAY_BGM}{MUS_ENCOUNTER_GYM_LEADER}$"

PokemonLeague_LancesRoom_Text_Defeat::
# 17 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	.string "That's it!\p"
	.string "I hate to admit it, but you are a\n"
	.string "POKéMON master!$"

PokemonLeague_LancesRoom_Text_PostBattle::
# 21 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	.string "I still can't believe my dragons lost to\n"
	.string "you, {PLAYER}.\p"
	.string "You are now the POKéMON LEAGUE\n"
	.string "CHAMPION!\p"
	.string "…Or, you would have been, but you have\n"
	.string "one more challenge left.\p"
	.string "There is one more TRAINER to face! His\n"
	.string "name is…\p"
	.string "{RIVAL}!\p"
	.string "He beat the ELITE FOUR before you.\p"
	.string "He is the real POKéMON LEAGUE CHAMPION.$"
