PokemonLeague_LancesRoom_MapScripts::
# 2 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_LancesRoom_OnResume
# 3 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_LancesRoom_OnLoad
# 4 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_LancesRoom_OnWarp
# 5 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_LancesRoom_OnFrame
	.byte 0


PokemonLeague_LancesRoom_MapScripts::
# 9 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_LancesRoom_OnResume
# 10 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_LancesRoom_OnLoad
# 11 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_LancesRoom_OnWarp
# 12 "data/maps/PokemonLeague_LancesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_LancesRoom_OnFrame
	return

