GoldenrodCity_Underground_Warehouse_MapScripts::
	.byte 0


GoldenrodCity_Underground_Warehouse_EventScript_SmithNPC1::
# 5 "data/maps/GoldenrodCity_Underground_Warehouse/scripts.pory"
	msgbox GoldenrodCity_Underground_Warehouse_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_Underground_Warehouse_EventScript_SmithNPC2::
# 14 "data/maps/GoldenrodCity_Underground_Warehouse/scripts.pory"
	msgbox GoldenrodCity_Underground_Warehouse_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_Underground_Warehouse_Text_SmithNPC1::
# 9 "data/maps/GoldenrodCity_Underground_Warehouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_Underground_Warehouse_Text_SmithNPC2::
# 18 "data/maps/GoldenrodCity_Underground_Warehouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
