MtChimney_MapScripts::
	.byte 0


MtChimney_EventScript_AquaPoochyena::
# 5 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_Bushaa, MSGBOX_SIGN
	end


MtChimney_EventScript_Archie::
	end


MtChimney_EventScript_BusyAquaGrunt1::
# 14 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_MagmaOutnumbersUs, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyAquaGrunt2::
# 19 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_LessHabitatForWaterPokemon, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyAquaGrunt3::
# 24 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_MagmasNameSimilar, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt1::
# 29 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_TeamAquaAlwaysMessingWithPlans, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt2::
# 34 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_MeteoritesPackAmazingPower, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt3::
# 39 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_YouBetterNotMessWithUs, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt4::
# 44 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_AquasNameSimilar, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt5::
# 49 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_DouseThemInFire, MSGBOX_SIGN
	end


MtChimney_EventScript_BusyMagmaGrunt6::
# 54 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_KeepMakingMoreLand, MSGBOX_SIGN
	end


MtChimney_EventScript_Grunt1::
# 59 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_CHIMNEY, MtChimney_Text_Grunt1Intro, MtChimney_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 60 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_Grunt1PostBattle
	return


MtChimney_EventScript_Grunt2::
# 64 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_CHIMNEY_2, MtChimney_Text_Grunt2Intro, MtChimney_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 65 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_Grunt2PostBattle
	return


MtChimney_EventScript_LavaCookieLady::
# 69 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_LavaCookiesJust200, MSGBOX_YESNO
	end


MtChimney_EventScript_MagmaPoochyena::
# 74 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_Bufoh, MSGBOX_SIGN
	end


MtChimney_EventScript_Maxie::
# 79 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_MeteoriteWillActivateVolcano, MSGBOX_DEFAULT
	end


MtChimney_EventScript_Melissa::
# 84 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_MELISSA, MtChimney_Text_MelissaIntro, MtChimney_Text_MelissaDefeat, Text_NotEnoughMonsForDoubleBattle
# 85 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_MelissaPostBattle
	return


MtChimney_EventScript_MeteoriteMachine::
# 92 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_RemoveTheMeteorite, MSGBOX_YESNO
# 94 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_PlayerRemovedMeteorite, MSGBOX_DEFAULT
	end


MtChimney_EventScript_RouteSign::
# 103 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_RouteSign, MSGBOX_SIGN
	end


MtChimney_EventScript_Sawyer::
# 108 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_SAWYER, MtChimney_Text_SawyerIntro, MtChimney_Text_SawyerDefeat, Text_NotEnoughMonsForDoubleBattle
# 109 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_SawyerPostBattle
	return


MtChimney_EventScript_Sheila::
# 113 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_SHEILA, MtChimney_Text_SheilaIntro, MtChimney_Text_SheilaDefeat, Text_NotEnoughMonsForDoubleBattle
# 114 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_SheilaPostBattle
	return


MtChimney_EventScript_Shelby::
# 118 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_SHELBY, MtChimney_Text_ShelbyIntro, MtChimney_Text_ShelbyDefeat, Text_NotEnoughMonsForDoubleBattle
# 119 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_ShelbyPostBattle
	return


MtChimney_EventScript_Shirley::
# 123 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_SHIRLEY, MtChimney_Text_ShirleyIntro, MtChimney_Text_ShirleyDefeat, Text_NotEnoughMonsForDoubleBattle
# 124 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_ShirleyPostBattle
	return


MtChimney_EventScript_Tabitha::
# 128 "data/maps/MtChimney/scripts.pory"
	trainerbattle_double TRAINER_TABITHA_MT_CHIMNEY, MtChimney_Text_TabithaIntro, MtChimney_Text_TabithaDefeat, Text_NotEnoughMonsForDoubleBattle
# 129 "data/maps/MtChimney/scripts.pory"
	msgbox MtChimney_Text_TabithaPostBattle
	return


MtChimney_Text_PlayerRemovedMeteorite::
# 133 "data/maps/MtChimney/scripts.pory"
	.string "{PLAYER} removed the METEORITE from\n"
	.string "the mysterious machine.$"

MtChimney_Text_RemoveTheMeteorite::
# 137 "data/maps/MtChimney/scripts.pory"
	.string "A METEORITE is fitted on a mysterious\n"
	.string "machine…\p"
	.string "Do you want to remove the METEORITE?$"

MtChimney_Text_RouteSign::
# 141 "data/maps/MtChimney/scripts.pory"
	.string "{DOWN_ARROW} JAGGED PATH LAVARIDGE TOWN AHEAD$"

MtChimney_Text_Grunt1Defeat::
# 146 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt1Defeat$"

MtChimney_Text_Grunt1Intro::
# 150 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt1Intro$"

MtChimney_Text_Grunt1PostBattle::
# 154 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt1PostBattle$"

MtChimney_Text_Grunt2Defeat::
# 158 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt2Defeat$"

MtChimney_Text_Grunt2Intro::
# 162 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt2Intro$"

MtChimney_Text_Grunt2PostBattle::
# 166 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_Grunt2PostBattle$"

MtChimney_Text_MelissaDefeat::
# 170 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_MelissaDefeat$"

MtChimney_Text_MelissaIntro::
# 174 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_MelissaIntro$"

MtChimney_Text_MelissaPostBattle::
# 178 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_MelissaPostBattle$"

MtChimney_Text_SawyerDefeat::
# 182 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SawyerDefeat$"

MtChimney_Text_SawyerIntro::
# 186 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SawyerIntro$"

MtChimney_Text_SawyerPostBattle::
# 190 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SawyerPostBattle$"

MtChimney_Text_SheilaDefeat::
# 194 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SheilaDefeat$"

MtChimney_Text_SheilaIntro::
# 198 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SheilaIntro$"

MtChimney_Text_SheilaPostBattle::
# 202 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_SheilaPostBattle$"

MtChimney_Text_ShelbyDefeat::
# 206 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShelbyDefeat$"

MtChimney_Text_ShelbyIntro::
# 210 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShelbyIntro$"

MtChimney_Text_ShelbyPostBattle::
# 214 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShelbyPostBattle$"

MtChimney_Text_ShirleyDefeat::
# 218 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShirleyDefeat$"

MtChimney_Text_ShirleyIntro::
# 222 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShirleyIntro$"

MtChimney_Text_ShirleyPostBattle::
# 226 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_ShirleyPostBattle$"

MtChimney_Text_TabithaDefeat::
# 230 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_TabithaDefeat$"

MtChimney_Text_TabithaIntro::
# 234 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_TabithaIntro$"

MtChimney_Text_TabithaPostBattle::
# 238 "data/maps/MtChimney/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtChimney_Text_TabithaPostBattle$"

MtChimney_Text_SawyerRegister::
# 242 "data/maps/MtChimney/scripts.pory"
	.string "I like little fireballs like you.\n"
	.string "Let me register you in my POKéNAV.$"

MtChimney_Text_MagmasNameSimilar::
# 246 "data/maps/MtChimney/scripts.pory"
	.string "We're TEAM AQUA!\p"
	.string "They're TEAM MAGMA!\p"
	.string "It burns me up that they'd use such\n"
	.string "a confusing name!$"

MtChimney_Text_DouseThemInFire::
# 250 "data/maps/MtChimney/scripts.pory"
	.string "Yeah!\n"
	.string "Douse them in fire!$"

MtChimney_Text_PlayerLeftMeteorite::
# 254 "data/maps/MtChimney/scripts.pory"
	.string "{PLAYER} left the METEORITE where\n"
	.string "it was.$"

MtChimney_Text_MeteoriteWillActivateVolcano::
# 258 "data/maps/MtChimney/scripts.pory"
	.string "The power contained in the METEORITE…\p"
	.string "By amplifying its power with this\n"
	.string "machine, MT. CHIMNEY's volcanic\l"
	.string "activity will instantly intensify…\p"
	.string "Its energy will grow deep inside\n"
	.string "the crater and…\l"
	.string "Fufufu…$"

MtChimney_Text_ArchieGoStopTeamMagma::
# 262 "data/maps/MtChimney/scripts.pory"
	.string "ARCHIE: Grr, {PLAYER}!\n"
	.string "I should've guessed you'd show up!\p"
	.string "See for yourself what the fanatics\n"
	.string "of TEAM MAGMA are up to!\p"
	.string "They're trying to inject the stolen\n"
	.string "METEORITE's power into the volcano!\p"
	.string "Doing something like that will cause\n"
	.string "the volcano's eruption!$"

MtChimney_Text_MagmaOutnumbersUs::
# 266 "data/maps/MtChimney/scripts.pory"
	.string "Darn… TEAM MAGMA outnumbers us!\n"
	.string "We can't keep up with them!$"

MtChimney_Text_MetoriteFittedOnMachine::
# 270 "data/maps/MtChimney/scripts.pory"
	.string "A METEORITE is fitted on a mysterious\n"
	.string "machine…\p"
	.string "The machine seems to be storing\n"
	.string "energy in the METEORITE.$"

MtChimney_Text_OhFineThen::
# 274 "data/maps/MtChimney/scripts.pory"
	.string "Oh, fine then.$"

MtChimney_Text_Bushaa::
# 278 "data/maps/MtChimney/scripts.pory"
	.string "Bushaa!$"

MtChimney_Text_MachineMakesNoResponse::
# 282 "data/maps/MtChimney/scripts.pory"
	.string "This mysterious machine…\n"
	.string "It makes no response whatsoever.$"

MtChimney_Text_AquasNameSimilar::
# 286 "data/maps/MtChimney/scripts.pory"
	.string "We're TEAM MAGMA!\p"
	.string "They're TEAM AQUA!\p"
	.string "It totally annoys me that they'd\n"
	.string "use a name like ours!$"

MtChimney_Text_MeteoritesPackAmazingPower::
# 290 "data/maps/MtChimney/scripts.pory"
	.string "METEORITES pack amazing power!$"

MtChimney_Text_LavaCookiesJust200::
# 294 "data/maps/MtChimney/scripts.pory"
	.string "LAVA COOKIES are MT. CHIMNEY's local\n"
	.string "specialty.\p"
	.string "Try one. It's just ¥200.$"

MtChimney_Text_LessHabitatForWaterPokemon::
# 298 "data/maps/MtChimney/scripts.pory"
	.string "If they expand the land, there'll be\n"
	.string "less habitats for WATER POKéMON!$"

MtChimney_Text_ArchieIHaveMyHandsFull::
# 302 "data/maps/MtChimney/scripts.pory"
	.string "ARCHIE: Grrr…\p"
	.string "I want to stop that MAXIE,\n"
	.string "but I can't!\p"
	.string "Not when I have my hands full battling\n"
	.string "three opponents at once!$"

MtChimney_Text_TeamAquaAlwaysMessingWithPlans::
# 306 "data/maps/MtChimney/scripts.pory"
	.string "That annoying TEAM AQUA…\n"
	.string "They always mess with our plans!$"

MtChimney_Text_ShelbyRegister::
# 310 "data/maps/MtChimney/scripts.pory"
	.string "Thank you, child. It was fun, as if\n"
	.string "I were battling my own grandchild.\p"
	.string "Please, come see me again for\n"
	.string "a rematch.$"

MtChimney_Text_ShelbyPostRematch::
# 314 "data/maps/MtChimney/scripts.pory"
	.string "Perhaps your heart has become one\n"
	.string "with the hearts of your POKéMON.$"

MtChimney_Text_SawyerPostRematch::
# 318 "data/maps/MtChimney/scripts.pory"
	.string "Actually, it really is hot here.\n"
	.string "I'm overdressed for these parts.$"

MtChimney_Text_YouBetterNotMessWithUs::
# 322 "data/maps/MtChimney/scripts.pory"
	.string "You'd better not mess with us!\p"
	.string "We're trying to awaken that thing\n"
	.string "for the benefit of everyone!$"

MtChimney_Text_KeepMakingMoreLand::
# 326 "data/maps/MtChimney/scripts.pory"
	.string "We're going to keep making more land!$"

MtChimney_Text_Bufoh::
# 330 "data/maps/MtChimney/scripts.pory"
	.string "Bufoh!$"

MtChimney_Text_YouveNotGotTheMoney::
# 334 "data/maps/MtChimney/scripts.pory"
	.string "Oh, dear. You can't buy a thing if\n"
	.string "you've not got the money.$"
