MtChimney_MapScripts::
# 2 "data/maps/MtChimney/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MtChimney_OnResume
# 3 "data/maps/MtChimney/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtChimney_OnTransition
	.byte 0


MtChimney_MapScripts::
# 7 "data/maps/MtChimney/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MtChimney_OnResume
# 8 "data/maps/MtChimney/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtChimney_OnTransition
	return


MtChimney_Text_MeteoriteWillActivateVolcano::
# 12 "data/maps/MtChimney/scripts.pory"
	.string "The power contained in the METEORITE…\p"
	.string "By amplifying its power with this\n"
	.string "machine, MT. CHIMNEY's volcanic\l"
	.string "activity will instantly intensify…\p"
	.string "Its energy will grow deep inside the\n"
	.string "crater and…\l"
	.string "Fufufu…$"

MtChimney_Text_MaxieIntro::
# 16 "data/maps/MtChimney/scripts.pory"
	.string "MAXIE: Hm? Who are you?\p"
	.string "… … … … … … … … … … … …\p"
	.string "I'd heard ARCHIE bemoaning a child\n"
	.string "who's been meddling in TEAM AQUA's\l"
	.string "affairs.\p"
	.string "It must be you he meant.\p"
	.string "Humph! So you're thinking of\n"
	.string "interfering with us, TEAM MAGMA?\p"
	.string "Now you listen. Long ago, living things\n"
	.string "used the\l"
	.string "land to live and grow.\p"
	.string "That is why land is all important! It is\n"
	.string "the cradle of all!\p"
	.string "That is why TEAM MAGMA is dedicated to\n"
	.string "the expansion of the land mass.\p"
	.string "It is for further advancement of\n"
	.string "humankind and POKéMON!\p"
	.string "And for that, we need the power of what\n"
	.string "sleeps within this mountain…\p"
	.string "Oh! There was no need for you to learn\n"
	.string "that much.\p"
	.string "But, no matter! I'll teach you the\n"
	.string "consequences of\l"
	.string "meddling in our grand design!$"

MtChimney_Text_MaxieDefeat::
# 20 "data/maps/MtChimney/scripts.pory"
	.string "What?!\p"
	.string "I, MAXIE, was caught off guard?!$"

MtChimney_Text_MaxieYouHaventSeenLastOfMagma::
# 24 "data/maps/MtChimney/scripts.pory"
	.string "MAXIE: But, enough. I will back off this\n"
	.string "time.\p"
	.string "But don't think that this is the last\n"
	.string "you've seen of TEAM MAGMA.\p"
	.string "Fufufu…\p"
	.string "Even without the METEORITE, if we\n"
	.string "obtain that ORB… Fufufu…$"

MtChimney_Text_TabithaIntro::
# 28 "data/maps/MtChimney/scripts.pory"
	.string "Hehehe!\p"
	.string "So you've come all the way here!\p"
	.string "But you're too late! I've already\n"
	.string "delivered the METEORITE\l"
	.string "from METEOR FALLS to the BOSS!$"

MtChimney_Text_TabithaDefeat::
# 32 "data/maps/MtChimney/scripts.pory"
	.string "Hehehe…\p"
	.string "Even though I've lost, if our leader\n"
	.string "awakens that thing…$"

MtChimney_Text_TabithaPostBattle::
# 36 "data/maps/MtChimney/scripts.pory"
	.string "BOSS, hurry! Give it the METEORITE's\n"
	.string "energy!\p"
	.string "Hehehe…$"

MtChimney_Text_Grunt2Intro::
# 40 "data/maps/MtChimney/scripts.pory"
	.string "We of TEAM MAGMA are working hard for\n"
	.string "everyone's sake.\p"
	.string "Like, if that thing's power made more\n"
	.string "land, there'd be more places to live.\p"
	.string "Everyone'd be happy!$"

MtChimney_Text_Grunt2Defeat::
# 44 "data/maps/MtChimney/scripts.pory"
	.string "Hunh? What do you mean I lost?$"

MtChimney_Text_Grunt2PostBattle::
# 48 "data/maps/MtChimney/scripts.pory"
	.string "Our BOSS says, “It will make everyone\n"
	.string "happy.”\p"
	.string "But why does everyone keep getting in\n"
	.string "our way?$"

MtChimney_Text_Grunt1Intro::
# 52 "data/maps/MtChimney/scripts.pory"
	.string "If there were more land, I'd be able to\n"
	.string "get a big house of my own!\p"
	.string "I'm going to build it on hardened lava!$"

MtChimney_Text_Grunt1Defeat::
# 56 "data/maps/MtChimney/scripts.pory"
	.string "My dream of a big house…$"

MtChimney_Text_Grunt1PostBattle::
# 60 "data/maps/MtChimney/scripts.pory"
	.string "A kid like you, you ought to be\n"
	.string "splashing about in the waves!$"

MtChimney_Text_TeamAquaAlwaysMessingWithPlans::
# 64 "data/maps/MtChimney/scripts.pory"
	.string "That annoying TEAM AQUA… They always\n"
	.string "mess with our plans!$"

MtChimney_Text_MeteoritesPackAmazingPower::
# 68 "data/maps/MtChimney/scripts.pory"
	.string "METEORITES pack amazing power!$"

MtChimney_Text_YouBetterNotMessWithUs::
# 72 "data/maps/MtChimney/scripts.pory"
	.string "You'd better not mess with us!\p"
	.string "We're trying to awaken that thing for\n"
	.string "the benefit of everyone!$"

MtChimney_Text_AquasNameSimilar::
# 76 "data/maps/MtChimney/scripts.pory"
	.string "We're TEAM MAGMA!\p"
	.string "They're TEAM AQUA!\p"
	.string "It totally annoys me that they'd use a\n"
	.string "name like ours!$"

MtChimney_Text_DouseThemInFire::
# 80 "data/maps/MtChimney/scripts.pory"
	.string "Yeah! Douse them in fire!$"

MtChimney_Text_KeepMakingMoreLand::
# 84 "data/maps/MtChimney/scripts.pory"
	.string "We're going to keep making more land!$"

MtChimney_Text_Bufoh::
# 88 "data/maps/MtChimney/scripts.pory"
	.string "Bufoh!$"

MtChimney_Text_ArchieGoStopTeamMagma::
# 92 "data/maps/MtChimney/scripts.pory"
	.string "ARCHIE: Grr, {PLAYER}! I should've\n"
	.string "guessed you'd show up!\p"
	.string "See for yourself what the fanatics of\n"
	.string "TEAM MAGMA are up to!\p"
	.string "They're trying to inject the stolen\n"
	.string "METEORITE's power into the volcano!\p"
	.string "Doing something like that will cause the\n"
	.string "volcano's eruption!$"

MtChimney_Text_ArchieIHaveMyHandsFull::
# 96 "data/maps/MtChimney/scripts.pory"
	.string "ARCHIE: Grrr…\p"
	.string "I want to stop that MAXIE, but I can't!\p"
	.string "Not when I have my hands full battling\n"
	.string "three opponents at once!$"

MtChimney_Text_ArchieThankYou::
# 100 "data/maps/MtChimney/scripts.pory"
	.string "ARCHIE: {PLAYER}! Thank you!\p"
	.string "With your help, we thwarted TEAM\n"
	.string "MAGMA's destructive plan!\p"
	.string "But… You… Whose side are you on?\p"
	.string "Ah, it doesn't matter.\p"
	.string "We will remain vigilant and keep up our\n"
	.string "pursuit of TEAM MAGMA.\p"
	.string "{PLAYER}, we shall meet again!$"

MtChimney_Text_MagmaOutnumbersUs::
# 104 "data/maps/MtChimney/scripts.pory"
	.string "Darn… TEAM MAGMA outnumbers us! We\n"
	.string "can't keep up with them!$"

MtChimney_Text_LessHabitatForWaterPokemon::
# 108 "data/maps/MtChimney/scripts.pory"
	.string "If they expand the land, there'll be\n"
	.string "less habitats for WATER POKéMON!$"

MtChimney_Text_MagmasNameSimilar::
# 112 "data/maps/MtChimney/scripts.pory"
	.string "We're TEAM AQUA!\p"
	.string "They're TEAM MAGMA!\p"
	.string "It burns me up that they'd use such a\n"
	.string "confusing name!$"

MtChimney_Text_Bushaa::
# 116 "data/maps/MtChimney/scripts.pory"
	.string "Bushaa!$"

MtChimney_Text_LavaCookiesJust200::
# 120 "data/maps/MtChimney/scripts.pory"
	.string "LAVA COOKIES are MT. CHIMNEY's local\n"
	.string "specialty.\p"
	.string "Try one. It's just ¥200.$"

MtChimney_Text_ThankYouDear::
# 124 "data/maps/MtChimney/scripts.pory"
	.string "Thank you, dear!$"

MtChimney_Text_YouveNotGotTheMoney::
# 128 "data/maps/MtChimney/scripts.pory"
	.string "Oh, dear. You can't buy a thing if you've\n"
	.string "not got the money.$"

MtChimney_Text_OhFineThen::
# 132 "data/maps/MtChimney/scripts.pory"
	.string "Oh, fine then.$"

MtChimney_Text_MetoriteFittedOnMachine::
# 136 "data/maps/MtChimney/scripts.pory"
	.string "A METEORITE is fitted on a mysterious\n"
	.string "machine…\p"
	.string "The machine seems to be storing energy\n"
	.string "in the METEORITE.$"

MtChimney_Text_RemoveTheMeteorite::
# 140 "data/maps/MtChimney/scripts.pory"
	.string "A METEORITE is fitted on a mysterious\n"
	.string "machine…\p"
	.string "Do you want to remove the METEORITE?$"

MtChimney_Text_PlayerRemovedMeteorite::
# 144 "data/maps/MtChimney/scripts.pory"
	.string "{PLAYER} removed the METEORITE from\n"
	.string "the mysterious machine.$"

MtChimney_Text_PlayerLeftMeteorite::
# 148 "data/maps/MtChimney/scripts.pory"
	.string "{PLAYER} left the METEORITE where it\n"
	.string "was.$"

MtChimney_Text_MachineMakesNoResponse::
# 152 "data/maps/MtChimney/scripts.pory"
	.string "This mysterious machine… It makes no\n"
	.string "response whatsoever.$"

MtChimney_Text_RouteSign::
# 156 "data/maps/MtChimney/scripts.pory"
	.string "{DOWN_ARROW} JAGGED PATH LAVARIDGE TOWN AHEAD$"

MtChimney_Text_ShelbyIntro::
# 160 "data/maps/MtChimney/scripts.pory"
	.string "I've been to the hot springs and\n"
	.string "refreshed my tired bones.\l"
	.string "Right now I'm feeling strong!$"

MtChimney_Text_ShelbyDefeat::
# 164 "data/maps/MtChimney/scripts.pory"
	.string "Oh, my goodness. Now, aren't you\n"
	.string "something!$"

MtChimney_Text_ShelbyPostBattle::
# 168 "data/maps/MtChimney/scripts.pory"
	.string "Well, well, I've lost. I can't call myself\n"
	.string "an EXPERT now, can I?$"

MtChimney_Text_ShelbyRegister::
# 172 "data/maps/MtChimney/scripts.pory"
	.string "Thank you, child. It was fun, as if I\n"
	.string "were battling my own grandchild.\p"
	.string "Please, come see me again for a rematch.$"

MtChimney_Text_ShelbyRematchIntro::
# 176 "data/maps/MtChimney/scripts.pory"
	.string "If you can mesh your heart with those\n"
	.string "of your POKéMON, why, you should be\l"
	.string "able to achieve great things.$"

MtChimney_Text_ShelbyRematchDefeat::
# 180 "data/maps/MtChimney/scripts.pory"
	.string "Oh, my goodness. Now, aren't you\n"
	.string "something!$"

MtChimney_Text_ShelbyPostRematch::
# 184 "data/maps/MtChimney/scripts.pory"
	.string "Perhaps your heart has become one with\n"
	.string "the hearts of your POKéMON.$"

MtChimney_Text_MelissaIntro::
# 188 "data/maps/MtChimney/scripts.pory"
	.string "I've got the fire in me, baby. I can't\n"
	.string "stand it! I have to battle!$"

MtChimney_Text_MelissaDefeat::
# 192 "data/maps/MtChimney/scripts.pory"
	.string "Ooh, that was a scorching-hot match!$"

MtChimney_Text_MelissaPostBattle::
# 196 "data/maps/MtChimney/scripts.pory"
	.string "The heat of MT. CHIMNEY warms me up,\n"
	.string "baby!$"

MtChimney_Text_SheilaIntro::
# 200 "data/maps/MtChimney/scripts.pory"
	.string "I've finally made it to MT. CHIMNEY. I\n"
	.string "want to make my POKéMON battle!$"

MtChimney_Text_SheilaDefeat::
# 204 "data/maps/MtChimney/scripts.pory"
	.string "The way you battle… It's like a MT.\n"
	.string "CHIMNEY eruption!$"

MtChimney_Text_SheilaPostBattle::
# 208 "data/maps/MtChimney/scripts.pory"
	.string "Like I said, I've finally made it to MT.\n"
	.string "CHIMNEY. It would be a shame if\l"
	.string "I only do a little sightseeing…\p"
	.string "I want to get in some battles and buy\n"
	.string "COOKIES as souvenirs.$"

MtChimney_Text_ShirleyIntro::
# 212 "data/maps/MtChimney/scripts.pory"
	.string "Since I bathed in the hot springs, I've\n"
	.string "been feeling great!\l"
	.string "I'm sure I'm going to win!$"

MtChimney_Text_ShirleyDefeat::
# 216 "data/maps/MtChimney/scripts.pory"
	.string "Yowch! I'm getting a chill out of the\n"
	.string "water.$"

MtChimney_Text_ShirleyPostBattle::
# 220 "data/maps/MtChimney/scripts.pory"
	.string "I'll have to take another dip in the hot\n"
	.string "springs. Want to join me?\p"
	.string "Just joking!$"

MtChimney_Text_SawyerIntro::
# 224 "data/maps/MtChimney/scripts.pory"
	.string "This is one fine mountain! Plenty of hot\n"
	.string "people around for company!$"

MtChimney_Text_SawyerDefeat::
# 228 "data/maps/MtChimney/scripts.pory"
	.string "Oh, you're a real firebrand, too!$"

MtChimney_Text_SawyerPostBattle::
# 232 "data/maps/MtChimney/scripts.pory"
	.string "I think I need a dip in LAVARIDGE HOT\n"
	.string "SPRING with the locals!$"

MtChimney_Text_SawyerRegister::
# 236 "data/maps/MtChimney/scripts.pory"
	.string "I like little fireballs like you. Let me\n"
	.string "register you in my POKéNAV.$"

MtChimney_Text_SawyerRematchIntro::
# 240 "data/maps/MtChimney/scripts.pory"
	.string "I'm happily surrounded by hot people\n"
	.string "around these parts. I won't lose!$"

MtChimney_Text_SawyerRematchDefeat::
# 244 "data/maps/MtChimney/scripts.pory"
	.string "Gosh, you're still the same firebrand as\n"
	.string "before!$"

MtChimney_Text_SawyerPostRematch::
# 248 "data/maps/MtChimney/scripts.pory"
	.string "Actually, it really is hot here. I'm\n"
	.string "overdressed for these parts.$"
