MossdeepCity_House4_MapScripts::
	.byte 0


MossdeepCity_House4_MapScripts::
	return


MossdeepCity_House4_Text_BrotherLikesToFindBases::
# 8 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "My little brother says he likes to go\n"
	.string "find people's SECRET BASES.$"

MossdeepCity_House4_Text_BrotherLikesToVisitBasesAndBattle::
# 12 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "My little brother says he likes to visit\n"
	.string "people's SECRET BASES and have\l"
	.string "POKéMON battles.$"

MossdeepCity_House4_Text_YouMadeSecretBaseNearX::
# 16 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "Was it you who made a SECRET BASE near\n"
	.string "{STR_VAR_1}?$"

MossdeepCity_House4_Text_MakeSecretBase::
# 20 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "You should make a SECRET BASE\n"
	.string "somewhere. I'll go find it!$"

MossdeepCity_House4_Text_Skitty::
# 24 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "SKITTY: Miyaan?$"
