MossdeepCity_House4_MapScripts::
	.byte 0


MossdeepCity_House4_EventScript_NinjaBoy::
	end


MossdeepCity_House4_EventScript_Skitty::
# 9 "data/maps/MossdeepCity_House4/scripts.pory"
	msgbox MossdeepCity_House4_Text_Skitty, MSGBOX_DEFAULT
	end


MossdeepCity_House4_EventScript_Woman::
	end


MossdeepCity_House4_Text_MakeSecretBase::
# 17 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "You should make a SECRET BASE\n"
	.string "somewhere. I'll go find it!$"

MossdeepCity_House4_Text_Skitty::
# 21 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "SKITTY: Miyaan?$"

MossdeepCity_House4_Text_BrotherLikesToVisitBasesAndBattle::
# 25 "data/maps/MossdeepCity_House4/scripts.pory"
	.string "My little brother says he likes to\n"
	.string "visit people's SECRET BASES and have\l"
	.string "POKéMON battles.$"
