SSAnne_B1F_Room5_MapScripts::
	.byte 0


SSAnne_B1F_Room5_EventScript_Boy::
# 5 "data/maps/SSAnne_B1F_Room5/scripts.pory"
	msgbox SSAnne_B1F_Room5_Text_MachokeHasStrengthToMoveRocks, MSGBOX_NPC
	end


SSAnne_B1F_Room5_EventScript_ItemSuperPotion::
	end


SSAnne_B1F_Room5_EventScript_Machoke::
	end


SSAnne_B1F_Room5_Text_MachokeHasStrengthToMoveRocks::
# 18 "data/maps/SSAnne_B1F_Room5/scripts.pory"
	.string "My buddy MACHOKE is super strong!\p"
	.string "He has enough STRENGTH to move\n"
	.string "big rocks!$"
