BattleFrontier_Lounge3_MapScripts::
# 2 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, BattleFrontier_Lounge3_OnLoad
	.byte 0


# 5 "data/maps/BattleFrontier_Lounge3/scripts.pory"

# 6 "data/maps/BattleFrontier_Lounge3/scripts.pory"

# 7 "data/maps/BattleFrontier_Lounge3/scripts.pory"
BattleFrontier_Lounge3_OnLoad::
# 8 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.set BET_AMOUNT_5,  5
# 9 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.set BET_AMOUNT_10, 10
# 10 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.set BET_AMOUNT_15, 15

BattleFrontier_Lounge3_Text_CantYouSeeWereBusyHere::
# 14 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "…What's that you want?\p"
	.string "Can't you see we're kind of busy here?\n"
	.string "Can't your business wait till later?$"

BattleFrontier_Lounge3_Text_YouLookToughExplainGambling::
# 18 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "…Huh? You look to me like a tough\n"
	.string "TRAINER.\p"
	.string "Heheh… Listen, I have this proposition.\p"
	.string "We have a little group going here, and\n"
	.string "we play a little game with what\l"
	.string "goes on in the BATTLE FRONTIER.\p"
	.string "The rules are really simple.\p"
	.string "First, we pick one of the facilities in\n"
	.string "the BATTLE FRONTIER.\p"
	.string "Then, we each pick a different TRAINER\n"
	.string "who's taking that facility's challenge,\l"
	.string "and bet with our Battle Points.\p"
	.string "The guy who bet on the TRAINER with the\n"
	.string "best record takes all the Battle\l"
	.string "Points in the pool.\p"
	.string "Sounds simple, huh? So, anyway…$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerSingle::
# 22 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be challenging the BATTLE\l"
	.string "TOWER's SINGLE BATTLE ROOMS.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerDouble::
# 26 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be challenging the BATTLE\l"
	.string "TOWER's DOUBLE BATTLE ROOMS.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleTowerMulti::
# 30 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be challenging the BATTLE\l"
	.string "TOWER's MULTI BATTLE ROOMS.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeSingle::
# 34 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "DOME's SINGLE BATTLE Tourney.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleDomeDouble::
# 38 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "DOME's DOUBLE BATTLE Tourney.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactorySingle::
# 42 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "FACTORY's Battle Swap Single Tourney.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleFactoryDouble::
# 46 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "FACTORY's Battle Swap Double Tourney.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceSingle::
# 50 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be challenging the BATTLE\l"
	.string "PALACE's SINGLE BATTLE HALLS.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePalaceDouble::
# 54 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be challenging the BATTLE\l"
	.string "PALACE's DOUBLE BATTLE HALLS.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattleArena::
# 58 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "ARENA's Set KO Tourney.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePike::
# 62 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE PIKE's\l"
	.string "Battle Choice.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_ChallengeBattlePyramid::
# 66 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "What I'm looking for is a TRAINER who's\n"
	.string "going to be entering the BATTLE\l"
	.string "PYRAMID's Battle Quest.\p"
	.string "But so far, I haven't seen a TRAINER\n"
	.string "that has that winning quality.$"

BattleFrontier_Lounge3_Text_HowAboutEnteringEventForMe::
# 70 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "I'll see to it that you benefit, too. So\n"
	.string "how about it?\l"
	.string "How about entering that event for me?$"

BattleFrontier_Lounge3_Text_SpotMeSomeBattlePoints::
# 74 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "All right, that's perfect. So, uh… How\n"
	.string "about spotting me some\l"
	.string "of your Battle Points?\p"
	.string "Trust me, I'll show you my gratitude\n"
	.string "afterward.$"

BattleFrontier_Lounge3_Text_HowMuchCanYouSpot::
# 78 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Great, great! So, how much can you spot\n"
	.string "me?$"

BattleFrontier_Lounge3_Text_YouDontHaveEnoughPoints::
# 82 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Oh, no, no, no! You don't have enough\n"
	.string "Battle Points!\p"
	.string "I wish you wouldn't monkey around and\n"
	.string "waste everyone's time!$"

BattleFrontier_Lounge3_Text_ThanksOffYouGo::
# 86 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Heheh! Thanks much! So, off you go!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerSingle::
# 90 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE TOWER's SINGLE\n"
	.string "BATTLE ROOMS pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerDouble::
# 94 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE TOWER's DOUBLE\n"
	.string "BATTLE ROOMS pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleTowerMulti::
# 98 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE TOWER's MULTI BATTLE\n"
	.string "ROOMS pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeSingle::
# 102 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE DOME's SINGLE BATTLE\n"
	.string "Tourney pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleDomeDouble::
# 106 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE DOME's DOUBLE BATTLE\n"
	.string "Tourney pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleFactorySingle::
# 110 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE FACTORY's Battle\n"
	.string "Swap Single Tourney pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleFactoryDouble::
# 114 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE FACTORY's Battle\n"
	.string "Swap Double Tourney pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceSingle::
# 118 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE PALACE's SINGLE\n"
	.string "BATTLE HALLS pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattlePalaceDouble::
# 122 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE PALACE's DOUBLE\n"
	.string "BATTLE HALLS pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattleArena::
# 126 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE ARENA's Set KO\n"
	.string "Tourney pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattlePike::
# 130 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE PIKE's Battle Choice\n"
	.string "pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_GetToBattlePyramid::
# 134 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Get to the BATTLE PYRAMID's Battle\n"
	.string "Quest pronto!\p"
	.string "It's a must-win situation! Don't blow\n"
	.string "your chance!\l"
	.string "Both of our futures depend on you!$"

BattleFrontier_Lounge3_Text_NiceTryCantReturnPoints::
# 138 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Oh, it's you… Nice try…\p"
	.string "I hate to break it to you, but I can't\n"
	.string "return your Battle Points…\p"
	.string "I guess we'll have to let it motivate us\n"
	.string "to try harder next time!$"

BattleFrontier_Lounge3_Text_HelloChampHeresYourPoints::
# 142 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Oh, yes! Hello there, champ!\p"
	.string "I knew you could! I knew you would!\l"
	.string "We're both big winners!\p"
	.string "I'll return your Battle Points and, of\n"
	.string "course, a little extra from me!$"

BattleFrontier_Lounge3_Text_ObtainedBattlePoints::
# 146 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "{PLAYER} obtained {STR_VAR_1}\n"
	.string "Battle Points.$"

BattleFrontier_Lounge3_Text_ThinkOfMeForAnotherChallenge::
# 150 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "If you're up for another challenge,\n"
	.string "please do think of me!$"

BattleFrontier_Lounge3_Text_NotInterested::
# 154 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Not interested?! You shouldn't be so\n"
	.string "afraid to take a chance!$"

BattleFrontier_Lounge3_Text_Oh::
# 158 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Oh…$"

BattleFrontier_Lounge3_Text_BackedWrongTrainer::
# 162 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "I backed the wrong TRAINER again!\p"
	.string "Maybe I should be battling normally like\n"
	.string "everyone else…$"

BattleFrontier_Lounge3_Text_TrainerGoodButRattled::
# 166 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "That TRAINER…\p"
	.string "He's good, but he gets rattled too\n"
	.string "easily to survive the BATTLE DOME…$"

BattleFrontier_Lounge3_Text_KnowWinnerWhenISeeOne::
# 170 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Giggle! I know a winner when I see one!$"

BattleFrontier_Lounge3_Text_ShouldBeTakingChallenges::
# 174 "data/maps/BattleFrontier_Lounge3/scripts.pory"
	.string "Those TRAINERS… What are they doing?\l"
	.string "They should be taking challenges.$"
