EverGrandeCity_MapScripts::
# 2 "data/maps/EverGrandeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_OnTransition
	.byte 0


EverGrandeCity_MapScripts::
# 6 "data/maps/EverGrandeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_OnTransition
	return


EverGrandeCity_Text_EnteringVictoryRoad::
# 10 "data/maps/EverGrandeCity/scripts.pory"
	.string "ENTERING VICTORY ROAD$"

EverGrandeCity_Text_EnteringPokemonLeague::
# 14 "data/maps/EverGrandeCity/scripts.pory"
	.string "ENTERING POKéMON LEAGUE CENTER GATE$"

EverGrandeCity_Text_CitySign::
# 18 "data/maps/EverGrandeCity/scripts.pory"
	.string "EVER GRANDE CITY\p"
	.string "“The paradise of flowers, the sea, and\n"
	.string "POKéMON.”$"
