Route206_North_MapScripts::
	.byte 0


Route206_North_EventScript_SmithNPC1::
# 5 "data/maps/Route206_North/scripts.pory"
	msgbox Route206_North_Text_SmithNPC1, MSGBOX_NPC
	end


Route206_North_EventScript_SmithNPC2::
# 14 "data/maps/Route206_North/scripts.pory"
	msgbox Route206_North_Text_SmithNPC2, MSGBOX_NPC
	end


Route206_North_EventScript_SmithNPC3::
# 23 "data/maps/Route206_North/scripts.pory"
	msgbox Route206_North_Text_SmithNPC3, MSGBOX_NPC
	end


Route206_North_Text_SmithNPC1::
# 9 "data/maps/Route206_North/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route206_North_Text_SmithNPC2::
# 18 "data/maps/Route206_North/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route206_North_Text_SmithNPC3::
# 27 "data/maps/Route206_North/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
