RustboroCity_DevonCorp_2F_MapScripts::
# 2 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RustboroCity_DevonCorp_2F_OnTransition
	.byte 0


RustboroCity_DevonCorp_2F_Text_DeviceForTalkingToPokemon::
# 6 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "We're developing a device for talking\n"
	.string "with POKMON.\p"
	.string "But we haven't had much success$"

RustboroCity_DevonCorp_2F_Text_DevelopingNewBalls::
# 10 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "I'm developing new kinds of POK BALLS\p"
	.string "But I haven't made much headway$"

RustboroCity_DevonCorp_2F_Text_WeFinallyMadeNewBalls::
# 14 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "We finally made new kinds of POK BALLS!\p"
	.string "The REPEAT BALL makes it easier to\n"
	.string "catch POKMON you've caught before.\p"
	.string "The TIMER BALL gets better at catching\n"
	.string "POKMON the longer a battle runs.\p"
	.string "Both are proudly developed by the\n"
	.string "DEVON CORPORATION.\p"
	.string "Please give them a try!$"

RustboroCity_DevonCorp_2F_Text_IMadePokenav::
# 18 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "I made the POKNAV!\p"
	.string "As an engineer, I feel blessed to have\n"
	.string "made something so great!$"

RustboroCity_DevonCorp_2F_Text_WowThatsAPokenav::
# 22 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Oh, wow! That's a POKNAV!\p"
	.string "It came about as a result of our\n"
	.string "PRESIDENT's desire to learn about\l"
	.string "the feelings of POKMON.\p"
	.string "Would you like me to describe its\n"
	.string "features in detail?\p"
	.string "No, no. I think you'll find out just by\n"
	.string "trying the POKNAV out.$"

RustboroCity_DevonCorp_2F_Text_DeviceToVisualizePokemonDreams::
# 26 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "I'm trying to develop a device that\n"
	.string "visually reproduces the dreams of\l"
	.string "POKMON\p"
	.string "But it's not going well.$"

RustboroCity_DevonCorp_2F_Text_DevelopDeviceToResurrectFossils::
# 30 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "I've been trying to develop a device\n"
	.string "that resurrects POKMON from fossils\p"
	.string "And, it's working!$"

RustboroCity_DevonCorp_2F_Text_WantToBringFossilBackToLife::
# 34 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Wait! That thing you have there Is that\n"
	.string "a POKMON fossil?\p"
	.string "Would you like to bring that POKMON\n"
	.string "back to life?\p"
	.string "I can with my newly developed FOSSIL\n"
	.string "REGENERATOR.$"

RustboroCity_DevonCorp_2F_Text_OhIsThatSo::
# 38 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Oh, is that so?\p"
	.string "DEVON's technological expertise is\n"
	.string "outstanding, I tell you.$"

RustboroCity_DevonCorp_2F_Text_TwoFossilsPickOne::
# 42 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Oh, now that's a surprise! You have not\n"
	.string "one, but two, fossils?\p"
	.string "Unfortunately, my machine can only\n"
	.string "regenerate one POKMON at a time.\p"
	.string "Would you like to pick one of your\n"
	.string "fossils for regeneration?$"

RustboroCity_DevonCorp_2F_Text_HandedFossilToResearcher::
# 46 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Excellent! Let's do this right away.\p"
	.string "{PLAYER} handed the {STR_VAR_1}\n"
	.string "to the DEVON RESEARCHER.$"

RustboroCity_DevonCorp_2F_Text_FossilRegeneratorTakesTime::
# 50 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "The FOSSIL REGENERATOR, which I made,\n"
	.string "is incredible.\p"
	.string "But it has one drawback--it takes a\n"
	.string "long time to work.\p"
	.string "So, uh How about you go for a stroll and\n"
	.string "look around for a while?$"

RustboroCity_DevonCorp_2F_Text_FossilizedMonBroughtBackToLife::
# 54 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Thanks for waiting!\p"
	.string "Your fossilized POKMON has been\n"
	.string "brought back to life!\p"
	.string "The fossil was an ancient POKMON.\n"
	.string "{STR_VAR_2}, it was!$"

RustboroCity_DevonCorp_2F_Text_ReceivedMonFromResearcher::
# 58 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "{PLAYER} received {STR_VAR_2}\n"
	.string "from the DEVON RESEARCHER.$"

RustboroCity_DevonCorp_2F_Text_TooManyPokemon::
# 62 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Uh-oh, you've got too many POKMON. You\n"
	.string "have no room for this one.$"

RustboroCity_DevonCorp_2F_Text_DevelopNewPokenavFeature::
# 66 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "I'm trying to develop a new feature for\n"
	.string "the POKNAV\p"
	.string "But it's not going well.$"

RustboroCity_DevonCorp_2F_Text_WhatToWorkOnNext::
# 70 "data/maps/RustboroCity_DevonCorp_2F/scripts.pory"
	.string "Well, now what shall I work on\n"
	.string "developing next?\p"
	.string "Our company allows us to make our\n"
	.string "inspirations into reality.\p"
	.string "One couldn't ask for a better\n"
	.string "environment as an engineer.$"
