PewterCity_Museum_1F_MapScripts::
	.byte 0

PewterCity_Museum_1F_EventScript_AerodactylFossil::
	msgbox PewterCity_Museum_1F_Text_AerodactylFossil, MSGBOX_SIGN
	end

PewterCity_Museum_1F_EventScript_KabutopsFossil::
	msgbox PewterCity_Museum_1F_Text_KabutopsFossil, MSGBOX_SIGN
	end

PewterCity_Museum_1F_Text_AerodactylFossil::
    .string "AERODACTYL: An ancient flying pokémon$"

PewterCity_Museum_1F_Text_KabutopsFossil::
    .string "KABUTO: An ancient scuttling pokémon$"
