PewterCity_Museum_1F_MapScripts::
	.byte 0


PewterCity_Museum_1F_Text_Its50YForChildsTicket::
# 5 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Yes, yes. It's ¥50 for a child's ticket.\p"
	.string "Would you like to come in?$"

PewterCity_Museum_1F_Text_ComeAgain::
# 9 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Come again!$"

PewterCity_Museum_1F_Text_Right50YThankYou::
# 13 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Right, ¥50! Thank you!$"

PewterCity_Museum_1F_Text_DontHaveEnoughMoney::
# 17 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "You don't have enough money.$"

PewterCity_Museum_1F_Text_PleaseEnjoyYourself::
# 21 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Please enjoy yourself.$"

PewterCity_Museum_1F_Text_DoYouKnowWhatAmberIs::
# 25 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "You can't sneak in the back way! Nice\n"
	.string "try, kid, but no.\p"
	.string "Oh, whatever! Do you know what AMBER\n"
	.string "is?$"

PewterCity_Museum_1F_Text_AmberContainsGeneticMatter::
# 29 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "AMBER contains the genetic matter of\n"
	.string "ancient POKéMON.\p"
	.string "There's a LAB somewhere trying to\n"
	.string "resurrect POKéMON from AMBER.$"

PewterCity_Museum_1F_Text_AmberIsFossilizedSap::
# 33 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "AMBER is actually sap, that gooey stuff\n"
	.string "that oozes from trees.\p"
	.string "The ancient sap fossilized over time to\n"
	.string "become rock-hard AMBER.$"

PewterCity_Museum_1F_Text_PleaseGoAround::
# 37 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "あちらへ　おまわりください$"

PewterCity_Museum_1F_Text_ShouldBeGratefulForLongLife::
# 41 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "I should be grateful for my long life.\p"
	.string "Never did I think I would get to see the\n"
	.string "bones of a dragon!$"

PewterCity_Museum_1F_Text_WantYouToGetAmberExamined::
# 45 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Ssh! Listen, I need to share a secret\n"
	.string "with someone.\p"
	.string "I think that this chunk of AMBER\n"
	.string "contains POKéMON DNA!\p"
	.string "It would be a shattering scientific\n"
	.string "breakthrough if POKéMON could be\l"
	.string "resurrected from it.\p"
	.string "But, my colleagues just ignore what I\n"
	.string "have to say.\p"
	.string "So, I have a favor to ask!\p"
	.string "I want you to get this examined at a\n"
	.string "POKéMON LAB somewhere.$"

PewterCity_Museum_1F_Text_ReceivedOldAmberFromMan::
# 49 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "{PLAYER} received the OLD AMBER from\n"
	.string "the man.$"

PewterCity_Museum_1F_Text_GetOldAmberChecked::
# 53 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "Ssh! Get the OLD AMBER checked!$"

PewterCity_Museum_1F_Text_DontHaveSpaceForThis::
# 57 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "You don't have space for this.$"

PewterCity_Museum_1F_Text_WeHaveTwoFossilsOnExhibit::
# 61 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "We have two fossils of rare, prehistoric\n"
	.string "POKéMON on exhibit.$"

PewterCity_Museum_1F_Text_BeautifulPieceOfAmber::
# 65 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "There is a beautiful piece of AMBER in a\n"
	.string "clear gold color.$"

PewterCity_Museum_1F_Text_AerodactylFossil::
# 69 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "AERODACTYL Fossil A primitive and rare\n"
	.string "POKéMON.$"

PewterCity_Museum_1F_Text_KabutopsFossil::
# 73 "data/maps/PewterCity_Museum_1F/scripts.pory"
	.string "KABUTOPS Fossil A primitive and rare\n"
	.string "POKéMON.$"
