GoldenrodCity_BillsFamilysHouse_MapScripts::
	.byte 0


GoldenrodCity_BillsFamilysHouse_EventScript_SmithNPC1::
# 5 "data/maps/GoldenrodCity_BillsFamilysHouse/scripts.pory"
	msgbox GoldenrodCity_BillsFamilysHouse_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_BillsFamilysHouse_EventScript_SmithNPC2::
# 14 "data/maps/GoldenrodCity_BillsFamilysHouse/scripts.pory"
	msgbox GoldenrodCity_BillsFamilysHouse_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_BillsFamilysHouse_Text_SmithNPC1::
# 9 "data/maps/GoldenrodCity_BillsFamilysHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_BillsFamilysHouse_Text_SmithNPC2::
# 18 "data/maps/GoldenrodCity_BillsFamilysHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
