EternaCity_MapScripts::
	.byte 0


EternaCity_EventScript_Sign1::
# 5 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_Sign1, MSGBOX_SIGN
	end


EternaCity_EventScript_Sign2::
# 10 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_Sign2, MSGBOX_SIGN
	end


EternaCity_EventScript_SmithNPC1::
# 23 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC1, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC2::
# 32 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC2, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC3::
# 41 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC3, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC4::
# 50 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC4, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC5::
# 59 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC5, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC6::
# 68 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC6, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC7::
# 77 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC7, MSGBOX_NPC
	end


EternaCity_EventScript_SmithNPC8::
# 86 "data/maps/EternaCity/scripts.pory"
	msgbox EternaCity_Text_SmithNPC8, MSGBOX_NPC
	end


EternaCity_Text_Sign1::
# 14 "data/maps/EternaCity/scripts.pory"
	.string "EternaCity Sign 1$"

EternaCity_Text_Sign2::
# 18 "data/maps/EternaCity/scripts.pory"
	.string "EternaCity Sign 2$"

EternaCity_Text_SmithNPC1::
# 27 "data/maps/EternaCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

EternaCity_Text_SmithNPC2::
# 36 "data/maps/EternaCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

EternaCity_Text_SmithNPC3::
# 45 "data/maps/EternaCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

EternaCity_Text_SmithNPC4::
# 54 "data/maps/EternaCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

EternaCity_Text_SmithNPC5::
# 63 "data/maps/EternaCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

EternaCity_Text_SmithNPC6::
# 72 "data/maps/EternaCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

EternaCity_Text_SmithNPC7::
# 81 "data/maps/EternaCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

EternaCity_Text_SmithNPC8::
# 90 "data/maps/EternaCity/scripts.pory"
	.string "I know kung fu.$"
