BattleFrontier_Lounge4_MapScripts::
	.byte 0


BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring::
# 5 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "I wonder if they'll be airing interviews\n"
	.string "with tough TRAINERS today?$"

BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere::
# 9 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "If I opened a restaurant here, it'd make\n"
	.string "money for sure.$"

BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles::
# 13 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "Whew\p"
	.string "I need to take a breather after some\n"
	.string "intense battles\p"
	.string "But even now, I never take a break from\n"
	.string "plotting strategy and combos.$"
