ShoalCave_LowTideInnerRoom_MapScripts::
	.byte 0


ShoalCave_LowTideInnerRoom_EventScript_ShoalSalt1::
	end


ShoalCave_LowTideInnerRoom_EventScript_ShoalSalt2::
	end


ShoalCave_LowTideInnerRoom_EventScript_ShoalShell1::
	end


ShoalCave_LowTideInnerRoom_EventScript_ShoalShell2::
	end


ShoalCave_LowTideInnerRoom_EventScript_ShoalShell3::
	end


ShoalCave_LowTideInnerRoom_EventScript_ShoalShell4::
	end

