SootopolisCity_House6_MapScripts::
	.byte 0


SootopolisCity_House6_EventScript_Woman::
	end


SootopolisCity_House6_Text_LovePlushDolls::
# 8 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "I love plush DOLLS!$"

SootopolisCity_House6_Text_DontWantThisDoll::
# 12 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Are you sure?\n"
	.string "You don't want this DOLL?$"

SootopolisCity_House6_Text_IllHoldItForYou::
# 16 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Oh, you want it, but not right now?\n"
	.string "Okay, then I'll hold it for you.$"
