SootopolisCity_House6_MapScripts::
	.byte 0


SootopolisCity_House6_Text_FirstGuestInWhileTakeDoll::
# 5 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Hello! You're our first guest in a good\n"
	.string "while.\p"
	.string "You've brightened up my day, so I'll give\n"
	.string "you a big WAILMER DOLL.$"

SootopolisCity_House6_Text_TakeGoodCareOfIt::
# 9 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Take good care of it!$"

SootopolisCity_House6_Text_IllHoldItForYou::
# 13 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Oh, you want it, but not right now? Okay,\n"
	.string "then I'll hold it for you.$"

SootopolisCity_House6_Text_DontWantThisDoll::
# 17 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "Are you sure? You don't want this DOLL?$"

SootopolisCity_House6_Text_LovePlushDolls::
# 21 "data/maps/SootopolisCity_House6/scripts.pory"
	.string "I love plush DOLLS!$"
