SevenIsland_SevaultCanyon_House_MapScripts::
	.byte 0


SevenIsland_SevaultCanyon_House_Text_ChanseyDanceJoinIn::
# 5 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "Dance, dance! CHANSEY Dance!\p"
	.string "You join in, too! Dance, dance!$"

SevenIsland_SevaultCanyon_House_Text_WouldYouLikeToDance::
# 9 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "Would you like to dance?$"

SevenIsland_SevaultCanyon_House_Text_ComeOnDance::
# 13 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "Come on, dance!$"

SevenIsland_SevaultCanyon_House_Text_DancedChanseyDance::
# 17 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "{PLAYER} danced the CHANSEY Dance!$"

SevenIsland_SevaultCanyon_House_Text_YoureAllChipperNow::
# 21 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "Ahahahaha!\p"
	.string "There, you're all chipper now! Lucky!$"

SevenIsland_SevaultCanyon_House_Text_Chansey::
# 25 "data/maps/SevenIsland_SevaultCanyon_House/scripts.pory"
	.string "CHANSEY: Chansi! Chansi!$"
