VermilionCity_House3_MapScripts::
	.byte 0


VermilionCity_House3_EventScript_Boy::
# 5 "data/maps/VermilionCity_House3/scripts.pory"
	msgbox VermilionCity_House3_Text_PidgeyFlyLetterToSaffron, MSGBOX_NPC
	end


VermilionCity_House3_EventScript_Lass::
# 10 "data/maps/VermilionCity_House3/scripts.pory"
	msgbox VermilionCity_House3_Text_SendMyPidgeyToUnionRoom, MSGBOX_NPC
	end


VermilionCity_House3_EventScript_Letter::
# 15 "data/maps/VermilionCity_House3/scripts.pory"
	msgbox VermilionCity_House3_Text_DearPippiLetter, MSGBOX_SIGN
	end


VermilionCity_House3_EventScript_Pidgey::
	end


VermilionCity_House3_Text_DearPippiLetter::
# 24 "data/maps/VermilionCity_House3/scripts.pory"
	.string "Dear PIPPI, I hope to see you soon.\p"
	.string "I heard SAFFRON has problems with TEAM\n"
	.string "ROCKET.\p"
	.string "VERMILION appears to be safe.$"

VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
# 28 "data/maps/VermilionCity_House3/scripts.pory"
	.string "I'm getting my PIDGEY to fly a\n"
	.string "letter to SAFFRON in the north.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
# 32 "data/maps/VermilionCity_House3/scripts.pory"
	.string "I want to exchange MAIL with all\n"
	.string "sorts of people.\p"
	.string "I send my PIDGEY to a UNION ROOM\n"
	.string "to exchange MAIL for me.$"
