VermilionCity_House3_MapScripts::
	.byte 0


VermilionCity_House3_Text_PidgeyFlyLetterToSaffron::
# 5 "data/maps/VermilionCity_House3/scripts.pory"
	.string "I'm getting my PIDGEY to fly a letter to\n"
	.string "SAFFRON in the north.$"

VermilionCity_House3_Text_Pidgey::
# 9 "data/maps/VermilionCity_House3/scripts.pory"
	.string "PIDGEY: Kurukkoo!$"

VermilionCity_House3_Text_DearPippiLetter::
# 13 "data/maps/VermilionCity_House3/scripts.pory"
	.string "Dear PIPPI, I hope to see you soon.\p"
	.string "I heard SAFFRON has problems with TEAM\n"
	.string "ROCKET.\p"
	.string "VERMILION appears to be safe.$"

VermilionCity_House3_Text_SendMyPidgeyToUnionRoom::
# 17 "data/maps/VermilionCity_House3/scripts.pory"
	.string "I want to exchange MAIL with all sorts\n"
	.string "of people.\p"
	.string "I send my PIDGEY to a UNION ROOM to\n"
	.string "exchange MAIL for me.$"
