FallarborTown_CozmosHouse_MapScripts::
	.byte 0


FallarborTown_CozmosHouse_Text_MeteoriteWillNeverBeMineNow::
# 5 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO: Oh I never should have let\n"
	.string "myself be\l"
	.string "conned into telling TEAM MAGMA where\l"
	.string "you can find METEORITES\p"
	.string "That METEORITE from METEOR FALLS It's\n"
	.string "never going to be mine now$"

FallarborTown_CozmosHouse_Text_IsThatMeteoriteMayIHaveIt::
# 9 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "Oh! Hah?\p"
	.string "That item\p"
	.string "Could it be?\p"
	.string "Is it the METEORITE that TEAM MAGMA\n"
	.string "took from METEOR FALLS?\p"
	.string "Please, may I have it?\p"
	.string "I'm not asking for it for free. How\n"
	.string "about in exchange for this TM?$"

FallarborTown_CozmosHouse_Text_PleaseUseThisTM::
# 13 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO: This TM, it represents my\n"
	.string "feeling of gratitude.\l"
	.string "Please use it!$"

FallarborTown_CozmosHouse_Text_ReallyGoingToHelpMyResearch::
# 17 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO: Oh, I can't believe it. This\n"
	.string "is really, really great!\p"
	.string "This is really going to help my research!$"

FallarborTown_CozmosHouse_Text_CrushedWithDisappointment::
# 21 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO: Oh, but I'm crushed with\n"
	.string "disappointment$"

FallarborTown_CozmosHouse_Text_MayIHaveMeteorite::
# 25 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO: Please, may I have that\n"
	.string "METEORITE?\p"
	.string "I'm not asking for it for free. How\n"
	.string "about in exchange for this TM?$"

FallarborTown_CozmosHouse_Text_CozmoWentToMeteorFalls::
# 29 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "PROF. COZMO went off to METEOR FALLS\n"
	.string "on ROUTE 114 with some people from\l"
	.string "TEAM MAGMA.$"

FallarborTown_CozmosHouse_Text_FeelSorryForCozmo::
# 33 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "Poor PROF. COZMO He's so depressed I\n"
	.string "feel sorry for him.$"

FallarborTown_CozmosHouse_Text_CozmoIsSoHappy::
# 37 "data/maps/FallarborTown_CozmosHouse/scripts.pory"
	.string "Look at PROF. COZMO He's so happy! I\n"
	.string "think it's cute.$"
