CherrygroveCity_House3_MapScripts::
	.byte 0


CherrygroveCity_House3_EventScript_SmithNPC1::
# 5 "data/maps/CherrygroveCity_House3/scripts.pory"
	msgbox CherrygroveCity_House3_Text_SmithNPC1, MSGBOX_NPC
	end


CherrygroveCity_House3_EventScript_SmithNPC2::
# 14 "data/maps/CherrygroveCity_House3/scripts.pory"
	msgbox CherrygroveCity_House3_Text_SmithNPC2, MSGBOX_NPC
	end


CherrygroveCity_House3_Text_SmithNPC1::
# 9 "data/maps/CherrygroveCity_House3/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CherrygroveCity_House3_Text_SmithNPC2::
# 18 "data/maps/CherrygroveCity_House3/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
