SSTidalLowerDeck_MapScripts::
	.byte 0


SSTidalLowerDeck_Text_PhillipIntro::
# 5 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "Arrrgh! I'm fed up and dog-tired of\n"
	.string "cleaning this huge place!\p"
	.string "Let's have a quick battle!$"

SSTidalLowerDeck_Text_PhillipDefeat::
# 9 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "Little bro, I lost!$"

SSTidalLowerDeck_Text_PhillipPostBattle::
# 13 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent, and\n"
	.string "the young one does the scrubbing!$"

SSTidalLowerDeck_Text_LeonardIntro::
# 17 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "This is the bottom of the ship's hull.\n"
	.string "There's plenty of room.\l"
	.string "It'll be alright for a POKéMON battle.$"

SSTidalLowerDeck_Text_LeonardDefeat::
# 21 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "Big bro, I lost!$"

SSTidalLowerDeck_Text_LeonardPostBattle::
# 25 "data/maps/SSTidalLowerDeck/scripts.pory"
	.string "We're the CLEANUP BROTHERS!\p"
	.string "The old one dumps the detergent, and\n"
	.string "the young one does the scrubbing!$"
