Route18_MapScripts::
# 2 "data/maps/Route18/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route18_OnTransition
# 3 "data/maps/Route18/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route18_OnWarp
	.byte 0


Route18_Text_WiltonIntro::
# 7 "data/maps/Route18/scripts.pory"
	.string "I always check every grassy area for\n"
	.string "new POKéMON.$"

Route18_Text_WiltonDefeat::
# 11 "data/maps/Route18/scripts.pory"
	.string "Tch!$"

Route18_Text_WiltonPostBattle::
# 15 "data/maps/Route18/scripts.pory"
	.string "I wish I had a BIKE!$"

Route18_Text_RamiroIntro::
# 19 "data/maps/Route18/scripts.pory"
	.string "Kurukkoo! How do you like my birdcall?$"

Route18_Text_RamiroDefeat::
# 23 "data/maps/Route18/scripts.pory"
	.string "I had to bug you!$"

Route18_Text_RamiroPostBattle::
# 27 "data/maps/Route18/scripts.pory"
	.string "I collect sea POKéMON on weekends\n"
	.string "because the sea is so close.$"

Route18_Text_JacobIntro::
# 31 "data/maps/Route18/scripts.pory"
	.string "This is my turf! Get out of here!$"

Route18_Text_JacobDefeat::
# 35 "data/maps/Route18/scripts.pory"
	.string "Darn!$"

Route18_Text_JacobPostBattle::
# 39 "data/maps/Route18/scripts.pory"
	.string "This is my fave area for catching\n"
	.string "POKéMON.$"

Route18_Text_RouteSign::
# 43 "data/maps/Route18/scripts.pory"
	.string "ROUTE 18 CELADON CITY - FUCHSIA CITY$"

Route18_Text_CyclingRoadSign::
# 47 "data/maps/Route18/scripts.pory"
	.string "CYCLING ROAD No pedestrians permitted!$"
