BattleFrontier_BattlePikeRoomNormal_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePikeRoom_OnResume
# 3 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattlePikeRoom_OnTransition
# 4 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeRoomNormal_OnFrame
# 5 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeRoom_OnWarp
	.byte 0


BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreToFullHealth::
# 9 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Welcome You must be commended for your\n"
	.string "luck\p"
	.string "Your POKMON shall be restored to full\n"
	.string "health$"

BattleFrontier_BattlePikeRoomNormal_Text_EnjoyRestOfChallenge::
# 13 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I urge you to enjoy the rest of your\n"
	.string "Battle Choice challenge$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreOneMon::
# 17 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Ah, you're a lucky one. I'm in\n"
	.string "somewhat-good spirits now.\p"
	.string "I will restore one of your POKMON to\n"
	.string "full health.$"

BattleFrontier_BattlePikeRoomNormal_Text_BestOfLuckFarewell::
# 21 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "The best of luck to you. Farewell.$"

BattleFrontier_BattlePikeRoomNormal_Text_CareForBattleWillRestoreMons::
# 25 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Excuse me\p"
	.string "Would you care for a battle? I'll\n"
	.string "restore your POKMON if you win.$"

BattleFrontier_BattlePikeRoomNormal_Text_NowShallWe::
# 29 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Very well Now, shall we?$"

BattleFrontier_BattlePikeRoomNormal_Text_HowUnsportingOfYou::
# 33 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I see How unsporting of you$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreMonsAsPromised::
# 37 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Magnificent\p"
	.string "As promised, I shall restore your\n"
	.string "POKMON to full health.$"

BattleFrontier_BattlePikeRoomNormal_Text_BestOfLuckFarewell2::
# 41 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "The best of luck to you. Farewell.$"

BattleFrontier_BattlePikeRoomNormal_Text_WatchOut::
# 45 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Oh, my!\p"
	.string "Watch out!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaStop::
# 49 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Now, now! KIRLIA, stop that!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsStop::
# 53 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Now, now! DUSCLOPS, stop that!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedToxic::
# 57 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "KIRLIA used TOXIC!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedHypnosis::
# 61 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "KIRLIA used HYPNOSIS!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedThunderWave::
# 65 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "KIRLIA used THUNDER WAVE!$"

BattleFrontier_BattlePikeRoomNormal_Text_KirliaUsedWillOWisp::
# 69 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "KIRLIA used WILL-O-WISP!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsUsedWillOWisp::
# 73 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "DUSCLOPS used WILL-O-WISP!$"

BattleFrontier_BattlePikeRoomNormal_Text_DusclopsUsedIceBeam::
# 77 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "DUSCLOPS used ICE BEAM!$"

BattleFrontier_BattlePikeRoomNormal_Text_ThatsEnough::
# 81 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Look here! That's quite enough!$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeForKirlia::
# 85 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I must apologize to you\p"
	.string "My KIRLIA has a TIMID nature$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeForDusclops::
# 89 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I must apologize to you\p"
	.string "My DUSCLOPS has a TIMID nature$"

BattleFrontier_BattlePikeRoomNormal_Text_AttacksWhenStartled::
# 93 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "It attacks without warning if it is\n"
	.string "startled by another person\p"
	.string "Are you and your POKMON all right?$"

BattleFrontier_BattlePikeRoomNormal_Text_ApologizeHopeMonsAreFine::
# 97 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I do apologize for what happened I do\n"
	.string "hope your POKMON are fine.$"

BattleFrontier_BattlePikeRoomNormal_Text_Silence::
# 101 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "$"

BattleFrontier_BattlePikeRoomNormal_Text_BattleSomewhatToughTrainer::
# 105 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Welcome\p"
	.string "Here, we will have you battle a\n"
	.string "somewhat-tough TRAINER$"

BattleFrontier_BattlePikeRoomNormal_Text_RestoreToFullHealth::
# 109 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "How wonderful\p"
	.string "To honor your victory, your POKMON\n"
	.string "shall be restored to full health$"

BattleFrontier_BattlePikeRoomNormal_Text_EnjoyRestOfChallenge2::
# 113 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I urge you to enjoy the rest of your\n"
	.string "Battle Choice challenge$"

BattleFrontier_BattlePikeRoomNormal_Text_ImThePikeQueen::
# 117 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I am LUCY I am the law here\l"
	.string "For I am the PIKE QUEEN\p"
	.string "You already know it, but to advance, you\n"
	.string "must defeat me\p"
	.string "I'm not one for idle chatter. Hurry. Come\n"
	.string "on$"

BattleFrontier_BattlePikeRoomNormal_Text_HopeYouDidntUseUpLuck::
# 121 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Your luck I hope you didn't use it all up\n"
	.string "here$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyShowMeFrontierPass::
# 125 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "LUCY: Show me your FRONTIER PASS$"

BattleFrontier_BattlePikeRoomNormal_Text_ReceivedLuckSymbol::
# 129 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "The Luck Symbol was embossed on the\n"
	.string "FRONTIER PASS!$"

BattleFrontier_BattlePikeRoomNormal_Text_AllThereIsDisappear::
# 133 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "That's all there is Disappear already$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyYouAgain::
# 137 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "LUCY: You again\p"
	.string "\p"
	.string "I've trampled flowers and braved storms\n"
	.string "to get to where I am\p"
	.string "I don't feel any compulsion to keep\n"
	.string "losing to the same opponent\p"
	.string "Fine I'll do it$"

BattleFrontier_BattlePikeRoomNormal_Text_NowComeOn::
# 141 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Now! Come on!$"

BattleFrontier_BattlePikeRoomNormal_Text_LucyFrontierPass::
# 145 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "LUCY:\p"
	.string "FRONTIER PASS$"

BattleFrontier_BattlePikeRoomNormal_Text_LuckSymbolTookGoldenShine::
# 149 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "The Luck Symbol took on a golden shine!$"

BattleFrontier_BattlePikeRoomNormal_Text_IWontForget::
# 153 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "You, I won't forget Ever$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomNoHeal::
# 157 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I welcome you\p"
	.string "Giggle You seem to be bereft of luck\p"
	.string "If only you hadn't chosen this room,\n"
	.string "your POKMON could have been healed$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomHealOne::
# 161 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I welcome you\p"
	.string "Since you have chosen this room, I will\n"
	.string "restore one POKMON to full health$"

BattleFrontier_BattlePikeRoomNormal_Text_ChoseRoomHealTwo::
# 165 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I welcome you\p"
	.string "Since you have chosen this room, I will\n"
	.string "restore two POKMON to full health$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreAllMons::
# 169 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I welcome you\p"
	.string "Giggle You should thank your lucky\n"
	.string "stars\p"
	.string "Since you have chosen this room, all\n"
	.string "your POKMON will be restored$"

BattleFrontier_BattlePikeRoomNormal_Text_ShallFetchOurMaster::
# 173 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "I shall go fetch our master$"

BattleFrontier_BattlePikeRoomNormal_Text_WillRestoreTwoMons::
# 177 "data/maps/BattleFrontier_BattlePikeRoomNormal/scripts.pory"
	.string "Ah, you're a lucky one! I'm in good\n"
	.string "spirits now.\p"
	.string "I will restore two of your POKMON to\n"
	.string "full health!$"
