PewterCity_Museum_2F_MapScripts::
	.byte 0


PewterCity_Museum_2F_EventScript_BaldingMan::
# 5 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_PikachuSoonIPromise, MSGBOX_NPC
	end


PewterCity_Museum_2F_EventScript_LittleGirl::
# 10 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu, MSGBOX_NPC
	end


PewterCity_Museum_2F_EventScript_Man::
# 15 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone, MSGBOX_NPC
	end


PewterCity_Museum_2F_EventScript_MoonStone::
# 20 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon, MSGBOX_SIGN
	end


PewterCity_Museum_2F_EventScript_OldMan::
# 25 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding, MSGBOX_NPC
	end


PewterCity_Museum_2F_EventScript_Scientist::
# 30 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth, MSGBOX_NPC
	end


PewterCity_Museum_2F_EventScript_SpaceShuttle::
# 35 "data/maps/PewterCity_Museum_2F/scripts.pory"
	msgbox PewterCity_Museum_1F_Text_SpaceShuttle, MSGBOX_SIGN
	end


PewterCity_Museum_1F_Text_SpaceShuttle::
# 40 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
# 44 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "A meteorite that fell on MT. MOON. It is\n"
	.string "thought to be a MOON STONE.$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
# 48 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Yeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
# 52 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "I want a PIKACHU!\n"
	.string "It's so cute!\p"
	.string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
# 56 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "MOON STONE, huh?\p"
	.string "What's so special about it?\n"
	.string "Looks like an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
# 60 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "July 20, 1969!\p"
	.string "Humankind first set foot on the\n"
	.string "moon that day.\p"
	.string "I bought a color TV just so I\n"
	.string "could watch that news.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
# 64 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "This month, we're running a space\n"
	.string "exhibit.$"
