PewterCity_Museum_2F_MapScripts::
	.byte 0


Text_SeismicTossTeach::
# 5 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "The secrets of space… The mysteries of\n"
	.string "earth…\p"
	.string "There are so many things about which we\n"
	.string "know so little.\p"
	.string "But that should spur us to study\n"
	.string "harder, not toss in the towel.\p"
	.string "The only thing you should toss…\p"
	.string "Well, how about SEISMIC TOSS? Should I\n"
	.string "teach that to a POKéMON?$"

Text_SeismicTossDeclined::
# 9 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Is that so? I'm sure you'll be back for\n"
	.string "it.$"

Text_SeismicTossWhichMon::
# 13 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Which POKéMON wants to learn SEISMIC\n"
	.string "TOSS?$"

Text_SeismicTossTaught::
# 17 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "I hope you won't toss in the towel. Keep\n"
	.string "it up.$"

PewterCity_Museum_1F_Text_WhatsSpecialAboutMoonStone::
# 21 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "MOON STONE, huh?\p"
	.string "What's so special about it? Looks like\n"
	.string "an ordinary rock to me.$"

PewterCity_Museum_1F_Text_BoughtColorTVForMoonLanding::
# 25 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "July 20, 1969!\p"
	.string "Humankind first set foot on the moon\n"
	.string "that day.\p"
	.string "I bought a color TV just so I could\n"
	.string "watch that news.$"

PewterCity_Museum_1F_Text_RunningSpaceExhibitThisMonth::
# 29 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "This month, we're running a space\n"
	.string "exhibit.$"

PewterCity_Museum_1F_Text_AskedDaddyToCatchPikachu::
# 33 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "I want a PIKACHU! It's so cute!\p"
	.string "I asked my daddy to catch me one!$"

PewterCity_Museum_1F_Text_PikachuSoonIPromise::
# 37 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Yeah, a PIKACHU soon, I promise!$"

PewterCity_Museum_1F_Text_SpaceShuttle::
# 41 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "Space Shuttle$"

PewterCity_Museum_1F_Text_MeteoriteThatFellOnMtMoon::
# 45 "data/maps/PewterCity_Museum_2F/scripts.pory"
	.string "A meteorite that fell on MT. MOON. It is\n"
	.string "thought to be a MOON STONE.$"
