Route34_Gatehouse_MapScripts::
	.byte 0


Route34_Gatehouse_EventScript_SmithNPC1::
# 5 "data/maps/Route34_Gatehouse/scripts.pory"
	msgbox Route34_Gatehouse_Text_SmithNPC1, MSGBOX_NPC
	end


Route34_Gatehouse_EventScript_SmithNPC2::
# 14 "data/maps/Route34_Gatehouse/scripts.pory"
	msgbox Route34_Gatehouse_Text_SmithNPC2, MSGBOX_NPC
	end


Route34_Gatehouse_Text_SmithNPC1::
# 9 "data/maps/Route34_Gatehouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route34_Gatehouse_Text_SmithNPC2::
# 18 "data/maps/Route34_Gatehouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
