RustboroCity_Flat2_1F_MapScripts::
	.byte 0


RustboroCity_Flat2_1F_EventScript_OldWoman::
# 5 "data/maps/RustboroCity_Flat2_1F/scripts.pory"
	msgbox RustboroCity_Flat2_1F_Text_DevonWorkersLiveHere, MSGBOX_NPC
	end


RustboroCity_Flat2_1F_EventScript_Skitty::
# 10 "data/maps/RustboroCity_Flat2_1F/scripts.pory"
	msgbox RustboroCity_Flat2_1F_Text_Skitty, MSGBOX_DEFAULT
	end


RustboroCity_Flat2_1F_Text_Skitty::
# 14 "data/maps/RustboroCity_Flat2_1F/scripts.pory"
	.string "SKITTY: Gyaaaah!$"

RustboroCity_Flat2_1F_Text_DevonWorkersLiveHere::
# 18 "data/maps/RustboroCity_Flat2_1F/scripts.pory"
	.string "DEVON CORPORATION's workers live in\n"
	.string "this building.$"
