RustboroCity_House2_MapScripts::
	.byte 0


RustboroCity_House2_EventScript_LittleGirl::
# 5 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_RoxanneKnowsALot, MSGBOX_NPC
	end


RustboroCity_House2_EventScript_PokefanF::
# 10 "data/maps/RustboroCity_House2/scripts.pory"
	msgbox RustboroCity_House2_Text_TrainerSchoolExcellent, MSGBOX_NPC
	end


RustboroCity_House2_Text_TrainerSchoolExcellent::
# 14 "data/maps/RustboroCity_House2/scripts.pory"
	.string "The TRAINER'S SCHOOL is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a GYM LEADER.$"

RustboroCity_House2_Text_RoxanneKnowsALot::
# 18 "data/maps/RustboroCity_House2/scripts.pory"
	.string "ROXANNE, the GYM LEADER, really knows\n"
	.string "a lot about POKéMON.\p"
	.string "She's really strong, too!$"
