RustboroCity_House2_MapScripts::
	.byte 0


RustboroCity_House2_Text_TrainerSchoolExcellent::
# 5 "data/maps/RustboroCity_House2/scripts.pory"
	.string "The TRAINER'S SCHOOL is excellent.\p"
	.string "If you study there, you could even\n"
	.string "become a GYM LEADER.$"

RustboroCity_House2_Text_RoxanneKnowsALot::
# 9 "data/maps/RustboroCity_House2/scripts.pory"
	.string "ROXANNE, the GYM LEADER, really knows a\n"
	.string "lot about POKéMON.\p"
	.string "She's really strong, too!$"
