SafariZone_Center_MapScripts::
# 2 "data/maps/SafariZone_Center/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SafariZone_Center_OnTransition
	.byte 0


SafariZone_Center_Text_RestHouse::
# 6 "data/maps/SafariZone_Center/scripts.pory"
	.string "REST HOUSE$"

SafariZone_Center_Text_PressStartToCheckTime::
# 10 "data/maps/SafariZone_Center/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Press START to check remaining time.$"

SafariZone_Center_Text_CenterArea::
# 14 "data/maps/SafariZone_Center/scripts.pory"
	.string "CENTER AREA$"
