SafariZone_SecretHouse_MapScripts::
	.byte 0


SafariZone_SecretHouse_Text_CongratsYouveWon::
# 5 "data/maps/SafariZone_SecretHouse/scripts.pory"
	.string "Ah! Finally!\p"
	.string "You're the first person to reach the\n"
	.string "SECRET HOUSE!\p"
	.string "Although I made a campaign for our\n"
	.string "grand opening,\p"
	.string "I was getting worried that no one would\n"
	.string "win our campaign prize.\p"
	.string "Congratulations! You have won!$"

SafariZone_SecretHouse_Text_ReceivedHM03FromAttendant::
# 9 "data/maps/SafariZone_SecretHouse/scripts.pory"
	.string "{PLAYER} received HM03 from the\n"
	.string "attendant!$"

SafariZone_SecretHouse_Text_ExplainSurf::
# 13 "data/maps/SafariZone_SecretHouse/scripts.pory"
	.string "HM03 is SURF.\p"
	.string "POKMON will be able to ferry you across\n"
	.string "water using it.\p"
	.string "And, this HM isn't disposable, so you can\n"
	.string "use it over and over.\p"
	.string "You're super lucky for winning this\n"
	.string "fabulous prize!$"

SafariZone_SecretHouse_Text_DontHaveRoomForPrize::
# 17 "data/maps/SafariZone_SecretHouse/scripts.pory"
	.string "You don't have room for this fabulous\n"
	.string "prize!$"
