FloaromaTown_Mart_MapScripts::
	.byte 0


FloaromaTown_Mart_EventScript_SmithNPC1::
# 5 "data/maps/FloaromaTown_Mart/scripts.pory"
	msgbox FloaromaTown_Mart_Text_SmithNPC1, MSGBOX_NPC
	end


FloaromaTown_Mart_EventScript_SmithNPC2::
# 14 "data/maps/FloaromaTown_Mart/scripts.pory"
	msgbox FloaromaTown_Mart_Text_SmithNPC2, MSGBOX_NPC
	end


FloaromaTown_Mart_EventScript_SmithNPC3::
# 23 "data/maps/FloaromaTown_Mart/scripts.pory"
	msgbox FloaromaTown_Mart_Text_SmithNPC3, MSGBOX_NPC
	end


FloaromaTown_Mart_Text_SmithNPC1::
# 9 "data/maps/FloaromaTown_Mart/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

FloaromaTown_Mart_Text_SmithNPC2::
# 18 "data/maps/FloaromaTown_Mart/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

FloaromaTown_Mart_Text_SmithNPC3::
# 27 "data/maps/FloaromaTown_Mart/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
