Route19_MapScripts::
	.byte 0


Route19_Text_RichardIntro::
# 5 "data/maps/Route19/scripts.pory"
	.string "I have to exercise and warm up before\n"
	.string "going out for a swim.$"

Route19_Text_RichardDefeat::
# 9 "data/maps/Route19/scripts.pory"
	.string "All warmed up!$"

Route19_Text_RichardPostBattle::
# 13 "data/maps/Route19/scripts.pory"
	.string "Thanks, kid! I'm ready for a swim.$"

Route19_Text_ReeceIntro::
# 17 "data/maps/Route19/scripts.pory"
	.string "Wait! Slow down! You'll have a heart\n"
	.string "attack!$"

Route19_Text_ReeceDefeat::
# 21 "data/maps/Route19/scripts.pory"
	.string "Ooh! That's chilly!$"

Route19_Text_ReecePostBattle::
# 25 "data/maps/Route19/scripts.pory"
	.string "Watch out for TENTACOOL. They sting so\n"
	.string "painfully.$"

Route19_Text_MatthewIntro::
# 29 "data/maps/Route19/scripts.pory"
	.string "I love swimming! What about you?$"

Route19_Text_MatthewDefeat::
# 33 "data/maps/Route19/scripts.pory"
	.string "Belly flop!$"

Route19_Text_MatthewPostBattle::
# 37 "data/maps/Route19/scripts.pory"
	.string "I can beat even marine POKMON at\n"
	.string "swimming.$"

Route19_Text_DouglasIntro::
# 41 "data/maps/Route19/scripts.pory"
	.string "What's beyond the horizon?$"

Route19_Text_DouglasDefeat::
# 45 "data/maps/Route19/scripts.pory"
	.string "Glub!$"

Route19_Text_DouglasPostBattle::
# 49 "data/maps/Route19/scripts.pory"
	.string "I see a couple of islands over yonder!$"

Route19_Text_DavidIntro::
# 53 "data/maps/Route19/scripts.pory"
	.string "I tried diving for POKMON, but it was a\n"
	.string "no-go.$"

Route19_Text_DavidDefeat::
# 57 "data/maps/Route19/scripts.pory"
	.string "Help!$"

Route19_Text_DavidPostBattle::
# 61 "data/maps/Route19/scripts.pory"
	.string "I guess you have to fish for sea\n"
	.string "POKMON.$"

Route19_Text_TonyIntro::
# 65 "data/maps/Route19/scripts.pory"
	.string "I look at the sea to forget all the bad\n"
	.string "things that happened.$"

Route19_Text_TonyDefeat::
# 69 "data/maps/Route19/scripts.pory"
	.string "Ooh! Traumatic!$"

Route19_Text_TonyPostBattle::
# 73 "data/maps/Route19/scripts.pory"
	.string "I'm looking at the sea to forget the bad\n"
	.string "thing that happened!$"

Route19_Text_AnyaIntro::
# 77 "data/maps/Route19/scripts.pory"
	.string "Oh, I just love your ride! Can I have it\n"
	.string "if I win?$"

Route19_Text_AnyaDefeat::
# 81 "data/maps/Route19/scripts.pory"
	.string "Oh! I lost!$"

Route19_Text_AnyaPostBattle::
# 85 "data/maps/Route19/scripts.pory"
	.string "It's still a long way to go to SEAFOAM\n"
	.string "ISLANDS\p"
	.string "I want to go back to FUCHSIA$"

Route19_Text_AliceIntro::
# 89 "data/maps/Route19/scripts.pory"
	.string "Swimming's great! Sunburns aren't!$"

Route19_Text_AliceDefeat::
# 93 "data/maps/Route19/scripts.pory"
	.string "Shocker!$"

Route19_Text_AlicePostBattle::
# 97 "data/maps/Route19/scripts.pory"
	.string "My boyfriend wanted to swim to SEAFOAM\n"
	.string "ISLANDS.$"

Route19_Text_AxleIntro::
# 101 "data/maps/Route19/scripts.pory"
	.string "Ahoy, there! These waters are\n"
	.string "treacherous!$"

Route19_Text_AxleDefeat::
# 105 "data/maps/Route19/scripts.pory"
	.string "Ooh! Dangerous!$"

Route19_Text_AxlePostBattle::
# 109 "data/maps/Route19/scripts.pory"
	.string "M-my legs! They cramped up! Glub, glub$"

Route19_Text_ConnieIntro::
# 113 "data/maps/Route19/scripts.pory"
	.string "I swam here with my friends I'm tired$"

Route19_Text_ConnieDefeat::
# 117 "data/maps/Route19/scripts.pory"
	.string "I'm exhausted$"

Route19_Text_ConniePostBattle::
# 121 "data/maps/Route19/scripts.pory"
	.string "If I were to ride a POKMON on the sea,\n"
	.string "I'd like a LAPRAS.\p"
	.string "LAPRAS is so big, I bet it would keep me\n"
	.string "dry on water.$"

Route19_Text_RouteSign::
# 125 "data/maps/Route19/scripts.pory"
	.string "SEA ROUTE 19 FUCHSIA CITY - SEAFOAM\n"
	.string "ISLANDS$"

Route19_Text_LiaIntro::
# 129 "data/maps/Route19/scripts.pory"
	.string "LIA: I'm looking after my brother. He\n"
	.string "just became a TRAINER.$"

Route19_Text_LiaDefeat::
# 133 "data/maps/Route19/scripts.pory"
	.string "LIA: That's no way to treat my little\n"
	.string "brother!$"

Route19_Text_LiaPostBattle::
# 137 "data/maps/Route19/scripts.pory"
	.string "LIA: Do you have a younger brother?\p"
	.string "I hope you're teaching him all sorts of\n"
	.string "things.$"

Route19_Text_LiaNotEnoughMons::
# 141 "data/maps/Route19/scripts.pory"
	.string "LIA: I want to battle together with my\n"
	.string "little brother.\p"
	.string "Don't you have two POKMON?$"

Route19_Text_LucIntro::
# 145 "data/maps/Route19/scripts.pory"
	.string "LUC: My big sis taught me how to swim\n"
	.string "and train POKMON.$"

Route19_Text_LucDefeat::
# 149 "data/maps/Route19/scripts.pory"
	.string "LUC: Oh, wow! Someone tougher than my\n"
	.string "big sis!$"

Route19_Text_LucPostBattle::
# 153 "data/maps/Route19/scripts.pory"
	.string "LUC: My big sis is strong and nice. I\n"
	.string "think she's awesome!$"

Route19_Text_LucNotEnoughMons::
# 157 "data/maps/Route19/scripts.pory"
	.string "LUC: I don't want to if I can't battle\n"
	.string "you with my big sis.\p"
	.string "Don't you have two POKMON?$"
