VictoryRoad_1F_MapScripts::
# 2 "data/maps/VictoryRoad_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, VictoryRoad_1F_OnLoad
# 3 "data/maps/VictoryRoad_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, VictoryRoad_1F_OnTransition
	.byte 0


VictoryRoad_1F_Text_NaomiIntro::
# 7 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "I wonder if you are good enough for me?$"

VictoryRoad_1F_Text_NaomiDefeat::
# 11 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "I lost out…$"

VictoryRoad_1F_Text_NaomiPostBattle::
# 15 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "I never wanted to lose to anybody,\n"
	.string "especially to a younger kid…$"

VictoryRoad_1F_Text_RolandoIntro::
# 19 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "I can see you're good. Let me see\n"
	.string "exactly how good!$"

VictoryRoad_1F_Text_RolandoDefeat::
# 23 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "I had a chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
# 27 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Tch! I concede, you are better than I!$"
