VictoryRoad_1F_MapScripts::
	.byte 0


VictoryRoad_1F_EventScript_Albert::
	end


VictoryRoad_1F_EventScript_Edgar::
	end


VictoryRoad_1F_EventScript_EntranceWally::
	end


VictoryRoad_1F_EventScript_ExitWally::
	end


VictoryRoad_1F_EventScript_Hope::
	end


VictoryRoad_1F_EventScript_Katelynn::
	end


VictoryRoad_1F_EventScript_Quincy::
	end


VictoryRoad_1F_EventScript_WallyBattleTrigger1::
	end


VictoryRoad_1F_EventScript_WallyBattleTrigger2::
	end


VictoryRoad_1F_Text_NaomiDefeat::
# 42 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_NaomiDefeat$"

VictoryRoad_1F_Text_NaomiIntro::
# 46 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_NaomiIntro$"

VictoryRoad_1F_Text_NaomiPostBattle::
# 50 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_NaomiPostBattle$"

VictoryRoad_1F_Text_RolandoDefeat::
# 54 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_RolandoDefeat$"

VictoryRoad_1F_Text_RolandoIntro::
# 58 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_RolandoIntro$"

VictoryRoad_1F_Text_RolandoPostBattle::
# 62 "data/maps/VictoryRoad_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_1F_Text_RolandoPostBattle$"
