SlateportCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SlateportCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


SlateportCity_PokemonCenter_1F_Text_RaiseDifferentTypesOfPokemon::
# 7 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	.string "Want a tip for battling?\p"
	.string "I'd say it's raising different kinds of\n"
	.string "POKéMON in a balanced manner.\p"
	.string "It's no good to make just one POKéMON\n"
	.string "strong.\p"
	.string "If it has a type disadvantage, it might\n"
	.string "not stand a chance.$"

SlateportCity_PokemonCenter_1F_Text_TradedMonWithFriend::
# 11 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	.string "I trade POKéMON with my friends.\p"
	.string "If a traded POKéMON is holding an item,\n"
	.string "it makes me twice as happy!$"
