SlateportCity_PokemonCenter_1F_MapScripts::
	.byte 0


SlateportCity_PokemonCenter_1F_EventScript_Nurse::
	end


SlateportCity_PokemonCenter_1F_EventScript_Sailor::
# 9 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	msgbox SlateportCity_PokemonCenter_1F_Text_RaiseDifferentTypesOfPokemon, MSGBOX_NPC
	end


SlateportCity_PokemonCenter_1F_EventScript_Woman::
# 14 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	msgbox SlateportCity_PokemonCenter_1F_Text_TradedMonWithFriend, MSGBOX_NPC
	end


SlateportCity_PokemonCenter_1F_Text_TradedMonWithFriend::
# 18 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	.string "I trade POKéMON with my friends.\p"
	.string "If a traded POKéMON is holding an\n"
	.string "item, it makes me twice as happy!$"

SlateportCity_PokemonCenter_1F_Text_RaiseDifferentTypesOfPokemon::
# 22 "data/maps/SlateportCity_PokemonCenter_1F/scripts.pory"
	.string "Want a tip for battling?\p"
	.string "I'd say it's raising different kinds\n"
	.string "of POKéMON in a balanced manner.\p"
	.string "It's no good to make just one\n"
	.string "POKéMON strong.\p"
	.string "If it has a type disadvantage,\n"
	.string "it might not stand a chance.$"
