SevenIsland_TanobyRuins_MapScripts::
	.byte 0


SevenIsland_TanobyRuins_Text_BrandonIntro::
# 5 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "Do you know anything about this stone\n"
	.string "chamber?$"

SevenIsland_TanobyRuins_Text_BrandonDefeat::
# 9 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "That was uncalled for. You didn't have\n"
	.string "to be so rough.$"

SevenIsland_TanobyRuins_Text_BrandonPostBattle::
# 13 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "The TANOBY RUINS date back at least\n"
	.string "1,500 years.\p"
	.string "But it's a baffling mystery as to why it\n"
	.string "was built in the first place.$"

SevenIsland_TanobyRuins_Text_BenjaminIntro::
# 17 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "A mystic POKMON is said to sleep inside\n"
	.string "here.$"

SevenIsland_TanobyRuins_Text_BenjaminDefeat::
# 21 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "I'm not much good in battle.$"

SevenIsland_TanobyRuins_Text_BenjaminPostBattle::
# 25 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "I hear there are other ruins like the\n"
	.string "one here.\p"
	.string "Might they be the resting places of\n"
	.string "other mystic POKMON?$"

SevenIsland_TanobyRuins_Text_EdnaIntro::
# 29 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "CLIFFORD is teaching me how to paint.$"

SevenIsland_TanobyRuins_Text_EdnaDefeat::
# 33 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "We might get in trouble for being noisy\n"
	.string "here.$"

SevenIsland_TanobyRuins_Text_EdnaPostBattle::
# 37 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "I said that I wanted to paint an old\n"
	.string "building.\p"
	.string "So CLIFFORD brought me here.$"

SevenIsland_TanobyRuins_Text_CliffordIntro::
# 41 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "Today, in addition to our lesson, we\n"
	.string "came to see the chamber.$"

SevenIsland_TanobyRuins_Text_CliffordDefeat::
# 45 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "My, how extraordinary.$"

SevenIsland_TanobyRuins_Text_CliffordPostBattle::
# 49 "data/maps/SevenIsland_TanobyRuins/scripts.pory"
	.string "Ah, so you are studying POKMON on your\n"
	.string "own\p"
	.string "Yes, you certainly are quite the\n"
	.string "extraordinary person, indeed.$"
