SSTidalCorridor_MapScripts::
	.byte 0


SSTidalCorridor_EventScript_Briney::
# 5 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_BrineyWelcomeAboard, MSGBOX_NPC
	end


SSTidalCorridor_EventScript_Cabin1Sign::
# 10 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_Cabin1, MSGBOX_SIGN
	end


SSTidalCorridor_EventScript_Cabin2Sign::
# 15 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_Cabin2, MSGBOX_SIGN
	end


SSTidalCorridor_EventScript_Cabin3Sign::
# 20 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_Cabin3, MSGBOX_SIGN
	end


SSTidalCorridor_EventScript_Cabin4Sign::
# 25 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_Cabin4, MSGBOX_SIGN
	end


SSTidalCorridor_EventScript_ExitSailor::
	end


SSTidalCorridor_EventScript_Peeko::
# 34 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_Peeko, MSGBOX_DEFAULT
	end


SSTidalCorridor_EventScript_Porthole::
# 42 "data/maps/SSTidalCorridor/scripts.pory"
	msgbox SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole, MSGBOX_DEFAULT
	end


SSTidalCorridor_EventScript_Sailor::
	end


SSTidalCorridor_EventScript_ReachedStepCount::
	end


SSTidalCorridor_Text_Cabin3::
# 55 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 3$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole::
# 59 "data/maps/SSTidalCorridor/scripts.pory"
	.string "The horizon spreads beyond the\n"
	.string "porthole.$"

SSTidalCorridor_Text_Cabin1::
# 63 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 1$"

SSTidalCorridor_Text_Cabin4::
# 67 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 4$"

SSTidalCorridor_Text_Cabin2::
# 71 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 2$"

SSTidal_Text_MadeLandInLilycove::
# 75 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We have made land in LILYCOVE CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage::
# 79 "data/maps/SSTidalCorridor/scripts.pory"
	.string "This ferry is built to plow through\n"
	.string "fast-running currents.\p"
	.string "We hope you enjoy your voyage with us.\n"
	.string "Feel free to explore the ship.$"

SSTidal_Text_MadeLandInSlateport::
# 83 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We have made land in SLATEPORT CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidalCorridor_Text_WeveArrived::
# 87 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We've arrived!$"

SSTidalCorridor_Text_Peeko::
# 91 "data/maps/SSTidalCorridor/scripts.pory"
	.string "PEEKO: Pihyo pihyohyo…$"

SSTidalCorridor_Text_EnjoyYourCruise::
# 95 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Enjoy your cruise!$"

SSTidalCorridor_Text_ScottBattleFrontierInvite::
# 99 "data/maps/SSTidalCorridor/scripts.pory"
	.string "SCOTT: Well, hi, hi!\n"
	.string "{PLAYER}{KUN}, {PLAYER}{KUN}!\p"
	.string "Something's come up, so I have to\n"
	.string "disembark, but am I glad to see you!\p"
	.string "Congratulations, LEAGUE CHAMPION!\p"
	.string "There's a place I'd like to invite\n"
	.string "someone like you.\p"
	.string "It's the…\n"
	.string "BATTLE FRONTIER!\p"
	.string "What's the place like?\n"
	.string "You'll understand when you see it!\p"
	.string "I've spoken with the ship's CAPTAIN\n"
	.string "about this.\p"
	.string "The next time you take a ferry,\n"
	.string "you should be able to sail to\l"
	.string "the BATTLE FRONTIER.\p"
	.string "Okay, {PLAYER}{KUN}, I'll be waiting for you\n"
	.string "at the BATTLE FRONTIER!$"

SSTidalCorridor_Text_BrineyWelcomeAboard::
# 103 "data/maps/SSTidalCorridor/scripts.pory"
	.string "MR. BRINEY: Welcome aboard, {PLAYER}{KUN}!\p"
	.string "They made me honorary captain of\n"
	.string "the S.S. TIDAL!\p"
	.string "You can call me CAPTAIN BRINEY now!\p"
	.string "You know, I retired once before,\n"
	.string "but when I saw this majestic ship…\p"
	.string "Let me just say, it stirred my sleeping\n"
	.string "soul as a sailor!$"

SSTidal_Text_HopeYouEnjoyVoyage::
# 107 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We hope you enjoy your voyage on\n"
	.string "our ferry.$"
