SSTidalCorridor_MapScripts::
# 2 "data/maps/SSTidalCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SSTidalCorridor_OnFrame
	.byte 0


SSTidalCorridor_MapScripts::
# 6 "data/maps/SSTidalCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SSTidalCorridor_OnFrame
	return


SSTidalCorridor_Text_ScottBattleFrontierInvite::
# 10 "data/maps/SSTidalCorridor/scripts.pory"
	.string "SCOTT: Well, hi, hi! {PLAYER}{KUN},\n"
	.string "{PLAYER}{KUN}!\p"
	.string "Something's come up, so I have to\n"
	.string "disembark, but am I glad to see you!\p"
	.string "Congratulations, LEAGUE CHAMPION!\p"
	.string "There's a place I'd like to invite\n"
	.string "someone like you.\p"
	.string "It's the… BATTLE FRONTIER!\p"
	.string "What's the place like? You'll understand\n"
	.string "when you see it!\p"
	.string "I've spoken with the ship's CAPTAIN\n"
	.string "about this.\p"
	.string "The next time you take a ferry, you\n"
	.string "should be able to sail to\l"
	.string "the BATTLE FRONTIER.\p"
	.string "Okay, {PLAYER}{KUN}, I'll be waiting for you\n"
	.string "at the BATTLE FRONTIER!$"

SSTidal_Text_FastCurrentsHopeYouEnjoyVoyage::
# 14 "data/maps/SSTidalCorridor/scripts.pory"
	.string "This ferry is built to plow through\n"
	.string "fast-running currents.\p"
	.string "We hope you enjoy your voyage with us.\n"
	.string "Feel free to explore the ship.$"

SSTidal_Text_HopeYouEnjoyVoyage::
# 18 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We hope you enjoy your voyage on our\n"
	.string "ferry.$"

SSTidal_Text_MadeLandInSlateport::
# 22 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We have made land in SLATEPORT CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidal_Text_MadeLandInLilycove::
# 26 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We have made land in LILYCOVE CITY.\n"
	.string "Thank you for sailing with us.$"

SSTidalCorridor_Text_CanRestInCabin2::
# 30 "data/maps/SSTidalCorridor/scripts.pory"
	.string "It'll be some time before we make land, I\n"
	.string "reckon.\p"
	.string "You can rest up in your cabin if you'd\n"
	.string "like. Your cabin's No. 2.\p"
	.string "The bed in there is soft and plushy. I\n"
	.string "can attest to how comfy it is!$"

SSTidalCorridor_Text_WeveArrived::
# 34 "data/maps/SSTidalCorridor/scripts.pory"
	.string "We've arrived!$"

SSTidalCorridor_Text_VisitOtherCabins::
# 38 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Go visit other cabins. TRAINERS bored\n"
	.string "of the boat trip will\l"
	.string "be itching to battle.$"

SSTidalCorridor_Text_EnjoyYourCruise::
# 42 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Enjoy your cruise!$"

SSTidalCorridor_Text_HorizonSpreadsBeyondPorthole::
# 46 "data/maps/SSTidalCorridor/scripts.pory"
	.string "The horizon spreads beyond the\n"
	.string "porthole.$"

SSTidalCorridor_Text_BrineyWelcomeAboard::
# 50 "data/maps/SSTidalCorridor/scripts.pory"
	.string "MR. BRINEY: Welcome aboard, {PLAYER}{KUN}!\p"
	.string "They made me honorary captain of the\n"
	.string "S.S. TIDAL!\p"
	.string "You can call me CAPTAIN BRINEY now!\p"
	.string "You know, I retired once before, but\n"
	.string "when I saw this majestic ship…\p"
	.string "Let me just say, it stirred my sleeping\n"
	.string "soul as a sailor!$"

SSTidalCorridor_Text_Peeko::
# 54 "data/maps/SSTidalCorridor/scripts.pory"
	.string "PEEKO: Pihyo pihyohyo…$"

SSTidalCorridor_Text_Cabin1::
# 58 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 1$"

SSTidalCorridor_Text_Cabin2::
# 62 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 2$"

SSTidalCorridor_Text_Cabin3::
# 66 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 3$"

SSTidalCorridor_Text_Cabin4::
# 70 "data/maps/SSTidalCorridor/scripts.pory"
	.string "Cabin 4$"
