CeruleanCity_House5_MapScripts::
	.byte 0


CeruleanCity_House1_Text_AnyInterestInBerries::
# 5 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "I concoct a variety of medicine from\n"
	.string "BERRY POWDER.\p"
	.string "Using good BERRY POWDER, I can make any\n"
	.string "kind of medicine.\p"
	.string "Now tell me, have you any interest in\n"
	.string "BERRIES?$"

CeruleanCity_House1_Text_HaveJustTheThing::
# 9 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Ah, good! For you, then, I have just the\n"
	.string "thing.$"

CeruleanCity_House1_Text_GoCrushBerriesAtDirectCorner::
# 13 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "There's something new on the second\n"
	.string "floor of POKéMON CENTERS, at the\l"
	.string "DIRECT CORNER.\p"
	.string "They installed a Wireless Adapter\n"
	.string "machine for crushing BERRIES.\p"
	.string "This is where you come in.\p"
	.string "I have a favor to ask, one that I can\n"
	.string "entrust only to you.\p"
	.string "Could you make BERRY POWDER for me\n"
	.string "using that machine?\p"
	.string "Don't forget, the machine is at the\n"
	.string "DIRECT CORNER of POKéMON CENTERS.\p"
	.string "I'll concoct medicine for you if you\n"
	.string "bring me some BERRY POWDER.\p"
	.string "Don't forget, crush BERRIES into BERRY\n"
	.string "POWDER and bring it to me.$"

CeruleanCity_House1_Text_WhyMustYouLieNoBerries::
# 17 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Why must you lie to me?\p"
	.string "How many BERRIES do you have? Not a\n"
	.string "one!$"

CeruleanCity_House1_Text_TakeInterestInAllSortsOfThings::
# 21 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "You have no interest in BERRIES?\p"
	.string "Young one, it's important to take an\n"
	.string "interest in all sorts of things.$"

CeruleanCity_House1_Text_HaveYouBroughtBerryPowder::
# 25 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Er-hem! Have you brought me some BERRY\n"
	.string "POWDER?$"

CeruleanCity_House5_Text_ExchangeWithWhat::
# 29 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "With what would you like to exchange\n"
	.string "it?$"

CeruleanCity_House1_Text_YoullExchangeBerryPowderForItem::
# 33 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Fine, you'll exchange your BERRY POWDER\n"
	.string "for one {STR_VAR_1}?$"

CeruleanCity_House1_Text_DontHaveEnoughBerryPowder::
# 37 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Hm? You don't have enough BERRY\n"
	.string "POWDER.$"

CeruleanCity_House1_Text_TradeMoreBerryPowder::
# 41 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "This is fine BERRY POWDER indeed. It will\n"
	.string "make excellent medicine.\p"
	.string "Would you like to trade more BERRY\n"
	.string "POWDER for something else?$"

CeruleanCity_House1_Text_HopeToSeeYouAgain::
# 45 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "That's fine, then. I'll hope to see you\n"
	.string "back again.$"

CeruleanCity_House1_Text_SeeMeIfYoudLikeToTradePowder::
# 49 "data/maps/CeruleanCity_House5/scripts.pory"
	.string "Come see me if you'd like to trade your\n"
	.string "BERRY POWDER.$"
