Route2_ViridianForest_NorthEntrance_MapScripts::
	.byte 0


Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
# 5 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Many POKéMON live only in forests and\n"
	.string "caves.\p"
	.string "You need to be persistent and look\n"
	.string "everywhere to get different kinds.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
# 9 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Have you noticed the skinny trees on\n"
	.string "the roadside?\p"
	.string "They can be cut down by a special\n"
	.string "POKéMON move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
# 13 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Do you know the evolution-cancel\n"
	.string "technique?\p"
	.string "When a POKéMON is evolving, you can\n"
	.string "stop the process.\p"
	.string "It's a technique for raising POKéMON\n"
	.string "the way they are.$"
