Route2_ViridianForest_NorthEntrance_MapScripts::
	.byte 0


Route2_ViridianForest_NorthEntrance_EventScript_CooltrainerF::
# 5 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution, MSGBOX_NPC
	end


Route2_ViridianForest_NorthEntrance_EventScript_OldMan::
# 10 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees, MSGBOX_NPC
	end


Route2_ViridianForest_NorthEntrance_EventScript_Youngster::
# 15 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests, MSGBOX_NPC
	end


Route2_ViridianForest_NorthEntrance_Text_CanCancelEvolution::
# 20 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Do you know the evolution-cancel\n"
	.string "technique?\p"
	.string "When a POKéMON is evolving, you\n"
	.string "can stop the process.\p"
	.string "It's a technique for raising\n"
	.string "POKéMON the way they are.$"

Route2_ViridianForest_NorthEntrance_Text_CanCutSkinnyTrees::
# 24 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Have you noticed the skinny trees\n"
	.string "on the roadside?\p"
	.string "They can be cut down by a special\n"
	.string "POKéMON move, I hear.$"

Route2_ViridianForest_NorthEntrance_Text_ManyMonsOnlyInForests::
# 28 "data/maps/Route2_ViridianForest_NorthEntrance/scripts.pory"
	.string "Many POKéMON live only in forests\n"
	.string "and caves.\p"
	.string "You need to be persistent and look\n"
	.string "everywhere to get different kinds.$"
