MtPyre_3F_MapScripts::
	.byte 0


MtPyre_3F_MapScripts::
	return


MtPyre_3F_Text_WilliamIntro::
# 8 "data/maps/MtPyre_3F/scripts.pory"
	.string "The rich atmosphere of the mountain\n"
	.string "has elevated my psychic power!\p"
	.string "A mere child like you… You dream of\n"
	.string "winning?$"

MtPyre_3F_Text_WilliamDefeat::
# 12 "data/maps/MtPyre_3F/scripts.pory"
	.string "I drown in self-pity…$"

MtPyre_3F_Text_WilliamPostBattle::
# 16 "data/maps/MtPyre_3F/scripts.pory"
	.string "My psychic powers have surely grown\n"
	.string "several times, but…$"

MtPyre_3F_Text_KaylaIntro::
# 20 "data/maps/MtPyre_3F/scripts.pory"
	.string "Ahahahaha!\p"
	.string "This is no place for children, least of\n"
	.string "all you!$"

MtPyre_3F_Text_KaylaDefeat::
# 24 "data/maps/MtPyre_3F/scripts.pory"
	.string "I lost that cleanly…$"

MtPyre_3F_Text_KaylaPostBattle::
# 28 "data/maps/MtPyre_3F/scripts.pory"
	.string "This means my training is still not\n"
	.string "enough…\p"
	.string "I've got to keep working toward the\n"
	.string "summit…\p"
	.string "Go, me!$"

MtPyre_3F_Text_GabrielleIntro::
# 32 "data/maps/MtPyre_3F/scripts.pory"
	.string "Why have you come here?$"

MtPyre_3F_Text_GabrielleDefeat::
# 36 "data/maps/MtPyre_3F/scripts.pory"
	.string "That was amazing! You're a very special\n"
	.string "TRAINER.$"

MtPyre_3F_Text_GabriellePostBattle::
# 40 "data/maps/MtPyre_3F/scripts.pory"
	.string "POKéMON no longer of this world.\n"
	.string "POKéMON that are with you now.\p"
	.string "And the POKéMON that you will meet in\n"
	.string "the future…\p"
	.string "They are all to be equally cherished.\n"
	.string "Please remember that.$"

MtPyre_3F_Text_GabrielleRegister::
# 44 "data/maps/MtPyre_3F/scripts.pory"
	.string "I would like to see your POKéMON when\n"
	.string "they grow up some more…\p"
	.string "Please, I need to see your POKéNAV.$"

MtPyre_3F_Text_GabrielleRematchIntro::
# 48 "data/maps/MtPyre_3F/scripts.pory"
	.string "Oh, it's you…\p"
	.string "Have you come to show me your grown\n"
	.string "POKéMON?$"

MtPyre_3F_Text_GabrielleRematchDefeat::
# 52 "data/maps/MtPyre_3F/scripts.pory"
	.string "How amazing! You are a special person.$"

MtPyre_3F_Text_GabriellePostRematch::
# 56 "data/maps/MtPyre_3F/scripts.pory"
	.string "POKéMON no longer of this world.\n"
	.string "POKéMON that are with you now.\p"
	.string "And the POKéMON that you will meet in\n"
	.string "the future…\p"
	.string "They are all to be equally cherished. I\n"
	.string "see that you've remembered that.$"
