MtPyre_3F_MapScripts::
	.byte 0


MtPyre_3F_Text_WilliamIntro::
# 5 "data/maps/MtPyre_3F/scripts.pory"
	.string "The rich atmosphere of the mountain\n"
	.string "has elevated my psychic power!\p"
	.string "A mere child like you You dream of\n"
	.string "winning?$"

MtPyre_3F_Text_WilliamDefeat::
# 9 "data/maps/MtPyre_3F/scripts.pory"
	.string "I drown in self-pity$"

MtPyre_3F_Text_WilliamPostBattle::
# 13 "data/maps/MtPyre_3F/scripts.pory"
	.string "My psychic powers have surely grown\n"
	.string "several times, but$"

MtPyre_3F_Text_KaylaIntro::
# 17 "data/maps/MtPyre_3F/scripts.pory"
	.string "Ahahahaha!\p"
	.string "This is no place for children, least of\n"
	.string "all you!$"

MtPyre_3F_Text_KaylaDefeat::
# 21 "data/maps/MtPyre_3F/scripts.pory"
	.string "I lost that cleanly$"

MtPyre_3F_Text_KaylaPostBattle::
# 25 "data/maps/MtPyre_3F/scripts.pory"
	.string "This means my training is still not\n"
	.string "enough\p"
	.string "I've got to keep working toward the\n"
	.string "summit\p"
	.string "Go, me!$"

MtPyre_3F_Text_GabrielleIntro::
# 29 "data/maps/MtPyre_3F/scripts.pory"
	.string "Why have you come here?$"

MtPyre_3F_Text_GabrielleDefeat::
# 33 "data/maps/MtPyre_3F/scripts.pory"
	.string "That was amazing! You're a very special\n"
	.string "TRAINER.$"

MtPyre_3F_Text_GabriellePostBattle::
# 37 "data/maps/MtPyre_3F/scripts.pory"
	.string "POKMON no longer of this world. POKMON\n"
	.string "that are with you now.\p"
	.string "And the POKMON that you will meet in the\n"
	.string "future\p"
	.string "They are all to be equally cherished.\n"
	.string "Please remember that.$"

MtPyre_3F_Text_GabrielleRegister::
# 41 "data/maps/MtPyre_3F/scripts.pory"
	.string "I would like to see your POKMON when\n"
	.string "they grow up some more\p"
	.string "Please, I need to see your POKNAV.$"

MtPyre_3F_Text_GabrielleRematchIntro::
# 45 "data/maps/MtPyre_3F/scripts.pory"
	.string "Oh, it's you\p"
	.string "Have you come to show me your grown\n"
	.string "POKMON?$"

MtPyre_3F_Text_GabrielleRematchDefeat::
# 49 "data/maps/MtPyre_3F/scripts.pory"
	.string "How amazing! You are a special person.$"

MtPyre_3F_Text_GabriellePostRematch::
# 53 "data/maps/MtPyre_3F/scripts.pory"
	.string "POKMON no longer of this world. POKMON\n"
	.string "that are with you now.\p"
	.string "And the POKMON that you will meet in the\n"
	.string "future\p"
	.string "They are all to be equally cherished. I\n"
	.string "see that you've remembered that.$"
