MtPyre_3F_MapScripts::
	.byte 0


MtPyre_3F_EventScript_Gabrielle::
# 5 "data/maps/MtPyre_3F/scripts.pory"
	trainerbattle_double TRAINER_GABRIELLE, MtPyre_3F_Text_GabrielleIntro, MtPyre_3F_Text_GabrielleDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MtPyre_3F/scripts.pory"
	msgbox MtPyre_3F_Text_GabriellePostBattle
	return


MtPyre_3F_EventScript_Kayla::
# 10 "data/maps/MtPyre_3F/scripts.pory"
	trainerbattle_double TRAINER_KAYLA, MtPyre_3F_Text_KaylaIntro, MtPyre_3F_Text_KaylaDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MtPyre_3F/scripts.pory"
	msgbox MtPyre_3F_Text_KaylaPostBattle
	return


MtPyre_3F_EventScript_William::
# 15 "data/maps/MtPyre_3F/scripts.pory"
	trainerbattle_double TRAINER_WILLIAM, MtPyre_3F_Text_WilliamIntro, MtPyre_3F_Text_WilliamDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/MtPyre_3F/scripts.pory"
	msgbox MtPyre_3F_Text_WilliamPostBattle
	return


MtPyre_3F_Text_GabrielleDefeat::
# 21 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_GabrielleDefeat$"

MtPyre_3F_Text_GabrielleIntro::
# 25 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_GabrielleIntro$"

MtPyre_3F_Text_GabriellePostBattle::
# 29 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_GabriellePostBattle$"

MtPyre_3F_Text_KaylaDefeat::
# 33 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_KaylaDefeat$"

MtPyre_3F_Text_KaylaIntro::
# 37 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_KaylaIntro$"

MtPyre_3F_Text_KaylaPostBattle::
# 41 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_KaylaPostBattle$"

MtPyre_3F_Text_WilliamDefeat::
# 45 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_WilliamDefeat$"

MtPyre_3F_Text_WilliamIntro::
# 49 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_WilliamIntro$"

MtPyre_3F_Text_WilliamPostBattle::
# 53 "data/maps/MtPyre_3F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_3F_Text_WilliamPostBattle$"

MtPyre_3F_Text_GabriellePostRematch::
# 57 "data/maps/MtPyre_3F/scripts.pory"
	.string "POKéMON no longer of this world.\n"
	.string "POKéMON that are with you now.\p"
	.string "And the POKéMON that you will meet\n"
	.string "in the future…\p"
	.string "They are all to be equally cherished.\n"
	.string "I see that you've remembered that.$"

MtPyre_3F_Text_GabrielleRegister::
# 61 "data/maps/MtPyre_3F/scripts.pory"
	.string "I would like to see your POKéMON\n"
	.string "when they grow up some more…\p"
	.string "Please, I need to see your POKéNAV.$"
