FiveIsland_LostCave_Room2_MapScripts::
	.byte 0


FiveIsland_LostCave_Room2_EventScript_SmithNPC1::
# 5 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	msgbox FiveIsland_LostCave_Room2_Text_SmithNPC1, MSGBOX_NPC
	end


FiveIsland_LostCave_Room2_EventScript_SmithNPC2::
# 14 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	msgbox FiveIsland_LostCave_Room2_Text_SmithNPC2, MSGBOX_NPC
	end


FiveIsland_LostCave_Room2_EventScript_SmithNPC3::
# 23 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	msgbox FiveIsland_LostCave_Room2_Text_SmithNPC3, MSGBOX_NPC
	end


FiveIsland_LostCave_Room2_Text_SmithNPC1::
# 9 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

FiveIsland_LostCave_Room2_Text_SmithNPC2::
# 18 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

FiveIsland_LostCave_Room2_Text_SmithNPC3::
# 27 "data/maps/FiveIsland_LostCave_Room2/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
