SSAnne_1F_Room5_MapScripts::
	.byte 0


SSAnne_1F_Room5_Text_ArthurIntro::
# 5 "data/maps/SSAnne_1F_Room5/scripts.pory"
	.string "You insolent pup! How dare you barge in!$"

SSAnne_1F_Room5_Text_ArthurDefeat::
# 9 "data/maps/SSAnne_1F_Room5/scripts.pory"
	.string "Humph! You rude child! You have no\n"
	.string "sense of courtesy!$"

SSAnne_1F_Room5_Text_ArthurPostBattle::
# 13 "data/maps/SSAnne_1F_Room5/scripts.pory"
	.string "I wish to be left alone! Get out!$"
