BattleFrontier_BattlePikeCorridor_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePikeCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeCorridor_OnFrame
# 3 "data/maps/BattleFrontier_BattlePikeCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeCorridor_OnWarp
	.byte 0


BattleFrontier_BattlePikeCorridor_MapScripts::
# 7 "data/maps/BattleFrontier_BattlePikeCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeCorridor_OnFrame
# 8 "data/maps/BattleFrontier_BattlePikeCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeCorridor_OnWarp
	return


BattleFrontier_BattlePikeCorridor_Text_YourChallengeHasBegun::
# 12 "data/maps/BattleFrontier_BattlePikeCorridor/scripts.pory"
	.string "Your Battle Choice challenge has now\n"
	.string "begun…$"
