Route116_MapScripts::
# 2 "data/maps/Route116/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route116_OnTransition
# 3 "data/maps/Route116/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route116_OnLoad
# 4 "data/maps/Route116/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route116_OnFrame
	.byte 0


Route116_Text_ScoundrelMadeOffWithPeeko::
# 8 "data/maps/Route116/scripts.pory"
	.string "Ohhh, what am I to do?\p"
	.string "We were on our walk, PEEKO and I, when\n"
	.string "we were jumped by an odd thug…\p"
	.string "The scoundrel made off with my darling\n"
	.string "PEEKO!\p"
	.string "Wrrrooooooaaaar! PEEKO!$"

Route116_Text_WantToDigTunnel::
# 12 "data/maps/Route116/scripts.pory"
	.string "Nnn… Roar!\p"
	.string "I want to dig that tunnel!$"

Route116_Text_DiggingTunnelWhenGoonOrderedMeOut::
# 16 "data/maps/Route116/scripts.pory"
	.string "Nnn… Roar! What's going on?\p"
	.string "I was digging the tunnel without any\n"
	.string "tools when some goon ordered me out!\p"
	.string "That tunnel's filled with POKéMON that\n"
	.string "react badly to loud noises.\l"
	.string "They could cause an uproar.\p"
	.string "That's why we stopped using heavy\n"
	.string "equipment for tunneling…\p"
	.string "I'm worried that the goon will do\n"
	.string "something stupid and startle the\l"
	.string "POKéMON into an uproar.$"

Route116_Text_GoonHightailedItOutOfTunnel::
# 20 "data/maps/Route116/scripts.pory"
	.string "Nnn… Roar!\p"
	.string "That goofy goon hightailed it out of\n"
	.string "the tunnel! I can go back to digging!$"

Route116_Text_ThankYouTokenOfAppreciation::
# 24 "data/maps/Route116/scripts.pory"
	.string "Oh! It's you!\p"
	.string "You're that person who not only helped\n"
	.string "me in PETALBURG WOODS, but also got\l"
	.string "back my stolen package and then even\l"
	.string "graciously delivered it to SLATEPORT!\p"
	.string "CAPT. STERN informed us that the\n"
	.string "package arrived, too!\p"
	.string "I thank you very, very much!\p"
	.string "Why, if I were a rain cloud, I would\n"
	.string "shower you with gratitude and hail\l"
	.string "you as a hero!\p"
	.string "For you, the most wonderful TRAINER, I\n"
	.string "bear good news!\p"
	.string "Recently, our company developed a new\n"
	.string "kind of POKé BALL.\p"
	.string "As a token of our appreciation, this is\n"
	.string "our gift to our wonderful TRAINER!$"

Route116_Text_NewBallAvailableAtMart::
# 28 "data/maps/Route116/scripts.pory"
	.string "Our new POKé BALL will be available at\n"
	.string "the POKéMON MART in RUSTBORO.\p"
	.string "Please do try it out! Thank you and\n"
	.string "bye-bye!$"

Route116_Text_BagIsJamPacked::
# 32 "data/maps/Route116/scripts.pory"
	.string "Your BAG is jam-packed. I can't give you\n"
	.string "this REPEAT BALL.$"

Route116_Text_TokenOfAppreciation::
# 36 "data/maps/Route116/scripts.pory"
	.string "As a token of our appreciation for your\n"
	.string "delivering our package, I have\l"
	.string "a gift of a new kind of POKé BALL\l"
	.string "for our most wonderful TRAINER!$"

Route116_Text_CanYouHelpMeFindGlasses::
# 40 "data/maps/Route116/scripts.pory"
	.string "I dropped my glasses… Can you help me\n"
	.string "find them?$"

Route116_Text_MayISeeThoseGlasses::
# 44 "data/maps/Route116/scripts.pory"
	.string "Those glasses! May I see them for a\n"
	.string "second?$"

Route116_Text_NotWhatImLookingForMaybeTheyArentHere::
# 48 "data/maps/Route116/scripts.pory"
	.string "Hmm… These are BLACKGLASSES.\l"
	.string "They're not what I'm looking for…\p"
	.string "Maybe my glasses aren't around here…$"

Route116_Text_CantFindGlassesNotHere::
# 52 "data/maps/Route116/scripts.pory"
	.string "Hmm… I can't find my glasses anywhere…\l"
	.string "Maybe they're not around here…$"

Route116_Text_NotWhatImLookingFor::
# 56 "data/maps/Route116/scripts.pory"
	.string "Hmm… These are BLACKGLASSES.\l"
	.string "They're not what I'm looking for…$"

Route116_Text_RouteSignRustboro::
# 60 "data/maps/Route116/scripts.pory"
	.string "ROUTE 116 {LEFT_ARROW} RUSTBORO CITY$"

Route116_Text_RusturfTunnelSign::
# 64 "data/maps/Route116/scripts.pory"
	.string "RUSTURF TUNNEL “Linking RUSTBORO and\n"
	.string "VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"

Route116_Text_TunnelersRestHouse::
# 68 "data/maps/Route116/scripts.pory"
	.string "TUNNELER'S REST HOUSE$"

Route116_Text_TrainerTipsBToStopEvolution::
# 72 "data/maps/Route116/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "If you want to stop a POKéMON from\n"
	.string "evolving, press the B Button while it\l"
	.string "is trying to evolve.\l"
	.string "The startled POKéMON will stop.\p"
	.string "This is called an evolution cancel.$"

Route116_Text_TrainerTipsBagHasPockets::
# 76 "data/maps/Route116/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Your BAG has several POCKETS.\p"
	.string "Items you obtain are automatically\n"
	.string "placed in the appropriate POCKETS.\p"
	.string "No TRAINER can afford to be without a\n"
	.string "BAG of their own.$"
