VioletCity_House1_MapScripts::
	.byte 0


VioletCity_House1_EventScript_SmithNPC1::
# 5 "data/maps/VioletCity_House1/scripts.pory"
	msgbox VioletCity_House1_Text_SmithNPC1, MSGBOX_NPC
	end


VioletCity_House1_EventScript_SmithNPC2::
# 14 "data/maps/VioletCity_House1/scripts.pory"
	msgbox VioletCity_House1_Text_SmithNPC2, MSGBOX_NPC
	end


VioletCity_House1_Text_SmithNPC1::
# 9 "data/maps/VioletCity_House1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

VioletCity_House1_Text_SmithNPC2::
# 18 "data/maps/VioletCity_House1/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
