FloaromaTown_MapScripts::
	.byte 0


FloaromaTown_EventScript_Sign1::
# 6 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_Sign1, MSGBOX_SIGN
	end


FloaromaTown_EventScript_Sign2::
# 15 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_Sign2, MSGBOX_SIGN
	end


FloaromaTown_EventScript_Sign3::
# 24 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_Sign3, MSGBOX_SIGN
	end


FloaromaTown_EventScript_SmithNPC1::
# 33 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC1, MSGBOX_NPC
	end


FloaromaTown_EventScript_SmithNPC2::
# 42 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC2, MSGBOX_NPC
	end


FloaromaTown_EventScript_SmithNPC3::
# 51 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC3, MSGBOX_NPC
	end


FloaromaTown_EventScript_SmithNPC4::
# 60 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC4, MSGBOX_NPC
	end


FloaromaTown_EventScript_SmithNPC5::
# 69 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC5, MSGBOX_NPC
	end


FloaromaTown_EventScript_SmithNPC6::
# 78 "data/maps/FloaromaTown/scripts.pory"
	msgbox FloaromaTown_Text_SmithNPC6, MSGBOX_NPC
	end


FloaromaTown_Text_Sign1::
# 10 "data/maps/FloaromaTown/scripts.pory"
	.string "FloaromaTown Sign 1$"

FloaromaTown_Text_Sign2::
# 19 "data/maps/FloaromaTown/scripts.pory"
	.string "FloaromaTown Sign 2$"

FloaromaTown_Text_Sign3::
# 28 "data/maps/FloaromaTown/scripts.pory"
	.string "FloaromaTown Sign 3$"

FloaromaTown_Text_SmithNPC1::
# 37 "data/maps/FloaromaTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

FloaromaTown_Text_SmithNPC2::
# 46 "data/maps/FloaromaTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

FloaromaTown_Text_SmithNPC3::
# 55 "data/maps/FloaromaTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

FloaromaTown_Text_SmithNPC4::
# 64 "data/maps/FloaromaTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

FloaromaTown_Text_SmithNPC5::
# 73 "data/maps/FloaromaTown/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

FloaromaTown_Text_SmithNPC6::
# 82 "data/maps/FloaromaTown/scripts.pory"
	.string "It's the question that drives us, Neo.$"
