Route20_MapScripts::
# 2 "data/maps/Route20/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route20_OnTransition
	.byte 0


Route20_Text_BarryIntro::
# 6 "data/maps/Route20/scripts.pory"
	.string "The water is shallow here. There are\n"
	.string "many people swimming.$"

Route20_Text_BarryDefeat::
# 10 "data/maps/Route20/scripts.pory"
	.string "Splash!$"

Route20_Text_BarryPostBattle::
# 14 "data/maps/Route20/scripts.pory"
	.string "I wish I could ride my POKéMON. I bet\n"
	.string "you're not tired.$"

Route20_Text_ShirleyIntro::
# 18 "data/maps/Route20/scripts.pory"
	.string "SEAFOAM is a quiet getaway. I'm\n"
	.string "vacationing here.$"

Route20_Text_ShirleyDefeat::
# 22 "data/maps/Route20/scripts.pory"
	.string "Quit it!$"

Route20_Text_ShirleyPostBattle::
# 26 "data/maps/Route20/scripts.pory"
	.string "There's a huge cavern underneath this\n"
	.string "island.$"

Route20_Text_TiffanyIntro::
# 30 "data/maps/Route20/scripts.pory"
	.string "I love floating with the fishes here\n"
	.string "among the waves.$"

Route20_Text_TiffanyDefeat::
# 34 "data/maps/Route20/scripts.pory"
	.string "Yowch!$"

Route20_Text_TiffanyPostBattle::
# 38 "data/maps/Route20/scripts.pory"
	.string "Want to float with me?$"

Route20_Text_IreneIntro::
# 42 "data/maps/Route20/scripts.pory"
	.string "Are you on vacation, too?$"

Route20_Text_IreneDefeat::
# 46 "data/maps/Route20/scripts.pory"
	.string "No mercy at all!$"

Route20_Text_IrenePostBattle::
# 50 "data/maps/Route20/scripts.pory"
	.string "SEAFOAM used to be a single island in\n"
	.string "the distant past.$"

Route20_Text_DeanIntro::
# 54 "data/maps/Route20/scripts.pory"
	.string "Check out my buff physique!$"

Route20_Text_DeanDefeat::
# 58 "data/maps/Route20/scripts.pory"
	.string "Wimpy!$"

Route20_Text_DeanPostBattle::
# 62 "data/maps/Route20/scripts.pory"
	.string "I should've been buffing up my POKéMON,\n"
	.string "not me!$"

Route20_Text_DarrinIntro::
# 66 "data/maps/Route20/scripts.pory"
	.string "Why are you riding a POKéMON? Can't you\n"
	.string "swim?$"

Route20_Text_DarrinDefeat::
# 70 "data/maps/Route20/scripts.pory"
	.string "Ouch! Torpedoed!$"

Route20_Text_DarrinPostBattle::
# 74 "data/maps/Route20/scripts.pory"
	.string "Riding a POKéMON sure looks fun!$"

Route20_Text_RogerIntro::
# 78 "data/maps/Route20/scripts.pory"
	.string "I rode my bird POKéMON here.$"

Route20_Text_RogerDefeat::
# 82 "data/maps/Route20/scripts.pory"
	.string "Oh, no! Now what am I to do?$"

Route20_Text_RogerPostBattle::
# 86 "data/maps/Route20/scripts.pory"
	.string "My birds are exhausted. They can't FLY\n"
	.string "me back!$"

Route20_Text_NoraIntro::
# 90 "data/maps/Route20/scripts.pory"
	.string "My boyfriend gave me big pearls.$"

Route20_Text_NoraDefeat::
# 94 "data/maps/Route20/scripts.pory"
	.string "Oh, no! My pearls were in them!$"

Route20_Text_NoraPostBattle::
# 98 "data/maps/Route20/scripts.pory"
	.string "Will my pearls grow bigger inside\n"
	.string "CLOYSTER?$"

Route20_Text_MissyIntro::
# 102 "data/maps/Route20/scripts.pory"
	.string "I swam here from CINNABAR ISLAND. It\n"
	.string "wasn't easy, I tell you.$"

Route20_Text_MissyDefeat::
# 106 "data/maps/Route20/scripts.pory"
	.string "I'm so disappointed!$"

Route20_Text_MissyPostBattle::
# 110 "data/maps/Route20/scripts.pory"
	.string "POKéMON have taken over an abandoned\n"
	.string "mansion on CINNABAR.\p"
	.string "They call it the POKéMON MANSION now.$"

Route20_Text_MelissaIntro::
# 114 "data/maps/Route20/scripts.pory"
	.string "CINNABAR, in the west, has a LAB for\n"
	.string "POKéMON.\p"
	.string "My daddy works there.$"

Route20_Text_MelissaDefeat::
# 118 "data/maps/Route20/scripts.pory"
	.string "Wait! You're supposed to wait!$"

Route20_Text_MelissaPostBattle::
# 122 "data/maps/Route20/scripts.pory"
	.string "CINNABAR is a volcanic island.\p"
	.string "I heard it rose out of the sea when a\n"
	.string "volcano erupted.$"

Route20_Text_SeafoamIslands::
# 126 "data/maps/Route20/scripts.pory"
	.string "SEAFOAM ISLANDS$"

Route20_Text_MistyTrainsHere::
# 130 "data/maps/Route20/scripts.pory"
	.string "Strong TRAINERS and WATER POKéMON are\n"
	.string "common sights in these parts.\p"
	.string "They say that MISTY of the CERULEAN\n"
	.string "GYM trains here.$"
