SSAnne_3F_Corridor_MapScripts::
	.byte 0


SSAnne_3F_Corridor_EventScript_Sailor::
# 5 "data/maps/SSAnne_3F_Corridor/scripts.pory"
	msgbox SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons, MSGBOX_NPC
	end


SSAnne_3F_Corridor_Text_CaptainTeachesCutToMons::
# 10 "data/maps/SSAnne_3F_Corridor/scripts.pory"
	.string "Our CAPTAIN is a sword master.\n"
	.string "He's awesome at using CUT.\p"
	.string "They say he even teaches CUT\n"
	.string "to POKéMON!$"
