FiveIsland_LostCave_Entrance_MapScripts::
	.byte 0


FiveIsland_LostCave_Entrance_EventScript_SmithNPC1::
# 5 "data/maps/FiveIsland_LostCave_Entrance/scripts.pory"
	msgbox FiveIsland_LostCave_Entrance_Text_SmithNPC1, MSGBOX_NPC
	end


FiveIsland_LostCave_Entrance_EventScript_SmithNPC2::
# 14 "data/maps/FiveIsland_LostCave_Entrance/scripts.pory"
	msgbox FiveIsland_LostCave_Entrance_Text_SmithNPC2, MSGBOX_NPC
	end


FiveIsland_LostCave_Entrance_Text_SmithNPC1::
# 9 "data/maps/FiveIsland_LostCave_Entrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

FiveIsland_LostCave_Entrance_Text_SmithNPC2::
# 18 "data/maps/FiveIsland_LostCave_Entrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
