SSAnne_Kitchen_MapScripts::
	.byte 0


SSAnne_Kitchen_EventScript_Chef1::
# 5 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_BusyOutOfTheWay, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_Chef2::
# 10 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_SawOddBerryInTrash, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_Chef3::
# 15 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_SoBusyImDizzy, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_Chef4::
	end


SSAnne_Kitchen_EventScript_Chef5::
# 24 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_PeelSpudsEveryDay, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_Chef6::
# 29 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_Chef7::
# 34 "data/maps/SSAnne_Kitchen/scripts.pory"
	msgbox SSAnne_Kitchen_Text_OnlyGetToPeelOnions, MSGBOX_NPC
	end


SSAnne_Kitchen_EventScript_ItemGreatBall::
	end


SSAnne_Kitchen_Text_BusyOutOfTheWay::
# 43 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "You, mon petit!\n"
	.string "We're busy here!\l"
	.string "Out of the way!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
# 47 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "I saw an odd BERRY in the trash.\n"
	.string "I wonder what that was?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
# 51 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "I'm so busy I'm getting dizzy!\n"
	.string "You have to give me room here!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
# 55 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Hum-de-hum-de-ho…\p"
	.string "I peel spuds every day!\n"
	.string "Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
# 59 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Did you hear about SNORLAX?\n"
	.string "It's a glutton.\p"
	.string "No other POKéMON eats and sleeps\n"
	.string "the way SNORLAX can and does!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
# 63 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Snivel… Sniff…\p"
	.string "I only get to peel onions…\n"
	.string "Snivel…$"
