SSAnne_Kitchen_MapScripts::
	.byte 0


SSAnne_Kitchen_Text_BusyOutOfTheWay::
# 5 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "You, mon petit! We're busy here!\l"
	.string "Out of the way!$"

SSAnne_Kitchen_Text_SawOddBerryInTrash::
# 9 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "I saw an odd BERRY in the trash. I\n"
	.string "wonder what that was?$"

SSAnne_Kitchen_Text_SoBusyImDizzy::
# 13 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "I'm so busy I'm getting dizzy! You have\n"
	.string "to give me room here!$"

SSAnne_Kitchen_Text_PeelSpudsEveryDay::
# 17 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Hum-de-hum-de-ho…\p"
	.string "I peel spuds every day! Hum-hum…$"

SSAnne_Kitchen_Text_HearAboutSnorlaxItsAGlutton::
# 21 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Did you hear about SNORLAX? It's a\n"
	.string "glutton.\p"
	.string "No other POKéMON eats and sleeps the\n"
	.string "way SNORLAX can and does!$"

SSAnne_Kitchen_Text_OnlyGetToPeelOnions::
# 25 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Snivel… Sniff…\p"
	.string "I only get to peel onions… Snivel…$"

SSAnne_Kitchen_Text_IAmLeChefMainCourseIs::
# 29 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Er-hem! Indeed I am le CHEF!\p"
	.string "Le main course is$"

SSAnne_Kitchen_Text_SalmonDuSalad::
# 33 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Salmon du Salad!\p"
	.string "Les guests may gripe it's fish again,\n"
	.string "however!$"

SSAnne_Kitchen_Text_EelsAuBarbecue::
# 37 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Eels au Barbecue!\p"
	.string "Les guests will mutiny, I fear.$"

SSAnne_Kitchen_Text_PrimeBeefsteak::
# 41 "data/maps/SSAnne_Kitchen/scripts.pory"
	.string "Prime Beefsteak!\p"
	.string "But, have I enough fillets du beef?$"
