Route104_MrBrineysHouse_MapScripts::
# 2 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route104_MrBrineysHouse_OnTransition
	.byte 0


Route104_MrBrineysHouse_MapScripts::
# 6 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route104_MrBrineysHouse_OnTransition
	return


Route104_MrBrineysHouse_Text_WaitUpPeeko::
# 10 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Hold on, lass! Wait up,\n"
	.string "PEEKO!$"

Route104_MrBrineysHouse_Text_ItsYouLetsSailToDewford::
# 14 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "Hm? You're {PLAYER}{KUN}! You saved my\n"
	.string "darling PEEKO!\l"
	.string "We owe so much to you!\p"
	.string "What's that? You want to sail with me?\p"
	.string "Hmhm…\p"
	.string "You have a LETTER bound for DEWFORD\n"
	.string "and a package for SLATEPORT, then?\p"
	.string "Quite the busy life you must lead!\p"
	.string "But, certainly, what you're asking is no\n"
	.string "problem at all.\p"
	.string "You've come to the right man! We'll set\n"
	.string "sail for DEWFORD.$"

Route104_MrBrineysHouse_Text_SetSailForDewford::
# 18 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: DEWFORD it is, then!\p"
	.string "Anchors aweigh! PEEKO, we're setting\n"
	.string "sail, my darling!$"

Route104_MrBrineysHouse_Text_DeclineDeliverySail::
# 22 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Is that so? Your deliveries\n"
	.string "can wait?\p"
	.string "You just go on and tell me whenever you\n"
	.string "want to set sail!$"

Route104_MrBrineysHouse_Text_NeedToMakeDeliveriesSailToDewford::
# 26 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Ahoy! I know exactly what\n"
	.string "you want to say!\p"
	.string "You're to deliver a LETTER to DEWFORD\n"
	.string "and a package to SLATEPORT.\p"
	.string "What you need me to do is no problem at\n"
	.string "all--I'm the man for the job!\p"
	.string "First, we'll set sail for DEWFORD.$"

Route104_MrBrineysHouse_Text_NeedToDeliverPackageSailToDewford::
# 30 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Ahoy! I know exactly what\n"
	.string "you want to say!\p"
	.string "You're to deliver a package to CAPT.\n"
	.string "STERN in SLATEPORT.\p"
	.string "What you need me to do is no problem at\n"
	.string "all--I'm the man for the job!\p"
	.string "First, we'll set sail for DEWFORD.$"

Route104_MrBrineysHouse_Text_WhereAreWeBound::
# 34 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Ahoy! For you, I'll go out to\n"
	.string "sea anytime!\p"
	.string "Now, my friend, where are we bound?$"

Route104_MrBrineysHouse_Text_TellMeWheneverYouWantToSail::
# 38 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "MR. BRINEY: Is that so? Well, PEEKO owes\n"
	.string "her life to you.\p"
	.string "You just go on and tell me whenever you\n"
	.string "want to set sail!$"

Route104_MrBrineysHouse_Text_Peeko::
# 42 "data/maps/Route104_MrBrineysHouse/scripts.pory"
	.string "PEEKO: Pii piihyoro!$"
