SilphCo_2F_MapScripts::
# 2 "data/maps/SilphCo_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_2F_OnLoad
	.byte 0


SilphCo_2F_Text_ConnorIntro::
# 6 "data/maps/SilphCo_2F/scripts.pory"
	.string "Help! I'm a SILPH employee.$"

SilphCo_2F_Text_ConnorDefeat::
# 10 "data/maps/SilphCo_2F/scripts.pory"
	.string "How did you know I was a ROCKET?$"

SilphCo_2F_Text_ConnorPostBattle::
# 14 "data/maps/SilphCo_2F/scripts.pory"
	.string "I work for both SILPH and TEAM ROCKET.$"

SilphCo_2F_Text_JerryIntro::
# 18 "data/maps/SilphCo_2F/scripts.pory"
	.string "It's off-limits here! Go home!$"

SilphCo_2F_Text_JerryDefeat::
# 22 "data/maps/SilphCo_2F/scripts.pory"
	.string "You're good.$"

SilphCo_2F_Text_JerryPostBattle::
# 26 "data/maps/SilphCo_2F/scripts.pory"
	.string "Can you solve the maze in here? It's not\n"
	.string "easy, I tell you!$"

SilphCo_2F_Text_Grunt1Intro::
# 30 "data/maps/SilphCo_2F/scripts.pory"
	.string "No kids are allowed in here!$"

SilphCo_2F_Text_Grunt1Defeat::
# 34 "data/maps/SilphCo_2F/scripts.pory"
	.string "Tough!$"

SilphCo_2F_Text_Grunt1PostBattle::
# 38 "data/maps/SilphCo_2F/scripts.pory"
	.string "Diamond-shaped tiles are teleport\n"
	.string "blocks.\p"
	.string "They're transporters for this\n"
	.string "high-tech building.$"

SilphCo_2F_Text_Grunt2Intro::
# 42 "data/maps/SilphCo_2F/scripts.pory"
	.string "Hey, kid! What are you wandering here\n"
	.string "for?$"

SilphCo_2F_Text_Grunt2Defeat::
# 46 "data/maps/SilphCo_2F/scripts.pory"
	.string "I goofed!$"

SilphCo_2F_Text_Grunt2PostBattle::
# 50 "data/maps/SilphCo_2F/scripts.pory"
	.string "SILPH CO. will be associated with TEAM\n"
	.string "ROCKET!$"

Text_ThunderWaveTeach::
# 54 "data/maps/SilphCo_2F/scripts.pory"
	.string "Eeek! No! Stop! Help!\p"
	.string "Oh, you're not with TEAM ROCKET. I'm\n"
	.string "sorry, I thought…\p"
	.string "Will you forgive me if I teach you the\n"
	.string "THUNDER WAVE technique?$"

Text_ThunderWaveDeclined::
# 58 "data/maps/SilphCo_2F/scripts.pory"
	.string "Oh… But THUNDER WAVE is convenient…$"

Text_ThunderWaveWhichMon::
# 62 "data/maps/SilphCo_2F/scripts.pory"
	.string "Which POKéMON should I teach THUNDER\n"
	.string "WAVE?$"

Text_ThunderWaveTaught::
# 66 "data/maps/SilphCo_2F/scripts.pory"
	.string "THUNDER WAVE causes paralysis in the\n"
	.string "target POKéMON.\p"
	.string "A paralyzed POKéMON may be unable to\n"
	.string "move in battle.\p"
	.string "It's an ELECTRIC-type move, so it won't\n"
	.string "work on some POKéMON.$"

SilphCo_2F_Text_FloorSign::
# 70 "data/maps/SilphCo_2F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 2F$"
