Route21_South_MapScripts::
	.byte 0


Route21_South_Text_JackIntro::
# 5 "data/maps/Route21_South/scripts.pory"
	.string "I caught my POKéMON at sea.$"

Route21_South_Text_JackDefeat::
# 9 "data/maps/Route21_South/scripts.pory"
	.string "Diver!! Down!!$"

Route21_South_Text_JackPostBattle::
# 13 "data/maps/Route21_South/scripts.pory"
	.string "Where'd you catch your POKéMON?$"

Route21_South_Text_JeromeIntro::
# 17 "data/maps/Route21_South/scripts.pory"
	.string "Right now, I'm in a triathlon meet.$"

Route21_South_Text_JeromeDefeat::
# 21 "data/maps/Route21_South/scripts.pory"
	.string "Pant… Pant… Pant…$"

Route21_South_Text_JeromePostBattle::
# 25 "data/maps/Route21_South/scripts.pory"
	.string "I'm beat! But, I still have the bike race\n"
	.string "and marathon left!$"

Route21_South_Text_RolandIntro::
# 29 "data/maps/Route21_South/scripts.pory"
	.string "Ahh! Feel the sun and the wind!$"

Route21_South_Text_RolandDefeat::
# 33 "data/maps/Route21_South/scripts.pory"
	.string "Yow! I lost!$"

Route21_South_Text_RolandPostBattle::
# 37 "data/maps/Route21_South/scripts.pory"
	.string "I'm sunburnt to a crisp!$"

Route21_South_Text_ClaudeIntro::
# 41 "data/maps/Route21_South/scripts.pory"
	.string "Hey, don't scare away the fish!$"

Route21_South_Text_ClaudeDefeat::
# 45 "data/maps/Route21_South/scripts.pory"
	.string "Sorry! I'm just so frustrated from not\n"
	.string "catching anything.$"

Route21_South_Text_ClaudePostBattle::
# 49 "data/maps/Route21_South/scripts.pory"
	.string "Sheesh, I haven't caught a thing. Could\n"
	.string "this place actually be a\l"
	.string "giant pool or something?$"

Route21_South_Text_NolanIntro::
# 53 "data/maps/Route21_South/scripts.pory"
	.string "Keep me company till I get a hit.$"

Route21_South_Text_NolanDefeat::
# 57 "data/maps/Route21_South/scripts.pory"
	.string "That burned some time.$"

Route21_South_Text_NolanPostBattle::
# 61 "data/maps/Route21_South/scripts.pory"
	.string "Oh wait! I got a bite! Yeah!$"

Route21_North_Text_LilIntro::
# 65 "data/maps/Route21_South/scripts.pory"
	.string "LIL: Huh? A battle? IAN, can't you do it\n"
	.string "alone?$"

Route21_North_Text_LilDefeat::
# 69 "data/maps/Route21_South/scripts.pory"
	.string "LIL: Oh, see? We lost. Happy now?$"

Route21_North_Text_LilPostBattle::
# 73 "data/maps/Route21_South/scripts.pory"
	.string "LIL: I'm tired. Can't we go home\n"
	.string "already?$"

Route21_North_Text_LilNotEnoughMons::
# 77 "data/maps/Route21_South/scripts.pory"
	.string "LIL: Huh? A battle? I can't be bothered\n"
	.string "to do it alone.\l"
	.string "Bring two POKéMON, won't you?$"

Route21_North_Text_IanIntro::
# 81 "data/maps/Route21_South/scripts.pory"
	.string "IAN: My sis doesn't get enough\n"
	.string "exercise, so I made her come.$"

Route21_North_Text_IanDefeat::
# 85 "data/maps/Route21_South/scripts.pory"
	.string "IAN: Awww, Sis! Get it together!$"

Route21_North_Text_IanPostBattle::
# 89 "data/maps/Route21_South/scripts.pory"
	.string "IAN: Come on, Sis!\p"
	.string "You're not going to lose weight like\n"
	.string "this!$"

Route21_North_Text_IanNotEnoughMons::
# 93 "data/maps/Route21_South/scripts.pory"
	.string "IAN: We want a two-on-two battle. So\n"
	.string "can you bring two POKéMON?$"
