FiveIsland_WaterLabyrinth_MapScripts::
	.byte 0


FiveIsland_WaterLabyrinth_Text_LetMeTakeLookAtMons::
# 5 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "You travel all over the place, don't\n"
	.string "you?\p"
	.string "You're not driving your POKéMON too\n"
	.string "harshly, are you?\p"
	.string "Let me take a look. … … … … … …$"

FiveIsland_WaterLabyrinth_Text_HmmISeeIsee::
# 9 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "Ah, hmm… I see, I see…$"

FiveIsland_WaterLabyrinth_Text_TreatMonRightHaveThis::
# 13 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "Oh, impressive. You treat your POKéMON\n"
	.string "right.\p"
	.string "I think you can be entrusted with this.\p"
	.string "Please, I'd like you to have this.$"

FiveIsland_WaterLabyrinth_Text_ReceivedEggFromMan::
# 17 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "{PLAYER} received an EGG from the\n"
	.string "man!$"

FiveIsland_WaterLabyrinth_Text_DontHaveSpaceInYourParty::
# 21 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "…Unfortunately, you don't have space\n"
	.string "for this in your party.\p"
	.string "You'd better come back for it another\n"
	.string "time.$"

FiveIsland_WaterLabyrinth_Text_YouveComeBackForTheEgg::
# 25 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "やあ タマゴを　もらいに\l"
	.string "きて　くれたんだね$"

FiveIsland_WaterLabyrinth_Text_GladIMetSomeoneLikeYou::
# 29 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "I received that EGG while I was\n"
	.string "traveling.\p"
	.string "I'm glad I met someone like you.$"

FiveIsland_WaterLabyrinth_Text_CuteMonRemindsMeOfDaisy::
# 33 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "Oh, hello. That's a cute {STR_VAR_2}.\p"
	.string "Seeing it reminds me of a sweet little\n"
	.string "girl I met while traveling.\p"
	.string "She was gently grooming POKéMON… She\n"
	.string "was a little angel.\p"
	.string "That little girl's name… I think it was\n"
	.string "DAISY.$"

FiveIsland_WaterLabyrinth_Text_AlizeIntro::
# 37 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "This is an excellent environment for\n"
	.string "raising POKéMON.$"

FiveIsland_WaterLabyrinth_Text_AlizeDefeat::
# 41 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "Your POKéMON are growing up admirably\n"
	.string "well!$"

FiveIsland_WaterLabyrinth_Text_AlizePostBattle::
# 45 "data/maps/FiveIsland_WaterLabyrinth/scripts.pory"
	.string "You know, I think you have the talent\n"
	.string "to be a good BREEDER.$"
