SeafloorCavern_Room1_MapScripts::
	.byte 0


SeafloorCavern_Room1_Text_Grunt1Intro::
# 5 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "We don't need a kid around! Go on home\n"
	.string "already!$"

SeafloorCavern_Room1_Text_Grunt1Defeat::
# 9 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "I want to go home…$"

SeafloorCavern_Room1_Text_Grunt1PostBattle::
# 13 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "I want to get a promotion so I can boss\n"
	.string "around the GRUNTS…$"

SeafloorCavern_Room1_Text_Grunt2Intro::
# 17 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "That submarine… It's tiny inside. I'm\n"
	.string "sore all over!$"

SeafloorCavern_Room1_Text_Grunt2Defeat::
# 21 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "Losing makes me sore!$"

SeafloorCavern_Room1_Text_Grunt2PostBattle::
# 25 "data/maps/SeafloorCavern_Room1/scripts.pory"
	.string "That submarine we jacked, man, it's\n"
	.string "brutal as a ride.\l"
	.string "It's way too tight in there!$"
