FuchsiaCity_Gym_MapScripts::
	.byte 0


FuchsiaCity_Gym_Text_KogaIntro::
# 5 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "KOGA: Fwahahaha!\p"
	.string "A mere child like you dares to challenge\n"
	.string "me?\p"
	.string "The very idea makes me shiver with\n"
	.string "mirth!\p"
	.string "Very well, I shall show you true terror\n"
	.string "as a ninja master.\p"
	.string "Poison brings steady doom. Sleep\n"
	.string "renders foes helpless.\p"
	.string "Despair to the creeping horror of\n"
	.string "POISON-type POKMON!{PLAY_BGM}{MUS_RG_GYM}$"

FuchsiaCity_Gym_Text_KogaDefeat::
# 9 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Humph! You have proven your worth!\p"
	.string "Here! Take the SOULBADGE!$"

FuchsiaCity_Gym_Text_KogaPostBattle::
# 13 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "When afflicted by TOXIC, a POKMON\n"
	.string "suffers more and more.\p"
	.string "It suffers worsening damage as the\n"
	.string "battle wears on!\p"
	.string "It will surely terrorize foes!$"

FuchsiaCity_Gym_Text_KogaExplainSoulBadge::
# 17 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Now that you have the SOULBADGE, the\n"
	.string "DEFENSE of your POKMON rises.\p"
	.string "It also lets you SURF outside of battle.\p"
	.string "Ah! Take this, too!$"

FuchsiaCity_Gym_Text_ReceivedTM06FromKoga::
# 21 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "{PLAYER} received TM06 from KOGA.$"

FuchsiaCity_Gym_Text_KogaExplainTM06::
# 25 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Sealed within that TM06 lies TOXIC!\p"
	.string "It is a secret technique dating back\n"
	.string "some four hundred years.$"

FuchsiaCity_Gym_Text_MakeSpaceForThis::
# 29 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Make space for this, child!$"

FuchsiaCity_Gym_Text_KaydenIntro::
# 33 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Strength isn't the key for POKMON. Do\n"
	.string "you understand this?\p"
	.string "POKMON is about strategy!\p"
	.string "I'll show you how strategy can beat\n"
	.string "brute strength.$"

FuchsiaCity_Gym_Text_KaydenDefeat::
# 37 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "What? Extraordinary!$"

FuchsiaCity_Gym_Text_KaydenPostBattle::
# 41 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "So, you mix brawn with brains? Good\n"
	.string "strategy!\p"
	.string "That's remarkable for a child TRAINER.$"

FuchsiaCity_Gym_Text_KirkIntro::
# 45 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "I was a magician once upon a time.\p"
	.string "But I dreamt of becoming a ninja, so I\n"
	.string "joined this GYM.$"

FuchsiaCity_Gym_Text_KirkDefeat::
# 49 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "I'm done for!$"

FuchsiaCity_Gym_Text_KirkPostBattle::
# 53 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Even though I've lost, I will keep\n"
	.string "training according to the teachings\l"
	.string "of KOGA, my ninja master.$"

FuchsiaCity_Gym_Text_NateIntro::
# 57 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Let's see you beat my special\n"
	.string "techniques!$"

FuchsiaCity_Gym_Text_NateDefeat::
# 61 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "You had me fooled!$"

FuchsiaCity_Gym_Text_NatePostBattle::
# 65 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "I like poison and sleep techniques, as\n"
	.string "they linger after battle!$"

FuchsiaCity_Gym_Text_PhilIntro::
# 69 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Stop right there!\p"
	.string "The famed invisible walls of FUCHSIA\n"
	.string "GYM have you frustrated?$"

FuchsiaCity_Gym_Text_PhilDefeat::
# 73 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Whoa! You've got it!$"

FuchsiaCity_Gym_Text_PhilPostBattle::
# 77 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "You impressed me! Here's a hint!\p"
	.string "Look very closely for gaps in the\n"
	.string "invisible walls!$"

FuchsiaCity_Gym_Text_EdgarIntro::
# 81 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "I also study the way of the ninja with\n"
	.string "Master KOGA!\p"
	.string "Ninja have a long history of using\n"
	.string "animals!$"

FuchsiaCity_Gym_Text_EdgarDefeat::
# 85 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Awoo!$"

FuchsiaCity_Gym_Text_EdgarPostBattle::
# 89 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "I still have much to learn.$"

FuchsiaCity_Gym_Text_ShawnIntro::
# 93 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Master KOGA comes from a long line of\n"
	.string "ninjas.\p"
	.string "What did you descend from?$"

FuchsiaCity_Gym_Text_ShawnDefeat::
# 97 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "You're more skilled than I'd thought!$"

FuchsiaCity_Gym_Text_ShawnPostBattle::
# 101 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Where there is light, there is shadow!\p"
	.string "Light and shadow! Which do you choose?$"

FuchsiaCity_Gym_Text_GymGuyAdvice::
# 105 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "FUCHSIA GYM is a tricked-up place. It's\n"
	.string "riddled with invisible walls!\p"
	.string "KOGA might appear close, but he's\n"
	.string "blocked off.\p"
	.string "You have to find gaps in the walls to\n"
	.string "reach him.$"

FuchsiaCity_Gym_Text_GymGuyPostVictory::
# 109 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "It's amazing how ninja can terrify, even\n"
	.string "now!$"

FuchsiaCity_Gym_Text_GymStatue::
# 113 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "FUCHSIA POKMON GYM LEADER: KOGA\p"
	.string "WINNING TRAINERS: {RIVAL}$"

FuchsiaCity_Gym_Text_GymStatuePlayerWon::
# 117 "data/maps/FuchsiaCity_Gym/scripts.pory"
	.string "FUCHSIA POKMON GYM LEADER: KOGA\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
