OreburghCity_Flat1_F1_MapScripts::
	.byte 0


OreburghCity_Flat1_F1_EventScript_SmithNPC1::
# 5 "data/maps/OreburghCity_Flat1_F1/scripts.pory"
	msgbox OreburghCity_Flat1_F1_Text_SmithNPC1, MSGBOX_NPC
	end


OreburghCity_Flat1_F1_EventScript_SmithNPC2::
# 14 "data/maps/OreburghCity_Flat1_F1/scripts.pory"
	msgbox OreburghCity_Flat1_F1_Text_SmithNPC2, MSGBOX_NPC
	end


OreburghCity_Flat1_F1_Text_SmithNPC1::
# 9 "data/maps/OreburghCity_Flat1_F1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OreburghCity_Flat1_F1_Text_SmithNPC2::
# 18 "data/maps/OreburghCity_Flat1_F1/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
