PokemonLeague_HallOfFame_MapScripts::
# 2 "data/maps/PokemonLeague_HallOfFame/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_HallOfFame_OnFrame
# 3 "data/maps/PokemonLeague_HallOfFame/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_HallOfFame_OnWarp
	.byte 0


PokemonLeague_HallOfFame_Text_OakCongratulations::
# 7 "data/maps/PokemonLeague_HallOfFame/scripts.pory"
	.string "OAK: Er-hem! Congratulations,\n"
	.string "{PLAYER}!\p"
	.string "This floor is the POKéMON HALL OF FAME.\p"
	.string "POKéMON LEAGUE CHAMPIONS are honored\n"
	.string "for their exploits here.\p"
	.string "Their POKéMON are also recorded in the\n"
	.string "HALL OF FAME.\p"
	.string "{PLAYER}!\p"
	.string "You have worked hard to become the new\n"
	.string "LEAGUE CHAMPION.\p"
	.string "Congratulations, {PLAYER}, you and\n"
	.string "your POKéMON are HALL OF FAMERS!$"
