#ifndef GUARD_CONSTANTS_OPPONENTS_H
#define GUARD_CONSTANTS_OPPONENTS_H

#include "constants/battle_partner.h"

#define TRAINER_NONE                        0
#define TRAINER_SAWYER                                     1
#define TRAINER_GRUNT_AQUA_HIDEOUT                         2
#define TRAINER_GRUNT_SEAFLOOR_CAVERN                      3
#define TRAINER_GABRIELLE                                  4
#define TRAINER_GRUNT_PETALBURG_WOODS                      5
#define TRAINER_MARCEL                                     6
#define TRAINER_ALBERTO                                    7
#define TRAINER_ED                                         8
#define TRAINER_DECLAN                                     9
#define TRAINER_GRUNT_RUSTURF_TUNNEL                       10
#define TRAINER_GRUNT_WEATHER_INST                         11
#define TRAINER_GRUNT_MUSEUM                               12
#define TRAINER_GRUNT_SPACE_CENTER                         13
#define TRAINER_GRUNT_MT_PYRE                              14
#define TRAINER_GRUNT_AQUA_HIDEOUT_6                       15
#define TRAINER_FREDRICK                                   16
#define TRAINER_MATT                                       17
#define TRAINER_ZANDER                                     18
#define TRAINER_SHELLY_WEATHER_INSTITUTE                   19
#define TRAINER_SHELLY_SEAFLOOR_CAVERN                     20
#define TRAINER_ARCHIE                                     21
#define TRAINER_LEAH                                       22
#define TRAINER_DAISY                                      23
#define TRAINER_ROSE                                       24
#define TRAINER_FELIX                                      25
#define TRAINER_VIOLET                                     26
#define TRAINER_DUSTY                                      27
#define TRAINER_CHIP                                       28
#define TRAINER_FOSTER                                     29
#define TRAINER_GABBY_AND_TY                               30
#define TRAINER_GABBY_AND_TY_1                             31
#define TRAINER_GABBY_AND_TY_2                             32
#define TRAINER_GABBY_AND_TY_3                             33
#define TRAINER_GABBY_AND_TY_4                             34
#define TRAINER_GABBY_AND_TY_5                             35
#define TRAINER_GABBY_AND_TY_6                             36
#define TRAINER_LOLA                                       37
#define TRAINER_AUSTINA                                    38
#define TRAINER_GWEN                                       39
#define TRAINER_RICKY                                      40
#define TRAINER_SIMON                                      41
#define TRAINER_CHARLIE                                    42
#define TRAINER_RANDALL                                    43
#define TRAINER_PARKER                                     44
#define TRAINER_GEORGE                                     45
#define TRAINER_BERKE                                      46
#define TRAINER_BRAXTON                                    47
#define TRAINER_VINCENT                                    48
#define TRAINER_LEROY                                      49
#define TRAINER_WILTON                                     50
#define TRAINER_EDGAR                                      51
#define TRAINER_ALBERT                                     52
#define TRAINER_SAMUEL                                     53
#define TRAINER_VITO                                       54
#define TRAINER_OWEN                                       55
#define TRAINER_WARREN                                     56
#define TRAINER_MARY                                       57
#define TRAINER_ALEXIA                                     58
#define TRAINER_JODY                                       59
#define TRAINER_WENDY                                      60
#define TRAINER_KEIRA                                      61
#define TRAINER_BROOKE                                     62
#define TRAINER_JENNIFER                                   63
#define TRAINER_HOPE                                       64
#define TRAINER_SHANNON                                    65
#define TRAINER_MICHELLE                                   66
#define TRAINER_CAROLINE                                   67
#define TRAINER_JULIE                                      68
#define TRAINER_PATRICIA                                   69
#define TRAINER_KINDRA                                     70
#define TRAINER_TAMMY                                      71
#define TRAINER_VALERIE                                    72
#define TRAINER_TASHA                                      73
#define TRAINER_CINDY                                      74
#define TRAINER_DAPHNE                                     75
#define TRAINER_BRIANNA                                    76
#define TRAINER_NAOMI                                      77
#define TRAINER_CINDY_6                                    78
#define TRAINER_MELISSA                                    79
#define TRAINER_SHEILA                                     80
#define TRAINER_SHIRLEY                                    81
#define TRAINER_JESSICA                                    82
#define TRAINER_CONNIE                                     83
#define TRAINER_BRIDGET                                    84
#define TRAINER_OLIVIA                                     85
#define TRAINER_TIFFANY                                    86
#define TRAINER_WINSTON                                    87
#define TRAINER_MOLLIE                                     88
#define TRAINER_GARRET                                     89
#define TRAINER_STEVE                                      90
#define TRAINER_THALIA                                     91
#define TRAINER_MARK                                       92
#define TRAINER_GRUNT_MT_CHIMNEY                           93
#define TRAINER_LUIS                                       94
#define TRAINER_DOMINIK                                    95
#define TRAINER_DOUGLAS                                    96
#define TRAINER_DARRIN                                     97
#define TRAINER_TONY                                       98
#define TRAINER_JEROME                                     99
#define TRAINER_MATTHEW                                    100
#define TRAINER_DAVID                                      101
#define TRAINER_SPENCER                                    102
#define TRAINER_ROLAND                                     103
#define TRAINER_NOLEN                                      104
#define TRAINER_STAN                                       105
#define TRAINER_BARRY                                      106
#define TRAINER_DEAN                                       107
#define TRAINER_RODNEY                                     108
#define TRAINER_RICHARD                                    109
#define TRAINER_HERMAN                                     110
#define TRAINER_SANTIAGO                                   111
#define TRAINER_GILBERT                                    112
#define TRAINER_FRANKLIN                                   113
#define TRAINER_KEVIN                                      114
#define TRAINER_JACK                                       115
#define TRAINER_DUDLEY                                     116
#define TRAINER_CHAD                                       117
#define TRAINER_TAKAO                                      118
#define TRAINER_HITOSHI                                    119
#define TRAINER_KIYO                                       120
#define TRAINER_KOICHI                                     121
#define TRAINER_NOB                                        122
#define TRAINER_YUJI                                       123
#define TRAINER_DAISUKE                                    124
#define TRAINER_ATSUSHI                                    125
#define TRAINER_KIRK                                       126
#define TRAINER_GRUNT_AQUA_HIDEOUT_7                       127
#define TRAINER_GRUNT_AQUA_HIDEOUT_8                       128
#define TRAINER_SHAWN                                      129
#define TRAINER_FERNANDO                                   130
#define TRAINER_DALTON                                     131
#define TRAINER_COLE                                       132
#define TRAINER_JEFF                                       133
#define TRAINER_AXLE                                       134
#define TRAINER_JACE                                       135
#define TRAINER_KEEGAN                                     136
#define TRAINER_BERNIE                                     137
#define TRAINER_DREW                                       138
#define TRAINER_BEAU                                       139
#define TRAINER_LARRY                                      140
#define TRAINER_SHANE                                      141
#define TRAINER_JUSTIN                                     142
#define TRAINER_ETHAN                                      143
#define TRAINER_AUTUMN                                     144
#define TRAINER_TRAVIS                                     145
#define TRAINER_BRENT                                      146
#define TRAINER_DONALD                                     147
#define TRAINER_TAYLOR                                     148
#define TRAINER_JEFFREY                                    149
#define TRAINER_DEREK                                      150
#define TRAINER_EDWARD                                     151
#define TRAINER_PRESTON                                    152
#define TRAINER_VIRGIL                                     153
#define TRAINER_BLAKE                                      154
#define TRAINER_WILLIAM                                    155
#define TRAINER_JOSHUA                                     156
#define TRAINER_CAMERON                                    157
#define TRAINER_JACLYN                                     158
#define TRAINER_HANNAH                                     159
#define TRAINER_SAMANTHA                                   160
#define TRAINER_MAURA                                      161
#define TRAINER_KAYLA                                      162
#define TRAINER_ALEXIS                                     163
#define TRAINER_JACKI                                      164
#define TRAINER_WALTER                                     165
#define TRAINER_MICAH                                      166
#define TRAINER_THOMAS                                     167
#define TRAINER_SIDNEY                                     168
#define TRAINER_PHOEBE                                     169
#define TRAINER_GLACIA                                     170
#define TRAINER_DRAKE                                      171
#define TRAINER_ROXANNE                                    172
#define TRAINER_BRAWLY                                     173
#define TRAINER_WATTSON                                    174
#define TRAINER_FLANNERY                                   175
#define TRAINER_NORMAN                                     176
#define TRAINER_WINONA                                     177
#define TRAINER_TATE_AND_LIZA                              178
#define TRAINER_JUAN                                       179
#define TRAINER_JERRY                                      180
#define TRAINER_TED                                        181
#define TRAINER_PAUL                                       182
#define TRAINER_KAREN                                      183
#define TRAINER_GEORGIA                                    184
#define TRAINER_KATE_AND_JOY                               185
#define TRAINER_ANNA_AND_MEG                               186
#define TRAINER_VICTOR                                     187
#define TRAINER_MIGUEL                                     188
#define TRAINER_COLTON                                     189
#define TRAINER_VICTORIA                                   190
#define TRAINER_VANESSA                                    191
#define TRAINER_BETHANY                                    192
#define TRAINER_ISABEL                                     193
#define TRAINER_TIMOTHY                                    194
#define TRAINER_VICKY                                      195
#define TRAINER_SHELBY                                     196
#define TRAINER_CALVIN                                     197
#define TRAINER_BILLY                                      198
#define TRAINER_JOSH                                       199
#define TRAINER_TOMMY                                      200
#define TRAINER_JOEY                                       201
#define TRAINER_BEN                                        202
#define TRAINER_QUINCY                                     203
#define TRAINER_KATELYNN                                   204
#define TRAINER_JAYLEN                                     205
#define TRAINER_DILLON                                     206
#define TRAINER_EDDIE                                      207
#define TRAINER_ALLEN                                      208
#define TRAINER_TIMMY                                      209
#define TRAINER_WALLACE                                    210
#define TRAINER_ANDREW                                     211
#define TRAINER_IVAN                                       212
#define TRAINER_CLAUDE                                     213
#define TRAINER_ELLIOT                                     214
#define TRAINER_NED                                        215
#define TRAINER_DALE                                       216
#define TRAINER_NOLAN                                      217
#define TRAINER_BARNY                                      218
#define TRAINER_WADE                                       219
#define TRAINER_CARTER                                     220
#define TRAINER_RONALD                                     221
#define TRAINER_JACOB                                      222
#define TRAINER_ANTHONY                                    223
#define TRAINER_BENJAMIN                                   224
#define TRAINER_ABIGAIL                                    225
#define TRAINER_JASMINE                                    226
#define TRAINER_DYLAN                                      227
#define TRAINER_MARIA                                      228
#define TRAINER_CAMDEN                                     229
#define TRAINER_DEMETRIUS                                  230
#define TRAINER_ISAIAH                                     231
#define TRAINER_PABLO                                      232
#define TRAINER_CHASE                                      233
#define TRAINER_ISOBEL                                     234
#define TRAINER_DONNY                                      235
#define TRAINER_TALIA                                      236
#define TRAINER_KATELYN                                    237
#define TRAINER_ALLISON                                    238
#define TRAINER_NICOLAS                                    239
#define TRAINER_AARON                                      240
#define TRAINER_PERRY                                      241
#define TRAINER_HUGH                                       242
#define TRAINER_PHIL                                       243
#define TRAINER_JARED                                      244
#define TRAINER_HUMBERTO                                   245
#define TRAINER_PRESLEY                                    246
#define TRAINER_EDWARDO                                    247
#define TRAINER_COLIN                                      248
#define TRAINER_ROBERT                                     249
#define TRAINER_BENNY                                      250
#define TRAINER_CHESTER                                    251
#define TRAINER_ALEX                                       252
#define TRAINER_BECK                                       253
#define TRAINER_YASU                                       254
#define TRAINER_TAKASHI                                    255
#define TRAINER_DIANNE                                     256
#define TRAINER_JANI                                       257
#define TRAINER_LAO                                        258
#define TRAINER_LUNG                                       259
#define TRAINER_JOCELYN                                    260
#define TRAINER_LAURA                                      261
#define TRAINER_CYNDY                                      262
#define TRAINER_CORA                                       263
#define TRAINER_PAULA                                      264
#define TRAINER_MADELINE                                   265
#define TRAINER_CLARISSA                                   266
#define TRAINER_ANGELICA                                   267
#define TRAINER_BEVERLY                                    268
#define TRAINER_IMANI                                      269
#define TRAINER_KYLA                                       270
#define TRAINER_DENISE                                     271
#define TRAINER_BETH                                       272
#define TRAINER_TARA                                       273
#define TRAINER_MISSY                                      274
#define TRAINER_ALICE                                      275
#define TRAINER_JENNY                                      276
#define TRAINER_GRACE                                      277
#define TRAINER_TANYA                                      278
#define TRAINER_SHARON                                     279
#define TRAINER_NIKKI                                      280
#define TRAINER_BRENDA                                     281
#define TRAINER_KATIE                                      282
#define TRAINER_SUSIE                                      283
#define TRAINER_KARA                                       284
#define TRAINER_DANA                                       285
#define TRAINER_SIENNA                                     286
#define TRAINER_DEBRA                                      287
#define TRAINER_LINDA                                      288
#define TRAINER_KAYLEE                                     289
#define TRAINER_LAUREL                                     290
#define TRAINER_CARLEE                                     291
#define TRAINER_HEIDI                                      292
#define TRAINER_BECKY                                      293
#define TRAINER_CAROL                                      294
#define TRAINER_NANCY                                      295
#define TRAINER_MARTHA                                     296
#define TRAINER_DIANA                                      297
#define TRAINER_CEDRIC                                     298
#define TRAINER_IRENE                                      299
#define TRAINER_AMY_AND_LIV                                300
#define TRAINER_GINA_AND_MIA                               301
#define TRAINER_MIU_AND_YUKI                               302
#define TRAINER_AMY_AND_LIV_6                              303
#define TRAINER_HUEY                                       304
#define TRAINER_EDMOND                                     305
#define TRAINER_ERNEST                                     306
#define TRAINER_DWAYNE                                     307
#define TRAINER_PHILLIP                                    308
#define TRAINER_LEONARD                                    309
#define TRAINER_DUNCAN                                     310
#define TRAINER_ELI                                        311
#define TRAINER_ANNIKA                                     312
#define TRAINER_JAZMYN                                     313
#define TRAINER_JONAS                                      314
#define TRAINER_KAYLEY                                     315
#define TRAINER_AURON                                      316
#define TRAINER_KELVIN                                     317
#define TRAINER_MARLEY                                     318
#define TRAINER_REYNA                                      319
#define TRAINER_HUDSON                                     320
#define TRAINER_CONOR                                      321
#define TRAINER_EDWIN                                      322
#define TRAINER_HECTOR                                     323
#define TRAINER_TABITHA_MOSSDEEP                           324
#define TRAINER_WALLY_VR                                   325
#define TRAINER_BRENDAN_ROUTE_103_MUDKIP                   326
#define TRAINER_BRENDAN_ROUTE_110_MUDKIP                   327
#define TRAINER_BRENDAN_ROUTE_119_MUDKIP                   328
#define TRAINER_BRENDAN_ROUTE_103_TREECKO                  329
#define TRAINER_BRENDAN_ROUTE_110_TREECKO                  330
#define TRAINER_BRENDAN_ROUTE_119_TREECKO                  331
#define TRAINER_BRENDAN_ROUTE_103_TORCHIC                  332
#define TRAINER_BRENDAN_ROUTE_110_TORCHIC                  333
#define TRAINER_BRENDAN_ROUTE_119_TORCHIC                  334
#define TRAINER_MAY_ROUTE_103_MUDKIP                       335
#define TRAINER_MAY_ROUTE_110_MUDKIP                       336
#define TRAINER_MAY_ROUTE_119_MUDKIP                       337
#define TRAINER_MAY_ROUTE_103_TREECKO                      338
#define TRAINER_MAY_ROUTE_110_TREECKO                      339
#define TRAINER_MAY_ROUTE_119_TREECKO                      340
#define TRAINER_MAY_ROUTE_103_TORCHIC                      341
#define TRAINER_MAY_ROUTE_110_TORCHIC                      342
#define TRAINER_MAY_ROUTE_119_TORCHIC                      343
#define TRAINER_ISAAC                                      344
#define TRAINER_DAVIS                                      345
#define TRAINER_MITCHELL                                   346
#define TRAINER_LYDIA                                      347
#define TRAINER_HALLE                                      348
#define TRAINER_GARRISON                                   349
#define TRAINER_JACKSON                                    350
#define TRAINER_LORENZO                                    351
#define TRAINER_SEBASTIAN                                  352
#define TRAINER_CATHERINE                                  353
#define TRAINER_JENNA                                      354
#define TRAINER_SOPHIA                                     355
#define TRAINER_JULIO                                      356
#define TRAINER_GRUNT_UNUSED                               357
#define TRAINER_GRUNT_JAGGED_PASS                          358
#define TRAINER_MARC                                       359
#define TRAINER_BRENDEN                                    360
#define TRAINER_LILITH                                     361
#define TRAINER_CRISTIAN                                   362
#define TRAINER_SYLVIA                                     363
#define TRAINER_LEONARDO                                   364
#define TRAINER_ATHENA                                     365
#define TRAINER_HARRISON                                   366
#define TRAINER_CLARENCE                                   367
#define TRAINER_TERRY                                      368
#define TRAINER_NATE                                       369
#define TRAINER_KATHLEEN                                   370
#define TRAINER_CLIFFORD                                   371
#define TRAINER_NICHOLAS                                   372
#define TRAINER_GRUNT_SPACE_CENTER_6                       373
#define TRAINER_GRUNT_SPACE_CENTER_7                       374
#define TRAINER_MACEY                                      375
#define TRAINER_BRENDAN_RUSTBORO_TREECKO                   376
#define TRAINER_BRENDAN_RUSTBORO_MUDKIP                    377
#define TRAINER_PAXTON                                     378
#define TRAINER_ISABELLA                                   379
#define TRAINER_TABITHA_MT_CHIMNEY                         380
#define TRAINER_JONATHAN                                   381
#define TRAINER_BRENDAN_RUSTBORO_TORCHIC                   382
#define TRAINER_MAY_RUSTBORO_MUDKIP                        383
#define TRAINER_MAXIE_MAGMA_HIDEOUT                        384
#define TRAINER_MAXIE_MT_CHIMNEY                           385
#define TRAINER_TIANA                                      386
#define TRAINER_HALEY                                      387
#define TRAINER_JANICE                                     388
#define TRAINER_VIVI                                       389
#define TRAINER_SALLY                                      390
#define TRAINER_ROBIN                                      391
#define TRAINER_ANDREA                                     392
#define TRAINER_CRISSY                                     393
#define TRAINER_RICK                                       394
#define TRAINER_LYLE                                       395
#define TRAINER_JOSE                                       396
#define TRAINER_DOUG                                       397
#define TRAINER_GREG                                       398
#define TRAINER_KENT                                       399
#define TRAINER_JAMES                                      400
#define TRAINER_BRICE                                      401
#define TRAINER_TRENT                                      402
#define TRAINER_LENNY                                      403
#define TRAINER_LUCAS                                      404
#define TRAINER_ALAN                                       405
#define TRAINER_CLARK                                      406
#define TRAINER_ERIC                                       407
#define TRAINER_MIKE                                       408
#define TRAINER_DEZ_AND_LUKE                               409
#define TRAINER_LEA_AND_JED                                410
#define TRAINER_KIRA_AND_DAN                               411
#define TRAINER_JOHANNA                                    412
#define TRAINER_GERALD                                     413
#define TRAINER_VIVIAN                                     414
#define TRAINER_DANIELLE                                   415
#define TRAINER_HIDEO                                      416
#define TRAINER_KEIGO                                      417
#define TRAINER_RILEY                                      418
#define TRAINER_FLINT                                      419
#define TRAINER_ASHLEY                                     420
#define TRAINER_WALLY_MAUVILLE                             421
#define TRAINER_BRENDAN_LILYCOVE_MUDKIP                    422
#define TRAINER_BRENDAN_LILYCOVE_TREECKO                   423
#define TRAINER_BRENDAN_LILYCOVE_TORCHIC                   424
#define TRAINER_MAY_LILYCOVE_MUDKIP                        425
#define TRAINER_MAY_LILYCOVE_TREECKO                       426
#define TRAINER_MAY_LILYCOVE_TORCHIC                       427
#define TRAINER_JONAH                                      428
#define TRAINER_HENRY                                      429
#define TRAINER_ROGER                                      430
#define TRAINER_ALEXA                                      431
#define TRAINER_RUBEN                                      432
#define TRAINER_KOJI                                       433
#define TRAINER_WAYNE                                      434
#define TRAINER_AIDAN                                      435
#define TRAINER_REED                                       436
#define TRAINER_TISHA                                      437
#define TRAINER_TORI_AND_TIA                               438
#define TRAINER_KIM_AND_IRIS                               439
#define TRAINER_TYRA_AND_IVY                               440
#define TRAINER_MEL_AND_PAUL                               441
#define TRAINER_JOHN_AND_JAY                               442
#define TRAINER_RELI_AND_IAN                               443
#define TRAINER_LILA_AND_ROY                               444
#define TRAINER_LISA_AND_RAY                               445
#define TRAINER_CHRIS                                      446
#define TRAINER_DAWSON                                     447
#define TRAINER_SARAH                                      448
#define TRAINER_DARIAN                                     449
#define TRAINER_HAILEY                                     450
#define TRAINER_CHANDLER                                   451
#define TRAINER_KALEB                                      452
#define TRAINER_JOSEPH                                     453
#define TRAINER_ALYSSA                                     454
#define TRAINER_MARCOS                                     455
#define TRAINER_RHETT                                      456
#define TRAINER_TYRON                                      457
#define TRAINER_CELINA                                     458
#define TRAINER_BIANCA                                     459
#define TRAINER_HAYDEN                                     460
#define TRAINER_SOPHIE                                     461
#define TRAINER_COBY                                       462
#define TRAINER_LAWRENCE                                   463
#define TRAINER_WYATT                                      464
#define TRAINER_ANGELINA                                   465
#define TRAINER_KAI                                        466
#define TRAINER_CHARLOTTE                                  467
#define TRAINER_DEANDRE                                    468
#define TRAINER_GRUNT_MAGMA_HIDEOUT                        469
#define TRAINER_GRUNT_MAGMA_HIDEOUT_6                      470
#define TRAINER_GRUNT_MAGMA_HIDEOUT_7                      471
#define TRAINER_GRUNT_MAGMA_HIDEOUT_8                      472
#define TRAINER_GRUNT_MAGMA_HIDEOUT_9                      473
#define TRAINER_GRUNT_MAGMA_HIDEOUT_10                     474
#define TRAINER_GRUNT_MAGMA_HIDEOUT_11                     475
#define TRAINER_GRUNT_MAGMA_HIDEOUT_12                     476
#define TRAINER_GRUNT_MAGMA_HIDEOUT_13                     477
#define TRAINER_GRUNT_MAGMA_HIDEOUT_14                     478
#define TRAINER_GRUNT_MAGMA_HIDEOUT_15                     479
#define TRAINER_GRUNT_MAGMA_HIDEOUT_16                     480
#define TRAINER_TABITHA_MAGMA_HIDEOUT                      481
#define TRAINER_DARCY                                      482
#define TRAINER_MAXIE_MOSSDEEP                             483
#define TRAINER_PETE                                       484
#define TRAINER_ISABELLE                                   485
#define TRAINER_ANDRES                                     486
#define TRAINER_JOSUE                                      487
#define TRAINER_CAMRON                                     488
#define TRAINER_CORY                                       489
#define TRAINER_CAROLINA                                   490
#define TRAINER_ELIJAH                                     491
#define TRAINER_CELIA                                      492
#define TRAINER_BRYAN                                      493
#define TRAINER_BRANDEN                                    494
#define TRAINER_BRYANT                                     495
#define TRAINER_SHAYLA                                     496
#define TRAINER_KYRA                                       497
#define TRAINER_JAIDEN                                     498
#define TRAINER_ALIX                                       499
#define TRAINER_HELENE                                     500
#define TRAINER_MARLENE                                    501
#define TRAINER_DEVAN                                      502
#define TRAINER_JOHNSON                                    503
#define TRAINER_MELINA                                     504
#define TRAINER_BRANDI                                     505
#define TRAINER_AISHA                                      506
#define TRAINER_MAKAYLA                                    507
#define TRAINER_FABIAN                                     508
#define TRAINER_DAYTON                                     509
#define TRAINER_RACHEL                                     510
#define TRAINER_LEONEL                                     511
#define TRAINER_CALLIE                                     512
#define TRAINER_CALE                                       513
#define TRAINER_MYLES                                      514
#define TRAINER_PAT                                        515
#define TRAINER_CRISTIN                                    516
#define TRAINER_MAY_RUSTBORO_TREECKO                       517
#define TRAINER_MAY_RUSTBORO_TORCHIC                       518
#define TRAINER_ANGELO                                     519
#define TRAINER_DARIUS                                     520
#define TRAINER_STEVEN                                     521
#define TRAINER_ANABEL                                     522
#define TRAINER_TUCKER                                     523
#define TRAINER_SPENSER                                    524
#define TRAINER_GRETA                                      525
#define TRAINER_NOLAND                                     526
#define TRAINER_LUCY                                       527
#define TRAINER_BRANDON                                    528
#define TRAINER_MARIELA                                    529
#define TRAINER_ALVARO                                     530
#define TRAINER_EVERETT                                    531
#define TRAINER_RED                                        532
#define TRAINER_LEAF                                       533
#define TRAINER_BRENDAN_PLACEHOLDER                        534
#define TRAINER_MAY_PLACEHOLDER                            535
#define TRAINER_BEAUTY_BRIDGET                             536
#define TRAINER_BEAUTY_LORI                                537
#define TRAINER_BEAUTY_TAMIA                               538
#define TRAINER_BLACK_BELT_AARON                           539
#define TRAINER_BLACK_BELT_ATSUSHI                         540
#define TRAINER_BLACK_BELT_DAISUKE                         541
#define TRAINER_BLACK_BELT_HIDEKI                          542
#define TRAINER_BLACK_BELT_HITOSHI                         543
#define TRAINER_BLACK_BELT_KIYO                            544
#define TRAINER_BLACK_BELT_KOICHI                          545
#define TRAINER_BLACK_BELT_MIKE                            546
#define TRAINER_BLACK_BELT_TAKASHI                         547
#define TRAINER_BUG_CATCHER_ANTHONY                        548
#define TRAINER_BUG_CATCHER_CHARLIE                        549
#define TRAINER_BUG_CATCHER_DOUG                           550
#define TRAINER_BUG_CATCHER_GARRET                         551
#define TRAINER_BUG_CATCHER_JONAH                          552
#define TRAINER_BUG_CATCHER_KENT                           553
#define TRAINER_BUG_CATCHER_RICK                           554
#define TRAINER_BUG_CATCHER_ROBBY                          555
#define TRAINER_BUG_CATCHER_SAMMY                          556
#define TRAINER_BUG_CATCHER_VANCE                          557
#define TRAINER_BURGLAR_ARNIE                              558
#define TRAINER_BURGLAR_DUSTY                              559
#define TRAINER_BURGLAR_LEWIS                              560
#define TRAINER_BURGLAR_QUINN                              561
#define TRAINER_BURGLAR_RAMON                              562
#define TRAINER_BURGLAR_SIMON                              563
#define TRAINER_CAMPER_LIAM                                564
#define TRAINER_CAMPER_RILEY                               565
#define TRAINER_CHANNELER_AMANDA                           566
#define TRAINER_CHANNELER_ANGELICA                         567
#define TRAINER_CHANNELER_CARLY                            568
#define TRAINER_CHANNELER_EMILIA                           569
#define TRAINER_CHANNELER_HOPE                             570
#define TRAINER_CHANNELER_JANAE                            571
#define TRAINER_CHANNELER_JENNIFER                         572
#define TRAINER_CHANNELER_JODY                             573
#define TRAINER_CHANNELER_KARINA                           574
#define TRAINER_CHANNELER_LAUREL                           575
#define TRAINER_CHANNELER_PATRICIA                         576
#define TRAINER_CHANNELER_PAULA                            577
#define TRAINER_CHANNELER_RUTH                             578
#define TRAINER_CHANNELER_STACY                            579
#define TRAINER_CHANNELER_TAMMY                            580
#define TRAINER_CHANNELER_TASHA                            581
#define TRAINER_COOLTRAINER_ALEXA                          582
#define TRAINER_COOLTRAINER_CAROLINE                       583
#define TRAINER_COOLTRAINER_COLBY                          584
#define TRAINER_COOLTRAINER_GEORGE                         585
#define TRAINER_COOLTRAINER_MARY                           586
#define TRAINER_COOLTRAINER_SAMUEL                         587
#define TRAINER_COOLTRAINER_WARREN                         588
#define TRAINER_COOLTRAINER_YUJI                           589
#define TRAINER_CRUSH_GIRL_JOCELYN                         590
#define TRAINER_ENGINEER_BAILY                             591
#define TRAINER_FISHERMAN_BARNY                            592
#define TRAINER_FISHERMAN_DALE                             593
#define TRAINER_GENTLEMAN_ARTHUR                           594
#define TRAINER_GENTLEMAN_BROOKS                           595
#define TRAINER_GENTLEMAN_LAMAR                            596
#define TRAINER_GENTLEMAN_THOMAS                           597
#define TRAINER_GENTLEMAN_TUCKER                           598
#define TRAINER_GRUNT_AQUA_HIDEOUT_2                       599
#define TRAINER_GRUNT_AQUA_HIDEOUT_3                       600
#define TRAINER_GRUNT_AQUA_HIDEOUT_4                       601
#define TRAINER_GRUNT_AQUA_HIDEOUT_5                       602
#define TRAINER_GRUNT_MAGMA_HIDEOUT_2                      603
#define TRAINER_GRUNT_MAGMA_HIDEOUT_3                      604
#define TRAINER_GRUNT_MAGMA_HIDEOUT_4                      605
#define TRAINER_GRUNT_MAGMA_HIDEOUT_5                      606
#define TRAINER_GRUNT_MT_CHIMNEY_2                         607
#define TRAINER_GRUNT_MT_PYRE_2                            608
#define TRAINER_GRUNT_MT_PYRE_3                            609
#define TRAINER_GRUNT_MT_PYRE_4                            610
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_2                    611
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_3                    612
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_4                    613
#define TRAINER_GRUNT_SEAFLOOR_CAVERN_5                    614
#define TRAINER_GRUNT_SPACE_CENTER_3                       615
#define TRAINER_GRUNT_SPACE_CENTER_4                       616
#define TRAINER_GRUNT_WEATHER_INST_2                       617
#define TRAINER_GRUNT_WEATHER_INST_3                       618
#define TRAINER_GRUNT_WEATHER_INST_4                       619
#define TRAINER_GRUNT_WEATHER_INST_5                       620
#define TRAINER_HIKER_ALLEN                                621
#define TRAINER_HIKER_DUDLEY                               622
#define TRAINER_HIKER_ERIC                                 623
#define TRAINER_HIKER_LENNY                                624
#define TRAINER_HIKER_LUCAS                                625
#define TRAINER_HIKER_MARCOS                               626
#define TRAINER_HIKER_OLIVER                               627
#define TRAINER_JUGGLER_DALTON                             628
#define TRAINER_JUGGLER_GREGORY                            629
#define TRAINER_JUGGLER_KAYDEN                             630
#define TRAINER_JUGGLER_KIRK                               631
#define TRAINER_JUGGLER_NATE                               632
#define TRAINER_JUGGLER_NELSON                             633
#define TRAINER_JUGGLER_SHAWN                              634
#define TRAINER_LASS_ANN                                   635
#define TRAINER_LASS_DALIA                                 636
#define TRAINER_LASS_DAWN                                  637
#define TRAINER_LASS_IRIS                                  638
#define TRAINER_LASS_JOANA                                 639
#define TRAINER_LASS_KAY                                   640
#define TRAINER_LASS_LISA                                  641
#define TRAINER_LASS_MIRIAM                                642
#define TRAINER_MIKE_2                                     643
#define TRAINER_PICNICKER_ARIANA                           644
#define TRAINER_PICNICKER_DANA                             645
#define TRAINER_PICNICKER_DIANA                            646
#define TRAINER_PICNICKER_LEAH                             647
#define TRAINER_PICNICKER_MARCY                            648
#define TRAINER_PICNICKER_MARTHA                           649
#define TRAINER_PICNICKER_SOFIA                            650
#define TRAINER_PICNICKER_TINA                             651
#define TRAINER_PKMN_BREEDER_ALLISON                       652
#define TRAINER_PKMN_BREEDER_BETHANY                       653
#define TRAINER_PKMN_RANGER_BETH                           654
#define TRAINER_PKMN_RANGER_LOGAN                          655
#define TRAINER_POKEMANIAC_ASHTON                          656
#define TRAINER_POKEMANIAC_COOPER                          657
#define TRAINER_POKEMANIAC_DAWSON                          658
#define TRAINER_POKEMANIAC_STEVE                           659
#define TRAINER_POKEMANIAC_WINSTON                         660
#define TRAINER_PSYCHIC_CAMERON                            661
#define TRAINER_PSYCHIC_JOHAN                              662
#define TRAINER_PSYCHIC_LAURA                              663
#define TRAINER_PSYCHIC_PRESTON                            664
#define TRAINER_PSYCHIC_TYRON                              665
#define TRAINER_RUIN_MANIAC_LAWSON                         666
#define TRAINER_RUIN_MANIAC_LAYTON                         667
#define TRAINER_SAILOR_DUNCAN                              668
#define TRAINER_SAILOR_DWAYNE                              669
#define TRAINER_SAILOR_DYLAN                               670
#define TRAINER_SAILOR_EDMOND                              671
#define TRAINER_SAILOR_HUEY                                672
#define TRAINER_SAILOR_LEONARD                             673
#define TRAINER_SAILOR_PHILLIP                             674
#define TRAINER_SAILOR_TREVOR                              675
#define TRAINER_SCIENTIST_BEAU                             676
#define TRAINER_SCIENTIST_BRAYDON                          677
#define TRAINER_SCIENTIST_CONNOR                           678
#define TRAINER_SCIENTIST_ED                               679
#define TRAINER_SCIENTIST_GIDEON                           680
#define TRAINER_SCIENTIST_IVAN                             681
#define TRAINER_SCIENTIST_JERRY                            682
#define TRAINER_SCIENTIST_JOSE                             683
#define TRAINER_SCIENTIST_JOSHUA                           684
#define TRAINER_SCIENTIST_PARKER                           685
#define TRAINER_SCIENTIST_RODNEY                           686
#define TRAINER_SCIENTIST_TAYLOR                           687
#define TRAINER_SCIENTIST_TED                              688
#define TRAINER_SCIENTIST_TRAVIS                           689
#define TRAINER_SUPER_NERD_AVERY                           690
#define TRAINER_SUPER_NERD_DEREK                           691
#define TRAINER_SUPER_NERD_ERIK                            692
#define TRAINER_SUPER_NERD_JOVAN                           693
#define TRAINER_SUPER_NERD_ZAC                             694
#define TRAINER_SWIMMER_MALE_LUIS                          695
#define TRAINER_TAMER_COLE                                 696
#define TRAINER_TAMER_EDGAR                                697
#define TRAINER_TAMER_JASON                                698
#define TRAINER_TAMER_PHIL                                 699
#define TRAINER_TAMER_VINCENT                              700
#define TRAINER_TEAM_ROCKET_ADMIN                          701
#define TRAINER_TEAM_ROCKET_ADMIN_2                        702
#define TRAINER_TEAM_ROCKET_GRUNT                          703
#define TRAINER_TEAM_ROCKET_GRUNT_10                       704
#define TRAINER_TEAM_ROCKET_GRUNT_11                       705
#define TRAINER_TEAM_ROCKET_GRUNT_12                       706
#define TRAINER_TEAM_ROCKET_GRUNT_13                       707
#define TRAINER_TEAM_ROCKET_GRUNT_14                       708
#define TRAINER_TEAM_ROCKET_GRUNT_15                       709
#define TRAINER_TEAM_ROCKET_GRUNT_16                       710
#define TRAINER_TEAM_ROCKET_GRUNT_17                       711
#define TRAINER_TEAM_ROCKET_GRUNT_18                       712
#define TRAINER_TEAM_ROCKET_GRUNT_19                       713
#define TRAINER_TEAM_ROCKET_GRUNT_2                        714
#define TRAINER_TEAM_ROCKET_GRUNT_20                       715
#define TRAINER_TEAM_ROCKET_GRUNT_21                       716
#define TRAINER_TEAM_ROCKET_GRUNT_23                       717
#define TRAINER_TEAM_ROCKET_GRUNT_24                       718
#define TRAINER_TEAM_ROCKET_GRUNT_25                       719
#define TRAINER_TEAM_ROCKET_GRUNT_26                       720
#define TRAINER_TEAM_ROCKET_GRUNT_27                       721
#define TRAINER_TEAM_ROCKET_GRUNT_28                       722
#define TRAINER_TEAM_ROCKET_GRUNT_29                       723
#define TRAINER_TEAM_ROCKET_GRUNT_3                        724
#define TRAINER_TEAM_ROCKET_GRUNT_30                       725
#define TRAINER_TEAM_ROCKET_GRUNT_31                       726
#define TRAINER_TEAM_ROCKET_GRUNT_32                       727
#define TRAINER_TEAM_ROCKET_GRUNT_33                       728
#define TRAINER_TEAM_ROCKET_GRUNT_34                       729
#define TRAINER_TEAM_ROCKET_GRUNT_35                       730
#define TRAINER_TEAM_ROCKET_GRUNT_36                       731
#define TRAINER_TEAM_ROCKET_GRUNT_37                       732
#define TRAINER_TEAM_ROCKET_GRUNT_38                       733
#define TRAINER_TEAM_ROCKET_GRUNT_39                       734
#define TRAINER_TEAM_ROCKET_GRUNT_4                        735
#define TRAINER_TEAM_ROCKET_GRUNT_40                       736
#define TRAINER_TEAM_ROCKET_GRUNT_41                       737
#define TRAINER_TEAM_ROCKET_GRUNT_42                       738
#define TRAINER_TEAM_ROCKET_GRUNT_46                       739
#define TRAINER_TEAM_ROCKET_GRUNT_47                       740
#define TRAINER_TEAM_ROCKET_GRUNT_48                       741
#define TRAINER_TEAM_ROCKET_GRUNT_49                       742
#define TRAINER_TEAM_ROCKET_GRUNT_50                       743
#define TRAINER_TEAM_ROCKET_GRUNT_51                       744
#define TRAINER_TEAM_ROCKET_GRUNT_7                        745
#define TRAINER_TEAM_ROCKET_GRUNT_8                        746
#define TRAINER_TEAM_ROCKET_GRUNT_9                        747
#define TRAINER_YOUNGSTER_CORDELL                          748
#define TRAINER_YOUNGSTER_JOHNSON                          749
#define TRAINER_YOUNGSTER_JOSH                             750
#define TRAINER_YOUNGSTER_NASH                             751
#define TRAINER_YOUNGSTER_TYLER                            752


// NOTE: Because each Trainer uses a flag to determine when they are defeated, there is only space for 9 additional trainers before trainer flag space overflows
// Missing trainer constants from .pory files
//       More space can be made by shifting flags around in constants/flags.h or changing how trainer flags are handled
//       MAX_TRAINERS_COUNT can be increased but will take up additional saveblock space

#define TRAINERS_COUNT                      1135
#define MAX_TRAINERS_COUNT                  1200
#define TRAINER_PARTNER(partner)           (MAX_TRAINERS_COUNT + partner)

#endif  // GUARD_CONSTANTS_OPPONENTS_H
