SafariZone_West_MapScripts::
	.byte 0


SafariZone_West_Text_RestHouse::
# 5 "data/maps/SafariZone_West/scripts.pory"
	.string "REST HOUSE$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
# 9 "data/maps/SafariZone_West/scripts.pory"
	.string "REQUEST NOTICE\p"
	.string "Please find the SAFARI WARDEN's lost\n"
	.string "GOLD TEETH.\l"
	.string "They're around here somewhere.\p"
	.string "Reward offered! Contact: WARDEN$"

SafariZone_West_Text_SearchForSecretHouse::
# 13 "data/maps/SafariZone_West/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Zone Exploration Campaign! The Search\n"
	.string "for the SECRET HOUSE!$"

SafariZone_West_Text_AreaSign::
# 17 "data/maps/SafariZone_West/scripts.pory"
	.string "AREA 3 EAST: CENTER AREA$"
