SafariZone_West_MapScripts::
	.byte 0


SafariZone_West_EventScript_AreaSign::
# 5 "data/maps/SafariZone_West/scripts.pory"
	msgbox SafariZone_West_Text_AreaSign, MSGBOX_SIGN
	end


SafariZone_West_EventScript_ItemGoldTeeth::
	end


SafariZone_West_EventScript_ItemMaxPotion::
	end


SafariZone_West_EventScript_ItemMaxRevive::
	end


SafariZone_West_EventScript_ItemTM32::
	end


SafariZone_West_EventScript_LostTeethNotice::
# 26 "data/maps/SafariZone_West/scripts.pory"
	msgbox SafariZone_West_Text_PleaseFindWardensLostTeeth, MSGBOX_SIGN
	end


SafariZone_West_EventScript_RestHouseSign::
# 31 "data/maps/SafariZone_West/scripts.pory"
	msgbox SafariZone_West_Text_RestHouse, MSGBOX_SIGN
	end


SafariZone_West_EventScript_TrainerTips::
# 36 "data/maps/SafariZone_West/scripts.pory"
	msgbox SafariZone_West_Text_SearchForSecretHouse, MSGBOX_SIGN
	end


SafariZone_West_Text_RestHouse::
# 41 "data/maps/SafariZone_West/scripts.pory"
	.string "REST HOUSE$"

SafariZone_West_Text_SearchForSecretHouse::
# 45 "data/maps/SafariZone_West/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Zone Exploration Campaign! The Search\n"
	.string "for the SECRET HOUSE!$"

SafariZone_West_Text_AreaSign::
# 49 "data/maps/SafariZone_West/scripts.pory"
	.string "AREA 3 EAST: CENTER AREA$"

SafariZone_West_Text_PleaseFindWardensLostTeeth::
# 53 "data/maps/SafariZone_West/scripts.pory"
	.string "REQUEST NOTICE\p"
	.string "Please find the SAFARI WARDEN's lost\n"
	.string "GOLD TEETH.\l"
	.string "They're around here somewhere.\p"
	.string "Reward offered! Contact: WARDEN$"
