Route121_SafariZoneEntrance_MapScripts::
	.byte 0


Route121_SafariZoneEntrance_EventScript_EntranceCounterTrigger::
# 5 "data/maps/Route121_SafariZoneEntrance/scripts.pory"
	msgbox Route121_SafariZoneEntrance_Text_WouldYouLikeToPlay, MSGBOX_YESNO
	end


Route121_SafariZoneEntrance_EventScript_InfoAttendant::
# 10 "data/maps/Route121_SafariZoneEntrance/scripts.pory"
	msgbox Route121_SafariZoneEntrance_Text_WelcomeFirstTime, MSGBOX_YESNO
	end


Route121_SafariZoneEntrance_EventScript_TrainerTipSign::
# 15 "data/maps/Route121_SafariZoneEntrance/scripts.pory"
	msgbox Route121_SafariZoneEntrance_Text_TrainerTip, MSGBOX_SIGN
	end


Route121_SafariZoneEntrance_EventScript_WelcomeAttendant::
# 20 "data/maps/Route121_SafariZoneEntrance/scripts.pory"
	msgbox Route121_SafariZoneEntrance_Text_WelcomeToSafariZone, MSGBOX_NPC
	end

