LilycoveCity_DepartmentStore_5F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_5F_EventScript_ClerkFarLeft::
	end


LilycoveCity_DepartmentStore_5F_EventScript_ClerkFarRight::
	end


LilycoveCity_DepartmentStore_5F_EventScript_ClerkMidLeft::
	end


LilycoveCity_DepartmentStore_5F_EventScript_ClerkMidRight::
	end


LilycoveCity_DepartmentStore_5F_EventScript_LittleGirl::
# 21 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_5F_EventScript_PokefanF::
# 26 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_5F_EventScript_Woman::
	end


LilycoveCity_DepartmentStore_5F_Text_PlaceFullOfCuteDolls::
# 34 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	.string "This place is full of cute DOLLS.\p"
	.string "I should buy some for me, instead of\n"
	.string "just for my children.$"

LilycoveCity_DepartmentStore_5F_Text_SellManyCuteMatsHere::
# 38 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	.string "They sell many cute MATS here.\p"
	.string "I wonder which one I should get?\n"
	.string "Maybe I'll buy them all…$"

LilycoveCity_DepartmentStore_5F_Text_ClosedRooftopForWeather::
# 42 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	.string "I think they closed the rooftop\n"
	.string "because the weather is wild today.$"

LilycoveCity_DepartmentStore_5F_Text_GettingDollInsteadOfPokemon::
# 46 "data/maps/LilycoveCity_DepartmentStore_5F/scripts.pory"
	.string "I'm not big enough to raise POKéMON,\n"
	.string "so I'm getting a cute DOLL instead.$"
