PacifidlogTown_House1_MapScripts::
	.byte 0


PacifidlogTown_House1_Text_RegiStory::
# 5 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "In the HOENN region, there are three\n"
	.string "POKéMON that represent the power of\l"
	.string "rock, ice, and steel.\p"
	.string "Each of them is said to hide away deep\n"
	.string "inside caves.\p"
	.string "That's the story I heard when I was\n"
	.string "just a little kid.$"

PacifidlogTown_House1_Text_SixDotsOpenThreeDoors::
# 9 "data/maps/PacifidlogTown_House1/scripts.pory"
	.string "“Six dots open three doors.”\p"
	.string "Grandpa used to say that, but I don't\n"
	.string "know what he meant.$"
