Route23_MapScripts::
	.byte 0


Route23_EventScript_CascadeBadgeGuard::
	end


Route23_EventScript_CascadeBadgeGuardTrigger::
	end


Route23_EventScript_EarthBadgeGuard::
	end


Route23_EventScript_EarthBadgeGuardTrigger::
	end


Route23_EventScript_MarshBadgeGuard::
	end


Route23_EventScript_MarshBadgeGuardTrigger::
	end


Route23_EventScript_RainbowBadgeGuard::
	end


Route23_EventScript_RainbowBadgeGuardTrigger::
	end


Route23_EventScript_SoulBadgeGuard::
	end


Route23_EventScript_SoulBadgeGuardTrigger::
	end


Route23_EventScript_ThunderBadgeGuard::
	end


Route23_EventScript_ThunderBadgeGuardTrigger::
	end


Route23_EventScript_VictoryRoadGateSign::
# 53 "data/maps/Route23/scripts.pory"
	msgbox Route23_Text_VictoryRoadGateSign, MSGBOX_SIGN
	end


Route23_EventScript_VolcanoBadgeGuard::
	end


Route23_EventScript_VolcanoBadgeGuardTrigger::
	end


Route23_Text_VictoryRoadGateSign::
# 66 "data/maps/Route23/scripts.pory"
	.string "VICTORY ROAD GATE - POKéMON LEAGUE$"
