VermilionCity_House1_MapScripts::
	.byte 0


VermilionCity_House1_Text_ImFishingGuruDoYouLikeToFish::
# 5 "data/maps/VermilionCity_House1/scripts.pory"
	.string "I'm the FISHING GURU!\p"
	.string "I simply looove fishing! I can't bear to\n"
	.string "go without.\p"
	.string "Tell me, do you like to fish?$"

VermilionCity_House1_Text_TakeThisAndFish::
# 9 "data/maps/VermilionCity_House1/scripts.pory"
	.string "Grand! I like your style. I think we can\n"
	.string "be friends.\p"
	.string "Take this and fish, young friend!$"

VermilionCity_House1_Text_ReceivedOldRodFromFishingGuru::
# 13 "data/maps/VermilionCity_House1/scripts.pory"
	.string "{PLAYER} received an OLD ROD from the\n"
	.string "FISHING GURU.$"

VermilionCity_House1_Text_FishingIsAWayOfLife::
# 17 "data/maps/VermilionCity_House1/scripts.pory"
	.string "Fishing is a way of life! It is like the\n"
	.string "finest poetry.\p"
	.string "From the seas to rivers, go out and land\n"
	.string "the big one, my friend.$"

VermilionCity_House1_Text_OhThatsSoDisappointing::
# 21 "data/maps/VermilionCity_House1/scripts.pory"
	.string "Oh That's so disappointing$"

VermilionCity_House1_Text_HowAreTheFishBiting::
# 25 "data/maps/VermilionCity_House1/scripts.pory"
	.string "Hello there, {PLAYER}!\p"
	.string "How are the fish biting?$"

VermilionCity_House1_Text_NoRoomForNiceGift::
# 29 "data/maps/VermilionCity_House1/scripts.pory"
	.string "Oh, no!\p"
	.string "I had a nice gift for you, but you have\n"
	.string "no room for it!$"
