FallarborTown_BattleTentCorridor_MapScripts::
# 2 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentCorridor_OnFrame
	.byte 0


FallarborTown_BattleTentCorridor_MapScripts::
# 6 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentCorridor_OnFrame
	return


FallarborTown_ContestHall_Text_DoAllRightInPreliminary::
# 10 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	.string "We do all right in the preliminary round,\n"
	.string "but we can never win the appeals…\p"
	.string "Maybe it means I have to watch what\n"
	.string "other contestants are doing…$"

FallarborTown_ContestHall_Text_MonAllTheseRibbons::
# 14 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	.string "See! My POKéMON won all these RIBBONS!\p"
	.string "Have your POKéMON earned any RIBBONS?\n"
	.string "You can check them on your POKéNAV.$"

FallarborTown_ContestHall_Text_CantWinEverywhere::
# 18 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	.string "I can't beat GYM LEADERS…\p"
	.string "I can't win any CONTESTS…\p"
	.string "I've been here, there, and everywhere,\n"
	.string "and it's all for naught…$"

FallarborTown_ContestHall_Text_SuperRankStage::
# 22 "data/maps/FallarborTown_BattleTentCorridor/scripts.pory"
	.string "POKéMON CONTESTS SUPER RANK STAGE!$"
