Route44_MapScripts::
	.byte 0


Route44_EventScript_Sign1::
# 6 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_Sign1, MSGBOX_SIGN
	end


Route44_EventScript_Sign2::
# 15 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_Sign2, MSGBOX_SIGN
	end


Route44_EventScript_SmithNPC1::
# 24 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC1, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC2::
# 33 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC2, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC3::
# 42 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC3, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC4::
# 51 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC4, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC5::
# 60 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC5, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC6::
# 69 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC6, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC7::
# 78 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC7, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC8::
# 87 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC8, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC9::
# 96 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC9, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC10::
# 105 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC10, MSGBOX_NPC
	end


Route44_EventScript_SmithNPC11::
# 114 "data/maps/Route44/scripts.pory"
	msgbox Route44_Text_SmithNPC11, MSGBOX_NPC
	end


Route44_Text_Sign1::
# 10 "data/maps/Route44/scripts.pory"
	.string "Route44 Sign 1$"

Route44_Text_Sign2::
# 19 "data/maps/Route44/scripts.pory"
	.string "Route44 Sign 2$"

Route44_Text_SmithNPC1::
# 28 "data/maps/Route44/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route44_Text_SmithNPC2::
# 37 "data/maps/Route44/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route44_Text_SmithNPC3::
# 46 "data/maps/Route44/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

Route44_Text_SmithNPC4::
# 55 "data/maps/Route44/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

Route44_Text_SmithNPC5::
# 64 "data/maps/Route44/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

Route44_Text_SmithNPC6::
# 73 "data/maps/Route44/scripts.pory"
	.string "It's the question that drives us, Neo.$"

Route44_Text_SmithNPC7::
# 82 "data/maps/Route44/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

Route44_Text_SmithNPC8::
# 91 "data/maps/Route44/scripts.pory"
	.string "I know kung fu.$"

Route44_Text_SmithNPC9::
# 100 "data/maps/Route44/scripts.pory"
	.string "Dodge this.$"

Route44_Text_SmithNPC10::
# 109 "data/maps/Route44/scripts.pory"
	.string "Choice is an illusion created between\n"
	.string "those with power and those without.$"

Route44_Text_SmithNPC11::
# 118 "data/maps/Route44/scripts.pory"
	.string "Hope is an illusion, Mr. Anderson.$"
