RustboroCity_Gym_MapScripts::
	.byte 0


RustboroCity_Gym_Text_GymGuideAdvice::
# 5 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Yo, how's it going?\p"
	.string "Listen, my friend! Would you like to\n"
	.string "become the CHAMPION?\p"
	.string "I'm no TRAINER, not me, but I can sure\n"
	.string "give you winning advice.\p"
	.string "That's settled, then! We'll aim for the\n"
	.string "POKMON CHAMPIONSHIP together!\p"
	.string "It's your job as a TRAINER to collect\n"
	.string "GYM BADGES, am I right?\p"
	.string "But GYM LEADERS aren't pushovers!\p"
	.string "And that's where I come in! I'm here to\n"
	.string "provide expert advice!\p"
	.string "ROXANNE, the GYM LEADER, is a user of\n"
	.string "ROCK-type POKMON.\p"
	.string "The ROCK type is very durable, but it\n"
	.string "can't stand WATER-type and\l"
	.string "GRASS-type moves.\p"
	.string "Come see me afterwards, if you beat the\n"
	.string "GYM LEADER.\p"
	.string "Well, go for it!$"

RustboroCity_Gym_Text_GymGuidePostVictory::
# 9 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Whoa! What a breathtaking victory! My\n"
	.string "cheering must've worked!\p"
	.string "Great! Check your TRAINER CARD.\p"
	.string "The STONE BADGE you got should be\n"
	.string "properly recorded on it.\p"
	.string "In other words\p"
	.string "You've climbed the first step on the\n"
	.string "stairs to the CHAMPIONSHIP!\p"
	.string "That's got to feel awesome!$"

RustboroCity_Gym_Text_JoshIntro::
# 13 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Don't take us GYM TRAINERS lightly! I'll\n"
	.string "show you why we're better!$"

RustboroCity_Gym_Text_JoshDefeat::
# 17 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "You were too good for me$"

RustboroCity_Gym_Text_JoshPostBattle::
# 21 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "You haven't seen anything of the ROCK\n"
	.string "type's terrifying power!$"

RustboroCity_Gym_Text_TommyIntro::
# 25 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "If you can't beat me, you won't stand a\n"
	.string "chance against ROXANNE!$"

RustboroCity_Gym_Text_TommyDefeat::
# 29 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Wow! You've got some potential!$"

RustboroCity_Gym_Text_TommyPostBattle::
# 33 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "ROXANNE is stronger than me by several\n"
	.string "times.\p"
	.string "You'd better be on your guard!$"

RustboroCity_Gym_Text_MarcIntro::
# 37 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "We might be in the middle of town, but so\n"
	.string "what?\p"
	.string "My ROCK POKMON need room to rampage!$"

RustboroCity_Gym_Text_MarcDefeat::
# 41 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Oh, man oh man! Our challenger is one\n"
	.string "feisty customer!$"

RustboroCity_Gym_Text_MarcPostBattle::
# 45 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "I have to hand it to our LEADER.\p"
	.string "It took smarts and sense for her to\n"
	.string "pick the ROCK type at her young age.$"

RustboroCity_Gym_Text_RoxanneIntro::
# 49 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Hello, I am ROXANNE, the RUSTBORO\n"
	.string "POKMON GYM LEADER.\p"
	.string "I became a GYM LEADER so that I might\n"
	.string "apply what I learned at the POKMON\l"
	.string "TRAINER'S SCHOOL in battle.\p"
	.string "Would you kindly demonstrate how you\n"
	.string "battle, and with which POKMON?$"

RustboroCity_Gym_Text_RoxanneDefeat::
# 53 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "So I lost\p"
	.string "It seems that I still have much more to\n"
	.string "learn\p"
	.string "I understand.\p"
	.string "The POKMON LEAGUE's rules state that\n"
	.string "TRAINERS are to be given this\l"
	.string "if they defeat a GYM LEADER.\p"
	.string "Please accept the official POKMON\n"
	.string "LEAGUE STONE BADGE.$"

RustboroCity_Gym_Text_ReceivedStoneBadge::
# 57 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "{PLAYER} received the STONE BADGE\n"
	.string "from ROXANNE.$"

RustboroCity_Gym_Text_StoneBadgeInfoTakeThis::
# 61 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "The STONE BADGE heightens the ATTACK\n"
	.string "power of your POKMON.\p"
	.string "It also enables them to use the HM move\n"
	.string "CUT outside of battle.\p"
	.string "Please take this with you, too.$"

RustboroCity_Gym_Text_ExplainRockTomb::
# 65 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "That TECHNICAL MACHINE, TM39, contains\n"
	.string "ROCK TOMB.\p"
	.string "It not only inflicts damage by dropping\n"
	.string "rocks, it also lowers SPEED.\p"
	.string "If you use a TM, it instantly teaches\n"
	.string "the move to a POKMON.\p"
	.string "Remember, a TM can be used only once, so\n"
	.string "think before you use it.$"

RustboroCity_Gym_Text_RoxannePostBattle::
# 69 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Since you are so strong, you should\n"
	.string "challenge other GYM LEADERS.\p"
	.string "By battling many TRAINERS, you should\n"
	.string "learn many things.$"

RustboroCity_Gym_Text_GymStatue::
# 73 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "RUSTBORO CITY POKMON GYM$"

RustboroCity_Gym_Text_GymStatueCertified::
# 77 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "RUSTBORO CITY POKMON GYM\p"
	.string "ROXANNE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

RustboroCity_Gym_Text_RoxanneRegisterCall::
# 81 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Beep!\p"
	.string "ROXANNE: Oh, hello, {PLAYER}? This is\n"
	.string "ROXANNE of RUSTBORO CITY.\p"
	.string "I heard from BRAWLY that you're moving\n"
	.string "up through the ranks of\l"
	.string "TRAINERS at an incredible clip.\p"
	.string "Well, I'd rather not think that I can't\n"
	.string "beat you.\p"
	.string "I promise, I will shape up my GYM so that\n"
	.string "you may challenge us again.\p"
	.string "I hope you'll be looking forward to that\n"
	.string "occasion as much as me!\p"
	.string "Click!$"

RustboroCity_Gym_Text_RegisteredRoxanne::
# 85 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Registered GYM LEADER ROXANNE in the\n"
	.string "POKNAV.$"

RustboroCity_Gym_Text_RoxannePreRematch::
# 89 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "ROXANNE: I'm so glad to see you again.\n"
	.string "I'm ROXANNE, the GYM LEADER here.\p"
	.string "I'm sure we've both experienced many\n"
	.string "battles since we last met.\p"
	.string "I would like to see how much better\n"
	.string "we've become. Let us battle!$"

RustboroCity_Gym_Text_RoxanneRematchDefeat::
# 93 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Grr Again, I have lost$"

RustboroCity_Gym_Text_RoxannePostRematch::
# 97 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "ROXANNE: I still have much to learn\n"
	.string "when it comes to battling POKMON.\p"
	.string "That awareness makes me love battling\n"
	.string "all that much more!$"

RustboroCity_Gym_Text_RoxanneRematchNeedTwoMons::
# 101 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "ROXANNE: I'm so glad to see you again.\n"
	.string "I'm ROXANNE, the GYM LEADER here.\p"
	.string "I'm sure we've both experienced many\n"
	.string "battles since we last met.\p"
	.string "I would like to see how much better\n"
	.string "we've become\p"
	.string "Oh, no You only have one POKMON with\n"
	.string "you?\p"
	.string "Please return with at least one more\n"
	.string "POKMON.$"
