RustboroCity_Gym_MapScripts::
	.byte 0


RustboroCity_Gym_EventScript_GymGuide::
	end


RustboroCity_Gym_EventScript_Josh::
# 9 "data/maps/RustboroCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_JOSH, RustboroCity_Gym_Text_JoshIntro, RustboroCity_Gym_Text_JoshDefeat, Text_NotEnoughMonsForDoubleBattle
# 10 "data/maps/RustboroCity_Gym/scripts.pory"
	msgbox RustboroCity_Gym_Text_JoshPostBattle
	return


RustboroCity_Gym_EventScript_LeftGymStatue::
	end


RustboroCity_Gym_EventScript_Marc::
# 21 "data/maps/RustboroCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_MARC, RustboroCity_Gym_Text_MarcIntro, RustboroCity_Gym_Text_MarcDefeat, Text_NotEnoughMonsForDoubleBattle
# 22 "data/maps/RustboroCity_Gym/scripts.pory"
	msgbox RustboroCity_Gym_Text_MarcPostBattle
	return


RustboroCity_Gym_EventScript_RightGymStatue::
	end


RustboroCity_Gym_EventScript_Roxanne::
	end


RustboroCity_Gym_EventScript_Tommy::
# 37 "data/maps/RustboroCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_TOMMY, RustboroCity_Gym_Text_TommyIntro, RustboroCity_Gym_Text_TommyDefeat, Text_NotEnoughMonsForDoubleBattle
# 38 "data/maps/RustboroCity_Gym/scripts.pory"
	msgbox RustboroCity_Gym_Text_TommyPostBattle
	return


RustboroCity_Gym_Text_JoshDefeat::
# 43 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_JoshDefeat$"

RustboroCity_Gym_Text_JoshIntro::
# 47 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_JoshIntro$"

RustboroCity_Gym_Text_JoshPostBattle::
# 51 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_JoshPostBattle$"

RustboroCity_Gym_Text_MarcDefeat::
# 55 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_MarcDefeat$"

RustboroCity_Gym_Text_MarcIntro::
# 59 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_MarcIntro$"

RustboroCity_Gym_Text_MarcPostBattle::
# 63 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_MarcPostBattle$"

RustboroCity_Gym_Text_TommyDefeat::
# 67 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_TommyDefeat$"

RustboroCity_Gym_Text_TommyIntro::
# 71 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_TommyIntro$"

RustboroCity_Gym_Text_TommyPostBattle::
# 75 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "RustboroCity_Gym_Text_TommyPostBattle$"

RustboroCity_Gym_Text_RoxannePostRematch::
# 79 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "ROXANNE: I still have much to learn\n"
	.string "when it comes to battling POKéMON.\p"
	.string "That awareness makes me love battling\n"
	.string "all that much more!$"

RustboroCity_Gym_Text_GymGuidePostVictory::
# 83 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Whoa! What a breathtaking victory!\n"
	.string "My cheering must've worked!\p"
	.string "Great!\n"
	.string "Check your TRAINER CARD.\p"
	.string "The STONE BADGE you got should be\n"
	.string "properly recorded on it.\p"
	.string "In other words…\p"
	.string "You've climbed the first step on\n"
	.string "the stairs to the CHAMPIONSHIP!\p"
	.string "That's got to feel awesome!$"

RustboroCity_Gym_Text_GymStatueCertified::
# 87 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "RUSTBORO CITY POKéMON GYM\p"
	.string "ROXANNE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

RustboroCity_Gym_Text_RegisteredRoxanne::
# 91 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "Registered GYM LEADER ROXANNE\n"
	.string "in the POKéNAV.$"

RustboroCity_Gym_Text_GymStatue::
# 95 "data/maps/RustboroCity_Gym/scripts.pory"
	.string "RUSTBORO CITY POKéMON GYM$"
