LilycoveCity_ContestHall_MapScripts::
	.byte 0


LilycoveCity_ContestHall_Text_TodayWonSmartnessContest::
# 5 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This POKéMON won the BEAUTY CONTEST\n"
	.string "here before.\p"
	.string "Well, guess what? Today, I made it win a\n"
	.string "SMARTNESS CONTEST!\p"
	.string "My abilities scare even me…$"

LilycoveCity_ContestHall_Text_EnteredBunchOfContests::
# 9 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I've entered a bunch of CONTESTS, so\n"
	.string "I'm seeing how things work.\p"
	.string "If you're in a COOLNESS CONTEST, cool\n"
	.string "moves go over as appeals.\p"
	.string "But smart moves and cute moves don't\n"
	.string "go over well, for instance.$"

LilycoveCity_ContestHall_Text_ManWhoWonEarlierHadPokeblocks::
# 13 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "That young man who won earlier had a\n"
	.string "whole bunch of different {POKEBLOCK}S.\p"
	.string "Can you win if you had that many of\n"
	.string "those things?$"

LilycoveCity_ContestHall_Text_IsntThisPlaceHumongous::
# 17 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Whoa, isn't this place humongous!\p"
	.string "The tension in the air… It's not like a\n"
	.string "CONTEST hall in the sticks.$"

LilycoveCity_ContestHall_Text_GiveItBestSmartAppeal::
# 21 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Okay, SMART POKéMON and their\n"
	.string "TRAINERS, are you ready?!\p"
	.string "Give it your best showing! Let's appeal!$"

LilycoveCity_ContestHall_Text_AreYouEnjoyingThisContest::
# 25 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Are you enjoying this CONTEST?\p"
	.string "Come back with three friends, and all of\n"
	.string "you may enter a CONTEST!$"

LilycoveCity_ContestHall_Text_EnteredWrongContest::
# 29 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Ayayayay… I entered the wrong CONTEST.\p"
	.string "I entered this tough POKéMON in the\n"
	.string "SMARTNESS CONTEST…\p"
	.string "Come on, wow them with a smart-looking\n"
	.string "ROCK SMASH.$"

LilycoveCity_ContestHall_Text_RaisedMonToBeSmart::
# 33 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I've spent many a year, and all my\n"
	.string "wisdom besides, raising this POKéMON\l"
	.string "to be smart.\p"
	.string "It won't be easily bested by some young\n"
	.string "pup's POKéMON.\p"
	.string "My dear wife, are you seeing this?$"

LilycoveCity_ContestHall_Text_IfMonPullsSmartMoveNext::
# 37 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "There it is!\p"
	.string "If my POKéMON pulls a smart move next,\n"
	.string "the audience's excitement will peak!$"

LilycoveCity_ContestHall_Text_DontAppreciateCuteLeechLife::
# 41 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Oh, dear, no!\p"
	.string "My darling ZUBAT's LEECH LIFE is so\n"
	.string "cute I kept using it over and over!\p"
	.string "But these mean people don't appreciate\n"
	.string "it at all!$"

LilycoveCity_ContestHall_Text_YoureBeautifulGrandpa::
# 45 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Kiyaaah! You're beautiful, Grandpa!$"

LilycoveCity_ContestHall_Text_AllSeemToUseDifferentMoves::
# 49 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Even when TRAINERS enter the same kind\n"
	.string "of POKéMON, they all seem to use\l"
	.string "different moves for appeals.\p"
	.string "It's just like the way people have\n"
	.string "different styles for battling.$"

LilycoveCity_ContestHall_Text_PokemonSmarterThanTrainers::
# 53 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I think the POKéMON look smarter than\n"
	.string "their TRAINERS. By a lot.$"

LilycoveCity_ContestHall_Text_StillLoveSmartnessContests::
# 57 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "When all's said and done, I still love\n"
	.string "SMARTNESS CONTESTS.\p"
	.string "That intellectual green color… It's so…\n"
	.string "So… Cool.$"

LilycoveCity_ContestHall_Text_AreYouEnteringBeautyContest::
# 61 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Are you entering the BEAUTY\n"
	.string "CONTEST, too? Good luck!$"

LilycoveCity_ContestHall_Text_EveryPokemonPristineBeauty::
# 65 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Ah, every POKéMON here is a\n"
	.string "model of pristine beauty!\p"
	.string "Why, I almost forgot to score them!$"

LilycoveCity_ContestHall_Text_EyesWillBeGluedToMyBeauty::
# 69 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "A POKéMON this beautiful… There isn't\n"
	.string "another one like it.\p"
	.string "Everyone's eyes will be glued to my\n"
	.string "beauty.$"

LilycoveCity_ContestHall_Text_OverdidGrooming::
# 73 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Waaaah!\p"
	.string "I brushed and groomed my POKéMON\n"
	.string "carefully for this CONTEST…\p"
	.string "But I overdid it… My POKéMON's coat\n"
	.string "turned all scraggly…\p"
	.string "What should I do?$"

LilycoveCity_ContestHall_Text_JudgeWontSeeAuroraBeam::
# 77 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This AURORA BEAM is so dazzling, the\n"
	.string "JUDGE won't be able to see it.\p"
	.string "Uh, wait a second… That'll be\n"
	.string "meaningless, then!$"

LilycoveCity_ContestHall_Text_PokemonLooksLikeYoungerMe::
# 81 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "This pretty POKéMON looks just like me\n"
	.string "when I was younger.\p"
	.string "Right when I said that, my husband\n"
	.string "spewed the coffee he was drinking.\p"
	.string "Did I say something funny?$"

LilycoveCity_ContestHall_Text_WinBeautyContestMakesMeHappy::
# 85 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "You know, if I win at a BEAUTY CONTEST,\n"
	.string "sure it makes me\l"
	.string "happy. More than usual, anyway.$"

LilycoveCity_ContestHall_Text_GanderAtAllThosePrettyPokemon::
# 89 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Wahahahah!\p"
	.string "Will you take a gander at all those\n"
	.string "pretty POKéMON!\l"
	.string "I just love this sort of glitz!$"

LilycoveCity_ContestHall_Text_CantWinOnBeautyAlone::
# 93 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "You can't always win on just beauty\n"
	.string "alone.\p"
	.string "You have to groom your POKéMON so it's\n"
	.string "nice and glossy like mine.$"

LilycoveCity_ContestHall_Text_InTheMiddleOfContest::
# 97 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "MC: Uh-oh! Hello! We're in the middle of\n"
	.string "a CONTEST!\p"
	.string "Please enter at our registration\n"
	.string "counter and come out, okay?$"

LilycoveCity_ContestHall_Text_SuchCharmingCuteAppeals::
# 101 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "JUDGE: Oh, such charming and cute\n"
	.string "appeals!\p"
	.string "Oh, my goodness! What a perfectly\n"
	.string "adorable WATER SPORT appeal!$"

LilycoveCity_ContestHall_Text_MyAzurillWasDistracted::
# 105 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Oh, no… My sweet AZURILL was\n"
	.string "distracted by another POKéMON.$"

LilycoveCity_ContestHall_Text_NeverWonBattleButContest::
# 109 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My POKéMON has never won in a battle,\n"
	.string "but put it in a CONTEST and look out!$"

LilycoveCity_ContestHall_Text_PetalDanceIsMarvel::
# 113 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My POKéMON's PETAL DANCE is a marvel of\n"
	.string "elegance.\p"
	.string "I won't let anyone disturb its\n"
	.string "performance.$"

LilycoveCity_ContestHall_Text_MyMonAppealSoMuchCuter::
# 117 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Everyone's POKéMON are very cute.\p"
	.string "However, if my POKéMON were to make a\n"
	.string "cute appeal…\p"
	.string "I'm sure that it would be so much cuter\n"
	.string "than the others.$"

LilycoveCity_ContestHall_Text_MyChildIsInContest::
# 121 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "My child is in this CONTEST.$"

LilycoveCity_ContestHall_Text_ComeOnDear::
# 125 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Come on, dear. Go for it! Your POKéMON is\n"
	.string "the best!$"

LilycoveCity_ContestHall_Text_ThatGirlThereIsCutest::
# 129 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "I think that girl over there is the\n"
	.string "cutest of the lot.\p"
	.string "What's that? They're judging POKéMON\n"
	.string "by their looks?$"

LilycoveCity_ContestHall_Text_WantCuteMonOfMyOwn::
# 133 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "Ohh, seeing all these cute POKéMON,\n"
	.string "they make we want to get my own!\p"
	.string "I'm going to go catch some!$"

LilycoveCity_ContestHall_Text_BeautyContestStage::
# 137 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "BEAUTY CONTEST STAGE BE ALLURED BY\n"
	.string "BEAUTIFUL POKéMON!$"

LilycoveCity_ContestHall_Text_CuteContestStage::
# 141 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "CUTENESS CONTEST STAGE BE CHARMED BY\n"
	.string "CUTE POKéMON!$"

LilycoveCity_ContestHall_Text_SmartContestStage::
# 145 "data/maps/LilycoveCity_ContestHall/scripts.pory"
	.string "SMARTNESS CONTEST STAGE BE IMPRESSED\n"
	.string "BY SMART POKéMON!$"
