MagmaHideout_4F_MapScripts::
	.byte 0


MagmaHideout_4F_Text_Grunt11Intro::
# 5 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "I want to see GROUDON, too, but they\n"
	.string "won't let me see even its tail…\p"
	.string "It's got me feeling really frustrated.\p"
	.string "Oh, no! I blabbed about GROUDON!$"

MagmaHideout_4F_Text_Grunt11Defeat::
# 9 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "I guess it's impossible to win if one\n"
	.string "doesn't have a calm mind…$"

MagmaHideout_4F_Text_Grunt11PostBattle::
# 13 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "I wonder if GROUDON even has a tail?$"

MagmaHideout_4F_Text_Grunt12Intro::
# 17 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "Fuhahaha! Soon! Very soon!\l"
	.string "Our grand objective will be achieved!$"

MagmaHideout_4F_Text_Grunt12Defeat::
# 21 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "Grrr… I've come so far, but now this?$"

MagmaHideout_4F_Text_Grunt12PostBattle::
# 25 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "MAXIE, sir! An intruder is headed your\n"
	.string "way!$"

MagmaHideout_4F_Text_Grunt13Intro::
# 29 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "You're not finished yet! You're not\n"
	.string "getting by me easily!$"

MagmaHideout_4F_Text_Grunt13Defeat::
# 33 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "Was I that easy to knock down?$"

MagmaHideout_4F_Text_Grunt13PostBattle::
# 37 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "C-come on, one more match…$"

MagmaHideout_4F_Text_TabithaIntro::
# 41 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "Hehehe! You made it this far, so I'll tell\n"
	.string "you!\p"
	.string "That's right! Up ahead, GROUDON is\n"
	.string "sleeping!\p"
	.string "MAXIE went to GROUDON just seconds\n"
	.string "ago!\p"
	.string "It's going to awaken real soon! Hehe!\n"
	.string "Hehehe!$"

MagmaHideout_4F_Text_TabithaDefeat::
# 45 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "Taken down again… Hehe…$"

MagmaHideout_4F_Text_TabithaPostBattle::
# 49 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "…And while you wasted time with me,\n"
	.string "MAXIE should have awakened GROUDON…$"

MagmaHideout_4F_Text_MaxieAwakenGroudon::
# 53 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "MAXIE: GROUDON…\p"
	.string "Nothing could awaken you from your\n"
	.string "sleep bathed in magma…\p"
	.string "This BLUE ORB is what you sought.\n"
	.string "Wasn't it?\p"
	.string "I have brought you the BLUE ORB. Let\n"
	.string "its shine awaken you!\p"
	.string "And show me… Show me the full extent of\n"
	.string "your power!$"

MagmaHideout_4F_Text_MaxieGroudonWhatsWrong::
# 57 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "MAXIE: GROUDON! What's wrong?\p"
	.string "Wasn't the BLUE ORB the key?\p"
	.string "GROUDON! Where have you gone…$"

MagmaHideout_4F_Text_MaxieOhItWasYou::
# 61 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "MAXIE: Oh, so it was you?\p"
	.string "I've seen you poking around uninvited\n"
	.string "here and there…\p"
	.string "I get it now! You must have pulled a\n"
	.string "cheap stunt!$"

MagmaHideout_4F_Text_MaxieDefeat::
# 65 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "What makes you so adept at handling\n"
	.string "POKéMON?$"

MagmaHideout_4F_Text_MaxieImGoingAfterGroudon::
# 69 "data/maps/MagmaHideout_4F/scripts.pory"
	.string "MAXIE: There has to be some reason why\n"
	.string "GROUDON fled…\p"
	.string "That's what you're trying to say, aren't\n"
	.string "you?\p"
	.string "… … … … … … … … … … … …\p"
	.string "Humph… You think I didn't know that?\p"
	.string "With GROUDON gone, there is no longer\n"
	.string "any need for this blasted volcano.\p"
	.string "I am going after GROUDON, so this is\n"
	.string "where we part!$"
