SSAnne_1F_Room6_MapScripts::
	.byte 0


SSAnne_1F_Room6_Text_TakeAShortRest::
# 5 "data/maps/SSAnne_1F_Room6/scripts.pory"
	.string "You look tired. Would you like to take a\n"
	.string "short rest?$"

SSAnne_1F_Room6_Text_GladEveryoneIsRefreshed::
# 9 "data/maps/SSAnne_1F_Room6/scripts.pory"
	.string "I'm glad to see that everyone is looking\n"
	.string "refreshed and chipper.$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMyBrother::
# 13 "data/maps/SSAnne_1F_Room6/scripts.pory"
	.string "Oh, I'm sorry for fussing over you. You\n"
	.string "look like my little brother$"

SSAnne_1F_Room6_Text_SorryYouLookLikeMySister::
# 17 "data/maps/SSAnne_1F_Room6/scripts.pory"
	.string "Oh, I'm sorry for fussing over you. You\n"
	.string "look like my little sister$"
