MagmaHideout_2F_1R_MapScripts::
	.byte 0


MagmaHideout_2F_1R_EventScript_Grunt14::
# 5 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_14, MagmaHideout_2F_1R_Text_Grunt14Intro, MagmaHideout_2F_1R_Text_Grunt14Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt14PostBattle
	return


MagmaHideout_2F_1R_EventScript_Grunt3::
# 10 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_3, MagmaHideout_2F_1R_Text_Grunt3Intro, MagmaHideout_2F_1R_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt3PostBattle
	return


MagmaHideout_2F_1R_EventScript_Grunt4::
# 15 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_4, MagmaHideout_2F_1R_Text_Grunt4Intro, MagmaHideout_2F_1R_Text_Grunt4Defeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt4PostBattle
	return


MagmaHideout_2F_1R_EventScript_Grunt5::
# 20 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_5, MagmaHideout_2F_1R_Text_Grunt5Intro, MagmaHideout_2F_1R_Text_Grunt5Defeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	msgbox MagmaHideout_2F_1R_Text_Grunt5PostBattle
	return


MagmaHideout_2F_1R_Text_Grunt14Defeat::
# 26 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt14Defeat$"

MagmaHideout_2F_1R_Text_Grunt14Intro::
# 30 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt14Intro$"

MagmaHideout_2F_1R_Text_Grunt14PostBattle::
# 34 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt14PostBattle$"

MagmaHideout_2F_1R_Text_Grunt3Defeat::
# 38 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt3Defeat$"

MagmaHideout_2F_1R_Text_Grunt3Intro::
# 42 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt3Intro$"

MagmaHideout_2F_1R_Text_Grunt3PostBattle::
# 46 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt3PostBattle$"

MagmaHideout_2F_1R_Text_Grunt4Defeat::
# 50 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt4Defeat$"

MagmaHideout_2F_1R_Text_Grunt4Intro::
# 54 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt4Intro$"

MagmaHideout_2F_1R_Text_Grunt4PostBattle::
# 58 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt4PostBattle$"

MagmaHideout_2F_1R_Text_Grunt5Defeat::
# 62 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt5Defeat$"

MagmaHideout_2F_1R_Text_Grunt5Intro::
# 66 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt5Intro$"

MagmaHideout_2F_1R_Text_Grunt5PostBattle::
# 70 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_1R_Text_Grunt5PostBattle$"
