MagmaHideout_2F_1R_MapScripts::
	.byte 0


MagmaHideout_2F_1R_Text_Grunt14Intro::
# 5 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "What, what, what?\p"
	.string "Only TEAM MAGMA members are supposed\n"
	.string "to be in here!\p"
	.string "But you're not dressed in TEAM MAGMA's\n"
	.string "uniform…\p"
	.string "You rouse my suspicion! Battle with me!$"

MagmaHideout_2F_1R_Text_Grunt14Defeat::
# 9 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Aiyiyi… My pride as a TEAM MAGMA\n"
	.string "member…$"

MagmaHideout_2F_1R_Text_Grunt14PostBattle::
# 13 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "If you suffer from chills, you should\n"
	.string "join TEAM MAGMA.$"

MagmaHideout_2F_1R_Text_Grunt3Intro::
# 17 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Hold it right there!\p"
	.string "You don't really expect me to keep my\n"
	.string "trap shut and let you waltz by me?$"

MagmaHideout_2F_1R_Text_Grunt3Defeat::
# 21 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Ooh wow! I concede!$"

MagmaHideout_2F_1R_Text_Grunt3PostBattle::
# 25 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Maybe it would've been better if I did\n"
	.string "just let you go unchallenged…$"

MagmaHideout_2F_1R_Text_Grunt4Intro::
# 29 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Ahah! An intruder!$"

MagmaHideout_2F_1R_Text_Grunt4Defeat::
# 33 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Graaah!$"

MagmaHideout_2F_1R_Text_Grunt4PostBattle::
# 37 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "I've already lost.\p"
	.string "Do I really need to keep running around\n"
	.string "in a circle?$"

MagmaHideout_2F_1R_Text_Grunt5Intro::
# 41 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Oh, oh! An intruder!$"

MagmaHideout_2F_1R_Text_Grunt5Defeat::
# 45 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Mutter…$"

MagmaHideout_2F_1R_Text_Grunt5PostBattle::
# 49 "data/maps/MagmaHideout_2F_1R/scripts.pory"
	.string "Actually, I'm no expert at battling…$"
