CinnabarIsland_PokemonLab_ResearchRoom_MapScripts::
	.byte 0


CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
# 5 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "EEVEE can evolve into one of three\n"
	.string "kinds of POKéMON.$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
# 9 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "There's an e-mail message.\p"
	.string "… … …\p"
	.string "There are three legendary bird POKéMON.\p"
	.string "They are ARTICUNO, ZAPDOS, and\n"
	.string "MOLTRES.\p"
	.string "Their whereabouts are unknown.\p"
	.string "We plan to explore the cavern close to\n"
	.string "CERULEAN.\p"
	.string "From: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
# 13 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "An amber pipe!$"
