CinnabarIsland_PokemonLab_ResearchRoom_MapScripts::
	.byte 0


CinnabarIsland_PokemonLab_ResearchRoom_EventScript_AmberPipe::
# 5 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Computer::
# 10 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail, MSGBOX_SIGN
	end


CinnabarIsland_PokemonLab_ResearchRoom_EventScript_MetronomeTutor::
	end


CinnabarIsland_PokemonLab_ResearchRoom_EventScript_Scientist::
# 19 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	msgbox CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons, MSGBOX_NPC
	end


CinnabarIsland_PokemonLab_ResearchRoom_Text_AnAmberPipe::
# 24 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "An amber pipe!$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_LegendaryBirdEmail::
# 28 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "There's an e-mail message.\p"
	.string "… … …\p"
	.string "There are three legendary bird POKéMON.\p"
	.string "They are ARTICUNO, ZAPDOS, and\n"
	.string "MOLTRES.\p"
	.string "Their whereabouts are unknown.\p"
	.string "We plan to explore the cavern close to\n"
	.string "CERULEAN.\p"
	.string "From: POKéMON RESEARCH TEAM…$"

CinnabarIsland_PokemonLab_ResearchRoom_Text_EeveeCanEvolveIntroThreeMons::
# 32 "data/maps/CinnabarIsland_PokemonLab_ResearchRoom/scripts.pory"
	.string "EEVEE can evolve into one of three\n"
	.string "kinds of POKéMON.$"
