Route4_PokemonCenter_1F_MapScripts::
# 2 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route4_PokemonCenter_1F_OnTransition
# 3 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


Route4_PokemonCenter_1F_Text_CanHaveSixMonsWithYou::
# 7 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "Okay, set six POKé BALLS in my belt…\p"
	.string "Yeah, that'll do it. At most, you can\n"
	.string "have six POKéMON with you.$"

Route4_PokemonCenter_1F_Text_TeamRocketAttacksCerulean::
# 11 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "TEAM ROCKET attacks CERULEAN\n"
	.string "citizens…\p"
	.string "Not a day goes by without TEAM ROCKET\n"
	.string "being in the news.$"

Route4_PokemonCenter_1F_Text_LaddieBuyMagikarpForJust500::
# 15 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "MAN: Hello there, laddie! Have I got a\n"
	.string "deal just for you!\p"
	.string "I'll let you have a secret POKéMON - a\n"
	.string "MAGIKARP - for just ¥500!\p"
	.string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_SweetieBuyMagikarpForJust500::
# 19 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "MAN: Hello there, sweetie pie! Have I\n"
	.string "got a deal just for you!\p"
	.string "I'll let you have a secret POKéMON - a\n"
	.string "MAGIKARP - for just ¥500!\p"
	.string "So, you'll buy it, am I right?$"

Route4_PokemonCenter_1F_Text_PaidOutrageouslyForMagikarp::
# 23 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} paid an outrageous ¥500 and\n"
	.string "bought the MAGIKARP…$"

Route4_PokemonCenter_1F_Text_OnlyDoingThisAsFavorToYou::
# 27 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "No? You say no? I'm only doing this as a\n"
	.string "favor to you!$"

Route4_PokemonCenter_1F_Text_NoRoomForMorePokemon::
# 31 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "There's no more room for any more\n"
	.string "POKéMON, it looks like.$"

Route4_PokemonCenter_1F_Text_YoullNeedMoreMoney::
# 35 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "You'll need more money than that!$"

Route4_PokemonCenter_1F_Text_IDontGiveRefunds::
# 39 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "MAN: Well, I don't give refunds. You knew\n"
	.string "what you were getting!$"

Route4_PokemonCenter_1F_Text_ShouldStoreMonsUsingPC::
# 43 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "Sometimes, you'll have too many POKéMON\n"
	.string "with you to add any more.\p"
	.string "In that case, you should just store\n"
	.string "some using any PC.$"

Route4_PokemonCenter_1F_Text_ItsANewspaper::
# 47 "data/maps/Route4_PokemonCenter_1F/scripts.pory"
	.string "It's a newspaper.$"
