PacifidlogTown_House5_MapScripts::
	.byte 0


PacifidlogTown_House5_MapScripts::
	return


PacifidlogTown_House5_Text_CantSeeMirageIslandToday::
# 8 "data/maps/PacifidlogTown_House5/scripts.pory"
	.string "I can't see MIRAGE ISLAND today…$"

PacifidlogTown_House5_Text_CanSeeMirageIslandToday::
# 12 "data/maps/PacifidlogTown_House5/scripts.pory"
	.string "Oh! Oh my! I can see MIRAGE ISLAND\n"
	.string "today!$"

PacifidlogTown_House5_Text_MirageIslandAppearDependingOnWeather::
# 16 "data/maps/PacifidlogTown_House5/scripts.pory"
	.string "MIRAGE ISLAND…\p"
	.string "It must become visible and invisible\n"
	.string "depending on the weather conditions\l"
	.string "that make mirages appear.\p"
	.string "Or is it really appearing and\n"
	.string "disappearing?$"
