PacifidlogTown_House5_MapScripts::
	.byte 0


PacifidlogTown_House5_EventScript_Gentleman::
# 5 "data/maps/PacifidlogTown_House5/scripts.pory"
	msgbox PacifidlogTown_House5_Text_MirageIslandAppearDependingOnWeather, MSGBOX_NPC
	end


PacifidlogTown_House5_EventScript_MirageIslandWatcher::
	end


PacifidlogTown_House5_Text_CanSeeMirageIslandToday::
# 13 "data/maps/PacifidlogTown_House5/scripts.pory"
	.string "Oh! Oh my!\n"
	.string "I can see MIRAGE ISLAND today!$"

PacifidlogTown_House5_Text_MirageIslandAppearDependingOnWeather::
# 17 "data/maps/PacifidlogTown_House5/scripts.pory"
	.string "MIRAGE ISLAND…\p"
	.string "It must become visible and invisible\n"
	.string "depending on the weather conditions\l"
	.string "that make mirages appear.\p"
	.string "Or is it really appearing and\n"
	.string "disappearing?$"
