LilycoveCity_DepartmentStoreRooftop_MapScripts::
	.byte 0


LilycoveCity_DepartmentStoreRooftop_EventScript_Man::
	end


LilycoveCity_DepartmentStoreRooftop_EventScript_SaleWoman::
	end


LilycoveCity_DepartmentStoreRooftop_EventScript_ThirstyMan::
# 13 "data/maps/LilycoveCity_DepartmentStoreRooftop/scripts.pory"
	msgbox LilycoveCity_DepartmentStoreRooftop_Text_BoneDryThirsty, MSGBOX_NPC
	end


LilycoveCity_DepartmentStoreRooftop_EventScript_VendingMachine::
	end


LilycoveCity_DepartmentStoreRooftop_Text_BoneDryThirsty::
# 26 "data/maps/LilycoveCity_DepartmentStoreRooftop/scripts.pory"
	.string "Ohh… I'm bone-dry thirsty!$"

LilycoveCity_DepartmentStoreRooftop_Text_NotEnoughMoney::
# 30 "data/maps/LilycoveCity_DepartmentStoreRooftop/scripts.pory"
	.string "Not enough money…$"

LilycoveCity_DepartmentStoreRooftop_Text_DecidedAgainstBuyingDrink::
# 34 "data/maps/LilycoveCity_DepartmentStoreRooftop/scripts.pory"
	.string "Decided against buying a drink.$"

LilycoveCity_DepartmentStoreRooftop_Text_BeenWaitingForClearOutSale::
# 38 "data/maps/LilycoveCity_DepartmentStoreRooftop/scripts.pory"
	.string "Yes! I've been waiting a long time for\n"
	.string "this clear-out sale.\p"
	.string "They have items that you can only get\n"
	.string "here. I'm going to load up, that I am!$"
