PokemonLeague_BrunosRoom_MapScripts::
# 2 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_BrunosRoom_OnResume
# 3 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_BrunosRoom_OnLoad
# 4 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_BrunosRoom_OnWarp
# 5 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_BrunosRoom_OnFrame
	.byte 0


PokemonLeague_BrunosRoom_Text_Intro::
# 9 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	.string "I am BRUNO of the ELITE FOUR!\p"
	.string "Through rigorous training, people and\n"
	.string "POKMON can become stronger\l"
	.string "without limit.\p"
	.string "I've lived and trained with my fighting\n"
	.string "POKMON!\l"
	.string "And that will never change!\p"
	.string "{PLAYER}!\p"
	.string "We will grind you down with our superior\n"
	.string "power!\p"
	.string "Hoo hah!{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_BrunosRoom_Text_RematchIntro::
# 13 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	.string "I am BRUNO of the ELITE FOUR!\p"
	.string "Through rigorous training, people and\n"
	.string "POKMON can become stronger\l"
	.string "without limit.\p"
	.string "I've lived and trained with my fighting\n"
	.string "POKMON!\l"
	.string "And that will never change!\p"
	.string "{PLAYER}!\p"
	.string "We will grind you down with our superior\n"
	.string "power!\p"
	.string "Hoo hah!{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_BrunosRoom_Text_Defeat::
# 17 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	.string "Why? How could I lose?$"

PokemonLeague_BrunosRoom_Text_PostBattle::
# 21 "data/maps/PokemonLeague_BrunosRoom/scripts.pory"
	.string "My job is done. Go face your next\n"
	.string "challenge.$"
