SSAnne_CaptainsOffice_MapScripts::
	.byte 0


SSAnne_CaptainsOffice_Text_CaptainIFeelSeasick::
# 5 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "CAPTAIN: Ooargh… I feel hideous…\l"
	.string "Urrp! Seasick…$"

SSAnne_CaptainsOffice_Text_RubbedCaptainsBack::
# 9 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "{PLAYER} rubbed the CAPTAIN's back!\p"
	.string "Rub-rub… Rub-rub…$"

SSAnne_CaptainsOffice_Text_ThankYouHaveHMForCut::
# 13 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "CAPTAIN: Whew! Thank you! I'm feeling\n"
	.string "much better now.\p"
	.string "You want to see my hidden CUT\n"
	.string "technique?\p"
	.string "I could show you my prized CUT\n"
	.string "technique if I weren't so ill…\p"
	.string "I know! You can have this! This HIDDEN\n"
	.string "MACHINE!\p"
	.string "Teach CUT to your POKéMON, and you can\n"
	.string "see it CUT anytime!$"

SSAnne_CaptainsOffice_Text_ObtainedHM01FromCaptain::
# 17 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "{PLAYER} obtained HM01 from the\n"
	.string "CAPTAIN!$"

SSAnne_CaptainsOffice_Text_ExplainCut::
# 21 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "Using CUT, you can chop down small\n"
	.string "trees.\p"
	.string "Why not try it with the trees around\n"
	.string "VERMILION CITY?$"

SSAnne_CaptainsOffice_Text_SSAnneWillSetSailSoon::
# 25 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "CAPTAIN: …Whew!\p"
	.string "Now that I'm not sick anymore, I guess\n"
	.string "it's time.\p"
	.string "The S.S. ANNE will set sail soon!\p"
	.string "Farewell, until our return to VERMILION\n"
	.string "CITY!$"

SSAnne_CaptainsOffice_Text_YouHaveNoRoomForThis::
# 29 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "Oh, no! You have no room for this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
# 33 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "Yuck! Shouldn't have looked!$"

SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
# 37 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "How to Conquer Seasickness… The\n"
	.string "CAPTAIN's reading this!$"
