SSAnne_CaptainsOffice_MapScripts::
	.byte 0


SSAnne_CaptainsOffice_EventScript_Book::
# 5 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	msgbox SSAnne_CaptainsOffice_Text_HowToConquerSeasickness, MSGBOX_SIGN
	end


SSAnne_CaptainsOffice_EventScript_Captain::
	end


SSAnne_CaptainsOffice_EventScript_TrashCan::
# 14 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	msgbox SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked, MSGBOX_SIGN
	end


SSAnne_CaptainsOffice_Text_HowToConquerSeasickness::
# 19 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "How to Conquer Seasickness… The\n"
	.string "CAPTAIN's reading this!$"

SSAnne_CaptainsOffice_Text_YuckShouldntHaveLooked::
# 23 "data/maps/SSAnne_CaptainsOffice/scripts.pory"
	.string "Yuck! Shouldn't have looked!$"
