Route108_MapScripts::
	.byte 0


Route108_EventScript_Carolina::
# 5 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_CAROLINA, Route108_Text_CarolinaIntro, Route108_Text_CarolinaDefeated, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_CarolinaPostBattle
	return


Route108_EventScript_Cory::
# 10 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_CORY, Route108_Text_CoryIntro, Route108_Text_CoryDefeated, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_CoryPostBattle
	return


Route108_EventScript_Jerome::
# 15 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_JEROME, Route108_Text_JeromeIntro, Route108_Text_JeromeDefeated, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_JeromePostBattle
	return


Route108_EventScript_Matthew::
# 20 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_MATTHEW, Route108_Text_MatthewIntro, Route108_Text_MatthewDefeated, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_MatthewPostBattle
	return


Route108_EventScript_Missy::
# 25 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_MISSY, Route108_Text_MissyIntro, Route108_Text_MissyDefeated, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_MissyPostBattle
	return


Route108_EventScript_Tara::
# 30 "data/maps/Route108/scripts.pory"
	trainerbattle_double TRAINER_TARA, Route108_Text_TaraIntro, Route108_Text_TaraDefeated, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route108/scripts.pory"
	msgbox Route108_Text_TaraPostBattle
	return


Route108_Text_CarolinaDefeated::
# 36 "data/maps/Route108/scripts.pory"
	.string "That wasn't cute at all.$"

Route108_Text_CarolinaIntro::
# 40 "data/maps/Route108/scripts.pory"
	.string "I take huge pride in my POKéMON. We'll\n"
	.string "show you one speedy battle!$"

Route108_Text_CarolinaPostBattle::
# 44 "data/maps/Route108/scripts.pory"
	.string "Since I'm at sea like this, I wouldn't\n"
	.string "mind putting on a pink, frilly swimsuit…$"

Route108_Text_CoryDefeated::
# 48 "data/maps/Route108/scripts.pory"
	.string "Waaah! I lost! Waaah! Waaah!$"

Route108_Text_CoryIntro::
# 52 "data/maps/Route108/scripts.pory"
	.string "I love WATER-type POKéMON. I love other\n"
	.string "POKéMON, too!$"

Route108_Text_CoryPostBattle::
# 56 "data/maps/Route108/scripts.pory"
	.string "Shouting is good for me! It uplifts me!$"

Route108_Text_JeromeDefeated::
# 60 "data/maps/Route108/scripts.pory"
	.string "I won't be able to swim the seven seas\n"
	.string "like this…$"

Route108_Text_JeromeIntro::
# 64 "data/maps/Route108/scripts.pory"
	.string "My dream is to swim the world's seven\n"
	.string "seas!$"

Route108_Text_JeromePostBattle::
# 68 "data/maps/Route108/scripts.pory"
	.string "Playing with marine POKéMON is one of\n"
	.string "the pleasures of swimming!$"

Route108_Text_MatthewDefeated::
# 72 "data/maps/Route108/scripts.pory"
	.string "I'm sinking! Glub… Glub…$"

Route108_Text_MatthewIntro::
# 76 "data/maps/Route108/scripts.pory"
	.string "Ahoy, there! Are you going out to the\n"
	.string "ABANDONED SHIP, too?$"

Route108_Text_MatthewPostBattle::
# 80 "data/maps/Route108/scripts.pory"
	.string "Some people even go inside that\n"
	.string "ABANDONED SHIP.$"

Route108_Text_MissyDefeated::
# 84 "data/maps/Route108/scripts.pory"
	.string "When I lose a battle, I get all stressed\n"
	.string "out!$"

Route108_Text_MissyIntro::
# 88 "data/maps/Route108/scripts.pory"
	.string "I love the sea! I forget all my worries\n"
	.string "when I swim!$"

Route108_Text_MissyPostBattle::
# 92 "data/maps/Route108/scripts.pory"
	.string "Work off your stress by swimming! It's\n"
	.string "so healthy!$"

Route108_Text_TaraDefeated::
# 96 "data/maps/Route108/scripts.pory"
	.string "Oh, boo!$"

Route108_Text_TaraIntro::
# 100 "data/maps/Route108/scripts.pory"
	.string "My liar of a boyfriend told me that I\n"
	.string "look great in a bikini…$"

Route108_Text_TaraPostBattle::
# 104 "data/maps/Route108/scripts.pory"
	.string "Even if it's a lie, I love being told I\n"
	.string "look great… We girls are so complex…$"
