SlateportCity_Mart_MapScripts::
	.byte 0


SlateportCity_Mart_Text_SomeItemsOnlyAtMart::
# 5 "data/maps/SlateportCity_Mart/scripts.pory"
	.string "The MARKET does have some interesting\n"
	.string "merchandise.\p"
	.string "But there are some items you can only\n"
	.string "get at a POKMON MART.$"

SlateportCity_Mart_Text_GreatBallIsBetter::
# 9 "data/maps/SlateportCity_Mart/scripts.pory"
	.string "A GREAT BALL is better than a POK BALL\n"
	.string "at catching POKMON.\p"
	.string "With this, I should be able to get that\n"
	.string "elusive POKMON$"
