SlateportCity_Mart_MapScripts::
	.byte 0


SlateportCity_Mart_EventScript_BlackBelt::
# 5 "data/maps/SlateportCity_Mart/scripts.pory"
	msgbox SlateportCity_Mart_Text_SomeItemsOnlyAtMart, MSGBOX_NPC
	end


SlateportCity_Mart_EventScript_Clerk::
	end


SlateportCity_Mart_EventScript_Man::
# 14 "data/maps/SlateportCity_Mart/scripts.pory"
	msgbox SlateportCity_Mart_Text_GreatBallIsBetter, MSGBOX_NPC
	end


SlateportCity_Mart_Text_GreatBallIsBetter::
# 18 "data/maps/SlateportCity_Mart/scripts.pory"
	.string "A GREAT BALL is better than a POKé BALL\n"
	.string "at catching POKéMON.\p"
	.string "With this, I should be able to get that\n"
	.string "elusive POKéMON…$"

SlateportCity_Mart_Text_SomeItemsOnlyAtMart::
# 22 "data/maps/SlateportCity_Mart/scripts.pory"
	.string "The MARKET does have some interesting\n"
	.string "merchandise.\p"
	.string "But there are some items you can only\n"
	.string "get at a POKéMON MART.$"
