PalletTown_RivalsHouse_MapScripts::
# 2 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PalletTown_RivalsHouse_OnTransition
	.byte 0


PalletTown_RivalsHouse_Text_HiBrothersAtLab::
# 6 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: Hi, {PLAYER}!\p"
	.string "My brother, {RIVAL}, is out at\n"
	.string "Grandpa's LAB.$"

PalletTown_RivalsHouse_Text_HeardYouBattledRival::
# 10 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: {PLAYER}, I heard you had a\n"
	.string "battle against {RIVAL}.\p"
	.string "I wish I'd seen that!$"

PalletTown_RivalsHouse_Text_ErrandForGrandpaThisWillHelp::
# 14 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "Grandpa asked you to run an errand?\p"
	.string "Gee, that's lazy of him. Here, this will\n"
	.string "help you.$"

PalletTown_RivalsHouse_Text_ReceivedTownMapFromDaisy::
# 18 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "{PLAYER} received a TOWN MAP from\n"
	.string "DAISY.$"

PalletTown_RivalsHouse_Text_DontHaveSpaceForThis::
# 22 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "You don't have space for this in your\n"
	.string "BAG.$"

PalletTown_RivalsHouse_Text_ExplainTownMap::
# 26 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "You can use the TOWN MAP to find out\n"
	.string "where you are, or check the\l"
	.string "names of places.$"

PalletTown_RivalsHouse_Text_PleaseGiveMonsRest::
# 30 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: Just like people, POKMON are\n"
	.string "living things.\p"
	.string "When they get tired, please give them a\n"
	.string "rest.$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
# 34 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It's a big map of the KANTO region. Now\n"
	.string "this would be useful!$"

PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
# 38 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "The shelves are crammed full of books\n"
	.string "on POKMON.$"

PalletTown_RivalsHouse_Text_LikeMeToGroomMon::
# 42 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: Hi, {PLAYER}! Good timing.\p"
	.string "I'm about to have some tea. Would you\n"
	.string "like to join me?\p"
	.string "Oh, but look. Your POKMON are a little\n"
	.string "dirty.\p"
	.string "Would you like me to groom one?$"

PalletTown_RivalsHouse_Text_DontNeedAnyGrooming::
# 46 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "You don't need any grooming done? Okay,\n"
	.string "we'll just have tea.$"

PalletTown_RivalsHouse_Text_GroomWhichOne::
# 50 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "Which one should I groom?$"

PalletTown_RivalsHouse_Text_LookingNiceInNoTime::
# 54 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: Okay, I'll get it looking nice in\n"
	.string "no time.$"

PalletTown_RivalsHouse_Text_ThereYouGoAllDone::
# 58 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "{COLOR DARK_GRAY}{STR_VAR_1} looks dreamily content\p"
	.string "{COLOR RED}DAISY: There you go! All done.\n"
	.string "{FONT_NORMAL}{STR_VAR_1} looks dreamily content\p"
	.string "{FONT_FEMALE}DAISY: There you go! All done. See?\n"
	.string "Doesn't it look nice?\p"
	.string "Giggle It's such a cute POKMON.$"

PalletTown_RivalsHouse_Text_CantGroomAnEgg::
# 62 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "Oh, sorry. I honestly can't groom an EGG.$"

PalletTown_RivalsHouse_Text_MayISeeFirstMon::
# 66 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "DAISY: Your POKMON grow to love you if\n"
	.string "you raise them with love.\p"
	.string "For example, {PLAYER}, may I see your\n"
	.string "first POKMON?$"

PalletTown_RivalsHouse_Text_CouldntLoveYouMore::
# 70 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It couldn't possibly love you any more\n"
	.string "than it does now.\p"
	.string "Your POKMON is happy beyond words.$"

PalletTown_RivalsHouse_Text_ItLooksVeryHappy::
# 74 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It looks very happy.\p"
	.string "I wish {RIVAL} could see this and\n"
	.string "learn something from it.$"

PalletTown_RivalsHouse_Text_ItsQuiteFriendly::
# 78 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It's quite friendly with you. Keep being\n"
	.string "good to it!$"

PalletTown_RivalsHouse_Text_ItsWarmingUpToYou::
# 82 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It's warming up to you. Trust must be\n"
	.string "growing between you.$"

PalletTown_RivalsHouse_Text_NotFamiliarWithYouYet::
# 86 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It's not quite familiar with you yet.\p"
	.string "POKMON are all quite wary when you first\n"
	.string "get them.$"

PalletTown_RivalsHouse_Text_DontLikeWayItGlaresAtYou::
# 90 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "{PLAYER}, I don't like the way it\n"
	.string "glares at you.\p"
	.string "Could you try being a little nicer to it?$"

PalletTown_RivalsHouse_Text_WhyWouldMonHateYouSoMuch::
# 94 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "Um, it's not easy for me to say this, but\p"
	.string "Is there some reason why your POKMON\n"
	.string "would hate you so much?$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
# 98 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "The lovely and sweet CLEFAIRY$"
