PalletTown_RivalsHouse_MapScripts::
	.byte 0


PalletTown_RivalsHouse_EventScript_Bookshelf::
# 5 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	msgbox PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks, MSGBOX_SIGN
	end


PalletTown_RivalsHouse_EventScript_Daisy::
	end


PalletTown_RivalsHouse_EventScript_Picture::
# 14 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	msgbox PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy, MSGBOX_SIGN
	end


PalletTown_RivalsHouse_EventScript_TownMap::
# 19 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	msgbox PalletTown_RivalsHouse_Text_ItsBigMapOfKanto, MSGBOX_NPC
	end


PalletTown_RivalsHouse_EventScript_SmithNPC1::
# 37 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	msgbox PalletTown_RivalsHouse_Text_SmithNPC1, MSGBOX_NPC
	end


PalletTown_RivalsHouse_Text_ShelvesCrammedFullOfBooks::
# 24 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "The shelves are crammed full of\n"
	.string "books on POKéMON.$"

PalletTown_RivalsHouse_Text_LovelyAndSweetClefairy::
# 28 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "“The lovely and sweet\n"
	.string "CLEFAIRY”$"

PalletTown_RivalsHouse_Text_ItsBigMapOfKanto::
# 32 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "It's a big map of the KANTO region.\n"
	.string "Now this would be useful!$"

PalletTown_RivalsHouse_Text_SmithNPC1::
# 41 "data/maps/PalletTown_RivalsHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"
