SilphCo_8F_MapScripts::
# 2 "data/maps/SilphCo_8F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_8F_OnLoad
	.byte 0


SilphCo_8F_Text_WonderIfSilphIsFinished::
# 6 "data/maps/SilphCo_8F/scripts.pory"
	.string "I wonder if SILPH is finished…$"

SilphCo_8F_Text_ThanksForSavingUs::
# 10 "data/maps/SilphCo_8F/scripts.pory"
	.string "Thanks for saving us!$"

SilphCo_8F_Text_Grunt1Intro::
# 14 "data/maps/SilphCo_8F/scripts.pory"
	.string "That's as far as you'll go!$"

SilphCo_8F_Text_Grunt1Defeat::
# 18 "data/maps/SilphCo_8F/scripts.pory"
	.string "Not enough grit!$"

SilphCo_8F_Text_Grunt1PostBattle::
# 22 "data/maps/SilphCo_8F/scripts.pory"
	.string "If you don't turn back… I'll call for\n"
	.string "backup!$"

SilphCo_8F_Text_ParkerIntro::
# 26 "data/maps/SilphCo_8F/scripts.pory"
	.string "You're causing us problems!$"

SilphCo_8F_Text_ParkerDefeat::
# 30 "data/maps/SilphCo_8F/scripts.pory"
	.string "Huh? I lost?$"

SilphCo_8F_Text_ParkerPostBattle::
# 34 "data/maps/SilphCo_8F/scripts.pory"
	.string "So, what do you think of SILPH\n"
	.string "BUILDING's maze?$"

SilphCo_8F_Text_Grunt2Intro::
# 38 "data/maps/SilphCo_8F/scripts.pory"
	.string "I am one of the four ROCKET BROTHERS!$"

SilphCo_8F_Text_Grunt2Defeat::
# 42 "data/maps/SilphCo_8F/scripts.pory"
	.string "Whoo! Oh, Brothers!$"

SilphCo_8F_Text_Grunt2PostBattle::
# 46 "data/maps/SilphCo_8F/scripts.pory"
	.string "I'll leave you up to my brothers.$"

SilphCo_8F_Text_FloorSign::
# 50 "data/maps/SilphCo_8F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 8F$"

SilphCo_8F_Text_ToRocketBossMonsAreTools::
# 54 "data/maps/SilphCo_8F/scripts.pory"
	.string "TEAM ROCKET's BOSS is terribly cruel!\p"
	.string "To him, POKéMON are just tools to be\n"
	.string "used.\p"
	.string "What will happen if that tyrant takes\n"
	.string "over our company…$"
