SSAnne_2F_Room4_MapScripts::
	.byte 0


SSAnne_2F_Room4_Text_LamarIntro::
# 5 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "Which do you find more worthy, a strong\n"
	.string "or a rare POKMON?$"

SSAnne_2F_Room4_Text_LamarDefeat::
# 9 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "I must salute you!$"

SSAnne_2F_Room4_Text_LamarPostBattle::
# 13 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "Personally, I prefer strong and rare\n"
	.string "POKMON.$"

SSAnne_2F_Room4_Text_DawnIntro::
# 17 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "I don't believe I saw you at the party?$"

SSAnne_2F_Room4_Text_DawnDefeat::
# 21 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "Take it easy!$"

SSAnne_2F_Room4_Text_DawnPostBattle::
# 25 "data/maps/SSAnne_2F_Room4/scripts.pory"
	.string "Oh, I adore your strong POKMON! Oh, how\n"
	.string "I envy you for them!$"
