VerdanturfTown_Mart_MapScripts::
	.byte 0


VerdanturfTown_Mart_Text_XSpecialIsCrucial::
# 5 "data/maps/VerdanturfTown_Mart/scripts.pory"
	.string "For any POKMON match, X SPECIAL is\n"
	.string "crucial.\p"
	.string "It jacks up the power of some moves\n"
	.string "even though it's only for one battle.$"

VerdanturfTown_Mart_Text_NoStrategyGuidesForBattleTent::
# 9 "data/maps/VerdanturfTown_Mart/scripts.pory"
	.string "They don't seem to sell any winning\n"
	.string "strategy guides for the BATTLE TENT\p"
	.string "It seems one must rely on one's own wits\n"
	.string "after all$"

VerdanturfTown_Mart_Text_NestBallOnWeakenedPokemon::
# 13 "data/maps/VerdanturfTown_Mart/scripts.pory"
	.string "The NEST BALL works better on weakened\n"
	.string "POKMON.\p"
	.string "VERDANTURF is the only place you can\n"
	.string "buy it.$"
