SafariZone_North_RestHouse_MapScripts::
	.byte 0


SafariZone_North_RestHouse_EventScript_BaldingMan::
	end


SafariZone_North_RestHouse_EventScript_Fisher::
# 9 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_PrizeInDeepestPartOfSafariZone, MSGBOX_NPC
	end


SafariZone_North_RestHouse_EventScript_Gentleman::
# 14 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_MyEeveeEvolvedIntoFlareon, MSGBOX_NPC
	end


SafariZone_North_RestHouse_EventScript_Scientist::
# 19 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	msgbox SafariZone_East_Text_KeepAnyItemFoundOnSafari, MSGBOX_NPC
	end


SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
# 24 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "Go to the deepest part of the\n"
	.string "SAFARI ZONE. You will win a prize!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
# 28 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "My EEVEE evolved into FLAREON.\p"
	.string "But, a friend's EEVEE turned into a\n"
	.string "VAPOREON. I wonder why?$"

SafariZone_East_Text_KeepAnyItemFoundOnSafari::
# 32 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "You can keep any item you find in\n"
	.string "the SAFARI ZONE.\p"
	.string "But, you'll run out of time if you\n"
	.string "try for all of them at once.$"
