SafariZone_North_RestHouse_MapScripts::
	.byte 0


SafariZone_East_Text_KeepAnyItemFoundOnSafari::
# 5 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "You can keep any item you find in the\n"
	.string "SAFARI ZONE.\p"
	.string "But, you'll run out of time if you try for\n"
	.string "all of them at once.$"

SafariZone_East_Text_PrizeInDeepestPartOfSafariZone::
# 9 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "Go to the deepest part of the SAFARI\n"
	.string "ZONE. You will win a prize!$"

SafariZone_East_Text_MyEeveeEvolvedIntoFlareon::
# 13 "data/maps/SafariZone_North_RestHouse/scripts.pory"
	.string "My EEVEE evolved into FLAREON.\p"
	.string "But, a friend's EEVEE turned into a\n"
	.string "VAPOREON. I wonder why?$"
