ThreeIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/ThreeIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/ThreeIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


ThreeIsland_PokemonCenter_1F_Text_PCNetworkCanLinkWithKanto::
# 7 "data/maps/ThreeIsland_PokemonCenter_1F/scripts.pory"
	.string "Hey, did you hear the news?\p"
	.string "The PC network here can now link with\n"
	.string "PCs in KANTO.\p"
	.string "I don't know how that came about, but\n"
	.string "it's fantastic!$"

ThreeIsland_PokemonCenter_1F_Text_ImpossibleToSurfBetweenIslands::
# 11 "data/maps/ThreeIsland_PokemonCenter_1F/scripts.pory"
	.string "It's impossible to SURF between the\n"
	.string "islands around these parts.\p"
	.string "The tides are too fast and treacherous.$"

ThreeIsland_PokemonCenter_1F_Text_AlwaysBerriesInBerryForest::
# 15 "data/maps/ThreeIsland_PokemonCenter_1F/scripts.pory"
	.string "Let's crush BERRIES! That'd be wasting\n"
	.string "BERRIES?\p"
	.string "You can always find some BERRIES on\n"
	.string "the ground in BERRY FOREST.$"
