JubilifeCity_PokemonSchool_MapScripts::
	.byte 0


JubilifeCity_PokemonSchool_EventScript_SmithNPC1::
# 5 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	msgbox JubilifeCity_PokemonSchool_Text_SmithNPC1, MSGBOX_NPC
	end


JubilifeCity_PokemonSchool_EventScript_SmithNPC2::
# 14 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	msgbox JubilifeCity_PokemonSchool_Text_SmithNPC2, MSGBOX_NPC
	end


JubilifeCity_PokemonSchool_EventScript_SmithNPC3::
# 23 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	msgbox JubilifeCity_PokemonSchool_Text_SmithNPC3, MSGBOX_NPC
	end


JubilifeCity_PokemonSchool_EventScript_SmithNPC4::
# 32 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	msgbox JubilifeCity_PokemonSchool_Text_SmithNPC4, MSGBOX_NPC
	end


JubilifeCity_PokemonSchool_Text_SmithNPC1::
# 9 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

JubilifeCity_PokemonSchool_Text_SmithNPC2::
# 18 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

JubilifeCity_PokemonSchool_Text_SmithNPC3::
# 27 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

JubilifeCity_PokemonSchool_Text_SmithNPC4::
# 36 "data/maps/JubilifeCity_PokemonSchool/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
