OneIsland_KindleRoad_MapScripts::
	.byte 0

OneIsland_KindleRoad_EventScript_RouteSign::
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_EventScript_EmberSpaSign::
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end

OneIsland_KindleRoad_Text_RouteSign::
    .string "This is KINDLE ROAD.\p"
    .string "Go straight for MT. EMBER.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
    .string "Light the Fire in Your Heart!\n"
    .string "EMBER SPA$"
