OneIsland_KindleRoad_MapScripts::
	.byte 0


OneIsland_KindleRoad_Text_MariaIntro::
# 5 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "The weather's gorgeous! Perfect for a\n"
	.string "battle!$"

OneIsland_KindleRoad_Text_MariaDefeat::
# 9 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Aiyeeeeh!$"

OneIsland_KindleRoad_Text_MariaPostBattle::
# 13 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Please don't splash my face! You'll ruin\n"
	.string "the makeup.$"

OneIsland_KindleRoad_Text_AbigailIntro::
# 17 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I'm beginning to get a sunburn…$"

OneIsland_KindleRoad_Text_AbigailDefeat::
# 21 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Oh, you're so awful.$"

OneIsland_KindleRoad_Text_AbigailPostBattle::
# 25 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I like that cap you have. Maybe I should\n"
	.string "wear one, too…$"

OneIsland_KindleRoad_Text_FinnIntro::
# 29 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Seen from here, MT. EMBER towers into\n"
	.string "the sky.$"

OneIsland_KindleRoad_Text_FinnDefeat::
# 33 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Well, aren't you tough?$"

OneIsland_KindleRoad_Text_FinnPostBattle::
# 37 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "The sky is immense around these parts.$"

OneIsland_KindleRoad_Text_GarrettIntro::
# 41 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I took a break from swimming, only to\n"
	.string "have you challenge me?$"

OneIsland_KindleRoad_Text_GarrettDefeat::
# 45 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Hey, what the… You're good, you!$"

OneIsland_KindleRoad_Text_GarrettPostBattle::
# 49 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Instead of using SURF all the time, you\n"
	.string "should swim some.$"

OneIsland_KindleRoad_Text_TommyIntro::
# 53 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Wait! Wait a second! I think I've hooked\n"
	.string "a big one!$"

OneIsland_KindleRoad_Text_TommyDefeat::
# 57 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I've lost it all again…$"

OneIsland_KindleRoad_Text_TommyPostBattle::
# 61 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Not only did I lose, the big one got away\n"
	.string "from me, too!$"

OneIsland_KindleRoad_Text_SharonIntro::
# 65 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Could you help me out with my training?$"

OneIsland_KindleRoad_Text_SharonDefeat::
# 69 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "You were a cut above me.$"

OneIsland_KindleRoad_Text_SharonPostBattle::
# 73 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "It's clear that you're skilled. I like\n"
	.string "you!$"

OneIsland_KindleRoad_Text_TanyaIntro::
# 77 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "There isn't a day in which we don't\n"
	.string "train!$"

OneIsland_KindleRoad_Text_TanyaDefeat::
# 81 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I'm such a fool!$"

OneIsland_KindleRoad_Text_TanyaPostBattle::
# 85 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I'll train even harder from now on!$"

OneIsland_KindleRoad_Text_SheaIntro::
# 89 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Every morning, before breakfast, I swim\n"
	.string "around this island.$"

OneIsland_KindleRoad_Text_SheaDefeat::
# 93 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Gasp… Gasp…$"

OneIsland_KindleRoad_Text_SheaPostBattle::
# 97 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "I lost because I'm pooped from all the\n"
	.string "running I did…$"

OneIsland_KindleRoad_Text_HughIntro::
# 101 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Dress appropriately for battle! Lose\n"
	.string "that frivolous outfit!$"

OneIsland_KindleRoad_Text_HughDefeat::
# 105 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Why me?!$"

OneIsland_KindleRoad_Text_HughPostBattle::
# 109 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Even martial artists are becoming\n"
	.string "fashion conscious these days…$"

OneIsland_KindleRoad_Text_BryceIntro::
# 113 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "You know, everything tastes great when\n"
	.string "you're out in the wild.$"

OneIsland_KindleRoad_Text_BryceDefeat::
# 117 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Awww, blown!$"

OneIsland_KindleRoad_Text_BrycePostBattle::
# 121 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "The water in volcanic regions is\n"
	.string "delicious.$"

OneIsland_KindleRoad_Text_ClaireIntro::
# 125 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "My lunch filled us up, so will you battle\n"
	.string "us for some exercise?$"

OneIsland_KindleRoad_Text_ClaireDefeat::
# 129 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "That made me all sweaty.$"

OneIsland_KindleRoad_Text_ClairePostBattle::
# 133 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "What should I do? I feel famished again.$"

OneIsland_KindleRoad_Text_KiaIntro::
# 137 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "KIA: My big brother and I make an\n"
	.string "awesome combination!$"

OneIsland_KindleRoad_Text_KiaDefeat::
# 141 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "KIA: Huh?! I can't believe it!$"

OneIsland_KindleRoad_Text_KiaPostBattle::
# 145 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "KIA: How could there be anyone better\n"
	.string "than my big brother?$"

OneIsland_KindleRoad_Text_KiaNotEnoughMons::
# 149 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "KIA: If you want to battle with us, you\n"
	.string "have to bring at least two\l"
	.string "POKéMON with you.$"

OneIsland_KindleRoad_Text_MikIntro::
# 153 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "MIK: Together with KIA, I'm afraid of\n"
	.string "nothing!$"

OneIsland_KindleRoad_Text_MikDefeat::
# 157 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "MIK: Whoa! That's too much!$"

OneIsland_KindleRoad_Text_MikPostBattle::
# 161 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "MIK: How could my combination with KIA\n"
	.string "fail?$"

OneIsland_KindleRoad_Text_MikNotEnoughMons::
# 165 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "MIK: Hey, do you want to battle with us\n"
	.string "two?\p"
	.string "Bring two or more POKéMON with you,\n"
	.string "then.$"

OneIsland_KindleRoad_Text_RouteSign::
# 169 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "This is KINDLE ROAD.\p"
	.string "Go straight for MT. EMBER.$"

OneIsland_KindleRoad_Text_EmberSpaSign::
# 173 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Light the Fire in Your Heart! EMBER SPA$"
