OneIsland_KindleRoad_MapScripts::
	.byte 0


OneIsland_KindleRoad_EventScript_EmberSpaSign::
# 5 "data/maps/OneIsland_KindleRoad/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_EmberSpaSign, MSGBOX_SIGN
	end


OneIsland_KindleRoad_EventScript_RouteSign::
# 10 "data/maps/OneIsland_KindleRoad/scripts.pory"
	msgbox OneIsland_KindleRoad_Text_RouteSign, MSGBOX_SIGN
	end


OneIsland_KindleRoad_Text_EmberSpaSign::
# 15 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "Light the Fire in Your Heart! EMBER SPA$"

OneIsland_KindleRoad_Text_RouteSign::
# 19 "data/maps/OneIsland_KindleRoad/scripts.pory"
	.string "This is KINDLE ROAD.\p"
	.string "Go straight for MT. EMBER.$"
