BattleFrontier_BattlePikeLobby_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeLobby_OnFrame
# 3 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeLobby_OnWarp
	.byte 0


BattleFrontier_BattlePikeLobby_Text_WelcomeToBattlePike::
# 7 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Where the luck of TRAINERS is put to\n"
	.string "the test\p"
	.string "Welcome to the BATTLE PIKE\p"
	.string "I am your guide to the BATTLE PIKE$"

BattleFrontier_BattlePikeLobby_Text_TakeChallenge::
# 11 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Would you like to take the Battle\n"
	.string "Choice challenge?$"

BattleFrontier_BattlePikeLobby_Text_ExplainBattlePike::
# 15 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Here we conduct an event we call the\n"
	.string "Battle Choice.\p"
	.string "The Battle Choice rules are very simple\p"
	.string "Choose one of three paths and make\n"
	.string "your way to the goal room at the end\l"
	.string "of the BATTLE PIKE. It's that simple.\p"
	.string "However, what happens on the chosen\n"
	.string "path depends entirely on the luck\l"
	.string "of the challenger\p"
	.string "If you reach the goal, you will be\n"
	.string "rewarded with Battle Points.\p"
	.string "If you want to interrupt your\n"
	.string "challenge, please have a word with\l"
	.string "our staff in the big rooms on the way.\p"
	.string "If you don't save before interrupting,\n"
	.string "you will be disqualified.$"

BattleFrontier_BattlePikeLobby_Text_LookForwardToSeeingYou::
# 19 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "We look forward to seeing you on\n"
	.string "another occasion$"

BattleFrontier_BattlePikeLobby_Text_WhichChallengeMode::
# 23 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "You have the choice of two courses,\n"
	.string "Level 50 and Open Level.\l"
	.string "Which will you challenge?$"

BattleFrontier_BattlePikeLobby_Text_NotEnoughValidMonsLv50::
# 27 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "I beg your pardon, but\p"
	.string "You do not have three eligible POKMON\n"
	.string "for the Battle Choice event.\p"
	.string "You must have three different POKMON\n"
	.string "of Level 50 or less to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Please come see me when you are ready$"

BattleFrontier_BattlePikeLobby_Text_NotEnoughValidMonsLvOpen::
# 31 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "I beg your pardon, but\p"
	.string "You do not have three eligible POKMON\n"
	.string "for the Battle Choice event.\p"
	.string "You must have three different POKMON\n"
	.string "to enter.\p"
	.string "They also must be holding different\n"
	.string "kinds of items.\p"
	.string "EGGS{STR_VAR_1} ineligible.\p"
	.string "Please come see me when you are ready$"

BattleFrontier_BattlePikeLobby_Text_PleaseChooseThreeMons::
# 35 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Please choose the three POKMON you\n"
	.string "wish to enter in the challenge$"

BattleFrontier_BattlePikeLobby_Text_SaveBeforeChallenge::
# 39 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Before starting your Battle Choice\n"
	.string "challenge, I must save the game.\l"
	.string "Is that acceptable?$"

BattleFrontier_BattlePikeLobby_Text_StepThisWay::
# 43 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Please step this way$"

BattleFrontier_BattlePikeLobby_Text_ChallengeEndedRecordResults::
# 47 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Your challenge has ended\p"
	.string "I shall record your results. Please wait$"

BattleFrontier_BattlePikeLobby_Text_PossessLuckInAbundance::
# 51 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "You have completed the challenge\p"
	.string "I must say You seem to possess luck in\n"
	.string "abundance$"

BattleFrontier_BattlePikeLobby_Text_ShallRecordResults::
# 55 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "I shall record your results. Please wait$"

BattleFrontier_BattlePikeLobby_Text_AwardYouTheseBattlePoints2::
# 59 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "To commemorate your completion of the\n"
	.string "Battle Choice challenge, we award\l"
	.string "you these Battle Point(s)$"

BattleFrontier_BattlePikeLobby_Text_ReachedBattlePointLimit::
# 63 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "You appear to have reached the limit\n"
	.string "for Battle Points\p"
	.string "Please exchange some Battle Points for\n"
	.string "prizes, then return$"

BattleFrontier_BattlePikeLobby_Text_FailedToSaveBeforeQuitting::
# 67 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "I beg your pardon, but\p"
	.string "You failed to save before you quit your\n"
	.string "challenge the last time.\p"
	.string "Because of that, your challenge so far\n"
	.string "has been disqualified. I am sorry$"

BattleFrontier_BattlePikeLobby_Text_SnatchedVictoryFromQueen::
# 71 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Congratulations\p"
	.string "You have snatched victory from the\n"
	.string "PIKE QUEEN and cleared the event$"

BattleFrontier_BattlePikeLobby_Text_AwardYouTheseBattlePoints::
# 75 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "In recognition of your amazing luck, we\n"
	.string "award you these Battle Point(s)$"

BattleFrontier_BattlePikeLobby_Text_OneRoomAwayFromGoal::
# 79 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Arrgh! I blew my chance! I was one room\n"
	.string "away from the goal!\p"
	.string "In this place, you'd better watch out\n"
	.string "for poison, freezing, and so on.$"

BattleFrontier_BattlePikeLobby_Text_NeverHadToBattleTrainer::
# 83 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "I've completed the challenge 10 times\n"
	.string "now, but I've never had to battle\l"
	.string "a TRAINER once.$"

BattleFrontier_BattlePikeLobby_Text_ThinkAbilitiesUsefulHere::
# 87 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Listen! Listen!\p"
	.string "Don't you think that the special\n"
	.string "abilities of POKMON will be useful\l"
	.string "here?$"

BattleFrontier_BattlePikeLobby_Text_TrainersWhicheverPathIChoose::
# 91 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "What is this weird place? I can't figure\n"
	.string "it out at all!\p"
	.string "I've taken the challenge a bunch of\n"
	.string "times, but all I ever do is run into\l"
	.string "TRAINERS whichever path I choose.$"

BattleFrontier_BattlePikeLobby_Text_RulesAreListed::
# 95 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "The Battle Choice's rules are listed.$"

BattleFrontier_BattlePikeLobby_Text_ReadWhichHeading::
# 99 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "Which heading do you want to read?$"

BattleFrontier_BattlePikeLobby_Text_ExplainPokenavBagRules::
# 103 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "The BAG and POKNAV may not be used\n"
	.string "during a Battle Choice challenge.$"

BattleFrontier_BattlePikeLobby_Text_ExplainHeldItemRules::
# 107 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "During a Battle Choice challenge, any\n"
	.string "BERRY or HERB held by POKMON\l"
	.string "will be effective only once.$"

BattleFrontier_BattlePikeLobby_Text_ExplainMonOrderRules::
# 111 "data/maps/BattleFrontier_BattlePikeLobby/scripts.pory"
	.string "During a Battle Choice challenge, the\n"
	.string "sequence of POKMON cannot be\l"
	.string "changed.\p"
	.string "The sequence must be set before\n"
	.string "starting your challenge.$"
