Route40_MapScripts::
	.byte 0


Route40_EventScript_Sign1::
# 6 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_Sign1, MSGBOX_SIGN
	end


Route40_EventScript_Sign2::
# 15 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_Sign2, MSGBOX_SIGN
	end


Route40_EventScript_SmithNPC1::
# 24 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC1, MSGBOX_NPC
	end


Route40_EventScript_SmithNPC2::
# 33 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC2, MSGBOX_NPC
	end


Route40_EventScript_SmithNPC3::
# 42 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC3, MSGBOX_NPC
	end


Route40_EventScript_SmithNPC4::
# 51 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC4, MSGBOX_NPC
	end


Route40_EventScript_SmithNPC5::
# 60 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC5, MSGBOX_NPC
	end


Route40_EventScript_SmithNPC6::
# 69 "data/maps/Route40/scripts.pory"
	msgbox Route40_Text_SmithNPC6, MSGBOX_NPC
	end


Route40_Text_Sign1::
# 10 "data/maps/Route40/scripts.pory"
	.string "Route40 Sign 1$"

Route40_Text_Sign2::
# 19 "data/maps/Route40/scripts.pory"
	.string "Route40 Sign 2$"

Route40_Text_SmithNPC1::
# 28 "data/maps/Route40/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route40_Text_SmithNPC2::
# 37 "data/maps/Route40/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route40_Text_SmithNPC3::
# 46 "data/maps/Route40/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

Route40_Text_SmithNPC4::
# 55 "data/maps/Route40/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

Route40_Text_SmithNPC5::
# 64 "data/maps/Route40/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

Route40_Text_SmithNPC6::
# 73 "data/maps/Route40/scripts.pory"
	.string "It's the question that drives us, Neo.$"
