PokemonTower_4F_MapScripts::
	.byte 0


PokemonTower_4F_Text_PaulaIntro::
# 5 "data/maps/PokemonTower_4F/scripts.pory"
	.string "Ghost! No! Kwaaah!$"

PokemonTower_4F_Text_PaulaDefeat::
# 9 "data/maps/PokemonTower_4F/scripts.pory"
	.string "Where is the ghost?$"

PokemonTower_4F_Text_PaulaPostBattle::
# 13 "data/maps/PokemonTower_4F/scripts.pory"
	.string "I must have been dreaming…$"

PokemonTower_4F_Text_LaurelIntro::
# 17 "data/maps/PokemonTower_4F/scripts.pory"
	.string "Be cursed with me! Kwaaah!$"

PokemonTower_4F_Text_LaurelDefeat::
# 21 "data/maps/PokemonTower_4F/scripts.pory"
	.string "What!$"

PokemonTower_4F_Text_LaurelPostBattle::
# 25 "data/maps/PokemonTower_4F/scripts.pory"
	.string "We can't determine the identity of the\n"
	.string "ghosts…$"

PokemonTower_4F_Text_JodyIntro::
# 29 "data/maps/PokemonTower_4F/scripts.pory"
	.string "Huhuhu… Beat me not!$"

PokemonTower_4F_Text_JodyDefeat::
# 33 "data/maps/PokemonTower_4F/scripts.pory"
	.string "Huh? Who? What?$"

PokemonTower_4F_Text_JodyPostBattle::
# 37 "data/maps/PokemonTower_4F/scripts.pory"
	.string "May the departed POKéMON rest in\n"
	.string "peace…$"
