CeladonCity_DepartmentStore_2F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_2F_Text_SuperRepelMorePowerfulRepel::
# 5 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "SUPER REPEL keeps weak POKMON at bay\p"
	.string "Hmm, it's a more powerful REPEL.$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
# 9 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "For long outings, you should buy\n"
	.string "REVIVE.$"

CeladonCity_DepartmentStore_2F_Text_FloorSign::
# 13 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "Top-Grade Items for TRAINERS!\p"
	.string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_LanceComesToBuyCapes::
# 17 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "We have a customer, LANCE, who\n"
	.string "occasionally comes.\p"
	.string "He always buys capes.\p"
	.string "I wonder Does he have many identical\n"
	.string "capes at home?$"
