CeladonCity_DepartmentStore_2F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_2F_EventScript_ClerkItems::
	end


CeladonCity_DepartmentStore_2F_EventScript_ClerkTMs::
	end


CeladonCity_DepartmentStore_2F_EventScript_FloorSign::
# 13 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_2F_Text_FloorSign, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_2F_EventScript_Lass::
# 18 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_2F_Text_FloorSign::
# 22 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "Top-Grade Items for TRAINERS!\p"
	.string "2F: TRAINER'S MARKET$"

CeladonCity_DepartmentStore_2F_Text_BuyReviveForLongOutings::
# 26 "data/maps/CeladonCity_DepartmentStore_2F/scripts.pory"
	.string "For long outings, you should buy\n"
	.string "REVIVE.$"
