MooMooFarm_MapScripts::
	.byte 0


MooMooFarm_EventScript_SmithNPC1::
# 5 "data/maps/MooMooFarm/scripts.pory"
	msgbox MooMooFarm_Text_SmithNPC1, MSGBOX_NPC
	end


MooMooFarm_EventScript_SmithNPC2::
# 14 "data/maps/MooMooFarm/scripts.pory"
	msgbox MooMooFarm_Text_SmithNPC2, MSGBOX_NPC
	end


MooMooFarm_EventScript_SmithNPC3::
# 23 "data/maps/MooMooFarm/scripts.pory"
	msgbox MooMooFarm_Text_SmithNPC3, MSGBOX_NPC
	end


MooMooFarm_Text_SmithNPC1::
# 9 "data/maps/MooMooFarm/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MooMooFarm_Text_SmithNPC2::
# 18 "data/maps/MooMooFarm/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

MooMooFarm_Text_SmithNPC3::
# 27 "data/maps/MooMooFarm/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
