SilphCo_5F_MapScripts::
# 2 "data/maps/SilphCo_5F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_5F_OnLoad
	.byte 0


SilphCo_5F_Text_RocketsInUproarAboutIntruder::
# 6 "data/maps/SilphCo_5F/scripts.pory"
	.string "TEAM ROCKET is in an uproar over some\n"
	.string "intruder.\p"
	.string "That's you, right?$"

SilphCo_5F_Text_YoureOurHeroThankYou::
# 10 "data/maps/SilphCo_5F/scripts.pory"
	.string "TEAM ROCKET took off! You're our hero!\n"
	.string "Thank you!$"

SilphCo_5F_Text_Grunt1Intro::
# 14 "data/maps/SilphCo_5F/scripts.pory"
	.string "I heard a kid was wandering around.$"

SilphCo_5F_Text_Grunt1Defeat::
# 18 "data/maps/SilphCo_5F/scripts.pory"
	.string "Boom!$"

SilphCo_5F_Text_Grunt1PostBattle::
# 22 "data/maps/SilphCo_5F/scripts.pory"
	.string "It's not smart to pick a fight with TEAM\n"
	.string "ROCKET!$"

SilphCo_5F_Text_BeauIntro::
# 26 "data/maps/SilphCo_5F/scripts.pory"
	.string "We study POK BALL technology on this\n"
	.string "floor.$"

SilphCo_5F_Text_BeauDefeat::
# 30 "data/maps/SilphCo_5F/scripts.pory"
	.string "Dang! Blast it!$"

SilphCo_5F_Text_BeauPostBattle::
# 34 "data/maps/SilphCo_5F/scripts.pory"
	.string "We worked on the ultimate POK BALL\n"
	.string "which would catch anything.$"

SilphCo_5F_Text_DaltonIntro::
# 38 "data/maps/SilphCo_5F/scripts.pory"
	.string "Whaaat?\p"
	.string "There shouldn't be any children here!$"

SilphCo_5F_Text_DaltonDefeat::
# 42 "data/maps/SilphCo_5F/scripts.pory"
	.string "Oh, goodness!$"

SilphCo_5F_Text_DaltonPostBattle::
# 46 "data/maps/SilphCo_5F/scripts.pory"
	.string "You're only on 5F. It's a long way to my\n"
	.string "BOSS!$"

SilphCo_5F_Text_Grunt2Intro::
# 50 "data/maps/SilphCo_5F/scripts.pory"
	.string "Show TEAM ROCKET a little respect!$"

SilphCo_5F_Text_Grunt2Defeat::
# 54 "data/maps/SilphCo_5F/scripts.pory"
	.string "Cough Cough$"

SilphCo_5F_Text_Grunt2PostBattle::
# 58 "data/maps/SilphCo_5F/scripts.pory"
	.string "Which reminds me.\p"
	.string "KOFFING evolves into WEEZING!$"

SilphCo_5F_Text_PorygonFirstVRMon::
# 62 "data/maps/SilphCo_5F/scripts.pory"
	.string "It's a POKMON REPORT!\p"
	.string "POKMON LAB created PORYGON, the first\n"
	.string "virtual-reality POKMON.$"

SilphCo_5F_Text_Over350TechniquesConfirmed::
# 66 "data/maps/SilphCo_5F/scripts.pory"
	.string "It's a POKMON REPORT!\p"
	.string "Over 350 POKMON techniques have been\n"
	.string "confirmed.$"

SilphCo_5F_Text_SomeMonsEvolveWhenTraded::
# 70 "data/maps/SilphCo_5F/scripts.pory"
	.string "It's a POKMON REPORT!\p"
	.string "Some POKMON have been confirmed to\n"
	.string "evolve when they are traded.$"

SilphCo_5F_Text_FloorSign::
# 74 "data/maps/SilphCo_5F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 5F$"

SilphCo_5F_Text_RocketBossLookingForStrongMons::
# 78 "data/maps/SilphCo_5F/scripts.pory"
	.string "Those thugs that took over our building\p"
	.string "Their BOSS said he was looking for\n"
	.string "strong POKMON.\p"
	.string "I hope our PRESIDENT managed to avoid\n"
	.string "trouble$"
