SafariZone_RestHouse_MapScripts::
	.byte 0


SafariZone_RestHouse_EventScript_FatMan::
# 5 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_FatMan, MSGBOX_NPC
	end


SafariZone_RestHouse_EventScript_PsychicM::
# 10 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_PsychicM, MSGBOX_NPC
	end


SafariZone_RestHouse_EventScript_Youngster::
# 15 "data/maps/SafariZone_RestHouse/scripts.pory"
	msgbox SafariZone_RestHouse_Text_Youngster, MSGBOX_NPC
	end

