LavenderTown_Mart_MapScripts::
	.byte 0


LavenderTown_Mart_Text_SearchingForStatRaiseItems::
# 5 "data/maps/LavenderTown_Mart/scripts.pory"
	.string "I'm searching for items that raise the\n"
	.string "stats of POKéMON.\p"
	.string "They're effective over the course of a\n"
	.string "single battle.\p"
	.string "X ATTACK, X DEFEND, X SPEED, and X\n"
	.string "SPECIAL are what I'm after.\p"
	.string "Do you know where I can get them?$"

LavenderTown_Mart_Text_DidYouBuyRevives::
# 9 "data/maps/LavenderTown_Mart/scripts.pory"
	.string "Did you buy some REVIVES? They revive\n"
	.string "any fainted POKéMON!$"

LavenderTown_Mart_Text_TrainerDuosCanChallengeYou::
# 13 "data/maps/LavenderTown_Mart/scripts.pory"
	.string "Sometimes, a TRAINER duo will challenge\n"
	.string "you with two POKéMON\l"
	.string "at the same time.\p"
	.string "If that happens, you have to send out\n"
	.string "two POKéMON to battle, too.$"

LavenderTown_Mart_Text_SoldNuggetFromMountainsFor5000::
# 17 "data/maps/LavenderTown_Mart/scripts.pory"
	.string "この　あいだ　やまおくで きんのたまを　ひろい　ましてね！\p"
	.string "つかえない　しなもの　ですが うったら　なんと　5000¥でした$"
