PalletTown_PlayersHouse_2F_MapScripts::
# 2 "data/maps/PalletTown_PlayersHouse_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PalletTown_PlayersHouse_2F_OnTransition
# 3 "data/maps/PalletTown_PlayersHouse_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PalletTown_PlayersHouse_2F_OnWarp
	.byte 0


PalletTown_PlayersHouse_2F_Text_PlayedWithNES::
# 7 "data/maps/PalletTown_PlayersHouse_2F/scripts.pory"
	.string "{PLAYER} played with the NES.\p"
	.string "…Okay! It's time to go!$"

PalletTown_PlayersHouse_2F_Text_PressLRForHelp::
# 11 "data/maps/PalletTown_PlayersHouse_2F/scripts.pory"
	.string "It's a posted notice…\p"
	.string "If you're confused, ask for HELP! Press\n"
	.string "the L or R Button!$"
