SlateportCity_MapScripts::
# 2 "data/maps/SlateportCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SlateportCity_OnTransition
# 3 "data/maps/SlateportCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SlateportCity_OnFrame
	.byte 0


SlateportCity_Text_EnergyGuruSellWhatYouNeed::
# 7 "data/maps/SlateportCity/scripts.pory"
	.string "I'm the ENERGY GURU! I'll go for it and\n"
	.string "sell you what you need!$"

SlateportCity_Text_OhYourPokemon::
# 11 "data/maps/SlateportCity/scripts.pory"
	.string "Oh? Your {STR_VAR_1}$"

SlateportCity_Text_PleaseGiveItThisEffortRibbon::
# 15 "data/maps/SlateportCity/scripts.pory"
	.string "Went for it stupendously!\p"
	.string "As its reward, please give it this\n"
	.string "EFFORT RIBBON.$"

SlateportCity_Text_ReceivedEffortRibbon::
# 19 "data/maps/SlateportCity/scripts.pory"
	.string "{PLAYER} received the EFFORT RIBBON.$"

SlateportCity_Text_PutEffortRibbonOnMon::
# 23 "data/maps/SlateportCity/scripts.pory"
	.string "{PLAYER} put the EFFORT RIBBON on\n"
	.string "{STR_VAR_1}.$"

SlateportCity_Text_GoForItLittleHarder::
# 27 "data/maps/SlateportCity/scripts.pory"
	.string "You have to go for it a little harder.\p"
	.string "If you do, I'll give your POKMON\n"
	.string "something nice.$"

SlateportCity_Text_EffortRibbonLooksGoodOnIt::
# 31 "data/maps/SlateportCity/scripts.pory"
	.string "Oh! Your {STR_VAR_1}, that EFFORT\n"
	.string "RIBBON looks good on it!$"

SlateportCity_Text_WonderIfLighthouseStartlesPokemon::
# 35 "data/maps/SlateportCity/scripts.pory"
	.string "The light of the lighthouse reaches\n"
	.string "dozens of miles away.\p"
	.string "I wonder if it doesn't startle POKMON in\n"
	.string "the sea.$"

SlateportCity_Text_SeaweedFullOfLife::
# 39 "data/maps/SlateportCity/scripts.pory"
	.string "Ooh, look at this!\p"
	.string "The seaweed you can get around these\n"
	.string "parts is fresh and full of life.\p"
	.string "Why, it looks like it can even rear up\n"
	.string "and attack!$"

SlateportCity_Text_HowTownIsBornAndGrows::
# 43 "data/maps/SlateportCity/scripts.pory"
	.string "Where the water is clean, the fruits of\n"
	.string "bountiful harvest gather.\p"
	.string "And where people gather, a market soon\n"
	.string "starts.\p"
	.string "That is how a town is born and grows.$"

SlateportCity_Text_SlateportWonderfulPlace::
# 47 "data/maps/SlateportCity/scripts.pory"
	.string "Shopping where you can breathe the\n"
	.string "scent of the ocean\p"
	.string "SLATEPORT is such a wonderful place!$"

SlateportCity_Text_BuyBricksSoDecorWontGetDirty::
# 51 "data/maps/SlateportCity/scripts.pory"
	.string "If you put DOLLS or CUSHIONS on the\n"
	.string "floor, they'll get dirty.\p"
	.string "I'm going to buy some BRICKS so my\n"
	.string "DOLLS and CUSHIONS won't get dirty\l"
	.string "when I leave them out.$"

SlateportCity_Text_GoingToCompeteInBattleTent::
# 55 "data/maps/SlateportCity/scripts.pory"
	.string "Wroooar! I'm going to compete in the\n"
	.string "BATTLE TENT, too!\p"
	.string "But before that, I need to catch some\n"
	.string "POKMON!$"

SlateportCity_Text_BushedHikingFromMauville::
# 59 "data/maps/SlateportCity/scripts.pory"
	.string "Whew I'm just bushed\p"
	.string "I hiked over from MAUVILLE CITY. But,\n"
	.string "boy, this city's huge.\p"
	.string "If I'd known this, I would've ridden my\n"
	.string "BIKE here.$"

SlateportCity_Text_EveryoneCallsHimCaptStern::
# 63 "data/maps/SlateportCity/scripts.pory"
	.string "STERN, the fellow who built the MUSEUM,\n"
	.string "also happens to be the leader\l"
	.string "of an undersea exploration team.\p"
	.string "So, everyone calls him CAPT. STERN.$"

SlateportCity_Text_WhatsLongLineOverThere::
# 67 "data/maps/SlateportCity/scripts.pory"
	.string "What is that over there? That long line$"

SlateportCity_Text_VisitedMuseumOften::
# 71 "data/maps/SlateportCity/scripts.pory"
	.string "When I was a child, I visited the MUSEUM\n"
	.string "often.\p"
	.string "I used to dream about the mysteries of\n"
	.string "the sea after seeing the exhibits.$"

SlateportCity_Text_QuitPushing::
# 75 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, there! Quit pushing! This is the\n"
	.string "line, can't you see?$"

SlateportCity_Text_AquaHasPolicy::
# 79 "data/maps/SlateportCity/scripts.pory"
	.string "TEAM AQUA has a policy of assembling\n"
	.string "and dispersing at\l"
	.string "the operation site.$"

SlateportCity_Text_BossIsBrilliant::
# 83 "data/maps/SlateportCity/scripts.pory"
	.string "Our BOSS is brilliant.\p"
	.string "What would he want to do with a MUSEUM\n"
	.string "now?$"

SlateportCity_Text_WhatsNewSchemeIWonder::
# 87 "data/maps/SlateportCity/scripts.pory"
	.string "What's the new scheme, I wonder?\p"
	.string "Our BOSS is scary when he's mad, so I'd\n"
	.string "better not screw things up$"

SlateportCity_Text_ShouldTakeItAll::
# 91 "data/maps/SlateportCity/scripts.pory"
	.string "If there's something we need in the\n"
	.string "MUSEUM, we should take it all!$"

SlateportCity_Text_DontButtIn::
# 95 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, you there! Don't butt in!$"

SlateportCity_Text_RemindsMeOfLongLineForGames::
# 99 "data/maps/SlateportCity/scripts.pory"
	.string "A long line, huh?\p"
	.string "It reminds me of the times I lined up to\n"
	.string "buy smash-hit games$"

SlateportCity_Text_WhyAreWeLiningUp::
# 103 "data/maps/SlateportCity/scripts.pory"
	.string "Why are we even lining up and paying? We\n"
	.string "should just march in!$"

SlateportCity_Text_WhatDoYouWant::
# 107 "data/maps/SlateportCity/scripts.pory"
	.string "What? What do you want?$"

SlateportCity_Text_IllReadSignForYou::
# 111 "data/maps/SlateportCity/scripts.pory"
	.string "You want to read this sign? I'll read it\n"
	.string "for you!$"

SlateportCity_Text_SaysSomethingLikeSeaIsEndless::
# 115 "data/maps/SlateportCity/scripts.pory"
	.string "Let's see\p"
	.string "Um I think it says something like the\n"
	.string "life in the sea is endless.\p"
	.string "Yup, I'm pretty sure that's what it\n"
	.string "says.$"

SlateportCity_Text_ShouldveBroughtMyGameBoy::
# 119 "data/maps/SlateportCity/scripts.pory"
	.string "Grumble\p"
	.string "I should've brought my Game Boy\n"
	.string "Advance so I wouldn't get bored in line\p"
	.string "Grumble$"

SlateportCity_Text_HotSpringsAfterOperation::
# 123 "data/maps/SlateportCity/scripts.pory"
	.string "When this operation's over, I'll take\n"
	.string "you to a hot spring spa!\p"
	.string "That's what our leader said. I can't\n"
	.string "wait!$"

SlateportCity_Text_SeaIsSoWet::
# 127 "data/maps/SlateportCity/scripts.pory"
	.string "The sea is just so vast\p"
	.string "Could the sea have been made by the\n"
	.string "tears shed by POKMON?$"

SlateportCity_Text_SinkOldBoats::
# 131 "data/maps/SlateportCity/scripts.pory"
	.string "Do you know what they do with old ships\n"
	.string "that become too creaky to sail?\p"
	.string "They sink them in the sea so they\n"
	.string "become habitats for POKMON.$"

SlateportCity_Text_BuyTooMuch::
# 135 "data/maps/SlateportCity/scripts.pory"
	.string "Whenever I visit here, I get carried\n"
	.string "away and buy too much.$"

SlateportCity_Text_GetNameRaterToHelpYou::
# 139 "data/maps/SlateportCity/scripts.pory"
	.string "If you want to change your POKMON's\n"
	.string "nickname, you'll have to get the NAME\l"
	.string "RATER to help you.$"

SlateportCity_Text_CantChangeTradeMonName::
# 143 "data/maps/SlateportCity/scripts.pory"
	.string "Any POKMON you get in a trade, you can't\n"
	.string "change its nickname.\p"
	.string "The original TRAINER's love for that\n"
	.string "POKMON is in the nickname.$"

SlateportCity_Text_BattleTentBuiltRecently::
# 147 "data/maps/SlateportCity/scripts.pory"
	.string "Recently, a BATTLE TENT was built in\n"
	.string "SLATEPORT.\p"
	.string "GYMS are fun, but the BATTLE TENT's\n"
	.string "awesome in its own way.\p"
	.string "You should go find tough POKMON for the\n"
	.string "BATTLE TENT!$"

SlateportCity_Text_CaptSternBeingInterviewed::
# 151 "data/maps/SlateportCity/scripts.pory"
	.string "I was hoping that it was a famous star\n"
	.string "so I could get an autograph.\p"
	.string "But who's that being interviewed? Isn't\n"
	.string "that CAPT. STERN?$"

SlateportCity_Text_InterviewerSoCool::
# 155 "data/maps/SlateportCity/scripts.pory"
	.string "That lady interviewer is so cool and\n"
	.string "pretty.\p"
	.string "When I grow up, I'm going to be an\n"
	.string "international journalist!$"

SlateportCity_Text_SternSaysDiscoveredSomething::
# 159 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN says they discovered\n"
	.string "something at the bottom of the sea.\p"
	.string "I wonder what it is? What could it be?$"

SlateportCity_Text_CaptainComeBackWithBigFish::
# 163 "data/maps/SlateportCity/scripts.pory"
	.string "What's going on here?\p"
	.string "Did the good CAPTAIN come back with a\n"
	.string "big fish from the ocean floor?$"

SlateportCity_Text_AmIOnTV::
# 167 "data/maps/SlateportCity/scripts.pory"
	.string "Hey! Are you watching? Am I on TV?$"

SlateportCity_Text_CaptainsACelebrity::
# 171 "data/maps/SlateportCity/scripts.pory"
	.string "A TV interview! Here! The CAPTAIN's a\n"
	.string "celebrity!$"

SlateportCity_Text_BigSmileForCamera::
# 175 "data/maps/SlateportCity/scripts.pory"
	.string "TY: Okay, CAPT. STERN, a big smile for\n"
	.string "the camera!$"

SlateportCity_Text_MostInvaluableExperience::
# 179 "data/maps/SlateportCity/scripts.pory"
	.string "GABBY: I see, I see. You've had a most\n"
	.string "invaluable experience$"

SlateportCity_Text_SternMoveAheadWithExploration::
# 183 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN: Yes, indeed. We intend to\n"
	.string "move ahead with our exploration.$"

SlateportCity_Text_GabbyWonderfulThanksForInterview::
# 187 "data/maps/SlateportCity/scripts.pory"
	.string "GABBY: That's wonderful, CAPT. STERN!\n"
	.string "Thank you for taking the time from\l"
	.string "your busy schedule to talk to us.\p"
	.string "We hope we can interview you again with\n"
	.string "news of more discoveries!$"

SlateportCity_Text_SternWhewFirstInterview::
# 191 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN: Whew\p"
	.string "That was my first time to be filmed for\n"
	.string "TV. That was nerve-wracking.$"

SlateportCity_Text_OhPlayerWeMadeDiscovery::
# 195 "data/maps/SlateportCity/scripts.pory"
	.string "Oh! {PLAYER}{KUN}! You're looking great!\p"
	.string "We made a huge discovery on our last\n"
	.string "seafloor exploration.\p"
	.string "We found an underwater cavern on ROUTE\n"
	.string "128.\p"
	.string "We think it's the habitat of a POKMON\n"
	.string "that's said to have been long extinct.$"

SlateportCity_Text_AquaWillAssumeControlOfSubmarine::
# 199 "data/maps/SlateportCity/scripts.pory"
	.string "Fufufu CAPT. STERN, I presume.\p"
	.string "We of TEAM AQUA will assume control of\n"
	.string "your submarine!\p"
	.string "Your objections are meaningless! We\n"
	.string "expect your total cooperation!\p"
	.string "Fufufu Just watch and learn what TEAM\l"
	.string "AQUA has planned!$"

SlateportCity_Text_SternWhatWasAllThat::
# 203 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN: What was that all about?\p"
	.string "It sounded like someone using a\n"
	.string "megaphone\p"
	.string "Where did it come from?$"

SlateportCity_Text_FromHarborTryingToTakeSub::
# 207 "data/maps/SlateportCity/scripts.pory"
	.string "It's from the HARBOR!\p"
	.string "The submarine! They're trying to take\n"
	.string "it!$"

SlateportCity_Text_PleaseComeWithMe::
# 211 "data/maps/SlateportCity/scripts.pory"
	.string "{PLAYER}{KUN}! Please, come with me!$"

SlateportCity_Text_BattleTentSign::
# 215 "data/maps/SlateportCity/scripts.pory"
	.string "BATTLE TENT SLATEPORT SITE Find it!\n"
	.string "The ultimate POKMON!$"

SlateportCity_Text_SternsShipyardWantedSign::
# 219 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "Wanted: A sailor capable of sailing in\n"
	.string "all currents.$"

SlateportCity_Text_SternsShipyardNearsCompletion::
# 223 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "The ferry S.S. TIDAL nears completion\n"
	.string "for serving the ports of\l"
	.string "SLATEPORT and LILYCOVE.$"

SlateportCity_Text_SternsShipyardFerryComplete::
# 227 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "Boarding of the SLATEPORT-LILYCOVE\n"
	.string "ferry S.S. TIDAL is handled at the\l"
	.string "HARBOR.$"

SlateportCity_Text_PokemonFanClubSign::
# 231 "data/maps/SlateportCity/scripts.pory"
	.string "POKMON FAN CLUB Calling all fans of\n"
	.string "POKMON!$"

SlateportCity_Text_OceanicMuseumSign::
# 235 "data/maps/SlateportCity/scripts.pory"
	.string "The endless sea sustains all life.\p"
	.string "OCEANIC MUSEUM$"

SlateportCity_Text_CitySign::
# 239 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT CITY\p"
	.string "The port where people and POKMON cross\n"
	.string "paths.$"

SlateportCity_Text_MarketSign::
# 243 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT MARKET Unique items found\n"
	.string "nowhere else!$"

SlateportCity_Text_HarborFerryUnderConstruction::
# 247 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT HARBOR\p"
	.string "The ferry S.S. TIDAL is under\n"
	.string "construction in the SHIPYARD.\p"
	.string "Service is scheduled to begin shortly.$"

SlateportCity_Text_HarborSign::
# 251 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT HARBOR\p"
	.string "Enjoy a delightful cruise on the ferry\n"
	.string "S.S. TIDAL.$"

SlateportCity_Text_NameRatersHouseSign::
# 255 "data/maps/SlateportCity/scripts.pory"
	.string "NAME RATER'S HOUSE POKMON nicknames\n"
	.string "rated.$"

SlateportCity_Text_ExplainBerries::
# 259 "data/maps/SlateportCity/scripts.pory"
	.string "If a wild POKMON gets hurt, it heals\n"
	.string "itself by chewing on BERRIES.\p"
	.string "Did you know that?\p"
	.string "Somebody saw that and got the idea of\n"
	.string "making medicine from BERRIES.\p"
	.string "Did you know that?\p"
	.string "To turn BERRIES into medicine, they\n"
	.string "must be crushed into powder.\p"
	.string "Did you know that?\p"
	.string "You seem to have an interest in\n"
	.string "BERRIES!\p"
	.string "I've got something good for someone\n"
	.string "like you.$"

SlateportCity_Text_ExplainBerryPowder::
# 263 "data/maps/SlateportCity/scripts.pory"
	.string "I recently had machines installed at\n"
	.string "POKMON CENTERS for crushing BERRIES.\p"
	.string "The BERRY CRUSH machines are at the\n"
	.string "DIRECT CORNER upstairs.\p"
	.string "Did you know?\p"
	.string "Could you make BERRY POWDER for me\n"
	.string "using those machines?\p"
	.string "I can make you all sorts of medicine if\n"
	.string "you bring me lots of BERRY POWDER.$"

SlateportCity_Text_BroughtMeSomeBerryPowder::
# 267 "data/maps/SlateportCity/scripts.pory"
	.string "Have you brought me some BERRY\n"
	.string "POWDER?$"

SlateportCity_Text_ExchangeWhatWithIt::
# 271 "data/maps/SlateportCity/scripts.pory"
	.string "What would you like to exchange it\n"
	.string "with?$"

SlateportCity_Text_ExchangeBerryPowderForItem::
# 275 "data/maps/SlateportCity/scripts.pory"
	.string "Okay, you want to exchange your BERRY\n"
	.string "POWDER for one {STR_VAR_1}?$"

SlateportCity_Text_DontHaveEnoughBerryPowder::
# 279 "data/maps/SlateportCity/scripts.pory"
	.string "Oh, dear. You don't have enough BERRY\n"
	.string "POWDER.$"

SlateportCity_Text_FineBerryPowderTradeSomethingElse::
# 283 "data/maps/SlateportCity/scripts.pory"
	.string "This is fine BERRY POWDER. It will make\n"
	.string "excellent medicine.\p"
	.string "Would you like to trade more of your\n"
	.string "BERRY POWDER for something else?$"

SlateportCity_Text_WhenYouGetMoreBringItToMe::
# 287 "data/maps/SlateportCity/scripts.pory"
	.string "Okay! When you get some more BERRY\n"
	.string "POWDER, bring it to me, please!$"

SlateportCity_Text_ComeBackToTradeBerryPowder::
# 291 "data/maps/SlateportCity/scripts.pory"
	.string "Come back if you'd like to trade your\n"
	.string "BERRY POWDER for some medicine.\p"
	.string "I'm always running a bazaar here.\p"
	.string "Did you know?$"

SlateportCity_Text_YouDroveTeamAquaAway::
# 295 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: Huh? I'm sure I met you\n"
	.string "somewhere before.\p"
	.string "Have I introduced myself to you? If\n"
	.string "not, my name's SCOTT.\p"
	.string "I just saw TEAM AQUA run away from here\n"
	.string "like they were stung.\p"
	.string "Let me guess--you drove them away?$"

SlateportCity_Text_MaybeThisTrainer::
# 299 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: Hmm Maybe, just maybe, this\n"
	.string "TRAINER$"

SlateportCity_Text_LetsRegisterEachOther::
# 303 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: All right! I think you're going to\n"
	.string "become a good friend.\p"
	.string "So, let's register each other in our\n"
	.string "POKNAVS.\p"
	.string "$"

SlateportCity_Text_RegisteredScott::
# 307 "data/maps/SlateportCity/scripts.pory"
	.string "Registered this SCOTT person in the\n"
	.string "POKNAV.$"

SlateportCity_Text_KeepEyeOnTrainersBeSeeingYou::
# 311 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: What I'd like to do is tag along\n"
	.string "with you, but I do want to keep an eye\l"
	.string "on the talents of other people, too.\p"
	.string "So, I'll be off to roam other towns a bit\n"
	.string "more.\p"
	.string "Be seeing you, {PLAYER}{KUN}!$"

SlateportCity_Text_TakingBattleTentChallenge::
# 315 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: Oh, hey! If it isn't {PLAYER}{KUN}!\p"
	.string "{PLAYER}{KUN}, let me guess--you're going\n"
	.string "to take the BATTLE TENT challenge?\p"
	.string "Yeah! That's a good idea! That's a really\n"
	.string "great idea!\p"
	.string "After all, a tough TRAINER is the\n"
	.string "perfect fit for the BATTLE TENT!\p"
	.string "Give it your best effort!$"
