SlateportCity_MapScripts::
	.byte 0


SlateportCity_EventScript_AquaGrunt1::
# 5 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_QuitPushing, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt10::
# 10 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ShouldveBroughtMyGameBoy, MSGBOX_SIGN
	end


SlateportCity_EventScript_AquaGrunt11::
# 15 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HotSpringsAfterOperation, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt2::
# 20 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_AquaHasPolicy, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt3::
# 25 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BossIsBrilliant, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt4::
# 30 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhatsNewSchemeIWonder, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt5::
# 35 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_ShouldTakeItAll, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt6::
# 40 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_DontButtIn, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt7::
# 45 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_RemindsMeOfLongLineForGames, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt8::
# 50 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhyAreWeLiningUp, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_AquaGrunt9::
# 55 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WhatDoYouWant, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_BattleTentSign::
# 60 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BattleTentSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_BerryCrushRankingsSign::
	end


SlateportCity_EventScript_BerryPowderClerk::
	end


SlateportCity_EventScript_CaptStern::
# 77 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternMoveAheadWithExploration, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_CitySign::
# 82 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_CitySign, MSGBOX_SIGN
	end


SlateportCity_EventScript_Cook::
	end


SlateportCity_EventScript_DecorClerk::
	end


SlateportCity_EventScript_DollClerk::
	end


SlateportCity_EventScript_EffortRibbonWoman::
# 99 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_OhYourPokemon, MSGBOX_DEFAULT
	end


SlateportCity_EventScript_EnergyGuru::
	end


SlateportCity_EventScript_FatMan::
	end


SlateportCity_EventScript_Gabby::
# 112 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_MostInvaluableExperience, MSGBOX_SIGN
	end


SlateportCity_EventScript_Girl::
	end


SlateportCity_EventScript_HarborSign::
# 123 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_HarborFerryUnderConstruction, MSGBOX_SIGN
	end


SlateportCity_EventScript_Man1::
	end


SlateportCity_EventScript_Man2::
# 133 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BattleTentBuiltRecently, MSGBOX_NPC
	end


SlateportCity_EventScript_Man3::
# 138 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_WonderIfLighthouseStartlesPokemon, MSGBOX_NPC
	end


SlateportCity_EventScript_Maniac::
	end


SlateportCity_EventScript_MarketSign::
# 147 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_MarketSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_NameRatersHouseSign::
# 152 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_NameRatersHouseSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_OceanicMuseumSign::
# 157 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_OceanicMuseumSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_OldWoman::
	end


SlateportCity_EventScript_PokefanF::
# 166 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BuyTooMuch, MSGBOX_NPC
	end


SlateportCity_EventScript_PokemonFanClubSign::
# 171 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_PokemonFanClubSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_PowerTMClerk::
	end


SlateportCity_EventScript_RichBoy::
	end


SlateportCity_EventScript_Sailor1::
# 184 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SeaIsSoWet, MSGBOX_NPC
	end


SlateportCity_EventScript_Sailor2::
# 189 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SinkOldBoats, MSGBOX_NPC
	end


SlateportCity_EventScript_ScottBattleTentScene::
	end


SlateportCity_EventScript_SternsShipyardSign::
# 201 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_SternsShipyardWantedSign, MSGBOX_SIGN
	end


SlateportCity_EventScript_Ty::
# 207 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_BigSmileForCamera, MSGBOX_SIGN
	end


SlateportCity_EventScript_Woman1::
	end


SlateportCity_EventScript_Woman2::
# 216 "data/maps/SlateportCity/scripts.pory"
	msgbox SlateportCity_Text_CantChangeTradeMonName, MSGBOX_NPC
	end


SlateportCity_Text_SternsShipyardWantedSign::
# 221 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "“Wanted: A sailor capable of sailing in\n"
	.string "all currents.”$"

SlateportCity_Text_MarketSign::
# 225 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT MARKET “Unique items found\n"
	.string "nowhere else!”$"

SlateportCity_Text_HarborFerryUnderConstruction::
# 229 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT HARBOR\p"
	.string "“The ferry S.S. TIDAL is under\n"
	.string "construction in the SHIPYARD.\p"
	.string "“Service is scheduled to begin\n"
	.string "shortly.”$"

SlateportCity_Text_NameRatersHouseSign::
# 233 "data/maps/SlateportCity/scripts.pory"
	.string "NAME RATER'S HOUSE “POKéMON nicknames\n"
	.string "rated.”$"

SlateportCity_Text_OceanicMuseumSign::
# 237 "data/maps/SlateportCity/scripts.pory"
	.string "“The endless sea sustains all life.”\p"
	.string "OCEANIC MUSEUM$"

SlateportCity_Text_BattleTentSign::
# 241 "data/maps/SlateportCity/scripts.pory"
	.string "BATTLE TENT SLATEPORT SITE “Find it!\n"
	.string "The ultimate POKéMON!”$"

SlateportCity_Text_PokemonFanClubSign::
# 245 "data/maps/SlateportCity/scripts.pory"
	.string "POKéMON FAN CLUB “Calling all fans of\n"
	.string "POKéMON!”$"

SlateportCity_Text_CitySign::
# 249 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT CITY\p"
	.string "“The port where people and POKéMON\n"
	.string "cross paths.”$"

SlateportCity_Text_InterviewerSoCool::
# 253 "data/maps/SlateportCity/scripts.pory"
	.string "That lady interviewer is so cool\n"
	.string "and pretty.\p"
	.string "When I grow up, I'm going to be\n"
	.string "an international journalist!$"

SlateportCity_Text_WhyAreWeLiningUp::
# 257 "data/maps/SlateportCity/scripts.pory"
	.string "Why are we even lining up and paying?\n"
	.string "We should just march in!$"

SlateportCity_Text_HotSpringsAfterOperation::
# 261 "data/maps/SlateportCity/scripts.pory"
	.string "When this operation's over, I'll take\n"
	.string "you to a hot spring spa!\p"
	.string "That's what our leader said.\n"
	.string "I can't wait!$"

SlateportCity_Text_ComeBackToTradeBerryPowder::
# 265 "data/maps/SlateportCity/scripts.pory"
	.string "Come back if you'd like to trade your\n"
	.string "BERRY POWDER for some medicine.\p"
	.string "I'm always running a bazaar here.\p"
	.string "Did you know?$"

SlateportCity_Text_SternsShipyardNearsCompletion::
# 269 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "“The ferry S.S. TIDAL nears\n"
	.string "completion for serving the ports of\l"
	.string "SLATEPORT and LILYCOVE.”$"

SlateportCity_Text_BuyTooMuch::
# 273 "data/maps/SlateportCity/scripts.pory"
	.string "Whenever I visit here, I get carried\n"
	.string "away and buy too much.$"

SlateportCity_Text_BuyBricksSoDecorWontGetDirty::
# 277 "data/maps/SlateportCity/scripts.pory"
	.string "If you put DOLLS or CUSHIONS on\n"
	.string "the floor, they'll get dirty.\p"
	.string "I'm going to buy some BRICKS so my\n"
	.string "DOLLS and CUSHIONS won't get dirty\l"
	.string "when I leave them out.$"

SlateportCity_Text_MostInvaluableExperience::
# 281 "data/maps/SlateportCity/scripts.pory"
	.string "GABBY: I see, I see. You've had a most\n"
	.string "invaluable experience…$"

SlateportCity_Text_OhYourPokemon::
# 285 "data/maps/SlateportCity/scripts.pory"
	.string "Oh?\n"
	.string "Your {STR_VAR_1}…$"

SlateportCity_Text_DontHaveEnoughBerryPowder::
# 289 "data/maps/SlateportCity/scripts.pory"
	.string "Oh, dear. You don't have enough\n"
	.string "BERRY POWDER.$"

SlateportCity_Text_BigSmileForCamera::
# 293 "data/maps/SlateportCity/scripts.pory"
	.string "TY: Okay, CAPT. STERN, a big smile\n"
	.string "for the camera!$"

SlateportCity_Text_HarborSign::
# 297 "data/maps/SlateportCity/scripts.pory"
	.string "SLATEPORT HARBOR\p"
	.string "“Enjoy a delightful cruise on\n"
	.string "the ferry S.S. TIDAL.”$"

SlateportCity_Text_SeaIsSoWet::
# 301 "data/maps/SlateportCity/scripts.pory"
	.string "The sea is just so vast…\p"
	.string "Could the sea have been made by\n"
	.string "the tears shed by POKéMON?$"

SlateportCity_Text_AquaHasPolicy::
# 305 "data/maps/SlateportCity/scripts.pory"
	.string "TEAM AQUA has a policy of\n"
	.string "assembling and dispersing at\l"
	.string "the operation site.$"

SlateportCity_Text_EffortRibbonLooksGoodOnIt::
# 309 "data/maps/SlateportCity/scripts.pory"
	.string "Oh! Your {STR_VAR_1}, that EFFORT\n"
	.string "RIBBON looks good on it!$"

SlateportCity_Text_GoForItLittleHarder::
# 313 "data/maps/SlateportCity/scripts.pory"
	.string "You have to go for it a little harder.\p"
	.string "If you do, I'll give your POKéMON\n"
	.string "something nice.$"

SlateportCity_Text_SinkOldBoats::
# 317 "data/maps/SlateportCity/scripts.pory"
	.string "Do you know what they do with old\n"
	.string "ships that become too creaky to sail?\p"
	.string "They sink them in the sea so they\n"
	.string "become habitats for POKéMON.$"

SlateportCity_Text_ExchangeBerryPowderForItem::
# 321 "data/maps/SlateportCity/scripts.pory"
	.string "Okay, you want to exchange your\n"
	.string "BERRY POWDER for one {STR_VAR_1}?$"

SlateportCity_Text_BossIsBrilliant::
# 325 "data/maps/SlateportCity/scripts.pory"
	.string "Our BOSS is brilliant.\p"
	.string "What would he want to do with\n"
	.string "a MUSEUM now?$"

SlateportCity_Text_CaptSternBeingInterviewed::
# 329 "data/maps/SlateportCity/scripts.pory"
	.string "I was hoping that it was a famous star\n"
	.string "so I could get an autograph.\p"
	.string "But who's that being interviewed?\n"
	.string "Isn't that CAPT. STERN?$"

SlateportCity_Text_CantChangeTradeMonName::
# 333 "data/maps/SlateportCity/scripts.pory"
	.string "Any POKéMON you get in a trade,\n"
	.string "you can't change its nickname.\p"
	.string "The original TRAINER's love for that\n"
	.string "POKéMON is in the nickname.$"

SlateportCity_Text_ShouldveBroughtMyGameBoy::
# 337 "data/maps/SlateportCity/scripts.pory"
	.string "Grumble…\p"
	.string "I should've brought my Game Boy\n"
	.string "Advance so I wouldn't get bored in line…\p"
	.string "Grumble…$"

SlateportCity_Text_DontButtIn::
# 341 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, you there!\n"
	.string "Don't butt in!$"

SlateportCity_Text_QuitPushing::
# 345 "data/maps/SlateportCity/scripts.pory"
	.string "Hey, there! Quit pushing!\n"
	.string "This is the line, can't you see?$"

SlateportCity_Text_CaptainsACelebrity::
# 349 "data/maps/SlateportCity/scripts.pory"
	.string "A TV interview! Here!\n"
	.string "The CAPTAIN's a celebrity!$"

SlateportCity_Text_ShouldTakeItAll::
# 353 "data/maps/SlateportCity/scripts.pory"
	.string "If there's something we need in\n"
	.string "the MUSEUM, we should take it all!$"

SlateportCity_Text_RemindsMeOfLongLineForGames::
# 357 "data/maps/SlateportCity/scripts.pory"
	.string "A long line, huh?\p"
	.string "It reminds me of the times I lined up to\n"
	.string "buy smash-hit games…$"

SlateportCity_Text_WhatDoYouWant::
# 361 "data/maps/SlateportCity/scripts.pory"
	.string "What?\n"
	.string "What do you want?$"

SlateportCity_Text_VisitedMuseumOften::
# 365 "data/maps/SlateportCity/scripts.pory"
	.string "When I was a child, I visited\n"
	.string "the MUSEUM often.\p"
	.string "I used to dream about the mysteries of\n"
	.string "the sea after seeing the exhibits.$"

SlateportCity_Text_AmIOnTV::
# 369 "data/maps/SlateportCity/scripts.pory"
	.string "Hey! Are you watching?\n"
	.string "Am I on TV?$"

SlateportCity_Text_GetNameRaterToHelpYou::
# 373 "data/maps/SlateportCity/scripts.pory"
	.string "If you want to change your POKéMON's\n"
	.string "nickname, you'll have to get the NAME\l"
	.string "RATER to help you.$"

SlateportCity_Text_WonderIfLighthouseStartlesPokemon::
# 377 "data/maps/SlateportCity/scripts.pory"
	.string "The light of the lighthouse reaches\n"
	.string "dozens of miles away.\p"
	.string "I wonder if it doesn't startle POKéMON\n"
	.string "in the sea.$"

SlateportCity_Text_YouDroveTeamAquaAway::
# 381 "data/maps/SlateportCity/scripts.pory"
	.string "SCOTT: Huh?\n"
	.string "I'm sure I met you somewhere before.\p"
	.string "Have I introduced myself to you?\n"
	.string "If not, my name's SCOTT.\p"
	.string "I just saw TEAM AQUA run away from\n"
	.string "here like they were stung.\p"
	.string "Let me guess--you drove them away?$"

SlateportCity_Text_SternMoveAheadWithExploration::
# 385 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN: Yes, indeed. We intend to\n"
	.string "move ahead with our exploration.$"

SlateportCity_Text_SternsShipyardFerryComplete::
# 389 "data/maps/SlateportCity/scripts.pory"
	.string "STERN'S SHIPYARD\p"
	.string "“Boarding of the SLATEPORT-LILYCOVE\n"
	.string "ferry S.S. TIDAL is handled at the\l"
	.string "HARBOR.”$"

SlateportCity_Text_CaptainComeBackWithBigFish::
# 393 "data/maps/SlateportCity/scripts.pory"
	.string "What's going on here?\p"
	.string "Did the good CAPTAIN come back with\n"
	.string "a big fish from the ocean floor?$"

SlateportCity_Text_BattleTentBuiltRecently::
# 397 "data/maps/SlateportCity/scripts.pory"
	.string "Recently, a BATTLE TENT was built\n"
	.string "in SLATEPORT.\p"
	.string "GYMS are fun, but the BATTLE TENT's\n"
	.string "awesome in its own way.\p"
	.string "You should go find tough POKéMON\n"
	.string "for the BATTLE TENT!$"

SlateportCity_Text_WhatsNewSchemeIWonder::
# 401 "data/maps/SlateportCity/scripts.pory"
	.string "What's the new scheme, I wonder?\p"
	.string "Our BOSS is scary when he's mad, so\n"
	.string "I'd better not screw things up…$"

SlateportCity_Text_ExplainBerryPowder::
# 405 "data/maps/SlateportCity/scripts.pory"
	.string "I recently had machines installed at\n"
	.string "POKéMON CENTERS for crushing BERRIES.\p"
	.string "The BERRY CRUSH machines are at\n"
	.string "the DIRECT CORNER upstairs.\p"
	.string "Did you know?\p"
	.string "Could you make BERRY POWDER for\n"
	.string "me using those machines?\p"
	.string "I can make you all sorts of medicine\n"
	.string "if you bring me lots of BERRY POWDER.$"

SlateportCity_Text_SternSaysDiscoveredSomething::
# 409 "data/maps/SlateportCity/scripts.pory"
	.string "CAPT. STERN says they discovered\n"
	.string "something at the bottom of the sea.\p"
	.string "I wonder what it is?\n"
	.string "What could it be?$"
