OlivineCity_Cafe_MapScripts::
	.byte 0


OlivineCity_Cafe_EventScript_SmithNPC1::
# 5 "data/maps/OlivineCity_Cafe/scripts.pory"
	msgbox OlivineCity_Cafe_Text_SmithNPC1, MSGBOX_NPC
	end


OlivineCity_Cafe_EventScript_SmithNPC2::
# 14 "data/maps/OlivineCity_Cafe/scripts.pory"
	msgbox OlivineCity_Cafe_Text_SmithNPC2, MSGBOX_NPC
	end


OlivineCity_Cafe_EventScript_SmithNPC3::
# 23 "data/maps/OlivineCity_Cafe/scripts.pory"
	msgbox OlivineCity_Cafe_Text_SmithNPC3, MSGBOX_NPC
	end


OlivineCity_Cafe_Text_SmithNPC1::
# 9 "data/maps/OlivineCity_Cafe/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OlivineCity_Cafe_Text_SmithNPC2::
# 18 "data/maps/OlivineCity_Cafe/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

OlivineCity_Cafe_Text_SmithNPC3::
# 27 "data/maps/OlivineCity_Cafe/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
