SaffronCity_Dojo_MapScripts::
	.byte 0


SaffronCity_Dojo_Text_MasterKoichiIntro::
# 5 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Grunt!\p"
	.string "I am the KARATE MASTER! I am the LEADER\n"
	.string "here!\p"
	.string "You wish to challenge us? Expect no\n"
	.string "mercy!\p"
	.string "Fwaaa!$"

SaffronCity_Dojo_Text_MasterKoichiDefeat::
# 9 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Hwa! Arrgh! Beaten!$"

SaffronCity_Dojo_Text_ChoosePrizedFightingMon::
# 13 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Indeed, I have lost!\p"
	.string "But, I beseech you, do not take our\n"
	.string "emblem as your trophy!\p"
	.string "In return, I will give you a prized\n"
	.string "FIGHTING POKéMON!\p"
	.string "Choose whichever one you like!$"

SaffronCity_Dojo_Text_StayAndTrainWithUs::
# 17 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Grunt! Stay and train at karate with us!$"

SaffronCity_Dojo_Text_MikeIntro::
# 21 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Hoargh! Take your shoes off!$"

SaffronCity_Dojo_Text_MikeDefeat::
# 25 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "I give up!$"

SaffronCity_Dojo_Text_MikePostBattle::
# 29 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "You wait 'til you see our MASTER! I'm a\n"
	.string "small fry compared to him!$"

SaffronCity_Dojo_Text_HidekiIntro::
# 33 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "I hear you're good! Show me!$"

SaffronCity_Dojo_Text_HidekiDefeat::
# 37 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Judge! One point!$"

SaffronCity_Dojo_Text_HidekiPostBattle::
# 41 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Our MASTER is a pro fighter. Be prepared\n"
	.string "to lose!$"

SaffronCity_Dojo_Text_AaronIntro::
# 45 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Hiyah! I have no fear for anything\n"
	.string "tough!\p"
	.string "I shatter boulders for training every\n"
	.string "day!$"

SaffronCity_Dojo_Text_AaronDefeat::
# 49 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Yow! Stubbed fingers!$"

SaffronCity_Dojo_Text_AaronPostBattle::
# 53 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "The only thing that frightens us is\n"
	.string "psychic power!$"

SaffronCity_Dojo_Text_HitoshiIntro::
# 57 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Hwaah!\p"
	.string "You're trespassing in our FIGHTING\n"
	.string "DOJO!$"

SaffronCity_Dojo_Text_HitoshiDefeat::
# 61 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Oof! I give up!$"

SaffronCity_Dojo_Text_HitoshiPostBattle::
# 65 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "The prime fighters across the land\n"
	.string "train here.$"

SaffronCity_Dojo_Text_YouWantHitmonlee::
# 69 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "You want the hard-kicking HITMONLEE?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster::
# 73 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "{PLAYER} received the {STR_VAR_1}\n"
	.string "from the KARATE MASTER.$"

SaffronCity_Dojo_Text_YouWantHitmonchan::
# 77 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "You want the piston-punching\n"
	.string "HITMONCHAN?$"

SaffronCity_Dojo_Text_ReceivedMonFromKarateMaster2::
# 81 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "{PLAYER}は　カラテ　だいおう　から {STR_VAR_1}を　もらった！$"

SaffronCity_Dojo_Text_BetterNotGetGreedy::
# 85 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Better not get greedy…$"

SaffronCity_Dojo_Text_EnemiesOnEverySide::
# 89 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "Enemies on every side!$"

SaffronCity_Dojo_Text_GoesAroundComesAround::
# 93 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "What goes around comes around.$"

SaffronCity_Dojo_Text_FightingDojo::
# 97 "data/maps/SaffronCity_Dojo/scripts.pory"
	.string "FIGHTING DOJO$"
