RuinsOfAlph_InnerChamber_MapScripts::
	.byte 0


RuinsOfAlph_InnerChamber_EventScript_SmithNPC1::
# 5 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC1, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC2::
# 14 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC2, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC3::
# 23 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC3, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC4::
# 32 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC4, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC5::
# 41 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC5, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC6::
# 50 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC6, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC7::
# 59 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC7, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC8::
# 68 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC8, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_EventScript_SmithNPC9::
# 77 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	msgbox RuinsOfAlph_InnerChamber_Text_SmithNPC9, MSGBOX_NPC
	end


RuinsOfAlph_InnerChamber_Text_SmithNPC1::
# 9 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC2::
# 18 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC3::
# 27 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC4::
# 36 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC5::
# 45 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC6::
# 54 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "It's the question that drives us, Neo.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC7::
# 63 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC8::
# 72 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "I know kung fu.$"

RuinsOfAlph_InnerChamber_Text_SmithNPC9::
# 81 "data/maps/RuinsOfAlph_InnerChamber/scripts.pory"
	.string "Dodge this.$"
