SolaceonTown_MapScripts::
	.byte 0


SolaceonTown_EventScript_Sign1::
# 6 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_Sign1, MSGBOX_SIGN
	end


SolaceonTown_EventScript_Sign2::
# 15 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_Sign2, MSGBOX_SIGN
	end


SolaceonTown_EventScript_SmithNPC1::
# 24 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_SmithNPC1, MSGBOX_NPC
	end


SolaceonTown_EventScript_SmithNPC2::
# 33 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_SmithNPC2, MSGBOX_NPC
	end


SolaceonTown_EventScript_SmithNPC3::
# 42 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_SmithNPC3, MSGBOX_NPC
	end


SolaceonTown_EventScript_SmithNPC4::
# 51 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_SmithNPC4, MSGBOX_NPC
	end


SolaceonTown_EventScript_SmithNPC5::
# 60 "data/maps/SolaceonTown/scripts.pory"
	msgbox SolaceonTown_Text_SmithNPC5, MSGBOX_NPC
	end


SolaceonTown_Text_Sign1::
# 10 "data/maps/SolaceonTown/scripts.pory"
	.string "SolaceonTown Sign 1$"

SolaceonTown_Text_Sign2::
# 19 "data/maps/SolaceonTown/scripts.pory"
	.string "SolaceonTown Sign 2$"

SolaceonTown_Text_SmithNPC1::
# 28 "data/maps/SolaceonTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SolaceonTown_Text_SmithNPC2::
# 37 "data/maps/SolaceonTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SolaceonTown_Text_SmithNPC3::
# 46 "data/maps/SolaceonTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

SolaceonTown_Text_SmithNPC4::
# 55 "data/maps/SolaceonTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

SolaceonTown_Text_SmithNPC5::
# 64 "data/maps/SolaceonTown/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"
