@ NOTE: The brailleformat macro in this file is leftover from RS.
@       The numbers are simply skipped over. If you'd like to omit
@       this macro you must also stop it from skipping over this
@       section by editing ScrCmd_braillemessage.
Underwater_SealedChamber_Braille_GoUpHere:
	brailleformat 4, 6, 26, 13, 7, 9
	.braille "GO UP HERE.$"

SealedChamber_OuterRoom_Braille_ABC:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "ABC$"

SealedChamber_OuterRoom_Braille_GHI:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "GHI$"

SealedChamber_OuterRoom_Braille_MNO:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "MNO$"

SealedChamber_OuterRoom_Braille_TUV:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "TUV$"

SealedChamber_OuterRoom_Braille_DEF:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "DEF$"

SealedChamber_OuterRoom_Braille_JKL:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "JKL$"

SealedChamber_OuterRoom_Braille_PQRS:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "PQRS$"

SealedChamber_OuterRoom_Braille_Period:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ".$"

SealedChamber_OuterRoom_Braille_WXYZ:
	brailleformat 7, 6, 21, 13, 10, 9
	.braille "WXYZ$"

SealedChamber_OuterRoom_Braille_Comma:
	brailleformat 9, 6, 19, 13, 12, 9
	.braille ",$"

SealedChamber_OuterRoom_Braille_DigHere:
	brailleformat 7, 4, 23, 15, 10, 7
	.braille "DIG HERE.$"

SealedChamber_InnerRoom_Braille_FirstWailordLastRelicanth:
	brailleformat 0, 0, 29, 19, 3, 3
	.braille "FIRST COMES\n"
	.braille "WAILORD.\n"
	.braille "LAST COMES\n"
	.braille "RELICANTH.$"

SealedChamber_InnerRoom_Braille_InThisCaveWeHaveLived:
	brailleformat 2, 0, 26, 19, 5, 3
	.braille "IN THIS\n"
	.braille "CAVE WE\n"
	.braille "HAVE\n"
	.braille "LIVED.$"

SealedChamber_InnerRoom_Braille_WeOweAllToThePokemon:
	brailleformat 7, 2, 23, 17, 10, 5
	.braille "WE OWE ALL\n"
	.braille "TO THE\n"
	.braille "POKEMON.$"

SealedChamber_InnerRoom_Braille_ButWeSealedThePokemonAway:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "BUT, WE\n"
	.braille "SEALED THE\n"
	.braille "POKEMON\n"
	.braille "AWAY.$"

SealedChamber_InnerRoom_Braille_WeFearedIt:
	brailleformat 5, 6, 25, 13, 8, 9
	.braille "WE FEARED IT.$"

SealedChamber_InnerRoom_Braille_ThoseWithCourageHope:
	brailleformat 6, 0, 24, 19, 9, 3
	.braille "THOSE WITH\n"
	.braille "COURAGE,\n"
	.braille "THOSE WITH\n"
	.braille "HOPE.$"

SealedChamber_InnerRoom_Braille_OpenDoorEternalPokemonWaits:
	brailleformat 3, 2, 27, 17, 6, 5
	.braille "OPEN A DOOR.\n"
	.braille "AN ETERNAL\n"
	.braille "POKEMON\n"
	.braille "WAITS.$"

DesertRuins_Braille_UseRockSmash:
	brailleformat 1, 0, 27, 19, 4, 3
	.braille "LEFT, LEFT,\n"
	.braille "DOWN, DOWN.\n"
	.braille "THEN, USE\n"
	.braille "ROCK SMASH.$"

IslandCave_Braille_RunLapAroundWall:
	brailleformat 5, 0, 25, 19, 8, 3
	.braille "STAY CLOSE\n"
	.braille "TO THE WALL.\n"
	.braille "RUN AROUND\n"
	.braille "ONE LAP.$"

AncientTomb_Braille_ShineInTheMiddle:
	brailleformat 3, 0, 25, 19, 6, 3
	.braille "THOSE WHO\n"
	.braille "INHERIT OUR\n"
	.braille "WILL, SHINE\n"
	.braille "IN THE MIDDLE.$"

	.global Braille_Text_Everything
	Braille_Text_Everything:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "EVERYTHING$"

	.global Braille_Text_HasMeaning1
	Braille_Text_HasMeaning1:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "HAS MEANING$"

	.global Braille_Text_Existence
	Braille_Text_Existence:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "EXISTENCE$"

	.global Braille_Text_HasMeaning2
	Braille_Text_HasMeaning2:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "HAS MEANING$"

	.global Braille_Text_BeingAlive
	Braille_Text_BeingAlive:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "BEING ALIVE$"

	.global Braille_Text_HasMeaning3
	Braille_Text_HasMeaning3:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "HAS MEANING$"

	.global Braille_Text_HaveDreams
	Braille_Text_HaveDreams:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "HAVE DREAMS$"

	.global Braille_Text_UsePower
	Braille_Text_UsePower:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "USE POWER$"

	.global Braille_Text_Up
	Braille_Text_Up:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "UP$"

	.global Braille_Text_Left
	Braille_Text_Left:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "LEFT$"

	.global Braille_Text_Right
	Braille_Text_Right:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "RIGHT$"

	.global Braille_Text_Down
	Braille_Text_Down:
		brailleformat 4, 6, 26, 13, 7, 9
		.braille "DOWN$"

	.global Braille_Text_LetTheTwo
	Braille_Text_LetTheTwo:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "LET THE TWO$"

	.global Braille_Text_Glittering
	Braille_Text_Glittering:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "GLITTERING$"

	.global Braille_Text_Stones
	Braille_Text_Stones:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "STONES$"

	.global Braille_Text_OneInRed
	Braille_Text_OneInRed:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "ONE IN RED$"

	.global Braille_Text_OneInBlue
	Braille_Text_OneInBlue:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "ONE IN BLUE$"

	.global Braille_Text_ConnectThe
	Braille_Text_ConnectThe:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "CONNECT THE$"

	.global Braille_Text_Past
	Braille_Text_Past:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "PAST$"

	.global Braille_Text_TwoFriends
	Braille_Text_TwoFriends:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "TWO FRIENDS$"

	.global Braille_Text_Sharing
	Braille_Text_Sharing:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "SHARING$"

	.global Braille_Text_PowerOpen
	Braille_Text_PowerOpen:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "POWER OPEN$"

	.global Braille_Text_AWindowTo
	Braille_Text_AWindowTo:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "A WINDOW TO$"

	.global Braille_Text_ANewWorld
	Braille_Text_ANewWorld:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "A NEW WORLD$"

	.global Braille_Text_ThatGlows
	Braille_Text_ThatGlows:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "THAT GLOWS$"

	.global Braille_Text_TheNext
	Braille_Text_TheNext:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "THE NEXT$"

	.global Braille_Text_WorldWaits
	Braille_Text_WorldWaits:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "WORLD WAITS$"

	.global Braille_Text_ForYou
	Braille_Text_ForYou:
		brailleformat 0, 0, 29, 19, 3, 3
		.braille "FOR YOU$"
