Route102_MapScripts::
	.byte 0


Route102_MapScripts::
	return


Route102_Text_WatchMeCatchPokemon::
# 8 "data/maps/Route102/scripts.pory"
	.string "WALLY: {PLAYER}… POKéMON hide in tall\n"
	.string "grass like this,\l"
	.string "don't they?\p"
	.string "Please watch me and see if I can catch\n"
	.string "one properly.\p"
	.string "…Whoa!$"

Route102_Text_WallyIDidIt::
# 12 "data/maps/Route102/scripts.pory"
	.string "WALLY: I did it… It's my… My POKéMON!$"

Route102_Text_LetsGoBack::
# 16 "data/maps/Route102/scripts.pory"
	.string "{PLAYER}, thank you! Let's go back to\n"
	.string "the GYM!$"

Route102_Text_ImNotVeryTall::
# 20 "data/maps/Route102/scripts.pory"
	.string "I'm…not very tall, so I sink right into\n"
	.string "tall grass.\p"
	.string "The grass goes up my nose and…\n"
	.string "Fwafwafwafwafwa…\p"
	.string "Fwatchoo!$"

Route102_Text_CatchWholeBunchOfPokemon::
# 24 "data/maps/Route102/scripts.pory"
	.string "I'm going to catch a whole bunch of\n"
	.string "POKéMON!$"

Route102_Text_RouteSignOldale::
# 28 "data/maps/Route102/scripts.pory"
	.string "ROUTE 102 {RIGHT_ARROW} OLDALE TOWN$"

Route102_Text_RouteSignPetalburg::
# 32 "data/maps/Route102/scripts.pory"
	.string "ROUTE 102 {LEFT_ARROW} PETALBURG CITY$"
