SevenIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/SevenIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/SevenIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


SevenIsland_PokemonCenter_1F_Text_EventsDependingOnConnections::
# 7 "data/maps/SevenIsland_PokemonCenter_1F/scripts.pory"
	.string "On this island, different events occur\n"
	.string "depending on connections.\p"
	.string "What are those connections?\p"
	.string "They are for you to discover on your\n"
	.string "own.$"

SevenIsland_PokemonCenter_1F_Text_DidYouRideSeagallopHere::
# 11 "data/maps/SevenIsland_PokemonCenter_1F/scripts.pory"
	.string "Did you ride a SEAGALLOP ferry to get\n"
	.string "here?\p"
	.string "There are at least ten of those\n"
	.string "high-speed ships.\p"
	.string "I don't know where they all go, though.$"

SevenIsland_PokemonCenter_1F_Text_CheckOutTrainerTower::
# 15 "data/maps/SevenIsland_PokemonCenter_1F/scripts.pory"
	.string "If you're confident, you should check\n"
	.string "out TRAINER TOWER.$"
