Route105_MapScripts::
# 2 "data/maps/Route105/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route105_OnLoad
# 3 "data/maps/Route105/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route105_OnTransition
# 4 "data/maps/Route105/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route105_OnFrame
	.byte 0


Route104_Text_DadPokenavCall::
# 8 "data/maps/Route105/scripts.pory"
	.string "… … … … … … … … … … … Beep!\p"
	.string "DAD: Oh, {PLAYER}?\p"
	.string "… … … … … … Where are you now?\l"
	.string "It sounds windy wherever you are.\p"
	.string "I just heard from DEVON's MR. STONE\n"
	.string "about your POKéNAV, so I decided\l"
	.string "to give you a call.\p"
	.string "It sounds like you're doing fine, so\n"
	.string "that's fine with me.\p"
	.string "You take care now.\p"
	.string "… … … … … … … … … … … Click!$"

Route104_Text_RegisteredDadInPokenav::
# 12 "data/maps/Route105/scripts.pory"
	.string "Registered DAD NORMAN in the POKéNAV.$"
