EverGrandeCity_SidneysRoom_MapScripts::
	.byte 0


EverGrandeCity_SidneysRoom_EventScript_Sidney::
	end


EverGrandeCity_SidneysRoom_Text_PostBattleSpeech::
# 8 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	.string "Well, listen to what this loser has\n"
	.string "to say.\p"
	.string "You've got what it takes to go far.\n"
	.string "Now, go on to the next room and enjoy\l"
	.string "your next battle!$"
