EverGrandeCity_SidneysRoom_MapScripts::
# 2 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, EverGrandeCity_SidneysRoom_OnLoad
# 3 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, EverGrandeCity_SidneysRoom_OnWarp
# 4 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_SidneysRoom_OnTransition
# 5 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, EverGrandeCity_SidneysRoom_OnFrame
	.byte 0


EverGrandeCity_SidneysRoom_Text_IntroSpeech::
# 9 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	.string "Welcome, challenger! I'm SIDNEY of the\n"
	.string "ELITE FOUR.\p"
	.string "I like that look you're giving me. I\n"
	.string "guess you'll give me a good match.\l"
	.string "That's good! Looking real good!\p"
	.string "All right! You and me, let's enjoy a\n"
	.string "battle that can only be staged\l"
	.string "here in the POKMON LEAGUE!$"

EverGrandeCity_SidneysRoom_Text_Defeat::
# 13 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	.string "Well, how do you like that? I lost! Eh, it\n"
	.string "was fun, so it doesn't matter.$"

EverGrandeCity_SidneysRoom_Text_PostBattleSpeech::
# 17 "data/maps/EverGrandeCity_SidneysRoom/scripts.pory"
	.string "Well, listen to what this loser has to\n"
	.string "say.\p"
	.string "You've got what it takes to go far. Now,\n"
	.string "go on to the next room and enjoy\l"
	.string "your next battle!$"
