SevenIsland_SevaultCanyon_MapScripts::
	.byte 0


SevenIsland_SevaultCanyon_Text_CyndyIntro::
# 5 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "My conditioning's in top form!$"

SevenIsland_SevaultCanyon_Text_CyndyDefeat::
# 9 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Huh? Something's not right$"

SevenIsland_SevaultCanyon_Text_CyndyPostBattle::
# 13 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "The way I am now, I may have to hold off\n"
	.string "on TRAINER TOWER$"

SevenIsland_SevaultCanyon_Text_EvanIntro::
# 17 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "It doesn't matter if you happen to have\n"
	.string "the strongest POKMON\p"
	.string "It doesn't mean a thing if you don't\n"
	.string "know how to use them properly!$"

SevenIsland_SevaultCanyon_Text_EvanDefeat::
# 21 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "You're a master at this.$"

SevenIsland_SevaultCanyon_Text_EvanPostBattle::
# 25 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "You see them every so often, TRAINERS\n"
	.string "with awesome POKMON\l"
	.string "who have no idea what to do.\p"
	.string "Before training POKMON, TRAINERS\n"
	.string "themselves need to grow up.$"

SevenIsland_SevaultCanyon_Text_JacksonIntro::
# 29 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "I work to protect the environment. In\n"
	.string "turn, nature protects me!$"

SevenIsland_SevaultCanyon_Text_JacksonDefeat::
# 33 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Whoa! You're tough! How about\n"
	.string "protecting me?$"

SevenIsland_SevaultCanyon_Text_JacksonPostBattle::
# 37 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "From far out among the stars, our\n"
	.string "planet is just a drop of water.\p"
	.string "But we want to protect that drop of\n"
	.string "water for everyone.$"

SevenIsland_SevaultCanyon_Text_KatelynIntro::
# 41 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Those shoes you have are pretty\n"
	.string "snazzy.$"

SevenIsland_SevaultCanyon_Text_KatelynDefeat::
# 45 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "You're hot stuff in spite of your cute\n"
	.string "looks.$"

SevenIsland_SevaultCanyon_Text_KatelynPostBattle::
# 49 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Your mom bought those snazzy RUNNING\n"
	.string "SHOES for you?\p"
	.string "She must adore you.$"

SevenIsland_SevaultCanyon_Text_LeroyIntro::
# 53 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "You look strong. Let me battle you,\n"
	.string "please!$"

SevenIsland_SevaultCanyon_Text_LeroyDefeat::
# 57 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "I knew it! You're as tough as I thought!$"

SevenIsland_SevaultCanyon_Text_LeroyPostBattle::
# 61 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "The way you battle has given me a lot of\n"
	.string "useful data.\p"
	.string "Thanks so much!$"

SevenIsland_SevaultCanyon_Text_MichelleIntro::
# 65 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "I was given the best possible education\n"
	.string "to become this strong.\p"
	.string "I don't want to lose to anyone!$"

SevenIsland_SevaultCanyon_Text_MichelleDefeat::
# 69 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Thank you. I feel like I've been set\n"
	.string "free by losing to you.$"

SevenIsland_SevaultCanyon_Text_MichellePostBattle::
# 73 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "For some reason, I get furious over the\n"
	.string "slightest thing.\p"
	.string "I'll calm myself by breathing deeply.$"

SevenIsland_SevaultCanyon_Text_LexIntro::
# 77 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "LEX: My darling NYA, together we could\n"
	.string "win!$"

SevenIsland_SevaultCanyon_Text_LexDefeat::
# 81 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "LEX: I seem to have been too careless$"

SevenIsland_SevaultCanyon_Text_LexPostBattle::
# 85 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "LEX: I think it was a good experience\n"
	.string "for NYA.\p"
	.string "You have my gratitude.$"

SevenIsland_SevaultCanyon_Text_LexNotEnoughMons::
# 89 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "LEX: May I ask you to battle the both\n"
	.string "of us at the same time?$"

SevenIsland_SevaultCanyon_Text_NyaIntro::
# 93 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "NYA: I'll do my best so I won't drag down\n"
	.string "my mentor, LEX!$"

SevenIsland_SevaultCanyon_Text_NyaDefeat::
# 97 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "NYA: Oh, no I'm so sorry, I$"

SevenIsland_SevaultCanyon_Text_NyaPostBattle::
# 101 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "NYA: I think I'm going to need much more\n"
	.string "seasoning and tutoring\l"
	.string "under LEX\p"
	.string "So, LEX, please, may I stay with you like\n"
	.string "this?$"

SevenIsland_SevaultCanyon_Text_NyaNotEnoughMons::
# 105 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "NYA: I'm sorry, but may we battle in\n"
	.string "two-on-two style?$"

SevenIsland_SevaultCanyon_Text_RouteSign::
# 109 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "SEVAULT CANYON TANOBY RUINS AHEAD$"

SevenIsland_SevaultCanyon_Text_BrunoTrainedWithBrawly::
# 113 "data/maps/SevenIsland_SevaultCanyon/scripts.pory"
	.string "Training by oneself is certainly not a\n"
	.string "bad thing.\p"
	.string "But it's also not bad to aim for the top\n"
	.string "with a partner.\p"
	.string "Even BRUNO He trained with a fellow by\n"
	.string "the\l"
	.string "name of BRAWLY before.$"
