OneIsland_MapScripts::
# 2 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OneIsland_OnTransition
# 3 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_OnFrame
	.byte 0


OneIsland_Text_BillLetsGoSeeCelio::
# 7 "data/maps/OneIsland/scripts.pory"
	.string "BILL: Here we are! This is ONE ISLAND.\p"
	.string "There are several islands around here,\n"
	.string "and this is one of them.\p"
	.string "My friend CELIO sent the boat to fetch\n"
	.string "me here.\p"
	.string "He's in charge of the island's PC\n"
	.string "network by his lonesome.\p"
	.string "Why am I telling you this now? Let's\n"
	.string "just go see CELIO!$"

Text_WhereDoYouWantToSail::
# 11 "data/maps/OneIsland/scripts.pory"
	.string "Ahoy, there! Where do you want to sail?$"

OneIsland_Text_LuckyToHaveCelioHere::
# 15 "data/maps/OneIsland/scripts.pory"
	.string "Here we are on an island smack in the\n"
	.string "middle of nowhere.\p"
	.string "We're lucky to have an upstanding young\n"
	.string "man like CELIO here.\p"
	.string "My granddaughter was in a tizzy over\n"
	.string "CELIO's friend.\p"
	.string "Something about a famous POKMANIAC?\p"
	.string "I'm not sure what that means, but CELIO\n"
	.string "is quite the man!$"

OneIsland_Text_HavePCLinkageWithKanto::
# 19 "data/maps/OneIsland/scripts.pory"
	.string "My granddaughter was in a tizzy over a\n"
	.string "new breakthrough.\p"
	.string "She said we now have PC linkage with\n"
	.string "people in KANTO.\p"
	.string "I'm not sure what that means, but CELIO\n"
	.string "is quite the man!$"

OneIsland_Text_HavePCLinkageWithHoenn::
# 23 "data/maps/OneIsland/scripts.pory"
	.string "My granddaughter was in a tizzy over a\n"
	.string "new breakthrough.\p"
	.string "She said we finally have PC linkage with\n"
	.string "people in HOENN.\p"
	.string "I'm not sure what that means, but CELIO\n"
	.string "is quite the man.\p"
	.string "He would make a fine husband for my\n"
	.string "granddaughter!$"

OneIsland_Text_IslandSign::
# 27 "data/maps/OneIsland/scripts.pory"
	.string "ONE ISLAND Friends Gather at Knot\n"
	.string "Island$"

OneIsland_Text_PokemonNetCenterSign::
# 31 "data/maps/OneIsland/scripts.pory"
	.string "Expanding the POKMON World! POKMON NET\n"
	.string "CENTER$"

OneIsland_Text_ReturnToCinnabar::
# 35 "data/maps/OneIsland/scripts.pory"
	.string "$"

OneIsland_Text_IsntWarmClimateHereGreat::
# 39 "data/maps/OneIsland/scripts.pory"
	.string "Hi, sight-seeing, are you? Isn't the\n"
	.string "warm climate here great?$"
