OneIsland_MapScripts::
# 2 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OneIsland_OnTransition
# 3 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_OnFrame
	.byte 0


OneIsland_MapScripts::
# 7 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OneIsland_OnTransition
# 8 "data/maps/OneIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_OnFrame
	return

