Route34_PokemonDayCare_MapScripts::
	.byte 0


Route34_PokemonDayCare_EventScript_SmithNPC1::
# 5 "data/maps/Route34_PokemonDayCare/scripts.pory"
	msgbox Route34_PokemonDayCare_Text_SmithNPC1, MSGBOX_NPC
	end


Route34_PokemonDayCare_EventScript_SmithNPC2::
# 14 "data/maps/Route34_PokemonDayCare/scripts.pory"
	msgbox Route34_PokemonDayCare_Text_SmithNPC2, MSGBOX_NPC
	end


Route34_PokemonDayCare_EventScript_SmithNPC3::
# 23 "data/maps/Route34_PokemonDayCare/scripts.pory"
	msgbox Route34_PokemonDayCare_Text_SmithNPC3, MSGBOX_NPC
	end


Route34_PokemonDayCare_EventScript_SmithNPC4::
# 32 "data/maps/Route34_PokemonDayCare/scripts.pory"
	msgbox Route34_PokemonDayCare_Text_SmithNPC4, MSGBOX_NPC
	end


Route34_PokemonDayCare_Text_SmithNPC1::
# 9 "data/maps/Route34_PokemonDayCare/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route34_PokemonDayCare_Text_SmithNPC2::
# 18 "data/maps/Route34_PokemonDayCare/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route34_PokemonDayCare_Text_SmithNPC3::
# 27 "data/maps/Route34_PokemonDayCare/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

Route34_PokemonDayCare_Text_SmithNPC4::
# 36 "data/maps/Route34_PokemonDayCare/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
