SlateportCity_NameRatersHouse_MapScripts::
	.byte 0


SlateportCity_NameRatersHouse_EventScript_NameRater::
# 5 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	msgbox SlateportCity_NameRatersHouse_Text_PleasedToRateMonNickname, MSGBOX_YESNO
	end


SlateportCity_NameRatersHouse_Text_PleasedToRateMonNickname::
# 9 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Hi, hi! I'm the NAME RATER!\n"
	.string "I'm the fortune-teller of names!\p"
	.string "I shall be pleased to rate your\n"
	.string "POKéMON's nickname.$"

SlateportCity_NameRatersHouse_Text_MagnificentName::
# 13 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Hmmm… {STR_VAR_1} it is!\p"
	.string "This is a magnificent nickname!\n"
	.string "It is impeccably beyond reproach!\p"
	.string "You'll do well to cherish your\n"
	.string "{STR_VAR_1} now and beyond.$"

SlateportCity_NameRatersHouse_Text_DoVisitAgain::
# 17 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "I see.\n"
	.string "Do come visit again.$"

SlateportCity_NameRatersHouse_Text_ThatIsMerelyAnEgg::
# 21 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Now, now.\n"
	.string "That is merely an EGG!$"

SlateportCity_NameRatersHouse_Text_WhatShallNewNameBe::
# 25 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Ah, good. Then, what shall the new\n"
	.string "nickname be?$"

SlateportCity_NameRatersHouse_Text_CritiqueWhichMonNickname::
# 29 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Which POKéMON's nickname should\n"
	.string "I critique?$"

SlateportCity_NameRatersHouse_Text_MonShallBeKnownAsName::
# 33 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Done! From now on, this POKéMON\n"
	.string "shall be known as {STR_VAR_1}!\p"
	.string "It is a better name than before!\n"
	.string "How fortunate for you!$"
