SlateportCity_NameRatersHouse_MapScripts::
	.byte 0


SlateportCity_NameRatersHouse_Text_PleasedToRateMonNickname::
# 5 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Hi, hi! I'm the NAME RATER! I'm the\n"
	.string "fortune-teller of names!\p"
	.string "I shall be pleased to rate your POKMON's\n"
	.string "nickname.$"

SlateportCity_NameRatersHouse_Text_CritiqueWhichMonNickname::
# 9 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Which POKMON's nickname should I\n"
	.string "critique?$"

SlateportCity_NameRatersHouse_Text_FineNameSuggestBetterOne::
# 13 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Hmmm {STR_VAR_1}, is it? That is\n"
	.string "quite a fine name you bestowed.\p"
	.string "But! What say you, if I were to suggest\n"
	.string "a slightly better name?$"

SlateportCity_NameRatersHouse_Text_WhatShallNewNameBe::
# 17 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Ah, good. Then, what shall the new\n"
	.string "nickname be?$"

SlateportCity_NameRatersHouse_Text_MonShallBeKnownAsName::
# 21 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Done! From now on, this POKMON shall be\n"
	.string "known as {STR_VAR_1}!\p"
	.string "It is a better name than before! How\n"
	.string "fortunate for you!$"

SlateportCity_NameRatersHouse_Text_DoVisitAgain::
# 25 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "I see. Do come visit again.$"

SlateportCity_NameRatersHouse_Text_NameNoDifferentYetSuperior::
# 29 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Done! From now on, this POKMON shall be\n"
	.string "known as {STR_VAR_1}!\p"
	.string "It looks no different from before, and\n"
	.string "yet, this is vastly superior!\p"
	.string "How fortunate for you!$"

SlateportCity_NameRatersHouse_Text_MagnificentName::
# 33 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Hmmm {STR_VAR_1} it is!\p"
	.string "This is a magnificent nickname! It is\n"
	.string "impeccably beyond reproach!\p"
	.string "You'll do well to cherish your\n"
	.string "{STR_VAR_1} now and beyond.$"

SlateportCity_NameRatersHouse_Text_ThatIsMerelyAnEgg::
# 37 "data/maps/SlateportCity_NameRatersHouse/scripts.pory"
	.string "Now, now. That is merely an EGG!$"
