VerdanturfTown_House_MapScripts::
	.byte 0


VerdanturfTown_House_EventScript_Woman1::
# 5 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
	end


VerdanturfTown_House_EventScript_Woman2::
# 10 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
	end


VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague::
# 14 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Far away, deep in EVER GRANDE CITY,\n"
	.string "is the POKéMON LEAGUE.\p"
	.string "The TRAINERS who gather there are\n"
	.string "all frighteningly well skilled.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow::
# 18 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "In the POKéMON LEAGUE, I think the\n"
	.string "rules say that you have to battle the\l"
	.string "ELITE FOUR all in a row.\p"
	.string "If you lose to any of them, you have\n"
	.string "to begin your challenge again from the\l"
	.string "first one.$"
