VerdanturfTown_House_MapScripts::
	.byte 0


VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague::
# 5 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Far away, deep in EVER GRANDE CITY, is\n"
	.string "the POKéMON LEAGUE.\p"
	.string "The TRAINERS who gather there are all\n"
	.string "frighteningly well skilled.$"

VerdanturfTown_House_Text_DefeatEliteFourInARow::
# 9 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "In the POKéMON LEAGUE, I think the\n"
	.string "rules say that you have to battle the\l"
	.string "ELITE FOUR all in a row.\p"
	.string "If you lose to any of them, you have to\n"
	.string "begin your challenge again from the\l"
	.string "first one.$"
