MtPyre_1F_MapScripts::
	.byte 0


MtPyre_1F_EventScript_CleanseTagWoman::
	end


MtPyre_1F_EventScript_Man::
# 9 "data/maps/MtPyre_1F/scripts.pory"
	msgbox MtPyre_1F_Text_RestingPlaceOfZigzagoon, MSGBOX_NPC
	end


MtPyre_1F_EventScript_PokefanF::
# 14 "data/maps/MtPyre_1F/scripts.pory"
	msgbox MtPyre_1F_Text_ComeToPayRespects, MSGBOX_NPC
	end


MtPyre_1F_Text_ExplainCleanseTag::
# 18 "data/maps/MtPyre_1F/scripts.pory"
	.string "Have a POKéMON hold that\n"
	.string "CLEANSE TAG.\p"
	.string "It will help ward off wild POKéMON.$"

MtPyre_1F_Text_ComeToPayRespects::
# 22 "data/maps/MtPyre_1F/scripts.pory"
	.string "Did you come to pay your respect\n"
	.string "to the spirits of departed POKéMON?\p"
	.string "You must care for your POKéMON a lot.$"

MtPyre_1F_Text_RestingPlaceOfZigzagoon::
# 26 "data/maps/MtPyre_1F/scripts.pory"
	.string "This is the final resting place of my\n"
	.string "ZIGZAGOON. I cherished it…$"
