MtPyre_1F_MapScripts::
	.byte 0


MtPyre_1F_Text_TakeThisForYourOwnGood::
# 5 "data/maps/MtPyre_1F/scripts.pory"
	.string "All sorts of beings wander the slopes\n"
	.string "of MT. PYRE\p"
	.string "There is no telling what may happen.\n"
	.string "Take this. It's for your own good.$"

MtPyre_1F_Text_ExplainCleanseTag::
# 9 "data/maps/MtPyre_1F/scripts.pory"
	.string "Have a POKMON hold that CLEANSE TAG.\p"
	.string "It will help ward off wild POKMON.$"

MtPyre_1F_Text_ComeToPayRespects::
# 13 "data/maps/MtPyre_1F/scripts.pory"
	.string "Did you come to pay your respect to the\n"
	.string "spirits of departed POKMON?\p"
	.string "You must care for your POKMON a lot.$"

MtPyre_1F_Text_RestingPlaceOfZigzagoon::
# 17 "data/maps/MtPyre_1F/scripts.pory"
	.string "This is the final resting place of my\n"
	.string "ZIGZAGOON. I cherished it$"
