BattleFrontier_Lounge2_MapScripts::
	.byte 0


BattleFrontier_Lounge2_Text_FrontierManiacIntro::
# 5 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Howdy! When it comes to news about the\n"
	.string "BATTLE FRONTIER, I'm no. 1.\p"
	.string "You can think of me as the FRONTIER\n"
	.string "MANIAC.\p"
	.string "Just checking, but you are a TRAINER,\n"
	.string "isn't that right?\p"
	.string "I'll happily share the hottest news I\n"
	.string "gathered about the BATTLE FRONTIER.$"

BattleFrontier_Lounge2_Text_SwingByForTheLatestWord::
# 9 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Howdy! Did you swing by to grill me\n"
	.string "about the latest word? Oh, all right!$"

BattleFrontier_Lounge2_Text_MyInformationsBeenUsefulRight::
# 13 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Well? Well? Well?\p"
	.string "I'm sure my information's been seriously\n"
	.string "useful to you, right?$"

BattleFrontier_Lounge2_Text_FacilityIsHottest::
# 17 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Let's see now\p"
	.string "It sounds like the {STR_VAR_1} is\n"
	.string "the hottest place going.$"

BattleFrontier_Lounge2_Text_BattleTowerIsHottest::
# 21 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Let's see now\p"
	.string "It sounds like BATTLE TOWER\n"
	.string "{STR_VAR_1} is the hottest.$"

BattleFrontier_Lounge2_Text_SalonMaidenIsThere::
# 25 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this mysterious TRAINER called the\n"
	.string "SALON MAIDEN that runs the place.$"

BattleFrontier_Lounge2_Text_SalonMaidenSilverMons::
# 29 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the SALON MAIDEN?\p"
	.string "When she's measuring up her opponent,\n"
	.string "she apparently uses these POKMON:\p"
	.string "A PSYCHIC-type PSI POKMON, a\n"
	.string "FIRE-type VOLCANO POKMON,\l"
	.string "and a NORMAL-type SLEEPING POKMON.$"

BattleFrontier_Lounge2_Text_SalonMaidenGoldMons::
# 33 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the SALON MAIDEN when\n"
	.string "she's serious?\p"
	.string "When she's battling flat out, she\n"
	.string "apparently uses these POKMON:\p"
	.string "A DRAGON & PSYCHIC EON POKMON, an\n"
	.string "ELECTRIC-type THUNDER POKMON,\l"
	.string "and a NORMAL-type SLEEPING POKMON.$"

BattleFrontier_Lounge2_Text_DomeAceIsThere::
# 37 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this flamboyant TRAINER called the\n"
	.string "DOME ACE that runs the place.$"

BattleFrontier_Lounge2_Text_DomeAceSilverMons::
# 41 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the DOME ACE?\p"
	.string "When he's treating the opponent\n"
	.string "lightly, he uses these three POKMON:\p"
	.string "A DRAGON & FLYING DRAGON POKMON, a\n"
	.string "WATER & GROUND MUD FISH POKMON,\l"
	.string "and a FIRE & FLYING FLAME POKMON.$"

BattleFrontier_Lounge2_Text_DomeAceGoldMons::
# 45 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the DOME ACE when he's\n"
	.string "serious?\p"
	.string "When he's demonstrating his strategy,\n"
	.string "he uses these three POKMON:\p"
	.string "A DRAGON & FLYING EON POKMON, a WATER\n"
	.string "& GROUND MUD FISH POKMON,\l"
	.string "and a STEEL- & PSYCHIC-type IRON LEG\l"
	.string "POKMON.$"

BattleFrontier_Lounge2_Text_FactoryHeadIsThere::
# 49 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this freaky TRAINER called the\n"
	.string "FACTORY HEAD that runs the place.$"

BattleFrontier_Lounge2_Text_FactoryHeadSilverMons::
# 53 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the FACTORY HEAD\n"
	.string "already?\p"
	.string "Let me think When he goes to battle, he\n"
	.string "just gets three rental POKMON.\p"
	.string "He battles under pretty much the same\n"
	.string "conditions as you.$"

BattleFrontier_Lounge2_Text_FactoryHeadGoldMons::
# 57 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the FACTORY HEAD when\n"
	.string "he's serious?\p"
	.string "When he goes seriously to battle, he\n"
	.string "still gets three rental POKMON.\p"
	.string "He battles under virtually the same\n"
	.string "conditions as you.$"

BattleFrontier_Lounge2_Text_PikeQueenIsThere::
# 61 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this scary TRAINER called the PIKE\n"
	.string "QUEEN that runs the place.$"

BattleFrontier_Lounge2_Text_PikeQueenSilverMons::
# 65 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PIKE QUEEN\n"
	.string "before?\p"
	.string "When she's in a good mood, they say she\n"
	.string "uses these three POKMON:\p"
	.string "A POISON-type FANG SNAKE POKMON, a BUG\n"
	.string "& ROCK MOLD POKMON,\l"
	.string "and a WATER-type TENDER POKMON.$"

BattleFrontier_Lounge2_Text_PikeQueenGoldMons::
# 69 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PIKE QUEEN when\n"
	.string "she's serious?\p"
	.string "When she's seriously annoyed, they say\n"
	.string "she uses these three POKMON:\p"
	.string "A POISON-type FANG SNAKE POKMON, a\n"
	.string "STEEL & GROUND IRON SNAKE POKMON,\l"
	.string "and a WATER- & FLYING-type ATROCIOUS\l"
	.string "POKMON.$"

BattleFrontier_Lounge2_Text_ArenaTycoonIsThere::
# 73 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this cute TRAINER called the ARENA\n"
	.string "TYCOON that runs the place.$"

BattleFrontier_Lounge2_Text_ArenaTycoonSilverMons::
# 77 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the ARENA TYCOON\n"
	.string "before?\p"
	.string "When she's assessing the foe's ability,\n"
	.string "she supposedly uses these POKMON:\p"
	.string "A BUG & FIGHTING SINGLE HORN POKMON, a\n"
	.string "DARK-type MOONLIGHT POKMON,\l"
	.string "and a BUG & GHOST SHED POKMON.$"

BattleFrontier_Lounge2_Text_ArenaTycoonGoldMons::
# 81 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the ARENA TYCOON when\n"
	.string "she's serious?\p"
	.string "When she battles for keeps, she\n"
	.string "supposedly uses these POKMON:\p"
	.string "A DARK-type MOONLIGHT POKMON, a GHOST\n"
	.string "& POISON SHADOW POKMON\l"
	.string "and a GRASS- & FIGHTING-type\l"
	.string "MUSHROOM POKMON.$"

BattleFrontier_Lounge2_Text_PalaceMavenIsThere::
# 85 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this sinister TRAINER called the\n"
	.string "PALACE MAVEN that runs the place.$"

BattleFrontier_Lounge2_Text_PalaceMavenSilverMons::
# 89 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PALACE MAVEN\n"
	.string "before?\p"
	.string "When he's testing the opponent's\n"
	.string "spirit, he's said to use these POKMON:\p"
	.string "A POISON & FLYING-type BAT POKMON, a\n"
	.string "NORMAL-type LAZY POKMON, and a\l"
	.string "WATER- & ICE-type TRANSPORT POKMON.$"

BattleFrontier_Lounge2_Text_PalaceMavenGoldMons::
# 93 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PALACE MAVEN when\n"
	.string "he's serious?\p"
	.string "When he throws his entire might into\n"
	.string "battle, he's said to use these POKMON:\p"
	.string "A FIRE-type LEGENDARY POKMON, a\n"
	.string "NORMAL-type LAZY POKMON,\l"
	.string "and a WATER-type AURORA POKMON.$"

BattleFrontier_Lounge2_Text_PyramidKingIsThere::
# 97 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Bet you didn't know this!\p"
	.string "One of those top TRAINERS that SCOTT\n"
	.string "calls the FRONTIER BRAINS is there.\p"
	.string "It's this fiery-hot TRAINER called the\n"
	.string "PYRAMID KING that runs the place.$"

BattleFrontier_Lounge2_Text_PyramidKingSilverMons::
# 101 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PYRAMID KING\n"
	.string "before?\p"
	.string "When he's checking the foe's power, he\n"
	.string "apparently uses these POKMON:\p"
	.string "A ROCK-type ROCK PEAK POKMON, an\n"
	.string "ICE-type ICEBERG POKMON,\l"
	.string "and a STEEL-type IRON POKMON.$"

BattleFrontier_Lounge2_Text_PyramidKingGoldMons::
# 105 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Have you battled the PYRAMID KING when\n"
	.string "he's serious?\p"
	.string "When he's pumped with hot power, he\n"
	.string "apparently uses these POKMON:\p"
	.string "An ICE & FLYING FREEZE POKMON, an\n"
	.string "ELECTRIC & FLYING ELECTRIC POKMON,\l"
	.string "and a FIRE- & FLYING-type FLAME\l"
	.string "POKMON.$"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice1::
# 109 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Sure, there are several places where\n"
	.string "you can enter DOUBLE BATTLES.\p"
	.string "But the DOUBLE BATTLE ROOMS of the\n"
	.string "BATTLE TOWER are, like, basic!\p"
	.string "They're where you should learn about\n"
	.string "how DOUBLE BATTLES are played here\l"
	.string "in the BATTLE FRONTIER.$"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice2::
# 113 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Watch yourself in the battles here.\p"
	.string "I hear there are TRAINERS that have\n"
	.string "strategies they developed just for\l"
	.string "DOUBLE BATTLES.$"

BattleFrontier_Lounge2_Text_DoubleBattleAdvice3::
# 117 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "Once you're confident and comfortable\n"
	.string "with DOUBLE BATTLES here, you should\l"
	.string "think about challenging other places\l"
	.string "offering DOUBLE BATTLES.$"

BattleFrontier_Lounge2_Text_MultiBattleAdvice::
# 121 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "All sorts of TRAINERS gather in the\n"
	.string "BATTLE SALON.\p"
	.string "Just think--you may run into your\n"
	.string "friends or followers!\l"
	.string "You should look carefully!$"

BattleFrontier_Lounge2_Text_LinkMultiBattleAdvice::
# 125 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "If you're with a friend, head for the\n"
	.string "LINK MULTI BATTLE ROOM.\p"
	.string "If you play with a strong friend, you\n"
	.string "can expect to see tough foes!$"

BattleFrontier_Lounge2_Text_NewsGatheringPower::
# 129 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "What amazing news-gathering power! My\n"
	.string "mentor's like none other!$"

BattleFrontier_Lounge2_Text_AmazingPowersOfObservation::
# 133 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "What amazing powers of observation! My\n"
	.string "mentor's like none other!$"

BattleFrontier_Lounge2_Text_AmazingPowerOfPersuasion::
# 137 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "What amazing power of persuasion! My\n"
	.string "mentor's like none other!$"

BattleFrontier_Lounge2_Text_ThisPlaceIsScaringMe::
# 141 "data/maps/BattleFrontier_Lounge2/scripts.pory"
	.string "What is this place? It's scaring me$"
