Route104_MapScripts::
# 2 "data/maps/Route104/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route104_OnFrame
# 3 "data/maps/Route104/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route104_OnTransition
	.byte 0


Route104_Text_BrineyLivesInSeasideCottage::
# 7 "data/maps/Route104/scripts.pory"
	.string "That seaside cottage is where MR.\n"
	.string "BRINEY lives.\p"
	.string "He was once a mighty sailor who never\n"
	.string "feared the sea, however stormy.$"

Route104_Text_WhatsItLikeAtBottomOfSea::
# 11 "data/maps/Route104/scripts.pory"
	.string "The sea, huh?\p"
	.string "I wonder what it's like at the bottom of\n"
	.string "the sea?$"

Route104_Text_ThrowBallAtWeakenedPokemon::
# 15 "data/maps/Route104/scripts.pory"
	.string "If you're going to throw a POK BALL,\n"
	.string "weaken the wild POKMON first.\p"
	.string "It will be easier to catch if it's been\n"
	.string "poisoned, burned, or lulled to sleep.$"

Route104_Text_OnlyThrowBallAtWildPokemon::
# 19 "data/maps/Route104/scripts.pory"
	.string "You're a thief if you try to steal\n"
	.string "someone else's POKMON.\p"
	.string "You should throw POK BALLS only at wild\n"
	.string "POKMON.$"

Route104_Text_ImNotATrainer::
# 23 "data/maps/Route104/scripts.pory"
	.string "Oh, no, I'm not a TRAINER.\p"
	.string "But that's right, if TRAINERS lock eyes,\n"
	.string "it's a challenge to battle.\p"
	.string "If you don't want to battle, stay out of\n"
	.string "their sight.$"

Route104_Text_LikeFillingMouthWithSeedsTakeThis::
# 27 "data/maps/Route104/scripts.pory"
	.string "I like filling my mouth with seeds, then\n"
	.string "spitting them out fast!\p"
	.string "You can have this, so you try it out!\p"
	.string "Use it on a POKMON, and it will learn a\n"
	.string "move for firing seeds rapidly.$"

Route104_Text_TMsAreOneTimeUse::
# 31 "data/maps/Route104/scripts.pory"
	.string "A word of advice!\p"
	.string "A TM, TECHNICAL MACHINE, is good only\n"
	.string "for one-time use.\p"
	.string "Once you use it, it's gone. Think twice\n"
	.string "before using it!$"

Route104_Text_DontNeedThisTakeIt::
# 35 "data/maps/Route104/scripts.pory"
	.string "This FLOWER SHOP started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping.\p"
	.string "I don't need this WHITE HERB anymore.\n"
	.string "Would you take it, please?$"

Route104_Text_FlowerShopSellingSaplings::
# 39 "data/maps/Route104/scripts.pory"
	.string "This FLOWER SHOP started selling\n"
	.string "saplings recently.\p"
	.string "It made me so happy, I went overboard\n"
	.string "shopping. Where should I put them?$"

Route104_Text_MrBrineysCottage::
# 43 "data/maps/Route104/scripts.pory"
	.string "MR. BRINEY'S COTTAGE$"

Route104_Text_RouteSignPetalburg::
# 47 "data/maps/Route104/scripts.pory"
	.string "ROUTE 1O4 {RIGHT_ARROW} PETALBURG CITY$"

Route104_Text_RouteSignRustboro::
# 51 "data/maps/Route104/scripts.pory"
	.string "ROUTE 1O4 {UP_ARROW} RUSTBORO CITY$"

Route104_Text_PrettyPetalFlowShop::
# 55 "data/maps/Route104/scripts.pory"
	.string "PRETTY PETAL FLOWER SHOP$"

Route104_Text_TrainerTipsDoubleBattles::
# 59 "data/maps/Route104/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "In the HOENN region there are pairs of\n"
	.string "TRAINERS who challenge others\l"
	.string "for 2-on-2 POKMON battles called\l"
	.string "DOUBLE BATTLES.\p"
	.string "In a DOUBLE BATTLE, the TRAINER must\n"
	.string "send out two POKMON, the one at the\l"
	.string "left of the list and the top one.\l"
	.string "Watch how POKMON are lined up.$"

Route104_Text_MayWeShouldRegister::
# 63 "data/maps/Route104/scripts.pory"
	.string "MAY: Oh, hi, {PLAYER}{KUN}!\p"
	.string "DEVON upgraded your POKNAV with the\n"
	.string "MATCH CALL system, huh?\p"
	.string "We should register each other so we can\n"
	.string "get in contact anytime.$"

Route104_Text_RegisteredMay::
# 67 "data/maps/Route104/scripts.pory"
	.string "{PLAYER} registered MAY in the\n"
	.string "POKNAV.$"

Route104_Text_MayHowsYourPokedex::
# 71 "data/maps/Route104/scripts.pory"
	.string "MAY: Oh, by the way, {PLAYER}{KUN}, how's\n"
	.string "your POKDEX coming along?$"

Route104_Text_MayMinesDecentLetsBattle::
# 75 "data/maps/Route104/scripts.pory"
	.string "Mine's looking pretty decent. So\l"
	.string "How about a little battle?$"

Route104_Text_MayHaventRaisedPokemon::
# 79 "data/maps/Route104/scripts.pory"
	.string "MAY: Oh, what's the matter?\p"
	.string "Haven't you caught or raised your\n"
	.string "POKMON very much?\p"
	.string "That's not very good for a TRAINER!$"

Route104_Text_MayLetsBattle::
# 83 "data/maps/Route104/scripts.pory"
	.string "MAY: So, what do you think? How about a\n"
	.string "little battle here?$"

Route104_Text_MayIntro::
# 87 "data/maps/Route104/scripts.pory"
	.string "MAY: You just became a TRAINER,\n"
	.string "{PLAYER}{KUN}. I'm not going to lose!$"

Route104_Text_MayDefeat::
# 91 "data/maps/Route104/scripts.pory"
	.string "Yikes! You're better than I expected!$"

Route104_Text_MayPostBattle::
# 95 "data/maps/Route104/scripts.pory"
	.string "MAY: I can tell you've gotten pretty\n"
	.string "good with the way you handle POKMON.\p"
	.string "But instead of only making them battle,\n"
	.string "you should be like MR. BRINEY.\p"
	.string "It's important to become friends with\n"
	.string "POKMON, too.$"

Route104_Text_BrendanWeShouldRegister::
# 99 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: Oh, hey, {PLAYER}!\p"
	.string "Cool, you had DEVON install the MATCH\n"
	.string "CALL system on your POKNAV!\p"
	.string "Let's register each other in our\n"
	.string "POKNAVS so we can keep in touch.$"

Route104_Text_RegisteredBrendan::
# 103 "data/maps/Route104/scripts.pory"
	.string "{PLAYER} registered BRENDAN in the\n"
	.string "POKNAV.$"

Route104_Text_BrendanHowsYourPokedex::
# 107 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: {PLAYER}, how's your\n"
	.string "POKDEX? Have you filled in any pages\l"
	.string "yet?$"

Route104_Text_BrendanDoingGreatLetsBattle::
# 111 "data/maps/Route104/scripts.pory"
	.string "Me, I'm doing great!\p"
	.string "Want to check out how good I am with a\n"
	.string "battle?$"

Route104_Text_BrendanNoConfidence::
# 115 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: What's the matter? Don't have\n"
	.string "any confidence in your POKMON?$"

Route104_Text_BrendanLetsBattle::
# 119 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: What's up? Want to have a\n"
	.string "battle with me?$"

Route104_Text_BrendanIntro::
# 123 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: I know you just became a\n"
	.string "TRAINER, but I won't go easy!$"

Route104_Text_BrendanDefeat::
# 127 "data/maps/Route104/scripts.pory"
	.string "Hmm You're pretty good.$"

Route104_Text_BrendanPostBattle::
# 131 "data/maps/Route104/scripts.pory"
	.string "BRENDAN: You've gotten pretty decent\n"
	.string "at handling POKMON.\p"
	.string "But, you know, you shouldn't just be\n"
	.string "making POKMON battle.\p"
	.string "Like MR. BRINEY, it's important to\n"
	.string "become friends with your POKMON.$"
