MarineCave_Entrance_MapScripts::
	.byte 0


MarineCave_Entrance_EventScript_SmithNPC1::
# 5 "data/maps/MarineCave_Entrance/scripts.pory"
	msgbox MarineCave_Entrance_Text_SmithNPC1, MSGBOX_NPC
	end


MarineCave_Entrance_EventScript_SmithNPC2::
# 14 "data/maps/MarineCave_Entrance/scripts.pory"
	msgbox MarineCave_Entrance_Text_SmithNPC2, MSGBOX_NPC
	end


MarineCave_Entrance_EventScript_SmithNPC3::
# 23 "data/maps/MarineCave_Entrance/scripts.pory"
	msgbox MarineCave_Entrance_Text_SmithNPC3, MSGBOX_NPC
	end


MarineCave_Entrance_Text_SmithNPC1::
# 9 "data/maps/MarineCave_Entrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MarineCave_Entrance_Text_SmithNPC2::
# 18 "data/maps/MarineCave_Entrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

MarineCave_Entrance_Text_SmithNPC3::
# 27 "data/maps/MarineCave_Entrance/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
