SealedChamber_InnerRoom_MapScripts::
	.byte 0


SealedChamber_InnerRoom_EventScript_BrailleBackWall::
# 27 "data/maps/SealedChamber_InnerRoom/scripts.pory"
	msgbox SealedChamber_InnerRoom_Text_DoorOpenedFarAway, MSGBOX_DEFAULT
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart1::
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart2::
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart3::
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart4::
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart5::
	end


SealedChamber_InnerRoom_EventScript_BrailleStoryPart6::
	end


SealedChamber_InnerRoom_Text_DoorOpenedFarAway::
# 34 "data/maps/SealedChamber_InnerRoom/scripts.pory"
	.string "You hear a door open far away.$"
