Route29_Gatehouse_MapScripts::
	.byte 0


Route29_Gatehouse_EventScript_SmithNPC1::
# 5 "data/maps/Route29_Gatehouse/scripts.pory"
	msgbox Route29_Gatehouse_Text_SmithNPC1, MSGBOX_NPC
	end


Route29_Gatehouse_EventScript_SmithNPC2::
# 14 "data/maps/Route29_Gatehouse/scripts.pory"
	msgbox Route29_Gatehouse_Text_SmithNPC2, MSGBOX_NPC
	end


Route29_Gatehouse_Text_SmithNPC1::
# 9 "data/maps/Route29_Gatehouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route29_Gatehouse_Text_SmithNPC2::
# 18 "data/maps/Route29_Gatehouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
