LavenderTown_MapScripts::
# 2 "data/maps/LavenderTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LavenderTown_OnTransition
	.byte 0


LavenderTown_Text_DoYouBelieveInGhosts::
# 6 "data/maps/LavenderTown/scripts.pory"
	.string "Do you believe in ghosts?$"

LavenderTown_Text_SoThereAreBelievers::
# 10 "data/maps/LavenderTown/scripts.pory"
	.string "Really? So there are believers…$"

LavenderTown_Text_JustImaginingWhiteHand::
# 14 "data/maps/LavenderTown/scripts.pory"
	.string "Hahaha, I guess not.\p"
	.string "That white hand on your shoulder… I'm\n"
	.string "just imagining it.$"

LavenderTown_Text_TownKnownAsMonGraveSite::
# 18 "data/maps/LavenderTown/scripts.pory"
	.string "This town is known as the grave site of\n"
	.string "POKéMON.\p"
	.string "Memorial services are held in POKéMON\n"
	.string "TOWER.$"

LavenderTown_Text_GhostsAppearedInTower::
# 22 "data/maps/LavenderTown/scripts.pory"
	.string "Ghosts appeared in POKéMON TOWER.\p"
	.string "I think they're the spirits of POKéMON\n"
	.string "that the ROCKETS killed.$"

LavenderTown_Text_TownSign::
# 26 "data/maps/LavenderTown/scripts.pory"
	.string "LAVENDER TOWN The Noble Purple Town$"

LavenderTown_Text_SilphScopeNotice::
# 30 "data/maps/LavenderTown/scripts.pory"
	.string "New SILPH SCOPE! Make the Invisible\n"
	.string "Plain to See!\p"
	.string "SILPH CO.$"

LavenderTown_Text_VolunteerPokemonHouse::
# 34 "data/maps/LavenderTown/scripts.pory"
	.string "LAVENDER VOLUNTEER POKéMON HOUSE$"

LavenderTown_Text_PokemonTowerSign::
# 38 "data/maps/LavenderTown/scripts.pory"
	.string "POKéMON TOWER Becalm the Spirits of\n"
	.string "POKéMON$"
