AbandonedShip_CaptainsOffice_MapScripts::
	.byte 0


AbandonedShip_CaptainsOffice_Text_NoSuccessFindingScanner::
# 5 "data/maps/AbandonedShip_CaptainsOffice/scripts.pory"
	.string "I'm investigating this ship on behalf of\n"
	.string "CAPT. STERN.\p"
	.string "He also asked me to find a SCANNER, but\n"
	.string "I haven't had any success…$"

AbandonedShip_CaptainsOffice_Text_OhCanYouDeliverScanner::
# 9 "data/maps/AbandonedShip_CaptainsOffice/scripts.pory"
	.string "Oh! That's a SCANNER!\p"
	.string "Listen, can I get you to deliver that to\n"
	.string "CAPT. STERN?\p"
	.string "I want to investigate this ship a little\n"
	.string "more.$"

AbandonedShip_CaptainsOffice_Text_ThisIsSSCactus::
# 13 "data/maps/AbandonedShip_CaptainsOffice/scripts.pory"
	.string "This ship is called S.S. CACTUS. It seems\n"
	.string "to be from an earlier era.$"
