PokemonMansion_3F_MapScripts::
# 2 "data/maps/PokemonMansion_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_3F_OnLoad
	.byte 0


PokemonMansion_Text_PressSecretSwitchJP::
# 6 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "\p"
	.string "$"

PokemonMansion_Text_LetsTryIt::
# 10 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "$"

PokemonMansion_Text_GaveUpOnPressingSwitch::
# 14 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "$"

PokemonMansion_1F_Text_SimonIntro::
# 18 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "This place is, like, huge!$"

PokemonMansion_1F_Text_SimonDefeat::
# 22 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "Ayah!$"

PokemonMansion_1F_Text_SimonPostBattle::
# 26 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "I wonder where my partner went.$"

PokemonMansion_1F_Text_BraydonIntro::
# 30 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "My mentor once lived here.$"

PokemonMansion_1F_Text_BraydonDefeat::
# 34 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "Whew! Overwhelming!$"

PokemonMansion_1F_Text_BraydonPostBattle::
# 38 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "So, you're stuck? Try jumping off over\n"
	.string "there!$"

PokemonMansion_1F_Text_MewGaveBirthToMewtwo::
# 42 "data/maps/PokemonMansion_3F/scripts.pory"
	.string "Diary: Feb. 6 MEW gave birth.\p"
	.string "We named the newborn MEWTWO.$"
