MauvilleCity_MapScripts::
# 2 "data/maps/MauvilleCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MauvilleCity_OnTransition
	.byte 0


MauvilleCity_Text_UncleHesTooPeppy::
# 6 "data/maps/MauvilleCity/scripts.pory"
	.string "UNCLE: It's because of POKMON that\n"
	.string "this boy's got more pep, I suppose\l"
	.string "But he's become a bit too peppy$"

MauvilleCity_Text_WallyWantToChallengeGym::
# 10 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: Aww, UNCLE, please?\p"
	.string "I want to challenge this GYM and see\n"
	.string "how much better I've become.\p"
	.string "Please? May I, please?$"

MauvilleCity_Text_UncleYourePushingIt::
# 14 "data/maps/MauvilleCity/scripts.pory"
	.string "UNCLE: Now hold on, WALLY.\p"
	.string "Since you started living with POKMON,\n"
	.string "you have grown quite a lot stronger.\p"
	.string "But don't you think you're pushing it to\n"
	.string "suddenly challenge a GYM?$"

MauvilleCity_Text_WallyWeCanBeatAnyone::
# 18 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: I'm not pushing it.\p"
	.string "If I combine forces with RALTS, we can\n"
	.string "beat anyone!$"

MauvilleCity_Text_WallyWillYouBattleMe::
# 22 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: Oh! Hi, {PLAYER}!\p"
	.string "I've gotten a lot stronger since we met.\p"
	.string "{PLAYER}, I want you and my UNCLE to\n"
	.string "understand that.\p"
	.string "{PLAYER}, please, will you have a\n"
	.string "battle with me?$"

MauvilleCity_Text_WallyMyUncleWontKnowImStrong::
# 26 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: Oh If you won't battle me,\n"
	.string "{PLAYER}, my UNCLE won't know that\l"
	.string "I've\l"
	.string "become really strong.$"

MauvilleCity_Text_UncleCanYouBattleWally::
# 30 "data/maps/MauvilleCity/scripts.pory"
	.string "UNCLE: {PLAYER}{KUN}, was it? On WALLY's\n"
	.string "behalf, can I ask you to\l"
	.string "battle with him just this once?\p"
	.string "I don't think he's going to listen to any\n"
	.string "reason the way he is now.$"

MauvilleCity_Text_WallyPleaseBattleMe::
# 34 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: {PLAYER}, please! Battle with\n"
	.string "me, please.$"

MauvilleCity_Text_WallyHereICome::
# 38 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: {PLAYER}, thank you.\p"
	.string "Okay Here I come!$"

MauvilleCity_Text_WallyDefeat::
# 42 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY:\p"
	.string "\p"
	.string "I lost$"

MauvilleCity_Text_WallyIllGoBackToVerdanturf::
# 46 "data/maps/MauvilleCity/scripts.pory"
	.string "WALLY: UNCLE I'll go back to VERDANTURF$"

MauvilleCity_Text_ThankYouNotEnoughToBattle::
# 50 "data/maps/MauvilleCity/scripts.pory"
	.string "{PLAYER}, thank you. Being a TRAINER\n"
	.string "is tough, isn't it?\p"
	.string "It's not enough just to have POKMON\n"
	.string "and make them battle. That isn't what\l"
	.string "being a real TRAINER is about.$"

MauvilleCity_Text_UncleNoNeedToBeDown::
# 54 "data/maps/MauvilleCity/scripts.pory"
	.string "UNCLE: WALLY, there's no need to be so\n"
	.string "down on yourself.\p"
	.string "Why, what's keeping you from becoming\n"
	.string "stronger and stronger?\p"
	.string "Come on, let's go home. Everyone's\n"
	.string "waiting for you.$"

MauvilleCity_Text_UncleVisitUsSometime::
# 58 "data/maps/MauvilleCity/scripts.pory"
	.string "UNCLE: {PLAYER}{KUN}, it just dawned on me\n"
	.string "that you must be the TRAINER who kept\l"
	.string "an eye out for WALLY when he caught\l"
	.string "his POKMON.\p"
	.string "Why don't you visit us in VERDANTURF\n"
	.string "sometime?\l"
	.string "I'm sure WALLY would enjoy it.$"

MauvilleCity_Text_WallyPokenavCall::
# 62 "data/maps/MauvilleCity/scripts.pory"
	.string "Beep!\p"
	.string "WALLY: Oh, hello, {PLAYER}!\p"
	.string "I just wanted to tell you that my uncle\n"
	.string "bought me a POKNAV!\p"
	.string "Now I can get in touch with you anytime,\n"
	.string "{PLAYER}!\p"
	.string "Click!$"

MauvilleCity_Text_RegisteredWally::
# 66 "data/maps/MauvilleCity/scripts.pory"
	.string "Registered WALLY in the POKNAV.$"

MauvilleCity_Text_ScottYouDidntHoldBack::
# 70 "data/maps/MauvilleCity/scripts.pory"
	.string "SCOTT: Hehe I was watching that match!\p"
	.string "You're friends with that boy WALLY,\n"
	.string "aren't you?\p"
	.string "But you didn't hold anything back and\n"
	.string "beat him impressively.\p"
	.string "Yeah! That's what a real POKMON battle\n"
	.string "is all about!\p"
	.string "I idolize TRAINERS like that!\p"
	.string "I'll be cheering for you!$"

MauvilleCity_Text_WattsonNeedFavorTakeKey::
# 74 "data/maps/MauvilleCity/scripts.pory"
	.string "WATTSON: Oh, {PLAYER}{KUN}! You look like\n"
	.string "you have a lot of zip!\l"
	.string "That's a good thing, wahahahaha!\p"
	.string "Fine! I've decided! I need a favor,\n"
	.string "{PLAYER}{KUN}!\p"
	.string "MAUVILLE CITY has an underground\n"
	.string "sector called NEW MAUVILLE.\p"
	.string "{PLAYER}{KUN}, I'd like you to go there and\n"
	.string "switch off the GENERATOR.\p"
	.string "The GENERATOR has been running a bit\n"
	.string "haywire. It's getting unsafe.\p"
	.string "Here, this is the KEY to get into NEW\n"
	.string "MAUVILLE.$"

MauvilleCity_Text_WattsonWontBeChallenge::
# 78 "data/maps/MauvilleCity/scripts.pory"
	.string "WATTSON: Don't you worry about it. It\n"
	.string "won't be a challenge to you.\p"
	.string "The entrance to NEW MAUVILLE is just a\n"
	.string "short SURF away from ROUTE 110.\p"
	.string "That's it, then, you have my trust!\n"
	.string "Wahahahaha!$"

MauvilleCity_Text_WattsonThanksTakeTM::
# 82 "data/maps/MauvilleCity/scripts.pory"
	.string "WATTSON: Wahahahaha!\p"
	.string "I knew it, {PLAYER}{KUN}! I knew I'd made\n"
	.string "the right choice asking you!\p"
	.string "This is my thanks--a TM containing\n"
	.string "THUNDERBOLT!\p"
	.string "Go on, you've earned it!$"

MauvilleCity_Text_WattsonYoungTakeCharge::
# 86 "data/maps/MauvilleCity/scripts.pory"
	.string "WATTSON: Wahahahaha!\p"
	.string "It pleases me to no end to see the\n"
	.string "young step up and take charge!$"

MauvilleCity_Text_NurseHurtMonBackToHealth::
# 90 "data/maps/MauvilleCity/scripts.pory"
	.string "You know, it's cool to have POKMON\n"
	.string "battles and stuff\p"
	.string "But if your POKMON gets hurt, you have\n"
	.string "to nurse it back to health.$"

MauvilleCity_Text_AllSortsOfPeopleComeThrough::
# 94 "data/maps/MauvilleCity/scripts.pory"
	.string "The roads of this town stretch north\n"
	.string "and south, and east and west.\p"
	.string "Because of that, we get all sorts of\n"
	.string "people coming through.$"

MauvilleCity_Text_RydelVeryGenerous::
# 98 "data/maps/MauvilleCity/scripts.pory"
	.string "Have you been to RYDEL'S CYCLES yet?\p"
	.string "RYDEL, the owner, is a very generous\n"
	.string "man.$"

MauvilleCity_Text_PokemonCanJumpYouOnBike::
# 102 "data/maps/MauvilleCity/scripts.pory"
	.string "Even if you're riding a BIKE, wild POKMON\n"
	.string "could jump you.$"

MauvilleCity_Text_CitySign::
# 106 "data/maps/MauvilleCity/scripts.pory"
	.string "MAUVILLE CITY The bright and shiny\n"
	.string "city of fun!$"

MauvilleCity_Text_GymSign::
# 110 "data/maps/MauvilleCity/scripts.pory"
	.string "MAUVILLE CITY POKMON GYM LEADER:\n"
	.string "WATTSON\l"
	.string "The cheerfully electrifying man!$"

MauvilleCity_Text_BikeShopSign::
# 114 "data/maps/MauvilleCity/scripts.pory"
	.string "Ride in gravel and shake up your soul!\l"
	.string "RYDEL'S CYCLES$"

MauvilleCity_Text_GameCornerSign::
# 118 "data/maps/MauvilleCity/scripts.pory"
	.string "The play spot for all! MAUVILLE GAME\n"
	.string "CORNER$"

MauvilleCity_Text_ExplainTV::
# 122 "data/maps/MauvilleCity/scripts.pory"
	.string "Hi, do you check out TV at all?\p"
	.string "They've added a bunch of cool new shows\n"
	.string "recently.\p"
	.string "TV is so cool. I've seen my friends on TV\n"
	.string "just out of the blue.\p"
	.string "And, sometimes, they even put you on TV\n"
	.string "without telling you.\p"
	.string "I wish I would be on TV sometime.\p"
	.string "That's why I think you should check out\n"
	.string "TVs whenever you can.$"

MauvilleCity_Text_BeenCheckingOutTV::
# 126 "data/maps/MauvilleCity/scripts.pory"
	.string "Hi, have you been checking out TVs?$"
