LavenderTown_PokemonCenter_1F_MapScripts::
# 2 "data/maps/LavenderTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LavenderTown_PokemonCenter_1F_OnTransition
# 3 "data/maps/LavenderTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


LavenderTown_PokemonCenter_1F_Text_RocketsDoAnythingForMoney::
# 7 "data/maps/LavenderTown_PokemonCenter_1F/scripts.pory"
	.string "TEAM ROCKET will do anything for the\n"
	.string "sake of money!\p"
	.string "There is no job too dirty, no deed too\n"
	.string "heinous, no crime too wicked!$"

LavenderTown_PokemonCenter_1F_Text_CubonesMotherKilledByRockets::
# 11 "data/maps/LavenderTown_PokemonCenter_1F/scripts.pory"
	.string "I saw CUBONE's mother trying to escape\n"
	.string "from TEAM ROCKET.\p"
	.string "She was killed trying to get away$"

LavenderTown_PokemonCenter_1F_Text_PeoplePayForCuboneSkulls::
# 15 "data/maps/LavenderTown_PokemonCenter_1F/scripts.pory"
	.string "You know how the CUBONE species wears\n"
	.string "skulls, right?\p"
	.string "People will pay a lot for one.$"
