LilycoveCity_MapScripts::
# 2 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_OnTransition
# 3 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, LilycoveCity_OnLoad
	.byte 0


LilycoveCity_Text_MayShoppingLetsBattle::
# 7 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Oh, hey? {PLAYER}{KUN}, are you\n"
	.string "shopping, too?\p"
	.string "I bought a whole bunch of DOLLS and\n"
	.string "POSTERS.\p"
	.string "Of course, I've also caught a lot of\n"
	.string "POKMON, and I'm raising them\l"
	.string "properly, too.\p"
	.string "Actually, I'm more worried if you're\n"
	.string "raising POKMON properly, {PLAYER}{KUN}.\p"
	.string "I'll battle with you, so you can show me\n"
	.string "your POKMON, {PLAYER}{KUN}.$"

LilycoveCity_Text_MayNotRaisingPokemon::
# 11 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Oh, why? {PLAYER}{KUN}, haven't you\n"
	.string "been raising your POKMON?\p"
	.string "That's not a very good showing as a\n"
	.string "TRAINER$"

LilycoveCity_Text_MayBattleMe::
# 15 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Come on, battle with me, so I can\n"
	.string "check out your POKMON!$"

LilycoveCity_Text_MayWontBeBeaten::
# 19 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: The POKMON I raised won't be\n"
	.string "beaten by your POKMON, {PLAYER}{KUN}!$"

LilycoveCity_Text_MayDefeat::
# 23 "data/maps/LilycoveCity/scripts.pory"
	.string "\p"
	.string "I remember the battle I had with you,\n"
	.string "{PLAYER}{KUN}, on ROUTE 103.\p"
	.string "That battle helped you become this\n"
	.string "strong, {PLAYER}{KUN}, didn't it?$"

LilycoveCity_Text_MayGoingBackToLittleroot::
# 27 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: I'm thinking of going back to\n"
	.string "LITTLEROOT soon.\p"
	.string "I've caught a decent group of POKMON,\n"
	.string "and my POKDEX is coming along, so\l"
	.string "I'm going home to show my dad.$"

LilycoveCity_Text_MayYouGoingToCollectBadges::
# 31 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Collect all the GYM BADGES and take the\n"
	.string "POKMON LEAGUE challenge?\p"
	.string "Well, while you're collecting BADGES,\n"
	.string "{PLAYER}{KUN}, I'm going to work on my\l"
	.string "POKDEX. I'll complete it before you!\p"
	.string "See you!$"

LilycoveCity_Text_MayYouGoingToPokemonLeague::
# 35 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Are you taking the POKMON LEAGUE\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKDEX?\p"
	.string "I might've lost to you in battling, but\n"
	.string "I'll finish my POKDEX before you!\p"
	.string "See you!$"

LilycoveCity_Text_MayYouGoingToBattleFrontier::
# 39 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Are you taking the BATTLE FRONTIER\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKDEX?\p"
	.string "I might've lost to you in battling, but\n"
	.string "I'll finish my POKDEX before you!\p"
	.string "See you!$"

LilycoveCity_Text_BrendanShoppingLetsBattle::
# 43 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Oh, hey, it's {PLAYER}.\p"
	.string "I'm running an errand for my dad. No, I'm\n"
	.string "not buying any DOLLS.\p"
	.string "Anyways, it's been a while.\p"
	.string "Want to have a battle to see who's been\n"
	.string "raising POKMON better?$"

LilycoveCity_Text_BrendanNoConfidence::
# 47 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Oh, what's the matter? Don't\n"
	.string "have the confidence?$"

LilycoveCity_Text_BrendanBattleMe::
# 51 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Want to battle to see who's\n"
	.string "been raising POKMON better?$"

LilycoveCity_Text_BrendanWontBeBeaten::
# 55 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Aww, but you know I'm not\n"
	.string "going to lose to no {PLAYER}.$"

LilycoveCity_Text_BrendanDefeat::
# 59 "data/maps/LilycoveCity/scripts.pory"
	.string "Humph You've done a lot of raising.\p"
	.string "That stings a bit--I had a head start\n"
	.string "on you as a TRAINER$"

LilycoveCity_Text_BrendanGoingBackToLittleroot::
# 63 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: I I plan on going home to\n"
	.string "LITTLEROOT.\p"
	.string "You know I'm helping out my dad on his\n"
	.string "POKDEX. It's coming together pretty\l"
	.string "decently, so I should go show him.$"

LilycoveCity_Text_BrendanYouGoingToCollectBadges::
# 67 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Collect all the GYM BADGES and take the\n"
	.string "POKMON LEAGUE challenge?\p"
	.string "Maybe I'll do that, too\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_BrendanYouGoingToPokemonLeague::
# 71 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Since you're that strong, are you\n"
	.string "taking the POKMON LEAGUE challenge?\p"
	.string "Heh, even me--if I trained my POKMON a\n"
	.string "bit more, I should be stronger than\l"
	.string "you, {PLAYER}.\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_BrendanYouGoingToBattleFrontier::
# 75 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Are you taking the BATTLE FRONTIER\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKDEX?\p"
	.string "Since you're that strong, you should\n"
	.string "consider the BATTLE FRONTIER.\p"
	.string "Heh, if I train my POKMON a bit more, I'll\n"
	.string "get stronger than you, {PLAYER}.\p"
	.string "Maybe I should go to the BATTLE\n"
	.string "FRONTIER.\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_MovedLootIntoHideoutToday::
# 79 "data/maps/LilycoveCity/scripts.pory"
	.string "Fufufu\p"
	.string "We moved more loot into our secret\n"
	.string "HIDEOUT today\p"
	.string "Wh-who are you?! I was just talking to\n"
	.string "myself!$"

LilycoveCity_Text_ChanceToDoBigThings::
# 83 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm just a GRUNT, so I don't know what\n"
	.string "the BOSS is thinking\p"
	.string "But being on TEAM AQUA, I know I'll get\n"
	.string "the chance to do big things!\p"
	.string "Wh-who are you?! I was just talking to\n"
	.string "myself!$"

LilycoveCity_Text_DontGoNearCaveInCove::
# 87 "data/maps/LilycoveCity/scripts.pory"
	.string "Hey, you!\p"
	.string "Don't go near the cave in the cove!\p"
	.string "Why? You don't need a reason why! I'm an\n"
	.string "adult, so you just listen to me!$"

LilycoveCity_Text_IfWorldBecomesOurs::
# 91 "data/maps/LilycoveCity/scripts.pory"
	.string "If this whole wide world becomes ours,\n"
	.string "TEAM AQUA's, it will be a happier\l"
	.string "place for POKMON, too.$"

LilycoveCity_Text_WailmerLeapOutOfWater::
# 95 "data/maps/LilycoveCity/scripts.pory"
	.string "There! WAILMER! Leap out of the water\n"
	.string "now!$"

LilycoveCity_Text_GetLostMessingUpTraining::
# 99 "data/maps/LilycoveCity/scripts.pory"
	.string "Hunh? What do you want?\p"
	.string "You're messing up our training, so can\n"
	.string "you, like, get lost?$"

LilycoveCity_Text_ContestHallInTown::
# 103 "data/maps/LilycoveCity/scripts.pory"
	.string "There's a POKMON CONTEST HALL right in\n"
	.string "this here town.\p"
	.string "That means well-raised POKMON will come\n"
	.string "from all over the country.\p"
	.string "My heart swells with excitement!$"

LilycoveCity_Text_StrangeCaveInCove::
# 107 "data/maps/LilycoveCity/scripts.pory"
	.string "Have you seen that strange cave in the\n"
	.string "cove at the edge of town?$"

LilycoveCity_Text_GoingToMoveDeleterForHMs::
# 111 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm going to teach my POKMON some new\n"
	.string "moves for entering a CONTEST.\p"
	.string "So, I'm going to see the MOVE DELETER\n"
	.string "and make it forget HM moves.$"

LilycoveCity_Text_ImFromKanto::
# 115 "data/maps/LilycoveCity/scripts.pory"
	.string "I came from KANTO.\p"
	.string "The HOENN region is beautiful with all\n"
	.string "its water and verdant nature.\p"
	.string "Hunh? Wait a second\p"
	.string "Could there be rare POKMON that live\n"
	.string "only in this area?$"

LilycoveCity_Text_TeamAquaBeenTrainingWailmer::
# 119 "data/maps/LilycoveCity/scripts.pory"
	.string "TEAM AQUA's been training their WAILMER\n"
	.string "in the cove.\p"
	.string "We SAILORS can't get our boats out to\n"
	.string "sea with them in the way!$"

LilycoveCity_Text_SomeonePuntedTeamAquaOut::
# 123 "data/maps/LilycoveCity/scripts.pory"
	.string "Ahoy, did you know?\p"
	.string "Someone punted TEAM AQUA out of the\n"
	.string "way for us!\p"
	.string "That got the WAILMER out of the cove,\n"
	.string "so we can get our boats out again.$"

LilycoveCity_Text_SomeoneStoleMyPokemon::
# 127 "data/maps/LilycoveCity/scripts.pory"
	.string "I was taking a relaxing snooze at the\n"
	.string "seaside inn to the sound of waves\p"
	.string "When someone stole my POKMON!\p"
	.string "Who's the abductor? TEAM AQUA? Is it\n"
	.string "TEAM AQUA?$"

LilycoveCity_Text_MissingPokemonCameBack::
# 131 "data/maps/LilycoveCity/scripts.pory"
	.string "My missing POKMON It came back without\n"
	.string "me noticing!$"

LilycoveCity_Text_ImArtDealer::
# 135 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm an ART DEALER.\p"
	.string "I am a buyer and seller of fine art,\n"
	.string "especially paintings.\p"
	.string "I've heard that the MUSEUM here has\n"
	.string "magnificent works on exhibit$"

LilycoveCity_Text_SeaRemainsForeverYoung::
# 139 "data/maps/LilycoveCity/scripts.pory"
	.string "Even as we grow old and wrinkled, the\n"
	.string "sea remains forever young with\l"
	.string "the vivid brilliance of life\p"
	.string "Fwohoho fwohohohoho$"

LilycoveCity_Text_SixtyYearsAgoHusbandProposed::
# 143 "data/maps/LilycoveCity/scripts.pory"
	.string "It was sixty years ago that my husband\n"
	.string "proposed to me here.\l"
	.string "The sea remains as beautiful as ever.\p"
	.string "Mufufufu mufufufufufu$"

LilycoveCity_Text_TeamAquaRenovatedCavern::
# 147 "data/maps/LilycoveCity/scripts.pory"
	.string "Hm, you know of the peculiar cavern in\n"
	.string "this cove?\p"
	.string "That had been a natural formation, but\n"
	.string "then that TEAM AQUA lot came\l"
	.string "along and made their renovations.\p"
	.string "They call themselves the nature-loving\n"
	.string "TEAM AQUA!\p"
	.string "But what they do and what they say\n"
	.string "don't match at all!$"

LilycoveCity_Text_TeamAquaLotGoneForGood::
# 151 "data/maps/LilycoveCity/scripts.pory"
	.string "That cave in the cove\p"
	.string "I didn't notice it right away, but it's\n"
	.string "completely empty now.\p"
	.string "That TEAM AQUA lot, they must have gone\n"
	.string "away for good.$"

LilycoveCity_Text_CitySign::
# 155 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY\p"
	.string "Where the land ends and the sea begins.$"

LilycoveCity_Text_ContestHallSign::
# 159 "data/maps/LilycoveCity/scripts.pory"
	.string "POKMON CONTEST HALL The gathering\n"
	.string "place for TRAINERS!$"

LilycoveCity_Text_MotelSign::
# 163 "data/maps/LilycoveCity/scripts.pory"
	.string "COVE LILY MOTEL\p"
	.string "Remember us as COVE LILY of LILYCOVE.$"

LilycoveCity_Text_MuseumSign::
# 167 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE MUSEUM\p"
	.string "POKMON Masterpiece Collection on\n"
	.string "exhibit!$"

LilycoveCity_Text_MuseumSignPlayersExhibit::
# 171 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE MUSEUM\p"
	.string "{PLAYER}'s POKMON Collection on\n"
	.string "exhibit!$"

LilycoveCity_Text_HarborSignUnderConstruction::
# 175 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY HARBOR\p"
	.string "The ferry S.S. TIDAL is under\n"
	.string "construction in SLATEPORT CITY.\p"
	.string "Service is scheduled to begin shortly.$"

LilycoveCity_Text_HarborSign::
# 179 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY HARBOR\p"
	.string "Enjoy a delightful cruise on the ferry\n"
	.string "S.S. TIDAL.$"

LilycoveCity_Text_TrainerFanClubSign::
# 183 "data/maps/LilycoveCity/scripts.pory"
	.string "POKMON TRAINER FAN CLUB\p"
	.string "The names of TRAINERS are scribbled all\n"
	.string "over the sign$"

LilycoveCity_Text_DepartmentStoreSign::
# 187 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE DEPARTMENT STORE\p"
	.string "Overflowing with great merchandise and\n"
	.string "excitement!\p"
	.string "A great place to find that something\n"
	.string "you need!$"

LilycoveCity_Text_MoveDeletersHouseSign::
# 191 "data/maps/LilycoveCity/scripts.pory"
	.string "MOVE DELETER'S HOUSE\p"
	.string "Unwanted POKMON moves deleted.$"

LilycoveCity_Text_DoYouKnowAboutBerryBlender::
# 195 "data/maps/LilycoveCity/scripts.pory"
	.string "Do you know about the machine BERRY\n"
	.string "BLENDER?$"

LilycoveCity_Text_FasterSpinBetterPokeblocks::
# 199 "data/maps/LilycoveCity/scripts.pory"
	.string "People have to work together to get it\n"
	.string "to spin faster.\p"
	.string "The faster you can make it spin, the\n"
	.string "better {POKEBLOCK}S you can get, I've heard.$"

LilycoveCity_Text_ExplainBerryBlender::
# 203 "data/maps/LilycoveCity/scripts.pory"
	.string "It's used for making a kind of candy\n"
	.string "called a {POKEBLOCK}.\p"
	.string "If you give a good {POKEBLOCK} to a POKMON,\n"
	.string "its condition will improve by a lot.$"

LilycoveCity_Text_HeardTowerCalledSkyPillar::
# 207 "data/maps/LilycoveCity/scripts.pory"
	.string "I heard there's a tower somewhere out\n"
	.string "on the sea routes.\p"
	.string "It's called the SKY PILLAR, I hear.$"

LilycoveCity_Text_SawTallTowerOnRoute131::
# 211 "data/maps/LilycoveCity/scripts.pory"
	.string "I saw this tall tower somewhere around\n"
	.string "ROUTE 131.\p"
	.string "Could that possibly be?$"

LilycoveCity_Text_JustArrivedAndSawRarePokemon::
# 215 "data/maps/LilycoveCity/scripts.pory"
	.string "We just arrived here on our honeymoon\n"
	.string "vacation.\p"
	.string "We happened to see a DRAGON-type\n"
	.string "POKMON flying way up in the sky.\p"
	.string "Do cool POKMON like that live in the\n"
	.string "HOENN region?$"

LilycoveCity_Text_HoneymoonVowToSeeRarePokemon::
# 219 "data/maps/LilycoveCity/scripts.pory"
	.string "On our honeymoon, we vowed to see as\n"
	.string "many rare POKMON as we can.\p"
	.string "So we were delighted to see a rare\n"
	.string "POKMON as soon as we arrived.\p"
	.string "I mean, we are totally happy!$"
