LilycoveCity_MapScripts::
# 2 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_OnTransition
# 3 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, LilycoveCity_OnLoad
	.byte 0


LilycoveCity_MapScripts::
# 7 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_OnTransition
# 8 "data/maps/LilycoveCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, LilycoveCity_OnLoad
	return


LilycoveCity_Text_MayShoppingLetsBattle::
# 12 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Oh, hey? {PLAYER}{KUN}, are you\n"
	.string "shopping, too?\p"
	.string "I bought a whole bunch of DOLLS and\n"
	.string "POSTERS.\p"
	.string "Of course, I've also caught a lot of\n"
	.string "POKéMON, and I'm raising them\l"
	.string "properly, too.\p"
	.string "Actually, I'm more worried if you're\n"
	.string "raising POKéMON properly, {PLAYER}{KUN}.\p"
	.string "I'll battle with you, so you can show me\n"
	.string "your POKéMON, {PLAYER}{KUN}.$"

LilycoveCity_Text_MayNotRaisingPokemon::
# 16 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Oh, why? {PLAYER}{KUN}, haven't you\n"
	.string "been raising your POKéMON?\p"
	.string "That's not a very good showing as a\n"
	.string "TRAINER…$"

LilycoveCity_Text_MayBattleMe::
# 20 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: Come on, battle with me, so I can\n"
	.string "check out your POKéMON!$"

LilycoveCity_Text_MayWontBeBeaten::
# 24 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: The POKéMON I raised won't be\n"
	.string "beaten by your POKéMON, {PLAYER}{KUN}!$"

LilycoveCity_Text_MayDefeat::
# 28 "data/maps/LilycoveCity/scripts.pory"
	.string "… … … … … … … …\p"
	.string "I remember the battle I had with you,\n"
	.string "{PLAYER}{KUN}, on ROUTE 103.\p"
	.string "That battle helped you become this\n"
	.string "strong, {PLAYER}{KUN}, didn't it?$"

LilycoveCity_Text_MayGoingBackToLittleroot::
# 32 "data/maps/LilycoveCity/scripts.pory"
	.string "MAY: I'm thinking of going back to\n"
	.string "LITTLEROOT soon.\p"
	.string "I've caught a decent group of POKéMON,\n"
	.string "and my POKéDEX is coming along, so\l"
	.string "I'm going home to show my dad.$"

LilycoveCity_Text_MayYouGoingToCollectBadges::
# 36 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Collect all the GYM BADGES and take the\n"
	.string "POKéMON LEAGUE challenge?\p"
	.string "Well, while you're collecting BADGES,\n"
	.string "{PLAYER}{KUN}, I'm going to work on my\l"
	.string "POKéDEX. I'll complete it before you!\p"
	.string "See you!$"

LilycoveCity_Text_MayYouGoingToPokemonLeague::
# 40 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Are you taking the POKéMON LEAGUE\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKéDEX?\p"
	.string "I might've lost to you in battling, but\n"
	.string "I'll finish my POKéDEX before you!\p"
	.string "See you!$"

LilycoveCity_Text_MayYouGoingToBattleFrontier::
# 44 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}{KUN}, what are you going to do?\p"
	.string "Are you taking the BATTLE FRONTIER\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKéDEX?\p"
	.string "I might've lost to you in battling, but\n"
	.string "I'll finish my POKéDEX before you!\p"
	.string "See you!$"

LilycoveCity_Text_BrendanShoppingLetsBattle::
# 48 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Oh, hey, it's {PLAYER}.\p"
	.string "I'm running an errand for my dad. No, I'm\n"
	.string "not buying any DOLLS.\p"
	.string "Anyways, it's been a while.\p"
	.string "Want to have a battle to see who's been\n"
	.string "raising POKéMON better?$"

LilycoveCity_Text_BrendanNoConfidence::
# 52 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Oh, what's the matter? Don't\n"
	.string "have the confidence?$"

LilycoveCity_Text_BrendanBattleMe::
# 56 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Want to battle to see who's\n"
	.string "been raising POKéMON better?$"

LilycoveCity_Text_BrendanWontBeBeaten::
# 60 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: Aww, but you know I'm not\n"
	.string "going to lose to no {PLAYER}.$"

LilycoveCity_Text_BrendanDefeat::
# 64 "data/maps/LilycoveCity/scripts.pory"
	.string "Humph… You've done a lot of raising.\p"
	.string "That stings a bit--I had a head start\n"
	.string "on you as a TRAINER…$"

LilycoveCity_Text_BrendanGoingBackToLittleroot::
# 68 "data/maps/LilycoveCity/scripts.pory"
	.string "BRENDAN: I… I plan on going home to\n"
	.string "LITTLEROOT.\p"
	.string "You know I'm helping out my dad on his\n"
	.string "POKéDEX. It's coming together pretty\l"
	.string "decently, so I should go show him.$"

LilycoveCity_Text_BrendanYouGoingToCollectBadges::
# 72 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Collect all the GYM BADGES and take the\n"
	.string "POKéMON LEAGUE challenge?\p"
	.string "Maybe I'll do that, too…\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_BrendanYouGoingToPokemonLeague::
# 76 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Since you're that strong, are you\n"
	.string "taking the POKéMON LEAGUE challenge?\p"
	.string "Heh, even me--if I trained my POKéMON a\n"
	.string "bit more, I should be stronger than\l"
	.string "you, {PLAYER}.\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_BrendanYouGoingToBattleFrontier::
# 80 "data/maps/LilycoveCity/scripts.pory"
	.string "{PLAYER}, what are you going to do?\p"
	.string "Are you taking the BATTLE FRONTIER\n"
	.string "challenge?\p"
	.string "Or, are you going to complete your\n"
	.string "POKéDEX?\p"
	.string "Since you're that strong, you should\n"
	.string "consider the BATTLE FRONTIER.\p"
	.string "Heh, if I train my POKéMON a bit more,\n"
	.string "I'll get stronger than you, {PLAYER}.\p"
	.string "Maybe I should go to the BATTLE\n"
	.string "FRONTIER.\p"
	.string "Well, anyway, hang in there!$"

LilycoveCity_Text_MovedLootIntoHideoutToday::
# 84 "data/maps/LilycoveCity/scripts.pory"
	.string "Fufufu…\p"
	.string "We moved more loot into our secret\n"
	.string "HIDEOUT today…\p"
	.string "Wh-who are you?! I was just talking to\n"
	.string "myself!$"

LilycoveCity_Text_ChanceToDoBigThings::
# 88 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm just a GRUNT, so I don't know what\n"
	.string "the BOSS is thinking…\p"
	.string "But being on TEAM AQUA, I know I'll get\n"
	.string "the chance to do big things!\p"
	.string "Wh-who are you?! I was just talking to\n"
	.string "myself!$"

LilycoveCity_Text_DontGoNearCaveInCove::
# 92 "data/maps/LilycoveCity/scripts.pory"
	.string "Hey, you!\p"
	.string "Don't go near the cave in the cove!\p"
	.string "Why? You don't need a reason why! I'm an\n"
	.string "adult, so you just listen to me!$"

LilycoveCity_Text_IfWorldBecomesOurs::
# 96 "data/maps/LilycoveCity/scripts.pory"
	.string "If this whole wide world becomes ours,\n"
	.string "TEAM AQUA's, it will be a happier\l"
	.string "place for POKéMON, too.$"

LilycoveCity_Text_WailmerLeapOutOfWater::
# 100 "data/maps/LilycoveCity/scripts.pory"
	.string "There! WAILMER! Leap out of the water\n"
	.string "now!$"

LilycoveCity_Text_GetLostMessingUpTraining::
# 104 "data/maps/LilycoveCity/scripts.pory"
	.string "Hunh? What do you want?\p"
	.string "You're messing up our training, so can\n"
	.string "you, like, get lost?$"

LilycoveCity_Text_ContestHallInTown::
# 108 "data/maps/LilycoveCity/scripts.pory"
	.string "There's a POKéMON CONTEST HALL right in\n"
	.string "this here town.\p"
	.string "That means well-raised POKéMON will\n"
	.string "come from all over the country.\p"
	.string "My heart swells with excitement!$"

LilycoveCity_Text_StrangeCaveInCove::
# 112 "data/maps/LilycoveCity/scripts.pory"
	.string "Have you seen that strange cave in the\n"
	.string "cove at the edge of town?$"

LilycoveCity_Text_GoingToMoveDeleterForHMs::
# 116 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm going to teach my POKéMON some new\n"
	.string "moves for entering a CONTEST.\p"
	.string "So, I'm going to see the MOVE DELETER\n"
	.string "and make it forget HM moves.$"

LilycoveCity_Text_ImFromKanto::
# 120 "data/maps/LilycoveCity/scripts.pory"
	.string "I came from KANTO.\p"
	.string "The HOENN region is beautiful with all\n"
	.string "its water and verdant nature.\p"
	.string "Hunh? Wait a second…\p"
	.string "Could there be rare POKéMON that live\n"
	.string "only in this area?$"

LilycoveCity_Text_TeamAquaBeenTrainingWailmer::
# 124 "data/maps/LilycoveCity/scripts.pory"
	.string "TEAM AQUA's been training their WAILMER\n"
	.string "in the cove.\p"
	.string "We SAILORS can't get our boats out to\n"
	.string "sea with them in the way!$"

LilycoveCity_Text_SomeonePuntedTeamAquaOut::
# 128 "data/maps/LilycoveCity/scripts.pory"
	.string "Ahoy, did you know?\p"
	.string "Someone punted TEAM AQUA out of the\n"
	.string "way for us!\p"
	.string "That got the WAILMER out of the cove,\n"
	.string "so we can get our boats out again.$"

LilycoveCity_Text_SomeoneStoleMyPokemon::
# 132 "data/maps/LilycoveCity/scripts.pory"
	.string "I was taking a relaxing snooze at the\n"
	.string "seaside inn to the sound of waves…\p"
	.string "When someone stole my POKéMON!\p"
	.string "Who's the abductor? TEAM AQUA? Is it\n"
	.string "TEAM AQUA?$"

LilycoveCity_Text_MissingPokemonCameBack::
# 136 "data/maps/LilycoveCity/scripts.pory"
	.string "My missing POKéMON… It came back\n"
	.string "without me noticing!$"

LilycoveCity_Text_ImArtDealer::
# 140 "data/maps/LilycoveCity/scripts.pory"
	.string "I'm an ART DEALER.\p"
	.string "I am a buyer and seller of fine art,\n"
	.string "especially paintings.\p"
	.string "I've heard that the MUSEUM here has\n"
	.string "magnificent works on exhibit…$"

LilycoveCity_Text_SeaRemainsForeverYoung::
# 144 "data/maps/LilycoveCity/scripts.pory"
	.string "Even as we grow old and wrinkled, the\n"
	.string "sea remains forever young with\l"
	.string "the vivid brilliance of life…\p"
	.string "Fwohoho fwohohohoho…$"

LilycoveCity_Text_SixtyYearsAgoHusbandProposed::
# 148 "data/maps/LilycoveCity/scripts.pory"
	.string "It was sixty years ago that my husband\n"
	.string "proposed to me here.\l"
	.string "The sea remains as beautiful as ever.\p"
	.string "Mufufufu mufufufufufu…$"

LilycoveCity_Text_TeamAquaRenovatedCavern::
# 152 "data/maps/LilycoveCity/scripts.pory"
	.string "Hm, you know of the peculiar cavern in\n"
	.string "this cove?\p"
	.string "That had been a natural formation, but\n"
	.string "then that TEAM AQUA lot came\l"
	.string "along and made their renovations.\p"
	.string "They call themselves the\n"
	.string "“nature-loving TEAM AQUA”!\p"
	.string "But what they do and what they say\n"
	.string "don't match at all!$"

LilycoveCity_Text_TeamAquaLotGoneForGood::
# 156 "data/maps/LilycoveCity/scripts.pory"
	.string "That cave in the cove…\p"
	.string "I didn't notice it right away, but it's\n"
	.string "completely empty now.\p"
	.string "That TEAM AQUA lot, they must have gone\n"
	.string "away for good.$"

LilycoveCity_Text_CitySign::
# 160 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY\p"
	.string "“Where the land ends and the sea\n"
	.string "begins.”$"

LilycoveCity_Text_ContestHallSign::
# 164 "data/maps/LilycoveCity/scripts.pory"
	.string "POKéMON CONTEST HALL “The gathering\n"
	.string "place for TRAINERS!”$"

LilycoveCity_Text_MotelSign::
# 168 "data/maps/LilycoveCity/scripts.pory"
	.string "COVE LILY MOTEL\p"
	.string "“Remember us as COVE LILY of\n"
	.string "LILYCOVE.”$"

LilycoveCity_Text_MuseumSign::
# 172 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE MUSEUM\p"
	.string "“POKéMON Masterpiece Collection on\n"
	.string "exhibit!”$"

LilycoveCity_Text_MuseumSignPlayersExhibit::
# 176 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE MUSEUM\p"
	.string "“{PLAYER}'s POKéMON Collection on\n"
	.string "exhibit!”$"

LilycoveCity_Text_HarborSignUnderConstruction::
# 180 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY HARBOR\p"
	.string "“The ferry S.S. TIDAL is under\n"
	.string "construction in SLATEPORT CITY.\p"
	.string "“Service is scheduled to begin\n"
	.string "shortly.”$"

LilycoveCity_Text_HarborSign::
# 184 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE CITY HARBOR\p"
	.string "“Enjoy a delightful cruise on the ferry\n"
	.string "S.S. TIDAL.”$"

LilycoveCity_Text_TrainerFanClubSign::
# 188 "data/maps/LilycoveCity/scripts.pory"
	.string "POKéMON TRAINER FAN CLUB\p"
	.string "The names of TRAINERS are scribbled all\n"
	.string "over the sign…$"

LilycoveCity_Text_DepartmentStoreSign::
# 192 "data/maps/LilycoveCity/scripts.pory"
	.string "LILYCOVE DEPARTMENT STORE\p"
	.string "“Overflowing with great merchandise\n"
	.string "and excitement!\p"
	.string "“A great place to find that something\n"
	.string "you need!”$"

LilycoveCity_Text_MoveDeletersHouseSign::
# 196 "data/maps/LilycoveCity/scripts.pory"
	.string "MOVE DELETER'S HOUSE\p"
	.string "“Unwanted POKéMON moves deleted.”$"

LilycoveCity_Text_DoYouKnowAboutBerryBlender::
# 200 "data/maps/LilycoveCity/scripts.pory"
	.string "Do you know about the machine BERRY\n"
	.string "BLENDER?$"

LilycoveCity_Text_FasterSpinBetterPokeblocks::
# 204 "data/maps/LilycoveCity/scripts.pory"
	.string "People have to work together to get it\n"
	.string "to spin faster.\p"
	.string "The faster you can make it spin, the\n"
	.string "better {POKEBLOCK}S you can get, I've heard.$"

LilycoveCity_Text_ExplainBerryBlender::
# 208 "data/maps/LilycoveCity/scripts.pory"
	.string "It's used for making a kind of candy\n"
	.string "called a {POKEBLOCK}.\p"
	.string "If you give a good {POKEBLOCK} to a POKéMON,\n"
	.string "its condition will improve by a lot.$"

LilycoveCity_Text_HeardTowerCalledSkyPillar::
# 212 "data/maps/LilycoveCity/scripts.pory"
	.string "I heard there's a tower somewhere out\n"
	.string "on the sea routes.\p"
	.string "It's called the SKY PILLAR, I hear.$"

LilycoveCity_Text_SawTallTowerOnRoute131::
# 216 "data/maps/LilycoveCity/scripts.pory"
	.string "I saw this tall tower somewhere around\n"
	.string "ROUTE 131.\p"
	.string "Could that possibly be…?$"

LilycoveCity_Text_JustArrivedAndSawRarePokemon::
# 220 "data/maps/LilycoveCity/scripts.pory"
	.string "We just arrived here on our honeymoon\n"
	.string "vacation.\p"
	.string "We happened to see a DRAGON-type\n"
	.string "POKéMON flying way up in the sky.\p"
	.string "Do cool POKéMON like that live in the\n"
	.string "HOENN region?$"

LilycoveCity_Text_HoneymoonVowToSeeRarePokemon::
# 224 "data/maps/LilycoveCity/scripts.pory"
	.string "On our honeymoon, we vowed to see as\n"
	.string "many rare POKéMON as we can.\p"
	.string "So we were delighted to see a rare\n"
	.string "POKéMON as soon as we arrived.\p"
	.string "I mean, we are totally happy!$"
