Route2_EastBuilding_MapScripts::
	.byte 0


Route2_EastBuilding_EventScript_Aide::
	end


Route2_EastBuilding_EventScript_Rocker::
# 9 "data/maps/Route2_EastBuilding/scripts.pory"
	msgbox Route2_EastBuilding_Text_CanGetThroughRockTunnel, MSGBOX_NPC
	end


Route2_EastBuilding_Text_CanGetThroughRockTunnel::
# 14 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "Once a POKéMON learns FLASH, you\n"
	.string "can get through ROCK TUNNEL.$"
