Route2_EastBuilding_MapScripts::
	.byte 0


Route2_EastBuilding_Text_GiveHM05IfSeen10Mons::
# 5 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "Hi! Remember me? I'm one of PROF. OAK's\n"
	.string "AIDES.\p"
	.string "If your POKéDEX has complete data on\n"
	.string "ten species, I'm supposed to\l"
	.string "give you a reward.\p"
	.string "PROF. OAK entrusted me with HM05 for\n"
	.string "you.\p"
	.string "So, {PLAYER}, let me ask you.\p"
	.string "Have you gathered data on at least ten\n"
	.string "kinds of POKéMON?$"

Route2_EastBuilding_Text_GreatHereYouGo::
# 9 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "Great! You have caught or owned\n"
	.string "{STR_VAR_3} kinds of POKéMON!\p"
	.string "Congratulations! Here you go!$"

Route2_EastBuilding_Text_ReceivedHM05FromAide::
# 13 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "{PLAYER} received HM05 from the AIDE.$"

Route2_EastBuilding_Text_ExplainHM05::
# 17 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "HM05 contains the hidden move FLASH.\p"
	.string "FLASH lights up even the darkest of\n"
	.string "caves and dungeons.$"

Route2_EastBuilding_Text_CanGetThroughRockTunnel::
# 21 "data/maps/Route2_EastBuilding/scripts.pory"
	.string "Once a POKéMON learns FLASH, you can\n"
	.string "get through ROCK TUNNEL.$"
