Route17_MapScripts::
	.byte 0


Route17_Text_RaulIntro::
# 5 "data/maps/Route17/scripts.pory"
	.string "There's no getting rich quick in\n"
	.string "battling kids.$"

Route17_Text_RaulDefeat::
# 9 "data/maps/Route17/scripts.pory"
	.string "Burned out!$"

Route17_Text_RaulPostBattle::
# 13 "data/maps/Route17/scripts.pory"
	.string "You can find good stuff lying around on\n"
	.string "CYCLING ROAD.\p"
	.string "There's good money in picking them up\n"
	.string "and selling them.$"

Route17_Text_IsaiahIntro::
# 17 "data/maps/Route17/scripts.pory"
	.string "I'm mighty proud of my bod, kiddo. Come\n"
	.string "on!$"

Route17_Text_IsaiahDefeat::
# 21 "data/maps/Route17/scripts.pory"
	.string "Whoo!$"

Route17_Text_IsaiahPostBattle::
# 25 "data/maps/Route17/scripts.pory"
	.string "I could belly-bump you outta here!$"

Route17_Text_VirgilIntro::
# 29 "data/maps/Route17/scripts.pory"
	.string "You heading to FUCHSIA?$"

Route17_Text_VirgilDefeat::
# 33 "data/maps/Route17/scripts.pory"
	.string "Crash and burn!$"

Route17_Text_VirgilPostBattle::
# 37 "data/maps/Route17/scripts.pory"
	.string "I love racing downhill!$"

Route17_Text_BillyIntro::
# 41 "data/maps/Route17/scripts.pory"
	.string "We're BIKERS! We rule the roads, man!$"

Route17_Text_BillyDefeat::
# 45 "data/maps/Route17/scripts.pory"
	.string "Smoked!$"

Route17_Text_BillyPostBattle::
# 49 "data/maps/Route17/scripts.pory"
	.string "Are you looking for adventure?$"

Route17_Text_NikolasIntro::
# 53 "data/maps/Route17/scripts.pory"
	.string "Let VOLTORB electrify you!$"

Route17_Text_NikolasDefeat::
# 57 "data/maps/Route17/scripts.pory"
	.string "Grounded out!$"

Route17_Text_NikolasPostBattle::
# 61 "data/maps/Route17/scripts.pory"
	.string "I got my VOLTORB at the abandoned\n"
	.string "POWER PLANT.$"

Route17_Text_ZeekIntro::
# 65 "data/maps/Route17/scripts.pory"
	.string "I leveled up my POKMON, but it won't\n"
	.string "evolve. Why?$"

Route17_Text_ZeekDefeat::
# 69 "data/maps/Route17/scripts.pory"
	.string "Why, you!$"

Route17_Text_ZeekPostBattle::
# 73 "data/maps/Route17/scripts.pory"
	.string "Maybe some POKMON need element STONES\n"
	.string "to evolve.$"

Route17_Text_JamalIntro::
# 77 "data/maps/Route17/scripts.pory"
	.string "I need a little exercise!$"

Route17_Text_JamalDefeat::
# 81 "data/maps/Route17/scripts.pory"
	.string "Whew! Good workout!$"

Route17_Text_JamalPostBattle::
# 85 "data/maps/Route17/scripts.pory"
	.string "I'm sure I lost weight there!$"

Route17_Text_CoreyIntro::
# 89 "data/maps/Route17/scripts.pory"
	.string "Be a rebel!$"

Route17_Text_CoreyDefeat::
# 93 "data/maps/Route17/scripts.pory"
	.string "Aaaargh!$"

Route17_Text_CoreyPostBattle::
# 97 "data/maps/Route17/scripts.pory"
	.string "Be ready to fight for your beliefs!$"

Route17_Text_JaxonIntro::
# 101 "data/maps/Route17/scripts.pory"
	.string "Nice BIKE! How's it handle?$"

Route17_Text_JaxonDefeat::
# 105 "data/maps/Route17/scripts.pory"
	.string "Shoot!$"

Route17_Text_JaxonPostBattle::
# 109 "data/maps/Route17/scripts.pory"
	.string "The slope makes it hard to steer.$"

Route17_Text_WilliamIntro::
# 113 "data/maps/Route17/scripts.pory"
	.string "Get lost, kid! I'm bushed!$"

Route17_Text_WilliamDefeat::
# 117 "data/maps/Route17/scripts.pory"
	.string "Are you satisfied?$"

Route17_Text_WilliamPostBattle::
# 121 "data/maps/Route17/scripts.pory"
	.string "I need to catch a few z's!$"

Route17_Text_WatchOutForDiscardedItems::
# 125 "data/maps/Route17/scripts.pory"
	.string "It's a notice.\p"
	.string "Watch out for discarded items.$"

Route17_Text_SameSpeciesGrowDifferentRates::
# 129 "data/maps/Route17/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "All POKMON are unique.\p"
	.string "Even POKMON of the same species and\n"
	.string "level grow at different rates.$"

Route17_Text_PressBToStayInPlace::
# 133 "data/maps/Route17/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Press the B Button to stay in place\n"
	.string "while on a slope.$"

Route17_Text_RouteSign::
# 137 "data/maps/Route17/scripts.pory"
	.string "ROUTE 17 CELADON CITY - FUCHSIA CITY$"

Route17_Text_DontThrowGameThrowBalls::
# 141 "data/maps/Route17/scripts.pory"
	.string "It's a notice!\p"
	.string "Don't throw the game, throw POK BALLS\n"
	.string "instead!$"

Route17_Text_CyclingRoadSign::
# 145 "data/maps/Route17/scripts.pory"
	.string "CYCLING ROAD Slope ends here!$"
