Route37_MapScripts::
	.byte 0


Route37_EventScript_Sign1::
# 6 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_Sign1, MSGBOX_SIGN
	end


Route37_EventScript_SmithNPC1::
# 15 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC1, MSGBOX_NPC
	end


Route37_EventScript_SmithNPC2::
# 24 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC2, MSGBOX_NPC
	end


Route37_EventScript_SmithNPC3::
# 33 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC3, MSGBOX_NPC
	end


Route37_EventScript_SmithNPC4::
# 42 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC4, MSGBOX_NPC
	end


Route37_EventScript_SmithNPC5::
# 51 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC5, MSGBOX_NPC
	end


Route37_EventScript_SmithNPC6::
# 60 "data/maps/Route37/scripts.pory"
	msgbox Route37_Text_SmithNPC6, MSGBOX_NPC
	end


Route37_Text_Sign1::
# 10 "data/maps/Route37/scripts.pory"
	.string "Route37 Sign 1$"

Route37_Text_SmithNPC1::
# 19 "data/maps/Route37/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route37_Text_SmithNPC2::
# 28 "data/maps/Route37/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route37_Text_SmithNPC3::
# 37 "data/maps/Route37/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

Route37_Text_SmithNPC4::
# 46 "data/maps/Route37/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

Route37_Text_SmithNPC5::
# 55 "data/maps/Route37/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

Route37_Text_SmithNPC6::
# 64 "data/maps/Route37/scripts.pory"
	.string "It's the question that drives us, Neo.$"
