Route5_PokemonDayCare_MapScripts::
	.byte 0


Route5_PokemonDayCare_Text_WantMeToRaiseMon::
# 5 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "I run the DAY-CARE service.\p"
	.string "Would you like me to raise one of your\n"
	.string "POKMON?$"

Route5_PokemonDayCare_Text_ComeAgain::
# 9 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Come again.$"

Route5_PokemonDayCare_Text_WhichMonShouldIRaise::
# 13 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Which POKMON should I raise?$"

Route5_PokemonDayCare_Text_ComeAnytimeYouLike::
# 17 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Fine. Come anytime you like.$"

Route5_PokemonDayCare_Text_LookAfterMonForAWhile::
# 21 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Fine, I'll look after your\n"
	.string "{STR_VAR_1} for a while.$"

Route5_PokemonDayCare_Text_ComeSeeMeInAWhile::
# 25 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Come see me in a while.$"

Route5_PokemonDayCare_Text_MonNeedsToSpendMoreTime::
# 29 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "You're back already?\p"
	.string "Your {STR_VAR_1} needs to spend\n"
	.string "some more time with me.$"

Route5_PokemonDayCare_Text_OweMeXForMonsReturn::
# 33 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "You owe me {STR_VAR_2} for the\n"
	.string "return of this POKMON.$"

Route5_PokemonDayCare_Text_ThankYouHeresMon::
# 37 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Thank you! Here's your POKMON.$"

Route5_PokemonDayCare_Text_PlayerGotMonBack::
# 41 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "{PLAYER} got {STR_VAR_1} back\n"
	.string "from the DAY-CARE MAN.$"

Route5_PokemonDayCare_Text_OnlyHaveOneMonWithYou::
# 45 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Oh? You only have one POKMON with you.$"

Route5_PokemonDayCare_Text_WhatWillYouBattleWith::
# 49 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "If you leave me that POKMON, what will\n"
	.string "you battle with?$"

Route5_PokemonDayCare_Text_MonHasGrownByXLevels::
# 53 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "Your {STR_VAR_1} has grown a lot.\n"
	.string "Yes, quite a lot, I'd say.\p"
	.string "Let me see By level, it's grown by\n"
	.string "{STR_VAR_2}.\p"
	.string "Aren't I great?$"

Route5_PokemonDayCare_Text_YouveGotNoRoomForIt::
# 57 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "You can't take this POKMON back if\n"
	.string "you've got no room for it.$"

Route5_PokemonDayCare_Text_DontHaveEnoughMoney::
# 61 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "You don't have enough money.$"

Route5_PokemonDayCare_Text_WantMeToTakeALookAtYours::
# 65 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "$"

Route5_PokemonDayCare_Text_CantAcceptMonWithHM::
# 69 "data/maps/Route5_PokemonDayCare/scripts.pory"
	.string "$"
