CeruleanCave_B1F_MapScripts::
# 2 "data/maps/CeruleanCave_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CeruleanCave_B1F_OnResume
# 3 "data/maps/CeruleanCave_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeruleanCave_B1F_OnTransition
	.byte 0


CeruleanCave_B1F_MapScripts::
# 7 "data/maps/CeruleanCave_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CeruleanCave_B1F_OnResume
# 8 "data/maps/CeruleanCave_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeruleanCave_B1F_OnTransition
	return

