RustboroCity_CuttersHouse_MapScripts::
	.byte 0


RustboroCity_CuttersHouse_Text_YouCanPutThisHMToGoodUse::
# 5 "data/maps/RustboroCity_CuttersHouse/scripts.pory"
	.string "That determined expression That limber\n"
	.string "way you move\l"
	.string "And your well-trained POKMON\p"
	.string "You're obviously a skilled TRAINER!\p"
	.string "No, wait, don't say a word. I can tell\n"
	.string "just by looking at you.\p"
	.string "I'm sure that you can put this HIDDEN\n"
	.string "MACHINE to good use.\p"
	.string "No need to be modest or shy. Go on, take\n"
	.string "it!$"

RustboroCity_CuttersHouse_Text_ExplainCut::
# 9 "data/maps/RustboroCity_CuttersHouse/scripts.pory"
	.string "That HIDDEN MACHINE, or HM for short, is\n"
	.string "CUT.\p"
	.string "An HM move is one that can be used by\n"
	.string "POKMON outside of battle.\p"
	.string "Any POKMON that's learned CUT can chop\n"
	.string "down thin trees if the TRAINER\l"
	.string "has earned the STONE BADGE.\p"
	.string "And, unlike a TM, an HM can be used more\n"
	.string "than once.$"

RustboroCity_CuttersHouse_Text_DadHelpedClearLandOfTrees::
# 13 "data/maps/RustboroCity_CuttersHouse/scripts.pory"
	.string "When they were expanding the city of\n"
	.string "RUSTBORO, my dad helped out.\p"
	.string "He made his POKMON use CUT to clear the\n"
	.string "land of trees.$"
