Route110_TrickHousePuzzle8_MapScripts::
	.byte 0


Route110_TrickHousePuzzle8_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	msgbox Route110_TrickHousePuzzle8_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle8_EventScript_SmithNPC2::
# 51 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	msgbox Route110_TrickHousePuzzle8_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHousePuzzle8_Text_KeiraDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_KeiraDefeat$"

Route110_TrickHousePuzzle8_Text_KeiraIntro::
# 9 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_KeiraIntro$"

Route110_TrickHousePuzzle8_Text_KeiraPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_KeiraPostBattle$"

Route110_TrickHousePuzzle8_Text_LeroyDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_LeroyDefeat$"

Route110_TrickHousePuzzle8_Text_LeroyIntro::
# 21 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_LeroyIntro$"

Route110_TrickHousePuzzle8_Text_LeroyPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_LeroyPostBattle$"

Route110_TrickHousePuzzle8_Text_VincentDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_VincentDefeat$"

Route110_TrickHousePuzzle8_Text_VincentIntro::
# 33 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_VincentIntro$"

Route110_TrickHousePuzzle8_Text_VincentPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle8_Text_VincentPostBattle$"

Route110_TrickHousePuzzle8_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHousePuzzle8_Text_SmithNPC2::
# 55 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
