Route110_TrickHousePuzzle8_MapScripts::
	.byte 0


Route110_TrickHousePuzzle8_MapScripts::
	return


Route110_TrickHousePuzzle8_Text_WroteSecretCodeLockOpened::
# 8 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER I love.” … … … … … … … …\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle8_Text_VincentIntro::
# 12 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Not many TRAINERS have made it this\n"
	.string "far.$"

Route110_TrickHousePuzzle8_Text_VincentDefeat::
# 16 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "That must mean you're tough, too…$"

Route110_TrickHousePuzzle8_Text_VincentPostBattle::
# 20 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "You've beaten the POKéMON LEAGUE\n"
	.string "CHAMPION? That's too much!$"

Route110_TrickHousePuzzle8_Text_KeiraIntro::
# 24 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Consider yourself lucky to be battling\n"
	.string "me!$"

Route110_TrickHousePuzzle8_Text_KeiraDefeat::
# 28 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "This isn't right! I can't lose!$"

Route110_TrickHousePuzzle8_Text_KeiraPostBattle::
# 32 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "It's a miracle that you beat me. You can\n"
	.string "brag about it.$"

Route110_TrickHousePuzzle8_Text_LeroyIntro::
# 36 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "You've been slugging through the TRICK\n"
	.string "HOUSE challenge, too.$"

Route110_TrickHousePuzzle8_Text_LeroyDefeat::
# 40 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "I see… You possess an extraordinary\n"
	.string "style.$"

Route110_TrickHousePuzzle8_Text_LeroyPostBattle::
# 44 "data/maps/Route110_TrickHousePuzzle8/scripts.pory"
	.string "Seeing someone like you should please\n"
	.string "the TRICK MASTER.$"
