MossdeepCity_House3_MapScripts::
	.byte 0


MossdeepCity_House3_EventScript_SuperRodFisherman::
	end


MossdeepCity_House3_Text_DontYouLikeToFish::
# 8 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Hunh?\n"
	.string "Don't you like to fish?$"

MossdeepCity_House3_Text_GoAfterSeafloorPokemon::
# 12 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Go after the seafloor POKéMON with\n"
	.string "your SUPER ROD.$"
