MossdeepCity_House3_MapScripts::
	.byte 0


MossdeepCity_House3_Text_YouWantSuperRod::
# 5 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Hey there, TRAINER! A SUPER ROD really\n"
	.string "is super!\p"
	.string "Say all you want, but this baby can\n"
	.string "catch POKMON off the seafloor!\p"
	.string "What do you think? You want it, don't\n"
	.string "you?$"

MossdeepCity_House3_Text_SuperRodIsSuper::
# 9 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "You bet, you bet! After all, a SUPER ROD\n"
	.string "is really super!$"

MossdeepCity_House3_Text_TryDroppingRodInWater::
# 13 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "If there's any water, try dropping in\n"
	.string "your ROD and see what bites!$"

MossdeepCity_House3_Text_DontYouLikeToFish::
# 17 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Hunh? Don't you like to fish?$"

MossdeepCity_House3_Text_GoAfterSeafloorPokemon::
# 21 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Go after the seafloor POKMON with your\n"
	.string "SUPER ROD.$"
