MossdeepCity_House3_MapScripts::
	.byte 0


MossdeepCity_House3_MapScripts::
	return


MossdeepCity_House3_Text_YouWantSuperRod::
# 8 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Hey there, TRAINER! A SUPER ROD really\n"
	.string "is super!\p"
	.string "Say all you want, but this baby can\n"
	.string "catch POKéMON off the seafloor!\p"
	.string "What do you think? You want it, don't\n"
	.string "you?$"

MossdeepCity_House3_Text_SuperRodIsSuper::
# 12 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "You bet, you bet! After all, a SUPER ROD\n"
	.string "is really super!$"

MossdeepCity_House3_Text_TryDroppingRodInWater::
# 16 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "If there's any water, try dropping in\n"
	.string "your ROD and see what bites!$"

MossdeepCity_House3_Text_DontYouLikeToFish::
# 20 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Hunh? Don't you like to fish?$"

MossdeepCity_House3_Text_GoAfterSeafloorPokemon::
# 24 "data/maps/MossdeepCity_House3/scripts.pory"
	.string "Go after the seafloor POKéMON with\n"
	.string "your SUPER ROD.$"
