SootopolisCity_PokemonCenter_1F_MapScripts::
	.byte 0


SootopolisCity_PokemonCenter_1F_EventScript_Gentleman::
	end


SootopolisCity_PokemonCenter_1F_EventScript_Nurse::
	end


SootopolisCity_PokemonCenter_1F_EventScript_Woman::
	end


SootopolisCity_PokemonCenter_1F_Text_WallaceToughestInHoenn::
# 16 "data/maps/SootopolisCity_PokemonCenter_1F/scripts.pory"
	.string "WALLACE is rumored to be the toughest\n"
	.string "TRAINER in the whole HOENN region.\p"
	.string "This town's GYM is led by the TRAINER\n"
	.string "who taught WALLACE.\p"
	.string "But the ELITE FOUR… They're said to be\n"
	.string "even stronger than WALLACE's mentor.\p"
	.string "How strong could they be?$"

SootopolisCity_PokemonCenter_1F_Text_AlwaysBeFriendsWithPokemon::
# 20 "data/maps/SootopolisCity_PokemonCenter_1F/scripts.pory"
	.string "Whenever, wherever, and whatever\n"
	.string "happens, I will always be friends with\l"
	.string "POKéMON.\p"
	.string "Because it's fun to be with POKéMON!$"
