SixIsland_WaterPath_House2_MapScripts::
	.byte 0


SixIsland_WaterPath_House2_EventScript_Man::
# 5 "data/maps/SixIsland_WaterPath_House2/scripts.pory"
	msgbox SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe, MSGBOX_NPC
	end


SixIsland_WaterPath_House2_Text_MyNeighborMeasuredMe::
# 10 "data/maps/SixIsland_WaterPath_House2/scripts.pory"
	.string "My height is 67.0 inches on the\n"
	.string "button.\p"
	.string "I know it is this precisely because\n"
	.string "my neighbor measured me.$"
