UndergroundPath_EastEntrance_MapScripts::
	.byte 0


UndergroundPath_EastEntrance_EventScript_Woman::
# 5 "data/maps/UndergroundPath_EastEntrance/scripts.pory"
	msgbox UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore, MSGBOX_NPC
	end


UndergroundPath_EastEntrance_Text_DoYouGoToCeladonDeptStore::
# 10 "data/maps/UndergroundPath_EastEntrance/scripts.pory"
	.string "The DEPARTMENT STORE in CELADON\n"
	.string "has a great selection.\p"
	.string "Do you go there very often?$"
