AquaHideout_B1F_MapScripts::
	.byte 0


AquaHideout_B1F_EventScript_Electrode1::
	end


AquaHideout_B1F_EventScript_Electrode2::
	end


AquaHideout_B1F_EventScript_Grunt2::
# 13 "data/maps/AquaHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_2, AquaHideout_B1F_Text_Grunt2Intro, AquaHideout_B1F_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 14 "data/maps/AquaHideout_B1F/scripts.pory"
	msgbox AquaHideout_B1F_Text_Grunt2PostBattle
	return


AquaHideout_B1F_EventScript_Grunt3::
# 18 "data/maps/AquaHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_3, AquaHideout_B1F_Text_Grunt3Intro, AquaHideout_B1F_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 19 "data/maps/AquaHideout_B1F/scripts.pory"
	msgbox AquaHideout_B1F_Text_Grunt3PostBattle
	return


AquaHideout_B1F_EventScript_Grunt5::
# 23 "data/maps/AquaHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_5, AquaHideout_B1F_Text_Grunt5Intro, AquaHideout_B1F_Text_Grunt5Defeat, Text_NotEnoughMonsForDoubleBattle
# 24 "data/maps/AquaHideout_B1F/scripts.pory"
	msgbox AquaHideout_B1F_Text_Grunt5PostBattle
	return


AquaHideout_B1F_EventScript_Grunt7::
# 28 "data/maps/AquaHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_7, AquaHideout_B1F_Text_Grunt7Intro, AquaHideout_B1F_Text_Grunt7Defeat, Text_NotEnoughMonsForDoubleBattle
# 29 "data/maps/AquaHideout_B1F/scripts.pory"
	msgbox AquaHideout_B1F_Text_Grunt7PostBattle
	return


AquaHideout_B1F_Text_Grunt2Defeat::
# 33 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt2Defeat$"

AquaHideout_B1F_Text_Grunt2Intro::
# 37 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt2Intro$"

AquaHideout_B1F_Text_Grunt2PostBattle::
# 41 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt2PostBattle$"

AquaHideout_B1F_Text_Grunt3Defeat::
# 45 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt3Defeat$"

AquaHideout_B1F_Text_Grunt3Intro::
# 49 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt3Intro$"

AquaHideout_B1F_Text_Grunt3PostBattle::
# 53 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt3PostBattle$"

AquaHideout_B1F_Text_Grunt5Defeat::
# 57 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt5Defeat$"

AquaHideout_B1F_Text_Grunt5Intro::
# 61 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt5Intro$"

AquaHideout_B1F_Text_Grunt5PostBattle::
# 65 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt5PostBattle$"

AquaHideout_B1F_Text_Grunt7Defeat::
# 69 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt7Defeat$"

AquaHideout_B1F_Text_Grunt7Intro::
# 73 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt7Intro$"

AquaHideout_B1F_Text_Grunt7PostBattle::
# 77 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B1F_Text_Grunt7PostBattle$"
