AquaHideout_B1F_MapScripts::
# 2 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, AquaHideout_B1F_OnResume
# 3 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_B1F_OnTransition
	.byte 0


AquaHideout_B1F_MapScripts::
# 7 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, AquaHideout_B1F_OnResume
# 8 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_B1F_OnTransition
	return


AquaHideout_B1F_Text_Grunt2Intro::
# 12 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you want to know the secret about\n"
	.string "our HIDEOUT, you have me to beat!$"

AquaHideout_B1F_Text_Grunt2Defeat::
# 16 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I can't win at all…$"

AquaHideout_B1F_Text_Grunt2PostBattle::
# 20 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Our HIDEOUT's secret?\p"
	.string "Well, let's just say… There's a submarine\n"
	.string "at the far end!\p"
	.string "But, by now… Kekekeke…$"

AquaHideout_B1F_Text_Grunt3Intro::
# 24 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Fuel supply loaded A-OK! In-cruise\n"
	.string "snacks loaded A-OK!\p"
	.string "Nothing left to do but KO a pesky\n"
	.string "meddler!$"

AquaHideout_B1F_Text_Grunt3Defeat::
# 28 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I took a serious licking!$"

AquaHideout_B1F_Text_Grunt3PostBattle::
# 32 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Humph! This was supposed to happen!\p"
	.string "My mission was to just hold you up!$"

AquaHideout_B1F_Text_Grunt5Intro::
# 36 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Yawn… Keeping watch over the HIDEOUT\n"
	.string "bores me. I'll take you on.$"

AquaHideout_B1F_Text_Grunt5Defeat::
# 40 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Yawn… Oh, I lost…$"

AquaHideout_B1F_Text_Grunt5PostBattle::
# 44 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you scurry too much, other TEAM AQUA\n"
	.string "members might get you.$"

AquaHideout_B1F_Text_Grunt7Intro::
# 48 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Hey! You there!\p"
	.string "Which do you think is cooler? TEAM\n"
	.string "AQUA's uniform or TEAM MAGMA's?$"

AquaHideout_B1F_Text_Grunt7Defeat::
# 52 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I lost in a cool way…$"

AquaHideout_B1F_Text_Grunt7PostBattle::
# 56 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you have a cool uniform, you look\n"
	.string "good even in a loss, don't you think?$"
