AquaHideout_B1F_MapScripts::
# 2 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, AquaHideout_B1F_OnResume
# 3 "data/maps/AquaHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_B1F_OnTransition
	.byte 0


AquaHideout_B1F_Text_Grunt2Intro::
# 7 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you want to know the secret about\n"
	.string "our HIDEOUT, you have me to beat!$"

AquaHideout_B1F_Text_Grunt2Defeat::
# 11 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I can't win at all$"

AquaHideout_B1F_Text_Grunt2PostBattle::
# 15 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Our HIDEOUT's secret?\p"
	.string "Well, let's just say There's a submarine\n"
	.string "at the far end!\p"
	.string "But, by now Kekekeke$"

AquaHideout_B1F_Text_Grunt3Intro::
# 19 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Fuel supply loaded A-OK! In-cruise\n"
	.string "snacks loaded A-OK!\p"
	.string "Nothing left to do but KO a pesky\n"
	.string "meddler!$"

AquaHideout_B1F_Text_Grunt3Defeat::
# 23 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I took a serious licking!$"

AquaHideout_B1F_Text_Grunt3PostBattle::
# 27 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Humph! This was supposed to happen!\p"
	.string "My mission was to just hold you up!$"

AquaHideout_B1F_Text_Grunt5Intro::
# 31 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Yawn Keeping watch over the HIDEOUT\n"
	.string "bores me. I'll take you on.$"

AquaHideout_B1F_Text_Grunt5Defeat::
# 35 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Yawn Oh, I lost$"

AquaHideout_B1F_Text_Grunt5PostBattle::
# 39 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you scurry too much, other TEAM AQUA\n"
	.string "members might get you.$"

AquaHideout_B1F_Text_Grunt7Intro::
# 43 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "Hey! You there!\p"
	.string "Which do you think is cooler? TEAM\n"
	.string "AQUA's uniform or TEAM MAGMA's?$"

AquaHideout_B1F_Text_Grunt7Defeat::
# 47 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "I lost in a cool way$"

AquaHideout_B1F_Text_Grunt7PostBattle::
# 51 "data/maps/AquaHideout_B1F/scripts.pory"
	.string "If you have a cool uniform, you look\n"
	.string "good even in a loss, don't you think?$"
