SevenIsland_SevaultCanyon_Entrance_MapScripts::
	.byte 0


SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
# 5 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Entrance_Text_RouteSign, MSGBOX_SIGN
	end


SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
# 10 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "SEVAULT CANYON ENTRANCE\p"
	.string "TRAINERS are asked to refrain from\n"
	.string "damaging plants in the CANYON.$"
