SevenIsland_SevaultCanyon_Entrance_MapScripts::
	.byte 0


SevenIsland_SevaultCanyon_Entrance_Text_MiahIntro::
# 5 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Kyahaha! I'll flick you away\n"
	.string "effortlessly!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahDefeat::
# 9 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Tch! Too strong for me!$"

SevenIsland_SevaultCanyon_Entrance_Text_MiahPostBattle::
# 13 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "What's that? I don't act the way I look?\p"
	.string "Heh, that's a part of my strategy!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonIntro::
# 17 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Howdy! Are you a member of my fan club?$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonDefeat::
# 21 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Oh, so you're not a fan\p"
	.string "Well, I can change that. Let me sing for\n"
	.string "you!$"

SevenIsland_SevaultCanyon_Entrance_Text_MasonPostBattle::
# 25 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Lalalah My POKMON, I send them out,\l"
	.string "all the girls scream and shout!$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasIntro::
# 29 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "This island is too spread out It's not\n"
	.string "easy patrolling the place.$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasDefeat::
# 33 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "Uh-huh$"

SevenIsland_SevaultCanyon_Entrance_Text_NicolasPostBattle::
# 37 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "TRAINERS like you from cities, they\n"
	.string "sure are tough.\p"
	.string "You'll be headed for the TOWER, won't\n"
	.string "you?$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineIntro::
# 41 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "I punish people who abuse POKMON!$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelineDefeat::
# 45 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "You don't seem to be a problem TRAINER.$"

SevenIsland_SevaultCanyon_Entrance_Text_MadelinePostBattle::
# 49 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "If you treat your POKMON with kindness,\n"
	.string "they'll understand.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveIntro::
# 53 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "EVE: I'll team up with JON and battle\n"
	.string "together.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveDefeat::
# 57 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "EVE: Me and JON, we lost. Ehehe.$"

SevenIsland_SevaultCanyon_Entrance_Text_EvePostBattle::
# 61 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "EVE: I'm going to work harder with JON.$"

SevenIsland_SevaultCanyon_Entrance_Text_EveNotEnoughMons::
# 65 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "EVE: I want to team up with JON when I\n"
	.string "battle you.\p"
	.string "Come back with two POKMON, okay?$"

SevenIsland_SevaultCanyon_Entrance_Text_JonIntro::
# 69 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "JON: When I'm with EVE, it feels like we\n"
	.string "could never lose.$"

SevenIsland_SevaultCanyon_Entrance_Text_JonDefeat::
# 73 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "JON: When I'm with EVE, it doesn't feel\n"
	.string "like I've lost!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonPostBattle::
# 77 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "JON: When I'm with EVE, I feel giddy\n"
	.string "whether I win or lose.\p"
	.string "It's magical!$"

SevenIsland_SevaultCanyon_Entrance_Text_JonNotEnoughMons::
# 81 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "JON: If it's with EVE, I'll be happy to\n"
	.string "battle with you.\p"
	.string "So, I'd like to make it a two-on-two\n"
	.string "battle, if I may.$"

SevenIsland_SevaultCanyon_Entrance_Text_RouteSign::
# 85 "data/maps/SevenIsland_SevaultCanyon_Entrance/scripts.pory"
	.string "SEVAULT CANYON ENTRANCE\p"
	.string "TRAINERS are asked to refrain from\n"
	.string "damaging plants in the CANYON.$"
