Route12_MapScripts::
# 2 "data/maps/Route12/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route12_OnResume
	.byte 0


Route12_Text_MonSprawledOutInSlumber::
# 6 "data/maps/Route12/scripts.pory"
	.string "A POKMON is sprawled out in a deep and\n"
	.string "comfortable slumber.$"

Text_SnorlaxWokeUp::
# 10 "data/maps/Route12/scripts.pory"
	.string "SNORLAX woke up!\p"
	.string "It attacked in a grumpy rage!$"

Text_SnorlaxReturnedToMountains::
# 14 "data/maps/Route12/scripts.pory"
	.string "SNORLAX calmed down. It gave a huge\n"
	.string "yawn\l"
	.string "And returned to the mountains.$"

Text_WantToUsePokeFlute::
# 18 "data/maps/Route12/scripts.pory"
	.string "Want to use the POK FLUTE?$"

Text_PlayedPokeFlute::
# 22 "data/maps/Route12/scripts.pory"
	.string "{PLAYER} played the POK FLUTE.$"

Route12_Text_NedIntro::
# 26 "data/maps/Route12/scripts.pory"
	.string "Yeah! I got a bite here!$"

Route12_Text_NedDefeat::
# 30 "data/maps/Route12/scripts.pory"
	.string "Tch! Just a small fry$"

Route12_Text_NedPostBattle::
# 34 "data/maps/Route12/scripts.pory"
	.string "Hang on! My line's snagged!$"

Route12_Text_ChipIntro::
# 38 "data/maps/Route12/scripts.pory"
	.string "Be patient. Fishing is a waiting game.$"

Route12_Text_ChipDefeat::
# 42 "data/maps/Route12/scripts.pory"
	.string "That one got away!$"

Route12_Text_ChipPostBattle::
# 46 "data/maps/Route12/scripts.pory"
	.string "With a better ROD, I could catch better\n"
	.string "POKMON$"

Route12_Text_JustinIntro::
# 50 "data/maps/Route12/scripts.pory"
	.string "I'm searching for a MOON STONE. Have\n"
	.string "you found one?$"

Route12_Text_JustinDefeat::
# 54 "data/maps/Route12/scripts.pory"
	.string "Oww!$"

Route12_Text_JustinPostBattle::
# 58 "data/maps/Route12/scripts.pory"
	.string "I could have made my POKMON evolve with\n"
	.string "a MOON STONE.\p"
	.string "I would have won then, I bet.$"

Route12_Text_LucaIntro::
# 62 "data/maps/Route12/scripts.pory"
	.string "Electricity is my specialty.\p"
	.string "I don't know a thing about POKMON of\n"
	.string "the sea, though.$"

Route12_Text_LucaDefeat::
# 66 "data/maps/Route12/scripts.pory"
	.string "Unplugged!$"

Route12_Text_LucaPostBattle::
# 70 "data/maps/Route12/scripts.pory"
	.string "Water conducts electricity, so you\n"
	.string "should zap sea POKMON.$"

Route12_Text_HankIntro::
# 74 "data/maps/Route12/scripts.pory"
	.string "The FISHING FOOL versus POKMON KID!$"

Route12_Text_HankDefeat::
# 78 "data/maps/Route12/scripts.pory"
	.string "Touch too much!$"

Route12_Text_HankPostBattle::
# 82 "data/maps/Route12/scripts.pory"
	.string "I guess you get to be good at what you\n"
	.string "like.\p"
	.string "Well, you beat me at POKMON, but you\n"
	.string "can't top me at fishing.$"

Route12_Text_ElliotIntro::
# 86 "data/maps/Route12/scripts.pory"
	.string "I love fishing, don't get me wrong.\p"
	.string "But it'd be best if I also had more work.$"

Route12_Text_ElliotDefeat::
# 90 "data/maps/Route12/scripts.pory"
	.string "It's not easy$"

Route12_Text_ElliotPostBattle::
# 94 "data/maps/Route12/scripts.pory"
	.string "It's all right. Losing doesn't bug me\n"
	.string "anymore.$"

Route12_Text_AndrewIntro::
# 98 "data/maps/Route12/scripts.pory"
	.string "What's catching?\p"
	.string "You never know what you could catch!$"

Route12_Text_AndrewDefeat::
# 102 "data/maps/Route12/scripts.pory"
	.string "Lost it!$"

Route12_Text_AndrewPostBattle::
# 106 "data/maps/Route12/scripts.pory"
	.string "What, MAGIKARP?\p"
	.string "I catch them all the time, sure. But, boy\n"
	.string "are they wimpy.$"

Route12_Text_RouteSign::
# 110 "data/maps/Route12/scripts.pory"
	.string "ROUTE 12 North to LAVENDER$"

Route12_Text_SportfishingArea::
# 114 "data/maps/Route12/scripts.pory"
	.string "SPORTFISHING AREA$"

Route12_Text_JesIntro::
# 118 "data/maps/Route12/scripts.pory"
	.string "JES: If I win, I'm going to propose to\n"
	.string "GIA.$"

Route12_Text_JesDefeat::
# 122 "data/maps/Route12/scripts.pory"
	.string "JES: Oh, please, why couldn't you let us\n"
	.string "win?$"

Route12_Text_JesPostBattle::
# 126 "data/maps/Route12/scripts.pory"
	.string "JES: Oh, GIA, forgive me, my love!$"

Route12_Text_JesNotEnoughMons::
# 130 "data/maps/Route12/scripts.pory"
	.string "JES: GIA and I, we'll be together\n"
	.string "forever.\p"
	.string "We won't battle unless you have two\n"
	.string "POKMON of your own.$"

Route12_Text_GiaIntro::
# 134 "data/maps/Route12/scripts.pory"
	.string "GIA: Hey, JES\p"
	.string "If we win, I'll marry you!$"

Route12_Text_GiaDefeat::
# 138 "data/maps/Route12/scripts.pory"
	.string "GIA: Oh, but why?$"

Route12_Text_GiaPostBattle::
# 142 "data/maps/Route12/scripts.pory"
	.string "GIA: JES, you silly! You ruined this!$"

Route12_Text_GiaNotEnoughMons::
# 146 "data/maps/Route12/scripts.pory"
	.string "GIA: I can't bear to battle without my\n"
	.string "JES!\p"
	.string "Don't you have one more POKMON?$"
