Route109_MapScripts::
	.byte 0


Route109_MapScripts::
	return


DewfordTown_Text_BrineyLandedInSlateportDeliverGoods::
# 8 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: Ahoy! We've made land in\n"
	.string "SLATEPORT!\p"
	.string "I suppose you're going to visit CAPT.\n"
	.string "STERN and deliver the DEVON GOODS?$"

Route109_Text_BrineySailToDewfordQuestion::
# 12 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: I thought you're supposed\n"
	.string "to deliver the DEVON GOODS.\p"
	.string "Would you like to sail back to DEWFORD,\n"
	.string "then?$"

Route109_Text_BrineyDewfordItIs::
# 16 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: DEWFORD it is, then!\p"
	.string "Anchors aweigh! PEEKO, we're setting\n"
	.string "sail, my darling!$"

Route109_Text_BrineyDeliverDevonGoods::
# 20 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: Then you go on and deliver\n"
	.string "the DEVON GOODS. I'll be waiting.$"

DewfordTown_Text_BrineyLandedInSlateport::
# 24 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: Ahoy! We've made land in\n"
	.string "SLATEPORT!\p"
	.string "You just go on and tell me whenever you\n"
	.string "want to set sail again!$"

Route109_Text_BrineyWhereAreWeBound::
# 28 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: Ahoy! For you, I'll go out to\n"
	.string "sea anytime!\p"
	.string "Now, my friend, where are we bound?$"

Route109_Text_BrineyTellMeWhenYouNeedToSail::
# 32 "data/maps/Route109/scripts.pory"
	.string "MR. BRINEY: You just tell me whenever\n"
	.string "you need to set sail again!$"

Route109_Text_ChillAtMyPapasSpot::
# 36 "data/maps/Route109/scripts.pory"
	.string "Yo, TRAINERS! Whether you're hot to\n"
	.string "trot,\l"
	.string "or cool cat not,\l"
	.string "chill at my papa's spot!$"

Route109_Text_LittleKidsDartAround::
# 40 "data/maps/Route109/scripts.pory"
	.string "Little kids can dart around so quickly…\p"
	.string "You don't dare take your eyes off them\n"
	.string "for an instant. It's very taxing.\p"
	.string "Mine are with my POKéMON, so they\n"
	.string "should be okay, but…$"

Route109_Text_SandCastleTakingLongTime::
# 44 "data/maps/Route109/scripts.pory"
	.string "Our sand castle's taking a long time to\n"
	.string "make.$"

Route109_Text_YouCanHaveThis::
# 48 "data/maps/Route109/scripts.pory"
	.string "You can have this!$"

Route109_Text_WereGoingToMakeBigCastle::
# 52 "data/maps/Route109/scripts.pory"
	.string "We're going to get all the sand from the\n"
	.string "beach and make a big castle!\p"
	.string "And then we're going to be a king and\n"
	.string "queen.\p"
	.string "We'll let you be a servant.$"

Route109_Text_ZigzagoonPicksUpLitter::
# 56 "data/maps/Route109/scripts.pory"
	.string "The water around these parts is clean.\p"
	.string "But, I get my ZIGZAGOON to pick up\n"
	.string "litter from the shoreline at times.\p"
	.string "Dirty water becomes rain and joins our\n"
	.string "rivers, which we drink from…\p"
	.string "If we pollute the sea, it all comes back\n"
	.string "to haunt us eventually.$"

Route109_Text_ZigzagoonCry::
# 60 "data/maps/Route109/scripts.pory"
	.string "ZIGZAGOON: Guguu?$"

Route109_Text_SeashoreHouseSign::
# 64 "data/maps/Route109/scripts.pory"
	.string "SEASHORE HOUSE\p"
	.string "“May hot battles rage on hot sands! The\n"
	.string "place for hot TRAINERS!”$"

Route109_Text_TrainerTipsSign::
# 68 "data/maps/Route109/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "POKéMON at the same level may not\n"
	.string "always have identical stats.\p"
	.string "POKéMON raised by TRAINERS are said to\n"
	.string "grow stronger than wild POKéMON.$"
