Route123_MapScripts::
# 2 "data/maps/Route123/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route123_OnTransition
	.byte 0


Route123_MapScripts::
# 6 "data/maps/Route123/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route123_OnTransition
	return


Route123_Text_LoveGrassMonsHaveAny::
# 10 "data/maps/Route123/scripts.pory"
	.string "I love GRASS-type POKéMON!\p"
	.string "Do you have any GRASS-type POKéMON?$"

Route123_Text_YouLikeGrassMonsTooHaveThis::
# 14 "data/maps/Route123/scripts.pory"
	.string "Oh?\p"
	.string "You like GRASS-type POKéMON, too, don't\n"
	.string "you?\p"
	.string "I'm so happy, you can have this! It's a\n"
	.string "token of our friendship.$"

Route123_Text_CheckTreesWithMyGrassMon::
# 18 "data/maps/Route123/scripts.pory"
	.string "I check trees with my GRASS-type\n"
	.string "POKéMON. I'm like a tree doctor.$"

Route123_Text_RouteSign::
# 22 "data/maps/Route123/scripts.pory"
	.string "{RIGHT_ARROW} ROUTE 123 {LEFT_ARROW} ROUTE 118$"

Route123_Text_RouteSignMtPyre::
# 26 "data/maps/Route123/scripts.pory"
	.string "{UP_ARROW} MT. PYRE “Forbidden to the faint of\n"
	.string "heart.”$"

Route123_Text_BerryMastersHouse::
# 30 "data/maps/Route123/scripts.pory"
	.string "BERRY MASTER'S HOUSE$"
