PetalburgCity_WallysHouse_MapScripts::
# 2 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_WallysHouse_OnFrame
# 3 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PetalburgCity_WallysHouse_OnWarp
	.byte 0


PetalburgCity_WallysHouse_Text_ThanksForPlayingWithWally::
# 7 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "You're… Ah, you must be {PLAYER}{KUN},\n"
	.string "right?\p"
	.string "Thank you for playing with WALLY a\n"
	.string "little while ago.\p"
	.string "He's been frail and sickly ever since he\n"
	.string "was a baby.\p"
	.string "We've sent him to stay with my relatives\n"
	.string "in VERDANTURF TOWN for a while.\p"
	.string "The air is a lot cleaner there than it is\n"
	.string "here.\p"
	.string "What's that? Where's WALLY? He's\n"
	.string "already left, our WALLY.\p"
	.string "I wonder where he could have gotten by\n"
	.string "now?$"

PetalburgCity_WallysHouse_Text_WonderHowWallyIsDoing::
# 11 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "I wonder how our WALLY is doing?$"

PetalburgCity_WallysHouse_Text_PleaseExcuseUs::
# 15 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "{PLAYER}{KUN}! Please excuse us for\n"
	.string "dragging you here this way.\p"
	.string "But our WALLY's become very healthy\n"
	.string "since he went to VERDANTURF TOWN.\p"
	.string "We owe it all to you!\p"
	.string "When WALLY left town, you helped him\n"
	.string "catch a POKéMON, right?\p"
	.string "I think that made WALLY really happy.\p"
	.string "Actually, not just WALLY. It made me,\n"
	.string "his father, happy too.\p"
	.string "Happy that he's gained such a great\n"
	.string "friend as you.\p"
	.string "This isn't a bribe or anything, but I'd\n"
	.string "really like you to have this.$"

PetalburgCity_WallysHouse_Text_SurfGoAllSortsOfPlaces::
# 19 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "If your POKéMON can SURF, you'll be able\n"
	.string "to go to all sorts of places.$"

PetalburgCity_WallysHouse_Text_WallyIsComingHomeSoon::
# 23 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "WALLY's coming home soon. I'm looking\n"
	.string "forward to that.$"

PetalburgCity_WallysHouse_Text_YouMetWallyInEverGrandeCity::
# 27 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "Oh? You met WALLY in EVER GRANDE CITY?\p"
	.string "Oh, {PLAYER}{KUN}, don't be silly.\p"
	.string "He may have gotten healthy, but he\n"
	.string "can't go somewhere far away like\l"
	.string "that all by himself.$"

PetalburgCity_WallysHouse_Text_WallyWasReallyHappy::
# 31 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "WALLY was really happy when he told us\n"
	.string "that he caught a POKéMON.\p"
	.string "It's been ages since I've seen him smile\n"
	.string "like that.$"

PetalburgCity_WallysHouse_Text_WallyLeftWithoutTelling::
# 35 "data/maps/PetalburgCity_WallysHouse/scripts.pory"
	.string "I want you to keep this a secret from\n"
	.string "my husband…\p"
	.string "But our WALLY left VERDANTURF TOWN\n"
	.string "without telling anyone.\p"
	.string "You know, WALLY is frail, but he's\n"
	.string "surprisingly strong-willed.\p"
	.string "I'm sure that he'll come back safe and\n"
	.string "sound one day!$"
