SaffronCity_Gym_MapScripts::
	.byte 0


SaffronCity_Gym_Text_SabrinaIntro::
# 5 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I had a vision of your arrival.\p"
	.string "I have had psychic powers since I was a\n"
	.string "child.\p"
	.string "It started when a spoon I carelessly\n"
	.string "tossed, bent.\p"
	.string "I dislike battling, but if you wish, I will\n"
	.string "show you my powers!{PLAY_BGM}{MUS_RG_GYM}$"

SaffronCity_Gym_Text_SabrinaDefeat::
# 9 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "This loss shocks me! But, a loss is a\n"
	.string "loss.\p"
	.string "I admit, I didn't work hard enough to\n"
	.string "win.\p"
	.string "Your victory has earned you the\n"
	.string "MARSHBADGE.$"

SaffronCity_Gym_Text_SabrinaPostBattle::
# 13 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Psychic power isn't something that only\n"
	.string "a few people have.\p"
	.string "Everyone has psychic power. People\n"
	.string "just don't realize it.$"

SaffronCity_Gym_Text_ExplainMarshBadgeTakeThis::
# 17 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "The MARSHBADGE makes POKéMON up to Lv.\n"
	.string "70 obey you.\p"
	.string "Stronger POKéMON will become wild,\n"
	.string "ignoring your orders in battle.\p"
	.string "Just don't raise your POKéMON too much\n"
	.string "to avoid that problem.\p"
	.string "Wait, please take this TM with you.$"

SaffronCity_Gym_Text_ReceivedTM04FromSabrina::
# 21 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "{PLAYER} received TM04 from SABRINA.$"

SaffronCity_Gym_Text_ExplainTM04::
# 25 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "TM04 is CALM MIND.\p"
	.string "It makes the POKéMON concentrate to\n"
	.string "raise both SP. ATK and SP. DEF.$"

SaffronCity_Gym_Text_BagFullOfOtherItems::
# 29 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Your BAG is full of other items.$"

SaffronCity_Gym_Text_AmandaIntro::
# 33 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SABRINA is far younger than I, but she\n"
	.string "has earned my respect.$"

SaffronCity_Gym_Text_AmandaDefeat::
# 37 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Not good enough!$"

SaffronCity_Gym_Text_AmandaPostBattle::
# 41 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "In a battle of equals, the one with the\n"
	.string "stronger will wins.\p"
	.string "If you wish to beat SABRINA, focus and\n"
	.string "will yourself to victory.$"

SaffronCity_Gym_Text_JohanIntro::
# 45 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Does our unseen power scare you?$"

SaffronCity_Gym_Text_JohanDefeat::
# 49 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I never foresaw this!$"

SaffronCity_Gym_Text_JohanPostBattle::
# 53 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "PSYCHIC POKéMON fear only ghosts and\n"
	.string "bugs!$"

SaffronCity_Gym_Text_StacyIntro::
# 57 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "POKéMON take on the appearance of\n"
	.string "their TRAINERS.\p"
	.string "Your POKéMON must be tough, then!$"

SaffronCity_Gym_Text_StacyDefeat::
# 61 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I knew it!$"

SaffronCity_Gym_Text_StacyPostBattle::
# 65 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I have much to learn still…\p"
	.string "I must master PSYCHIC and teach it to\n"
	.string "my POKéMON…$"

SaffronCity_Gym_Text_TyronIntro::
# 69 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "You understand, don't you?\p"
	.string "That power alone isn't enough to win in\n"
	.string "the world of POKéMON?$"

SaffronCity_Gym_Text_TyronDefeat::
# 73 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I don't believe this!$"

SaffronCity_Gym_Text_TyronPostBattle::
# 77 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SABRINA just wiped out the KARATE\n"
	.string "MASTER next door.$"

SaffronCity_Gym_Text_TashaIntro::
# 81 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "You and I, our POKéMON shall battle!$"

SaffronCity_Gym_Text_TashaDefeat::
# 85 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I lost after all!$"

SaffronCity_Gym_Text_TashaPostBattle::
# 89 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "I knew that this was going to take\n"
	.string "place.$"

SaffronCity_Gym_Text_CameronIntro::
# 93 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SABRINA is young, but she's also our\n"
	.string "highly skilled LEADER.\p"
	.string "You won't reach her easily!$"

SaffronCity_Gym_Text_CameronDefeat::
# 97 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Ow! Down and out!$"

SaffronCity_Gym_Text_CameronPostBattle::
# 101 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "There used to be two POKéMON GYMS in\n"
	.string "SAFFRON.\p"
	.string "The FIGHTING DOJO next door lost its\n"
	.string "GYM status, though.\p"
	.string "We simply creamed them when we decided\n"
	.string "to have just one GYM.$"

SaffronCity_Gym_Text_PrestonIntro::
# 105 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SAFFRON POKéMON GYM is famous for\n"
	.string "training psychics.\p"
	.string "You want to see SABRINA, don't you? I\n"
	.string "can tell!$"

SaffronCity_Gym_Text_PrestonDefeat::
# 109 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Arrrgh!$"

SaffronCity_Gym_Text_PrestonPostBattle::
# 113 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "That's right! I used telepathy to read\n"
	.string "your mind!$"

SaffronCity_Gym_Text_GymGuyAdvice::
# 117 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "SABRINA's POKéMON use psychic power\n"
	.string "instead of force.\p"
	.string "FIGHTING POKéMON are especially weak\n"
	.string "against PSYCHIC POKéMON.\p"
	.string "They'll get destroyed before they can\n"
	.string "even aim a punch!$"

SaffronCity_Gym_Text_GymGuyPostVictory::
# 121 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "Psychic power, huh?\p"
	.string "If I had that, I'd make a bundle at the\n"
	.string "slots!$"

SaffronCity_Gym_Text_GymStatue::
# 125 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SAFFRON POKéMON GYM LEADER: SABRINA\p"
	.string "WINNING TRAINERS: {RIVAL}$"

SaffronCity_Gym_Text_GymStatuePlayerWon::
# 129 "data/maps/SaffronCity_Gym/scripts.pory"
	.string "SAFFRON POKéMON GYM LEADER: SABRINA\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
