PewterCity_Mart_MapScripts::
	.byte 0


PewterCity_Mart_EventScript_Boy::
# 5 "data/maps/PewterCity_Mart/scripts.pory"
	msgbox PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently, MSGBOX_NPC
	end


PewterCity_Mart_EventScript_Clerk::
	end


PewterCity_Mart_EventScript_Youngster::
# 14 "data/maps/PewterCity_Mart/scripts.pory"
	msgbox PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy, MSGBOX_NPC
	end


PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
# 19 "data/maps/PewterCity_Mart/scripts.pory"
	.string "Good things can happen if you raise\n"
	.string "POKéMON diligently.\p"
	.string "Even the weak ones can surprise\n"
	.string "you if you don't give up on them.$"

PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
# 23 "data/maps/PewterCity_Mart/scripts.pory"
	.string "A shady old guy sucked me into\n"
	.string "buying this weird fish POKéMON!\p"
	.string "It's totally weak and it cost ¥500!$"
