PewterCity_Mart_MapScripts::
	.byte 0


PewterCity_Mart_Text_BoughtWeirdFishFromShadyGuy::
# 5 "data/maps/PewterCity_Mart/scripts.pory"
	.string "A shady old guy sucked me into buying\n"
	.string "this weird fish POKMON!\p"
	.string "It's totally weak and it cost 500!$"

PewterCity_Mart_Text_GoodThingsIfRaiseMonsDiligently::
# 9 "data/maps/PewterCity_Mart/scripts.pory"
	.string "Good things can happen if you raise\n"
	.string "POKMON diligently.\p"
	.string "Even the weak ones can surprise you if\n"
	.string "you don't give up on them.$"
