PokemonTower_6F_MapScripts::
	.byte 0


PokemonTower_6F_Text_AngelicaIntro::
# 5 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Giveme blood$"

PokemonTower_6F_Text_AngelicaDefeat::
# 9 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Groan!$"

PokemonTower_6F_Text_AngelicaPostBattle::
# 13 "data/maps/PokemonTower_6F/scripts.pory"
	.string "I feel anemic and weak$"

PokemonTower_6F_Text_EmiliaIntro::
# 17 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Urff Kwaah!$"

PokemonTower_6F_Text_EmiliaDefeat::
# 21 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Something fell out!$"

PokemonTower_6F_Text_EmiliaPostBattle::
# 25 "data/maps/PokemonTower_6F/scripts.pory"
	.string "My hair didn't fall out! It was a\n"
	.string "malevolent spirit!$"

PokemonTower_6F_Text_JenniferIntro::
# 29 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Kekeke kekeke!$"

PokemonTower_6F_Text_JenniferDefeat::
# 33 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Keee!$"

PokemonTower_6F_Text_JenniferPostBattle::
# 37 "data/maps/PokemonTower_6F/scripts.pory"
	.string "What's going on here?$"

PokemonTower_6F_Text_BeGoneIntruders::
# 41 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Be gone Intruders$"

PokemonTower_6F_Text_GhostWasCubonesMother::
# 45 "data/maps/PokemonTower_6F/scripts.pory"
	.string "The ghost was the restless spirit of\n"
	.string "CUBONE's mother!$"

PokemonTower_6F_Text_MothersSpiritWasCalmed::
# 49 "data/maps/PokemonTower_6F/scripts.pory"
	.string "The mother's spirit was calmed.\p"
	.string "It departed to the afterlife$"
