PokemonTower_6F_MapScripts::
	.byte 0


PokemonTower_6F_EventScript_Angelica::
# 5 "data/maps/PokemonTower_6F/scripts.pory"
	trainerbattle_double TRAINER_CHANNELER_ANGELICA, PokemonTower_6F_Text_AngelicaIntro, PokemonTower_6F_Text_AngelicaDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/PokemonTower_6F/scripts.pory"
	msgbox PokemonTower_6F_Text_AngelicaPostBattle
	return


PokemonTower_6F_EventScript_Emilia::
# 10 "data/maps/PokemonTower_6F/scripts.pory"
	trainerbattle_double TRAINER_CHANNELER_EMILIA, PokemonTower_6F_Text_EmiliaIntro, PokemonTower_6F_Text_EmiliaDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/PokemonTower_6F/scripts.pory"
	msgbox PokemonTower_6F_Text_EmiliaPostBattle
	return


PokemonTower_6F_EventScript_Jennifer::
# 15 "data/maps/PokemonTower_6F/scripts.pory"
	trainerbattle_double TRAINER_CHANNELER_JENNIFER, PokemonTower_6F_Text_JenniferIntro, PokemonTower_6F_Text_JenniferDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/PokemonTower_6F/scripts.pory"
	msgbox PokemonTower_6F_Text_JenniferPostBattle
	return


PokemonTower_6F_EventScript_MarowakGhost::
	end


PokemonTower_6F_Text_AngelicaDefeat::
# 25 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_AngelicaDefeat$"

PokemonTower_6F_Text_AngelicaIntro::
# 29 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_AngelicaIntro$"

PokemonTower_6F_Text_AngelicaPostBattle::
# 33 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_AngelicaPostBattle$"

PokemonTower_6F_Text_EmiliaDefeat::
# 37 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_EmiliaDefeat$"

PokemonTower_6F_Text_EmiliaIntro::
# 41 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_EmiliaIntro$"

PokemonTower_6F_Text_EmiliaPostBattle::
# 45 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_EmiliaPostBattle$"

PokemonTower_6F_Text_JenniferDefeat::
# 49 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_JenniferDefeat$"

PokemonTower_6F_Text_JenniferIntro::
# 53 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_JenniferIntro$"

PokemonTower_6F_Text_JenniferPostBattle::
# 57 "data/maps/PokemonTower_6F/scripts.pory"
	.string "Placeholder text for\n"
	.string "PokemonTower_6F_Text_JenniferPostBattle$"
