Route127_MapScripts::
	.byte 0


Route127_EventScript_Aidan::
# 5 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_AIDAN, Route127_Text_AidanIntro, Route127_Text_AidanDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_AidanPostBattle
	return


Route127_EventScript_Athena::
# 10 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_ATHENA, Route127_Text_AthenaIntro, Route127_Text_AthenaDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_AthenaPostBattle
	return


Route127_EventScript_Camden::
# 15 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_CAMDEN, Route127_Text_CamdenIntro, Route127_Text_CamdenDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_CamdenPostBattle
	return


Route127_EventScript_Donny::
# 20 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_DONNY, Route127_Text_DonnyIntro, Route127_Text_DonnyDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_DonnyPostBattle
	return


Route127_EventScript_Henry::
# 25 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_HENRY, Route127_Text_HenryIntro, Route127_Text_HenryDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_HenryPostBattle
	return


Route127_EventScript_Jonah::
# 30 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_JONAH, Route127_Text_JonahIntro, Route127_Text_JonahDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_JonahPostBattle
	return


Route127_EventScript_Koji::
# 35 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_KOJI, Route127_Text_KojiIntro, Route127_Text_KojiDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_KojiPostBattle
	return


Route127_EventScript_Roger::
# 40 "data/maps/Route127/scripts.pory"
	trainerbattle_double TRAINER_ROGER, Route127_Text_RogerIntro, Route127_Text_RogerDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route127/scripts.pory"
	msgbox Route127_Text_RogerPostBattle
	return


Route127_Text_AidanDefeat::
# 46 "data/maps/Route127/scripts.pory"
	.string "Whew… I give up.$"

Route127_Text_AidanIntro::
# 50 "data/maps/Route127/scripts.pory"
	.string "BIRD POKéMON have excellent vision.\n"
	.string "They spot prey from great heights.$"

Route127_Text_AidanPostBattle::
# 54 "data/maps/Route127/scripts.pory"
	.string "There're lots of diving spots in the sea\n"
	.string "around here.\p"
	.string "You can spot them easily from the sky\n"
	.string "because of their darker color.$"

Route127_Text_AthenaDefeat::
# 58 "data/maps/Route127/scripts.pory"
	.string "You didn't give me the chance to do any\n"
	.string "strategizing.$"

Route127_Text_AthenaIntro::
# 62 "data/maps/Route127/scripts.pory"
	.string "We should have a slow and methodical\n"
	.string "match.$"

Route127_Text_AthenaPostBattle::
# 66 "data/maps/Route127/scripts.pory"
	.string "When I'm surrounded by the blue sea and\n"
	.string "sky, it feels as if time slows down.$"

Route127_Text_CamdenDefeat::
# 70 "data/maps/Route127/scripts.pory"
	.string "Awawawawawa…$"

Route127_Text_CamdenIntro::
# 74 "data/maps/Route127/scripts.pory"
	.string "I can see it in your face. You want to\n"
	.string "challenge me.$"

Route127_Text_CamdenPostBattle::
# 78 "data/maps/Route127/scripts.pory"
	.string "A well-played match leaves me feeling\n"
	.string "refreshed and serene.$"

Route127_Text_DonnyDefeat::
# 82 "data/maps/Route127/scripts.pory"
	.string "Arrrgh! I hate losing!$"

Route127_Text_DonnyIntro::
# 86 "data/maps/Route127/scripts.pory"
	.string "Do you have a rival whom you just hate\n"
	.string "to lose against?$"

Route127_Text_DonnyPostBattle::
# 90 "data/maps/Route127/scripts.pory"
	.string "If you have a rival, don't you get the\n"
	.string "feeling that you have to keep getting\l"
	.string "better?$"

Route127_Text_HenryDefeat::
# 94 "data/maps/Route127/scripts.pory"
	.string "I can't keep up!$"

Route127_Text_HenryIntro::
# 98 "data/maps/Route127/scripts.pory"
	.string "Whoops! Don't tell me I snagged a\n"
	.string "SURFING POKéMON?$"

Route127_Text_HenryPostBattle::
# 102 "data/maps/Route127/scripts.pory"
	.string "It'd be a handful if I hooked your tough\n"
	.string "POKéMON!$"

Route127_Text_JonahDefeat::
# 106 "data/maps/Route127/scripts.pory"
	.string "Though I have lost, my heart remains\n"
	.string "calm…$"

Route127_Text_JonahIntro::
# 110 "data/maps/Route127/scripts.pory"
	.string "Through fishing, I have attained a\n"
	.string "state of becalmed serenity…\p"
	.string "Please, allow me to demonstrate…$"

Route127_Text_JonahPostBattle::
# 114 "data/maps/Route127/scripts.pory"
	.string "It matters not that I catch nothing.\n"
	.string "The line remains in the water…$"

Route127_Text_KojiDefeat::
# 118 "data/maps/Route127/scripts.pory"
	.string "Yowch! I got a pebble under a toenail!$"

Route127_Text_KojiIntro::
# 122 "data/maps/Route127/scripts.pory"
	.string "Run in your bare feet. That will toughen\n"
	.string "up your soles!$"

Route127_Text_KojiPostBattle::
# 126 "data/maps/Route127/scripts.pory"
	.string "Going barefoot feels great. But your\n"
	.string "RUNNING SHOES are cool, too.$"

Route127_Text_RogerDefeat::
# 130 "data/maps/Route127/scripts.pory"
	.string "No! My line's all tangled! The party's\n"
	.string "over!$"

Route127_Text_RogerIntro::
# 134 "data/maps/Route127/scripts.pory"
	.string "Well, hey! This is a match between a\n"
	.string "POKéMON fan and a fishing buff!$"

Route127_Text_RogerPostBattle::
# 138 "data/maps/Route127/scripts.pory"
	.string "My fishing line's doing a dance! The\n"
	.string "tangle tango! Hahaha, snarl!$"
