PowerPlant_MapScripts::
# 2 "data/maps/PowerPlant/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PowerPlant_OnResume
# 3 "data/maps/PowerPlant/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PowerPlant_OnTransition
	.byte 0


PowerPlant_MapScripts::
# 7 "data/maps/PowerPlant/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PowerPlant_OnResume
# 8 "data/maps/PowerPlant/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PowerPlant_OnTransition
	return

