BattleFrontier_ExchangeServiceCorner_MapScripts::
	.byte 0


BattleFrontier_ExchangeServiceCorner_Text_WelcomePleaseChoosePrize::
# 5 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Hello, this is the EXCHANGE SERVICE\n"
	.string "CORNER.\p"
	.string "We exchange the Battle Points you have\n"
	.string "collected for lovely prizes.\p"
	.string "Please choose a prize from this list.$"

BattleFrontier_ExchangeServiceCorner_Text_PleaseChoosePrize::
# 9 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Please choose a prize from this list.$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmKissPoster::
# 13 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the KISS POSTER. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmKissCushion::
# 17 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the KISS CUSHION. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmSmoochumDoll::
# 21 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the SMOOCHUM DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmTogepiDoll::
# 25 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the TOGEPI DOLL. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmMeowthDoll::
# 29 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the MEOWTH DOLL. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmClefairyDoll::
# 33 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CLEFAIRY DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmDittoDoll::
# 37 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the DITTO DOLL. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmCyndaquilDoll::
# 41 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CYNDAQUIL DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmChikoritaDoll::
# 45 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CHIKORITA DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmTotodileDoll::
# 49 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the TOTODILE DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmLaprasDoll::
# 53 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the LAPRAS DOLL. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmSnorlaxDoll::
# 57 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the SNORLAX DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmVenusaurDoll::
# 61 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the VENUSAUR DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmCharizardDoll::
# 65 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CHARIZARD DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmBlastoiseDoll::
# 69 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the BLASTOISE DOLL. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmProtein::
# 73 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the PROTEIN. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmCalcium::
# 77 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CALCIUM. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmIron::
# 81 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the IRON. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmZinc::
# 85 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the ZINC. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmCarbos::
# 89 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CARBOS. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmHPUp::
# 93 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the HP UP. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmBrightpowder::
# 97 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the BRIGHTPOWDER. Is\n"
	.string "that correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmWhiteHerb::
# 101 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the WHITE HERB. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmQuickClaw::
# 105 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the QUICK CLAW. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmMentalHerb::
# 109 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the MENTAL HERB. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmChoiceBand::
# 113 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the CHOICE BAND. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmKingsRock::
# 117 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the KING'S ROCK. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmFocusBand::
# 121 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the FOCUS BAND. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmScopeLens::
# 125 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the SCOPE LENS. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_ConfirmLeftovers::
# 129 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "You've chosen the LEFTOVERS. Is that\n"
	.string "correct?$"

BattleFrontier_ExchangeServiceCorner_Text_WellSendItToPC::
# 133 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Thank you! We'll send it to your PC at\n"
	.string "home.$"

BattleFrontier_ExchangeServiceCorner_Text_HereIsYourPrize::
# 137 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Here is your prize!$"

BattleFrontier_ExchangeServiceCorner_Text_DontHaveEnoughPoints::
# 141 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "I'm so sorry You don't have enough\n"
	.string "Battle Points$"

BattleFrontier_ExchangeServiceCorner_Text_PCIsFull::
# 145 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "I'm so sorry Your PC appears to be full$"

BattleFrontier_ExchangeServiceCorner_Text_DontHaveSpaceToHoldIt::
# 149 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "I'm so sorry You don't have space to\n"
	.string "hold it$"

BattleFrontier_ExchangeServiceCorner_Text_ThankYouVisitWithPoints::
# 153 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Thank you very much.\p"
	.string "Please visit us when you have saved up\n"
	.string "Battle Points.$"

BattleFrontier_ExchangeServiceCorner_Text_WishIHadAllDolls::
# 157 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Oh, they're so nice! I wish I had them!\l"
	.string "Cute cushions!\l"
	.string "Big plush DOLLS!\l"
	.string "Little plush DOLLS!\l"
	.string "I wish I had them all!$"

BattleFrontier_ExchangeServiceCorner_Text_GetYouAnythingYouWant::
# 161 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Leave it to your mommy!\p"
	.string "If it's anything you want, I'll go\n"
	.string "through anything to get it, honey!$"

BattleFrontier_ExchangeServiceCorner_Text_ItemsWillGetMonTougher::
# 165 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "If I can get hold of the items here, my\n"
	.string "POKMON will get tougher.\p"
	.string "You bet they will! No question about it!$"

BattleFrontier_ExchangeServiceCorner_Text_GoGetYourOwnDoll::
# 169 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Hah? What are you gawking at?\p"
	.string "I don't like you staring at my plush doll\n"
	.string "like that.\p"
	.string "If you want it, go get one yourself!\n"
	.string "Isn't that right, SMOOCHUM?$"

BattleFrontier_ExchangeServiceCorner_Text_MoreBattlePointsForRecord::
# 173 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Did you know?\p"
	.string "If you stretch your record at any of\n"
	.string "the BATTLE facilities, they start\l"
	.string "giving you more and more Battle Points.$"

BattleFrontier_ExchangeServiceCorner_Text_KissPosterDesc::
# 177 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A large poster with a SMOOCHUM print.$"

BattleFrontier_ExchangeServiceCorner_Text_KissCushionDesc::
# 181 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A SMOOCHUM cushion. Place it on a mat or\n"
	.string "a desk.$"

BattleFrontier_ExchangeServiceCorner_Text_SmoochumDollDesc::
# 185 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A SMOOCHUM DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_TogepiDollDesc::
# 189 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A TOGEPI DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_MeowthDollDesc::
# 193 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A MEOWTH DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_ClefairyDollDesc::
# 197 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A CLEFAIRY DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_DittoDollDesc::
# 201 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A DITTO DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_CyndaquilDollDesc::
# 205 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A CYNDAQUIL DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_ChikoritaDollDesc::
# 209 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A CHIKORITA DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_TotodileDollDesc::
# 213 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A TOTODILE DOLL. Place it on a mat or a\n"
	.string "desk.$"

BattleFrontier_ExchangeServiceCorner_Text_LargeDollDesc::
# 217 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A large DOLL. Place it on a mat or a desk.$"

BattleFrontier_ExchangeServiceCorner_Text_ProteinDesc::
# 221 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the stat ATTACK of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_CalciumDesc::
# 225 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the stat SP. ATK of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_IronDesc::
# 229 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the stat DEFENSE of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_ZincDesc::
# 233 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the stat SP. DEF of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_CarbosDesc::
# 237 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the stat SPEED of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_HPUpDesc::
# 241 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises the HP of one POKMON.$"

BattleFrontier_ExchangeServiceCorner_Text_LeftoversDesc::
# 245 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that gradually restores HP\n"
	.string "in battle.$"

BattleFrontier_ExchangeServiceCorner_Text_WhiteHerbDesc::
# 249 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that restores any lowered\n"
	.string "stat.$"

BattleFrontier_ExchangeServiceCorner_Text_QuickClawDesc::
# 253 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that occasionally allows the\n"
	.string "first strike.$"

BattleFrontier_ExchangeServiceCorner_Text_MentalHerbDesc::
# 257 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that snaps POKMON out of\n"
	.string "infatuation.$"

BattleFrontier_ExchangeServiceCorner_Text_BrightpowderDesc::
# 261 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that casts a glare to reduce\n"
	.string "accuracy.$"

BattleFrontier_ExchangeServiceCorner_Text_ChoiceBandDesc::
# 265 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "Raises a move's power, but permits only\n"
	.string "that move.$"

BattleFrontier_ExchangeServiceCorner_Text_KingsRockDesc::
# 269 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that may cause flinching\n"
	.string "when the foe is hit.$"

BattleFrontier_ExchangeServiceCorner_Text_FocusBandDesc::
# 273 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that occasionally prevents\n"
	.string "fainting.$"

BattleFrontier_ExchangeServiceCorner_Text_ScopeLensDesc::
# 277 "data/maps/BattleFrontier_ExchangeServiceCorner/scripts.pory"
	.string "A hold item that raises the critical-hit\n"
	.string "rate.$"
