VictoryRoad_B1F_MapScripts::
	.byte 0


VictoryRoad_B1F_EventScript_Halle::
# 5 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_double TRAINER_HALLE, VictoryRoad_B1F_Text_HalleIntro, VictoryRoad_B1F_Text_HalleDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_HallePostBattle
	return


VictoryRoad_B1F_EventScript_Michelle::
# 10 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_double TRAINER_MICHELLE, VictoryRoad_B1F_Text_MichelleIntro, VictoryRoad_B1F_Text_MichelleDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MichellePostBattle
	return


VictoryRoad_B1F_EventScript_Mitchell::
# 15 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_double TRAINER_MITCHELL, VictoryRoad_B1F_Text_MitchellIntro, VictoryRoad_B1F_Text_MitchellDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_MitchellPostBattle
	return


VictoryRoad_B1F_EventScript_Samuel::
# 20 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_double TRAINER_SAMUEL, VictoryRoad_B1F_Text_SamuelIntro, VictoryRoad_B1F_Text_SamuelDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_SamuelPostBattle
	return


VictoryRoad_B1F_EventScript_Shannon::
# 25 "data/maps/VictoryRoad_B1F/scripts.pory"
	trainerbattle_double TRAINER_SHANNON, VictoryRoad_B1F_Text_ShannonIntro, VictoryRoad_B1F_Text_ShannonDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/VictoryRoad_B1F/scripts.pory"
	msgbox VictoryRoad_B1F_Text_ShannonPostBattle
	return


VictoryRoad_B1F_Text_HalleDefeat::
# 31 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_HalleDefeat$"

VictoryRoad_B1F_Text_HalleIntro::
# 35 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_HalleIntro$"

VictoryRoad_B1F_Text_HallePostBattle::
# 39 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_HallePostBattle$"

VictoryRoad_B1F_Text_MichelleDefeat::
# 43 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MichelleDefeat$"

VictoryRoad_B1F_Text_MichelleIntro::
# 47 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MichelleIntro$"

VictoryRoad_B1F_Text_MichellePostBattle::
# 51 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MichellePostBattle$"

VictoryRoad_B1F_Text_MitchellDefeat::
# 55 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MitchellDefeat$"

VictoryRoad_B1F_Text_MitchellIntro::
# 59 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MitchellIntro$"

VictoryRoad_B1F_Text_MitchellPostBattle::
# 63 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_MitchellPostBattle$"

VictoryRoad_B1F_Text_SamuelDefeat::
# 67 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_SamuelDefeat$"

VictoryRoad_B1F_Text_SamuelIntro::
# 71 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_SamuelIntro$"

VictoryRoad_B1F_Text_SamuelPostBattle::
# 75 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_SamuelPostBattle$"

VictoryRoad_B1F_Text_ShannonDefeat::
# 79 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_ShannonDefeat$"

VictoryRoad_B1F_Text_ShannonIntro::
# 83 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_ShannonIntro$"

VictoryRoad_B1F_Text_ShannonPostBattle::
# 87 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B1F_Text_ShannonPostBattle$"
