VictoryRoad_B1F_MapScripts::
	.byte 0


VictoryRoad_B1F_Text_SamuelIntro::
# 5 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "The thought that I'm getting closer to\n"
	.string "the POKéMON LEAGUE…\p"
	.string "I'm getting stage fright…$"

VictoryRoad_B1F_Text_SamuelDefeat::
# 9 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "I couldn't do a thing…$"

VictoryRoad_B1F_Text_SamuelPostBattle::
# 13 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "The POKéMON LEAGUE became distant\n"
	.string "again… What a letdown…$"

VictoryRoad_B1F_Text_ShannonIntro::
# 17 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "To win your way through the POKéMON\n"
	.string "LEAGUE, you need the trust of your\l"
	.string "POKéMON.$"

VictoryRoad_B1F_Text_ShannonDefeat::
# 21 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Your relationship is based on solid\n"
	.string "trust.$"

VictoryRoad_B1F_Text_ShannonPostBattle::
# 25 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "By being together all the time, trust\n"
	.string "grows between POKéMON and TRAINERS.$"

VictoryRoad_B1F_Text_MichelleIntro::
# 29 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "This isn't the goal. It's only a place on\n"
	.string "the way to the POKéMON LEAGUE.$"

VictoryRoad_B1F_Text_MichelleDefeat::
# 33 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "That's the way!$"

VictoryRoad_B1F_Text_MichellePostBattle::
# 37 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "You'll do fine, for sure! Your POKéMON\n"
	.string "are all eager to go!$"

VictoryRoad_B1F_Text_MitchellIntro::
# 41 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "My POKéMON are cosmically awe\n"
	.string "inspiring!$"

VictoryRoad_B1F_Text_MitchellDefeat::
# 45 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "I've never met anyone like you before.$"

VictoryRoad_B1F_Text_MitchellPostBattle::
# 49 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Even outside of battle, I sense\n"
	.string "incredible power emanating from you\l"
	.string "and your POKéMON.$"

VictoryRoad_B1F_Text_HalleIntro::
# 53 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Okay, no need to get your back up!\n"
	.string "Relax, let's take it easy!$"

VictoryRoad_B1F_Text_HalleDefeat::
# 57 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Whoa! Wonderful!$"

VictoryRoad_B1F_Text_HallePostBattle::
# 61 "data/maps/VictoryRoad_B1F/scripts.pory"
	.string "Sure, this is VICTORY ROAD.\p"
	.string "But it's not all that different from the\n"
	.string "path you've taken so far.\p"
	.string "Try to enjoy things the rest of the\n"
	.string "way!$"
