WhirlIslands_B5F_MapScripts::
	.byte 0


WhirlIslands_B5F_EventScript_SmithNPC1::
# 5 "data/maps/WhirlIslands_B5F/scripts.pory"
	msgbox WhirlIslands_B5F_Text_SmithNPC1, MSGBOX_NPC
	end


WhirlIslands_B5F_EventScript_SmithNPC2::
# 14 "data/maps/WhirlIslands_B5F/scripts.pory"
	msgbox WhirlIslands_B5F_Text_SmithNPC2, MSGBOX_NPC
	end


WhirlIslands_B5F_Text_SmithNPC1::
# 9 "data/maps/WhirlIslands_B5F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

WhirlIslands_B5F_Text_SmithNPC2::
# 18 "data/maps/WhirlIslands_B5F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
