RusturfTunnel_MapScripts::
# 2 "data/maps/RusturfTunnel/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RusturfTunnel_OnTransition
# 3 "data/maps/RusturfTunnel/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, RusturfTunnel_OnFrame
	.byte 0


RusturfTunnel_Text_ComeAndGetSome::
# 7 "data/maps/RusturfTunnel/scripts.pory"
	.string "What, are you coming? Come and get\n"
	.string "some, then!$"

RusturfTunnel_Text_Peeko::
# 11 "data/maps/RusturfTunnel/scripts.pory"
	.string "PEEKO: Pii pihyoh!$"

RusturfTunnel_Text_GruntIntro::
# 15 "data/maps/RusturfTunnel/scripts.pory"
	.string "Grah, keelhaul it all!\p"
	.string "That hostage POKMON turned out to be\n"
	.string "worthless!\p"
	.string "And to think I made a getaway In this\n"
	.string "tunnel to nowhere!\p"
	.string "Hey! You! So you want to battle me?$"

RusturfTunnel_Text_GruntDefeat::
# 19 "data/maps/RusturfTunnel/scripts.pory"
	.string "Urrrggh! My career in crime comes to a\n"
	.string "dead end!$"

RusturfTunnel_Text_GruntTakePackage::
# 23 "data/maps/RusturfTunnel/scripts.pory"
	.string "This is plain not right\p"
	.string "The BOSS told me this would be a\n"
	.string "slick-and-easy job to pull.\p"
	.string "All I had to do was steal some package\n"
	.string "from DEVON.\p"
	.string "Tch! You want it back that badly, take\n"
	.string "it!$"

RusturfTunnel_Text_PeekoGladToSeeYouSafe::
# 27 "data/maps/RusturfTunnel/scripts.pory"
	.string "PEEKO! Am I glad to see you're safe!$"

RusturfTunnel_Text_ThankYouLetsGoHomePeeko::
# 31 "data/maps/RusturfTunnel/scripts.pory"
	.string "PEEKO owes her life to you!\p"
	.string "They call me MR. BRINEY. And, you are?\p"
	.string "\p"
	.string "Ah, so you are {PLAYER}{KUN}! I sincerely\n"
	.string "thank you!\p"
	.string "Now, if there's anything that troubles\n"
	.string "you, don't hesitate to tell me!\p"
	.string "You can usually find me in my cottage by\n"
	.string "the sea near PETALBURG WOODS.\p"
	.string "Come, PEEKO, we should make our way\n"
	.string "home.\p"
	.string "PEEKO: Pihyoh!$"

RusturfTunnel_Text_WhyCantTheyKeepDigging::
# 35 "data/maps/RusturfTunnel/scripts.pory"
	.string "\p"
	.string "Why can't they keep digging? Is the\n"
	.string "bedrock too hard?\p"
	.string "My beloved awaits me in VERDANTURF\n"
	.string "TOWN just beyond here\p"
	.string "If RUSTBORO and VERDANTURF were\n"
	.string "joined by this tunnel, I could visit\l"
	.string "her every day\p"
	.string "But this What am I to do?$"

RusturfTunnel_Text_ToGetToVerdanturf::
# 39 "data/maps/RusturfTunnel/scripts.pory"
	.string "To get from RUSTBORO to VERDANTURF,\n"
	.string "you need to go to DEWFORD, then pass\l"
	.string "through SLATEPORT and MAUVILLE$"

RusturfTunnel_Text_YouShatteredBoulderTakeHM::
# 43 "data/maps/RusturfTunnel/scripts.pory"
	.string "Wow! You shattered that boulder\n"
	.string "blocking the way.\p"
	.string "To show you how much I appreciate it,\n"
	.string "I'd like you to have this HM.$"

RusturfTunnel_Text_ExplainStrength::
# 47 "data/maps/RusturfTunnel/scripts.pory"
	.string "That HM contains STRENGTH.\p"
	.string "If a muscular POKMON were to learn\n"
	.string "that, it would be able to move even\l"
	.string "large boulders.$"

RusturfTunnel_Text_WandaReunion::
# 51 "data/maps/RusturfTunnel/scripts.pory"
	.string "WANDA! Now I can see you anytime!\p"
	.string "WANDA: That'swonderful.\p"
	.string "Please, take some rest at my home.$"

RusturfTunnel_Text_BoyfriendOnOtherSideOfRock::
# 55 "data/maps/RusturfTunnel/scripts.pory"
	.string "On the other side of this rock My\n"
	.string "boyfriend is there.\p"
	.string "He He's not just digging the tunnel to\n"
	.string "come see me.\p"
	.string "He works his hands raw and rough for\n"
	.string "the benefit of everyone.$"

RusturfTunnel_Text_MikeIntro::
# 59 "data/maps/RusturfTunnel/scripts.pory"
	.string "What do you call a wild man up in the\n"
	.string "mountains? A mountain man, right?\p"
	.string "So why don't they call a POKMON in the\n"
	.string "mountains a mountain POKMON?$"

RusturfTunnel_Text_MikeDefeat::
# 63 "data/maps/RusturfTunnel/scripts.pory"
	.string "My POKMON Ran out of power$"

RusturfTunnel_Text_MikePostBattle::
# 67 "data/maps/RusturfTunnel/scripts.pory"
	.string "They halted development here to\n"
	.string "protect POKMON, right?\l"
	.string "There's a feel-good story!$"
