FourIsland_IcefallCave_1F_MapScripts::
# 2 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FourIsland_IcefallCave_1F_OnResume
# 3 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, FourIsland_IcefallCave_1F_OnLoad
# 4 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FourIsland_IcefallCave_1F_OnFrame
	.byte 0


FourIsland_IcefallCave_1F_MapScripts::
# 8 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FourIsland_IcefallCave_1F_OnResume
# 9 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, FourIsland_IcefallCave_1F_OnLoad
# 10 "data/maps/FourIsland_IcefallCave_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FourIsland_IcefallCave_1F_OnFrame
	return

