VermilionCity_Mart_MapScripts::
	.byte 0


VermilionCity_Mart_EventScript_BaldingMan::
# 5 "data/maps/VermilionCity_Mart/scripts.pory"
	msgbox VermilionCity_Mart_Text_TeamRocketAreWickedPeople, MSGBOX_NPC
	end


VermilionCity_Mart_EventScript_Clerk::
	end


VermilionCity_Mart_EventScript_CooltrainerF::
# 14 "data/maps/VermilionCity_Mart/scripts.pory"
	msgbox VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer, MSGBOX_NPC
	end


VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
# 19 "data/maps/VermilionCity_Mart/scripts.pory"
	.string "There are wicked people who will\n"
	.string "use POKéMON for criminal acts.\p"
	.string "TEAM ROCKET traffics in rare\n"
	.string "POKéMON, for example.\p"
	.string "They also abandon POKéMON that\n"
	.string "they consider unpopular or useless.\p"
	.string "That's the sort of horrid people\n"
	.string "they are, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
# 23 "data/maps/VermilionCity_Mart/scripts.pory"
	.string "I think POKéMON can be good or\n"
	.string "bad. It depends on the TRAINER.$"
