VermilionCity_Mart_MapScripts::
	.byte 0


VermilionCity_Mart_Text_TeamRocketAreWickedPeople::
# 5 "data/maps/VermilionCity_Mart/scripts.pory"
	.string "There are wicked people who will use\n"
	.string "POKMON for criminal acts.\p"
	.string "TEAM ROCKET traffics in rare POKMON,\n"
	.string "for example.\p"
	.string "They also abandon POKMON that they\n"
	.string "consider unpopular or useless.\p"
	.string "That's the sort of horrid people they\n"
	.string "are, TEAM ROCKET.$"

VermilionCity_Mart_Text_MonsGoodOrBadDependingOnTrainer::
# 9 "data/maps/VermilionCity_Mart/scripts.pory"
	.string "I think POKMON can be good or bad. It\n"
	.string "depends on the TRAINER.$"
