MtEmber_Exterior_MapScripts::
# 2 "data/maps/MtEmber_Exterior/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtEmber_Exterior_OnTransition
# 3 "data/maps/MtEmber_Exterior/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MtEmber_Exterior_OnLoad
	.byte 0


Text_ExplosionTeach::
# 7 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Can you imagine? If this volcano were\n"
	.string "to erupt?\p"
	.string "The explosion would be the end of us.\n"
	.string "How terrifying is that?\p"
	.string "While we're terrified, would you like me\n"
	.string "to teach EXPLOSION?$"

Text_ExplosionDeclined::
# 11 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Yeah, you're right. It is too terrifying.$"

Text_ExplosionWhichMon::
# 15 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "You're terribly brave!\p"
	.string "Which POKMON should I teach\n"
	.string "EXPLOSION?$"

Text_ExplosionTaught::
# 19 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Using EXPLOSION while on this volcano\p"
	.string "What a terrifying thrill!$"

Text_ExplosionTeachJP::
# 23 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "\l"
	.string "\l"
	.string "\p"
	.string "$"

Text_ExplosionDeclinedJP::
# 27 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "$"

Text_ExplosionWhichMonJP::
# 31 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "$"

Text_ExplosionTaughtJP::
# 35 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "$"

MtEmber_Exterior_Text_WellTryDiggingHere::
# 39 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Over here. We'll try digging here.\p"
	.string "That treasure the ADMINS've been\n"
	.string "talking about should be here.$"

MtEmber_Exterior_Text_YoureInTheWayGetLost::
# 43 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "What the? You're in the way. Get lost.$"

MtEmber_Exterior_Text_PunchedThroughAtLast::
# 47 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Whew, punched through at last. Let's go\n"
	.string "treasure hunting!$"

MtEmber_Exterior_Text_WhatsPasswordAgain::
# 51 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Any treasure we find, we haul back to\n"
	.string "the WAREHOUSE, understood?\p"
	.string "Oh, and what're the passwords? At the\n"
	.string "ROCKET WAREHOUSE, I mean.$"

MtEmber_Exterior_Text_FirstPasswordGoldeen::
# 55 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "What, you forgot the password?\n"
	.string "There're actually two.\p"
	.string "The first one's GOLDEEN need log.\p"
	.string "And the second one is$"

MtEmber_Exterior_Text_SnoopsBeenListeningIn::
# 59 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Hey! This snoop's been listening in!$"

MtEmber_Exterior_Text_Grunt1Intro::
# 63 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "You've been eavesdropping on us,\n"
	.string "haven't you?$"

MtEmber_Exterior_Text_Grunt1Defeat::
# 67 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Huh, what?$"

MtEmber_Exterior_Text_Grunt1PostBattle::
# 71 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Why'd you have to win?$"

MtEmber_Exterior_Text_Grunt2Intro::
# 75 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Trying to horn in on our treasure? Don't\n"
	.string "bet on it!$"

MtEmber_Exterior_Text_Grunt2Defeat::
# 79 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Wait! But how?$"

MtEmber_Exterior_Text_Grunt2PostBattle::
# 83 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Develop amnesia conveniently and\n"
	.string "forget everything you heard!$"

MtEmber_Exterior_Text_WellRegroupDontStepInsideThere::
# 87 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "What a setback We'll have to regroup.\p"
	.string "You! Don't even think about taking a\n"
	.string "step inside here!\p"
	.string "If you know what's good for you, don't\n"
	.string "even think about this!$"

MtEmber_Exterior_Text_LoganIntro::
# 91 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "An active volcano is one that's\n"
	.string "erupting, or about to.$"

MtEmber_Exterior_Text_LoganDefeat::
# 95 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Whew That was hot! Sweat's erupting\n"
	.string "from me!$"

MtEmber_Exterior_Text_LoganPostBattle::
# 99 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "They say there're over 1,500 active\n"
	.string "volcanoes in the world.\p"
	.string "Just thinking about them makes me feel\n"
	.string "all hot and gooey inside!$"

MtEmber_Exterior_Text_BethIntro::
# 103 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Do you know how caves form inside\n"
	.string "volcanoes?$"

MtEmber_Exterior_Text_BethDefeat::
# 107 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Atchah! You're shockingly good!$"

MtEmber_Exterior_Text_BethPostBattle::
# 111 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "When lava at the surface of magma\n"
	.string "hardens, and the magma inside flows\l"
	.string "out, caverns are left behind.$"

MtEmber_Exterior_Text_JocelynIntro::
# 115 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "I've been in training so I can mend my\n"
	.string "broken heart\p"
	.string "It toughened me up physically at least!\n"
	.string "Hi-yah!$"

MtEmber_Exterior_Text_JocelynDefeat::
# 119 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "I think I tried to overdo it$"

MtEmber_Exterior_Text_JocelynPostBattle::
# 123 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "The way you battle, it reminds me of the\n"
	.string "guy who dumped me$"
