MtEmber_Exterior_MapScripts::
	.byte 0


MtEmber_Exterior_EventScript_Beth::
# 5 "data/maps/MtEmber_Exterior/scripts.pory"
	trainerbattle_double TRAINER_PKMN_RANGER_BETH, MtEmber_Exterior_Text_BethIntro, MtEmber_Exterior_Text_BethDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MtEmber_Exterior/scripts.pory"
	msgbox MtEmber_Exterior_Text_BethPostBattle
	return


MtEmber_Exterior_EventScript_Grunt1::
	end


MtEmber_Exterior_EventScript_Grunt2::
	end


MtEmber_Exterior_EventScript_Jocelyn::
# 18 "data/maps/MtEmber_Exterior/scripts.pory"
	trainerbattle_double TRAINER_CRUSH_GIRL_JOCELYN, MtEmber_Exterior_Text_JocelynIntro, MtEmber_Exterior_Text_JocelynDefeat, Text_NotEnoughMonsForDoubleBattle
# 19 "data/maps/MtEmber_Exterior/scripts.pory"
	msgbox MtEmber_Exterior_Text_JocelynPostBattle
	return


MtEmber_Exterior_EventScript_Logan::
# 23 "data/maps/MtEmber_Exterior/scripts.pory"
	trainerbattle_double TRAINER_PKMN_RANGER_LOGAN, MtEmber_Exterior_Text_LoganIntro, MtEmber_Exterior_Text_LoganDefeat, Text_NotEnoughMonsForDoubleBattle
# 24 "data/maps/MtEmber_Exterior/scripts.pory"
	msgbox MtEmber_Exterior_Text_LoganPostBattle
	return


MtEmber_Exterior_EventScript_RocketPasswordScene::
	end


MtEmber_Exterior_Text_BethDefeat::
# 33 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_BethDefeat$"

MtEmber_Exterior_Text_BethIntro::
# 37 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_BethIntro$"

MtEmber_Exterior_Text_BethPostBattle::
# 41 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_BethPostBattle$"

MtEmber_Exterior_Text_JocelynDefeat::
# 45 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_JocelynDefeat$"

MtEmber_Exterior_Text_JocelynIntro::
# 49 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_JocelynIntro$"

MtEmber_Exterior_Text_JocelynPostBattle::
# 53 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_JocelynPostBattle$"

MtEmber_Exterior_Text_LoganDefeat::
# 57 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_LoganDefeat$"

MtEmber_Exterior_Text_LoganIntro::
# 61 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_LoganIntro$"

MtEmber_Exterior_Text_LoganPostBattle::
# 65 "data/maps/MtEmber_Exterior/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtEmber_Exterior_Text_LoganPostBattle$"
