SSAnne_B1F_Room4_MapScripts::
	.byte 0


SSAnne_B1F_Room4_Text_LeonardIntro::
# 5 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "You know what they say about sailors\n"
	.string "and battling!$"

SSAnne_B1F_Room4_Text_LeonardDefeat::
# 9 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "Right! Good battle, mate!$"

SSAnne_B1F_Room4_Text_LeonardPostBattle::
# 13 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "Hahaha! Want to be a sailor, mate?$"

SSAnne_B1F_Room4_Text_DuncanIntro::
# 17 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "Come on, then! My sailor's pride is at\n"
	.string "stake!$"

SSAnne_B1F_Room4_Text_DuncanDefeat::
# 21 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "Your spirit sank me!$"

SSAnne_B1F_Room4_Text_DuncanPostBattle::
# 25 "data/maps/SSAnne_B1F_Room4/scripts.pory"
	.string "Did you see the FISHING GURU in\n"
	.string "VERMILION CITY?$"
