MauvilleCity_Mart_MapScripts::
	.byte 0


MauvilleCity_Mart_MapScripts::
	return


MauvilleCity_Mart_Text_ItemsToTemporarilyElevateStats::
# 8 "data/maps/MauvilleCity_Mart/scripts.pory"
	.string "There are items that temporarily\n"
	.string "elevate the stats of POKéMON.\p"
	.string "The ones I know you use in battle are X\n"
	.string "ATTACK and X DEFEND…\p"
	.string "I do believe that there are others like\n"
	.string "them.$"

MauvilleCity_Mart_Text_DecisionsDetermineBattle::
# 12 "data/maps/MauvilleCity_Mart/scripts.pory"
	.string "Use a certain move, or use an item\n"
	.string "instead…\p"
	.string "The TRAINER's decisions determine how\n"
	.string "battles turn out, I think.$"
