FortreeCity_House1_MapScripts::
	.byte 0


FortreeCity_House1_EventScript_ExpertF::
# 5 "data/maps/FortreeCity_House1/scripts.pory"
	msgbox FortreeCity_House1_Text_TradingMemoriesWithOthers, MSGBOX_NPC
	end


FortreeCity_House1_EventScript_Trader::
	end


FortreeCity_House1_EventScript_Zigzagoon::
# 14 "data/maps/FortreeCity_House1/scripts.pory"
	msgbox FortreeCity_House1_Text_Zigzagoon, MSGBOX_DEFAULT
	end


FortreeCity_House1_Text_GoingToMakeVolbeatStrong::
# 18 "data/maps/FortreeCity_House1/scripts.pory"
	.string "I'm going to make VOLBEAT super\n"
	.string "strong from this moment on!\p"
	.string "I hope you do the same with PLUSLE!$"

FortreeCity_House1_Text_TradingMemoriesWithOthers::
# 22 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Trading POKéMON with others…\p"
	.string "It's as if you're trading your own\n"
	.string "memories with other people.$"

FortreeCity_House1_Text_Zigzagoon::
# 26 "data/maps/FortreeCity_House1/scripts.pory"
	.string "ZIGZAGOON: Gumomoh?$"

FortreeCity_House1_Text_YouWontTradeMe::
# 30 "data/maps/FortreeCity_House1/scripts.pory"
	.string "No? You won't trade me?\n"
	.string "Even after I bared my heart to you?$"

FortreeCity_House1_Text_ThisIsntAMon::
# 34 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Uh, no, I don't think so.\n"
	.string "That isn't a {STR_VAR_1}.$"
