FortreeCity_House1_MapScripts::
	.byte 0


FortreeCity_House1_Text_YouWillTradeWontYou::
# 5 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Wrooooaaar! I need it! I have to get me\n"
	.string "a {STR_VAR_1}!\l"
	.string "I'll do anything for it!\p"
	.string "…Uh… Did you hear that? My shout from\n"
	.string "the bottom of my heart?\p"
	.string "Having heard that, you will trade your\n"
	.string "{STR_VAR_1} for my {STR_VAR_2},\l"
	.string "won't you?$"

FortreeCity_House1_Text_MonYouTakeCare::
# 9 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Oh, yeah, right on!\p"
	.string "{STR_VAR_1}, welcome!\n"
	.string "{STR_VAR_2}, you take care!$"

FortreeCity_House1_Text_ThisIsntAMon::
# 13 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Uh, no, I don't think so. That isn't a\n"
	.string "{STR_VAR_1}.$"

FortreeCity_House1_Text_YouWontTradeMe::
# 17 "data/maps/FortreeCity_House1/scripts.pory"
	.string "No? You won't trade me? Even after I\n"
	.string "bared my heart to you?$"

FortreeCity_House1_Text_GoingToMakeVolbeatStrong::
# 21 "data/maps/FortreeCity_House1/scripts.pory"
	.string "I'm going to make VOLBEAT super strong\n"
	.string "from this moment on!\p"
	.string "I hope you do the same with PLUSLE!$"

FortreeCity_House1_Text_TradingMemoriesWithOthers::
# 25 "data/maps/FortreeCity_House1/scripts.pory"
	.string "Trading POKéMON with others…\p"
	.string "It's as if you're trading your own\n"
	.string "memories with other people.$"

FortreeCity_House1_Text_Zigzagoon::
# 29 "data/maps/FortreeCity_House1/scripts.pory"
	.string "ZIGZAGOON: Gumomoh?$"
