SixIsland_MapScripts::
	.byte 0


SixIsland_EventScript_Boy::
# 5 "data/maps/SixIsland/scripts.pory"
	msgbox SixIsland_Text_SkyAtNightIsFantastic, MSGBOX_NPC
	end


SixIsland_EventScript_Hiker::
# 10 "data/maps/SixIsland/scripts.pory"
	msgbox SixIsland_Text_ThatWayToWaterPathRuinValley, MSGBOX_NPC
	end


SixIsland_EventScript_IslandSign::
# 15 "data/maps/SixIsland/scripts.pory"
	msgbox SixIsland_Text_IslandSign, MSGBOX_SIGN
	end


SixIsland_Text_IslandSign::
# 20 "data/maps/SixIsland/scripts.pory"
	.string "SIX ISLAND Fortune Island of Aged\n"
	.string "Wisdom$"

SixIsland_Text_SkyAtNightIsFantastic::
# 24 "data/maps/SixIsland/scripts.pory"
	.string "When you're this far away from the\n"
	.string "city, the sky at night is fantastic.$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
# 28 "data/maps/SixIsland/scripts.pory"
	.string "Keep going this way and you'll get\n"
	.string "to the WATER PATH.\p"
	.string "Stay on that and you'll get to\n"
	.string "the RUIN VALLEY.$"
