SixIsland_MapScripts::
# 2 "data/maps/SixIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SixIsland_OnTransition
	.byte 0


SixIsland_Text_IslandSign::
# 6 "data/maps/SixIsland/scripts.pory"
	.string "SIX ISLAND Fortune Island of Aged\n"
	.string "Wisdom$"

SixIsland_Text_ThatWayToWaterPathRuinValley::
# 10 "data/maps/SixIsland/scripts.pory"
	.string "Keep going this way and you'll get to\n"
	.string "the WATER PATH.\p"
	.string "Stay on that and you'll get to the RUIN\n"
	.string "VALLEY.$"

SixIsland_Text_SkyAtNightIsFantastic::
# 14 "data/maps/SixIsland/scripts.pory"
	.string "When you're this far away from the city,\n"
	.string "the sky at night is fantastic.$"
