SeafoamIslands_B4F_MapScripts::
	.byte 0


SeafoamIslands_B4F_EventScript_Articuno::
	end


SeafoamIslands_B4F_EventScript_BoulderHintSign::
# 9 "data/maps/SeafoamIslands_B4F/scripts.pory"
	msgbox SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow, MSGBOX_SIGN
	end


SeafoamIslands_B4F_EventScript_FastCurrentSign::
# 14 "data/maps/SeafoamIslands_B4F/scripts.pory"
	msgbox SeafoamIslands_B4F_Text_DangerFastCurrent, MSGBOX_SIGN
	end


SeafoamIslands_B4F_EventScript_UpwardCurrent::
	end


SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
# 23 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "Hint: Boulders might change the flow of\n"
	.string "water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
# 27 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "DANGER Fast current!$"
