SeafoamIslands_B4F_MapScripts::
# 2 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SeafoamIslands_B4F_OnTransition
# 3 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SeafoamIslands_B4F_OnResume
# 4 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SeafoamIslands_B4F_OnLoad
# 5 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SeafoamIslands_B4F_OnWarp
# 6 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SeafoamIslands_B4F_OnFrame
	.byte 0


Text_RockSlideTeach::
# 10 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "When you're up on a rocky mountain like\n"
	.string "this, rockslides are a threat.\p"
	.string "Can you imagine? Boulders tumbling down\n"
	.string "on you?\p"
	.string "That'd be, like, waaaaaaaaaaah! Total\n"
	.string "terror!\p"
	.string "You don't seem to be scared. Want to try\n"
	.string "using ROCK SLIDE?$"

Text_RockSlideDeclined::
# 14 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "Oh, so you are scared after all.$"

Text_RockSlideWhichMon::
# 18 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "Which POKMON should I teach ROCK\n"
	.string "SLIDE?$"

Text_RockSlideTaught::
# 22 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "It might be scary to use it in this\n"
	.string "tunnel$"

SeafoamIslands_B4F_Text_BouldersMightChangeWaterFlow::
# 26 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "Hint: Boulders might change the flow of\n"
	.string "water.$"

SeafoamIslands_B4F_Text_DangerFastCurrent::
# 30 "data/maps/SeafoamIslands_B4F/scripts.pory"
	.string "DANGER Fast current!$"
