SeafoamIslands_B4F_MapScripts::
# 2 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SeafoamIslands_B4F_OnTransition
# 3 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SeafoamIslands_B4F_OnResume
# 4 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SeafoamIslands_B4F_OnLoad
# 5 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SeafoamIslands_B4F_OnWarp
# 6 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SeafoamIslands_B4F_OnFrame
	.byte 0


SeafoamIslands_B4F_MapScripts::
# 10 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SeafoamIslands_B4F_OnTransition
# 11 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SeafoamIslands_B4F_OnResume
# 12 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SeafoamIslands_B4F_OnLoad
# 13 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SeafoamIslands_B4F_OnWarp
# 14 "data/maps/SeafoamIslands_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SeafoamIslands_B4F_OnFrame
	return

