Route110_MapScripts::
# 2 "data/maps/Route110/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route110_OnResume
# 3 "data/maps/Route110/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_OnTransition
# 4 "data/maps/Route110/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route110_OnFrame
	.byte 0


Route110_Text_WeCantTalkAboutAquaActivities::
# 8 "data/maps/Route110/scripts.pory"
	.string "TEAM AQUA's activities… We can't talk\n"
	.string "about them yet.$"

Route110_Text_KickUpARuckus::
# 12 "data/maps/Route110/scripts.pory"
	.string "I want to get going to SLATEPORT and\n"
	.string "kick up a ruckus!$"

Route110_Text_MyFirstJobInAqua::
# 16 "data/maps/Route110/scripts.pory"
	.string "This is my first job after joining TEAM\n"
	.string "AQUA. It's a little scary.$"

Route110_Text_AquaActionsBringSmiles::
# 20 "data/maps/Route110/scripts.pory"
	.string "TEAM AQUA's actions should bring smiles\n"
	.string "to people's faces!$"

Route110_Text_MayLetsBattle::
# 24 "data/maps/Route110/scripts.pory"
	.string "MAY: Hi, {PLAYER}{KUN}, long time no see!\p"
	.string "While I was searching for other\n"
	.string "POKéMON, my POKéMON grew stronger.\p"
	.string "So… How about a little battle?$"

Route110_Text_MayDefeated::
# 28 "data/maps/Route110/scripts.pory"
	.string "Yikes! You're better than I expected!$"

Route110_Text_MayTakeThis::
# 32 "data/maps/Route110/scripts.pory"
	.string "MAY: {PLAYER}{KUN}, you've been busy\n"
	.string "training, too, haven't you?\p"
	.string "I think you deserve a reward! This is\n"
	.string "from me!$"

Route110_Text_MayExplainItemfinder::
# 36 "data/maps/Route110/scripts.pory"
	.string "MAY: That's an ITEMFINDER.\p"
	.string "Try it out. If there is an item that's\n"
	.string "not visible, it emits a sound.\p"
	.string "Okay, {PLAYER}{KUN}, let's meet again!\p"
	.string "I know it's a little silly coming from me,\n"
	.string "but I think you should train a lot\l"
	.string "harder for the next time.$"

Route110_Text_BrendanLetsBattle::
# 40 "data/maps/Route110/scripts.pory"
	.string "BRENDAN: Hey, {PLAYER}. So this is\n"
	.string "where you were.\l"
	.string "How's it going?\p"
	.string "Have you been raising your POKéMON?\n"
	.string "I'll check for you.$"

Route110_Text_BrendanDefeated::
# 44 "data/maps/Route110/scripts.pory"
	.string "Hmm… You're pretty good.$"

Route110_Text_BrendanTakeThis::
# 48 "data/maps/Route110/scripts.pory"
	.string "BRENDAN: {PLAYER}, you've trained\n"
	.string "without me noticing…\p"
	.string "Good enough! Here, take this.$"

Route110_Text_BrendanExplainItemfinder::
# 52 "data/maps/Route110/scripts.pory"
	.string "BRENDAN: That's an ITEMFINDER.\p"
	.string "Use it to root around for items that\n"
	.string "aren't visible.\p"
	.string "If it senses something, it emits a\n"
	.string "sound.\p"
	.string "Anyway, I'm off to look for new POKéMON.$"

Route110_Text_RideBikeAtFullSpeed::
# 56 "data/maps/Route110/scripts.pory"
	.string "Wouldn't it be great to ride a BIKE at\n"
	.string "full speed on CYCLING ROAD?$"

Route110_Text_HairStreamsBehindMe::
# 60 "data/maps/Route110/scripts.pory"
	.string "How do you like the way my raven-\n"
	.string "colored hair streams behind me?\p"
	.string "I grew my hair out just for that.$"

Route110_Text_YouGotBikeFromRydel::
# 64 "data/maps/Route110/scripts.pory"
	.string "Oh, hey, you got that BIKE from RYDEL!\p"
	.string "Oh, it's glaringly obvious. It says right\n"
	.string "on your bike…\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL… That\n"
	.string "name's everywhere.\p"
	.string "You should ride it around all over the\n"
	.string "place--it's good advertising!$"

Route110_Text_TwoRoads::
# 68 "data/maps/Route110/scripts.pory"
	.string "The two roads, one above, one below…\p"
	.string "A road each for people and POKéMON.\n"
	.string "Perhaps that is right and fair.$"

Route110_Text_WalkOnTheLowRoad::
# 72 "data/maps/Route110/scripts.pory"
	.string "I don't have a BIKE, so I'll take a\n"
	.string "leisurely walk on the low road.$"

Route110_Text_BikeTechniques::
# 76 "data/maps/Route110/scripts.pory"
	.string "Learning techniques will make BIKE\n"
	.string "riding even more fun.\p"
	.string "There are some places that you can\n"
	.string "reach only by using a BIKE technique.$"

Route110_Text_WhichShouldIChoose::
# 80 "data/maps/Route110/scripts.pory"
	.string "Which should I choose?\p"
	.string "Make a beeline for MAUVILLE on CYCLING\n"
	.string "ROAD, or take the low road\l"
	.string "and look for POKéMON?$"

Route110_Text_CyclingChallengeResultSummary::
# 84 "data/maps/Route110/scripts.pory"
	.string "Number of collisions: … …\n"
	.string "{STR_VAR_1}!\p"
	.string "Total time: … … {STR_VAR_2}!$"

Route110_Text_ChallengeReactionBest::
# 88 "data/maps/Route110/scripts.pory"
	.string "Bravo! Splendid showing!\p"
	.string "Your love of cycling comes from deep\n"
	.string "within your heart.\l"
	.string "You've shaken me to my very soul!$"

Route110_Text_ChallengeReactionGood::
# 92 "data/maps/Route110/scripts.pory"
	.string "Your technique is remarkable.\p"
	.string "I suggest you speed up a bit while still\n"
	.string "avoiding collisions.$"

Route110_Text_ChallengeReactionOk::
# 96 "data/maps/Route110/scripts.pory"
	.string "I would consider you a work in progress.\p"
	.string "Still, I hope you don't forget the sheer\n"
	.string "pleasure of cycling.$"

Route110_Text_ChallengeReactionBad::
# 100 "data/maps/Route110/scripts.pory"
	.string "My word… Your cycling skills border on\n"
	.string "terrifying.\p"
	.string "Most certainly, you need much more\n"
	.string "practice riding.$"

Route110_Text_ChallengeReactionWorst::
# 104 "data/maps/Route110/scripts.pory"
	.string "…I am aghast…\p"
	.string "You're perhaps not cut out for this\n"
	.string "unfortunate cycling business.\p"
	.string "You ought to give serious thought to\n"
	.string "returning that BIKE to RYDEL.$"

Route110_Text_RatedForNumberOfCollisions::
# 108 "data/maps/Route110/scripts.pory"
	.string "This is CYCLING ROAD.\p"
	.string "If you were to ride from MAUVILLE to\n"
	.string "SLATEPORT on a MACH BIKE, you would\l"
	.string "be rated for the number of collisions\l"
	.string "and your total time.$"

Route110_Text_AlwaysAimHigher::
# 112 "data/maps/Route110/scripts.pory"
	.string "Regardless of the results, I count on\n"
	.string "seeing more challenges from you.\l"
	.string "Always aim higher!$"

Route110_Text_AcroBikesDoNotQualify::
# 116 "data/maps/Route110/scripts.pory"
	.string "On this CYCLING ROAD, those riding MACH\n"
	.string "BIKES are rated for their number\l"
	.string "of collisions and their total times.\p"
	.string "ACRO BIKES do not qualify for rating.\n"
	.string "They are easy to turn, so it's not fair.$"

Route110_Text_SlateportCitySign::
# 120 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {DOWN_ARROW} SLATEPORT CITY$"

Route110_Text_CyclingRoadSign::
# 124 "data/maps/Route110/scripts.pory"
	.string "SEASIDE CYCLING ROAD$"

Route110_Text_AquaWasHere::
# 128 "data/maps/Route110/scripts.pory"
	.string "“TEAM AQUA was here!”\p"
	.string "Someone painted that onto this sign,\n"
	.string "but then someone else painted over it.\p"
	.string "“TEAM MAGMA rules!” is what it says now.$"

Route110_Text_Route103Sign::
# 132 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {LEFT_ARROW} ROUTE 103$"

Route110_Text_SeasideParkingSign::
# 136 "data/maps/Route110/scripts.pory"
	.string "SEASIDE PARKING$"

Route110_Text_MauvilleCitySign::
# 140 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {UP_ARROW} MAUVILLE CITY$"

Route110_Text_TrainerTipsPrlzSleep::
# 144 "data/maps/Route110/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The foe can be made helpless by\n"
	.string "paralyzing it or causing it to sleep.\p"
	.string "It is an important technique for\n"
	.string "POKéMON battles.$"

Route110_Text_TrainerTipsRegisterItems::
# 148 "data/maps/Route110/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The items in the BAG can be reorganized\n"
	.string "by pressing SELECT.$"

Route110_Text_TrickHouseSign::
# 152 "data/maps/Route110/scripts.pory"
	.string "“Three steps {RIGHT_ARROW} and two steps {UP_ARROW} to\n"
	.string "reach the wondrous TRICK HOUSE.”$"

Route110_Text_BestRecord::
# 156 "data/maps/Route110/scripts.pory"
	.string "THE BEST RECORD TO DATE…\p"
	.string "No. of collisions: {STR_VAR_1}\p"
	.string "Elapsed time: {STR_VAR_2}$"

Route110_Text_ThereIsNoRecord::
# 160 "data/maps/Route110/scripts.pory"
	.string "THE BEST RECORD TO DATE…\p"
	.string "No one seems to have taken the\n"
	.string "challenge. There is no record…$"

Route110_Text_ImagineSeeingYouHere::
# 164 "data/maps/Route110/scripts.pory"
	.string "PROF. BIRCH: Oh, {PLAYER}{KUN}! Imagine\n"
	.string "seeing you here!\p"
	.string "And where might my {RIVAL} be?$"

Route110_Text_HeardYouInstallMatchCall::
# 168 "data/maps/Route110/scripts.pory"
	.string "Oh, I see! You two are running\n"
	.string "separately.\l"
	.string "Well, that's fine.\p"
	.string "Oh, yes, I heard that your POKéNAV had\n"
	.string "the MATCH CALL system installed.\p"
	.string "Well, then, I should register you in my\n"
	.string "POKéNAV as well.\p"
	.string "That way, even when we're apart, I can\n"
	.string "rate your POKéDEX anytime.\p"
	.string "… … … … … …$"

Route110_Text_RegisteredBirchInPokenav::
# 172 "data/maps/Route110/scripts.pory"
	.string "Registered PROF. BIRCH in the POKéNAV.$"

Route110_Text_KeepAnEyeOutForRival::
# 176 "data/maps/Route110/scripts.pory"
	.string "PROF. BIRCH: {PLAYER}{KUN}…\p"
	.string "Please keep an eye out for my\n"
	.string "{RIVAL}. … … … … … …\p"
	.string "Well, I had better get going. See you\n"
	.string "again, {PLAYER}{KUN}!$"
