Route110_MapScripts::
	.byte 0


Route110_EventScript_Abigail::
# 5 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_ABIGAIL, Route110_Text_AbigailIntro, Route110_Text_AbigailDefeated, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_AbigailPostBattle
	return


Route110_EventScript_Alyssa::
# 10 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_ALYSSA, Route110_Text_AlyssaIntro, Route110_Text_AlyssaDefeated, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_AlyssaPostBattle
	return


Route110_EventScript_Anthony::
# 15 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_ANTHONY, Route110_Text_AnthonyIntro, Route110_Text_AnthonyDefeated, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_AnthonyPostBattle
	return


Route110_EventScript_AquaGrunt1::
# 20 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_WeCantTalkAboutAquaActivities, MSGBOX_DEFAULT
	end


Route110_EventScript_AquaGrunt2::
# 25 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_KickUpARuckus, MSGBOX_DEFAULT
	end


Route110_EventScript_AquaGrunt3::
# 30 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_MyFirstJobInAqua, MSGBOX_DEFAULT
	end


Route110_EventScript_AquaGrunt4::
# 35 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_AquaActionsBringSmiles, MSGBOX_DEFAULT
	end


Route110_EventScript_Benjamin::
# 40 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_BENJAMIN, Route110_Text_BenjaminIntro, Route110_Text_BenjaminDefeated, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_BenjaminPostBattle
	return


Route110_EventScript_BirchScene1::
	end


Route110_EventScript_BirchScene2::
	end


Route110_EventScript_BirchScene3::
	end


Route110_EventScript_BirchScene4::
	end


Route110_EventScript_Boy1::
# 61 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_RideBikeAtFullSpeed, MSGBOX_NPC
	end


Route110_EventScript_Boy2::
# 66 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_WhichShouldIChoose, MSGBOX_NPC
	end


Route110_EventScript_ChallengeGuy::
	end


Route110_EventScript_CyclingChallengeEnd::
	end


Route110_EventScript_CyclingGirl1::
# 79 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_HairStreamsBehindMe, MSGBOX_NPC
	end


Route110_EventScript_CyclingGuy1::
# 84 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_YouGotBikeFromRydel, MSGBOX_NPC
	end


Route110_EventScript_CyclingGuy2::
# 89 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_BikeTechniques, MSGBOX_NPC
	end


Route110_EventScript_CyclingRoadResultsSign::
# 97 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_BestRecord, MSGBOX_SIGN
	end


Route110_EventScript_CyclingRoadSign::
# 103 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_CyclingRoadSign, MSGBOX_SIGN
	end


Route110_EventScript_Dale::
# 108 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_DALE, Route110_Text_DaleIntro, Route110_Text_DaleDefeated, Text_NotEnoughMonsForDoubleBattle
# 109 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_DalePostBattle
	return


Route110_EventScript_Edward::
# 113 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_EDWARD, Route110_Text_EdwardIntro, Route110_Text_EdwardDefeated, Text_NotEnoughMonsForDoubleBattle
# 114 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_EdwardPostBattle
	return


Route110_EventScript_Edwin::
# 118 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_EDWIN, Route110_Text_EdwinIntro, Route110_Text_EdwinDefeated, Text_NotEnoughMonsForDoubleBattle
# 119 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_EdwinPostBattle
	return


Route110_EventScript_Isabel::
# 123 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_ISABEL, Route110_Text_IsabelIntro, Route110_Text_IsabelDefeated, Text_NotEnoughMonsForDoubleBattle
# 124 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_IsabelPostBattle
	return


Route110_EventScript_Jaclyn::
# 128 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_JACLYN, Route110_Text_JaclynIntro, Route110_Text_JaclynDefeated, Text_NotEnoughMonsForDoubleBattle
# 129 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_JaclynPostBattle
	return


Route110_EventScript_Jacob::
# 133 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_JACOB, Route110_Text_JacobIntro, Route110_Text_JacobDefeated, Text_NotEnoughMonsForDoubleBattle
# 134 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_JacobPostBattle
	return


Route110_EventScript_Jasmine::
# 138 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_JASMINE, Route110_Text_JasmineIntro, Route110_Text_JasmineDefeated, Text_NotEnoughMonsForDoubleBattle
# 139 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_JasminePostBattle
	return


Route110_EventScript_Joseph::
# 143 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_JOSEPH, Route110_Text_JosephIntro, Route110_Text_JosephDefeated, Text_NotEnoughMonsForDoubleBattle
# 144 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_JosephPostBattle
	return


Route110_EventScript_Kaleb::
# 148 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_KALEB, Route110_Text_KalebIntro, Route110_Text_KalebDefeated, Text_NotEnoughMonsForDoubleBattle
# 149 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_KalebPostBattle
	return


Route110_EventScript_MauvilleCitySign::
# 153 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_MauvilleCitySign, MSGBOX_SIGN
	end


Route110_EventScript_OldMan::
# 158 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_TwoRoads, MSGBOX_NPC
	end


Route110_EventScript_OldWoman::
# 163 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_WalkOnTheLowRoad, MSGBOX_NPC
	end


Route110_EventScript_RivalTrigger1::
	end


Route110_EventScript_RivalTrigger2::
	end


Route110_EventScript_RivalTrigger3::
	end


Route110_EventScript_Route103Sign::
# 180 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_Route103Sign, MSGBOX_SIGN
	end


Route110_EventScript_SeasideParkingSign::
# 185 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_SeasideParkingSign, MSGBOX_SIGN
	end


Route110_EventScript_SlateportCitySign::
# 190 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_SlateportCitySign, MSGBOX_SIGN
	end


Route110_EventScript_Timmy::
# 195 "data/maps/Route110/scripts.pory"
	trainerbattle_double TRAINER_TIMMY, Route110_Text_TimmyIntro, Route110_Text_TimmyDefeated, Text_NotEnoughMonsForDoubleBattle
# 196 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_TimmyPostBattle
	return


Route110_EventScript_TrainerTipsPrlzSleep::
# 200 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_TrainerTipsPrlzSleep, MSGBOX_SIGN
	end


Route110_EventScript_TrainerTipsRegisterItems::
# 205 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_TrainerTipsRegisterItems, MSGBOX_SIGN
	end


Route110_EventScript_TrickHouseSign::
# 210 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_TrickHouseSign, MSGBOX_SIGN
	end


Route110_EventScript_VandalizedSign::
# 215 "data/maps/Route110/scripts.pory"
	msgbox Route110_Text_AquaWasHere, MSGBOX_SIGN
	end


Route110_Text_MauvilleCitySign::
# 220 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {UP_ARROW} MAUVILLE CITY$"

Route110_Text_TrainerTipsPrlzSleep::
# 224 "data/maps/Route110/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The foe can be made helpless by\n"
	.string "paralyzing it or causing it to sleep.\p"
	.string "It is an important technique for\n"
	.string "POKéMON battles.$"

Route110_Text_TrickHouseSign::
# 228 "data/maps/Route110/scripts.pory"
	.string "“Three steps {RIGHT_ARROW} and two steps {UP_ARROW} to\n"
	.string "reach the wondrous TRICK HOUSE.”$"

Route110_Text_BestRecord::
# 232 "data/maps/Route110/scripts.pory"
	.string "THE BEST RECORD TO DATE…\p"
	.string "No. of collisions: {STR_VAR_1}\p"
	.string "Elapsed time: {STR_VAR_2}$"

Route110_Text_AquaWasHere::
# 236 "data/maps/Route110/scripts.pory"
	.string "“TEAM AQUA was here!”\p"
	.string "Someone painted that onto this sign,\n"
	.string "but then someone else painted over it.\p"
	.string "“TEAM MAGMA rules!” is what it says now.$"

Route110_Text_CyclingRoadSign::
# 240 "data/maps/Route110/scripts.pory"
	.string "SEASIDE CYCLING ROAD$"

Route110_Text_SlateportCitySign::
# 244 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {DOWN_ARROW} SLATEPORT CITY$"

Route110_Text_SeasideParkingSign::
# 248 "data/maps/Route110/scripts.pory"
	.string "SEASIDE PARKING$"

Route110_Text_TrainerTipsRegisterItems::
# 252 "data/maps/Route110/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The items in the BAG can be reorganized\n"
	.string "by pressing SELECT.$"

Route110_Text_Route103Sign::
# 256 "data/maps/Route110/scripts.pory"
	.string "ROUTE 110 {LEFT_ARROW} ROUTE 103$"

Route110_Text_AbigailDefeated::
# 261 "data/maps/Route110/scripts.pory"
	.string "POKéMON battles are hard, too!$"

Route110_Text_AbigailIntro::
# 265 "data/maps/Route110/scripts.pory"
	.string "The triathlon is hard in the extreme.\p"
	.string "You have to complete the three events\n"
	.string "of swimming, cycling, and running.$"

Route110_Text_AbigailPostBattle::
# 269 "data/maps/Route110/scripts.pory"
	.string "I'm exhausted, so I need a break. It's\n"
	.string "important to get proper rest.$"

Route110_Text_AlyssaDefeated::
# 273 "data/maps/Route110/scripts.pory"
	.string "Oops! I ended up losing!$"

Route110_Text_AlyssaIntro::
# 277 "data/maps/Route110/scripts.pory"
	.string "I fell off CYCLING ROAD…\p"
	.string "I'll get over my embarrassment by\n"
	.string "battling with you!$"

Route110_Text_AlyssaPostBattle::
# 281 "data/maps/Route110/scripts.pory"
	.string "Falling… Losing… This is so humiliating\n"
	.string "for me!$"

Route110_Text_AnthonyDefeated::
# 285 "data/maps/Route110/scripts.pory"
	.string "Crash and burn!$"

Route110_Text_AnthonyIntro::
# 289 "data/maps/Route110/scripts.pory"
	.string "Yo, you! Can you keep up with my speed?$"

Route110_Text_AnthonyPostBattle::
# 293 "data/maps/Route110/scripts.pory"
	.string "Speed alone won't let me win at POKéMON.\n"
	.string "I need to reconsider this…$"

Route110_Text_BenjaminDefeated::
# 297 "data/maps/Route110/scripts.pory"
	.string "I shouldn't panic during POKéMON\n"
	.string "battles…$"

Route110_Text_BenjaminIntro::
# 301 "data/maps/Route110/scripts.pory"
	.string "Don't panic if your BIKE's going fast!$"

Route110_Text_BenjaminPostBattle::
# 305 "data/maps/Route110/scripts.pory"
	.string "There's no need to panic or stress. Take\n"
	.string "it easy. There's plenty of time.$"

Route110_Text_DaleDefeated::
# 309 "data/maps/Route110/scripts.pory"
	.string "I lost! Drat!$"

Route110_Text_DaleIntro::
# 313 "data/maps/Route110/scripts.pory"
	.string "Hey! Don't sneak up behind me like that!$"

Route110_Text_DalePostBattle::
# 317 "data/maps/Route110/scripts.pory"
	.string "Fishing is all about concentration. You\n"
	.string "have to focus on the floater.$"

Route110_Text_EdwardDefeated::
# 321 "data/maps/Route110/scripts.pory"
	.string "I failed to prophesize my own demise!$"

Route110_Text_EdwardIntro::
# 325 "data/maps/Route110/scripts.pory"
	.string "I have foreseen your intentions! I\n"
	.string "cannot possibly lose!$"

Route110_Text_EdwardPostBattle::
# 329 "data/maps/Route110/scripts.pory"
	.string "I see your future…\p"
	.string "Hmm… I see a shining light…$"

Route110_Text_EdwinDefeated::
# 333 "data/maps/Route110/scripts.pory"
	.string "I wanted to complete my collection…$"

Route110_Text_EdwinIntro::
# 337 "data/maps/Route110/scripts.pory"
	.string "Could I see your POKéMON? Just one\n"
	.string "look, please?$"

Route110_Text_EdwinPostBattle::
# 341 "data/maps/Route110/scripts.pory"
	.string "When I see a POKéMON that I don't know,\n"
	.string "my passion as a collector is ignited!$"

Route110_Text_IsabelDefeated::
# 345 "data/maps/Route110/scripts.pory"
	.string "Oh, dear, this won't do.$"

Route110_Text_IsabelIntro::
# 349 "data/maps/Route110/scripts.pory"
	.string "Ahahaha! I would go anywhere to show\n"
	.string "off my delightful POKéMON.$"

Route110_Text_IsabelPostBattle::
# 353 "data/maps/Route110/scripts.pory"
	.string "Rather than battling, perhaps I should\n"
	.string "show off my POKéMON at the FAN CLUB.$"

Route110_Text_JaclynDefeated::
# 357 "data/maps/Route110/scripts.pory"
	.string "I wondrously lost!$"

Route110_Text_JaclynIntro::
# 361 "data/maps/Route110/scripts.pory"
	.string "Ahahahaha! I'll dazzle you with my\n"
	.string "wonders!$"

Route110_Text_JaclynPostBattle::
# 365 "data/maps/Route110/scripts.pory"
	.string "You managed to win only because it was\n"
	.string "a wonder! Yes, a wonder! Don't think you\l"
	.string "can win all the time!$"

Route110_Text_JacobDefeated::
# 369 "data/maps/Route110/scripts.pory"
	.string "Whoa! My brakes failed!$"

Route110_Text_JacobIntro::
# 373 "data/maps/Route110/scripts.pory"
	.string "Whoa! Watch it! I guess you're not used\n"
	.string "to BIKE racing.$"

Route110_Text_JacobPostBattle::
# 377 "data/maps/Route110/scripts.pory"
	.string "Flat tires and brake problems can cause\n"
	.string "serious injury! Inspect your BIKE for\l"
	.string "problems!$"

Route110_Text_JasmineDefeated::
# 381 "data/maps/Route110/scripts.pory"
	.string "I'm worried about muscle cramps…$"

Route110_Text_JasmineIntro::
# 385 "data/maps/Route110/scripts.pory"
	.string "I've been riding without stopping. My\n"
	.string "thighs are like rocks!$"

Route110_Text_JasminePostBattle::
# 389 "data/maps/Route110/scripts.pory"
	.string "Oh, you have some GYM BADGES? No\n"
	.string "wonder you're so strong!$"

Route110_Text_JosephDefeated::
# 393 "data/maps/Route110/scripts.pory"
	.string "You got into the groove all right…$"

Route110_Text_JosephIntro::
# 397 "data/maps/Route110/scripts.pory"
	.string "Okay! Full-throttle time! If you can't\n"
	.string "groove, you get left behind!$"

Route110_Text_JosephPostBattle::
# 401 "data/maps/Route110/scripts.pory"
	.string "This isn't going to bring me down!\n"
	.string "Losing has made me a better man!$"

Route110_Text_KalebDefeated::
# 405 "data/maps/Route110/scripts.pory"
	.string "Have you no compassion or pity?$"

Route110_Text_KalebIntro::
# 409 "data/maps/Route110/scripts.pory"
	.string "When cute POKéMON help each other… You\n"
	.string "won't see a more adorable sight!$"

Route110_Text_KalebPostBattle::
# 413 "data/maps/Route110/scripts.pory"
	.string "Okay, okay, you've done the best you\n"
	.string "could, my pretties.$"

Route110_Text_TimmyDefeated::
# 417 "data/maps/Route110/scripts.pory"
	.string "Being cool isn't enough to win…$"

Route110_Text_TimmyIntro::
# 421 "data/maps/Route110/scripts.pory"
	.string "I found some cool POKéMON in the grass\n"
	.string "around here!$"

Route110_Text_TimmyPostBattle::
# 425 "data/maps/Route110/scripts.pory"
	.string "It's hard to battle with POKéMON you\n"
	.string "just caught.$"

Route110_Text_ChallengeReactionWorst::
# 429 "data/maps/Route110/scripts.pory"
	.string "…I am aghast…\p"
	.string "You're perhaps not cut out for this\n"
	.string "unfortunate cycling business.\p"
	.string "You ought to give serious thought to\n"
	.string "returning that BIKE to RYDEL.$"

Route110_Text_WalkOnTheLowRoad::
# 433 "data/maps/Route110/scripts.pory"
	.string "I don't have a BIKE, so I'll take\n"
	.string "a leisurely walk on the low road.$"

Route110_Text_ChallengeReactionBest::
# 437 "data/maps/Route110/scripts.pory"
	.string "Bravo! Splendid showing!\p"
	.string "Your love of cycling comes from deep\n"
	.string "within your heart.\l"
	.string "You've shaken me to my very soul!$"

Route110_Text_WeCantTalkAboutAquaActivities::
# 441 "data/maps/Route110/scripts.pory"
	.string "TEAM AQUA's activities…\n"
	.string "We can't talk about them yet.$"

Route110_Text_BrendanTakeThis::
# 445 "data/maps/Route110/scripts.pory"
	.string "BRENDAN: {PLAYER}, you've trained\n"
	.string "without me noticing…\p"
	.string "Good enough!\n"
	.string "Here, take this.$"

Route110_Text_HairStreamsBehindMe::
# 449 "data/maps/Route110/scripts.pory"
	.string "How do you like the way my raven-\n"
	.string "colored hair streams behind me?\p"
	.string "I grew my hair out just for that.$"

Route110_Text_ChallengeReactionGood::
# 453 "data/maps/Route110/scripts.pory"
	.string "Your technique is remarkable.\p"
	.string "I suggest you speed up a bit while\n"
	.string "still avoiding collisions.$"

Route110_Text_AquaActionsBringSmiles::
# 457 "data/maps/Route110/scripts.pory"
	.string "TEAM AQUA's actions should bring\n"
	.string "smiles to people's faces!$"

Route110_Text_TwoRoads::
# 461 "data/maps/Route110/scripts.pory"
	.string "The two roads, one above, one below…\p"
	.string "A road each for people and POKéMON.\n"
	.string "Perhaps that is right and fair.$"

Route110_Text_KickUpARuckus::
# 465 "data/maps/Route110/scripts.pory"
	.string "I want to get going to SLATEPORT and\n"
	.string "kick up a ruckus!$"

Route110_Text_RatedForNumberOfCollisions::
# 469 "data/maps/Route110/scripts.pory"
	.string "This is CYCLING ROAD.\p"
	.string "If you were to ride from MAUVILLE to\n"
	.string "SLATEPORT on a MACH BIKE, you would\l"
	.string "be rated for the number of collisions\l"
	.string "and your total time.$"

Route110_Text_MayLetsBattle::
# 473 "data/maps/Route110/scripts.pory"
	.string "MAY: Hi, {PLAYER}{KUN}, long time no see!\p"
	.string "While I was searching for other\n"
	.string "POKéMON, my POKéMON grew stronger.\p"
	.string "So…\n"
	.string "How about a little battle?$"

Route110_Text_AcroBikesDoNotQualify::
# 477 "data/maps/Route110/scripts.pory"
	.string "On this CYCLING ROAD, those riding\n"
	.string "MACH BIKES are rated for their number\l"
	.string "of collisions and their total times.\p"
	.string "ACRO BIKES do not qualify for rating.\n"
	.string "They are easy to turn, so it's not fair.$"

Route110_Text_BrendanLetsBattle::
# 481 "data/maps/Route110/scripts.pory"
	.string "BRENDAN: Hey, {PLAYER}.\n"
	.string "So this is where you were.\l"
	.string "How's it going?\p"
	.string "Have you been raising your POKéMON?\n"
	.string "I'll check for you.$"

Route110_Text_MyFirstJobInAqua::
# 485 "data/maps/Route110/scripts.pory"
	.string "This is my first job after joining\n"
	.string "TEAM AQUA. It's a little scary.$"

Route110_Text_ChallengeReactionBad::
# 489 "data/maps/Route110/scripts.pory"
	.string "My word… Your cycling skills border\n"
	.string "on terrifying.\p"
	.string "Most certainly, you need much more\n"
	.string "practice riding.$"

Route110_Text_RideBikeAtFullSpeed::
# 493 "data/maps/Route110/scripts.pory"
	.string "Wouldn't it be great to ride a BIKE\n"
	.string "at full speed on CYCLING ROAD?$"

Route110_Text_YouGotBikeFromRydel::
# 497 "data/maps/Route110/scripts.pory"
	.string "Oh, hey, you got that BIKE from RYDEL!\p"
	.string "Oh, it's glaringly obvious.\n"
	.string "It says right on your bike…\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\n"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL,\p"
	.string "RYDEL, RYDEL, RYDEL, RYDEL, RYDEL…\n"
	.string "That name's everywhere.\p"
	.string "You should ride it around all over\n"
	.string "the place--it's good advertising!$"

Route110_Text_ChallengeReactionOk::
# 501 "data/maps/Route110/scripts.pory"
	.string "I would consider you a work in\n"
	.string "progress.\p"
	.string "Still, I hope you don't forget the\n"
	.string "sheer pleasure of cycling.$"

Route110_Text_WhichShouldIChoose::
# 505 "data/maps/Route110/scripts.pory"
	.string "Which should I choose?\p"
	.string "Make a beeline for MAUVILLE on\n"
	.string "CYCLING ROAD, or take the low road\l"
	.string "and look for POKéMON?$"

Route110_Text_CyclingChallengeResultSummary::
# 509 "data/maps/Route110/scripts.pory"
	.string "Number of collisions:\n"
	.string "… … {STR_VAR_1}!\p"
	.string "Total time:\n"
	.string "… … {STR_VAR_2}!$"

Route110_Text_BikeTechniques::
# 513 "data/maps/Route110/scripts.pory"
	.string "Learning techniques will make BIKE\n"
	.string "riding even more fun.\p"
	.string "There are some places that you can\n"
	.string "reach only by using a BIKE technique.$"

Route110_Text_MayTakeThis::
# 517 "data/maps/Route110/scripts.pory"
	.string "MAY: {PLAYER}{KUN}, you've been busy\n"
	.string "training, too, haven't you?\p"
	.string "I think you deserve a reward!\n"
	.string "This is from me!$"

Route110_Text_ThereIsNoRecord::
# 521 "data/maps/Route110/scripts.pory"
	.string "THE BEST RECORD TO DATE…\p"
	.string "No one seems to have taken the\n"
	.string "challenge. There is no record…$"
