LilycoveCity_DepartmentStore_3F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_3F_EventScript_ClerkLeft::
	end


LilycoveCity_DepartmentStore_3F_EventScript_ClerkRight::
	end


LilycoveCity_DepartmentStore_3F_EventScript_PokefanM::
# 13 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_3F_EventScript_TriathleteM::
# 18 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_3F_EventScript_Woman::
# 23 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance::
# 27 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon::
# 31 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "I gave a CARBOS to my POKéMON,\n"
	.string "and its SPEED went up.$"

LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon::
# 35 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK,\n"
	.string "and CALCIUM raises SP. ATK.$"
