LilycoveCity_DepartmentStore_3F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_3F_Text_ItemsBestForTougheningPokemon::
# 5 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "For quickly toughening up POKéMON,\n"
	.string "items are the best.\p"
	.string "PROTEIN boosts ATTACK, and CALCIUM\n"
	.string "raises SP. ATK.$"

LilycoveCity_DepartmentStore_3F_Text_WantMoreEndurance::
# 9 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "I want my POKéMON to have more\n"
	.string "endurance.\p"
	.string "I'm trying to decide whether to raise\n"
	.string "DEFENSE with IRON, or SP. DEF with ZINC.$"

LilycoveCity_DepartmentStore_3F_Text_GaveCarbosToSpeedUpMon::
# 13 "data/maps/LilycoveCity_DepartmentStore_3F/scripts.pory"
	.string "I gave a CARBOS to my POKéMON, and its\n"
	.string "SPEED went up.$"
