CeladonCity_Condominiums_3F_MapScripts::
	.byte 0


CeladonCity_Condominiums_3F_EventScript_Computer1::
# 5 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_ItsTheGameProgram, MSGBOX_SIGN
	end


CeladonCity_Condominiums_3F_EventScript_Computer2::
# 10 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame, MSGBOX_SIGN
	end


CeladonCity_Condominiums_3F_EventScript_Computer3::
# 15 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding, MSGBOX_SIGN
	end


CeladonCity_Condominiums_3F_EventScript_Designer::
	end


CeladonCity_Condominiums_3F_EventScript_DevelopmentRoomSign::
# 24 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom, MSGBOX_SIGN
	end


CeladonCity_Condominiums_3F_EventScript_GraphicArtist::
# 29 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist, MSGBOX_NPC
	end


CeladonCity_Condominiums_3F_EventScript_Programmer::
# 34 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_ImTheProgrammer, MSGBOX_NPC
	end


CeladonCity_Condominiums_3F_EventScript_Writer::
# 39 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	msgbox CeladonCity_Condominiums_3F_Text_IWroteTheStory, MSGBOX_NPC
	end


CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
# 44 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Someone's playing a game instead of\n"
	.string "working!$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
# 48 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "It's the game program! Messing with it\n"
	.string "could bug out the game!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
# 52 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "It's the script! Better not look at the\n"
	.string "ending!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
# 56 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "GAME FREAK Development Room$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
# 60 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "I'm the graphic artist!\n"
	.string "I drew you!$"

CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
# 64 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Me?\n"
	.string "I'm the programmer!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
# 68 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "I wrote the story!\n"
	.string "Isn't ERIKA cute?\p"
	.string "I like MISTY a lot, too!\n"
	.string "Oh, and SABRINA, I like her!$"
