CeladonCity_Condominiums_3F_MapScripts::
	.byte 0


CeladonCity_Condominiums_3F_Text_ImTheProgrammer::
# 5 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Me? I'm the programmer!$"

CeladonCity_Condominiums_3F_Text_ImTheGraphicArtist::
# 9 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "I'm the graphic artist! I drew you!$"

CeladonCity_Condominiums_3F_Text_IWroteTheStory::
# 13 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "I wrote the story! Isn't ERIKA cute?\p"
	.string "I like MISTY a lot, too! Oh, and SABRINA,\n"
	.string "I like her!$"

CeladonCity_Condominiums_3F_Text_ImGameDesignerShowMeFinishedPokedex::
# 17 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Is that right?\p"
	.string "I'm the game designer!\p"
	.string "Filling up your POKéDEX is tough, but\n"
	.string "don't quit!\p"
	.string "When you finish, come tell me!$"

CeladonCity_Condominiums_3F_Text_CompletedPokedexCongratulations::
# 21 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Wow! Excellent! You completed your\n"
	.string "POKéDEX!\l"
	.string "Congratulations!\l"
	.string "…$"

CeladonCity_Condominiums_3F_Text_ItsTheGameProgram::
# 25 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "It's the game program! Messing with it\n"
	.string "could bug out the game!$"

CeladonCity_Condominiums_3F_Text_SomeonesPlayingGame::
# 29 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "Someone's playing a game instead of\n"
	.string "working!$"

CeladonCity_Condominiums_3F_Text_ItsScriptBetterNotLookAtEnding::
# 33 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "It's the script! Better not look at the\n"
	.string "ending!$"

CeladonCity_Condominiums_3F_Text_GameFreakDevelopmentRoom::
# 37 "data/maps/CeladonCity_Condominiums_3F/scripts.pory"
	.string "GAME FREAK Development Room$"
