Route111_MapScripts::
	.byte 0


Route111_EventScript_Beau::
# 5 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BEAU, Route111_Text_BeauIntro, Route111_Text_BeauDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BeauPostBattle
	return


Route111_EventScript_Becky::
# 10 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BECKY, Route111_Text_BeckyIntro, Route111_Text_BeckyDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BeckyPostBattle
	return


Route111_EventScript_Bianca::
# 15 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BIANCA, Route111_Text_BiancaIntro, Route111_Text_BiancaDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BiancaPostBattle
	return


Route111_EventScript_Branden::
# 20 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BRANDEN, Route111_Text_BrandenIntro, Route111_Text_BrandenDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BrandenPostBattle
	return


Route111_EventScript_Brooke::
# 25 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BROOKE, Route111_Text_BrookeIntro, Route111_Text_BrookeDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BrookePostBattle
	return


Route111_EventScript_Bryan::
# 30 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_BRYAN, Route111_Text_BryanIntro, Route111_Text_BryanDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BryanPostBattle
	return


Route111_EventScript_Celia::
# 35 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_CELIA, Route111_Text_CeliaIntro, Route111_Text_CeliaDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_CeliaPostBattle
	return


Route111_EventScript_Celina::
# 40 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_CELINA, Route111_Text_CelinaIntro, Route111_Text_CelinaDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_CelinaPostBattle
	return


Route111_EventScript_Daisuke::
# 45 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_DAISUKE, Route111_Text_DaisukeIntro, Route111_Text_DaisukeDefeat, Text_NotEnoughMonsForDoubleBattle
# 46 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_DaisukePostBattle
	return


Route111_EventScript_Drew::
# 50 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_DREW, Route111_Text_DrewIntro, Route111_Text_DrewDefeat, Text_NotEnoughMonsForDoubleBattle
# 51 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_DrewPostBattle
	return


Route111_EventScript_Dusty::
# 55 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_DUSTY, Route111_Text_DustyIntro, Route111_Text_DustyDefeat, Text_NotEnoughMonsForDoubleBattle
# 56 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_DustyPostBattle
	return


Route111_EventScript_Girl::
	end


Route111_EventScript_Hayden::
# 64 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_HAYDEN, Route111_Text_HaydenIntro, Route111_Text_HaydenDefeat, Text_NotEnoughMonsForDoubleBattle
# 65 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_HaydenPostBattle
	return


Route111_EventScript_Heidi::
# 69 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_HEIDI, Route111_Text_HeidiIntro, Route111_Text_HeidiDefeat, Text_NotEnoughMonsForDoubleBattle
# 70 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_HeidiPostBattle
	return


Route111_EventScript_Hiker::
	end


Route111_EventScript_Irene::
# 78 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_IRENE, Route111_Text_IreneIntro, Route111_Text_IreneDefeat, Text_NotEnoughMonsForDoubleBattle
# 79 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_IrenePostBattle
	return


Route111_EventScript_Man1::
# 83 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_ToughToKeepWinningUpTheRanks, MSGBOX_NPC
	end


Route111_EventScript_Man2::
# 88 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_WinstrateFamilyDestroyedMe, MSGBOX_NPC
	end


Route111_EventScript_OldLadysRestStopSign::
# 93 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_OldLadysRestStopSign, MSGBOX_SIGN
	end


Route111_EventScript_RockSmashTipFatMan::
# 98 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_MauvilleUncleToldMeToTakeRockSmash, MSGBOX_DEFAULT
	end


Route111_EventScript_RouteSign112::
# 103 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_RouteSign112, MSGBOX_SIGN
	end


Route111_EventScript_RouteSign113::
# 108 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_RouteSign113, MSGBOX_SIGN
	end


Route111_EventScript_RouteSignMauville::
# 113 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_RouteSignMauville, MSGBOX_SIGN
	end


Route111_EventScript_SandstormTrigger::
	end


Route111_EventScript_SunTrigger::
	end


Route111_EventScript_TrainerHillSign::
# 126 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_TrainerHillSign, MSGBOX_SIGN
	end


Route111_EventScript_TrainerTipsSpAtkSpDef::
# 131 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_TrainerTipsSpAtkSpDef, MSGBOX_SIGN
	end


Route111_EventScript_Travis::
# 136 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_TRAVIS, Route111_Text_TravisIntro, Route111_Text_TravisDefeat, Text_NotEnoughMonsForDoubleBattle
# 137 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_TravisPostBattle
	return


Route111_EventScript_Tyron::
# 141 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_TYRON, Route111_Text_TyronIntro, Route111_Text_TyronDefeat, Text_NotEnoughMonsForDoubleBattle
# 142 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_TyronPostBattle
	return


Route111_EventScript_ViciousSandstormTriggerDown::
	end


Route111_EventScript_ViciousSandstormTriggerLeft::
	end


Route111_EventScript_Victor::
# 154 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_BattleOurFamily, MSGBOX_YESNO
	end


Route111_EventScript_Wilton::
# 159 "data/maps/Route111/scripts.pory"
	trainerbattle_double TRAINER_WILTON, Route111_Text_WiltonIntro, Route111_Text_WiltonDefeat, Text_NotEnoughMonsForDoubleBattle
# 160 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_WiltonPostBattle
	return


Route111_EventScript_WinstrateHouseSign::
# 164 "data/maps/Route111/scripts.pory"
	msgbox Route111_Text_WinstrateHouseSign, MSGBOX_SIGN
	end


Route111_Text_TrainerHillSign::
# 169 "data/maps/Route111/scripts.pory"
	.string "{RIGHT_ARROW} TRAINER HILL ENTRANCE\p"
	.string "“Scale the heights, you hot-blooded\n"
	.string "TRAINERS!”$"

Route111_Text_TrainerTipsSpAtkSpDef::
# 173 "data/maps/Route111/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "One of the indicators of a POKéMON's\n"
	.string "powerfulness is SP. ATK. It stands for\l"
	.string "“SPECIAL ATTACK.”\p"
	.string "Likewise, SP. DEF stands for “SPECIAL\n"
	.string "DEFENSE.”$"

Route111_Text_RouteSign112::
# 177 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {LEFT_ARROW} ROUTE 112$"

Route111_Text_WinstrateHouseSign::
# 181 "data/maps/Route111/scripts.pory"
	.string "“Our family's hearts beat as one!” THE\n"
	.string "WINSTRATE'S HOUSE$"

Route111_Text_OldLadysRestStopSign::
# 185 "data/maps/Route111/scripts.pory"
	.string "OLD LADY'S REST STOP “Come in and rest\n"
	.string "your tired bones.”$"

Route111_Text_RouteSignMauville::
# 189 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {DOWN_ARROW} MAUVILLE CITY$"

Route111_Text_RouteSign113::
# 193 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {LEFT_ARROW} ROUTE 113$"

Route111_Text_BeauDefeat::
# 198 "data/maps/Route111/scripts.pory"
	.string "I can't win on spirit alone…$"

Route111_Text_BeauIntro::
# 202 "data/maps/Route111/scripts.pory"
	.string "Wearing these GO-GOGGLES makes me feel\n"
	.string "like a superhero. Right now, nobody can\l"
	.string "beat me!$"

Route111_Text_BeauPostBattle::
# 206 "data/maps/Route111/scripts.pory"
	.string "I'm going to be a real hero one day. I'm\n"
	.string "going to work harder to make me and my\l"
	.string "POKéMON stronger.$"

Route111_Text_BeckyDefeat::
# 210 "data/maps/Route111/scripts.pory"
	.string "I came up short…$"

Route111_Text_BeckyIntro::
# 214 "data/maps/Route111/scripts.pory"
	.string "I heard there are fossils to be found in\n"
	.string "the desert. Where could they be?$"

Route111_Text_BeckyPostBattle::
# 218 "data/maps/Route111/scripts.pory"
	.string "If they can find fossils in the desert,\n"
	.string "it must have been a sea before.$"

Route111_Text_BiancaDefeat::
# 222 "data/maps/Route111/scripts.pory"
	.string "Ooh lala! That's a lot to take!$"

Route111_Text_BiancaIntro::
# 226 "data/maps/Route111/scripts.pory"
	.string "Did you come from MAUVILLE? Then you\n"
	.string "should be full of energy!$"

Route111_Text_BiancaPostBattle::
# 230 "data/maps/Route111/scripts.pory"
	.string "This road here… You have quite a ways\n"
	.string "to travel.$"

Route111_Text_BrandenDefeat::
# 234 "data/maps/Route111/scripts.pory"
	.string "Tch! I thought a sandwich would be\n"
	.string "enough of a bribe…$"

Route111_Text_BrandenIntro::
# 238 "data/maps/Route111/scripts.pory"
	.string "I'll give you some of my sandwich if\n"
	.string "you'll lose.$"

Route111_Text_BrandenPostBattle::
# 242 "data/maps/Route111/scripts.pory"
	.string "My SANDSHREW loves eating my\n"
	.string "sandwiches.$"

Route111_Text_BrookeDefeat::
# 246 "data/maps/Route111/scripts.pory"
	.string "They didn't just look strong, they are\n"
	.string "strong!$"

Route111_Text_BrookeIntro::
# 250 "data/maps/Route111/scripts.pory"
	.string "Oh, your POKéMON look like serious\n"
	.string "actors. I have to ask you for an\l"
	.string "engagement.$"

Route111_Text_BrookePostBattle::
# 254 "data/maps/Route111/scripts.pory"
	.string "I thought I was raising my POKéMON\n"
	.string "diligently, but, oh no, there is still\l"
	.string "much to be done.$"

Route111_Text_BryanDefeat::
# 258 "data/maps/Route111/scripts.pory"
	.string "Oh! Your strength! It is shrouded in\n"
	.string "mystery!$"

Route111_Text_BryanIntro::
# 262 "data/maps/Route111/scripts.pory"
	.string "How tough are you? We shall expose that\n"
	.string "secret!$"

Route111_Text_BryanPostBattle::
# 266 "data/maps/Route111/scripts.pory"
	.string "This desert hoards mysteries in its\n"
	.string "shifting sands!$"

Route111_Text_CeliaDefeat::
# 270 "data/maps/Route111/scripts.pory"
	.string "Aww! I really shouldn't have come!$"

Route111_Text_CeliaIntro::
# 274 "data/maps/Route111/scripts.pory"
	.string "I shouldn't have come to a place like\n"
	.string "this for a picnic!$"

Route111_Text_CeliaPostBattle::
# 278 "data/maps/Route111/scripts.pory"
	.string "In a sandstorm like this, I can't set\n"
	.string "the places for a picnic even with my\l"
	.string "GO-GOGGLES on…$"

Route111_Text_CelinaDefeat::
# 282 "data/maps/Route111/scripts.pory"
	.string "Oh… My… That was too much excitement.$"

Route111_Text_CelinaIntro::
# 286 "data/maps/Route111/scripts.pory"
	.string "Show me how to put a little excitement\n"
	.string "into my life.$"

Route111_Text_CelinaPostBattle::
# 290 "data/maps/Route111/scripts.pory"
	.string "My pulse is still racing. You're one\n"
	.string "fabulous TRAINER.$"

Route111_Text_DaisukeDefeat::
# 294 "data/maps/Route111/scripts.pory"
	.string "Uncle! I give up!$"

Route111_Text_DaisukeIntro::
# 298 "data/maps/Route111/scripts.pory"
	.string "To train myself, I challenge all whom I\n"
	.string "meet!$"

Route111_Text_DaisukePostBattle::
# 302 "data/maps/Route111/scripts.pory"
	.string "All I can do is keep training until I can\n"
	.string "defeat strong TRAINERS such as\l"
	.string "yourself.$"

Route111_Text_DrewDefeat::
# 306 "data/maps/Route111/scripts.pory"
	.string "I couldn't see what was happening at my\n"
	.string "sides because of the GO-GOGGLES.$"

Route111_Text_DrewIntro::
# 310 "data/maps/Route111/scripts.pory"
	.string "Oh, hey! Those GO-GOGGLES suit you. But\n"
	.string "I think they look better on me.\p"
	.string "Let's decide who they look better on\n"
	.string "with a battle!$"

Route111_Text_DrewPostBattle::
# 314 "data/maps/Route111/scripts.pory"
	.string "The GO-GOGGLES make it possible to get\n"
	.string "through sandstorms. That makes me\l"
	.string "happy!$"

Route111_Text_DustyDefeat::
# 318 "data/maps/Route111/scripts.pory"
	.string "While I have searched for ruins, I've\n"
	.string "not searched for strong POKéMON.$"

Route111_Text_DustyIntro::
# 322 "data/maps/Route111/scripts.pory"
	.string "For thirty years I have searched for\n"
	.string "ancient ruins! I am to be challenged?$"

Route111_Text_DustyPostBattle::
# 326 "data/maps/Route111/scripts.pory"
	.string "For thirty years I have searched for\n"
	.string "ancient ruins!\p"
	.string "No, wait, was that forty years? Which\n"
	.string "was it now?$"

Route111_Text_HaydenDefeat::
# 330 "data/maps/Route111/scripts.pory"
	.string "Groan…$"

Route111_Text_HaydenIntro::
# 334 "data/maps/Route111/scripts.pory"
	.string "When you're as famished as I am, there\n"
	.string "is no room for pity!$"

Route111_Text_HaydenPostBattle::
# 338 "data/maps/Route111/scripts.pory"
	.string "My stomach is grumbling! Maybe I can\n"
	.string "grill some BERRIES…$"

Route111_Text_HeidiDefeat::
# 342 "data/maps/Route111/scripts.pory"
	.string "Ohhh! You're mean!$"

Route111_Text_HeidiIntro::
# 346 "data/maps/Route111/scripts.pory"
	.string "I'm having a picnic in the desert.\p"
	.string "You can always find a TRAINER, so I can\n"
	.string "enjoy a battle here, too!$"

Route111_Text_HeidiPostBattle::
# 350 "data/maps/Route111/scripts.pory"
	.string "When you're battling in a sandstorm,\n"
	.string "watch out for your POKéMON's HP.\p"
	.string "It can faint if you don't keep an eye on\n"
	.string "it!$"

Route111_Text_IreneDefeat::
# 354 "data/maps/Route111/scripts.pory"
	.string "Oh, you're disgustingly good!$"

Route111_Text_IreneIntro::
# 358 "data/maps/Route111/scripts.pory"
	.string "I don't know where you're going, but\n"
	.string "would you like to battle?$"

Route111_Text_IrenePostBattle::
# 362 "data/maps/Route111/scripts.pory"
	.string "I'm thinking that I should go to MT.\n"
	.string "CHIMNEY, but the view around here is\l"
	.string "very nice, too.$"

Route111_Text_TravisDefeat::
# 366 "data/maps/Route111/scripts.pory"
	.string "My POKéMON lost its pep…$"

Route111_Text_TravisIntro::
# 370 "data/maps/Route111/scripts.pory"
	.string "I'm full of pep! And my POKéMON is peppy,\n"
	.string "too!$"

Route111_Text_TravisPostBattle::
# 374 "data/maps/Route111/scripts.pory"
	.string "When I see a TRAINER with a lot of pep,\n"
	.string "I can't help looking.$"

Route111_Text_TyronDefeat::
# 378 "data/maps/Route111/scripts.pory"
	.string "Wait! Did you get a good look at my\n"
	.string "POKéMON?$"

Route111_Text_TyronIntro::
# 382 "data/maps/Route111/scripts.pory"
	.string "This is my favorite kind of POKéMON!$"

Route111_Text_TyronPostBattle::
# 386 "data/maps/Route111/scripts.pory"
	.string "When having a battle, I get a kick out\n"
	.string "of showing off my POKéMON.\p"
	.string "I bet everyone feels that way when\n"
	.string "they enter a battle!$"

Route111_Text_WiltonDefeat::
# 390 "data/maps/Route111/scripts.pory"
	.string "I see, you've toughened them\n"
	.string "considerably.$"

Route111_Text_WiltonIntro::
# 394 "data/maps/Route111/scripts.pory"
	.string "Show me how much you've toughened your\n"
	.string "POKéMON.$"

Route111_Text_WiltonPostBattle::
# 398 "data/maps/Route111/scripts.pory"
	.string "POKéMON and TRAINERS learn much\n"
	.string "through battling.\p"
	.string "What's important is to never give up\n"
	.string "even if you lose.$"

Route111_Text_MirageTowerClearlyVisible::
# 402 "data/maps/Route111/scripts.pory"
	.string "I see it!\n"
	.string "The tower of sand!\p"
	.string "The sand tower they called a mirage\n"
	.string "is clearly visible!\p"
	.string "But it looks so fragile…\n"
	.string "It could crumble away anytime…\p"
	.string "I want to go inside it, but I can't\n"
	.string "get my courage up for it…$"

Route111_Text_ToughToKeepWinningUpTheRanks::
# 406 "data/maps/Route111/scripts.pory"
	.string "If you don't raise your POKéMON some\n"
	.string "more, it could be tough to keep winning\l"
	.string "up through the ranks.\p"
	.string "I've heard the POKéMON LEAGUE's\n"
	.string "ELITE FOUR are far stronger than\l"
	.string "any GYM LEADER.$"

Route111_Text_MauvilleUncleToldMeToTakeRockSmash::
# 410 "data/maps/Route111/scripts.pory"
	.string "Oh, no!\p"
	.string "My uncle in MAUVILLE told me to take\n"
	.string "ROCK SMASH with me if I was going to\l"
	.string "ROUTE 111!\p"
	.string "My uncle? He lives across from\n"
	.string "the bike shop in MAUVILLE.$"

Route111_Text_MirageTowerHasntBeenSeenSince::
# 414 "data/maps/Route111/scripts.pory"
	.string "Since I spoke to you, the tower of sand\n"
	.string "hasn't been seen.\p"
	.string "Perhaps it really was\n"
	.string "the MIRAGE TOWER…$"

Route111_Text_BattleOurFamily::
# 418 "data/maps/Route111/scripts.pory"
	.string "Hello! I take it you're a traveler.\p"
	.string "How's this? What do you say to taking\n"
	.string "on our family of four in a series of\l"
	.string "POKéMON battles?$"

Route111_Text_WinstrateFamilyDestroyedMe::
# 422 "data/maps/Route111/scripts.pory"
	.string "I challenged the WINSTRATE family,\n"
	.string "but four matches in a row is tough\l"
	.string "going… They destroyed me.$"

Route111_Text_VictorIntro::
# 426 "data/maps/Route111/scripts.pory"
	.string "That's the spirit! I like you!$"

Route111_Text_ThatWasShockingSandRainedDown::
# 430 "data/maps/Route111/scripts.pory"
	.string "Whoa…\n"
	.string "That was shocking.\p"
	.string "Sand rained down in chunks all of\n"
	.string "a sudden.\p"
	.string "What was it like inside?\n"
	.string "Were there sandy ghosts and such?$"

Route111_Text_RootFossilDisappeared::
# 434 "data/maps/Route111/scripts.pory"
	.string "The ROOT FOSSIL disappeared into\n"
	.string "the sand…$"
