Route111_MapScripts::
# 2 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route111_OnLoad
# 3 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route111_OnTransition
# 4 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route111_OnWarp
# 5 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route111_OnFrame
	.byte 0


Route111_MapScripts::
# 9 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route111_OnLoad
# 10 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route111_OnTransition
# 11 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route111_OnWarp
# 12 "data/maps/Route111/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route111_OnFrame
	return


Route111_Text_BattleOurFamily::
# 16 "data/maps/Route111/scripts.pory"
	.string "Hello! I take it you're a traveler.\p"
	.string "How's this? What do you say to taking\n"
	.string "on our family of four in a series of\l"
	.string "POKéMON battles?$"

Route111_Text_IsThatSo::
# 20 "data/maps/Route111/scripts.pory"
	.string "Is that so? Drop in, if you change your\n"
	.string "mind!$"

Route111_Text_VictorIntro::
# 24 "data/maps/Route111/scripts.pory"
	.string "That's the spirit! I like you!$"

Route111_Text_VictorDefeat::
# 28 "data/maps/Route111/scripts.pory"
	.string "Aiyah! You're a lot tougher than I\n"
	.string "expected!$"

Route111_Text_VictorPostBattle::
# 32 "data/maps/Route111/scripts.pory"
	.string "Hey, all! I've found a pretty strong\n"
	.string "TRAINER!$"

Route111_Text_VictoriaIntro::
# 36 "data/maps/Route111/scripts.pory"
	.string "Oh, my goodness! Aren't you young?\p"
	.string "You must be quite the TRAINER to beat\n"
	.string "my husband, though.\p"
	.string "It's my turn to battle now!$"

Route111_Text_VictoriaDefeat::
# 40 "data/maps/Route111/scripts.pory"
	.string "Oh, gosh! I can't get over how strong\n"
	.string "you are!$"

Route111_Text_VictoriaPostBattle::
# 44 "data/maps/Route111/scripts.pory"
	.string "There's a strong TRAINER here! This\n"
	.string "one's really strong!$"

Route111_Text_ViviIntro::
# 48 "data/maps/Route111/scripts.pory"
	.string "You're stronger than Mommy? Wow!\p"
	.string "But I'm strong, too! Really! Honestly!$"

Route111_Text_ViviDefeat::
# 52 "data/maps/Route111/scripts.pory"
	.string "Huh? Did I just lose?$"

Route111_Text_ViviPostBattle::
# 56 "data/maps/Route111/scripts.pory"
	.string "This stinks…\p"
	.string "…Snivel… Grandma!$"

Route111_Text_VickyIntro::
# 60 "data/maps/Route111/scripts.pory"
	.string "How dare you make my granddaughter\n"
	.string "cry!\p"
	.string "For that, I'm going to smack you!\n"
	.string "Prepare to lose!$"

Route111_Text_VickyDefeat::
# 64 "data/maps/Route111/scripts.pory"
	.string "Kwah! You are strong… My granddaughter\n"
	.string "was right…$"

Route111_Text_VickyPostBattle::
# 68 "data/maps/Route111/scripts.pory"
	.string "If you're not in any hurry, visit with us\n"
	.string "awhile.$"

Route111_Text_ToughToKeepWinningUpTheRanks::
# 72 "data/maps/Route111/scripts.pory"
	.string "If you don't raise your POKéMON some\n"
	.string "more, it could be tough to keep winning\l"
	.string "up through the ranks.\p"
	.string "I've heard the POKéMON LEAGUE's ELITE\n"
	.string "FOUR are far stronger than\l"
	.string "any GYM LEADER.$"

Route111_Text_WinstrateFamilyDestroyedMe::
# 76 "data/maps/Route111/scripts.pory"
	.string "I challenged the WINSTRATE family, but\n"
	.string "four matches in a row is tough\l"
	.string "going… They destroyed me.$"

Route111_Text_RouteSignMauville::
# 80 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {DOWN_ARROW} MAUVILLE CITY$"

Route111_Text_WinstrateHouseSign::
# 84 "data/maps/Route111/scripts.pory"
	.string "“Our family's hearts beat as one!” THE\n"
	.string "WINSTRATE'S HOUSE$"

Route111_Text_RouteSign112::
# 88 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {LEFT_ARROW} ROUTE 112$"

Route111_Text_RouteSign113::
# 92 "data/maps/Route111/scripts.pory"
	.string "ROUTE 111 {LEFT_ARROW} ROUTE 113$"

Route111_Text_OldLadysRestStopSign::
# 96 "data/maps/Route111/scripts.pory"
	.string "OLD LADY'S REST STOP “Come in and rest\n"
	.string "your tired bones.”$"

Route111_Text_TrainerTipsSpAtkSpDef::
# 100 "data/maps/Route111/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "One of the indicators of a POKéMON's\n"
	.string "powerfulness is SP. ATK. It stands for\l"
	.string "“SPECIAL ATTACK.”\p"
	.string "Likewise, SP. DEF stands for “SPECIAL\n"
	.string "DEFENSE.”$"

Route111_Text_ShouldBeMirageTowerAroundHere::
# 104 "data/maps/Route111/scripts.pory"
	.string "There should be a tower made of sand\n"
	.string "around here somewhere.\p"
	.string "But for some reason, it can be seen\n"
	.string "sometimes, and sometimes not.\p"
	.string "That's why I call it the MIRAGE TOWER.$"

Route111_Text_MirageTowerClearlyVisible::
# 108 "data/maps/Route111/scripts.pory"
	.string "I see it! The tower of sand!\p"
	.string "The sand tower they called a mirage is\n"
	.string "clearly visible!\p"
	.string "But it looks so fragile… It could\n"
	.string "crumble away anytime…\p"
	.string "I want to go inside it, but I can't get\n"
	.string "my courage up for it…$"

Route111_Text_ThatWasShockingSandRainedDown::
# 112 "data/maps/Route111/scripts.pory"
	.string "Whoa… That was shocking.\p"
	.string "Sand rained down in chunks all of a\n"
	.string "sudden.\p"
	.string "What was it like inside? Were there\n"
	.string "sandy ghosts and such?$"

Route111_Text_MirageTowerHasntBeenSeenSince::
# 116 "data/maps/Route111/scripts.pory"
	.string "Since I spoke to you, the tower of sand\n"
	.string "hasn't been seen.\p"
	.string "Perhaps it really was the MIRAGE TOWER…$"

Route111_Text_ClawFossilDisappeared::
# 120 "data/maps/Route111/scripts.pory"
	.string "The CLAW FOSSIL disappeared into the\n"
	.string "sand…$"

Route111_Text_RootFossilDisappeared::
# 124 "data/maps/Route111/scripts.pory"
	.string "The ROOT FOSSIL disappeared into the\n"
	.string "sand…$"

Route111_Text_MauvilleUncleToldMeToTakeRockSmash::
# 128 "data/maps/Route111/scripts.pory"
	.string "Oh, no!\p"
	.string "My uncle in MAUVILLE told me to take\n"
	.string "ROCK SMASH with me if I was going to\l"
	.string "ROUTE 111!\p"
	.string "My uncle? He lives across from the bike\n"
	.string "shop in MAUVILLE.$"

Route111_Text_TrainerHillSign::
# 132 "data/maps/Route111/scripts.pory"
	.string "{RIGHT_ARROW} TRAINER HILL ENTRANCE\p"
	.string "“Scale the heights, you hot-blooded\n"
	.string "TRAINERS!”$"
