CeladonCity_DepartmentStore_5F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_5F_Text_ExplainStatEnhancers::
# 5 "data/maps/CeladonCity_DepartmentStore_5F/scripts.pory"
	.string "POKéMON stat enhancers can be bought\n"
	.string "only here.\p"
	.string "HP UP increases the base HP of a\n"
	.string "POKéMON.\p"
	.string "CALCIUM raises the base SP. ATK stat of\n"
	.string "one POKéMON.\p"
	.string "ZINC boosts the base SP. DEF stat of\n"
	.string "one POKéMON.\p"
	.string "CARBOS enhances the base SPEED stat.$"

CeladonCity_DepartmentStore_5F_Text_HereForStatEnhancers::
# 9 "data/maps/CeladonCity_DepartmentStore_5F/scripts.pory"
	.string "I'm here for POKéMON stat enhancers.\p"
	.string "PROTEIN increases the base ATTACK\n"
	.string "power.\p"
	.string "IRON increases the base DEFENSE stat.$"

CeladonCity_DepartmentStore_5F_Text_Drugstore::
# 13 "data/maps/CeladonCity_DepartmentStore_5F/scripts.pory"
	.string "5F: DRUGSTORE$"
