BattleFrontier_RankingHall_MapScripts::
	.byte 0


BattleFrontier_RankingHall_Text_ExplainRankingHall::
# 5 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "This is the RANKING HALL.\p"
	.string "This is where we recognize the immortal\n"
	.string "TRAINERS who left great records in\l"
	.string "BATTLE FRONTIER events.$"

BattleFrontier_RankingHall_Text_DomePikeFactoryRecords::
# 9 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "BATTLE DOME, BATTLE PIKE, and BATTLE\n"
	.string "FACTORY Records$"

BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords::
# 13 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "BATTLE PALACE, BATTLE ARENA, and\n"
	.string "BATTLE PYRAMID Records$"

BattleFrontier_RankingHall_Text_IsYourNameOnThisList::
# 17 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hi, is your name on this list?$"

BattleFrontier_RankingHall_Text_WowThatsSuper::
# 21 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Wow, that's super! I'll have to try\n"
	.string "harder, too!$"

BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName::
# 25 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Oh, is that right?\p"
	.string "If you saw your friend's name up here, I\n"
	.string "bet it would make you work harder!$"

BattleFrontier_RankingHall_Text_MyNamesNotUpThere::
# 29 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hmm… My name's not up there…\p"
	.string "Well, it's only natural since I haven't\n"
	.string "taken any challenges yet.$"
