MossdeepCity_SpaceCenter_2F_MapScripts::
# 2 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MossdeepCity_SpaceCenter_2F_OnTransition
# 3 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, MossdeepCity_SpaceCenter_2F_OnFrame
	.byte 0


MossdeepCity_SpaceCenter_2F_MapScripts::
# 7 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MossdeepCity_SpaceCenter_2F_OnTransition
# 8 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, MossdeepCity_SpaceCenter_2F_OnFrame
	return


MossdeepCity_SpaceCenter_2F_Text_MossdeepIdealForRockets::
# 12 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "MOSSDEEP has mainly sunny weather, and\n"
	.string "its winds are stable.\p"
	.string "It's an ideal location for launching\n"
	.string "rockets.$"

MossdeepCity_SpaceCenter_2F_Text_WhyWouldMagmaStealRocketFuel::
# 16 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "Why would TEAM MAGMA want to steal our\n"
	.string "rocket fuel in the first place?$"

MossdeepCity_SpaceCenter_2F_Text_WouldveLikedToBeAstronaut::
# 20 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "If only I was a little younger, I would\n"
	.string "have liked being an astronaut…\p"
	.string "No… It's not too late! I can and will\n"
	.string "try!$"

MossdeepCity_SpaceCenter_2F_Text_MagmaCantGetAwayWithThis::
# 24 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "If TEAM MAGMA takes the rocket fuel, I\n"
	.string "won't be able to go to space!\p"
	.string "They can't be allowed to get away with\n"
	.string "such an outrage!$"

MossdeepCity_SpaceCenter_2F_Text_WishOrdinaryPeopleCouldGoIntoSpace::
# 28 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "I wish ordinary people could go into\n"
	.string "space one day…$"

MossdeepCity_SpaceCenter_2F_Text_DoesMagmaWantToGoToSpace::
# 32 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "TEAM MAGMA… Do they want to go to\n"
	.string "space, too?$"

MossdeepCity_SpaceCenter_2F_Text_YoureOutnumberedTakeUsOn::
# 36 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "What's wrong with you?\p"
	.string "You're outnumbered three to one, but\n"
	.string "you still want to take us on?$"

MossdeepCity_SpaceCenter_2F_Text_GoodAnswer::
# 40 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "Good answer! That's what a smart\n"
	.string "person'll do!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5Intro::
# 44 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "A reckless go-getter, are you? Okay,\n"
	.string "I'll go first!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5Defeat::
# 48 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "I lost! But!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6Intro::
# 52 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "It's too soon to be relieved! I'm up\n"
	.string "next!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6Defeat::
# 56 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "I lost, too! But!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7Intro::
# 60 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "I bet you want to take a break. But I'm\n"
	.string "not about to let you do that!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7Defeat::
# 64 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "We should've taken a break… That's what\n"
	.string "we should've done…$"

MossdeepCity_SpaceCenter_2F_Text_Grunt6PostBattle::
# 68 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "Three of us here, and look at the sorry\n"
	.string "mess we got ourselves into.$"

MossdeepCity_SpaceCenter_2F_Text_Grunt7PostBattle::
# 72 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "We three losing like this… We look worse\n"
	.string "than usual by triple!$"

MossdeepCity_SpaceCenter_2F_Text_Grunt5PostBattle::
# 76 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "Are we being useful to our leader at\n"
	.string "all?$"

MossdeepCity_SpaceCenter_2F_Text_WellTakeCareOfYou::
# 80 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "Hehehe!\p"
	.string "We come all the way here to get some\n"
	.string "fuel, and we're interfered with again!\p"
	.string "If you're going to mess with us too,\n"
	.string "we'll take care of you at the same time!$"

MossdeepCity_SpaceCenter_2F_Text_MaxieDontInterfere::
# 84 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "MAXIE: Clear out of the way! Don't you\n"
	.string "dare interfere!$"

MossdeepCity_SpaceCenter_2F_Text_StevenWhyStealRocketFuel::
# 88 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "STEVEN: TEAM MAGMA…\p"
	.string "What's the point of stealing rocket\n"
	.string "fuel?$"

MossdeepCity_SpaceCenter_2F_Text_MaxieUseFuelToEruptVolcano::
# 92 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "MAXIE: Fufufu… Since you're so curious,\n"
	.string "you deserve an explanation.\p"
	.string "We're going to jettison the entire load\n"
	.string "into MT. CHIMNEY!\p"
	.string "With GROUDON gone, we have no need for\n"
	.string "that slag heap of a mountain!\p"
	.string "So we'll use the fuel's power to make\n"
	.string "the volcano erupt!\p"
	.string "It will be savage!$"

MossdeepCity_SpaceCenter_2F_Text_StevenAreYouReadyToBattle::
# 96 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "STEVEN: {PLAYER}{KUN}! You're going to\n"
	.string "help me?\p"
	.string "Let's go into battle together! Are you\n"
	.string "ready?$"

MossdeepCity_SpaceCenter_2F_Text_StevenHurryGetReadyQuickly::
# 100 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "STEVEN: Then, hurry! Get ready quickly!$"

MossdeepCity_SpaceCenter_2F_Text_JustWantToExpandLand::
# 104 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "All I want… I just want to expand the\n"
	.string "land mass…$"

MossdeepCity_SpaceCenter_Text_TabithaDefeat::
# 108 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "I'm with our leader…$"

MossdeepCity_SpaceCenter_2F_Text_MaxieWeFailedIsAquaAlsoMisguided::
# 112 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "MAXIE: We failed to make the volcano\n"
	.string "erupt…\p"
	.string "We failed to control GROUDON after we\n"
	.string "had awoken it…\p"
	.string "Is our goal to expand the land\n"
	.string "misguided?\p"
	.string "… … … … … … … … … … … …\p"
	.string "If… If we, TEAM MAGMA, are wrong…\l"
	.string "… … … … … …\p"
	.string "Then might TEAM AQUA's goal to expand\n"
	.string "the sea also be equally misguided?$"

MossdeepCity_SpaceCenter_2F_Text_MaxieWeWillGiveUp::
# 116 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "MAXIE: All right… We will give up on the\n"
	.string "fuel…\p"
	.string "There appear to be more important\n"
	.string "matters that I must examine…$"

MossdeepCity_SpaceCenter_2F_Text_StevenThankYouComeSeeMeAtHome::
# 120 "data/maps/MossdeepCity_SpaceCenter_2F/scripts.pory"
	.string "STEVEN: Whew, that was too tense.\n"
	.string "{PLAYER}{KUN}, thank you.\p"
	.string "I have something to give you as thanks\n"
	.string "for your support.\p"
	.string "Please come see me at home after this.\p"
	.string "Oh, yes, I don't live in RUSTBORO CITY. I\n"
	.string "live right here on this island.$"
