SealedChamber_OuterRoom_MapScripts::
	.byte 0


SealedChamber_OuterRoom_EventScript_BrailleABC::
	end


SealedChamber_OuterRoom_EventScript_BrailleComma::
	end


SealedChamber_OuterRoom_EventScript_BrailleDEF::
	end


SealedChamber_OuterRoom_EventScript_BrailleDigHere::
	end


SealedChamber_OuterRoom_EventScript_BrailleGHI::
	end


SealedChamber_OuterRoom_EventScript_BrailleJKL::
	end


SealedChamber_OuterRoom_EventScript_BrailleMNO::
	end


SealedChamber_OuterRoom_EventScript_BraillePQRS::
	end


SealedChamber_OuterRoom_EventScript_BraillePeriod::
	end


SealedChamber_OuterRoom_EventScript_BrailleTUV::
	end


SealedChamber_OuterRoom_EventScript_BrailleWXYZ::
	end


SealedChamber_OuterRoom_EventScript_InnerRoomEntranceWall::
	end

