SootopolisCity_House7_MapScripts::
	.byte 0


SootopolisCity_House7_MapScripts::
	return


SootopolisCity_House7_Text_CityFromEruptedVolcano::
# 8 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "An underwater volcano erupted and\n"
	.string "forced itself up from the depths.\p"
	.string "Its crater emerged from the sea and\n"
	.string "became filled with rainwater.\p"
	.string "That's how SOOTOPOLIS CITY came into\n"
	.string "being.$"

SootopolisCity_House7_Text_CaveMadeToKeepSomething::
# 12 "data/maps/SootopolisCity_House7/scripts.pory"
	.string "The cave that links SOOTOPOLIS and the\n"
	.string "outside world…\p"
	.string "It seems as if the cave was made to\n"
	.string "keep something from getting out.\p"
	.string "Or am I just imagining things?$"
