FortreeCity_House4_MapScripts::
	.byte 0


FortreeCity_House4_EventScript_Boy::
	end


FortreeCity_House4_EventScript_Wingull::
# 9 "data/maps/FortreeCity_House4/scripts.pory"
	msgbox FortreeCity_House4_Text_Wingull, MSGBOX_DEFAULT
	end


FortreeCity_House4_EventScript_Woman::
# 14 "data/maps/FortreeCity_House4/scripts.pory"
	msgbox FortreeCity_House4_Text_BringsWorldCloserTogether, MSGBOX_NPC
	end


FortreeCity_House4_Text_WelcomeWingullTakeMentalHerb::
# 18 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Good!\n"
	.string "Welcome back, WINGULL!\p"
	.string "Huh? What is this?\n"
	.string "What is it holding?\p"
	.string "A MENTAL HERB?\n"
	.string "It must have picked it up somewhere.\p"
	.string "But I'm not a TRAINER, so you can\n"
	.string "have it.$"

FortreeCity_House4_Text_BringsWorldCloserTogether::
# 22 "data/maps/FortreeCity_House4/scripts.pory"
	.string "By being together with POKéMON,\n"
	.string "people make more and more friends.\p"
	.string "And that brings the world closer\n"
	.string "together. I think it's wonderful!$"

FortreeCity_House4_Text_FriendsFarAwayThanksToWingull::
# 26 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Thanks to my WINGULL, I have friends\n"
	.string "who live far away.$"

FortreeCity_House4_Text_AskedWingullToRunErrand::
# 30 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Heheh, I asked my WINGULL to run\n"
	.string "an errand for me.$"

FortreeCity_House4_Text_Wingull::
# 34 "data/maps/FortreeCity_House4/scripts.pory"
	.string "WINGULL: Pihyoh!$"
