FortreeCity_House4_MapScripts::
	.byte 0


FortreeCity_House4_Text_BringsWorldCloserTogether::
# 5 "data/maps/FortreeCity_House4/scripts.pory"
	.string "By being together with POKéMON, people\n"
	.string "make more and more friends.\p"
	.string "And that brings the world closer\n"
	.string "together. I think it's wonderful!$"

FortreeCity_House4_Text_GoBirdPokemon::
# 9 "data/maps/FortreeCity_House4/scripts.pory"
	.string "There! Go, BIRD POKéMON!$"

FortreeCity_House4_Text_AskedWingullToRunErrand::
# 13 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Heheh, I asked my WINGULL to run an\n"
	.string "errand for me.$"

FortreeCity_House4_Text_WelcomeWingullTakeMentalHerb::
# 17 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Good! Welcome back, WINGULL!\p"
	.string "Huh? What is this? What is it holding?\p"
	.string "A MENTAL HERB? It must have picked it\n"
	.string "up somewhere.\p"
	.string "But I'm not a TRAINER, so you can have\n"
	.string "it.$"

FortreeCity_House4_Text_FriendsFarAwayThanksToWingull::
# 21 "data/maps/FortreeCity_House4/scripts.pory"
	.string "Thanks to my WINGULL, I have friends\n"
	.string "who live far away.$"

FortreeCity_House4_Text_Wingull::
# 25 "data/maps/FortreeCity_House4/scripts.pory"
	.string "WINGULL: Pihyoh!$"
