SilphCo_7F_MapScripts::
# 2 "data/maps/SilphCo_7F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_7F_OnLoad
# 3 "data/maps/SilphCo_7F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SilphCo_7F_OnTransition
	.byte 0


SilphCo_7F_Text_HaveMonForSavingUs::
# 7 "data/maps/SilphCo_7F/scripts.pory"
	.string "Oh! Hi! You're not a ROCKET! You came to\n"
	.string "save us?\l"
	.string "Why, thank you!\p"
	.string "I want you to have this POKMON for\n"
	.string "saving us.$"

SilphCo_7F_Text_ObtainedLaprasFromEmployee::
# 11 "data/maps/SilphCo_7F/scripts.pory"
	.string "{PLAYER} obtained a LAPRAS from the\n"
	.string "SILPH employee!$"

SilphCo_7F_Text_ExplainLapras::
# 15 "data/maps/SilphCo_7F/scripts.pory"
	.string "It's a LAPRAS. It's a very intelligent\n"
	.string "POKMON.\p"
	.string "We kept it in our lab, but it will be much\n"
	.string "better off with you.\p"
	.string "I think you will be a good TRAINER for\n"
	.string "LAPRAS!\p"
	.string "It's a good swimmer. It'll give you a lift\n"
	.string "across water!$"

SilphCo_7F_Text_RocketBossWentToBoardroom::
# 19 "data/maps/SilphCo_7F/scripts.pory"
	.string "TEAM ROCKET's BOSS went to the\n"
	.string "boardroom!\p"
	.string "Is our PRESIDENT okay? I'm worried.$"

SilphCo_7F_Text_OhNo::
# 23 "data/maps/SilphCo_7F/scripts.pory"
	.string "$"

SilphCo_7F_Text_SavedAtLast::
# 27 "data/maps/SilphCo_7F/scripts.pory"
	.string "$"

SilphCo_7F_Text_RocketsAfterMasterBall::
# 31 "data/maps/SilphCo_7F/scripts.pory"
	.string "TEAM ROCKET was after the MASTER BALL,\n"
	.string "which catches any POKMON.$"

SilphCo_7F_Text_CanceledMasterBallProject::
# 35 "data/maps/SilphCo_7F/scripts.pory"
	.string "We canceled the MASTER BALL project\n"
	.string "because of TEAM ROCKET.$"

SilphCo_7F_Text_BadIfTeamRocketTookOver::
# 39 "data/maps/SilphCo_7F/scripts.pory"
	.string "It would be bad if TEAM ROCKET took\n"
	.string "over SILPH or our POKMON.$"

SilphCo_7F_Text_WowYouChasedOffTeamRocket::
# 43 "data/maps/SilphCo_7F/scripts.pory"
	.string "Wow!\p"
	.string "You chased off TEAM ROCKET all by\n"
	.string "yourself?$"

SilphCo_7F_Text_ReallyDangerousHere::
# 47 "data/maps/SilphCo_7F/scripts.pory"
	.string "You! It's really dangerous here!\p"
	.string "You came to save me? You can't!$"

SilphCo_7F_Text_ThankYouSoMuch::
# 51 "data/maps/SilphCo_7F/scripts.pory"
	.string "Thank you so much!$"

SilphCo_7F_Text_Grunt3Intro::
# 55 "data/maps/SilphCo_7F/scripts.pory"
	.string "Uh-oh! I smell a little mouse!$"

SilphCo_7F_Text_Grunt3Defeat::
# 59 "data/maps/SilphCo_7F/scripts.pory"
	.string "Lights out!$"

SilphCo_7F_Text_Grunt3PostBattle::
# 63 "data/maps/SilphCo_7F/scripts.pory"
	.string "You won't find my BOSS by just\n"
	.string "scurrying around!$"

SilphCo_7F_Text_JoshuaIntro::
# 67 "data/maps/SilphCo_7F/scripts.pory"
	.string "Heheh!\p"
	.string "You mistook me for a SILPH worker?$"

SilphCo_7F_Text_JoshuaDefeat::
# 71 "data/maps/SilphCo_7F/scripts.pory"
	.string "I'm done!$"

SilphCo_7F_Text_JoshuaPostBattle::
# 75 "data/maps/SilphCo_7F/scripts.pory"
	.string "Despite your age, you are a skilled\n"
	.string "TRAINER!$"

SilphCo_7F_Text_Grunt1Intro::
# 79 "data/maps/SilphCo_7F/scripts.pory"
	.string "I am one of the four ROCKET BROTHERS!$"

SilphCo_7F_Text_Grunt1Defeat::
# 83 "data/maps/SilphCo_7F/scripts.pory"
	.string "Aack! Brothers, I lost!$"

SilphCo_7F_Text_Grunt1PostBattle::
# 87 "data/maps/SilphCo_7F/scripts.pory"
	.string "Doesn't matter. My brothers will repay\n"
	.string "the favor!$"

SilphCo_7F_Text_Grunt2Intro::
# 91 "data/maps/SilphCo_7F/scripts.pory"
	.string "A child intruder? That must be you!$"

SilphCo_7F_Text_Grunt2Defeat::
# 95 "data/maps/SilphCo_7F/scripts.pory"
	.string "Fine! I lost!$"

SilphCo_7F_Text_Grunt2PostBattle::
# 99 "data/maps/SilphCo_7F/scripts.pory"
	.string "Go on home before my BOSS gets ticked\n"
	.string "off!$"

SilphCo_7F_Text_RivalWhatKeptYou::
# 103 "data/maps/SilphCo_7F/scripts.pory"
	.string "{RIVAL}: What kept you, {PLAYER}?$"

SilphCo_7F_Text_RivalIntro::
# 107 "data/maps/SilphCo_7F/scripts.pory"
	.string "{RIVAL}: Hahaha! I thought you'd\n"
	.string "turn up if I waited here!\p"
	.string "I guess TEAM ROCKET slowed you down!\n"
	.string "Not that I care!\p"
	.string "I saw you in SAFFRON, so I decided to\n"
	.string "see if you got better!$"

SilphCo_7F_Text_RivalDefeat::
# 111 "data/maps/SilphCo_7F/scripts.pory"
	.string "Oh, man! So, you are ready for BOSS\l"
	.string "ROCKET!$"

SilphCo_7F_Text_RivalVictory::
# 115 "data/maps/SilphCo_7F/scripts.pory"
	.string "{RIVAL}\p"
	.string "\l"
	.string "$"

SilphCo_7F_Text_RivalPostBattle::
# 119 "data/maps/SilphCo_7F/scripts.pory"
	.string "Well, {PLAYER}! I'm moving on up and\n"
	.string "ahead!\p"
	.string "By checking my POKDEX, I'm starting to\n"
	.string "see what's strong and\l"
	.string "how they evolve!\p"
	.string "Am I a genius or what?\p"
	.string "I'm going to the POKMON LEAGUE to boot\n"
	.string "out the ELITE FOUR.\p"
	.string "I'll become the world's most powerful\n"
	.string "TRAINER!\p"
	.string "{PLAYER}, well, good luck to you! Don't\n"
	.string "sweat it!\l"
	.string "Smell ya!$"

SilphCo_7F_Text_FloorSign::
# 123 "data/maps/SilphCo_7F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 7F$"
