MahoganyTown_MapScripts::
	.byte 0


MahoganyTown_EventScript_Sign1::
# 6 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_Sign1, MSGBOX_SIGN
	end


MahoganyTown_EventScript_Sign2::
# 15 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_Sign2, MSGBOX_SIGN
	end


MahoganyTown_EventScript_Gym3::
# 24 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_Gym3, MSGBOX_SIGN
	end


MahoganyTown_EventScript_SmithNPC1::
# 33 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_SmithNPC1, MSGBOX_NPC
	end


MahoganyTown_EventScript_SmithNPC2::
# 42 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_SmithNPC2, MSGBOX_NPC
	end


MahoganyTown_EventScript_SmithNPC3::
# 51 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_SmithNPC3, MSGBOX_NPC
	end


MahoganyTown_EventScript_SmithNPC4::
# 60 "data/maps/MahoganyTown/scripts.pory"
	msgbox MahoganyTown_Text_SmithNPC4, MSGBOX_NPC
	end


MahoganyTown_Text_Sign1::
# 10 "data/maps/MahoganyTown/scripts.pory"
	.string "MahoganyTown Sign 1$"

MahoganyTown_Text_Sign2::
# 19 "data/maps/MahoganyTown/scripts.pory"
	.string "MahoganyTown Sign 2$"

MahoganyTown_Text_Gym3::
# 28 "data/maps/MahoganyTown/scripts.pory"
	.string "Mahogany Gym$"

MahoganyTown_Text_SmithNPC1::
# 37 "data/maps/MahoganyTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MahoganyTown_Text_SmithNPC2::
# 46 "data/maps/MahoganyTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

MahoganyTown_Text_SmithNPC3::
# 55 "data/maps/MahoganyTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

MahoganyTown_Text_SmithNPC4::
# 64 "data/maps/MahoganyTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
