CianwoodCity_KirksHouse_MapScripts::
	.byte 0


CianwoodCity_KirksHouse_EventScript_SmithNPC1::
# 5 "data/maps/CianwoodCity_KirksHouse/scripts.pory"
	msgbox CianwoodCity_KirksHouse_Text_SmithNPC1, MSGBOX_NPC
	end


CianwoodCity_KirksHouse_EventScript_SmithNPC2::
# 14 "data/maps/CianwoodCity_KirksHouse/scripts.pory"
	msgbox CianwoodCity_KirksHouse_Text_SmithNPC2, MSGBOX_NPC
	end


CianwoodCity_KirksHouse_Text_SmithNPC1::
# 9 "data/maps/CianwoodCity_KirksHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CianwoodCity_KirksHouse_Text_SmithNPC2::
# 18 "data/maps/CianwoodCity_KirksHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
