Route8_WestEntrance_MapScripts::
	.byte 0


Route8_WestEntrance_EventScript_Guard::
# 5 "data/maps/Route8_WestEntrance/scripts.pory"
	msgbox Route8_WestEntrance_Text_HiHowsItGoing, MSGBOX_NPC
	end


Route8_WestEntrance_EventScript_GuardTriggerBottom::
	end


Route8_WestEntrance_EventScript_GuardTriggerMid::
	end


Route8_WestEntrance_EventScript_GuardTriggerTop::
	end


Route8_WestEntrance_Text_HiHowsItGoing::
# 22 "data/maps/Route8_WestEntrance/scripts.pory"
	.string "Hi, how's it going?$"
