Route8_WestEntrance_MapScripts::
	.byte 0


Route8_WestEntrance_Text_ThirstyOnGuardDuty::
# 5 "data/maps/Route8_WestEntrance/scripts.pory"
	.string "I'm on guard duty. Gee, I'm thirsty,\n"
	.string "though!\p"
	.string "Oh, wait there, the road's closed.$"

Route8_WestEntrance_Text_ThatTeaLooksTasty::
# 9 "data/maps/Route8_WestEntrance/scripts.pory"
	.string "Oh, that TEA It looks awfully tasty$"

Route8_WestEntrance_Text_ThanksIllShareTeaWithGuards::
# 13 "data/maps/Route8_WestEntrance/scripts.pory"
	.string "Huh? I can have this drink? Gee,\n"
	.string "thanks!\l"
	.string "\l"
	.string "Glug, glug\l"
	.string "\l"
	.string "Gulp\l"
	.string "If you want to go to SAFFRON\l"
	.string "CITY\l"
	.string "\l"
	.string "You can go on through.\p"
	.string "I'll share this TEA with the other\n"
	.string "guards!$"

Route8_WestEntrance_Text_HiHowsItGoing::
# 17 "data/maps/Route8_WestEntrance/scripts.pory"
	.string "Hi, how's it going?$"
