CianwoodCity_House1_MapScripts::
	.byte 0


CianwoodCity_House1_EventScript_SmithNPC1::
# 5 "data/maps/CianwoodCity_House1/scripts.pory"
	msgbox CianwoodCity_House1_Text_SmithNPC1, MSGBOX_NPC
	end


CianwoodCity_House1_EventScript_SmithNPC2::
# 14 "data/maps/CianwoodCity_House1/scripts.pory"
	msgbox CianwoodCity_House1_Text_SmithNPC2, MSGBOX_NPC
	end


CianwoodCity_House1_Text_SmithNPC1::
# 9 "data/maps/CianwoodCity_House1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CianwoodCity_House1_Text_SmithNPC2::
# 18 "data/maps/CianwoodCity_House1/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
