OneIsland_Harbor_MapScripts::
# 2 "data/maps/OneIsland_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, OneIsland_Harbor_OnWarp
# 3 "data/maps/OneIsland_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_Harbor_OnFrame
	.byte 0


OneIsland_Harbor_MapScripts::
# 7 "data/maps/OneIsland_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, OneIsland_Harbor_OnWarp
# 8 "data/maps/OneIsland_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, OneIsland_Harbor_OnFrame
	return

