ThreeIsland_House1_MapScripts::
	.byte 0


ThreeIsland_House1_EventScript_DisplayCase::
# 5 "data/maps/ThreeIsland_House1/scripts.pory"
	msgbox ThreeIsland_House1_Text_RareRocksGemsDisplayed, MSGBOX_SIGN
	end


ThreeIsland_House1_EventScript_Lostelle::
	end


ThreeIsland_House1_Text_RareRocksGemsDisplayed::
# 14 "data/maps/ThreeIsland_House1/scripts.pory"
	.string "Rare rocks and gems are displayed.$"
