ThreeIsland_House1_MapScripts::
	.byte 0


ThreeIsland_House1_Text_YoureAlwaysSoCool::
# 5 "data/maps/ThreeIsland_House1/scripts.pory"
	.string "LOSTELLE: Hi, {PLAYER}! You're always\n"
	.string "so cool!\p"
	.string "I'll make lunch for you, too, one day,\n"
	.string "{PLAYER}.$"

ThreeIsland_House1_Text_RareRocksGemsDisplayed::
# 9 "data/maps/ThreeIsland_House1/scripts.pory"
	.string "Rare rocks and gems are displayed.$"
