SixIsland_WaterPath_House1_MapScripts::
	.byte 0


SixIsland_WaterPath_House1_Text_LoveItNeedItHeracross::
# 5 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Hera, hera, HERACROSS! Big and shiny,\n"
	.string "it's the bug boss!\l"
	.string "Love it, need it, HERACROSS!$"

SixIsland_WaterPath_House1_Text_MayIMeasureHeracross::
# 9 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Eeeeek! That's a HERACROSS!\p"
	.string "Please, please, may I measure how big it\n"
	.string "is?$"

SixIsland_WaterPath_House1_Text_ItsXInchesDeserveReward::
# 13 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Eeeek, it's {STR_VAR_2} inches! I've\n"
	.string "never seen anything like this!\l"
	.string "You deserve a reward!$"

SixIsland_WaterPath_House1_Text_WantToSeeBiggerOne::
# 17 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "I want to see a much, much bigger\n"
	.string "HERACROSS than that one.\p"
	.string "Oh, how I adore them, big HERACROSS!$"

SixIsland_WaterPath_House1_Text_ItsXInchesSameAsBefore::
# 21 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Huh? This {STR_VAR_2}-inch\n"
	.string "measurement… Oh, boo! It's the same as\l"
	.string "before.$"

SixIsland_WaterPath_House1_Text_ItsXInchesYInchesWasBiggest::
# 25 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Oh, it's just {STR_VAR_2} inches. The\n"
	.string "HERACROSS before was bigger.\p"
	.string "It was {STR_VAR_3} inches, the\n"
	.string "biggest HERACROSS you've brought me.$"

SixIsland_WaterPath_House1_Text_ThisWontDo::
# 29 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Oh, no! This won't do!\p"
	.string "HERACROSS looks much more macho and\n"
	.string "cool, and has a lovely horn!$"

SixIsland_WaterPath_House1_Text_YourBagIsFull::
# 33 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "Your BAG is full. My reward won't fit.$"

SixIsland_WaterPath_House1_Text_BiggestHeracrossIsXInches::
# 37 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "The biggest HERACROSS that I have ever\n"
	.string "seen measured so far is:\p"
	.string "{STR_VAR_3} inches!$"

SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
# 41 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "It's a blank chart of some sort.\p"
	.string "It has spaces for writing in records of\n"
	.string "some kind.$"
