SixIsland_WaterPath_House1_MapScripts::
	.byte 0


SixIsland_WaterPath_House1_EventScript_Beauty::
	end


SixIsland_WaterPath_House1_EventScript_SizeRecord::
# 11 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	msgbox SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort, MSGBOX_DEFAULT
	end


SixIsland_WaterPath_House1_Text_BlankChartOfSomeSort::
# 17 "data/maps/SixIsland_WaterPath_House1/scripts.pory"
	.string "It's a blank chart of some sort.\p"
	.string "It has spaces for writing in records of\n"
	.string "some kind.$"
