ViridianCity_Gym_MapScripts::
	.byte 0


ViridianCity_Gym_Text_GiovanniIntro::
# 5 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Fwahahaha! Welcome to my hideout!\p"
	.string "It shall be so until I can restore TEAM\n"
	.string "ROCKET to its former glory.\p"
	.string "But, you have found me again. So be it.\l"
	.string "This time, I'm not holding back!\p"
	.string "Once more, you shall face GIOVANNI, the\n"
	.string "greatest TRAINER!{PLAY_BGM}{MUS_RG_ROCKET_HIDEOUT}$"

ViridianCity_Gym_Text_GiovanniDefeat::
# 9 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Ha! That was a truly intense fight.\l"
	.string "You have won!\p"
	.string "As proof, here is the EARTHBADGE! {PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}$"

ViridianCity_Gym_Text_GiovanniPostBattle::
# 13 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Having lost in this fashion, I can't\n"
	.string "face my followers.\l"
	.string "I have betrayed their trust.\p"
	.string "As of today, TEAM ROCKET is finished\n"
	.string "forever!\p"
	.string "As for myself, I shall dedicate my life\n"
	.string "to training again.\p"
	.string "Let us meet again someday! Farewell!$"

ViridianCity_Gym_Text_ExplainEarthBadgeTakeThis::
# 17 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "The EARTHBADGE makes POKMON of any\n"
	.string "level obey without question.\p"
	.string "It is evidence of your mastery as a\n"
	.string "POKMON TRAINER.\p"
	.string "With it, you can challenge the POKMON\n"
	.string "LEAGUE.\p"
	.string "Also, take this TM.\p"
	.string "Consider it a gift for your POKMON\n"
	.string "LEAGUE challenge.$"

ViridianCity_Gym_Text_ReceivedTM26FromGiovanni::
# 21 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "{PLAYER} received TM26 from\n"
	.string "GIOVANNI.$"

ViridianCity_Gym_Text_ExplainTM26::
# 25 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "TM26 contains EARTHQUAKE.\p"
	.string "It is a powerful attack that causes a\n"
	.string "massive tremor.\p"
	.string "I made it when I ran the GYM here, far\n"
	.string "too long ago$"

ViridianCity_Gym_Text_YouDoNotHaveSpace::
# 29 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "You do not have space for this!$"

ViridianCity_Gym_Text_YujiIntro::
# 33 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Heh! You must be running out of steam\l"
	.string "by now!$"

ViridianCity_Gym_Text_YujiDefeat::
# 37 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "I ran out of gas!$"

ViridianCity_Gym_Text_YujiPostBattle::
# 41 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "You'll need power to keep up with our\n"
	.string "GYM LEADER.$"

ViridianCity_Gym_Text_AtsushiIntro::
# 45 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Rrrroar! I'm working myself into a rage!$"

ViridianCity_Gym_Text_AtsushiDefeat::
# 49 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Wargh!$"

ViridianCity_Gym_Text_AtsushiPostBattle::
# 53 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "I'm still not worthy!$"

ViridianCity_Gym_Text_JasonIntro::
# 57 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "POKMON and I, we make wonderful music\n"
	.string "together!$"

ViridianCity_Gym_Text_JasonDefeat::
# 61 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "You are in perfect harmony!$"

ViridianCity_Gym_Text_JasonPostBattle::
# 65 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Do you know the identity of our GYM\n"
	.string "LEADER?$"

ViridianCity_Gym_Text_KiyoIntro::
# 69 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Karate is the ultimate form of martial\n"
	.string "arts!$"

ViridianCity_Gym_Text_KiyoDefeat::
# 73 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Aiyah!$"

ViridianCity_Gym_Text_KiyoPostBattle::
# 77 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "If my POKMON were as good at karate as\n"
	.string "I$"

ViridianCity_Gym_Text_WarrenIntro::
# 81 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "The truly talented win with style.$"

ViridianCity_Gym_Text_WarrenDefeat::
# 85 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "I lost my grip!$"

ViridianCity_Gym_Text_WarrenPostBattle::
# 89 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "The LEADER will scold me for losing this\n"
	.string "way$"

ViridianCity_Gym_Text_TakashiIntro::
# 93 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "I'm the KARATE KING! Your fate rests\n"
	.string "with me!$"

ViridianCity_Gym_Text_TakashiDefeat::
# 97 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Ayah!$"

ViridianCity_Gym_Text_TakashiPostBattle::
# 101 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "The POKMON LEAGUE? You? Don't get\n"
	.string "cocky!$"

ViridianCity_Gym_Text_ColeIntro::
# 105 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Your POKMON will cower at the crack of\n"
	.string "my whip!$"

ViridianCity_Gym_Text_ColeDefeat::
# 109 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Yowch! Whiplash!$"

ViridianCity_Gym_Text_ColePostBattle::
# 113 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Wait! I was just careless!$"

ViridianCity_Gym_Text_SamuelIntro::
# 117 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "VIRIDIAN GYM was closed for a long\n"
	.string "time.\p"
	.string "But now, our LEADER is back!$"

ViridianCity_Gym_Text_SamuelDefeat::
# 121 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "I was beaten?$"

ViridianCity_Gym_Text_SamuelPostBattle::
# 125 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "You can go on to the POKMON LEAGUE only\n"
	.string "by defeating our GYM\l"
	.string "LEADER!$"

ViridianCity_Gym_Text_GymGuyAdvice::
# 129 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "Even I don't know the VIRIDIAN\n"
	.string "LEADER's identity.\p"
	.string "But one thing's certain. This will be the\n"
	.string "toughest of all\l"
	.string "the GYM LEADERS.\p"
	.string "Also, I heard that the TRAINERS here\n"
	.string "like GROUND-type POKMON.$"

ViridianCity_Gym_Text_GymGuyPostVictory::
# 133 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "Blow me away! GIOVANNI was the GYM\n"
	.string "LEADER of VIRIDIAN?$"

ViridianCity_Gym_Text_GymStatue::
# 137 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "VIRIDIAN POKMON GYM LEADER: ?\p"
	.string "WINNING TRAINERS: {RIVAL}$"

ViridianCity_Gym_Text_GymStatuePlayerWon::
# 141 "data/maps/ViridianCity_Gym/scripts.pory"
	.string "VIRIDIAN POKMON GYM LEADER: GIOVANNI\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
