RocketHideout_B1F_MapScripts::
# 2 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, RocketHideout_B1F_OnLoad
# 3 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RocketHideout_B1F_OnTransition
	.byte 0


RocketHideout_B1F_MapScripts::
# 7 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, RocketHideout_B1F_OnLoad
# 8 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RocketHideout_B1F_OnTransition
	return

