RocketHideout_B1F_MapScripts::
# 2 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, RocketHideout_B1F_OnLoad
# 3 "data/maps/RocketHideout_B1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RocketHideout_B1F_OnTransition
	.byte 0


RocketHideout_B1F_Text_Grunt1Intro::
# 7 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Who are you? How did you get here?$"

RocketHideout_B1F_Text_Grunt1Defeat::
# 11 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Oww! Beaten!$"

RocketHideout_B1F_Text_Grunt1PostBattle::
# 15 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Blast it You're dissing TEAM ROCKET,\n"
	.string "aren't you?$"

RocketHideout_B1F_Text_Grunt2Intro::
# 19 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "You broke into TEAM ROCKET's\n"
	.string "operation? What nerve!$"

RocketHideout_B1F_Text_Grunt2Defeat::
# 23 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Boom!$"

RocketHideout_B1F_Text_Grunt2PostBattle::
# 27 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "You're not going to get away with this,\n"
	.string "brat!$"

RocketHideout_B1F_Text_Grunt3Intro::
# 31 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Intruder alert!$"

RocketHideout_B1F_Text_Grunt3Defeat::
# 35 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "I can't do it!$"

RocketHideout_B1F_Text_Grunt3PostBattle::
# 39 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "SILPH SCOPE? Humph! I don't know where\n"
	.string "it is.$"

RocketHideout_B1F_Text_Grunt4Intro::
# 43 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Why did you come here?$"

RocketHideout_B1F_Text_Grunt4Defeat::
# 47 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "This won't do!$"

RocketHideout_B1F_Text_Grunt4PostBattle::
# 51 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Okay, I'll talk Take the elevator to see\n"
	.string "my BOSS.$"

RocketHideout_B1F_Text_Grunt5Intro::
# 55 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Are you lost, you little mouse?$"

RocketHideout_B1F_Text_Grunt5Defeat::
# 59 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Why?$"

RocketHideout_B1F_Text_Grunt5PostBattle::
# 63 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Uh-oh, that ruckus somehow opened the\n"
	.string "door!$"
