RocketHideout_B1F_MapScripts::
	.byte 0


RocketHideout_B1F_EventScript_Grunt1::
# 5 "data/maps/RocketHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_8, RocketHideout_B1F_Text_Grunt1Intro, RocketHideout_B1F_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/RocketHideout_B1F/scripts.pory"
	msgbox RocketHideout_B1F_Text_Grunt1PostBattle
	return


RocketHideout_B1F_EventScript_Grunt2::
# 10 "data/maps/RocketHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_9, RocketHideout_B1F_Text_Grunt2Intro, RocketHideout_B1F_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/RocketHideout_B1F/scripts.pory"
	msgbox RocketHideout_B1F_Text_Grunt2PostBattle
	return


RocketHideout_B1F_EventScript_Grunt3::
# 15 "data/maps/RocketHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_10, RocketHideout_B1F_Text_Grunt3Intro, RocketHideout_B1F_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/RocketHideout_B1F/scripts.pory"
	msgbox RocketHideout_B1F_Text_Grunt3PostBattle
	return


RocketHideout_B1F_EventScript_Grunt4::
# 20 "data/maps/RocketHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_11, RocketHideout_B1F_Text_Grunt4Intro, RocketHideout_B1F_Text_Grunt4Defeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/RocketHideout_B1F/scripts.pory"
	msgbox RocketHideout_B1F_Text_Grunt4PostBattle
	return


RocketHideout_B1F_EventScript_Grunt5::
# 25 "data/maps/RocketHideout_B1F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_12, RocketHideout_B1F_Text_Grunt5Intro, RocketHideout_B1F_Text_Grunt5Defeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/RocketHideout_B1F/scripts.pory"
	msgbox RocketHideout_B1F_Text_Grunt5PostBattle
	return


RocketHideout_B1F_Text_Grunt1Defeat::
# 31 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt1Defeat$"

RocketHideout_B1F_Text_Grunt1Intro::
# 35 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt1Intro$"

RocketHideout_B1F_Text_Grunt1PostBattle::
# 39 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt1PostBattle$"

RocketHideout_B1F_Text_Grunt2Defeat::
# 43 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt2Defeat$"

RocketHideout_B1F_Text_Grunt2Intro::
# 47 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt2Intro$"

RocketHideout_B1F_Text_Grunt2PostBattle::
# 51 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt2PostBattle$"

RocketHideout_B1F_Text_Grunt3Defeat::
# 55 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt3Defeat$"

RocketHideout_B1F_Text_Grunt3Intro::
# 59 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt3Intro$"

RocketHideout_B1F_Text_Grunt3PostBattle::
# 63 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt3PostBattle$"

RocketHideout_B1F_Text_Grunt4Defeat::
# 67 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt4Defeat$"

RocketHideout_B1F_Text_Grunt4Intro::
# 71 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt4Intro$"

RocketHideout_B1F_Text_Grunt4PostBattle::
# 75 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt4PostBattle$"

RocketHideout_B1F_Text_Grunt5Defeat::
# 79 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt5Defeat$"

RocketHideout_B1F_Text_Grunt5Intro::
# 83 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt5Intro$"

RocketHideout_B1F_Text_Grunt5PostBattle::
# 87 "data/maps/RocketHideout_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B1F_Text_Grunt5PostBattle$"
