SeafloorCavern_Room3_MapScripts::
	.byte 0


SeafloorCavern_Room3_Text_ShellyIntro::
# 5 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\p"
	.string "How did you manage to get here without\n"
	.string "a submarine?\l"
	.string "What an impressive child!\p"
	.string "But It won't do to have you meddling\n"
	.string "about here.\p"
	.string "And, I do want payback for what\n"
	.string "happened at the WEATHER INSTITUTE\p"
	.string "I'm going to give you a little taste of\n"
	.string "pain! Resign yourself to it!$"

SeafloorCavern_Room3_Text_ShellyDefeat::
# 9 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha!\p"
	.string "Ouch!$"

SeafloorCavern_Room3_Text_ShellyPostBattle::
# 13 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Ahahahaha! You're so darn strong.\p"
	.string "It's terribly disappointing that you're\n"
	.string "not a TEAM AQUA member.\p"
	.string "You could have enjoyed the fabulous\n"
	.string "world our BOSS has promised as\l"
	.string "one of us$"

SeafloorCavern_Room3_Text_Grunt5Intro::
# 17 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "For our dream to become real, we need\n"
	.string "the power of POKMON.\p"
	.string "But meddlers like you use the power of\n"
	.string "POKMON to mess with us even at\l"
	.string "a place like this!\p"
	.string "Life just doesn't work the way we need\n"
	.string "it to!$"

SeafloorCavern_Room3_Text_Grunt5Defeat::
# 21 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "Gwah!$"

SeafloorCavern_Room3_Text_Grunt5PostBattle::
# 25 "data/maps/SeafloorCavern_Room3/scripts.pory"
	.string "You know, we don't dare question the\n"
	.string "motives of our leader.\p"
	.string "But here you are, just some punk, going\n"
	.string "up against our BOSS.\p"
	.string "Maybe You must be something$"
