Route134_MapScripts::
	.byte 0


Route134_EventScript_Aaron::
# 5 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_AARON, Route134_Text_AaronIntro, Route134_Text_AaronDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_AaronPostBattle
	return


Route134_EventScript_Alex::
# 10 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_ALEX, Route134_Text_AlexIntro, Route134_Text_AlexDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_AlexPostBattle
	return


Route134_EventScript_Hitoshi::
# 15 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_HITOSHI, Route134_Text_HitoshiIntro, Route134_Text_HitoshiDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_HitoshiPostBattle
	return


Route134_EventScript_Hudson::
# 20 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_HUDSON, Route134_Text_HudsonIntro, Route134_Text_HudsonDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_HudsonPostBattle
	return


Route134_EventScript_Jack::
# 25 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_JACK, Route134_Text_JackIntro, Route134_Text_JackDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_JackPostBattle
	return


Route134_EventScript_Kelvin::
# 30 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_KELVIN, Route134_Text_KelvinIntro, Route134_Text_KelvinDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_KelvinPostBattle
	return


Route134_EventScript_Laurel::
# 35 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_LAUREL, Route134_Text_LaurelIntro, Route134_Text_LaurelDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_LaurelPostBattle
	return


Route134_EventScript_Marley::
# 40 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_MARLEY, Route134_Text_MarleyIntro, Route134_Text_MarleyDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_MarleyPostBattle
	return


Route134_EventScript_Reyna::
# 45 "data/maps/Route134/scripts.pory"
	trainerbattle_double TRAINER_REYNA, Route134_Text_ReynaIntro, Route134_Text_ReynaDefeat, Text_NotEnoughMonsForDoubleBattle
# 46 "data/maps/Route134/scripts.pory"
	msgbox Route134_Text_ReynaPostBattle
	return


Route134_Text_AaronDefeat::
# 51 "data/maps/Route134/scripts.pory"
	.string "I willingly concede defeat.$"

Route134_Text_AaronIntro::
# 55 "data/maps/Route134/scripts.pory"
	.string "The savage tide in this area serves to\n"
	.string "make us stronger than ever.$"

Route134_Text_AaronPostBattle::
# 59 "data/maps/Route134/scripts.pory"
	.string "We will return for more training at\n"
	.string "METEOR FALLS.\p"
	.string "If you'd like, you should go, too. It will\n"
	.string "definitely toughen you up!$"

Route134_Text_AlexDefeat::
# 63 "data/maps/Route134/scripts.pory"
	.string "Tuckered out again…$"

Route134_Text_AlexIntro::
# 67 "data/maps/Route134/scripts.pory"
	.string "Okeydokey! That's enough rest, gang!\n"
	.string "It's time for a match!$"

Route134_Text_AlexPostBattle::
# 71 "data/maps/Route134/scripts.pory"
	.string "My BIRD POKéMON get tired quickly after\n"
	.string "a long flight…$"

Route134_Text_HitoshiDefeat::
# 75 "data/maps/Route134/scripts.pory"
	.string "… … … … … … … … … … … …$"

Route134_Text_HitoshiIntro::
# 79 "data/maps/Route134/scripts.pory"
	.string "You're a POKéMON TRAINER. No need for\n"
	.string "words. We battle now.$"

Route134_Text_HitoshiPostBattle::
# 83 "data/maps/Route134/scripts.pory"
	.string "It was I who challenged you, and yet I\n"
	.string "lost. I am deeply shamed…$"

Route134_Text_HudsonDefeat::
# 87 "data/maps/Route134/scripts.pory"
	.string "Now, that's something!$"

Route134_Text_HudsonIntro::
# 91 "data/maps/Route134/scripts.pory"
	.string "Listen, have you seen another SAILOR\n"
	.string "around here?$"

Route134_Text_HudsonPostBattle::
# 95 "data/maps/Route134/scripts.pory"
	.string "Our boat drifted out to sea.\p"
	.string "My buddy's a timid fellow, so I'm worried\n"
	.string "about him.$"

Route134_Text_JackDefeat::
# 99 "data/maps/Route134/scripts.pory"
	.string "Aiyeeeeh!$"

Route134_Text_JackIntro::
# 103 "data/maps/Route134/scripts.pory"
	.string "Even those POKéMON that can swim are\n"
	.string "carried along by the rapid currents.$"

Route134_Text_JackPostBattle::
# 107 "data/maps/Route134/scripts.pory"
	.string "I think POKéMON enjoy the fast-running\n"
	.string "currents around these parts.$"

Route134_Text_KelvinDefeat::
# 111 "data/maps/Route134/scripts.pory"
	.string "Awawawawah! Please, stop! Please!$"

Route134_Text_KelvinIntro::
# 115 "data/maps/Route134/scripts.pory"
	.string "O-our boat! The tide carried it away!$"

Route134_Text_KelvinPostBattle::
# 119 "data/maps/Route134/scripts.pory"
	.string "If we can't SURF, how are we supposed\n"
	.string "to get home?\p"
	.string "Actually, I know a fainted POKéMON can\n"
	.string "still SURF, but it feels wrong.$"

Route134_Text_LaurelDefeat::
# 123 "data/maps/Route134/scripts.pory"
	.string "Oopsie!$"

Route134_Text_LaurelIntro::
# 127 "data/maps/Route134/scripts.pory"
	.string "My LUVDISC are looking for a fun match.\n"
	.string "Will you join us?$"

Route134_Text_LaurelPostBattle::
# 131 "data/maps/Route134/scripts.pory"
	.string "There's a collector who's after the\n"
	.string "SCALES of LUVDISC.$"

Route134_Text_MarleyDefeat::
# 135 "data/maps/Route134/scripts.pory"
	.string "I never knew such a technique existed!\n"
	.string "You've defeated us thoroughly.$"

Route134_Text_MarleyIntro::
# 139 "data/maps/Route134/scripts.pory"
	.string "Can your POKéMON dodge our\n"
	.string "lightning-quick attacks?$"

Route134_Text_MarleyPostBattle::
# 143 "data/maps/Route134/scripts.pory"
	.string "I haven't lost my passion for speed. I\n"
	.string "will try harder.$"

Route134_Text_ReynaDefeat::
# 147 "data/maps/Route134/scripts.pory"
	.string "You're kidding! Explain how I lost!$"

Route134_Text_ReynaIntro::
# 151 "data/maps/Route134/scripts.pory"
	.string "My POKéMON can't be taken down easily!$"

Route134_Text_ReynaPostBattle::
# 155 "data/maps/Route134/scripts.pory"
	.string "Haha! You won, all right!\p"
	.string "I'll work my way back up by taking on\n"
	.string "TRAINERS I happen to meet!$"
