SaffronCity_Mart_MapScripts::
	.byte 0


SaffronCity_Mart_Text_MaxRepelMoreEffectiveThanSuper::
# 5 "data/maps/SaffronCity_Mart/scripts.pory"
	.string "MAX REPEL keeps weaker POKéMON from\n"
	.string "appearing.\p"
	.string "MAX REPEL stays effective longer than\n"
	.string "SUPER REPEL.$"

SaffronCity_Mart_Text_ReviveIsCostly::
# 9 "data/maps/SaffronCity_Mart/scripts.pory"
	.string "REVIVE is costly, but it revives fainted\n"
	.string "POKéMON!$"
