SixIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SixIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
# 4 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SixIsland_PokemonCenter_1F_OnFrame
	.byte 0


SixIsland_PokemonCenter_1F_Text_SomethingHiddenOnThisIsland::
# 8 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	.string "For ten years, I've searched for RUINS.\p"
	.string "No, make that twenty years.\p"
	.string "I get this feeling that there's\n"
	.string "something hidden on this island.$"

SixIsland_PokemonCenter_1F_Text_SomeMonsEvolveByTradingWithHeldItem::
# 12 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	.string "You know of POKéMON that evolve only\n"
	.string "upon trading, yes?\p"
	.string "But did you know that there are still\n"
	.string "others?\p"
	.string "Some POKéMON evolve only when traded\n"
	.string "while holding specific items.$"

SixIsland_PokemonCenter_1F_Text_RivalImpossibleToGetAllMonsAroundHere::
# 16 "data/maps/SixIsland_PokemonCenter_1F/scripts.pory"
	.string "{RIVAL}: Hey, {PLAYER}! How's your\n"
	.string "POKéDEX filling up?\p"
	.string "It looks like it's impossible to get all\n"
	.string "the POKéMON by hanging around\l"
	.string "just these parts.\p"
	.string "Maybe there are POKéMON we don't know\n"
	.string "about somewhere far away…\p"
	.string "… … … … … … … … …\p"
	.string "Well, if I can't do it, there's no way for\n"
	.string "you to get it done.\p"
	.string "I'm not going to get all desperate over\n"
	.string "this.\p"
	.string "I'll keep collecting POKéMON at my own\n"
	.string "pace while I train them.\p"
	.string "That's what I'll do. So there's no point\n"
	.string "staying here.\l"
	.string "I may as well leave for home.\p"
	.string "That's that, then! Smell ya later!$"
