SandgemTown_MapScripts::
	.byte 0


SandgemTown_EventScript_Sign1::
# 5 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_Sign1, MSGBOX_SIGN
	end


SandgemTown_EventScript_Sign2::
# 14 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_Sign2, MSGBOX_SIGN
	end


SandgemTown_EventScript_Sign5::
	end


SandgemTown_EventScript_Sign6::
	end


SandgemTown_EventScript_SmithNPC1::
# 32 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_SmithNPC1, MSGBOX_NPC
	end


SandgemTown_EventScript_SmithNPC2::
# 41 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_SmithNPC2, MSGBOX_NPC
	end


SandgemTown_EventScript_SmithNPC3::
# 50 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_SmithNPC3, MSGBOX_NPC
	end


SandgemTown_EventScript_SmithNPC4::
# 59 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_SmithNPC4, MSGBOX_NPC
	end


SandgemTown_EventScript_SmithNPC5::
# 68 "data/maps/SandgemTown/scripts.pory"
	msgbox SandgemTown_Text_SmithNPC5, MSGBOX_NPC
	end


SandgemTown_Text_Sign1::
# 9 "data/maps/SandgemTown/scripts.pory"
	.string "SandgemTown Sign 1$"

SandgemTown_Text_Sign2::
# 18 "data/maps/SandgemTown/scripts.pory"
	.string "SandgemTown Sign 2$"

SandgemTown_Text_SmithNPC1::
# 36 "data/maps/SandgemTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SandgemTown_Text_SmithNPC2::
# 45 "data/maps/SandgemTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SandgemTown_Text_SmithNPC3::
# 54 "data/maps/SandgemTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

SandgemTown_Text_SmithNPC4::
# 63 "data/maps/SandgemTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

SandgemTown_Text_SmithNPC5::
# 72 "data/maps/SandgemTown/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"
