Route2_House_MapScripts::
	.byte 0


Route2_House_EventScript_Reyley::
	end


Route2_House_EventScript_Scientist::
# 9 "data/maps/Route2_House/scripts.pory"
	msgbox Route2_House_Text_FaintedMonsCanUseFieldMoves, MSGBOX_NPC
	end


Route2_House_Text_FaintedMonsCanUseFieldMoves::
# 14 "data/maps/Route2_House/scripts.pory"
	.string "A fainted POKéMON just has no\n"
	.string "energy left to battle.\p"
	.string "It can still use moves like CUT\n"
	.string "outside of battle.$"
