BattleFrontier_Lounge6_MapScripts::
	.byte 0


BattleFrontier_Lounge6_MapScripts::
	return


BattleFrontier_Lounge6_Text_WouldYouLikeToTrade::
# 8 "data/maps/BattleFrontier_Lounge6/scripts.pory"
	.string "My POKéMON is a {STR_VAR_2}. Do you\n"
	.string "know it?\l"
	.string "It's quite cute and rather nice.\p"
	.string "This little one, I could trade with\n"
	.string "pride!\p"
	.string "Would you like to trade me a\n"
	.string "{STR_VAR_1} for my {STR_VAR_2}?$"

BattleFrontier_Lounge6_Text_PromiseIllBeGoodToIt::
# 12 "data/maps/BattleFrontier_Lounge6/scripts.pory"
	.string "Oh, it's adorable! Thank you!\l"
	.string "I promise I'll be good to it!\p"
	.string "Oh! I hope you'll be good to my\n"
	.string "{STR_VAR_2}, too!$"

BattleFrontier_Lounge6_Text_DontTradeForAnythingButMon::
# 16 "data/maps/BattleFrontier_Lounge6/scripts.pory"
	.string "Oh, I'm sorry! I don't intend to trade\n"
	.string "for anything\l"
	.string "but a {STR_VAR_1}.$"

BattleFrontier_Lounge6_Text_WellThatsFineToo::
# 20 "data/maps/BattleFrontier_Lounge6/scripts.pory"
	.string "Oh, you won't? Well, that's fine, too.\l"
	.string "Please come visit us again.$"

BattleFrontier_Lounge6_Text_SkittySoMuchCuterThanImagined::
# 24 "data/maps/BattleFrontier_Lounge6/scripts.pory"
	.string "Giggle! A SKITTY is so much cuter than I\n"
	.string "had\l"
	.string "imagined. I'm delighted!$"
