PacifidlogTown_House3_MapScripts::
	.byte 0


PacifidlogTown_House3_EventScript_Girl::
# 5 "data/maps/PacifidlogTown_House3/scripts.pory"
	msgbox PacifidlogTown_House3_Text_IsThatAPokedex, MSGBOX_NPC
	end


PacifidlogTown_House3_EventScript_Trader::
	end


PacifidlogTown_House3_Text_WontAcceptAnyLessThanRealMon::
# 13 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "No, no, no! I won't accept any\n"
	.string "less than a real {STR_VAR_1}!$"

PacifidlogTown_House3_Text_ReallyWantedToGetBagon::
# 17 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "I know I could go looking for one\n"
	.string "on my own, but…\p"
	.string "But I really wanted to get a BAGON\n"
	.string "that another TRAINER caught…$"

PacifidlogTown_House3_Text_IsThatAPokedex::
# 21 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Is that a POKéDEX?\p"
	.string "Did you get to meet a lot of different\n"
	.string "POKéMON?\p"
	.string "I wish I was like you.$"

PacifidlogTown_House3_Text_NotDesperateOrAnything::
# 25 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Oh, so you're not going to go through\n"
	.string "with this?\p"
	.string "That's cool. I'm not desperate to make\n"
	.string "a trade or anything.$"
