PacifidlogTown_House3_MapScripts::
	.byte 0


PacifidlogTown_House3_Text_WillingToTradeIt::
# 5 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Check out this {STR_VAR_2}!\p"
	.string "It's the {STR_VAR_2} that I caught\n"
	.string "yesterday to celebrate my birthday!\p"
	.string "Oh, I can see that you want it! After\n"
	.string "all, it's priceless!\p"
	.string "I'll tell you what. I might be willing to\n"
	.string "trade it for a {STR_VAR_1}.$"

PacifidlogTown_House3_Text_ItsSubtlyDifferentThankYou::
# 9 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Oh, so this is a {STR_VAR_1}?\p"
	.string "It's sort of like a {STR_VAR_2}, and\n"
	.string "yet it's subtly different.\p"
	.string "Thank you!$"

PacifidlogTown_House3_Text_WontAcceptAnyLessThanRealMon::
# 13 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "No, no, no! I won't accept any less than\n"
	.string "a real {STR_VAR_1}!$"

PacifidlogTown_House3_Text_NotDesperateOrAnything::
# 17 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Oh, so you're not going to go through\n"
	.string "with this?\p"
	.string "That's cool. I'm not desperate to make a\n"
	.string "trade or anything.$"

PacifidlogTown_House3_Text_ReallyWantedToGetBagon::
# 21 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "I know I could go looking for one on my\n"
	.string "own, but\p"
	.string "But I really wanted to get a BAGON that\n"
	.string "another TRAINER caught$"

PacifidlogTown_House3_Text_IsThatAPokedex::
# 25 "data/maps/PacifidlogTown_House3/scripts.pory"
	.string "Is that a POKDEX?\p"
	.string "Did you get to meet a lot of different\n"
	.string "POKMON?\p"
	.string "I wish I was like you.$"
