RocketHideout_B4F_MapScripts::
	.byte 0


RocketHideout_B4F_EventScript_Giovanni::
	end


RocketHideout_B4F_EventScript_Grunt1::
# 9 "data/maps/RocketHideout_B4F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_18, RocketHideout_B4F_Text_Grunt1Intro, RocketHideout_B4F_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 10 "data/maps/RocketHideout_B4F/scripts.pory"
	msgbox RocketHideout_B4F_Text_Grunt1PostBattle
	return


RocketHideout_B4F_EventScript_Grunt2::
# 14 "data/maps/RocketHideout_B4F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_16, RocketHideout_B4F_Text_Grunt2Intro, RocketHideout_B4F_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 15 "data/maps/RocketHideout_B4F/scripts.pory"
	msgbox RocketHideout_B4F_Text_Grunt2PostBattle
	return


RocketHideout_B4F_EventScript_Grunt3::
# 19 "data/maps/RocketHideout_B4F/scripts.pory"
	trainerbattle_double TRAINER_TEAM_ROCKET_GRUNT_17, RocketHideout_B4F_Text_Grunt3Intro, RocketHideout_B4F_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 20 "data/maps/RocketHideout_B4F/scripts.pory"
	msgbox RocketHideout_B4F_Text_Grunt3PostBattle
	return


RocketHideout_B4F_EventScript_LiftKey::
	end


RocketHideout_B4F_EventScript_SilphScope::
	end


RocketHideout_B4F_Text_Grunt1Defeat::
# 33 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt1Defeat$"

RocketHideout_B4F_Text_Grunt1Intro::
# 37 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt1Intro$"

RocketHideout_B4F_Text_Grunt1PostBattle::
# 41 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt1PostBattle$"

RocketHideout_B4F_Text_Grunt2Defeat::
# 45 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt2Defeat$"

RocketHideout_B4F_Text_Grunt2Intro::
# 49 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt2Intro$"

RocketHideout_B4F_Text_Grunt2PostBattle::
# 53 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt2PostBattle$"

RocketHideout_B4F_Text_Grunt3Defeat::
# 57 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt3Defeat$"

RocketHideout_B4F_Text_Grunt3Intro::
# 61 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt3Intro$"

RocketHideout_B4F_Text_Grunt3PostBattle::
# 65 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RocketHideout_B4F_Text_Grunt3PostBattle$"
