RocketHideout_B4F_MapScripts::
# 2 "data/maps/RocketHideout_B4F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, RocketHideout_B4F_OnLoad
	.byte 0


RocketHideout_B4F_Text_GiovanniIntro::
# 6 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "So! I must say, I am impressed you got\n"
	.string "here.\p"
	.string "TEAM ROCKET captures POKMON from\n"
	.string "around the world.\p"
	.string "They're important tools for keeping our\n"
	.string "criminal enterprise going.\p"
	.string "I am the leader, GIOVANNI!\p"
	.string "For your insolence, you will feel a world\n"
	.string "of pain!$"

RocketHideout_B4F_Text_GiovanniDefeat::
# 10 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "WHAT! This can't be!$"

RocketHideout_B4F_Text_GiovanniPostBattle::
# 14 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "I see that you raise POKMON with utmost\n"
	.string "care.\p"
	.string "A child like you would never understand\n"
	.string "what I hope to achieve.\p"
	.string "I shall step aside this time!\p"
	.string "I hope we meet again$"

RocketHideout_B4F_Text_Grunt2Intro::
# 18 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "I know you! You ruined our plans at MT.\n"
	.string "MOON!$"

RocketHideout_B4F_Text_Grunt2Defeat::
# 22 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Burned again!$"

RocketHideout_B4F_Text_Grunt2PostBattle::
# 26 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Do you have something against TEAM\n"
	.string "ROCKET?$"

RocketHideout_B4F_Text_Grunt3Intro::
# 30 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "How can you not see the beauty of our\n"
	.string "evil?$"

RocketHideout_B4F_Text_Grunt3Defeat::
# 34 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Ayaya!$"

RocketHideout_B4F_Text_Grunt3PostBattle::
# 38 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "BOSS! I'm sorry I failed you!$"

RocketHideout_B4F_Text_Grunt1Intro::
# 42 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "The elevator doesn't work? Who has the\n"
	.string "LIFT KEY?$"

RocketHideout_B4F_Text_Grunt1Defeat::
# 46 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "No!$"

RocketHideout_B4F_Text_Grunt1PostBattle::
# 50 "data/maps/RocketHideout_B4F/scripts.pory"
	.string "Oh, no! I dropped the LIFT KEY!$"
