SSAnne_B1F_Room3_MapScripts::
	.byte 0


SSAnne_B1F_Room3_Text_DylanIntro::
# 5 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	.string "I like feisty kids like you!$"

SSAnne_B1F_Room3_Text_DylanDefeat::
# 9 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	.string "Argh! Lost it!$"

SSAnne_B1F_Room3_Text_DylanPostBattle::
# 13 "data/maps/SSAnne_B1F_Room3/scripts.pory"
	.string "Sea POKéMON live in deep water. You'll\n"
	.string "need a ROD to fish them up!$"
