CianwoodCity_Gym_MapScripts::
	.byte 0


CianwoodCity_Gym_EventScript_SmithNPC1::
# 5 "data/maps/CianwoodCity_Gym/scripts.pory"
	msgbox CianwoodCity_Gym_Text_SmithNPC1, MSGBOX_NPC
	end


CianwoodCity_Gym_EventScript_SmithNPC2::
# 14 "data/maps/CianwoodCity_Gym/scripts.pory"
	msgbox CianwoodCity_Gym_Text_SmithNPC2, MSGBOX_NPC
	end


CianwoodCity_Gym_EventScript_SmithNPC3::
# 23 "data/maps/CianwoodCity_Gym/scripts.pory"
	msgbox CianwoodCity_Gym_Text_SmithNPC3, MSGBOX_NPC
	end


CianwoodCity_Gym_EventScript_SmithNPC4::
# 32 "data/maps/CianwoodCity_Gym/scripts.pory"
	msgbox CianwoodCity_Gym_Text_SmithNPC4, MSGBOX_NPC
	end


CianwoodCity_Gym_EventScript_SmithNPC5::
# 41 "data/maps/CianwoodCity_Gym/scripts.pory"
	msgbox CianwoodCity_Gym_Text_SmithNPC5, MSGBOX_NPC
	end


CianwoodCity_Gym_Text_SmithNPC1::
# 9 "data/maps/CianwoodCity_Gym/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CianwoodCity_Gym_Text_SmithNPC2::
# 18 "data/maps/CianwoodCity_Gym/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

CianwoodCity_Gym_Text_SmithNPC3::
# 27 "data/maps/CianwoodCity_Gym/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

CianwoodCity_Gym_Text_SmithNPC4::
# 36 "data/maps/CianwoodCity_Gym/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

CianwoodCity_Gym_Text_SmithNPC5::
# 45 "data/maps/CianwoodCity_Gym/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"
