WhirlIslands_NorthWestEntrance_MapScripts::
	.byte 0


WhirlIslands_NorthWestEntrance_EventScript_SmithNPC1::
# 5 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	msgbox WhirlIslands_NorthWestEntrance_Text_SmithNPC1, MSGBOX_NPC
	end


WhirlIslands_NorthWestEntrance_EventScript_SmithNPC2::
# 14 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	msgbox WhirlIslands_NorthWestEntrance_Text_SmithNPC2, MSGBOX_NPC
	end


WhirlIslands_NorthWestEntrance_EventScript_SmithNPC3::
# 23 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	msgbox WhirlIslands_NorthWestEntrance_Text_SmithNPC3, MSGBOX_NPC
	end


WhirlIslands_NorthWestEntrance_Text_SmithNPC1::
# 9 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

WhirlIslands_NorthWestEntrance_Text_SmithNPC2::
# 18 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

WhirlIslands_NorthWestEntrance_Text_SmithNPC3::
# 27 "data/maps/WhirlIslands_NorthWestEntrance/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
