SixIsland_RuinValley_MapScripts::
# 2 "data/maps/SixIsland_RuinValley/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SixIsland_RuinValley_OnLoad
	.byte 0


SixIsland_RuinValley_Text_CantFigureOutHowToGetInside::
# 6 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "I can't figure out how I'm supposed to\n"
	.string "get inside.$"

SixIsland_RuinValley_Text_IFoundThisPlace::
# 10 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Let me tell you, I found this place.\p"
	.string "Don't look so envious, will you?$"

SixIsland_RuinValley_Text_CheckDoorMoreThoroughly::
# 14 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "The door doesn't budge at all. Check it\n"
	.string "more thoroughly?$"

SixIsland_RuinValley_Text_LeftDoorAlone::
# 18 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "{PLAYER} left the door alone.$"

SixIsland_RuinValley_Text_SeveralDotsOnTheDoor::
# 22 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "On closer inspection, there are several\n"
	.string "dots on the door$"

SixIsland_RuinValley_Text_DoorIsOpen::
# 26 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "The door is open.$"

SixIsland_RuinValley_Text_StanlyIntro::
# 30 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "There appear to be many secrets still\n"
	.string "unsolved in this world.$"

SixIsland_RuinValley_Text_StanlyDefeat::
# 34 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Hmm$"

SixIsland_RuinValley_Text_StanlyPostBattle::
# 38 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "I suggest to you that you, too, give a\n"
	.string "thought to the secrets and\l"
	.string "mysteries of our world once a day.$"

SixIsland_RuinValley_Text_FosterIntro::
# 42 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "I'm curious, what compelled you to come\n"
	.string "here?$"

SixIsland_RuinValley_Text_FosterDefeat::
# 46 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "It's been so long since I battled, my\n"
	.string "instincts are off.$"

SixIsland_RuinValley_Text_FosterPostBattle::
# 50 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "There are several ruins on the SEVII\n"
	.string "ISLANDS.\p"
	.string "The majority of them date back a long\n"
	.string "way.$"

SixIsland_RuinValley_Text_LarryIntro::
# 54 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "It's been said that there are\n"
	.string "mysterious stones on this island.\p"
	.string "I suspect it has something to do with\n"
	.string "the ruins here.$"

SixIsland_RuinValley_Text_LarryDefeat::
# 58 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Oh, interesting.$"

SixIsland_RuinValley_Text_LarryPostBattle::
# 62 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Those ruins over there\p"
	.string "I haven't had any luck in finding how I\n"
	.string "can get inside.$"

SixIsland_RuinValley_Text_DarylIntro::
# 66 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "A battle with you, so high up!$"

SixIsland_RuinValley_Text_DarylDefeat::
# 70 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Oh, the heartbreak of losing so easily\n"
	.string "to you!$"

SixIsland_RuinValley_Text_DarylPostBattle::
# 74 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "Experience the joy of climbing!$"

SixIsland_RuinValley_Text_HectorIntro::
# 78 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "I'm pretty familiar with the land around\n"
	.string "these parts.$"

SixIsland_RuinValley_Text_HectorDefeat::
# 82 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "You don't need to be so pushy. I'll be\n"
	.string "happy to tell you.$"

SixIsland_RuinValley_Text_HectorPostBattle::
# 86 "data/maps/SixIsland_RuinValley/scripts.pory"
	.string "The door to the ruins It has these\n"
	.string "strange patterns\l"
	.string "engraved on the outside.\p"
	.string "I don't know what they mean, though.$"
