SafariZone_North_MapScripts::
	.byte 0


SafariZone_North_Text_RestHouse::
# 5 "data/maps/SafariZone_North/scripts.pory"
	.string "REST HOUSE$"

SafariZone_North_Text_SecretHouseStillAhead::
# 9 "data/maps/SafariZone_North/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The SECRET HOUSE is still ahead.$"

SafariZone_North_Text_Area2::
# 13 "data/maps/SafariZone_North/scripts.pory"
	.string "AREA 2$"

SafariZone_North_Text_ZigzagThroughTallGrass::
# 17 "data/maps/SafariZone_North/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "POKMON hide in tall grass.\p"
	.string "Zigzag through grassy areas to flush\n"
	.string "them out.$"

SafariZone_North_Text_WinFreeHMFindSecretHouse::
# 21 "data/maps/SafariZone_North/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Win a free HM for finding the SECRET\n"
	.string "HOUSE.$"
