RuinsOfAlph_KabutoItemRoom_MapScripts::
	.byte 0


RuinsOfAlph_KabutoItemRoom_EventScript_SmithNPC1::
# 5 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	msgbox RuinsOfAlph_KabutoItemRoom_Text_SmithNPC1, MSGBOX_NPC
	end


RuinsOfAlph_KabutoItemRoom_EventScript_SmithNPC2::
# 14 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	msgbox RuinsOfAlph_KabutoItemRoom_Text_SmithNPC2, MSGBOX_NPC
	end


RuinsOfAlph_KabutoItemRoom_EventScript_SmithNPC3::
# 23 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	msgbox RuinsOfAlph_KabutoItemRoom_Text_SmithNPC3, MSGBOX_NPC
	end


RuinsOfAlph_KabutoItemRoom_Text_SmithNPC1::
# 9 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

RuinsOfAlph_KabutoItemRoom_Text_SmithNPC2::
# 18 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

RuinsOfAlph_KabutoItemRoom_Text_SmithNPC3::
# 27 "data/maps/RuinsOfAlph_KabutoItemRoom/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
