VictoryRoad_2F_MapScripts::
	.byte 0


VictoryRoad_2F_EventScript_Daisuke::
# 5 "data/maps/VictoryRoad_2F/scripts.pory"
	trainerbattle_double TRAINER_BLACK_BELT_DAISUKE, VictoryRoad_2F_Text_DaisukeIntro, VictoryRoad_2F_Text_DaisukeDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/VictoryRoad_2F/scripts.pory"
	msgbox VictoryRoad_2F_Text_DaisukePostBattle
	return


VictoryRoad_2F_EventScript_Dawson::
# 10 "data/maps/VictoryRoad_2F/scripts.pory"
	trainerbattle_double TRAINER_POKEMANIAC_DAWSON, VictoryRoad_2F_Text_DawsonIntro, VictoryRoad_2F_Text_DawsonDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/VictoryRoad_2F/scripts.pory"
	msgbox VictoryRoad_2F_Text_DawsonPostBattle
	return


VictoryRoad_2F_EventScript_DoubleEdgeTutor::
	end


VictoryRoad_2F_EventScript_FloorSwitch1::
	end


VictoryRoad_2F_EventScript_FloorSwitch2::
	end


VictoryRoad_2F_EventScript_Gregory::
# 27 "data/maps/VictoryRoad_2F/scripts.pory"
	trainerbattle_double TRAINER_JUGGLER_GREGORY, VictoryRoad_2F_Text_GregoryIntro, VictoryRoad_2F_Text_GregoryDefeat, Text_NotEnoughMonsForDoubleBattle
# 28 "data/maps/VictoryRoad_2F/scripts.pory"
	msgbox VictoryRoad_2F_Text_GregoryPostBattle
	return


VictoryRoad_2F_EventScript_ItemFullHeal::
	end


VictoryRoad_2F_EventScript_ItemGuardSpec::
	end


VictoryRoad_2F_EventScript_ItemTM07::
	end


VictoryRoad_2F_EventScript_ItemTM37::
	end


VictoryRoad_2F_EventScript_Nelson::
# 48 "data/maps/VictoryRoad_2F/scripts.pory"
	trainerbattle_double TRAINER_JUGGLER_NELSON, VictoryRoad_2F_Text_NelsonIntro, VictoryRoad_2F_Text_NelsonDefeat, Text_NotEnoughMonsForDoubleBattle
# 49 "data/maps/VictoryRoad_2F/scripts.pory"
	msgbox VictoryRoad_2F_Text_NelsonPostBattle
	return


VictoryRoad_2F_EventScript_Vincent::
# 53 "data/maps/VictoryRoad_2F/scripts.pory"
	trainerbattle_double TRAINER_TAMER_VINCENT, VictoryRoad_2F_Text_VincentIntro, VictoryRoad_2F_Text_VincentDefeat, Text_NotEnoughMonsForDoubleBattle
# 54 "data/maps/VictoryRoad_2F/scripts.pory"
	msgbox VictoryRoad_2F_Text_VincentPostBattle
	return


VictoryRoad_2F_Text_DaisukeDefeat::
# 59 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DaisukeDefeat$"

VictoryRoad_2F_Text_DaisukeIntro::
# 63 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DaisukeIntro$"

VictoryRoad_2F_Text_DaisukePostBattle::
# 67 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DaisukePostBattle$"

VictoryRoad_2F_Text_DawsonDefeat::
# 71 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DawsonDefeat$"

VictoryRoad_2F_Text_DawsonIntro::
# 75 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DawsonIntro$"

VictoryRoad_2F_Text_DawsonPostBattle::
# 79 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_DawsonPostBattle$"

VictoryRoad_2F_Text_GregoryDefeat::
# 83 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_GregoryDefeat$"

VictoryRoad_2F_Text_GregoryIntro::
# 87 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_GregoryIntro$"

VictoryRoad_2F_Text_GregoryPostBattle::
# 91 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_GregoryPostBattle$"

VictoryRoad_2F_Text_NelsonDefeat::
# 95 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_NelsonDefeat$"

VictoryRoad_2F_Text_NelsonIntro::
# 99 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_NelsonIntro$"

VictoryRoad_2F_Text_NelsonPostBattle::
# 103 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_NelsonPostBattle$"

VictoryRoad_2F_Text_VincentDefeat::
# 107 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_VincentDefeat$"

VictoryRoad_2F_Text_VincentIntro::
# 111 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_VincentIntro$"

VictoryRoad_2F_Text_VincentPostBattle::
# 115 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_2F_Text_VincentPostBattle$"
