VictoryRoad_2F_MapScripts::
# 2 "data/maps/VictoryRoad_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, VictoryRoad_2F_OnLoad
	.byte 0


VictoryRoad_2F_Text_DawsonIntro::
# 6 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "If you can get through here, you can go\n"
	.string "meet the ELITE FOUR.$"

VictoryRoad_2F_Text_DawsonDefeat::
# 10 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "No! Unbelievable!$"

VictoryRoad_2F_Text_DawsonPostBattle::
# 14 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "I can beat you when it comes to\n"
	.string "knowledge about POKéMON!$"

VictoryRoad_2F_Text_DaisukeIntro::
# 18 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "This here is VICTORY ROAD. It's the\n"
	.string "final test for TRAINERS!$"

VictoryRoad_2F_Text_DaisukeDefeat::
# 22 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Atcho!$"

VictoryRoad_2F_Text_DaisukePostBattle::
# 26 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "If you get stuck, try moving some\n"
	.string "boulders around.$"

VictoryRoad_2F_Text_NelsonIntro::
# 30 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Ah, so you wish to challenge the ELITE\n"
	.string "FOUR?$"

VictoryRoad_2F_Text_NelsonDefeat::
# 34 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "You got me!$"

VictoryRoad_2F_Text_NelsonPostBattle::
# 38 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "{RIVAL} also came through here.$"

VictoryRoad_2F_Text_VincentIntro::
# 42 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Come on! I'll whip you!$"

VictoryRoad_2F_Text_VincentDefeat::
# 46 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "I got whipped!$"

VictoryRoad_2F_Text_VincentPostBattle::
# 50 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "You earned the right to be on VICTORY\n"
	.string "ROAD…$"

VictoryRoad_2F_Text_GregoryIntro::
# 54 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Is VICTORY ROAD too tough?$"

VictoryRoad_2F_Text_GregoryDefeat::
# 58 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Well done!$"

VictoryRoad_2F_Text_GregoryPostBattle::
# 62 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "Many TRAINERS give up their challenge\n"
	.string "here and go home.$"

VictoryRoad_2F_Text_Gyaoo::
# 66 "data/maps/VictoryRoad_2F/scripts.pory"
	.string "ギヤーオ！$"
