GoldenrodCity_GatehouseNorth_MapScripts::
	.byte 0


GoldenrodCity_GatehouseNorth_EventScript_SmithNPC1::
# 5 "data/maps/GoldenrodCity_GatehouseNorth/scripts.pory"
	msgbox GoldenrodCity_GatehouseNorth_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_GatehouseNorth_EventScript_SmithNPC2::
# 14 "data/maps/GoldenrodCity_GatehouseNorth/scripts.pory"
	msgbox GoldenrodCity_GatehouseNorth_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_GatehouseNorth_Text_SmithNPC1::
# 9 "data/maps/GoldenrodCity_GatehouseNorth/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_GatehouseNorth_Text_SmithNPC2::
# 18 "data/maps/GoldenrodCity_GatehouseNorth/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
