SafariZone_West_RestHouse_MapScripts::
	.byte 0


SafariZone_West_RestHouse_EventScript_CooltrainerF::
# 5 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_HikedLotsDidntSeeMonIWanted, MSGBOX_NPC
	end


SafariZone_West_RestHouse_EventScript_Man::
# 10 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_BaitMakesMonStickAround, MSGBOX_NPC
	end


SafariZone_West_RestHouse_EventScript_Scientist::
# 15 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	msgbox SafariZone_West_Text_RocksMakeMonRunButEasierCatch, MSGBOX_NPC
	end


SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
# 20 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "I hiked a lot, but I didn't see any\n"
	.string "POKéMON I wanted.$"

SafariZone_West_Text_BaitMakesMonStickAround::
# 24 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "Using BAIT will make POKéMON more\n"
	.string "likely to stick around if they get\l"
	.string "busy eating.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
# 28 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "Tossing ROCKS at POKéMON might\n"
	.string "make them run, but they'll be\l"
	.string "easier to catch.$"
