SafariZone_West_RestHouse_MapScripts::
	.byte 0


SafariZone_West_Text_KogaPatrolsSafariEverySoOften::
# 5 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "The SAFARI ZONE's huge, wouldn't you\n"
	.string "say?\p"
	.string "FUCHSIA's GYM LEADER, KOGA, patrols the\n"
	.string "grounds every so often.\p"
	.string "Thanks to him, we can play here knowing\n"
	.string "that we're safe.$"

SafariZone_West_Text_RocksMakeMonRunButEasierCatch::
# 9 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "Tossing ROCKS at POKéMON might make\n"
	.string "them run, but they'll be\l"
	.string "easier to catch.$"

SafariZone_West_Text_BaitMakesMonStickAround::
# 13 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "Using BAIT will make POKéMON more likely\n"
	.string "to stick around if they get\l"
	.string "busy eating.$"

SafariZone_West_Text_HikedLotsDidntSeeMonIWanted::
# 17 "data/maps/SafariZone_West_RestHouse/scripts.pory"
	.string "I hiked a lot, but I didn't see any\n"
	.string "POKéMON I wanted.$"
