FallarborTown_MapScripts::
	.byte 0


FallarborTown_EventScript_Azurill::
# 5 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_Azurill, MSGBOX_DEFAULT
	end


FallarborTown_EventScript_BattleTentSign::
# 10 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_BattleTentSign, MSGBOX_SIGN
	end


FallarborTown_EventScript_ExpertM::
	end


FallarborTown_EventScript_Gentleman::
# 19 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_HaveYouChallengedFlannery, MSGBOX_NPC
	end


FallarborTown_EventScript_Girl::
# 24 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_MyPreciousAzurill, MSGBOX_NPC
	end


FallarborTown_EventScript_MoveTutorSign::
# 29 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_MoveTutorSign, MSGBOX_SIGN
	end


FallarborTown_EventScript_TownSign::
# 34 "data/maps/FallarborTown/scripts.pory"
	msgbox FallarborTown_Text_TownSign, MSGBOX_SIGN
	end


FallarborTown_Text_TownSign::
# 39 "data/maps/FallarborTown/scripts.pory"
	.string "FALLARBOR TOWN “A farm community with\n"
	.string "small gardens.”$"

FallarborTown_Text_MoveTutorSign::
# 43 "data/maps/FallarborTown/scripts.pory"
	.string "MOVE TUTOR'S HOUSE “New moves taught\n"
	.string "to POKéMON.”$"

FallarborTown_Text_BattleTentSign::
# 47 "data/maps/FallarborTown/scripts.pory"
	.string "BATTLE TENT FALLARBOR SITE “May the\n"
	.string "Greatest Teams Gather!”$"

FallarborTown_Text_Azurill::
# 51 "data/maps/FallarborTown/scripts.pory"
	.string "AZURILL: Rooreelooo.$"

FallarborTown_Text_HaveYouChallengedFlannery::
# 55 "data/maps/FallarborTown/scripts.pory"
	.string "Have you already challenged FLANNERY,\n"
	.string "the LEADER of LAVARIDGE GYM?\p"
	.string "The girl's grandfather was famous.\n"
	.string "He was one of the ELITE FOUR in the\l"
	.string "POKéMON LEAGUE at one point.\p"
	.string "It wouldn't surprise me to see FLANNERY\n"
	.string "become a great TRAINER in her own\l"
	.string "right.$"

FallarborTown_Text_MyPreciousAzurill::
# 59 "data/maps/FallarborTown/scripts.pory"
	.string "See! Take a look!\n"
	.string "This is my precious AZURILL!\p"
	.string "It's slick and smooth and plushy, too!$"

FallarborTown_Text_RegionKnownForMeteors::
# 63 "data/maps/FallarborTown/scripts.pory"
	.string "This region's been known for meteors\n"
	.string "since the olden days.\p"
	.string "They say METEOR FALLS was gouged out\n"
	.string "by a falling meteorite long ago.$"
