FallarborTown_MapScripts::
# 2 "data/maps/FallarborTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FallarborTown_OnTransition
	.byte 0


FallarborTown_MapScripts::
# 6 "data/maps/FallarborTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FallarborTown_OnTransition
	return


FallarborTown_Text_ShadyCharactersCozmosHome::
# 10 "data/maps/FallarborTown/scripts.pory"
	.string "Something's happening, and I don't like\n"
	.string "it!\p"
	.string "I've seen shady characters wandering\n"
	.string "in and out of PROF. COZMO's home…$"

FallarborTown_Text_RegionKnownForMeteors::
# 14 "data/maps/FallarborTown/scripts.pory"
	.string "This region's been known for meteors\n"
	.string "since the olden days.\p"
	.string "They say METEOR FALLS was gouged out\n"
	.string "by a falling meteorite long ago.$"

FallarborTown_Text_MyPreciousAzurill::
# 18 "data/maps/FallarborTown/scripts.pory"
	.string "See! Take a look! This is my precious\n"
	.string "AZURILL!\p"
	.string "It's slick and smooth and plushy, too!$"

FallarborTown_Text_Azurill::
# 22 "data/maps/FallarborTown/scripts.pory"
	.string "AZURILL: Rooreelooo.$"

FallarborTown_Text_HaveYouChallengedFlannery::
# 26 "data/maps/FallarborTown/scripts.pory"
	.string "Have you already challenged FLANNERY,\n"
	.string "the LEADER of LAVARIDGE GYM?\p"
	.string "The girl's grandfather was famous. He\n"
	.string "was one of the ELITE FOUR in the\l"
	.string "POKéMON LEAGUE at one point.\p"
	.string "It wouldn't surprise me to see FLANNERY\n"
	.string "become a great TRAINER in her own\l"
	.string "right.$"

FallarborTown_Text_BattleTentSign::
# 30 "data/maps/FallarborTown/scripts.pory"
	.string "BATTLE TENT FALLARBOR SITE “May the\n"
	.string "Greatest Teams Gather!”$"

FallarborTown_Text_TownSign::
# 34 "data/maps/FallarborTown/scripts.pory"
	.string "FALLARBOR TOWN “A farm community with\n"
	.string "small gardens.”$"

FallarborTown_Text_MoveTutorSign::
# 38 "data/maps/FallarborTown/scripts.pory"
	.string "MOVE TUTOR'S HOUSE “New moves taught\n"
	.string "to POKéMON.”$"
