MtPyre_Summit_MapScripts::
	.byte 0


MtPyre_Summit_EventScript_ArchieMaxieTrigger0::
	end


MtPyre_Summit_EventScript_ArchieMaxieTrigger1::
	end


MtPyre_Summit_EventScript_ArchieMaxieTrigger2::
	end


MtPyre_Summit_EventScript_Grunt1::
# 17 "data/maps/MtPyre_Summit/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_PYRE, MtPyre_Summit_Text_Grunt1Intro, MtPyre_Summit_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 18 "data/maps/MtPyre_Summit/scripts.pory"
	msgbox MtPyre_Summit_Text_Grunt1PostBattle
	return


MtPyre_Summit_EventScript_Grunt2::
# 22 "data/maps/MtPyre_Summit/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_PYRE_2, MtPyre_Summit_Text_Grunt2Intro, MtPyre_Summit_Text_Grunt2Defeat, Text_NotEnoughMonsForDoubleBattle
# 23 "data/maps/MtPyre_Summit/scripts.pory"
	msgbox MtPyre_Summit_Text_Grunt2PostBattle
	return


MtPyre_Summit_EventScript_Grunt3::
# 27 "data/maps/MtPyre_Summit/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_PYRE_3, MtPyre_Summit_Text_Grunt3Intro, MtPyre_Summit_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 28 "data/maps/MtPyre_Summit/scripts.pory"
	msgbox MtPyre_Summit_Text_Grunt3PostBattle
	return


MtPyre_Summit_EventScript_Grunt4::
# 32 "data/maps/MtPyre_Summit/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MT_PYRE_4, MtPyre_Summit_Text_Grunt4Intro, MtPyre_Summit_Text_Grunt4Defeat, Text_NotEnoughMonsForDoubleBattle
# 33 "data/maps/MtPyre_Summit/scripts.pory"
	msgbox MtPyre_Summit_Text_Grunt4PostBattle
	return


MtPyre_Summit_EventScript_OldLady::
	end


MtPyre_Summit_EventScript_OldMan::
	end


MtPyre_Summit_EventScript_TeamAquaTrigger0::
	end


MtPyre_Summit_EventScript_TeamAquaTrigger1::
	end


MtPyre_Summit_EventScript_TeamAquaTrigger2::
	end


MtPyre_Summit_Text_Grunt1Defeat::
# 58 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt1Defeat$"

MtPyre_Summit_Text_Grunt1Intro::
# 62 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt1Intro$"

MtPyre_Summit_Text_Grunt1PostBattle::
# 66 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt1PostBattle$"

MtPyre_Summit_Text_Grunt2Defeat::
# 70 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt2Defeat$"

MtPyre_Summit_Text_Grunt2Intro::
# 74 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt2Intro$"

MtPyre_Summit_Text_Grunt2PostBattle::
# 78 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt2PostBattle$"

MtPyre_Summit_Text_Grunt3Defeat::
# 82 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt3Defeat$"

MtPyre_Summit_Text_Grunt3Intro::
# 86 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt3Intro$"

MtPyre_Summit_Text_Grunt3PostBattle::
# 90 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt3PostBattle$"

MtPyre_Summit_Text_Grunt4Defeat::
# 94 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt4Defeat$"

MtPyre_Summit_Text_Grunt4Intro::
# 98 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt4Intro$"

MtPyre_Summit_Text_Grunt4PostBattle::
# 102 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_Summit_Text_Grunt4PostBattle$"

MtPyre_Summit_Text_SuperAncientPokemonTaughtUs::
# 106 "data/maps/MtPyre_Summit/scripts.pory"
	.string "The embodiments of the land, sea,\n"
	.string "and the sky…\p"
	.string "That is said to be the identities of\n"
	.string "the super-ancient POKéMON…\p"
	.string "In the same way that we humans and\n"
	.string "POKéMON have life, our world, too,\l"
	.string "is alive…\p"
	.string "The super-ancient POKéMON have\n"
	.string "taught us that…$"

MtPyre_Summit_Text_ThoseTwoMenReturnedOrbs::
# 110 "data/maps/MtPyre_Summit/scripts.pory"
	.string "The two men who took the ORBS came\n"
	.string "back to return them on their own.\p"
	.string "Those men…\n"
	.string "Perhaps they are not so evil after all…$"

MtPyre_Summit_Text_GroudonKyogreTale::
# 114 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It happened long, long ago…\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKéMON of the land\l"
	.string "and the POKéMON of the sea…\p"
	.string "The POKéMON of the land raised\n"
	.string "mountains and created continents…\p"
	.string "The POKéMON of the sea raised huge\n"
	.string "waves and carved out oceans…\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive\n"
	.string "infernos and vicious storms.\p"
	.string "The BLUE ORB and the RED ORB brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two ORBS and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, dove deep into\n"
	.string "the sea where eventually they\l"
	.string "disappeared…$"

MtPyre_Summit_Text_WellThatTooIsFine::
# 118 "data/maps/MtPyre_Summit/scripts.pory"
	.string "I see…\n"
	.string "Well, that, too, is fine…$"

MtPyre_Summit_Text_GroudonKyogreAwakened::
# 122 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Oh, my goodness…\p"
	.string "You say that both GROUDON and KYOGRE\n"
	.string "have been awakened?\p"
	.string "It is said that the BLUE ORB and\n"
	.string "the RED ORB quelled the rage of\l"
	.string "the two POKéMON…\p"
	.string "It is also said that the true owner\n"
	.string "of the ORBS still exists.\p"
	.string "However, no one knows who, or what\n"
	.string "exactly, the ORBS belong to.\p"
	.string "It could be a human, or perhaps\n"
	.string "a POKéMON, but no one knows.$"

MtPyre_Summit_Text_HoennTrioTale::
# 126 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It happened long, long ago…\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKéMON of the land\l"
	.string "and the POKéMON of the sea…\p"
	.string "The POKéMON of the land raised\n"
	.string "mountains and created continents…\p"
	.string "The POKéMON of the sea raised huge\n"
	.string "waves and carved out oceans…\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive\n"
	.string "fires and vicious storms.\p"
	.string "It was then that the POKéMON of\n"
	.string "the sky descended from a storm.\p"
	.string "The POKéMON, shining a vivid green,\n"
	.string "becalmed the two enraged POKéMON.\p"
	.string "Then, its duty done, the green POKéMON\n"
	.string "flew off into the wild blue yonder…$"

MtPyre_Summit_Text_HearTheNewLegendOfHoenn::
# 130 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It is my role to pass on the legends\n"
	.string "of HOENN to future generations.\p"
	.string "And the crisis that just ended in\n"
	.string "SOOTOPOLIS rewrote a legend…\p"
	.string "Have you the time to hear the new\n"
	.string "legend of HOENN?$"
