MtPyre_Summit_MapScripts::
# 2 "data/maps/MtPyre_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtPyre_Summit_OnTransition
	.byte 0


MtPyre_Summit_Text_Grunt1Intro::
# 6 "data/maps/MtPyre_Summit/scripts.pory"
	.string "No! Those TEAM MAGMA goons got here\n"
	.string "ahead of us!\p"
	.string "We can't fall behind!$"

MtPyre_Summit_Text_Grunt1Defeat::
# 10 "data/maps/MtPyre_Summit/scripts.pory"
	.string "I thought you were one of the MAGMAS\n"
	.string "who happened to come back$"

MtPyre_Summit_Text_Grunt1PostBattle::
# 14 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Yeah, so you are strong But there're a\n"
	.string "lot of us!$"

MtPyre_Summit_Text_Grunt2Intro::
# 18 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Hah! Too bad for you!\p"
	.string "If you came earlier, you only would've\n"
	.string "had to battle the wimpy TEAM MAGMA.\p"
	.string "But since you arrived now, you have to\n"
	.string "take on us toughies!$"

MtPyre_Summit_Text_Grunt2Defeat::
# 22 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Urgh I should've let you take on TEAM\n"
	.string "MAGMA first$"

MtPyre_Summit_Text_Grunt2PostBattle::
# 26 "data/maps/MtPyre_Summit/scripts.pory"
	.string "You don't know anything! So why are you\n"
	.string "messing with us?$"

MtPyre_Summit_Text_Grunt3Intro::
# 30 "data/maps/MtPyre_Summit/scripts.pory"
	.string "You We saw you at MT. CHIMNEY.\p"
	.string "You don't belong to either TEAM, so why\n"
	.string "would you be here?$"

MtPyre_Summit_Text_Grunt3Defeat::
# 34 "data/maps/MtPyre_Summit/scripts.pory"
	.string "If you're going to mess with anyone, let\n"
	.string "it be TEAM MAGMA$"

MtPyre_Summit_Text_Grunt3PostBattle::
# 38 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Heh, it doesn't matter! We bought\n"
	.string "ourselves some time!\p"
	.string "The BOSS should have snatched what he\n"
	.string "was after!$"

MtPyre_Summit_Text_Grunt4Intro::
# 42 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Oh, I know! You tried to join TEAM MAGMA,\l"
	.string "but they wouldn't have you!\p"
	.string "Well, don't think that we'll let you join\n"
	.string "our TEAM AQUA!$"

MtPyre_Summit_Text_Grunt4Defeat::
# 46 "data/maps/MtPyre_Summit/scripts.pory"
	.string "If you want to join TEAM AQUA that\n"
	.string "badly, we can consider it$"

MtPyre_Summit_Text_Grunt4PostBattle::
# 50 "data/maps/MtPyre_Summit/scripts.pory"
	.string "We have a great combination going with\n"
	.string "us members and our leader.$"

MtPyre_Summit_Text_ArchieWeGotTheOrbLetsGo::
# 54 "data/maps/MtPyre_Summit/scripts.pory"
	.string "ARCHIE: TEAM MAGMA's MAXIE got ahead\n"
	.string "of us, but we also got what we wanted.\p"
	.string "The RED ORB preserved at MT. PYRE I,\n"
	.string "ARCHIE, now have it in my possession!\p"
	.string "Fufufu Now we can bring our ultimate\n"
	.string "objective to fruition!\p"
	.string "Okay, TEAM! We're pulling out!$"

MtPyre_Summit_Text_BothOrbsTakenMagmaLeftThis::
# 58 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Oh, no This cannot happen\p"
	.string "Not only the BLUE ORB, but even the RED\n"
	.string "ORB has been taken\p"
	.string "The BLUE ORB and RED ORB must never be\n"
	.string "separated. They belong together.\p"
	.string "What are those men trying to do with\n"
	.string "the two ORBS?\p"
	.string "\p"
	.string "Oh, yes. Was it TEAM MAGMA who came and\n"
	.string "took the BLUE ORB first?\p"
	.string "Well, in their haste, they left this\n"
	.string "behind.\p"
	.string "I couldn't imagine what exactly it could\n"
	.string "be.\p"
	.string "I would like you to have it. Perhaps it\n"
	.string "will be useful in some way.$"

MtPyre_Summit_Text_OrbsHaveBeenTaken::
# 62 "data/maps/MtPyre_Summit/scripts.pory"
	.string "The BLUE ORB and RED ORB taken by\n"
	.string "those sinister men\p"
	.string "They must never be apart I fear\n"
	.string "something terrible will happen$"

MtPyre_Summit_Text_GroudonKyogreAwakened::
# 66 "data/maps/MtPyre_Summit/scripts.pory"
	.string "Oh, my goodness\p"
	.string "You say that both GROUDON and KYOGRE\n"
	.string "have been awakened?\p"
	.string "It is said that the BLUE ORB and the\n"
	.string "RED ORB quelled the rage of\l"
	.string "the two POKMON\p"
	.string "It is also said that the true owner of\n"
	.string "the ORBS still exists.\p"
	.string "However, no one knows who, or what\n"
	.string "exactly, the ORBS belong to.\p"
	.string "It could be a human, or perhaps a\n"
	.string "POKMON, but no one knows.$"

MtPyre_Summit_Text_ThoseTwoMenReturnedOrbs::
# 70 "data/maps/MtPyre_Summit/scripts.pory"
	.string "The two men who took the ORBS came\n"
	.string "back to return them on their own.\p"
	.string "Those men Perhaps they are not so evil\n"
	.string "after all$"

MtPyre_Summit_Text_SuperAncientPokemonTaughtUs::
# 74 "data/maps/MtPyre_Summit/scripts.pory"
	.string "The embodiments of the land, sea, and\n"
	.string "the sky\p"
	.string "That is said to be the identities of the\n"
	.string "super-ancient POKMON\p"
	.string "In the same way that we humans and\n"
	.string "POKMON have life, our world, too,\l"
	.string "is alive\p"
	.string "The super-ancient POKMON have taught\n"
	.string "us that$"

MtPyre_Summit_Text_WillYouHearOutMyTale::
# 78 "data/maps/MtPyre_Summit/scripts.pory"
	.string "MT. PYRE is where we calm the spirits of\n"
	.string "POKMON that have passed on\p"
	.string "This is a high place where one can see\n"
	.string "all of HOENN\p"
	.string "The disembodied spirits of POKMON must\n"
	.string "find solace here\p"
	.string "Is it coincidence that you are here\p"
	.string "Will you hear out my tale? A tale long\n"
	.string "told in the HOENN region?$"

MtPyre_Summit_Text_GroudonKyogreTale::
# 82 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It happened long, long ago\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKMON of the land\l"
	.string "and the POKMON of the sea\p"
	.string "The POKMON of the land raised\n"
	.string "mountains and created continents\p"
	.string "The POKMON of the sea raised huge\n"
	.string "waves and carved out oceans\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive\n"
	.string "infernos and vicious storms.\p"
	.string "The BLUE ORB and the RED ORB brought\n"
	.string "an end to the calamity.\p"
	.string "Light poured from the two ORBS and\n"
	.string "becalmed the enraged adversaries.\p"
	.string "The pair, made docile, dove deep into\n"
	.string "the sea where eventually they\l"
	.string "disappeared$"

MtPyre_Summit_Text_WellThatTooIsFine::
# 86 "data/maps/MtPyre_Summit/scripts.pory"
	.string "I see Well, that, too, is fine$"

MtPyre_Summit_Text_MaxieSilence::
# 90 "data/maps/MtPyre_Summit/scripts.pory"
	.string "MAXIE: {PLAYER}\p"
	.string "$"

MtPyre_Summit_Text_HearTheNewLegendOfHoenn::
# 94 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It is my role to pass on the legends of\n"
	.string "HOENN to future generations.\p"
	.string "And the crisis that just ended in\n"
	.string "SOOTOPOLIS rewrote a legend\p"
	.string "Have you the time to hear the new\n"
	.string "legend of HOENN?$"

MtPyre_Summit_Text_HoennTrioTale::
# 98 "data/maps/MtPyre_Summit/scripts.pory"
	.string "It happened long, long ago\p"
	.string "The world was wracked by a ferocious\n"
	.string "clash between the POKMON of the land\l"
	.string "and the POKMON of the sea\p"
	.string "The POKMON of the land raised\n"
	.string "mountains and created continents\p"
	.string "The POKMON of the sea raised huge\n"
	.string "waves and carved out oceans\p"
	.string "Their fierce duel raged without end.\p"
	.string "The world was engulfed in massive fires\n"
	.string "and vicious storms.\p"
	.string "It was then that the POKMON of the sky\n"
	.string "descended from a storm.\p"
	.string "The POKMON, shining a vivid green,\n"
	.string "becalmed the two enraged POKMON.\p"
	.string "Then, its duty done, the green POKMON\n"
	.string "flew off into the wild blue yonder$"
