MtChimney_CableCarStation_MapScripts::
	.byte 0


MtChimney_CableCarStation_EventScript_Attendant::
# 5 "data/maps/MtChimney_CableCarStation/scripts.pory"
	msgbox MtChimney_CableCarStation_Text_CableCarReadyGetOn, MSGBOX_YESNO
	end


MtChimney_CableCarStation_Text_StepThisWay::
# 9 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "Please step this way.$"

MtChimney_CableCarStation_Text_CableCarReadyGetOn::
# 13 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "The CABLE CAR is ready to go down.\n"
	.string "Would you like to be on it?$"

MtChimney_CableCarStation_Text_RideAnotherTime::
# 17 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "Please ride with us another time.$"
