MtChimney_CableCarStation_MapScripts::
# 2 "data/maps/MtChimney_CableCarStation/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtChimney_CableCarStation_OnTransition
# 3 "data/maps/MtChimney_CableCarStation/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, MtChimney_CableCarStation_OnFrame
	.byte 0


MtChimney_CableCarStation_MapScripts::
# 7 "data/maps/MtChimney_CableCarStation/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtChimney_CableCarStation_OnTransition
# 8 "data/maps/MtChimney_CableCarStation/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, MtChimney_CableCarStation_OnFrame
	return


MtChimney_CableCarStation_Text_CableCarReadyGetOn::
# 12 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "The CABLE CAR is ready to go down. Would\n"
	.string "you like to be on it?$"

MtChimney_CableCarStation_Text_StepThisWay::
# 16 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "Please step this way.$"

MtChimney_CableCarStation_Text_RideAnotherTime::
# 20 "data/maps/MtChimney_CableCarStation/scripts.pory"
	.string "Please ride with us another time.$"
