SeafloorCavern_Entrance_MapScripts::
# 2 "data/maps/SeafloorCavern_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SeafloorCavern_Entrance_OnResume
	.byte 0


SeafloorCavern_Entrance_Text_HearMagmaNearMossdeep::
# 6 "data/maps/SeafloorCavern_Entrance/scripts.pory"
	.string "Hey! I remember your face!\p"
	.string "If you're here, it must mean that you're\n"
	.string "about to mess with us again!\p"
	.string "A punk like you, do you really think you\n"
	.string "can take on TEAM AQUA?\p"
	.string "I'd say you're too early by about a\n"
	.string "trillion years!\p"
	.string "You're a perfect fit for the likes of\n"
	.string "TEAM MAGMA!\p"
	.string "Speaking of TEAM MAGMA, I hear they\n"
	.string "were spotted near MOSSDEEP.\p"
	.string "That bunch of goons, they sure don't\n"
	.string "look good near the sea!$"

SeafloorCavern_Entrance_Text_HearMagmaNearMossdeepShort::
# 10 "data/maps/SeafloorCavern_Entrance/scripts.pory"
	.string "A punk like you, do you really think you\n"
	.string "can take on TEAM AQUA?\p"
	.string "I'd say you're too early by about a\n"
	.string "trillion years!\p"
	.string "You're a perfect fit for the likes of\n"
	.string "TEAM MAGMA!\p"
	.string "Speaking of TEAM MAGMA, I hear they\n"
	.string "were spotted near MOSSDEEP.\p"
	.string "That bunch of goons, they sure don't\n"
	.string "look good near the sea!$"
