EverGrandeCity_ChampionsRoom_MapScripts::
# 2 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_ChampionsRoom_OnTransition
# 3 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, EverGrandeCity_ChampionsRoom_OnWarp
# 4 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, EverGrandeCity_ChampionsRoom_OnFrame
	.byte 0


EverGrandeCity_ChampionsRoom_MapScripts::
# 8 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, EverGrandeCity_ChampionsRoom_OnTransition
# 9 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, EverGrandeCity_ChampionsRoom_OnWarp
# 10 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, EverGrandeCity_ChampionsRoom_OnFrame
	return


EverGrandeCity_ChampionsRoom_Text_IntroSpeech::
# 14 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "WALLACE: Welcome, {PLAYER}{KUN}.\p"
	.string "That incident in SOOTOPOLIS CITY… That\n"
	.string "was superb work, putting an end\l"
	.string "to that crisis all by yourself.\p"
	.string "Oops!\p"
	.string "It wouldn't be fair to say that you\n"
	.string "alone ended the crisis.\p"
	.string "You overcame that difficult situation\n"
	.string "by working as one with your POKéMON.\p"
	.string "We TRAINERS raise POKéMON by giving\n"
	.string "them items and by teaching them new\l"
	.string "techniques for battle.\p"
	.string "But we ourselves also learn many things\n"
	.string "from POKéMON.\p"
	.string "And this is where your achievements are\n"
	.string "put to the test against what\l"
	.string "others like you have achieved.\p"
	.string "Now!\p"
	.string "Who can most elegantly dance with their\n"
	.string "POKéMON in HOENN?\p"
	.string "Show me right here and now!$"

EverGrandeCity_ChampionsRoom_Text_Defeat::
# 18 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "I, the CHAMPION, fall in defeat…\p"
	.string "That was wonderful work. You were\n"
	.string "elegant, infuriatingly so.\l"
	.string "And yet it was utterly glorious!\p"
	.string "Kudos to you, {PLAYER}{KUN}!\p"
	.string "You are a truly noble POKéMON TRAINER!$"

EverGrandeCity_ChampionsRoom_Text_PostBattleSpeech::
# 22 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "WALLACE: The POKéMON you sent into\n"
	.string "battle…\p"
	.string "At times they danced like a spring\n"
	.string "breeze, and at times they struck\l"
	.string "like lightning.\p"
	.string "It was with light, yet surefooted,\n"
	.string "elegance that you led your POKéMON.\p"
	.string "Even I felt bedazzled by your masterful\n"
	.string "performance!\p"
	.string "You now stand at the glorious peak of\n"
	.string "the POKéMON LEAGUE.\p"
	.string "I now proclaim you to be the new HOENN\n"
	.string "region…$"

EverGrandeCity_ChampionsRoom_Text_MayAdvice::
# 26 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "MAY: {PLAYER}{KUN}!\p"
	.string "Here's some advice before you challenge\n"
	.string "the CHAMPION…$"

EverGrandeCity_ChampionsRoom_Text_MayItsAlreadyOver::
# 30 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "MAY: Huh? What, what, what?\p"
	.string "{PLAYER}{KUN}… Could it be that…\l"
	.string "It's already over?$"

EverGrandeCity_ChampionsRoom_Text_BrendanAdvice::
# 34 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "BRENDAN: {PLAYER}!\p"
	.string "How would you like some advice before\n"
	.string "you challenge the CHAMPION?…$"

EverGrandeCity_ChampionsRoom_Text_BrendanYouveWon::
# 38 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "BRENDAN: {PLAYER}…\p"
	.string "Are you trying to tell me… You've beaten\n"
	.string "the CHAMPION?$"

EverGrandeCity_ChampionsRoom_Text_BirchArriveRatePokedex::
# 42 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "PROF. BIRCH: See? What did I tell you,\n"
	.string "{RIVAL}?\p"
	.string "Didn't I tell you that you don't need to\n"
	.string "worry about {PLAYER}{KUN}?\p"
	.string "… … … … … … … … {PLAYER}{KUN}, you've finally\n"
	.string "done it.\p"
	.string "When I heard that you defeated your\n"
	.string "own father at the PETALBURG GYM,\l"
	.string "I thought perhaps you had a chance…\p"
	.string "But to think you've actually become the\n"
	.string "CHAMPION!\p"
	.string "Ah, yes!\p"
	.string "What became of your POKéDEX? Here, let\n"
	.string "me see.$"

EverGrandeCity_ChampionsRoom_Text_BirchCongratulations::
# 46 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "PROF. BIRCH: Anyways, congratulations!\p"
	.string "Now, go proudly into the final room!$"

EverGrandeCity_ChampionsRoom_Text_WallaceComeWithMe::
# 50 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "WALLACE: {PLAYER}{KUN}…\p"
	.string "No, let me rephrase that properly.\p"
	.string "The new CHAMPION!\p"
	.string "Come with me.$"

EverGrandeCity_ChampionsRoom_Text_WallaceWaitOutside::
# 54 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "WALLACE: I'm sorry, but…\p"
	.string "From here on, only those TRAINERS who\n"
	.string "have become CHAMPIONS may enter.\p"
	.string "You'll have to wait outside with PROF.\n"
	.string "BIRCH.$"

EverGrandeCity_ChampionsRoom_Text_MayCongratulations::
# 58 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "MAY: Groan…\p"
	.string "… … … … … … … … … … … … … … … …\p"
	.string "I'm just joking! That's okay! That's the\n"
	.string "rule!\p"
	.string "{PLAYER}{KUN}! Honestly, congratulations!$"

EverGrandeCity_ChampionsRoom_Text_BrendanCongratulations::
# 62 "data/maps/EverGrandeCity_ChampionsRoom/scripts.pory"
	.string "BRENDAN: Whaaaat?! … … … … … … … … … … …\n"
	.string "… …\p"
	.string "It can't be helped if that's the rule.\p"
	.string "{PLAYER}, way to go! Congratulations!$"
