SSAnne_Deck_MapScripts::
	.byte 0


SSAnne_Deck_Text_ShipDepartingSoon::
# 5 "data/maps/SSAnne_Deck/scripts.pory"
	.string "The party's over. The ship will be\n"
	.string "departing soon.$"

SSAnne_Deck_Text_ScrubbingDecksHardWork::
# 9 "data/maps/SSAnne_Deck/scripts.pory"
	.string "Whew! Scrubbing decks is hard work!$"

SSAnne_Deck_Text_FeelSeasick::
# 13 "data/maps/SSAnne_Deck/scripts.pory"
	.string "Urf… I feel ill…\p"
	.string "I got seasick, so I stepped out to get\n"
	.string "some air…$"

SSAnne_Deck_Text_EdmondIntro::
# 17 "data/maps/SSAnne_Deck/scripts.pory"
	.string "Hey, matey!\p"
	.string "Let's do a little jig!$"

SSAnne_Deck_Text_EdmondDefeat::
# 21 "data/maps/SSAnne_Deck/scripts.pory"
	.string "You're impressive!$"

SSAnne_Deck_Text_EdmondPostBattle::
# 25 "data/maps/SSAnne_Deck/scripts.pory"
	.string "How many kinds of POKéMON do you think\n"
	.string "there are in this big world?$"

SSAnne_Deck_Text_TrevorIntro::
# 29 "data/maps/SSAnne_Deck/scripts.pory"
	.string "Ahoy, there! Are you seasick?$"

SSAnne_Deck_Text_TrevorDefeat::
# 33 "data/maps/SSAnne_Deck/scripts.pory"
	.string "I was just careless!$"

SSAnne_Deck_Text_TrevorPostBattle::
# 37 "data/maps/SSAnne_Deck/scripts.pory"
	.string "My pa said there are 100 kinds of\n"
	.string "POKéMON. I think there are more.$"
