Route110_SeasideCyclingRoadSouthEntrance_MapScripts::
	.byte 0


Route110_SeasideCyclingRoadSouthEntrance_MapScripts::
	return


Route110_SeasideCyclingRoadSouthEntrance_Text_GoAllOutOnCyclingRoad::
# 8 "data/maps/Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	.string "On CYCLING ROAD, you can go all out and\n"
	.string "cycle as fast as you'd like.\p"
	.string "It feels great to go that fast, but try\n"
	.string "not to crash into anyone!$"

Route110_SeasideCyclingRoadSouthEntrance_Text_TooDangerousToWalk::
# 12 "data/maps/Route110_SeasideCyclingRoadSouthEntrance/scripts.pory"
	.string "Sorry, you can't walk on CYCLING ROAD.\n"
	.string "It's too dangerous.\p"
	.string "Please come back with a BIKE.$"
