FourIsland_IcefallCave_Back_MapScripts::
# 2 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_IcefallCave_Back_OnTransition
	.byte 0


FourIsland_IcefallCave_Back_Text_LoreleiKeepHandsOffMons::
# 6 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "LORELEI: Keep your filthy hands off\n"
	.string "the POKMON in the cave!\p"
	.string "Do as I say, or you'll have me to answer\n"
	.string "to!$"

FourIsland_IcefallCave_Back_Text_ShutItLadyLeaveUsBe::
# 10 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "Aww, shut it, lady, and leave us be.\p"
	.string "Don't let your glasses get all steamed\n"
	.string "up!$"

FourIsland_IcefallCave_Back_Text_LoreleiPlayerHelpMeKickPoachersOut::
# 14 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "LORELEI: {PLAYER}?! What are you\n"
	.string "doing here?\p"
	.string "No, we can catch up later. Right now, I\n"
	.string "need your help.\p"
	.string "Help me kick these poachers out before\n"
	.string "they do anything else.\p"
	.string "They've been catching POKMON here,\n"
	.string "then selling them off!\p"
	.string "Are you ready? You take that one,\n"
	.string "please!$"

FourIsland_IcefallCave_Back_Text_GruntIntro::
# 18 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "W-what?!\p"
	.string "Who says we can't do what we want with\n"
	.string "the POKMON we catch?$"

FourIsland_IcefallCave_Back_Text_GruntDefeat::
# 22 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "We didn't plan on this!$"

FourIsland_IcefallCave_Back_Text_LoreleiWhereHaveYouTakenMons::
# 26 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "LORELEI: Humph. So despicably weak.\p"
	.string "You! Tell me!\p"
	.string "Where have you taken the captured\n"
	.string "POKMON?\p"
	.string "I'm smashing your ring once and for all!$"

FourIsland_IcefallCave_Back_Text_NotTellingYouThat::
# 30 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "N-no way! I'm not telling you that!$"

FourIsland_IcefallCave_Back_Text_LoreleiWellDeepFreezeYou::
# 34 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "LORELEI: If you won't confess, we'll\n"
	.string "deep-freeze you.\p"
	.string "My LAPRAS is furious for what you've\n"
	.string "done to its friends.\p"
	.string "Go, LAPRAS! ICE BEAM$"

FourIsland_IcefallCave_Back_Text_OkayRocketWareHouseFiveIsland::
# 38 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "Wawaah! Okay! I'll talk!\p"
	.string "The POKMON are in the ROCKET WAREHOUSE\n"
	.string "on FIVE ISLAND.\p"
	.string "There! I said it! We'll be going now!\p"
	.string "But I doubt you'll ever make it into the\n"
	.string "ROCKET WAREHOUSE!\p"
	.string "Heheheheh!$"

FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
# 42 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "{PLAYER}, thank you. But this is awful\p"
	.string "I was born and raised here on these\n"
	.string "islands.\p"
	.string "I had no idea that those horrible\n"
	.string "criminals were loose here$"
