FourIsland_IcefallCave_Back_MapScripts::
	.byte 0


FourIsland_IcefallCave_Back_EventScript_Lorelei::
# 5 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	msgbox FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful, MSGBOX_NPC
	end


FourIsland_IcefallCave_Back_EventScript_LoreleiRocketsScene::
	end


FourIsland_IcefallCave_Back_Text_ThankYouThisIsAwful::
# 14 "data/maps/FourIsland_IcefallCave_Back/scripts.pory"
	.string "{PLAYER}, thank you.\n"
	.string "But this is awful…\p"
	.string "I was born and raised here on\n"
	.string "these islands.\p"
	.string "I had no idea that those horrible\n"
	.string "criminals were loose here…$"
