CeruleanCity_House2_MapScripts::
	.byte 0


CeruleanCity_House2_EventScript_Hiker::
	end


CeruleanCity_House2_EventScript_Lass::
# 9 "data/maps/CeruleanCity_House2/scripts.pory"
	msgbox CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood, MSGBOX_NPC
	end


CeruleanCity_House2_EventScript_WallHole::
# 14 "data/maps/CeruleanCity_House2/scripts.pory"
	msgbox CeruleanCity_House2_Text_TeamRocketLeftWayOut, MSGBOX_SIGN
	end


CeruleanCity_House2_Text_TeamRocketLeftWayOut::
# 19 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "TEAM ROCKET left a way out!$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
# 23 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "TEAM ROCKET must be trying to DIG\n"
	.string "their way into no good!$"
