CeruleanCity_House2_MapScripts::
	.byte 0


CeruleanCity_House2_Text_RocketsStoleTMForDig::
# 5 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "Those miserable ROCKETS!\p"
	.string "Look what they've done to my house!\p"
	.string "They stole a TM for teaching POKéMON\n"
	.string "how to DIG holes!\p"
	.string "I was going to use it on a MANKEY or a\n"
	.string "SANDSHREW…\p"
	.string "That cost me a bundle, it did!$"

CeruleanCity_House2_Text_TeachDiglettDigWithoutTM::
# 9 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "I figure what's lost is lost.\p"
	.string "I decided to teach DIGLETT how to DIG\n"
	.string "without a TM.$"

CeruleanCity_House2_Text_TeamRocketTryingToDigIntoNoGood::
# 13 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "TEAM ROCKET must be trying to DIG their\n"
	.string "way into no good!$"

CeruleanCity_House2_Text_TeamRocketLeftWayOut::
# 17 "data/maps/CeruleanCity_House2/scripts.pory"
	.string "TEAM ROCKET left a way out!$"
