SilphCo_1F_MapScripts::
# 2 "data/maps/SilphCo_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SilphCo_1F_OnTransition
	.byte 0


SilphCo_1F_Text_WelcomePresidentInBoardroom::
# 6 "data/maps/SilphCo_1F/scripts.pory"
	.string "Welcome.\p"
	.string "The PRESIDENT is in the boardroom on\n"
	.string "11F.$"

SilphCo_1F_Text_DestroyedWontBeFixedForWhile::
# 10 "data/maps/SilphCo_1F/scripts.pory"
	.string "$"

SilphCo_1F_Text_FloorSign::
# 14 "data/maps/SilphCo_1F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 1F$"
