EverGrandeCity_PokemonLeague_1F_MapScripts::
	.byte 0


EverGrandeCity_PokemonLeague_1F_EventScript_Clerk::
	end


EverGrandeCity_PokemonLeague_1F_EventScript_DoorGuard::
	end


EverGrandeCity_PokemonLeague_1F_EventScript_Nurse::
	end


EverGrandeCity_PokemonLeague_1F_Text_GoForth::
# 16 "data/maps/EverGrandeCity_PokemonLeague_1F/scripts.pory"
	.string "TRAINER! Believe in yourself and your\n"
	.string "POKéMON, and go forth!$"

EverGrandeCity_PokemonLeague_1F_Text_HaventObtainedAllBadges::
# 20 "data/maps/EverGrandeCity_PokemonLeague_1F/scripts.pory"
	.string "You haven't obtained all the BADGES.\p"
	.string "If you're bound for the POKéMON\n"
	.string "LEAGUE, you must return with them.$"
