MtPyre_5F_MapScripts::
	.byte 0


MtPyre_5F_EventScript_Atsushi::
	end


MtPyre_4F_Text_TashaDefeat::
# 10 "data/maps/MtPyre_5F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_4F_Text_TashaDefeat$"

MtPyre_4F_Text_TashaIntro::
# 14 "data/maps/MtPyre_5F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_4F_Text_TashaIntro$"

MtPyre_4F_Text_TashaPostBattle::
# 18 "data/maps/MtPyre_5F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_4F_Text_TashaPostBattle$"
