MtPyre_5F_MapScripts::
	.byte 0


MtPyre_4F_Text_TashaIntro::
# 5 "data/maps/MtPyre_5F/scripts.pory"
	.string "I love all things horrifying… It's like a\n"
	.string "disease…\p"
	.string "When I'm here… I shiver with fear…$"

MtPyre_4F_Text_TashaDefeat::
# 9 "data/maps/MtPyre_5F/scripts.pory"
	.string "Losing, I dislike…$"

MtPyre_4F_Text_TashaPostBattle::
# 13 "data/maps/MtPyre_5F/scripts.pory"
	.string "I want to see dreadful things… I can't\n"
	.string "leave…\p"
	.string "Stay… Won't you stay with me?$"
