SlateportCity_SternsShipyard_1F_MapScripts::
	.byte 0


SlateportCity_SternsShipyard_1F_Text_CantMakeHeadsOrTails::
# 5 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "Umm If this goes here, and that goes\n"
	.string "over there\p"
	.string "Then where does this thing go? And what\n"
	.string "about that doohickey?\p"
	.string "Aaargh! I can't make heads or tails of\n"
	.string "this!$"

SlateportCity_SternsShipyard_1F_Text_MeetDockDeliverToStern::
# 9 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "Hm? Hi, I'm DOCK.\p"
	.string "CAPT. STERN commissioned me to design a\n"
	.string "ferry.\p"
	.string "Oh! That there Are they DEVON GOODS?\p"
	.string "But, hmm This won't do\p"
	.string "CAPT. STERN went off somewhere. He said\n"
	.string "he had some work to do.\p"
	.string "Could I get you to go find CAPT. STERN\n"
	.string "and deliver that to him?$"

SlateportCity_SternsShipyard_1F_Text_CouldYouFindStern::
# 13 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "DOCK: Where could CAPT. STERN have\n"
	.string "gone off to?\p"
	.string "Could you go find CAPT. STERN and\n"
	.string "deliver that parcel to him?$"

SlateportCity_SternsShipyard_1F_Text_CouldUseAdviceFromVeteran::
# 17 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "DOCK: Shipbuilding is an art.\p"
	.string "A lot of things can't be figured out\n"
	.string "just by calculating.\p"
	.string "I really could use advice from a veteran\n"
	.string "who knows the seas$"

SlateportCity_SternsShipyard_1F_Text_BrineyJoinedUs::
# 21 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "DOCK: Hi! MR. BRINEY's joined us to lend\n"
	.string "us his help.\p"
	.string "Thanks to the veteran sailor, the ferry\n"
	.string "is steadily coming together.$"

SlateportCity_SternsShipyard_1F_Text_FerryIsReady::
# 25 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "DOCK: The ferry is finally ready!\p"
	.string "The new S.S. TIDAL is truly a marvel of\n"
	.string "technology!\p"
	.string "But, I get the feeling that we can make\n"
	.string "something even better.\p"
	.string "You know, there's never an end to\n"
	.string "technology's march.$"

SlateportCity_SternsShipyard_1F_Text_DecidedToHelpDock::
# 29 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "MR. BRINEY: Ah, {PLAYER}{KUN}! It's been\n"
	.string "too long!\p"
	.string "Aye, since I met you, this old sea dog's\n"
	.string "been feeling frisky!\p"
	.string "So I've decided to help DOCK make a\n"
	.string "ferry.\p"
	.string "Aye, after all, a ferry would be able to\n"
	.string "carry a lot of people.\p"
	.string "But, you know, that DOCK is really\n"
	.string "something special.\p"
	.string "With his knack for technology and my\n"
	.string "experience, I'm sure that we can\l"
	.string "build one great ship, aye!$"

SlateportCity_SternsShipyard_1F_Text_SeaIsLikeLivingThing::
# 33 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "The seasons, the weather, where the\n"
	.string "moon sits in the sky\p"
	.string "These and other conditions make the\n"
	.string "sea change its expression.\p"
	.string "That's right! The sea is like a living\n"
	.string "thing!$"

SlateportCity_SternsShipyard_1F_Text_GetSeasickEasily::
# 37 "data/maps/SlateportCity_SternsShipyard_1F/scripts.pory"
	.string "I get seasick real easily. So I get to\n"
	.string "help out here instead.$"
