AbandonedShip_Rooms2_1F_MapScripts::
	.byte 0


AbandonedShip_Rooms2_1F_Text_DanIntro::
# 5 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: While searching for treasures, we\n"
	.string "discovered a TRAINER!$"

AbandonedShip_Rooms2_1F_Text_DanDefeat::
# 9 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: We couldn't win even though we\n"
	.string "worked together…$"

AbandonedShip_Rooms2_1F_Text_DanPostBattle::
# 13 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: We can't find any treasures… I\n"
	.string "wonder if someone got them already?$"

AbandonedShip_Rooms2_1F_Text_DanNotEnoughMons::
# 17 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraIntro::
# 21 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh? We were searching for\n"
	.string "treasures.\l"
	.string "But we discovered a TRAINER instead!$"

AbandonedShip_Rooms2_1F_Text_KiraDefeat::
# 25 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Ooh, so strong!$"

AbandonedShip_Rooms2_1F_Text_KiraPostBattle::
# 29 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Where could the treasures be?\p"
	.string "I've already decided what I'm buying\n"
	.string "when we find the treasures!$"

AbandonedShip_Rooms2_1F_Text_KiraNotEnoughMons::
# 33 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_KiraRegister::
# 37 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh, you make me so angry! I'm\n"
	.string "going to register you for that!$"

AbandonedShip_Rooms2_1F_Text_DanRematchIntro::
# 41 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: We've been searching for\n"
	.string "treasures all this time.\p"
	.string "Our POKéMON have grown stronger, too.\n"
	.string "Let us show you, okay?$"

AbandonedShip_Rooms2_1F_Text_DanRematchDefeat::
# 45 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: You're strong, as usual!$"

AbandonedShip_Rooms2_1F_Text_DanPostRematch::
# 49 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: We can't find any treasures, we\n"
	.string "lose at POKéMON…\p"
	.string "I want to go home… But if I say that,\n"
	.string "she gets all angry with me…$"

AbandonedShip_Rooms2_1F_Text_DanRematchNotEnoughMons::
# 53 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "DAN: You don't even have two POKéMON.\n"
	.string "You can't expect to beat us like that.$"

AbandonedShip_Rooms2_1F_Text_KiraRematchIntro::
# 57 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh? We meet again!\p"
	.string "Just like us, you still haven't given up\n"
	.string "searching for treasures, have you?\p"
	.string "Want to make it so the loser has to give\n"
	.string "up searching?$"

AbandonedShip_Rooms2_1F_Text_KiraRematchDefeat::
# 61 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh, we lost again…$"

AbandonedShip_Rooms2_1F_Text_KiraPostRematch::
# 65 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: We're not leaving until we raise\n"
	.string "our POKéMON some more and we find\l"
	.string "the treasures here!$"

AbandonedShip_Rooms2_1F_Text_KiraRematchNotEnoughMons::
# 69 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "KIRA: Oh, you don't have two POKéMON?\n"
	.string "We'll have to battle some other time!$"

AbandonedShip_Rooms2_1F_Text_JaniIntro::
# 73 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "I'm not good at swimming, but I am good\n"
	.string "at battles!$"

AbandonedShip_Rooms2_1F_Text_JaniDefeat::
# 77 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "Oops. That didn't go very well.$"

AbandonedShip_Rooms2_1F_Text_JaniPostBattle::
# 81 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "Walking around barefoot in this ship is\n"
	.string "kind of gross.$"

AbandonedShip_Rooms2_1F_Text_GarrisonIntro::
# 85 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "Strength and compassion… Those are a\n"
	.string "TRAINER's treasures!$"

AbandonedShip_Rooms2_1F_Text_GarrisonDefeat::
# 89 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "Ah, there is something about you that\n"
	.string "sparkles.$"

AbandonedShip_Rooms2_1F_Text_GarrisonPostBattle::
# 93 "data/maps/AbandonedShip_Rooms2_1F/scripts.pory"
	.string "In a cabin somewhere on board, I saw\n"
	.string "something sparkle.$"
