LavenderTown_House1_MapScripts::
	.byte 0


LavenderTown_House1_Text_Cubone::
# 5 "data/maps/LavenderTown_House1/scripts.pory"
	.string "CUBONE: Kyarugoo!$"

LavenderTown_House1_Text_RocketsKilledCubonesMother::
# 9 "data/maps/LavenderTown_House1/scripts.pory"
	.string "Those horrible ROCKETS! They deserve\n"
	.string "no mercy!\p"
	.string "That poor CUBONE's mother…\p"
	.string "It was killed trying to escape from\n"
	.string "TEAM ROCKET.$"

LavenderTown_House1_Text_GhostOfPokemonTowerIsGone::
# 13 "data/maps/LavenderTown_House1/scripts.pory"
	.string "The ghost of POKéMON TOWER is gone!\p"
	.string "Someone must have soothed its restless\n"
	.string "spirit!$"
