PetalburgCity_House2_MapScripts::
	.byte 0


PetalburgCity_House2_MapScripts::
	return


PetalburgCity_House2_Text_NormanBecameGymLeader::
# 8 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "NORMAN became our town's new GYM\n"
	.string "LEADER.\p"
	.string "I think he called his family over from\n"
	.string "somewhere far away.$"

PetalburgCity_House2_Text_BattledNormanOnce::
# 12 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I battled NORMAN once, but, whew, he was\n"
	.string "way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he lives for\n"
	.string "POKéMON.$"
