PetalburgCity_House2_MapScripts::
	.byte 0


PetalburgCity_House2_EventScript_SchoolKid::
# 5 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_BattledNormanOnce, MSGBOX_NPC
	end


PetalburgCity_House2_EventScript_Woman::
# 10 "data/maps/PetalburgCity_House2/scripts.pory"
	msgbox PetalburgCity_House2_Text_NormanBecameGymLeader, MSGBOX_NPC
	end


PetalburgCity_House2_Text_BattledNormanOnce::
# 14 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "I battled NORMAN once, but, whew,\n"
	.string "he was way too strong.\p"
	.string "How would I put it?\p"
	.string "I just got the feeling that he\n"
	.string "lives for POKéMON.$"

PetalburgCity_House2_Text_NormanBecameGymLeader::
# 18 "data/maps/PetalburgCity_House2/scripts.pory"
	.string "NORMAN became our town's new\n"
	.string "GYM LEADER.\p"
	.string "I think he called his family over from\n"
	.string "somewhere far away.$"
