SaffronCity_House_MapScripts::
	.byte 0


SaffronCity_House_Text_DontLookAtMyLetter::
# 5 "data/maps/SaffronCity_House/scripts.pory"
	.string "…Thank you for writing. I hope to see\n"
	.string "you soon!\p"
	.string "…Hey! Don't look at my letter!$"

SaffronCity_House_Text_Pidgey::
# 9 "data/maps/SaffronCity_House/scripts.pory"
	.string "PIDGEY: Kurukkoo!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
# 13 "data/maps/SaffronCity_House/scripts.pory"
	.string "The COPYCAT is cute! I'm getting her a\n"
	.string "POKé DOLL.$"

SaffronCity_House_Text_ExplainPPUp::
# 17 "data/maps/SaffronCity_House/scripts.pory"
	.string "I was given a PP UP as a gift.\p"
	.string "It's used to increase the PP of a\n"
	.string "POKéMON's move.\p"
	.string "I should use it on a powerful move with\n"
	.string "only a few PP.$"
