SaffronCity_House_MapScripts::
	.byte 0


SaffronCity_House_EventScript_Lass::
# 5 "data/maps/SaffronCity_House/scripts.pory"
	msgbox SaffronCity_House_Text_DontLookAtMyLetter, MSGBOX_NPC
	end


SaffronCity_House_EventScript_Letter::
# 10 "data/maps/SaffronCity_House/scripts.pory"
	msgbox SaffronCity_House_Text_ExplainPPUp, MSGBOX_SIGN
	end


SaffronCity_House_EventScript_Pidgey::
	end


SaffronCity_House_EventScript_Youngster::
# 19 "data/maps/SaffronCity_House/scripts.pory"
	msgbox SaffronCity_House_Text_GettingCopycatPokeDoll, MSGBOX_NPC
	end


SaffronCity_House_Text_ExplainPPUp::
# 24 "data/maps/SaffronCity_House/scripts.pory"
	.string "I was given a PP UP as a gift.\p"
	.string "It's used to increase the PP of a\n"
	.string "POKéMON's move.\p"
	.string "I should use it on a powerful move with\n"
	.string "only a few PP.$"

SaffronCity_House_Text_DontLookAtMyLetter::
# 28 "data/maps/SaffronCity_House/scripts.pory"
	.string "…Thank you for writing.\n"
	.string "I hope to see you soon!\p"
	.string "…Hey!\n"
	.string "Don't look at my letter!$"

SaffronCity_House_Text_GettingCopycatPokeDoll::
# 32 "data/maps/SaffronCity_House/scripts.pory"
	.string "The COPYCAT is cute!\n"
	.string "I'm getting her a POKé DOLL.$"
