SevenIsland_SevaultCanyon_TanobyKey_MapScripts::
	.byte 0


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch1::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch2::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch3::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch4::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch5::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch6::
	end


SevenIsland_SevaultCanyon_TanobyKey_EventScript_Switch7::
	end

