SevenIsland_SevaultCanyon_TanobyKey_MapScripts::
# 2 "data/maps/SevenIsland_SevaultCanyon_TanobyKey/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_SevaultCanyon_TanobyKey_OnTransition
	.byte 0


SevenIsland_SevaultCanyon_TanobyKey_Text_MysteriousRumbleFarAway::
# 6 "data/maps/SevenIsland_SevaultCanyon_TanobyKey/scripts.pory"
	.string "A mysterious rumble echoed somewhere\n"
	.string "far away.$"
