CinnabarIsland_Mart_MapScripts::
	.byte 0


CinnabarIsland_Mart_Text_DontTheyHaveXAttack::
# 5 "data/maps/CinnabarIsland_Mart/scripts.pory"
	.string "Don't they have X ATTACK?\p"
	.string "I like it because it raises the ATTACK\n"
	.string "stat in battle.$"

CinnabarIsland_Mart_Text_ExtraItemsNeverHurt::
# 9 "data/maps/CinnabarIsland_Mart/scripts.pory"
	.string "It never hurts to have extra items. You\n"
	.string "never know what might happen.$"
