SSAnne_2F_Room2_MapScripts::
	.byte 0


SSAnne_2F_Room2_Text_BrooksIntro::
# 5 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "Competing against the young keeps me\n"
	.string "youthful.$"

SSAnne_2F_Room2_Text_BrooksDefeat::
# 9 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "Good match! Ah, I feel young again!$"

SSAnne_2F_Room2_Text_BrooksPostBattle::
# 13 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "Fifteen years ago, I would have won!$"

SSAnne_2F_Room2_Text_DaleIntro::
# 17 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "Check out what I fished up!$"

SSAnne_2F_Room2_Text_DaleDefeat::
# 21 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "I'm all out!$"

SSAnne_2F_Room2_Text_DalePostBattle::
# 25 "data/maps/SSAnne_2F_Room2/scripts.pory"
	.string "Party?\p"
	.string "The cruise ship's party should be over\n"
	.string "by now.$"
