MtPyre_2F_MapScripts::
# 2 "data/maps/MtPyre_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CaveHole_CheckFallDownHole
# 3 "data/maps/MtPyre_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CaveHole_FixCrackedGround
# 4 "data/maps/MtPyre_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MtPyre_2F_SetHoleWarp
	.byte 0


MtPyre_2F_Text_MemoriesOfSkitty::
# 8 "data/maps/MtPyre_2F/scripts.pory"
	.string "Memories of my darling SKITTY… My eyes\n"
	.string "overflow thinking about it.$"

MtPyre_2F_Text_TumbledFromFloorAbove::
# 12 "data/maps/MtPyre_2F/scripts.pory"
	.string "Ooch, ouch… There are holes in the\n"
	.string "ground here and there.\p"
	.string "I didn't notice and took a tumble from\n"
	.string "the floor above.$"

MtPyre_2F_Text_MarkIntro::
# 16 "data/maps/MtPyre_2F/scripts.pory"
	.string "Hey! Are you searching for POKéMON?\n"
	.string "You came along after me! You're rude!$"

MtPyre_2F_Text_MarkDefeat::
# 20 "data/maps/MtPyre_2F/scripts.pory"
	.string "Ayieeeeh! I'm sorry, forgive me, please!$"

MtPyre_2F_Text_MarkPostBattle::
# 24 "data/maps/MtPyre_2F/scripts.pory"
	.string "People don't come here often, so I\n"
	.string "thought there'd be rare POKéMON.$"

MtPyre_2F_Text_LukeIntro::
# 28 "data/maps/MtPyre_2F/scripts.pory"
	.string "LUKE: We're here on a dare.\p"
	.string "Heheh, if I show her how cool I am, she'll\n"
	.string "fall for me. I know it!\p"
	.string "I know! I'll cream you and show her how\n"
	.string "cool I am!$"

MtPyre_2F_Text_LukeDefeat::
# 32 "data/maps/MtPyre_2F/scripts.pory"
	.string "LUKE: Whoopsie!$"

MtPyre_2F_Text_LukePostBattle::
# 36 "data/maps/MtPyre_2F/scripts.pory"
	.string "LUKE: Well, we lost but that's okay! I'm\n"
	.string "right here by your side.\l"
	.string "We'll make it through this dare!$"

MtPyre_2F_Text_LukeNotEnoughMons::
# 40 "data/maps/MtPyre_2F/scripts.pory"
	.string "LUKE: If you want to take me on, bring\n"
	.string "some more POKéMON.\p"
	.string "If you don't, I won't be able to show off\n"
	.string "to my girl how cool I am!$"

MtPyre_2F_Text_DezIntro::
# 44 "data/maps/MtPyre_2F/scripts.pory"
	.string "DEZ: I came here on a dare with my\n"
	.string "boyfriend.\p"
	.string "It's really scary, but I'm with my\n"
	.string "boyfriend. It's okay.\p"
	.string "I know! I'll get my boyfriend to look\n"
	.string "cool by beating you!$"

MtPyre_2F_Text_DezDefeat::
# 48 "data/maps/MtPyre_2F/scripts.pory"
	.string "DEZ: Waaaah! I'm scared!$"

MtPyre_2F_Text_DezPostBattle::
# 52 "data/maps/MtPyre_2F/scripts.pory"
	.string "DEZ: We're lovey-dovey, so we don't care\n"
	.string "if we lose!$"

MtPyre_2F_Text_DezNotEnoughMons::
# 56 "data/maps/MtPyre_2F/scripts.pory"
	.string "DEZ: If you want to challenge us, you\n"
	.string "should bring at least two POKéMON.\p"
	.string "My boyfriend's strong. Just one\n"
	.string "POKéMON won't do at all.$"

MtPyre_2F_Text_LeahIntro::
# 60 "data/maps/MtPyre_2F/scripts.pory"
	.string "You are an unfamiliar sight… Depart\n"
	.string "before anything befalls you!$"

MtPyre_2F_Text_LeahDefeat::
# 64 "data/maps/MtPyre_2F/scripts.pory"
	.string "Hmm… You're durable.$"

MtPyre_2F_Text_LeahPostBattle::
# 68 "data/maps/MtPyre_2F/scripts.pory"
	.string "Our family has been TRAINERS here since\n"
	.string "my great-grandmother's time…\p"
	.string "It is my duty to protect this mountain…$"

MtPyre_2F_Text_ZanderIntro::
# 72 "data/maps/MtPyre_2F/scripts.pory"
	.string "Kiyaaaaah! I'm terrified!$"

MtPyre_2F_Text_ZanderDefeat::
# 76 "data/maps/MtPyre_2F/scripts.pory"
	.string "Nooooooo! I lost my wits!$"

MtPyre_2F_Text_ZanderPostBattle::
# 80 "data/maps/MtPyre_2F/scripts.pory"
	.string "I get freaked out every time I see\n"
	.string "anything move…\p"
	.string "I shouldn't have come here to train…$"
