DewfordTown_MapScripts::
	.byte 0


DewfordTown_EventScript_Briney::
	end


DewfordTown_EventScript_GymSign::
# 9 "data/maps/DewfordTown/scripts.pory"
	msgbox DewfordTown_Text_GymSign, MSGBOX_SIGN
	end


DewfordTown_EventScript_HallSign::
# 14 "data/maps/DewfordTown/scripts.pory"
	msgbox DewfordTown_Text_HallSign, MSGBOX_SIGN
	end


DewfordTown_EventScript_OldRodFisherman::
	end


DewfordTown_EventScript_TownSign::
# 23 "data/maps/DewfordTown/scripts.pory"
	msgbox DewfordTown_Text_TownSign, MSGBOX_SIGN
	end


DewfordTown_EventScript_TrendyPhraseBoy::
	end


DewfordTown_EventScript_Woman::
	end


DewfordTown_Text_TownSign::
# 36 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD TOWN “A tiny island in the blue\n"
	.string "sea.”$"

DewfordTown_Text_HallSign::
# 40 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD HALL “Everyone's information\n"
	.string "exchange!”$"

DewfordTown_Text_GymSign::
# 44 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD TOWN POKéMON GYM LEADER:\n"
	.string "BRAWLY\l"
	.string "“A big wave in fighting!”$"
