DewfordTown_MapScripts::
# 2 "data/maps/DewfordTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, DewfordTown_OnTransition
	.byte 0


DewfordTown_Text_TinyIslandCommunity::
# 6 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD is a tiny island community. If\n"
	.string "something gets trendy here,\l"
	.string "everyone picks up on it right away.$"

DewfordTown_Text_TownSign::
# 10 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD TOWN A tiny island in the blue\n"
	.string "sea.$"

DewfordTown_Text_GymSign::
# 14 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD TOWN POKMON GYM LEADER:\n"
	.string "BRAWLY\l"
	.string "A big wave in fighting!$"

DewfordTown_Text_HallSign::
# 18 "data/maps/DewfordTown/scripts.pory"
	.string "DEWFORD HALL Everyone's information\n"
	.string "exchange!$"

Route104_Text_LandedInDewfordDeliverLetter::
# 22 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: Ahoy! We've hit land in\n"
	.string "DEWFORD.\p"
	.string "I suppose you're off to deliver that\n"
	.string "LETTER to, who was it now, STEVEN!$"

DewfordTown_Text_SetSailBackToPetalburg::
# 26 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: Have you delivered your\n"
	.string "LETTER?\p"
	.string "Or were you meaning to sail back to\n"
	.string "PETALBURG?$"

DewfordTown_Text_PetalburgWereSettingSail2::
# 30 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: PETALBURG it is, then!\p"
	.string "Anchors aweigh! PEEKO, we're setting\n"
	.string "sail, my darling!$"

DewfordTown_Text_GoDeliverIllBeWaiting::
# 34 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: Then you go on and deliver\n"
	.string "the LETTER. I'll be waiting.$"

DewfordTown_Text_BrineyLandedInDewford::
# 38 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: Ahoy! We've hit land in\n"
	.string "DEWFORD!\p"
	.string "You just go on and tell me whenever you\n"
	.string "want to set sail again!$"

DewfordTown_Text_WhereAreWeBound::
# 42 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: Ahoy! For you, I'll go out to\n"
	.string "sea anytime!\p"
	.string "Now, my friend, where are we bound?$"

DewfordTown_Text_PetalburgWereSettingSail::
# 46 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: PETALBURG, is it?\p"
	.string "Anchors aweigh! PEEKO, we're setting\n"
	.string "sail, my darling!$"

DewfordTown_Text_SlateportWereSettingSail::
# 50 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: SLATEPORT, is it?\p"
	.string "Anchors aweigh! PEEKO, we're setting\n"
	.string "sail, my darling!$"

DewfordTown_Text_JustTellMeWhenYouNeedToSetSail::
# 54 "data/maps/DewfordTown/scripts.pory"
	.string "MR. BRINEY: You just tell me whenever\n"
	.string "you need to set sail again!$"

DewfordTown_Text_GettingItchToFish::
# 58 "data/maps/DewfordTown/scripts.pory"
	.string "This is a renowned fishing spot. Are you\n"
	.string "getting the itch to fish?$"

DewfordTown_Text_GiveYouOneOfMyRods::
# 62 "data/maps/DewfordTown/scripts.pory"
	.string "I hear you, and I like what you're\n"
	.string "saying!\p"
	.string "I'll give you one of my fishing RODS.$"

DewfordTown_Text_ThrowInFishingAdvice::
# 66 "data/maps/DewfordTown/scripts.pory"
	.string "And, as an added bonus, I'll even throw\n"
	.string "in a little fishing advice!\p"
	.string "First, you want to face the water, then\n"
	.string "use the ROD.\p"
	.string "Focus your mind If you get a bite, pull\n"
	.string "on the ROD.\p"
	.string "Sometimes you can snag something\n"
	.string "immediately, but with bigger catches,\l"
	.string "you need to time the pulls on your ROD\l"
	.string "to haul them in.$"

DewfordTown_Text_ThatsTooBadThen::
# 70 "data/maps/DewfordTown/scripts.pory"
	.string "Oh, is that so? That's too bad, then.$"

DewfordTown_Text_HowsYourFishing::
# 74 "data/maps/DewfordTown/scripts.pory"
	.string "Yo! How's your fishing?$"

DewfordTown_Text_GreatHaulInSomeBigOnes::
# 78 "data/maps/DewfordTown/scripts.pory"
	.string "Is that right! That's great! Haul in\n"
	.string "some big ones!$"

DewfordTown_Text_FishingAdvice::
# 82 "data/maps/DewfordTown/scripts.pory"
	.string "Oh, hey, don't get down on yourself! I'll\n"
	.string "give you a little fishing advice.\p"
	.string "First, you want to face the water, then\n"
	.string "use the ROD.\p"
	.string "Focus your mind If you get a bite, pull\n"
	.string "the ROD.\p"
	.string "Sometimes you can snag something\n"
	.string "immediately, but with bigger catches,\l"
	.string "you need to time the pulls on your ROD\l"
	.string "to haul them in.$"

DewfordTown_Text_XIsTheBiggestHappeningThingRight::
# 86 "data/maps/DewfordTown/scripts.pory"
	.string "I like what's hip, happening, and trendy.\n"
	.string "I'm always checking it out.\p"
	.string "Listen, have you heard about this new\n"
	.string "{STR_VAR_1}?\p"
	.string "That's right! Of course you know!\p"
	.string "I mean, sheesh, {STR_VAR_1}\l"
	.string "It's the hottest thing in cool!\p"
	.string "Wherever you're from, {STR_VAR_1}\l"
	.string "is the biggest happening thing, right?$"

DewfordTown_Text_TellMeWhatsNewAndIn::
# 90 "data/maps/DewfordTown/scripts.pory"
	.string "Hunh? It's not the hip and happening\n"
	.string "thing?\p"
	.string "Well, hey, you have to tell me, what's new\n"
	.string "and what's in?$"

DewfordTown_Text_OfCourseIKnowAboutThat::
# 94 "data/maps/DewfordTown/scripts.pory"
	.string "Hunh? {STR_VAR_2}?\p"
	.string "\p"
	.string "Uh Yeah! That's right! Yeah, I knew\n"
	.string "that! Knew it all along!\p"
	.string "Of course I know about that!\n"
	.string "{STR_VAR_2}, right?\p"
	.string "Yeah, that's it, it's there! Isn't\n"
	.string "{STR_VAR_2}\l"
	.string "the coolest, or what?\p"
	.string "It's the hippest thing in hip. You think\n"
	.string "I'd not know about it?\p"
	.string "{STR_VAR_1} It's, like, so five\n"
	.string "minutes ago.\p"
	.string "Now, {STR_VAR_2} is what's vital and\n"
	.string "in tune with the times!$"

DewfordTown_Text_XHuhIThinkYIsCool::
# 98 "data/maps/DewfordTown/scripts.pory"
	.string "Hmm {STR_VAR_2}, huh?\p"
	.string "But personally, I think {STR_VAR_1}\l"
	.string "is what's real in cool.$"

DewfordTown_Text_HearOfAnyTrendsComeShareWithMe::
# 102 "data/maps/DewfordTown/scripts.pory"
	.string "Well, if you hear of any happening new\n"
	.string "trends, come share them with me, okay?$"

DewfordTown_Text_YeahDefinitionOfInRightNow::
# 106 "data/maps/DewfordTown/scripts.pory"
	.string "Yeah, absolutely right!\p"
	.string "{STR_VAR_1} is the definition of in\n"
	.string "right now.$"
