DragonsDen_B1F_MapScripts::
	.byte 0


DragonsDen_B1F_EventScript_SmithNPC1::
# 5 "data/maps/DragonsDen_B1F/scripts.pory"
	msgbox DragonsDen_B1F_Text_SmithNPC1, MSGBOX_NPC
	end


DragonsDen_B1F_EventScript_SmithNPC2::
# 14 "data/maps/DragonsDen_B1F/scripts.pory"
	msgbox DragonsDen_B1F_Text_SmithNPC2, MSGBOX_NPC
	end


DragonsDen_B1F_EventScript_SmithNPC3::
# 23 "data/maps/DragonsDen_B1F/scripts.pory"
	msgbox DragonsDen_B1F_Text_SmithNPC3, MSGBOX_NPC
	end


DragonsDen_B1F_Text_SmithNPC1::
# 9 "data/maps/DragonsDen_B1F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

DragonsDen_B1F_Text_SmithNPC2::
# 18 "data/maps/DragonsDen_B1F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

DragonsDen_B1F_Text_SmithNPC3::
# 27 "data/maps/DragonsDen_B1F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
