BattleFrontier_BattlePyramidTop_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePyramidTop_OnResume
# 3 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePyramidTop_OnFrame
# 4 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattlePyramidTop_OnTransition
# 5 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePyramidTop_OnWarp
	.byte 0


BattleFrontier_BattlePyramidTop_Text_ReachedSummitUpYouGo::
# 9 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "It is a delight to see you here! You\n"
	.string "have reached the summit of\l"
	.string "the BATTLE PYRAMID!\p"
	.string "Above here is the PYRAMID's lookout\n"
	.string "point.\p"
	.string "It is a place open only to those who\n"
	.string "have conquered the PYRAMID.\p"
	.string "Now, please! Up you go!$"

BattleFrontier_BattlePyramidTop_Text_PlayerConqueredPyramid::
# 13 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "The PYRAMID's new conqueror! Let the\n"
	.string "name {PLAYER} be known!$"

BattleFrontier_BattlePyramidTop_Text_ChiefBeatYouHere::
# 17 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "It is a delight to see you here!\p"
	.string "Unfortunately, you were second by a\n"
	.string "mere fraction of time!\p"
	.string "Our chief has already conquered the\n"
	.string "PYRAMID ahead of you.\p"
	.string "However, my young explorer You are a\n"
	.string "TRAINER!\p"
	.string "Assert your power and take the glory of\n"
	.string "the pinnacle from our chief!\p"
	.string "Now, please! When you are ready, take\n"
	.string "one more step of courage!$"

BattleFrontier_BattlePyramidTop_Text_ExplorationsAreGrandestAdventure::
# 21 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Young adventurer\p"
	.string "Wouldn't you agree that explorations\n"
	.string "are the grandest of adventures?\p"
	.string "Your own wits!\p"
	.string "Your own strength!\p"
	.string "Your own POKMON!\p"
	.string "And, above all, only your own courage to\n"
	.string "lead you through unknown worlds$"

BattleFrontier_BattlePyramidTop_Text_ImPyramidKingBrandon::
# 25 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Aah, yes, indeed this life is grand!\n"
	.string "Grand, it is! Eh?\p"
	.string "I'm BRANDON!\p"
	.string "I'm the PYRAMID KING, which means I'm in\n"
	.string "charge here.\p"
	.string "Most people call me the chief!\p"
	.string "You coming here means you have that\n"
	.string "much confidence in yourself,\l"
	.string "am I right?\p"
	.string "Hahahah! This should be exciting!$"

BattleFrontier_BattlePyramidTop_Text_BringCourageToOurBattle::
# 29 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Now, then! Bring your courage to our\n"
	.string "battle!$"

BattleFrontier_BattlePyramidTop_Text_BrandonFrontierPassPlease::
# 33 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "BRANDON: Hahahah! Grand it was! Grand,\n"
	.string "yes, indeed!\p"
	.string "Well done! You've earned recognition!\n"
	.string "Your FRONTIER PASS, please!$"

BattleFrontier_BattlePyramidTop_Text_ReceivedBraveSymbol::
# 37 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "The Brave Symbol was embossed on the\n"
	.string "FRONTIER PASS!$"

BattleFrontier_BattlePyramidTop_Text_LookForwardToNextMeeting::
# 41 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Young explorer! I look forward to our\n"
	.string "next meeting!$"

BattleFrontier_BattlePyramidTop_Text_BrandonYouveReturned::
# 45 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "BRANDON: You've finally returned, young\n"
	.string "explorer\p"
	.string "Your love of adventure seems to come\n"
	.string "deep from within your heart\p"
	.string "Yes You are exactly as I was in my own\n"
	.string "youth\p"
	.string "Ah\p"
	.string "The passionate!\p"
	.string "The dangerous!\p"
	.string "The desperate!\p"
	.string "Those days of death-defying,\n"
	.string "life-affirming adventures are back$"

BattleFrontier_BattlePyramidTop_Text_MyCourageIsOffMeter::
# 49 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Now, then!\p"
	.string "I sense my own courage is off the\n"
	.string "meter!$"

BattleFrontier_BattlePyramidTop_Text_EverythingYouHave::
# 53 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Everything you have! I'm braced for it\n"
	.string "all!$"

BattleFrontier_BattlePyramidTop_Text_BrandonRemarkableHaveThis::
# 57 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "BRANDON: Hahahah! Remarkable!\l"
	.string "Yes, it's grand, indeed!\p"
	.string "Young explorer!\p"
	.string "You've bested me through and through!\n"
	.string "Here! I want you to have this!$"

BattleFrontier_BattlePyramidTop_Text_BraveSymbolTookGoldenShine::
# 61 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "The Brave Symbol took on a golden\n"
	.string "shine!$"

BattleFrontier_BattlePyramidTop_Text_FarewellForNow::
# 65 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Ah, yes! It just goes to show that I\n"
	.string "have much to learn still!\p"
	.string "May our paths cross again! Farewell for\n"
	.string "now, young explorer!$"

BattleFrontier_BattlePyramidTop_Text_StepForwardWhenReady::
# 69 "data/maps/BattleFrontier_BattlePyramidTop/scripts.pory"
	.string "Now, when you are ready, take courage\n"
	.string "and step forward.$"
