OreburghCity_MapScripts::
	.byte 0


OreburghCity_EventScript_Sign1::
# 5 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_Sign1, MSGBOX_SIGN
	end


OreburghCity_EventScript_Sign4::
	end


OreburghCity_EventScript_SmithNPC1::
# 19 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC1, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC2::
# 28 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC2, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC3::
# 37 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC3, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC4::
# 46 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC4, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC5::
# 55 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC5, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC6::
# 64 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC6, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC7::
# 73 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC7, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC8::
# 82 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC8, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC9::
# 91 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC9, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC10::
# 100 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC10, MSGBOX_NPC
	end


OreburghCity_EventScript_SmithNPC11::
# 109 "data/maps/OreburghCity/scripts.pory"
	msgbox OreburghCity_Text_SmithNPC11, MSGBOX_NPC
	end


OreburghCity_Text_Sign1::
# 9 "data/maps/OreburghCity/scripts.pory"
	.string "OreburghCity Sign 1$"

OreburghCity_Text_SmithNPC1::
# 23 "data/maps/OreburghCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OreburghCity_Text_SmithNPC2::
# 32 "data/maps/OreburghCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

OreburghCity_Text_SmithNPC3::
# 41 "data/maps/OreburghCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

OreburghCity_Text_SmithNPC4::
# 50 "data/maps/OreburghCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

OreburghCity_Text_SmithNPC5::
# 59 "data/maps/OreburghCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

OreburghCity_Text_SmithNPC6::
# 68 "data/maps/OreburghCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

OreburghCity_Text_SmithNPC7::
# 77 "data/maps/OreburghCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

OreburghCity_Text_SmithNPC8::
# 86 "data/maps/OreburghCity/scripts.pory"
	.string "I know kung fu.$"

OreburghCity_Text_SmithNPC9::
# 95 "data/maps/OreburghCity/scripts.pory"
	.string "Dodge this.$"

OreburghCity_Text_SmithNPC10::
# 104 "data/maps/OreburghCity/scripts.pory"
	.string "Choice is an illusion created between\n"
	.string "those with power and those without.$"

OreburghCity_Text_SmithNPC11::
# 113 "data/maps/OreburghCity/scripts.pory"
	.string "Hope is an illusion, Mr. Anderson.$"
