Route213_Access_MapScripts::
	.byte 0


Route213_Access_EventScript_SmithNPC1::
# 5 "data/maps/Route213_Access/scripts.pory"
	msgbox Route213_Access_Text_SmithNPC1, MSGBOX_NPC
	end


Route213_Access_EventScript_SmithNPC2::
# 14 "data/maps/Route213_Access/scripts.pory"
	msgbox Route213_Access_Text_SmithNPC2, MSGBOX_NPC
	end


Route213_Access_EventScript_SmithNPC3::
# 23 "data/maps/Route213_Access/scripts.pory"
	msgbox Route213_Access_Text_SmithNPC3, MSGBOX_NPC
	end


Route213_Access_Text_SmithNPC1::
# 9 "data/maps/Route213_Access/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route213_Access_Text_SmithNPC2::
# 18 "data/maps/Route213_Access/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route213_Access_Text_SmithNPC3::
# 27 "data/maps/Route213_Access/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
