MtEmber_Summit_MapScripts::
# 2 "data/maps/MtEmber_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtEmber_Summit_OnTransition
# 3 "data/maps/MtEmber_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MtEmber_Summit_OnResume
	.byte 0


MtEmber_Summit_MapScripts::
# 7 "data/maps/MtEmber_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtEmber_Summit_OnTransition
# 8 "data/maps/MtEmber_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MtEmber_Summit_OnResume
	return

