WhirlIslands_NorthEastEntrance_MapScripts::
	.byte 0


WhirlIslands_NorthEastEntrance_EventScript_SmithNPC1::
# 5 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	msgbox WhirlIslands_NorthEastEntrance_Text_SmithNPC1, MSGBOX_NPC
	end


WhirlIslands_NorthEastEntrance_EventScript_SmithNPC2::
# 14 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	msgbox WhirlIslands_NorthEastEntrance_Text_SmithNPC2, MSGBOX_NPC
	end


WhirlIslands_NorthEastEntrance_EventScript_SmithNPC3::
# 23 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	msgbox WhirlIslands_NorthEastEntrance_Text_SmithNPC3, MSGBOX_NPC
	end


WhirlIslands_NorthEastEntrance_EventScript_SmithNPC4::
# 32 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	msgbox WhirlIslands_NorthEastEntrance_Text_SmithNPC4, MSGBOX_NPC
	end


WhirlIslands_NorthEastEntrance_Text_SmithNPC1::
# 9 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

WhirlIslands_NorthEastEntrance_Text_SmithNPC2::
# 18 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

WhirlIslands_NorthEastEntrance_Text_SmithNPC3::
# 27 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

WhirlIslands_NorthEastEntrance_Text_SmithNPC4::
# 36 "data/maps/WhirlIslands_NorthEastEntrance/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
