LilycoveCity_PokemonCenter_1F_MapScripts::
	.byte 0


LilycoveCity_PokemonCenter_1F_EventScript_Boy::
# 5 "data/maps/LilycoveCity_PokemonCenter_1F/scripts.pory"
	msgbox LilycoveCity_PokemonCenter_1F_Text_HowManyKindsOfPokemon, MSGBOX_NPC
	end


LilycoveCity_PokemonCenter_1F_EventScript_Maniac::
	end


LilycoveCity_PokemonCenter_1F_EventScript_Nurse::
	end


LilycoveCity_PokemonCenter_1F_Text_HaventSeenRottenScoundrels::
# 17 "data/maps/LilycoveCity_PokemonCenter_1F/scripts.pory"
	.string "Those rotten scoundrels who steal\n"
	.string "POKéMON and rip off METEORITES…\p"
	.string "I haven't seen them around recently.$"

LilycoveCity_PokemonCenter_1F_Text_HowManyKindsOfPokemon::
# 21 "data/maps/LilycoveCity_PokemonCenter_1F/scripts.pory"
	.string "I wonder how many kinds of POKéMON\n"
	.string "there are in the world.\p"
	.string "It'd be great to cross seas and\n"
	.string "trade POKéMON with people far away.$"
