FourIsland_LoreleisHouse_MapScripts::
# 2 "data/maps/FourIsland_LoreleisHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_LoreleisHouse_OnTransition
	.byte 0


FourIsland_LoreleisHouse_Text_IfAnythingWereToHappenToIsland::
# 6 "data/maps/FourIsland_LoreleisHouse/scripts.pory"
	.string "LORELEI: There's something weighing\n"
	.string "heavily on my mind.\p"
	.string "If anything were to happen on the\n"
	.string "island where I was born…\p"
	.string "I wouldn't know about it if I were in the\n"
	.string "POKéMON LEAGUE.\p"
	.string "I wonder if that would make me\n"
	.string "irresponsible to my home…$"

FourIsland_LoreleisHouse_Text_IllReturnToLeagueInShortWhile::
# 10 "data/maps/FourIsland_LoreleisHouse/scripts.pory"
	.string "LORELEI: So, you managed to solve all\n"
	.string "the problems here?\p"
	.string "That's wonderful.\p"
	.string "That means there isn't any reason for\n"
	.string "me to be here all the time.\p"
	.string "Thank you…\p"
	.string "I'll return to the POKéMON LEAGUE in a\n"
	.string "short while.$"

FourIsland_LoreleisHouse_Text_WillDoWhatICanHereAndNow::
# 14 "data/maps/FourIsland_LoreleisHouse/scripts.pory"
	.string "I don't know what will happen in the\n"
	.string "future, but…\p"
	.string "I will do what I can here and now. That's\n"
	.string "all I can do.$"

FourIsland_LoreleisHouse_Text_StuffedMonDollsGalore::
# 18 "data/maps/FourIsland_LoreleisHouse/scripts.pory"
	.string "Stuffed POKéMON dolls galore!$"
