EverGrandeCity_PhoebesRoom_MapScripts::
	.byte 0


EverGrandeCity_PhoebesRoom_EventScript_Phoebe::
	end


EverGrandeCity_PhoebesRoom_Text_PostBattleSpeech::
# 8 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	.string "There's a definite bond between you\n"
	.string "and your POKéMON, too.\p"
	.string "I didn't recognize it, so it's only\n"
	.string "natural that I lost.\p"
	.string "Yup, I'd like to see how far your bond\n"
	.string "will carry you.\p"
	.string "Go ahead, move on to the next room.$"
