EverGrandeCity_PhoebesRoom_MapScripts::
# 2 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, EverGrandeCity_PhoebesRoom_OnLoad
# 3 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, EverGrandeCity_PhoebesRoom_OnWarp
# 4 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, EverGrandeCity_PhoebesRoom_OnFrame
	.byte 0


EverGrandeCity_PhoebesRoom_Text_IntroSpeech::
# 8 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	.string "Ahahaha!\p"
	.string "I'm PHOEBE of the ELITE FOUR. I did my\n"
	.string "training on MT. PYRE.\p"
	.string "While I trained, I gained the ability to\n"
	.string "commune with GHOST-type POKMON.\p"
	.string "Yes, the bond I developed with POKMON\n"
	.string "is extremely tight.\p"
	.string "So, come on, just try and see if you can\n"
	.string "even inflict damage on my POKMON!$"

EverGrandeCity_PhoebesRoom_Text_Defeat::
# 12 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	.string "Oh, darn. I've gone and lost.$"

EverGrandeCity_PhoebesRoom_Text_PostBattleSpeech::
# 16 "data/maps/EverGrandeCity_PhoebesRoom/scripts.pory"
	.string "There's a definite bond between you and\n"
	.string "your POKMON, too.\p"
	.string "I didn't recognize it, so it's only\n"
	.string "natural that I lost.\p"
	.string "Yup, I'd like to see how far your bond\n"
	.string "will carry you.\p"
	.string "Go ahead, move on to the next room.$"
