SkyPillar_Outside_MapScripts::
	.byte 0


SkyPillar_Outside_EventScript_Wallace::
	end


SkyPillar_Outside_Text_OpenedDoorToSkyPillar::
# 8 "data/maps/SkyPillar_Outside/scripts.pory"
	.string "WALLACE: Oh, my, I'm terribly sorry!\p"
	.string "In my haste, I didn't notice that\n"
	.string "I'd left you behind!\p"
	.string "I've opened the locked door of\n"
	.string "the SKY PILLAR.\p"
	.string "{PLAYER}{KUN}, let's be on our way!$"

SkyPillar_Outside_Text_DoorIsClosed::
# 12 "data/maps/SkyPillar_Outside/scripts.pory"
	.string "The door is closed.$"
