Route4_MapScripts::
	.byte 0


Route4_Text_TrippedOverGeodude::
# 5 "data/maps/Route4/scripts.pory"
	.string "Ouch! I tripped over a rocky POKMON,\n"
	.string "GEODUDE!$"

Route4_Text_CrissyIntro::
# 9 "data/maps/Route4/scripts.pory"
	.string "I came to MT. MOON in search of\n"
	.string "mushroom POKMON.$"

Route4_Text_CrissyDefeat::
# 13 "data/maps/Route4/scripts.pory"
	.string "After all I did to catch them!$"

Route4_Text_CrissyPostBattle::
# 17 "data/maps/Route4/scripts.pory"
	.string "There might not be any more mushrooms\n"
	.string "here.\p"
	.string "I think I got them all.$"

Route4_Text_MtMoonEntrance::
# 21 "data/maps/Route4/scripts.pory"
	.string "MT. MOON Tunnel Entrance$"

Route4_Text_RouteSign::
# 25 "data/maps/Route4/scripts.pory"
	.string "ROUTE 4 MT. MOON - CERULEAN CITY$"

Text_MegaPunchTeach::
# 29 "data/maps/Route4/scripts.pory"
	.string "A punch of roaring ferocity!\p"
	.string "Packed with destructive power!\p"
	.string "When the chips are down, MEGA PUNCH is\n"
	.string "the ultimate attack!\l"
	.string "You agree, yes?\p"
	.string "Now! Let me teach it to your POKMON!$"

Text_MegaPunchDeclined::
# 33 "data/maps/Route4/scripts.pory"
	.string "You'll be back when you understand the\n"
	.string "worth of MEGA PUNCH.$"

Text_MegaPunchWhichMon::
# 37 "data/maps/Route4/scripts.pory"
	.string "Fine! Which POKMON will learn it?$"

Text_MegaPunchTaught::
# 41 "data/maps/Route4/scripts.pory"
	.string "Now, we are comrades in the way of\n"
	.string "punching!\p"
	.string "You should go before you're seen by the\n"
	.string "misguided fool who trains\l"
	.string "only his silly kicking over there.$"

Text_MegaKickTeach::
# 45 "data/maps/Route4/scripts.pory"
	.string "A kick of brutal ferocity!\p"
	.string "Packed with destructive power!\p"
	.string "When you get right down to it, MEGA KICK\n"
	.string "is the ultimate attack!\l"
	.string "Don't you agree?\p"
	.string "Okay! I'll teach it to your POKMON!$"

Text_MegaKickDeclined::
# 49 "data/maps/Route4/scripts.pory"
	.string "You'll come crawling back when you\n"
	.string "realize the value of MEGA KICK.$"

Text_MegaKickWhichMon::
# 53 "data/maps/Route4/scripts.pory"
	.string "All right! Which POKMON wants to learn\n"
	.string "it?$"

Text_MegaKickTaught::
# 57 "data/maps/Route4/scripts.pory"
	.string "Now, we are soul mates in the way of\n"
	.string "kicking!\p"
	.string "You should run before you're seen by\n"
	.string "the deluded nitwit who trains\l"
	.string "only simple punching over there.$"

Route4_Text_PeopleLikeAndRespectBrock::
# 61 "data/maps/Route4/scripts.pory"
	.string "Oh, wow, that's the BOULDERBADGE! You\n"
	.string "got it from BROCK, didn't you?\p"
	.string "BROCK is cool. He's not just tough.\n"
	.string "People like and respect him.\p"
	.string "I want to become a GYM LEADER like him.$"
