VermilionCity_MapScripts::
# 2 "data/maps/VermilionCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, VermilionCity_OnTransition
# 3 "data/maps/VermilionCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, VermilionCity_OnFrame
	.byte 0


VermilionCity_Text_GrimerMultipliesInSludge::
# 7 "data/maps/VermilionCity/scripts.pory"
	.string "We're careful about pollution here.\p"
	.string "We've heard GRIMER multiplies in toxic\n"
	.string "sludge.$"

VermilionCity_Text_DidYouSeeSSAnneInHarbor::
# 11 "data/maps/VermilionCity/scripts.pory"
	.string "Did you see the S.S. ANNE moored in the\n"
	.string "harbor?$"

VermilionCity_Text_SSAnneHasDepartedForYear::
# 15 "data/maps/VermilionCity/scripts.pory"
	.string "So, the S.S. ANNE has departed?\p"
	.string "She'll be back in VERMILION about this\n"
	.string "time next year.$"

VermilionCity_Text_BuildingOnThisLand::
# 19 "data/maps/VermilionCity/scripts.pory"
	.string "I'm putting up a building on this plot of\n"
	.string "land. I own it all.\p"
	.string "My POKéMON is tamping the land to lay\n"
	.string "the foundation.$"

VermilionCity_Text_Machop::
# 23 "data/maps/VermilionCity/scripts.pory"
	.string "MACHOP: Guoh! Gogogoh!$"

VermilionCity_Text_MachopStompingLandFlat::
# 27 "data/maps/VermilionCity/scripts.pory"
	.string "A MACHOP is stomping the land flat.$"

VermilionCity_Text_SSAnneVisitsOnceAYear::
# 31 "data/maps/VermilionCity/scripts.pory"
	.string "The S.S. ANNE is a famous luxury cruise\n"
	.string "ship.\p"
	.string "It visits VERMILION once a year.$"

VermilionCity_Text_CitySign::
# 35 "data/maps/VermilionCity/scripts.pory"
	.string "VERMILION CITY The Port of Exquisite\n"
	.string "Sunsets$"

VermilionCity_Text_SnorlaxBlockingRoute12::
# 39 "data/maps/VermilionCity/scripts.pory"
	.string "NOTICE!\p"
	.string "ROUTE 12 may be blocked off by a\n"
	.string "sleeping POKéMON.\p"
	.string "Detour through ROCK TUNNEL to\n"
	.string "LAVENDER TOWN.\p"
	.string "VERMILION POLICE$"

VermilionCity_Text_PokemonFanClubSign::
# 43 "data/maps/VermilionCity/scripts.pory"
	.string "POKéMON FAN CLUB All POKéMON fans\n"
	.string "welcome!$"

VermilionCity_Text_GymSign::
# 47 "data/maps/VermilionCity/scripts.pory"
	.string "VERMILION CITY POKéMON GYM LEADER:\n"
	.string "LT. SURGE\l"
	.string "The Lightning American!$"

VermilionCity_Text_VermilionHarbor::
# 51 "data/maps/VermilionCity/scripts.pory"
	.string "VERMILION HARBOR$"

VermilionCity_Text_WelcomeToTheSSAnne::
# 55 "data/maps/VermilionCity/scripts.pory"
	.string "Welcome to the S.S. ANNE!$"

VermilionCity_Text_DoYouHaveATicket::
# 59 "data/maps/VermilionCity/scripts.pory"
	.string "Welcome to the S.S. ANNE!\p"
	.string "Excuse me, do you have a ticket?$"

VermilionCity_Text_FlashedSSTicket::
# 63 "data/maps/VermilionCity/scripts.pory"
	.string "{FONT_NORMAL}{PLAYER} flashed the S.S. TICKET!\p"
	.string "{FONT_MALE}Great! Welcome to the S.S. ANNE!$"

VermilionCity_Text_DontHaveNeededSSTicket::
# 67 "data/maps/VermilionCity/scripts.pory"
	.string "{FONT_NORMAL}{PLAYER} doesn't have the needed S.S.\n"
	.string "TICKET.\p"
	.string "{FONT_MALE}Sorry!\p"
	.string "You need a ticket to get aboard.$"

VermilionCity_Text_TheShipSetSail::
# 71 "data/maps/VermilionCity/scripts.pory"
	.string "The ship set sail.$"

VermilionCity_Text_BoardSeagallopTriPass::
# 75 "data/maps/VermilionCity/scripts.pory"
	.string "Ah, you have a TRI-PASS.\p"
	.string "Would you like to board a SEAGALLOP\n"
	.string "ferry?$"

VermilionCity_Text_Seagallop7Departing::
# 79 "data/maps/VermilionCity/scripts.pory"
	.string "Okay, everything's in order.\p"
	.string "SEAGALLOP HI-SPEED 7 will be departing\n"
	.string "immediately.$"

VermilionCity_Text_BoardSeagallopRainbowPass::
# 83 "data/maps/VermilionCity/scripts.pory"
	.string "Ah, you have a RAINBOW PASS.\p"
	.string "Would you like to board a SEAGALLOP\n"
	.string "ferry?$"

VermilionCity_Text_OhMysticTicketTakeYouToNavelRock::
# 87 "data/maps/VermilionCity/scripts.pory"
	.string "Oh! That's a MYSTICTICKET! Now that is\n"
	.string "rare.\p"
	.string "We'll be happy to take you to NAVEL\n"
	.string "ROCK anytime.$"

VermilionCity_Text_OhAuroraTicketTakeYouToBirthIsland::
# 91 "data/maps/VermilionCity/scripts.pory"
	.string "Oh! That's an AURORATICKET! Now that is\n"
	.string "rare.\p"
	.string "We'll be happy to take you to BIRTH\n"
	.string "ISLAND anytime.$"

VermilionCity_Text_BoardSeagallopFerry::
# 95 "data/maps/VermilionCity/scripts.pory"
	.string "Would you like to board a SEAGALLOP\n"
	.string "ferry?$"

VermilionCity_Text_Seagallop10Departing::
# 99 "data/maps/VermilionCity/scripts.pory"
	.string "Okay, everything's in order for you to\n"
	.string "board a special ferry.\p"
	.string "SEAGALLOP HI-SPEED 10 will be\n"
	.string "departing immediately.$"

VermilionCity_Text_Seagallop12Departing::
# 103 "data/maps/VermilionCity/scripts.pory"
	.string "Okay, everything's in order for you to\n"
	.string "board a special ferry.\p"
	.string "SEAGALLOP HI-SPEED 12 will be\n"
	.string "departing immediately.$"

VermilionCity_Text_Route2AideHasPackageForYou::
# 107 "data/maps/VermilionCity/scripts.pory"
	.string "Oh, hello, {PLAYER}! How are you\n"
	.string "doing?\p"
	.string "It's me, one of PROF. OAK's AIDES.\p"
	.string "Did you meet the other AIDE?\p"
	.string "He had a package from PROF. OAK for you,\n"
	.string "{PLAYER}.\p"
	.string "He said he'd look for you around ROUTE\n"
	.string "2, {PLAYER}.\p"
	.string "If you're in the ROUTE 2 area, please\n"
	.string "look for him.$"
