LilycoveCity_ContestLobby_MapScripts::
	.byte 0


LilycoveCity_ContestLobby_EventScript_Artist::
# 5 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_ContestFeastForEyes, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_BerryBlenderSpeedRecords::
	end


LilycoveCity_ContestLobby_EventScript_BlackBelt::
# 19 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_MasterRankHereICome, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_BlendMaster::
# 24 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_BlendWithTheBlendMaster, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker1::
# 29 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_WhoaAwesome, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker2::
# 34 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_WickedlyFast, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker3::
# 39 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_WhatAnExpert, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker4::
# 44 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_MadeAmazingPokeblocksWithMaster, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker5::
# 49 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_QualitiesOfBlendMaster, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_BlendMasterOnlooker6::
# 54 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_MasterWorksOnSkillsInMountains, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_Blender3Boy::
# 59 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_LetsGetBlendingAlready, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_Blender3Girl::
# 64 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox BerryBlender_Text_WhatKindOfPokeblockWillIGet, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_ContestReceptionist::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner1::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner2::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner3::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner4::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner5::
	end


LilycoveCity_ContestLobby_EventScript_ContestWinner6::
	end


LilycoveCity_ContestLobby_EventScript_FatMan::
# 121 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_ToughContestIsExtreme, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_Fisherman::
# 126 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_LavishedCareOnMon, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_Girl::
# 131 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_EventScript_LinkContestReceptionist::
# 136 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_LinkContestReception, MSGBOX_DEFAULT
	end


LilycoveCity_ContestLobby_EventScript_LinkContestResults::
	end


LilycoveCity_ContestLobby_EventScript_LittleGirl::
	end


LilycoveCity_ContestLobby_EventScript_NinjaBoy::
# 154 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	msgbox LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily, MSGBOX_NPC
	end


LilycoveCity_ContestLobby_Text_TakeHomeButIdLikeToTakeToMuseum::
# 158 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Oh… Then, I guess I'll just take\n"
	.string "this home with me…\p"
	.string "But, you know, I would like to take\n"
	.string "this to the art museum… Okay?$"

LilycoveCity_ContestLobby_Text_YourPokemonSpurredMeToPaint::
# 162 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Congratulations!\p"
	.string "I did a painting of your POKéMON to\n"
	.string "commemorate its victory…\p"
	.string "Well, your POKéMON's appeals were\n"
	.string "so fantastic, it spurred me into\l"
	.string "painting better than I usually do.\l"
	.string "Look, see?$"

LilycoveCity_ContestLobby_Text_WholeVarietyOfPokemonHere::
# 166 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "You can see a whole variety of\n"
	.string "POKéMON here.\p"
	.string "That's why I make this place a regular\n"
	.string "part of my daily stroll.$"

LilycoveCity_ContestLobby_Text_ToughContestIsExtreme::
# 170 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "The TOUGHNESS CONTEST is like\n"
	.string "extreme, man!\p"
	.string "Those muscular appeals…\n"
	.string "Cascading sweat… I swoon!$"

LilycoveCity_ContestLobby_Text_MasterRankHereICome::
# 174 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Hoo, boy… Master Rank CONTESTS,\n"
	.string "here I come.\p"
	.string "The world will know that my dearest\n"
	.string "POKéMON is the cutest being in all\l"
	.string "existence. The time has come!\l"
	.string "Uheheheh.$"

LilycoveCity_ContestLobby_Text_MakePokeblocksDifferentBerries::
# 178 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Make {POKEBLOCK}S and put them in there.\p"
	.string "When you make a {POKEBLOCK}, everyone\n"
	.string "has to put in a different BERRY.$"

LilycoveCity_ContestLobby_Text_ContestFeastForEyes::
# 182 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Wow, coming out to a CONTEST is\n"
	.string "a feast for these eyes!\p"
	.string "Would you look at all the POKéMON\n"
	.string "that just scream to be painted?$"

LilycoveCity_ContestLobby_Text_MadePokeblocksWithFamily::
# 186 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "I made {POKEBLOCK}S with Mom, Dad, and\n"
	.string "Big Sister. They turned out great!\p"
	.string "I bet you can make smoother, better\n"
	.string "{POKEBLOCK}S if you have more people.$"

LilycoveCity_ContestLobby_Text_IllTakePaintingToMuseum::
# 190 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "What, really? Then, sure, I will take\n"
	.string "this painting there right now.\p"
	.string "I'll give it a proper title, too.\p"
	.string "I hope they'll like it and consider\n"
	.string "exhibiting this.\p"
	.string "Please check if they did accept this.\n"
	.string "Thank you!$"

LilycoveCity_ContestLobby_Text_LavishedCareOnMon::
# 194 "data/maps/LilycoveCity_ContestLobby/scripts.pory"
	.string "Day in and day out, I lavished my care\n"
	.string "on this POKéMON.\p"
	.string "Its condition is peaking.\n"
	.string "Today, victory is mine!$"
