TrainerTower_Lobby_MapScripts::
# 2 "data/maps/TrainerTower_Lobby/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerTower_Lobby_OnResume
# 3 "data/maps/TrainerTower_Lobby/scripts.pory"
	map_script MAP_SCRIPT_ON_RETURN_TO_FIELD, TrainerTower_Lobby_OnReturnToField
# 4 "data/maps/TrainerTower_Lobby/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TrainerTower_Lobby_OnTransition
# 5 "data/maps/TrainerTower_Lobby/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, TrainerTower_Lobby_OnLoad
# 6 "data/maps/TrainerTower_Lobby/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerTower_Lobby_OnFrame
	.byte 0


TrainerTower_Lobby_Text_WelcomeToTrainerTower::
# 10 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Hello!\p"
	.string "Welcome to TRAINER TOWER where\n"
	.string "TRAINERS gather from all over!$"

TrainerTower_Lobby_Text_TrainersUpToFloorNum::
# 14 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "TRAINERS from all over the world gather\n"
	.string "here to battle.\p"
	.string "Let me see\p"
	.string "Right now, there are TRAINERS only up\n"
	.string "to Floor {STR_VAR_1}.$"

TrainerTower_Lobby_Text_TrainersUpEighthFloor::
# 18 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "TRAINERS are awaiting your challenge\n"
	.string "up to the eighth floor.$"

TrainerTower_Lobby_Text_LikeToChallengeTrainers::
# 22 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Would you like to challenge the waiting\n"
	.string "TRAINERS?$"

TrainerTower_Lobby_Text_StartClockGetSetGo::
# 26 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Okay, I'll get the clock started, so give\n"
	.string "it everything you have.\p"
	.string "On your marks\p"
	.string "Get set\p"
	.string "Go!$"

TrainerTower_Lobby_Text_PleaseVisitUsAgain::
# 30 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Please do visit us again!$"

TrainerTower_Lobby_Text_TooBadComeBackTryAgain::
# 34 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "That was too bad.\p"
	.string "I think you put in a tremendous effort\n"
	.string "in your battling.\p"
	.string "Please come back and try again!$"

TrainerTower_Lobby_Text_GiveItYourBest::
# 38 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "I hope you give it your best.$"

TrainerTower_Lobby_Text_MoveCounterHereWhenTrainersSwitch::
# 42 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "When the TRAINERS switch places, the\n"
	.string "movement can be hectic.\p"
	.string "To avoid the stampede, we moved the\n"
	.string "reception counter here.\p"
	.string "I'm sorry for the inconvenience.$"

TrainerTower_Roof_Text_ImOwnerBattledPerfectly::
# 46 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Hello\p"
	.string "I am the owner of this TOWER\p"
	.string "How the sky soars above this rooftop\p"
	.string "The caress of the winds up here\p"
	.string "It's all so perfect\p"
	.string "The way you battled It, too, was\n"
	.string "perfection$"

TrainerTower_Roof_Text_ThisIsForYou::
# 50 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "This is for you$"

TrainerTower_Roof_Text_DoneItInRecordTime::
# 54 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Oh! Stupendous!\p"
	.string "It's marvelous how you've come up here\n"
	.string "so quickly.\p"
	.string "The fact is, you've done it in record\n"
	.string "time\p"
	.string "I'll have your record posted at the\n"
	.string "reception counter.$"

TrainerTower_Roof_Text_TookSweetTimeGettingHere::
# 58 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "You seem to have taken your sweet time\n"
	.string "getting here$"

TrainerTower_Roof_Text_IdLikeToSeeBetterTime::
# 62 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "What I would like to see is a better time\n"
	.string "out of you\p"
	.string "I'm counting on you.\p"
	.string "Until then, farewell$"

TrainerTower_Text_XMinYZSec::
# 66 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "{STR_VAR_1} min.\n"
	.string "{STR_VAR_2}.{STR_VAR_3} sec.$"

TrainerTower_Lobby_Text_HereAreTheResults::
# 70 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "$"

TrainerTower_Lobby_Text_NeedTwoMonsForDouble::
# 74 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "This is a two-on-two battle.\p"
	.string "You may not battle unless you have at\n"
	.string "least two POKMON.$"

TrainerTower_Lobby_Text_ExplainTrainerTower::
# 78 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Here at TRAINER TOWER, there is an\n"
	.string "event called TIME ATTACK.\p"
	.string "You will be timed on how quickly you can\n"
	.string "get from the reception\l"
	.string "counter to the OWNER on the roof.\p"
	.string "The best times will be recorded on the\n"
	.string "Time Board.\p"
	.string "Try competing with friends to see who\n"
	.string "can beat it the fastest.\p"
	.string "You will not earn any EXP. Points or\n"
	.string "money by beating TRAINERS here.$"

TrainerTower_Lobby_Text_ThanksForCompeting::
# 82 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Thank you for competing!$"

TrainerTower_Lobby_Text_WonderWhatKindsOfTrainers::
# 86 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "I'm here to see how good I am.\p"
	.string "I wonder what kinds of TRAINERS are\n"
	.string "waiting for me?\p"
	.string "It's nerve-racking!$"

TrainerTower_Lobby_Text_StairsTougherThanAnyBattle::
# 90 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Gasp, gasp Gasp\p"
	.string "Never mind battling! These stairs\n"
	.string "They're tougher than any battle$"
