TrainerTower_Lobby_MapScripts::
	.byte 0


TrainerTower_Lobby_EventScript_SmithNPC1::
# 5 "data/maps/TrainerTower_Lobby/scripts.pory"
	msgbox TrainerTower_Lobby_Text_SmithNPC1, MSGBOX_NPC
	end


TrainerTower_Lobby_EventScript_SmithNPC2::
# 14 "data/maps/TrainerTower_Lobby/scripts.pory"
	msgbox TrainerTower_Lobby_Text_SmithNPC2, MSGBOX_NPC
	end


TrainerTower_Lobby_EventScript_SmithNPC3::
# 23 "data/maps/TrainerTower_Lobby/scripts.pory"
	msgbox TrainerTower_Lobby_Text_SmithNPC3, MSGBOX_NPC
	end


TrainerTower_Lobby_Text_SmithNPC1::
# 9 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

TrainerTower_Lobby_Text_SmithNPC2::
# 18 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

TrainerTower_Lobby_Text_SmithNPC3::
# 27 "data/maps/TrainerTower_Lobby/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
