GoldenrodCity_DepartmentStore_Rooftop_MapScripts::
	.byte 0


GoldenrodCity_DepartmentStore_Rooftop_EventScript_SmithNPC1::
# 5 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	msgbox GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_DepartmentStore_Rooftop_EventScript_SmithNPC2::
# 14 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	msgbox GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_DepartmentStore_Rooftop_EventScript_SmithNPC3::
# 23 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	msgbox GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC3, MSGBOX_NPC
	end


GoldenrodCity_DepartmentStore_Rooftop_EventScript_SmithNPC4::
# 32 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	msgbox GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC4, MSGBOX_NPC
	end


GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC1::
# 9 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC2::
# 18 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC3::
# 27 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

GoldenrodCity_DepartmentStore_Rooftop_Text_SmithNPC4::
# 36 "data/maps/GoldenrodCity_DepartmentStore_Rooftop/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
