AquaHideout_1F_MapScripts::
	.byte 0


AquaHideout_1F_Text_OurBossIsSnatchingSomething::
# 5 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with TEAM\n"
	.string "AQUA?\p"
	.string "Our BOSS isn't here! He's gone off to\n"
	.string "snatch something important!\p"
	.string "Where did he go?\p"
	.string "Wahaha! Do you really think I'd tell you\n"
	.string "something that crucial?$"

AquaHideout_1F_Text_WhereMightMagmaHideoutBe::
# 9 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? Are you a TEAM MAGMA\n"
	.string "grunt?\p"
	.string "I hear that TEAM MAGMA is trying to\n"
	.string "awaken an awesome POKMON at their\l"
	.string "HIDEOUT.\p"
	.string "But where might their HIDEOUT be?$"

AquaHideout_1F_Text_BossWentToJackASubmarine::
# 13 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with TEAM\n"
	.string "AQUA?\p"
	.string "Our BOSS isn't here! He's gone off to\n"
	.string "jack a submarine!\p"
	.string "Where did he go?\p"
	.string "Wahaha! Do you really think I'd tell you\n"
	.string "something that crucial?$"

AquaHideout_1F_Text_BossIsOnRoute122::
# 17 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with TEAM\n"
	.string "AQUA?\p"
	.string "Our BOSS isn't here! He's on his way to\n"
	.string "MT. PYRE on ROUTE 122!\p"
	.string "Why did he go?\p"
	.string "Wahaha! Do you really think I'd tell you\n"
	.string "something that crucial?$"

AquaHideout_1F_Text_TeamMagmaAtMtChimney::
# 21 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? Are you a TEAM MAGMA\n"
	.string "grunt?\p"
	.string "I hear that TEAM MAGMA is after an\n"
	.string "awesome POKMON at MT. CHIMNEY.\p"
	.string "But what is that POKMON like?$"

AquaHideout_1F_Text_BossIsInSlateportCity::
# 25 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with TEAM\n"
	.string "AQUA?\p"
	.string "Our BOSS isn't here! He's on his way to\n"
	.string "SLATEPORT CITY!\p"
	.string "Why did he go?\p"
	.string "Wahaha! Do you really think I'd tell you\n"
	.string "something that crucial?$"

AquaHideout_1F_Text_Grunt1Intro::
# 29 "data/maps/AquaHideout_1F/scripts.pory"
	.string "Ayiyiyi! Suspicious character spotted!$"

AquaHideout_1F_Text_Grunt1Defeat::
# 33 "data/maps/AquaHideout_1F/scripts.pory"
	.string "Grrrrr I lost it!$"

AquaHideout_1F_Text_Grunt1PostBattle::
# 37 "data/maps/AquaHideout_1F/scripts.pory"
	.string "I took the loss for the TEAM, but I did\n"
	.string "my job$"
