AquaHideout_1F_MapScripts::
	.byte 0


AquaHideout_1F_EventScript_Grunt1::
# 5 "data/maps/AquaHideout_1F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT, AquaHideout_1F_Text_Grunt1Intro, AquaHideout_1F_Text_Grunt1Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/AquaHideout_1F/scripts.pory"
	msgbox AquaHideout_1F_Text_Grunt1PostBattle
	return


AquaHideout_1F_EventScript_HideoutEntranceGrunt1::
	end


AquaHideout_1F_EventScript_HideoutEntranceGrunt2::
	end


AquaHideout_1F_Text_Grunt1Defeat::
# 19 "data/maps/AquaHideout_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_1F_Text_Grunt1Defeat$"

AquaHideout_1F_Text_Grunt1Intro::
# 23 "data/maps/AquaHideout_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_1F_Text_Grunt1Intro$"

AquaHideout_1F_Text_Grunt1PostBattle::
# 27 "data/maps/AquaHideout_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_1F_Text_Grunt1PostBattle$"

AquaHideout_1F_Text_BossIsInSlateportCity::
# 31 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with\n"
	.string "TEAM AQUA?\p"
	.string "Our BOSS isn't here!\n"
	.string "He's on his way to SLATEPORT CITY!\p"
	.string "… …\n"
	.string "Why did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"

AquaHideout_1F_Text_TeamMagmaAtMtChimney::
# 35 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What?\n"
	.string "Are you a TEAM MAGMA grunt?\p"
	.string "I hear that TEAM MAGMA is after\n"
	.string "an awesome POKéMON at MT. CHIMNEY.\p"
	.string "But what is that POKéMON like?$"

AquaHideout_1F_Text_WhereMightMagmaHideoutBe::
# 39 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What?\n"
	.string "Are you a TEAM MAGMA grunt?\p"
	.string "I hear that TEAM MAGMA is trying to\n"
	.string "awaken an awesome POKéMON at their\l"
	.string "HIDEOUT.\p"
	.string "But where might their HIDEOUT be?$"

AquaHideout_1F_Text_BossWentToJackASubmarine::
# 43 "data/maps/AquaHideout_1F/scripts.pory"
	.string "What? What? What do you want with\n"
	.string "TEAM AQUA?\p"
	.string "Our BOSS isn't here!\n"
	.string "He's gone off to jack a submarine!\p"
	.string "… …\n"
	.string "Where did he go?\p"
	.string "Wahaha! Do you really think I'd tell\n"
	.string "you something that crucial?$"
