SootopolisCity_House1_MapScripts::
	.byte 0


SootopolisCity_House1_EventScript_BrickBreakBlackBelt::
	end


SootopolisCity_House1_EventScript_Kecleon::
# 9 "data/maps/SootopolisCity_House1/scripts.pory"
	msgbox SootopolisCity_House1_Text_Kecleon, MSGBOX_DEFAULT
	end


SootopolisCity_House1_Text_Kecleon::
# 13 "data/maps/SootopolisCity_House1/scripts.pory"
	.string "KECLEON: Puu puhyaah.$"

SootopolisCity_House1_Text_ExplainBrickBreak::
# 17 "data/maps/SootopolisCity_House1/scripts.pory"
	.string "TM31 contains BRICK BREAK! It's a move\n"
	.string "so horrible that I can't describe it.$"
