SootopolisCity_House1_MapScripts::
	.byte 0


SootopolisCity_House1_MapScripts::
	return


SootopolisCity_House1_Text_DevelopedThisTM::
# 8 "data/maps/SootopolisCity_House1/scripts.pory"
	.string "For thirty years I've remained in\n"
	.string "SOOTOPOLIS honing my skills.\p"
	.string "I developed a shattering TM. I bequeath\n"
	.string "it to you!$"

SootopolisCity_House1_Text_ExplainBrickBreak::
# 12 "data/maps/SootopolisCity_House1/scripts.pory"
	.string "TM31 contains BRICK BREAK! It's a move\n"
	.string "so horrible that I can't describe it.$"

SootopolisCity_House1_Text_Kecleon::
# 16 "data/maps/SootopolisCity_House1/scripts.pory"
	.string "KECLEON: Puu puhyaah.$"
