SootopolisCity_House4_MapScripts::
	.byte 0


SootopolisCity_House4_Text_AncientTreasuresWaitingInSea::
# 5 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "Listen up, and I'll tell you something\n"
	.string "good.\p"
	.string "There's supposed to be an ancient ruin\n"
	.string "in the sea around here.\p"
	.string "There could be treasures just waiting\n"
	.string "to be discovered down there.$"

SootopolisCity_House4_Text_StrollUnderwaterWithPokemon::
# 9 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "Ancient treasures…\p"
	.string "It would be nice if they existed, but\n"
	.string "even if they didn't, it would be so\l"
	.string "beautiful to take an underwater\l"
	.string "stroll with my POKéMON.$"

SootopolisCity_House4_Text_Azumarill::
# 13 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "AZUMARILL: Marurii.$"
