SootopolisCity_House4_MapScripts::
	.byte 0


SootopolisCity_House4_EventScript_Azumarill::
# 5 "data/maps/SootopolisCity_House4/scripts.pory"
	msgbox SootopolisCity_House4_Text_Azumarill, MSGBOX_DEFAULT
	end


SootopolisCity_House4_EventScript_Man::
# 10 "data/maps/SootopolisCity_House4/scripts.pory"
	msgbox SootopolisCity_House4_Text_AncientTreasuresWaitingInSea, MSGBOX_NPC
	end


SootopolisCity_House4_EventScript_Woman::
# 15 "data/maps/SootopolisCity_House4/scripts.pory"
	msgbox SootopolisCity_House4_Text_StrollUnderwaterWithPokemon, MSGBOX_NPC
	end


SootopolisCity_House4_Text_Azumarill::
# 19 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "AZUMARILL: Marurii.$"

SootopolisCity_House4_Text_AncientTreasuresWaitingInSea::
# 23 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "Listen up, and I'll tell you something\n"
	.string "good.\p"
	.string "There's supposed to be an ancient\n"
	.string "ruin in the sea around here.\p"
	.string "There could be treasures just waiting\n"
	.string "to be discovered down there.$"

SootopolisCity_House4_Text_StrollUnderwaterWithPokemon::
# 27 "data/maps/SootopolisCity_House4/scripts.pory"
	.string "Ancient treasures…\p"
	.string "It would be nice if they existed, but\n"
	.string "even if they didn't, it would be so\l"
	.string "beautiful to take an underwater\l"
	.string "stroll with my POKéMON.$"
