PewterCity_House2_MapScripts::
	.byte 0


PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
# 5 "data/maps/PewterCity_House2/scripts.pory"
	.string "POKéMON learn new techniques as they\n"
	.string "grow.\p"
	.string "But some moves must be taught to them\n"
	.string "by people.$"

PewterCity_House2_Text_MonsEasierCatchIfStatused::
# 9 "data/maps/PewterCity_House2/scripts.pory"
	.string "A POKéMON becomes easier to catch if it\n"
	.string "has a status problem.\p"
	.string "Sleep, poison, burn, or paralysis… Those\n"
	.string "are all effective.\p"
	.string "But catching POKéMON is never a sure\n"
	.string "thing!$"
