PewterCity_House2_MapScripts::
	.byte 0


PewterCity_House2_EventScript_LittleBoy::
# 5 "data/maps/PewterCity_House2/scripts.pory"
	msgbox PewterCity_House2_Text_MonsEasierCatchIfStatused, MSGBOX_NPC
	end


PewterCity_House2_EventScript_OldMan::
# 10 "data/maps/PewterCity_House2/scripts.pory"
	msgbox PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow, MSGBOX_NPC
	end


PewterCity_House2_Text_MonsEasierCatchIfStatused::
# 15 "data/maps/PewterCity_House2/scripts.pory"
	.string "A POKéMON becomes easier to\n"
	.string "catch if it has a status problem.\p"
	.string "Sleep, poison, burn, or paralysis…\n"
	.string "Those are all effective.\p"
	.string "But catching POKéMON is never\n"
	.string "a sure thing!$"

PewterCity_House2_Text_MonsLearnTechniquesAsTheyGrow::
# 19 "data/maps/PewterCity_House2/scripts.pory"
	.string "POKéMON learn new techniques as\n"
	.string "they grow.\p"
	.string "But some moves must be taught to\n"
	.string "them by people.$"
