PalletTown_LeafsHouse_MapScripts::
	.byte 0


PalletTown_LeafsHouse_EventScript_SmithNPC1::
# 5 "data/maps/PalletTown_LeafsHouse/scripts.pory"
	msgbox PalletTown_LeafsHouse_Text_SmithNPC1, MSGBOX_NPC
	end


PalletTown_LeafsHouse_EventScript_SmithNPC2::
# 14 "data/maps/PalletTown_LeafsHouse/scripts.pory"
	msgbox PalletTown_LeafsHouse_Text_SmithNPC2, MSGBOX_NPC
	end


PalletTown_LeafsHouse_Text_SmithNPC1::
# 9 "data/maps/PalletTown_LeafsHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

PalletTown_LeafsHouse_Text_SmithNPC2::
# 18 "data/maps/PalletTown_LeafsHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
