ThreeIsland_House5_MapScripts::
	.byte 0


ThreeIsland_House5_Text_ImNotLostelle::
# 5 "data/maps/ThreeIsland_House5/scripts.pory"
	.string "Me? I'm not LOSTELLE.\p"
	.string "She's probably gone to the BERRY\n"
	.string "FOREST, I think.\p"
	.string "She picks BERRIES there for making\n"
	.string "lunch.$"

ThreeIsland_House5_Text_IllGoPlayWithLostelle::
# 9 "data/maps/ThreeIsland_House5/scripts.pory"
	.string "I think I'll go play with LOSTELLE\n"
	.string "today.$"
