PokemonLeague_LoreleisRoom_MapScripts::
# 2 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_LoreleisRoom_OnResume
# 3 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_LoreleisRoom_OnLoad
# 4 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonLeague_LoreleisRoom_OnTransition
# 5 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_LoreleisRoom_OnWarp
# 6 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_LoreleisRoom_OnFrame
	.byte 0


PokemonLeague_LoreleisRoom_Text_Intro::
# 10 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	.string "Welcome to the POKMON LEAGUE.\p"
	.string "I am LORELEI of the ELITE FOUR.\p"
	.string "No one can best me when it comes to icy\n"
	.string "POKMON.\p"
	.string "Freezing moves are powerful.\p"
	.string "Your POKMON will be at my mercy when\n"
	.string "they are frozen solid.\p"
	.string "Hahaha! Are you ready?{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_LoreleisRoom_Text_RematchIntro::
# 14 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	.string "Welcome to the POKMON LEAGUE.\p"
	.string "I, LORELEI of the ELITE FOUR, have\n"
	.string "returned!\p"
	.string "You know how it goes. No one can best me\n"
	.string "when it comes\l"
	.string "to icy POKMON.\p"
	.string "Freezing moves are powerful.\p"
	.string "Your POKMON will be at my mercy when\n"
	.string "they are frozen solid.\p"
	.string "Hahaha! Are you ready?{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_LoreleisRoom_Text_Defeat::
# 18 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	.string "Things shouldn't be this way!$"

PokemonLeague_LoreleisRoom_Text_PostBattle::
# 22 "data/maps/PokemonLeague_LoreleisRoom/scripts.pory"
	.string "You're better than I thought. Go on\n"
	.string "ahead.\p"
	.string "You only got a taste of the POKMON\n"
	.string "LEAGUE's power.$"
