MauvilleCity_BikeShop_MapScripts::
	.byte 0


MauvilleCity_BikeShop_Text_RydelGreeting::
# 5 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "Well, well, what have we here? A most\n"
	.string "energetic customer!\p"
	.string "Me? You may call me RYDEL. I'm the owner\n"
	.string "of this cycle shop.$"

MauvilleCity_BikeShop_Text_DidYouComeFromFarAway::
# 9 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Your RUNNING SHOES… They're\n"
	.string "awfully filthy.\p"
	.string "Did you come from far away?$"

MauvilleCity_BikeShop_Text_GuessYouDontNeedBike::
# 13 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Is that right?\p"
	.string "Then, I guess you have no need for any\n"
	.string "of my BIKES.$"

MauvilleCity_BikeShop_Text_ExplainBikesChooseWhichOne::
# 17 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Hm, hm… … … … …\p"
	.string "You're saying that you came all this way\n"
	.string "from LITTLEROOT?\p"
	.string "My goodness! That's ridiculously far!\p"
	.string "If you had one of my BIKES, you could go\n"
	.string "anywhere easily while feeling the\l"
	.string "gentle caress of the wind!\p"
	.string "I'll tell you what! I'll give you a BIKE!\p"
	.string "Oh, wait a second!\p"
	.string "I forgot to tell you that there are two\n"
	.string "kinds of BIKES!\p"
	.string "They are the MACH BIKE and the ACRO\n"
	.string "BIKE!\p"
	.string "The MACH BIKE is for cyclists who want\n"
	.string "to feel the wind with their bodies!\p"
	.string "And an ACRO BIKE is for those who\n"
	.string "prefer technical rides!\p"
	.string "I'm a real sweetheart, so you can have\n"
	.string "whichever one you like!\p"
	.string "Which one will you choose?$"

MauvilleCity_BikeShop_Text_ChoseMachBike::
# 21 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} chose the MACH BIKE.$"

MauvilleCity_BikeShop_Text_ChoseAcroBike::
# 25 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} chose the ACRO BIKE.$"

MauvilleCity_BikeShop_Text_ComeBackToSwitchBikes::
# 29 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: If you get the urge to switch\n"
	.string "BIKES, just come see me!$"

MauvilleCity_BikeShop_Text_WantToSwitchBikes::
# 33 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Oh? Were you thinking about\n"
	.string "switching BIKES?$"

MauvilleCity_BikeShop_Text_IllSwitchBikes::
# 37 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Okay, no problem! I'll switch\n"
	.string "BIKES for you!$"

MauvilleCity_BikeShop_Text_ExchangedMachForAcro::
# 41 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} got the MACH BIKE\n"
	.string "exchanged for an ACRO BIKE.$"

MauvilleCity_BikeShop_Text_ExchangedAcroForMach::
# 45 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} got the ACRO BIKE\n"
	.string "exchanged for a MACH BIKE.$"

MauvilleCity_BikeShop_Text_HappyYouLikeIt::
# 49 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Good, good! I'm happy that you\n"
	.string "like it!$"

MauvilleCity_BikeShop_Text_OhYourBikeIsInPC::
# 53 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "Oh? What happened to that BIKE I gave\n"
	.string "you?\p"
	.string "Oh, I get it, you stored it using your PC.\p"
	.string "Well, take it out of PC storage, and I'll\n"
	.string "be happy to exchange it!\p"
	.string "May the wind always be at your back on\n"
	.string "your adventure!$"

MauvilleCity_BikeShop_Text_HandbooksAreInBack::
# 57 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "I'm learning about BIKES while I work\n"
	.string "here.\p"
	.string "If you need advice on how to ride your\n"
	.string "BIKE, there're a couple handbooks in\l"
	.string "the back.$"

MauvilleCity_BikeShop_Text_MachHandbookWhichPage::
# 61 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "It's a handbook on the MACH BIKE.\p"
	.string "Which page do you want to read?$"

MauvilleCity_BikeShop_Text_HowToRideMachBike::
# 65 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "A BIKE moves in the direction that the\n"
	.string "+ Control Pad is pressed.\p"
	.string "It will speed up once it gets rolling.\p"
	.string "To stop, release the + Control Pad. The\n"
	.string "BIKE will slow to a stop.\p"
	.string "Want to read a different page?$"

MauvilleCity_BikeShop_Text_HowToTurnMachBike::
# 69 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "A MACH BIKE is speedy, but it can't stop\n"
	.string "very quickly.\p"
	.string "It gets a little tricky to get around a\n"
	.string "corner.\p"
	.string "Release the + Control Pad a little\n"
	.string "before the corner and slow down.\p"
	.string "Want to read a different page?$"

MauvilleCity_BikeShop_Text_SandySlopes::
# 73 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "There are small sandy slopes\n"
	.string "throughout the HOENN region.\p"
	.string "The loose, crumbly sand makes it\n"
	.string "impossible to climb normally.\p"
	.string "But if you have a MACH BIKE, you can zip\n"
	.string "up a sandy slope.\p"
	.string "Want to read a different page?$"

MauvilleCity_BikeShop_Text_AcroHandbookWhichPage::
# 77 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "It's a handbook on the ACRO BIKE.\p"
	.string "Which page do you want to read?$"

MauvilleCity_BikeShop_Text_Wheelies::
# 81 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "Press the B Button while riding, and the\n"
	.string "front wheel lifts up.\p"
	.string "You can zip around with the front wheel\n"
	.string "up using the + Control Pad.\p"
	.string "This technique is called a wheelie.\p"
	.string "Want to read a different page?$"

MauvilleCity_BikeShop_Text_BunnyHops::
# 85 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "Keeping the B Button pressed, your\n"
	.string "BIKE can hop on the spot.\p"
	.string "This technique is called a bunny hop.\p"
	.string "You can ride while hopping, too.\p"
	.string "Want to read a different page?$"

MauvilleCity_BikeShop_Text_Jumps::
# 89 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "Press the B Button and the + Control\n"
	.string "Pad at the same time to jump.\p"
	.string "Press the + Control Pad to the side to\n"
	.string "jump sideways.\p"
	.string "Press it backwards to make the BIKE\n"
	.string "change directions while jumping.\p"
	.string "Want to read a different page?$"
