MauvilleCity_BikeShop_MapScripts::
	.byte 0


MauvilleCity_BikeShop_EventScript_AcroBikeHandbook::
	end


MauvilleCity_BikeShop_EventScript_Assistant::
# 12 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	msgbox MauvilleCity_BikeShop_Text_HandbooksAreInBack, MSGBOX_NPC
	end


MauvilleCity_BikeShop_EventScript_MachBikeHandbook::
	end


MauvilleCity_BikeShop_EventScript_Rydel::
	end


MauvilleCity_BikeShop_Text_ChoseAcroBike::
# 27 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} chose the ACRO BIKE.$"

MauvilleCity_BikeShop_Text_ChoseMachBike::
# 31 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} chose the MACH BIKE.$"

MauvilleCity_BikeShop_Text_WantToSwitchBikes::
# 35 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Oh? Were you thinking about\n"
	.string "switching BIKES?$"

MauvilleCity_BikeShop_Text_DidYouComeFromFarAway::
# 39 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Your RUNNING SHOES…\n"
	.string "They're awfully filthy.\p"
	.string "Did you come from far away?$"

MauvilleCity_BikeShop_Text_HandbooksAreInBack::
# 43 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "I'm learning about BIKES while\n"
	.string "I work here.\p"
	.string "If you need advice on how to ride your\n"
	.string "BIKE, there're a couple handbooks in\l"
	.string "the back.$"

MauvilleCity_BikeShop_Text_ExchangedAcroForMach::
# 47 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} got the ACRO BIKE\n"
	.string "exchanged\n"
	.string "for a MACH BIKE.$"

MauvilleCity_BikeShop_Text_ComeBackToSwitchBikes::
# 51 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: If you get the urge to switch\n"
	.string "BIKES, just come see me!$"

MauvilleCity_BikeShop_Text_GuessYouDontNeedBike::
# 55 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Is that right?\p"
	.string "Then, I guess you have no need for\n"
	.string "any of my BIKES.$"

MauvilleCity_BikeShop_Text_IllSwitchBikes::
# 59 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Okay, no problem!\n"
	.string "I'll switch BIKES for you!$"

MauvilleCity_BikeShop_Text_HappyYouLikeIt::
# 63 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "RYDEL: Good, good!\n"
	.string "I'm happy that you like it!$"

MauvilleCity_BikeShop_Text_ExchangedMachForAcro::
# 67 "data/maps/MauvilleCity_BikeShop/scripts.pory"
	.string "{PLAYER} got the MACH BIKE\n"
	.string "exchanged\n"
	.string "for an ACRO BIKE.$"
