InsideOfTruck_MapScripts::
# 2 "data/maps/InsideOfTruck/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, InsideOfTruck_OnLoad
# 3 "data/maps/InsideOfTruck/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, InsideOfTruck_OnResume
	.byte 0


InsideOfTruck_Text_BoxPrintedWithMonLogo::
# 7 "data/maps/InsideOfTruck/scripts.pory"
	.string "The box is printed with a POKMON logo.\p"
	.string "It's a POKMON brand moving and delivery\n"
	.string "service.$"
