CeladonCity_Gym_MapScripts::
	.byte 0


CeladonCity_Gym_Text_ErikaIntro::
# 5 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Hello Lovely weather, isn't it?\l"
	.string "It's so pleasant\p"
	.string "Oh, dear I must have dozed off. Welcome.\p"
	.string "My name is ERIKA. I am the LEADER of\n"
	.string "CELADON GYM.\p"
	.string "I am a student of the art of flower\n"
	.string "arranging.\p"
	.string "My POKMON are solely of the GRASS type.\p"
	.string "Oh, I'm sorry, I had no idea that you\n"
	.string "wished to challenge me.\p"
	.string "Very well, but I shall not lose.{PLAY_BGM MUS_RG_GYM}$"

CeladonCity_Gym_Text_ErikaDefeat::
# 9 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh! I concede defeat.\l"
	.string "You are remarkably strong.\p"
	.string "I must confer on you the RAINBOWBADGE.$"

CeladonCity_Gym_Text_ErikaPostBattle::
# 13 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "You are cataloging POKMON? I must say\n"
	.string "I'm impressed.\p"
	.string "I would never collect POKMON if they\n"
	.string "were unattractive.$"

CeladonCity_Gym_Text_ExplainRainbowBadgeTakeThis::
# 17 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "The RAINBOWBADGE will make POKMON up\n"
	.string "to Lv. 50 obey.\p"
	.string "It also allows POKMON to use STRENGTH\n"
	.string "in and out of battle.\p"
	.string "Please also take this with you.$"

CeladonCity_Gym_Text_ReceivedTM19FromErika::
# 21 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "{PLAYER} received TM19 from ERIKA.$"

CeladonCity_Gym_Text_ExplainTM19::
# 25 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "TM19 contains GIGA DRAIN.\p"
	.string "Half the damage it inflicts is drained\n"
	.string "to heal your POKMON.\p"
	.string "Wouldn't you agree that it's a wonderful\n"
	.string "move?$"

CeladonCity_Gym_Text_ShouldMakeRoomForThis::
# 29 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "You should make room for this.$"

CeladonCity_Gym_Text_KayIntro::
# 33 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "I should tell you about this GYM.\p"
	.string "Only real ladies are allowed in here!$"

CeladonCity_Gym_Text_KayDefeat::
# 37 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "You're too rough!$"

CeladonCity_Gym_Text_KayPostBattle::
# 41 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Bleaah! I hope ERIKA wipes you out!$"

CeladonCity_Gym_Text_BridgetIntro::
# 45 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh, welcome. I was getting bored.$"

CeladonCity_Gym_Text_BridgetDefeat::
# 49 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "My makeup!$"

CeladonCity_Gym_Text_BridgetPostBattle::
# 53 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "GRASS-type POKMON are tough against\n"
	.string "the WATER type.\p"
	.string "They also have an edge on ROCK- and\n"
	.string "GROUND-type POKMON.$"

CeladonCity_Gym_Text_TinaIntro::
# 57 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Weren't you peeking in here earlier?$"

CeladonCity_Gym_Text_TinaDefeat::
# 61 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "You're an eye-opener!$"

CeladonCity_Gym_Text_TinaPostBattle::
# 65 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh, you were looking at ERIKA You\n"
	.string "weren't looking at me$"

CeladonCity_Gym_Text_TamiaIntro::
# 69 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Look, look! See my POKMON!\p"
	.string "I like the GRASS type. I like how they're\n"
	.string "easy to raise.$"

CeladonCity_Gym_Text_TamiaDefeat::
# 73 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "No!$"

CeladonCity_Gym_Text_TamiaPostBattle::
# 77 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "We only use GRASS-type POKMON at our\n"
	.string "GYM.\p"
	.string "Why? We also use them for making flower\n"
	.string "arrangements!$"

CeladonCity_Gym_Text_LisaIntro::
# 81 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh, hey!\p"
	.string "We don't like BUG- or FIRE-type POKMON\n"
	.string "in here!$"

CeladonCity_Gym_Text_LisaDefeat::
# 85 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh! You!$"

CeladonCity_Gym_Text_LisaPostBattle::
# 89 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Our LEADER ERIKA might be quiet, but\n"
	.string "she's famous around here.$"

CeladonCity_Gym_Text_LoriIntro::
# 93 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Pleased to meet you. My hobby is POKMON\n"
	.string "training.$"

CeladonCity_Gym_Text_LoriDefeat::
# 97 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh! Splendid!$"

CeladonCity_Gym_Text_LoriPostBattle::
# 101 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "I have a blind date coming up. I have to\n"
	.string "learn to be polite,\l"
	.string "especially if I have to battle.$"

CeladonCity_Gym_Text_MaryIntro::
# 105 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Welcome to CELADON GYM!\p"
	.string "You'd better not underestimate the\n"
	.string "nice ladies here.$"

CeladonCity_Gym_Text_MaryDefeat::
# 109 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "Oh! Beaten!$"

CeladonCity_Gym_Text_MaryPostBattle::
# 113 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "I didn't bring my best POKMON. Wait until\n"
	.string "next time!$"

CeladonCity_Gym_Text_GymStatue::
# 117 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "CELADON POKMON GYM LEADER: ERIKA\p"
	.string "WINNING TRAINERS: {RIVAL}$"

CeladonCity_Gym_Text_GymStatuePlayerWon::
# 121 "data/maps/CeladonCity_Gym/scripts.pory"
	.string "CELADON POKMON GYM LEADER: ERIKA\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
