CeladonCity_DepartmentStore_Roof_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_Roof_Text_ImThirstyGiveHerDrink::
# 5 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "I'm thirsty! I want something to drink!\p"
	.string "{FONT_NORMAL}Give her a drink?$"

CeladonCity_DepartmentStore_Roof_Text_GiveWhichDrink::
# 9 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Give her which drink?$"

CeladonCity_DepartmentStore_Roof_Text_YayFreshWaterHaveThis::
# 13 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Yay!\p"
	.string "FRESH WATER!\p"
	.string "Thank you! You can have this from me!$"

Text_ReceivedItemFromLittleGirl::
# 17 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "{PLAYER} received a {STR_VAR_2}\n"
	.string "from the little girl.$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM16::
# 21 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "TM16 contains LIGHT SCREEN.\p"
	.string "It's a move that weakens the power of\n"
	.string "special attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_YaySodaPopHaveThis::
# 25 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Yay!\p"
	.string "SODA POP!\p"
	.string "Thank you! You can have this from me!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM20::
# 29 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "TM20 contains SAFEGUARD.\p"
	.string "It's a move that prevents status\n"
	.string "problems among your POKMON.$"

CeladonCity_DepartmentStore_Roof_Text_YayLemonadeHaveThis::
# 33 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Yay!\p"
	.string "LEMONADE!\p"
	.string "Thank you! You can have this from me!$"

CeladonCity_DepartmentStore_Roof_Text_ExplainTM33::
# 37 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "TM33 contains REFLECT.\p"
	.string "It's a move that weakens the power of\n"
	.string "physical attacks by your foe.$"

CeladonCity_DepartmentStore_Roof_Text_DontHaveSpaceForThis::
# 41 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "You don't have space for this!$"

CeladonCity_DepartmentStore_Roof_Text_ImNotThirstyAfterAll::
# 45 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "No, thank you! I'm not thirsty after all!$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
# 49 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "My sister is a TRAINER, believe it or\n"
	.string "not.\p"
	.string "But, she's so immature, she drives me\n"
	.string "nuts!$"

CeladonCity_DepartmentStore_Roof_Text_ImThirstyIWantDrink::
# 53 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "I'm thirsty! I want something to drink!$"

CeladonCity_DepartmentStore_Roof_Text_FloorSign::
# 57 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_Roof_Text_VendingMachineWhatDoesItHave::
# 61 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "A vending machine! What does it have?$"

CeladonCity_DepartmentStore_Roof_Text_NotEnoughMoney::
# 65 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Oops, not enough money!$"

CeladonCity_DepartmentStore_Roof_Text_DrinkCanPoppedOut::
# 69 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "A can of {STR_VAR_1} popped out!$"

CeladonCity_DepartmentStore_Roof_Text_NoMoreRoomForStuff::
# 73 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "There's no more room for stuff!$"

CeladonCity_DepartmentStore_Roof_Text_NotThirsty::
# 77 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "Not thirsty!$"
