CeladonCity_DepartmentStore_Roof_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_Roof_EventScript_CooltrainerM::
# 5 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	msgbox CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_Roof_EventScript_FloorSign::
# 10 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	msgbox CeladonCity_DepartmentStore_Roof_Text_FloorSign, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_Roof_EventScript_ThirstyGirl::
	end


CeladonCity_DepartmentStore_Roof_EventScript_VendingMachine::
	end


CeladonCity_DepartmentStore_Roof_Text_FloorSign::
# 28 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_Roof_Text_MySisterIsImmature::
# 32 "data/maps/CeladonCity_DepartmentStore_Roof/scripts.pory"
	.string "My sister is a TRAINER, believe it\n"
	.string "or not.\p"
	.string "But, she's so immature, she drives\n"
	.string "me nuts!$"
