Route110_TrickHouseCorridor_MapScripts::
	.byte 0


Route110_TrickHouseCorridor_EventScript_SmithNPC1::
# 5 "data/maps/Route110_TrickHouseCorridor/scripts.pory"
	msgbox Route110_TrickHouseCorridor_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHouseCorridor_EventScript_SmithNPC2::
# 14 "data/maps/Route110_TrickHouseCorridor/scripts.pory"
	msgbox Route110_TrickHouseCorridor_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHouseCorridor_Text_SmithNPC1::
# 9 "data/maps/Route110_TrickHouseCorridor/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHouseCorridor_Text_SmithNPC2::
# 18 "data/maps/Route110_TrickHouseCorridor/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
