LilycoveCity_House1_MapScripts::
	.byte 0


LilycoveCity_House1_EventScript_ExpertM::
# 5 "data/maps/LilycoveCity_House1/scripts.pory"
	msgbox LilycoveCity_House1_Text_PokemonPartnersNotTools, MSGBOX_NPC
	end


LilycoveCity_House1_EventScript_Kecleon::
# 10 "data/maps/LilycoveCity_House1/scripts.pory"
	msgbox LilycoveCity_House1_Text_Kecleon, MSGBOX_DEFAULT
	end


LilycoveCity_House1_Text_PokemonPartnersNotTools::
# 14 "data/maps/LilycoveCity_House1/scripts.pory"
	.string "POKéMON are partners to people.\n"
	.string "They aren't our tools.\p"
	.string "Unfortunately, there are some people\n"
	.string "who fail to understand that…$"

LilycoveCity_House1_Text_Kecleon::
# 18 "data/maps/LilycoveCity_House1/scripts.pory"
	.string "KECLEON: Ruroro?$"
