LilycoveCity_House1_MapScripts::
	.byte 0


LilycoveCity_House1_Text_PokemonPartnersNotTools::
# 5 "data/maps/LilycoveCity_House1/scripts.pory"
	.string "POKMON are partners to people. They\n"
	.string "aren't our tools.\p"
	.string "Unfortunately, there are some people\n"
	.string "who fail to understand that$"

LilycoveCity_House1_Text_Kecleon::
# 9 "data/maps/LilycoveCity_House1/scripts.pory"
	.string "KECLEON: Ruroro?$"
