Underwater_MarineCave_MapScripts::
# 2 "data/maps/Underwater_MarineCave/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Underwater_MarineCave_OnResume
# 3 "data/maps/Underwater_MarineCave/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Underwater_MarineCave_OnTransition
	.byte 0


Underwater_MarineCave_MapScripts::
# 7 "data/maps/Underwater_MarineCave/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Underwater_MarineCave_OnResume
# 8 "data/maps/Underwater_MarineCave/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Underwater_MarineCave_OnTransition
	return

