LittlerootTown_BrendansHouse_2F_MapScripts::
	.byte 0


LittlerootTown_BrendansHouse_2F_EventScript_PC::
	end


LittlerootTown_BrendansHouse_2F_EventScript_RivalsPokeBall::
	end


LittlerootTown_BrendansHouse_2F_EventScript_SmithNPC1::
# 21 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	msgbox LittlerootTown_BrendansHouse_2F_Text_SmithNPC1, MSGBOX_NPC
	end


LittlerootTown_BrendansHouse_2F_EventScript_SmithNPC2::
# 30 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	msgbox LittlerootTown_BrendansHouse_2F_Text_SmithNPC2, MSGBOX_NPC
	end


PlayersHouse_2F_Text_ItsAGameCube::
# 12 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	.string "It's a Nintendo GameCube.\p"
	.string "A Game Boy Advance is connected to\n"
	.string "serve as the Controller.$"

PlayersHouse_2F_Text_Notebook::
# 16 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	.string "{PLAYER} flipped open the notebook.\p"
	.string "ADVENTURE RULE NO. 1\n"
	.string "Open the MENU with START.\p"
	.string "ADVENTURE RULE NO. 2\n"
	.string "Record your progress with SAVE.\p"
	.string "The remaining pages are blank…$"

LittlerootTown_BrendansHouse_2F_Text_SmithNPC1::
# 25 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

LittlerootTown_BrendansHouse_2F_Text_SmithNPC2::
# 34 "data/maps/LittlerootTown_BrendansHouse_2F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
