SSAnne_1F_Room2_MapScripts::
	.byte 0


SSAnne_1F_Room2_Text_TylerIntro::
# 5 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "I love POKéMON! Do you?$"

SSAnne_1F_Room2_Text_TylerDefeat::
# 9 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "Wow! You're great!$"

SSAnne_1F_Room2_Text_TylerPostBattle::
# 13 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "Listen, listen! Let me be your friend,\n"
	.string "okay?\p"
	.string "Then we can trade POKéMON and do\n"
	.string "stuff.$"

SSAnne_1F_Room2_Text_AnnIntro::
# 17 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "I collected these POKéMON from all\n"
	.string "around the world!$"

SSAnne_1F_Room2_Text_AnnDefeat::
# 21 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "Oh, no! I went around the world for\n"
	.string "these!$"

SSAnne_1F_Room2_Text_AnnPostBattle::
# 25 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "You hurt my poor POKéMON!\p"
	.string "I demand that you heal them at a\n"
	.string "POKéMON CENTER!$"

SSAnne_1F_Room2_Text_CruisingAroundWorld::
# 29 "data/maps/SSAnne_1F_Room2/scripts.pory"
	.string "We are cruising around the world, my\n"
	.string "children and I.$"
