AbandonedShip_HiddenFloorRooms_MapScripts::
	.byte 0


AbandonedShip_HiddenFloorRooms_EventScript_Trash::
# 6 "data/maps/AbandonedShip_HiddenFloorRooms/scripts.pory"
	msgbox AbandonedShip_HiddenFloorRooms_Text_BrightShinyTrash, MSGBOX_DEFAULT
	end


AbandonedShip_HiddenFloorRooms_Text_BrightShinyTrash::
# 11 "data/maps/AbandonedShip_HiddenFloorRooms/scripts.pory"
	.string "It's bright and shiny! But it's just\n"
	.string "trash…$"
