FuchsiaCity_House2_MapScripts::
	.byte 0


FuchsiaCity_House2_Text_DoYouLikeToFish::
# 5 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "I'm the FISHING GURU's older brother.\p"
	.string "I simply looove fishing! I can't bear to\n"
	.string "go without.\p"
	.string "Tell me, do you like to fish?$"

FuchsiaCity_House2_Text_LikeYourStyleTakeThis::
# 9 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "Grand! I like your style. I think we can\n"
	.string "be friends.\p"
	.string "Take this and fish, young friend!$"

FuchsiaCity_House2_Text_ReceivedGoodRod::
# 13 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "{PLAYER} received a GOOD ROD from the\n"
	.string "FISHING GURU's brother.$"

FuchsiaCity_House2_Text_GoodRodCanCatchBetterMons::
# 17 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "Fishing is a way of life! It is like the\n"
	.string "finest poetry.\p"
	.string "A crummy OLD ROD could only catch\n"
	.string "MAGIKARP, yes?\p"
	.string "But with a GOOD ROD, you can catch much\n"
	.string "better POKéMON.$"

FuchsiaCity_House2_Text_OhThatsDisappointing::
# 21 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "Oh… That's so disappointing…$"

FuchsiaCity_House2_Text_HowAreTheFishBiting::
# 25 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "Hello there, {PLAYER}!\p"
	.string "How are the fish biting?$"

FuchsiaCity_House2_Text_YouHaveNoRoomForGift::
# 29 "data/maps/FuchsiaCity_House2/scripts.pory"
	.string "Oh, no!\p"
	.string "I had a gift for you, but you have no\n"
	.string "room for it!$"
