OldaleTown_House1_MapScripts::
	.byte 0


OldaleTown_House1_Text_LeftPokemonGoesOutFirst::
# 5 "data/maps/OldaleTown_House1/scripts.pory"
	.string "When a POKMON battle starts, the one at\n"
	.string "the left of the list goes out first.\p"
	.string "So, when you get more POKMON in your\n"
	.string "party, try switching around the order\l"
	.string "of your POKMON.\p"
	.string "It could give you an advantage.$"
