MossdeepCity_MapScripts::
# 2 "data/maps/MossdeepCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MossdeepCity_OnTransition
	.byte 0


MossdeepCity_Text_WantKingsRockStevenGaveMe::
# 6 "data/maps/MossdeepCity/scripts.pory"
	.string "I got this from STEVEN, but I don't know\n"
	.string "what it's good for.\p"
	.string "I think it's called KING'S ROCK. Do you\n"
	.string "want it?$"

MossdeepCity_Text_YouCanKeepIt::
# 10 "data/maps/MossdeepCity/scripts.pory"
	.string "Why would you want it? You're weird.\p"
	.string "You can keep it, but keep it a secret\n"
	.string "from STEVEN.$"

MossdeepCity_Text_StevensHouseOverThere::
# 14 "data/maps/MossdeepCity/scripts.pory"
	.string "STEVEN's house is right over there!$"

MossdeepCity_Text_WhatToDoWithWeirdRock::
# 18 "data/maps/MossdeepCity/scripts.pory"
	.string "Yeah, you think so, too! What are you\n"
	.string "supposed to do with some weird rock?$"

MossdeepCity_Text_WailmerWatching::
# 22 "data/maps/MossdeepCity/scripts.pory"
	.string "Around MOSSDEEP, you can see wild\n"
	.string "WAILMER.\p"
	.string "It's called, uh What was it now\p"
	.string "WAI, WAI, WAI\p"
	.string "WAILMER watching!$"

MossdeepCity_Text_SpaceCenterReceivedLetter::
# 26 "data/maps/MossdeepCity/scripts.pory"
	.string "The island's SPACE CENTER has been\n"
	.string "launching huge rockets.\p"
	.string "There's been some kind of an uproar\n"
	.string "over a letter they received recently.$"

MossdeepCity_Text_SpaceCenterLaunchingRockets::
# 30 "data/maps/MossdeepCity/scripts.pory"
	.string "The island's SPACE CENTER has been\n"
	.string "launching huge rockets.$"

MossdeepCity_Text_MossdeepTargetedByMagma::
# 34 "data/maps/MossdeepCity/scripts.pory"
	.string "I heard from a SAILOR buddy that TEAM\n"
	.string "AQUA set up shop in LILYCOVE.\p"
	.string "I also heard that someone came along\n"
	.string "and wiped the floor with them!\p"
	.string "But MOSSDEEP here's been targeted by\n"
	.string "that TEAM MAGMA.\p"
	.string "If you want to know what they're up to,\n"
	.string "go visit the SPACE CENTER.$"

MossdeepCity_Text_FeelReliefOnLand::
# 38 "data/maps/MossdeepCity/scripts.pory"
	.string "I'm a SAILOR, so the sea's obviously\n"
	.string "more important to me.\p"
	.string "But you know? When I get back on land\n"
	.string "after a long voyage, I do feel relief!$"

MossdeepCity_Text_NiceIfWorldCoveredByFlowers::
# 42 "data/maps/MossdeepCity/scripts.pory"
	.string "Wouldn't it be nice?\p"
	.string "If the whole world was covered in\n"
	.string "plants and flowers like this island?$"

MossdeepCity_Text_LifeNeedsSeaToLive::
# 46 "data/maps/MossdeepCity/scripts.pory"
	.string "All life needs the sea to live, even\n"
	.string "though it makes its home on the land.\p"
	.string "Life, having run its course, becomes\n"
	.string "soil and returns to the land.\p"
	.string "And the sea is always connected to the\n"
	.string "land.\p"
	.string "Yes, like the very shoreline here.$"

MossdeepCity_Text_SurfExhilarating::
# 50 "data/maps/MossdeepCity/scripts.pory"
	.string "A voyage on a ship is fine.\p"
	.string "But crossing the sea with POKMON using\n"
	.string "SURF\p"
	.string "Now that's an exhilarating trip!\n"
	.string "Wouldn't you agree, youngster?$"

MossdeepCity_Text_SpecialSpaceCenterRock::
# 54 "data/maps/MossdeepCity/scripts.pory"
	.string "This rock has a special meaning to the\n"
	.string "people at the SPACE CENTER.\p"
	.string "They put it here as their wish for their\n"
	.string "rockets to fly safely.\p"
	.string "When you make a wish, what do you use?\n"
	.string "Do you wish upon a star?\p"
	.string "I use a wish tag to make it happen.\n"
	.string "That's what I do.$"

MossdeepCity_Text_ItsAWhiteRock::
# 58 "data/maps/MossdeepCity/scripts.pory"
	.string "It's a white rock.$"

MossdeepCity_Text_GymSign::
# 62 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP CITY POKMON GYM LEADERS:\n"
	.string "LIZA & TATE\p"
	.string "The mystic combination!$"

MossdeepCity_Text_CitySign::
# 66 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP CITY Our slogan: Cherish\n"
	.string "POKMON!$"

MossdeepCity_Text_SpaceCenterSign::
# 70 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP SPACE CENTER The closest\n"
	.string "place to space.$"

MossdeepCity_Text_ScottSomethingWrongWithTown::
# 74 "data/maps/MossdeepCity/scripts.pory"
	.string "SCOTT: {PLAYER}{KUN}, feeling good? I'm\n"
	.string "doing great!\p"
	.string "I'd heard MOSSDEEP's GYM LEADER is\n"
	.string "pretty strong, so I decided to come\l"
	.string "take a look-see for myself.\p"
	.string "But there's something wrong about this\n"
	.string "town.\p"
	.string "People are going on about a warning\n"
	.string "letter and the SPACE CENTER\p"
	.string "I don't think it concerns me in any way,\n"
	.string "though.$"

MossdeepCity_Text_SootopolisNewGymLeader::
# 78 "data/maps/MossdeepCity/scripts.pory"
	.string "Ahh It feels great letting the waves\n"
	.string "wash over my feet\p"
	.string "Speaking of the waves, you know that\n"
	.string "island city SOOTOPOLIS?\p"
	.string "I think the GYM there had a new LEADER\n"
	.string "come in.\p"
	.string "People tell me the new LEADER once\n"
	.string "mentored WALLACE.$"
