MossdeepCity_MapScripts::
	.byte 0


MossdeepCity_EventScript_BlackBelt::
# 5 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_SootopolisNewGymLeader, MSGBOX_NPC
	end


MossdeepCity_EventScript_CitySign::
# 10 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_CitySign, MSGBOX_SIGN
	end


MossdeepCity_EventScript_ExpertM::
# 15 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_LifeNeedsSeaToLive, MSGBOX_NPC
	end


MossdeepCity_EventScript_Girl::
# 20 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_NiceIfWorldCoveredByFlowers, MSGBOX_NPC
	end


MossdeepCity_EventScript_GymSign::
# 25 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_GymSign, MSGBOX_SIGN
	end


MossdeepCity_EventScript_KingsRockBoy::
	end


MossdeepCity_EventScript_Man::
# 34 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_SurfExhilarating, MSGBOX_DEFAULT
	end


MossdeepCity_EventScript_NinjaBoy::
# 39 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_WailmerWatching, MSGBOX_NPC
	end


MossdeepCity_EventScript_PokefanF::
	end


MossdeepCity_EventScript_Sailor::
	end


MossdeepCity_EventScript_Scott::
# 52 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_ScottSomethingWrongWithTown, MSGBOX_DEFAULT
	end


MossdeepCity_EventScript_SpaceCenterSign::
# 57 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_SpaceCenterSign, MSGBOX_SIGN
	end


MossdeepCity_EventScript_TeamMagmaEnterSpaceCenter::
	end


MossdeepCity_EventScript_VisitedMossdeep::
	end


MossdeepCity_EventScript_WhiteRock::
# 70 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_ItsAWhiteRock, MSGBOX_SIGN
	end


MossdeepCity_EventScript_Woman::
# 75 "data/maps/MossdeepCity/scripts.pory"
	msgbox MossdeepCity_Text_SpecialSpaceCenterRock, MSGBOX_NPC
	end


MossdeepCity_Text_GymSign::
# 80 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP CITY POKéMON GYM LEADERS:\n"
	.string "LIZA & TATE\p"
	.string "“The mystic combination!”$"

MossdeepCity_Text_CitySign::
# 84 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP CITY “Our slogan: Cherish\n"
	.string "POKéMON!”$"

MossdeepCity_Text_SpaceCenterSign::
# 88 "data/maps/MossdeepCity/scripts.pory"
	.string "MOSSDEEP SPACE CENTER “The closest\n"
	.string "place to space.”$"

MossdeepCity_Text_ItsAWhiteRock::
# 92 "data/maps/MossdeepCity/scripts.pory"
	.string "It's a white rock.$"

MossdeepCity_Text_WailmerWatching::
# 96 "data/maps/MossdeepCity/scripts.pory"
	.string "Around MOSSDEEP, you can see wild\n"
	.string "WAILMER.\p"
	.string "It's called, uh…\n"
	.string "What was it now…\p"
	.string "WAI, WAI, WAI…\p"
	.string "WAILMER watching!$"

MossdeepCity_Text_SootopolisNewGymLeader::
# 100 "data/maps/MossdeepCity/scripts.pory"
	.string "Ahh… It feels great letting the waves\n"
	.string "wash over my feet…\p"
	.string "Speaking of the waves, you know that\n"
	.string "island city SOOTOPOLIS?\p"
	.string "I think the GYM there had a new\n"
	.string "LEADER come in.\p"
	.string "People tell me the new LEADER once\n"
	.string "mentored WALLACE.$"

MossdeepCity_Text_SurfExhilarating::
# 104 "data/maps/MossdeepCity/scripts.pory"
	.string "A voyage on a ship is fine.\p"
	.string "But crossing the sea with POKéMON\n"
	.string "using SURF…\p"
	.string "Now that's an exhilarating trip!\n"
	.string "Wouldn't you agree, youngster?$"

MossdeepCity_Text_SpaceCenterLaunchingRockets::
# 108 "data/maps/MossdeepCity/scripts.pory"
	.string "The island's SPACE CENTER has been\n"
	.string "launching huge rockets.$"

MossdeepCity_Text_WhatToDoWithWeirdRock::
# 112 "data/maps/MossdeepCity/scripts.pory"
	.string "Yeah, you think so, too! What are you\n"
	.string "supposed to do with some weird rock?$"

MossdeepCity_Text_FeelReliefOnLand::
# 116 "data/maps/MossdeepCity/scripts.pory"
	.string "I'm a SAILOR, so the sea's obviously\n"
	.string "more important to me.\p"
	.string "But you know? When I get back on land\n"
	.string "after a long voyage, I do feel relief!$"

MossdeepCity_Text_StevensHouseOverThere::
# 120 "data/maps/MossdeepCity/scripts.pory"
	.string "STEVEN's house is right over there!$"

MossdeepCity_Text_SpecialSpaceCenterRock::
# 124 "data/maps/MossdeepCity/scripts.pory"
	.string "This rock has a special meaning to\n"
	.string "the people at the SPACE CENTER.\p"
	.string "They put it here as their wish for\n"
	.string "their rockets to fly safely.\p"
	.string "When you make a wish, what do you use?\n"
	.string "Do you wish upon a star?\p"
	.string "I use a wish tag to make it happen.\n"
	.string "That's what I do.$"

MossdeepCity_Text_ScottSomethingWrongWithTown::
# 128 "data/maps/MossdeepCity/scripts.pory"
	.string "SCOTT: {PLAYER}{KUN}, feeling good?\n"
	.string "I'm doing great!\p"
	.string "I'd heard MOSSDEEP's GYM LEADER is\n"
	.string "pretty strong, so I decided to come\l"
	.string "take a look-see for myself.\p"
	.string "But there's something wrong about\n"
	.string "this town.\p"
	.string "People are going on about a warning\n"
	.string "letter and the SPACE CENTER…\p"
	.string "I don't think it concerns me in any\n"
	.string "way, though.$"

MossdeepCity_Text_LifeNeedsSeaToLive::
# 132 "data/maps/MossdeepCity/scripts.pory"
	.string "All life needs the sea to live, even\n"
	.string "though it makes its home on the land.\p"
	.string "Life, having run its course, becomes\n"
	.string "soil and returns to the land.\p"
	.string "And the sea is always connected to\n"
	.string "the land.\p"
	.string "Yes, like the very shoreline here.$"

MossdeepCity_Text_NiceIfWorldCoveredByFlowers::
# 136 "data/maps/MossdeepCity/scripts.pory"
	.string "Wouldn't it be nice?\p"
	.string "If the whole world was covered in\n"
	.string "plants and flowers like this island?$"
