Route119_WeatherInstitute_2F_MapScripts::
# 2 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route119_WeatherInstitute_2F_OnTransition
	.byte 0


Route119_WeatherInstitute_2F_Text_Grunt2Intro::
# 6 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "The INSTITUTE created a type of\n"
	.string "POKéMON that has something to do with\l"
	.string "the weather. We're here to take them!$"

Route119_WeatherInstitute_2F_Text_Grunt2Defeat::
# 10 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Our plan's being spoiled by a kid?$"

Route119_WeatherInstitute_2F_Text_Grunt2PostBattle::
# 14 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "If the POKéMON they made here can\n"
	.string "control the weather freely, then we of\l"
	.string "TEAM AQUA definitely need it!$"

Route119_WeatherInstitute_2F_Text_Grunt3Intro::
# 18 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "We're TEAM AQUA! We appear wherever\n"
	.string "anything rare is\l"
	.string "found!$"

Route119_WeatherInstitute_2F_Text_Grunt3Defeat::
# 22 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "You got me!$"

Route119_WeatherInstitute_2F_Text_Grunt3PostBattle::
# 26 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "You don't have any idea what we of TEAM\n"
	.string "AQUA are working towards!\l"
	.string "You stay out of our way!$"

Route119_WeatherInstitute_2F_Text_Grunt5Intro::
# 30 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Don't tell me you're looking for that\n"
	.string "weather POKéMON, too?\p"
	.string "That's a no-no! We were here to get it\n"
	.string "first!$"

Route119_WeatherInstitute_2F_Text_Grunt5Defeat::
# 34 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Oh, will you look at my POKéMON?$"

Route119_WeatherInstitute_2F_Text_Grunt5PostBattle::
# 38 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Humph, so what? What we want…\p"
	.string "What we really want isn't here…\n"
	.string "Ihihihihi…$"

Route119_WeatherInstitute_2F_Text_ShellyIntro::
# 42 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Ahahahaha!\p"
	.string "You're going to meddle in TEAM AQUA's\n"
	.string "affairs?\p"
	.string "You're either absolutely fearless,\n"
	.string "simply ignorant, or both!\p"
	.string "You're so cute, you're disgusting! I'll\n"
	.string "put you down, kiddy!$"

Route119_WeatherInstitute_2F_Text_ShellyDefeat::
# 46 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Ahahahaha! You're disgustingly strong!$"

Route119_WeatherInstitute_2F_Text_ShellyPostBattle::
# 50 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "It's bad enough to have TEAM MAGMA\n"
	.string "blunder about, but now there's you!\p"
	.string "What makes you want to sniff around in\n"
	.string "our business, anyway?$"

Route119_WeatherInstitute_2F_Text_TeamMagmaJustPassedBy::
# 54 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "We have a situation here!\p"
	.string "A TEAM MAGMA mob just passed the\n"
	.string "WEATHER INSTITUTE.\p"
	.string "They appear to be headed for MT. PYRE!$"

Route119_WeatherInstitute_2F_Text_WeHaveToHurryToMtPyre::
# 58 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "What?!\p"
	.string "We can't waste any more time here! We\n"
	.string "have to hurry to MT. PYRE, too!\p"
	.string "Ahahahaha! TEAM MAGMA, just you wait!$"

Route119_WeatherInstitute_2F_Text_ThanksPleaseTakePokemon::
# 62 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Thanks! Thanks to you, we're safe!\p"
	.string "It might be an odd way of thanking you,\n"
	.string "but take this POKéMON.$"

Route119_WeatherInstitute_2F_Text_NoRoomForPokemon::
# 66 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Hm? You don't seem to have any room for\n"
	.string "this POKéMON.$"

Route119_WeatherInstitute_2F_Text_PlayerReceivedCastform::
# 70 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "{PLAYER} received CASTFORM!$"

Route119_WeatherInstitute_2F_Text_PokemonChangesWithWeather::
# 74 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "That POKéMON changes shape according\n"
	.string "to the weather conditions.\p"
	.string "There're plenty of them in the\n"
	.string "INSTITUTE--go ahead and take it.$"

Route119_WeatherInstitute_2F_Text_ChangingWeatherRidiculous::
# 78 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "I've been researching rain for many\n"
	.string "years, but it's ridiculous to think that\l"
	.string "humans can freely change the weather.$"

Route119_WeatherInstitute_2F_Text_GroudonWeather::
# 82 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "I track weather patterns over the\n"
	.string "HOENN region.\p"
	.string "Presently, a drought has been recorded\n"
	.string "in {STR_VAR_1}.\p"
	.string "Could that mean, somewhere near\n"
	.string "{STR_VAR_1}…$"

Route119_WeatherInstitute_2F_Text_KyogreWeather::
# 86 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "I track weather patterns over the\n"
	.string "HOENN region.\p"
	.string "Presently, heavy rainfall has been\n"
	.string "recorded over {STR_VAR_1}.\p"
	.string "Could that mean, somewhere near\n"
	.string "{STR_VAR_1}…$"

Route119_WeatherInstitute_2F_Text_NoAbnormalWeather::
# 90 "data/maps/Route119_WeatherInstitute_2F/scripts.pory"
	.string "Abnormal weather conditions are no\n"
	.string "longer being reported.\p"
	.string "The occasional rainfall is a blessing,\n"
	.string "really.$"
