PacifidlogTown_PokemonCenter_1F_MapScripts::
	.byte 0


PacifidlogTown_PokemonCenter_1F_EventScript_Girl::
# 5 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	msgbox PacifidlogTown_PokemonCenter_1F_Text_WhatColorTrainerCard, MSGBOX_NPC
	end


PacifidlogTown_PokemonCenter_1F_EventScript_Nurse::
	end


PacifidlogTown_PokemonCenter_1F_EventScript_OldMan::
# 14 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	msgbox PacifidlogTown_PokemonCenter_1F_Text_AncestorsLivedOnBoats, MSGBOX_NPC
	end


PacifidlogTown_PokemonCenter_1F_EventScript_Woman::
# 19 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	msgbox PacifidlogTown_PokemonCenter_1F_Text_OnColonyOfCorsola, MSGBOX_NPC
	end


PacifidlogTown_PokemonCenter_1F_Text_WhatColorTrainerCard::
# 23 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	.string "What color is your TRAINER CARD?\n"
	.string "Mine's copper!$"

PacifidlogTown_PokemonCenter_1F_Text_AncestorsLivedOnBoats::
# 27 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	.string "The ancestors of the people in\n"
	.string "PACIFIDLOG were said to have been\l"
	.string "born on boats and then lived and died\l"
	.string "aboard them.\p"
	.string "I understand that they lived that way\n"
	.string "because they were searching for\l"
	.string "something.$"

PacifidlogTown_PokemonCenter_1F_Text_OnColonyOfCorsola::
# 31 "data/maps/PacifidlogTown_PokemonCenter_1F/scripts.pory"
	.string "PACIFIDLOG TOWN floats on top of\n"
	.string "a colony of CORSOLA.\p"
	.string "If I told you that, would you believe\n"
	.string "me?$"
