FarawayIsland_Entrance_MapScripts::
	.byte 0


FarawayIsland_Entrance_EventScript_ClearWeather::
	end


FarawayIsland_Entrance_EventScript_Sailor::
# 9 "data/maps/FarawayIsland_Entrance/scripts.pory"
	msgbox FarawayIsland_Entrance_Text_SailorReturn, MSGBOX_YESNO
	end


FarawayIsland_Entrance_EventScript_SetCloudsWeather::
	end


FarawayIsland_Entrance_EventScript_Sign::
# 18 "data/maps/FarawayIsland_Entrance/scripts.pory"
	msgbox FarawayIsland_Entrance_Text_Sign, MSGBOX_SIGN
	end

