IndigoPlateau_PokemonCenter_1F_MapScripts::
# 2 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, IndigoPlateau_PokemonCenter_1F_OnTransition
# 3 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


IndigoPlateau_PokemonCenter_1F_Text_GymGuyAdvice::
# 7 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "At the POKéMON LEAGUE, you will face\n"
	.string "the ELITE FOUR all in a row.\p"
	.string "If you lose, you have to start all over\n"
	.string "again!\p"
	.string "This is it! Go for it!$"

IndigoPlateau_PokemonCenter_1F_Text_FaceEliteFourGoodLuck::
# 11 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	.string "From here on, you face the ELITE FOUR\n"
	.string "one by one.\p"
	.string "If you win, a door opens to the next\n"
	.string "TRAINER. Good luck!$"

IndigoPlateau_PokemonCenter_1F_Text_LoreleiIsAbsentClosedForTimeBeing::
# 15 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	.string "I am so sorry, but you've wasted your\n"
	.string "time coming here.\p"
	.string "LORELEI of the ELITE FOUR is absent,\n"
	.string "you see.\p"
	.string "As a result, the POKéMON LEAGUE is\n"
	.string "closed for the time being.$"

IndigoPlateau_PokemonCenter_1F_Text_AgathaWhuppedUs::
# 19 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	.string "AGATHA's GHOST-type POKéMON are\n"
	.string "horrifically terrifying in toughness.\p"
	.string "I took my FIGHTING-type POKéMON and\n"
	.string "raised them to the max.\p"
	.string "I went at AGATHA feeling pretty\n"
	.string "confident, but she whupped us.\p"
	.string "That old lady's also got a really short\n"
	.string "fuse, too.\p"
	.string "It doesn't take anything to get that\n"
	.string "scary lady hollering.$"

IndigoPlateau_PokemonCenter_1F_Text_LancesCousinGymLeaderFarAway::
# 23 "data/maps/IndigoPlateau_PokemonCenter_1F/scripts.pory"
	.string "Maybe becoming an ELITE FOUR member is\n"
	.string "in the blood.\p"
	.string "From what I've heard, LANCE has a\n"
	.string "cousin who's a GYM LEADER\l"
	.string "somewhere far away.$"
