CinnabarIsland_PokemonLab_ExperimentRoom_MapScripts::
	.byte 0


Text_MetronomeTeach::
# 5 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Tch-tch-tch! I'll teach you a nifty\n"
	.string "move.\p"
	.string "Teach it to a POKéMON, and watch the\n"
	.string "fun unfold!\p"
	.string "It's a move called METRONOME. Does it\n"
	.string "strike your fancy?$"

Text_MetronomeDeclined::
# 9 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "I tell you, it's a lot of fun!$"

Text_MetronomeWhichMon::
# 13 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Okay! Which POKéMON should I teach?$"

Text_MetronomeTaught::
# 17 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Tch-tch-tch! That's the sound of a\n"
	.string "METRONOME.\p"
	.string "It tweaks your POKéMON's brain into\n"
	.string "using moves it doesn't even know.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HaveYouAFossilForMe::
# 21 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Hiya!\p"
	.string "I am important doctor. Yes, very much\n"
	.string "so, indeed.\p"
	.string "Here, I study rare POKéMON fossils. All\n"
	.string "the time, I study.\p"
	.string "You! Have you a fossil for me?$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoIsTooBad::
# 25 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "No! Is too bad!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalkJP::
# 29 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "ちょっと　じかん　かかるよ！\p"
	.string "そこらへんを　すこし ブラブラ　してくると　よろしー！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_FossilMonBackToLife::
# 33 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "You late. Where were you?\p"
	.string "Your fossil is back to life! It was\n"
	.string "{STR_VAR_1} like I think!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ReceivedMonFromDoctor::
# 37 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "{PLAYER} received the {STR_VAR_1}\n"
	.string "from the doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_NoRoomForPokemon::
# 41 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "ポケモン　いっぱいで　もてないね！$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_ThatFossilIsOfMonMakeItLiveAgain::
# 45 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Oh! That is {STR_VAR_2}, it is!\p"
	.string "It is fossil of {STR_VAR_1}, a\n"
	.string "POKéMON that is already extinct!\p"
	.string "My Resurrection Machine will make that\n"
	.string "POKéMON live again!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_HandedFossilToWeirdDoctor::
# 49 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "So! You hurry and give me that!\p"
	.string "{FONT_NORMAL}{PLAYER} handed over the\n"
	.string "{STR_VAR_2} to the weird doctor.$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_TakesTimeGoForWalk::
# 53 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "I take a little time! You go for walk a\n"
	.string "little while!$"

CinnabarIsland_PokemonLab_ExperimentRoom_Text_YouComeAgain::
# 57 "data/maps/CinnabarIsland_PokemonLab_ExperimentRoom/scripts.pory"
	.string "Aiyah! You come again!$"
