GoldenrodCity_DepartmentStore_1F_MapScripts::
	.byte 0

GoldenrodCity_DepartmentStore_1F_EventScript_FloorSign::
	msgbox GoldenrodCity_DepartmentStore_1F_Text_FloorSign, MSGBOX_SIGN
	end

GoldenrodCity_DepartmentStore_1F_EventScript_Directory::
	msgbox GoldenrodCity_DepartmentStore_1F_Text_Directory, MSGBOX_SIGN
	end

GoldenrodCity_DepartmentStore_1F_Text_FloorSign::
	.string "1F: SERVICE COUNTER$"

GoldenrodCity_DepartmentStore_1F_Text_Directory::
	.string "1F: SERVICE COUNTER\p"
    .string "2F: TRAINER'S MARKET\p"
    .string "3F: BATTLE COLLECTION\p"
    .string "4F: MEDICINE BOX\p"
    .string "5F: TM CORNER\p"
	.string "6F: TRANQUIL SQUARE\p"
    .string "ROOFTOP LOOKOUT$"
