Route21_North_MapScripts::
	.byte 0


Route21_North_Text_RonaldIntro::
# 5 "data/maps/Route21_North/scripts.pory"
	.string "You want to know if the fish are biting?$"

Route21_North_Text_RonaldDefeat::
# 9 "data/maps/Route21_North/scripts.pory"
	.string "Dang!$"

Route21_North_Text_RonaldPostBattle::
# 13 "data/maps/Route21_North/scripts.pory"
	.string "I can't catch anything good. Not one\n"
	.string "good POKéMON to be had!$"

Route21_North_Text_WadeIntro::
# 17 "data/maps/Route21_North/scripts.pory"
	.string "I got a big haul! Wanna go for it?$"

Route21_North_Text_WadeDefeat::
# 21 "data/maps/Route21_North/scripts.pory"
	.string "Heheh, MAGIKARP just don't make the\n"
	.string "grade, do they?$"

Route21_North_Text_WadePostBattle::
# 25 "data/maps/Route21_North/scripts.pory"
	.string "I seem to only catch MAGIKARP!$"

Route21_North_Text_SpencerIntro::
# 29 "data/maps/Route21_North/scripts.pory"
	.string "The sea cleanses my body and soul!$"

Route21_North_Text_SpencerDefeat::
# 33 "data/maps/Route21_North/scripts.pory"
	.string "Ayah!$"

Route21_North_Text_SpencerPostBattle::
# 37 "data/maps/Route21_North/scripts.pory"
	.string "The sea is great and all, but I like the\n"
	.string "mountains, too.$"

Route21_North_Text_CueBallIntro::
# 41 "data/maps/Route21_North/scripts.pory"
	.string "おれだって　たまには およぎに　くるぜ！$"

Route21_North_Text_CueBallDefeat::
# 45 "data/maps/Route21_North/scripts.pory"
	.string "ぐわわ！$"

Route21_North_Text_CueBallPostBattle::
# 49 "data/maps/Route21_North/scripts.pory"
	.string "うきやすそう　だと？ うるせー　おおきな　おせわだッ！$"
