MossdeepCity_House2_MapScripts::
	.byte 0


MossdeepCity_House2_EventScript_Man::
# 5 "data/maps/MossdeepCity_House2/scripts.pory"
	msgbox MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree, MSGBOX_NPC
	end


MossdeepCity_House2_EventScript_Twin::
# 10 "data/maps/MossdeepCity_House2/scripts.pory"
	msgbox MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth, MSGBOX_NPC
	end


MossdeepCity_House2_EventScript_Wingull::
# 15 "data/maps/MossdeepCity_House2/scripts.pory"
	msgbox MossdeepCity_House2_Text_Wingull, MSGBOX_DEFAULT
	end


MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth::
# 19 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "Even though I can't see my friend in\n"
	.string "FORTREE, my POKéMON carries MAIL\l"
	.string "back and forth for us.\p"
	.string "I'm not lonesome, even though we're\n"
	.string "apart.$"

MossdeepCity_House2_Text_Wingull::
# 23 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "WINGULL: Pihyoh!$"

MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree::
# 27 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "My little sister exchanges MAIL with\n"
	.string "her boyfriend in FORTREE.\p"
	.string "I don't envy her one bit at all.$"
