MossdeepCity_House2_MapScripts::
	.byte 0


MossdeepCity_House2_MapScripts::
	return


MossdeepCity_House2_Text_SisterMailsBoyfriendInFortree::
# 8 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "My little sister exchanges MAIL with\n"
	.string "her boyfriend in FORTREE.\p"
	.string "I don't envy her one bit at all.$"

MossdeepCity_House2_Text_PokemonCarriesMailBackAndForth::
# 12 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "Even though I can't see my friend in\n"
	.string "FORTREE, my POKéMON carries MAIL\l"
	.string "back and forth for us.\p"
	.string "I'm not lonesome, even though we're\n"
	.string "apart.$"

MossdeepCity_House2_Text_Wingull::
# 16 "data/maps/MossdeepCity_House2/scripts.pory"
	.string "WINGULL: Pihyoh!$"
