AbandonedShip_Corridors_1F_MapScripts::
	.byte 0


AbandonedShip_Corridors_1F_MapScripts::
	return


AbandonedShip_Corridors_1F_Text_CharlieIntro::
# 8 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "What's so funny about having my inner\n"
	.string "tube aboard the ship?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat::
# 12 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "Whoa, you overwhelmed me!$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle::
# 16 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "It's not easy throwing POKé BALLS while\n"
	.string "hanging on to an inner tube!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere::
# 20 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "Isn't it fun here? I get excited just\n"
	.string "being here!$"
