AbandonedShip_Corridors_1F_MapScripts::
	.byte 0


AbandonedShip_Corridors_1F_Text_CharlieIntro::
# 5 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "What's so funny about having my inner\n"
	.string "tube aboard the ship?$"

AbandonedShip_Corridors_1F_Text_CharlieDefeat::
# 9 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "Whoa, you overwhelmed me!$"

AbandonedShip_Corridors_1F_Text_CharliePostBattle::
# 13 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "It's not easy throwing POK BALLS while\n"
	.string "hanging on to an inner tube!$"

AbandonedShip_Corridors_1F_Text_IsntItFunHere::
# 17 "data/maps/AbandonedShip_Corridors_1F/scripts.pory"
	.string "Isn't it fun here? I get excited just\n"
	.string "being here!$"
