MagmaHideout_2F_2R_MapScripts::
	.byte 0


MagmaHideout_2F_2R_EventScript_Grunt15::
# 5 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_15, MagmaHideout_2F_2R_Text_Grunt15Intro, MagmaHideout_2F_2R_Text_Grunt15Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt15PostBattle
	return


MagmaHideout_2F_2R_EventScript_Grunt6::
# 10 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_6, MagmaHideout_2F_2R_Text_Grunt6Intro, MagmaHideout_2F_2R_Text_Grunt6Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt6PostBattle
	return


MagmaHideout_2F_2R_EventScript_Grunt7::
# 15 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_7, MagmaHideout_2F_2R_Text_Grunt7Intro, MagmaHideout_2F_2R_Text_Grunt7Defeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt7PostBattle
	return


MagmaHideout_2F_2R_EventScript_Grunt8::
# 20 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_8, MagmaHideout_2F_2R_Text_Grunt8Intro, MagmaHideout_2F_2R_Text_Grunt8Defeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	msgbox MagmaHideout_2F_2R_Text_Grunt8PostBattle
	return


MagmaHideout_2F_2R_Text_Grunt15Defeat::
# 26 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt15Defeat$"

MagmaHideout_2F_2R_Text_Grunt15Intro::
# 30 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt15Intro$"

MagmaHideout_2F_2R_Text_Grunt15PostBattle::
# 34 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt15PostBattle$"

MagmaHideout_2F_2R_Text_Grunt6Defeat::
# 38 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt6Defeat$"

MagmaHideout_2F_2R_Text_Grunt6Intro::
# 42 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt6Intro$"

MagmaHideout_2F_2R_Text_Grunt6PostBattle::
# 46 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt6PostBattle$"

MagmaHideout_2F_2R_Text_Grunt7Defeat::
# 50 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt7Defeat$"

MagmaHideout_2F_2R_Text_Grunt7Intro::
# 54 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt7Intro$"

MagmaHideout_2F_2R_Text_Grunt7PostBattle::
# 58 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt7PostBattle$"

MagmaHideout_2F_2R_Text_Grunt8Defeat::
# 62 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt8Defeat$"

MagmaHideout_2F_2R_Text_Grunt8Intro::
# 66 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt8Intro$"

MagmaHideout_2F_2R_Text_Grunt8PostBattle::
# 70 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_2F_2R_Text_Grunt8PostBattle$"
