MagmaHideout_2F_2R_MapScripts::
	.byte 0


MagmaHideout_2F_2R_MapScripts::
	return


MagmaHideout_2F_2R_Text_Grunt15Intro::
# 8 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "I don't have a bone to pick with you. I'm\n"
	.string "just following orders!$"

MagmaHideout_2F_2R_Text_Grunt15Defeat::
# 12 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "I may have lost, but…$"

MagmaHideout_2F_2R_Text_Grunt15PostBattle::
# 16 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "We dug up something beyond belief! And,\n"
	.string "we got the BLUE ORB!\p"
	.string "All that's left is for our leader to…\n"
	.string "Fufufu… Fwahahaha!$"

MagmaHideout_2F_2R_Text_Grunt6Intro::
# 20 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "I can't stand heat. Maybe I should've\n"
	.string "joined TEAM AQUA instead…$"

MagmaHideout_2F_2R_Text_Grunt6Defeat::
# 24 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Yeah, I really may not be right for TEAM\n"
	.string "MAGMA…$"

MagmaHideout_2F_2R_Text_Grunt6PostBattle::
# 28 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "Don't you get lonely for the sea being\n"
	.string "in a place like this?$"

MagmaHideout_2F_2R_Text_Grunt7Intro::
# 32 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "You can hear tremors here sometimes.\p"
	.string "Could it be the volcano rattling? Or is\n"
	.string "it GROU…\p"
	.string "Whoops! No, no, never mind!$"

MagmaHideout_2F_2R_Text_Grunt7Defeat::
# 36 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "You're a fiery battler. Just like a\n"
	.string "volcano!$"

MagmaHideout_2F_2R_Text_Grunt7PostBattle::
# 40 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "You just happened to win this time, but\n"
	.string "that doesn't matter.\p"
	.string "TEAM MAGMA's goal is about to be\n"
	.string "reached!$"

MagmaHideout_2F_2R_Text_Grunt8Intro::
# 44 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "One of our guys was freaking out that\n"
	.string "he lost his MAGMA EMBLEM…\p"
	.string "Wait a minute! Was it you who found it?$"

MagmaHideout_2F_2R_Text_Grunt8Defeat::
# 48 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "I'm having trouble believing this…$"

MagmaHideout_2F_2R_Text_Grunt8PostBattle::
# 52 "data/maps/MagmaHideout_2F_2R/scripts.pory"
	.string "I'm getting this feeling that our plan\n"
	.string "is going to end in failure…$"
