SeafloorCavern_Room4_MapScripts::
	.byte 0


SeafloorCavern_Room4_MapScripts::
	return


SeafloorCavern_Room4_Text_Grunt3Intro::
# 8 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Who are you? Where did you come in\n"
	.string "from?$"

SeafloorCavern_Room4_Text_Grunt3Defeat::
# 12 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Lost it…$"

SeafloorCavern_Room4_Text_Grunt3PostBattle::
# 16 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "I can't find the way out!\p"
	.string "I'm not afraid. Don't get me wrong!$"

SeafloorCavern_Room4_Text_Grunt4Intro::
# 20 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Who are you? Where do you think you're\n"
	.string "going?$"

SeafloorCavern_Room4_Text_Grunt4Defeat::
# 24 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "I failed to win!$"

SeafloorCavern_Room4_Text_Grunt4PostBattle::
# 28 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "My partner forgot the map in that\n"
	.string "submarine!\p"
	.string "How's that for being useless?$"
