SeafloorCavern_Room4_MapScripts::
	.byte 0


SeafloorCavern_Room4_EventScript_Grunt3::
# 5 "data/maps/SeafloorCavern_Room4/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_SEAFLOOR_CAVERN_3, SeafloorCavern_Room4_Text_Grunt3Intro, SeafloorCavern_Room4_Text_Grunt3Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/SeafloorCavern_Room4/scripts.pory"
	msgbox SeafloorCavern_Room4_Text_Grunt3PostBattle
	return


SeafloorCavern_Room4_EventScript_Grunt4::
# 10 "data/maps/SeafloorCavern_Room4/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_SEAFLOOR_CAVERN_4, SeafloorCavern_Room4_Text_Grunt4Intro, SeafloorCavern_Room4_Text_Grunt4Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/SeafloorCavern_Room4/scripts.pory"
	msgbox SeafloorCavern_Room4_Text_Grunt4PostBattle
	return


SeafloorCavern_Room4_Text_Grunt3Defeat::
# 16 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt3Defeat$"

SeafloorCavern_Room4_Text_Grunt3Intro::
# 20 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt3Intro$"

SeafloorCavern_Room4_Text_Grunt3PostBattle::
# 24 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt3PostBattle$"

SeafloorCavern_Room4_Text_Grunt4Defeat::
# 28 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt4Defeat$"

SeafloorCavern_Room4_Text_Grunt4Intro::
# 32 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt4Intro$"

SeafloorCavern_Room4_Text_Grunt4PostBattle::
# 36 "data/maps/SeafloorCavern_Room4/scripts.pory"
	.string "Placeholder text for\n"
	.string "SeafloorCavern_Room4_Text_Grunt4PostBattle$"
