SafariZone_East_MapScripts::
	.byte 0


SafariZone_East_Text_RestHouse::
# 5 "data/maps/SafariZone_East/scripts.pory"
	.string "REST HOUSE$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
# 9 "data/maps/SafariZone_East/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The remaining time declines only while\n"
	.string "you walk.$"

SafariZone_East_Text_AreaSign::
# 13 "data/maps/SafariZone_East/scripts.pory"
	.string "AREA 1 WEST: CENTER AREA$"
