SafariZone_East_MapScripts::
	.byte 0


SafariZone_East_EventScript_AreaSign::
# 5 "data/maps/SafariZone_East/scripts.pory"
	msgbox SafariZone_East_Text_AreaSign, MSGBOX_SIGN
	end


SafariZone_East_EventScript_ItemFullRestore::
	end


SafariZone_East_EventScript_ItemLeafStone::
	end


SafariZone_East_EventScript_ItemMaxPotion::
	end


SafariZone_East_EventScript_ItemTM11::
	end


SafariZone_East_EventScript_RestHouseSign::
# 26 "data/maps/SafariZone_East/scripts.pory"
	msgbox SafariZone_East_Text_RestHouse, MSGBOX_SIGN
	end


SafariZone_East_EventScript_TrainerTips::
# 31 "data/maps/SafariZone_East/scripts.pory"
	msgbox SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk, MSGBOX_SIGN
	end


SafariZone_East_Text_RestHouse::
# 36 "data/maps/SafariZone_East/scripts.pory"
	.string "REST HOUSE$"

SafariZone_East_Text_AreaSign::
# 40 "data/maps/SafariZone_East/scripts.pory"
	.string "AREA 1 WEST: CENTER AREA$"

SafariZone_East_Text_TimeDeclinesOnlyWhileYouWalk::
# 44 "data/maps/SafariZone_East/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The remaining time declines only while\n"
	.string "you walk.$"
