PetalburgCity_Mart_MapScripts::
	.byte 0


PetalburgCity_Mart_Text_WeakWillGrowStronger::
# 5 "data/maps/PetalburgCity_Mart/scripts.pory"
	.string "Even if a POKéMON is weak now, it will\n"
	.string "grow stronger.\p"
	.string "The most important thing is love! Love\n"
	.string "for your POKéMON!$"

PetalburgCity_Mart_Text_RepelIsUseful::
# 9 "data/maps/PetalburgCity_Mart/scripts.pory"
	.string "Do you use REPEL? It keeps POKéMON\n"
	.string "away, so it's\l"
	.string "useful when you're in a hurry.$"

PetalburgCity_Mart_Text_TakeSomeAntidotesWithYou::
# 13 "data/maps/PetalburgCity_Mart/scripts.pory"
	.string "Do you have any ANTIDOTES with you?\p"
	.string "If you walk around with a poisoned\n"
	.string "POKéMON, it will lose HP until it faints.\l"
	.string "Take some ANTIDOTES with you.$"
