RustboroCity_Flat2_2F_MapScripts::
	.byte 0


RustboroCity_Flat2_2F_EventScript_NinjaBoy::
	end


RustboroCity_Flat2_2F_EventScript_OldMan::
# 9 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	msgbox RustboroCity_Flat2_2F_Text_DevonWasTinyInOldDays, MSGBOX_NPC
	end


RustboroCity_Flat2_2F_Text_GoingToWorkAtDevonToo::
# 13 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	.string "My daddy's working at the CORPORATION.\p"
	.string "When I grow up, I'm going to work for\n"
	.string "DEVON, too.$"

RustboroCity_Flat2_2F_Text_DevonWasTinyInOldDays::
# 17 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	.string "Way back in the old days, DEVON was just\n"
	.string "a teeny, tiny company.$"
