RustboroCity_Flat2_2F_MapScripts::
	.byte 0


RustboroCity_Flat2_2F_Text_DevonWasTinyInOldDays::
# 5 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	.string "Way back in the old days, DEVON was just\n"
	.string "a teeny, tiny company.$"

RustboroCity_Flat2_2F_Text_MyDaddyMadeThisYouCanHaveIt::
# 9 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	.string "My daddy's working at the CORPORATION.\p"
	.string "My daddy made this! But I can't use it,\n"
	.string "so you can have it.$"

RustboroCity_Flat2_2F_Text_GoingToWorkAtDevonToo::
# 13 "data/maps/RustboroCity_Flat2_2F/scripts.pory"
	.string "My daddy's working at the CORPORATION.\p"
	.string "When I grow up, I'm going to work for\n"
	.string "DEVON, too.$"
