Route15_MapScripts::
	.byte 0


Route15_Text_KindraIntro::
# 5 "data/maps/Route15/scripts.pory"
	.string "I just got some POKéMON in trades. Can\n"
	.string "I try them out on you?$"

Route15_Text_KindraDefeat::
# 9 "data/maps/Route15/scripts.pory"
	.string "Not good enough!$"

Route15_Text_KindraPostBattle::
# 13 "data/maps/Route15/scripts.pory"
	.string "You can't change the nickname of any\n"
	.string "POKéMON you get in a trade.\p"
	.string "Only the Original TRAINER can get the\n"
	.string "nickname changed.$"

Route15_Text_BeckyIntro::
# 17 "data/maps/Route15/scripts.pory"
	.string "You look gentle, so I think I can beat\n"
	.string "you.\p"
	.string "I'll give it a go!$"

Route15_Text_BeckyDefeat::
# 21 "data/maps/Route15/scripts.pory"
	.string "No, wrong!$"

Route15_Text_BeckyPostBattle::
# 25 "data/maps/Route15/scripts.pory"
	.string "I'm afraid of BIKERS. They look so ugly\n"
	.string "and mean!$"

Route15_Text_EdwinIntro::
# 29 "data/maps/Route15/scripts.pory"
	.string "When I whistle, I can summon bird\n"
	.string "POKéMON.$"

Route15_Text_EdwinDefeat::
# 33 "data/maps/Route15/scripts.pory"
	.string "Ow! That's tragic!$"

Route15_Text_EdwinPostBattle::
# 37 "data/maps/Route15/scripts.pory"
	.string "Maybe I'm not cut out for battles. I'm\n"
	.string "not the right type, I guess.$"

Route15_Text_ChesterIntro::
# 41 "data/maps/Route15/scripts.pory"
	.string "Hmm? My birds are shivering! You're\n"
	.string "good, aren't you?$"

Route15_Text_ChesterDefeat::
# 45 "data/maps/Route15/scripts.pory"
	.string "Just as I thought!$"

Route15_Text_ChesterPostBattle::
# 49 "data/maps/Route15/scripts.pory"
	.string "This is so obvious, you should know\n"
	.string "this, but…\p"
	.string "Moves like EARTHQUAKE and FISSURE\n"
	.string "have no effect on bird POKéMON.$"

Route15_Text_GraceIntro::
# 53 "data/maps/Route15/scripts.pory"
	.string "Oh, you're a little cutie! So like a\n"
	.string "darling POKéMON!$"

Route15_Text_GraceDefeat::
# 57 "data/maps/Route15/scripts.pory"
	.string "You looked so cute, too!$"

Route15_Text_GracePostBattle::
# 61 "data/maps/Route15/scripts.pory"
	.string "I forgive you. I can take it.\l"
	.string "I'm a big girl now.$"

Route15_Text_OliviaIntro::
# 65 "data/maps/Route15/scripts.pory"
	.string "I raise POKéMON for protection because\n"
	.string "I live alone.$"

Route15_Text_OliviaDefeat::
# 69 "data/maps/Route15/scripts.pory"
	.string "POKéMON isn't about winning or losing\n"
	.string "for me.$"

Route15_Text_OliviaPostBattle::
# 73 "data/maps/Route15/scripts.pory"
	.string "I love having my POKéMON greet me when\n"
	.string "I get home.\p"
	.string "It's so reassuring.$"

Route15_Text_ErnestIntro::
# 77 "data/maps/Route15/scripts.pory"
	.string "Hey, kid! C'mon! I just got these off\n"
	.string "some loser!$"

Route15_Text_ErnestDefeat::
# 81 "data/maps/Route15/scripts.pory"
	.string "Why not?$"

Route15_Text_ErnestPostBattle::
# 85 "data/maps/Route15/scripts.pory"
	.string "Life's too short. It's cool to live as an\n"
	.string "outlaw.\l"
	.string "TEAM ROCKET RULES!$"

Route15_Text_AlexIntro::
# 89 "data/maps/Route15/scripts.pory"
	.string "Fork over all your cash when you lose to\n"
	.string "me, kid!$"

Route15_Text_AlexDefeat::
# 93 "data/maps/Route15/scripts.pory"
	.string "That can't be true!$"

Route15_Text_AlexPostBattle::
# 97 "data/maps/Route15/scripts.pory"
	.string "I was just joking about the money.\n"
	.string "Don't take me all serious.$"

Route15_Text_CeliaIntro::
# 101 "data/maps/Route15/scripts.pory"
	.string "What's cool and happening? Trading\n"
	.string "POKéMON!$"

Route15_Text_CeliaDefeat::
# 105 "data/maps/Route15/scripts.pory"
	.string "I said trade!$"

Route15_Text_CeliaPostBattle::
# 109 "data/maps/Route15/scripts.pory"
	.string "I trade POKéMON with my friends all the\n"
	.string "time.$"

Route15_Text_YazminIntro::
# 113 "data/maps/Route15/scripts.pory"
	.string "Want to play with my POKéMON?$"

Route15_Text_YazminDefeat::
# 117 "data/maps/Route15/scripts.pory"
	.string "I was too impatient!$"

Route15_Text_YazminPostBattle::
# 121 "data/maps/Route15/scripts.pory"
	.string "I'll go train with weaker people.$"

Route15_Text_RouteSign::
# 125 "data/maps/Route15/scripts.pory"
	.string "ROUTE 15 West to FUCHSIA CITY$"

Route15_Text_MyaIntro::
# 129 "data/maps/Route15/scripts.pory"
	.string "MYA: You're perfect. Help me train my\n"
	.string "little brother?$"

Route15_Text_MyaDefeat::
# 133 "data/maps/Route15/scripts.pory"
	.string "MYA: RON, you have to focus!\n"
	.string "Concentrate on what you're doing!$"

Route15_Text_MyaPostBattle::
# 137 "data/maps/Route15/scripts.pory"
	.string "MYA: Okay, we'll turn it up. I'll add to\n"
	.string "our training menu!$"

Route15_Text_MyaNotEnoughMons::
# 141 "data/maps/Route15/scripts.pory"
	.string "MYA: Do you want to challenge us? You'll\n"
	.string "need two POKéMON, though.$"

Route15_Text_RonIntro::
# 145 "data/maps/Route15/scripts.pory"
	.string "RON: My sister gets scary when we lose.$"

Route15_Text_RonDefeat::
# 149 "data/maps/Route15/scripts.pory"
	.string "RON: Oh, no, no… Sis, I'm sorry!$"

Route15_Text_RonPostBattle::
# 153 "data/maps/Route15/scripts.pory"
	.string "RON: Oh, bleah… I wish I had a nice\n"
	.string "sister…$"

Route15_Text_RonNotEnoughMons::
# 157 "data/maps/Route15/scripts.pory"
	.string "RON: Did you want to battle with my\n"
	.string "sister and me?\p"
	.string "You need two POKéMON, then.$"
