LilycoveCity_House3_MapScripts::
	.byte 0


LilycoveCity_House3_EventScript_GameBoyKid1::
	end


LilycoveCity_House3_EventScript_GameBoyKid2::
	end


LilycoveCity_House3_EventScript_GameBoyKid3::
	end


LilycoveCity_House3_EventScript_GameBoyKid4::
	end


LilycoveCity_House3_EventScript_Man::
# 21 "data/maps/LilycoveCity_House3/scripts.pory"
	msgbox LilycoveCity_House3_Text_HappyToHaveQuadruplets, MSGBOX_DEFAULT
	end


LilycoveCity_House3_EventScript_PokefanF::
# 26 "data/maps/LilycoveCity_House3/scripts.pory"
	msgbox LilycoveCity_House3_Text_LearnFromMasterOfPokeblocks, MSGBOX_YESNO
	end


LilycoveCity_House3_Text_GoingToEnterContest::
# 30 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "I want to brag about how tough my\n"
	.string "POKéMON is, so we're going to enter\l"
	.string "a CONTEST together.$"

LilycoveCity_House3_Text_LearnFromMasterOfPokeblocks::
# 34 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "Oh, my, my! Are you traveling alone?\n"
	.string "But you're so young! Good for you!\p"
	.string "I'm sure my kids could learn a thing\n"
	.string "or two from you!\p"
	.string "Me? I'm a master of {POKEBLOCK}S.\p"
	.string "If I get serious just a little, why,\n"
	.string "I can concoct great {POKEBLOCK}S.\p"
	.string "Would you like to learn from me,\n"
	.string "a master of {POKEBLOCK}S?$"

LilycoveCity_House3_Text_LikeMixingAtRecordCorner::
# 38 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We like mixing stuff at\n"
	.string "the RECORD CORNER.\p"
	.string "But what gets mixed up?$"

LilycoveCity_House3_Text_MakePokeblocksWithBerryBlender::
# 42 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We're going to make super {POKEBLOCK}S\n"
	.string "with a BERRY BLENDER!$"

LilycoveCity_House3_Text_GoingToWinMultiBattles::
# 46 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We're having MULTI BATTLES, but I know\n"
	.string "I'm going to win.$"

LilycoveCity_House3_Text_OhAreYouSure::
# 50 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "Oh? Are you sure?\p"
	.string "You shouldn't always try to do\n"
	.string "everything by yourself, dear!$"

LilycoveCity_House3_Text_HappyToHaveQuadruplets::
# 54 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "When my wife gave birth to quadruplets,\n"
	.string "you bet I was shocked.\p"
	.string "But, now, seeing them play together,\n"
	.string "it makes me happy.$"
