LilycoveCity_House3_MapScripts::
# 2 "data/maps/LilycoveCity_House3/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_House3_OnTransition
	.byte 0


LilycoveCity_House3_MapScripts::
# 6 "data/maps/LilycoveCity_House3/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_House3_OnTransition
	return


LilycoveCity_House3_Text_LearnFromMasterOfPokeblocks::
# 10 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "Oh, my, my! Are you traveling alone? But\n"
	.string "you're so young! Good for you!\p"
	.string "I'm sure my kids could learn a thing or\n"
	.string "two from you!\p"
	.string "Me? I'm a master of {POKEBLOCK}S.\p"
	.string "If I get serious just a little, why, I\n"
	.string "can concoct great {POKEBLOCK}S.\p"
	.string "Would you like to learn from me, a master\n"
	.string "of {POKEBLOCK}S?$"

LilycoveCity_House3_Text_OhAreYouSure::
# 14 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "Oh? Are you sure?\p"
	.string "You shouldn't always try to do\n"
	.string "everything by yourself, dear!$"

LilycoveCity_House3_Text_ExplainPokeblocks::
# 18 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "Oh, good! You're a smart soul! This is a\n"
	.string "bit long, so listen up!\p"
	.string "Are you ready?\p"
	.string "If you look at {POKEBLOCK}S, you should see\n"
	.string "that they are rated on how they feel.\p"
	.string "The lower the feel rating, the better it\n"
	.string "is. Don't forget this!\p"
	.string "A good {POKEBLOCK} has a low feel rating and\n"
	.string "a high level.\p"
	.string "A POKéMON can eat more good {POKEBLOCK}S\n"
	.string "than ordinary ones, too.\p"
	.string "And this is important.\p"
	.string "If you want to make smooth {POKEBLOCK}S,\n"
	.string "use different kinds of BERRIES.\p"
	.string "Don't be stingy--the kinds of BERRIES\n"
	.string "affect the smoothness of {POKEBLOCK}S.\p"
	.string "And another thing.\p"
	.string "The more people blending BERRIES, the\n"
	.string "smoother the {POKEBLOCK}S.\p"
	.string "That's why you should talk to other\n"
	.string "people and make {POKEBLOCK}S together.\p"
	.string "That's about all you need to know to\n"
	.string "make good {POKEBLOCK}S.\p"
	.string "If everyone had POKéMON they love,\n"
	.string "smooth {POKEBLOCK}S, and a loving family,\l"
	.string "the world would be a happier place.\p"
	.string "Don't give up, dear!$"

LilycoveCity_House3_Text_HappyToHaveQuadruplets::
# 22 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "When my wife gave birth to quadruplets,\n"
	.string "you bet I was shocked.\p"
	.string "But, now, seeing them play together, it\n"
	.string "makes me happy.$"

LilycoveCity_House3_Text_GoingToWinMultiBattles::
# 26 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We're having MULTI BATTLES, but I know\n"
	.string "I'm going to win.$"

LilycoveCity_House3_Text_LikeMixingAtRecordCorner::
# 30 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We like mixing stuff at the RECORD\n"
	.string "CORNER.\p"
	.string "But what gets mixed up?$"

LilycoveCity_House3_Text_MakePokeblocksWithBerryBlender::
# 34 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "We're going to make super {POKEBLOCK}S with\n"
	.string "a BERRY BLENDER!$"

LilycoveCity_House3_Text_GoingToEnterContest::
# 38 "data/maps/LilycoveCity_House3/scripts.pory"
	.string "I want to brag about how tough my\n"
	.string "POKéMON is, so we're going to enter\l"
	.string "a CONTEST together.$"
