CeladonCity_GameCorner_MapScripts::
# 2 "data/maps/CeladonCity_GameCorner/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CeladonCity_GameCorner_OnLoad
	.byte 0


CeladonCity_GameCorner_Text_CanExchangeCoinsNextDoor::
# 6 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Welcome!\p"
	.string "You can exchange your COINS for\n"
	.string "fabulous prizes next door.$"

CeladonCity_GameCorner_Text_WelcomeBuySomeCoins::
# 10 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Welcome to ROCKET GAME CORNER!\p"
	.string "Do you need some game COINS? Would you\n"
	.string "like to buy some?$"

CeladonCity_GameCorner_Text_ComePlaySometime::
# 14 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "No? Please come play sometime!$"

CeladonCity_GameCorner_Text_SorryDontHaveCoinCase::
# 18 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Oh, I'm sorry. You don't have a COIN\n"
	.string "CASE.$"

CeladonCity_GameCorner_Text_CoinCaseIsFull::
# 22 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Whoops! Your COIN CASE is full.$"

CeladonCity_GameCorner_Text_CantAffordCoins::
# 26 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "You can't afford the COINS.$"

CeladonCity_GameCorner_Text_HereAreYourCoins::
# 30 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Thank you. Here are your COINS!$"

CeladonCity_GameCorner_Text_RumoredTeamRocketRunsThisPlace::
# 34 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Keep this quiet.\p"
	.string "It's rumored that this place is run by\n"
	.string "TEAM ROCKET.$"

CeladonCity_GameCorner_Text_ThinkMachinesHaveDifferentOdds::
# 38 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "I think these machines have different\n"
	.string "odds.$"

CeladonCity_GameCorner_Text_DoYouWantToPlay::
# 42 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Kid, do you want to play?$"

CeladonCity_GameCorner_Text_Received10CoinsFromMan::
# 46 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "{PLAYER} received 10 COINS from the\n"
	.string "man.$"

CeladonCity_GameCorner_Text_DontNeedMyCoins::
# 50 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "You don't need my COINS!$"

CeladonCity_GameCorner_Text_WinsComeAndGo::
# 54 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Wins seem to come and go. Nothing's a\n"
	.string "sure thing.$"

CeladonCity_GameCorner_Text_WinOrLoseItsOnlyLuck::
# 58 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "These slot games Win or lose, it's only\n"
	.string "by luck.$"

CeladonCity_GameCorner_Text_GymGuyAdvice::
# 62 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Hey!\p"
	.string "You have better things to do, champ in\n"
	.string "the making!\p"
	.string "CELADON GYM's LEADER is ERIKA.\p"
	.string "She is a user of GRASS-type POKMON, and\n"
	.string "at one with nature.\p"
	.string "She might appear docile because of her\n"
	.string "flower arranging\p"
	.string "But she's not one to be taken lightly!$"

CeladonCity_GameCorner_Text_RareMonsForCoins::
# 66 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "They offer rare POKMON that can be\n"
	.string "exchanged for your COINS.\p"
	.string "But, I just can't seem to win!$"

CeladonCity_GameCorner_Text_SoEasyToGetHooked::
# 70 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Games are scary! It's so easy to get\n"
	.string "hooked!$"

CeladonCity_GameCorner_Text_WantSomeCoins::
# 74 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "What's up? Want some COINS?$"

CeladonCity_GameCorner_Text_Received20CoinsFromNiceGuy::
# 78 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "{PLAYER} received 20 COINS from the\n"
	.string "nice guy.$"

CeladonCity_GameCorner_Text_YouHaveLotsOfCoins::
# 82 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "You have lots of COINS!$"

CeladonCity_GameCorner_Text_NeedMoreCoinsForMonIWant::
# 86 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Darn! I need more COINS for the POKMON\n"
	.string "I want!$"

CeladonCity_GameCorner_Text_HereAreSomeCoinsShoo::
# 90 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Hey, what? You're throwing me off! Here\n"
	.string "are some COINS, so shoo!$"

CeladonCity_GameCorner_Text_Received20CoinsFromMan::
# 94 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "{PLAYER} received 20 COINS from the\n"
	.string "man.$"

CeladonCity_GameCorner_Text_YouveGotPlentyCoins::
# 98 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "You've got plenty of your own COINS!$"

CeladonCity_GameCorner_Text_WatchReelsClosely::
# 102 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "The trick is to watch the reels closely.$"

CeladonCity_GameCorner_Text_GruntIntro::
# 106 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "I'm guarding this poster! Go away, or\n"
	.string "else!$"

CeladonCity_GameCorner_Text_GruntDefeat::
# 110 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Dang!$"

CeladonCity_GameCorner_Text_GruntPostBattle::
# 114 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "The TEAM ROCKET HIDEOUT might be\n"
	.string "discovered!\p"
	.string "I better tell BOSS!$"

CeladonCity_GameCorner_Text_SwitchBehindPosterPushIt::
# 118 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Hey!\p"
	.string "A switch behind the poster!? Let's push\n"
	.string "it!$"

CeladonCity_GameCorner_Text_CoinCaseIsRequired::
# 122 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "A COIN CASE is required$"

CeladonCity_GameCorner_Text_DontHaveCoinCase::
# 126 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Oops! Don't have the COIN CASE!$"

CeladonCity_GameCorner_Text_SlotMachineWantToPlay::
# 130 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "A slot machine! Want to play?$"

CeladonCity_GameCorner_Text_OutOfOrder::
# 134 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "OUT OF ORDER This is broken.$"

CeladonCity_GameCorner_Text_OutToLunch::
# 138 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "OUT TO LUNCH This is reserved.$"

CeladonCity_GameCorner_Text_SomeonesKeys::
# 142 "data/maps/CeladonCity_GameCorner/scripts.pory"
	.string "Someone's keys! They'll be back.$"
