SlateportCity_BattleTentCorridor_MapScripts::
# 2 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SlateportCity_BattleTentCorridor_OnFrame
# 3 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SlateportCity_BattleTentCorridor_OnWarp
	.byte 0


SlateportCity_ContestHall_Text_AdviceForContests::
# 7 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "Want a tasty little bit of advice for\n"
	.string "CONTESTS?\p"
	.string "Using a certain move after another\n"
	.string "certain kind of move sometimes gets\l"
	.string "you extra attention.\p"
	.string "If you know what you're doing, you can\n"
	.string "score big in appeal.\p"
	.string "Of course, your opponents might try\n"
	.string "disrupting your POKéMON's showing.$"

SlateportCity_ContestHall_Text_MyPapaIsContestJudge::
# 11 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "My papa, he's a CONTEST JUDGE.\p"
	.string "I wonder what I should be when I grow\n"
	.string "up, a JUDGE or a GYM LEADER?$"

SlateportCity_ContestHall_Text_ImLikeMajorlyCheesed::
# 15 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "Hey, man, I'm like majorly cheesed, you\n"
	.string "know. Like, you know, I just\l"
	.string "wanted to know why my POKéMON\l"
	.string "never won, you know, like, hey?\p"
	.string "So, like, I gave the JUDGE my two cents,\n"
	.string "you know, they're free.\p"
	.string "And he wouldn't hear me out, like, hey!\n"
	.string "So, like, total bummer, man!\p"
	.string "Hey, like, you! Zip it, you know? Just,\n"
	.string "you know, take this!$"

SlateportCity_ContestHall_Text_ExplainTorment::
# 19 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "That's, like, TM41, you know? Hey, it's\n"
	.string "TORMENT, you hearing me?\p"
	.string "Like, it won't let the other guy use the\n"
	.string "same move twice in a row, see?\p"
	.string "Hey, now, you listen here, like, I'm not\n"
	.string "laying a torment on you!$"

SlateportCity_ContestHall_Text_MCStepUpTakePartInContest::
# 23 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "MC: Oh, my, my! Now isn't that a dandy of\n"
	.string "a POKéMON?\p"
	.string "Please! Do step right up and take part\n"
	.string "in our splendid CONTESTS!\p"
	.string "You'll do well! I'm sure of it! My eyes\n"
	.string "have never failed me!$"

SlateportCity_ContestHall_Text_JudgeWouldntDoToMissContest::
# 27 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "JUDGE: Well, hello there! I see that\n"
	.string "you're a TRAINER!\p"
	.string "Then, it just wouldn't do for you to miss\n"
	.string "a POKéMON CONTEST!\p"
	.string "Get a CONTEST PASS in VERDANTURF CITY\n"
	.string "and enter anytime!$"

SlateportCity_ContestHall_Text_ItsAppealTime::
# 31 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "It's appeal time! What should I lead\n"
	.string "with?$"

SlateportCity_ContestHall_Text_DidntPayAttentionToAppeal::
# 35 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "They didn't pay much attention to my\n"
	.string "POKéMON's appeal…\p"
	.string "Humph, that JUDGE, he doesn't know a\n"
	.string "good thing when he sees it.$"

SlateportCity_ContestHall_Text_RewardWithSageAdvice::
# 39 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "Oh, hi! You must be a serious fan to get\n"
	.string "this close to the action.\p"
	.string "I'll reward your enthusiasm with this\n"
	.string "sage advice.\p"
	.string "If a move goes over really well, the\n"
	.string "audience will get excited.\p"
	.string "The POKéMON that makes its appeal\n"
	.string "right when everyone's excited…\p"
	.string "Well, you'd think something good has to\n"
	.string "happen!$"

SlateportCity_ContestHall_Text_MoreFreakedOutThanMon::
# 43 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "I can't do this! I'm more freaked out\n"
	.string "than my POKéMON.\p"
	.string "I'm shivering and my heart is racing!$"

SlateportCity_ContestHall_Text_BattleAndContestAlike::
# 47 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "A battle and a CONTEST aren't the same,\n"
	.string "but they are alike, too.\p"
	.string "You need to work hard and believe in the\n"
	.string "POKéMON you've raised.$"

SlateportCity_ContestHall_Text_MonLooksOnTopOfGame::
# 51 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "That POKéMON looks like it's on top of\n"
	.string "its game, huh?\p"
	.string "A POKéMON that does good in the\n"
	.string "secondary judging seems to be more\l"
	.string "relaxed when it's doing appeals.$"

SlateportCity_ContestHall_Text_MyMonBetterThanThatLot::
# 55 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "Will you look at that sorry sight?\p"
	.string "Heh, my POKéMON's absolutely better\n"
	.string "than that lot!$"

SlateportCity_ContestHall_Text_GetUrgeToMoveWithMon::
# 59 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "Don't you get the urge to move with\n"
	.string "POKéMON if they're putting on an\l"
	.string "energetic appeal?$"

SlateportCity_ContestHall_Text_HyperRankStage::
# 63 "data/maps/SlateportCity_BattleTentCorridor/scripts.pory"
	.string "POKéMON CONTESTS HYPER RANK STAGE!$"
