SixIsland_WaterPath_MapScripts::
	.byte 0


SixIsland_WaterPath_Text_RoseIntro::
# 5 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "I let a pleasant breeze lead me all the\n"
	.string "way here.$"

SixIsland_WaterPath_Text_RoseDefeat::
# 9 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Giggle… You're so cute when you're\n"
	.string "determined.$"

SixIsland_WaterPath_Text_RosePostBattle::
# 13 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "I want to go to the woods over there,\n"
	.string "but…\p"
	.string "There are lots of BUG POKéMON. They\n"
	.string "scare me a little.$"

SixIsland_WaterPath_Text_EdwardIntro::
# 17 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "I'm practicing in secret so no one can\n"
	.string "see me.$"

SixIsland_WaterPath_Text_EdwardDefeat::
# 21 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Nobody saw me losing, right?$"

SixIsland_WaterPath_Text_EdwardPostBattle::
# 25 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "As a performer, I don't want people to\n"
	.string "know about the effort I put in.$"

SixIsland_WaterPath_Text_SamirIntro::
# 29 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "What, you're suggesting that you're\n"
	.string "sick of seeing SWIMMERS like me?\p"
	.string "Aww, don't be hatin'!$"

SixIsland_WaterPath_Text_SamirDefeat::
# 33 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Oh, no, no, no.$"

SixIsland_WaterPath_Text_SamirPostBattle::
# 37 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "I couldn't lift the stigma of being a\n"
	.string "SWIMMER…$"

SixIsland_WaterPath_Text_DeniseIntro::
# 41 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "My boyfriend's always busy, so I come\n"
	.string "swimming by myself.$"

SixIsland_WaterPath_Text_DeniseDefeat::
# 45 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Awww, I knew this would happen!$"

SixIsland_WaterPath_Text_DenisePostBattle::
# 49 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "When I can't be with my boyfriend, I\n"
	.string "spend time with the POKéMON he\l"
	.string "gave me.$"

SixIsland_WaterPath_Text_EarlIntro::
# 53 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Tell me, where are the mountains around\n"
	.string "these parts?$"

SixIsland_WaterPath_Text_EarlDefeat::
# 57 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "I lost my way while I was busy battling!$"

SixIsland_WaterPath_Text_EarlPostBattle::
# 61 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Aren't there any mountains around\n"
	.string "these parts?$"

SixIsland_WaterPath_Text_MiuIntro::
# 65 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIU: Hello, POKéMON! It's time to play!$"

SixIsland_WaterPath_Text_MiuDefeat::
# 69 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIU: Oh, no! Mommy!$"

SixIsland_WaterPath_Text_MiuPostBattle::
# 73 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIU: It makes me all sad inside when we\n"
	.string "lose…$"

SixIsland_WaterPath_Text_MiuNotEnoughMons::
# 77 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIU: MIA and I are TWINS. We want to\n"
	.string "battle together.$"

SixIsland_WaterPath_Text_MiaIntro::
# 81 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIA: Hello, POKéMON! It's time to\n"
	.string "battle!$"

SixIsland_WaterPath_Text_MiaDefeat::
# 85 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIA: You're mean! You're bad for\n"
	.string "winning!$"

SixIsland_WaterPath_Text_MiaPostBattle::
# 89 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIA: Ohh… I'm sorry, my POKéMON…$"

SixIsland_WaterPath_Text_MiaNotEnoughMons::
# 93 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "MIA: Oh, you only have one POKéMON?\p"
	.string "Don't you feel lonesome?$"

SixIsland_WaterPath_Text_WantedUltimateHorn::
# 97 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Wanted! The Ultimate Horn!$"

SixIsland_WaterPath_Text_RouteSign::
# 101 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "WATER PATH Leads to RUIN VALLEY$"
