SixIsland_WaterPath_MapScripts::
	.byte 0


SixIsland_WaterPath_EventScript_HornWantedSign::
# 5 "data/maps/SixIsland_WaterPath/scripts.pory"
	msgbox SixIsland_WaterPath_Text_WantedUltimateHorn, MSGBOX_SIGN
	end


SixIsland_WaterPath_EventScript_RouteSign::
# 10 "data/maps/SixIsland_WaterPath/scripts.pory"
	msgbox SixIsland_WaterPath_Text_RouteSign, MSGBOX_SIGN
	end


SixIsland_WaterPath_Text_WantedUltimateHorn::
# 15 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "Wanted! The Ultimate Horn!$"

SixIsland_WaterPath_Text_RouteSign::
# 19 "data/maps/SixIsland_WaterPath/scripts.pory"
	.string "WATER PATH Leads to RUIN VALLEY$"
