Route18_EastEntrance_1F_MapScripts::
# 2 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route18_EastEntrance_1F_OnTransition
	.byte 0


Route18_EastEntrance_1F_Text_NeedBicycleForCyclingRoad::
# 6 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	.string "You need a BICYCLE to go out on\n"
	.string "CYCLING ROAD!$"

Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere::
# 10 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	.string "CYCLING ROAD is all uphill from here.$"

Route18_EastEntrance_1F_Text_ExcuseMe::
# 14 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	.string "Excuse me!$"
