Route18_EastEntrance_1F_MapScripts::
	.byte 0


Route18_EastEntrance_1F_EventScript_Guard::
# 5 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	msgbox Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere, MSGBOX_NPC
	end


Route18_EastEntrance_1F_EventScript_NeedBikeTriggerBottom::
	end


Route18_EastEntrance_1F_EventScript_NeedBikeTriggerMid::
	end


Route18_EastEntrance_1F_EventScript_NeedBikeTriggerMidBottom::
	end


Route18_EastEntrance_1F_EventScript_NeedBikeTriggerMidTop::
	end


Route18_EastEntrance_1F_EventScript_NeedBikeTriggerTop::
	end


Route18_EastEntrance_1F_Text_CyclingRoadAllUphillFromHere::
# 30 "data/maps/Route18_EastEntrance_1F/scripts.pory"
	.string "CYCLING ROAD is all uphill from\n"
	.string "here.$"
