CinnabarIsland_MapScripts::
# 2 "data/maps/CinnabarIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CinnabarIsland_OnTransition
# 3 "data/maps/CinnabarIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CinnabarIsland_OnFrame
	.byte 0


CinnabarIsland_Text_DoorIsLocked::
# 7 "data/maps/CinnabarIsland/scripts.pory"
	.string "The door is locked$"

CinnabarIsland_Text_BlaineLivedHereSinceBeforeLab::
# 11 "data/maps/CinnabarIsland/scripts.pory"
	.string "CINNABAR GYM's BLAINE is quite the odd\n"
	.string "fellow.\p"
	.string "He's lived on the island since way\n"
	.string "before the LAB was built.$"

CinnabarIsland_Text_ScientistsExperimentInMansion::
# 15 "data/maps/CinnabarIsland/scripts.pory"
	.string "Scientists conduct experiments in the\n"
	.string "burned-out building.\p"
	.string "You know, the one they call the POKMON\n"
	.string "MANSION.$"

CinnabarIsland_Text_IslandSign::
# 19 "data/maps/CinnabarIsland/scripts.pory"
	.string "CINNABAR ISLAND The Fiery Town of\n"
	.string "Burning Desire$"

CinnabarIsland_Text_PokemonLab::
# 23 "data/maps/CinnabarIsland/scripts.pory"
	.string "POKMON LAB$"

CinnabarIsland_Text_GymSign::
# 27 "data/maps/CinnabarIsland/scripts.pory"
	.string "CINNABAR ISLAND POKMON GYM LEADER:\n"
	.string "BLAINE\l"
	.string "The Hotheaded Quiz Master!$"

CinnabarIsland_Text_HeyIfItIsntPlayer::
# 31 "data/maps/CinnabarIsland/scripts.pory"
	.string "Huh? Hey, if it isn't {PLAYER}!$"

CinnabarIsland_Text_ComeWithMeToOneIsland::
# 35 "data/maps/CinnabarIsland/scripts.pory"
	.string "Look, it's me, BILL. Long time no see!\p"
	.string "I hope you're still using my PC system.\p"
	.string "Well, listen, since we met up here, how\n"
	.string "about spending time with me?\p"
	.string "There's this little island in the far\n"
	.string "south called ONE ISLAND.\p"
	.string "A friend invited me, so I'm on my way out\n"
	.string "there.\p"
	.string "How about it? Do you feel like coming\n"
	.string "with me?$"

CinnabarIsland_Text_AllRightLetsGo::
# 39 "data/maps/CinnabarIsland/scripts.pory"
	.string "All right, then. Let's go!$"

CinnabarIsland_Text_IllBeWaitingInPokeCenter::
# 43 "data/maps/CinnabarIsland/scripts.pory"
	.string "What, are you too busy?\p"
	.string "Well, all right. The boat hasn't arrived\n"
	.string "yet anyway.\p"
	.string "I'll be waiting at the POKMON CENTER\n"
	.string "over there.\p"
	.string "Come see me when you're done with your\n"
	.string "business here.$"

CinnabarIsland_Text_MyPalsBoatArrived::
# 47 "data/maps/CinnabarIsland/scripts.pory"
	.string "Looks like my pal's boat arrived, too.\p"
	.string "He sent it specially here to CINNABAR\n"
	.string "to pick me up.$"

CinnabarIsland_Text_IfYouHaveTriPassYouCanGoAgain::
# 51 "data/maps/CinnabarIsland/scripts.pory"
	.string "Hey, wasn't that a long cruise?\p"
	.string "My buddy CELIO seemed to enjoy your\n"
	.string "company.\p"
	.string "I'm sure he'd welcome you if you were to\n"
	.string "visit him again.\p"
	.string "If you have a TRI-PASS, you can always\n"
	.string "take a ferry there from\l"
	.string "VERMILION PORT.\p"
	.string "All right, thanks for your company!$"
