AbandonedShip_HiddenFloorCorridors_MapScripts::
	.byte 0


AbandonedShip_HiddenFloorCorridors_EventScript_Room1Door::
# 9 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	msgbox AbandonedShip_HiddenFloorCorridors_Text_InsertedKey, MSGBOX_DEFAULT
	end


AbandonedShip_HiddenFloorCorridors_EventScript_Room2Door::
# 24 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	msgbox AbandonedShip_HiddenFloorCorridors_Text_InsertedKey, MSGBOX_DEFAULT
	end


AbandonedShip_HiddenFloorCorridors_EventScript_Room4Door::
# 39 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	msgbox AbandonedShip_HiddenFloorCorridors_Text_InsertedKey, MSGBOX_DEFAULT
	end


AbandonedShip_HiddenFloorCorridors_EventScript_Room6Door::
# 54 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	msgbox AbandonedShip_HiddenFloorCorridors_Text_InsertedKey, MSGBOX_DEFAULT
	end


AbandonedShip_HiddenFloorCorridors_Text_InsertedKey::
# 65 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	.string "{PLAYER} inserted and turned the KEY.\p"
	.string "The inserted KEY stuck fast, but the\n"
	.string "door opened.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm4DoorIsLocked::
# 69 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	.string "The door is locked.\p"
	.string "“RM. 4” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm1DoorIsLocked::
# 73 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	.string "The door is locked.\p"
	.string "“RM. 1” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm2DoorIsLocked::
# 77 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	.string "The door is locked.\p"
	.string "“RM. 2” is painted on the door.$"

AbandonedShip_HiddenFloorCorridors_Text_Rm6DoorIsLocked::
# 81 "data/maps/AbandonedShip_HiddenFloorCorridors/scripts.pory"
	.string "The door is locked.\p"
	.string "“RM. 6” is painted on the door.$"
