BattleFrontier_BattleTowerBattleRoom_MapScripts::
# 2 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleTowerBattleRoom_OnFrame
# 3 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattleTowerBattleRoom_OnWarp
	.byte 0


BattleFrontier_BattleTowerBattleRoom_MapScripts::
# 7 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleTowerBattleRoom_OnFrame
# 8 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattleTowerBattleRoom_OnWarp
	return


BattleFrontier_BattleTowerBattleRoom_Text_RestoreMonsToFullHealth::
# 12 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "We will restore your POKéMON to full\n"
	.string "health.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyForOpponent::
# 16 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no.\n"
	.string "{STR_VAR_1}. Are you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor2ndOpponent::
# 20 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 2. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor3rdOpponent::
# 24 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 3. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor4thOpponent::
# 28 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 4. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor5thOpponent::
# 32 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 5. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor6thOpponent::
# 36 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 6. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyFor7thOpponent::
# 40 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing opponent no. 7. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordYourBattle::
# 44 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Record your battle on your FRONTIER\n"
	.string "PASS?$"

BattleFrontier_BattleTowerLobby_Text_BattleRecordedOnPass::
# 48 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "{PLAYER}'s battle was recorded on the\n"
	.string "FRONTIER PASS.$"

BattleFrontier_BattleTowerBattleRoom_Text_SaveAndQuitGame::
# 52 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Would you like to save and quit the\n"
	.string "game?$"

BattleFrontier_BattleTowerBattleRoom_Text_SavingPleaseWait::
# 56 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Saving your battle data. Please wait.$"

BattleFrontier_BattleTowerBattleRoom_Text_CancelYourChallenge::
# 60 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Would you like to cancel your BATTLE\n"
	.string "ROOM challenge?$"

BattleFrontier_BattleTowerBattleRoom_Text_RecordCouldntBeSaved::
# 64 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "There was an error of some sort. Your\n"
	.string "record could not be saved.$"

BattleFrontier_BattleTowerBattleRoom_Text_SalonMaidenOnHerWay::
# 68 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Excuse me, but…\p"
	.string "Our leader, the SALON MAIDEN, is on her\n"
	.string "way here in hopes of battling you.\p"
	.string "She should be arriving very shortly.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReadyForSalonMaiden::
# 72 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "You will be facing the SALON MAIDEN. Are\n"
	.string "you prepared?$"

BattleFrontier_BattleTowerBattleRoom_Text_GreetingsImAnabel::
# 76 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Greetings… My name is ANABEL.\p"
	.string "I am the SALON MAIDEN, and I am in\n"
	.string "charge of running the BATTLE TOWER…\p"
	.string "I have heard several rumors about you…\p"
	.string "In all honesty, what I have heard does\n"
	.string "not seem attractive in any way…\p"
	.string "The reason I've come to see you… Well,\n"
	.string "there is but one reason…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetMeSeeYourTalent::
# 80 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Let me see your talent in its entirety…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelTalentShallBeRecognized::
# 84 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "ANABEL: Fufufu, nicely done…\p"
	.string "Your FRONTIER PASS, please… Your\n"
	.string "talent shall be recognized.$"

BattleFrontier_BattleTowerBattleRoom_Text_ReceivedAbilitySymbol::
# 88 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "The Ability Symbol was embossed on the\n"
	.string "FRONTIER PASS!$"

BattleFrontier_BattleTowerBattleRoom_Text_UntilNextTime::
# 92 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "… … … … … …\p"
	.string "You have confidence in your POKéMON\n"
	.string "battling talent, don't you?\p"
	.string "I urge you to keep battling and keep on\n"
	.string "winning.\p"
	.string "I will be waiting for you. Until the next\n"
	.string "time we meet…$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelYouCameBack::
# 96 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "ANABEL: You really did come back to see\n"
	.string "me…\p"
	.string "… … … … … …\p"
	.string "You've won straight matches to see me…\n"
	.string "I won't have to hold back against you…\p"
	.string "It's been too long now…\p"
	.string "Too long since I've been able to battle\n"
	.string "without thinking about anything…$"

BattleFrontier_BattleTowerBattleRoom_Text_LetsBeginShallWe::
# 100 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "Let's begin, shall we?$"

BattleFrontier_BattleTowerBattleRoom_Text_AnabelCongratsYourPassPlease::
# 104 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "ANABEL: Fufu, congratulations… Your\n"
	.string "FRONTIER PASS, please…$"

BattleFrontier_BattleTowerBattleRoom_Text_AbilitySymbolTookGoldenShine::
# 108 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "The Ability Symbol took on a golden\n"
	.string "shine!$"

BattleFrontier_BattleTowerBattleRoom_Text_WishICouldBattleYouAgain::
# 112 "data/maps/BattleFrontier_BattleTowerBattleRoom/scripts.pory"
	.string "That was fun…\p"
	.string "I have never had a POKéMON battle so\n"
	.string "enjoyable before…\p"
	.string "I wish I could battle with you again…$"
