BattleFrontier_BattleTowerMultiBattleRoom_MapScripts::
# 2 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattleTowerMultiBattleRoom_OnTransition
# 3 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattleTowerMultiBattleRoom_OnWarp
# 4 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleTowerMultiBattleRoom_OnFrame
	.byte 0


BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor2ndOpponentSet::
# 8 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 2nd set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor3rdOpponentSet::
# 12 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 3rd set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor4thOpponentSet::
# 16 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 4th set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor5thOpponentSet::
# 20 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 5th set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor6thOpponentSet::
# 24 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 6th set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_ReadyFor7thOpponentSet::
# 28 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 7th set of opponents is next. Are\n"
	.string "you ready?$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_2ndOpponentSetNext::
# 32 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 2nd set of opponents is next. Do\n"
	.string "your best!$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_3rdOpponentSetNext::
# 36 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 3rd set of opponents is next. Do\n"
	.string "your best!$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_4thOpponentSetNext::
# 40 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 4th set of opponents is next. Do\n"
	.string "your best!$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_5thOpponentSetNext::
# 44 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 5th set of opponents is next. Do\n"
	.string "your best!$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_6thOpponentSetNext::
# 48 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 6th set of opponents is next. Do\n"
	.string "your best!$"

BattleFrontier_BattleTowerMultiBattleRoom_Text_7thOpponentSetNext::
# 52 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "The 7th set of opponents is next. Do\n"
	.string "your best!$"

gText_LinkStandby3::
# 56 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "Link standby$"

gText_YourPartnerHasRetired::
# 60 "data/maps/BattleFrontier_BattleTowerMultiBattleRoom/scripts.pory"
	.string "Your partner has retired.\p"
	.string "Your BATTLE ROOM challenge will be\n"
	.string "canceled.$"
