FiveIsland_House2_MapScripts::
	.byte 0


FiveIsland_House2_EventScript_OldMan::
# 5 "data/maps/FiveIsland_House2/scripts.pory"
	msgbox FiveIsland_House2_Text_MeadowBelongedToFamily, MSGBOX_NPC
	end


FiveIsland_House2_Text_MeadowBelongedToFamily::
# 10 "data/maps/FiveIsland_House2/scripts.pory"
	.string "That MEADOW has belonged to our\n"
	.string "family for generations.\p"
	.string "I should have had a giant mansion\n"
	.string "built on it.\p"
	.string "It would be preferable to having\n"
	.string "those thugs run wild on it!$"
