OneIsland_KindleRoad_EmberSpa_MapScripts::
	.byte 0


OneIsland_KindleRoad_EmberSpa_EventScript_BaldingMan1::
# 5 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	msgbox OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder, MSGBOX_NPC
	end


OneIsland_KindleRoad_EmberSpa_EventScript_BaldingMan2::
# 10 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	msgbox OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic, MSGBOX_NPC
	end


OneIsland_KindleRoad_EmberSpa_EventScript_BlackBelt::
	end


OneIsland_KindleRoad_EmberSpa_EventScript_OldMan::
# 19 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	msgbox OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore, MSGBOX_NPC
	end


OneIsland_KindleRoad_EmberSpa_EventScript_OldWoman::
# 24 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	msgbox OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs, MSGBOX_NPC
	end


OneIsland_KindleRoad_EmberSpa_EventScript_RockSmashMan::
	end


OneIsland_KindleRoad_EmberSpa_EventScript_SpaHeal::
	end


OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
# 37 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "My favorite part of bathing comes\n"
	.string "up right after this.\p"
	.string "I enjoy a bowl of chowder to\n"
	.string "warm me from the inside, too!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
# 41 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Soaking in a hot spring pool is\n"
	.string "therapeutic, people say.$"

OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
# 45 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Hm!\n"
	.string "Haaaaaaaaaaah!\p"
	.string "Aaaah! This is heavenly!\n"
	.string "The water warms me to my core!\p"
	.string "You should jump in, too.\p"
	.string "Go to the middle, relax, and get\n"
	.string "good and warm!$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
# 49 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Have a look at my face.\n"
	.string "See how smooth my skin is?\p"
	.string "The hot spring's water keeps my\n"
	.string "skin younger than my age.$"
