OneIsland_KindleRoad_EmberSpa_MapScripts::
	.byte 0


OneIsland_KindleRoad_EmberSpa_Text_WaterWarmsMeToCore::
# 5 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Hm! Haaaaaaaaaaah!\p"
	.string "Aaaah! This is heavenly! The water\n"
	.string "warms me to my core!\p"
	.string "You should jump in, too.\p"
	.string "Go to the middle, relax, and get good\n"
	.string "and warm!$"

OneIsland_KindleRoad_EmberSpa_Text_EnjoyBowlOfChowder::
# 9 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "My favorite part of bathing comes up\n"
	.string "right after this.\p"
	.string "I enjoy a bowl of chowder to warm me\n"
	.string "from the inside, too!$"

OneIsland_KindleRoad_EmberSpa_Text_WaterExquisiteFullyRefreshed::
# 13 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "The water is perfectly warm. It feels\n"
	.string "exquisite\p"
	.string "{PLAYER} and the POKMON were fully\n"
	.string "refreshed!$"

OneIsland_KindleRoad_EmberSpa_Text_HotSpringIsTherapeutic::
# 17 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Soaking in a hot spring pool is\n"
	.string "therapeutic, people say.$"

OneIsland_KindleRoad_EmberSpa_Text_SeeHowSmoothMySkinIs::
# 21 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Have a look at my face. See how smooth\n"
	.string "my skin is?\p"
	.string "The hot spring's water keeps my skin\n"
	.string "younger than my age.$"

OneIsland_KindleRoad_EmberSpa_Text_BrunoVisitsSpaOnOccasion::
# 25 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "After an honest day of training,\n"
	.string "nothing beats a relaxing soak in\l"
	.string "the hot spring pool.\p"
	.string "BRUNO, who's a senior ahead of me,\n"
	.string "visits the SPA on occasion.\p"
	.string "He comes to rehab injuries, both his own\n"
	.string "and his POKMON's.$"

OneIsland_KindleRoad_EmberSpa_Text_UsedThisToMakeEmberSpa::
# 29 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "Hot springs go hand-in-hand with\n"
	.string "volcanoes.\p"
	.string "The EMBER SPA here, well, I made it years\n"
	.string "ago.\p"
	.string "I hewed the pool right out of a gigantic\n"
	.string "boulder by hand.\p"
	.string "I was using this at the time. I suppose\n"
	.string "I can part with it.$"

OneIsland_KindleRoad_EmberSpa_Text_ExplainHM06::
# 33 "data/maps/OneIsland_KindleRoad_EmberSpa/scripts.pory"
	.string "That shatters boulders as if they were\n"
	.string "made of crackers.$"
