RustboroCity_Mart_MapScripts::
	.byte 0


RustboroCity_Mart_MapScripts::
	return


RustboroCity_Mart_Text_BuyingHealsInCaseOfShroomish::
# 8 "data/maps/RustboroCity_Mart/scripts.pory"
	.string "I'm buying some PARLYZ HEALS and\n"
	.string "ANTIDOTES.\p"
	.string "Just in case I run into SHROOMISH in\n"
	.string "PETALBURG WOODS.$"

RustboroCity_Mart_Text_ShouldBuySuperPotionsInstead::
# 12 "data/maps/RustboroCity_Mart/scripts.pory"
	.string "My POKéMON evolved. It has a lot of HP\n"
	.string "now.\p"
	.string "I should buy SUPER POTIONS for it\n"
	.string "instead of ordinary POTIONS.$"

RustboroCity_Mart_Text_GettingEscapeRopeJustInCase::
# 16 "data/maps/RustboroCity_Mart/scripts.pory"
	.string "I'm getting an ESCAPE ROPE just in case\n"
	.string "I get lost in a cave.\p"
	.string "I just need to use it to get back to the\n"
	.string "entrance.$"
