MtEmber_RubyPath_B4F_MapScripts::
	.byte 0


MtEmber_RubyPath_B4F_EventScript_BrailleABC::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleComma::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleDEF::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleGHI::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleJKL::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleMNO::
	end


MtEmber_RubyPath_B4F_EventScript_BraillePQRS::
	end


MtEmber_RubyPath_B4F_EventScript_BraillePeriod::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleTUV::
	end


MtEmber_RubyPath_B4F_EventScript_BrailleWXYZ::
	end


MtEmber_RubyPath_B4F_EventScript_SmithNPC1::
# 85 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	msgbox MtEmber_RubyPath_B4F_Text_SmithNPC1, MSGBOX_NPC
	end


MtEmber_RubyPath_B4F_EventScript_SmithNPC2::
# 94 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	msgbox MtEmber_RubyPath_B4F_Text_SmithNPC2, MSGBOX_NPC
	end


MtEmber_RubyPath_B4F_EventScript_SmithNPC3::
# 103 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	msgbox MtEmber_RubyPath_B4F_Text_SmithNPC3, MSGBOX_NPC
	end


MtEmber_RubyPath_B4F_EventScript_SmithNPC4::
# 112 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	msgbox MtEmber_RubyPath_B4F_Text_SmithNPC4, MSGBOX_NPC
	end


MtEmber_RubyPath_B4F_EventScript_SmithNPC5::
# 121 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	msgbox MtEmber_RubyPath_B4F_Text_SmithNPC5, MSGBOX_NPC
	end


MtEmber_RubyPath_B4F_Text_SmithNPC1::
# 89 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MtEmber_RubyPath_B4F_Text_SmithNPC2::
# 98 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

MtEmber_RubyPath_B4F_Text_SmithNPC3::
# 107 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

MtEmber_RubyPath_B4F_Text_SmithNPC4::
# 116 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

MtEmber_RubyPath_B4F_Text_SmithNPC5::
# 125 "data/maps/MtEmber_RubyPath_B4F/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"
