SilphCo_6F_MapScripts::
# 2 "data/maps/SilphCo_6F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_6F_OnLoad
	.byte 0


SilphCo_6F_Text_RocketsTookOverBuilding::
# 6 "data/maps/SilphCo_6F/scripts.pory"
	.string "The ROCKETS came and took over the\n"
	.string "building!$"

SilphCo_6F_Text_BetterGetBackToWork::
# 10 "data/maps/SilphCo_6F/scripts.pory"
	.string "Well, better get back to work.$"

SilphCo_6F_Text_HelpMePlease::
# 14 "data/maps/SilphCo_6F/scripts.pory"
	.string "Oh dear, oh dear. Help me, please!$"

SilphCo_6F_Text_WeGotEngaged::
# 18 "data/maps/SilphCo_6F/scripts.pory"
	.string "We got engaged. Heheh!$"

SilphCo_6F_Text_ThatManIsSuchACoward::
# 22 "data/maps/SilphCo_6F/scripts.pory"
	.string "That man next to me He's such a coward!$"

SilphCo_6F_Text_NeedsMeToLookAfterHim::
# 26 "data/maps/SilphCo_6F/scripts.pory"
	.string "He's so helpless, he needed someone like\n"
	.string "me to look after him.$"

SilphCo_6F_Text_RocketsTryingToConquerWorld::
# 30 "data/maps/SilphCo_6F/scripts.pory"
	.string "TEAM ROCKET is trying to conquer the\n"
	.string "world with POKMON.$"

SilphCo_6F_Text_RocketsRanAwayBecauseOfYou::
# 34 "data/maps/SilphCo_6F/scripts.pory"
	.string "TEAM ROCKET ran away, and it's all\n"
	.string "because of you!$"

SilphCo_6F_Text_TargetedSilphForOurMonProducts::
# 38 "data/maps/SilphCo_6F/scripts.pory"
	.string "They must have targeted SILPH for our\n"
	.string "POKMON products.$"

SilphCo_6F_Text_ComeWorkForSilphWhenYoureOlder::
# 42 "data/maps/SilphCo_6F/scripts.pory"
	.string "Come work for SILPH when you get older.$"

SilphCo_6F_Text_Grunt1Intro::
# 46 "data/maps/SilphCo_6F/scripts.pory"
	.string "I am one of the four ROCKET BROTHERS!$"

SilphCo_6F_Text_Grunt1Defeat::
# 50 "data/maps/SilphCo_6F/scripts.pory"
	.string "Flame out!$"

SilphCo_6F_Text_Grunt1PostBattle::
# 54 "data/maps/SilphCo_6F/scripts.pory"
	.string "No matter! My brothers will avenge me!$"

SilphCo_6F_Text_TaylorIntro::
# 58 "data/maps/SilphCo_6F/scripts.pory"
	.string "That rotten PRESIDENT!\p"
	.string "Serves him right for shipping me off to\n"
	.string "the TIKSI BRANCH!\p"
	.string "That's why TEAM ROCKET came after us,\n"
	.string "I'm sure of it!$"

SilphCo_6F_Text_TaylorDefeat::
# 62 "data/maps/SilphCo_6F/scripts.pory"
	.string "Shoot!$"

SilphCo_6F_Text_TaylorPostBattle::
# 66 "data/maps/SilphCo_6F/scripts.pory"
	.string "TIKSI BRANCH? It's in Russian\n"
	.string "no-man's-land!$"

SilphCo_6F_Text_Grunt2Intro::
# 70 "data/maps/SilphCo_6F/scripts.pory"
	.string "You dare betray TEAM ROCKET?$"

SilphCo_6F_Text_Grunt2Defeat::
# 74 "data/maps/SilphCo_6F/scripts.pory"
	.string "You traitor!$"

SilphCo_6F_Text_Grunt2PostBattle::
# 78 "data/maps/SilphCo_6F/scripts.pory"
	.string "If you stand for justice, you betray us\n"
	.string "bad guys!$"

SilphCo_6F_Text_FloorSign::
# 82 "data/maps/SilphCo_6F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 6F$"
