ThreeIsland_House2_MapScripts::
	.byte 0


ThreeIsland_House2_EventScript_Man::
	end


ThreeIsland_House2_EventScript_Rocker::
# 9 "data/maps/ThreeIsland_House2/scripts.pory"
	msgbox ThreeIsland_House2_Text_CantMakeThisSpoonBend, MSGBOX_NPC
	end


ThreeIsland_House2_Text_CantMakeThisSpoonBend::
# 14 "data/maps/ThreeIsland_House2/scripts.pory"
	.string "Urrrrrrrrgggghhhh…\n"
	.string "Kwaaaaah!\p"
	.string "…It's useless! I can't make this\n"
	.string "spoon bend with my mind.\p"
	.string "Maybe I really don't have any\n"
	.string "psychic powers.$"
