ThreeIsland_House2_MapScripts::
	.byte 0


ThreeIsland_House2_Text_CantMakeThisSpoonBend::
# 5 "data/maps/ThreeIsland_House2/scripts.pory"
	.string "Urrrrrrrrgggghhhh… Kwaaaaah!\p"
	.string "…It's useless! I can't make this spoon\n"
	.string "bend with my mind.\p"
	.string "Maybe I really don't have any psychic\n"
	.string "powers.$"

ThreeIsland_House2_Text_IAdmireSabrina::
# 9 "data/maps/ThreeIsland_House2/scripts.pory"
	.string "You know about a girl GYM LEADER in\n"
	.string "SAFFRON CITY?\p"
	.string "She uses PSYCHIC-type POKéMON, right?\p"
	.string "I admire her, I really do.\p"
	.string "I've heard that she's one cool customer\n"
	.string "and beautiful, too.$"
