SootopolisCity_Mart_MapScripts::
	.byte 0


SootopolisCity_Mart_EventScript_Clerk::
	end


SootopolisCity_Mart_EventScript_FatMan::
	end


SootopolisCity_Mart_EventScript_Gentleman::
	end


SootopolisCity_Mart_Text_PPUpIsGreat::
# 16 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "PP UP is great!\p"
	.string "It raises the POWER POINTS, the PP,\n"
	.string "of a POKéMON move.$"

SootopolisCity_Mart_Text_FullRestoreItemOfDreams::
# 20 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "Do you know FULL RESTORE?\p"
	.string "Full restoration of HP!\n"
	.string "Eradication of all status problems!\p"
	.string "It's truly an item of your dreams!$"
