SootopolisCity_Mart_MapScripts::
	.byte 0


SootopolisCity_Mart_MapScripts::
	return


SootopolisCity_Mart_Text_PPUpIsGreat::
# 8 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "PP UP is great!\p"
	.string "It raises the POWER POINTS, the PP, of a\n"
	.string "POKéMON move.$"

SootopolisCity_Mart_Text_TooScaryOutside::
# 12 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "What… What is happening?\p"
	.string "I really want to know, but it's too scary\n"
	.string "to go outside.$"

SootopolisCity_Mart_Text_FullRestoreItemOfDreams::
# 16 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "Do you know FULL RESTORE?\p"
	.string "Full restoration of HP! Eradication of\n"
	.string "all status problems!\p"
	.string "It's truly an item of your dreams!$"

SootopolisCity_Mart_Text_DidSomethingAwaken::
# 20 "data/maps/SootopolisCity_Mart/scripts.pory"
	.string "This weather… Did something awaken?$"
