FourIsland_House1_MapScripts::
	.byte 0


JPText_BodySlamTeach::
# 5 "data/maps/FourIsland_House1/scripts.pory"
	.string "そーれ　ぼよーん！ どっちが　さきに　へたばるか？\l"
	.string "のしかかり　しょうぶ　してるんだ\p"
	.string "きみは　なかまに　はいったら つぶれそうだな‥\l"
	.string "かわりに　きみの　ポケモンに\l"
	.string "のしかかり　おしえて　やろっか？$"

JPText_BodySlamDeclined::
# 9 "data/maps/FourIsland_House1/scripts.pory"
	.string "また　おいで　ぼよーん！$"

JPText_BodySlamWhichMon::
# 13 "data/maps/FourIsland_House1/scripts.pory"
	.string "どの　ポケモンに おしえたい　かい？$"

JPText_BodySlamTaught::
# 17 "data/maps/FourIsland_House1/scripts.pory"
	.string "ぼよよーん！$"

FourIsland_House1_Text_YoureAwfullyHeavy::
# 21 "data/maps/FourIsland_House1/scripts.pory"
	.string "There! Boing! You're awfully heavy!$"
