FourIsland_House1_MapScripts::
	.byte 0


JPText_BodySlamTeach::
# 5 "data/maps/FourIsland_House1/scripts.pory"
	.string "\l"
	.string "\p"
	.string "\l"
	.string "\l"
	.string "$"

JPText_BodySlamDeclined::
# 9 "data/maps/FourIsland_House1/scripts.pory"
	.string "$"

JPText_BodySlamWhichMon::
# 13 "data/maps/FourIsland_House1/scripts.pory"
	.string "$"

JPText_BodySlamTaught::
# 17 "data/maps/FourIsland_House1/scripts.pory"
	.string "$"

FourIsland_House1_Text_YoureAwfullyHeavy::
# 21 "data/maps/FourIsland_House1/scripts.pory"
	.string "There! Boing! You're awfully heavy!$"
