SafariZone_South_MapScripts::
	.byte 0


SafariZone_South_EventScript_Boy::
# 5 "data/maps/SafariZone_South/scripts.pory"
	msgbox SafariZone_South_Text_Boy, MSGBOX_NPC
	end


SafariZone_South_EventScript_ConstructionWorker1::
# 10 "data/maps/SafariZone_South/scripts.pory"
	msgbox SafariZone_South_Text_AreaOffLimits1, MSGBOX_NPC
	end


SafariZone_South_EventScript_ConstructionWorker2::
# 15 "data/maps/SafariZone_South/scripts.pory"
	msgbox SafariZone_South_Text_AreaOffLimits2, MSGBOX_NPC
	end


SafariZone_South_EventScript_ExitAttendant::
	end


SafariZone_South_EventScript_Man::
# 24 "data/maps/SafariZone_South/scripts.pory"
	msgbox SafariZone_South_Text_Man, MSGBOX_NPC
	end


SafariZone_South_EventScript_Youngster::
# 29 "data/maps/SafariZone_South/scripts.pory"
	msgbox SafariZone_South_Text_Youngster, MSGBOX_NPC
	end

