FortreeCity_MapScripts::
	.byte 0


FortreeCity_EventScript_Boy::
# 5 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_BugPokemonComeThroughWindow, MSGBOX_NPC
	end


FortreeCity_EventScript_CitySign::
# 10 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_CitySign, MSGBOX_SIGN
	end


FortreeCity_EventScript_GameboyKid::
# 15 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_PokemonThatEvolveWhenTraded, MSGBOX_NPC
	end


FortreeCity_EventScript_Girl::
# 20 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_TreesGrowByDrinkingRainwater, MSGBOX_NPC
	end


FortreeCity_EventScript_GymSign::
# 25 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_GymSign, MSGBOX_SIGN
	end


FortreeCity_EventScript_Man::
# 30 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_SawGiganticPokemonInSky, MSGBOX_NPC
	end


FortreeCity_EventScript_OldMan::
# 35 "data/maps/FortreeCity/scripts.pory"
	msgbox FortreeCity_Text_EveryoneHealthyAndLively, MSGBOX_NPC
	end


FortreeCity_EventScript_Woman::
	end


FortreeCity_Text_CitySign::
# 44 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY “The treetop city that\n"
	.string "frolics with\l"
	.string "nature.”$"

FortreeCity_Text_GymSign::
# 48 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY POKéMON GYM LEADER:\n"
	.string "WINONA\p"
	.string "“The bird user taking flight into the\n"
	.string "world.”$"

FortreeCity_Text_SawGiganticPokemonInSky::
# 52 "data/maps/FortreeCity/scripts.pory"
	.string "No one believes me, but I saw this\n"
	.string "gigantic POKéMON in the sky.\p"
	.string "It seemed to squirm as it flew toward\n"
	.string "ROUTE 131.\p"
	.string "By the way… Sniff…\n"
	.string "Um… You, uh…smell singed.\p"
	.string "Were you at a volcano or something?$"

FortreeCity_Text_ThisTimeIllBeatWinona::
# 56 "data/maps/FortreeCity/scripts.pory"
	.string "I've got my pride-and-joy POKéMON\n"
	.string "with me. This time, I'll beat WINONA.$"

FortreeCity_Text_EveryoneHealthyAndLively::
# 60 "data/maps/FortreeCity/scripts.pory"
	.string "The CITY consists of homes built on\n"
	.string "trees.\p"
	.string "Perhaps because of that lifestyle,\n"
	.string "everyone is healthy and lively.\p"
	.string "Why, even myself--I feel as if I've\n"
	.string "grown thirty years younger.$"

FortreeCity_Text_BugPokemonComeThroughWindow::
# 64 "data/maps/FortreeCity/scripts.pory"
	.string "Living on top of trees is okay.\p"
	.string "But sometimes BUG POKéMON come in\n"
	.string "through windows.\l"
	.string "It can be really startling.$"

FortreeCity_Text_UsedDevonScopePokemonFled::
# 68 "data/maps/FortreeCity/scripts.pory"
	.string "{PLAYER} used the DEVON SCOPE.\p"
	.string "An invisible POKéMON became completely\n"
	.string "visible!\p"
	.string "The startled POKéMON fled!$"

FortreeCity_Text_UnseeableUseDevonScope::
# 72 "data/maps/FortreeCity/scripts.pory"
	.string "Something unseeable is in the way.\p"
	.string "Want to use the DEVON SCOPE?$"

FortreeCity_Text_PokemonThatEvolveWhenTraded::
# 76 "data/maps/FortreeCity/scripts.pory"
	.string "There are POKéMON that evolve when\n"
	.string "you trade them! That's what I heard.$"

FortreeCity_Text_TreesGrowByDrinkingRainwater::
# 80 "data/maps/FortreeCity/scripts.pory"
	.string "The ground absorbs rainwater, and\n"
	.string "trees grow by drinking that water…\p"
	.string "Our FORTREE CITY exists because\n"
	.string "there's both water and soil.$"
