FortreeCity_MapScripts::
# 2 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_OnTransition
# 3 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FortreeCity_OnResume
	.byte 0


FortreeCity_Text_SawGiganticPokemonInSky::
# 7 "data/maps/FortreeCity/scripts.pory"
	.string "No one believes me, but I saw this\n"
	.string "gigantic POKMON in the sky.\p"
	.string "It seemed to squirm as it flew toward\n"
	.string "ROUTE 131.\p"
	.string "By the way Sniff Um You, uhsmell singed.\p"
	.string "Were you at a volcano or something?$"

FortreeCity_Text_SomethingBlockingGym::
# 11 "data/maps/FortreeCity/scripts.pory"
	.string "I want to go to the POKMON GYM, but\n"
	.string "something's blocking the way.\p"
	.string "After all the bother I went through\n"
	.string "training on ROUTE 120$"

FortreeCity_Text_ThisTimeIllBeatWinona::
# 15 "data/maps/FortreeCity/scripts.pory"
	.string "I've got my pride-and-joy POKMON with\n"
	.string "me. This time, I'll beat WINONA.$"

FortreeCity_Text_TreesGrowByDrinkingRainwater::
# 19 "data/maps/FortreeCity/scripts.pory"
	.string "The ground absorbs rainwater, and\n"
	.string "trees grow by drinking that water\p"
	.string "Our FORTREE CITY exists because\n"
	.string "there's both water and soil.$"

FortreeCity_Text_EveryoneHealthyAndLively::
# 23 "data/maps/FortreeCity/scripts.pory"
	.string "The CITY consists of homes built on\n"
	.string "trees.\p"
	.string "Perhaps because of that lifestyle,\n"
	.string "everyone is healthy and lively.\p"
	.string "Why, even myself--I feel as if I've\n"
	.string "grown thirty years younger.$"

FortreeCity_Text_BugPokemonComeThroughWindow::
# 27 "data/maps/FortreeCity/scripts.pory"
	.string "Living on top of trees is okay.\p"
	.string "But sometimes BUG POKMON come in\n"
	.string "through windows.\l"
	.string "It can be really startling.$"

FortreeCity_Text_PokemonThatEvolveWhenTraded::
# 31 "data/maps/FortreeCity/scripts.pory"
	.string "There are POKMON that evolve when you\n"
	.string "trade them! That's what I heard.$"

FortreeCity_Text_SomethingUnseeable::
# 35 "data/maps/FortreeCity/scripts.pory"
	.string "Something unseeable is in the way.$"

FortreeCity_Text_UnseeableUseDevonScope::
# 39 "data/maps/FortreeCity/scripts.pory"
	.string "Something unseeable is in the way.\p"
	.string "Want to use the DEVON SCOPE?$"

FortreeCity_Text_UsedDevonScopePokemonFled::
# 43 "data/maps/FortreeCity/scripts.pory"
	.string "{PLAYER} used the DEVON SCOPE.\p"
	.string "An invisible POKMON became completely\n"
	.string "visible!\p"
	.string "The startled POKMON fled!$"

FortreeCity_Text_CitySign::
# 47 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY The treetop city that\n"
	.string "frolics with\l"
	.string "nature.$"

FortreeCity_Text_GymSign::
# 51 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY POKMON GYM LEADER:\n"
	.string "WINONA\p"
	.string "The bird user taking flight into the\n"
	.string "world.$"
