FortreeCity_MapScripts::
# 2 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_OnTransition
# 3 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FortreeCity_OnResume
	.byte 0


FortreeCity_MapScripts::
# 7 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_OnTransition
# 8 "data/maps/FortreeCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FortreeCity_OnResume
	return


FortreeCity_Text_SawGiganticPokemonInSky::
# 12 "data/maps/FortreeCity/scripts.pory"
	.string "No one believes me, but I saw this\n"
	.string "gigantic POKéMON in the sky.\p"
	.string "It seemed to squirm as it flew toward\n"
	.string "ROUTE 131.\p"
	.string "By the way… Sniff… Um… You, uh…smell\n"
	.string "singed.\p"
	.string "Were you at a volcano or something?$"

FortreeCity_Text_SomethingBlockingGym::
# 16 "data/maps/FortreeCity/scripts.pory"
	.string "I want to go to the POKéMON GYM, but\n"
	.string "something's blocking the way.\p"
	.string "After all the bother I went through\n"
	.string "training on ROUTE 120…$"

FortreeCity_Text_ThisTimeIllBeatWinona::
# 20 "data/maps/FortreeCity/scripts.pory"
	.string "I've got my pride-and-joy POKéMON with\n"
	.string "me. This time, I'll beat WINONA.$"

FortreeCity_Text_TreesGrowByDrinkingRainwater::
# 24 "data/maps/FortreeCity/scripts.pory"
	.string "The ground absorbs rainwater, and\n"
	.string "trees grow by drinking that water…\p"
	.string "Our FORTREE CITY exists because\n"
	.string "there's both water and soil.$"

FortreeCity_Text_EveryoneHealthyAndLively::
# 28 "data/maps/FortreeCity/scripts.pory"
	.string "The CITY consists of homes built on\n"
	.string "trees.\p"
	.string "Perhaps because of that lifestyle,\n"
	.string "everyone is healthy and lively.\p"
	.string "Why, even myself--I feel as if I've\n"
	.string "grown thirty years younger.$"

FortreeCity_Text_BugPokemonComeThroughWindow::
# 32 "data/maps/FortreeCity/scripts.pory"
	.string "Living on top of trees is okay.\p"
	.string "But sometimes BUG POKéMON come in\n"
	.string "through windows.\l"
	.string "It can be really startling.$"

FortreeCity_Text_PokemonThatEvolveWhenTraded::
# 36 "data/maps/FortreeCity/scripts.pory"
	.string "There are POKéMON that evolve when you\n"
	.string "trade them! That's what I heard.$"

FortreeCity_Text_SomethingUnseeable::
# 40 "data/maps/FortreeCity/scripts.pory"
	.string "Something unseeable is in the way.$"

FortreeCity_Text_UnseeableUseDevonScope::
# 44 "data/maps/FortreeCity/scripts.pory"
	.string "Something unseeable is in the way.\p"
	.string "Want to use the DEVON SCOPE?$"

FortreeCity_Text_UsedDevonScopePokemonFled::
# 48 "data/maps/FortreeCity/scripts.pory"
	.string "{PLAYER} used the DEVON SCOPE.\p"
	.string "An invisible POKéMON became completely\n"
	.string "visible!\p"
	.string "The startled POKéMON fled!$"

FortreeCity_Text_CitySign::
# 52 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY “The treetop city that\n"
	.string "frolics with\l"
	.string "nature.”$"

FortreeCity_Text_GymSign::
# 56 "data/maps/FortreeCity/scripts.pory"
	.string "FORTREE CITY POKéMON GYM LEADER:\n"
	.string "WINONA\p"
	.string "“The bird user taking flight into the\n"
	.string "world.”$"
