FuchsiaCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FuchsiaCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
# 7 "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.pory"
	.string "You can't become a good TRAINER with\n"
	.string "just one strong POKMON.\p"
	.string "But raising many POKMON evenly is no\n"
	.string "easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
# 11 "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.pory"
	.string "There's a narrow trail west of VIRIDIAN\n"
	.string "CITY.\p"
	.string "It goes to the POKMON LEAGUE HQ. The HQ\n"
	.string "governs all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
# 15 "data/maps/FuchsiaCity_PokemonCenter_1F/scripts.pory"
	.string "If you're working on a POKDEX, visit the\n"
	.string "SAFARI ZONE.\p"
	.string "All sorts of rare POKMON breed there.$"
