BarrierStation_NorthEntrance_MapScripts::
	.byte 0


BarrierStation_NorthEntrance_EventScript_SmithNPC1::
# 5 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	msgbox BarrierStation_NorthEntrance_Text_SmithNPC1, MSGBOX_NPC
	end


BarrierStation_NorthEntrance_EventScript_SmithNPC2::
# 14 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	msgbox BarrierStation_NorthEntrance_Text_SmithNPC2, MSGBOX_NPC
	end


BarrierStation_NorthEntrance_EventScript_SmithNPC3::
# 23 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	msgbox BarrierStation_NorthEntrance_Text_SmithNPC3, MSGBOX_NPC
	end


BarrierStation_NorthEntrance_EventScript_SmithNPC4::
# 32 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	msgbox BarrierStation_NorthEntrance_Text_SmithNPC4, MSGBOX_NPC
	end


BarrierStation_NorthEntrance_Text_SmithNPC1::
# 9 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

BarrierStation_NorthEntrance_Text_SmithNPC2::
# 18 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

BarrierStation_NorthEntrance_Text_SmithNPC3::
# 27 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

BarrierStation_NorthEntrance_Text_SmithNPC4::
# 36 "data/maps/BarrierStation_NorthEntrance/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
