Route6_NorthEntrance_MapScripts::
	.byte 0


Route6_NorthEntrance_EventScript_Guard::
# 5 "data/maps/Route6_NorthEntrance/scripts.pory"
	msgbox Route6_NorthEntrance_Text_HiHowsItGoing, MSGBOX_NPC
	end


Route6_NorthEntrance_EventScript_GuardTriggerLeft::
	end


Route6_NorthEntrance_EventScript_GuardTriggerMid::
	end


Route6_NorthEntrance_EventScript_GuardTriggerRight::
	end


Route6_NorthEntrance_Text_HiHowsItGoing::
# 22 "data/maps/Route6_NorthEntrance/scripts.pory"
	.string "Hi, how's it going?$"
