CeruleanCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeruleanCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


CeruleanCity_PokemonCenter_1F_Text_BillDoesWhateverForRareMons::
# 7 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	.string "That BILL!\p"
	.string "I heard that he'll do whatever it takes\n"
	.string "to get rare POKéMON.\p"
	.string "He's not above doing all sorts of\n"
	.string "things, I've heard.$"

CeruleanCity_PokemonCenter_1F_Text_EveryoneCallsBillPokemaniac::
# 11 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	.string "Have you heard about BILL?\p"
	.string "Everyone calls him a POKéMANIAC!\p"
	.string "I think people are just jealous of BILL,\n"
	.string "though.\p"
	.string "Who wouldn't want to boast about their\n"
	.string "POKéMON?$"

CeruleanCity_PokemonCenter_1F_Text_BillCollectsRareMons::
# 15 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	.string "BILL has lots of POKéMON! He collects\n"
	.string "rare ones, too!$"

CeruleanCity_PokemonCenter_1F_Text_TryTradingUpstairs::
# 19 "data/maps/CeruleanCity_PokemonCenter_1F/scripts.pory"
	.string "Why don't you go upstairs and try\n"
	.string "trading POKéMON with your friends?\p"
	.string "You could get a lot more variety by\n"
	.string "trading.\p"
	.string "The POKéMON you get in trades grow\n"
	.string "quickly, too.$"
