SaffronCity_MapScripts::
# 2 "data/maps/SaffronCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SaffronCity_OnTransition
	.byte 0


SaffronCity_Text_WhatDoYouWantGetLost::
# 6 "data/maps/SaffronCity/scripts.pory"
	.string "What do you want? Get lost!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
# 10 "data/maps/SaffronCity/scripts.pory"
	.string "BOSS said he'll take this town in the\n"
	.string "name of TEAM ROCKET!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
# 14 "data/maps/SaffronCity/scripts.pory"
	.string "Don't get defiant! Or I'll have to hurt\n"
	.string "you!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
# 18 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON belongs to TEAM ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
# 22 "data/maps/SaffronCity/scripts.pory"
	.string "My life as a criminal makes me feel so\n"
	.string "alive!$"

SaffronCity_Text_WatchWhereYoureWalking::
# 26 "data/maps/SaffronCity/scripts.pory"
	.string "Ow! Watch where you're walking!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
# 30 "data/maps/SaffronCity/scripts.pory"
	.string "With SILPH under control, we can\n"
	.string "exploit POKMON around the world!\p"
	.string "We'll get stinking rich, yeahah!$"

SaffronCity_Text_YouBeatTeamRocket::
# 34 "data/maps/SaffronCity/scripts.pory"
	.string "You beat TEAM ROCKET all alone? That's\n"
	.string "amazing!$"

SaffronCity_Text_SafeToGoOutAgain::
# 38 "data/maps/SaffronCity/scripts.pory"
	.string "Yeah! TEAM ROCKET is gone! It's safe to\n"
	.string "go out again!$"

SaffronCity_Text_PeopleComingBackToSaffron::
# 42 "data/maps/SaffronCity/scripts.pory"
	.string "People fled from here in droves when\n"
	.string "those ROCKETS came.\p"
	.string "They should be flocking back to\n"
	.string "SAFFRON now.$"

SaffronCity_Text_FlewHereOnPidgeot::
# 46 "data/maps/SaffronCity/scripts.pory"
	.string "I flew here on my PIDGEOT when I read\n"
	.string "about SILPH.\p"
	.string "It's already over? I missed the media\n"
	.string "action$"

SaffronCity_Text_Pidgeot::
# 50 "data/maps/SaffronCity/scripts.pory"
	.string "PIDGEOT: Bi bibii!$"

SaffronCity_Text_SawRocketBossEscaping::
# 54 "data/maps/SaffronCity/scripts.pory"
	.string "I saw the ROCKET BOSS escaping SILPH's\n"
	.string "building.$"

SaffronCity_Text_ImASecurityGuard::
# 58 "data/maps/SaffronCity/scripts.pory"
	.string "I'm a security guard.\p"
	.string "Suspicious kids I don't allow in!$"

SaffronCity_Text_HesTakingASnooze::
# 62 "data/maps/SaffronCity/scripts.pory"
	.string "Snore\p"
	.string "Hah! He's taking a snooze!$"

SaffronCity_Text_CitySign::
# 66 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON CITY Shining, Golden Land of\n"
	.string "Commerce$"

SaffronCity_Text_FightingDojo::
# 70 "data/maps/SaffronCity/scripts.pory"
	.string "FIGHTING DOJO$"

SaffronCity_Text_GymSign::
# 74 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON CITY POKMON GYM LEADER:\n"
	.string "SABRINA\l"
	.string "The Master of PSYCHIC POKMON!$"

SaffronCity_Text_FullHealCuresStatus::
# 78 "data/maps/SaffronCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "FULL HEAL cures all ailments like burns,\n"
	.string "paralysis, poisoning,\l"
	.string "freezing, and sleep.\p"
	.string "It costs a bit more, but it's more\n"
	.string "convenient than buying other items.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
# 82 "data/maps/SaffronCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The new GREAT BALL offers improved\n"
	.string "catching rates.\p"
	.string "Try it on those hard-to-catch POKMON.$"

SaffronCity_Text_SilphCoSign::
# 86 "data/maps/SaffronCity/scripts.pory"
	.string "SILPH CO. OFFICE BUILDING$"

SaffronCity_Text_MrPsychicsHouse::
# 90 "data/maps/SaffronCity/scripts.pory"
	.string "MR. PSYCHIC'S HOUSE$"

SaffronCity_Text_SilphsLatestProduct::
# 94 "data/maps/SaffronCity/scripts.pory"
	.string "SILPH's latest product! Release to be\n"
	.string "determined$"

SaffronCity_Text_TrainerFanClubSign::
# 98 "data/maps/SaffronCity/scripts.pory"
	.string "POKMON TRAINER FAN CLUB\p"
	.string "Many TRAINERS have scribbled their\n"
	.string "names on this sign.$"

SaffronCity_Text_HowCanClubNotRecognizeLance::
# 102 "data/maps/SaffronCity/scripts.pory"
	.string "This FAN CLUB No one here has a clue!\p"
	.string "How could they not recognize the\n"
	.string "brilliance that is LANCE?\p"
	.string "He stands for justice! He's cool, and\n"
	.string "yet passionate!\l"
	.string "He's the greatest, LANCE!$"
