SaffronCity_MapScripts::
	.byte 0


SaffronCity_EventScript_Boy::
# 5 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_FlewHereOnPidgeot, MSGBOX_NPC
	end


SaffronCity_EventScript_CitySign::
# 10 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_CitySign, MSGBOX_SIGN
	end


SaffronCity_EventScript_DojoSign::
# 15 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_FightingDojo, MSGBOX_SIGN
	end


SaffronCity_EventScript_DoorGuardGrunt::
	end


SaffronCity_EventScript_GymSign::
# 26 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_GymSign, MSGBOX_SIGN
	end


SaffronCity_EventScript_Lass::
# 32 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_PeopleComingBackToSaffron, MSGBOX_NPC
	end


SaffronCity_EventScript_Man::
# 37 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_SawRocketBossEscaping, MSGBOX_NPC
	end


SaffronCity_EventScript_MrPsychicsHouseSign::
# 42 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_MrPsychicsHouse, MSGBOX_SIGN
	end


SaffronCity_EventScript_Pidgeot::
	end


SaffronCity_EventScript_RocketGrunt1::
# 51 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_WhatDoYouWantGetLost, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt2::
# 56 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_BossTakeTownForTeamRocket, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt3::
# 61 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_DontGetDefiantOrIllHurtYou, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt4::
# 66 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_SaffronBelongsToTeamRocket, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt5::
# 71 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_CriminalLifeMakesMeFeelAlive, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt6::
# 76 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_WatchWhereYoureWalking, MSGBOX_NPC
	end


SaffronCity_EventScript_RocketGrunt7::
# 81 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_WeCanExploitMonsAroundWorld, MSGBOX_NPC
	end


SaffronCity_EventScript_SilphCoSign::
# 86 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_SilphCoSign, MSGBOX_SIGN
	end


SaffronCity_EventScript_SilphProductSign::
# 91 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_SilphsLatestProduct, MSGBOX_SIGN
	end


SaffronCity_EventScript_TrainerFanClubSign::
# 96 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_TrainerFanClubSign, MSGBOX_SIGN
	end


SaffronCity_EventScript_TrainerTips1::
# 101 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_FullHealCuresStatus, MSGBOX_SIGN
	end


SaffronCity_EventScript_TrainerTips2::
# 106 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_GreatBallImprovedCatchRate, MSGBOX_SIGN
	end


SaffronCity_EventScript_WorkerM::
# 111 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_YouBeatTeamRocket, MSGBOX_NPC
	end


SaffronCity_EventScript_Youngster::
# 116 "data/maps/SaffronCity/scripts.pory"
	msgbox SaffronCity_Text_SafeToGoOutAgain, MSGBOX_NPC
	end


SaffronCity_Text_SilphCoSign::
# 121 "data/maps/SaffronCity/scripts.pory"
	.string "SILPH CO. OFFICE BUILDING$"

SaffronCity_Text_MrPsychicsHouse::
# 125 "data/maps/SaffronCity/scripts.pory"
	.string "MR. PSYCHIC'S HOUSE$"

SaffronCity_Text_TrainerFanClubSign::
# 129 "data/maps/SaffronCity/scripts.pory"
	.string "POKéMON TRAINER FAN CLUB\p"
	.string "Many TRAINERS have scribbled their\n"
	.string "names on this sign.$"

SaffronCity_Text_CitySign::
# 133 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON CITY Shining, Golden Land of\n"
	.string "Commerce$"

SaffronCity_Text_FullHealCuresStatus::
# 137 "data/maps/SaffronCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "FULL HEAL cures all ailments like burns,\n"
	.string "paralysis, poisoning,\l"
	.string "freezing, and sleep.\p"
	.string "It costs a bit more, but it's more\n"
	.string "convenient than buying other items.$"

SaffronCity_Text_GreatBallImprovedCatchRate::
# 141 "data/maps/SaffronCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The new GREAT BALL offers improved\n"
	.string "catching rates.\p"
	.string "Try it on those hard-to-catch POKéMON.$"

SaffronCity_Text_FightingDojo::
# 145 "data/maps/SaffronCity/scripts.pory"
	.string "FIGHTING DOJO$"

SaffronCity_Text_GymSign::
# 149 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON CITY POKéMON GYM LEADER:\n"
	.string "SABRINA\l"
	.string "The Master of PSYCHIC POKéMON!$"

SaffronCity_Text_SilphsLatestProduct::
# 153 "data/maps/SaffronCity/scripts.pory"
	.string "SILPH's latest product! Release to be\n"
	.string "determined…$"

SaffronCity_Text_FlewHereOnPidgeot::
# 157 "data/maps/SaffronCity/scripts.pory"
	.string "I flew here on my PIDGEOT when\n"
	.string "I read about SILPH.\p"
	.string "It's already over?\n"
	.string "I missed the media action…$"

SaffronCity_Text_PeopleComingBackToSaffron::
# 161 "data/maps/SaffronCity/scripts.pory"
	.string "People fled from here in droves\n"
	.string "when those ROCKETS came.\p"
	.string "They should be flocking back to\n"
	.string "SAFFRON now.$"

SaffronCity_Text_SawRocketBossEscaping::
# 165 "data/maps/SaffronCity/scripts.pory"
	.string "I saw the ROCKET BOSS escaping\n"
	.string "SILPH's building.$"

SaffronCity_Text_WhatDoYouWantGetLost::
# 169 "data/maps/SaffronCity/scripts.pory"
	.string "What do you want?\n"
	.string "Get lost!$"

SaffronCity_Text_BossTakeTownForTeamRocket::
# 173 "data/maps/SaffronCity/scripts.pory"
	.string "BOSS said he'll take this town\n"
	.string "in the name of TEAM ROCKET!$"

SaffronCity_Text_DontGetDefiantOrIllHurtYou::
# 177 "data/maps/SaffronCity/scripts.pory"
	.string "Don't get defiant!\n"
	.string "Or I'll have to hurt you!$"

SaffronCity_Text_SaffronBelongsToTeamRocket::
# 181 "data/maps/SaffronCity/scripts.pory"
	.string "SAFFRON belongs to TEAM ROCKET!$"

SaffronCity_Text_CriminalLifeMakesMeFeelAlive::
# 185 "data/maps/SaffronCity/scripts.pory"
	.string "My life as a criminal makes me feel\n"
	.string "so alive!$"

SaffronCity_Text_WatchWhereYoureWalking::
# 189 "data/maps/SaffronCity/scripts.pory"
	.string "Ow!\n"
	.string "Watch where you're walking!$"

SaffronCity_Text_WeCanExploitMonsAroundWorld::
# 193 "data/maps/SaffronCity/scripts.pory"
	.string "With SILPH under control, we can\n"
	.string "exploit POKéMON around the world!\p"
	.string "We'll get stinking rich, yeahah!$"

SaffronCity_Text_YouBeatTeamRocket::
# 197 "data/maps/SaffronCity/scripts.pory"
	.string "You beat TEAM ROCKET all alone?\n"
	.string "That's amazing!$"

SaffronCity_Text_SafeToGoOutAgain::
# 201 "data/maps/SaffronCity/scripts.pory"
	.string "Yeah! TEAM ROCKET is gone!\n"
	.string "It's safe to go out again!$"
