TwoIsland_MapScripts::
# 2 "data/maps/TwoIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TwoIsland_OnTransition
	.byte 0


TwoIsland_Text_IslandSign::
# 6 "data/maps/TwoIsland/scripts.pory"
	.string "TWO ISLAND Boon Island for Two$"

TwoIsland_Text_JoyfulGameCornerSign::
# 10 "data/maps/TwoIsland/scripts.pory"
	.string "Skip & Chomp! Joyful GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
# 14 "data/maps/TwoIsland/scripts.pory"
	.string "DANGER! FAST CURRENT! Fishing and\n"
	.string "surfing prohibited!$"

TwoIsland_Text_WelcomeToShopMerchandiseLimited::
# 18 "data/maps/TwoIsland/scripts.pory"
	.string "Oh! Hello, welcome to my shop!\p"
	.string "We've only opened up recently.\p"
	.string "Our merchandise is limited, but I hope\n"
	.string "we can serve your needs.$"

TwoIsland_Text_AddedMerchandiseForLostelle::
# 22 "data/maps/TwoIsland/scripts.pory"
	.string "I can't tell you how grateful I am for\n"
	.string "your rescue of LOSTELLE.\p"
	.string "Thanks to your feat, the people of\n"
	.string "THREE ISLAND have changed their\l"
	.string "attitudes about KANTO people.\p"
	.string "And, I'm from KANTO, you see.\p"
	.string "The people of THREE ISLAND helped me\n"
	.string "add to my merchandise.$"

TwoIsland_Text_HopeYouGiveItYourBest::
# 26 "data/maps/TwoIsland/scripts.pory"
	.string "Hi! I'm giving it my best here. I hope you\n"
	.string "do too, {PLAYER}.$"

TwoIsland_Text_BringingItemsFromDistantLands::
# 30 "data/maps/TwoIsland/scripts.pory"
	.string "Oh, hello, {PLAYER}! Welcome!\p"
	.string "I've started bringing in items from\n"
	.string "distant lands.\p"
	.string "I've got some rare items in, too. Please\n"
	.string "have a look!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
# 34 "data/maps/TwoIsland/scripts.pory"
	.string "That fellow there, he moved here from\n"
	.string "CELADON CITY.\p"
	.string "He started up a shop with his younger\n"
	.string "brother.\p"
	.string "You have to wonder if he knew what he\n"
	.string "was getting into.$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
# 38 "data/maps/TwoIsland/scripts.pory"
	.string "The shopkeeper's brother took a job at\n"
	.string "the GAME CORNER.\p"
	.string "He's trying to pull together money so\n"
	.string "they can buy more merchandise.$"

TwoIsland_Text_BrunoCameToIslandWhileBack::
# 42 "data/maps/TwoIsland/scripts.pory"
	.string "Listen, listen. Did you know?\p"
	.string "A famous TRAINER came to the ISLAND a\n"
	.string "little while back.\p"
	.string "He's one of the ELITE FOUR. His name is\n"
	.string "BRUNO.\p"
	.string "He went away disappointed when he\n"
	.string "found out that they were all sold\l"
	.string "out of Rage Candybars.$"

TwoIsland_Text_BuyRareItemsHere::
# 46 "data/maps/TwoIsland/scripts.pory"
	.string "The discerning TRAINER knows to buy\n"
	.string "rare items here!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
# 50 "data/maps/TwoIsland/scripts.pory"
	.string "There's an old woman who lives in a\n"
	.string "cottage out on the cape.\p"
	.string "She gives the eye to POKéMON. It's a bit\n"
	.string "unnerving.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
# 54 "data/maps/TwoIsland/scripts.pory"
	.string "Boing! Boing! Have you tried the jumping\n"
	.string "game?\p"
	.string "The POKéMON you can enter… Boing!\p"
	.string "Some go boing!\p"
	.string "And some go boooooooing!\p"
	.string "Did you know that? Boing!$"
