TwoIsland_MapScripts::
	.byte 0


TwoIsland_EventScript_Beauty::
	end


TwoIsland_EventScript_Boy::
# 9 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_OldWomanLivesOutOnCape, MSGBOX_NPC
	end


TwoIsland_EventScript_Clerk::
	end


TwoIsland_EventScript_FastCurrentSign::
# 18 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_DangerFastCurrent, MSGBOX_SIGN
	end


TwoIsland_EventScript_IslandSign::
# 23 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_IslandSign, MSGBOX_SIGN
	end


TwoIsland_EventScript_JoyfulGameCornerSign::
# 28 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_JoyfulGameCornerSign, MSGBOX_SIGN
	end


TwoIsland_EventScript_LittleBoy::
# 33 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_HaveYouTriedJumpingGame, MSGBOX_NPC
	end


TwoIsland_EventScript_Sailor::
# 38 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_FellowMovedFromCeladonCity, MSGBOX_NPC
	end


TwoIsland_EventScript_SuperNerd::
# 43 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_BuyRareItemsHere, MSGBOX_NPC
	end


TwoIsland_EventScript_Woman::
# 48 "data/maps/TwoIsland/scripts.pory"
	msgbox TwoIsland_Text_ShopkeepersBrotherWorksGameCorner, MSGBOX_NPC
	end


TwoIsland_Text_IslandSign::
# 53 "data/maps/TwoIsland/scripts.pory"
	.string "TWO ISLAND Boon Island for Two$"

TwoIsland_Text_JoyfulGameCornerSign::
# 57 "data/maps/TwoIsland/scripts.pory"
	.string "Skip & Chomp! Joyful GAME CORNER$"

TwoIsland_Text_DangerFastCurrent::
# 61 "data/maps/TwoIsland/scripts.pory"
	.string "DANGER! FAST CURRENT! Fishing and\n"
	.string "surfing prohibited!$"

TwoIsland_Text_OldWomanLivesOutOnCape::
# 65 "data/maps/TwoIsland/scripts.pory"
	.string "There's an old woman who lives in\n"
	.string "a cottage out on the cape.\p"
	.string "She gives the eye to POKéMON.\n"
	.string "It's a bit unnerving.$"

TwoIsland_Text_HaveYouTriedJumpingGame::
# 69 "data/maps/TwoIsland/scripts.pory"
	.string "Boing! Boing!\n"
	.string "Have you tried the jumping game?\p"
	.string "The POKéMON you can enter…\n"
	.string "Boing!\p"
	.string "Some go boing!\p"
	.string "And some go boooooooing!\p"
	.string "Did you know that?\n"
	.string "Boing!$"

TwoIsland_Text_FellowMovedFromCeladonCity::
# 73 "data/maps/TwoIsland/scripts.pory"
	.string "That fellow there, he moved here\n"
	.string "from CELADON CITY.\p"
	.string "He started up a shop with his\n"
	.string "younger brother.\p"
	.string "You have to wonder if he knew what\n"
	.string "he was getting into.$"

TwoIsland_Text_BuyRareItemsHere::
# 77 "data/maps/TwoIsland/scripts.pory"
	.string "The discerning TRAINER knows to\n"
	.string "buy rare items here!$"

TwoIsland_Text_ShopkeepersBrotherWorksGameCorner::
# 81 "data/maps/TwoIsland/scripts.pory"
	.string "The shopkeeper's brother took\n"
	.string "a job at the GAME CORNER.\p"
	.string "He's trying to pull together money\n"
	.string "so they can buy more merchandise.$"
