TwoIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/TwoIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TwoIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/TwoIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


TwoIsland_PokemonCenter_1F_Text_HaveYouVisitedGameCorner::
# 7 "data/maps/TwoIsland_PokemonCenter_1F/scripts.pory"
	.string "Have you visited the GAME CORNER\n"
	.string "already?\p"
	.string "It's no good to go alone. You have to\n"
	.string "take a friend along.$"

TwoIsland_PokemonCenter_1F_Text_OldLadyLivesOutOnCape::
# 11 "data/maps/TwoIsland_PokemonCenter_1F/scripts.pory"
	.string "Not many people live on TWO ISLAND.\p"
	.string "There is this old lady who lives out on\n"
	.string "the cape.\p"
	.string "She's been there since I don't know\n"
	.string "when.$"
