Route110_TrickHousePuzzle6_MapScripts::
	.byte 0


Route110_TrickHousePuzzle6_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	msgbox Route110_TrickHousePuzzle6_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle6_EventScript_SmithNPC2::
# 51 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	msgbox Route110_TrickHousePuzzle6_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHousePuzzle6_Text_BennyDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_BennyDefeat$"

Route110_TrickHousePuzzle6_Text_BennyIntro::
# 9 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_BennyIntro$"

Route110_TrickHousePuzzle6_Text_BennyPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_BennyPostBattle$"

Route110_TrickHousePuzzle6_Text_SebastianDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SebastianDefeat$"

Route110_TrickHousePuzzle6_Text_SebastianIntro::
# 21 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SebastianIntro$"

Route110_TrickHousePuzzle6_Text_SebastianPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SebastianPostBattle$"

Route110_TrickHousePuzzle6_Text_SophiaDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SophiaDefeat$"

Route110_TrickHousePuzzle6_Text_SophiaIntro::
# 33 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SophiaIntro$"

Route110_TrickHousePuzzle6_Text_SophiaPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle6_Text_SophiaPostBattle$"

Route110_TrickHousePuzzle6_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHousePuzzle6_Text_SmithNPC2::
# 55 "data/maps/Route110_TrickHousePuzzle6/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
