TrainerTower_1F_MapScripts::
# 2 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerTower_OnResume
# 3 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TrainerTower_OnTransition
# 4 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerTower_OnFrame
	.byte 0


TrainerTower_1F_MapScripts::
# 8 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerTower_OnResume
# 9 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TrainerTower_OnTransition
# 10 "data/maps/TrainerTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerTower_OnFrame
	return

