BlackthornCity_MapScripts::
	.byte 0


BlackthornCity_EventScript_Sign1::
# 6 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_Sign1, MSGBOX_SIGN
	end


BlackthornCity_EventScript_Gym2::
# 15 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_Gym2, MSGBOX_SIGN
	end


BlackthornCity_EventScript_Sign3::
# 24 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_Sign3, MSGBOX_SIGN
	end


BlackthornCity_EventScript_Sign4::
# 33 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_Sign4, MSGBOX_SIGN
	end


BlackthornCity_EventScript_SmithNPC1::
# 42 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC1, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC2::
# 51 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC2, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC3::
# 60 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC3, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC4::
# 69 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC4, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC5::
# 78 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC5, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC6::
# 87 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC6, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC7::
# 96 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC7, MSGBOX_NPC
	end


BlackthornCity_EventScript_SmithNPC8::
# 105 "data/maps/BlackthornCity/scripts.pory"
	msgbox BlackthornCity_Text_SmithNPC8, MSGBOX_NPC
	end


BlackthornCity_Text_Sign1::
# 10 "data/maps/BlackthornCity/scripts.pory"
	.string "BlackthornCity Sign 1$"

BlackthornCity_Text_Gym2::
# 19 "data/maps/BlackthornCity/scripts.pory"
	.string "Blackthorn Gym$"

BlackthornCity_Text_Sign3::
# 28 "data/maps/BlackthornCity/scripts.pory"
	.string "BlackthornCity Sign 3$"

BlackthornCity_Text_Sign4::
# 37 "data/maps/BlackthornCity/scripts.pory"
	.string "BlackthornCity Sign 4$"

BlackthornCity_Text_SmithNPC1::
# 46 "data/maps/BlackthornCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

BlackthornCity_Text_SmithNPC2::
# 55 "data/maps/BlackthornCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

BlackthornCity_Text_SmithNPC3::
# 64 "data/maps/BlackthornCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

BlackthornCity_Text_SmithNPC4::
# 73 "data/maps/BlackthornCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

BlackthornCity_Text_SmithNPC5::
# 82 "data/maps/BlackthornCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

BlackthornCity_Text_SmithNPC6::
# 91 "data/maps/BlackthornCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

BlackthornCity_Text_SmithNPC7::
# 100 "data/maps/BlackthornCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

BlackthornCity_Text_SmithNPC8::
# 109 "data/maps/BlackthornCity/scripts.pory"
	.string "I know kung fu.$"
