GoldenrodCity_MapScripts::
	.byte 0


GoldenrodCity_EventScript_Sign1::
# 6 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign1, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign2::
# 15 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign2, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign3::
# 24 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign3, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign4::
# 33 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign4, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign5::
# 42 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign5, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign6::
# 51 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign6, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign7::
# 60 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign7, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign8::
# 69 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign8, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_Sign9::
# 78 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_Sign9, MSGBOX_SIGN
	end


GoldenrodCity_EventScript_SmithNPC1::
# 87 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC2::
# 96 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC3::
# 105 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC3, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC4::
# 114 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC4, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC5::
# 123 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC5, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC6::
# 132 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC6, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC7::
# 141 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC7, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC8::
# 150 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC8, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC9::
# 159 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC9, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC10::
# 168 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC10, MSGBOX_NPC
	end


GoldenrodCity_EventScript_SmithNPC11::
# 177 "data/maps/GoldenrodCity/scripts.pory"
	msgbox GoldenrodCity_Text_SmithNPC11, MSGBOX_NPC
	end


GoldenrodCity_Text_Sign1::
# 10 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 1$"

GoldenrodCity_Text_Sign2::
# 19 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 2$"

GoldenrodCity_Text_Sign3::
# 28 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 3$"

GoldenrodCity_Text_Sign4::
# 37 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 4$"

GoldenrodCity_Text_Sign5::
# 46 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 5$"

GoldenrodCity_Text_Sign6::
# 55 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 6$"

GoldenrodCity_Text_Sign7::
# 64 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 7$"

GoldenrodCity_Text_Sign8::
# 73 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 8$"

GoldenrodCity_Text_Sign9::
# 82 "data/maps/GoldenrodCity/scripts.pory"
	.string "GoldenrodCity Sign 9$"

GoldenrodCity_Text_SmithNPC1::
# 91 "data/maps/GoldenrodCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_Text_SmithNPC2::
# 100 "data/maps/GoldenrodCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

GoldenrodCity_Text_SmithNPC3::
# 109 "data/maps/GoldenrodCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

GoldenrodCity_Text_SmithNPC4::
# 118 "data/maps/GoldenrodCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

GoldenrodCity_Text_SmithNPC5::
# 127 "data/maps/GoldenrodCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

GoldenrodCity_Text_SmithNPC6::
# 136 "data/maps/GoldenrodCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

GoldenrodCity_Text_SmithNPC7::
# 145 "data/maps/GoldenrodCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

GoldenrodCity_Text_SmithNPC8::
# 154 "data/maps/GoldenrodCity/scripts.pory"
	.string "I know kung fu.$"

GoldenrodCity_Text_SmithNPC9::
# 163 "data/maps/GoldenrodCity/scripts.pory"
	.string "Dodge this.$"

GoldenrodCity_Text_SmithNPC10::
# 172 "data/maps/GoldenrodCity/scripts.pory"
	.string "Choice is an illusion created between\n"
	.string "those with power and those without.$"

GoldenrodCity_Text_SmithNPC11::
# 181 "data/maps/GoldenrodCity/scripts.pory"
	.string "Hope is an illusion, Mr. Anderson.$"
