FiveIsland_ResortGorgeous_House_MapScripts::
	.byte 0


FiveIsland_ResortGorgeous_House_EventScript_Butler::
# 5 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	msgbox FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun, MSGBOX_NPC
	end


FiveIsland_ResortGorgeous_House_EventScript_Selphy::
	end


FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
# 14 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: The smile of Lady SELPHY\n"
	.string "has the brilliance of the sun.\p"
	.string "Please, I beg you to bring joy\n"
	.string "to Lady SELPHY.$"
