FiveIsland_ResortGorgeous_House_MapScripts::
	.byte 0


FiveIsland_ResortGorgeous_House_Text_PleaseHearMyWish::
# 5 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "SELPHY: Oh? Do I know you from\n"
	.string "somewhere?\p"
	.string "Oh, but that doesn't matter.\p"
	.string "I am exquisitely bored. Please, hear my\n"
	.string "wish.$"

FiveIsland_ResortGorgeous_House_Text_WishToSeeMonPlease::
# 9 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "I wish to see a POKéMON. A darling\n"
	.string "{STR_VAR_1}.\p"
	.string "I want to see one right away. Please,\n"
	.string "make my wish come true.$"

FiveIsland_ResortGorgeous_House_Text_OhImTiredOfWaiting::
# 13 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "SELPHY: Oh, I'm tired of this. I'm tired\n"
	.string "of waiting for you.\p"
	.string "I'll forgive you this time, but please\n"
	.string "don't fail me next time.$"

FiveIsland_ResortGorgeous_House_Text_MonYouCaughtForMeThankYou::
# 17 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "SELPHY: Oh, hello, there.\p"
	.string "Oh, my gracious. That must be the\n"
	.string "{STR_VAR_1} you caught for me.\p"
	.string "Giggle… I see a resemblance to you.\p"
	.string "Thank you so kindly.\p"
	.string "… … … … … … Is something the matter?\p"
	.string "You may leave.\p"
	.string "… … … … … … Oh, fine. I understand now.\p"
	.string "SEBASTIAN! I need you here this\n"
	.string "instant!$"

FiveIsland_ResortGorgeous_House_Text_ButlerYesMyLady::
# 21 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: Yes, my lady.$"

FiveIsland_ResortGorgeous_House_Text_SelphyGiveTokenOfAppreciation::
# 25 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "SELPHY: See to it that this person is\n"
	.string "given a token of appreciation.$"

FiveIsland_ResortGorgeous_House_Text_ButlerIShallDoAsYouBid::
# 29 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: I shall do as you bid, my lady.$"

FiveIsland_ResortGorgeous_House_Text_ButlerPleaseAcceptThisAsHerThanks::
# 33 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: I sincerely thank you for\n"
	.string "pleasing Lady SELPHY.\p"
	.string "Please accept this as her thanks…$"

FiveIsland_ResortGorgeous_House_Text_ButlerBagAppearsToBeFull::
# 37 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: Your BAG appears to be\n"
	.string "unfortunately full.$"

FiveIsland_ResortGorgeous_House_Text_OhHowDisappointing::
# 41 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Oh… How disappointing.$"

FiveIsland_ResortGorgeous_House_Text_SelphyWishYouBestOfLuck::
# 45 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "SELPHY: I wish you the best of luck.$"

FiveIsland_ResortGorgeous_House_Text_LadySelphySmileHasBrillianceOfSun::
# 49 "data/maps/FiveIsland_ResortGorgeous_House/scripts.pory"
	.string "Butler: The smile of Lady SELPHY has\n"
	.string "the brilliance of the sun.\p"
	.string "Please, I beg you to bring joy to Lady\n"
	.string "SELPHY.$"
