FiveIsland_ResortGorgeous_House_MapScripts::
	.byte 0

FiveIsland_ResortGorgeous_House_EventScript_PokemonJournal::
	msgbox FiveIsland_ResortGorgeous_House_Text_SpecialFeatureBlaine, MSGBOX_SIGN
	end

FiveIsland_ResortGorgeous_House_Text_SpecialFeatureBlaine::
	.string "POKéMON JOURNAL\p"
	.string "Special Feature: CINNABAR GYM\n"
	.string "LEADER BLAINE!\p"
	.string "BLAINE is said to remove his dark\n"
	.string "shades only when he is thinking up\l"
	.string "new quiz questions.$"
