FiveIsland_LostCave_Room4_MapScripts::
	.byte 0


FiveIsland_LostCave_Room4_Text_LauraIntro::
# 5 "data/maps/FiveIsland_LostCave_Room4/scripts.pory"
	.string "I think there is a mysterious power at\n"
	.string "work in this cave.$"

FiveIsland_LostCave_Room4_Text_LauraDefeat::
# 9 "data/maps/FiveIsland_LostCave_Room4/scripts.pory"
	.string "If you don't go into the right tunnel,\n"
	.string "you won't get ahead.$"

FiveIsland_LostCave_Room4_Text_LauraPostBattle::
# 13 "data/maps/FiveIsland_LostCave_Room4/scripts.pory"
	.string "Earlier, a lady went into the caves\n"
	.string "ahead.$"
