Route16_MapScripts::
# 2 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route16_OnResume
# 3 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route16_OnTransition
# 4 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route16_OnWarp
	.byte 0


Route16_Text_LaoIntro::
# 8 "data/maps/Route16/scripts.pory"
	.string "What do you want?$"

Route16_Text_LaoDefeat::
# 12 "data/maps/Route16/scripts.pory"
	.string "Don't you dare laugh!$"

Route16_Text_LaoPostBattle::
# 16 "data/maps/Route16/scripts.pory"
	.string "We like just hanging here. What's it to\n"
	.string "you?$"

Route16_Text_KojiIntro::
# 20 "data/maps/Route16/scripts.pory"
	.string "Nice BIKE! Hand it over!$"

Route16_Text_KojiDefeat::
# 24 "data/maps/Route16/scripts.pory"
	.string "Knockout!$"

Route16_Text_KojiPostBattle::
# 28 "data/maps/Route16/scripts.pory"
	.string "Forget it, who needs your BIKE!$"

Route16_Text_LukeIntro::
# 32 "data/maps/Route16/scripts.pory"
	.string "Come out and play, little mouse!$"

Route16_Text_LukeDefeat::
# 36 "data/maps/Route16/scripts.pory"
	.string "You little rat!$"

Route16_Text_LukePostBattle::
# 40 "data/maps/Route16/scripts.pory"
	.string "I hate losing! Get out of my face!$"

Route16_Text_HideoIntro::
# 44 "data/maps/Route16/scripts.pory"
	.string "Hey, you just bumped me!$"

Route16_Text_HideoDefeat::
# 48 "data/maps/Route16/scripts.pory"
	.string "Kaboom!$"

Route16_Text_HideoPostBattle::
# 52 "data/maps/Route16/scripts.pory"
	.string "We'll always be hanging around here\n"
	.string "even if you don't like it.\p"
	.string "You can detour to VERMILION from\n"
	.string "FUCHSIA going along the coast.$"

Route16_Text_CamronIntro::
# 56 "data/maps/Route16/scripts.pory"
	.string "I'm feeling hungry and mean! I need a\n"
	.string "punching bag!$"

Route16_Text_CamronDefeat::
# 60 "data/maps/Route16/scripts.pory"
	.string "Bad, bad, bad!$"

Route16_Text_CamronPostBattle::
# 64 "data/maps/Route16/scripts.pory"
	.string "If I'm going to have POKMON, they may as\n"
	.string "well be ferocious.\p"
	.string "I'd use them to leave my enemies in\n"
	.string "tatters.$"

Route16_Text_RubenIntro::
# 68 "data/maps/Route16/scripts.pory"
	.string "Hey, there! Let's have ourselves a good\n"
	.string "time!$"

Route16_Text_RubenDefeat::
# 72 "data/maps/Route16/scripts.pory"
	.string "Don't make me mad!$"

Route16_Text_RubenPostBattle::
# 76 "data/maps/Route16/scripts.pory"
	.string "I get my kicks by harassing people with\n"
	.string "my stinking POKMON.\p"
	.string "They're great for startling people. And,\n"
	.string "they bite, too.$"

Route16_Text_MonSprawledOutInSlumber::
# 80 "data/maps/Route16/scripts.pory"
	.string "A POKMON is sprawled out in a deep and\n"
	.string "comfortable slumber.$"

Route16_Text_CyclingRoadSign::
# 84 "data/maps/Route16/scripts.pory"
	.string "Enjoy the slope! CYCLING ROAD$"

Route16_Text_RouteSign::
# 88 "data/maps/Route16/scripts.pory"
	.string "ROUTE 16 CELADON CITY - FUCHSIA CITY$"

Route16_Text_JedIntro::
# 92 "data/maps/Route16/scripts.pory"
	.string "JED: Our love knows no bounds. We're in\n"
	.string "love and we show it!$"

Route16_Text_JedDefeat::
# 96 "data/maps/Route16/scripts.pory"
	.string "JED: Oh, no! My love has seen me as a\n"
	.string "loser!$"

Route16_Text_JedPostBattle::
# 100 "data/maps/Route16/scripts.pory"
	.string "JED: Listen, LEA. You need to focus less\n"
	.string "on me.$"

Route16_Text_JedNotEnoughMons::
# 104 "data/maps/Route16/scripts.pory"
	.string "JED: You have just one POKMON? Is\n"
	.string "there no love in your heart?$"

Route16_Text_LeaIntro::
# 108 "data/maps/Route16/scripts.pory"
	.string "LEA: Sometimes, the intensity of our\n"
	.string "love scares me.$"

Route16_Text_LeaDefeat::
# 112 "data/maps/Route16/scripts.pory"
	.string "LEA: Ohh! But JED looks cool even in a\n"
	.string "loss!$"

Route16_Text_LeaPostBattle::
# 116 "data/maps/Route16/scripts.pory"
	.string "LEA: Ehehe, I'm sorry. JED is so cool.$"

Route16_Text_LeaNotEnoughMons::
# 120 "data/maps/Route16/scripts.pory"
	.string "LEA: Oh, you don't have two POKMON with\n"
	.string "you?\p"
	.string "Doesn't it feel lonely for you or your\n"
	.string "POKMON?$"
