Route16_MapScripts::
# 2 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route16_OnResume
# 3 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route16_OnTransition
# 4 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route16_OnWarp
	.byte 0


Route16_MapScripts::
# 8 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route16_OnResume
# 9 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route16_OnTransition
# 10 "data/maps/Route16/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, Route16_OnWarp
	return

