RustboroCity_House3_MapScripts::
	.byte 0


RustboroCity_House3_Text_IGivePerfectlySuitedNicknames::
# 5 "data/maps/RustboroCity_House3/scripts.pory"
	.string "For my own POKéMON, I give them\n"
	.string "perfectly suited nicknames!\p"
	.string "It's my expression of, uh… originality,\n"
	.string "yes, that's it!$"

RustboroCity_House3_Text_NamingPikachuPekachu::
# 9 "data/maps/RustboroCity_House3/scripts.pory"
	.string "But giving the name PEKACHU to a\n"
	.string "PIKACHU? It seems pointless.\p"
	.string "I suppose it is good to use a name\n"
	.string "that's easy to understand, but…$"

RustboroCity_House3_Text_Pekachu::
# 13 "data/maps/RustboroCity_House3/scripts.pory"
	.string "PEKACHU: Peka!$"
