RustboroCity_House3_MapScripts::
	.byte 0


RustboroCity_House3_EventScript_OldMan::
# 5 "data/maps/RustboroCity_House3/scripts.pory"
	msgbox RustboroCity_House3_Text_IGivePerfectlySuitedNicknames, MSGBOX_NPC
	end


RustboroCity_House3_EventScript_OldWoman::
# 10 "data/maps/RustboroCity_House3/scripts.pory"
	msgbox RustboroCity_House3_Text_NamingPikachuPekachu, MSGBOX_NPC
	end


RustboroCity_House3_EventScript_Pekachu::
# 15 "data/maps/RustboroCity_House3/scripts.pory"
	msgbox RustboroCity_House3_Text_Pekachu, MSGBOX_DEFAULT
	end


RustboroCity_House3_Text_Pekachu::
# 19 "data/maps/RustboroCity_House3/scripts.pory"
	.string "PEKACHU: Peka!$"

RustboroCity_House3_Text_NamingPikachuPekachu::
# 23 "data/maps/RustboroCity_House3/scripts.pory"
	.string "But giving the name PEKACHU to\n"
	.string "a PIKACHU? It seems pointless.\p"
	.string "I suppose it is good to use a name\n"
	.string "that's easy to understand, but…$"

RustboroCity_House3_Text_IGivePerfectlySuitedNicknames::
# 27 "data/maps/RustboroCity_House3/scripts.pory"
	.string "For my own POKéMON, I give them\n"
	.string "perfectly suited nicknames!\p"
	.string "It's my expression of, uh…\n"
	.string "originality, yes, that's it!$"
