UndergroundPath_WestEntrance_MapScripts::
	.byte 0


UndergroundPath_WestEntrance_EventScript_BaldingMan::
# 5 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
	msgbox UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon, MSGBOX_NPC
	end


UndergroundPath_WestEntrance_Text_SleepyMonNearCeladon::
# 10 "data/maps/UndergroundPath_WestEntrance/scripts.pory"
	.string "I heard a sleepy POKéMON appeared\n"
	.string "out near CELADON CITY, too.$"
