Route6_MapScripts::
	.byte 0


Route6_Text_RickyIntro::
# 5 "data/maps/Route6/scripts.pory"
	.string "Who's there? Quit listening in on us!$"

Route6_Text_RickyDefeat::
# 9 "data/maps/Route6/scripts.pory"
	.string "I just can't win!$"

Route6_Text_RickyPostBattle::
# 13 "data/maps/Route6/scripts.pory"
	.string "Whisper Whisper$"

Route6_Text_NancyIntro::
# 17 "data/maps/Route6/scripts.pory"
	.string "Excuse me! This is a private\n"
	.string "conversation!$"

Route6_Text_NancyDefeat::
# 21 "data/maps/Route6/scripts.pory"
	.string "Ugh! I hate losing.$"

Route6_Text_NancyPostBattle::
# 25 "data/maps/Route6/scripts.pory"
	.string "Whisper Whisper$"

Route6_Text_KeigoIntro::
# 29 "data/maps/Route6/scripts.pory"
	.string "There aren't many bugs out here.$"

Route6_Text_KeigoDefeat::
# 33 "data/maps/Route6/scripts.pory"
	.string "No! You're kidding!$"

Route6_Text_KeigoPostBattle::
# 37 "data/maps/Route6/scripts.pory"
	.string "I like bugs, so I'm going back to\n"
	.string "VIRIDIAN FOREST.$"

Route6_Text_JeffIntro::
# 41 "data/maps/Route6/scripts.pory"
	.string "Huh? You want to talk to me?$"

Route6_Text_JeffDefeat::
# 45 "data/maps/Route6/scripts.pory"
	.string "This stinks I couldn't beat your\n"
	.string "challenge$"

Route6_Text_JeffPostBattle::
# 49 "data/maps/Route6/scripts.pory"
	.string "I should bring more POKMON with me. I'll\n"
	.string "feel safer that way.$"

Route6_Text_IsabelleIntro::
# 53 "data/maps/Route6/scripts.pory"
	.string "Me? Well, okay. I'll play!$"

Route6_Text_IsabelleDefeat::
# 57 "data/maps/Route6/scripts.pory"
	.string "Things just didn't work$"

Route6_Text_IsabellePostBattle::
# 61 "data/maps/Route6/scripts.pory"
	.string "I want to get stronger. What's your\n"
	.string "secret?$"

Route6_Text_ElijahIntro::
# 65 "data/maps/Route6/scripts.pory"
	.string "I've never seen you around. Are you\n"
	.string "good?$"

Route6_Text_ElijahDefeat::
# 69 "data/maps/Route6/scripts.pory"
	.string "You're too good!$"

Route6_Text_ElijahPostBattle::
# 73 "data/maps/Route6/scripts.pory"
	.string "Are my POKMON weak? Or, am I just bad?\l"
	.string "Which do you think?$"

Route6_Text_UndergroundPathSign::
# 77 "data/maps/Route6/scripts.pory"
	.string "UNDERGROUND PATH CERULEAN CITY -\n"
	.string "VERMILION CITY$"
