Route132_MapScripts::
	.byte 0


Route132_EventScript_Dana::
# 5 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_DANA, Route132_Text_DanaIntro, Route132_Text_DanaDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_DanaPostBattle
	return


Route132_EventScript_Darcy::
# 10 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_DARCY, Route132_Text_DarcyIntro, Route132_Text_DarcyDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_DarcyPostBattle
	return


Route132_EventScript_Gilbert::
# 15 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_GILBERT, Route132_Text_GilbertIntro, Route132_Text_GilbertDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_GilbertPostBattle
	return


Route132_EventScript_Jonathan::
# 20 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_JONATHAN, Route132_Text_JonathanIntro, Route132_Text_JonathanDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_JonathanPostBattle
	return


Route132_EventScript_Kiyo::
# 25 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_KIYO, Route132_Text_KiyoIntro, Route132_Text_KiyoDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_KiyoPostBattle
	return


Route132_EventScript_Makayla::
# 30 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_MAKAYLA, Route132_Text_MakaylaIntro, Route132_Text_MakaylaDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_MakaylaPostBattle
	return


Route132_EventScript_Paxton::
# 35 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_PAXTON, Route132_Text_PaxtonIntro, Route132_Text_PaxtonDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_PaxtonPostBattle
	return


Route132_EventScript_Ronald::
# 40 "data/maps/Route132/scripts.pory"
	trainerbattle_double TRAINER_RONALD, Route132_Text_RonaldIntro, Route132_Text_RonaldDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/Route132/scripts.pory"
	msgbox Route132_Text_RonaldPostBattle
	return


Route132_Text_DanaDefeat::
# 46 "data/maps/Route132/scripts.pory"
	.string "Oh, please, no!$"

Route132_Text_DanaIntro::
# 50 "data/maps/Route132/scripts.pory"
	.string "I try not to swim where the currents\n"
	.string "are too strong.$"

Route132_Text_DanaPostBattle::
# 54 "data/maps/Route132/scripts.pory"
	.string "If I get swept away, I'll lose all my\n"
	.string "sense of place…$"

Route132_Text_DarcyDefeat::
# 58 "data/maps/Route132/scripts.pory"
	.string "Okay! I won't complain about other\n"
	.string "people being here.$"

Route132_Text_DarcyIntro::
# 62 "data/maps/Route132/scripts.pory"
	.string "I liked training here by myself. It's\n"
	.string "awful that all these people came!$"

Route132_Text_DarcyPostBattle::
# 66 "data/maps/Route132/scripts.pory"
	.string "I suppose I can partner up with that\n"
	.string "old man and challenge that other team.$"

Route132_Text_GilbertDefeat::
# 70 "data/maps/Route132/scripts.pory"
	.string "I crave more power…$"

Route132_Text_GilbertIntro::
# 74 "data/maps/Route132/scripts.pory"
	.string "I used to catch colds all the time as a\n"
	.string "kid, but I became totally fit after I\l"
	.string "started swimming.$"

Route132_Text_GilbertPostBattle::
# 78 "data/maps/Route132/scripts.pory"
	.string "TRAINERS travel the fields and\n"
	.string "mountains, so they must be fit, too.$"

Route132_Text_JonathanDefeat::
# 82 "data/maps/Route132/scripts.pory"
	.string "Wow! That's pretty strong, all right!$"

Route132_Text_JonathanIntro::
# 86 "data/maps/Route132/scripts.pory"
	.string "Someone's been watching me intently.\n"
	.string "Was it you?$"

Route132_Text_JonathanPostBattle::
# 90 "data/maps/Route132/scripts.pory"
	.string "I can't shake this feeling that\n"
	.string "someone's watching me.\p"
	.string "I can't concentrate!$"

Route132_Text_KiyoDefeat::
# 94 "data/maps/Route132/scripts.pory"
	.string "I lose. I will concede defeat.$"

Route132_Text_KiyoIntro::
# 98 "data/maps/Route132/scripts.pory"
	.string "I contemplate POKéMON 24 hours a day.\n"
	.string "How could you possibly beat me?$"

Route132_Text_KiyoPostBattle::
# 102 "data/maps/Route132/scripts.pory"
	.string "Urggh… You're a POKéMON fanatic, aren't\n"
	.string "you?\p"
	.string "You must contemplate POKéMON 24 hours\n"
	.string "a day, don't you?$"

Route132_Text_MakaylaDefeat::
# 106 "data/maps/Route132/scripts.pory"
	.string "Oh, I guess I wasn't good enough.$"

Route132_Text_MakaylaIntro::
# 110 "data/maps/Route132/scripts.pory"
	.string "I'm always with my husband, but I can\n"
	.string "win even without him.$"

Route132_Text_MakaylaPostBattle::
# 114 "data/maps/Route132/scripts.pory"
	.string "That young man over there looks just\n"
	.string "like my husband when he was young.\p"
	.string "He's making me blush!$"

Route132_Text_PaxtonDefeat::
# 118 "data/maps/Route132/scripts.pory"
	.string "Ah, I see that I couldn't manage to win\n"
	.string "on my own after all.$"

Route132_Text_PaxtonIntro::
# 122 "data/maps/Route132/scripts.pory"
	.string "Now where could my wife have gone? I'm\n"
	.string "always with her. I wonder if I can win on\l"
	.string "my own.$"

Route132_Text_PaxtonPostBattle::
# 126 "data/maps/Route132/scripts.pory"
	.string "My wife must be looking for me. I'd best\n"
	.string "go find her right away.$"

Route132_Text_RonaldDefeat::
# 130 "data/maps/Route132/scripts.pory"
	.string "Waah! I sank in defeat!$"

Route132_Text_RonaldIntro::
# 134 "data/maps/Route132/scripts.pory"
	.string "Win or lose, you'll never know until you\n"
	.string "try!$"

Route132_Text_RonaldPostBattle::
# 138 "data/maps/Route132/scripts.pory"
	.string "I never battle when I know I'll win. I\n"
	.string "like to battle at the razor's edge of\l"
	.string "victory and defeat!$"
