CeruleanCity_House1_MapScripts::
	.byte 0


CeruleanCity_House1_Text_BadgesHaveAmazingSecrets::
# 5 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "Only skilled TRAINERS can collect\n"
	.string "POKéMON BADGES.\p"
	.string "I see you have at least one.\p"
	.string "Those BADGES have amazing secrets, did\n"
	.string "you know?$"

CeruleanCity_House1_Text_DescribeWhichBadge::
# 9 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "Now then…\p"
	.string "Which of the eight BADGES should I\n"
	.string "describe?$"

CeruleanCity_House1_Text_ComeVisitAnytime::
# 13 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "Come visit me anytime you wish.$"

CeruleanCity_House1_Text_AttackStatFlash::
# 17 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "The ATTACK stat of all your POKéMON\n"
	.string "increases a little bit.\p"
	.string "It also lets you use the move FLASH\n"
	.string "outside of battle.$"

CeruleanCity_House1_Text_ObeyLv30Cut::
# 21 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "POKéMON up to Lv. 30 will obey you.\p"
	.string "That includes even outsiders you\n"
	.string "obtain in trades.\p"
	.string "POKéMON of higher levels will be unruly\n"
	.string "in battle, however.\p"
	.string "It also lets you use the move CUT\n"
	.string "outside of battle.$"

CeruleanCity_House1_Text_SpeedStatFly::
# 25 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "The SPEED stat of all your POKéMON\n"
	.string "increases a little bit.\p"
	.string "It also lets you use the move FLY\n"
	.string "outside of battle.$"

CeruleanCity_House1_Text_ObeyLv50Strength::
# 29 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "POKéMON up to Lv. 50 will obey you.\p"
	.string "That includes even outsiders you\n"
	.string "obtain in trades.\p"
	.string "POKéMON of higher levels will be unruly\n"
	.string "in battle, however.\p"
	.string "It also lets you use the move STRENGTH\n"
	.string "outside of battle.$"

CeruleanCity_House1_Text_DefenseStatSurf::
# 33 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "The DEFENSE stat of all your POKéMON\n"
	.string "increases a little bit.\p"
	.string "It also lets you use the move SURF\n"
	.string "outside of battle.$"

CeruleanCity_House1_Text_ObeyLv70RockSmash::
# 37 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "POKéMON up to Lv. 70 will obey you.\p"
	.string "That includes even outsiders you\n"
	.string "obtain in trades.\p"
	.string "POKéMON of higher levels will be unruly\n"
	.string "in battle, however.\p"
	.string "It also lets you use the move ROCK\n"
	.string "SMASH outside of battle.$"

CeruleanCity_House1_Text_SpStatsWaterfall::
# 41 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "The SP. ATK and SP. DEF stats of all your\n"
	.string "POKéMON rise a little bit.\p"
	.string "It also lets you use the move\n"
	.string "WATERFALL outside of battle.$"

CeruleanCity_House1_Text_AllMonsWillObeyYou::
# 45 "data/maps/CeruleanCity_House1/scripts.pory"
	.string "All POKéMON will obey you!$"
