ViridianCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/ViridianCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ViridianCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/ViridianCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


ViridianCity_PokemonCenter_1F_Text_FeelFreeToUsePC::
# 7 "data/maps/ViridianCity_PokemonCenter_1F/scripts.pory"
	.string "Please feel free to use that PC in the\n"
	.string "corner.\p"
	.string "The receptionist told me so. It's so\n"
	.string "kind of her!$"

ViridianCity_PokemonCenter_1F_Text_PokeCenterInEveryTown::
# 11 "data/maps/ViridianCity_PokemonCenter_1F/scripts.pory"
	.string "There's a POKMON CENTER in every town\n"
	.string "ahead.\p"
	.string "They charge no money, so don't be shy\n"
	.string "about healing POKMON.$"

ViridianCity_PokemonCenter_1F_Text_PokeCentersHealMons::
# 15 "data/maps/ViridianCity_PokemonCenter_1F/scripts.pory"
	.string "POKMON CENTERS heal your tired, hurt, or\n"
	.string "fainted POKMON.\p"
	.string "They make all POKMON completely\n"
	.string "healthy.$"
