Route3_MapScripts::
	.byte 0


Route3_Text_TunnelFromCeruleanTiring::
# 5 "data/maps/Route3/scripts.pory"
	.string "Whew… I better take a rest… Groan…\p"
	.string "That tunnel from CERULEAN takes a lot\n"
	.string "out of you!$"

Route3_Text_ColtonIntro::
# 9 "data/maps/Route3/scripts.pory"
	.string "Hey! I saw you in VIRIDIAN FOREST!$"

Route3_Text_ColtonDefeat::
# 13 "data/maps/Route3/scripts.pory"
	.string "You beat me again!$"

Route3_Text_ColtonPostBattle::
# 17 "data/maps/Route3/scripts.pory"
	.string "There are other kinds of POKéMON than\n"
	.string "the ones you find in forests.$"

Route3_Text_BenIntro::
# 21 "data/maps/Route3/scripts.pory"
	.string "Hi! I like shorts!\p"
	.string "They're delightfully comfy and easy to\n"
	.string "wear!$"

Route3_Text_BenDefeat::
# 25 "data/maps/Route3/scripts.pory"
	.string "I don't believe it!$"

Route3_Text_BenPostBattle::
# 29 "data/maps/Route3/scripts.pory"
	.string "Are you using a POKéMON CENTER's PC for\n"
	.string "storing your POKéMON?\p"
	.string "Each BOX can hold up to 30 POKéMON.$"

Route3_Text_JaniceIntro::
# 33 "data/maps/Route3/scripts.pory"
	.string "Excuse me! You looked at me, didn't you?$"

Route3_Text_JaniceDefeat::
# 37 "data/maps/Route3/scripts.pory"
	.string "You're mean!$"

Route3_Text_JanicePostBattle::
# 41 "data/maps/Route3/scripts.pory"
	.string "You shouldn't be staring if you don't\n"
	.string "want to battle!$"

Route3_Text_GregIntro::
# 45 "data/maps/Route3/scripts.pory"
	.string "Are you a TRAINER? Let's get with it\n"
	.string "right away!$"

Route3_Text_GregDefeat::
# 49 "data/maps/Route3/scripts.pory"
	.string "If I had new POKéMON, I would've won!$"

Route3_Text_GregPostBattle::
# 53 "data/maps/Route3/scripts.pory"
	.string "If a POKéMON BOX on the PC gets full,\n"
	.string "just switch to another BOX.$"

Route3_Text_SallyIntro::
# 57 "data/maps/Route3/scripts.pory"
	.string "That look you gave me… It's so\n"
	.string "intriguing!$"

Route3_Text_SallyDefeat::
# 61 "data/maps/Route3/scripts.pory"
	.string "Be nice!$"

Route3_Text_SallyPostBattle::
# 65 "data/maps/Route3/scripts.pory"
	.string "You can avoid battles by not letting\n"
	.string "TRAINERS see you.$"

Route3_Text_CalvinIntro::
# 69 "data/maps/Route3/scripts.pory"
	.string "Hey! You're not wearing shorts! What's\n"
	.string "wrong with you?$"

Route3_Text_CalvinDefeat::
# 73 "data/maps/Route3/scripts.pory"
	.string "Lost! Lost! Lost!$"

Route3_Text_CalvinPostBattle::
# 77 "data/maps/Route3/scripts.pory"
	.string "I always wear shorts, even in winter.\n"
	.string "That's my policy.$"

Route3_Text_JamesIntro::
# 81 "data/maps/Route3/scripts.pory"
	.string "I'll battle you with the POKéMON I just\n"
	.string "caught.$"

Route3_Text_JamesDefeat::
# 85 "data/maps/Route3/scripts.pory"
	.string "Done like dinner!$"

Route3_Text_JamesPostBattle::
# 89 "data/maps/Route3/scripts.pory"
	.string "Trained POKéMON are stronger than the\n"
	.string "wild ones.$"

Route3_Text_RobinIntro::
# 93 "data/maps/Route3/scripts.pory"
	.string "Eek! Did you touch me?$"

Route3_Text_RobinDefeat::
# 97 "data/maps/Route3/scripts.pory"
	.string "That's it?$"

Route3_Text_RobinPostBattle::
# 101 "data/maps/Route3/scripts.pory"
	.string "ROUTE 4 is at the foot of MT. MOON.$"

Route3_Text_RouteSign::
# 105 "data/maps/Route3/scripts.pory"
	.string "ROUTE 3 MT. MOON AHEAD$"
