SevenIsland_Mart_MapScripts::
	.byte 0


SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
# 5 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "POKéMON have personalities of their\n"
	.string "own, just like people.\p"
	.string "My PIKACHU has a HASTY nature, so it\n"
	.string "grew to be a speedy POKéMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
# 9 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "Okay, preparations are complete for me\n"
	.string "to explore the RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
# 13 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "I need to fish on SEVEN ISLAND.\p"
	.string "That will complete my fishing tour of\n"
	.string "the SEVII ISLANDS.\p"
	.string "I'd better stock up on some POKé BALLS\n"
	.string "first, though.$"
