SevenIsland_Mart_MapScripts::
	.byte 0


SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
# 5 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "POKMON have personalities of their own,\n"
	.string "just like people.\p"
	.string "My PIKACHU has a HASTY nature, so it\n"
	.string "grew to be a speedy POKMON.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
# 9 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "Okay, preparations are complete for me\n"
	.string "to explore the RUINS.$"

SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
# 13 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "I need to fish on SEVEN ISLAND.\p"
	.string "That will complete my fishing tour of\n"
	.string "the SEVII ISLANDS.\p"
	.string "I'd better stock up on some POK BALLS\n"
	.string "first, though.$"
