SevenIsland_Mart_MapScripts::
	.byte 0


SevenIsland_Mart_EventScript_Clerk::
	end


SevenIsland_Mart_EventScript_Fisher::
# 9 "data/maps/SevenIsland_Mart/scripts.pory"
	msgbox SevenIsland_Mart_Text_NeedToFishOnSevenIsland, MSGBOX_NPC
	end


SevenIsland_Mart_EventScript_Hiker::
# 14 "data/maps/SevenIsland_Mart/scripts.pory"
	msgbox SevenIsland_Mart_Text_PreparationsCompleteForRuins, MSGBOX_NPC
	end


SevenIsland_Mart_EventScript_Lass::
# 19 "data/maps/SevenIsland_Mart/scripts.pory"
	msgbox SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn, MSGBOX_NPC
	end


SevenIsland_Mart_Text_NeedToFishOnSevenIsland::
# 24 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "I need to fish on SEVEN ISLAND.\p"
	.string "That will complete my fishing tour\n"
	.string "of the SEVII ISLANDS.\p"
	.string "I'd better stock up on some\n"
	.string "POKé BALLS first, though.$"

SevenIsland_Mart_Text_PreparationsCompleteForRuins::
# 28 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "Okay, preparations are complete\n"
	.string "for me to explore the RUINS.$"

SevenIsland_Mart_Text_MonHavePersonalitiesOfTheirOwn::
# 32 "data/maps/SevenIsland_Mart/scripts.pory"
	.string "POKéMON have personalities of their\n"
	.string "own, just like people.\p"
	.string "My PIKACHU has a HASTY nature,\n"
	.string "so it grew to be a speedy POKéMON.$"
