VictoryRoad_3F_MapScripts::
# 2 "data/maps/VictoryRoad_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, VictoryRoad_3F_OnLoad
	.byte 0


Text_DoubleEdgeTeach::
# 6 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "You should be proud of yourself, having\n"
	.string "battled your way through\l"
	.string "VICTORY ROAD so courageously.\p"
	.string "In recognition of your feat, I'll teach\n"
	.string "you DOUBLE-EDGE.\p"
	.string "Would you like me to teach that\n"
	.string "technique?$"

Text_DoubleEdgeDeclined::
# 10 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "I'll teach you the technique anytime.$"

Text_DoubleEdgeWhichMon::
# 14 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "Which POKéMON should I teach\n"
	.string "DOUBLE-EDGE?$"

Text_DoubleEdgeTaught::
# 18 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "Keep that drive going for the POKéMON\n"
	.string "LEAGUE!\p"
	.string "Take a run at them and knock 'em out!$"

VictoryRoad_3F_Text_GeorgeIntro::
# 22 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "I heard rumors of a child prodigy.$"

VictoryRoad_3F_Text_GeorgeDefeat::
# 26 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "The rumors were true!$"

VictoryRoad_3F_Text_GeorgePostBattle::
# 30 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "So, it was you who beat GIOVANNI of\n"
	.string "TEAM ROCKET?$"

VictoryRoad_3F_Text_AlexaIntro::
# 34 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "TRAINERS live to seek stronger\n"
	.string "opponents.$"

VictoryRoad_3F_Text_AlexaDefeat::
# 38 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "Oh! So strong!$"

VictoryRoad_3F_Text_AlexaPostBattle::
# 42 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "By fighting tough battles, you get\n"
	.string "stronger.$"

VictoryRoad_3F_Text_CarolineIntro::
# 46 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "I'll show you just how good you are. Not!$"

VictoryRoad_3F_Text_CarolineDefeat::
# 50 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "I'm furious!$"

VictoryRoad_3F_Text_CarolinePostBattle::
# 54 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "You showed me just how good I was…$"

VictoryRoad_3F_Text_ColbyIntro::
# 58 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "Only the chosen can pass here!$"

VictoryRoad_3F_Text_ColbyDefeat::
# 62 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "I don't believe it!$"

VictoryRoad_3F_Text_ColbyPostBattle::
# 66 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "All TRAINERS here are headed to the\n"
	.string "POKéMON LEAGUE.\p"
	.string "Don't let down your guard.$"

VictoryRoad_3F_Text_RayIntro::
# 70 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "RAY: Together, the two of us are\n"
	.string "destined for greatness!$"

VictoryRoad_3F_Text_RayDefeat::
# 74 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "RAY: Ludicrous! This can't be!$"

VictoryRoad_3F_Text_RayPostBattle::
# 78 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "RAY: You've beaten us. Greatness\n"
	.string "remains elusive…$"

VictoryRoad_3F_Text_RayNotEnoughMons::
# 82 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "RAY: Together, the two of us are\n"
	.string "striving for the pinnacle.\p"
	.string "We need you to bring two POKéMON into\n"
	.string "battle with us.$"

VictoryRoad_3F_Text_TyraIntro::
# 86 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "TYRA: We're trying to become champions\n"
	.string "together.$"

VictoryRoad_3F_Text_TyraDefeat::
# 90 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "TYRA: Oh, but…$"

VictoryRoad_3F_Text_TyraPostBattle::
# 94 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "TYRA: You've taught me that power can\n"
	.string "be infinite in shape and form.$"

VictoryRoad_3F_Text_TyraNotEnoughMons::
# 98 "data/maps/VictoryRoad_3F/scripts.pory"
	.string "TYRA: You can't battle with us if you\n"
	.string "have only one POKéMON.$"
