MirageTower_3F_MapScripts::
# 2 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CaveHole_CheckFallDownHole
# 3 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CaveHole_FixCrackedGround
# 4 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MirageTower_3F_SetHoleWarp
	.byte 0


MirageTower_3F_MapScripts::
# 8 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, CaveHole_CheckFallDownHole
# 9 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CaveHole_FixCrackedGround
# 10 "data/maps/MirageTower_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, MirageTower_3F_SetHoleWarp
	return

