FiveIsland_MapScripts::
# 2 "data/maps/FiveIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FiveIsland_OnTransition
	.byte 0


FiveIsland_Text_IslandSign::
# 6 "data/maps/FiveIsland/scripts.pory"
	.string "FIVE ISLAND Chrono Island: Where Time\n"
	.string "Goes$"

FiveIsland_Text_WeirdBuildingInMeadow::
# 10 "data/maps/FiveIsland/scripts.pory"
	.string "Oh, this stinks. I wanted to play in the\n"
	.string "MEADOW.\p"
	.string "But they put up a weird building on it,\n"
	.string "so I can't play there.$"

FiveIsland_Text_BeenGettingBusierAroundHere::
# 14 "data/maps/FiveIsland/scripts.pory"
	.string "It's been getting busier around these\n"
	.string "parts lately.\p"
	.string "I haven't been catching many good fish\n"
	.string "lately, either.$"
