ViridianForest_MapScripts::
# 2 "data/maps/ViridianForest/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ViridianForest_OnTransition
	.byte 0


ViridianForest_Text_FriendsItchingToBattle::
# 6 "data/maps/ViridianForest/scripts.pory"
	.string "I came here with some friends to catch\n"
	.string "us some BUG POKMON!\p"
	.string "They're all itching to get into some\n"
	.string "POKMON battles!$"

ViridianForest_Text_RickIntro::
# 10 "data/maps/ViridianForest/scripts.pory"
	.string "Hey! You have POKMON! Come on!\l"
	.string "Let's battle 'em!$"

ViridianForest_Text_RickDefeat::
# 14 "data/maps/ViridianForest/scripts.pory"
	.string "No! CATERPIE can't hack it!$"

ViridianForest_Text_RickPostBattle::
# 18 "data/maps/ViridianForest/scripts.pory"
	.string "Ssh! You'll scare the bugs away. Another\n"
	.string "time, okay?$"

ViridianForest_Text_DougIntro::
# 22 "data/maps/ViridianForest/scripts.pory"
	.string "Yo! You can't jam out if you're a\l"
	.string "POKMON TRAINER!$"

ViridianForest_Text_DougDefeat::
# 26 "data/maps/ViridianForest/scripts.pory"
	.string "Huh? I ran out of POKMON!$"

ViridianForest_Text_DougPostBattle::
# 30 "data/maps/ViridianForest/scripts.pory"
	.string "That totally stinks! I'm going to catch\n"
	.string "some stronger ones!$"

ViridianForest_Text_SammyIntro::
# 34 "data/maps/ViridianForest/scripts.pory"
	.string "Hey, wait up! What's the hurry? Why the\n"
	.string "rush?$"

ViridianForest_Text_SammyDefeat::
# 38 "data/maps/ViridianForest/scripts.pory"
	.string "I give! You're good at this!$"

ViridianForest_Text_SammyPostBattle::
# 42 "data/maps/ViridianForest/scripts.pory"
	.string "Sometimes, you can find stuff on the\n"
	.string "ground.\p"
	.string "I'm looking for the stuff I dropped. Can\n"
	.string "you help me?$"

ViridianForest_Text_AnthonyIntro::
# 46 "data/maps/ViridianForest/scripts.pory"
	.string "I might be little, but I won't like it if\n"
	.string "you go easy on me!$"

ViridianForest_Text_AnthonyDefeat::
# 50 "data/maps/ViridianForest/scripts.pory"
	.string "Oh, boo. Nothing went right.$"

ViridianForest_Text_AnthonyPostBattle::
# 54 "data/maps/ViridianForest/scripts.pory"
	.string "I lost some of my allowance$"

ViridianForest_Text_CharlieIntro::
# 58 "data/maps/ViridianForest/scripts.pory"
	.string "Did you know that POKMON evolve?$"

ViridianForest_Text_CharlieDefeat::
# 62 "data/maps/ViridianForest/scripts.pory"
	.string "Oh! I lost!$"

ViridianForest_Text_CharliePostBattle::
# 66 "data/maps/ViridianForest/scripts.pory"
	.string "BUG POKMON evolve quickly. They're a lot\n"
	.string "of fun!$"

ViridianForest_Text_RanOutOfPokeBalls::
# 70 "data/maps/ViridianForest/scripts.pory"
	.string "I was throwing POK BALLS to catch\n"
	.string "POKMON, and I ran out.\p"
	.string "That's why you can never have too many\n"
	.string "POK BALLS.$"

ViridianForest_Text_AvoidGrassyAreasWhenWeak::
# 74 "data/maps/ViridianForest/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "If your POKMON are weak and you want to\n"
	.string "avoid battles, stay away\l"
	.string "from grassy areas!$"

ViridianForest_Text_UseAntidoteForPoison::
# 78 "data/maps/ViridianForest/scripts.pory"
	.string "For poison, use ANTIDOTE! Get it at\n"
	.string "POKMON MARTS!$"

ViridianForest_Text_ContactOakViaPCToRatePokedex::
# 82 "data/maps/ViridianForest/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Contact PROF. OAK via a PC to get your\n"
	.string "POKDEX evaluated!$"

ViridianForest_Text_CantCatchOwnedMons::
# 86 "data/maps/ViridianForest/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "You can't catch a POKMON that belongs\n"
	.string "to someone else.\p"
	.string "Throw POK BALLS only at wild POKMON to\n"
	.string "catch them!$"

ViridianForest_Text_WeakenMonsBeforeCapture::
# 90 "data/maps/ViridianForest/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Weaken POKMON before attempting\n"
	.string "capture!\p"
	.string "When healthy, they may escape!$"

ViridianForest_Text_LeavingViridianForest::
# 94 "data/maps/ViridianForest/scripts.pory"
	.string "LEAVING VIRIDIAN FOREST PEWTER CITY\n"
	.string "AHEAD$"
