AbandonedShip_Rooms_1F_MapScripts::
	.byte 0


AbandonedShip_Rooms_1F_Text_TakingALookAround::
# 5 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Ships of this sort are rare, so I'm\n"
	.string "taking a look around.\p"
	.string "Hmhm There appear to be other cabins$"

AbandonedShip_Rooms_1F_Text_ThaliaIntro::
# 9 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "What on earth would compel you to come\n"
	.string "here? You must be curious!$"

AbandonedShip_Rooms_1F_Text_ThaliaDefeat::
# 13 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Not just curious, but also strong$"

AbandonedShip_Rooms_1F_Text_ThaliaPostBattle::
# 17 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "The man next door\p"
	.string "He says he's just sightseeing, but I\n"
	.string "don't know about that.$"

AbandonedShip_Rooms_1F_Text_ThaliaRegister::
# 21 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "You're such a tough TRAINER! Let me\n"
	.string "register you as a memento!$"

AbandonedShip_Rooms_1F_Text_ThaliaRematchIntro::
# 25 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "What on earth would compel you to come\n"
	.string "back? You must really be curious!$"

AbandonedShip_Rooms_1F_Text_ThaliaRematchDefeat::
# 29 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Aren't you too strong?$"

AbandonedShip_Rooms_1F_Text_ThaliaPostRematch::
# 33 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "I'm sure that man's up to something! He\n"
	.string "just acts so suspiciously!$"

AbandonedShip_Rooms_1F_Text_DemetriusIntro::
# 37 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Waaah! I've been found! Huh?$"

AbandonedShip_Rooms_1F_Text_DemetriusDefeat::
# 41 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Oh, you're not my mom.$"

AbandonedShip_Rooms_1F_Text_DemetriusPostBattle::
# 45 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "I'm in trouble with my mom, so I ran. Keep\n"
	.string "it a secret where I am!$"
