AbandonedShip_Rooms_1F_MapScripts::
	.byte 0


AbandonedShip_Rooms_1F_MapScripts::
	return


AbandonedShip_Rooms_1F_Text_TakingALookAround::
# 8 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Ships of this sort are rare, so I'm\n"
	.string "taking a look around.\p"
	.string "Hmhm… There appear to be other cabins…$"

AbandonedShip_Rooms_1F_Text_ThaliaIntro::
# 12 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "What on earth would compel you to come\n"
	.string "here? You must be curious!$"

AbandonedShip_Rooms_1F_Text_ThaliaDefeat::
# 16 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Not just curious, but also strong…$"

AbandonedShip_Rooms_1F_Text_ThaliaPostBattle::
# 20 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "The man next door…\p"
	.string "He says he's just sightseeing, but I\n"
	.string "don't know about that.$"

AbandonedShip_Rooms_1F_Text_ThaliaRegister::
# 24 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "You're such a tough TRAINER! Let me\n"
	.string "register you as a memento!$"

AbandonedShip_Rooms_1F_Text_ThaliaRematchIntro::
# 28 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "What on earth would compel you to come\n"
	.string "back? You must really be curious!$"

AbandonedShip_Rooms_1F_Text_ThaliaRematchDefeat::
# 32 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Aren't you too strong?$"

AbandonedShip_Rooms_1F_Text_ThaliaPostRematch::
# 36 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "I'm sure that man's up to something! He\n"
	.string "just acts so suspiciously!$"

AbandonedShip_Rooms_1F_Text_DemetriusIntro::
# 40 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Waaah! I've been found! …Huh?$"

AbandonedShip_Rooms_1F_Text_DemetriusDefeat::
# 44 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "Oh, you're not my mom.$"

AbandonedShip_Rooms_1F_Text_DemetriusPostBattle::
# 48 "data/maps/AbandonedShip_Rooms_1F/scripts.pory"
	.string "I'm in trouble with my mom, so I ran. Keep\n"
	.string "it a secret where I am!$"
