MauvilleCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/MauvilleCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MauvilleCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/MauvilleCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


MauvilleCity_PokemonCenter_1F_Text_ManOverThereSaysWeirdThings::
# 7 "data/maps/MauvilleCity_PokemonCenter_1F/scripts.pory"
	.string "That man over there, he says weird\n"
	.string "things!\p"
	.string "He's funny in a weird way. I doubt I'll\n"
	.string "forget about him!$"

MauvilleCity_PokemonCenter_1F_Text_MyDataUpdatedFromRecordCorner::
# 11 "data/maps/MauvilleCity_PokemonCenter_1F/scripts.pory"
	.string "When I accessed the RECORD CORNER, the\n"
	.string "data for what's hot in DEWFORD\l"
	.string "got updated.\p"
	.string "Now that bit of data is the same as my\n"
	.string "friend's!$"

MauvilleCity_PokemonCenter_1F_Text_RecordCornerSoundsFun::
# 15 "data/maps/MauvilleCity_PokemonCenter_1F/scripts.pory"
	.string "A RECORD CORNER opened upstairs in the\n"
	.string "POKéMON CENTER.\p"
	.string "I don't know what it's about, but it\n"
	.string "sounds fun. I'll go check it out!$"
