MauvilleCity_Gym_MapScripts::
# 2 "data/maps/MauvilleCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MauvilleCity_Gym_OnLoad
	.byte 0


MauvilleCity_Gym_MapScripts::
# 6 "data/maps/MauvilleCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MauvilleCity_Gym_OnLoad
	return


MauvilleCity_Gym_Text_GymGuideAdvice::
# 10 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Hey, how's it going, CHAMPION- bound\n"
	.string "{PLAYER}?\p"
	.string "WATTSON, the LEADER of MAUVILLE GYM,\n"
	.string "uses ELECTRIC-type POKéMON.\p"
	.string "If you challenge him with WATER-type\n"
	.string "POKéMON, he'll zap them! Bzzt!\p"
	.string "And, he's put in switch-controlled\n"
	.string "doors all over his GYM! Eccentric!\p"
	.string "Hey, go for it!$"

MauvilleCity_Gym_Text_GymGuidePostVictory::
# 14 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Whoa, you're electrifying! You've\n"
	.string "powered the door open!$"

MauvilleCity_Gym_Text_KirkIntro::
# 18 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "My electric soul, it'll shatter your\n"
	.string "dreams whole, whoa-yeahah!$"

MauvilleCity_Gym_Text_KirkDefeat::
# 22 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "That was plugged in, amped up,\n"
	.string "over-driven electric, man!$"

MauvilleCity_Gym_Text_KirkPostBattle::
# 26 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "POKéMON and rock, it's all about heart,\n"
	.string "whoa-yeah!$"

MauvilleCity_Gym_Text_ShawnIntro::
# 30 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I trained under WATTSON! There ain't no\n"
	.string "way I'll lose easily!$"

MauvilleCity_Gym_Text_ShawnDefeat::
# 34 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Unplugged and turned off…$"

MauvilleCity_Gym_Text_ShawnPostBattle::
# 38 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON, our GYM LEADER, has been\n"
	.string "around for a long, long time.\p"
	.string "He was battling even before your daddy\n"
	.string "was born, that tough coot.$"

MauvilleCity_Gym_Text_BenIntro::
# 42 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "This GYM's got puzzles! Isn't it fun?$"

MauvilleCity_Gym_Text_BenDefeat::
# 46 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "It's no fun to lose…$"

MauvilleCity_Gym_Text_BenPostBattle::
# 50 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON says he likes setting up little\n"
	.string "traps with switches.$"

MauvilleCity_Gym_Text_VivianIntro::
# 54 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "With my charm and my POKéMON's moves,\n"
	.string "you'll be shocked!$"

MauvilleCity_Gym_Text_VivianDefeat::
# 58 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I'm shocked by your power!$"

MauvilleCity_Gym_Text_VivianPostBattle::
# 62 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I've heard that MAUVILLE was founded\n"
	.string "by WATTSON.\p"
	.string "He was a TRAINER long before we became\n"
	.string "TRAINERS.\l"
	.string "He must know all sorts of things!$"

MauvilleCity_Gym_Text_AngeloIntro::
# 66 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I love shiny things!$"

MauvilleCity_Gym_Text_AngeloDefeat::
# 70 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Oh… My eyes are frazzled…$"

MauvilleCity_Gym_Text_AngeloPostBattle::
# 74 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "MAUVILLE GYM's WATTSON has a shiny\n"
	.string "forehead. It makes me happy!$"

MauvilleCity_Gym_Text_WattsonIntro::
# 78 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I've given up on my plans to convert the\n"
	.string "city, I have.\p"
	.string "And so, I put my time into making door\n"
	.string "traps in my GYM.\p"
	.string "Oh? Now, what are you doing here?\p"
	.string "What's that? You say you've gotten\n"
	.string "past all my rigged doors?\p"
	.string "Wahahahah! Now, that is amusing!\p"
	.string "Then, I, WATTSON, the LEADER of\n"
	.string "MAUVILLE GYM, shall electrify you!$"

MauvilleCity_Gym_Text_WattsonDefeat::
# 82 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Wahahahah! Fine, I lost!\p"
	.string "You ended up giving me a thrill! Take\n"
	.string "this BADGE!$"

MauvilleCity_Gym_Text_ReceivedDynamoBadge::
# 86 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "{PLAYER} received the DYNAMO BADGE\n"
	.string "from WATTSON.$"

MauvilleCity_Gym_Text_ExplainDynamoBadgeTakeThis::
# 90 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "With the DYNAMO BADGE, POKéMON can use\n"
	.string "ROCK SMASH out of battle.\p"
	.string "And, it will make your POKéMON a little\n"
	.string "bit faster, too.\p"
	.string "Hmm… You should take this, too!$"

MauvilleCity_Gym_Text_ExplainShockWave::
# 94 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "That TM34 there contains SHOCK WAVE.\p"
	.string "It's a trustworthy move that never\n"
	.string "misses! You can count on it!\p"
	.string "… … … … … …$"

MauvilleCity_Gym_Text_RegisteredWattson::
# 98 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Registered GYM LEADER WATTSON in the\n"
	.string "POKéNAV.$"

MauvilleCity_Gym_Text_WattsonPostBattle::
# 102 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "I swell with optimism, seeing a promising\n"
	.string "young TRAINER like you!$"

MauvilleCity_Gym_Text_WattsonGoForthAndEndeavor::
# 106 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Wahahahah! Go forth and endeavor,\n"
	.string "youngster!$"

MauvilleCity_Gym_Text_GymStatue::
# 110 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "MAUVILLE CITY POKéMON GYM$"

MauvilleCity_Gym_Text_GymStatueCertified::
# 114 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "MAUVILLE CITY POKéMON GYM\p"
	.string "WATTSON'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

MauvilleCity_Gym_Text_WattsonPreRematch::
# 118 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON: Ah-ha! Here at last! I know\n"
	.string "what you want.\l"
	.string "You want to battle my POKéMON!\p"
	.string "Wahahahaha!\p"
	.string "I'll make sparks fly from you! Don't say\n"
	.string "I didn't warn you!$"

MauvilleCity_Gym_Text_WattsonRematchDefeat::
# 122 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Oof… Our batteries ran dry…$"

MauvilleCity_Gym_Text_WattsonPostRematch::
# 126 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON: We'll have to recharge our\n"
	.string "batteries again.\p"
	.string "When we're fully charged up, we'll gladly\n"
	.string "accept your challenge.\p"
	.string "So, come back again sometime, won't\n"
	.string "you?$"

MauvilleCity_Gym_Text_WattsonRematchNeedTwoMons::
# 130 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON: Ah-ha! Here at last! I know\n"
	.string "what you want.\l"
	.string "You want to battle my POKéMON!\p"
	.string "Wahahahaha!\p"
	.string "Oops! Wait! You've only one POKéMON\n"
	.string "with you!\p"
	.string "Come see me with two or more POKéMON,\n"
	.string "all right?$"
