MauvilleCity_Gym_MapScripts::
	.byte 0


MauvilleCity_Gym_EventScript_Angelo::
# 5 "data/maps/MauvilleCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_ANGELO, MauvilleCity_Gym_Text_AngeloIntro, MauvilleCity_Gym_Text_AngeloDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MauvilleCity_Gym/scripts.pory"
	msgbox MauvilleCity_Gym_Text_AngeloPostBattle
	return


MauvilleCity_Gym_EventScript_Ben::
# 10 "data/maps/MauvilleCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_BEN, MauvilleCity_Gym_Text_BenIntro, MauvilleCity_Gym_Text_BenDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MauvilleCity_Gym/scripts.pory"
	msgbox MauvilleCity_Gym_Text_BenPostBattle
	return


MauvilleCity_Gym_EventScript_GymGuide::
	end


MauvilleCity_Gym_EventScript_Kirk::
# 19 "data/maps/MauvilleCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_KIRK, MauvilleCity_Gym_Text_KirkIntro, MauvilleCity_Gym_Text_KirkDefeat, Text_NotEnoughMonsForDoubleBattle
# 20 "data/maps/MauvilleCity_Gym/scripts.pory"
	msgbox MauvilleCity_Gym_Text_KirkPostBattle
	return


MauvilleCity_Gym_EventScript_LeftGymStatue::
	end


MauvilleCity_Gym_EventScript_RightGymStatue::
	end


MauvilleCity_Gym_EventScript_Shawn::
# 38 "data/maps/MauvilleCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_SHAWN, MauvilleCity_Gym_Text_ShawnIntro, MauvilleCity_Gym_Text_ShawnDefeat, Text_NotEnoughMonsForDoubleBattle
# 39 "data/maps/MauvilleCity_Gym/scripts.pory"
	msgbox MauvilleCity_Gym_Text_ShawnPostBattle
	return


MauvilleCity_Gym_EventScript_Switch1::
	end


MauvilleCity_Gym_EventScript_Switch2::
	end


MauvilleCity_Gym_EventScript_Switch3::
	end


MauvilleCity_Gym_EventScript_Switch4::
	end


MauvilleCity_Gym_EventScript_Vivian::
# 59 "data/maps/MauvilleCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_VIVIAN, MauvilleCity_Gym_Text_VivianIntro, MauvilleCity_Gym_Text_VivianDefeat, Text_NotEnoughMonsForDoubleBattle
# 60 "data/maps/MauvilleCity_Gym/scripts.pory"
	msgbox MauvilleCity_Gym_Text_VivianPostBattle
	return


MauvilleCity_Gym_EventScript_Wattson::
	end


MauvilleCity_Gym_Text_AngeloDefeat::
# 69 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_AngeloDefeat$"

MauvilleCity_Gym_Text_AngeloIntro::
# 73 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_AngeloIntro$"

MauvilleCity_Gym_Text_AngeloPostBattle::
# 77 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_AngeloPostBattle$"

MauvilleCity_Gym_Text_BenDefeat::
# 81 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_BenDefeat$"

MauvilleCity_Gym_Text_BenIntro::
# 85 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_BenIntro$"

MauvilleCity_Gym_Text_BenPostBattle::
# 89 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_BenPostBattle$"

MauvilleCity_Gym_Text_KirkDefeat::
# 93 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_KirkDefeat$"

MauvilleCity_Gym_Text_KirkIntro::
# 97 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_KirkIntro$"

MauvilleCity_Gym_Text_KirkPostBattle::
# 101 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_KirkPostBattle$"

MauvilleCity_Gym_Text_ShawnDefeat::
# 105 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_ShawnDefeat$"

MauvilleCity_Gym_Text_ShawnIntro::
# 109 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_ShawnIntro$"

MauvilleCity_Gym_Text_ShawnPostBattle::
# 113 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_ShawnPostBattle$"

MauvilleCity_Gym_Text_VivianDefeat::
# 117 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_VivianDefeat$"

MauvilleCity_Gym_Text_VivianIntro::
# 121 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_VivianIntro$"

MauvilleCity_Gym_Text_VivianPostBattle::
# 125 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MauvilleCity_Gym_Text_VivianPostBattle$"

MauvilleCity_Gym_Text_WattsonPostRematch::
# 129 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "WATTSON: We'll have to recharge our\n"
	.string "batteries again.\p"
	.string "When we're fully charged up, we'll\n"
	.string "gladly accept your challenge.\p"
	.string "So, come back again sometime,\n"
	.string "won't you?$"

MauvilleCity_Gym_Text_GymStatueCertified::
# 133 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "MAUVILLE CITY POKéMON GYM\p"
	.string "WATTSON'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

MauvilleCity_Gym_Text_ExplainShockWave::
# 137 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "That TM34 there contains SHOCK WAVE.\p"
	.string "It's a trustworthy move that never\n"
	.string "misses! You can count on it!\p"
	.string "… … … … … …$"

MauvilleCity_Gym_Text_WattsonGoForthAndEndeavor::
# 141 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Wahahahah!\n"
	.string "Go forth and endeavor, youngster!$"

MauvilleCity_Gym_Text_GymGuidePostVictory::
# 145 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "Whoa, you're electrifying!\n"
	.string "You've powered the door open!$"

MauvilleCity_Gym_Text_GymStatue::
# 149 "data/maps/MauvilleCity_Gym/scripts.pory"
	.string "MAUVILLE CITY POKéMON GYM$"
