SevenIsland_House_Room1_MapScripts::
	.byte 0


SevenIsland_House_Room1_EventScript_Box::
# 5 "data/maps/SevenIsland_House_Room1/scripts.pory"
	msgbox SevenIsland_House_Room1_Text_SlightBreezeAroundBox, MSGBOX_SIGN
	end


SevenIsland_House_Room1_EventScript_OldWoman::
	end


SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
# 14 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "There is a slight breeze blowing around\n"
	.string "the box.$"
