SevenIsland_House_Room1_MapScripts::
# 2 "data/maps/SevenIsland_House_Room1/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_House_Room1_OnTransition
# 3 "data/maps/SevenIsland_House_Room1/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SevenIsland_House_Room1_OnFrame
	.byte 0


SevenIsland_House_Room1_Text_OnlyEnjoymentWatchingBattles::
# 7 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "I may not look like much now, but when I\n"
	.string "was younger…\p"
	.string "I flew everywhere, challenging\n"
	.string "TRAINERS wherever I found them.\p"
	.string "Now, my only source of enjoyment is\n"
	.string "reminiscing about the past while\l"
	.string "watching battles.$"

SevenIsland_House_Room1_Text_SlightBreezeAroundBox::
# 11 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "There is a slight breeze blowing around\n"
	.string "the box.$"

SevenIsland_House_Room1_Text_ChallengeVisitingTrainer::
# 15 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Ah! Welcome, my friend!\p"
	.string "Let me tell you something. There's a\n"
	.string "hidden room in the basement.\p"
	.string "A TRAINER named {STR_VAR_1} is\n"
	.string "waiting there now.\p"
	.string "Tell me, you did come to challenge\n"
	.string "{STR_VAR_1}, am I right?$"

SevenIsland_House_Room1_Text_OhYouWontBattle::
# 19 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Oh… You won't battle…\p"
	.string "I see, I see. … …\p"
	.string "Well, perhaps if you change your mind,\n"
	.string "do come back.$"

SevenIsland_House_Room1_Text_LimitThreeMonsPerSide::
# 23 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Ah! You will battle for me?\p"
	.string "It was worth my time moving the box\n"
	.string "aside, then.\p"
	.string "… … But there is one slight problem.\p"
	.string "This hidden room is not built very\n"
	.string "sturdy.\p"
	.string "Can I get you to limit it to battles of\n"
	.string "three POKéMON per side?$"

SevenIsland_House_Room1_Text_SaveProgressBeforeBattle::
# 27 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Fine! Before your battle, would you like\n"
	.string "to save your game?$"

SevenIsland_House_Room1_Text_DontHoldAnythingBack::
# 31 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "All right. Don't hold anything back!$"

SevenIsland_House_Room1_Text_StrVar1_1::
# 35 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "{STR_VAR_1}$"

SevenIsland_House_Room2_Text_MatchEndedUpDraw::
# 39 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "The match ended up a draw.$"

SevenIsland_House_Room1_Text_DrawWasIt::
# 43 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "A draw, was it?\p"
	.string "However, let me say that it was a worthy\n"
	.string "spectacle.\p"
	.string "I'd say it was a wonderful battle with a\n"
	.string "real sense of depth!$"

SevenIsland_House_Room1_Text_StrVar1_2::
# 47 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_AstoundingBattle::
# 51 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Bravo!\p"
	.string "Bravo, indeed! What an astounding\n"
	.string "battle!\p"
	.string "It was so astounding, why, it keeps\n"
	.string "filling my eyes with tears!\p"
	.string "The thrust and parry of expertly used\n"
	.string "techniques!\p"
	.string "The clash of power upon power!\p"
	.string "Yes! It was sheer magnificence!$"

SevenIsland_House_Room1_Text_StrVar1_3::
# 55 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "{STR_VAR_1}$"

SevenIsland_House_Room1_Text_FeelYourDisappointment::
# 59 "data/maps/SevenIsland_House_Room1/scripts.pory"
	.string "Too bad! I feel your disappointment.\p"
	.string "However, that disappointment is what\n"
	.string "will make you better.\p"
	.string "Use it, learn from it, and make it\n"
	.string "motivate you to seek greatness.\p"
	.string "Forget not this disappointment and\n"
	.string "redouble your training!$"
