FiveIsland_House1_MapScripts::
	.byte 0


FiveIsland_House1_JPText_HusbandWentOffFishing::
# 5 "data/maps/FiveIsland_House1/scripts.pory"
	.string "\p"
	.string "\l"
	.string "$"

FiveIsland_House1_Text_HusbandWentOffFishing::
# 9 "data/maps/FiveIsland_House1/scripts.pory"
	.string "Don't worry about buying anything for\n"
	.string "dinner tonight!\p"
	.string "That's what my husband said when he\n"
	.string "went off fishing today.\p"
	.string "I'm not sure if I can count on him to\n"
	.string "live up to that promise.$"
