FiveIsland_House1_MapScripts::
	.byte 0


FiveIsland_House1_EventScript_Woman::
# 5 "data/maps/FiveIsland_House1/scripts.pory"
	msgbox FiveIsland_House1_Text_HusbandWentOffFishing, MSGBOX_NPC
	end


FiveIsland_House1_Text_HusbandWentOffFishing::
# 10 "data/maps/FiveIsland_House1/scripts.pory"
	.string "Don't worry about buying anything\n"
	.string "for dinner tonight!\p"
	.string "…That's what my husband said when\n"
	.string "he went off fishing today.\p"
	.string "I'm not sure if I can count on him\n"
	.string "to live up to that promise.$"
