MtMoon_B2F_MapScripts::
# 2 "data/maps/MtMoon_B2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MtMoon_B2F_OnTransition
	.byte 0


MtMoon_B2F_Text_MiguelIntro::
# 6 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Hey, stop!\p"
	.string "I found these fossils! They're both\n"
	.string "mine!$"

MtMoon_B2F_Text_MiguelDefeat::
# 10 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Okay! I'll share!$"

MtMoon_B2F_Text_WellEachTakeAFossil::
# 14 "data/maps/MtMoon_B2F/scripts.pory"
	.string "We'll each take a fossil! No being\n"
	.string "greedy!$"

MtMoon_B2F_Text_ThenThisFossilIsMine::
# 18 "data/maps/MtMoon_B2F/scripts.pory"
	.string "All right. Then this fossil is mine!$"

MtMoon_B2F_Text_LabOnCinnabarRegeneratesFossils::
# 22 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Far away, on CINNABAR ISLAND, there's a\n"
	.string "POKMON LAB.\p"
	.string "They do research on regenerating\n"
	.string "fossils.$"

MtMoon_B2F_Text_Grunt1Intro::
# 26 "data/maps/MtMoon_B2F/scripts.pory"
	.string "We, TEAM ROCKET, shall find the fossils!\p"
	.string "Reviving POKMON from them will earn us\n"
	.string "huge riches!$"

MtMoon_B2F_Text_Grunt1Defeat::
# 30 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Urgh! Now I'm mad!$"

MtMoon_B2F_Text_Grunt1PostBattle::
# 34 "data/maps/MtMoon_B2F/scripts.pory"
	.string "You made me mad! TEAM ROCKET will\n"
	.string "blacklist you!$"

MtMoon_B2F_Text_Grunt2Intro::
# 38 "data/maps/MtMoon_B2F/scripts.pory"
	.string "We, TEAM ROCKET, are POKMON gangsters!\l"
	.string "We strike fear with our strength!$"

MtMoon_B2F_Text_Grunt2Defeat::
# 42 "data/maps/MtMoon_B2F/scripts.pory"
	.string "I blew it!$"

MtMoon_B2F_Text_Grunt2PostBattle::
# 46 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Darn it all! My associates won't stand\n"
	.string "for this!$"

MtMoon_B2F_Text_Grunt3Intro::
# 50 "data/maps/MtMoon_B2F/scripts.pory"
	.string "We're pulling a big job here! Get lost,\n"
	.string "kid!$"

MtMoon_B2F_Text_Grunt3Defeat::
# 54 "data/maps/MtMoon_B2F/scripts.pory"
	.string "So, you are good$"

MtMoon_B2F_Text_Grunt3PostBattle::
# 58 "data/maps/MtMoon_B2F/scripts.pory"
	.string "If you find a fossil, give it to me and\n"
	.string "scram!$"

MtMoon_B2F_Text_Grunt4Intro::
# 62 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Little kids shouldn't be messing around\n"
	.string "with grown-ups!\p"
	.string "It could be bad news!$"

MtMoon_B2F_Text_Grunt4Defeat::
# 66 "data/maps/MtMoon_B2F/scripts.pory"
	.string "I'm steamed!$"

MtMoon_B2F_Text_Grunt4PostBattle::
# 70 "data/maps/MtMoon_B2F/scripts.pory"
	.string "POKMON lived here long before people\n"
	.string "came.$"

MtMoon_B2F_Text_YouWantDomeFossil::
# 74 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Do you want the DOME FOSSIL?$"

MtMoon_B2F_Text_YouWantHelixFossil::
# 78 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Do you want the HELIX FOSSIL?$"

MtMoon_B2F_Text_ObtainedHelixFossil::
# 82 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Obtained the HELIX FOSSIL!$"

MtMoon_B2F_Text_ObtainedDomeFossil::
# 86 "data/maps/MtMoon_B2F/scripts.pory"
	.string "Obtained the DOME FOSSIL!$"
