FiveIsland_LostCave_Room1_MapScripts::
	.byte 0


FiveIsland_LostCave_Room1_Text_LawsonIntro::
# 5 "data/maps/FiveIsland_LostCave_Room1/scripts.pory"
	.string "Aiyeeeeeh!\p"
	.string "I thought this was an ancient ruin. But\n"
	.string "it's teeming with ghosts!$"

FiveIsland_LostCave_Room1_Text_LawsonDefeat::
# 9 "data/maps/FiveIsland_LostCave_Room1/scripts.pory"
	.string "Aiyeeeeeh! Mercy!$"

FiveIsland_LostCave_Room1_Text_LawsonPostBattle::
# 13 "data/maps/FiveIsland_LostCave_Room1/scripts.pory"
	.string "I'm trying to get out of here, but I\n"
	.string "always end up at the same spot.\p"
	.string "Maybe the number of boulders is a hint…$"
