TwoIsland_JoyfulGameCorner_MapScripts::
# 2 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TwoIsland_JoyfulGameCorner_OnTransition
# 3 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, TwoIsland_JoyfulGameCorner_OnWarp
# 4 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TwoIsland_JoyfulGameCorner_OnFrame
# 5 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CableClub_OnLoad
	.byte 0


TwoIsland_JoyfulGameCorner_Text_WhereHasLostelleGottenTo::
# 9 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Now, where's LOSTELLE gotten to today?\p"
	.string "She always brings me lunch every day\n"
	.string "right about now…$"

TwoIsland_JoyfulGameCorner_Text_PleaseHelpFindLostelle::
# 13 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Hm? You, there! Are you a friend of\n"
	.string "LOSTELLE's?\p"
	.string "Have you seen LOSTELLE around? I don't\n"
	.string "know where she might be.\l"
	.string "She should've been here long ago.\p"
	.string "LOSTELLE's a cutie - she got my looks -\n"
	.string "so what if someone…\p"
	.string "What if something's happened to my\n"
	.string "LOSTELLE?!\p"
	.string "Please, help me find her! Please go\n"
	.string "search THREE ISLAND!$"

TwoIsland_JoyfulGameCorner_Text_IsThisOnlyThreeIsland::
# 17 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Hah? What is this GAME CORNER? How\n"
	.string "much sadder can this get?\p"
	.string "Those clowns…\p"
	.string "They said they'd be waiting on the\n"
	.string "island, so where are they?\p"
	.string "Hey, you! Is this the only THREE ISLAND\n"
	.string "around here?$"

TwoIsland_JoyfulGameCorner_Text_ThisIsTwoIslandMoveIt::
# 21 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Try waking up before you crawl out of\n"
	.string "bed, you punk.\p"
	.string "This is TWO ISLAND!\p"
	.string "Move it! Get your filthy motorbike out\n"
	.string "of my place!$"

TwoIsland_JoyfulGameCorner_Text_TheseIslandsAreConfusing::
# 25 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Huh… Oh, oh, gotcha.\p"
	.string "Tch… These islands are confusing…$"

TwoIsland_JoyfulGameCorner_Text_PunkScuffedUpMyFloor::
# 29 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Would you look at that? That punk\n"
	.string "scuffed up my floor.$"

TwoIsland_JoyfulGameCorner_Text_PleaseGoToThreeIsland::
# 33 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Hey, but listen! I'm begging you, you\n"
	.string "have to go to THREE ISLAND.\p"
	.string "If anything were to happen to my\n"
	.string "LOSTELLE…\p"
	.string "My place is the house with the red roof\n"
	.string "on THREE ISLAND.\p"
	.string "She may just show up late here, so I\n"
	.string "can't run off anywhere.\p"
	.string "That's why I have to get you to do me\n"
	.string "this big favor.$"

TwoIsland_JoyfulGameCorner_Text_NotRunningAnyGamesToday::
# 37 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "I'm sorry. We're not running any games\n"
	.string "today.$"

TwoIsland_JoyfulGameCorner_Text_GetGamesGoingSoon::
# 41 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "We'll get the games going soon for you!$"

TwoIsland_JoyfulGameCorner_Text_YouRescuedLostelle::
# 45 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "So you rescued LOSTELLE? How can I\n"
	.string "thank you?\p"
	.string "LOSTELLE, darling, forgive me!\p"
	.string "Daddy didn't know you were scared and\n"
	.string "in trouble!$"

TwoIsland_JoyfulGameCorner_Text_LostelleItsOkayDaddy::
# 49 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "LOSTELLE: It's okay, Daddy. I got to be\n"
	.string "friends with {PLAYER}!$"

TwoIsland_JoyfulGameCorner_Text_ThisIsForMe::
# 53 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Oh, what's that? You're saying that this\n"
	.string "is for me?\p"
	.string "How did you know that I love rare rocks\n"
	.string "and gems?\p"
	.string "You sure know how to make a guy happy.$"

TwoIsland_JoyfulGameCorner_Text_HandedMeteoriteToLostellesDaddy::
# 57 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "{PLAYER} handed the METEORITE to\n"
	.string "LOSTELLE's daddy.$"

TwoIsland_JoyfulGameCorner_Text_OhThisIsFromBill::
# 61 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Oh, I see, this is from BILL! You have to\n"
	.string "thank him for me!\p"
	.string "You know, you've been fantastic. I want\n"
	.string "you to have this.$"

TwoIsland_JoyfulGameCorner_Text_ReceivedMoonStoneFromLostellesDaddy::
# 65 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "{PLAYER} received a MOON STONE from\n"
	.string "LOSTELLE's daddy.$"

TwoIsland_JoyfulGameCorner_Text_NotGoingToFitInBag::
# 69 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Your BAG's not going to fit another\n"
	.string "thing…$"

TwoIsland_JoyfulGameCorner_Text_IllGetGameCornerRunning::
# 73 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "All right, I'll get the GAME CORNER\n"
	.string "running right away.\p"
	.string "You have to come visit with a friend.$"

TwoIsland_JoyfulGameCorner_Text_PleaseShowMeYouBeingCool::
# 77 "data/maps/TwoIsland_JoyfulGameCorner/scripts.pory"
	.string "Listen, listen!\p"
	.string "Please show me you being cool again!$"
