TrainerHill_Entrance_MapScripts::
	.byte 0


TrainerHill_Entrance_EventScript_Attendant::
	end


TrainerHill_Entrance_EventScript_Clerk::
	end


TrainerHill_Entrance_EventScript_EntryTrigger::
	end


TrainerHill_Entrance_EventScript_Girl::
	end


TrainerHill_Entrance_EventScript_Man::
	end


TrainerHill_Entrance_EventScript_Nurse::
	end


TrainerHill_Entrance_EventScript_Records::
	end


TrainerHill_Entrance_Text_TrainersInEveryRoom::
# 37 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Let's see…\n"
	.string "The TRAINERS here now are…\p"
	.string "There appear to be TRAINERS gathered\n"
	.string "in every room.$"

TrainerHill_Entrance_Text_StillGettingReady::
# 41 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "This is the TRAINER HILL where\n"
	.string "you may enjoy tag battles with many\l"
	.string "TRAINERS.\p"
	.string "Unfortunately, we're still getting\n"
	.string "things ready. Please come back later!$"

TrainerHill_Entrance_Text_ThankYouForPlaying::
# 45 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Thank you for playing!$"

TrainerHill_Entrance_Text_SaveGameBeforeEnter::
# 49 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Is this your first visit here?\p"
	.string "Before you enter, please save\n"
	.string "your game.$"

TrainerHill_Entrance_Text_CantWaitToTestTheWaters::
# 53 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "I heard tough TRAINERS come to this\n"
	.string "TRAINER HILL from all over.\p"
	.string "I can't wait to test the waters!\p"
	.string "I'll knock aside anyone that stands\n"
	.string "in my way!$"

TrainerHill_Entrance_Text_TooBadTremendousEffort::
# 57 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "That was too bad.\p"
	.string "I think you put in a tremendous\n"
	.string "effort in your battling.\p"
	.string "Please come back and try again!$"

TrainerHill_Entrance_Text_DoYouKnowWhenTheyOpen::
# 61 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Do you know when they're opening\n"
	.string "this place up?\p"
	.string "I'm waiting here to be the first\n"
	.string "challenger ever!$"

TrainerHill_Entrance_Text_MovedReceptionHereForSwitch::
# 65 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "When the TRAINERS switch places,\n"
	.string "the movement can be hectic.\p"
	.string "To avoid the stampede, we moved\n"
	.string "the reception counter here.\p"
	.string "I'm sorry for the inconvenience.$"

TrainerHill_Entrance_Text_PleaseVisitUsAgain::
# 69 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Please do visit us again!$"

TrainerHill_Entrance_Text_ExplainTrainerHill::
# 73 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Here at the TRAINER HILL, we conduct\n"
	.string "an event called the Time Attack.\p"
	.string "It is a race that measures how long\n"
	.string "you take to reach our owner on\l"
	.string "the rooftop from this counter.\p"
	.string "The fastest times are posted on\n"
	.string "the Time Board--try competing with\l"
	.string "your friends.\p"
	.string "In TRAINER battles along the way,\n"
	.string "neither Exp. Points nor money will\l"
	.string "be awarded.$"
