TrainerHill_Entrance_MapScripts::
# 2 "data/maps/TrainerHill_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, TrainerHill_Entrance_OnResume
# 3 "data/maps/TrainerHill_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_RETURN_TO_FIELD, TrainerHill_Entrance_OnReturn
# 4 "data/maps/TrainerHill_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, TrainerHill_Entrance_OnTransition
# 5 "data/maps/TrainerHill_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, TrainerHill_Entrance_OnLoad
# 6 "data/maps/TrainerHill_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, TrainerHill_Entrance_OnFrame
	.byte 0


TrainerHill_Entrance_Text_StillGettingReady::
# 10 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "This is the TRAINER HILL where you may\n"
	.string "enjoy tag battles with many\l"
	.string "TRAINERS.\p"
	.string "Unfortunately, we're still getting\n"
	.string "things ready. Please come back later!$"

TrainerHill_Entrance_Text_WelcomeToTrainerHill::
# 14 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Welcome!\p"
	.string "This is the TRAINER HILL where you may\n"
	.string "enjoy tag battles with many\l"
	.string "TRAINERS!$"

TrainerHill_Entrance_Text_SaveGameBeforeEnter::
# 18 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Is this your first visit here?\p"
	.string "Before you enter, please save your\n"
	.string "game.$"

TrainerHill_Entrance_Text_TrainersUpToFloorX::
# 22 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Let's see… The TRAINERS here now are…\p"
	.string "Up to floor no. {STR_VAR_1}.$"

TrainerHill_Entrance_Text_TrainersInEveryRoom::
# 26 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Let's see… The TRAINERS here now are…\p"
	.string "There appear to be TRAINERS gathered\n"
	.string "in every room.$"

TrainerHill_Entrance_Text_LikeToChallengeTrainers::
# 30 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Would you like to challenge the waiting\n"
	.string "TRAINERS?$"

TrainerHill_Entrance_Text_TimeProgessGetSetGo::
# 34 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "I will time your progress. Best of luck!\p"
	.string "On your marks…\p"
	.string "Get set…\p"
	.string "Go!$"

TrainerHill_Entrance_Text_PleaseVisitUsAgain::
# 38 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Please do visit us again!$"

TrainerHill_Entrance_Text_TooBadTremendousEffort::
# 42 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "That was too bad.\p"
	.string "I think you put in a tremendous effort\n"
	.string "in your battling.\p"
	.string "Please come back and try again!$"

TrainerHill_Entrance_Text_HopeYouGiveItYourBest::
# 46 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "I hope you give it your best.$"

TrainerHill_Entrance_Text_MovedReceptionHereForSwitch::
# 50 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "When the TRAINERS switch places, the\n"
	.string "movement can be hectic.\p"
	.string "To avoid the stampede, we moved the\n"
	.string "reception counter here.\p"
	.string "I'm sorry for the inconvenience.$"

TrainerHill_Entrance_Text_ThankYouForPlaying::
# 54 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Thank you for playing!$"

TrainerHill_Entrance_Text_ExplainTrainerHill::
# 58 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Here at the TRAINER HILL, we conduct\n"
	.string "an event called the Time Attack.\p"
	.string "It is a race that measures how long you\n"
	.string "take to reach our owner on\l"
	.string "the rooftop from this counter.\p"
	.string "The fastest times are posted on the\n"
	.string "Time Board--try competing with\l"
	.string "your friends.\p"
	.string "In TRAINER battles along the way,\n"
	.string "neither Exp. Points nor money will\l"
	.string "be awarded.$"

TrainerHill_Entrance_Text_NeedAtLeastTwoPokemon::
# 62 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Oh, I'm sorry, but you appear to have\n"
	.string "only one POKéMON with you.\p"
	.string "You will need at least two POKéMON to\n"
	.string "enter this event.$"

TrainerHill_Roof_Text_YouFinallyCameBravo::
# 66 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Hm! Hm!\p"
	.string "You finally came! Yes, you have arrived!\p"
	.string "Wait! Don't say it! I know why you came\n"
	.string "all the way\l"
	.string "here by yourself!\p"
	.string "You wanted to see me, the owner of the\n"
	.string "TRAINER HILL, because…\p"
	.string "You want to form a tag team with me!\n"
	.string "Wa-hoo!\p"
	.string "…Uh? That's not it?\p"
	.string "Anyway, I watched you on your way up.\n"
	.string "Marvelous battling! Bravo, indeed!$"

TrainerHill_Roof_Text_HaveTheMostMarvelousGift::
# 70 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "For a marvelous someone like you, I have\n"
	.string "the most marvelous gift!$"

TrainerHill_Roof_Text_FullUpBeBackLaterForThis::
# 74 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Oh, no, full up with things! You'll be\n"
	.string "back later for this!$"

TrainerHill_Roof_Text_GotHereMarvelouslyQuickly::
# 78 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Oh, hold on here! Did you possibly get\n"
	.string "here marvelously quickly?\p"
	.string "How splendid! You needn't have hurried\n"
	.string "so to see me!\p"
	.string "That is so delightful. I'll have the Time\n"
	.string "Board at the reception updated!$"

TrainerHill_Roof_Text_YouWerentVeryQuick::
# 82 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "But, oh… You weren't very quick getting\n"
	.string "here.$"

TrainerHill_Roof_Text_ArriveZippierNextTime::
# 86 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Perhaps it would please me more if you\n"
	.string "arrived zippier next time.\p"
	.string "Then, I should be pleased to form a tag\n"
	.string "team with you!\p"
	.string "Until we meet again, amigo!$"

TrainerHill_Roof_Text_BuiltTrainerHillToFindPartner::
# 90 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "I had the TRAINER HILL built for but\n"
	.string "one reason and one only!\p"
	.string "To find the most suitable partner with\n"
	.string "whom I may form a tag team!$"

TrainerHill_Entrance_Text_ChallengeTime::
# 94 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "{STR_VAR_1} min.\n"
	.string "{STR_VAR_2}.{STR_VAR_3} sec.$"

TrainerHill_Entrance_Text_WhatSortOfTrainersAreAhead::
# 98 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Who knows what sort of TRAINERS and\n"
	.string "POKéMON combos are ahead?\p"
	.string "All I know is that I'll knock aside\n"
	.string "anyone that stands in my way!$"

TrainerHill_Entrance_Text_CantWaitToTestTheWaters::
# 102 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "I heard tough TRAINERS come to this\n"
	.string "TRAINER HILL from all over.\p"
	.string "I can't wait to test the waters!\p"
	.string "I'll knock aside anyone that stands in\n"
	.string "my way!$"

TrainerHill_Entrance_Text_FriendsTryingToReachTimeBoardTop::
# 106 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Do you see the Time Board over there?\p"
	.string "My friends and I are trying to see who\n"
	.string "can reach the top in the least time.$"

TrainerHill_Entrance_Text_DoYouKnowWhenTheyOpen::
# 110 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Do you know when they're opening this\n"
	.string "place up?\p"
	.string "I'm waiting here to be the first\n"
	.string "challenger ever!$"

TrainerHill_Elevator_Text_ReturnToReception::
# 114 "data/maps/TrainerHill_Entrance/scripts.pory"
	.string "Would you like to return to the\n"
	.string "reception counter?$"
