Route22_MapScripts::
	.byte 0


Route22_EventScript_EarlyRivalTriggerBottom::
	end


Route22_EventScript_EarlyRivalTriggerMid::
	end


Route22_EventScript_EarlyRivalTriggerTop::
	end


Route22_EventScript_LateRivalTriggerBottom::
	end


Route22_EventScript_LateRivalTriggerMid::
	end


Route22_EventScript_LateRivalTriggerTop::
	end


Route22_EventScript_LeagueGateSign::
# 29 "data/maps/Route22/scripts.pory"
	msgbox Route22_Text_LeagueGateSign, MSGBOX_SIGN
	end


Route22_Text_LeagueGateSign::
# 34 "data/maps/Route22/scripts.pory"
	.string "POKéMON LEAGUE Front Gate$"
