Route22_MapScripts::
	.byte 0


Route22_Text_EarlyRivalIntro::
# 5 "data/maps/Route22/scripts.pory"
	.string "{RIVAL}: Hey! {PLAYER}!\p"
	.string "You're off to the POKéMON LEAGUE?\n"
	.string "Forget about it!\p"
	.string "You probably don't have any BADGES, do\n"
	.string "you?\p"
	.string "The guard won't let you through without\n"
	.string "them.\p"
	.string "By the way, did your POKéMON get any\n"
	.string "stronger?$"

Route22_Text_EarlyRivalDefeat::
# 9 "data/maps/Route22/scripts.pory"
	.string "Awww! You just lucked out!$"

Route22_Text_EarlyRivalPostBattle::
# 13 "data/maps/Route22/scripts.pory"
	.string "I heard the POKéMON LEAGUE is crawling\n"
	.string "with tough TRAINERS.\p"
	.string "I have to figure out how to get past\n"
	.string "them.\p"
	.string "You should quit dawdling and get a move\n"
	.string "on!$"

Route22_Text_RivalShouldCatchSomeMons::
# 17 "data/maps/Route22/scripts.pory"
	.string "{RIVAL}“なんだ？ ポケモン　2ひきも\l"
	.string "もってるの　なぜか　だって？\p"
	.string "おまえも つかまえれば　いい　じゃん！$"

Route22_Text_LateRivalIntro::
# 21 "data/maps/Route22/scripts.pory"
	.string "{RIVAL}: What? {PLAYER}! What a\n"
	.string "surprise to see you here!\p"
	.string "So you're going to the POKéMON LEAGUE?\p"
	.string "You collected all the BADGES, too?\n"
	.string "That's cool!\p"
	.string "Then I'll whip you, {PLAYER}, as a\n"
	.string "warm-up for the POKéMON LEAGUE!\p"
	.string "Come on!$"

Route22_Text_LateRivalDefeat::
# 25 "data/maps/Route22/scripts.pory"
	.string "What!?\p"
	.string "I was just careless, you!$"

Route22_Text_LateRivalPostBattle::
# 29 "data/maps/Route22/scripts.pory"
	.string "That loosened me up. I'm ready for the\n"
	.string "POKéMON LEAGUE!\p"
	.string "{PLAYER}, you need more practice.\p"
	.string "But hey, you know that! I'm out of here.\n"
	.string "Smell ya!$"

Route22_Text_LateRivalVictory::
# 33 "data/maps/Route22/scripts.pory"
	.string "{RIVAL}“ひゃははッ　{PLAYER}ー！ それで　がんばってるのかよ！\l"
	.string "おれの　さいのうに　くらべりゃ\l"
	.string "{PLAYER}は　まだまだ　だな！\p"
	.string "もっと　れんしゅう　こいよ！ あははーッ！$"

Route22_Text_LeagueGateSign::
# 37 "data/maps/Route22/scripts.pory"
	.string "POKéMON LEAGUE Front Gate$"
