OldaleTown_House2_MapScripts::
	.byte 0


OldaleTown_House2_MapScripts::
	return


OldaleTown_House2_Text_PokemonLevelUp::
# 8 "data/maps/OldaleTown_House2/scripts.pory"
	.string "When POKéMON battle, they eventually\n"
	.string "level up and become stronger.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon::
# 12 "data/maps/OldaleTown_House2/scripts.pory"
	.string "If the POKéMON with you become\n"
	.string "stronger, you'll be able to go farther\l"
	.string "away from here.$"
