OldaleTown_House2_MapScripts::
	.byte 0


OldaleTown_House2_EventScript_Man::
# 5 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon, MSGBOX_NPC
	end


OldaleTown_House2_EventScript_Woman::
# 10 "data/maps/OldaleTown_House2/scripts.pory"
	msgbox OldaleTown_House2_Text_PokemonLevelUp, MSGBOX_NPC
	end


OldaleTown_House2_Text_PokemonLevelUp::
# 14 "data/maps/OldaleTown_House2/scripts.pory"
	.string "When POKéMON battle, they eventually\n"
	.string "level up and become stronger.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon::
# 18 "data/maps/OldaleTown_House2/scripts.pory"
	.string "If the POKéMON with you become\n"
	.string "stronger, you'll be able to go farther\l"
	.string "away from here.$"
