OldaleTown_House2_MapScripts::
	.byte 0


OldaleTown_House2_Text_PokemonLevelUp::
# 5 "data/maps/OldaleTown_House2/scripts.pory"
	.string "When POKMON battle, they eventually\n"
	.string "level up and become stronger.$"

OldaleTown_House2_Text_YoullGoFurtherWithStrongPokemon::
# 9 "data/maps/OldaleTown_House2/scripts.pory"
	.string "If the POKMON with you become\n"
	.string "stronger, you'll be able to go farther\l"
	.string "away from here.$"
