OneIsland_TreasureBeach_MapScripts::
	.byte 0


OneIsland_TreasureBeach_Text_AmaraIntro::
# 5 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.string "Lying back, rocked by the waves… It's\n"
	.string "exquisite.$"

OneIsland_TreasureBeach_Text_AmaraDefeat::
# 9 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.string "I lost… It feels awful.$"

OneIsland_TreasureBeach_Text_AmaraPostBattle::
# 13 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.string "The sea is pleasantly warm in these\n"
	.string "parts.$"

OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
# 17 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.string "Good things get washed up by the ocean\n"
	.string "current onto this beach.\p"
	.string "That's why I often come here for some\n"
	.string "beachcombing.$"
