OneIsland_TreasureBeach_MapScripts::
	.byte 0


OneIsland_TreasureBeach_EventScript_Boy::
# 5 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
	end


OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach::
# 10 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.string "Good things get washed up by the\n"
	.string "ocean current onto this beach.\p"
	.string "That's why I often come here for\n"
	.string "some beachcombing.$"
