PetalburgCity_ParentsHouse_MapScripts::
	.byte 0


PetalburgCity_ParentsHouse_EventScript_SmithNPC1::
# 5 "data/maps/PetalburgCity_ParentsHouse/scripts.pory"
	msgbox PetalburgCity_ParentsHouse_Text_SmithNPC1, MSGBOX_NPC
	end


PetalburgCity_ParentsHouse_EventScript_SmithNPC2::
# 14 "data/maps/PetalburgCity_ParentsHouse/scripts.pory"
	msgbox PetalburgCity_ParentsHouse_Text_SmithNPC2, MSGBOX_NPC
	end


PetalburgCity_ParentsHouse_Text_SmithNPC1::
# 9 "data/maps/PetalburgCity_ParentsHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

PetalburgCity_ParentsHouse_Text_SmithNPC2::
# 18 "data/maps/PetalburgCity_ParentsHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
