ViridianCity_House1_MapScripts::
	.byte 0


ViridianCity_House1_EventScript_SmithNPC1::
# 5 "data/maps/ViridianCity_House1/scripts.pory"
	msgbox ViridianCity_House1_Text_SmithNPC1, MSGBOX_NPC
	end


ViridianCity_House1_EventScript_SmithNPC2::
# 14 "data/maps/ViridianCity_House1/scripts.pory"
	msgbox ViridianCity_House1_Text_SmithNPC2, MSGBOX_NPC
	end


ViridianCity_House1_Text_SmithNPC1::
# 9 "data/maps/ViridianCity_House1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

ViridianCity_House1_Text_SmithNPC2::
# 18 "data/maps/ViridianCity_House1/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
