SilphCo_11F_MapScripts::
# 2 "data/maps/SilphCo_11F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_11F_OnLoad
	.byte 0


SilphCo_11F_Text_ThanksForSavingMeDearBoy::
# 6 "data/maps/SilphCo_11F/scripts.pory"
	.string "PRESIDENT: Oh, dear boy! Thank you for\n"
	.string "saving SILPH.\p"
	.string "I will never forget you saved us in our\n"
	.string "moment of peril.\p"
	.string "I have to thank you in some way.\p"
	.string "Because I am rich, I can give you\n"
	.string "anything.\p"
	.string "Here, maybe this will do.$"

SilphCo_11F_Text_ThanksForSavingMeDearGirl::
# 10 "data/maps/SilphCo_11F/scripts.pory"
	.string "PRESIDENT: Oh, dear girl! Thank you for\n"
	.string "saving SILPH.\p"
	.string "I will never forget you saved us in our\n"
	.string "moment of peril.\p"
	.string "I have to thank you in some way.\p"
	.string "Because I am rich, I can give you\n"
	.string "anything.\p"
	.string "Here, maybe this will do.$"

SilphCo_11F_Text_ObtainedMasterBallFromPresident::
# 14 "data/maps/SilphCo_11F/scripts.pory"
	.string "{PLAYER} obtained a MASTER BALL from\n"
	.string "the PRESIDENT!$"

SilphCo_11F_Text_ThatsOurSecretPrototype::
# 18 "data/maps/SilphCo_11F/scripts.pory"
	.string "PRESIDENT: You can't buy that\n"
	.string "anywhere.\p"
	.string "It's our secret prototype MASTER BALL.\p"
	.string "It will catch any POKéMON without fail!\p"
	.string "You should be quiet about using it,\n"
	.string "though.$"

SilphCo_11F_Text_YouHaveNoRoomForThis::
# 22 "data/maps/SilphCo_11F/scripts.pory"
	.string "You have no room for this.$"

SilphCo_11F_Text_ThanksForRescuingUs::
# 26 "data/maps/SilphCo_11F/scripts.pory"
	.string "SECRETARY: Thank you for rescuing all\n"
	.string "of us.\p"
	.string "We, from the PRESIDENT down, are\n"
	.string "indebted to you.$"

SilphCo_11F_Text_GiovanniIntro::
# 30 "data/maps/SilphCo_11F/scripts.pory"
	.string "Ah, {PLAYER}! So we meet again!\p"
	.string "The PRESIDENT and I are discussing a\n"
	.string "vital business proposition.\p"
	.string "Keep your nose out of grown-up\n"
	.string "matters…\p"
	.string "Or, experience a world of pain!$"

SilphCo_11F_Text_GiovanniDefeat::
# 34 "data/maps/SilphCo_11F/scripts.pory"
	.string "Arrgh!! I lost again!?$"

SilphCo_11F_Text_GiovanniPostBattle::
# 38 "data/maps/SilphCo_11F/scripts.pory"
	.string "Blast it all! You ruined our plans for\n"
	.string "SILPH!\p"
	.string "But, TEAM ROCKET will never fall!\p"
	.string "{PLAYER}! Never forget that all\n"
	.string "POKéMON exist for TEAM ROCKET!\p"
	.string "I must go, but I shall return!$"

SilphCo_11F_Text_Grunt2Intro::
# 42 "data/maps/SilphCo_11F/scripts.pory"
	.string "Stop right there! Don't you move!$"

SilphCo_11F_Text_Grunt2Defeat::
# 46 "data/maps/SilphCo_11F/scripts.pory"
	.string "Don't… Please!$"

SilphCo_11F_Text_Grunt2PostBattle::
# 50 "data/maps/SilphCo_11F/scripts.pory"
	.string "So, you want to see my BOSS?$"

SilphCo_11F_Text_Grunt1Intro::
# 54 "data/maps/SilphCo_11F/scripts.pory"
	.string "Halt! Do you have an appointment with\n"
	.string "my BOSS?$"

SilphCo_11F_Text_Grunt1Defeat::
# 58 "data/maps/SilphCo_11F/scripts.pory"
	.string "Gaah! Demolished!$"

SilphCo_11F_Text_Grunt1PostBattle::
# 62 "data/maps/SilphCo_11F/scripts.pory"
	.string "Watch your step… My BOSS likes his\n"
	.string "POKéMON tough!$"

SilphCo_11F_Text_MonitorHasMonsOnIt::
# 66 "data/maps/SilphCo_11F/scripts.pory"
	.string "The monitor has POKéMON on it!$"

SilphCo_11F_Text_FloorSign::
# 70 "data/maps/SilphCo_11F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 11F$"
