PokemonMansion_2F_MapScripts::
# 2 "data/maps/PokemonMansion_2F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonMansion_2F_OnLoad
	.byte 0


PokemonMansion_Text_PressSecretSwitch::
# 6 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "A secret switch!\p"
	.string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
# 10 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
# 14 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
# 18 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "I can't get out! This old place is one\n"
	.string "big puzzle.$"

PokemonMansion_1F_Text_ArnieDefeat::
# 22 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "Oh, no! My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
# 26 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "The switches here open and close\n"
	.string "alternating sets of doors.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
# 30 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "Diary: July 5 Guyana, South America\p"
	.string "A new POKMON was discovered deep in the\n"
	.string "jungle.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
# 34 "data/maps/PokemonMansion_2F/scripts.pory"
	.string "Diary: July 10 We christened the newly\n"
	.string "discovered\l"
	.string "POKMON, MEW.$"
