CinnabarIsland_Gym_MapScripts::
# 2 "data/maps/CinnabarIsland_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, CinnabarIsland_Gym_OnLoad
	.byte 0


CinnabarIsland_Gym_Text_BlaineIntro::
# 6 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Hah!\p"
	.string "I am BLAINE, the red-hot LEADER of\n"
	.string "CINNABAR GYM!\p"
	.string "My fiery POKMON are all rough and ready\n"
	.string "with intense heat!\p"
	.string "They incinerate all challengers!\p"
	.string "Hah! You better have BURN HEAL!{PLAY_BGM}{MUS_RG_GYM}$"

CinnabarIsland_Gym_Text_BlaineDefeat::
# 10 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I have burned down to nothing! Not even\n"
	.string "ashes remain!\p"
	.string "You have earned the VOLCANOBADGE.$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
# 14 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "FIRE BLAST is the ultimate fire\n"
	.string "technique.\p"
	.string "Don't waste it on WATER POKMON.$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
# 18 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Hah!\p"
	.string "The VOLCANOBADGE heightens the\n"
	.string "SPECIAL stats of your POKMON.\p"
	.string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
# 22 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "{PLAYER} received TM38 from BLAINE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
# 26 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "TM38 contains FIRE BLAST. Teach it to\n"
	.string "FIRE-type POKMON.\p"
	.string "VULPIX or CHARMELEON would be ideal for\n"
	.string "that move.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
# 30 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro::
# 34 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Do you know how hot POKMON fire breath\n"
	.string "can get?$"

CinnabarIsland_Gym_Text_ErikDefeat::
# 38 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Yow! Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
# 42 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Fire, or to be more precise, combustion\p"
	.string "Oxygen in the air Blah, blah, blah, blah$"

CinnabarIsland_Gym_Text_QuinnIntro::
# 46 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I was a thief, but I went straight as a\n"
	.string "TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
# 50 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
# 54 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I get this uncontrollable urge to steal\n"
	.string "other people's POKMON.$"

CinnabarIsland_Gym_Text_AveryIntro::
# 58 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I've studied POKMON thoroughly. You\n"
	.string "can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat::
# 62 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Waah! My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
# 66 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "My theories are too complicated for you\n"
	.string "to understand.$"

CinnabarIsland_Gym_Text_RamonIntro::
# 70 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I like using FIRE-type POKMON. I just\n"
	.string "do.$"

CinnabarIsland_Gym_Text_RamonDefeat::
# 74 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
# 78 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I wish there were a thief POKMON. I'd\n"
	.string "use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
# 82 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I know why BLAINE became a TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
# 86 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
# 90 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Our LEADER, BLAINE, became lost in the\n"
	.string "mountains but good.\p"
	.string "Night fell when a fiery bird POKMON\n"
	.string "appeared.\p"
	.string "Its light allowed BLAINE to find his way\n"
	.string "down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
# 94 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "I've been to many GYMS, but this one\n"
	.string "best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
# 98 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Yowza! Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
# 102 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "PONYTA, NINETALES Those are popular\n"
	.string "FIRE POKMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
# 106 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
# 110 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Oh! Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
# 114 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Water beats fire, of course.\p"
	.string "But fire melts ice, so the FIRE type\n"
	.string "beats ICE-type POKMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
# 118 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "The hotheaded BLAINE is a FIRE POKMON\n"
	.string "pro.\p"
	.string "Douse his spirits with water!\p"
	.string "You'd better take some BURN HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
# 122 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "{PLAYER}! You beat that firebrand!$"

CinnabarIsland_Gym_Text_GymStatue::
# 126 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "CINNABAR POKMON GYM LEADER: BLAINE\p"
	.string "WINNING TRAINERS: {RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
# 130 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "CINNABAR POKMON GYM LEADER: BLAINE\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
# 134 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "POKMON Quiz!\p"
	.string "Get it right, and the door opens to the\n"
	.string "next room.\p"
	.string "Get it wrong, and face a TRAINER!\p"
	.string "If you want to conserve your POKMON\n"
	.string "for the GYM LEADER\p"
	.string "Then get it right! Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
# 138 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "CATERPIE evolves into METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
# 142 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "There are nine certified POKMON LEAGUE\n"
	.string "BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
# 146 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "POLIWAG evolves three times?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
# 150 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Are electric moves effective against\n"
	.string "GROUND-type POKMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
# 154 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "POKMON of the same kind and level are\n"
	.string "not identical?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
# 158 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "TM28 contains TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
# 162 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "You're absolutely correct!\p"
	.string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall::
# 166 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Sorry! Bad call!$"
