CinnabarIsland_Gym_MapScripts::
	.byte 0


CinnabarIsland_Gym_EventScript_Avery::
# 5 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_SUPER_NERD_AVERY, CinnabarIsland_Gym_Text_AveryIntro, CinnabarIsland_Gym_Text_AveryDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_AveryPostBattle
	return


CinnabarIsland_Gym_EventScript_Blaine::
	end


CinnabarIsland_Gym_EventScript_Derek::
# 14 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_SUPER_NERD_DEREK, CinnabarIsland_Gym_Text_DerekIntro, CinnabarIsland_Gym_Text_DerekDefeat, Text_NotEnoughMonsForDoubleBattle
# 15 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_DerekPostBattle
	return


CinnabarIsland_Gym_EventScript_Dusty::
# 19 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_BURGLAR_DUSTY, CinnabarIsland_Gym_Text_DustyIntro, CinnabarIsland_Gym_Text_DustyDefeat, Text_NotEnoughMonsForDoubleBattle
# 20 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_DustyPostBattle
	return


CinnabarIsland_Gym_EventScript_Erik::
# 24 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_SUPER_NERD_ERIK, CinnabarIsland_Gym_Text_ErikIntro, CinnabarIsland_Gym_Text_ErikDefeat, Text_NotEnoughMonsForDoubleBattle
# 25 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_ErikPostBattle
	return


CinnabarIsland_Gym_EventScript_GymGuy::
	end


CinnabarIsland_Gym_EventScript_GymStatue::
# 35 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_GymStatue, MSGBOX_DEFAULT
	end


CinnabarIsland_Gym_EventScript_Quinn::
# 41 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_BURGLAR_QUINN, CinnabarIsland_Gym_Text_QuinnIntro, CinnabarIsland_Gym_Text_QuinnDefeat, Text_NotEnoughMonsForDoubleBattle
# 42 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_QuinnPostBattle
	return


CinnabarIsland_Gym_EventScript_Quiz2Left::
	end


CinnabarIsland_Gym_EventScript_Quiz2Right::
	end


CinnabarIsland_Gym_EventScript_Quiz3Left::
	end


CinnabarIsland_Gym_EventScript_Quiz3Right::
	end


CinnabarIsland_Gym_EventScript_Quiz4Left::
	end


CinnabarIsland_Gym_EventScript_Quiz4Right::
	end


CinnabarIsland_Gym_EventScript_Quiz5Left::
	end


CinnabarIsland_Gym_EventScript_Quiz5Right::
	end


CinnabarIsland_Gym_EventScript_Quiz6Left::
	end


CinnabarIsland_Gym_EventScript_Quiz6Right::
	end


CinnabarIsland_Gym_EventScript_Quz1Left::
	end


CinnabarIsland_Gym_EventScript_Quz1Right::
	end


CinnabarIsland_Gym_EventScript_Ramon::
# 130 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_BURGLAR_RAMON, CinnabarIsland_Gym_Text_RamonIntro, CinnabarIsland_Gym_Text_RamonDefeat, Text_NotEnoughMonsForDoubleBattle
# 131 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_RamonPostBattle
	return


CinnabarIsland_Gym_EventScript_Zac::
# 135 "data/maps/CinnabarIsland_Gym/scripts.pory"
	trainerbattle_double TRAINER_SUPER_NERD_ZAC, CinnabarIsland_Gym_Text_ZacIntro, CinnabarIsland_Gym_Text_ZacDefeat, Text_NotEnoughMonsForDoubleBattle
# 136 "data/maps/CinnabarIsland_Gym/scripts.pory"
	msgbox CinnabarIsland_Gym_Text_ZacPostBattle
	return


CinnabarIsland_Gym_Text_GymStatue::
# 139 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "CINNABAR POKéMON GYM LEADER: BLAINE\p"
	.string "WINNING TRAINERS: {RIVAL}$"

CinnabarIsland_Gym_Text_AveryDefeat::
# 144 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_AveryDefeat$"

CinnabarIsland_Gym_Text_AveryIntro::
# 148 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_AveryIntro$"

CinnabarIsland_Gym_Text_AveryPostBattle::
# 152 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_AveryPostBattle$"

CinnabarIsland_Gym_Text_DerekDefeat::
# 156 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DerekDefeat$"

CinnabarIsland_Gym_Text_DerekIntro::
# 160 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DerekIntro$"

CinnabarIsland_Gym_Text_DerekPostBattle::
# 164 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DerekPostBattle$"

CinnabarIsland_Gym_Text_DustyDefeat::
# 168 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DustyDefeat$"

CinnabarIsland_Gym_Text_DustyIntro::
# 172 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DustyIntro$"

CinnabarIsland_Gym_Text_DustyPostBattle::
# 176 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_DustyPostBattle$"

CinnabarIsland_Gym_Text_ErikDefeat::
# 180 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ErikDefeat$"

CinnabarIsland_Gym_Text_ErikIntro::
# 184 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ErikIntro$"

CinnabarIsland_Gym_Text_ErikPostBattle::
# 188 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ErikPostBattle$"

CinnabarIsland_Gym_Text_QuinnDefeat::
# 192 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_QuinnDefeat$"

CinnabarIsland_Gym_Text_QuinnIntro::
# 196 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_QuinnIntro$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
# 200 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_QuinnPostBattle$"

CinnabarIsland_Gym_Text_RamonDefeat::
# 204 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_RamonDefeat$"

CinnabarIsland_Gym_Text_RamonIntro::
# 208 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_RamonIntro$"

CinnabarIsland_Gym_Text_RamonPostBattle::
# 212 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_RamonPostBattle$"

CinnabarIsland_Gym_Text_ZacDefeat::
# 216 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ZacDefeat$"

CinnabarIsland_Gym_Text_ZacIntro::
# 220 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ZacIntro$"

CinnabarIsland_Gym_Text_ZacPostBattle::
# 224 "data/maps/CinnabarIsland_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "CinnabarIsland_Gym_Text_ZacPostBattle$"
