SootopolisCity_MapScripts::
	.byte 0


SootopolisCity_EventScript_Archie::
	end


SootopolisCity_EventScript_BlackBelt::
	end


SootopolisCity_EventScript_Boy1::
	end


SootopolisCity_EventScript_Boy2::
	end


SootopolisCity_EventScript_CaveOfOriginExpert::
	end


SootopolisCity_EventScript_CitySign::
# 25 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_CitySign, MSGBOX_SIGN
	end


SootopolisCity_EventScript_Girl::
	end


SootopolisCity_EventScript_GymSign::
# 34 "data/maps/SootopolisCity/scripts.pory"
	msgbox SootopolisCity_Text_GymSign, MSGBOX_SIGN
	end


SootopolisCity_EventScript_Kiri::
	end


SootopolisCity_EventScript_Man::
	end


SootopolisCity_EventScript_Maniac::
	end


SootopolisCity_EventScript_Maxie::
	end


SootopolisCity_EventScript_NinjaBoy::
	end


SootopolisCity_EventScript_Steven::
	end


SootopolisCity_EventScript_Wallace::
	end


SootopolisCity_EventScript_Woman1::
	end


SootopolisCity_EventScript_Woman2::
	end


SootopolisCity_Text_GymSign::
# 75 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY POKéMON GYM LEADER:\n"
	.string "JUAN\p"
	.string "“The GYM LEADER with the beauty of\n"
	.string "pure water!”$"

SootopolisCity_Text_CitySign::
# 79 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY\p"
	.string "“The mystical city where history\n"
	.string "slumbers.”$"

SootopolisCity_Text_YouBroughtFlyingMon::
# 83 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh?\p"
	.string "It was you who brought that flying\n"
	.string "POKéMON here?\p"
	.string "Well, aren't you amazing!$"

SootopolisCity_Text_TryingMeaninglessToPokemon::
# 87 "data/maps/SootopolisCity/scripts.pory"
	.string "ARCHIE: KYOGRE and GROUDON both\n"
	.string "flew off to who knows where.\p"
	.string "The weather in HOENN has returned\n"
	.string "to its normal state…\p"
	.string "Haha…\n"
	.string "Hahaha…\p"
	.string "Maybe what we were trying to do was\n"
	.string "something small, even meaningless,\l"
	.string "to POKéMON…$"

SootopolisCity_Text_PrettyMonCameFromSky::
# 91 "data/maps/SootopolisCity/scripts.pory"
	.string "A pretty POKéMON came down from\n"
	.string "the sky…$"

SootopolisCity_Text_LeadSuperiorTrainerToCave::
# 95 "data/maps/SootopolisCity/scripts.pory"
	.string "A person with a strong will and\n"
	.string "superior talent…\p"
	.string "A TRAINER who has knowledge and\n"
	.string "experience of many kinds of POKéMON…\p"
	.string "If such a person were to appear, I was\n"
	.string "instructed by WALLACE to lead that\l"
	.string "TRAINER to this CAVE.$"

SootopolisCity_Text_CaveOfOriginSleepsToo::
# 99 "data/maps/SootopolisCity/scripts.pory"
	.string "This is the CAVE OF ORIGIN…\p"
	.string "With the passing of the crisis,\n"
	.string "the cave, too, shall sleep…$"

SootopolisCity_Text_GreenOneSettlesThings::
# 103 "data/maps/SootopolisCity/scripts.pory"
	.string "I was wondering which one would win,\n"
	.string "the red one or the blue one, but, oh no,\l"
	.string "it's the green one that settles things!\p"
	.string "Talk about a huge turn of events!$"

SootopolisCity_Text_SawLegendWithOwnEyes::
# 107 "data/maps/SootopolisCity/scripts.pory"
	.string "There's an ancient legend that claims\n"
	.string "the land and sea were shaped by\l"
	.string "a colossal battle between POKéMON.\p"
	.string "Well, I saw that happen with\n"
	.string "my very own eyes!\p"
	.string "Whoa! I never expected to be\n"
	.string "witness to something this huge!$"

SootopolisCity_Text_FearedWorstWhenPokemonFlewDown::
# 111 "data/maps/SootopolisCity/scripts.pory"
	.string "When that third POKéMON flew down,\n"
	.string "I feared the worst.$"

SootopolisCity_Text_DazzledByMentor::
# 115 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: I'm sure that you will be\n"
	.string "dazzled by my mentor's breathtakingly\l"
	.string "elegant battle style.$"

SootopolisCity_Text_PhysicallyFitLivingHere::
# 119 "data/maps/SootopolisCity/scripts.pory"
	.string "Diving in the sea. Climbing up and\n"
	.string "down stairs all the time…\p"
	.string "If you live in this town, you end up\n"
	.string "getting physically fit.$"

SootopolisCity_Text_WonderWhatWorldIsLike::
# 123 "data/maps/SootopolisCity/scripts.pory"
	.string "I… I've never been out of this city.\p"
	.string "I wonder what the world is like on\n"
	.string "the other side of this round sky?$"

SootopolisCity_Text_SootopolisDidntGetWrecked::
# 127 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY didn't get wrecked!$"

SootopolisCity_Text_HaventYouScaledSkyPillar::
# 131 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: Oh?\n"
	.string "{PLAYER}{KUN}?\p"
	.string "Haven't you scaled the SKY PILLAR\n"
	.string "yet?\p"
	.string "I'm sure that you can make it to\n"
	.string "the top of the SKY PILLAR…$"

SootopolisCity_Text_ThankYouForHelpAcceptThis::
# 135 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: {PLAYER}{KUN}…\n"
	.string "My eyes didn't deceive me.\p"
	.string "Thanks to your help, SOOTOPOLIS…\n"
	.string "No, all of HOENN was saved.\p"
	.string "On behalf of the people, I thank you.\p"
	.string "This is a gift from me.\n"
	.string "Please accept it.$"

SootopolisCity_Text_WhereDidLegendariesGo::
# 139 "data/maps/SootopolisCity/scripts.pory"
	.string "GROUDON and KYOGRE…\n"
	.string "Where did they go?\p"
	.string "Will they cause droughts or downpours\n"
	.string "somewhere else?$"

SootopolisCity_Text_FlyingMonStoppedRampage::
# 143 "data/maps/SootopolisCity/scripts.pory"
	.string "That flying POKéMON came down from\n"
	.string "the sky and stopped the rampaging\l"
	.string "POKéMON…$"

SootopolisCity_Text_WhatIsThatGreenPokemon::
# 147 "data/maps/SootopolisCity/scripts.pory"
	.string "What? What? What?\n"
	.string "What is that green POKéMON?!$"

SootopolisCity_Text_NightSkyFavoriteScenery::
# 151 "data/maps/SootopolisCity/scripts.pory"
	.string "A circle of a night sky framed by\n"
	.string "the crater of a volcano…\p"
	.string "And in that ring, stars flicker and\n"
	.string "blink as if they were alive…\l"
	.string "It's my favorite scenery.$"

SootopolisCity_Text_KnowWhatsNeededToHelpHim::
# 155 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: I think you have what's\n"
	.string "needed to help him…$"

SootopolisCity_Text_NeverBeenToSkyPillar::
# 159 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: The SKY PILLAR…\p"
	.string "I've never been there.\n"
	.string "I wonder where it could be?$"

SootopolisCity_Text_InvolvedWithCrisisComeWithMe::
# 163 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: Those POKéMON fighting…\n"
	.string "GROUDON… And KYOGRE…\p"
	.string "The two super-ancient POKéMON\n"
	.string "were awakened from a long sleep…\p"
	.string "And now they are smashing each other\n"
	.string "with their uncontrollable energy…\p"
	.string "…{PLAYER}{KUN}.\p"
	.string "You being here now I'll take to mean\n"
	.string "that you're prepared to become\l"
	.string "involved in this crisis.\p"
	.string "Well, then, there's someone that\n"
	.string "I'd like you to meet.\p"
	.string "Come with me, please.$"

SootopolisCity_Text_CityRegainedCalm::
# 167 "data/maps/SootopolisCity/scripts.pory"
	.string "The city has regained its calm…$"

SootopolisCity_Text_AwakenedPokemonClash::
# 171 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh, my…\p"
	.string "The clash between the two awakened\n"
	.string "POKéMON was quelled by the awakening\l"
	.string "of a third POKéMON…$"

SootopolisCity_Text_MaxieArchieLeft::
# 175 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: It looks like both MAXIE and\n"
	.string "ARCHIE have gone away somewhere.\p"
	.string "Perhaps they've gone to MT. PYRE to\n"
	.string "return those ORBS…$"

SootopolisCity_Text_AfterAllOurScheming::
# 179 "data/maps/SootopolisCity/scripts.pory"
	.string "MAXIE: So the super-ancient POKéMON\n"
	.string "weren't only GROUDON and KYOGRE…\p"
	.string "After all our fruitless scheming and\n"
	.string "frantic efforts, that one POKéMON's\l"
	.string "simple action puts everything right\l"
	.string "again as if nothing had happened…\p"
	.string "Fu…\n"
	.string "Fuhahaha…$"

SootopolisCity_Text_GiganticPokemonFight::
# 183 "data/maps/SootopolisCity/scripts.pory"
	.string "When two POKéMON that gigantic\n"
	.string "are fighting that savagely, there's\l"
	.string "not much that we can do.$"

SootopolisCity_Text_ThatWasWicked::
# 187 "data/maps/SootopolisCity/scripts.pory"
	.string "Wow!\n"
	.string "That was wicked!$"
