SootopolisCity_MapScripts::
# 2 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SootopolisCity_OnLoad
# 3 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SootopolisCity_OnTransition
# 4 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SootopolisCity_OnResume
# 5 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SootopolisCity_OnFrame
# 6 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SootopolisCity_OnWarp
	.byte 0


SootopolisCity_MapScripts::
# 10 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SootopolisCity_OnLoad
# 11 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SootopolisCity_OnTransition
# 12 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, SootopolisCity_OnResume
# 13 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SootopolisCity_OnFrame
# 14 "data/maps/SootopolisCity/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SootopolisCity_OnWarp
	return


SootopolisCity_Text_GymSign::
# 18 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY POKéMON GYM LEADER:\n"
	.string "JUAN\p"
	.string "“The GYM LEADER with the beauty of\n"
	.string "pure water!”$"

SootopolisCity_Text_CitySign::
# 22 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY\p"
	.string "“The mystical city where history\n"
	.string "slumbers.”$"

SootopolisCity_Text_DoorIsClosed::
# 26 "data/maps/SootopolisCity/scripts.pory"
	.string "The door is closed.$"

SootopolisCity_Text_PhysicallyFitLivingHere::
# 30 "data/maps/SootopolisCity/scripts.pory"
	.string "Diving in the sea. Climbing up and down\n"
	.string "stairs all the time…\p"
	.string "If you live in this town, you end up\n"
	.string "getting physically fit.$"

SootopolisCity_Text_GiantPokemonSuddenlyAppeared::
# 34 "data/maps/SootopolisCity/scripts.pory"
	.string "These giant POKéMON suddenly appeared\n"
	.string "in the middle of the city!\p"
	.string "And, I've never seen them before!\p"
	.string "Why are they smashing into each other\n"
	.string "like that?\p"
	.string "Why can't they be friends, those\n"
	.string "POKéMON?$"

SootopolisCity_Text_WhatIsThatGreenPokemon::
# 38 "data/maps/SootopolisCity/scripts.pory"
	.string "What? What? What? What is that green\n"
	.string "POKéMON?!$"

SootopolisCity_Text_WhereDidLegendariesGo::
# 42 "data/maps/SootopolisCity/scripts.pory"
	.string "GROUDON and KYOGRE… Where did they go?\p"
	.string "Will they cause droughts or downpours\n"
	.string "somewhere else?$"

SootopolisCity_Text_TwoPokemonArentAngry::
# 46 "data/maps/SootopolisCity/scripts.pory"
	.string "I just get this sense somehow that the\n"
	.string "two POKéMON aren't angry.\p"
	.string "I think… They probably can't control\n"
	.string "their own power…$"

SootopolisCity_Text_FlyingMonStoppedRampage::
# 50 "data/maps/SootopolisCity/scripts.pory"
	.string "That flying POKéMON came down from the\n"
	.string "sky and stopped the rampaging\l"
	.string "POKéMON…$"

SootopolisCity_Text_WonderWhatWorldIsLike::
# 54 "data/maps/SootopolisCity/scripts.pory"
	.string "I… I've never been out of this city.\p"
	.string "I wonder what the world is like on the\n"
	.string "other side of this round sky?$"

SootopolisCity_Text_ThisIsWicked::
# 58 "data/maps/SootopolisCity/scripts.pory"
	.string "Wow! This is wicked!$"

SootopolisCity_Text_ThatWasWicked::
# 62 "data/maps/SootopolisCity/scripts.pory"
	.string "Wow! That was wicked!$"

SootopolisCity_Text_GoRedAndBlueMon::
# 66 "data/maps/SootopolisCity/scripts.pory"
	.string "Go for it, red POKéMON! Don't back off,\n"
	.string "blue POKéMON!$"

SootopolisCity_Text_DoYouKnowMonNames::
# 70 "data/maps/SootopolisCity/scripts.pory"
	.string "… … … … … …\p"
	.string "Hi, do you know the names of those\n"
	.string "POKéMON fighting over there?$"

SootopolisCity_Text_GreenOneSettlesThings::
# 74 "data/maps/SootopolisCity/scripts.pory"
	.string "I was wondering which one would win, the\n"
	.string "red one or the blue one, but, oh no,\l"
	.string "it's the green one that settles things!\p"
	.string "Talk about a huge turn of events!$"

SootopolisCity_Text_SeeingLegendWithOwnEyes::
# 78 "data/maps/SootopolisCity/scripts.pory"
	.string "There's an ancient legend that claims\n"
	.string "the land and sea were shaped by\l"
	.string "a colossal battle between POKéMON.\p"
	.string "Well, I'm seeing that happen with my\n"
	.string "very own eyes!\p"
	.string "Whoa! I never expected to be witness to\n"
	.string "something this huge!$"

SootopolisCity_Text_SawLegendWithOwnEyes::
# 82 "data/maps/SootopolisCity/scripts.pory"
	.string "There's an ancient legend that claims\n"
	.string "the land and sea were shaped by\l"
	.string "a colossal battle between POKéMON.\p"
	.string "Well, I saw that happen with my very own\n"
	.string "eyes!\p"
	.string "Whoa! I never expected to be witness to\n"
	.string "something this huge!$"

SootopolisCity_Text_BigPokemonFighting::
# 86 "data/maps/SootopolisCity/scripts.pory"
	.string "A big POKéMON is fighting with another\n"
	.string "big POKéMON!\p"
	.string "Please, someone make them stop!$"

SootopolisCity_Text_PrettyMonCameFromSky::
# 90 "data/maps/SootopolisCity/scripts.pory"
	.string "A pretty POKéMON came down from the\n"
	.string "sky…$"

SootopolisCity_Text_SootopolisWillBeWrecked::
# 94 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh, no! SOOTOPOLIS CITY will get\n"
	.string "wrecked!$"

SootopolisCity_Text_SootopolisDidntGetWrecked::
# 98 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS CITY didn't get wrecked!$"

SootopolisCity_Text_NoOrdinaryTourist::
# 102 "data/maps/SootopolisCity/scripts.pory"
	.string "Hm! You've come all the way to\n"
	.string "SOOTOPOLIS?\l"
	.string "You're no ordinary tourist.\p"
	.string "But I suppose that doesn't make you an\n"
	.string "extraordinary tourist, either.$"

SootopolisCity_Text_CityRegainedCalm::
# 106 "data/maps/SootopolisCity/scripts.pory"
	.string "The city has regained its calm…$"

SootopolisCity_Text_CaveOfOriginPleaseLeave::
# 110 "data/maps/SootopolisCity/scripts.pory"
	.string "Who might you be?\p"
	.string "This is the CAVE OF ORIGIN.\p"
	.string "The spirits of POKéMON, becalmed at MT.\n"
	.string "PYRE, are said to be revived here.\p"
	.string "Please leave.$"

SootopolisCity_Text_LeadSuperiorTrainerToCave::
# 114 "data/maps/SootopolisCity/scripts.pory"
	.string "A person with a strong will and superior\n"
	.string "talent…\p"
	.string "A TRAINER who has knowledge and\n"
	.string "experience of many kinds of POKéMON…\p"
	.string "If such a person were to appear, I was\n"
	.string "instructed by WALLACE to lead that\l"
	.string "TRAINER to this CAVE.$"

SootopolisCity_Text_AwakenedPokemonClash::
# 118 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh, my…\p"
	.string "The clash between the two awakened\n"
	.string "POKéMON was quelled by the awakening\l"
	.string "of a third POKéMON…$"

SootopolisCity_Text_CaveOfOriginSleepsToo::
# 122 "data/maps/SootopolisCity/scripts.pory"
	.string "This is the CAVE OF ORIGIN…\p"
	.string "With the passing of the crisis, the\n"
	.string "cave, too, shall sleep…$"

SootopolisCity_Text_SootopolisSkyBeautiful::
# 126 "data/maps/SootopolisCity/scripts.pory"
	.string "SOOTOPOLIS sprang up as a town in the\n"
	.string "crater of a volcano.\p"
	.string "If you look up at the sky, the lip of the\n"
	.string "crater is also visible.\l"
	.string "So, all you see is the sky in a circle.\p"
	.string "But that's what makes the sky above\n"
	.string "SOOTOPOLIS the most beautiful.$"

SootopolisCity_Text_GiganticPokemonFight::
# 130 "data/maps/SootopolisCity/scripts.pory"
	.string "When two POKéMON that gigantic are\n"
	.string "fighting that savagely, there's\l"
	.string "not much that we can do.$"

SootopolisCity_Text_FearedWorstWhenPokemonFlewDown::
# 134 "data/maps/SootopolisCity/scripts.pory"
	.string "When that third POKéMON flew down, I\n"
	.string "feared the worst.$"

SootopolisCity_Text_NightSkyFavoriteScenery::
# 138 "data/maps/SootopolisCity/scripts.pory"
	.string "A circle of a night sky framed by the\n"
	.string "crater of a volcano…\p"
	.string "And in that ring, stars flicker and blink\n"
	.string "as if they were alive…\l"
	.string "It's my favorite scenery.$"

SootopolisCity_Text_WeatherWentWild::
# 142 "data/maps/SootopolisCity/scripts.pory"
	.string "The weather was clear this morning,\n"
	.string "but…\p"
	.string "All of a sudden, dark clouds brewed up,\n"
	.string "rain started falling in sheets, and\l"
	.string "there was thunder and lightning, too.\p"
	.string "The weather just went completely wild!\p"
	.string "Is all of this because of those\n"
	.string "POKéMON?$"

SootopolisCity_Text_YouBroughtFlyingMon::
# 146 "data/maps/SootopolisCity/scripts.pory"
	.string "Oh?\p"
	.string "It was you who brought that flying\n"
	.string "POKéMON here?\p"
	.string "Well, aren't you amazing!$"

SootopolisCity_Text_GroudonPleaseStop::
# 150 "data/maps/SootopolisCity/scripts.pory"
	.string "MAXIE: G… GROUDON… Please! Stop what\n"
	.string "you're doing!\p"
	.string "I know the extent of your power now!\p"
	.string "If you keep going, all HOENN, not just\n"
	.string "SOOTOPOLIS, will be utterly ruined!$"

SootopolisCity_Text_AfterAllOurScheming::
# 154 "data/maps/SootopolisCity/scripts.pory"
	.string "MAXIE: So the super-ancient POKéMON\n"
	.string "weren't only GROUDON and KYOGRE…\p"
	.string "After all our fruitless scheming and\n"
	.string "frantic efforts, that one POKéMON's\l"
	.string "simple action puts everything right\l"
	.string "again as if nothing had happened…\p"
	.string "Fu… Fuhahaha…$"

SootopolisCity_Text_KyogreCalmDown::
# 158 "data/maps/SootopolisCity/scripts.pory"
	.string "ARCHIE: KYOGRE! What's wrong?! Look\n"
	.string "over here! It's the RED ORB!\l"
	.string "Calm down! KYOGRE!\p"
	.string "… … … … … … … … … … … …\p"
	.string "It's no good! It's not responding at all!$"

SootopolisCity_Text_TryingMeaninglessToPokemon::
# 162 "data/maps/SootopolisCity/scripts.pory"
	.string "ARCHIE: KYOGRE and GROUDON both flew\n"
	.string "off to who knows where.\p"
	.string "The weather in HOENN has returned to\n"
	.string "its normal state…\p"
	.string "Haha… Hahaha…\p"
	.string "Maybe what we were trying to do was\n"
	.string "something small, even meaningless,\l"
	.string "to POKéMON…$"

SootopolisCity_Text_InvolvedWithCrisisComeWithMe::
# 166 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: Those POKéMON fighting…\n"
	.string "GROUDON… And KYOGRE…\p"
	.string "The two super-ancient POKéMON were\n"
	.string "awakened from a long sleep…\p"
	.string "And now they are smashing each other\n"
	.string "with their uncontrollable energy…\p"
	.string "…{PLAYER}{KUN}.\p"
	.string "You being here now I'll take to mean\n"
	.string "that you're prepared to become\l"
	.string "involved in this crisis.\p"
	.string "Well, then, there's someone that I'd like\n"
	.string "you to meet.\p"
	.string "Come with me, please.$"

SootopolisCity_Text_DoesThisMakeYourFearPokemon::
# 170 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: Listen, {PLAYER}{KUN}.\p"
	.string "Does seeing GROUDON and KYOGRE make\n"
	.string "you think POKéMON are to be feared?\p"
	.string "But that's not true. POKéMON are really\n"
	.string "more…\p"
	.string "…Why am I asking you this? You already\n"
	.string "know.$"

SootopolisCity_Text_HereWereAreHelpWallace::
# 174 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: Okay, here we are!\p"
	.string "Inside here you'll find someone named\n"
	.string "WALLACE.\p"
	.string "I think you have what's needed to help\n"
	.string "him…$"

SootopolisCity_Text_KnowWhatsNeededToHelpHim::
# 178 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: I think you have what's needed\n"
	.string "to help him…$"

SootopolisCity_Text_NeverBeenToSkyPillar::
# 182 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: The SKY PILLAR…\p"
	.string "I've never been there. I wonder where it\n"
	.string "could be?$"

SootopolisCity_Text_SoThatsRayquaza::
# 186 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: So that's RAYQUAZA…\p"
	.string "It's incredible how the two rampaging\n"
	.string "POKéMON would flee from it in fear…$"

SootopolisCity_Text_MaxieArchieLeft::
# 190 "data/maps/SootopolisCity/scripts.pory"
	.string "STEVEN: It looks like both MAXIE and\n"
	.string "ARCHIE have gone away somewhere.\p"
	.string "Perhaps they've gone to MT. PYRE to\n"
	.string "return those ORBS…$"

SootopolisCity_Text_HaventYouScaledSkyPillar::
# 194 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: Oh? {PLAYER}{KUN}?\p"
	.string "Haven't you scaled the SKY PILLAR yet?\p"
	.string "I'm sure that you can make it to the top\n"
	.string "of the SKY PILLAR…$"

SootopolisCity_Text_AquaMagmaDidntMeanHarm::
# 198 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: {PLAYER}{KUN}…\p"
	.string "The leaders of TEAM MAGMA and AQUA, I\n"
	.string "don't think they meant harm.\p"
	.string "It wouldn't hurt to hear what they have\n"
	.string "to say for themselves.$"

SootopolisCity_Text_ThankYouForHelpAcceptThis::
# 202 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: {PLAYER}{KUN}… My eyes didn't\n"
	.string "deceive me.\p"
	.string "Thanks to your help, SOOTOPOLIS… No,\n"
	.string "all of HOENN was saved.\p"
	.string "On behalf of the people, I thank you.\p"
	.string "This is a gift from me. Please accept it.$"

SootopolisCity_Text_ExplainWaterfallGoToGym::
# 206 "data/maps/SootopolisCity/scripts.pory"
	.string "That HIDDEN MACHINE contains\n"
	.string "WATERFALL.\p"
	.string "If you have the RAIN BADGE, a POKéMON\n"
	.string "that has learned that HM move can\l"
	.string "force its way up waterfalls.\p"
	.string "And where does one get the RAIN BADGE?\n"
	.string "You know, don't you?\p"
	.string "That's right! You have to beat the\n"
	.string "SOOTOPOLIS GYM LEADER.\p"
	.string "When you're all set to go, step through\n"
	.string "that door.$"

SootopolisCity_Text_DazzledByMentor::
# 210 "data/maps/SootopolisCity/scripts.pory"
	.string "WALLACE: I'm sure that you will be\n"
	.string "dazzled by my mentor's breathtakingly\l"
	.string "elegant battle style.$"
