PewterCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PewterCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


PewterCity_PokemonCenter_1F_Text_TeamRocketMtMoonImOnPhone::
# 7 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	.string "What!?\p"
	.string "TEAM ROCKET is at MT. MOON? Huh?\p"
	.string "I'm on the phone! Scram!$"

PewterCity_PokemonCenter_1F_Text_Jigglypuff::
# 11 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	.string "JIGGLYPUFF: Puu pupuu!$"

PewterCity_PokemonCenter_1F_Text_WhenJiggylypuffSingsMonsGetDrowsy::
# 15 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	.string "Yawn!\p"
	.string "When JIGGLYPUFF sings, POKéMON get\n"
	.string "drowsy…\p"
	.string "…Me, too… Snore…$"

PewterCity_PokemonCenter_1F_Text_TradingMyClefairyForPikachu::
# 19 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	.string "I really want a PIKACHU, so I'm trading\n"
	.string "my CLEFAIRY for one.$"

PewterCity_PokemonCenter_1F_Text_TradingPikachuWithKid::
# 23 "data/maps/PewterCity_PokemonCenter_1F/scripts.pory"
	.string "I'm trading POKéMON with that kid there.\p"
	.string "I had two PIKACHU, so I figured I might\n"
	.string "as well trade one.$"
