Route119_House_MapScripts::
	.byte 0


Route119_House_Text_RumorAboutCaveOfOrigin::
# 5 "data/maps/Route119_House/scripts.pory"
	.string "I heard about a cave called the CAVE OF\n"
	.string "ORIGIN.\p"
	.string "People rumor that the spirits of\n"
	.string "POKéMON are revived there. Could\l"
	.string "something like that really happen?$"

Route119_House_Text_Wingull::
# 9 "data/maps/Route119_House/scripts.pory"
	.string "WINGULL: Pihyoh!$"
