SSAnne_B1F_Room1_MapScripts::
	.byte 0


SSAnne_B1F_Room1_Text_PhillipIntro::
# 5 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "Matey, you're walking the plank if you\n"
	.string "lose!$"

SSAnne_B1F_Room1_Text_PhillipDefeat::
# 9 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "Argh! Beaten by a kid!$"

SSAnne_B1F_Room1_Text_PhillipPostBattle::
# 13 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "When we're out at sea, jellyfish POKéMON\n"
	.string "sometimes drift by.$"

SSAnne_B1F_Room1_Text_BarnyIntro::
# 17 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "Hello, stranger!\p"
	.string "I can't tell if you're from the seas or\n"
	.string "mountains, but stop and chat.\p"
	.string "All my POKéMON are from the sea.$"

SSAnne_B1F_Room1_Text_BarnyDefeat::
# 21 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "Darn! I let that one get away!$"

SSAnne_B1F_Room1_Text_BarnyPostBattle::
# 25 "data/maps/SSAnne_B1F_Room1/scripts.pory"
	.string "I was going to make you my assistant,\n"
	.string "too!$"
