LilycoveCity_Harbor_MapScripts::
	.byte 0


LilycoveCity_Harbor_EventScript_FerryAttendant::
	end


LilycoveCity_Harbor_EventScript_Sailor::
	end


LilycoveCity_Harbor_Text_SailorFerryAvailable::
# 12 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "The ferry S.S. TIDAL is finally in\n"
	.string "operation.\p"
	.string "The folks at the SHIPYARD in SLATEPORT\n"
	.string "must've worked extra hard.\p"
	.string "Well, it's my turn to get busy now!$"

LilycoveCity_Harbor_Text_PleaseBoard::
# 16 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Please board the ferry and wait for\n"
	.string "departure.$"

LilycoveCity_Harbor_Text_MayISeeYourTicket::
# 20 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Hello, are you here for the ferry?\n"
	.string "May I see your TICKET?$"

LilycoveCity_Harbor_Text_SlateportItIs::
# 24 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "SLATEPORT CITY it is, then!$"

LilycoveCity_Harbor_Text_FerryUnavailable::
# 28 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "I beg your pardon?\n"
	.string "You're looking for a ship?\p"
	.string "I'm sorry, the ferry service isn't\n"
	.string "available at present…$"

LilycoveCity_Harbor_Text_BattleFrontierItIs::
# 32 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "BATTLE FRONTIER it is, then!$"

LilycoveCity_Harbor_Text_NoTicket::
# 36 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "{PLAYER} doesn't have the TICKET…\p"
	.string "I'm terribly sorry.\p"
	.string "You must have a TICKET to board\n"
	.string "the ferry.$"

LilycoveCity_Harbor_Text_SailAnotherTime::
# 40 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Please sail with us another time!$"
