LilycoveCity_Harbor_MapScripts::
# 2 "data/maps/LilycoveCity_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LilycoveCity_Harbor_OnTransition
	.byte 0


LilycoveCity_Harbor_Text_FerryUnavailable::
# 6 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "I beg your pardon? You're looking for a\n"
	.string "ship?\p"
	.string "I'm sorry, the ferry service isn't\n"
	.string "available at present…$"

LilycoveCity_Harbor_Text_MayISeeYourTicket::
# 10 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Hello, are you here for the ferry? May I\n"
	.string "see your TICKET?$"

LilycoveCity_Harbor_Text_NoTicket::
# 14 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "{PLAYER} doesn't have the TICKET…\p"
	.string "I'm terribly sorry.\p"
	.string "You must have a TICKET to board the\n"
	.string "ferry.$"

LilycoveCity_Harbor_Text_FlashTicketWhereTo::
# 18 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "{PLAYER} flashed the TICKET.\p"
	.string "Perfect! That's all you need!\p"
	.string "And where would you like to go?$"

LilycoveCity_Harbor_Text_SailAnotherTime::
# 22 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Please sail with us another time!$"

LilycoveCity_Harbor_Text_SlateportItIs::
# 26 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "SLATEPORT CITY it is, then!$"

LilycoveCity_Harbor_Text_BattleFrontierItIs::
# 30 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "BATTLE FRONTIER it is, then!$"

LilycoveCity_Harbor_Text_PleaseBoard::
# 34 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Please board the ferry and wait for\n"
	.string "departure.$"

LilycoveCity_Harbor_Text_WhereWouldYouLikeToGo::
# 38 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Then, where would you like to go?$"

LilycoveCity_Harbor_Text_SailorFerryUnavailable::
# 42 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "Until they finish making the ferry, we\n"
	.string "sailors have nothing to do…\p"
	.string "I wish they'd get a move on, the folks\n"
	.string "at the SHIPYARD in SLATEPORT.$"

LilycoveCity_Harbor_Text_SailorFerryAvailable::
# 46 "data/maps/LilycoveCity_Harbor/scripts.pory"
	.string "The ferry S.S. TIDAL is finally in\n"
	.string "operation.\p"
	.string "The folks at the SHIPYARD in SLATEPORT\n"
	.string "must've worked extra hard.\p"
	.string "Well, it's my turn to get busy now!$"
