AzaleaTown_PokemonCenter_2F_MapScripts::
	.byte 0


AzaleaTown_PokemonCenter_2F_EventScript_SmithNPC1::
# 5 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	msgbox AzaleaTown_PokemonCenter_2F_Text_SmithNPC1, MSGBOX_NPC
	end


AzaleaTown_PokemonCenter_2F_EventScript_SmithNPC2::
# 14 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	msgbox AzaleaTown_PokemonCenter_2F_Text_SmithNPC2, MSGBOX_NPC
	end


AzaleaTown_PokemonCenter_2F_EventScript_SmithNPC3::
# 23 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	msgbox AzaleaTown_PokemonCenter_2F_Text_SmithNPC3, MSGBOX_NPC
	end


AzaleaTown_PokemonCenter_2F_EventScript_SmithNPC4::
# 32 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	msgbox AzaleaTown_PokemonCenter_2F_Text_SmithNPC4, MSGBOX_NPC
	end


AzaleaTown_PokemonCenter_2F_Text_SmithNPC1::
# 9 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

AzaleaTown_PokemonCenter_2F_Text_SmithNPC2::
# 18 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

AzaleaTown_PokemonCenter_2F_Text_SmithNPC3::
# 27 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

AzaleaTown_PokemonCenter_2F_Text_SmithNPC4::
# 36 "data/maps/AzaleaTown_PokemonCenter_2F/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"
