PacifidlogTown_House4_MapScripts::
	.byte 0


PacifidlogTown_House4_EventScript_Boy::
# 5 "data/maps/PacifidlogTown_House4/scripts.pory"
	msgbox PacifidlogTown_House4_Text_WhereDidYouComeFrom, MSGBOX_YESNO
	end


PacifidlogTown_House4_EventScript_LittleGirl::
# 10 "data/maps/PacifidlogTown_House4/scripts.pory"
	msgbox PacifidlogTown_House4_Text_SkyPokemon, MSGBOX_NPC
	end


PacifidlogTown_House4_EventScript_Woman::
# 15 "data/maps/PacifidlogTown_House4/scripts.pory"
	msgbox PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon, MSGBOX_NPC
	end


PacifidlogTown_House4_Text_WhereDidYouComeFrom::
# 19 "data/maps/PacifidlogTown_House4/scripts.pory"
	.string "Where did you come from?$"

PacifidlogTown_House4_Text_YouHaveToComeFromSomewhere::
# 23 "data/maps/PacifidlogTown_House4/scripts.pory"
	.string "No? That doesn't make any sense.\n"
	.string "You have to come from somewhere.\p"
	.string "Oh! Wait! You're not going to say you\n"
	.string "were born at the bottom of the sea?$"

PacifidlogTown_House4_Text_YesTown::
# 27 "data/maps/PacifidlogTown_House4/scripts.pory"
	.string "Yes?\n"
	.string "YES TOWN?\p"
	.string "I've never heard of a place like that.$"

PacifidlogTown_House4_Text_PeopleSawHighFlyingPokemon::
# 31 "data/maps/PacifidlogTown_House4/scripts.pory"
	.string "People were saying they saw a POKéMON\n"
	.string "flying high above HOENN.\p"
	.string "Is it flying around all the time?\n"
	.string "Doesn't it need to rest somewhere?$"

PacifidlogTown_House4_Text_SkyPokemon::
# 35 "data/maps/PacifidlogTown_House4/scripts.pory"
	.string "A sky POKéMON!\n"
	.string "A sky POKéMON!$"
