ThreeIsland_House4_MapScripts::
	.byte 0


ThreeIsland_House4_Text_GhostsInBerryForest::
# 5 "data/maps/ThreeIsland_House4/scripts.pory"
	.string "You must never, ever go out to the\n"
	.string "BERRY FOREST alone.\p"
	.string "Why? There are ghosts there.$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
# 9 "data/maps/ThreeIsland_House4/scripts.pory"
	.string "Papa keeps lying to me, and won't let me\n"
	.string "go out and play!$"
