ThreeIsland_House4_MapScripts::
	.byte 0


ThreeIsland_House4_EventScript_BaldingMan::
# 5 "data/maps/ThreeIsland_House4/scripts.pory"
	msgbox ThreeIsland_House4_Text_GhostsInBerryForest, MSGBOX_NPC
	end


ThreeIsland_House4_EventScript_LittleBoy::
# 10 "data/maps/ThreeIsland_House4/scripts.pory"
	msgbox ThreeIsland_House4_Text_PapaKeepsLyingToMe, MSGBOX_NPC
	end


ThreeIsland_House4_Text_GhostsInBerryForest::
# 15 "data/maps/ThreeIsland_House4/scripts.pory"
	.string "You must never, ever go out to\n"
	.string "the BERRY FOREST alone.\p"
	.string "Why?\n"
	.string "There are ghosts there.$"

ThreeIsland_House4_Text_PapaKeepsLyingToMe::
# 19 "data/maps/ThreeIsland_House4/scripts.pory"
	.string "Papa keeps lying to me, and won't\n"
	.string "let me go out and play!$"
