Route25_SeaCottage_MapScripts::
	.byte 0


Route25_SeaCottage_EventScript_Bill::
	end


Route25_SeaCottage_EventScript_Computer::
# 12 "data/maps/Route25_SeaCottage/scripts.pory"
	msgbox Route25_SeaCottage_Text_TeleporterIsDisplayed, MSGBOX_DEFAULT
	end


Route25_SeaCottage_Text_TeleporterIsDisplayed::
# 18 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "TELEPORTER is displayed on the PC\n"
	.string "monitor.$"
