Route25_SeaCottage_MapScripts::
# 2 "data/maps/Route25_SeaCottage/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route25_SeaCottage_OnTransition
	.byte 0


Route25_SeaCottage_Text_ImBillHelpMeOutPal::
# 6 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "Hiya! I'm a POKéMON… …No I'm not!\p"
	.string "Call me BILL! I'm a true-blue\n"
	.string "POKéMANIAC!\p"
	.string "Hey! What's with that skeptical look?\p"
	.string "I'm not joshing you, pal.\p"
	.string "I screwed up an experiment and got\n"
	.string "combined with a POKéMON!\p"
	.string "So, how about it? Help me out here!$"

Route25_SeaCottage_Text_ImBillHelpMeOutLady::
# 10 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "Hiya! I'm a POKéMON… …No I'm not!\p"
	.string "Call me BILL! I'm a true-blue\n"
	.string "POKéMANIAC!\p"
	.string "Hey! What's with that skeptical look?\p"
	.string "I'm not joshing you, lady.\p"
	.string "I screwed up an experiment and got\n"
	.string "combined with a POKéMON!\p"
	.string "So, how about it? Help me out here!$"

Route25_SeaCottage_Text_RunCellSeparationOnPC::
# 14 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "Wait till I get inside the TELEPORTER.\p"
	.string "When I do, go to my PC and run the Cell\n"
	.string "Separation System.$"

Route25_SeaCottage_Text_NoPleaseChief::
# 18 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "No!? Now don't be so cold!\p"
	.string "Come on, you gotta help a guy in deep,\n"
	.string "deep trouble!\p"
	.string "What do you say, chief? Please?\l"
	.string "Okay?\l"
	.string "All right!$"

Route25_SeaCottage_Text_NoPleaseBeautiful::
# 22 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "No!? Now don't be so cold!\p"
	.string "Come on, you gotta help a guy in deep,\n"
	.string "deep trouble!\p"
	.string "What do you say, beautiful? Please?\l"
	.string "Okay?\l"
	.string "All right!$"

Route25_SeaCottage_Text_ThanksBudTakeThis::
# 26 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "BILL: Yeehah! Thanks, bud! I owe you\n"
	.string "one!\p"
	.string "So, did you come to see my POKéMON\n"
	.string "collection?\p"
	.string "You didn't? That's a bummer.\p"
	.string "I've got to thank you… Oh, here, maybe\n"
	.string "this'll do.$"

Route25_SeaCottage_Text_ThanksLadyTakeThis::
# 30 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "BILL: Yeehah! Thanks, lady! I owe you\n"
	.string "one!\p"
	.string "So, did you come to see my POKéMON\n"
	.string "collection?\p"
	.string "You didn't? That's a bummer.\p"
	.string "I've got to thank you… Oh, here, maybe\n"
	.string "this'll do.$"

Route25_SeaCottage_Text_ReceivedSSTicketFromBill::
# 34 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "{PLAYER} received an S.S. TICKET from\n"
	.string "BILL.$"

Route25_SeaCottage_Text_YouveGotTooMuchStuff::
# 38 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "You've got too much stuff!$"

Route25_SeaCottage_Text_SSAnnePartyYouGoInstead::
# 42 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "That cruise ship S.S. ANNE is in\n"
	.string "VERMILION CITY.\p"
	.string "I hear there are lots of TRAINERS on\n"
	.string "board, too.\p"
	.string "They invited me to their party, but I\n"
	.string "can't stand fancy do's.\p"
	.string "Why don't you go instead of me? Go on\n"
	.string "and have a good time.$"

Route25_SeaCottage_Text_CheckOutRareMonsOnPC::
# 46 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "BILL: Feel like checking out some of my\n"
	.string "rare POKéMON on my PC?\p"
	.string "Go on, check out my PC.$"

Route25_SeaCottage_Text_TeleporterIsDisplayed::
# 50 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "TELEPORTER is displayed on the PC\n"
	.string "monitor.$"

Route25_SeaCottage_Text_InitiatedTeleportersCellSeparator::
# 54 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "{PLAYER} initiated the TELEPORTER's\n"
	.string "Cell Separator.$"

Route25_SeaCottage_Text_BillsFavoriteMonList::
# 58 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "BILL's favorite POKéMON list!$"

Route25_SeaCottage_Text_SeeWhichMon::
# 62 "data/maps/Route25_SeaCottage/scripts.pory"
	.string "Which POKéMON do you want to see?$"
