BattleFrontier_Mart_MapScripts::
	.byte 0


BattleFrontier_Mart_Text_ChaperonGrandson::
# 5 "data/maps/BattleFrontier_Mart/scripts.pory"
	.string "We came here to chaperon our grandson.\p"
	.string "But since we're here, we thought we\n"
	.string "should get some souvenirs.$"

BattleFrontier_Mart_Text_ProteinMakeNiceGift::
# 9 "data/maps/BattleFrontier_Mart/scripts.pory"
	.string "Dear, what do you think of this?\n"
	.string "Wouldn't this make a nice gift?\p"
	.string "It'sPROTEIN? It sounds delicious,\n"
	.string "doesn't it?$"

BattleFrontier_Mart_Text_FacilitiesDontAllowItems::
# 13 "data/maps/BattleFrontier_Mart/scripts.pory"
	.string "A lot of the BATTLE FRONTIER's\n"
	.string "facilities don't allow the use of items\l"
	.string "during battles.\p"
	.string "That rule makes things tougher than\n"
	.string "they already are!$"
