DewfordTown_Hall_MapScripts::
	.byte 0


DewfordTown_Hall_EventScript_Bookshelf::
# 7 "data/maps/DewfordTown_Hall/scripts.pory"
	msgbox DewfordTown_Hall_Text_BooksAboutTrend, MSGBOX_DEFAULT
	end


DewfordTown_Hall_EventScript_ExpertM::
	end


DewfordTown_Hall_EventScript_Girl::
	end


DewfordTown_Hall_EventScript_LittleBoy::
	end


DewfordTown_Hall_EventScript_Man::
	end


DewfordTown_Hall_EventScript_Painting::
	end


DewfordTown_Hall_EventScript_PsychicM::
	end


DewfordTown_Hall_EventScript_SchoolKidM::
	end


DewfordTown_Hall_EventScript_SludgeBombMan::
	end


DewfordTown_Hall_EventScript_Twin::
	end


DewfordTown_Hall_EventScript_Woman::
	end


DewfordTown_Hall_Text_BooksAboutTrend::
# 65 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "IDENTIFYING GOOD “{STR_VAR_1}” &\l"
	.string "BAD “{STR_VAR_1}”…\p"
	.string "THE LINK BETWEEN “{STR_VAR_1}” AND\l"
	.string "POKéMON…\p"
	.string "USEFUL “{STR_VAR_1}”…\p"
	.string "It's neatly jammed with books about\n"
	.string "“{STR_VAR_1}.”$"

DewfordTown_Hall_Text_TrendsSmile::
# 69 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "“{STR_VAR_1}'S\n"
	.string "SMILE” is the title.$"

DewfordTown_Hall_Text_LastTrend::
# 73 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "It's titled “THE LAST\n"
	.string "{STR_VAR_1}”.$"

DewfordTown_Hall_Text_GettingBoredOfTrend::
# 77 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "What's in vogue? Why, it has to be\n"
	.string "“{STR_VAR_1}”!\p"
	.string "But I'm getting kind of bored with it.\p"
	.string "I should look for the next big thing.$"

DewfordTown_Hall_Text_NotEasyToKeepUp::
# 81 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "What?!\n"
	.string "Is that so?!\p"
	.string "It's not easy for an older fellow like\n"
	.string "me to keep up with trends!$"

DewfordTown_Hall_Text_TrendsScream::
# 85 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "“{STR_VAR_1}'S\n"
	.string "SCREAM” is the title.$"

DewfordTown_Hall_Text_LoveSludgeBombButTrendInToo::
# 89 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "I love SLUDGE BOMB.\p"
	.string "But POKéMON with the move\n"
	.string "“{STR_VAR_1}”\l"
	.string "are in, too.$"

DewfordTown_Hall_Text_BirthOfTrend::
# 93 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "It's titled “THE BIRTH OF\n"
	.string "{STR_VAR_1}”.$"

DewfordTown_Hall_Text_MyHunchWasRight::
# 97 "data/maps/DewfordTown_Hall/scripts.pory"
	.string "Oh!\n"
	.string "So, my hunch was right!\p"
	.string "I'm one step closer to being hip and\n"
	.string "happening, yowza!$"
