LilycoveCity_House2_MapScripts::
	.byte 0


LilycoveCity_House2_Text_NotAwakeYetHaveThis::
# 5 "data/maps/LilycoveCity_House2/scripts.pory"
	.string "Huh? What? What's that?\p"
	.string "I'm not near awake yet… You can have\n"
	.string "this…$"

LilycoveCity_House2_Text_SleepIsEssential::
# 9 "data/maps/LilycoveCity_House2/scripts.pory"
	.string "Yawn…\p"
	.string "Sleep is essential for good health…\n"
	.string "Sleep and regain health…$"
