FortreeCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/FortreeCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/FortreeCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


FortreeCity_PokemonCenter_1F_Text_GoToSafariZone::
# 7 "data/maps/FortreeCity_PokemonCenter_1F/scripts.pory"
	.string "Listen, kid, are you working on a\n"
	.string "POKéDEX?\p"
	.string "Hmm… Go to the SAFARI ZONE. That's my\n"
	.string "suggestion.$"

FortreeCity_PokemonCenter_1F_Text_RecordCornerIsNeat::
# 11 "data/maps/FortreeCity_PokemonCenter_1F/scripts.pory"
	.string "Have you done anything at the RECORD\n"
	.string "CORNER?\p"
	.string "It's pretty neat. It mixes and matches\n"
	.string "the records of TRAINERS.\p"
	.string "I don't know quite how it works, but it's\n"
	.string "cool. It's exciting, even!$"

FortreeCity_PokemonCenter_1F_Text_DoYouKnowAboutPokenav::
# 15 "data/maps/FortreeCity_PokemonCenter_1F/scripts.pory"
	.string "Oh, wow, you have a POKéNAV! And it's\n"
	.string "just like mine!\p"
	.string "Do you know about POKéNAV's MATCH CALL\n"
	.string "system?\p"
	.string "Access it, and you can chat with\n"
	.string "registered TRAINERS anytime.\p"
	.string "It also shows you which TRAINERS want\n"
	.string "a rematch with you.\p"
	.string "It's really nifty! Those DEVON guys\n"
	.string "sure know what they're doing!$"
