Route12_NorthEntrance_2F_MapScripts::
	.byte 0


Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreMale::
# 5 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "My POKéMON's ashes are stored in\n"
	.string "POKéMON TOWER.\p"
	.string "You can have this TM. I don't need it\n"
	.string "anymore…$"

Route12_NorthEntrance_2F_Text_TakeTMDontNeedAnymoreFemale::
# 9 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "My POKéMON's ashes are stored in\n"
	.string "POKéMON TOWER.\p"
	.string "You can have this TM. I don't need it\n"
	.string "anymore…$"

Route12_NorthEntrance_2F_Text_ReceivedTM27FromLittleGirl::
# 13 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "{PLAYER} received TM27 from the\n"
	.string "little girl.$"

Route12_NorthEntrance_2F_Text_ExplainTM27::
# 17 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "TM27 is a move called RETURN…\p"
	.string "If you treat your POKéMON good, it will\n"
	.string "return your love by working\l"
	.string "its hardest in battle.$"

Route12_NorthEntrance_2F_Text_DontHaveRoomForThis::
# 21 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "You don't have room for this.$"

Route12_NorthEntrance_2F_Text_TheresManFishing::
# 25 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
# 29 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "It's POKéMON TOWER!$"
