Route12_NorthEntrance_2F_MapScripts::
	.byte 0


Route12_NorthEntrance_2F_EventScript_Lass::
	end


Route12_NorthEntrance_2F_EventScript_LeftBinoculars::
# 9 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	msgbox Route12_NorthEntrance_2F_Text_TheresManFishing, MSGBOX_SIGN
	end


Route12_NorthEntrance_2F_EventScript_RightBinoculars::
# 14 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	msgbox Route12_NorthEntrance_2F_Text_ItsPokemonTower, MSGBOX_SIGN
	end


Route12_NorthEntrance_2F_Text_TheresManFishing::
# 19 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "There's a man fishing!$"

Route12_NorthEntrance_2F_Text_ItsPokemonTower::
# 23 "data/maps/Route12_NorthEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "It's POKéMON TOWER!$"
