CinnabarIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CinnabarIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


CinnabarIsland_PokemonCenter_1F_Text_CinnabarGymLocked::
# 7 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "I came to visit the CINNABAR GYM, but\n"
	.string "the door is locked tight.\p"
	.string "There should be a key for it somewhere.\p"
	.string "Could it be in that burned-out mansion?\p"
	.string "The GYM LEADER's friend used to live\n"
	.string "there, they say.$"

CinnabarIsland_PokemonCenter_1F_Text_VisitUnionRoom::
# 11 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "Do you have lots of friends?\p"
	.string "Linking up with the usual friends is\n"
	.string "fun, of course.\p"
	.string "But how about visiting the UNION ROOM\n"
	.string "every so often?\p"
	.string "Who knows, you may end up making new\n"
	.string "friends.\p"
	.string "I think it would be worth your time to\n"
	.string "check the UNION ROOM.$"

CinnabarIsland_PokemonCenter_1F_Text_EvolutionCanWaitForNewMoves::
# 15 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "POKMON can still learn techniques after\n"
	.string "canceling evolution.\p"
	.string "Evolution can wait until new moves have\n"
	.string "been learned.$"

CinnabarIsland_PokemonCenter_1F_Text_ReadyToSailToOneIsland::
# 19 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "BILL: Hey, you kept me waiting! Ready\n"
	.string "to set sail to ONE ISLAND?$"

CinnabarIsland_PokemonCenter_1F_Text_OhNotDoneYet::
# 23 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "Oh, you're still not done yet?$"

CinnabarIsland_PokemonCenter_1F_Text_LetsGo::
# 27 "data/maps/CinnabarIsland_PokemonCenter_1F/scripts.pory"
	.string "Well, that's it. Let's go!$"
