BattleFrontier_BattlePalaceBattleRoom_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattlePalaceBattleRoom_OnTransition
# 3 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePalaceBattleRoom_OnFrame
# 4 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePalaceBattleRoom_OnWarp
	.byte 0


BattleFrontier_BattlePalaceBattleRoom_Text_LetMeRestoreYourMons::
# 8 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Excellent Let me restore your POKMON.$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor2ndOpponent::
# 12 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 2nd opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor3rdOpponent::
# 16 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 3rd opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor4thOpponent::
# 20 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 4th opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor5thOpponent::
# 24 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 5th opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor6thOpponent::
# 28 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 6th opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_PreparedFor7thOpponent::
# 32 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The 7th opponent is next. Are you\n"
	.string "prepared?$"

BattleFrontier_BattlePalaceBattleRoom_Text_SaveAndQuitGame::
# 36 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Would you like to save and quit the\n"
	.string "game?$"

BattleFrontier_BattlePalaceBattleRoom_Text_WishToQuitChallenge::
# 40 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Do you wish to quit your challenge?$"

BattleFrontier_BattlePalaceBattleRoom_Text_SavingData::
# 44 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Saving the data. Have patience$"

BattleFrontier_BattlePalaceBattleRoom_Text_RecordLastMatch::
# 48 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Do you wish to record your latest match\n"
	.string "on your FRONTIER PASS?$"

BattleFrontier_BattlePalaceBattleRoom_Text_ChallengingPalaceMaven::
# 52 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "And now\p"
	.string "By winning consistently, you have\n"
	.string "earned the privilege of challenging\l"
	.string "our master, the PALACE MAVEN$"

BattleFrontier_BattlePalaceBattleRoom_Text_ReadyForPalaceMaven::
# 56 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "I shall send for the PALACE MAVEN. Are\n"
	.string "you ready?$"

BattleFrontier_BattlePalaceBattleRoom_Text_AnnounceArrivalOfSpenser::
# 60 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Let great fanfare announce the arrival\n"
	.string "of the PALACE MAVEN, SPENSER!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserFirstIntro::
# 64 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: My physical being is with\n"
	.string "POKMON always!\p"
	.string "My heart beats as one with POKMON\n"
	.string "always!\p"
	.string "Young one of a TRAINER! Do you believe\n"
	.string "in your POKMON?\p"
	.string "Can you believe them through and\n"
	.string "through?\p"
	.string "If your bonds of trust are frail, you\n"
	.string "will never beat my brethren!$"

BattleFrontier_BattlePalaceBattleRoom_Text_ProveYourBondWithMons::
# 68 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The bond you share with your POKMON!\n"
	.string "Prove it to me here!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserPostSilverBattle::
# 72 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: Gwahahah!\p"
	.string "Hah, you never fell for my bluster!\n"
	.string "Sorry for trying that stunt!\p"
	.string "Here! Bring me the thing!$"

BattleFrontier_BattlePalaceBattleRoom_Text_LetsSeeFrontierPass::
# 76 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "My, my, if only you could maintain that\n"
	.string "facade of distinguished authority\p"
	.string "Here! Let's see your FRONTIER PASS!$"

BattleFrontier_BattlePalaceBattleRoom_Text_ReceivedSpiritsSymbol::
# 80 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The Spirits Symbol was embossed on the\n"
	.string "FRONTIER PASS!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserAwaitNextTime::
# 84 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: Your POKMON's eyes are truly\n"
	.string "clear and unclouded.\p"
	.string "I will eagerly await the next\n"
	.string "opportunity to see you.$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserThisTimeWontHoldBack::
# 88 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: Gwahahah! You've battled your\n"
	.string "way up again?\p"
	.string "You must have developed a truly\n"
	.string "formidable bond with your POKMON.\p"
	.string "So be it!\p"
	.string "This time, I won't bluster or hold back.\n"
	.string "This time, there's no fooling around.\p"
	.string "Ready now? Prepare to lose!$"

BattleFrontier_BattlePalaceBattleRoom_Text_Kaaah::
# 92 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "Kaaah!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserYourTeamIsAdmirable::
# 96 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: Well, that was some display!\n"
	.string "Even fully unleashed, my brethren\l"
	.string "could not overpower you.\p"
	.string "Your team spirit is truly admirable!\p"
	.string "Here! Bring me that thing, will you?$"

BattleFrontier_BattlePalaceBattleRoom_Text_HurryWithFrontierPass::
# 100 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "My, my, if only you could maintain a\n"
	.string "certain level of decorum\p"
	.string "Gaaah, here! Hurry with that FRONTIER\n"
	.string "PASS, you!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpiritsSymbolTookGoldenShine::
# 104 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "The Spirits Symbol took on a golden\n"
	.string "shine!$"

BattleFrontier_BattlePalaceBattleRoom_Text_SpenserComeSeeMeAgain::
# 108 "data/maps/BattleFrontier_BattlePalaceBattleRoom/scripts.pory"
	.string "SPENSER: Gwahahah!\p"
	.string "Come see me time and again! My brethren\n"
	.string "and I will be waiting!$"
