SlateportCity_House_MapScripts::
	.byte 0


SlateportCity_House_Text_NatureToDoWithStatGains::
# 5 "data/maps/SlateportCity_House/scripts.pory"
	.string "My POKéMON has a HASTY nature.\p"
	.string "It has higher SPEED compared to my\n"
	.string "other POKéMON.\p"
	.string "Maybe their nature has something to do\n"
	.string "with the stat gains of POKéMON.$"

SlateportCity_House_Text_MustBeGoingToBattleTent::
# 9 "data/maps/SlateportCity_House/scripts.pory"
	.string "You're a TRAINER, aren't you?\p"
	.string "Since you came to SLATEPORT CITY, you\n"
	.string "must be going to the BATTLE TENT.$"
