BattleFrontier_BattlePikeThreePathRoom_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePikeRoom_OnResume
# 3 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePikeThreePathRoom_OnFrame
# 4 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattlePikeThreePathRoom_OnWarp
	.byte 0


BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom1::
# 8 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 1st room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom3::
# 12 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 3rd room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom5::
# 16 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 5th room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom7::
# 20 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 7th room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom9::
# 24 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 9th room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom11::
# 28 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 11th room$"

BattleFrontier_BattlePikeThreePathRoom_Text_CurrentlyInRoom13::
# 32 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "You are currently in the 13th room$"

BattleFrontier_BattlePikeThreePathRoom_Text_ContinueWithChallenge::
# 36 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Will you continue with your challenge?$"

BattleFrontier_BattlePikeThreePathRoom_Text_SaveChallengeAndQuit::
# 40 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Would you like to save your challenge\n"
	.string "and quit the game for now?$"

BattleFrontier_BattlePikeThreePathRoom_Text_RetireFromChallenge::
# 44 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Do you wish to retire from your Battle\n"
	.string "Choice challenge?$"

BattleFrontier_BattlePikeThreePathRoom_Text_AwaitingReturnSaveBeforeResume::
# 48 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "We've been awaiting your return\p"
	.string "Before resuming your Battle Choice\n"
	.string "challenge, let me save the game$"

BattleFrontier_BattlePikeThreePathRoom_Text_PleaseEnjoyChallenge::
# 52 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Please do enjoy your Battle Choice\n"
	.string "challenge$"

BattleFrontier_BattlePikeThreePathRoom_Text_SavingYourData::
# 56 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "I am saving your data A little time,\n"
	.string "please$"

BattleFrontier_BattlePike_Text_PathBlockedNoTurningBack::
# 60 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "The path is blocked! And there is no\n"
	.string "turning back$"

BattleFrontier_BattlePikeThreePathRoom_Text_FindingItDifficultToChoose::
# 64 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "I beg your pardon, but\p"
	.string "Are you perhaps finding it difficult to\n"
	.string "choose your path?$"

BattleFrontier_BattlePikeThreePathRoom_Text_ApologizeForImpertinence::
# 68 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "I see I apologize for my impertinence$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutRightPath::
# 72 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Ah, let me see There is something about\n"
	.string "the path on the right$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutCenterPath::
# 76 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Ah, let me see There is something about\n"
	.string "the path in the center$"

BattleFrontier_BattlePikeThreePathRoom_Text_SomethingAboutLeftPath::
# 80 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Ah, let me see There is something about\n"
	.string "the path on the left$"

BattleFrontier_BattlePikeThreePathRoom_Text_AromaOfPokemon::
# 84 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "It seems to have the distinct aroma of\n"
	.string "POKMON wafting around it$"

BattleFrontier_BattlePikeThreePathRoom_Text_PresenceOfPeople::
# 88 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "Is it A TRAINER? I sense the presence\n"
	.string "of people$"

BattleFrontier_BattlePikeThreePathRoom_Text_HeardWhispering::
# 92 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "I seem to have heard something It may\n"
	.string "have been whispering$"

BattleFrontier_BattlePikeThreePathRoom_Text_WaveOfNostaliga::
# 96 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "For some odd reason, I felt a wave of\n"
	.string "nostalgia coming from it$"

BattleFrontier_BattlePikeThreePathRoom_Text_TerrifyingEvent::
# 100 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "I am sorry to say\p"
	.string "A terrifying event, yes, a horrible one,\n"
	.string "is about to befall you\p"
	.string "I urge you to pay the utmost care and\n"
	.string "prepare for the worst$"

BattleFrontier_BattlePikeThreePathRoom_Text_DreadfulPresence::
# 104 "data/maps/BattleFrontier_BattlePikeThreePathRoom/scripts.pory"
	.string "From every path I sense a dreadful\n"
	.string "presence$"
