BattleFrontier_Lounge5_MapScripts::
	.byte 0


BattleFrontier_Lounge5_MapScripts::
	return


BattleFrontier_Lounge5_Text_NatureGirlGreeting::
# 8 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Ehehe! I can tell what POKéMON are\n"
	.string "thinking!\p"
	.string "Please! Can I see your POKéMON?$"

BattleFrontier_Lounge5_Text_NatureGirlNoneShown::
# 12 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Boo! Cheapie!$"

BattleFrontier_Lounge5_Text_NatureGirlAttackHighAttackLow::
# 16 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to battle! It will\n"
	.string "battle even if it has a lot\l"
	.string "of ouchies!$"

BattleFrontier_Lounge5_Text_NatureGirlAttackHighDefenseLow::
# 20 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to battle! But if\n"
	.string "it gets enough ouchies,\l"
	.string "it will worry about itself!$"

BattleFrontier_Lounge5_Text_NatureGirlAttackHighSupportLow::
# 24 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to battle! But if\n"
	.string "it gets enough ouchies,\l"
	.string "it will turn sneaky!$"

BattleFrontier_Lounge5_Text_NatureGirlDefenseHighAttackLow::
# 28 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it looks after itself! But\n"
	.string "if it gets enough ouchies,\l"
	.string "it will hit back!$"

BattleFrontier_Lounge5_Text_NatureGirlDefenseHighDefenseLow::
# 32 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it looks after itself! It\n"
	.string "says it worries about itself whether\l"
	.string "or not it has a lot of ouchies!$"

BattleFrontier_Lounge5_Text_NatureGirlDefenseHighSupportLow::
# 36 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it looks after itself! But\n"
	.string "if it gets enough ouchies,\l"
	.string "it will turn sneaky!$"

BattleFrontier_Lounge5_Text_NatureGirlSupportHighAttackLow::
# 40 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to be sneaky! But\n"
	.string "if it gets enough ouchies,\l"
	.string "it will hit back!$"

BattleFrontier_Lounge5_Text_NatureGirlSupportHighDefenseLow::
# 44 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to be sneaky! But\n"
	.string "if it gets enough ouchies,\l"
	.string "it will worry about itself!$"

BattleFrontier_Lounge5_Text_NatureGirlSupportHighSupportLow::
# 48 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "Hmhm…\p"
	.string "This one says it likes to be sneaky! It\n"
	.string "says it likes to be sneaky even\l"
	.string "if it has a lot of ouchies!$"

BattleFrontier_Lounge5_Text_NatureGirlEgg::
# 52 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "That's silly! An EGG is asleep! I can't\n"
	.string "talk to it!$"

BattleFrontier_Lounge5_Text_LadyClaimsSheUnderstandsPokemon::
# 56 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "How charming! That little lady claims\n"
	.string "she can\l"
	.string "understand POKéMON!$"

BattleFrontier_Lounge5_Text_GirlSayingSomethingProfound::
# 60 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "I have this feeling that the little girl\n"
	.string "is saying something profound.$"

BattleFrontier_Lounge5_Text_GirlPlaysAtRedHouseALot::
# 64 "data/maps/BattleFrontier_Lounge5/scripts.pory"
	.string "I know something!\p"
	.string "That little girl plays at the red house a\n"
	.string "lot!$"
