RocketHideout_B2F_MapScripts::
	.byte 0


RocketHideout_B2F_Text_GruntIntro::
# 5 "data/maps/RocketHideout_B2F/scripts.pory"
	.string "BOSS said you can see ghosts with the\n"
	.string "SILPH SCOPE.$"

RocketHideout_B2F_Text_GruntDefeat::
# 9 "data/maps/RocketHideout_B2F/scripts.pory"
	.string "I surrender!$"

RocketHideout_B2F_Text_GruntPostBattle::
# 13 "data/maps/RocketHideout_B2F/scripts.pory"
	.string "The TEAM ROCKET HQ has four\n"
	.string "underground floors.\p"
	.string "Think you can reach the BOSS?$"
