LilycoveCity_CoveLilyMotel_1F_MapScripts::
	.byte 0


LilycoveCity_CoveLilyMotel_1F_Text_GuestsDoubledByMascot::
# 5 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Hm, so they doubled the guests by using\n"
	.string "POKMON as attractions?\p"
	.string "Hm, well, maybe I should make a cute\n"
	.string "POKMON our inn's mascot.\p"
	.string "I wonder if that will attract more\n"
	.string "guests to stay with us?$"

LilycoveCity_CoveLilyMotel_1F_Text_NoGuestsWithTeamAqua::
# 9 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Oh, sorry, sorry! I was too involved in\n"
	.string "watching TV!\p"
	.string "Since that TEAM AQUA came to town, the\n"
	.string "tourists have been staying away.$"

LilycoveCity_CoveLilyMotel_1F_Text_CantSeeTheTV::
# 13 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Hey, down in front! I can't see the TV!$"

LilycoveCity_CoveLilyMotel_1F_Text_MonFoundLostItem::
# 17 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Amazing! You're telling me a POKMON\n"
	.string "found someone's lost item?\p"
	.string "That's something. If we had some smart\n"
	.string "POKMON like that\p"
	.string "We could recover anything that our\n"
	.string "guests mislaid$"

LilycoveCity_CoveLilyMotel_1F_Text_HeardAquaHideoutBusted::
# 21 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Oh, sorry, sorry! I was too involved in\n"
	.string "watching TV!\p"
	.string "I heard that someone busted the TEAM\n"
	.string "AQUA HIDEOUT.\p"
	.string "Thanks to that, we just booked a\n"
	.string "reservation from a big group.\p"
	.string "It was a company called Uh GAME\n"
	.string "something$"

LilycoveCity_CoveLilyMotel_1F_Text_HouseSittingMonCaughtBurglar::
# 25 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Amazing! A house-sitting POKMON caught\n"
	.string "a burglar?\p"
	.string "That's something. If we had a tough\n"
	.string "POKMON as a security guard\p"
	.string "We would be able to provide our guests\n"
	.string "with greater safety.$"

LilycoveCity_CoveLilyMotel_1F_Text_BetterGetWorkingOnGuestsDinner::
# 29 "data/maps/LilycoveCity_CoveLilyMotel_1F/scripts.pory"
	.string "Oh, sorry, sorry! I was too involved in\n"
	.string "watching TV.\p"
	.string "Oh, yes. A big group of guests arrived a\n"
	.string "little while ago.\p"
	.string "They booked in as GAME FREAK, so I\n"
	.string "guess they must make games.\p"
	.string "Uh-oh, I'd better get working on their\n"
	.string "dinner!$"
