PetalburgCity_House1_MapScripts::
	.byte 0


PetalburgCity_House1_EventScript_Man::
# 5 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_TravelingIsWonderful, MSGBOX_NPC
	end


PetalburgCity_House1_EventScript_Woman::
# 10 "data/maps/PetalburgCity_House1/scripts.pory"
	msgbox PetalburgCity_House1_Text_GoOnAdventure, MSGBOX_NPC
	end


PetalburgCity_House1_Text_GoOnAdventure::
# 14 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Sigh…\p"
	.string "I wish I could go on an adventure\n"
	.string "with some POKéMON…\p"
	.string "Crawl through some damp grass…\n"
	.string "Climb rocky, rugged mountains…\p"
	.string "Cross the raging seas…\n"
	.string "Wander about in dark caves…\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick…\p"
	.string "It must be fabulous to travel!$"

PetalburgCity_House1_Text_TravelingIsWonderful::
# 18 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Traveling is wonderful!\p"
	.string "When I was young, I roamed the seas\n"
	.string "and the mountains!$"
