PetalburgCity_House1_MapScripts::
	.byte 0


PetalburgCity_House1_Text_TravelingIsWonderful::
# 5 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Traveling is wonderful!\p"
	.string "When I was young, I roamed the seas and\n"
	.string "the mountains!$"

PetalburgCity_House1_Text_GoOnAdventure::
# 9 "data/maps/PetalburgCity_House1/scripts.pory"
	.string "Sigh\p"
	.string "I wish I could go on an adventure with\n"
	.string "some POKMON\p"
	.string "Crawl through some damp grass Climb\n"
	.string "rocky, rugged mountains\p"
	.string "Cross the raging seas Wander about in\n"
	.string "dark caves\p"
	.string "And, sometimes, even get a little\n"
	.string "homesick\p"
	.string "It must be fabulous to travel!$"
