PokemonTower_2F_MapScripts::
	.byte 0


PokemonTower_2F_Text_RivalIntro::
# 5 "data/maps/PokemonTower_2F/scripts.pory"
	.string "{RIVAL}: Hey, {PLAYER}! What\n"
	.string "brings you here?\l"
	.string "Is your POKMON dead?\p"
	.string "Hey! It's alive!\p"
	.string "I can at least make them faint! Let's\n"
	.string "go!$"

PokemonTower_2F_Text_RivalDefeat::
# 9 "data/maps/PokemonTower_2F/scripts.pory"
	.string "What? You stinker!\p"
	.string "I took it easy on you, too!$"

PokemonTower_2F_Text_RivalVictory::
# 13 "data/maps/PokemonTower_2F/scripts.pory"
	.string "{RIVAL}\l"
	.string "\l"
	.string "$"

PokemonTower_2F_Text_RivalPostBattle::
# 17 "data/maps/PokemonTower_2F/scripts.pory"
	.string "How's your POKDEX coming? I just\n"
	.string "caught a CUBONE!\p"
	.string "I can't find the bigger MAROWAK. Where\n"
	.string "could they be?\p"
	.string "I bet there aren't any left!\p"
	.string "Well, I better get going. I've got a lot\n"
	.string "to accomplish,\l"
	.string "unlike you.\p"
	.string "Smell ya later!$"

PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
# 21 "data/maps/PokemonTower_2F/scripts.pory"
	.string "Even we could not identify the wayward\n"
	.string "ghosts.\p"
	.string "A SILPH SCOPE might be able to unmask\n"
	.string "them.$"
