PokemonTower_2F_MapScripts::
	.byte 0


PokemonTower_2F_EventScript_Channeler::
# 5 "data/maps/PokemonTower_2F/scripts.pory"
	msgbox PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts, MSGBOX_NPC
	end


PokemonTower_2F_EventScript_RivalTriggerDown::
	end


PokemonTower_2F_EventScript_RivalTriggerRight::
	end


PokemonTower_2F_Text_SilphScopeCouldUnmaskGhosts::
# 18 "data/maps/PokemonTower_2F/scripts.pory"
	.string "Even we could not identify the\n"
	.string "wayward ghosts.\p"
	.string "A SILPH SCOPE might be able to\n"
	.string "unmask them.$"
