GoldenrodCity_Underground_B1F_MapScripts::
	.byte 0


GoldenrodCity_Underground_B1F_EventScript_SmithNPC1::
# 5 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	msgbox GoldenrodCity_Underground_B1F_Text_SmithNPC1, MSGBOX_NPC
	end


GoldenrodCity_Underground_B1F_EventScript_SmithNPC2::
# 14 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	msgbox GoldenrodCity_Underground_B1F_Text_SmithNPC2, MSGBOX_NPC
	end


GoldenrodCity_Underground_B1F_EventScript_SmithNPC3::
# 23 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	msgbox GoldenrodCity_Underground_B1F_Text_SmithNPC3, MSGBOX_NPC
	end


GoldenrodCity_Underground_B1F_Text_SmithNPC1::
# 9 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

GoldenrodCity_Underground_B1F_Text_SmithNPC2::
# 18 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

GoldenrodCity_Underground_B1F_Text_SmithNPC3::
# 27 "data/maps/GoldenrodCity_Underground_B1F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
