Route128_MapScripts::
# 2 "data/maps/Route128/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route128_OnTransition
# 3 "data/maps/Route128/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route128_OnFrame
	.byte 0


Route128_MapScripts::
# 7 "data/maps/Route128/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route128_OnTransition
# 8 "data/maps/Route128/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route128_OnFrame
	return


Route128_Text_ArchieWhatHappened::
# 12 "data/maps/Route128/scripts.pory"
	.string "ARCHIE: What happened… What is this\n"
	.string "wretched scene…\p"
	.string "Did I…make a horrible mistake?$"

Route128_Text_ArchieIOnlyWanted::
# 16 "data/maps/Route128/scripts.pory"
	.string "I… I only wanted…$"

Route128_Text_MaxieDoYouUnderstandNow::
# 20 "data/maps/Route128/scripts.pory"
	.string "MAXIE: Do you understand now, ARCHIE?\p"
	.string "Do you finally see how disastrous your\n"
	.string "dream turned out to be?\p"
	.string "We have to hurry! We have to do\n"
	.string "something before the situation goes\l"
	.string "completely out of control!$"

Route128_Text_MaxieResposibilityFallsToArchieAndMe::
# 24 "data/maps/Route128/scripts.pory"
	.string "MAXIE: {PLAYER}, don't say anything.\p"
	.string "I know that I have no right to be\n"
	.string "critical of ARCHIE…\p"
	.string "But the way things are now, I doubt\n"
	.string "that we humans will be capable of\l"
	.string "doing anything about it.\p"
	.string "But neither can we stand by and just\n"
	.string "watch helplessly.\p"
	.string "The responsibility for putting an end\n"
	.string "to this falls to ARCHIE and me…$"

Route128_Text_MaxieThisDefiesBelief::
# 28 "data/maps/Route128/scripts.pory"
	.string "MAXIE: This defies belief…\p"
	.string "Those super-ancient POKéMON…\p"
	.string "Their power is unbelievable. They've\n"
	.string "upset the balance of nature…$"

Route128_Text_StevenWhatIsHappening::
# 32 "data/maps/Route128/scripts.pory"
	.string "STEVEN: {PLAYER}{KUN}! What is happening?$"

Route128_Text_StevenWholeWorldWillDrown::
# 36 "data/maps/Route128/scripts.pory"
	.string "This is terrible…\p"
	.string "After the scorching heat wave ended,\n"
	.string "this deluge began.\p"
	.string "If this doesn't stop, all of HOENN… No,\n"
	.string "the whole world will drown.\p"
	.string "This huge rain cloud is spreading from\n"
	.string "above SOOTOPOLIS…\p"
	.string "What in the world is taking place there?\p"
	.string "There's no point arguing here…\n"
	.string "SOOTOPOLIS might provide answers…$"

Route128_Text_StevenImGoingToSootopolis::
# 40 "data/maps/Route128/scripts.pory"
	.string "{PLAYER}{KUN}… I don't know what you\n"
	.string "intend to do,\l"
	.string "but don't do anything reckless.\p"
	.string "Okay. I'm going to SOOTOPOLIS.$"
