SevenIsland_House_Room2_MapScripts::
# 2 "data/maps/SevenIsland_House_Room2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_House_Room2_OnTransition
# 3 "data/maps/SevenIsland_House_Room2/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SevenIsland_House_Room2_OnFrame
	.byte 0


SevenIsland_House_Room2_MapScripts::
# 7 "data/maps/SevenIsland_House_Room2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SevenIsland_House_Room2_OnTransition
# 8 "data/maps/SevenIsland_House_Room2/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SevenIsland_House_Room2_OnFrame
	return

