SSAnne_1F_Corridor_MapScripts::
	.byte 0


SSAnne_1F_Corridor_Text_LeStrongSilentType::
# 5 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	.string "Bonjour! I am le waiter on this ship!\p"
	.string "I will be happy to serve you anything\n"
	.string "you please!\p"
	.string "Ah! Le strong silent type!$"

SSAnne_1F_Corridor_Text_PassengersAreRestless::
# 9 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	.string "The passengers are restless from this\n"
	.string "long voyage.\p"
	.string "You might be challenged by the more\n"
	.string "bored ones!$"
