SSAnne_1F_Corridor_MapScripts::
	.byte 0


SSAnne_1F_Corridor_EventScript_Sailor::
# 5 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_PassengersAreRestless, MSGBOX_NPC
	end


SSAnne_1F_Corridor_EventScript_WorkerM::
# 10 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	msgbox SSAnne_1F_Corridor_Text_LeStrongSilentType, MSGBOX_NPC
	end


SSAnne_1F_Corridor_Text_PassengersAreRestless::
# 15 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	.string "The passengers are restless from\n"
	.string "this long voyage.\p"
	.string "You might be challenged by the\n"
	.string "more bored ones!$"

SSAnne_1F_Corridor_Text_LeStrongSilentType::
# 19 "data/maps/SSAnne_1F_Corridor/scripts.pory"
	.string "Bonjour!\n"
	.string "I am le waiter on this ship!\p"
	.string "I will be happy to serve you\n"
	.string "anything you please!\p"
	.string "… … …\n"
	.string "Ah! Le strong silent type!$"
