CelesticTown_MapScripts::
	.byte 0


CelesticTown_EventScript_Sign1::
# 6 "data/maps/CelesticTown/scripts.pory"
	msgbox CelesticTown_Text_Sign1, MSGBOX_SIGN
	end


CelesticTown_EventScript_SmithNPC1::
# 15 "data/maps/CelesticTown/scripts.pory"
	msgbox CelesticTown_Text_SmithNPC1, MSGBOX_NPC
	end


CelesticTown_EventScript_SmithNPC2::
# 24 "data/maps/CelesticTown/scripts.pory"
	msgbox CelesticTown_Text_SmithNPC2, MSGBOX_NPC
	end


CelesticTown_EventScript_SmithNPC3::
# 33 "data/maps/CelesticTown/scripts.pory"
	msgbox CelesticTown_Text_SmithNPC3, MSGBOX_NPC
	end


CelesticTown_Text_Sign1::
# 10 "data/maps/CelesticTown/scripts.pory"
	.string "CelesticTown Sign 1$"

CelesticTown_Text_SmithNPC1::
# 19 "data/maps/CelesticTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CelesticTown_Text_SmithNPC2::
# 28 "data/maps/CelesticTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

CelesticTown_Text_SmithNPC3::
# 37 "data/maps/CelesticTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
