Route5_SouthEntrance_MapScripts::
	.byte 0


Route5_SouthEntrance_EventScript_Guard::
# 5 "data/maps/Route5_SouthEntrance/scripts.pory"
	msgbox Route5_SouthEntrance_Text_HiHowsItGoing, MSGBOX_NPC
	end


Route5_SouthEntrance_EventScript_GuardTriggerLeft::
	end


Route5_SouthEntrance_EventScript_GuardTriggerMid::
	end


Route5_SouthEntrance_EventScript_GuardTriggerRight::
	end


Route5_SouthEntrance_Text_HiHowsItGoing::
# 22 "data/maps/Route5_SouthEntrance/scripts.pory"
	.string "Hi, how's it going?$"
