CeruleanCity_Gym_MapScripts::
	.byte 0


CeruleanCity_Gym_Text_MistyIntro::
# 5 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "Hi, you're a new face!\p"
	.string "Only those TRAINERS who have a policy\n"
	.string "about POKéMON can turn pro.\p"
	.string "What is your approach when you catch\n"
	.string "and train POKéMON?\p"
	.string "My policy is an all-out offensive with\n"
	.string "WATER-type POKéMON!{PLAY_BGM}{MUS_RG_GYM}$"

CeruleanCity_Gym_Text_ExplainTM03::
# 9 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "TM03 teaches WATER PULSE.\p"
	.string "Use it on an aquatic POKéMON!$"

CeruleanCity_Gym_Text_ExplainCascadeBadge::
# 13 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "The CASCADEBADGE makes all POKéMON up\n"
	.string "to Lv. 30 obey.\p"
	.string "That includes even outsiders you got in\n"
	.string "trades.\p"
	.string "There's more. You can now use CUT\n"
	.string "anytime, even out of battle.\p"
	.string "You can CUT down small trees to open\n"
	.string "new pathways.\p"
	.string "You can also have my favorite TM.$"

CeruleanCity_Gym_Text_ReceivedTM03FromMisty::
# 17 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "{PLAYER} received TM03 from MISTY.$"

CeruleanCity_Gym_Text_BetterMakeRoomForThis::
# 21 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "You better make room for this!$"

CeruleanCity_Gym_Text_MistyDefeat::
# 25 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "Wow! You're too much!\p"
	.string "All right!\p"
	.string "You can have the CASCADEBADGE to show\n"
	.string "you beat me.$"

CeruleanCity_Gym_Text_DianaIntro::
# 29 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "What? You? I'm more than good enough\n"
	.string "for you!\p"
	.string "MISTY won't have to be bothered.$"

CeruleanCity_Gym_Text_DianaDefeat::
# 33 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "You overwhelmed me!$"

CeruleanCity_Gym_Text_DianaPostBattle::
# 37 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "You have to face other TRAINERS to see\n"
	.string "how good you really are.$"

CeruleanCity_Gym_Text_LuisIntro::
# 41 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "Splash!\p"
	.string "I'm first up! Let's do it!$"

CeruleanCity_Gym_Text_LuisDefeat::
# 45 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "That can't be!$"

CeruleanCity_Gym_Text_LuisPostBattle::
# 49 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "MISTY is a TRAINER who's going to keep\n"
	.string "improving.\p"
	.string "She won't lose to someone like you!$"

CeruleanCity_Gym_Text_GymGuyAdvice::
# 53 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "Let me give you some advice!\p"
	.string "The LEADER, MISTY, is a pro who uses\n"
	.string "WATER-type POKéMON.\p"
	.string "You can drain all their water with\n"
	.string "GRASS-type POKéMON.\p"
	.string "Or, you might use ELECTRIC-type\n"
	.string "POKéMON and zap them!$"

CeruleanCity_Gym_Text_WeMakePrettyGoodTeam::
# 57 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "You beat MISTY! See, what'd I tell ya?\p"
	.string "You and me, kid, we make a pretty\n"
	.string "darn-good team!$"

CeruleanCity_Gym_Text_GymStatue::
# 61 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "CERULEAN POKéMON GYM LEADER: MISTY\p"
	.string "WINNING TRAINERS: {RIVAL}$"

CeruleanCity_Gym_Text_GymStatuePlayerWon::
# 65 "data/maps/CeruleanCity_Gym/scripts.pory"
	.string "CERULEAN POKéMON GYM LEADER: MISTY\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
