FuchsiaCity_House3_MapScripts::
	.byte 0


FuchsiaCity_House3_EventScript_MoveDeleter::
# 5 "data/maps/FuchsiaCity_House3/scripts.pory"
	msgbox FuchsiaCity_House3_Text_WouldYouLikeToForgetMove, MSGBOX_YESNO
	end


FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
# 10 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Uh…\n"
	.string "Oh, yes, I'm the MOVE DELETER.\p"
	.string "I can make POKéMON forget their\n"
	.string "moves.\p"
	.string "Would you like me to do that?$"
