FuchsiaCity_House3_MapScripts::
	.byte 0


FuchsiaCity_House3_Text_WouldYouLikeToForgetMove::
# 5 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Uh… Oh, yes, I'm the MOVE DELETER.\p"
	.string "I can make POKéMON forget their moves.\p"
	.string "Would you like me to do that?$"

FuchsiaCity_House3_Text_WhichMonShouldForgetMove::
# 9 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Which POKéMON should forget a move?$"

FuchsiaCity_House3_Text_WhichMoveShouldBeForgotten::
# 13 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Which move should be forgotten?$"

FuchsiaCity_House3_Text_MonOnlyKnowsOneMove::
# 17 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "{STR_VAR_1} seems to know only one\n"
	.string "move…$"

FuchsiaCity_House3_Text_MonsMoveShouldBeForgotten::
# 21 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
	.string "That move should be forgotten?$"

FuchsiaCity_House3_Text_MonHasForgottenMoveCompletely::
# 25 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "It worked to perfection!\p"
	.string "{STR_VAR_1} has forgotten\n"
	.string "{STR_VAR_2} completely.$"

FuchsiaCity_House3_Text_ComeAgainToForgetOtherMoves::
# 29 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "Come again if there are other moves to\n"
	.string "be forgotten.$"

FuchsiaCity_House3_Text_NoEggShouldKnowMoves::
# 33 "data/maps/FuchsiaCity_House3/scripts.pory"
	.string "What? No EGG should know any moves.$"
