PewterCity_MapScripts::
	.byte 0


PewterCity_EventScript_BugCatcher::
# 5 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_DoYouKnowWhatImDoing, MSGBOX_YESNO
	end


PewterCity_EventScript_CitySign::
# 10 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_CitySign, MSGBOX_SIGN
	end


PewterCity_EventScript_FatMan::
	end


PewterCity_EventScript_GymGuide::
	end


PewterCity_EventScript_GymGuideTriggerBottom::
	end


PewterCity_EventScript_GymGuideTriggerMid::
	end


PewterCity_EventScript_GymGuideTriggerRight::
	end


PewterCity_EventScript_GymGuideTriggerTop::
	end


PewterCity_EventScript_GymSign::
# 41 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_GymSign, MSGBOX_SIGN
	end


PewterCity_EventScript_Lass::
# 47 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_ClefairyCameFromMoon, MSGBOX_NPC
	end


PewterCity_EventScript_MuseumGuide::
# 52 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_DidYouCheckOutMuseum, MSGBOX_YESNO
	end


PewterCity_EventScript_MuseumSign::
# 57 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_MuseumOfScience, MSGBOX_SIGN
	end


PewterCity_EventScript_PoliceNotice::
# 62 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_CallPoliceIfInfoOnThieves, MSGBOX_SIGN
	end


PewterCity_EventScript_RunningShoesAide::
	end


PewterCity_EventScript_RunningShoesAideTriggerBottom::
	end


PewterCity_EventScript_RunningShoesAideTriggerMid::
	end


PewterCity_EventScript_RunningShoesAideTriggerTop::
	end


PewterCity_EventScript_TrainerTips::
# 83 "data/maps/PewterCity/scripts.pory"
	msgbox PewterCity_Text_TrainerTipsEarningEXP, MSGBOX_SIGN
	end


PewterCity_Text_GymSign::
# 88 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER CITY POKéMON GYM LEADER: BROCK\l"
	.string "The Rock-Solid POKéMON TRAINER!$"

PewterCity_Text_MuseumOfScience::
# 92 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_CitySign::
# 96 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER CITY A Stone Gray City$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
# 100 "data/maps/PewterCity/scripts.pory"
	.string "NOTICE!\p"
	.string "Thieves have been stealing POKéMON\n"
	.string "fossils from MT. MOON.\p"
	.string "Please call the PEWTER POLICE if you\n"
	.string "have any information.$"

PewterCity_Text_TrainerTipsEarningEXP::
# 104 "data/maps/PewterCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "All POKéMON that appear in battle,\n"
	.string "however briefly, earn EXP Points.$"

PewterCity_Text_DoYouKnowWhatImDoing::
# 108 "data/maps/PewterCity/scripts.pory"
	.string "Psssst!\n"
	.string "Do you know what I'm doing?$"

PewterCity_Text_ClefairyCameFromMoon::
# 112 "data/maps/PewterCity/scripts.pory"
	.string "CLEFAIRY came from the moon.\n"
	.string "That's what the rumor is.\p"
	.string "They appeared after MOON STONES\n"
	.string "fell on MT. MOON.$"

PewterCity_Text_DidYouCheckOutMuseum::
# 116 "data/maps/PewterCity/scripts.pory"
	.string "Did you check out the MUSEUM?$"
