PewterCity_MapScripts::
# 2 "data/maps/PewterCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PewterCity_OnTransition
	.byte 0


Text_DreamEaterTeach::
# 6 "data/maps/PewterCity/scripts.pory"
	.string "Yawn! I must have dozed off in the sun.\p"
	.string "I had this weird dream about a DROWZEE\n"
	.string "eating my dream.\p"
	.string "And I learned how to eat dreams\p"
	.string "Oogh, this is too spooky!\p"
	.string "Let me teach it to a POKMON so I can\n"
	.string "forget about it!$"

Text_DreamEaterDeclined::
# 10 "data/maps/PewterCity/scripts.pory"
	.string "Snore$"

Text_DreamEaterWhichMon::
# 14 "data/maps/PewterCity/scripts.pory"
	.string "Which POKMON wants to learn DREAM\n"
	.string "EATER?$"

Text_DreamEaterTaught::
# 18 "data/maps/PewterCity/scripts.pory"
	.string "ZZZ Ican't eatanymore$"

PewterCity_Text_ClefairyCameFromMoon::
# 22 "data/maps/PewterCity/scripts.pory"
	.string "CLEFAIRY came from the moon. That's\n"
	.string "what the rumor is.\p"
	.string "They appeared after MOON STONES fell\n"
	.string "on MT. MOON.$"

PewterCity_Text_BrockOnlySeriousTrainerHere::
# 26 "data/maps/PewterCity/scripts.pory"
	.string "There aren't many serious POKMON\n"
	.string "TRAINERS here.\p"
	.string "They're all like BUG CATCHERS, you know,\n"
	.string "just hobbyists.\p"
	.string "But PEWTER GYM's BROCK isn't like that,\n"
	.string "not one bit.$"

PewterCity_Text_DidYouCheckOutMuseum::
# 30 "data/maps/PewterCity/scripts.pory"
	.string "Did you check out the MUSEUM?$"

PewterCity_Text_WerentThoseFossilsAmazing::
# 34 "data/maps/PewterCity/scripts.pory"
	.string "Weren't those fossils from MT. MOON\n"
	.string "amazing?$"

PewterCity_Text_ReallyYouHaveToGo::
# 38 "data/maps/PewterCity/scripts.pory"
	.string "Really? You absolutely have to go!$"

PewterCity_Text_ThisIsTheMuseum::
# 42 "data/maps/PewterCity/scripts.pory"
	.string "This is it, the MUSEUM.\p"
	.string "You have to pay to get in, but it's worth\n"
	.string "it. See you around!$"

PewterCity_Text_DoYouKnowWhatImDoing::
# 46 "data/maps/PewterCity/scripts.pory"
	.string "Psssst! Do you know what I'm doing?$"

PewterCity_Text_ThatsRightItsHardWork::
# 50 "data/maps/PewterCity/scripts.pory"
	.string "That's right! It's hard work!$"

PewterCity_Text_SprayingRepelToKeepWildMonsOut::
# 54 "data/maps/PewterCity/scripts.pory"
	.string "I'm spraying REPEL to keep wild POKMON\n"
	.string "out of my garden!$"

PewterCity_Text_BrocksLookingForChallengersFollowMe::
# 58 "data/maps/PewterCity/scripts.pory"
	.string "You're a TRAINER, right?\p"
	.string "BROCK's looking for new challengers.\n"
	.string "Follow me!$"

PewterCity_Text_GoTakeOnBrock::
# 62 "data/maps/PewterCity/scripts.pory"
	.string "If you have the right stuff, go take on\n"
	.string "BROCK!$"

PewterCity_Text_TrainerTipsEarningEXP::
# 66 "data/maps/PewterCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "All POKMON that appear in battle,\n"
	.string "however briefly, earn EXP Points.$"

PewterCity_Text_CallPoliceIfInfoOnThieves::
# 70 "data/maps/PewterCity/scripts.pory"
	.string "NOTICE!\p"
	.string "Thieves have been stealing POKMON\n"
	.string "fossils from MT. MOON.\p"
	.string "Please call the PEWTER POLICE if you\n"
	.string "have any information.$"

PewterCity_Text_MuseumOfScience::
# 74 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER MUSEUM OF SCIENCE$"

PewterCity_Text_GymSign::
# 78 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER CITY POKMON GYM LEADER: BROCK\l"
	.string "The Rock-Solid POKMON TRAINER!$"

PewterCity_Text_CitySign::
# 82 "data/maps/PewterCity/scripts.pory"
	.string "PEWTER CITY A Stone Gray City$"

PewterCity_Text_DefeatedBrockYouCanHaveTreasure::
# 86 "data/maps/PewterCity/scripts.pory"
	.string "\l"
	.string "\p"
	.string "$"

PewterCity_Text_BerriesInsideUseCarefully::
# 90 "data/maps/PewterCity/scripts.pory"
	.string "\p"
	.string "\l"
	.string "$"

PewterCity_Text_MonsWillUseHeldBerriesOnTheirOwn::
# 94 "data/maps/PewterCity/scripts.pory"
	.string "\l"
	.string "\l"
	.string "\p"
	.string "$"

PewterCity_Text_OhPlayer::
# 98 "data/maps/PewterCity/scripts.pory"
	.string "Oh, {PLAYER}{KUN}!$"

PewterCity_Text_AskedToDeliverThis::
# 102 "data/maps/PewterCity/scripts.pory"
	.string "I'm glad I caught up to you. I'm PROF.\n"
	.string "OAK's AIDE.\p"
	.string "I've been asked to deliver this, so here\n"
	.string "you go.$"

PewterCity_Text_ReceivedRunningShoesFromAide::
# 106 "data/maps/PewterCity/scripts.pory"
	.string "{PLAYER} received the RUNNING SHOES\n"
	.string "from the AIDE.$"

PewterCity_Text_SwitchedShoesWithRunningShoes::
# 110 "data/maps/PewterCity/scripts.pory"
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"

PewterCity_Text_ExplainRunningShoes::
# 114 "data/maps/PewterCity/scripts.pory"
	.string "Press the B Button to run. But only\n"
	.string "where there's room to run!$"

PewterCity_Text_MustBeGoingBackToLab::
# 118 "data/maps/PewterCity/scripts.pory"
	.string "Well, I must be going back to the LAB.\p"
	.string "Bye-bye!$"

PewterCity_Text_RunningShoesLetterFromMom::
# 122 "data/maps/PewterCity/scripts.pory"
	.string "There's a letter attached\p"
	.string "Dear {PLAYER},\p"
	.string "Here is a pair of RUNNING SHOES for my\n"
	.string "beloved challenger.\p"
	.string "Remember, I'll always cheer for you!\n"
	.string "Don't ever give up!\p"
	.string "From Mom$"
