RustboroCity_Flat2_3F_MapScripts::
	.byte 0


RustboroCity_Flat2_3F_EventScript_DevonEmployee::
# 5 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_EventScript_Woman::
# 10 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	msgbox RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones, MSGBOX_NPC
	end


RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones::
# 14 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "DEVON's PRESIDENT likes to collect\n"
	.string "rare stones.$"

RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones::
# 18 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I think the PRESIDENT's son also\n"
	.string "collects rare stones.$"
