RustboroCity_Flat2_3F_MapScripts::
	.byte 0


RustboroCity_Flat2_3F_Text_PresidentCollectsRareStones::
# 5 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "DEVON's PRESIDENT likes to collect rare\n"
	.string "stones.$"

RustboroCity_Flat2_3F_Text_PresidentsSonAlsoCollectsRareStones::
# 9 "data/maps/RustboroCity_Flat2_3F/scripts.pory"
	.string "I think the PRESIDENT's son also\n"
	.string "collects rare stones.$"
