PokemonTower_3F_MapScripts::
	.byte 0


PokemonTower_3F_Text_HopeIntro::
# 5 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Urrg… Awaa… Huhu… Graa…$"

PokemonTower_3F_Text_HopeDefeat::
# 9 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Hwa! I'm saved!$"

PokemonTower_3F_Text_HopePostBattle::
# 13 "data/maps/PokemonTower_3F/scripts.pory"
	.string "The ghosts can be identified by the\n"
	.string "SILPH SCOPE.$"

PokemonTower_3F_Text_CarlyIntro::
# 17 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Kekeke… Kwaaah!$"

PokemonTower_3F_Text_CarlyDefeat::
# 21 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Hmm? What am I doing?$"

PokemonTower_3F_Text_CarlyPostBattle::
# 25 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Sorry! I was possessed!$"

PokemonTower_3F_Text_PatriciaIntro::
# 29 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Be gone! Malevolent spirit!$"

PokemonTower_3F_Text_PatriciaDefeat::
# 33 "data/maps/PokemonTower_3F/scripts.pory"
	.string "Whew! The spirit left!$"

PokemonTower_3F_Text_PatriciaPostBattle::
# 37 "data/maps/PokemonTower_3F/scripts.pory"
	.string "The others above… They must have been\n"
	.string "possessed.$"
