OldaleTown_MapScripts::
# 2 "data/maps/OldaleTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OldaleTown_OnTransition
	.byte 0


OldaleTown_MapScripts::
# 6 "data/maps/OldaleTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, OldaleTown_OnTransition
	return


OldaleTown_Text_SavingMyProgress::
# 10 "data/maps/OldaleTown/scripts.pory"
	.string "I want to take a rest, so I'm saving my\n"
	.string "progress.$"

OldaleTown_Text_IWorkAtPokemonMart::
# 14 "data/maps/OldaleTown/scripts.pory"
	.string "Hi! I work at a POKéMON MART.\p"
	.string "Can I get you to come with me?$"

OldaleTown_Text_ThisIsAPokemonMart::
# 18 "data/maps/OldaleTown/scripts.pory"
	.string "This is a POKéMON MART. Just look for\n"
	.string "our blue roof.\p"
	.string "We sell a variety of goods including\n"
	.string "POKé BALLS for catching POKéMON.\p"
	.string "Here, I'd like you to have this as a\n"
	.string "promotional item.$"

OldaleTown_Text_PotionExplanation::
# 22 "data/maps/OldaleTown/scripts.pory"
	.string "A POTION can be used anytime, so it's\n"
	.string "even more useful than a POKéMON CENTER\l"
	.string "in certain situations.$"

OldaleTown_Text_WaitDontComeInHere::
# 26 "data/maps/OldaleTown/scripts.pory"
	.string "Aaaaah! Wait! Please don't come in here.\p"
	.string "I just discovered the footprints of a\n"
	.string "rare POKéMON!\p"
	.string "Wait until I finish sketching them,\n"
	.string "okay?$"

OldaleTown_Text_DiscoveredFootprints::
# 30 "data/maps/OldaleTown/scripts.pory"
	.string "I just discovered the footprints of a\n"
	.string "rare POKéMON!\p"
	.string "Wait until I finish sketching them,\n"
	.string "okay?$"

OldaleTown_Text_FinishedSketchingFootprints::
# 34 "data/maps/OldaleTown/scripts.pory"
	.string "I finished sketching the footprints of\n"
	.string "a rare POKéMON.\p"
	.string "But it turns out they were only my own\n"
	.string "footprints…$"

OldaleTown_Text_MayLetsGoBack::
# 38 "data/maps/OldaleTown/scripts.pory"
	.string "MAY: {PLAYER}{KUN}! Over here!\l"
	.string "Let's hurry home!$"

OldaleTown_Text_BrendanLetsGoBack::
# 42 "data/maps/OldaleTown/scripts.pory"
	.string "BRENDAN: I'm heading back to my dad's\n"
	.string "LAB now.\l"
	.string "{PLAYER}, you should hustle back, too.$"

OldaleTown_Text_TownSign::
# 46 "data/maps/OldaleTown/scripts.pory"
	.string "OLDALE TOWN “Where things start off\n"
	.string "scarce.”$"
