OldaleTown_MapScripts::
	.byte 0


OldaleTown_EventScript_BlockedPath::
# 5 "data/maps/OldaleTown/scripts.pory"
	msgbox OldaleTown_Text_WaitDontComeInHere, MSGBOX_DEFAULT
	end


OldaleTown_EventScript_FootprintsMan::
	end


OldaleTown_EventScript_Girl::
# 14 "data/maps/OldaleTown/scripts.pory"
	msgbox OldaleTown_Text_SavingMyProgress, MSGBOX_NPC
	end


OldaleTown_EventScript_MartEmployee::
	end


OldaleTown_EventScript_Rival::
	end


OldaleTown_EventScript_RivalTrigger1::
	end


OldaleTown_EventScript_RivalTrigger2::
	end


OldaleTown_EventScript_RivalTrigger3::
	end


OldaleTown_EventScript_TownSign::
# 39 "data/maps/OldaleTown/scripts.pory"
	msgbox OldaleTown_Text_TownSign, MSGBOX_SIGN
	end


OldaleTown_Text_TownSign::
# 44 "data/maps/OldaleTown/scripts.pory"
	.string "OLDALE TOWN “Where things start off\n"
	.string "scarce.”$"

OldaleTown_Text_MayLetsGoBack::
# 48 "data/maps/OldaleTown/scripts.pory"
	.string "MAY: {PLAYER}{KUN}!\n"
	.string "Over here!\l"
	.string "Let's hurry home!$"

OldaleTown_Text_SavingMyProgress::
# 52 "data/maps/OldaleTown/scripts.pory"
	.string "I want to take a rest, so I'm saving my\n"
	.string "progress.$"

OldaleTown_Text_PotionExplanation::
# 56 "data/maps/OldaleTown/scripts.pory"
	.string "A POTION can be used anytime, so it's\n"
	.string "even more useful than a POKéMON CENTER\l"
	.string "in certain situations.$"

OldaleTown_Text_ThisIsAPokemonMart::
# 60 "data/maps/OldaleTown/scripts.pory"
	.string "This is a POKéMON MART.\n"
	.string "Just look for our blue roof.\p"
	.string "We sell a variety of goods including\n"
	.string "POKé BALLS for catching POKéMON.\p"
	.string "Here, I'd like you to have this as\n"
	.string "a promotional item.$"

OldaleTown_Text_FinishedSketchingFootprints::
# 64 "data/maps/OldaleTown/scripts.pory"
	.string "I finished sketching the footprints of\n"
	.string "a rare POKéMON.\p"
	.string "But it turns out they were only my\n"
	.string "own footprints…$"

OldaleTown_Text_WaitDontComeInHere::
# 68 "data/maps/OldaleTown/scripts.pory"
	.string "Aaaaah! Wait!\n"
	.string "Please don't come in here.\p"
	.string "I just discovered the footprints of\n"
	.string "a rare POKéMON!\p"
	.string "Wait until I finish sketching\n"
	.string "them, okay?$"

OldaleTown_Text_BrendanLetsGoBack::
# 72 "data/maps/OldaleTown/scripts.pory"
	.string "BRENDAN: I'm heading back to my dad's\n"
	.string "LAB now.\l"
	.string "{PLAYER}, you should hustle back, too.$"
