MagmaHideout_1F_MapScripts::
# 2 "data/maps/MagmaHideout_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MagmaHideout_1F_OnTransition
	.byte 0


MagmaHideout_1F_Text_Grunt1Intro::
# 6 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "When TEAM MAGMA has roll call, we get\n"
	.string "important guarding assignments in\l"
	.string "the order that we line up.\p"
	.string "That's why I'm stuck off in this corner.\n"
	.string "I'm always late to roll call!$"

MagmaHideout_1F_Text_Grunt1Defeat::
# 10 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "I'm always late for training sessions,\n"
	.string "too!\p"
	.string "I hate to say it, but I'm wimpy…$"

MagmaHideout_1F_Text_Grunt1PostBattle::
# 14 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "Okay, I'll try to put a little more\n"
	.string "effort into things from now on…$"

MagmaHideout_1F_Text_Grunt2Intro::
# 18 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "Our leader told us to dig into MT.\n"
	.string "CHIMNEY, so we dug and dug.\p"
	.string "And in the course of digging, we came\n"
	.string "across something that blew our minds!\p"
	.string "What did we find?\p"
	.string "Fuhahaha! I'll tell you if you beat me!$"

MagmaHideout_1F_Text_Grunt2Defeat::
# 22 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "Arrgh! Taken down!$"

MagmaHideout_1F_Text_Grunt2PostBattle::
# 26 "data/maps/MagmaHideout_1F/scripts.pory"
	.string "I won't tell you after all. You'll find\n"
	.string "out when you get there!\p"
	.string "It'd be better if you saved surprises\n"
	.string "to the end, don't you think?$"
