Route15_WestEntrance_2F_MapScripts::
	.byte 0


Route15_WestEntrance_2F_Text_GiveItemIfCaughtEnough::
# 5 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "Hi! Remember me? I'm one of PROF. OAK's\n"
	.string "AIDES.\p"
	.string "If your POKDEX has complete data on\n"
	.string "{STR_VAR_1} species, I'm supposed\l"
	.string "to\l"
	.string "give you a reward.\p"
	.string "PROF. OAK entrusted me with the\n"
	.string "{STR_VAR_2} for you.\p"
	.string "So, {PLAYER}, let me ask you.\p"
	.string "Have you gathered data on at least\n"
	.string "{STR_VAR_1} kinds of POKMON?$"

Route15_WestEntrance_2F_Text_GreatHereYouGo::
# 9 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "Great! You have caught or owned\n"
	.string "{STR_VAR_3} kinds of POKMON!\p"
	.string "Congratulations! Here you go!$"

Route15_WestEntrance_2F_Text_ReceivedItemFromAide::
# 13 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "{PLAYER} received the {STR_VAR_2}\n"
	.string "from the AIDE.$"

Route15_WestEntrance_2F_Text_ExplainExpShare::
# 17 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "EXP. SHARE is an item to be held by a\n"
	.string "POKMON.\p"
	.string "The POKMON will receive a share of the\n"
	.string "EXP. Points without having\l"
	.string "to battle.$"

Route15_WestEntrance_2F_Text_LargeShiningBird::
# 21 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "A large, shining bird is flying toward\n"
	.string "the sea.$"

Route15_WestEntrance_2F_Text_SmallIslandOnHorizon::
# 25 "data/maps/Route15_WestEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "It looks like a small island on the\n"
	.string "horizon!$"
