BattleFrontier_ScottsHouse_MapScripts::
	.byte 0


BattleFrontier_ScottsHouse_Text_WelcomeToBattleFrontier::
# 5 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Well, hello and welcome! Heheh…\n"
	.string "Sorry about the cramped space.\p"
	.string "Anyway, {PLAYER}{KUN}, let me formally\n"
	.string "welcome you to the BATTLE FRONTIER.\p"
	.string "This is my dream come true. It took me\n"
	.string "years and years, but I've\l"
	.string "finally given shape to my dream.$"

BattleFrontier_ScottsHouse_Text_HowMuchEffortItTookToMakeReal::
# 9 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "On reflection, it was a terribly long\n"
	.string "journey…\p"
	.string "I left home alone on a quest to find\n"
	.string "strong TRAINERS.\p"
	.string "No one can imagine how much effort or\n"
	.string "time it took to make this real.$"

BattleFrontier_ScottsHouse_Text_HaveThisAsMementoOfOurPathsCrossing::
# 13 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "But that's all in the past. No point\n"
	.string "dwelling on that!\p"
	.string "All I want for you is to enjoy battling\n"
	.string "to your heart's content here.\p"
	.string "{PLAYER}{KUN}, I want you to have this as a\n"
	.string "memento for all the time our\l"
	.string "paths crossed on our journeys.$"

BattleFrontier_ScottsHouse_Text_ObtainedXBattlePoints::
# 17 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "{PLAYER} obtained {STR_VAR_1}\n"
	.string "Battle Point(s).$"

BattleFrontier_ScottsHouse_Text_ExplainBattlePoints::
# 21 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: You can check your Battle\n"
	.string "Points on your FRONTIER PASS.\p"
	.string "The more success you have here at the\n"
	.string "BATTLE FRONTIER, the more Battle\l"
	.string "Points you will collect.\p"
	.string "Use your Battle Points the way you see\n"
	.string "fit, like trading them for items.$"

BattleFrontier_ScottsHouse_Text_ExpectingGreatThings::
# 25 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "I'm expecting great things from you!$"

BattleFrontier_ScottsHouse_Text_WhyIGoSeekingTrainers::
# 29 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Every TRAINER is an individual.\n"
	.string "They all lead lives of their own.\p"
	.string "But when they're in a battle, it doesn't\n"
	.string "matter who they are.\p"
	.string "They're all the same!\p"
	.string "I love the purity of battle, where\n"
	.string "everyone is equal.\p"
	.string "That's why I go everywhere seeking\n"
	.string "TRAINERS who are serious about\l"
	.string "battling, and invite them here.$"

BattleFrontier_ScottsHouse_Text_HaveYouMetFrontierBrain::
# 33 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Have you met any of the\n"
	.string "FRONTIER BRAINS?\p"
	.string "Better yet, have you obtained any\n"
	.string "symbols from them?\p"
	.string "I handpicked the FRONTIER BRAINS as\n"
	.string "the toughest TRAINERS anywhere.\p"
	.string "But I'm sure that seeing how tough you\n"
	.string "are will startle even them!$"

BattleFrontier_ScottsHouse_Text_MayFindWildMonsInFrontier::
# 37 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: You don't just train for battle,\n"
	.string "right?\p"
	.string "I think I remember you working on a\n"
	.string "POKéDEX as well.\p"
	.string "Well, guess what?\p"
	.string "You may run into wild POKéMON in the\n"
	.string "BATTLE FRONTIER somewhere…\l"
	.string "Fufufu!$"

BattleFrontier_ScottsHouse_Text_YouveCollectedAllSilverSymbols::
# 41 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Are you enjoying things in the\n"
	.string "BATTLE FRONTIER?\p"
	.string "…Wait a second… Oh!\p"
	.string "Your FRONTIER PASS! You've collected\n"
	.string "the full set\l"
	.string "of silver symbols!\p"
	.string "That's more than impressive! You are\n"
	.string "tough, just as I suspected!\p"
	.string "Normally, I wouldn't do something like\n"
	.string "this, but this is a special time!\p"
	.string "I want you to have this. I'm sure you\n"
	.string "can put it to proper use.$"

BattleFrontier_ScottsHouse_Text_YouveCollectedAllGoldSymbols::
# 45 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: I hope you're enjoying\n"
	.string "everything in the BATTLE FRONTIER.\p"
	.string "…Wait a second… Oh, my disbelieving\n"
	.string "eyes!\p"
	.string "Your FRONTIER PASS! You've gathered up\n"
	.string "the full set\l"
	.string "of gold symbols!\p"
	.string "That's more than stupendous! You're\n"
	.string "incredible, just as I suspected!\p"
	.string "… … … … … …\p"
	.string "{PLAYER}, you've got to accept this!\p"
	.string "I think you will be able to appreciate\n"
	.string "the value of my gift!$"

BattleFrontier_ScottsHouse_Text_SoGladIBroughtYouHere::
# 49 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "I must say I have the gift of knowing a\n"
	.string "good TRAINER when I see one.\p"
	.string "I'm so glad I had the foresight to bring\n"
	.string "you here!$"

BattleFrontier_ScottsHouse_Text_BerryPocketStuffed::
# 53 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "Your BERRY POCKET seems to be stuffed.$"

BattleFrontier_ScottsHouse_Text_Beat50TrainersInARow::
# 57 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Oh, I heard about you! How you\n"
	.string "ruled the BATTLE TOWER!\l"
	.string "You beat over 50 TRAINERS in a row?\p"
	.string "That's fantastic! I want you to have\n"
	.string "this!$"

BattleFrontier_ScottsHouse_Text_Beat100TrainersInARow::
# 61 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "SCOTT: Oh, my! I heard about you! How\n"
	.string "you overwhelmed the BATTLE TOWER!\l"
	.string "You beat over 100 TRAINERS in a row?\p"
	.string "That's ridiculously spectacular! You've\n"
	.string "got to have this!$"

BattleFrontier_ScottsHouse_Text_ExpectingToHearEvenGreaterThings::
# 65 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "I'll be expecting to hear even greater\n"
	.string "things about you now!$"

BattleFrontier_ScottsHouse_Text_ComeBackForThisLater::
# 69 "data/maps/BattleFrontier_ScottsHouse/scripts.pory"
	.string "Oops, well, if you have too much stuff,\n"
	.string "come back for this later.$"
