ValleyWindworks_MapScripts::
	.byte 0


ValleyWindworks_EventScript_Sign1::
# 6 "data/maps/ValleyWindworks/scripts.pory"
	msgbox ValleyWindworks_Text_Sign1, MSGBOX_SIGN
	end


ValleyWindworks_EventScript_SmithNPC1::
# 15 "data/maps/ValleyWindworks/scripts.pory"
	msgbox ValleyWindworks_Text_SmithNPC1, MSGBOX_NPC
	end


ValleyWindworks_EventScript_SmithNPC2::
# 24 "data/maps/ValleyWindworks/scripts.pory"
	msgbox ValleyWindworks_Text_SmithNPC2, MSGBOX_NPC
	end


ValleyWindworks_EventScript_SmithNPC3::
# 33 "data/maps/ValleyWindworks/scripts.pory"
	msgbox ValleyWindworks_Text_SmithNPC3, MSGBOX_NPC
	end


ValleyWindworks_Text_Sign1::
# 10 "data/maps/ValleyWindworks/scripts.pory"
	.string "ValleyWindworks Sign 1$"

ValleyWindworks_Text_SmithNPC1::
# 19 "data/maps/ValleyWindworks/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

ValleyWindworks_Text_SmithNPC2::
# 28 "data/maps/ValleyWindworks/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

ValleyWindworks_Text_SmithNPC3::
# 37 "data/maps/ValleyWindworks/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
