RustboroCity_MapScripts::
	.byte 0


RustboroCity_EventScript_Boy1::
# 5 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_YouCanHave2On2Battle, MSGBOX_NPC
	end


RustboroCity_EventScript_Boy2::
	end


RustboroCity_EventScript_CitySign::
# 14 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_CitySign, MSGBOX_SIGN
	end


RustboroCity_EventScript_CuttersHouseSign::
# 19 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_CuttersHouse, MSGBOX_SIGN
	end


RustboroCity_EventScript_DevonCorpSign::
# 24 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_DevonCorpSign, MSGBOX_SIGN
	end


RustboroCity_EventScript_DevonEmployee1::
# 29 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_ShadyCharacterTookOffTowardsTunnel, MSGBOX_DEFAULT
	end


RustboroCity_EventScript_DevonEmployee2::
# 34 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_YoureNewAroundHere, MSGBOX_DEFAULT
	end


RustboroCity_EventScript_FatMan::
	end


RustboroCity_EventScript_GymSign::
# 43 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_GymSign, MSGBOX_SIGN
	end


RustboroCity_EventScript_HelpGetGoodsTrigger0::
	end


RustboroCity_EventScript_HelpGetGoodsTrigger1::
	end


RustboroCity_EventScript_HelpGetGoodsTrigger2::
	end


RustboroCity_EventScript_HelpGetGoodsTrigger3::
	end


RustboroCity_EventScript_LittleBoy::
# 64 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_PokemonCanChangeLookFromExp, MSGBOX_DEFAULT
	end


RustboroCity_EventScript_LittleGirl::
# 69 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_PokemonChangeShape, MSGBOX_DEFAULT
	end


RustboroCity_EventScript_Man1::
	end


RustboroCity_EventScript_Man2::
# 78 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_TradePokemonGrowFast, MSGBOX_DEFAULT
	end


RustboroCity_EventScript_NinjaBoy::
# 83 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_CatchRarePokemonIfIGoToSchool, MSGBOX_SIGN
	end


RustboroCity_EventScript_Rival::
	end


RustboroCity_EventScript_RivalTrigger0::
	end


RustboroCity_EventScript_RivalTrigger1::
	end


RustboroCity_EventScript_RivalTrigger2::
	end


RustboroCity_EventScript_RivalTrigger3::
	end


RustboroCity_EventScript_RivalTrigger4::
	end


RustboroCity_EventScript_RivalTrigger5::
	end


RustboroCity_EventScript_RivalTrigger6::
	end


RustboroCity_EventScript_RivalTrigger7::
	end


RustboroCity_EventScript_StolenGoodsTrigger0::
	end


RustboroCity_EventScript_StolenGoodsTrigger1::
	end


RustboroCity_EventScript_StolenGoodsTrigger2::
	end


RustboroCity_EventScript_StolenGoodsTrigger3::
	end


RustboroCity_EventScript_StolenGoodsTrigger4::
	end


RustboroCity_EventScript_TrainersSchoolSign::
# 144 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_TrainersSchoolSign, MSGBOX_SIGN
	end


RustboroCity_EventScript_TunnelSign::
# 149 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_TunnelNearingCompletion, MSGBOX_SIGN
	end


RustboroCity_EventScript_Twin::
# 154 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_WowYouHavePokemon, MSGBOX_NPC
	end


RustboroCity_EventScript_Woman::
# 159 "data/maps/RustboroCity/scripts.pory"
	msgbox RustboroCity_Text_GymLeaderIsntEasyWithFire, MSGBOX_NPC
	end


RustboroCity_Text_CuttersHouse::
# 164 "data/maps/RustboroCity/scripts.pory"
	.string "CUTTER'S HOUSE$"

RustboroCity_Text_CitySign::
# 168 "data/maps/RustboroCity/scripts.pory"
	.string "RUSTBORO CITY\p"
	.string "“The city probing the integration of\n"
	.string "nature and science.”$"

RustboroCity_Text_GymSign::
# 172 "data/maps/RustboroCity/scripts.pory"
	.string "RUSTBORO CITY POKéMON GYM LEADER:\n"
	.string "ROXANNE\p"
	.string "“The ROCK-loving honors student!”$"

RustboroCity_Text_TrainersSchoolSign::
# 176 "data/maps/RustboroCity/scripts.pory"
	.string "POKéMON TRAINER'S SCHOOL\p"
	.string "“We'll teach you anything about\n"
	.string "POKéMON!”$"

RustboroCity_Text_DevonCorpSign::
# 180 "data/maps/RustboroCity/scripts.pory"
	.string "DEVON CORPORATION\p"
	.string "“For all your living needs, we make it\n"
	.string "all.”$"

RustboroCity_Text_TunnelNearingCompletion::
# 184 "data/maps/RustboroCity/scripts.pory"
	.string "“Timesaving tunnel nearing\n"
	.string "completion!”\p"
	.string "…Is what it says on the sign, but\n"
	.string "there's also a big “X” splashed\l"
	.string "across it in red paint…$"

RustboroCity_Text_BrendanWantToBattle::
# 188 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: What's up?\n"
	.string "Want to have a battle with me?$"

RustboroCity_Text_MrBrineyLovesPeeko::
# 192 "data/maps/RustboroCity/scripts.pory"
	.string "The old sailor MR. BRINEY lives in\n"
	.string "a cottage by the sea.\p"
	.string "He said he was going shopping in\n"
	.string "SLATEPORT for his pet, PEEKO.\p"
	.string "That old sea dog, he must really love\n"
	.string "that PEEKO.$"

RustboroCity_Text_PokemonCanChangeLookFromExp::
# 196 "data/maps/RustboroCity/scripts.pory"
	.string "If a POKéMON gains experience in\n"
	.string "battles, it can sometimes change in\l"
	.string "the way it looks.$"

RustboroCity_Text_PokemonChangeShape::
# 200 "data/maps/RustboroCity/scripts.pory"
	.string "A POKéMON changes shape?\n"
	.string "If one did that, I would be shocked!$"

RustboroCity_Text_SneakyLookingManWentAroundCorner::
# 204 "data/maps/RustboroCity/scripts.pory"
	.string "Hm? A sneaky-looking man?\p"
	.string "Come to think of it, yes, a shady-\n"
	.string "looking guy went around the corner.$"

RustboroCity_Text_BrendanIWontGoEasy::
# 208 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: I know you just became\n"
	.string "a TRAINER, but I won't go easy!$"

RustboroCity_Text_BrendanMrBrineyHint::
# 212 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: By the way, you know\n"
	.string "MR. BRINEY? The guy I just passed?\p"
	.string "I bet you didn't know this, since you\n"
	.string "just moved here, {PLAYER}, but\l"
	.string "MR. BRINEY was once a great sailor.$"

RustboroCity_Text_PleaseSelectPokenav::
# 216 "data/maps/RustboroCity/scripts.pory"
	.string "Please select the POKéNAV.$"

RustboroCity_Text_YoureNewAroundHere::
# 220 "data/maps/RustboroCity/scripts.pory"
	.string "Oh? Who might you be?\n"
	.string "You're a new face around these parts.\p"
	.string "Have you just transferred into the\n"
	.string "POKéMON TRAINER'S SCHOOL?$"

RustboroCity_Text_YoureLoadedWithItems::
# 224 "data/maps/RustboroCity/scripts.pory"
	.string "You're loaded with items.\n"
	.string "I can't give you this GREAT BALL.$"

RustboroCity_Text_HeyThatsRustborosGymBadge::
# 228 "data/maps/RustboroCity/scripts.pory"
	.string "Hey, that's RUSTBORO's GYM BADGE!\p"
	.string "Out of all the POKéMON GYM BADGES,\n"
	.string "RUSTBORO's is the coolest, I'd say.$"

RustboroCity_Text_YouCanHave2On2Battle::
# 232 "data/maps/RustboroCity/scripts.pory"
	.string "Did you know this?\p"
	.string "You can have a 2-on-2 battle even\n"
	.string "if you're not with another TRAINER.\p"
	.string "If you catch the eyes of two TRAINERS\n"
	.string "when you have two or more POKéMON,\l"
	.string "they'll both challenge you.\p"
	.string "Don't you think it'd be cool if you\n"
	.string "could beat two TRAINERS by yourself?$"

RustboroCity_Text_GymLeaderIsntEasyWithFire::
# 236 "data/maps/RustboroCity/scripts.pory"
	.string "I challenged the GYM LEADER, but…\p"
	.string "It's not going to be easy winning with\n"
	.string "my FIRE-type POKéMON…\p"
	.string "FIRE-type POKéMON don't match up\n"
	.string "well against ROCK-type POKéMON…$"

RustboroCity_Text_WowYouHavePokemon::
# 240 "data/maps/RustboroCity/scripts.pory"
	.string "Wow, you have POKéMON with you, too.\p"
	.string "When I get bigger, I'm going to go\n"
	.string "places with POKéMON, too.$"

RustboroCity_Text_OutOfTheWay::
# 244 "data/maps/RustboroCity/scripts.pory"
	.string "Get out!\n"
	.string "Out of the way!$"

RustboroCity_Text_MayImNotGoingToLose::
# 248 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: You just became a TRAINER,\n"
	.string "{PLAYER}{KUN}. I'm not going to lose!$"

RustboroCity_Text_CatchRarePokemonIfIGoToSchool::
# 252 "data/maps/RustboroCity/scripts.pory"
	.string "POKéMON TRAINER'S SCHOOL!\p"
	.string "If I go to this school, will I be able\n"
	.string "to catch rare POKéMON easily?$"

RustboroCity_Text_ShadyCharacterTookOffTowardsTunnel::
# 256 "data/maps/RustboroCity/scripts.pory"
	.string "That shady character, I think he took\n"
	.string "off towards the tunnel over there.$"

RustboroCity_Text_TradePokemonGrowFast::
# 260 "data/maps/RustboroCity/scripts.pory"
	.string "A POKéMON you get in a trade from\n"
	.string "someone grows fast.\p"
	.string "But if you don't have certain GYM\n"
	.string "BADGES, it may not obey you…$"

RustboroCity_Text_MayMrBrineyHint::
# 264 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: Oh, by the way, MR. BRINEY, who\n"
	.string "I just passed…\p"
	.string "{PLAYER}{KUN}, you just moved here so you\n"
	.string "might not know this, but MR. BRINEY\l"
	.string "was once a revered seafarer.$"

RustboroCity_Text_YouGotItThankYou::
# 268 "data/maps/RustboroCity/scripts.pory"
	.string "Oh! How did it go?\n"
	.string "The DEVON GOODS?\p"
	.string "You did!\n"
	.string "You got them back!\p"
	.string "You really are a great TRAINER!\p"
	.string "I know! As my thanks, I'll give you\n"
	.string "another GREAT BALL!$"

RustboroCity_Text_MayWantToBattle::
# 272 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: So, what do you think?\n"
	.string "How about a little battle here?$"

RustboroCity_Text_DevonCorpBranchOfficeSign::
# 276 "data/maps/RustboroCity/scripts.pory"
	.string "DEVON CORP. BRANCH OFFICE\p"
	.string "“Access limited to DEVON employees\n"
	.string "and authorized personnel.”$"
