RustboroCity_MapScripts::
# 2 "data/maps/RustboroCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RustboroCity_OnTransition
# 3 "data/maps/RustboroCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, RustboroCity_OnFrame
	.byte 0


RustboroCity_Text_WeShortenItToDevon::
# 7 "data/maps/RustboroCity/scripts.pory"
	.string "The DEVON CORPORATION… We all just\n"
	.string "shorten it to DEVON.\p"
	.string "That company makes all sorts of\n"
	.string "convenient products.$"

RustboroCity_Text_SneakyLookingManWentAroundCorner::
# 11 "data/maps/RustboroCity/scripts.pory"
	.string "Hm? A sneaky-looking man?\p"
	.string "Come to think of it, yes, a shady-\n"
	.string "looking guy went around the corner.$"

RustboroCity_Text_HaveYouChallengedGym::
# 15 "data/maps/RustboroCity/scripts.pory"
	.string "Have you taken the POKéMON GYM\n"
	.string "challenge?\p"
	.string "When you get that shiny GYM BADGE in\n"
	.string "hand, I guess TRAINERS begin to\l"
	.string "realize what is required of them.$"

RustboroCity_Text_HeyThatsRustborosGymBadge::
# 19 "data/maps/RustboroCity/scripts.pory"
	.string "Hey, that's RUSTBORO's GYM BADGE!\p"
	.string "Out of all the POKéMON GYM BADGES,\n"
	.string "RUSTBORO's is the coolest, I'd say.$"

RustboroCity_Text_YoureNewAroundHere::
# 23 "data/maps/RustboroCity/scripts.pory"
	.string "Oh? Who might you be? You're a new face\n"
	.string "around these parts.\p"
	.string "Have you just transferred into the\n"
	.string "POKéMON TRAINER'S SCHOOL?$"

RustboroCity_Text_GymLeaderIsntEasyWithFire::
# 27 "data/maps/RustboroCity/scripts.pory"
	.string "I challenged the GYM LEADER, but…\p"
	.string "It's not going to be easy winning with\n"
	.string "my FIRE-type POKéMON…\p"
	.string "FIRE-type POKéMON don't match up well\n"
	.string "against ROCK-type POKéMON…$"

RustboroCity_Text_MrBrineyWalksInTheTunnel::
# 31 "data/maps/RustboroCity/scripts.pory"
	.string "The old sailor MR. BRINEY lives in a\n"
	.string "cottage by the sea.\p"
	.string "He goes for walks in the tunnel every so\n"
	.string "often.$"

RustboroCity_Text_MrBrineyLovesPeeko::
# 35 "data/maps/RustboroCity/scripts.pory"
	.string "The old sailor MR. BRINEY lives in a\n"
	.string "cottage by the sea.\p"
	.string "He said he was going shopping in\n"
	.string "SLATEPORT for his pet, PEEKO.\p"
	.string "That old sea dog, he must really love\n"
	.string "that PEEKO.$"

RustboroCity_Text_WowYouHavePokemon::
# 39 "data/maps/RustboroCity/scripts.pory"
	.string "Wow, you have POKéMON with you, too.\p"
	.string "When I get bigger, I'm going to go\n"
	.string "places with POKéMON, too.$"

RustboroCity_Text_CatchRarePokemonIfIGoToSchool::
# 43 "data/maps/RustboroCity/scripts.pory"
	.string "POKéMON TRAINER'S SCHOOL!\p"
	.string "If I go to this school, will I be able to\n"
	.string "catch rare POKéMON easily?$"

RustboroCity_Text_PokemonCanChangeLookFromExp::
# 47 "data/maps/RustboroCity/scripts.pory"
	.string "If a POKéMON gains experience in\n"
	.string "battles, it can sometimes change in\l"
	.string "the way it looks.$"

RustboroCity_Text_PokemonChangeShape::
# 51 "data/maps/RustboroCity/scripts.pory"
	.string "A POKéMON changes shape? If one did\n"
	.string "that, I would be shocked!$"

RustboroCity_Text_TradePokemonGrowFast::
# 55 "data/maps/RustboroCity/scripts.pory"
	.string "A POKéMON you get in a trade from\n"
	.string "someone grows fast.\p"
	.string "But if you don't have certain GYM\n"
	.string "BADGES, it may not obey you…$"

RustboroCity_Text_OutOfTheWay::
# 59 "data/maps/RustboroCity/scripts.pory"
	.string "Get out! Out of the way!$"

RustboroCity_Text_WaitDontTakeMyGoods::
# 63 "data/maps/RustboroCity/scripts.pory"
	.string "Wait! Pleeeaaase!\p"
	.string "Don't take my GOODS!$"

RustboroCity_Text_HelpMeIWasRobbed::
# 67 "data/maps/RustboroCity/scripts.pory"
	.string "Oh, it's you!\p"
	.string "You're that fantastic TRAINER who\n"
	.string "helped me in PETALBURG WOODS!\p"
	.string "Help me! I was robbed by TEAM AQUA! I\n"
	.string "have to get the DEVON GOODS back!\p"
	.string "If I don't… I'm going to be in serious\n"
	.string "trouble.$"

RustboroCity_Text_ShadyCharacterTookOffTowardsTunnel::
# 71 "data/maps/RustboroCity/scripts.pory"
	.string "That shady character, I think he took\n"
	.string "off towards the tunnel over there.$"

RustboroCity_Text_YouGotItThankYou::
# 75 "data/maps/RustboroCity/scripts.pory"
	.string "Oh! How did it go? The DEVON GOODS?\p"
	.string "You did! You got them back!\p"
	.string "You really are a great TRAINER!\p"
	.string "I know! As my thanks, I'll give you\n"
	.string "another GREAT BALL!$"

RustboroCity_Text_YoureLoadedWithItems::
# 79 "data/maps/RustboroCity/scripts.pory"
	.string "You're loaded with items. I can't give\n"
	.string "you this GREAT BALL.$"

RustboroCity_Text_PleaseComeWithMe::
# 83 "data/maps/RustboroCity/scripts.pory"
	.string "Excuse me, please! Please come with me!$"

RustboroCity_Text_MayHiLetsRegister::
# 87 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: Oh, hi, {PLAYER}{KUN}!\p"
	.string "You had a MATCH CALL feature put on\n"
	.string "your POKéNAV!\p"
	.string "Let's register each other so we can\n"
	.string "contact one another anytime!\p"
	.string "… … … … … …$"

RustboroCity_Text_RegisteredMay::
# 91 "data/maps/RustboroCity/scripts.pory"
	.string "Registered MAY in the POKéNAV.$"

RustboroCity_Text_MayPassedBrineyWantToBattle::
# 95 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: Oh, by the way, I passed MR. BRINEY\n"
	.string "in PETALBURG WOODS.\p"
	.string "I guess he's on his way home to his\n"
	.string "cottage by the sea.\p"
	.string "How's your POKéDEX coming along,\n"
	.string "{PLAYER}{KUN}? Mine's looking pretty\l"
	.string "decent!\p"
	.string "So… How about a little battle?$"

RustboroCity_Text_MayOhHaventRaisedPokemonEnough::
# 99 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: Oh, what's the matter?\p"
	.string "Haven't you caught or raised your\n"
	.string "POKéMON very much?\p"
	.string "That's not very good for a TRAINER!$"

RustboroCity_Text_MayWantToBattle::
# 103 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: So, what do you think? How about a\n"
	.string "little battle here?$"

RustboroCity_Text_MayImNotGoingToLose::
# 107 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: You just became a TRAINER,\n"
	.string "{PLAYER}{KUN}. I'm not going to lose!$"

RustboroCity_Text_MayDefeat::
# 111 "data/maps/RustboroCity/scripts.pory"
	.string "Yikes! You're better than I expected!$"

RustboroCity_Text_MayMrBrineyHint::
# 115 "data/maps/RustboroCity/scripts.pory"
	.string "MAY: Oh, by the way, MR. BRINEY, who I\n"
	.string "just passed…\p"
	.string "{PLAYER}{KUN}, you just moved here so you\n"
	.string "might not know this, but MR. BRINEY\l"
	.string "was once a revered seafarer.$"

RustboroCity_Text_BrendanHiLetsRegister::
# 119 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: Oh, hey, {PLAYER}!\p"
	.string "You had a MATCH CALL feature put on\n"
	.string "your POKéNAV! Cool!\p"
	.string "Let's register each other so we can get\n"
	.string "in touch anytime!\p"
	.string "… … … … … …$"

RustboroCity_Text_RegisteredBrendan::
# 123 "data/maps/RustboroCity/scripts.pory"
	.string "Registered BRENDAN in the POKéNAV.$"

RustboroCity_Text_BrendanPassedBrineyWantToBattle::
# 127 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: By the way, {PLAYER}, I\n"
	.string "walked by MR. BRINEY in PETALBURG\l"
	.string "WOODS.\p"
	.string "I bet he was on his way home to his\n"
	.string "cottage by the sea.\p"
	.string "{PLAYER}, how's your POKéDEX? Have\n"
	.string "you filled in any pages yet?\p"
	.string "Mine rules.\p"
	.string "Want to have a battle to test how far\n"
	.string "you've progressed?$"

RustboroCity_Text_BrendanNoConfidenceInPokemon::
# 131 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: What's the matter? Don't have\n"
	.string "any confidence in your POKéMON?$"

RustboroCity_Text_BrendanWantToBattle::
# 135 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: What's up? Want to have a\n"
	.string "battle with me?$"

RustboroCity_Text_BrendanIWontGoEasy::
# 139 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: I know you just became a\n"
	.string "TRAINER, but I won't go easy!$"

RustboroCity_Text_BrendanDefeat::
# 143 "data/maps/RustboroCity/scripts.pory"
	.string "Hmm… You're pretty good.$"

RustboroCity_Text_BrendanMrBrineyHint::
# 147 "data/maps/RustboroCity/scripts.pory"
	.string "BRENDAN: By the way, you know MR.\n"
	.string "BRINEY? The guy I just passed?\p"
	.string "I bet you didn't know this, since you\n"
	.string "just moved here, {PLAYER}, but\l"
	.string "MR. BRINEY was once a great sailor.$"

RustboroCity_Text_TunnelNearingCompletion::
# 151 "data/maps/RustboroCity/scripts.pory"
	.string "“Timesaving tunnel nearing\n"
	.string "completion!”\p"
	.string "…Is what it says on the sign, but\n"
	.string "there's also a big “X” splashed\l"
	.string "across it in red paint…$"

RustboroCity_Text_DevonCorpSign::
# 155 "data/maps/RustboroCity/scripts.pory"
	.string "DEVON CORPORATION\p"
	.string "“For all your living needs, we make it\n"
	.string "all.”$"

RustboroCity_Text_GymSign::
# 159 "data/maps/RustboroCity/scripts.pory"
	.string "RUSTBORO CITY POKéMON GYM LEADER:\n"
	.string "ROXANNE\p"
	.string "“The ROCK-loving honors student!”$"

RustboroCity_Text_DevonCorpBranchOfficeSign::
# 163 "data/maps/RustboroCity/scripts.pory"
	.string "DEVON CORP. BRANCH OFFICE\p"
	.string "“Access limited to DEVON employees and\n"
	.string "authorized personnel.”$"

RustboroCity_Text_CitySign::
# 167 "data/maps/RustboroCity/scripts.pory"
	.string "RUSTBORO CITY\p"
	.string "“The city probing the integration of\n"
	.string "nature and science.”$"

RustboroCity_Text_TrainersSchoolSign::
# 171 "data/maps/RustboroCity/scripts.pory"
	.string "POKéMON TRAINER'S SCHOOL\p"
	.string "“We'll teach you anything about\n"
	.string "POKéMON!”$"

RustboroCity_Text_CuttersHouse::
# 175 "data/maps/RustboroCity/scripts.pory"
	.string "CUTTER'S HOUSE$"

RustboroCity_Text_DevelopedNewPokenavFeature::
# 179 "data/maps/RustboroCity/scripts.pory"
	.string "I've been developing an added feature\n"
	.string "for the POKéNAV…\p"
	.string "And it turned out great!\p"
	.string "{PLAYER}, may I see that POKéNAV?\n"
	.string "The one our PRESIDENT gave you?$"

RustboroCity_Text_AddedMatchCallPleaseCallMrStone::
# 183 "data/maps/RustboroCity/scripts.pory"
	.string "There you go, {PLAYER}!\p"
	.string "I added a new feature named MATCH CALL\n"
	.string "to your POKéNAV.\p"
	.string "Using the MATCH CALL feature, you can\n"
	.string "chat with people who have\l"
	.string "been registered in your POKéNAV.\p"
	.string "{PLAYER}, our PRESIDENT STONE should\n"
	.string "be registered in your POKéNAV.\p"
	.string "Test it out. Please give our PRESIDENT\n"
	.string "a call.$"

RustboroCity_Text_PleaseSelectPokenav::
# 187 "data/maps/RustboroCity/scripts.pory"
	.string "Please select the POKéNAV.$"

RustboroCity_Text_IdBetterGetBackToWork::
# 191 "data/maps/RustboroCity/scripts.pory"
	.string "Okay, I'd better get back to work.\n"
	.string "Please take care, {PLAYER}!$"

RustboroCity_Text_YouCanHave2On2Battle::
# 195 "data/maps/RustboroCity/scripts.pory"
	.string "Did you know this?\p"
	.string "You can have a 2-on-2 battle even if\n"
	.string "you're not with another TRAINER.\p"
	.string "If you catch the eyes of two TRAINERS\n"
	.string "when you have two or more POKéMON,\l"
	.string "they'll both challenge you.\p"
	.string "Don't you think it'd be cool if you could\n"
	.string "beat two TRAINERS by yourself?$"
