SilphCo_9F_MapScripts::
# 2 "data/maps/SilphCo_9F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_9F_OnLoad
	.byte 0


SilphCo_9F_Text_YouShouldTakeQuickNap::
# 6 "data/maps/SilphCo_9F/scripts.pory"
	.string "You look tired. You should take a quick\n"
	.string "nap.$"

SilphCo_9F_Text_DontGiveUp::
# 10 "data/maps/SilphCo_9F/scripts.pory"
	.string "Don't give up!$"

SilphCo_9F_Text_ThankYouSoMuch::
# 14 "data/maps/SilphCo_9F/scripts.pory"
	.string "Thank you so much.$"

SilphCo_9F_Text_Grunt1Intro::
# 18 "data/maps/SilphCo_9F/scripts.pory"
	.string "Your POKéMON seem to adore you, kid!$"

SilphCo_9F_Text_Grunt1Defeat::
# 22 "data/maps/SilphCo_9F/scripts.pory"
	.string "Ghaaah!$"

SilphCo_9F_Text_Grunt1PostBattle::
# 26 "data/maps/SilphCo_9F/scripts.pory"
	.string "If I had started as a TRAINER at your\n"
	.string "age…$"

SilphCo_9F_Text_EdIntro::
# 30 "data/maps/SilphCo_9F/scripts.pory"
	.string "Your POKéMON have weak points! I can\n"
	.string "nail them!$"

SilphCo_9F_Text_EdDefeat::
# 34 "data/maps/SilphCo_9F/scripts.pory"
	.string "You hammered me!$"

SilphCo_9F_Text_EdPostBattle::
# 38 "data/maps/SilphCo_9F/scripts.pory"
	.string "Exploiting weak spots does work. Think\n"
	.string "about type advantages.$"

SilphCo_9F_Text_Grunt2Intro::
# 42 "data/maps/SilphCo_9F/scripts.pory"
	.string "I am one of the four ROCKET BROTHERS!$"

SilphCo_9F_Text_Grunt2Defeat::
# 46 "data/maps/SilphCo_9F/scripts.pory"
	.string "Warg! Brothers, I lost!$"

SilphCo_9F_Text_Grunt2PostBattle::
# 50 "data/maps/SilphCo_9F/scripts.pory"
	.string "My brothers will avenge me!$"

SilphCo_9F_Text_FloorSign::
# 54 "data/maps/SilphCo_9F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 9F$"
