MeteorFalls_1F_2R_MapScripts::
	.byte 0


MeteorFalls_1F_2R_Text_NicolasIntro::
# 5 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "This is where we DRAGON users do our\n"
	.string "training.\p"
	.string "The CHAMPION even visits. Now do you\n"
	.string "see how special it is here?$"

MeteorFalls_1F_2R_Text_NicolasDefeat::
# 9 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Urgh! I didn't expect you to be so\n"
	.string "strong!$"

MeteorFalls_1F_2R_Text_NicolasPostBattle::
# 13 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "The road ahead remains long and harsh.\p"
	.string "When will my POKMON and I become the\n"
	.string "best?$"

MeteorFalls_1F_2R_Text_NicolasRegister::
# 17 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "I want to know more about your power.\n"
	.string "Let me register you in my POKNAV.$"

MeteorFalls_1F_2R_Text_NicolasRematchIntro::
# 21 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Since we met, we have trained hard with\n"
	.string "our sights on number one.\p"
	.string "Help us see how much stronger we've\n"
	.string "become!$"

MeteorFalls_1F_2R_Text_NicolasRematchDefeat::
# 25 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Urgh! I didn't expect you to be so\n"
	.string "strong!$"

MeteorFalls_1F_2R_Text_NicolasPostRematch::
# 29 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "You've obviously kept up your POKMON\n"
	.string "training.\p"
	.string "So long as you remain strong, I, too, can\n"
	.string "become stronger!$"

MeteorFalls_1F_2R_Text_JohnIntro::
# 33 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've always battled POKMON\n"
	.string "together as a twosome.\l"
	.string "We've confidence in ourselves.$"

MeteorFalls_1F_2R_Text_JohnDefeat::
# 37 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Oh, my. We've lost, dear wife.$"

MeteorFalls_1F_2R_Text_JohnPostBattle::
# 41 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've been married for fifty\n"
	.string "years.\p"
	.string "Come to think of it, I've yet to beat my\n"
	.string "dear wife in a battle.$"

MeteorFalls_1F_2R_Text_JohnNotEnoughMons::
# 45 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Well, well, what a young TRAINER!\p"
	.string "Will you battle with us? If so, you'll\n"
	.string "have to return with more POKMON.$"

MeteorFalls_1F_2R_Text_JohnRegister::
# 49 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Young TRAINER, if the chance\n"
	.string "arises, will you battle with us again?$"

MeteorFalls_1F_2R_Text_JayIntro::
# 53 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: We've been married for fifty years.\p"
	.string "The bond we share as a couple could\n"
	.string "never be broken.$"

MeteorFalls_1F_2R_Text_JayDefeat::
# 57 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Oh, dear. We've lost, my dear\n"
	.string "husband.$"

MeteorFalls_1F_2R_Text_JayPostBattle::
# 61 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Fifty years of marriage\p"
	.string "If we ever argued, we always settled it\n"
	.string "with a POKMON battle$"

MeteorFalls_1F_2R_Text_JayNotEnoughMons::
# 65 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Well, well, aren't you a young\n"
	.string "TRAINER?\p"
	.string "If you'd care to battle with us, you'll\n"
	.string "have to come back with more POKMON.$"

MeteorFalls_1F_2R_Text_JohnRematchIntro::
# 69 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've always battled POKMON\n"
	.string "together as a twosome.\l"
	.string "We've confidence in ourselves.$"

MeteorFalls_1F_2R_Text_JohnRematchDefeat::
# 73 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Oh, my. We've lost, dear wife.$"

MeteorFalls_1F_2R_Text_JohnPostRematch::
# 77 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Married for fifty years\p"
	.string "On reflection, the dear wife and I, we\n"
	.string "battled day in and day out$"

MeteorFalls_1F_2R_Text_JohnRematchNotEnoughMons::
# 81 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Well, well, what a young TRAINER!\p"
	.string "Will you battle with us? If so, you'll\n"
	.string "have to return with more POKMON.$"

MeteorFalls_1F_2R_Text_JayRematchIntro::
# 85 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: We've been married for fifty years.\p"
	.string "We've supported each other all that\n"
	.string "time. We've made ourselves strong.$"

MeteorFalls_1F_2R_Text_JayRematchDefeat::
# 89 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Oh, dear. We've lost, my dear\n"
	.string "husband.$"

MeteorFalls_1F_2R_Text_JayPostRematch::
# 93 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Fifty years of marriage Many\n"
	.string "things have happened.\p"
	.string "I hope that we will continue to make\n"
	.string "happy memories together.$"

MeteorFalls_1F_2R_Text_JayRematchNotEnoughMons::
# 97 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Well, well, aren't you a young\n"
	.string "TRAINER?\p"
	.string "If you'd care to battle with us, you'll\n"
	.string "have to come back with more POKMON.$"
