MeteorFalls_1F_2R_MapScripts::
	.byte 0


MeteorFalls_1F_2R_MapScripts::
	return


MeteorFalls_1F_2R_Text_NicolasIntro::
# 8 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "This is where we DRAGON users do our\n"
	.string "training.\p"
	.string "The CHAMPION even visits. Now do you\n"
	.string "see how special it is here?$"

MeteorFalls_1F_2R_Text_NicolasDefeat::
# 12 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Urgh! I didn't expect you to be so\n"
	.string "strong!$"

MeteorFalls_1F_2R_Text_NicolasPostBattle::
# 16 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "The road ahead remains long and harsh.\p"
	.string "When will my POKéMON and I become the\n"
	.string "best?$"

MeteorFalls_1F_2R_Text_NicolasRegister::
# 20 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "I want to know more about your power.\n"
	.string "Let me register you in my POKéNAV.$"

MeteorFalls_1F_2R_Text_NicolasRematchIntro::
# 24 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Since we met, we have trained hard with\n"
	.string "our sights on number one.\p"
	.string "Help us see how much stronger we've\n"
	.string "become!$"

MeteorFalls_1F_2R_Text_NicolasRematchDefeat::
# 28 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "Urgh! I didn't expect you to be so\n"
	.string "strong!$"

MeteorFalls_1F_2R_Text_NicolasPostRematch::
# 32 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "You've obviously kept up your POKéMON\n"
	.string "training.\p"
	.string "So long as you remain strong, I, too, can\n"
	.string "become stronger!$"

MeteorFalls_1F_2R_Text_JohnIntro::
# 36 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've always battled POKéMON\n"
	.string "together as a twosome.\l"
	.string "We've confidence in ourselves.$"

MeteorFalls_1F_2R_Text_JohnDefeat::
# 40 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Oh, my. We've lost, dear wife.$"

MeteorFalls_1F_2R_Text_JohnPostBattle::
# 44 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've been married for fifty\n"
	.string "years.\p"
	.string "Come to think of it, I've yet to beat my\n"
	.string "dear wife in a battle.$"

MeteorFalls_1F_2R_Text_JohnNotEnoughMons::
# 48 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Well, well, what a young TRAINER!\p"
	.string "Will you battle with us? If so, you'll\n"
	.string "have to return with more POKéMON.$"

MeteorFalls_1F_2R_Text_JohnRegister::
# 52 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Young TRAINER, if the chance\n"
	.string "arises, will you battle with us again?$"

MeteorFalls_1F_2R_Text_JayIntro::
# 56 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: We've been married for fifty years.\p"
	.string "The bond we share as a couple could\n"
	.string "never be broken.$"

MeteorFalls_1F_2R_Text_JayDefeat::
# 60 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Oh, dear. We've lost, my dear\n"
	.string "husband.$"

MeteorFalls_1F_2R_Text_JayPostBattle::
# 64 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Fifty years of marriage…\p"
	.string "If we ever argued, we always settled it\n"
	.string "with a POKéMON battle…$"

MeteorFalls_1F_2R_Text_JayNotEnoughMons::
# 68 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Well, well, aren't you a young\n"
	.string "TRAINER?\p"
	.string "If you'd care to battle with us, you'll\n"
	.string "have to come back with more POKéMON.$"

MeteorFalls_1F_2R_Text_JohnRematchIntro::
# 72 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: We've always battled POKéMON\n"
	.string "together as a twosome.\l"
	.string "We've confidence in ourselves.$"

MeteorFalls_1F_2R_Text_JohnRematchDefeat::
# 76 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Oh, my. We've lost, dear wife.$"

MeteorFalls_1F_2R_Text_JohnPostRematch::
# 80 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Married for fifty years…\p"
	.string "On reflection, the dear wife and I, we\n"
	.string "battled day in and day out…$"

MeteorFalls_1F_2R_Text_JohnRematchNotEnoughMons::
# 84 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JOHN: Well, well, what a young TRAINER!\p"
	.string "Will you battle with us? If so, you'll\n"
	.string "have to return with more POKéMON.$"

MeteorFalls_1F_2R_Text_JayRematchIntro::
# 88 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: We've been married for fifty years.\p"
	.string "We've supported each other all that\n"
	.string "time. We've made ourselves strong.$"

MeteorFalls_1F_2R_Text_JayRematchDefeat::
# 92 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Oh, dear. We've lost, my dear\n"
	.string "husband.$"

MeteorFalls_1F_2R_Text_JayPostRematch::
# 96 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Fifty years of marriage… Many\n"
	.string "things have happened.\p"
	.string "I hope that we will continue to make\n"
	.string "happy memories together.$"

MeteorFalls_1F_2R_Text_JayRematchNotEnoughMons::
# 100 "data/maps/MeteorFalls_1F_2R/scripts.pory"
	.string "JAY: Well, well, aren't you a young\n"
	.string "TRAINER?\p"
	.string "If you'd care to battle with us, you'll\n"
	.string "have to come back with more POKéMON.$"
