LittlerootTown_BrendansHouse_1F_MapScripts::
	.byte 0


LittlerootTown_BrendansHouse_1F_EventScript_GoSeeRoom::
	end


LittlerootTown_BrendansHouse_1F_EventScript_MeetRival0::
	end


LittlerootTown_BrendansHouse_1F_EventScript_MeetRival1::
	end


LittlerootTown_BrendansHouse_1F_EventScript_MeetRival2::
	end


LittlerootTown_BrendansHouse_1F_EventScript_SmithNPC1::
# 25 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	msgbox LittlerootTown_BrendansHouse_1F_Text_SmithNPC1, MSGBOX_NPC
	end


LittlerootTown_BrendansHouse_1F_EventScript_SmithNPC2::
# 34 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	msgbox LittlerootTown_BrendansHouse_1F_Text_SmithNPC2, MSGBOX_NPC
	end


PlayersHouse_1F_Text_GoSetTheClock::
# 20 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: {PLAYER}.\p"
	.string "Go set the clock in your room, honey.$"

LittlerootTown_BrendansHouse_1F_Text_SmithNPC1::
# 29 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

LittlerootTown_BrendansHouse_1F_Text_SmithNPC2::
# 38 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
