LittlerootTown_BrendansHouse_1F_MapScripts::
# 2 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, LittlerootTown_BrendansHouse_1F_OnLoad
# 3 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_BrendansHouse_1F_OnTransition
# 4 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_BrendansHouse_1F_OnFrame
	.byte 0


PlayersHouse_1F_Text_IsntItNiceInHere::
# 8 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: See, {PLAYER}? Isn't it nice in\n"
	.string "here, too?$"

PlayersHouse_1F_Text_MoversPokemonGoSetClock::
# 12 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "The mover's POKMON do all the work of\n"
	.string "moving us in and cleaning up after.\l"
	.string "This is so convenient!\p"
	.string "{PLAYER}, your room is upstairs. Go\n"
	.string "check it out, dear!\p"
	.string "DAD bought you a new clock to mark our\n"
	.string "move here.\l"
	.string "Don't forget to set it!$"

PlayersHouse_1F_Text_ArentYouInterestedInRoom::
# 16 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Well, {PLAYER}?\p"
	.string "Aren't you interested in seeing your\n"
	.string "very own room?$"

PlayersHouse_1F_Text_GoSetTheClock::
# 20 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: {PLAYER}.\p"
	.string "Go set the clock in your room, honey.$"

PlayersHouse_1F_Text_OhComeQuickly::
# 24 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Oh! {PLAYER}, {PLAYER}! Quick!\n"
	.string "Come quickly!$"

PlayersHouse_1F_Text_MaybeDadWillBeOn::
# 28 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Look! It's PETALBURG GYM! Maybe\n"
	.string "DAD will be on!$"

PlayersHouse_1F_Text_ItsOverWeMissedHim::
# 32 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Oh It's over.\p"
	.string "I think DAD was on, but we missed him.\n"
	.string "Too bad.$"

PlayersHouse_1F_Text_GoIntroduceYourselfNextDoor::
# 36 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Oh, yes. One of DAD's friends lives in\n"
	.string "town.\p"
	.string "PROF. BIRCH is his name.\p"
	.string "He lives right next door, so you should\n"
	.string "go over and introduce yourself.$"

PlayersHouse_1F_Text_SeeYouHoney::
# 40 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: See you, honey!$"

PlayersHouse_1F_Text_DidYouMeetProfBirch::
# 44 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Did you introduce yourself to\n"
	.string "PROF. BIRCH?$"

PlayersHouse_1F_Text_YouShouldRestABit::
# 48 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: How are you doing, {PLAYER}? You\n"
	.string "look a little tired.\p"
	.string "I think you should rest a bit.$"

PlayersHouse_1F_Text_TakeCareHoney::
# 52 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Take care, honey!$"

PlayersHouse_1F_Text_GotDadsBadgeHeresSomethingFromMom::
# 56 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Oh? Did DAD give you that BADGE?\p"
	.string "Then here's something from your MOM!$"

PlayersHouse_1F_Text_DontPushYourselfTooHard::
# 60 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Don't push yourself too hard, dear. You\n"
	.string "can always come home.\p"
	.string "Go for it, honey!$"

PlayersHouse_1F_Text_IsThatAPokenav::
# 64 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: What is that, honey? A POKNAV?\n"
	.string "Someone from DEVON gave it to you?\p"
	.string "Well, honey, how about registering your\n"
	.string "mom?\p"
	.string "$"

PlayersHouse_1F_Text_RegisteredMom::
# 68 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Registered MOM in the POKNAV.$"

PlayersHouse_1F_Text_Vigoroth1::
# 72 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Fugiiiiih!$"

PlayersHouse_1F_Text_Vigoroth2::
# 76 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "Huggoh, uggo uggo$"

PlayersHouse_1F_Text_ReportFromPetalburgGym::
# 80 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "INTERVIEWER: We brought you this\n"
	.string "report from in front of PETALBURG GYM.$"

PlayersHouse_1F_Text_TheresAMovieOnTV::
# 84 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "There is a movie on TV.\p"
	.string "Two men are dancing on a big piano\n"
	.string "keyboard.\p"
	.string "Better get going!$"

PlayersHouse_1F_Text_RunningShoesManual::
# 88 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "It's the instruction booklet for the\n"
	.string "RUNNING SHOES.\p"
	.string "Press the B Button to run while wearing\n"
	.string "your RUNNING SHOES.\p"
	.string "Lace up your RUNNING SHOES and hit the\n"
	.string "road running!$"

PlayersHouse_1F_Text_TicketFromBrineyCameForYou::
# 92 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "DAD: Hm?\p"
	.string "Hey, it's {PLAYER}!\p"
	.string "It's been a while since I saw you, but\n"
	.string "you lookstronger, somehow.\p"
	.string "That's the impression I get. But your\n"
	.string "old man hasn't given up yet!\p"
	.string "Oh, yes, I have something for you. This\n"
	.string "came to you from someone named\l"
	.string "MR. BRINEY.$"

PlayersHouse_1F_Text_PortsInSlateportLilycove::
# 96 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "DAD: Hm, a TICKET for a ferry?\p"
	.string "If I recall, there are ferry ports in\n"
	.string "SLATEPORT and LILYCOVE.$"

PlayersHouse_1F_Text_BetterGetBackToGym::
# 100 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "I'd better get back to PETALBURG GYM.\p"
	.string "MOM, thanks for looking after the house\n"
	.string "while I'm away.$"

PlayersHouse_1F_Text_DadShouldStayLonger::
# 104 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: That DAD of yours\p"
	.string "He comes home for the first time in a\n"
	.string "while, but all he talks about is POKMON.\p"
	.string "He should relax and stay a little longer.$"

PlayersHouse_1F_Text_IsThatABreakingStory::
# 108 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Is that a breaking news story?$"

PlayersHouse_1F_Text_LatiEmergencyNewsFlash::
# 112 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "We bring you this emergency news flash!\p"
	.string "In various HOENN locales, there have\n"
	.string "been reports of a BZZTcolored\l"
	.string "POKMON in flight.\p"
	.string "The identity of this POKMON is\n"
	.string "currently unknown.\p"
	.string "We now return you to the regular movie\n"
	.string "program.$"

PlayersHouse_1F_Text_WhatColorDidTheySay::
# 116 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: {PLAYER}, did you catch that?\p"
	.string "What color did the announcer say that\n"
	.string "POKMON was?$"

PlayersHouse_1F_Text_StillUnknownPokemon::
# 120 "data/maps/LittlerootTown_BrendansHouse_1F/scripts.pory"
	.string "MOM: Well, isn't that something! There\n"
	.string "are still unknown POKMON.$"
