Route25_MapScripts::
	.byte 0


Route25_Text_JoeyIntro::
# 5 "data/maps/Route25/scripts.pory"
	.string "Local TRAINERS come here to practice.$"

Route25_Text_JoeyDefeat::
# 9 "data/maps/Route25/scripts.pory"
	.string "You're decent.$"

Route25_Text_JoeyPostBattle::
# 13 "data/maps/Route25/scripts.pory"
	.string "All POKéMON have weaknesses. Even the\n"
	.string "strongest ones.\p"
	.string "That's why it's best to raise POKéMON of\n"
	.string "different types.$"

Route25_Text_DanIntro::
# 17 "data/maps/Route25/scripts.pory"
	.string "Dad took me to a great party on the S.S.\n"
	.string "ANNE at VERMILION CITY.$"

Route25_Text_DanDefeat::
# 21 "data/maps/Route25/scripts.pory"
	.string "I'm not mad!$"

Route25_Text_DanPostBattle::
# 25 "data/maps/Route25/scripts.pory"
	.string "On the S.S. ANNE, I saw TRAINERS from\n"
	.string "around the world.$"

Route25_Text_FlintIntro::
# 29 "data/maps/Route25/scripts.pory"
	.string "I'm a cool guy. I've got a girlfriend!$"

Route25_Text_FlintDefeat::
# 33 "data/maps/Route25/scripts.pory"
	.string "Aww, darn…$"

Route25_Text_FlintPostBattle::
# 37 "data/maps/Route25/scripts.pory"
	.string "Oh, well. My girlfriend will cheer me up.$"

Route25_Text_KelseyIntro::
# 41 "data/maps/Route25/scripts.pory"
	.string "Hi! My boyfriend is cool!$"

Route25_Text_KelseyDefeat::
# 45 "data/maps/Route25/scripts.pory"
	.string "My conditioning isn't the best…$"

Route25_Text_KelseyPostBattle::
# 49 "data/maps/Route25/scripts.pory"
	.string "I wish my boyfriend was as good as you.$"

Route25_Text_ChadIntro::
# 53 "data/maps/Route25/scripts.pory"
	.string "I had this feeling… I knew I had to\n"
	.string "battle you!$"

Route25_Text_ChadDefeat::
# 57 "data/maps/Route25/scripts.pory"
	.string "I knew I'd lose, too!$"

Route25_Text_ChadPostBattle::
# 61 "data/maps/Route25/scripts.pory"
	.string "If your POKéMON gets confused, switch\n"
	.string "it out.\p"
	.string "That's a good tactic.$"

Route25_Text_HaleyIntro::
# 65 "data/maps/Route25/scripts.pory"
	.string "My friend has many cute POKéMON. I'm so\n"
	.string "jealous!$"

Route25_Text_HaleyDefeat::
# 69 "data/maps/Route25/scripts.pory"
	.string "I'm not so jealous!$"

Route25_Text_HaleyPostBattle::
# 73 "data/maps/Route25/scripts.pory"
	.string "You came from MT. MOON? May I have a\n"
	.string "CLEFAIRY?$"

Route25_Text_FranklinIntro::
# 77 "data/maps/Route25/scripts.pory"
	.string "I just got down from MT. MOON, but I've\n"
	.string "still got gas in the tank!$"

Route25_Text_FranklinDefeat::
# 81 "data/maps/Route25/scripts.pory"
	.string "You worked hard!$"

Route25_Text_FranklinPostBattle::
# 85 "data/maps/Route25/scripts.pory"
	.string "Drat! A ZUBAT bit me back in that cave.$"

Route25_Text_NobIntro::
# 89 "data/maps/Route25/scripts.pory"
	.string "I'm off to see a POKéMANIAC's\n"
	.string "collection at the cape.$"

Route25_Text_NobDefeat::
# 93 "data/maps/Route25/scripts.pory"
	.string "You done got me, and real good, too!$"

Route25_Text_NobPostBattle::
# 97 "data/maps/Route25/scripts.pory"
	.string "The POKéMANIAC sure lives up to his\n"
	.string "name.\p"
	.string "His collection includes many rare\n"
	.string "species of POKéMON.$"

Route25_Text_WayneIntro::
# 101 "data/maps/Route25/scripts.pory"
	.string "You're going to see BILL? First, we\n"
	.string "battle!$"

Route25_Text_WayneDefeat::
# 105 "data/maps/Route25/scripts.pory"
	.string "You're something.$"

Route25_Text_WaynePostBattle::
# 109 "data/maps/Route25/scripts.pory"
	.string "The trail below is a shortcut to\n"
	.string "CERULEAN CITY.$"

Route25_Text_SeaCottageSign::
# 113 "data/maps/Route25/scripts.pory"
	.string "SEA COTTAGE BILL lives here!$"

Route25_Text_MistyHighHopesAboutThisPlace::
# 117 "data/maps/Route25/scripts.pory"
	.string "This cape is a famous date spot.\p"
	.string "MISTY, the GYM LEADER, has high hopes\n"
	.string "about this place.$"

Route25_Text_AreYouHereAlone::
# 121 "data/maps/Route25/scripts.pory"
	.string "Hello, are you here alone?\p"
	.string "If you're out at CERULEAN's cape… Well,\n"
	.string "it should be as a couple.$"
