ThreeIsland_Port_MapScripts::
# 2 "data/maps/ThreeIsland_Port/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_Port_OnTransition
	.byte 0


ThreeIsland_Port_Text_WereKantoRiderFederation::
# 6 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "We're the KANTO RIDER FEDERATION!\n"
	.string "Vroom! Vavavavooom! Vroom!\p"
	.string "My bike's wimpy, so I have to make\n"
	.string "exhaust noises myself!$"

ThreeIsland_Port_Text_ForkOverMoney::
# 10 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "Hey, hey, lady! Fork over some spending\n"
	.string "money!$"

ThreeIsland_Port_Text_IllCallThePolice::
# 14 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "Aiyeeh!\p"
	.string "Wh-who are you?! I I'll call the police!$"

ThreeIsland_Port_Text_ThankGoodnessBikersGone::
# 18 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "Those BIKERS Are they gone?\p"
	.string "Oh, thank goodness! They certainly had\n"
	.string "me terrified!$"

ThreeIsland_Port_Text_EverythingTurnedOutForBest::
# 22 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "Those BIKERS ran off, and LOSTELLE was\n"
	.string "found safe.\p"
	.string "Everything turned out for the best!$"
