ThreeIsland_Port_MapScripts::
	.byte 0


ThreeIsland_Port_EventScript_Biker1::
# 5 "data/maps/ThreeIsland_Port/scripts.pory"
	msgbox ThreeIsland_Port_Text_WereKantoRiderFederation, MSGBOX_NPC
	end


ThreeIsland_Port_EventScript_Biker2::
	end


ThreeIsland_Port_EventScript_Woman::
	end


ThreeIsland_Port_Text_WereKantoRiderFederation::
# 18 "data/maps/ThreeIsland_Port/scripts.pory"
	.string "We're the KANTO RIDER FEDERATION!\n"
	.string "Vroom! Vavavavooom! Vroom!\p"
	.string "My bike's wimpy, so I have to\n"
	.string "make exhaust noises myself!$"
