MossdeepCity_PokemonCenter_2F_MapScripts::
	.byte 0


MossdeepCity_PokemonCenter_2F_EventScript_Woman5::
# 5 "data/maps/MossdeepCity_PokemonCenter_2F/scripts.pory"
	msgbox MossdeepCity_PokemonCenter_2F_Text_Woman5, MSGBOX_NPC
	end


MossdeepCity_PokemonCenter_2F_Text_Woman5::
# 9 "data/maps/MossdeepCity_PokemonCenter_2F/scripts.pory"
	.string "If I win a whole lot of link battles\n"
	.string "and show everyone how good I am,\l"
	.string "I might get a fan following!$"
