PalletTown_ProfessorOaksLab_MapScripts::
	.byte 0


PalletTown_ProfessorOaksLab_EventScript_Aide1::
	end


PalletTown_ProfessorOaksLab_EventScript_Aide2::
	end


PalletTown_ProfessorOaksLab_EventScript_Aide3::
	end


PalletTown_ProfessorOaksLab_EventScript_BulbasaurBall::
	end


PalletTown_ProfessorOaksLab_EventScript_CharmanderBall::
	end


PalletTown_ProfessorOaksLab_EventScript_Computer::
# 25 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	msgbox PalletTown_ProfessorOaksLab_Text_EmailMessage, MSGBOX_SIGN
	end


PalletTown_ProfessorOaksLab_EventScript_LeaveStarterSceneTrigger::
	end


PalletTown_ProfessorOaksLab_EventScript_LeftSign::
# 34 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	msgbox PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu, MSGBOX_SIGN
	end


PalletTown_ProfessorOaksLab_EventScript_Pokedex::
# 39 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	msgbox PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia, MSGBOX_NPC
	end


PalletTown_ProfessorOaksLab_EventScript_ProfOak::
	end


PalletTown_ProfessorOaksLab_EventScript_RightSign::
# 50 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	msgbox PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu, MSGBOX_SIGN
	end


PalletTown_ProfessorOaksLab_EventScript_Rival::
	end


PalletTown_ProfessorOaksLab_EventScript_RivalBattleTriggerLeft::
	end


PalletTown_ProfessorOaksLab_EventScript_RivalBattleTriggerMid::
	end


PalletTown_ProfessorOaksLab_EventScript_RivalBattleTriggerRight::
	end


PalletTown_ProfessorOaksLab_EventScript_SquirtleBall::
	end


PalletTown_ProfessorOaksLab_Text_EmailMessage::
# 76 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	.string "There's an e-mail message here.\p"
	.string "…\p"
	.string "Finally! The ultimate TRAINERS of the\l"
	.string "POKéMON LEAGUE are ready to\l"
	.string "take on all comers!\p"
	.string "Bring your best POKéMON and see how\n"
	.string "you rate as a TRAINER!\p"
	.string "POKéMON LEAGUE HQ INDIGO PLATEAU\p"
	.string "PROF. OAK, please visit us! …$"

PalletTown_ProfessorOaksLab_Text_SaveOptionInMenu::
# 80 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	.string "The SAVE option is on the MENU. Use it\n"
	.string "regularly.$"

PalletTown_ProfessorOaksLab_Text_PressStartToOpenMenu::
# 84 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	.string "Press START to open the MENU!$"

PalletTown_ProfessorOaksLab_Text_BlankEncyclopedia::
# 88 "data/maps/PalletTown_ProfessorOaksLab/scripts.pory"
	.string "It's like an encyclopedia, but the\n"
	.string "pages are blank.$"
