FourIsland_Mart_MapScripts::
	.byte 0


FourIsland_Mart_EventScript_Camper::
# 5 "data/maps/FourIsland_Mart/scripts.pory"
	msgbox FourIsland_Mart_Text_IcefallCaveIsFrigid, MSGBOX_NPC
	end


FourIsland_Mart_EventScript_Clerk::
	end


FourIsland_Mart_Text_IcefallCaveIsFrigid::
# 14 "data/maps/FourIsland_Mart/scripts.pory"
	.string "The SEVII ISLANDS are in a warm\n"
	.string "region overall.\p"
	.string "But there is one exception you\n"
	.string "need to know about.\p"
	.string "The ICEFALL CAVE is frigid because\n"
	.string "of the POKéMON that live in it.$"
