FourIsland_Mart_MapScripts::
	.byte 0


FourIsland_Mart_Text_LoreleiGrewUpOnThisIsland::
# 5 "data/maps/FourIsland_Mart/scripts.pory"
	.string "We've had a great and powerful TRAINER\n"
	.string "grow up on this island.\p"
	.string "I bet even you'd know her. It's LORELEI\n"
	.string "of the ELITE FOUR!\p"
	.string "When LORELEI was just a tyke, I taught\n"
	.string "her about POKéMON.$"

FourIsland_Mart_Text_IcefallCaveIsFrigid::
# 9 "data/maps/FourIsland_Mart/scripts.pory"
	.string "The SEVII ISLANDS are in a warm region\n"
	.string "overall.\p"
	.string "But there is one exception you need to\n"
	.string "know about.\p"
	.string "The ICEFALL CAVE is frigid because of\n"
	.string "the POKéMON that live in it.$"
