MtPyre_6F_MapScripts::
	.byte 0


MtPyre_6F_Text_ValerieIntro::
# 5 "data/maps/MtPyre_6F/scripts.pory"
	.string "When I'm here A curious power flows into\n"
	.string "me$"

MtPyre_6F_Text_ValerieDefeat::
# 9 "data/maps/MtPyre_6F/scripts.pory"
	.string "The power is ebbing away$"

MtPyre_6F_Text_ValeriePostBattle::
# 13 "data/maps/MtPyre_6F/scripts.pory"
	.string "Perhaps the power is from the spirits\n"
	.string "of POKMON in fitful sleep here$"

MtPyre_6F_Text_ValerieRegister::
# 17 "data/maps/MtPyre_6F/scripts.pory"
	.string "Fufufu I lost the match, but I have\n"
	.string "this little ability\p"
	.string "Without ever laying my hands on your\n"
	.string "POKNAV Hiyah!$"

MtPyre_6F_Text_ValerieRematchIntro::
# 21 "data/maps/MtPyre_6F/scripts.pory"
	.string "Behind you What is it$"

MtPyre_6F_Text_ValerieRematchDefeat::
# 25 "data/maps/MtPyre_6F/scripts.pory"
	.string "Something faded away$"

MtPyre_6F_Text_ValeriePostRematch::
# 29 "data/maps/MtPyre_6F/scripts.pory"
	.string "The POKMON at rest here Sometimes,\n"
	.string "they play$"

MtPyre_6F_Text_CedricIntro::
# 33 "data/maps/MtPyre_6F/scripts.pory"
	.string "Have you lost your bearings? Have no\n"
	.string "fear for I am here!$"

MtPyre_6F_Text_CedricDefeat::
# 37 "data/maps/MtPyre_6F/scripts.pory"
	.string "Weren't you lost?$"

MtPyre_6F_Text_CedricPostBattle::
# 41 "data/maps/MtPyre_6F/scripts.pory"
	.string "I had this feeling that a lost TRAINER\n"
	.string "would be panicked and easy to beat.\p"
	.string "It's dirty and I won't try it again$"
