MtPyre_6F_MapScripts::
	.byte 0


MtPyre_6F_MapScripts::
	return


MtPyre_6F_Text_ValerieIntro::
# 8 "data/maps/MtPyre_6F/scripts.pory"
	.string "When I'm here… A curious power flows\n"
	.string "into me…$"

MtPyre_6F_Text_ValerieDefeat::
# 12 "data/maps/MtPyre_6F/scripts.pory"
	.string "The power is ebbing away…$"

MtPyre_6F_Text_ValeriePostBattle::
# 16 "data/maps/MtPyre_6F/scripts.pory"
	.string "Perhaps the power is from the spirits\n"
	.string "of POKéMON in fitful sleep here…$"

MtPyre_6F_Text_ValerieRegister::
# 20 "data/maps/MtPyre_6F/scripts.pory"
	.string "Fufufu… I lost the match, but… I have\n"
	.string "this little ability…\p"
	.string "Without ever laying my hands on your\n"
	.string "POKéNAV… Hiyah!$"

MtPyre_6F_Text_ValerieRematchIntro::
# 24 "data/maps/MtPyre_6F/scripts.pory"
	.string "Behind you… What is it…$"

MtPyre_6F_Text_ValerieRematchDefeat::
# 28 "data/maps/MtPyre_6F/scripts.pory"
	.string "Something faded away…$"

MtPyre_6F_Text_ValeriePostRematch::
# 32 "data/maps/MtPyre_6F/scripts.pory"
	.string "The POKéMON at rest here… Sometimes,\n"
	.string "they play…$"

MtPyre_6F_Text_CedricIntro::
# 36 "data/maps/MtPyre_6F/scripts.pory"
	.string "Have you lost your bearings? Have no\n"
	.string "fear for I am here!$"

MtPyre_6F_Text_CedricDefeat::
# 40 "data/maps/MtPyre_6F/scripts.pory"
	.string "Weren't you lost?$"

MtPyre_6F_Text_CedricPostBattle::
# 44 "data/maps/MtPyre_6F/scripts.pory"
	.string "I had this feeling that a lost TRAINER\n"
	.string "would be panicked and easy to beat.\p"
	.string "It's dirty and I won't try it again…$"
