Route11_EastEntrance_1F_MapScripts::
	.byte 0


Route11_EastEntrance_1F_EventScript_BottomGuard::
# 5 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	msgbox Route11_EastEntrance_1F_Text_RockTunnelToReachLavender, MSGBOX_NPC
	end


Route11_EastEntrance_1F_EventScript_TopGuard::
# 10 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	msgbox Route11_EastEntrance_1F_Text_ManInLavenderRatesNames, MSGBOX_NPC
	end


Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
# 15 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	.string "If you're aiming to reach LAVENDER\n"
	.string "TOWN, take ROCK TUNNEL.\p"
	.string "You can get to ROCK TUNNEL from\n"
	.string "CERULEAN CITY.$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
# 19 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	.string "Don't you think it's hard to think\n"
	.string "up good names for POKéMON?\p"
	.string "Especially if you've caught a\n"
	.string "whole bunch?\p"
	.string "In LAVENDER TOWN, there's a man\n"
	.string "who rates POKéMON nicknames.\p"
	.string "He can even help you rename your\n"
	.string "POKéMON, too.$"
