Route11_EastEntrance_1F_MapScripts::
	.byte 0


Route11_EastEntrance_1F_Text_BagIsFull::
# 5 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	.string "{PLAYER}{KUN}$"

Route11_EastEntrance_1F_Text_ManInLavenderRatesNames::
# 9 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	.string "Don't you think it's hard to think up\n"
	.string "good names for POKMON?\p"
	.string "Especially if you've caught a whole\n"
	.string "bunch?\p"
	.string "In LAVENDER TOWN, there's a man who\n"
	.string "rates POKMON nicknames.\p"
	.string "He can even help you rename your\n"
	.string "POKMON, too.$"

Route11_EastEntrance_1F_Text_RockTunnelToReachLavender::
# 13 "data/maps/Route11_EastEntrance_1F/scripts.pory"
	.string "If you're aiming to reach LAVENDER\n"
	.string "TOWN, take ROCK TUNNEL.\p"
	.string "You can get to ROCK TUNNEL from\n"
	.string "CERULEAN CITY.$"
