Route109_SeashoreHouse_MapScripts::
# 2 "data/maps/Route109_SeashoreHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route109_SeashoreHouse_OnTransition
	.byte 0


Route109_SeashoreHouse_Text_SeashoreHouseIntro::
# 6 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "I'm the owner of the SEASHORE HOUSE.\n"
	.string "But you can call me MR. SEA!\p"
	.string "What I love above all is to see hot\n"
	.string "POKéMON battles.\p"
	.string "Let me see that your heart burns hot!\p"
	.string "If you can defeat all the TRAINERS\n"
	.string "here, I'll reward your efforts.$"

Route109_SeashoreHouse_Text_ShowMeSomeHotMatches::
# 10 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Show me some hot matches!\p"
	.string "I run this SEASHORE HOUSE just for that\n"
	.string "reason alone!$"

Route109_SeashoreHouse_Text_TakeTheseSodaPopBottles::
# 14 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "You're scorching hot! Those battles\n"
	.string "blazed!\l"
	.string "I'm more than just satisfied!\p"
	.string "As thanks for showing me your hot\n"
	.string "streak, I want you to take these.\p"
	.string "It's half a dozen bottles of SODA POP!$"

Route109_SeashoreHouse_Text_BagFull::
# 18 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Oh, but hey, your BAG's jammed full. I'll\n"
	.string "hang on to these for you.$"

Route109_SeashoreHouse_Text_WantToBuySodaPop::
# 22 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Want to buy some SODA POP? POKéMON\n"
	.string "love it!\p"
	.string "Just ¥300 a bottle! Buy some!$"

Route109_SeashoreHouse_Text_HereYouGo::
# 26 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Here you go!$"

Route109_SeashoreHouse_Text_NotEnoughMoney::
# 30 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "You don't have the money.$"

Route109_SeashoreHouse_Text_ThatsTooBad::
# 34 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "No? That's too bad.$"

Route109_SeashoreHouse_Text_DwayneIntro::
# 38 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "If you're looking for a battle in the\n"
	.string "SEASHORE HOUSE, you'll find no\l"
	.string "hotter TRAINER than me, matey!$"

Route109_SeashoreHouse_Text_DwayneDefeated::
# 42 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "That was a hot battle! I can accept\n"
	.string "that loss, matey!$"

Route109_SeashoreHouse_Text_DwaynePostBattle::
# 46 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Whenever I'm in SLATEPORT, I enjoy hot\n"
	.string "battles and ice-cold SODA POP!$"

Route109_SeashoreHouse_Text_JohannaIntro::
# 50 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Boring battles aren't worth the effort.\p"
	.string "Fiery hot battles are what toughen up\n"
	.string "TRAINERS and POKéMON!$"

Route109_SeashoreHouse_Text_JohannaDefeated::
# 54 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "That's hot!$"

Route109_SeashoreHouse_Text_JohannaPostBattle::
# 58 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "Whew, I'm all thirsty. Maybe I'll have a\n"
	.string "SODA POP.$"

Route109_SeashoreHouse_Text_SimonIntro::
# 62 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "I'm going to show you how great my\n"
	.string "POKéMON are, but don't cry!$"

Route109_SeashoreHouse_Text_SimonDefeated::
# 66 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "…I lost, but I won't cry…$"

Route109_SeashoreHouse_Text_SimonPostBattle::
# 70 "data/maps/Route109_SeashoreHouse/scripts.pory"
	.string "If one of my POKéMON knew the move for\n"
	.string "carrying me across water on its\l"
	.string "back, I could get rid of this inner tube.$"
