Route9_MapScripts::
	.byte 0


Route9_Text_AliciaIntro::
# 5 "data/maps/Route9/scripts.pory"
	.string "You have POKéMON with you! You're mine!$"

Route9_Text_AliciaDefeat::
# 9 "data/maps/Route9/scripts.pory"
	.string "You deceived me…$"

Route9_Text_AliciaPostBattle::
# 13 "data/maps/Route9/scripts.pory"
	.string "The tunnel coming up is pitch-black\n"
	.string "inside.\p"
	.string "You'll need FLASH to get through there.$"

Route9_Text_ChrisIntro::
# 17 "data/maps/Route9/scripts.pory"
	.string "Who's that walking there with those\n"
	.string "good-looking POKéMON?$"

Route9_Text_ChrisDefeat::
# 21 "data/maps/Route9/scripts.pory"
	.string "Out like a light!$"

Route9_Text_ChrisPostBattle::
# 25 "data/maps/Route9/scripts.pory"
	.string "Keep walking!$"

Route9_Text_DrewIntro::
# 29 "data/maps/Route9/scripts.pory"
	.string "I'm taking the ROCK TUNNEL to go to\n"
	.string "LAVENDER…$"

Route9_Text_DrewDefeat::
# 33 "data/maps/Route9/scripts.pory"
	.string "Can't measure up…$"

Route9_Text_DrewPostBattle::
# 37 "data/maps/Route9/scripts.pory"
	.string "Are you off to ROCK TUNNEL, too?$"

Route9_Text_CaitlinIntro::
# 41 "data/maps/Route9/scripts.pory"
	.string "Don't you dare patronize me!$"

Route9_Text_CaitlinDefeat::
# 45 "data/maps/Route9/scripts.pory"
	.string "No! You're too much.$"

Route9_Text_CaitlinPostBattle::
# 49 "data/maps/Route9/scripts.pory"
	.string "You're obviously talented. Good luck to\n"
	.string "you!$"

Route9_Text_JeremyIntro::
# 53 "data/maps/Route9/scripts.pory"
	.string "Bwahaha! Great! I was bored, eh!$"

Route9_Text_JeremyDefeat::
# 57 "data/maps/Route9/scripts.pory"
	.string "Keep it coming, eh!\p"
	.string "Oh wait. I'm out of POKéMON!$"

Route9_Text_JeremyPostBattle::
# 61 "data/maps/Route9/scripts.pory"
	.string "You sure had guts standing up to me\n"
	.string "there, eh?$"

Route9_Text_BriceIntro::
# 65 "data/maps/Route9/scripts.pory"
	.string "Hahaha! Aren't you a little toughie!$"

Route9_Text_BriceDefeat::
# 69 "data/maps/Route9/scripts.pory"
	.string "What's that?$"

Route9_Text_BricePostBattle::
# 73 "data/maps/Route9/scripts.pory"
	.string "Hahaha! Kids should be tough!$"

Route9_Text_BrentIntro::
# 77 "data/maps/Route9/scripts.pory"
	.string "I got up early every day to raise my\n"
	.string "POKéMON from cocoons!$"

Route9_Text_BrentDefeat::
# 81 "data/maps/Route9/scripts.pory"
	.string "WHAT?\p"
	.string "What a total waste of time!$"

Route9_Text_BrentPostBattle::
# 85 "data/maps/Route9/scripts.pory"
	.string "I have to collect more than bugs to get\n"
	.string "stronger…$"

Route9_Text_AlanIntro::
# 89 "data/maps/Route9/scripts.pory"
	.string "Hahahaha! Bring it on!$"

Route9_Text_AlanDefeat::
# 93 "data/maps/Route9/scripts.pory"
	.string "Hahahaha! You beat me fair!$"

Route9_Text_AlanPostBattle::
# 97 "data/maps/Route9/scripts.pory"
	.string "Hahahaha! Us hearty guys always laugh!$"

Route9_Text_ConnerIntro::
# 101 "data/maps/Route9/scripts.pory"
	.string "Go, my super BUG POKéMON!$"

Route9_Text_ConnerDefeat::
# 105 "data/maps/Route9/scripts.pory"
	.string "My bugs…$"

Route9_Text_ConnerPostBattle::
# 109 "data/maps/Route9/scripts.pory"
	.string "If you don't like BUG POKéMON, you bug\n"
	.string "me!$"

Route9_Text_RouteSign::
# 113 "data/maps/Route9/scripts.pory"
	.string "ROUTE 9 CERULEAN CITY - ROCK TUNNEL$"
