PokemonLeague_ChampionsRoom_MapScripts::
# 2 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_ChampionsRoom_OnWarp
# 3 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_ChampionsRoom_OnResume
# 4 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_ChampionsRoom_OnFrame
	.byte 0


PokemonLeague_ChampionsRoom_Text_Intro::
# 8 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "{RIVAL}: Hey, {PLAYER}!\p"
	.string "I was looking forward to seeing you,\n"
	.string "{PLAYER}.\p"
	.string "My rival should be strong to keep me\n"
	.string "sharp.\p"
	.string "While working on my POKDEX, I looked all\n"
	.string "over for POKMON.\p"
	.string "Not only that, I assembled teams that\n"
	.string "would beat any POKMON type.\p"
	.string "And now\p"
	.string "I'm the POKMON LEAGUE CHAMPION!\p"
	.string "{PLAYER}! Do you know what that\n"
	.string "means?\p"
	.string "I'll tell you.\p"
	.string "I am the most powerful TRAINER in the\n"
	.string "world!$"

PokemonLeague_ChampionsRoom_Text_RematchIntro::
# 12 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "{RIVAL}: Hey, {PLAYER}!\p"
	.string "You came back, {PLAYER}! Hahah, that\n"
	.string "is so great!\p"
	.string "My rival should be strong to keep me\n"
	.string "sharp.\p"
	.string "While working on my POKDEX, I looked all\n"
	.string "over for POKMON.\p"
	.string "Not only that, I assembled teams that\n"
	.string "would beat any POKMON type.\p"
	.string "And now\p"
	.string "I'm the POKMON LEAGUE CHAMPION!\p"
	.string "{PLAYER}! Do you know what that\n"
	.string "means?\p"
	.string "I'll tell you.\p"
	.string "I am the most powerful TRAINER in the\n"
	.string "world!$"

PokemonLeague_ChampionsRoom_Text_Defeat::
# 16 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "NO! That can't be!\l"
	.string "You beat me at my best!\p"
	.string "After all that work to become the\n"
	.string "LEAGUE CHAMP?\p"
	.string "My reign is over already? It's not fair!$"

PokemonLeague_ChampionsRoom_Text_Victory::
# 20 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "\p"
	.string "{PLAYER}\p"
	.string "{RIVAL}\l"
	.string "\p"
	.string "$"

PokemonLeague_ChampionsRoom_Text_PostBattle::
# 24 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "Why? Why did I lose?\p"
	.string "I never made any mistakes raising my\n"
	.string "POKMON\p"
	.string "Darn it! You're the new POKMON LEAGUE\n"
	.string "CHAMPION!\p"
	.string "Although I don't like to admit it$"

PokemonLeague_ChampionsRoom_Text_OakPlayer::
# 28 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "OAK: {PLAYER}!$"

PokemonLeague_ChampionsRoom_Text_OakCongratulations::
# 32 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "OAK: So, you've won! Sincerely,\n"
	.string "congratulations!\p"
	.string "You're the new POKMON LEAGUE CHAMPION!\p"
	.string "You've grown up so much since you first\n"
	.string "left with {STR_VAR_1} to work\l"
	.string "on the POKDEX.\p"
	.string "{PLAYER}, you have come of age!$"

PokemonLeague_ChampionsRoom_Text_OakImDisappointedRival::
# 36 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "OAK: {RIVAL} I'm disappointed in you.\p"
	.string "I came when I heard you'd beaten the\n"
	.string "ELITE FOUR.\p"
	.string "But, when I got here, you had already\n"
	.string "lost!\p"
	.string "{RIVAL}, do you understand why you\n"
	.string "lost?\p"
	.string "You have forgotten to treat your\n"
	.string "POKMON with love and trust.\p"
	.string "Without them, you will never become a\n"
	.string "CHAMP again!$"

PokemonLeague_ChampionsRoom_Text_OakPlayerComeWithMe::
# 40 "data/maps/PokemonLeague_ChampionsRoom/scripts.pory"
	.string "OAK: {PLAYER}.\p"
	.string "You understand that your victory was\n"
	.string "not just your own doing.\p"
	.string "The bond you share with your POKMON is\n"
	.string "marvelous.\p"
	.string "{PLAYER}! Come with me!$"
