Route119_WeatherInstitute_1F_MapScripts::
# 2 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route119_WeatherInstitute_1F_OnTransition
	.byte 0


Route119_WeatherInstitute_1F_Text_Grunt1Intro::
# 6 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "The BOSS got interested in the\n"
	.string "research they have going here,\l"
	.string "so he sent us out.\p"
	.string "You quit meddling!$"

Route119_WeatherInstitute_1F_Text_Grunt1Defeat::
# 10 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Blast it… Blasted by a kid…$"

Route119_WeatherInstitute_1F_Text_Grunt1PostBattle::
# 14 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Our BOSS knows everything.\p"
	.string "But I'm just a GRUNT. What would I know\n"
	.string "about what he's thinking?$"

Route119_WeatherInstitute_1F_Text_Grunt4Intro::
# 18 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Huh? What's a kid doing here?$"

Route119_WeatherInstitute_1F_Text_Grunt4Defeat::
# 22 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Huh? I lost?!$"

Route119_WeatherInstitute_1F_Text_Grunt4PostBattle::
# 26 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Oh, no… I'll catch an earful for losing\n"
	.string "to a kid…\p"
	.string "I should just take a nap in the bed…$"

Route119_WeatherInstitute_1F_Text_EveryoneWentUpstairs::
# 30 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "While I was sleeping, everyone went\n"
	.string "upstairs!$"

Route119_WeatherInstitute_1F_Text_WowYoureStrong::
# 34 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Wow, you're really strong!\p"
	.string "I wish I could be a POKéMON TRAINER like\n"
	.string "you!$"

Route119_WeatherInstitute_1F_Text_ProfStudyingRain::
# 38 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "The PROFESSOR loves rain. That's a fact.\p"
	.string "But if it keeps raining, people will be in\n"
	.string "trouble. That's another fact.\p"
	.string "And thus, the PROFESSOR is studying if\n"
	.string "the rain can be put to good use.$"

Route119_WeatherInstitute_1F_Text_NoticingAbnormalWeather::
# 42 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "On the 2nd floor of the INSTITUTE, we\n"
	.string "study the weather patterns over\l"
	.string "the HOENN region.\p"
	.string "We've been noticing temporary and\n"
	.string "isolated cases of droughts and\l"
	.string "heavy rain lately…$"

Route119_WeatherInstitute_1F_Text_WhatWereAquasUpTo::
# 46 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "Hello! We've been saved by your actions!\p"
	.string "What I don't understand is what on\n"
	.string "earth the AQUAS were up to.$"

Route119_WeatherInstitute_1F_Text_TakeRestInBed::
# 50 "data/maps/Route119_WeatherInstitute_1F/scripts.pory"
	.string "There's a bed… Let's take a rest.$"
