LilycoveCity_MoveDeletersHouse_MapScripts::
	.byte 0


LilycoveCity_MoveDeletersHouse_MapScripts::
	return


LilycoveCity_MoveDeletersHouse_Text_ICanMakeMonForgetMove::
# 8 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Uh… Oh, yes, I'm the MOVE DELETER.\p"
	.string "I can make POKéMON forget their moves.\p"
	.string "Would you like me to do that?$"

LilycoveCity_MoveDeletersHouse_Text_WhichMonShouldForget::
# 12 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Which POKéMON should forget a move?$"

LilycoveCity_MoveDeletersHouse_Text_WhichMoveShouldBeForgotten::
# 16 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Which move should be forgotten?$"

LilycoveCity_MoveDeletersHouse_Text_MonOnlyKnowsOneMove::
# 20 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "{STR_VAR_1} knows only one move so\n"
	.string "it can't be forgotten…$"

LilycoveCity_MoveDeletersHouse_Text_MonsMoveShouldBeForgotten::
# 24 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
	.string "That move should be forgotten?$"

LilycoveCity_MoveDeletersHouse_Text_MonHasForgottenMove::
# 28 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "It worked to perfection!\p"
	.string "{STR_VAR_1} has forgotten\n"
	.string "{STR_VAR_2} completely.$"

LilycoveCity_MoveDeletersHouse_Text_ComeAgain::
# 32 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Come again if there are moves that need\n"
	.string "to be forgotten.$"

LilycoveCity_MoveDeletersHouse_Text_EggCantForgetMoves::
# 36 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "What? No EGG should know any moves.$"

LilycoveCity_MoveDeletersHouse_Text_CantForgetSurf::
# 40 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Hm!\p"
	.string "Your {STR_VAR_1} doesn't seem\n"
	.string "willing to forget SURF.$"
