LilycoveCity_MoveDeletersHouse_MapScripts::
	.byte 0


LilycoveCity_MoveDeletersHouse_EventScript_MoveDeleter::
# 5 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	msgbox LilycoveCity_MoveDeletersHouse_Text_ICanMakeMonForgetMove, MSGBOX_YESNO
	end


LilycoveCity_MoveDeletersHouse_Text_EggCantForgetMoves::
# 9 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "What?\n"
	.string "No EGG should know any moves.$"

LilycoveCity_MoveDeletersHouse_Text_ICanMakeMonForgetMove::
# 13 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Uh…\n"
	.string "Oh, yes, I'm the MOVE DELETER.\p"
	.string "I can make POKéMON forget their moves.\p"
	.string "Would you like me to do that?$"

LilycoveCity_MoveDeletersHouse_Text_WhichMonShouldForget::
# 17 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Which POKéMON should forget a move?$"

LilycoveCity_MoveDeletersHouse_Text_MonOnlyKnowsOneMove::
# 21 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "{STR_VAR_1} knows only one move\n"
	.string "so it can't be forgotten…$"

LilycoveCity_MoveDeletersHouse_Text_CantForgetSurf::
# 25 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Hm!\p"
	.string "Your {STR_VAR_1} doesn't seem\n"
	.string "willing\n"
	.string "to forget SURF.$"

LilycoveCity_MoveDeletersHouse_Text_ComeAgain::
# 29 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Come again if there are moves that\n"
	.string "need to be forgotten.$"
