LilycoveCity_MoveDeletersHouse_MapScripts::
	.byte 0


LilycoveCity_MoveDeletersHouse_Text_ICanMakeMonForgetMove::
# 5 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Uh Oh, yes, I'm the MOVE DELETER.\p"
	.string "I can make POKMON forget their moves.\p"
	.string "Would you like me to do that?$"

LilycoveCity_MoveDeletersHouse_Text_WhichMonShouldForget::
# 9 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Which POKMON should forget a move?$"

LilycoveCity_MoveDeletersHouse_Text_WhichMoveShouldBeForgotten::
# 13 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Which move should be forgotten?$"

LilycoveCity_MoveDeletersHouse_Text_MonOnlyKnowsOneMove::
# 17 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "{STR_VAR_1} knows only one move so\n"
	.string "it can't be forgotten$"

LilycoveCity_MoveDeletersHouse_Text_MonsMoveShouldBeForgotten::
# 21 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Hm! {STR_VAR_1}'s {STR_VAR_2}?\n"
	.string "That move should be forgotten?$"

LilycoveCity_MoveDeletersHouse_Text_MonHasForgottenMove::
# 25 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "It worked to perfection!\p"
	.string "{STR_VAR_1} has forgotten\n"
	.string "{STR_VAR_2} completely.$"

LilycoveCity_MoveDeletersHouse_Text_ComeAgain::
# 29 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Come again if there are moves that need\n"
	.string "to be forgotten.$"

LilycoveCity_MoveDeletersHouse_Text_EggCantForgetMoves::
# 33 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "What? No EGG should know any moves.$"

LilycoveCity_MoveDeletersHouse_Text_CantForgetSurf::
# 37 "data/maps/LilycoveCity_MoveDeletersHouse/scripts.pory"
	.string "Hm!\p"
	.string "Your {STR_VAR_1} doesn't seem\n"
	.string "willing to forget SURF.$"
