FiveIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/FiveIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FiveIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/FiveIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


FiveIsland_PokemonCenter_1F_Text_OnMyWayToPrepareMeal::
# 7 "data/maps/FiveIsland_PokemonCenter_1F/scripts.pory"
	.string "I'm on my way to prepare a meal for a\n"
	.string "certain high-society person.$"

FiveIsland_PokemonCenter_1F_Text_YoureOnQuestToCatchEveryMon::
# 11 "data/maps/FiveIsland_PokemonCenter_1F/scripts.pory"
	.string "You're on a quest to catch every single\n"
	.string "kind of POKéMON?\p"
	.string "…How incredible. Please tell me if you\n"
	.string "catch a strong one!$"
