Route24_MapScripts::
	.byte 0


Route24_Text_JustEarnedFabulousPrize::
# 5 "data/maps/Route24/scripts.pory"
	.string "Congratulations! You beat our five\n"
	.string "contest TRAINERS!\p"
	.string "You just earned a fabulous prize!$"

Route24_Text_ReceivedNuggetFromMysteryTrainer::
# 9 "data/maps/Route24/scripts.pory"
	.string "{PLAYER} received a NUGGET from the\n"
	.string "mystery TRAINER!$"

Route24_Text_YouDontHaveAnyRoom::
# 13 "data/maps/Route24/scripts.pory"
	.string "You don't have any room!$"

Route24_Text_JoinTeamRocket::
# 17 "data/maps/Route24/scripts.pory"
	.string "By the way, how would you like to join\n"
	.string "TEAM ROCKET?\p"
	.string "We're a group of professional criminals\n"
	.string "specializing in POKéMON!\p"
	.string "Want to join?\p"
	.string "Are you sure?\p"
	.string "Come on, join us!\p"
	.string "I'm telling you to join!\p"
	.string "…Okay, you need convincing!\p"
	.string "I'll make you an offer you can't refuse!$"

Route24_Text_RocketDefeat::
# 21 "data/maps/Route24/scripts.pory"
	.string "Arrgh! You are good!$"

Route24_Text_YoudBecomeTopRocketLeader::
# 25 "data/maps/Route24/scripts.pory"
	.string "With your ability, you'd become a top\n"
	.string "leader in TEAM ROCKET.\p"
	.string "Come on, think of the opportunity!\n"
	.string "Don't let this chance go to waste.$"

Route24_Text_ShaneIntro::
# 29 "data/maps/Route24/scripts.pory"
	.string "I saw your feat from the grass!$"

Route24_Text_ShaneDefeat::
# 33 "data/maps/Route24/scripts.pory"
	.string "I thought not!$"

Route24_Text_ShanePostBattle::
# 37 "data/maps/Route24/scripts.pory"
	.string "I hid because the people on the bridge\n"
	.string "frightened me.$"

Route24_Text_EthanIntro::
# 41 "data/maps/Route24/scripts.pory"
	.string "Okay! I'm No. 5! I'll stomp you!$"

Route24_Text_EthanDefeat::
# 45 "data/maps/Route24/scripts.pory"
	.string "Whoa! Too much!$"

Route24_Text_EthanPostBattle::
# 49 "data/maps/Route24/scripts.pory"
	.string "I did my best. I have no regrets!$"

Route24_Text_ReliIntro::
# 53 "data/maps/Route24/scripts.pory"
	.string "I'm No. 4! Getting tired?$"

Route24_Text_ReliDefeat::
# 57 "data/maps/Route24/scripts.pory"
	.string "I lost, too!$"

Route24_Text_ReliPostBattle::
# 61 "data/maps/Route24/scripts.pory"
	.string "I did my best, so I've no regrets!$"

Route24_Text_TimmyIntro::
# 65 "data/maps/Route24/scripts.pory"
	.string "Here's No. 3! I won't be easy!$"

Route24_Text_TimmyDefeat::
# 69 "data/maps/Route24/scripts.pory"
	.string "Ow! Stomped flat!$"

Route24_Text_TimmyPostBattle::
# 73 "data/maps/Route24/scripts.pory"
	.string "I did my best. I have no regrets!$"

Route24_Text_AliIntro::
# 77 "data/maps/Route24/scripts.pory"
	.string "I'm second! Now it's serious!$"

Route24_Text_AliDefeat::
# 81 "data/maps/Route24/scripts.pory"
	.string "How could I lose?$"

Route24_Text_AliPostBattle::
# 85 "data/maps/Route24/scripts.pory"
	.string "I did my best. I have no regrets!$"

Route24_Text_CaleIntro::
# 89 "data/maps/Route24/scripts.pory"
	.string "People call this the NUGGET BRIDGE!\p"
	.string "Beat us five TRAINERS and win a\n"
	.string "fabulous prize!\p"
	.string "Think you got what it takes?$"

Route24_Text_CaleDefeat::
# 93 "data/maps/Route24/scripts.pory"
	.string "Whoo! Good stuff!$"

Route24_Text_CalePostBattle::
# 97 "data/maps/Route24/scripts.pory"
	.string "I did my best. I have no regrets!$"
