ThreeIsland_Mart_MapScripts::
	.byte 0


ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
# 5 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "Is it true?\p"
	.string "CELADON DEPT. STORE is several times\n"
	.string "bigger than this shop?$"

ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
# 9 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "I sometimes buy medicine here.\p"
	.string "But a lot of people heal POKéMON with\n"
	.string "BERRIES from BERRY FOREST.\p"
	.string "After all, BERRIES are free and they\n"
	.string "never run out.$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
# 13 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "Those BIKERS were about to trash this\n"
	.string "POKéMON MART.\p"
	.string "Am I glad they decided to leave!$"
