ThreeIsland_Mart_MapScripts::
	.byte 0


ThreeIsland_Mart_EventScript_BugCatcher::
# 5 "data/maps/ThreeIsland_Mart/scripts.pory"
	msgbox ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest, MSGBOX_NPC
	end


ThreeIsland_Mart_EventScript_Clerk::
	end


ThreeIsland_Mart_EventScript_Picnicker::
# 14 "data/maps/ThreeIsland_Mart/scripts.pory"
	msgbox ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger, MSGBOX_NPC
	end


ThreeIsland_Mart_EventScript_Youngster::
# 19 "data/maps/ThreeIsland_Mart/scripts.pory"
	msgbox ThreeIsland_Mart_Text_BikersWereAboutToTrashMart, MSGBOX_NPC
	end


ThreeIsland_Mart_Text_PeopleHealWithBerriesFromForest::
# 24 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "I sometimes buy medicine here.\p"
	.string "But a lot of people heal POKéMON\n"
	.string "with BERRIES from BERRY FOREST.\p"
	.string "After all, BERRIES are free and\n"
	.string "they never run out.$"

ThreeIsland_Mart_Text_TrueThatCeldadonDeptStoreBigger::
# 28 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "Is it true?\p"
	.string "CELADON DEPT. STORE is several\n"
	.string "times bigger than this shop?$"

ThreeIsland_Mart_Text_BikersWereAboutToTrashMart::
# 32 "data/maps/ThreeIsland_Mart/scripts.pory"
	.string "Those BIKERS were about to trash\n"
	.string "this POKéMON MART.\p"
	.string "Am I glad they decided to leave!$"
