SafariZone_Center_RestHouse_MapScripts::
	.byte 0


SafariZone_Center_RestHouse_EventScript_Sara::
# 5 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	msgbox SafariZone_Center_Text_WhereDidErikGo, MSGBOX_NPC
	end


SafariZone_Center_RestHouse_EventScript_Scientist::
# 10 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	msgbox SafariZone_Center_Text_CatchingMonsAsGifts, MSGBOX_NPC
	end


SafariZone_Center_Text_WhereDidErikGo::
# 15 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	.string "SARA: Where did my boyfriend,\n"
	.string "ERIK, go?$"

SafariZone_Center_Text_CatchingMonsAsGifts::
# 19 "data/maps/SafariZone_Center_RestHouse/scripts.pory"
	.string "I'm catching POKéMON to take home\n"
	.string "as gifts.$"
