ThreeIsland_BondBridge_MapScripts::
	.byte 0

ThreeIsland_BondBridge_EventScript_BerryForestSign::
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_EventScript_BondBridgeSign::
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end

ThreeIsland_BondBridge_Text_BerryForestAhead::
    .string "BERRY FOREST AHEAD$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
    .string "BOND BRIDGE\n"
    .string "Please be quiet when crossing.\p"
    .string "BERRY FOREST AHEAD$"
