ThreeIsland_BondBridge_MapScripts::
	.byte 0


ThreeIsland_BondBridge_Text_NikkiIntro::
# 5 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "The salty tang of the sea It tickles my\n"
	.string "heart.$"

ThreeIsland_BondBridge_Text_NikkiDefeat::
# 9 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Sniff, sniff Something smells\n"
	.string "unpleasant$"

ThreeIsland_BondBridge_Text_NikkiPostBattle::
# 13 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Perhaps that reek is your sweaty\n"
	.string "POKMON's body odor$"

ThreeIsland_BondBridge_Text_VioletIntro::
# 17 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Where are you off to in such a hurry?$"

ThreeIsland_BondBridge_Text_VioletDefeat::
# 21 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "You're raising some wonderful POKMON.$"

ThreeIsland_BondBridge_Text_VioletPostBattle::
# 25 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "If you keep going this way, you'll\n"
	.string "eventually reach BERRY FOREST.$"

ThreeIsland_BondBridge_Text_AmiraIntro::
# 29 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "My mommy said that I can't swim without\n"
	.string "my float ring.$"

ThreeIsland_BondBridge_Text_AmiraDefeat::
# 33 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Waaah! Waaah!$"

ThreeIsland_BondBridge_Text_AmiraPostBattle::
# 37 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "This year, I'm going to finally learn how\n"
	.string "to swim!$"

ThreeIsland_BondBridge_Text_AlexisIntro::
# 41 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Yay, yay! POKMON!$"

ThreeIsland_BondBridge_Text_AlexisDefeat::
# 45 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "What happens now?$"

ThreeIsland_BondBridge_Text_AlexisPostBattle::
# 49 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Did I just win? Or did I lose?$"

ThreeIsland_BondBridge_Text_TishaIntro::
# 53 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Oh, no, don't come here! Please, stay\n"
	.string "away from me!$"

ThreeIsland_BondBridge_Text_TishaDefeat::
# 57 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "Okay, you've won! Now will you please go\n"
	.string "away?$"

ThreeIsland_BondBridge_Text_TishaPostBattle::
# 61 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "A POKMON bit through my swimsuit.\p"
	.string "I can't get out of the water!$"

ThreeIsland_BondBridge_Text_JoyIntro::
# 65 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "JOY: We'll teach you what our favorite\n"
	.string "POKMON is!$"

ThreeIsland_BondBridge_Text_JoyDefeat::
# 69 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "JOY: Ohh MEG!$"

ThreeIsland_BondBridge_Text_JoyPostBattle::
# 73 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "JOY: Wasn't that fun? I hope we can\n"
	.string "battle again!$"

ThreeIsland_BondBridge_Text_JoyNotEnoughMons::
# 77 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "JOY: I really want to battle with MEG.\p"
	.string "One POKMON isn't enough.$"

ThreeIsland_BondBridge_Text_MegIntro::
# 81 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "MEG: We'll show you our favorite POKMON.$"

ThreeIsland_BondBridge_Text_MegDefeat::
# 85 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "MEG: Ohh JOY!$"

ThreeIsland_BondBridge_Text_MegPostBattle::
# 89 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "MEG: JOY, wasn't that fun?$"

ThreeIsland_BondBridge_Text_MegNotEnoughMons::
# 93 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "MEG: I want to battle together with\n"
	.string "JOY.\p"
	.string "One POKMON isn't enough.$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
# 97 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "BERRY FOREST AHEAD$"

ThreeIsland_BondBridge_Text_BondBridgeSign::
# 101 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "BOND BRIDGE Please be quiet when\n"
	.string "crossing.\p"
	.string "BERRY FOREST AHEAD$"
