ThreeIsland_BondBridge_MapScripts::
	.byte 0


ThreeIsland_BondBridge_EventScript_BerryForestSign::
# 5 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	msgbox ThreeIsland_BondBridge_Text_BerryForestAhead, MSGBOX_SIGN
	end


ThreeIsland_BondBridge_EventScript_BondBridgeSign::
# 10 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	msgbox ThreeIsland_BondBridge_Text_BondBridgeSign, MSGBOX_SIGN
	end


ThreeIsland_BondBridge_Text_BondBridgeSign::
# 15 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "BOND BRIDGE Please be quiet when\n"
	.string "crossing.\p"
	.string "BERRY FOREST AHEAD$"

ThreeIsland_BondBridge_Text_BerryForestAhead::
# 19 "data/maps/ThreeIsland_BondBridge/scripts.pory"
	.string "BERRY FOREST AHEAD$"
