OlivineCity_Lighthouse_6F_MapScripts::
	.byte 0


OlivineCity_Lighthouse_6F_EventScript_SmithNPC1::
# 5 "data/maps/OlivineCity_Lighthouse_6F/scripts.pory"
	msgbox OlivineCity_Lighthouse_6F_Text_SmithNPC1, MSGBOX_NPC
	end


OlivineCity_Lighthouse_6F_EventScript_SmithNPC2::
# 14 "data/maps/OlivineCity_Lighthouse_6F/scripts.pory"
	msgbox OlivineCity_Lighthouse_6F_Text_SmithNPC2, MSGBOX_NPC
	end


OlivineCity_Lighthouse_6F_Text_SmithNPC1::
# 9 "data/maps/OlivineCity_Lighthouse_6F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OlivineCity_Lighthouse_6F_Text_SmithNPC2::
# 18 "data/maps/OlivineCity_Lighthouse_6F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
