SootopolisCity_LotadAndSeedotHouse_MapScripts::
	.byte 0


SootopolisCity_LotadAndSeedotHouse_Text_PleaseShowMeBigSeedot::
# 5 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Do you know the POKéMON SEEDOT? It's\n"
	.string "hardly ever seen in SOOTOPOLIS.\p"
	.string "Anyway, I love big SEEDOT. The bigger\n"
	.string "the better.\p"
	.string "But my younger brother, he says that\n"
	.string "LOTAD is bigger.\p"
	.string "That's silly. SEEDOT has to be bigger\n"
	.string "than that!\p"
	.string "Huh? Do you have a SEEDOT with you?\n"
	.string "P-p-please, show me!$"

SootopolisCity_LotadAndSeedotHouse_Text_GoshMightBeBiggerThanLotad::
# 9 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{STR_VAR_2}! Oh, my gosh, this is a\n"
	.string "big one!\p"
	.string "It might even beat the big LOTAD my\n"
	.string "younger brother saw!\p"
	.string "Thanks for showing me. This is my\n"
	.string "thanks!$"

SootopolisCity_LotadAndSeedotHouse_Text_ReceivedPotion1::
# 13 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{PLAYER} received a POTION.$"

SootopolisCity_LotadAndSeedotHouse_Text_BagCrammedFull1::
# 17 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Hunh? Your BAG is crammed full.$"

SootopolisCity_LotadAndSeedotHouse_Text_SeenBiggerSeedot::
# 21 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{STR_VAR_2}, is it?\p"
	.string "Hmm… I've seen a bigger SEEDOT than\n"
	.string "this one.$"

SootopolisCity_LotadAndSeedotHouse_Text_ThatsNotSeedot::
# 25 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Oh, now this is quite something… But\n"
	.string "it's not a SEEDOT!$"

SootopolisCity_LotadAndSeedotHouse_Text_DontHaveBigSeedot::
# 29 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "You don't have a big SEEDOT? That's too\n"
	.string "bad…\p"
	.string "If you get a big SEEDOT, please come\n"
	.string "show me.$"

SootopolisCity_LotadAndSeedotHouse_Text_BiggestSeedotInHistory::
# 33 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "The biggest SEEDOT in history!\n"
	.string "{STR_VAR_2}'s {STR_VAR_3} giant!\p"
	.string "A SEEDOT bigger than a LOTAD always\n"
	.string "wanted!$"

SootopolisCity_LotadAndSeedotHouse_Text_PleaseShowMeBigLotad::
# 37 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Do you know the POKéMON LOTAD? It's\n"
	.string "rarely seen in SOOTOPOLIS.\p"
	.string "I love, I mean love, big LOTAD!\p"
	.string "My big brother says that SEEDOT is\n"
	.string "bigger.\p"
	.string "But that's wrong! Everyone knows that\n"
	.string "LOTAD is a lot bigger.\p"
	.string "Hunh? Do you have a LOTAD? P-p-please\n"
	.string "show me!$"

SootopolisCity_LotadAndSeedotHouse_Text_WowMightBeBiggerThanSeedot::
# 41 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{STR_VAR_2}! Wow, that is big!\p"
	.string "It might be even bigger than the huge\n"
	.string "SEEDOT my big brother saw.\p"
	.string "Thanks for showing me! This is my\n"
	.string "thanks!$"

SootopolisCity_LotadAndSeedotHouse_Text_ReceivedPotion2::
# 45 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{PLAYER} received a POTION.$"

SootopolisCity_LotadAndSeedotHouse_Text_BagCrammedFull2::
# 49 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Hunh? Your BAG is crammed full.$"

SootopolisCity_LotadAndSeedotHouse_Text_SeenBiggerLotad::
# 53 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "{STR_VAR_2}?\p"
	.string "Hmm… I've seen a bigger LOTAD than this\n"
	.string "one here.$"

SootopolisCity_LotadAndSeedotHouse_Text_ThatsNotLotad::
# 57 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Well, isn't this something! But it's no\n"
	.string "LOTAD!$"

SootopolisCity_LotadAndSeedotHouse_Text_DontHaveBigLotad::
# 61 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "Don't you have a big LOTAD? How\n"
	.string "disappointing…\p"
	.string "If you get a big LOTAD, please come\n"
	.string "show me!$"

SootopolisCity_LotadAndSeedotHouse_Text_BiggestLotadInHistory::
# 65 "data/maps/SootopolisCity_LotadAndSeedotHouse/scripts.pory"
	.string "The biggest LOTAD in history!\n"
	.string "{STR_VAR_2}'s {STR_VAR_3}\l"
	.string "colossus!\p"
	.string "A LOTAD bigger than a SEEDOT always\n"
	.string "wanted!$"
