FiveIsland_ResortGorgeous_MapScripts::
# 2 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FiveIsland_ResortGorgeous_OnWarp
# 3 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FiveIsland_ResortGorgeous_OnFrame
	.byte 0


FiveIsland_ResortGorgeous_Text_DaisyIntro::
# 7 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "With these hands, I will create my\n"
	.string "victory!$"

FiveIsland_ResortGorgeous_Text_DaisyDefeat::
# 11 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "The shame of this I'm red-faced$"

FiveIsland_ResortGorgeous_Text_DaisyPostBattle::
# 15 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Uh-oh, my paint tubes have scattered\n"
	.string "everywhere!$"

FiveIsland_ResortGorgeous_Text_CelinaIntro::
# 19 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Excuse me! I'm trying to paint.\l"
	.string "Please keep out of my sight!$"

FiveIsland_ResortGorgeous_Text_CelinaDefeat::
# 23 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "This loss I feel like I'm whiting out$"

FiveIsland_ResortGorgeous_Text_CelinaPostBattle::
# 27 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "GILLIAN? Please tilt your head slightly\l"
	.string "There! That's the look I want!$"

FiveIsland_ResortGorgeous_Text_RaynaIntro::
# 31 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Hmm The angle, it is not quite there$"

FiveIsland_ResortGorgeous_Text_RaynaDefeat::
# 35 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Oh My feelings, they are blue$"

FiveIsland_ResortGorgeous_Text_RaynaPostBattle::
# 39 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "The sky and the sea They are so fickle.\p"
	.string "Their changing expressions make them\n"
	.string "difficult to capture.$"

FiveIsland_ResortGorgeous_Text_JackiIntro::
# 43 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "I am visiting my friend's retreat, if you\n"
	.string "must know.$"

FiveIsland_ResortGorgeous_Text_JackiDefeat::
# 47 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Oh, my, so strong.$"

FiveIsland_ResortGorgeous_Text_JackiPostBattle::
# 51 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "I find it pleasurable to leisurely\n"
	.string "battle in the gentle sea breeze.$"

FiveIsland_ResortGorgeous_Text_GillianIntro::
# 55 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "I'm thinking of having a pool made\n"
	.string "specially for POKMON.$"

FiveIsland_ResortGorgeous_Text_GillianDefeat::
# 59 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Oh, my goodness gracious!$"

FiveIsland_ResortGorgeous_Text_GillianPostBattle::
# 63 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "A pool would be nice, but I must say, a\n"
	.string "sun-room may be sublime.$"

FiveIsland_ResortGorgeous_Text_DestinIntro::
# 67 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "I'm a good runner. I'm really fast!$"

FiveIsland_ResortGorgeous_Text_DestinDefeat::
# 71 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Oops! I rushed things!$"

FiveIsland_ResortGorgeous_Text_DestinPostBattle::
# 75 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "When I run with the wind, it feels like I\n"
	.string "could fly!$"

FiveIsland_ResortGorgeous_Text_TobyIntro::
# 79 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "I say, this marine life here at this\n"
	.string "resort agrees with me.$"

FiveIsland_ResortGorgeous_Text_TobyDefeat::
# 83 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "That's a shocker! You must be joking.$"

FiveIsland_ResortGorgeous_Text_TobyPostBattle::
# 87 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "Getting so serious over this How\n"
	.string "nonsensical.$"

FiveIsland_ResortGorgeous_Text_SelphyThanksYouMayGoNow::
# 91 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "SELPHY: Thank you.\p"
	.string "You may go now.$"

FiveIsland_ResortGorgeous_Text_SelphysHouse::
# 95 "data/maps/FiveIsland_ResortGorgeous/scripts.pory"
	.string "SELPHY'S HOUSE$"
