KantoSafariZone_SecretHouse_MapScripts::
	.byte 0


KantoSafariZone_SecretHouse_EventScript_SmithNPC1::
# 5 "data/maps/KantoSafariZone_SecretHouse/scripts.pory"
	msgbox KantoSafariZone_SecretHouse_Text_SmithNPC1, MSGBOX_NPC
	end


KantoSafariZone_SecretHouse_EventScript_SmithNPC2::
# 14 "data/maps/KantoSafariZone_SecretHouse/scripts.pory"
	msgbox KantoSafariZone_SecretHouse_Text_SmithNPC2, MSGBOX_NPC
	end


KantoSafariZone_SecretHouse_Text_SmithNPC1::
# 9 "data/maps/KantoSafariZone_SecretHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

KantoSafariZone_SecretHouse_Text_SmithNPC2::
# 18 "data/maps/KantoSafariZone_SecretHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
