Route121_MapScripts::
	.byte 0


Route121_MapScripts::
	return


Route121_Text_OkayMoveOutToMtPyre::
# 8 "data/maps/Route121/scripts.pory"
	.string "Okay! We're to move out to MT. PYRE!$"

Route121_Text_AheadLoomsMtPyre::
# 12 "data/maps/Route121/scripts.pory"
	.string "Ahead looms MT. PYRE…\p"
	.string "It is a natural monument to the spirits\n"
	.string "of departed POKéMON…$"

Route121_Text_MtPyrePierSign::
# 16 "data/maps/Route121/scripts.pory"
	.string "MT. PYRE PIER\p"
	.string "…The sign is old and worn out. The words\n"
	.string "are barely legible…$"

Route121_Text_SafariZoneSign::
# 20 "data/maps/Route121/scripts.pory"
	.string "“Filled with rare POKéMON!” SAFARI ZONE$"
