BattleFrontier_BattleArenaCorridor_MapScripts::
# 2 "data/maps/BattleFrontier_BattleArenaCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleArenaCorridor_OnFrame
	.byte 0


BattleFrontier_BattleArenaCorridor_MapScripts::
# 6 "data/maps/BattleFrontier_BattleArenaCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleArenaCorridor_OnFrame
	return


BattleFrontier_BattleArenaCorridor_Text_PleaseStepIn::
# 10 "data/maps/BattleFrontier_BattleArenaCorridor/scripts.pory"
	.string "Your battles shall be waged in the next\n"
	.string "room. Please step in!$"
