PetalburgCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


PetalburgCity_PokemonCenter_1F_Text_PCStorageSystem::
# 7 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "That PC-based POKMON Storage System\p"
	.string "Whoever made it must be some kind of a\n"
	.string "scientific wizard!$"

PetalburgCity_PokemonCenter_1F_Text_OranBerryRegainedHP::
# 11 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "When my POKMON ate an ORAN BERRY, it\n"
	.string "regained HP!$"

PetalburgCity_PokemonCenter_1F_Text_ManyTypesOfPokemon::
# 15 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "There are many types of POKMON.\p"
	.string "All types have their strengths and\n"
	.string "weaknesses against other types.\p"
	.string "Depending on the types of POKMON, a\n"
	.string "battle could be easy or hard.$"

PetalburgCity_PokemonCenter_1F_Text_TreeckoIsGrassType::
# 19 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "For example, your TREECKO is a GRASS\n"
	.string "type.\p"
	.string "It's strong against the WATER and\n"
	.string "GROUND types.\p"
	.string "But, it's weak against FIRE-type\n"
	.string "POKMON.$"

PetalburgCity_PokemonCenter_1F_Text_TorchicIsFireType::
# 23 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "For example, your TORCHIC is a FIRE\n"
	.string "type.\p"
	.string "It's strong against the GRASS and BUG\n"
	.string "types.\p"
	.string "But, it's weak against WATER-type\n"
	.string "POKMON.$"

PetalburgCity_PokemonCenter_1F_Text_MudkipIsWaterType::
# 27 "data/maps/PetalburgCity_PokemonCenter_1F/scripts.pory"
	.string "For example, your MUDKIP is a WATER\n"
	.string "type.\p"
	.string "It's strong against the FIRE type.\p"
	.string "But, it's weak against GRASS-type and\n"
	.string "ELECTRIC-type POKMON.$"
