Route18_EastEntrance_2F_MapScripts::
	.byte 0


Route18_EastEntrance_2F_Text_PalletTownInWest::
# 5 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "PALLET TOWN is in the west.$"

Route18_EastEntrance_2F_Text_PeopleSwimming::
# 9 "data/maps/Route18_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "There are people swimming.$"
