CeruleanCity_Mart_MapScripts::
	.byte 0


CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
# 5 "data/maps/CeruleanCity_Mart/scripts.pory"
	.string "REPEL not only keeps bugs away, it also\n"
	.string "works on weak POKMON.\p"
	.string "Put your strongest POKMON at the left\n"
	.string "of the POKMON LIST.\p"
	.string "If your first POKMON is strong, REPEL's\n"
	.string "effect is boosted.$"

CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
# 9 "data/maps/CeruleanCity_Mart/scripts.pory"
	.string "Do you know about RARE CANDY? They\n"
	.string "don't sell it in shops.\p"
	.string "I think it makes POKMON grow very\n"
	.string "quickly all of a sudden.$"
