CeruleanCity_Mart_MapScripts::
	.byte 0


CeruleanCity_Mart_EventScript_Clerk::
	end


CeruleanCity_Mart_EventScript_Woman::
# 9 "data/maps/CeruleanCity_Mart/scripts.pory"
	msgbox CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy, MSGBOX_NPC
	end


CeruleanCity_Mart_EventScript_Youngster::
# 14 "data/maps/CeruleanCity_Mart/scripts.pory"
	msgbox CeruleanCity_Mart_Text_RepelWorksOnWeakMons, MSGBOX_NPC
	end


CeruleanCity_Mart_Text_DoYouKnowAboutRareCandy::
# 19 "data/maps/CeruleanCity_Mart/scripts.pory"
	.string "Do you know about RARE CANDY?\n"
	.string "They don't sell it in shops.\p"
	.string "I think it makes POKéMON grow\n"
	.string "very quickly all of a sudden.$"

CeruleanCity_Mart_Text_RepelWorksOnWeakMons::
# 23 "data/maps/CeruleanCity_Mart/scripts.pory"
	.string "REPEL not only keeps bugs away,\n"
	.string "it also works on weak POKéMON.\p"
	.string "Put your strongest POKéMON at the\n"
	.string "left of the POKéMON LIST.\p"
	.string "If your first POKéMON is strong,\n"
	.string "REPEL's effect is boosted.$"
