BattleFrontier_Lounge7_MapScripts::
	.byte 0


BattleFrontier_Lounge7_Text_LeftTutorIntro::
# 5 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Buhahaha!\p"
	.string "You couldn't tell it from looking now,\n"
	.string "but I used to be one tough TRAINER.\p"
	.string "I had a reputation as the toughest\n"
	.string "BEAUTY around, I tell you!\p"
	.string "\p"
	.string "What is it now? You don't believe me.\p"
	.string "I'm not like that blowhard woman over\n"
	.string "there. I'm actually talented!\p"
	.string "Let me prove it to you. I can teach your\n"
	.string "POKMON special and\l"
	.string "yet cute moves.\p"
	.string "But my lessons don't come free. How\n"
	.string "about paying for the moves I teach\l"
	.string "with a wee bit of Battle Points?$"

BattleFrontier_Lounge7_Text_LeftTutorWelcomeBack::
# 9 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Buhahaha!\p"
	.string "Are you back to learn special and yet\n"
	.string "cute POKMON moves?$"

BattleFrontier_Lounge7_Text_TeachWhichMove::
# 13 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Fine, fine, look here! Which move should\n"
	.string "I teach?$"

BattleFrontier_Lounge7_Text_MoveWillBeXBattlePoints::
# 17 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "The move {STR_VAR_1}, is it? That\n"
	.string "will be {STR_VAR_2} Battle Points,\l"
	.string "okay?$"

BattleFrontier_Lounge7_Text_TeachMoveToWhichMon::
# 21 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Fine, fine, now pick the POKMON I should\n"
	.string "teach the move to.$"

BattleFrontier_Lounge7_Text_HaventGotEnoughPoints::
# 25 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "What the You haven't got enough Battle\n"
	.string "Points!$"

BattleFrontier_Lounge7_Text_IllTakeBattlePoints::
# 29 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Do you see how skilled I am now? I'll\n"
	.string "take your Battle Points, thanks!$"

BattleFrontier_Lounge7_Text_YouDontWantTo::
# 33 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "What's that? You don't want to\p"
	.string "If you want to see how skilled I am, you\n"
	.string "come see me anytime!$"

BattleFrontier_Lounge7_Text_RightTutorIntro::
# 37 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Ihihihi!\p"
	.string "I know it's hard to see now, but I used\n"
	.string "to be one fantastic TRAINER.\p"
	.string "I had a reputation as the most\n"
	.string "invincible SWIMMER around, I tell you!\p"
	.string "\p"
	.string "What's wrong? You don't believe me.\p"
	.string "I'm not like that buffoonish woman over\n"
	.string "there. I'm actually experienced!\p"
	.string "I can prove it to you. I can teach your\n"
	.string "POKMON hard and\l"
	.string "yet pretty moves.\p"
	.string "But my lessons don't come free. How\n"
	.string "about paying for the moves I teach\l"
	.string "with a wee bit of Battle Points?$"

BattleFrontier_Lounge7_Text_RightTutorWelcomeBack::
# 41 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Ihihihi!\p"
	.string "Have you come to learn hard and yet\n"
	.string "pretty POKMON moves?$"

BattleFrontier_Lounge7_Text_ThinkLadiesDontGetAlong::
# 45 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Those ladies, the way they bad-mouth\n"
	.string "each other, you probably think that\l"
	.string "they don't get along.\p"
	.string "But if that were true, they wouldn't\n"
	.string "stay out here together, would they?$"

BattleFrontier_Lounge7_Text_LadiesWereStrongAndBeautiful::
# 49 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "When I was just a wee YOUNGSTER, those\n"
	.string "ladies were strong and beautiful.\p"
	.string "They were idols among us TRAINERS.\p"
	.string "Even now, age hasn't dulled their\n"
	.string "abilities.\p"
	.string "In fact, their POKMON moves have grown\n"
	.string "even more polished.\p"
	.string "But For some reason, I can't help but\n"
	.string "feel this\p"
	.string "Time is so cruel$"

BattleFrontier_Lounge7_Text_SoftboiledDesc::
# 53 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Recovers up to half the user's maximum\n"
	.string "HP.$"

BattleFrontier_Lounge7_Text_SeismicTossDesc::
# 57 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Inflicts damage identical to the user's\n"
	.string "level.$"

BattleFrontier_Lounge7_Text_DreamEaterDesc::
# 61 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Recovers half the damage inflicted on a\n"
	.string "sleeping foe.$"

BattleFrontier_Lounge7_Text_MegaPunchDesc::
# 65 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A strong punch thrown with incredible\n"
	.string "power.$"

BattleFrontier_Lounge7_Text_MegaKickDesc::
# 69 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "An extremely powerful kick with intense\n"
	.string "force.$"

BattleFrontier_Lounge7_Text_BodySlamDesc::
# 73 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A full-body slam that may cause\n"
	.string "paralysis.$"

BattleFrontier_Lounge7_Text_RockSlideDesc::
# 77 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Large boulders are hurled. May cause\n"
	.string "flinching.$"

BattleFrontier_Lounge7_Text_CounterDesc::
# 81 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Retaliates any physical hit with double\n"
	.string "the power.$"

BattleFrontier_Lounge7_Text_ThunderWaveDesc::
# 85 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A weak jolt of electricity that\n"
	.string "paralyzes the foe.$"

BattleFrontier_Lounge7_Text_SwordsDanceDesc::
# 89 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A fighting dance that sharply raises\n"
	.string "ATTACK.$"

BattleFrontier_Lounge7_Text_DefenseCurlDesc::
# 93 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Curls up to con- ceal weak spots and\n"
	.string "raise DEFENSE.$"

BattleFrontier_Lounge7_Text_SnoreDesc::
# 97 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A loud attack that can be used only\n"
	.string "while asleep.$"

BattleFrontier_Lounge7_Text_MudSlapDesc::
# 101 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Hurls mud in the foe's face to re- duce\n"
	.string "its accuracy.$"

BattleFrontier_Lounge7_Text_SwiftDesc::
# 105 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Sprays star- shaped rays that never\n"
	.string "miss.$"

BattleFrontier_Lounge7_Text_IcyWindDesc::
# 109 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A chilling attack that lowers the foe's\n"
	.string "SPEED.$"

BattleFrontier_Lounge7_Text_EndureDesc::
# 113 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Endures any at- tack for 1 turn,\n"
	.string "leaving 1HP.$"

BattleFrontier_Lounge7_Text_PsychUpDesc::
# 117 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "Copies the foe's effect(s) and gives to\n"
	.string "the user.$"

BattleFrontier_Lounge7_Text_IcePunchDesc::
# 121 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "An icy punch that may freeze the foe.$"

BattleFrontier_Lounge7_Text_ThunderPunchDesc::
# 125 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "An electrified punch that may paralyze\n"
	.string "the foe.$"

BattleFrontier_Lounge7_Text_FirePunchDesc::
# 129 "data/maps/BattleFrontier_Lounge7/scripts.pory"
	.string "A fiery punch that may burn the foe.$"
