LavaridgeTown_House_MapScripts::
	.byte 0


LavaridgeTown_House_MapScripts::
	return


LavaridgeTown_House_Text_WifeWarmingEggInHotSprings::
# 8 "data/maps/LavaridgeTown_House/scripts.pory"
	.string "My wife's warming an EGG in the hot\n"
	.string "springs. This is what she told me.\p"
	.string "She left two POKéMON with the DAY CARE.\n"
	.string "And they discovered that EGG!$"

LavaridgeTown_House_Text_Zigzagoon::
# 12 "data/maps/LavaridgeTown_House/scripts.pory"
	.string "ZIGZAGOON: Pshoo!$"
