Route11_MapScripts::
	.byte 0


Route11_Text_HugoIntro::
# 5 "data/maps/Route11/scripts.pory"
	.string "Win, lose, or draw!$"

Route11_Text_HugoDefeat::
# 9 "data/maps/Route11/scripts.pory"
	.string "Atcha! Didn't go my way!$"

Route11_Text_HugoPostBattle::
# 13 "data/maps/Route11/scripts.pory"
	.string "POKéMON is life! And to live is to play\n"
	.string "games!$"

Route11_Text_JasperIntro::
# 17 "data/maps/Route11/scripts.pory"
	.string "Competition! I can't get enough!$"

Route11_Text_JasperDefeat::
# 21 "data/maps/Route11/scripts.pory"
	.string "I had a chance!$"

Route11_Text_JasperPostBattle::
# 25 "data/maps/Route11/scripts.pory"
	.string "You can't be a coward in the world of\n"
	.string "POKéMON!$"

Route11_Text_EddieIntro::
# 29 "data/maps/Route11/scripts.pory"
	.string "Let's go, but don't cheat!$"

Route11_Text_EddieDefeat::
# 33 "data/maps/Route11/scripts.pory"
	.string "Huh? That's not right!$"

Route11_Text_EddiePostBattle::
# 37 "data/maps/Route11/scripts.pory"
	.string "I did my best. I have no regrets.$"

Route11_Text_BraxtonIntro::
# 41 "data/maps/Route11/scripts.pory"
	.string "Careful! I'm laying down some cables!$"

Route11_Text_BraxtonDefeat::
# 45 "data/maps/Route11/scripts.pory"
	.string "That was electric!$"

Route11_Text_BraxtonPostBattle::
# 49 "data/maps/Route11/scripts.pory"
	.string "Spread the word to save energy!$"

Route11_Text_DillonIntro::
# 53 "data/maps/Route11/scripts.pory"
	.string "I just became a TRAINER. But, I think I\n"
	.string "can win.$"

Route11_Text_DillonDefeat::
# 57 "data/maps/Route11/scripts.pory"
	.string "My POKéMON couldn't win… Haven't they\n"
	.string "grown enough?$"

Route11_Text_DillonPostBattle::
# 61 "data/maps/Route11/scripts.pory"
	.string "What now? Leave me alone!$"

Route11_Text_DirkIntro::
# 65 "data/maps/Route11/scripts.pory"
	.string "Fwahaha! I have never lost!$"

Route11_Text_DirkDefeat::
# 69 "data/maps/Route11/scripts.pory"
	.string "My first loss!$"

Route11_Text_DirkPostBattle::
# 73 "data/maps/Route11/scripts.pory"
	.string "You were just lucky, that's all.$"

Route11_Text_DarianIntro::
# 77 "data/maps/Route11/scripts.pory"
	.string "I have never won before…$"

Route11_Text_DarianDefeat::
# 81 "data/maps/Route11/scripts.pory"
	.string "I saw this coming…$"

Route11_Text_DarianPostBattle::
# 85 "data/maps/Route11/scripts.pory"
	.string "I was unlucky, as always.$"

Route11_Text_YasuIntro::
# 89 "data/maps/Route11/scripts.pory"
	.string "I'm the best in my class. I train every\n"
	.string "morning.$"

Route11_Text_YasuDefeat::
# 93 "data/maps/Route11/scripts.pory"
	.string "Darn! My POKéMON need to be stronger!$"

Route11_Text_YasuPostBattle::
# 97 "data/maps/Route11/scripts.pory"
	.string "There's a fat POKéMON that comes down\n"
	.string "from the mountains.\p"
	.string "I bet it'd be strong if you can catch it.$"

Route11_Text_BernieIntro::
# 101 "data/maps/Route11/scripts.pory"
	.string "Watch out for live wires!$"

Route11_Text_BernieDefeat::
# 105 "data/maps/Route11/scripts.pory"
	.string "Whoa! You spark plug!$"

Route11_Text_BerniePostBattle::
# 109 "data/maps/Route11/scripts.pory"
	.string "Well, better get back to work.$"

Route11_Text_DaveIntro::
# 113 "data/maps/Route11/scripts.pory"
	.string "I raised my POKéMON carefully. They\n"
	.string "should be ready by now!$"

Route11_Text_DaveDefeat::
# 117 "data/maps/Route11/scripts.pory"
	.string "Bye-bye! Thank you, and good-bye!$"

Route11_Text_DavePostBattle::
# 121 "data/maps/Route11/scripts.pory"
	.string "Tch… I better go find stronger ones!$"

Route11_Text_DiglettsCave::
# 125 "data/maps/Route11/scripts.pory"
	.string "DIGLETT'S CAVE$"
