CeladonCity_House1_MapScripts::
	.byte 0


CeladonCity_House1_Text_SlotsReelInTheDough::
# 5 "data/maps/CeladonCity_House1/scripts.pory"
	.string "Hehehe!\p"
	.string "The slots just reel in the dough,\n"
	.string "big-time!$"

CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
# 9 "data/maps/CeladonCity_House1/scripts.pory"
	.string "CHIEF!\p"
	.string "We just shipped two thousand more\n"
	.string "POKMON as slot prizes\l"
	.string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
# 13 "data/maps/CeladonCity_House1/scripts.pory"
	.string "Don't touch the poster at the GAME\n"
	.string "CORNER!\p"
	.string "There's no secret switch behind it!$"

Text_ItsABuddhistAltar::
# 17 "data/maps/CeladonCity_House1/scripts.pory"
	.string "$"
