CeladonCity_House1_MapScripts::
	.byte 0


CeladonCity_House1_EventScript_Rocket1::
# 5 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_ShippedMonsAsSlotPrizes, MSGBOX_NPC
	end


CeladonCity_House1_EventScript_Rocket2::
# 10 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_DontTouchGameCornerPoster, MSGBOX_NPC
	end


CeladonCity_House1_EventScript_RocketChief::
# 15 "data/maps/CeladonCity_House1/scripts.pory"
	msgbox CeladonCity_House1_Text_SlotsReelInTheDough, MSGBOX_NPC
	end


CeladonCity_House1_Text_ShippedMonsAsSlotPrizes::
# 20 "data/maps/CeladonCity_House1/scripts.pory"
	.string "CHIEF!\p"
	.string "We just shipped two thousand\n"
	.string "more POKéMON as slot prizes\l"
	.string "again today!$"

CeladonCity_House1_Text_DontTouchGameCornerPoster::
# 24 "data/maps/CeladonCity_House1/scripts.pory"
	.string "Don't touch the poster at the GAME\n"
	.string "CORNER!\p"
	.string "There's no secret switch behind it!$"

CeladonCity_House1_Text_SlotsReelInTheDough::
# 28 "data/maps/CeladonCity_House1/scripts.pory"
	.string "Hehehe!\p"
	.string "The slots just reel in the dough,\n"
	.string "big-time!$"
