NavelRock_Summit_MapScripts::
# 2 "data/maps/NavelRock_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, NavelRock_Summit_OnTransition
# 3 "data/maps/NavelRock_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, NavelRock_Summit_OnResume
	.byte 0


NavelRock_Summit_MapScripts::
# 7 "data/maps/NavelRock_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, NavelRock_Summit_OnTransition
# 8 "data/maps/NavelRock_Summit/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, NavelRock_Summit_OnResume
	return

