PokmonLeague_MapScripts::
	.byte 0


PokmonLeague_EventScript_Sign1::
# 6 "data/maps/PokmonLeague/scripts.pory"
	msgbox PokmonLeague_Text_Sign1, MSGBOX_SIGN
	end


PokmonLeague_EventScript_Sign2::
# 15 "data/maps/PokmonLeague/scripts.pory"
	msgbox PokmonLeague_Text_Sign2, MSGBOX_SIGN
	end


PokmonLeague_Text_Sign1::
# 10 "data/maps/PokmonLeague/scripts.pory"
	.string "PokmonLeague Sign 1$"

PokmonLeague_Text_Sign2::
# 19 "data/maps/PokmonLeague/scripts.pory"
	.string "PokmonLeague Sign 2$"
