AzaleaTown_KurtsHouse_MapScripts::
	.byte 0


AzaleaTown_KurtsHouse_EventScript_SmithNPC1::
# 5 "data/maps/AzaleaTown_KurtsHouse/scripts.pory"
	msgbox AzaleaTown_KurtsHouse_Text_SmithNPC1, MSGBOX_NPC
	end


AzaleaTown_KurtsHouse_EventScript_SmithNPC2::
# 14 "data/maps/AzaleaTown_KurtsHouse/scripts.pory"
	msgbox AzaleaTown_KurtsHouse_Text_SmithNPC2, MSGBOX_NPC
	end


AzaleaTown_KurtsHouse_Text_SmithNPC1::
# 9 "data/maps/AzaleaTown_KurtsHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

AzaleaTown_KurtsHouse_Text_SmithNPC2::
# 18 "data/maps/AzaleaTown_KurtsHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
