SixIsland_OutcastIsland_MapScripts::
	.byte 0


SixIsland_OutcastIsland_Text_RocketIntro::
# 5 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "There're no rare POKMON around these\n"
	.string "parts! Not a one!\p"
	.string "That burns me up, man. I'll take it out\n"
	.string "on you!$"

SixIsland_OutcastIsland_Text_RocketDefeat::
# 9 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "Huh?$"

SixIsland_OutcastIsland_Text_RocketPostBattle::
# 13 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "So listen, you haven't seen any rare\n"
	.string "POKMON, have you?$"

SixIsland_OutcastIsland_Text_TylorIntro::
# 17 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "I'm having no luck at all. A battle'd be a\n"
	.string "change of pace!$"

SixIsland_OutcastIsland_Text_TylorDefeat::
# 21 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "Nope, no luck at all$"

SixIsland_OutcastIsland_Text_TylorPostBattle::
# 25 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "I can't very well go home without\n"
	.string "catching something, though.$"

SixIsland_OutcastIsland_Text_MymoIntro::
# 29 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "Gasp Gasp\p"
	.string "I swam here from SIX ISLE PORT in one\n"
	.string "go.$"

SixIsland_OutcastIsland_Text_MymoDefeat::
# 33 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "Gasp Gasp$"

SixIsland_OutcastIsland_Text_MymoPostBattle::
# 37 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "I'm only at the halfway point I'm beat$"

SixIsland_OutcastIsland_Text_NicoleIntro::
# 41 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "It's not so easy sending POKMON out\n"
	.string "while swimming, you know?$"

SixIsland_OutcastIsland_Text_NicoleDefeat::
# 45 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "I didn't lose to you at swimming. This\n"
	.string "doesn't bother me.$"

SixIsland_OutcastIsland_Text_NicolePostBattle::
# 49 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "Are you headed for the island up past\n"
	.string "here?\p"
	.string "I didn't see anything interesting\n"
	.string "there.$"

SixIsland_OutcastIsland_Text_AvaIntro::
# 53 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "AVA: Let's have a two-on-two marine\n"
	.string "battle!$"

SixIsland_OutcastIsland_Text_AvaDefeat::
# 57 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "AVA: Oh, you're amazing! Even better,\n"
	.string "you're on your own!$"

SixIsland_OutcastIsland_Text_AvaPostBattle::
# 61 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "AVA: You know, I do prefer the sea over\n"
	.string "any pool.$"

SixIsland_OutcastIsland_Text_AvaNotEnoughMons::
# 65 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "AVA: You're challenging us to a battle?\p"
	.string "You'll need at least two POKMON if you\n"
	.string "want to do that.$"

SixIsland_OutcastIsland_Text_GebIntro::
# 69 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "GEB: Big Sister, help! Please battle\n"
	.string "with me!$"

SixIsland_OutcastIsland_Text_GebDefeat::
# 73 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "GEB: Wow, Big Sister, this person's\n"
	.string "really good!$"

SixIsland_OutcastIsland_Text_GebPostBattle::
# 77 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "GEB: I'm hanging onto my sister because\n"
	.string "I can't touch the bottom.$"

SixIsland_OutcastIsland_Text_GebNotEnoughMons::
# 81 "data/maps/SixIsland_OutcastIsland/scripts.pory"
	.string "GEB: Please battle against me and my\n"
	.string "sister!\p"
	.string "Oh, you don't have two POKMON?$"
