MtPyre_4F_MapScripts::
	.byte 0


MtPyre_5F_Text_AtsushiIntro::
# 5 "data/maps/MtPyre_4F/scripts.pory"
	.string "Teacher Please watch over my progress!$"

MtPyre_5F_Text_AtsushiDefeat::
# 9 "data/maps/MtPyre_4F/scripts.pory"
	.string "Teacher Please forgive me!$"

MtPyre_5F_Text_AtsushiPostBattle::
# 13 "data/maps/MtPyre_4F/scripts.pory"
	.string "Until I improve, my teacher, who rests\n"
	.string "here, will never find true peace$"
