MtPyre_4F_MapScripts::
	.byte 0


MtPyre_4F_EventScript_Tasha::
	end


MtPyre_5F_Text_AtsushiDefeat::
# 10 "data/maps/MtPyre_4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_5F_Text_AtsushiDefeat$"

MtPyre_5F_Text_AtsushiIntro::
# 14 "data/maps/MtPyre_4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_5F_Text_AtsushiIntro$"

MtPyre_5F_Text_AtsushiPostBattle::
# 18 "data/maps/MtPyre_4F/scripts.pory"
	.string "Placeholder text for\n"
	.string "MtPyre_5F_Text_AtsushiPostBattle$"
