MtPyre_4F_MapScripts::
	.byte 0


MtPyre_4F_MapScripts::
	return


MtPyre_5F_Text_AtsushiIntro::
# 9 "data/maps/MtPyre_4F/scripts.pory"
	.string "Teacher… Please watch over my\n"
	.string "progress!$"

MtPyre_5F_Text_AtsushiDefeat::
# 13 "data/maps/MtPyre_4F/scripts.pory"
	.string "Teacher… Please forgive me!$"

MtPyre_5F_Text_AtsushiPostBattle::
# 17 "data/maps/MtPyre_4F/scripts.pory"
	.string "Until I improve, my teacher, who rests\n"
	.string "here, will never find true peace…$"
