DarkCave_Blackthorn_MapScripts::
	.byte 0


DarkCave_Blackthorn_EventScript_SmithNPC1::
# 5 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC1, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC2::
# 14 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC2, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC3::
# 23 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC3, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC4::
# 32 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC4, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC5::
# 41 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC5, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC6::
# 50 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC6, MSGBOX_NPC
	end


DarkCave_Blackthorn_EventScript_SmithNPC7::
# 59 "data/maps/DarkCave_Blackthorn/scripts.pory"
	msgbox DarkCave_Blackthorn_Text_SmithNPC7, MSGBOX_NPC
	end


DarkCave_Blackthorn_Text_SmithNPC1::
# 9 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

DarkCave_Blackthorn_Text_SmithNPC2::
# 18 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

DarkCave_Blackthorn_Text_SmithNPC3::
# 27 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

DarkCave_Blackthorn_Text_SmithNPC4::
# 36 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

DarkCave_Blackthorn_Text_SmithNPC5::
# 45 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

DarkCave_Blackthorn_Text_SmithNPC6::
# 54 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "It's the question that drives us, Neo.$"

DarkCave_Blackthorn_Text_SmithNPC7::
# 63 "data/maps/DarkCave_Blackthorn/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"
