PetalburgCity_MapScripts::
# 2 "data/maps/PetalburgCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_OnTransition
# 3 "data/maps/PetalburgCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_OnFrame
	.byte 0


PetalburgCity_MapScripts::
# 7 "data/maps/PetalburgCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_OnTransition
# 8 "data/maps/PetalburgCity/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_OnFrame
	return


PetalburgCity_Text_WhereIsWally::
# 12 "data/maps/PetalburgCity/scripts.pory"
	.string "Where has our WALLY gone?\p"
	.string "We have to leave for VERDANTURF TOWN\n"
	.string "very soon…$"

PetalburgCity_Text_AreYouRookieTrainer::
# 16 "data/maps/PetalburgCity/scripts.pory"
	.string "Hiya! Are you maybe… A rookie TRAINER?\p"
	.string "Do you know what POKéMON TRAINERS do\n"
	.string "when they reach a new town?\p"
	.string "They first check what kind of GYM is in\n"
	.string "the town.$"

PetalburgCity_Text_ThisIsPetalburgGym::
# 20 "data/maps/PetalburgCity/scripts.pory"
	.string "See? This is PETALBURG CITY's GYM.$"

PetalburgCity_Text_ThisIsGymSign::
# 24 "data/maps/PetalburgCity/scripts.pory"
	.string "This is the GYM's sign. Look for it\n"
	.string "whenever you're looking for a GYM.$"

PetalburgCity_Text_WaterReflection::
# 28 "data/maps/PetalburgCity/scripts.pory"
	.string "My face is reflected in the water.\p"
	.string "It's a shining grin full of hope…\p"
	.string "Or it could be a look of somber silence\n"
	.string "struggling with fear…\p"
	.string "What do you see reflected in your face?$"

PetalburgCity_Text_FullPartyExplanation::
# 32 "data/maps/PetalburgCity/scripts.pory"
	.string "Let's say you have six POKéMON. If you\n"
	.string "catch another one…\p"
	.string "It is automatically sent to a STORAGE\n"
	.string "BOX over a PC connection.$"

PetalburgCity_Text_GymSign::
# 36 "data/maps/PetalburgCity/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM LEADER:\n"
	.string "NORMAN\l"
	.string "“A man in pursuit of power!”$"

PetalburgCity_Text_CitySign::
# 40 "data/maps/PetalburgCity/scripts.pory"
	.string "PETALBURG CITY “Where people mingle\n"
	.string "with nature.”$"

PetalburgCity_Text_WallyHouseSign::
# 44 "data/maps/PetalburgCity/scripts.pory"
	.string "WALLY'S HOUSE$"

PetalburgCity_Text_AreYouATrainer::
# 48 "data/maps/PetalburgCity/scripts.pory"
	.string "Excuse me!\p"
	.string "Let me guess, from the way you're\n"
	.string "dressed, are you a POKéMON TRAINER?$"

PetalburgCity_Text_WellMaybeNot::
# 52 "data/maps/PetalburgCity/scripts.pory"
	.string "… … … … … …\p"
	.string "Well, maybe not. Your clothes aren't all\n"
	.string "that dirty.\p"
	.string "You're either a rookie TRAINER, or maybe\n"
	.string "you're just an ordinary kid.$"

PetalburgCity_Text_ImLookingForTalentedTrainers::
# 56 "data/maps/PetalburgCity/scripts.pory"
	.string "I'm roaming the land in search of\n"
	.string "talented TRAINERS.\p"
	.string "I'm sorry to have taken your time.$"
