PetalburgCity_MapScripts::
	.byte 0


PetalburgCity_EventScript_Boy::
# 5 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_WaterReflection, MSGBOX_DEFAULT
	end


PetalburgCity_EventScript_CitySign::
# 10 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_CitySign, MSGBOX_SIGN
	end


PetalburgCity_EventScript_Gentleman::
# 15 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_FullPartyExplanation, MSGBOX_NPC
	end


PetalburgCity_EventScript_GymBoy::
# 20 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_AreYouRookieTrainer, MSGBOX_NPC
	end


PetalburgCity_EventScript_GymSign::
# 25 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_GymSign, MSGBOX_SIGN
	end


PetalburgCity_EventScript_Scott0::
	end


PetalburgCity_EventScript_Scott1::
	end


PetalburgCity_EventScript_Scott2::
	end


PetalburgCity_EventScript_Scott3::
	end


PetalburgCity_EventScript_ShowGymToPlayer0::
	end


PetalburgCity_EventScript_ShowGymToPlayer1::
	end


PetalburgCity_EventScript_ShowGymToPlayer2::
	end


PetalburgCity_EventScript_ShowGymToPlayer3::
	end


PetalburgCity_EventScript_WallyHouseSign::
# 62 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_WallyHouseSign, MSGBOX_SIGN
	end


PetalburgCity_EventScript_WallysMom::
# 67 "data/maps/PetalburgCity/scripts.pory"
	msgbox PetalburgCity_Text_WhereIsWally, MSGBOX_NPC
	end


PetalburgCity_Text_CitySign::
# 72 "data/maps/PetalburgCity/scripts.pory"
	.string "PETALBURG CITY “Where people mingle\n"
	.string "with nature.”$"

PetalburgCity_Text_WallyHouseSign::
# 76 "data/maps/PetalburgCity/scripts.pory"
	.string "WALLY'S HOUSE$"

PetalburgCity_Text_GymSign::
# 80 "data/maps/PetalburgCity/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM LEADER:\n"
	.string "NORMAN\l"
	.string "“A man in pursuit of power!”$"

PetalburgCity_Text_WaterReflection::
# 84 "data/maps/PetalburgCity/scripts.pory"
	.string "My face is reflected in the water.\p"
	.string "It's a shining grin full of hope…\p"
	.string "Or it could be a look of somber silence\n"
	.string "struggling with fear…\p"
	.string "What do you see reflected in your face?$"

PetalburgCity_Text_FullPartyExplanation::
# 88 "data/maps/PetalburgCity/scripts.pory"
	.string "Let's say you have six POKéMON.\n"
	.string "If you catch another one…\p"
	.string "It is automatically sent to a STORAGE\n"
	.string "BOX over a PC connection.$"

PetalburgCity_Text_WhereIsWally::
# 92 "data/maps/PetalburgCity/scripts.pory"
	.string "Where has our WALLY gone?\p"
	.string "We have to leave for VERDANTURF TOWN\n"
	.string "very soon…$"

PetalburgCity_Text_AreYouRookieTrainer::
# 96 "data/maps/PetalburgCity/scripts.pory"
	.string "Hiya! Are you maybe…\n"
	.string "A rookie TRAINER?\p"
	.string "Do you know what POKéMON TRAINERS\n"
	.string "do when they reach a new town?\p"
	.string "They first check what kind of GYM\n"
	.string "is in the town.$"
