Route14_MapScripts::
	.byte 0


Route14_Text_CarterIntro::
# 5 "data/maps/Route14/scripts.pory"
	.string "You need to use TMs to teach good\n"
	.string "moves to POKéMON.$"

Route14_Text_CarterDefeat::
# 9 "data/maps/Route14/scripts.pory"
	.string "Not good enough quite yet.$"

Route14_Text_CarterPostBattle::
# 13 "data/maps/Route14/scripts.pory"
	.string "You have some HMs, right? POKéMON can't\n"
	.string "forget those moves easily.$"

Route14_Text_MitchIntro::
# 17 "data/maps/Route14/scripts.pory"
	.string "My bird POKéMON should be ready for\n"
	.string "battle.$"

Route14_Text_MitchDefeat::
# 21 "data/maps/Route14/scripts.pory"
	.string "Not ready yet!$"

Route14_Text_MitchPostBattle::
# 25 "data/maps/Route14/scripts.pory"
	.string "My bird POKéMON need to learn better\n"
	.string "moves.$"

Route14_Text_BeckIntro::
# 29 "data/maps/Route14/scripts.pory"
	.string "They have TMs on sale at the CELADON\n"
	.string "DEPT. STORE.\p"
	.string "TMs aren't really rare, but not many\n"
	.string "people have HMs.$"

Route14_Text_BeckDefeat::
# 33 "data/maps/Route14/scripts.pory"
	.string "Aww, bummer!$"

Route14_Text_BeckPostBattle::
# 37 "data/maps/Route14/scripts.pory"
	.string "Try teaching POKéMON a move that's the\n"
	.string "same type as it.\p"
	.string "That apparently boosts the power of\n"
	.string "the move.$"

Route14_Text_MarlonIntro::
# 41 "data/maps/Route14/scripts.pory"
	.string "Have you taught your bird POKéMON how\n"
	.string "to FLY?\p"
	.string "You'll be able to soar with it into the\n"
	.string "sky!$"

Route14_Text_MarlonDefeat::
# 45 "data/maps/Route14/scripts.pory"
	.string "Shot down in flames!$"

Route14_Text_MarlonPostBattle::
# 49 "data/maps/Route14/scripts.pory"
	.string "Bird POKéMON are my one true love. I\n"
	.string "don't want to raise anything else.$"

Route14_Text_DonaldIntro::
# 53 "data/maps/Route14/scripts.pory"
	.string "Have you heard the legend of the winged\n"
	.string "mirages?$"

Route14_Text_DonaldDefeat::
# 57 "data/maps/Route14/scripts.pory"
	.string "Why? Why'd I lose?$"

Route14_Text_DonaldPostBattle::
# 61 "data/maps/Route14/scripts.pory"
	.string "Well, the winged mirages are the\n"
	.string "legendary bird POKéMON.\p"
	.string "There are three of them: ARTICUNO,\n"
	.string "ZAPDOS, and MOLTRES.$"

Route14_Text_BennyIntro::
# 65 "data/maps/Route14/scripts.pory"
	.string "I'm not into it, but okay. Let's go!$"

Route14_Text_BennyDefeat::
# 69 "data/maps/Route14/scripts.pory"
	.string "I knew it!$"

Route14_Text_BennyPostBattle::
# 73 "data/maps/Route14/scripts.pory"
	.string "Winning, losing… It's insignificant\n"
	.string "under this huge sky.$"

Route14_Text_LukasIntro::
# 77 "data/maps/Route14/scripts.pory"
	.string "C'mon, c'mon. Let's go, let's go, let's go!$"

Route14_Text_LukasDefeat::
# 81 "data/maps/Route14/scripts.pory"
	.string "Arrg! Lost! Get lost!$"

Route14_Text_LukasPostBattle::
# 85 "data/maps/Route14/scripts.pory"
	.string "What, what, what? What do you want\n"
	.string "still?$"

Route14_Text_IsaacIntro::
# 89 "data/maps/Route14/scripts.pory"
	.string "I need to burn some time. Shut up and\n"
	.string "battle.$"

Route14_Text_IsaacDefeat::
# 93 "data/maps/Route14/scripts.pory"
	.string "What? You!?$"

Route14_Text_IsaacPostBattle::
# 97 "data/maps/Route14/scripts.pory"
	.string "Raising POKéMON is a drag, man.$"

Route14_Text_GeraldIntro::
# 101 "data/maps/Route14/scripts.pory"
	.string "We ride out here because of the\n"
	.string "wide-open spaces.$"

Route14_Text_GeraldDefeat::
# 105 "data/maps/Route14/scripts.pory"
	.string "Wipeout!$"

Route14_Text_GeraldPostBattle::
# 109 "data/maps/Route14/scripts.pory"
	.string "It's cool you made your POKéMON so\n"
	.string "strong.\p"
	.string "Might is right! And you know it!$"

Route14_Text_MalikIntro::
# 113 "data/maps/Route14/scripts.pory"
	.string "POKéMON battle? Cool! Rumble!$"

Route14_Text_MalikDefeat::
# 117 "data/maps/Route14/scripts.pory"
	.string "Blown away!$"

Route14_Text_MalikPostBattle::
# 121 "data/maps/Route14/scripts.pory"
	.string "You know who'd win, you and me\n"
	.string "one-on-one!$"

Route14_Text_RouteSign::
# 125 "data/maps/Route14/scripts.pory"
	.string "ROUTE 14 West to FUCHSIA CITY$"

Route14_Text_KiriIntro::
# 129 "data/maps/Route14/scripts.pory"
	.string "KIRI: JAN, let's try really, really hard\n"
	.string "together.$"

Route14_Text_KiriDefeat::
# 133 "data/maps/Route14/scripts.pory"
	.string "KIRI: Whimper… We lost, didn't we?$"

Route14_Text_KiriPostBattle::
# 137 "data/maps/Route14/scripts.pory"
	.string "KIRI: Did we lose because of me?$"

Route14_Text_KiriNotEnoughMons::
# 141 "data/maps/Route14/scripts.pory"
	.string "KIRI: We can battle if you have two\n"
	.string "POKéMON.$"

Route14_Text_JanIntro::
# 145 "data/maps/Route14/scripts.pory"
	.string "JAN: KIRI, here we go! We have to try\n"
	.string "hard!$"

Route14_Text_JanDefeat::
# 149 "data/maps/Route14/scripts.pory"
	.string "JAN: Eeeeh! No fair!$"

Route14_Text_JanPostBattle::
# 153 "data/maps/Route14/scripts.pory"
	.string "JAN: KIRI, don't cry! We'll just try\n"
	.string "harder next time.$"

Route14_Text_JanNotEnoughMons::
# 157 "data/maps/Route14/scripts.pory"
	.string "JAN: You want to battle? You don't have\n"
	.string "enough POKéMON.$"
