SlateportCity_OceanicMuseum_1F_MapScripts::
	.byte 0


SlateportCity_OceanicMuseum_1F_Text_WouldYouLikeToEnter::
# 5 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Welcome to the OCEANIC MUSEUM.\p"
	.string "The entrance fee is ¥50. Would you like\n"
	.string "to enter?$"

SlateportCity_OceanicMuseum_1F_Text_PleaseEnjoyYourself::
# 9 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Please enjoy yourself.$"

SlateportCity_OceanicMuseum_1F_Text_NotEnoughMoney::
# 13 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Oh? I'm sorry, but you don't seem to\n"
	.string "have enough money.$"

SlateportCity_OceanicMuseum_1F_Text_CatchUpWithYourGroup::
# 17 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Oh? You're with that group that went in\n"
	.string "earlier?\p"
	.string "You're the only one who's late. You'd\n"
	.string "better go catch up to them!$"

SlateportCity_OceanicMuseum_1F_Text_AquaExistForGoodOfAll::
# 21 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "We, TEAM AQUA, exist for the good of all!$"

SlateportCity_OceanicMuseum_1F_Text_OurBossIsntHere::
# 25 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "We were told to assemble here, so we did,\n"
	.string "but…\p"
	.string "Our BOSS, the linchpin, isn't here.$"

SlateportCity_OceanicMuseum_1F_Text_WouldStuffHereMakeMeRich::
# 29 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "If I ripped off the stuff here, would it\n"
	.string "make me rich?$"

SlateportCity_OceanicMuseum_1F_Text_CanLearnForNefariousDeeds::
# 33 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "What I learn here, I can put to use on\n"
	.string "nefarious deeds…$"

SlateportCity_OceanicMuseum_1F_Text_RustboroBungled::
# 37 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "If our goons didn't bungle things in\n"
	.string "RUSTBORO, we wouldn't be here!$"

SlateportCity_OceanicMuseum_1F_Text_DidntHaveMoney::
# 41 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "I didn't have ¥50, so it took a long time\n"
	.string "getting by the receptionist.$"

SlateportCity_OceanicMuseum_1F_Text_LearnAboutSeaForBattling::
# 45 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "I want to learn about the sea and use\n"
	.string "that knowledge for battling.$"

SlateportCity_OceanicMuseum_1F_Text_SternIsRoleModel::
# 49 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "I get all giddy and gooey when I see the\n"
	.string "sea!\p"
	.string "For me, CAPT. STERN is the number one\n"
	.string "role model!$"

SlateportCity_OceanicMuseum_1F_Text_MustBePokemonWeDontKnow::
# 53 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "The sea is vast without end, and\n"
	.string "infinitely deep…\p"
	.string "There must be many POKéMON that we\n"
	.string "don't know about.$"

SlateportCity_OceanicMuseum_1F_Text_WantSeaPokemon::
# 57 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "I want a sea POKéMON.\p"
	.string "I think it would feel cool and nice to\n"
	.string "hug.$"

SlateportCity_OceanicMuseum_1F_Text_RememberMeTakeThis::
# 61 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Aiyeeeh! What are you doing here?\p"
	.string "Me? I'm the TEAM AQUA member you\n"
	.string "thumped before, remember?\l"
	.string "Back in RUSTURF TUNNEL?\p"
	.string "Here, take this! You have to forgive me!$"

SlateportCity_OceanicMuseum_1F_Text_HopeINeverSeeYouAgain::
# 65 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "That TM, it suits you more than it does\n"
	.string "me.\p"
	.string "Hope I never see you again! Wahahaha!$"

SlateportCity_OceanicMuseum_1F_Text_YouHaveToTakeThis::
# 69 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "Awww, come on! You have to take this\n"
	.string "and let me go!$"

SlateportCity_OceanicMuseum_1F_Text_WhirlpoolExperiment::
# 73 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "A blue fluid is spiraling inside a glass\n"
	.string "vessel.\p"
	.string "“This is an experiment to create a\n"
	.string "WHIRLPOOL artificially using wind.”$"

SlateportCity_OceanicMuseum_1F_Text_WaterfallExperiment::
# 77 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "A red ball is bobbing up and down inside\n"
	.string "a glass vessel.\p"
	.string "“This is an experiment simulating a\n"
	.string "WATERFALL using the ball's buoyancy.”$"

SlateportCity_OceanicMuseum_1F_Text_OceanSoilDisplay::
# 81 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "It's a sample of soil from the ocean\n"
	.string "floor.\p"
	.string "“Over many years, the remains of\n"
	.string "life-forms settle at the bottom of\l"
	.string "the sea, making sedimentary layers.\p"
	.string "“By analyzing these layers, the ancient\n"
	.string "past is revealed.”$"

SlateportCity_OceanicMuseum_1F_Text_BeachSandDisplay::
# 85 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "It's a sample of beach sand.\p"
	.string "“Stones from mountains are washed\n"
	.string "down by rivers where they are\l"
	.string "chipped and ground down.\p"
	.string "“They are reduced to grains and end up\n"
	.string "as sand on beaches.”$"

SlateportCity_OceanicMuseum_1F_Text_OceanicMinifact1::
# 89 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "“OCEANIC MINIFACT 1 Why is seawater\n"
	.string "blue?\p"
	.string "“Light is composed of many colors.\p"
	.string "“When light passes through water, most\n"
	.string "kinds of light lose color.\p"
	.string "“However, blue light retains its color,\n"
	.string "making the sea appear blue.”$"

SlateportCity_OceanicMuseum_1F_Text_OceanicMinifact2::
# 93 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "“OCEANIC MINIFACT 2 Why is the sea\n"
	.string "salty?\p"
	.string "“Seawater contains dissolved salt in\n"
	.string "the form of sodium and chlorine ions.\p"
	.string "“These ions leech out of rocks and are\n"
	.string "carried out to sea by rain.\p"
	.string "“The concentration of dissolved salt\n"
	.string "makes the sea salty.”$"

SlateportCity_OceanicMuseum_1F_Text_OceanicMinifact3::
# 97 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "“OCEANIC MINIFACT 3 Which is bigger?\n"
	.string "The sea or land?\p"
	.string "“The sea covers about 70% of the\n"
	.string "planet, and the rest is land.\p"
	.string "“The sea is therefore more than twice\n"
	.string "the size of land.”$"

SlateportCity_OceanicMuseum_1F_Text_FossilDisplay::
# 101 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "It's a fossil with wavy ridges on it.\p"
	.string "“Soil on the ocean floor gets scoured\n"
	.string "by the tide.\p"
	.string "“The flowing seawater marks the soil\n"
	.string "with small ridges and valleys.\p"
	.string "“If this soil becomes fossilized, it is\n"
	.string "called a ripple mark.”$"

SlateportCity_OceanicMuseum_1F_Text_DepthMeasuringMachine::
# 105 "data/maps/SlateportCity_OceanicMuseum_1F/scripts.pory"
	.string "A strange machine is rotating under a\n"
	.string "glass dome.\p"
	.string "Maybe it's for measuring the depth of\n"
	.string "something…$"
