ViridianCity_School_MapScripts::
	.byte 0


ViridianCity_School_EventScript_Blackboard::
# 6 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_BlackboardListsStatusProblems, MSGBOX_DEFAULT
	end


ViridianCity_School_EventScript_Lass::
	end


ViridianCity_School_EventScript_Notebook::
# 17 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_NotebookFirstPage, MSGBOX_DEFAULT
# 18 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
# 20 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_NotebookSecondPage, MSGBOX_DEFAULT
# 21 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
# 23 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_NotebookThirdPage, MSGBOX_DEFAULT
# 24 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_TurnThePage, MSGBOX_YESNO
# 26 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_NotebookFourthPage, MSGBOX_DEFAULT
# 30 "data/maps/ViridianCity_School/scripts.pory"
	msgbox ViridianCity_School_Text_HeyDontLookAtMyNotes, MSGBOX_DEFAULT
	end


ViridianCity_School_EventScript_PokemonJournal::
	end


ViridianCity_School_EventScript_Woman::
	end


ViridianCity_School_Text_NotebookSecondPage::
# 44 "data/maps/ViridianCity_School/scripts.pory"
	.string "Second page…\p"
	.string "A healthy POKéMON may be hard to catch,\n"
	.string "so weaken it first.\p"
	.string "Poison, burn, or cause another status\n"
	.string "problem to weaken it.$"

ViridianCity_School_Text_NotebookFourthPage::
# 48 "data/maps/ViridianCity_School/scripts.pory"
	.string "Fourth page…\p"
	.string "The ultimate goal for all POKéMON\n"
	.string "TRAINERS is simple.\p"
	.string "It is to defeat the top eight POKéMON\n"
	.string "GYM LEADERS.\p"
	.string "Do so to earn the right to face…\p"
	.string "The ELITE FOUR of the POKéMON LEAGUE!$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
# 52 "data/maps/ViridianCity_School/scripts.pory"
	.string "GIRL: Hey! Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
# 56 "data/maps/ViridianCity_School/scripts.pory"
	.string "The blackboard lists POKéMON STATUS\n"
	.string "problems during battles.$"

ViridianCity_School_Text_NotebookThirdPage::
# 60 "data/maps/ViridianCity_School/scripts.pory"
	.string "Third page…\p"
	.string "POKéMON TRAINERS seek others to\n"
	.string "engage in POKéMON battles.\p"
	.string "To TRAINERS, the taste of victory is\n"
	.string "sweet, indeed.\p"
	.string "Battles are constantly waged at\n"
	.string "POKéMON GYMS everywhere.$"

ViridianCity_School_Text_NotebookFirstPage::
# 64 "data/maps/ViridianCity_School/scripts.pory"
	.string "Let's check out the notebook.\p"
	.string "First page…\p"
	.string "POKé BALLS are used to catch POKéMON.\p"
	.string "Up to six POKéMON can be carried in your\n"
	.string "party.\p"
	.string "People who raise and battle with\n"
	.string "POKéMON are called TRAINERS.$"

ViridianCity_School_Text_TurnThePage::
# 68 "data/maps/ViridianCity_School/scripts.pory"
	.string "Turn the page?$"
