ViridianCity_School_MapScripts::
	.byte 0


ViridianCity_School_Text_TryingToMemorizeNotes::
# 5 "data/maps/ViridianCity_School/scripts.pory"
	.string "Whew! I'm trying to memorize all my\n"
	.string "notes.$"

ViridianCity_School_Text_ReadBlackboardCarefully::
# 9 "data/maps/ViridianCity_School/scripts.pory"
	.string "Okay!\p"
	.string "Be sure to read what's on the\n"
	.string "blackboard carefully!$"

ViridianCity_School_Text_NotebookFirstPage::
# 13 "data/maps/ViridianCity_School/scripts.pory"
	.string "Let's check out the notebook.\p"
	.string "First page…\p"
	.string "POKé BALLS are used to catch POKéMON.\p"
	.string "Up to six POKéMON can be carried in your\n"
	.string "party.\p"
	.string "People who raise and battle with\n"
	.string "POKéMON are called TRAINERS.$"

ViridianCity_School_Text_NotebookSecondPage::
# 17 "data/maps/ViridianCity_School/scripts.pory"
	.string "Second page…\p"
	.string "A healthy POKéMON may be hard to catch,\n"
	.string "so weaken it first.\p"
	.string "Poison, burn, or cause another status\n"
	.string "problem to weaken it.$"

ViridianCity_School_Text_NotebookThirdPage::
# 21 "data/maps/ViridianCity_School/scripts.pory"
	.string "Third page…\p"
	.string "POKéMON TRAINERS seek others to\n"
	.string "engage in POKéMON battles.\p"
	.string "To TRAINERS, the taste of victory is\n"
	.string "sweet, indeed.\p"
	.string "Battles are constantly waged at\n"
	.string "POKéMON GYMS everywhere.$"

ViridianCity_School_Text_NotebookFourthPage::
# 25 "data/maps/ViridianCity_School/scripts.pory"
	.string "Fourth page…\p"
	.string "The ultimate goal for all POKéMON\n"
	.string "TRAINERS is simple.\p"
	.string "It is to defeat the top eight POKéMON\n"
	.string "GYM LEADERS.\p"
	.string "Do so to earn the right to face…\p"
	.string "The ELITE FOUR of the POKéMON LEAGUE!$"

ViridianCity_School_Text_TurnThePage::
# 29 "data/maps/ViridianCity_School/scripts.pory"
	.string "Turn the page?$"

ViridianCity_School_Text_HeyDontLookAtMyNotes::
# 33 "data/maps/ViridianCity_School/scripts.pory"
	.string "GIRL: Hey! Don't look at my notes!$"

ViridianCity_School_Text_BlackboardListsStatusProblems::
# 37 "data/maps/ViridianCity_School/scripts.pory"
	.string "The blackboard lists POKéMON STATUS\n"
	.string "problems during battles.$"

ViridianCity_School_Text_ReadWhichTopic::
# 41 "data/maps/ViridianCity_School/scripts.pory"
	.string "Which topic do you want to read?$"

ViridianCity_School_Text_ExplainSleep::
# 45 "data/maps/ViridianCity_School/scripts.pory"
	.string "A POKéMON can't attack if it's asleep.\p"
	.string "POKéMON will stay asleep even after\n"
	.string "battles.\p"
	.string "Use AWAKENING to awaken one from\n"
	.string "sleep.$"

ViridianCity_School_Text_ExplainBurn::
# 49 "data/maps/ViridianCity_School/scripts.pory"
	.string "A burn reduces ATTACK power. It also\n"
	.string "causes ongoing HP loss.\p"
	.string "A burn remains after a battle. Use BURN\n"
	.string "HEAL to cure a burn.$"

ViridianCity_School_Text_ExplainPoison::
# 53 "data/maps/ViridianCity_School/scripts.pory"
	.string "When poisoned, a POKéMON's health\n"
	.string "steadily drops.\p"
	.string "Poison lingers after battles. Use an\n"
	.string "ANTIDOTE to cure poison!$"

ViridianCity_School_Text_ExplainFreeze::
# 57 "data/maps/ViridianCity_School/scripts.pory"
	.string "A frozen POKéMON becomes helplessly\n"
	.string "immobile.\p"
	.string "It stays frozen even after the battle\n"
	.string "ends.\p"
	.string "Use ICE HEAL to thaw out the suffering\n"
	.string "POKéMON.$"

ViridianCity_School_Text_ExplainParalysis::
# 61 "data/maps/ViridianCity_School/scripts.pory"
	.string "Paralysis reduces SPEED and may\n"
	.string "prevent the POKéMON from moving.\p"
	.string "Paralysis remains after battles. Use\n"
	.string "PARLYZ HEAL for treatment.$"
