PacifidlogTown_MapScripts::
# 2 "data/maps/PacifidlogTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PacifidlogTown_OnTransition
# 3 "data/maps/PacifidlogTown/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PacifidlogTown_OnResume
	.byte 0


PacifidlogTown_MapScripts::
# 7 "data/maps/PacifidlogTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PacifidlogTown_OnTransition
# 8 "data/maps/PacifidlogTown/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PacifidlogTown_OnResume
	return


PacifidlogTown_Text_FastRunningCurrent::
# 12 "data/maps/PacifidlogTown/scripts.pory"
	.string "The sea between PACIFIDLOG and\n"
	.string "SLATEPORT has a fast-running tide.\p"
	.string "If you decide to SURF, you could end up\n"
	.string "swept away somewhere else.$"

PacifidlogTown_Text_NeatHousesOnWater::
# 16 "data/maps/PacifidlogTown/scripts.pory"
	.string "See, isn't it neat? These houses are on\n"
	.string "water!\p"
	.string "I was born here!$"

PacifidlogTown_Text_SkyPillarTooScary::
# 20 "data/maps/PacifidlogTown/scripts.pory"
	.string "The SKY PILLAR?\p"
	.string "…Oh, you must mean that tall, tall tower\n"
	.string "a little further out.\p"
	.string "If you asked me, I wouldn't climb it. It's\n"
	.string "too scary to get up that high.\p"
	.string "Life at sea level in PACIFIDLOG, that\n"
	.string "suits me fine.$"

PacifidlogTown_Text_TownSign::
# 24 "data/maps/PacifidlogTown/scripts.pory"
	.string "PACIFIDLOG TOWN\p"
	.string "“Where the morning sun smiles upon the\n"
	.string "waters.”$"
