SSAnne_2F_Corridor_MapScripts::
	.byte 0


SSAnne_2F_Corridor_EventScript_RivalTriggerLeft::
	end


SSAnne_2F_Corridor_EventScript_RivalTriggerMid::
	end


SSAnne_2F_Corridor_EventScript_RivalTriggerRight::
	end


SSAnne_2F_Corridor_EventScript_Sailor::
# 17 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	msgbox SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner, MSGBOX_NPC
	end


SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
# 22 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "This ship, she is a luxury liner for\n"
	.string "TRAINERS of the world!\p"
	.string "At every port, we hold parties with\n"
	.string "invited TRAINERS.$"
