SSAnne_2F_Corridor_MapScripts::
	.byte 0


SSAnne_2F_Corridor_Text_ThisShipIsLuxuryLiner::
# 5 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "This ship, she is a luxury liner for\n"
	.string "TRAINERS of the world!\p"
	.string "At every port, we hold parties with\n"
	.string "invited TRAINERS.$"

SSAnne_2F_Corridor_Text_RivalIntro::
# 9 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "{RIVAL}: Bonjour! {PLAYER}!\p"
	.string "Imagine seeing you here! {PLAYER},\n"
	.string "were you really invited?\p"
	.string "So how's your POKDEX coming?\p"
	.string "I already caught 40 kinds, pal.\n"
	.string "Different kinds are everywhere.\p"
	.string "Crawl around in grassy areas, and look\n"
	.string "hard for them.$"

SSAnne_2F_Corridor_Text_RivalDefeat::
# 13 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "Humph!\p"
	.string "At least you're raising your POKMON!$"

SSAnne_2F_Corridor_Text_RivalVictory::
# 17 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "{PLAYER}\p"
	.string "$"

SSAnne_2F_Corridor_Text_RivalPostBattle::
# 21 "data/maps/SSAnne_2F_Corridor/scripts.pory"
	.string "{RIVAL}: I heard there was a CUT\n"
	.string "master on board.\p"
	.string "But he was just a seasick old man!\p"
	.string "CUT itself is really useful. Yup, it'll be\n"
	.string "handy.\p"
	.string "You should go see him, too. Smell ya!$"
