BattleFrontier_OutsideWest_MapScripts::
# 2 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_OutsideWest_OnTransition
	.byte 0


BattleFrontier_OutsideWest_Text_BattleDomeSign::
# 6 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE DOME! Your path to\n"
	.string "the invincible superstar!$"

BattleFrontier_OutsideWest_Text_BattleFactorySign::
# 10 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE FACTORY! Seek out\n"
	.string "the toughest POKMON!$"

BattleFrontier_OutsideWest_Text_BattlePikeSign::
# 14 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE PIKE! Choose one of\n"
	.string "three paths!$"

BattleFrontier_OutsideWest_Text_ThisIsBattleTower::
# 18 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "This is the BATTLE TOWER.\p"
	.string "TRAINERS bring their best-raised\n"
	.string "POKMON for elimination-style matches.$"

BattleFrontier_OutsideWest_Text_MayISeeYourTicket::
# 22 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Hello, are you here for the ferry? May I\n"
	.string "see your TICKET?$"

BattleFrontier_OutsideWest_Text_MustHaveTicketToBoard::
# 26 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "{PLAYER} doesn't have the TICKET\p"
	.string "I'm terribly sorry.\p"
	.string "You must have a TICKET to board the\n"
	.string "ferry.$"

BattleFrontier_OutsideWest_Text_WhereWouldYouLikeToGo::
# 30 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "{PLAYER} flashed the TICKET.\p"
	.string "Perfect! That's all you need!\p"
	.string "And where would you like to go?$"

BattleFrontier_OutsideWest_Text_SlateportItIs::
# 34 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "SLATEPORT CITY it is, then!$"

BattleFrontier_OutsideWest_Text_LilycoveItIs::
# 38 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "LILYCOVE CITY it is, then!$"

BattleFrontier_OutsideWest_Text_SailWithUsAnotherTime::
# 42 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Please sail with us another time!$"

BattleFrontier_OutsideWest_Text_PleaseBoardFerry::
# 46 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Please board the ferry and wait for\n"
	.string "departure.$"

BattleFrontier_OutsideWest_Text_ThenWhereWouldYouLikeToGo::
# 50 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Then, where would you like to go?$"

BattleFrontier_OutsideWest_Text_BestOutOfAllMyFriends::
# 54 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm the best out of all my friends. But\n"
	.string "here\l"
	.string "I've been useless!$"

BattleFrontier_OutsideWest_Text_CantFindBattleTower::
# 58 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I want to go to the BATTLE TOWER, but I\n"
	.string "can't find it even though I have\l"
	.string "a map of the BATTLE FRONTIER.\p"
	.string "This place is just too big!$"

BattleFrontier_OutsideWest_Text_GotSeasickOnWayHere::
# 62 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I wanted to take a challenge as soon as\n"
	.string "I arrived here.\p"
	.string "But on the way, I got seasick Urrrrp$"

BattleFrontier_OutsideWest_Text_OnlyToughTrainersBroughtHere::
# 66 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "It's not as if just anyone can come\n"
	.string "here, you know?\p"
	.string "Only those TRAINERS who've been\n"
	.string "recognized as tough are brought here.\p"
	.string "That's why many TRAINERS don't even\n"
	.string "know about the BATTLE FRONTIER.$"

BattleFrontier_OutsideWest_Text_SureWeCanChallengeWithNoMons::
# 70 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Hey, bro\p"
	.string "Are you sure we can make challenges\n"
	.string "even if we don't have any POKMON?$"

BattleFrontier_OutsideWest_Text_BigGuySaidIllLendYouMons::
# 74 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Uh I'm sure it'll be okay.\p"
	.string "I think\p"
	.string "But remember that big scary guy? He\n"
	.string "said, I'll lend you POKMON!$"

BattleFrontier_OutsideWest_Text_WhosRaisingThoseRentalMons::
# 78 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "That's the BATTLE FACTORY. You can\n"
	.string "rent strong POKMON there.\p"
	.string "But it makes me wonder. Who's raising\n"
	.string "those rental POKMON?$"

BattleFrontier_OutsideWest_Text_ScaredOfPikeBecauseSeviper::
# 82 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I'm scared of going into the BATTLE\n"
	.string "PIKE because of SEVIPER\p"
	.string "B-but I came all the way here, so I will\n"
	.string "try to conquer everything!\l"
	.string "Shudder$"

BattleFrontier_OutsideWest_Text_LetsPlayRockPaperScissors::
# 86 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Let's play rock, paper, scissors! One,\n"
	.string "two, three!\p"
	.string "$"

BattleFrontier_OutsideWest_Text_WonIllTakePikeChallenge::
# 90 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Yay! I won! I will take the BATTLE PIKE\n"
	.string "challenge!$"

BattleFrontier_OutsideWest_Text_LostIllPutOffPikeChallenge::
# 94 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh, no I lost.\p"
	.string "I guess I'm not very lucky today. I'll\n"
	.string "put off my BATTLE PIKE challenge\l"
	.string "until tomorrow.$"

BattleFrontier_OutsideWest_Text_ChooseFishingOverBattling::
# 98 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I believe I'm the only person here who,\n"
	.string "for some unknown reason, would choose\l"
	.string "fishing over battling.\p"
	.string "Huh? You can't catch anything here?\n"
	.string "That's disappointing$"

BattleFrontier_OutsideWest_Text_KeepBattlingUntilIGetSymbol::
# 102 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Today, I'm going to keep battling, no\n"
	.string "matter what, until I get a Symbol.$"

BattleFrontier_OutsideWest_Text_YoureOffToChallengeDome::
# 106 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh? You're off to challenge the BATTLE\n"
	.string "DOME?\p"
	.string "I'll wish you the best of luck. Let us\n"
	.string "both win our way up and meet\l"
	.string "in challenges.$"

BattleFrontier_OutsideWest_Text_DomeIsHereGrandpa::
# 110 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Grandpa, over here! The BATTLE DOME is\n"
	.string "here!\l"
	.string "Go get 'em, Grandpa!$"

BattleFrontier_OutsideWest_Text_WontLetGentlemenBeatMe::
# 114 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Ah, so this here is the BATTLE DOME? I\n"
	.string "won't let GENTLEMEN beat me!\p"
	.string "But where is the entrance?$"

BattleFrontier_OutsideWest_Text_NothingHereNotLongAgo::
# 118 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "There used to be nothing here not all\n"
	.string "that long ago.\p"
	.string "But, now look at this place! Amazing!\n"
	.string "I'll bring my mother out to see this.$"

BattleFrontier_OutsideWest_Text_FinallyArrivedAtFrontier::
# 122 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I've finally arrived at the BATTLE\n"
	.string "FRONTIER!\p"
	.string "I'm sure to grab attention with my looks\n"
	.string "and ability!$"

BattleFrontier_OutsideWest_Text_SquareFilledWithToughPeople::
# 126 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Munch, munch\p"
	.string "It looks like this square's filled with\n"
	.string "tough people.\p"
	.string "Munch, munch$"

BattleFrontier_OutsideWest_Text_MetOlderGirlAtPike::
# 130 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Crunch, munch\p"
	.string "A while back, I met this older girl at the\n"
	.string "BATTLE PIKE.\p"
	.string "She had these eyes that were scary in a\n"
	.string "real ornery way.\p"
	.string "Crunch, munch\p"
	.string "She got all furious: Will you quit\n"
	.string "eating! Then she whaled on me.\p"
	.string "It was a hair-raising kind of scary\n"
	.string "experience, sure enough.\p"
	.string "Crunch, munch$"

BattleFrontier_OutsideWest_Text_LastTimeOurEyesMet::
# 134 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Huh? Will you listen to yourself? That's\n"
	.string "nothing!\p"
	.string "Why, the last time I cheered for him, our\n"
	.string "eyes met and sparks flew!$"

BattleFrontier_OutsideWest_Text_DomeAceLookedBecauseOfMyCheering::
# 138 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Whaaaaaat?! Pfft!\p"
	.string "That only happened because I happened\n"
	.string "to be sitting next to you!\p"
	.string "The DOME ACE only looked our way\n"
	.string "because my cheering was so loud!$"

BattleFrontier_OutsideWest_Text_DomeAceIsMine::
# 142 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Oh, shush! Keep that racket down!\p"
	.string "You fair-weather fans should stick to\n"
	.string "cheering for some GYM LEADER!\p"
	.string "The DOME ACE is mine! The only idol for\n"
	.string "me!$"

BattleFrontier_OutsideWest_Text_FansOverThereUsedToBeTrainers::
# 146 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "Those people squabbling over there\p"
	.string "It's hard to believe, but they once were\n"
	.string "TRAINERS, and good ones, too.\p"
	.string "They used to be incredibly tough, and\n"
	.string "they were famous, too.\p"
	.string "But they were obliterated by this\n"
	.string "certain TRAINER at a tournament.\p"
	.string "They were so thoroughly whipped, they\n"
	.string "became smitten by the TRAINER.\p"
	.string "Now they're just fans of the TRAINER.\n"
	.string "They go cheer for their idol at the\l"
	.string "BATTLE DOME every day now.$"

BattleFrontier_OutsideWest_Text_MonWithLongTailInFrontier::
# 150 "data/maps/BattleFrontier_OutsideWest/scripts.pory"
	.string "I heard a rumor that someone saw a\n"
	.string "POKMON with an unusually long tail\l"
	.string "somewhere in the BATTLE FRONTIER.\p"
	.string "It must be adorable. I'm sure of it\p"
	.string "Oh, challenges can wait. I feel driven to\n"
	.string "find the delightful creature!$"
