Route10_MapScripts::
	.byte 0


Route10_Text_MarkIntro::
# 5 "data/maps/Route10/scripts.pory"
	.string "Wow, you came all the way here? Maybe\n"
	.string "you're a POKéMANIAC, too?\l"
	.string "Want to see my collection?$"

Route10_Text_MarkDefeat::
# 9 "data/maps/Route10/scripts.pory"
	.string "Humph. I'm not angry!$"

Route10_Text_MarkPostBattle::
# 13 "data/maps/Route10/scripts.pory"
	.string "I have more rare POKéMON at home!$"

Route10_Text_ClarkIntro::
# 17 "data/maps/Route10/scripts.pory"
	.string "Ha-hahah-ah-ha!$"

Route10_Text_ClarkDefeat::
# 21 "data/maps/Route10/scripts.pory"
	.string "Ha-haha! Not laughing!\l"
	.string "Ha-hay fever! Haha-ha-choo!$"

Route10_Text_ClarkPostBattle::
# 25 "data/maps/Route10/scripts.pory"
	.string "Haha-ha-choo! Ha-choo!\l"
	.string "Snort! Snivel!$"

Route10_Text_HermanIntro::
# 29 "data/maps/Route10/scripts.pory"
	.string "Hi, kid! Want to see my POKéMON?$"

Route10_Text_HermanDefeat::
# 33 "data/maps/Route10/scripts.pory"
	.string "Oh, no! My POKéMON!$"

Route10_Text_HermanPostBattle::
# 37 "data/maps/Route10/scripts.pory"
	.string "I don't like you. I don't like anyone\n"
	.string "better than me!$"

Route10_Text_HeidiIntro::
# 41 "data/maps/Route10/scripts.pory"
	.string "I've been out at a POKéMON GYM a few\n"
	.string "times.\p"
	.string "…But I always lose.$"

Route10_Text_HeidiDefeat::
# 45 "data/maps/Route10/scripts.pory"
	.string "Ohh! After all my training!$"

Route10_Text_HeidiPostBattle::
# 49 "data/maps/Route10/scripts.pory"
	.string "I noticed some POKéMANIACS prowling\n"
	.string "around.\p"
	.string "Can you imagine? Them? Up here in the\n"
	.string "mountains?$"

Route10_Text_TrentIntro::
# 53 "data/maps/Route10/scripts.pory"
	.string "Ah! This mountain air is delicious!$"

Route10_Text_TrentDefeat::
# 57 "data/maps/Route10/scripts.pory"
	.string "That cleared my head!$"

Route10_Text_TrentPostBattle::
# 61 "data/maps/Route10/scripts.pory"
	.string "I feel bloated on mountain air!$"

Route10_Text_CarolIntro::
# 65 "data/maps/Route10/scripts.pory"
	.string "I'm feeling a bit faint. I haven't hiked\n"
	.string "in some time.$"

Route10_Text_CarolDefeat::
# 69 "data/maps/Route10/scripts.pory"
	.string "I'm too tired. I wasn't up for it.$"

Route10_Text_CarolPostBattle::
# 73 "data/maps/Route10/scripts.pory"
	.string "The POKéMON here in the mountains are\n"
	.string "so chunky…\p"
	.string "I wish there were pink POKéMON with a\n"
	.string "floral pattern!$"

Route10_Text_RockTunnelDetourToLavender::
# 77 "data/maps/Route10/scripts.pory"
	.string "ROCK TUNNEL Detour to LAVENDER TOWN$"

Route10_Text_RockTunnel::
# 81 "data/maps/Route10/scripts.pory"
	.string "ROCK TUNNEL$"

Route10_Text_PowerPlant::
# 85 "data/maps/Route10/scripts.pory"
	.string "POWER PLANT$"
