LavenderTown_VolunteerPokemonHouse_MapScripts::
	.byte 0


LavenderTown_VolunteerPokemonHouse_EventScript_Bookshelf::
# 5 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	msgbox LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf, MSGBOX_SIGN
	end


LavenderTown_VolunteerPokemonHouse_EventScript_LittleBoy::
# 10 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	msgbox LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug, MSGBOX_NPC
	end


LavenderTown_VolunteerPokemonHouse_EventScript_LittleGirl::
	end


LavenderTown_VolunteerPokemonHouse_EventScript_MrFuji::
	end


LavenderTown_VolunteerPokemonHouse_EventScript_Nidorino::
	end


LavenderTown_VolunteerPokemonHouse_EventScript_PokemonFanMagazine::
# 29 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	msgbox LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped, MSGBOX_DEFAULT
	end


LavenderTown_VolunteerPokemonHouse_EventScript_Psyduck::
	end


LavenderTown_VolunteerPokemonHouse_EventScript_Youngster::
	end


LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
# 43 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKéMON FAN MAGAZINE Monthly Grand\n"
	.string "Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out. Someone\n"
	.string "must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
# 47 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKéMON magazines line the shelf.\p"
	.string "POKéMON INSIDER…\p"
	.string "POKéMON FAN…$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
# 51 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "It's so warm!\n"
	.string "POKéMON are so nice to hug.$"
