LavenderTown_VolunteerPokemonHouse_MapScripts::
	.byte 0


LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
# 5 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "I recently moved to this town.\p"
	.string "I hear that MR. FUJI's not from these\n"
	.string "parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
# 9 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "That's odd, MR. FUJI isn't here. Where'd\n"
	.string "he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
# 13 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI had been praying alone for\n"
	.string "CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
# 17 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "This is really MR. FUJI's house.\p"
	.string "He's really kind.\p"
	.string "He looks after abandoned and orphaned\n"
	.string "POKMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
# 21 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "It's so warm! POKMON are so nice to hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
# 25 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
# 29 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
# 33 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI: {PLAYER}\p"
	.string "Your POKDEX quest is one that requires\n"
	.string "strong dedication.\p"
	.string "Without deep love for POKMON, your\n"
	.string "quest may fail.\p"
	.string "I'm not sure if this will help you, but\n"
	.string "I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
# 37 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "{PLAYER} received a POK FLUTE from\n"
	.string "MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
# 41 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "Upon hearing the POK FLUTE, sleeping\n"
	.string "POKMON will spring awake.\p"
	.string "Try using it on POKMON that are\n"
	.string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
# 45 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
# 49 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI: Has my POK FLUTE helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
# 53 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKMON FAN MAGAZINE Monthly Grand\n"
	.string "Prize Drawing!\p"
	.string "The application form is\p"
	.string "Gone! It's been clipped out. Someone\n"
	.string "must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
# 57 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKMON magazines line the shelf.\p"
	.string "POKMON INSIDER\p"
	.string "POKMON FAN$"
