LavenderTown_VolunteerPokemonHouse_MapScripts::
	.byte 0


LavenderTown_PokemonCenter_1F_Text_HearMrFujiNotFromAroundHere::
# 5 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "I recently moved to this town.\p"
	.string "I hear that MR. FUJI's not from these\n"
	.string "parts originally, either.$"

LavenderTown_VolunteerPokemonHouse_Text_WhereDidMrFujiGo::
# 9 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "That's odd, MR. FUJI isn't here. Where'd\n"
	.string "he go?$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiWasPrayingForCubonesMother::
# 13 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI had been praying alone for\n"
	.string "CUBONE's mother.$"

LavenderTown_VolunteerPokemonHouse_Text_MrFujiLooksAfterOrphanedMons::
# 17 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "This is really MR. FUJI's house.\p"
	.string "He's really kind.\p"
	.string "He looks after abandoned and orphaned\n"
	.string "POKéMON.$"

LavenderTown_VolunteerPokemonHouse_Text_MonsNiceToHug::
# 21 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "It's so warm! POKéMON are so nice to\n"
	.string "hug.$"

LavenderTown_VolunteerPokemonHouse_Text_Nidorino::
# 25 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "NIDORINO: Gaoo!$"

LavenderTown_VolunteerPokemonHouse_Text_Psyduck::
# 29 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "PSYDUCK: Gwappa!$"

LavenderTown_VolunteerPokemonHouse_Text_IdLikeYouToHaveThis::
# 33 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI: {PLAYER}…\p"
	.string "Your POKéDEX quest is one that\n"
	.string "requires strong dedication.\p"
	.string "Without deep love for POKéMON, your\n"
	.string "quest may fail.\p"
	.string "I'm not sure if this will help you, but\n"
	.string "I'd like you to have it.$"

LavenderTown_VolunteerPokemonHouse_Text_ReceivedPokeFluteFromMrFuji::
# 37 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "{PLAYER} received a POKé FLUTE from\n"
	.string "MR. FUJI.$"

LavenderTown_VolunteerPokemonHouse_Text_ExplainPokeFlute::
# 41 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "Upon hearing the POKé FLUTE, sleeping\n"
	.string "POKéMON will spring awake.\p"
	.string "Try using it on POKéMON that are\n"
	.string "sleeping obstacles.$"

LavenderTown_VolunteerPokemonHouse_Text_MustMakeRoomForThis::
# 45 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "You must make room for this!$"

LavenderTown_VolunteerPokemonHouse_Text_HasPokeFluteHelpedYou::
# 49 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "MR. FUJI: Has my POKé FLUTE helped you?$"

LavenderTown_VolunteerPokemonHouse_Text_GrandPrizeDrawingClipped::
# 53 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKéMON FAN MAGAZINE Monthly Grand\n"
	.string "Prize Drawing!\p"
	.string "The application form is…\p"
	.string "Gone! It's been clipped out. Someone\n"
	.string "must have applied already.$"

LavenderTown_VolunteerPokemonHouse_Text_PokemonMagazinesLineShelf::
# 57 "data/maps/LavenderTown_VolunteerPokemonHouse/scripts.pory"
	.string "POKéMON magazines line the shelf.\p"
	.string "POKéMON INSIDER…\p"
	.string "POKéMON FAN…$"
