Route114_FossilManiacsHouse_MapScripts::
# 2 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route114_FossilManiacsHouse_OnTransition
	.byte 0


Route114_FossilManiacsHouse_Text_HaveThisToDigLikeMyBrother::
# 6 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "My big brother's the FOSSIL MANIAC He's\n"
	.string "a nice guy who loves FOSSILS\p"
	.string "He loves digging holes, too He dug this\n"
	.string "hole by himself\p"
	.string "You can have this, so you can DIG holes\n"
	.string "just like my big brother$"

Route114_FossilManiacsHouse_Text_DigReturnsYouToEntrance::
# 10 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "If you make a POKMON DIG inside a cave,\n"
	.string "you're returned to the entrance$"

Route114_FossilManiacsHouse_Text_RocksFillDisplayCase::
# 14 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "Rocks in peculiar shapes fill the\n"
	.string "display case$"

Route114_FossilManiacsHouse_Text_CrammedWithBooks::
# 18 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "THE COMPOSITION OF STRATA HOW RAIN\n"
	.string "SHAPES THE LAND\l"
	.string "STONES, SOIL, AND ROCK\p"
	.string "It's crammed with books.$"
