Route114_FossilManiacsHouse_MapScripts::
	.byte 0


Route114_FossilManiacsHouse_EventScript_Bookshelf::
# 5 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	msgbox Route114_FossilManiacsHouse_Text_CrammedWithBooks, MSGBOX_SIGN
	end


Route114_FossilManiacsHouse_EventScript_FossilManiacsBrother::
	end


Route114_FossilManiacsHouse_EventScript_RockDisplay::
# 14 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	msgbox Route114_FossilManiacsHouse_Text_RocksFillDisplayCase, MSGBOX_SIGN
	end


Route114_FossilManiacsHouse_Text_CrammedWithBooks::
# 19 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "THE COMPOSITION OF STRATA… HOW RAIN\n"
	.string "SHAPES THE LAND…\l"
	.string "STONES, SOIL, AND ROCK…\p"
	.string "It's crammed with books.$"

Route114_FossilManiacsHouse_Text_RocksFillDisplayCase::
# 23 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "Rocks in peculiar shapes fill the\n"
	.string "display case…$"

Route114_FossilManiacsHouse_Text_DigReturnsYouToEntrance::
# 27 "data/maps/Route114_FossilManiacsHouse/scripts.pory"
	.string "If you make a POKéMON DIG inside a\n"
	.string "cave, you're returned to the entrance…$"
