RockTunnel_1F_MapScripts::
# 2 "data/maps/RockTunnel_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, RockTunnel_1F_OnTransition
	.byte 0


RockTunnel_1F_Text_LennyIntro::
# 6 "data/maps/RockTunnel_1F/scripts.pory"
	.string "This tunnel goes a long way, kid!$"

RockTunnel_1F_Text_LennyDefeat::
# 10 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Doh! You win!$"

RockTunnel_1F_Text_LennyPostBattle::
# 14 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Watch for ONIX. They appear only\n"
	.string "occasionally.\p"
	.string "High-level ones can put the squeeze on\n"
	.string "you!$"

RockTunnel_1F_Text_OliverIntro::
# 18 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Hmm. Maybe I'm lost in here$"

RockTunnel_1F_Text_OliverDefeat::
# 22 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Ease up! What am I doing?\l"
	.string "Which way is out?$"

RockTunnel_1F_Text_OliverPostBattle::
# 26 "data/maps/RockTunnel_1F/scripts.pory"
	.string "That sleeping POKMON on ROUTE 12\n"
	.string "forced me to take this detour.$"

RockTunnel_1F_Text_LucasIntro::
# 30 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Outsiders like you need to show me some\n"
	.string "respect!$"

RockTunnel_1F_Text_LucasDefeat::
# 34 "data/maps/RockTunnel_1F/scripts.pory"
	.string "I give!$"

RockTunnel_1F_Text_LucasPostBattle::
# 38 "data/maps/RockTunnel_1F/scripts.pory"
	.string "You're talented enough to hike!$"

RockTunnel_1F_Text_AshtonIntro::
# 42 "data/maps/RockTunnel_1F/scripts.pory"
	.string "POKMON fight! Ready, go!$"

RockTunnel_1F_Text_AshtonDefeat::
# 46 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Game over!$"

RockTunnel_1F_Text_AshtonPostBattle::
# 50 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Oh well, I'll get a ZUBAT as I go!$"

RockTunnel_1F_Text_LeahIntro::
# 54 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Eek!\p"
	.string "Don't try anything funny in the dark!$"

RockTunnel_1F_Text_LeahDefeat::
# 58 "data/maps/RockTunnel_1F/scripts.pory"
	.string "It was too dark$"

RockTunnel_1F_Text_LeahPostBattle::
# 62 "data/maps/RockTunnel_1F/scripts.pory"
	.string "I saw a MACHOP in this tunnel.$"

RockTunnel_1F_Text_DanaIntro::
# 66 "data/maps/RockTunnel_1F/scripts.pory"
	.string "I came this far looking for wild POKMON.$"

RockTunnel_1F_Text_DanaDefeat::
# 70 "data/maps/RockTunnel_1F/scripts.pory"
	.string "I'm out of POKMON!$"

RockTunnel_1F_Text_DanaPostBattle::
# 74 "data/maps/RockTunnel_1F/scripts.pory"
	.string "You looked cute and harmless. Was I\n"
	.string "ever wrong!$"

RockTunnel_1F_Text_ArianaIntro::
# 78 "data/maps/RockTunnel_1F/scripts.pory"
	.string "You have POKMON! Let's start!$"

RockTunnel_1F_Text_ArianaDefeat::
# 82 "data/maps/RockTunnel_1F/scripts.pory"
	.string "You play hard!$"

RockTunnel_1F_Text_ArianaPostBattle::
# 86 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Whew! I'm all sweaty now.$"

RockTunnel_1F_Text_RouteSign::
# 90 "data/maps/RockTunnel_1F/scripts.pory"
	.string "ROCK TUNNEL CERULEAN CITY - LAVENDER\n"
	.string "TOWN$"
