RockTunnel_1F_MapScripts::
	.byte 0


RockTunnel_1F_EventScript_Ariana::
# 5 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_ARIANA, RockTunnel_1F_Text_ArianaIntro, RockTunnel_1F_Text_ArianaDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_ArianaPostBattle
	return


RockTunnel_1F_EventScript_Ashton::
# 10 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_POKEMANIAC_ASHTON, RockTunnel_1F_Text_AshtonIntro, RockTunnel_1F_Text_AshtonDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_AshtonPostBattle
	return


RockTunnel_1F_EventScript_Dana::
# 15 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_DANA, RockTunnel_1F_Text_DanaIntro, RockTunnel_1F_Text_DanaDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_DanaPostBattle
	return


RockTunnel_1F_EventScript_Leah::
# 20 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_LEAH, RockTunnel_1F_Text_LeahIntro, RockTunnel_1F_Text_LeahDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_LeahPostBattle
	return


RockTunnel_1F_EventScript_Lenny::
# 25 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_LENNY, RockTunnel_1F_Text_LennyIntro, RockTunnel_1F_Text_LennyDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_LennyPostBattle
	return


RockTunnel_1F_EventScript_Lucas::
# 30 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_LUCAS, RockTunnel_1F_Text_LucasIntro, RockTunnel_1F_Text_LucasDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_LucasPostBattle
	return


RockTunnel_1F_EventScript_Oliver::
# 35 "data/maps/RockTunnel_1F/scripts.pory"
	trainerbattle_double TRAINER_HIKER_OLIVER, RockTunnel_1F_Text_OliverIntro, RockTunnel_1F_Text_OliverDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_OliverPostBattle
	return


RockTunnel_1F_EventScript_RouteSign::
# 40 "data/maps/RockTunnel_1F/scripts.pory"
	msgbox RockTunnel_1F_Text_RouteSign, MSGBOX_SIGN
	end


RockTunnel_1F_Text_RouteSign::
# 45 "data/maps/RockTunnel_1F/scripts.pory"
	.string "ROCK TUNNEL CERULEAN CITY - LAVENDER\n"
	.string "TOWN$"

RockTunnel_1F_Text_ArianaDefeat::
# 50 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_ArianaDefeat$"

RockTunnel_1F_Text_ArianaIntro::
# 54 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_ArianaIntro$"

RockTunnel_1F_Text_ArianaPostBattle::
# 58 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_ArianaPostBattle$"

RockTunnel_1F_Text_AshtonDefeat::
# 62 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_AshtonDefeat$"

RockTunnel_1F_Text_AshtonIntro::
# 66 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_AshtonIntro$"

RockTunnel_1F_Text_AshtonPostBattle::
# 70 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_AshtonPostBattle$"

RockTunnel_1F_Text_DanaDefeat::
# 74 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_DanaDefeat$"

RockTunnel_1F_Text_DanaIntro::
# 78 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_DanaIntro$"

RockTunnel_1F_Text_DanaPostBattle::
# 82 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_DanaPostBattle$"

RockTunnel_1F_Text_LeahDefeat::
# 86 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LeahDefeat$"

RockTunnel_1F_Text_LeahIntro::
# 90 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LeahIntro$"

RockTunnel_1F_Text_LeahPostBattle::
# 94 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LeahPostBattle$"

RockTunnel_1F_Text_LennyDefeat::
# 98 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LennyDefeat$"

RockTunnel_1F_Text_LennyIntro::
# 102 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LennyIntro$"

RockTunnel_1F_Text_LennyPostBattle::
# 106 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LennyPostBattle$"

RockTunnel_1F_Text_LucasDefeat::
# 110 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LucasDefeat$"

RockTunnel_1F_Text_LucasIntro::
# 114 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LucasIntro$"

RockTunnel_1F_Text_LucasPostBattle::
# 118 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_LucasPostBattle$"

RockTunnel_1F_Text_OliverDefeat::
# 122 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_OliverDefeat$"

RockTunnel_1F_Text_OliverIntro::
# 126 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_OliverIntro$"

RockTunnel_1F_Text_OliverPostBattle::
# 130 "data/maps/RockTunnel_1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "RockTunnel_1F_Text_OliverPostBattle$"
