FortreeCity_House5_MapScripts::
	.byte 0


FortreeCity_House5_EventScript_Man::
# 5 "data/maps/FortreeCity_House5/scripts.pory"
	msgbox FortreeCity_House5_Text_AdaptedToNature, MSGBOX_NPC
	end


FortreeCity_House5_EventScript_PokefanF::
# 10 "data/maps/FortreeCity_House5/scripts.pory"
	msgbox FortreeCity_House5_Text_TreeHousesAreGreat, MSGBOX_NPC
	end


FortreeCity_House5_EventScript_Zigzagoon::
# 15 "data/maps/FortreeCity_House5/scripts.pory"
	msgbox FortreeCity_House5_Text_Zigzagoon, MSGBOX_DEFAULT
	end


FortreeCity_House5_Text_TreeHousesAreGreat::
# 19 "data/maps/FortreeCity_House5/scripts.pory"
	.string "The tree houses of FORTREE are great!\p"
	.string "I think it's the number one town for\n"
	.string "living together with POKéMON.$"

FortreeCity_House5_Text_AdaptedToNature::
# 23 "data/maps/FortreeCity_House5/scripts.pory"
	.string "POKéMON and people have adapted to\n"
	.string "nature for survival.\p"
	.string "There's no need to make nature\n"
	.string "conform to the way we want to live.$"

FortreeCity_House5_Text_Zigzagoon::
# 27 "data/maps/FortreeCity_House5/scripts.pory"
	.string "ZIGZAGOON: Bufuu!$"
