FortreeCity_House5_MapScripts::
	.byte 0


FortreeCity_House5_MapScripts::
	return


FortreeCity_House5_Text_TreeHousesAreGreat::
# 8 "data/maps/FortreeCity_House5/scripts.pory"
	.string "The tree houses of FORTREE are great!\p"
	.string "I think it's the number one town for\n"
	.string "living together with POKéMON.$"

FortreeCity_House5_Text_AdaptedToNature::
# 12 "data/maps/FortreeCity_House5/scripts.pory"
	.string "POKéMON and people have adapted to\n"
	.string "nature for survival.\p"
	.string "There's no need to make nature conform\n"
	.string "to the way we want to live.$"

FortreeCity_House5_Text_Zigzagoon::
# 16 "data/maps/FortreeCity_House5/scripts.pory"
	.string "ZIGZAGOON: Bufuu!$"
