Route114_MapScripts::
# 2 "data/maps/Route114/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route114_OnTransition
# 3 "data/maps/Route114/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route114_OnLoad
# 4 "data/maps/Route114/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route114_OnFrame
	.byte 0


Route114_Text_AllMyMonDoesIsRoarTakeThis::
# 8 "data/maps/Route114/scripts.pory"
	.string "All my POKéMON does is ROAR… No one\n"
	.string "dares to come near me…\p"
	.string "Sigh… If you would, please take this TM\n"
	.string "away…$"

Route114_Text_ExplainRoar::
# 12 "data/maps/Route114/scripts.pory"
	.string "TM05 contains ROAR. A ROAR sends\n"
	.string "POKéMON scurrying.$"

Route114_Text_Poochyena::
# 16 "data/maps/Route114/scripts.pory"
	.string "Bow! Bowwow!$"

Route114_Text_MeteorFallsSign::
# 20 "data/maps/Route114/scripts.pory"
	.string "METEOR FALLS RUSTBORO CITY THROUGH\n"
	.string "HERE$"

Route114_Text_FossilManiacsHouseSign::
# 24 "data/maps/Route114/scripts.pory"
	.string "FOSSIL MANIAC'S HOUSE “Fossils\n"
	.string "gratefully accepted!”$"

Route114_Text_LanettesHouse::
# 28 "data/maps/Route114/scripts.pory"
	.string "LANETTE'S HOUSE$"
