CeladonCity_Restaurant_MapScripts::
	.byte 0


CeladonCity_Restaurant_EventScript_Chef::
# 5 "data/maps/CeladonCity_Restaurant/scripts.pory"
	msgbox CeladonCity_Restaurant_Text_TakingBreakRightNow, MSGBOX_NPC
	end


CeladonCity_Restaurant_EventScript_CoinCaseMan::
	end


CeladonCity_Restaurant_EventScript_FatMan::
# 14 "data/maps/CeladonCity_Restaurant/scripts.pory"
	msgbox CeladonCity_Restaurant_Text_ManLostItAllAtSlots, MSGBOX_NPC
	end


CeladonCity_Restaurant_EventScript_Woman::
# 19 "data/maps/CeladonCity_Restaurant/scripts.pory"
	msgbox CeladonCity_Restaurant_Text_OftenGoToDrugstore, MSGBOX_NPC
	end


CeladonCity_Restaurant_EventScript_WorkerM::
# 24 "data/maps/CeladonCity_Restaurant/scripts.pory"
	msgbox CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner, MSGBOX_NPC
	end


CeladonCity_Restaurant_Text_TakingBreakRightNow::
# 29 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Hi!\p"
	.string "Sorry, but we're taking a break\n"
	.string "right now.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
# 33 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Munch…\p"
	.string "The man at that table lost it all\n"
	.string "at the slots.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
# 37 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "My POKéMON are weak, so I often\n"
	.string "have to go to the DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
# 41 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Psst! There's a basement under the\n"
	.string "GAME CORNER, I hear.$"
