CeladonCity_Restaurant_MapScripts::
	.byte 0


CeladonCity_Restaurant_Text_TakingBreakRightNow::
# 5 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Hi!\p"
	.string "Sorry, but we're taking a break right\n"
	.string "now.$"

CeladonCity_Restaurant_Text_OftenGoToDrugstore::
# 9 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "My POKéMON are weak, so I often have to\n"
	.string "go to the DRUGSTORE.$"

CeladonCity_Restaurant_Text_PsstBasementUnderGameCorner::
# 13 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Psst! There's a basement under the\n"
	.string "GAME CORNER, I hear.$"

CeladonCity_Restaurant_Text_ManLostItAllAtSlots::
# 17 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Munch…\p"
	.string "The man at that table lost it all at the\n"
	.string "slots.$"

CeladonCity_Restaurant_Text_TakeThisImBusted::
# 21 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Go ahead! Laugh! I'm flat-out busted!\p"
	.string "No more slots for me! I'm going\n"
	.string "straight!\p"
	.string "Here! I won't be needing this anymore!$"

CeladonCity_Restaurant_Text_ReceivedCoinCaseFromMan::
# 25 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "{PLAYER} received a COIN CASE from\n"
	.string "the man.$"

CeladonCity_Restaurant_Text_MakeRoomForThis::
# 29 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "Make room for this!$"

CeladonCity_Restaurant_Text_ThoughtIdWinItBack::
# 33 "data/maps/CeladonCity_Restaurant/scripts.pory"
	.string "I always thought I was going to win it\n"
	.string "back…$"
