TwoIsland_House_MapScripts::
	.byte 0


TwoIsland_House_Text_TeachMonMoveForMushroom::
# 5 "data/maps/TwoIsland_House/scripts.pory"
	.string "I'm the POKéMON MOVE MANIAC.\p"
	.string "I know every single move that POKéMON\n"
	.string "learn growing up.\p"
	.string "I'm also a mushroom maniac.\p"
	.string "Bring me two TINYMUSHROOMS, or one BIG\n"
	.string "MUSHROOM.\p"
	.string "If you do that for me, I'll teach a move\n"
	.string "to one POKéMON.$"

TwoIsland_House_Text_WantMeToTeachMove::
# 9 "data/maps/TwoIsland_House/scripts.pory"
	.string "Sniff, sniff… Hm! You smell of\n"
	.string "MUSHROOMS!\p"
	.string "Do you want me to teach a move to a\n"
	.string "POKéMON of yours?$"

TwoIsland_House_Text_TutorWhichMon::
# 13 "data/maps/TwoIsland_House/scripts.pory"
	.string "Which POKéMON needs tutoring?$"

TwoIsland_House_Text_TeachWhichMove::
# 17 "data/maps/TwoIsland_House/scripts.pory"
	.string "Which move should I teach?$"

TwoIsland_House_Text_NoMoveICanTeachThatMon::
# 21 "data/maps/TwoIsland_House/scripts.pory"
	.string "Sorry…\p"
	.string "It doesn't appear as if I have a move I\n"
	.string "can teach that POKéMON.$"

TwoIsland_House_Text_IllNeedMushroomOrTwo::
# 25 "data/maps/TwoIsland_House/scripts.pory"
	.string "Then, I'll need a MUSHROOM or two. What\n"
	.string "are you going to give me?$"

TwoIsland_House_Text_HandedOverTwoTinyMushrooms::
# 29 "data/maps/TwoIsland_House/scripts.pory"
	.string "{PLAYER} handed over two\n"
	.string "TINYMUSHROOMS in exchange.$"

TwoIsland_House_Text_HandedOverOneBigMushroom::
# 33 "data/maps/TwoIsland_House/scripts.pory"
	.string "{PLAYER} handed over one BIG\n"
	.string "MUSHROOM in exchange.$"

TwoIsland_House_Text_NeedMushroomOrTwoToLearnMove::
# 37 "data/maps/TwoIsland_House/scripts.pory"
	.string "If your POKéMON need to learn a move, I\n"
	.string "need a MUSHROOM or two.$"

TwoIsland_House_Text_CantTeachAnEgg::
# 41 "data/maps/TwoIsland_House/scripts.pory"
	.string "Hunh? There isn't a single move that I\n"
	.string "can teach an EGG.$"
