Route118_MapScripts::
# 2 "data/maps/Route118/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route118_OnTransition
# 3 "data/maps/Route118/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route118_OnLoad
# 4 "data/maps/Route118/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, Route118_OnFrame
	.byte 0


Route118_Text_StevenQuestions::
# 8 "data/maps/Route118/scripts.pory"
	.string "STEVEN: Hi, {PLAYER}{KUN}!\p"
	.string "It's me, STEVEN! We met in the cave near\n"
	.string "DEWFORD.\p"
	.string "Have you met many kinds of POKéMON\n"
	.string "since I last saw you?\p"
	.string "There are many, many kinds of POKéMON\n"
	.string "in this wide world of ours.\p"
	.string "If you wanted to raise only your\n"
	.string "favorites, that's fine.\p"
	.string "Perhaps you find it more fun to raise\n"
	.string "all sorts of POKéMON.\p"
	.string "As a TRAINER of POKéMON, what do you\n"
	.string "think?\p"
	.string "Of course, it's not any of my business.\p"
	.string "It would be nice if we were to meet\n"
	.string "again somewhere.$"

Route118_Text_YouAgreeGoodRodIsGood::
# 12 "data/maps/Route118/scripts.pory"
	.string "Hmm! A GOOD ROD is really good!\p"
	.string "Wouldn't you agree?$"

Route118_Text_IdenticalMindsTakeThis::
# 16 "data/maps/Route118/scripts.pory"
	.string "Hmm! We're of identical minds!\p"
	.string "Hmm! Take this GOOD ROD!$"

Route118_Text_TryYourLuckFishing::
# 20 "data/maps/Route118/scripts.pory"
	.string "Wherever there's water, try your luck at\n"
	.string "fishing.$"

Route118_Text_DontYouLikeToFish::
# 24 "data/maps/Route118/scripts.pory"
	.string "Don't you like to fish?$"

Route118_Text_TryCatchingMonWithGoodRod::
# 28 "data/maps/Route118/scripts.pory"
	.string "Try catching all sorts of POKéMON with\n"
	.string "your GOOD ROD.$"

Route118_Text_CanCrossRiversWithSurf::
# 32 "data/maps/Route118/scripts.pory"
	.string "Even if there isn't a boat, you can\n"
	.string "cross rivers and the sea if you have\l"
	.string "a POKéMON that knows SURF.\p"
	.string "POKéMON can be counted on to do so\n"
	.string "much!$"

Route118_Text_RouteSignMauville::
# 36 "data/maps/Route118/scripts.pory"
	.string "ROUTE 118 {LEFT_ARROW} MAUVILLE CITY$"

Route118_Text_RouteSign119::
# 40 "data/maps/Route118/scripts.pory"
	.string "ROUTE 118 {UP_ARROW} ROUTE 119$"
