MossdeepCity_PokemonCenter_1F_MapScripts::
	.byte 0


MossdeepCity_PokemonCenter_1F_EventScript_Girl::
# 5 "data/maps/MossdeepCity_PokemonCenter_1F/scripts.pory"
	msgbox MossdeepCity_PokemonCenter_1F_Text_AbilitiesMightChangeMoves, MSGBOX_NPC
	end


MossdeepCity_PokemonCenter_1F_EventScript_Nurse::
	end


MossdeepCity_PokemonCenter_1F_EventScript_Woman::
# 14 "data/maps/MossdeepCity_PokemonCenter_1F/scripts.pory"
	msgbox MossdeepCity_PokemonCenter_1F_Text_GymLeaderDuoFormidable, MSGBOX_NPC
	end


MossdeepCity_PokemonCenter_1F_Text_GymLeaderDuoFormidable::
# 18 "data/maps/MossdeepCity_PokemonCenter_1F/scripts.pory"
	.string "The GYM LEADERS in this town are\n"
	.string "a formidable duo.\p"
	.string "Their combination attacks are, like,\n"
	.string "excellent and wow!$"

MossdeepCity_PokemonCenter_1F_Text_AbilitiesMightChangeMoves::
# 22 "data/maps/MossdeepCity_PokemonCenter_1F/scripts.pory"
	.string "Depending on the special abilities of\n"
	.string "POKéMON, some moves might change\l"
	.string "or not work at all.$"
