SixIsland_DottedHole_SapphireRoom_MapScripts::
	.byte 0


SixIsland_DottedHole_SapphireRoom_Text_FoundSapphire::
# 5 "data/maps/SixIsland_DottedHole_SapphireRoom/scripts.pory"
	.string "{PLAYER} found a SAPPHIRE!$"

SixIsland_DottedHole_SapphireRoom_Text_IWasRightInTailingYou::
# 9 "data/maps/SixIsland_DottedHole_SapphireRoom/scripts.pory"
	.string "Fufu… Fufufufu… I guessed right.\p"
	.string "I was right in tailing you!$"

SixIsland_DottedHole_SapphireRoom_Text_SellToTeamRocketTellPassword::
# 13 "data/maps/SixIsland_DottedHole_SapphireRoom/scripts.pory"
	.string "I knew that there was a SAPPHIRE here,\n"
	.string "so it belongs to me!\p"
	.string "I'll sell it to TEAM ROCKET for serious\n"
	.string "money.\p"
	.string "…D-don't glare at me like that!\p"
	.string "If you want it back, why don't you go\n"
	.string "get it after I sell it?\p"
	.string "I'll even tell you one of the passwords\n"
	.string "to TEAM ROCKET's\l"
	.string "WAREHOUSE.\p"
	.string "The WAREHOUSE password I know is “Yes,\n"
	.string "nah, CHANSEY.”\p"
	.string "I'm done. Don't think badly of me!$"
