BattleFrontier_BattleFactoryBattleRoom_MapScripts::
# 2 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattleFactoryBattleRoom_OnTransition
# 3 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, BattleFrontier_BattleFactoryBattleRoom_OnWarp
# 4 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattleFactoryBattleRoom_OnFrame
	.byte 0


BattleFrontier_BattleFactoryBattleRoom_Text_GetAMoveOn::
# 8 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "Hey, hey! Get a move on!$"

BattleFrontier_BattleFactoryBattleRoom_Text_NolandImFactoryHead::
# 12 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "Hey, my name's NOLAND! I'm basically in\n"
	.string "charge of this place,\l"
	.string "which is why I'm the FACTORY HEAD!\p"
	.string "I had a look at your Battle Swap data.\p"
	.string "You seem to have the right idea, but\n"
	.string "you're still square in your head!\p"
	.string "Listen up, okay? Knowledge isn't only\n"
	.string "about reading books or doing desk work.\p"
	.string "Just doing that sort of thing It may as\n"
	.string "well be useless!\p"
	.string "You have to experience things with your\n"
	.string "heart and your body, understand?\p"
	.string "I'll take you on under the same\n"
	.string "conditions as you.\p"
	.string "I'll be using rental POKMON, too!$"

BattleFrontier_BattleFactoryBattleRoom_Text_ShakeOutKnowledgeBringItOn::
# 16 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "Shake out every last bit of your\n"
	.string "knowledge and bring it on!$"

BattleFrontier_BattleFactoryBattleRoom_Text_NolandLetsSeeFrontierPass::
# 20 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "NOLAND: Smart going! Let's see your\n"
	.string "FRONTIER PASS.$"

BattleFrontier_BattleFactoryBattleRoom_Text_ReceivedKnowledgeSymbol::
# 24 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "The Knowledge Symbol was embossed on\n"
	.string "the FRONTIER PASS!$"

BattleFrontier_BattleFactoryBattleRoom_Text_NextTimeNoHoldsBarred::
# 28 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "Heh You're a pretty bright spark\p"
	.string "Next time, I'll come after you hard. No\n"
	.string "holds barred, understand?\p"
	.string "You keep up your studies!$"

BattleFrontier_BattleFactoryBattleRoom_Text_HarderLookThanLastTime::
# 32 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "NOLAND: Hey, hey! How's it going? You\n"
	.string "keeping up with your studies?\p"
	.string "Oh?\p"
	.string "You've taken on a harder look than the\n"
	.string "last time I saw you.\p"
	.string "Now, this should be fun! I'm getting\n"
	.string "excited, hey!$"

BattleFrontier_BattleFactoryBattleRoom_Text_AllRightBringItOn::
# 36 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "All right! Bring it on!$"

BattleFrontier_BattleFactoryBattleRoom_Text_OutOfMyLeagueLetsSeePass::
# 40 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "NOLAND: What the You're getting out of\n"
	.string "my league!\p"
	.string "Sheesh! Let's see that FRONTIER PASS!$"

BattleFrontier_BattleFactoryBattleRoom_Text_KnowledgeSymbolTookGoldenShine::
# 44 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "The Knowledge Symbol took on a golden\n"
	.string "shine!$"

BattleFrontier_BattleFactoryBattleRoom_Text_LastTimeILoseToYou::
# 48 "data/maps/BattleFrontier_BattleFactoryBattleRoom/scripts.pory"
	.string "Pfft, man!\p"
	.string "That's absolutely the last time I lose\n"
	.string "to you!\p"
	.string "We have to do this again, hey?$"
