VictoryRoad_B2F_MapScripts::
	.byte 0


VictoryRoad_B2F_Text_VitoIntro::
# 5 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I trained together with my whole family,\n"
	.string "every one of us!\l"
	.string "I'm not losing to anyone!$"

VictoryRoad_B2F_Text_VitoDefeat::
# 9 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Better than my family?! Is that\n"
	.string "possible?!$"

VictoryRoad_B2F_Text_VitoPostBattle::
# 13 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I was better than everyone in my family.\n"
	.string "I've never lost before…\p"
	.string "I've lost my confidence… Maybe I'll go\n"
	.string "home…$"

VictoryRoad_B2F_Text_OwenIntro::
# 17 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I'd heard that there was a tough little\n"
	.string "kid around. Do they mean you?$"

VictoryRoad_B2F_Text_OwenDefeat::
# 21 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The little shrimp is tough!$"

VictoryRoad_B2F_Text_OwenPostBattle::
# 25 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The rumors I heard, that tough little\n"
	.string "kid is from PETALBURG CITY.$"

VictoryRoad_B2F_Text_CarolineIntro::
# 29 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You must be getting a little tired.$"

VictoryRoad_B2F_Text_CarolineDefeat::
# 33 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "No signs of tiring at all!$"

VictoryRoad_B2F_Text_CarolinePostBattle::
# 37 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "VICTORY ROAD and the POKéMON LEAGUE\n"
	.string "are long and grueling challenges.\l"
	.string "Beware of fatigue!$"

VictoryRoad_B2F_Text_JulieIntro::
# 41 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You shouldn't get complacent just\n"
	.string "because you have a lot of GYM BADGES.\p"
	.string "There's always going to be someone\n"
	.string "who's better than you!$"

VictoryRoad_B2F_Text_JulieDefeat::
# 45 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You're better than me!$"

VictoryRoad_B2F_Text_JuliePostBattle::
# 49 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Gaze on your collected BADGES and\n"
	.string "remember the TRAINERS you've faced.$"

VictoryRoad_B2F_Text_FelixIntro::
# 53 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I've come this far, but the tension's\n"
	.string "giving me awful stomach pain…$"

VictoryRoad_B2F_Text_FelixDefeat::
# 57 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Ooh… It hurts…$"

VictoryRoad_B2F_Text_FelixPostBattle::
# 61 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "I can't help getting all tense knowing\n"
	.string "that I'm nearing the POKéMON LEAGUE.\p"
	.string "It's all I can do to feign calm.$"

VictoryRoad_B2F_Text_DianneIntro::
# 65 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "The elite among the elite gather in this\n"
	.string "cave.\p"
	.string "How are you finding it?$"

VictoryRoad_B2F_Text_DianneDefeat::
# 69 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Not rattled in the least bit!$"

VictoryRoad_B2F_Text_DiannePostBattle::
# 73 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "You do have guts! I like that! Keep it\n"
	.string "going!$"
