VictoryRoad_B2F_MapScripts::
	.byte 0


VictoryRoad_B2F_EventScript_Caroline::
# 5 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_CAROLINE, VictoryRoad_B2F_Text_CarolineIntro, VictoryRoad_B2F_Text_CarolineDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_CarolinePostBattle
	return


VictoryRoad_B2F_EventScript_Dianne::
# 10 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_DIANNE, VictoryRoad_B2F_Text_DianneIntro, VictoryRoad_B2F_Text_DianneDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_DiannePostBattle
	return


VictoryRoad_B2F_EventScript_Felix::
# 15 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_FELIX, VictoryRoad_B2F_Text_FelixIntro, VictoryRoad_B2F_Text_FelixDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_FelixPostBattle
	return


VictoryRoad_B2F_EventScript_Julie::
# 20 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_JULIE, VictoryRoad_B2F_Text_JulieIntro, VictoryRoad_B2F_Text_JulieDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_JuliePostBattle
	return


VictoryRoad_B2F_EventScript_Owen::
# 25 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_OWEN, VictoryRoad_B2F_Text_OwenIntro, VictoryRoad_B2F_Text_OwenDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_OwenPostBattle
	return


VictoryRoad_B2F_EventScript_Vito::
# 30 "data/maps/VictoryRoad_B2F/scripts.pory"
	trainerbattle_double TRAINER_VITO, VictoryRoad_B2F_Text_VitoIntro, VictoryRoad_B2F_Text_VitoDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/VictoryRoad_B2F/scripts.pory"
	msgbox VictoryRoad_B2F_Text_VitoPostBattle
	return


VictoryRoad_B2F_Text_CarolineDefeat::
# 36 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_CarolineDefeat$"

VictoryRoad_B2F_Text_CarolineIntro::
# 40 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_CarolineIntro$"

VictoryRoad_B2F_Text_CarolinePostBattle::
# 44 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_CarolinePostBattle$"

VictoryRoad_B2F_Text_DianneDefeat::
# 48 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_DianneDefeat$"

VictoryRoad_B2F_Text_DianneIntro::
# 52 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_DianneIntro$"

VictoryRoad_B2F_Text_DiannePostBattle::
# 56 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_DiannePostBattle$"

VictoryRoad_B2F_Text_FelixDefeat::
# 60 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_FelixDefeat$"

VictoryRoad_B2F_Text_FelixIntro::
# 64 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_FelixIntro$"

VictoryRoad_B2F_Text_FelixPostBattle::
# 68 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_FelixPostBattle$"

VictoryRoad_B2F_Text_JulieDefeat::
# 72 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_JulieDefeat$"

VictoryRoad_B2F_Text_JulieIntro::
# 76 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_JulieIntro$"

VictoryRoad_B2F_Text_JuliePostBattle::
# 80 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_JuliePostBattle$"

VictoryRoad_B2F_Text_OwenDefeat::
# 84 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_OwenDefeat$"

VictoryRoad_B2F_Text_OwenIntro::
# 88 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_OwenIntro$"

VictoryRoad_B2F_Text_OwenPostBattle::
# 92 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_OwenPostBattle$"

VictoryRoad_B2F_Text_VitoDefeat::
# 96 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_VitoDefeat$"

VictoryRoad_B2F_Text_VitoIntro::
# 100 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_VitoIntro$"

VictoryRoad_B2F_Text_VitoPostBattle::
# 104 "data/maps/VictoryRoad_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "VictoryRoad_B2F_Text_VitoPostBattle$"
