Route218_East_MapScripts::
	.byte 0


Route218_East_EventScript_SmithNPC1::
# 5 "data/maps/Route218_East/scripts.pory"
	msgbox Route218_East_Text_SmithNPC1, MSGBOX_NPC
	end


Route218_East_EventScript_SmithNPC2::
# 14 "data/maps/Route218_East/scripts.pory"
	msgbox Route218_East_Text_SmithNPC2, MSGBOX_NPC
	end


Route218_East_EventScript_SmithNPC3::
# 23 "data/maps/Route218_East/scripts.pory"
	msgbox Route218_East_Text_SmithNPC3, MSGBOX_NPC
	end


Route218_East_Text_SmithNPC1::
# 9 "data/maps/Route218_East/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route218_East_Text_SmithNPC2::
# 18 "data/maps/Route218_East/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

Route218_East_Text_SmithNPC3::
# 27 "data/maps/Route218_East/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
