FiveIsland_MemorialPillar_MapScripts::
	.byte 0


FiveIsland_MemorialPillar_EventScript_Memorial::
# 10 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	msgbox FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering, MSGBOX_DEFAULT
	end


FiveIsland_MemorialPillar_EventScript_MemorialMan::
	end


FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
# 22 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "“Here lies TECTONIX” is engraved on a\n"
	.string "boulder.\p"
	.string "There is a LEMONADE placed as an\n"
	.string "offering in front of the grave.$"
