FiveIsland_MemorialPillar_MapScripts::
	.byte 0


FiveIsland_MemorialPillar_Text_MiloIntro::
# 5 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "I'm the eldest of the BIRD BROTHERS.\p"
	.string "The best thing about birds… It has to\n"
	.string "be the beak.$"

FiveIsland_MemorialPillar_Text_MiloDefeat::
# 9 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Oh, so sharp!$"

FiveIsland_MemorialPillar_Text_MiloPostBattle::
# 13 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "You can fly to FOUR ISLAND from here.$"

FiveIsland_MemorialPillar_Text_ChazIntro::
# 17 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "I'm the middle kid of the BIRD BROTHERS.\p"
	.string "The best thing about birds… It has to\n"
	.string "be the wings.$"

FiveIsland_MemorialPillar_Text_ChazDefeat::
# 21 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Flap, flap!$"

FiveIsland_MemorialPillar_Text_ChazPostBattle::
# 25 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "There was a really somber guy over that\n"
	.string "way.$"

FiveIsland_MemorialPillar_Text_HaroldIntro::
# 29 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "I'm the youngest of the BIRD BROTHERS.\p"
	.string "The best thing about birds… It has to\n"
	.string "be the down.$"

FiveIsland_MemorialPillar_Text_HaroldDefeat::
# 33 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Down is so comfy… It makes me drowsy…$"

FiveIsland_MemorialPillar_Text_HaroldPostBattle::
# 37 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "It fills me with happiness when bird\n"
	.string "POKéMON beg playfully…$"

FiveIsland_MemorialPillar_Text_ScrubScrub::
# 41 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Scrub, scrub…$"

FiveIsland_MemorialPillar_Text_YourMonsLookHealthy::
# 45 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Hello… Your POKéMON look healthy…$"

FiveIsland_MemorialPillar_Text_ThisIsWhereIBuriedMyOnix::
# 49 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "This is where I buried my ONIX… It was\n"
	.string "named TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonixLemonadeOffering::
# 53 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "“Here lies TECTONIX” is engraved on a\n"
	.string "boulder.\p"
	.string "There is a LEMONADE placed as an\n"
	.string "offering in front of the grave.$"

FiveIsland_MemorialPillar_Text_LeaveAnotherLemonadeOffering::
# 57 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Would you like to leave another\n"
	.string "LEMONADE as an offering?$"

FiveIsland_MemorialPillar_Text_PlacedCanOfLemonade::
# 61 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "{PLAYER} placed a can of LEMONADE in\n"
	.string "front of the grave.$"

FiveIsland_MemorialPillar_Text_ThankYouPleaseTakeThis::
# 65 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Th-thank you…\p"
	.string "That was my TECTONIX's favorite drink…\p"
	.string "I don't even know you, but your act of\n"
	.string "kindness…\p"
	.string "It's uplifted me a little.\p"
	.string "Can you please take this as my thanks?$"

FiveIsland_MemorialPillar_Text_BeGoodToYourMonsToo::
# 69 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Please be good to your POKéMON, too.$"

FiveIsland_MemorialPillar_Text_DontHaveRoomForIt::
# 73 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "If you don't have room for it, I'll hold\n"
	.string "it for you till next time.$"

FiveIsland_MemorialPillar_Text_StillHaveThingAsMyThanks::
# 77 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Oh, it's you from that time…\p"
	.string "I still have that thing I wanted you to\n"
	.string "have as my thanks.$"

FiveIsland_MemorialPillar_Text_ScrubScrubTectonix::
# 81 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Scrub, scrub…\p"
	.string "… … … TECTONIX…$"

FiveIsland_MemorialPillar_Text_HereLiesTectonix::
# 85 "data/maps/FiveIsland_MemorialPillar/scripts.pory"
	.string "Boulders and rocks are neatly piled up\n"
	.string "as a cairn.\p"
	.string "“Here lies TECTONIX” is engraved on a\n"
	.string "boulder.$"
