OneIsland_House1_MapScripts::
	.byte 0


OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
# 5 "data/maps/OneIsland_House1/scripts.pory"
	.string "On sunny days, I step out and gaze upon\n"
	.string "the volcano.\p"
	.string "That's my daily routine.$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
# 9 "data/maps/OneIsland_House1/scripts.pory"
	.string "Let me think… When was the last time MT.\n"
	.string "EMBER erupted?$"
