OneIsland_House1_MapScripts::
	.byte 0


OneIsland_House1_EventScript_OldMan::
# 5 "data/maps/OneIsland_House1/scripts.pory"
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
	end


OneIsland_House1_EventScript_OldWoman::
# 10 "data/maps/OneIsland_House1/scripts.pory"
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
	end


OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays::
# 15 "data/maps/OneIsland_House1/scripts.pory"
	.string "On sunny days, I step out and gaze\n"
	.string "upon the volcano.\p"
	.string "That's my daily routine.$"

OneIsland_House1_Text_LastTimeMtEmberErupted::
# 19 "data/maps/OneIsland_House1/scripts.pory"
	.string "Let me think… When was the last\n"
	.string "time MT. EMBER erupted?$"
