FallarborTown_PokemonCenter_1F_MapScripts::
# 2 "data/maps/FallarborTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FallarborTown_PokemonCenter_1F_OnTransition
# 3 "data/maps/FallarborTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


FallarborTown_PokemonCenter_1F_Text_LanetteGreeting::
# 7 "data/maps/FallarborTown_PokemonCenter_1F/scripts.pory"
	.string "Oh, hello. You are?\p"
	.string "Okay, your name's {PLAYER}{KUN}. I can see\n"
	.string "that you're a TRAINER.\p"
	.string "So that means you use the POKMON\n"
	.string "Storage System I developed.\p"
	.string "How I arrived at that conclusion is a\n"
	.string "simple deductive process.\p"
	.string "You spoke to me because you wanted to\n"
	.string "access something on this PC.\p"
	.string "Oh, I'm sorry. I'm LANETTE.\p"
	.string "Honestly, I'm glad to meet you--it's\n"
	.string "great you're using the Storage System.\p"
	.string "If you could, please visit me at home. My\n"
	.string "house is on ROUTE 114.$"

FallarborTown_PokemonCenter_1F_Text_FossilManiacEdgeOfTown::
# 11 "data/maps/FallarborTown_PokemonCenter_1F/scripts.pory"
	.string "I wonder what POKMON looked like long,\n"
	.string "long ago?\p"
	.string "Maybe the FOSSIL MANIAC at the edge of\n"
	.string "town will know.$"

FallarborTown_PokemonCenter_1F_Text_PlantHardyTrees::
# 15 "data/maps/FallarborTown_PokemonCenter_1F/scripts.pory"
	.string "In the fields of FALLARBOR, we plant\n"
	.string "seedlings of hardy trees that thrive\l"
	.string "even in volcanic ash.$"
