BattleFrontier_OutsideEast_MapScripts::
# 2 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_OutsideEast_OnResume
# 3 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_OutsideEast_OnTransition
	.byte 0


BattleFrontier_OutsideEast_MapScripts::
# 7 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_OutsideEast_OnResume
# 8 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_OutsideEast_OnTransition
	return


BattleFrontier_OutsideEast_Text_BattleTowerSign::
# 12 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "This is the BATTLE TOWER! Keep the win\n"
	.string "streak as the toughest\l"
	.string "TRAINER!$"

BattleFrontier_OutsideEast_Text_BattlePalaceSign::
# 16 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "This is the BATTLE PALACE! Keep your\n"
	.string "eyes on POKéMON battles!$"

BattleFrontier_OutsideEast_Text_BattleArenaSign::
# 20 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "This is the BATTLE ARENA! Let the\n"
	.string "toughest teams gather!$"

BattleFrontier_OutsideEast_Text_BattlePyramidSign::
# 24 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "This is the BATTLE PYRAMID! Advance\n"
	.string "through the Battle Quest!$"

BattleFrontier_OutsideEast_Text_RankingHallSign::
# 28 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "BATTLE FRONTIER RANKING HALL Set your\n"
	.string "sights on new records!$"

BattleFrontier_OutsideEast_Text_ExchangeCornerSign::
# 32 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "BATTLE POINT EXCHANGE SERVICE CORNER\n"
	.string "Exchange your Battle Points!$"

BattleFrontier_OutsideEast_Text_BattleTowerFeelsSpecial::
# 36 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Wow! It's huge!\p"
	.string "The BATTLE TOWER feels special. It's\n"
	.string "different from the others.$"

BattleFrontier_OutsideEast_Text_ConquerLeagueAndFrontier::
# 40 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "My grand ambition is to conquer both\n"
	.string "the BATTLE FRONTIER and the POKéMON\l"
	.string "LEAGUE.\p"
	.string "And if my dream comes true…\p"
	.string "I… I'm going to ask MIMI next door if\n"
	.string "she will be friends with me!$"

BattleFrontier_OutsideEast_Text_PyramidTooHarsh::
# 44 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "The BATTLE PYRAMID's too harsh! I just\n"
	.string "can't make it to the top!\p"
	.string "Since I'm out of options, maybe I can\n"
	.string "climb the outside…$"

BattleFrontier_OutsideEast_Text_ThriveInDarkness::
# 48 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I thrive in darkness… Yes… What is\n"
	.string "worthy of me?\l"
	.string "None other than the BATTLE PYRAMID…\p"
	.string "What say you to wandering in darkness\n"
	.string "and in utter and total desperation?$"

BattleFrontier_OutsideEast_Text_PutTogetherUltimateTeam::
# 52 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I didn't sleep for a week, but then I put\n"
	.string "together the ultimate team!\p"
	.string "I can't see myself losing, no joke. We're\n"
	.string "storming the BATTLE ARENA!$"

BattleFrontier_OutsideEast_Text_DidScottBringYouHere::
# 56 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Did SCOTT bring you here, too? What is\n"
	.string "it with that guy?\p"
	.string "It sounds like he really does know how\n"
	.string "to spot talented TRAINERS, but…\p"
	.string "I've never seen him battling in person\n"
	.string "ever.$"

BattleFrontier_OutsideEast_Text_BelieveInYouBuddy::
# 60 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "ZIGG! I believe in you, little buddy!\p"
	.string "I'll make my little ZIGG any favorite\n"
	.string "tasty treats you like if you win!$"

BattleFrontier_OutsideEast_Text_ZigzagoonLooksVacant::
# 64 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "ZIGZAGOON looks vacant…$"

BattleFrontier_OutsideEast_Text_PeopleCallMeBusybody::
# 68 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "People call me a busybody, but I can't\n"
	.string "help it.\p"
	.string "Your hat's on crooked! Oh, no, trash on\n"
	.string "the ground!\l"
	.string "Oops, it's almost dinnertime!\p"
	.string "I don't know if I can stand to just\n"
	.string "watch at the BATTLE PALACE…$"

BattleFrontier_OutsideEast_Text_OnceBeatGymLeader::
# 72 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I may not look that impressive now, but\n"
	.string "I once beat a GYM LEADER.\p"
	.string "Who knows, maybe I should give it\n"
	.string "another shot at glory.$"

BattleFrontier_OutsideEast_Text_FastOnBikeAndBattles::
# 76 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I'm fast on my BIKE, and that goes for\n"
	.string "the way I battle, too.\p"
	.string "I win matches in the blink of an eye!$"

BattleFrontier_OutsideEast_Text_BetterThanDaddyAtPokemon::
# 80 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I'm better than my daddy at POKéMON.$"

BattleFrontier_OutsideEast_Text_GoRackUpSomeWinsForDaddy::
# 84 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Go on, my baby sweetie! Go rack up some\n"
	.string "wins for Daddy!\p"
	.string "You're just like your mother, so you'll\n"
	.string "be dominating!$"

BattleFrontier_OutsideEast_Text_HeardPrettyGirlAtBattleArena::
# 88 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "It wasn't easy getting here, but I'd\n"
	.string "heard about this knockout\l"
	.string "pretty girl at the BATTLE ARENA.\p"
	.string "Instead of her, do you know what I\n"
	.string "found?\p"
	.string "A whole teeming mob of sweaty, stinky,\n"
	.string "and primitive martial artists!$"

BattleFrontier_OutsideEast_Text_SometimesImportantOldManInThere::
# 92 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I sometimes see this really important-\n"
	.string "looking old man going in there.\p"
	.string "He has these really awesome POKéMON. He\n"
	.string "seems really nice, though.$"

BattleFrontier_OutsideEast_Text_LegendOfBattlePyramid::
# 96 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Do you know it? The legend of the\n"
	.string "BATTLE PYRAMID?\p"
	.string "When there comes a confident TRAINER\n"
	.string "reaching for the golden pinnacle,\l"
	.string "there shall appear a man among men.\p"
	.string "Don't know that legend? Well, of course\n"
	.string "not!\l"
	.string "I just made it up!\p"
	.string "What's it supposed to mean? That, my\n"
	.string "friend, I can't say!$"

BattleFrontier_OutsideEast_Text_GotWipedOut::
# 100 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Man! Oh man! I've never lost once\n"
	.string "before!\p"
	.string "But I got wiped out with no saving\n"
	.string "grace at all!\p"
	.string "And then I'm told I don't have any\n"
	.string "talent?! Man!$"

BattleFrontier_OutsideEast_Text_ToughTrainerInBattleTower::
# 104 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "This guy ran into a horribly tough\n"
	.string "TRAINER while he was on the BATTLE\l"
	.string "TOWER challenge.\p"
	.string "Now look at him…\p"
	.string "You need to be cautious if you ever\n"
	.string "decide to go to the BATTLE TOWER.$"

BattleFrontier_OutsideEast_Text_EnoughBattlePointsForDoll::
# 108 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Yes! I've finally got enough Battle\n"
	.string "Points!\p"
	.string "I guess I'll trade for another giant\n"
	.string "plush DOLL!$"

BattleFrontier_OutsideEast_Text_LikeToHaveNameRecordedHere::
# 112 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Oh, yeah, okay! So this is the RANKING\n"
	.string "HALL!\p"
	.string "I'd like to go down in history as a super\n"
	.string "champ and have my name\l"
	.string "recorded here for posterity.$"

BattleFrontier_OutsideEast_Text_CanDoAnythingWithYou::
# 116 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "With you by my side, I can do anything.$"

BattleFrontier_OutsideEast_Text_PowerOfOurLoveWillOvercome::
# 120 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Ooh, darling, you are so wonderful!\p"
	.string "Ooh, I just can't wait anymore!\p"
	.string "Let's go to a MULTI BATTLE ROOM right\n"
	.string "this instant!\p"
	.string "If we get together in the BATTLE SALON,\n"
	.string "the power of our love will overcome\l"
	.string "everyone we meet.\p"
	.string "Why, before us, darling, everything will\n"
	.string "topple like dominoes!$"

BattleFrontier_OutsideEast_Text_FrontierNotExclusivelyForToughTrainers::
# 124 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "The BATTLE FRONTIER isn't exclusively\n"
	.string "for tough TRAINERS.\p"
	.string "Many people with special abilities have\n"
	.string "been invited, it seems.\p"
	.string "That man SCOTT…\p"
	.string "He may have built this place to serve a\n"
	.string "bigger objective…$"

BattleFrontier_OutsideEast_Text_OddTreeHereSeemsToWiggle::
# 128 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Excuse me, young one. Have you good\n"
	.string "eyesight?\p"
	.string "There is an odd tree past here, and to\n"
	.string "my tired eyes it seems to wiggle.$"

BattleFrontier_OutsideEast_Text_OnceAnOddTreePastHere::
# 132 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "Excuse me, young one. Have you a good\n"
	.string "memory?\p"
	.string "I have this feeling there once was an\n"
	.string "odd tree past here.$"

BattleFrontier_OutsideEast_Text_StickyMonWithLongTail::
# 136 "data/maps/BattleFrontier_OutsideEast/scripts.pory"
	.string "I… I saw it!\p"
	.string "There was a sticky sort of a POKéMON\n"
	.string "with a long tail up ahead!\p"
	.string "It was hiding under a boulder, and it\n"
	.string "kept staring at me!$"
