DewfordTown_House1_MapScripts::
	.byte 0


DewfordTown_House1_Text_LotToBeSaidForLivingOnIsland::
# 5 "data/maps/DewfordTown_House1/scripts.pory"
	.string "There's a lot to be said for living on a\n"
	.string "small island like this in harmony with\l"
	.string "POKéMON and the family.$"

DewfordTown_House1_Text_LifeGoesSlowlyOnIsland::
# 9 "data/maps/DewfordTown_House1/scripts.pory"
	.string "I left the major port of SLATEPORT CITY\n"
	.string "when I married my husband here.\p"
	.string "Life goes by slowly on this little\n"
	.string "island. But being surrounded by the\l"
	.string "beautiful sea--that's happiness, too.$"

DewfordTown_House1_Text_Zigzagoon::
# 13 "data/maps/DewfordTown_House1/scripts.pory"
	.string "ZIGZAGOON: Guguuh!$"
