MagmaHideout_3F_2R_MapScripts::
	.byte 0


MagmaHideout_3F_2R_Text_Grunt10Intro::
# 5 "data/maps/MagmaHideout_3F_2R/scripts.pory"
	.string "I understand everything our leader\n"
	.string "says. But you know what?\p"
	.string "Doing stuff like digging up a super-\n"
	.string "ancient POKéMON and ripping off\l"
	.string "someone's METEORITE…\p"
	.string "I think we're going a little too far.\n"
	.string "What do you think?$"

MagmaHideout_3F_2R_Text_Grunt10Defeat::
# 9 "data/maps/MagmaHideout_3F_2R/scripts.pory"
	.string "Yeah, I think we are doing something\n"
	.string "wrong somehow.$"

MagmaHideout_3F_2R_Text_Grunt10PostBattle::
# 13 "data/maps/MagmaHideout_3F_2R/scripts.pory"
	.string "You know, losing to you cleared my mind.\p"
	.string "The next time I see our leader, I'm going\n"
	.string "to ask him about what we do.$"
