Route6_UnusedHouse_MapScripts::
	.byte 0


Route6_UnusedHouse_EventScript_SmithNPC1::
# 5 "data/maps/Route6_UnusedHouse/scripts.pory"
	msgbox Route6_UnusedHouse_Text_SmithNPC1, MSGBOX_NPC
	end


Route6_UnusedHouse_EventScript_SmithNPC2::
# 14 "data/maps/Route6_UnusedHouse/scripts.pory"
	msgbox Route6_UnusedHouse_Text_SmithNPC2, MSGBOX_NPC
	end


Route6_UnusedHouse_Text_SmithNPC1::
# 9 "data/maps/Route6_UnusedHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route6_UnusedHouse_Text_SmithNPC2::
# 18 "data/maps/Route6_UnusedHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
