LilycoveCity_DepartmentStore_4F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_4F_Text_AttackOrDefenseTM::
# 5 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "Hmm\p"
	.string "An attacking move Or a defensive move\p"
	.string "It's no easy matter to decide which TM\n"
	.string "moves should be taught to POKMON$"

LilycoveCity_DepartmentStore_4F_Text_FiftyDifferentTMs::
# 9 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "There are so many different kinds of TM\n"
	.string "moves.\p"
	.string "A catalog I read said there are fifty\n"
	.string "different kinds.$"

LilycoveCity_DepartmentStore_4F_Text_PokemonOnlyHaveFourMoves::
# 13 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "I'd like to get all the different TMs,\n"
	.string "but a POKMON learns only four moves.$"
