LilycoveCity_DepartmentStore_4F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_4F_EventScript_ClerkLeft::
	end


LilycoveCity_DepartmentStore_4F_EventScript_ClerkRight::
	end


LilycoveCity_DepartmentStore_4F_EventScript_Gentleman::
# 13 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_4F_Text_AttackOrDefenseTM, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_4F_EventScript_Woman::
# 18 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_4F_Text_FiftyDifferentTMs, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_4F_EventScript_Youngster::
# 23 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_4F_Text_PokemonOnlyHaveFourMoves, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_4F_Text_FiftyDifferentTMs::
# 27 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "There are so many different kinds of\n"
	.string "TM moves.\p"
	.string "A catalog I read said there are fifty\n"
	.string "different kinds.$"

LilycoveCity_DepartmentStore_4F_Text_AttackOrDefenseTM::
# 31 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "Hmm…\p"
	.string "An attacking move…\n"
	.string "Or a defensive move…\p"
	.string "It's no easy matter to decide which TM\n"
	.string "moves should be taught to POKéMON…$"

LilycoveCity_DepartmentStore_4F_Text_PokemonOnlyHaveFourMoves::
# 35 "data/maps/LilycoveCity_DepartmentStore_4F/scripts.pory"
	.string "I'd like to get all the different TMs,\n"
	.string "but a POKéMON learns only four moves.$"
