SSAnne_1F_Room7_MapScripts::
	.byte 0


SSAnne_1F_Room7_Text_ThomasIntro::
# 5 "data/maps/SSAnne_1F_Room7/scripts.pory"
	.string "I am but a solitary traveler…\p"
	.string "My sole companions and friends are\n"
	.string "POKéMON I caught on my journeys…$"

SSAnne_1F_Room7_Text_ThomasDefeat::
# 9 "data/maps/SSAnne_1F_Room7/scripts.pory"
	.string "My, my friends…$"

SSAnne_1F_Room7_Text_ThomasPostBattle::
# 13 "data/maps/SSAnne_1F_Room7/scripts.pory"
	.string "You should be nice to friends!$"
