Route117_MapScripts::
# 2 "data/maps/Route117/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route117_OnTransition
	.byte 0


Route117_MapScripts::
# 6 "data/maps/Route117/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route117_OnTransition
	return


Route117_Text_DayCarePokemonHadNewMove::
# 10 "data/maps/Route117/scripts.pory"
	.string "I left my POKéMON at the DAY CARE.\p"
	.string "When I got it back, it had a new move\n"
	.string "that I didn't teach it.\l"
	.string "I was really, really surprised.$"

Route117_Text_ArentTheseFlowersPretty::
# 14 "data/maps/Route117/scripts.pory"
	.string "What do you think? Aren't these flowers\n"
	.string "pretty?\p"
	.string "I planted them all!$"

Route117_Text_AirIsTastyHere::
# 18 "data/maps/Route117/scripts.pory"
	.string "The air is tasty here!$"

Route117_Text_RouteSignVerdanturf::
# 22 "data/maps/Route117/scripts.pory"
	.string "ROUTE 117 {LEFT_ARROW} VERDANTURF TOWN$"

Route117_Text_RouteSignMauville::
# 26 "data/maps/Route117/scripts.pory"
	.string "ROUTE 117 {RIGHT_ARROW} MAUVILLE CITY$"

Route117_Text_DayCareSign::
# 30 "data/maps/Route117/scripts.pory"
	.string "POKéMON DAY CARE “Let us raise your\n"
	.string "POKéMON.”$"
