Route117_MapScripts::
	.byte 0


NULL::
	end


Route117_EventScript_Aisha::
	end


Route117_EventScript_Anna::
	end


Route117_EventScript_Brandi::
	end


Route117_EventScript_DayCareSign::
# 21 "data/maps/Route117/scripts.pory"
	msgbox Route117_Text_DayCareSign, MSGBOX_SIGN
	end


Route117_EventScript_Derek::
	end


Route117_EventScript_Dylan::
	end


Route117_EventScript_Girl::
	end


Route117_EventScript_Isaac::
	end


Route117_EventScript_LittleBoy::
	end


Route117_EventScript_Lydia::
	end


Route117_EventScript_Maria::
	end


Route117_EventScript_Meg::
	end


Route117_EventScript_Melina::
	end


Route117_EventScript_RouteSignMauville::
# 62 "data/maps/Route117/scripts.pory"
	msgbox Route117_Text_RouteSignMauville, MSGBOX_SIGN
	end


Route117_EventScript_RouteSignVerdanturf::
# 67 "data/maps/Route117/scripts.pory"
	msgbox Route117_Text_RouteSignVerdanturf, MSGBOX_SIGN
	end


Route117_EventScript_Woman::
	end


Route117_Text_DayCareSign::
# 76 "data/maps/Route117/scripts.pory"
	.string "POKéMON DAY CARE\n"
	.string "Let us raise your POKéMON.$"

Route117_Text_RouteSignVerdanturf::
# 80 "data/maps/Route117/scripts.pory"
	.string "ROUTE 117 {LEFT_ARROW} VERDANTURF TOWN$"

Route117_Text_RouteSignMauville::
# 84 "data/maps/Route117/scripts.pory"
	.string "ROUTE 117 {RIGHT_ARROW} MAUVILLE CITY$"
