GraniteCave_StevensRoom_MapScripts::
	.byte 0


GraniteCave_StevensRoom_Text_ImStevenLetterForMe::
# 5 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "My name is STEVEN.\p"
	.string "I'm interested in rare stones, so I\n"
	.string "travel here and there.\p"
	.string "Oh? A LETTER for me?$"

GraniteCave_StevensRoom_Text_ThankYouTakeThis::
# 9 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "STEVEN: Okay, thank you.\p"
	.string "You went through all this trouble to\n"
	.string "deliver that. I need to thank you.\p"
	.string "Let me see I'll give you this TM.\p"
	.string "It contains my favorite move, STEEL\n"
	.string "WING.$"

GraniteCave_StevensRoom_Text_CouldBecomeChampionLetsRegister::
# 13 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "STEVEN: Your POKMON appear quite\n"
	.string "capable.\p"
	.string "If you keep training, you could even\n"
	.string "become the CHAMPION of the POKMON\l"
	.string "LEAGUE one day. That's what I think.\p"
	.string "I know, since we've gotten to know each\n"
	.string "other, let's register one another in\l"
	.string "our POKNAVS.\p"
	.string "$"

GraniteCave_StevensRoom_Text_RegisteredSteven::
# 17 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "Registered STEVEN in the POKNAV.$"

GraniteCave_StevensRoom_Text_IveGotToHurryAlong::
# 21 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "Now, I've got to hurry along.$"

GraniteCave_StevensRoom_Text_OhBagIsFull::
# 25 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "Oh, your BAG is full That's too bad,\n"
	.string "then.$"
