GraniteCave_StevensRoom_MapScripts::
	.byte 0


GraniteCave_StevensRoom_EventScript_Steven::
# 5 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	msgbox GraniteCave_StevensRoom_Text_ImStevenLetterForMe, MSGBOX_DEFAULT
	end


GraniteCave_StevensRoom_Text_OhBagIsFull::
# 9 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "Oh, your BAG is full…\n"
	.string "That's too bad, then.$"

GraniteCave_StevensRoom_Text_ImStevenLetterForMe::
# 13 "data/maps/GraniteCave_StevensRoom/scripts.pory"
	.string "My name is STEVEN.\p"
	.string "I'm interested in rare stones,\n"
	.string "so I travel here and there.\p"
	.string "Oh?\n"
	.string "A LETTER for me?$"
