TwoIsland_CapeBrink_House_MapScripts::
	.byte 0


Text_UltimateMoveThatMon::
# 5 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "I perfected the ultimate move of its\n"
	.string "type\p"
	.string "But will no one take it for future use?\p"
	.string "Hm? Hmmm!\p"
	.string "Y-you Th-that {STR_VAR_1}$"

Text_JustMistaken::
# 9 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "No I was just mistaken.$"

Text_AllowMeToTeachMonUltimateMove::
# 13 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "Oh! This is the one! This is the POKMON!\p"
	.string "This {STR_VAR_1} is worthy of\n"
	.string "learning my ultimate move!\p"
	.string "Will you allow it?\p"
	.string "Will you allow your {STR_VAR_1} to\n"
	.string "learn my {STR_VAR_2}?$"

Text_YouRejectIt::
# 17 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "Gaah! You reject it? No, I won't be\n"
	.string "dissuaded!$"

Text_LetMeConferUltimateMove::
# 21 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "You will allow it?\p"
	.string "Then, let me confer my ultimate\n"
	.string "{STR_VAR_2} on your {STR_VAR_1}.\p"
	.string "Ggggrah-awooo!$"

Text_TaughtMove::
# 25 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "Gasp, gasp, gasp\p"
	.string "I didn't think I could teach that move\n"
	.string "while I still lived$"

Text_MakeBestUseOfMove::
# 29 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "I implore you to make the best use of\n"
	.string "that move and gain power!$"

Text_PassedOnEverythingIKnow::
# 33 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "Gasp, gasp, gasp\p"
	.string "I have no regrets now. I've passed on\n"
	.string "everything I know.\p"
	.string "Now I can live out my life knowing my\n"
	.string "work is done.$"

Text_FeelRejuvenated::
# 37 "data/maps/TwoIsland_CapeBrink_House/scripts.pory"
	.string "After I passed on my knowledge to you,\n"
	.string "I felt so much relief.\p"
	.string "In fact, I feel rejuvenated, as if I\n"
	.string "were younger again!$"
