VerdanturfTown_WandasHouse_MapScripts::
	.byte 0


VerdanturfTown_WandasHouse_MapScripts::
	return


VerdanturfTown_WandasHouse_Text_StrongerSpeech::
# 8 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WALLY: I lost to you, {PLAYER}, but\n"
	.string "I'm not feeling down anymore.\p"
	.string "Because I have a new purpose in life.\n"
	.string "Together with my RALTS, I'm going\l"
	.string "to challenge POKéMON GYMS and become\l"
	.string "a great TRAINER.\p"
	.string "Please watch me, {PLAYER}. I'm going\n"
	.string "to be stronger than you.\p"
	.string "When I do, I'm going to challenge you to\n"
	.string "another battle.$"

VerdanturfTown_WandasHouse_Text_StrongerSpeechShort::
# 12 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WALLY: Please watch me, {PLAYER}. I'm\n"
	.string "going to get stronger than you.\p"
	.string "When I do, I'm going to challenge you to\n"
	.string "another battle.$"

VerdanturfTown_WandasHouse_Text_WallysNextDoor::
# 16 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "UNCLE: Oh! {PLAYER}{KUN}! WALLY's next\n"
	.string "door.\p"
	.string "But, boy, there's something I have to\n"
	.string "tell you.\p"
	.string "This natural environment is doing\n"
	.string "wonders for WALLY's health.\p"
	.string "Maybe it's not just the environment. It\n"
	.string "could be POKéMON that are giving\l"
	.string "the boy hope.$"

VerdanturfTown_WandasHouse_Text_WallySlippedOff::
# 20 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WALLY's gone away… He slipped off on\n"
	.string "his own…$"

VerdanturfTown_WandasHouse_Text_WallyGoneThatFar::
# 24 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "UNCLE: Is that right? WALLY's gone\n"
	.string "away that far all by\l"
	.string "himself…\p"
	.string "Well, I have to give him credit--he is my\n"
	.string "little brother's son.$"

VerdanturfTown_WandasHouse_Text_MeetWanda::
# 28 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WANDA: You are? Oh, right, I get it!\p"
	.string "You're the {PLAYER} who WALLY was\n"
	.string "telling me about.\p"
	.string "I'm WALLY's cousin. Glad to meet you!\p"
	.string "I think WALLY's become a lot more lively\n"
	.string "and healthy since he came here.$"

VerdanturfTown_WandasHouse_Text_DontWorryAboutWally::
# 32 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WANDA: Don't worry about WALLY. He'll be\n"
	.string "just fine.\p"
	.string "I know my little cousin, and he has\n"
	.string "POKéMON with him, too.$"

VerdanturfTown_WandasHouse_Text_CanSeeGirlfriendEveryDay::
# 36 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "Thanks to you, I can see my girlfriend\n"
	.string "every day.\l"
	.string "Happy? You bet I am!$"

VerdanturfTown_WandasHouse_Text_DaughtersBoyfriendDriven::
# 40 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "My daughter's boyfriend is a very\n"
	.string "driven and passionate sort of person.\p"
	.string "He's been digging a tunnel nonstop just\n"
	.string "so he can see my daughter.\p"
	.string "My daughter's a little concerned, so she\n"
	.string "goes out to the tunnel a lot.$"

VerdanturfTown_WandasHouse_Text_DaughtersBoyfriendWasDigging::
# 44 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "It's amazing. My daughter's boyfriend\n"
	.string "was digging the tunnel by hand!\p"
	.string "It's so incredible!$"

VerdanturfTown_WandasHouse_Text_IfAnythingHappenedToWally::
# 48 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "If anything were to happen to WALLY, I\n"
	.string "would never be able to look his\l"
	.string "parents in PETALBURG in the eye…$"

VerdanturfTown_WandasHouse_Text_WallyWasInEverGrande::
# 52 "data/maps/VerdanturfTown_WandasHouse/scripts.pory"
	.string "WALLY was in EVER GRANDE?\p"
	.string "His parents in PETALBURG would be\n"
	.string "astonished to hear that!$"
