SootopolisCity_House3_MapScripts::
	.byte 0


SootopolisCity_House3_Text_JuanHasManyFansDoYou::
# 5 "data/maps/SootopolisCity_House3/scripts.pory"
	.string "You're a POKéMON TRAINER, aren't you?\p"
	.string "SOOTOPOLIS's JUAN has many fans. Even\n"
	.string "more than his student WALLACE!\p"
	.string "Do you have any?$"

SootopolisCity_House3_Text_YouMustBePrettyStrong::
# 9 "data/maps/SootopolisCity_House3/scripts.pory"
	.string "Oh, then you must be pretty strong.$"

SootopolisCity_House3_Text_LonesomeTryWorkingHarder::
# 13 "data/maps/SootopolisCity_House3/scripts.pory"
	.string "Oh, dear… That's a little lonesome.\p"
	.string "Try working a little harder to get a fan\n"
	.string "following.$"

SootopolisCity_House3_Text_TrainerFanClubWasWild::
# 17 "data/maps/SootopolisCity_House3/scripts.pory"
	.string "Dedicated fans come over from even\n"
	.string "outside of HOENN.\p"
	.string "It was really wild when I went to the\n"
	.string "TRAINER FAN CLUB in LILYCOVE.$"
