LavaridgeTown_MapScripts::
# 2 "data/maps/LavaridgeTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LavaridgeTown_OnTransition
# 3 "data/maps/LavaridgeTown/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LavaridgeTown_OnFrame
	.byte 0


LavaridgeTown_Text_MayNiceBadgesTakeThis::
# 7 "data/maps/LavaridgeTown/scripts.pory"
	.string "MAY: {PLAYER}{KUN}! Long time no see!\p"
	.string "Oh? While I visited the hot springs, you\n"
	.string "got the LAVARIDGE GYM BADGE.\p"
	.string "You must have collected good POKéMON…\l"
	.string "No, I believe you raised some.\p"
	.string "I guess it would be okay for you to have\n"
	.string "this.$"

LavaridgeTown_Text_MayExplainGoGogglesChallengeDad::
# 11 "data/maps/LavaridgeTown/scripts.pory"
	.string "MAY: With those GO-GOGGLES, you'll have\n"
	.string "no trouble getting through the\l"
	.string "desert near ROUTE 111.\p"
	.string "But, wow, {PLAYER}{KUN}… Challenging GYMS…\p"
	.string "You're trying hard because you don't\n"
	.string "want to lose to me, I bet!\p"
	.string "{PLAYER}{KUN}, I think I should challenge\n"
	.string "your dad in PETALBURG GYM.\p"
	.string "See you again!$"

LavaridgeTown_Text_BrendanNiceBadgesTakeThis::
# 15 "data/maps/LavaridgeTown/scripts.pory"
	.string "BRENDAN: {PLAYER}, hey, it's been a\n"
	.string "while. How's it going?\p"
	.string "Hmm… That's a decent collection of\n"
	.string "BADGES.\p"
	.string "All right, then. You may as well have\n"
	.string "this.$"

LavaridgeTown_Text_BrendanExplainGoGogglesChallengeDad::
# 19 "data/maps/LavaridgeTown/scripts.pory"
	.string "BRENDAN: Keep those with you if you're\n"
	.string "planning on going into that desert near\l"
	.string "ROUTE 111.\p"
	.string "There should be some POKéMON that are\n"
	.string "exclusively desert-dwellers.\l"
	.string "You might look around for those.\p"
	.string "As for me… I'm considering challenging\n"
	.string "NORMAN,\l"
	.string "the GYM LEADER of PETALBURG.\p"
	.string "Unlike you, {PLAYER}, your dad looks\n"
	.string "like he really is tough.\p"
	.string "See you around!$"

LavaridgeTown_Text_HaveEggWillYouTakeIt::
# 23 "data/maps/LavaridgeTown/scripts.pory"
	.string "I have here an EGG.\p"
	.string "I'd hoped to hatch it by covering it in\n"
	.string "hot sand by the hot springs.\l"
	.string "But that doesn't seem to be enough…\p"
	.string "I've heard it would be best if it were\n"
	.string "kept together with POKéMON and\l"
	.string "carried about.\p"
	.string "You are a TRAINER, yes? And your\n"
	.string "POKéMON radiate vitality.\p"
	.string "So, what say you? Will you take this EGG\n"
	.string "to hatch?$"

LavaridgeTown_Text_HopeYoullWalkPlentyWithEgg::
# 27 "data/maps/LavaridgeTown/scripts.pory"
	.string "Good! I hope you'll walk plenty with this\n"
	.string "here EGG!$"

LavaridgeTown_Text_ReceivedTheEgg::
# 31 "data/maps/LavaridgeTown/scripts.pory"
	.string "{PLAYER} received the EGG.$"

LavaridgeTown_Text_NoRoomForThisEgg::
# 35 "data/maps/LavaridgeTown/scripts.pory"
	.string "Oh? You've too many POKéMON. There's no\n"
	.string "room for this EGG…$"

LavaridgeTown_Text_AsYouWishThen::
# 39 "data/maps/LavaridgeTown/scripts.pory"
	.string "As you wish, then…\p"
	.string "If you have a change of heart about\n"
	.string "hatching this EGG, I will be here.$"

LavaridgeTown_Text_EverySoOftenEggFoundAtDayCare::
# 43 "data/maps/LavaridgeTown/scripts.pory"
	.string "Every so often, an EGG will be found at\n"
	.string "the POKéMON DAY CARE.\p"
	.string "Or at least that's how the rumor goes.$"

LavaridgeTown_Text_HotSpringsNeverRunDry::
# 47 "data/maps/LavaridgeTown/scripts.pory"
	.string "We draw as much hot water as we need,\n"
	.string "and yet the hot springs never run dry.\p"
	.string "Isn't it magical?\p"
	.string "These hot springs appear near active\n"
	.string "volcanoes. Veins of water under the\l"
	.string "ground are heated by magma to well up\l"
	.string "as hot springs.$"

LavaridgeTown_Text_PokemonNippedBackside::
# 51 "data/maps/LavaridgeTown/scripts.pory"
	.string "Being buried in this hot sand is… Sigh…\p"
	.string "So warm and heavenly…\p"
	.string "Eh? Gyaah! Ouch!\p"
	.string "A POKéMON nipped my backside!$"

LavaridgeTown_Text_OhYouLikeHotSprings::
# 55 "data/maps/LavaridgeTown/scripts.pory"
	.string "Oh, you like hot springs, do you?\p"
	.string "That's surprising for one as young as\n"
	.string "you.$"

LavaridgeTown_Text_BatheInHotSpringsEveryDay::
# 59 "data/maps/LavaridgeTown/scripts.pory"
	.string "I bathe in the hot springs every day.\p"
	.string "I want to become a beautiful and strong\n"
	.string "GYM LEADER like FLANNERY.$"

LavaridgeTown_Text_IfPokemonInHotSprings::
# 63 "data/maps/LavaridgeTown/scripts.pory"
	.string "If people put POKéMON in hot springs, it\n"
	.string "might be seriously strange.\p"
	.string "Why, it might be an electric bath, or a\n"
	.string "bubble bath, or even a lava bath…$"

LavaridgeTown_Text_HotSpringsClaims::
# 67 "data/maps/LavaridgeTown/scripts.pory"
	.string "They're claiming that these hot springs\n"
	.string "are good for calming nervous tension,\l"
	.string "relieving aching muscles, solving\l"
	.string "romantic problems, and attracting\l"
	.string "money…$"

LavaridgeTown_Text_TownSign::
# 71 "data/maps/LavaridgeTown/scripts.pory"
	.string "LAVARIDGE TOWN\p"
	.string "“POKéMON CENTER HOT SPRINGS An\n"
	.string "excellent place for relaxing!”$"

LavaridgeTown_Text_GymSign::
# 75 "data/maps/LavaridgeTown/scripts.pory"
	.string "LAVARIDGE TOWN POKéMON GYM LEADER:\n"
	.string "FLANNERY\l"
	.string "“One with a fiery passion that burns!”$"

LavaridgeTown_Text_HerbShopSign::
# 79 "data/maps/LavaridgeTown/scripts.pory"
	.string "POKéMON HERB SHOP “Bitter\n"
	.string "taste--better cure!”$"
