PokemonTower_5F_MapScripts::
	.byte 0


PokemonTower_5F_Text_RestHereInPurifiedSpace::
# 5 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Come, child! I have purified this space.\l"
	.string "You can rest here.$"

PokemonTower_5F_Text_TammyIntro::
# 9 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Give…me… your…all…$"

PokemonTower_5F_Text_TammyDefeat::
# 13 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Gasp!$"

PokemonTower_5F_Text_TammyPostBattle::
# 17 "data/maps/PokemonTower_5F/scripts.pory"
	.string "I was under possession.$"

PokemonTower_5F_Text_RuthIntro::
# 21 "data/maps/PokemonTower_5F/scripts.pory"
	.string "You…shall… join…us…$"

PokemonTower_5F_Text_RuthDefeat::
# 25 "data/maps/PokemonTower_5F/scripts.pory"
	.string "What a nightmare!$"

PokemonTower_5F_Text_RuthPostBattle::
# 29 "data/maps/PokemonTower_5F/scripts.pory"
	.string "I was possessed.$"

PokemonTower_5F_Text_KarinaIntro::
# 33 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Zombies!$"

PokemonTower_5F_Text_KarinaDefeat::
# 37 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Ha?$"

PokemonTower_5F_Text_KarinaPostBattle::
# 41 "data/maps/PokemonTower_5F/scripts.pory"
	.string "I regained my senses.$"

PokemonTower_5F_Text_JanaeIntro::
# 45 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Urgah… Urff…$"

PokemonTower_5F_Text_JanaeDefeat::
# 49 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Whoo!$"

PokemonTower_5F_Text_JanaePostBattle::
# 53 "data/maps/PokemonTower_5F/scripts.pory"
	.string "I fell to evil spirits despite my\n"
	.string "training in the mountains…$"

PokemonTower_5F_Text_PurifiedZoneMonsFullyHealed::
# 57 "data/maps/PokemonTower_5F/scripts.pory"
	.string "Entered the purified and protected\n"
	.string "zone.\p"
	.string "{PLAYER}'s POKéMON were fully healed.$"
