Route16_NorthEntrance_1F_MapScripts::
	.byte 0


Route16_NorthEntrance_1F_EventScript_Guard::
# 5 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	msgbox Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse, MSGBOX_NPC
	end


Route16_NorthEntrance_1F_EventScript_NeedBikeTriggerBottom::
	end


Route16_NorthEntrance_1F_EventScript_NeedBikeTriggerMid::
	end


Route16_NorthEntrance_1F_EventScript_NeedBikeTriggerMidBottom::
	end


Route16_NorthEntrance_1F_EventScript_NeedBikeTriggerMidTop::
	end


Route16_NorthEntrance_1F_EventScript_NeedBikeTriggerTop::
	end


Route16_NorthEntrance_1F_EventScript_OldMan::
# 30 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	msgbox Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort, MSGBOX_NPC
	end


Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
# 35 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "CYCLING ROAD is a downhill course\n"
	.string "by the sea. It's a great ride.$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
# 39 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "How'd you get in?\n"
	.string "Good effort!$"
