Route16_NorthEntrance_1F_MapScripts::
# 2 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route16_NorthEntrance_1F_OnTransition
	.byte 0


Route16_NorthEntrance_1F_Text_NoPedestriansOnCyclingRoad::
# 6 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "No pedestrians are allowed on CYCLING\n"
	.string "ROAD!$"

Route16_NorthEntrance_1F_Text_CyclingRoadIsDownhillCourse::
# 10 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "CYCLING ROAD is a downhill course by\n"
	.string "the sea. It's a great ride.$"

Route16_NorthEntrance_1F_Text_ExcuseMeWaitUp::
# 14 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "Excuse me! Wait up, please!$"

Route16_NorthEntrance_1F_Text_HowdYouGetInGoodEffort::
# 18 "data/maps/Route16_NorthEntrance_1F/scripts.pory"
	.string "How'd you get in? Good effort!$"
