MeteorFalls_1F_1R_MapScripts::
# 2 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MeteorFalls_1F_1R_OnLoad
	.byte 0


MeteorFalls_1F_1R_MapScripts::
# 6 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MeteorFalls_1F_1R_OnLoad
	return


MeteorFalls_1F_1R_Text_WithThisMeteorite::
# 10 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "Hehehe!\p"
	.string "With this METEORITE, that thing in MT.\n"
	.string "CHIMNEY will…$"

MeteorFalls_1F_1R_Text_DontExpectMercyFromMagma::
# 14 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "Heh?\p"
	.string "I don't know who you are, but if you get\n"
	.string "in the way of TEAM MAGMA, don't\l"
	.string "expect any mercy!$"

MeteorFalls_1F_1R_Text_HoldItRightThereMagma::
# 18 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "Hold it right there, TEAM MAGMA!\p"
	.string "You're badly mistaken if you think you\n"
	.string "can have your way with the world!$"

MeteorFalls_1F_1R_Text_BeSeeingYouTeamAqua::
# 22 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "Hehehe! Even TEAM AQUA joins us!\p"
	.string "But it's too much trouble to deal with\n"
	.string "you all…\p"
	.string "Heh, it doesn't matter!\p"
	.string "We've got the METEORITE, so off to MT.\n"
	.string "CHIMNEY we go!\p"
	.string "Hehehe! Be seeing you, you TEAM AQUA\n"
	.string "dingbats!$"

MeteorFalls_1F_1R_Text_ArchieSeenYouBefore::
# 26 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "ARCHIE: Didn't I see you before? At\n"
	.string "SLATEPORT's MUSEUM?\p"
	.string "Ah, so your name is {PLAYER}.\p"
	.string "At the time, I thought you were one of\n"
	.string "TEAM MAGMA's goons.\p"
	.string "Humph… You're one odd kid.\p"
	.string "TEAM MAGMA is a dangerous group of\n"
	.string "total fanatics.\p"
	.string "They engage in destruction, claiming to\n"
	.string "expand the land mass.\p"
	.string "They are the rivals to us, the\n"
	.string "sea-loving TEAM AQUA!$"

MeteorFalls_1F_1R_Text_BossWeShouldChaseMagma::
# 30 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "BOSS, we should give chase to TEAM\n"
	.string "MAGMA…$"

MeteorFalls_1F_1R_Text_ArchieYesNoTellingWhatMagmaWillDo::
# 34 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "ARCHIE: Yes, yes, we must! We've got to\n"
	.string "hurry.\p"
	.string "There's no telling what TEAM MAGMA will\n"
	.string "do at MT. CHIMNEY!$"

MeteorFalls_1F_1R_Text_ArchieFarewell::
# 38 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "ARCHIE: {PLAYER}, you should keep an\n"
	.string "eye out for TEAM MAGMA, too.\p"
	.string "Farewell!$"

MeteorFalls_1F_1R_Text_MeetProfCozmo::
# 42 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "I… I'm COZMO… I'm a PROFESSOR…\p"
	.string "TEAM MAGMA asked me to guide them to\n"
	.string "METEOR FALLS…\p"
	.string "But they tricked me. They even took my\n"
	.string "METEORITE away…\p"
	.string "And then another similar bunch, TEAM\n"
	.string "AQUA showed up.\p"
	.string "After that… I don't understand any of\n"
	.string "it.\p"
	.string "But that TEAM MAGMA…\p"
	.string "What are they going to do with that\n"
	.string "METEORITE at MT. CHIMNEY?$"

MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney::
# 46 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "PROF. COZMO: But that TEAM MAGMA…\p"
	.string "What are they going to do with that\n"
	.string "METEORITE at MT. CHIMNEY?$"
