MeteorFalls_1F_1R_MapScripts::
	.byte 0


MeteorFalls_1F_1R_EventScript_MagmaStealsMeteoriteScene::
# 5 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	msgbox MeteorFalls_1F_1R_Text_WithThisMeteorite, MSGBOX_DEFAULT
	end


MeteorFalls_1F_1R_EventScript_ProfCozmo::
	end


MeteorFalls_1F_1R_Text_WithThisMeteorite::
# 13 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "Hehehe!\p"
	.string "With this METEORITE, that thing in\n"
	.string "MT. CHIMNEY will…$"

MeteorFalls_1F_1R_Text_WhatsTeamMagmaDoingAtMtChimney::
# 17 "data/maps/MeteorFalls_1F_1R/scripts.pory"
	.string "PROF. COZMO: But that TEAM MAGMA…\p"
	.string "What are they going to do with that\n"
	.string "METEORITE at MT. CHIMNEY?$"
