SSAnne_2F_Room6_MapScripts::
	.byte 0


SSAnne_2F_Room6_EventScript_Woman1::
# 5 "data/maps/SSAnne_2F_Room6/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_CaptainIsAwfullySick, MSGBOX_NPC
	end


SSAnne_2F_Room6_EventScript_Woman2::
# 10 "data/maps/SSAnne_2F_Room6/scripts.pory"
	msgbox SSAnne_2F_Room6_Text_ManyPeopleGetSeasick, MSGBOX_NPC
	end


SSAnne_2F_Room6_Text_CaptainIsAwfullySick::
# 15 "data/maps/SSAnne_2F_Room6/scripts.pory"
	.string "The CAPTAIN said he's awfully sick.\n"
	.string "He was all pale.$"

SSAnne_2F_Room6_Text_ManyPeopleGetSeasick::
# 19 "data/maps/SSAnne_2F_Room6/scripts.pory"
	.string "I hear many people get seasick.$"
