CanalaveCity_MapScripts::
	.byte 0


CanalaveCity_EventScript_Sign1::
# 6 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_Sign1, MSGBOX_SIGN
	end


CanalaveCity_EventScript_Sign2::
# 15 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_Sign2, MSGBOX_SIGN
	end


CanalaveCity_EventScript_Sign3::
# 24 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_Sign3, MSGBOX_SIGN
	end


CanalaveCity_EventScript_Sign4::
# 33 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_Sign4, MSGBOX_SIGN
	end


CanalaveCity_EventScript_SmithNPC1::
# 42 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC1, MSGBOX_NPC
	end


CanalaveCity_EventScript_SmithNPC2::
# 51 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC2, MSGBOX_NPC
	end


CanalaveCity_EventScript_SmithNPC3::
# 60 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC3, MSGBOX_NPC
	end


CanalaveCity_EventScript_SmithNPC4::
# 69 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC4, MSGBOX_NPC
	end


CanalaveCity_EventScript_SmithNPC5::
# 78 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC5, MSGBOX_NPC
	end


CanalaveCity_EventScript_SmithNPC6::
# 87 "data/maps/CanalaveCity/scripts.pory"
	msgbox CanalaveCity_Text_SmithNPC6, MSGBOX_NPC
	end


CanalaveCity_Text_Sign1::
# 10 "data/maps/CanalaveCity/scripts.pory"
	.string "CanalaveCity Sign 1$"

CanalaveCity_Text_Sign2::
# 19 "data/maps/CanalaveCity/scripts.pory"
	.string "CanalaveCity Sign 2$"

CanalaveCity_Text_Sign3::
# 28 "data/maps/CanalaveCity/scripts.pory"
	.string "CanalaveCity Sign 3$"

CanalaveCity_Text_Sign4::
# 37 "data/maps/CanalaveCity/scripts.pory"
	.string "CanalaveCity Sign 4$"

CanalaveCity_Text_SmithNPC1::
# 46 "data/maps/CanalaveCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CanalaveCity_Text_SmithNPC2::
# 55 "data/maps/CanalaveCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

CanalaveCity_Text_SmithNPC3::
# 64 "data/maps/CanalaveCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

CanalaveCity_Text_SmithNPC4::
# 73 "data/maps/CanalaveCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

CanalaveCity_Text_SmithNPC5::
# 82 "data/maps/CanalaveCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

CanalaveCity_Text_SmithNPC6::
# 91 "data/maps/CanalaveCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"
