ResortArea_MapScripts::
	.byte 0


ResortArea_EventScript_Sign1::
# 6 "data/maps/ResortArea/scripts.pory"
	msgbox ResortArea_Text_Sign1, MSGBOX_SIGN
	end


ResortArea_EventScript_SmithNPC1::
# 15 "data/maps/ResortArea/scripts.pory"
	msgbox ResortArea_Text_SmithNPC1, MSGBOX_NPC
	end


ResortArea_EventScript_SmithNPC2::
# 24 "data/maps/ResortArea/scripts.pory"
	msgbox ResortArea_Text_SmithNPC2, MSGBOX_NPC
	end


ResortArea_EventScript_SmithNPC3::
# 33 "data/maps/ResortArea/scripts.pory"
	msgbox ResortArea_Text_SmithNPC3, MSGBOX_NPC
	end


ResortArea_Text_Sign1::
# 10 "data/maps/ResortArea/scripts.pory"
	.string "ResortArea Sign 1$"

ResortArea_Text_SmithNPC1::
# 19 "data/maps/ResortArea/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

ResortArea_Text_SmithNPC2::
# 28 "data/maps/ResortArea/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

ResortArea_Text_SmithNPC3::
# 37 "data/maps/ResortArea/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
