BattleFrontier_BattlePalaceCorridor_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePalaceCorridor_OnFrame
	.byte 0


BattleFrontier_BattlePalaceCorridor_Text_PeopleAndMonAreSame::
# 6 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	.string "People and POKéMON, they are but the\n"
	.string "same…\p"
	.string "Their individual nature makes them good\n"
	.string "at certain things, and not good\l"
	.string "at others.$"

BattleFrontier_BattlePalaceCorridor_Text_LetMonDoWhatItLikes::
# 10 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	.string "Rather than trying to make a POKéMON\n"
	.string "do what it dislikes, try to let it do\l"
	.string "what it likes and is good at doing.\p"
	.string "Put yourself in the POKéMON's position\n"
	.string "and consider what moves it would like.$"

BattleFrontier_BattlePalaceCorridor_Text_MonDifferentWhenCornered::
# 14 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	.string "A POKéMON's nature is a remarkable\n"
	.string "thing…\p"
	.string "Some POKéMON behave in a completely\n"
	.string "different way when they are cornered.$"

BattleFrontier_BattlePalaceCorridor_Text_BeginningToUnderstandNature::
# 18 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	.string "Are you beginning to understand how a\n"
	.string "POKéMON's nature makes it behave?$"

BattleFrontier_BattlePalaceCorridor_Text_HeartfeltBondBetweenYouAndMons::
# 22 "data/maps/BattleFrontier_BattlePalaceCorridor/scripts.pory"
	.string "Ah… I see a strong, heartfelt bond\n"
	.string "between you and your POKéMON…$"
