Route12_FishingHouse_MapScripts::
	.byte 0


Route12_FishingHouse_EventScript_FishingGuruBrother::
	end


Route12_FishingHouse_EventScript_MagikarpRecordSign::
# 11 "data/maps/Route12_FishingHouse/scripts.pory"
	msgbox Route12_FishingHouse_Text_BlankChartOfSomeSort, MSGBOX_SIGN
	end


Route12_FishingHouse_Text_BlankChartOfSomeSort::
# 17 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "It's a blank chart of some sort.\p"
	.string "It has spaces for writing in records of\n"
	.string "some kind.$"
