Route12_FishingHouse_MapScripts::
	.byte 0


Route12_FishingHouse_Text_DoYouLikeToFish::
# 5 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "I'm the FISHING GURU's younger brother.\p"
	.string "I simply looove fishing! I can't bear to\n"
	.string "go without.\p"
	.string "Tell me, do you like to fish?$"

Route12_FishingHouse_Text_TakeThisAndFish::
# 9 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Grand! I like your style. I think we can\n"
	.string "be friends.\p"
	.string "Take this and fish, young friend!$"

Route12_FishingHouse_Text_ReceivedSuperRod::
# 13 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "{PLAYER} received a SUPER ROD from\n"
	.string "the FISHING GURU's brother.$"

Route12_FishingHouse_Text_IfYouCatchBigMagikarpShowMe::
# 17 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Fishing is a way of life! It is like the\n"
	.string "finest poetry.\p"
	.string "From the seas to rivers, go out and land\n"
	.string "the big one, my friend.\p"
	.string "Now, I have a request.\p"
	.string "If you catch a big MAGIKARP with that\n"
	.string "ROD, I want to see it.\p"
	.string "As much as I love to fish, I also love\n"
	.string "seeing gigantic MAGIKARP.$"

Route12_FishingHouse_Text_OhThatsDisappointing::
# 21 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Oh… That's so disappointing…$"

Route12_FishingHouse_Text_TryFishingBringMeMagikarp::
# 25 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Hello there, {PLAYER}! Have you been\n"
	.string "fishing?\p"
	.string "Try fishing with the SUPER ROD in any\n"
	.string "body of water.\p"
	.string "You'll find different POKéMON in\n"
	.string "different places.\p"
	.string "Oh, and don't forget to bring me\n"
	.string "gigantic MAGIKARP.$"

Route12_FishingHouse_Text_OhMagikarpAllowMeToSee::
# 29 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Oh? {PLAYER}? Why, if it isn't a\n"
	.string "MAGIKARP!\p"
	.string "Allow me to see it, quick!$"

Route12_FishingHouse_Text_WhoaXInchesTakeThis::
# 33 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "… … …Whoa! {STR_VAR_2} inches!\p"
	.string "You have a rare appreciation for the\n"
	.string "fine, poetic aspects of fishing!\p"
	.string "You must take this. I insist!$"

Route12_FishingHouse_Text_LookForwardToGreaterRecords::
# 37 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "I'll look forward to seeing greater\n"
	.string "records from you!$"

Route12_FishingHouse_Text_HuhXInchesSameSizeAsLast::
# 41 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Huh? {STR_VAR_2} inches?\p"
	.string "This is the same size as the one I saw\n"
	.string "before.$"

Route12_FishingHouse_Text_HmmXInchesDoesntMeasureUp::
# 45 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Hmm… This one is {STR_VAR_2} inches\n"
	.string "long.\p"
	.string "It doesn't measure up to the\n"
	.string "{STR_VAR_3}-inch one you brought\l"
	.string "before.$"

Route12_FishingHouse_Text_DoesntLookLikeMagikarp::
# 49 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Uh… That doesn't look much like a\n"
	.string "MAGIKARP.$"

Route12_FishingHouse_Text_NoRoomForGift::
# 53 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "Oh, no!\p"
	.string "I had a gift for you, but you have no\n"
	.string "room for it.$"

Route12_FishingHouse_Text_MostGiganticMagikarpXInches::
# 57 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "The most gigantic MAGIKARP I have ever\n"
	.string "witnessed…\p"
	.string "{STR_VAR_3} inches!$"

Route12_FishingHouse_Text_BlankChartOfSomeSort::
# 61 "data/maps/Route12_FishingHouse/scripts.pory"
	.string "It's a blank chart of some sort.\p"
	.string "It has spaces for writing in records of\n"
	.string "some kind.$"
