CeladonCity_Condominiums_RoofRoom_MapScripts::
	.byte 0


CeladonCity_Condominiums_RoofRoom_EventScript_BlackBelt::
# 5 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	msgbox CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow, MSGBOX_NPC
	end


CeladonCity_Condominiums_RoofRoom_EventScript_Blackboard::
# 11 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	msgbox CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture, MSGBOX_DEFAULT
	end


CeladonCity_Condominiums_RoofRoom_EventScript_EeveeBall::
	end


CeladonCity_Condominiums_RoofRoom_EventScript_TMsPamphlet::
# 30 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	msgbox CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs, MSGBOX_SIGN
	end


CeladonCity_Condominiums_RoofRoom_Text_PamphletOnTMs::
# 35 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	.string "It's a pamphlet on TMs.\p"
	.string "… …\p"
	.string "There are fifty TMs in all.\p"
	.string "There are also seven HMs that can be\n"
	.string "used repeatedly.\p"
	.string "SILPH CO.$"

CeladonCity_Condominiums_RoofRoom_Text_WirelessAdapterLecture::
# 39 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	.string "POKéMON Lecture\p"
	.string "Playing with the Wireless Adapter$"

CeladonCity_Condominiums_RoofRoom_Text_TheresNothingIDontKnow::
# 43 "data/maps/CeladonCity_Condominiums_RoofRoom/scripts.pory"
	.string "There is nothing that I don't know,\n"
	.string "like I wrote on the blackboard.\p"
	.string "I know about the world of POKéMON\n"
	.string "in your GAME BOY ADVANCE!\p"
	.string "Get together with your friends and\n"
	.string "enjoy trading POKéMON!$"
