BattleFrontier_BattlePyramidFloor_MapScripts::
# 2 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePyramidFloor_OnResume
# 3 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePyramidFloor_OnFrame
# 4 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattlePyramidFloor_OnTransition
	.byte 0


BattleFrontier_BattlePyramidFloor_MapScripts::
# 8 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, BattleFrontier_BattlePyramidFloor_OnResume
# 9 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, BattleFrontier_BattlePyramidFloor_OnFrame
# 10 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, BattleFrontier_BattlePyramidFloor_OnTransition
	return


BattleFacility_TrainerBattle_PlaceholderText::
# 14 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is a sample message.$"

gText_BattlePyramidConfirmRest::
# 18 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Your BATTLE PYRAMID quest will be\n"
	.string "saved so that you may quit for now.\l"
	.string "Is that okay?$"

gText_BattlePyramidConfirmRetire::
# 22 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you sure you want to quit your\n"
	.string "PYRAMID quest?$"

BattlePyramid_Text_ExitHintUp1::
# 26 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This floor's exit is in that direction: {UP_ARROW}$"

BattlePyramid_Text_ExitHintLeft1::
# 30 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This floor's exit is in that direction: {LEFT_ARROW}$"

BattlePyramid_Text_ExitHintRight1::
# 34 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This floor's exit is in that direction: {RIGHT_ARROW}$"

BattlePyramid_Text_ExitHintDown1::
# 38 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This floor's exit is in that direction: {DOWN_ARROW}$"

BattlePyramid_Text_ExitHintUp2::
# 42 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit on this floor is in the {UP_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintLeft2::
# 46 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit on this floor is in the {LEFT_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintRight2::
# 50 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit on this floor is in the {RIGHT_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintDown2::
# 54 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit on this floor is in the {DOWN_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintUp3::
# 58 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit is over that {UP_ARROW} way.$"

BattlePyramid_Text_ExitHintLeft3::
# 62 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit is over that {LEFT_ARROW} way.$"

BattlePyramid_Text_ExitHintRight3::
# 66 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit is over that {RIGHT_ARROW} way.$"

BattlePyramid_Text_ExitHintDown3::
# 70 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit is over that {DOWN_ARROW} way.$"

BattlePyramid_Text_ExitHintUp4::
# 74 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor, the exit is somewhere in\n"
	.string "the {UP_ARROW} direction.$"

BattlePyramid_Text_ExitHintLeft4::
# 78 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor, the exit is somewhere in\n"
	.string "the {LEFT_ARROW} direction.$"

BattlePyramid_Text_ExitHintRight4::
# 82 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor, the exit is somewhere in\n"
	.string "the {RIGHT_ARROW} direction.$"

BattlePyramid_Text_ExitHintDown4::
# 86 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor, the exit is somewhere in\n"
	.string "the {DOWN_ARROW} direction.$"

BattlePyramid_Text_ExitHintUp5::
# 90 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit? It's that {UP_ARROW} way.$"

BattlePyramid_Text_ExitHintLeft5::
# 94 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit? It's that {LEFT_ARROW} way.$"

BattlePyramid_Text_ExitHintRight5::
# 98 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit? It's that {RIGHT_ARROW} way.$"

BattlePyramid_Text_ExitHintDown5::
# 102 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit? It's that {DOWN_ARROW} way.$"

BattlePyramid_Text_ExitHintUp6::
# 106 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit happens to be in the {UP_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintLeft6::
# 110 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit happens to be in the {LEFT_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintRight6::
# 114 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit happens to be in the {RIGHT_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_ExitHintDown6::
# 118 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "The exit happens to be in the {DOWN_ARROW}\n"
	.string "direction.$"

BattlePyramid_Text_EightItemsRemaining1::
# 122 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are eight items left to be found.$"

BattlePyramid_Text_SevenItemsRemaining1::
# 126 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are seven items left to be found.$"

BattlePyramid_Text_SixItemsRemaining1::
# 130 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are six items left to be found.$"

BattlePyramid_Text_FiveItemsRemaining1::
# 134 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are five items left to be found.$"

BattlePyramid_Text_FourItemsRemaining1::
# 138 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are four items left to be found.$"

BattlePyramid_Text_ThreeItemsRemaining1::
# 142 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are three items left to be found.$"

BattlePyramid_Text_TwoItemsRemaining1::
# 146 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There are two items left to be found.$"

BattlePyramid_Text_OneItemRemaining1::
# 150 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There is one item left to be found.$"

BattlePyramid_Text_ZeroItemsRemaining1::
# 154 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Are you looking for items?\p"
	.string "There isn't anything left to be found!$"

BattlePyramid_Text_EightItemsRemaining2::
# 158 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are eight items lying around here.$"

BattlePyramid_Text_SevenItemsRemaining2::
# 162 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are seven items left lying around\n"
	.string "here.$"

BattlePyramid_Text_SixItemsRemaining2::
# 166 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are six items left lying around\n"
	.string "here.$"

BattlePyramid_Text_FiveItemsRemaining2::
# 170 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are five items left lying around\n"
	.string "here.$"

BattlePyramid_Text_FourItemsRemaining2::
# 174 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are four items left lying around\n"
	.string "here.$"

BattlePyramid_Text_ThreeItemsRemaining2::
# 178 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are three items left lying around\n"
	.string "here.$"

BattlePyramid_Text_TwoItemsRemaining2::
# 182 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There are two items left lying around\n"
	.string "here.$"

BattlePyramid_Text_OneItemRemaining2::
# 186 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There is just one item lying around\n"
	.string "here.$"

BattlePyramid_Text_ZeroItemsRemaining2::
# 190 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Because you won, I'll tell you a little\n"
	.string "secret!\p"
	.string "There isn't anything left lying around\n"
	.string "here.$"

BattlePyramid_Text_EightItemsRemaining3::
# 194 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are eight items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_SevenItemsRemaining3::
# 198 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are seven items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_SixItemsRemaining3::
# 202 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are six items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_FiveItemsRemaining3::
# 206 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are five items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_FourItemsRemaining3::
# 210 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are four items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_ThreeItemsRemaining3::
# 214 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are three items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_TwoItemsRemaining3::
# 218 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are two items left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_OneItemRemaining3::
# 222 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there's but one item left\n"
	.string "waiting to be found on this floor.$"

BattlePyramid_Text_ZeroItemsRemaining3::
# 226 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "How's your stock of items holding up?\p"
	.string "I reckon there are no more items\n"
	.string "waiting to be found on this floor.\l"
	.string "You take care now!$"

BattlePyramid_Text_EightItemsRemaining4::
# 230 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be eight more items on\n"
	.string "the ground.$"

BattlePyramid_Text_SevenItemsRemaining4::
# 234 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be seven more items on\n"
	.string "the ground.$"

BattlePyramid_Text_SixItemsRemaining4::
# 238 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be six more items on\n"
	.string "the ground.$"

BattlePyramid_Text_FiveItemsRemaining4::
# 242 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be five more items on\n"
	.string "the ground.$"

BattlePyramid_Text_FourItemsRemaining4::
# 246 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be four more items on\n"
	.string "the ground.$"

BattlePyramid_Text_ThreeItemsRemaining4::
# 250 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be three more items on\n"
	.string "the ground.$"

BattlePyramid_Text_TwoItemsRemaining4::
# 254 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be two more items on\n"
	.string "the ground.$"

BattlePyramid_Text_OneItemRemaining4::
# 258 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appears to be only one more item\n"
	.string "on the ground.$"

BattlePyramid_Text_ZeroItemsRemaining4::
# 262 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You're strong, so you've earned a hint!\p"
	.string "There appear to be no more items on the\n"
	.string "ground.$"

BattlePyramid_Text_EightItemsRemaining5::
# 266 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are eight items…$"

BattlePyramid_Text_SevenItemsRemaining5::
# 270 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are seven items…$"

BattlePyramid_Text_SixItemsRemaining5::
# 274 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are six items…$"

BattlePyramid_Text_FiveItemsRemaining5::
# 278 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are five items…$"

BattlePyramid_Text_FourItemsRemaining5::
# 282 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are four items…$"

BattlePyramid_Text_ThreeItemsRemaining5::
# 286 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are three items…$"

BattlePyramid_Text_TwoItemsRemaining5::
# 290 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are two items…$"

BattlePyramid_Text_OneItemRemaining5::
# 294 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there is one item…$"

BattlePyramid_Text_ZeroItemsRemaining5::
# 298 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "On this floor of the PYRAMID, I hear\n"
	.string "there are no items…$"

BattlePyramid_Text_EightItemsRemaining6::
# 302 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are eight more items on\n"
	.string "this floor.$"

BattlePyramid_Text_SevenItemsRemaining6::
# 306 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are seven more items on\n"
	.string "this floor.$"

BattlePyramid_Text_SixItemsRemaining6::
# 310 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are six more items on\n"
	.string "this floor.$"

BattlePyramid_Text_FiveItemsRemaining6::
# 314 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are five more items on\n"
	.string "this floor.$"

BattlePyramid_Text_FourItemsRemaining6::
# 318 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are four more items on\n"
	.string "this floor.$"

BattlePyramid_Text_ThreeItemsRemaining6::
# 322 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are three more items on\n"
	.string "this floor.$"

BattlePyramid_Text_TwoItemsRemaining6::
# 326 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are two more items on\n"
	.string "this floor.$"

BattlePyramid_Text_OneItemRemaining6::
# 330 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there is one more item on this\n"
	.string "floor.$"

BattlePyramid_Text_ZeroItemsRemaining6::
# 334 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Have you collected any items?\p"
	.string "I believe there are no more items on\n"
	.string "this floor.$"

BattlePyramid_Text_SevenTrainersRemaining1::
# 338 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still seven tough\n"
	.string "TRAINERS other than me!$"

BattlePyramid_Text_SixTrainersRemaining1::
# 342 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still six tough TRAINERS\n"
	.string "other than me!$"

BattlePyramid_Text_FiveTrainersRemaining1::
# 346 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still five tough TRAINERS\n"
	.string "other than me!$"

BattlePyramid_Text_FourTrainersRemaining1::
# 350 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still four tough TRAINERS\n"
	.string "other than me!$"

BattlePyramid_Text_ThreeTrainersRemaining1::
# 354 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still three tough\n"
	.string "TRAINERS other than me!$"

BattlePyramid_Text_TwoTrainersRemaining1::
# 358 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there are still two tough TRAINERS\n"
	.string "other than me!$"

BattlePyramid_Text_OneTrainersRemaining1::
# 362 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "But there's still one tough TRAINER\n"
	.string "other than me!$"

BattlePyramid_Text_ZeroTrainersRemaining1::
# 366 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You were really awesome!\p"
	.string "There's no one left that can beat you!$"

BattlePyramid_Text_SevenTrainersRemaining2::
# 370 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are seven TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_SixTrainersRemaining2::
# 374 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are six TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_FiveTrainersRemaining2::
# 378 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are five TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_FourTrainersRemaining2::
# 382 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are four TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_ThreeTrainersRemaining2::
# 386 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are three TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_TwoTrainersRemaining2::
# 390 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are two TRAINERS left!\n"
	.string "Someone will humble you!$"

BattlePyramid_Text_OneTrainersRemaining2::
# 394 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there's one TRAINER left! I'm sure\n"
	.string "you will be humbled!$"

BattlePyramid_Text_ZeroTrainersRemaining2::
# 398 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "This is so upsetting!\p"
	.string "But there are no more TRAINERS who can\n"
	.string "engage you!$"

BattlePyramid_Text_SevenTrainersRemaining3::
# 402 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are seven more TRAINERS on\n"
	.string "this floor. Can you beat them all?$"

BattlePyramid_Text_SixTrainersRemaining3::
# 406 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are six more TRAINERS on this\n"
	.string "floor. Can you beat them all?$"

BattlePyramid_Text_FiveTrainersRemaining3::
# 410 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are five more TRAINERS on\n"
	.string "this floor. Can you beat them all?$"

BattlePyramid_Text_FourTrainersRemaining3::
# 414 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are four more TRAINERS on\n"
	.string "this floor. Can you beat them all?$"

BattlePyramid_Text_ThreeTrainersRemaining3::
# 418 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are three more TRAINERS on\n"
	.string "this floor. Can you beat them all?$"

BattlePyramid_Text_TwoTrainersRemaining3::
# 422 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there are two more TRAINERS on this\n"
	.string "floor. Can you beat them both?$"

BattlePyramid_Text_OneTrainersRemaining3::
# 426 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "But there's still one more TRAINER on\n"
	.string "this floor. Can you prevail?$"

BattlePyramid_Text_ZeroTrainersRemaining3::
# 430 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "That's pretty impressive!\p"
	.string "You've gone through all the TRAINERS on\n"
	.string "this floor.$"

BattlePyramid_Text_SevenTrainersRemaining4::
# 434 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the\n"
	.string "seven TRAINERS left on this floor.$"

BattlePyramid_Text_SixTrainersRemaining4::
# 438 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the six\n"
	.string "TRAINERS left on this floor.$"

BattlePyramid_Text_FiveTrainersRemaining4::
# 442 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the five\n"
	.string "TRAINERS left on this floor.$"

BattlePyramid_Text_FourTrainersRemaining4::
# 446 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the four\n"
	.string "TRAINERS left on this floor.$"

BattlePyramid_Text_ThreeTrainersRemaining4::
# 450 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the\n"
	.string "three TRAINERS left on this floor.$"

BattlePyramid_Text_TwoTrainersRemaining4::
# 454 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could sweep through the two\n"
	.string "TRAINERS left on this floor.$"

BattlePyramid_Text_OneTrainersRemaining4::
# 458 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Maybe you could complete your sweep\n"
	.string "with the one TRAINER left on this floor.$"

BattlePyramid_Text_ZeroTrainersRemaining4::
# 462 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "There isn't a single person left who can\n"
	.string "defeat you now…$"

BattlePyramid_Text_SevenTrainersRemaining5::
# 466 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "seven expert TRAINERS who remain.$"

BattlePyramid_Text_SixTrainersRemaining5::
# 470 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "six expert TRAINERS who remain.$"

BattlePyramid_Text_FiveTrainersRemaining5::
# 474 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "five expert TRAINERS who remain.$"

BattlePyramid_Text_FourTrainersRemaining5::
# 478 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "four expert TRAINERS who remain.$"

BattlePyramid_Text_ThreeTrainersRemaining5::
# 482 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "three expert TRAINERS who remain.$"

BattlePyramid_Text_TwoTrainersRemaining5::
# 486 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "two expert TRAINERS who remain.$"

BattlePyramid_Text_OneTrainersRemaining5::
# 490 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "You may have what it takes to beat the\n"
	.string "one expert TRAINER who remains.$"

BattlePyramid_Text_ZeroTrainersRemaining5::
# 494 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Your skills are beyond reproach.\p"
	.string "There are no more TRAINERS here who\n"
	.string "have any chance of beating you.$"

BattlePyramid_Text_SevenTrainersRemaining6::
# 498 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the seven\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_SixTrainersRemaining6::
# 502 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the six\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_FiveTrainersRemaining6::
# 506 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the five\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_FourTrainersRemaining6::
# 510 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the four\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_ThreeTrainersRemaining6::
# 514 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the three\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_TwoTrainersRemaining6::
# 518 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the two\n"
	.string "remaining TRAINERS?$"

BattlePyramid_Text_OneTrainersRemaining6::
# 522 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "Can you keep winning against the last\n"
	.string "remaining TRAINER?$"

BattlePyramid_Text_ZeroTrainersRemaining6::
# 526 "data/maps/BattleFrontier_BattlePyramidFloor/scripts.pory"
	.string "There aren't any TRAINERS left that\n"
	.string "can take you on now…$"
