CeladonCity_GameCorner_PrizeRoom_MapScripts::
	.byte 0


CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
# 5 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "I sure do fancy that PORYGON! But, it's\n"
	.string "hard to win at slots!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
# 9 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "Gahaha! I raked it in today! If only\n"
	.string "every day were like this…$"

CeladonCity_GameCorner_PrizeRoom_Text_CoinCaseRequired::
# 13 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "A COIN CASE is required…$"

CeladonCity_GameCorner_PrizeRoom_Text_WeExchangeCoinsForPrizes::
# 17 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "We exchange your COINS for prizes.$"

CeladonCity_GameCorner_PrizeRoom_Text_WhichPrize::
# 21 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "Which prize would you like?$"

CeladonCity_GameCorner_PrizeRoom_Text_HereYouGo::
# 25 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "はい どうぞ$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantPrize::
# 29 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "So, you want the {STR_VAR_1}?$"

CeladonCity_GameCorner_PrizeRoom_Text_YouWantTM::
# 33 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "Okay, a TM of {STR_VAR_2} is what\n"
	.string "you want?$"

CeladonCity_GameCorner_PrizeRoom_Text_NeedMoreCoins::
# 37 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "Sorry, you'll need more COINS than that.$"

CeladonCity_GameCorner_PrizeRoom_Text_OopsNotEnoughRoom::
# 41 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "おきゃくさん もう もてないよ$"

CeladonCity_GameCorner_PrizeRoom_Text_OhFineThen::
# 45 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "あっ そう$"
