CeladonCity_GameCorner_PrizeRoom_MapScripts::
	.byte 0


CeladonCity_GameCorner_PrizeRoom_EventScript_BaldingMan::
# 5 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon, MSGBOX_NPC
	end


CeladonCity_GameCorner_PrizeRoom_EventScript_OldMan::
# 10 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	msgbox CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday, MSGBOX_NPC
	end


CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkItems::
	end


CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkMons::
	end


CeladonCity_GameCorner_PrizeRoom_EventScript_PrizeClerkTMs::
	end


CeladonCity_GameCorner_PrizeRoom_Text_FancyThatPorygon::
# 27 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "I sure do fancy that PORYGON!\n"
	.string "But, it's hard to win at slots!$"

CeladonCity_GameCorner_PrizeRoom_Text_RakedItInToday::
# 31 "data/maps/CeladonCity_GameCorner_PrizeRoom/scripts.pory"
	.string "Gahaha! I raked it in today!\n"
	.string "If only every day were like this…$"
