SixIsland_PatternBush_MapScripts::
	.byte 0


SixIsland_PatternBush_EventScript_Allison::
# 5 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_PKMN_BREEDER_ALLISON, SixIsland_PatternBush_Text_AllisonIntro, SixIsland_PatternBush_Text_AllisonDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_AllisonPostBattle
	return


SixIsland_PatternBush_EventScript_Bethany::
# 10 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_PKMN_BREEDER_BETHANY, SixIsland_PatternBush_Text_BethanyIntro, SixIsland_PatternBush_Text_BethanyDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_BethanyPostBattle
	return


SixIsland_PatternBush_EventScript_Cordell::
# 15 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_YOUNGSTER_CORDELL, SixIsland_PatternBush_Text_CordellIntro, SixIsland_PatternBush_Text_CordellDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_CordellPostBattle
	return


SixIsland_PatternBush_EventScript_Dalia::
# 20 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_LASS_DALIA, SixIsland_PatternBush_Text_DaliaIntro, SixIsland_PatternBush_Text_DaliaDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_DaliaPostBattle
	return


SixIsland_PatternBush_EventScript_Garret::
# 25 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_BUG_CATCHER_GARRET, SixIsland_PatternBush_Text_GarretIntro, SixIsland_PatternBush_Text_GarretDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_GarretPostBattle
	return


SixIsland_PatternBush_EventScript_Joana::
# 30 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_LASS_JOANA, SixIsland_PatternBush_Text_JoanaIntro, SixIsland_PatternBush_Text_JoanaDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_JoanaPostBattle
	return


SixIsland_PatternBush_EventScript_Jonah::
# 35 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_BUG_CATCHER_JONAH, SixIsland_PatternBush_Text_JonahIntro, SixIsland_PatternBush_Text_JonahDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_JonahPostBattle
	return


SixIsland_PatternBush_EventScript_Layton::
# 40 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_RUIN_MANIAC_LAYTON, SixIsland_PatternBush_Text_LaytonIntro, SixIsland_PatternBush_Text_LaytonDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_LaytonPostBattle
	return


SixIsland_PatternBush_EventScript_Marcy::
# 45 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_PICNICKER_MARCY, SixIsland_PatternBush_Text_MarcyIntro, SixIsland_PatternBush_Text_MarcyDefeat, Text_NotEnoughMonsForDoubleBattle
# 46 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_MarcyPostBattle
	return


SixIsland_PatternBush_EventScript_Nash::
# 50 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_YOUNGSTER_NASH, SixIsland_PatternBush_Text_NashIntro, SixIsland_PatternBush_Text_NashDefeat, Text_NotEnoughMonsForDoubleBattle
# 51 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_NashPostBattle
	return


SixIsland_PatternBush_EventScript_Riley::
# 55 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_CAMPER_RILEY, SixIsland_PatternBush_Text_RileyIntro, SixIsland_PatternBush_Text_RileyDefeat, Text_NotEnoughMonsForDoubleBattle
# 56 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_RileyPostBattle
	return


SixIsland_PatternBush_EventScript_Vance::
# 60 "data/maps/SixIsland_PatternBush/scripts.pory"
	trainerbattle_double TRAINER_BUG_CATCHER_VANCE, SixIsland_PatternBush_Text_VanceIntro, SixIsland_PatternBush_Text_VanceDefeat, Text_NotEnoughMonsForDoubleBattle
# 61 "data/maps/SixIsland_PatternBush/scripts.pory"
	msgbox SixIsland_PatternBush_Text_VancePostBattle
	return


SixIsland_PatternBush_Text_AllisonDefeat::
# 66 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_AllisonDefeat$"

SixIsland_PatternBush_Text_AllisonIntro::
# 70 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_AllisonIntro$"

SixIsland_PatternBush_Text_AllisonPostBattle::
# 74 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_AllisonPostBattle$"

SixIsland_PatternBush_Text_BethanyDefeat::
# 78 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_BethanyDefeat$"

SixIsland_PatternBush_Text_BethanyIntro::
# 82 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_BethanyIntro$"

SixIsland_PatternBush_Text_BethanyPostBattle::
# 86 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_BethanyPostBattle$"

SixIsland_PatternBush_Text_CordellDefeat::
# 90 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_CordellDefeat$"

SixIsland_PatternBush_Text_CordellIntro::
# 94 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_CordellIntro$"

SixIsland_PatternBush_Text_CordellPostBattle::
# 98 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_CordellPostBattle$"

SixIsland_PatternBush_Text_DaliaDefeat::
# 102 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_DaliaDefeat$"

SixIsland_PatternBush_Text_DaliaIntro::
# 106 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_DaliaIntro$"

SixIsland_PatternBush_Text_DaliaPostBattle::
# 110 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_DaliaPostBattle$"

SixIsland_PatternBush_Text_GarretDefeat::
# 114 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_GarretDefeat$"

SixIsland_PatternBush_Text_GarretIntro::
# 118 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_GarretIntro$"

SixIsland_PatternBush_Text_GarretPostBattle::
# 122 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_GarretPostBattle$"

SixIsland_PatternBush_Text_JoanaDefeat::
# 126 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JoanaDefeat$"

SixIsland_PatternBush_Text_JoanaIntro::
# 130 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JoanaIntro$"

SixIsland_PatternBush_Text_JoanaPostBattle::
# 134 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JoanaPostBattle$"

SixIsland_PatternBush_Text_JonahDefeat::
# 138 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JonahDefeat$"

SixIsland_PatternBush_Text_JonahIntro::
# 142 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JonahIntro$"

SixIsland_PatternBush_Text_JonahPostBattle::
# 146 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_JonahPostBattle$"

SixIsland_PatternBush_Text_LaytonDefeat::
# 150 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_LaytonDefeat$"

SixIsland_PatternBush_Text_LaytonIntro::
# 154 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_LaytonIntro$"

SixIsland_PatternBush_Text_LaytonPostBattle::
# 158 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_LaytonPostBattle$"

SixIsland_PatternBush_Text_MarcyDefeat::
# 162 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_MarcyDefeat$"

SixIsland_PatternBush_Text_MarcyIntro::
# 166 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_MarcyIntro$"

SixIsland_PatternBush_Text_MarcyPostBattle::
# 170 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_MarcyPostBattle$"

SixIsland_PatternBush_Text_NashDefeat::
# 174 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_NashDefeat$"

SixIsland_PatternBush_Text_NashIntro::
# 178 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_NashIntro$"

SixIsland_PatternBush_Text_NashPostBattle::
# 182 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_NashPostBattle$"

SixIsland_PatternBush_Text_RileyDefeat::
# 186 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_RileyDefeat$"

SixIsland_PatternBush_Text_RileyIntro::
# 190 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_RileyIntro$"

SixIsland_PatternBush_Text_RileyPostBattle::
# 194 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_RileyPostBattle$"

SixIsland_PatternBush_Text_VanceDefeat::
# 198 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_VanceDefeat$"

SixIsland_PatternBush_Text_VanceIntro::
# 202 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_VanceIntro$"

SixIsland_PatternBush_Text_VancePostBattle::
# 206 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Placeholder text for\n"
	.string "SixIsland_PatternBush_Text_VancePostBattle$"
