SixIsland_PatternBush_MapScripts::
# 2 "data/maps/SixIsland_PatternBush/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SixIsland_PatternBush_OnTransition
	.byte 0


SixIsland_PatternBush_Text_BethanyIntro::
# 6 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm curious, how do you raise your\n"
	.string "POKMON?$"

SixIsland_PatternBush_Text_BethanyDefeat::
# 10 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "You raise your POKMON with a whole lot\n"
	.string "of love!$"

SixIsland_PatternBush_Text_BethanyPostBattle::
# 14 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "In the same way your mother raised you\n"
	.string "full of love, you should raise\l"
	.string "your POKMON.$"

SixIsland_PatternBush_Text_AllisonIntro::
# 18 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm working to preserve the natural\n"
	.string "ecology of POKMON here.$"

SixIsland_PatternBush_Text_AllisonDefeat::
# 22 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Oh, for someone so young, you are\n"
	.string "tremendous!$"

SixIsland_PatternBush_Text_AllisonPostBattle::
# 26 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm not saying that you shouldn't catch\n"
	.string "POKMON.\p"
	.string "I just want people to raise their\n"
	.string "POKMON responsibly.$"

SixIsland_PatternBush_Text_GarretIntro::
# 30 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I caught a BUG POKMON that lives only\n"
	.string "around here!$"

SixIsland_PatternBush_Text_GarretDefeat::
# 34 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Heheh Isn't my POKMON awesome?$"

SixIsland_PatternBush_Text_GarretPostBattle::
# 38 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "There's a girl near the BUSH who\n"
	.string "measures HERACROSS for TRAINERS.$"

SixIsland_PatternBush_Text_JonahIntro::
# 42 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "You know, it just doesn't feel right if I\n"
	.string "don't use BUG POKMON.$"

SixIsland_PatternBush_Text_JonahDefeat::
# 46 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "It's okay, losing is a fun part of\n"
	.string "POKMON's appeal, too.$"

SixIsland_PatternBush_Text_JonahPostBattle::
# 50 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "By the way, appeal is a weird word, if\n"
	.string "you think about it.\p"
	.string "Like, is it like an orange peel? Or like a\n"
	.string "ringing bell?$"

SixIsland_PatternBush_Text_VanceIntro::
# 54 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Yeah, yeah, yeah! Look at all the BUG\n"
	.string "POKMON!$"

SixIsland_PatternBush_Text_VanceDefeat::
# 58 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I got beat while I was still busy\n"
	.string "celebrating!$"

SixIsland_PatternBush_Text_VancePostBattle::
# 62 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm going to bring my little brother here\n"
	.string "next time.$"

SixIsland_PatternBush_Text_NashIntro::
# 66 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Look, look! There are funny patterns on\n"
	.string "the ground.$"

SixIsland_PatternBush_Text_NashDefeat::
# 70 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Super awesome!$"

SixIsland_PatternBush_Text_NashPostBattle::
# 74 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "The funny patterns on the ground\p"
	.string "They look like the patterns on my\n"
	.string "grandpa's clothes.$"

SixIsland_PatternBush_Text_CordellIntro::
# 78 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I bet you think I'm just some guy, don't\n"
	.string "you, eh?$"

SixIsland_PatternBush_Text_CordellDefeat::
# 82 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I bet you think I'm weak, don't you, eh?$"

SixIsland_PatternBush_Text_CordellPostBattle::
# 86 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Ayup, you townies come around all so\n"
	.string "dandy with a hat that flashy\p"
	.string "How about giving me that?$"

SixIsland_PatternBush_Text_DaliaIntro::
# 90 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Take a deep breath. Isn't the air\n"
	.string "delicious?$"

SixIsland_PatternBush_Text_DaliaDefeat::
# 94 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "If you'd like, I can teach you how to\n"
	.string "breathe properly.$"

SixIsland_PatternBush_Text_DaliaPostBattle::
# 98 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "First, exhale. Blow everything out.\p"
	.string "When you can't exhale anymore, inhale\n"
	.string "the clean air!\p"
	.string "Isn't it refreshing?$"

SixIsland_PatternBush_Text_JoanaIntro::
# 102 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I love BUG POKMON. That's why I'm here\n"
	.string "all the time.\p"
	.string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_JoanaDefeat::
# 106 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I lost, but I'm still laughing. Am I the\n"
	.string "only girl like that?$"

SixIsland_PatternBush_Text_JoanaPostBattle::
# 110 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm going to keep on collecting BUG\n"
	.string "POKMON.\p"
	.string "Am I the only girl like that?$"

SixIsland_PatternBush_Text_RileyIntro::
# 114 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "This is a good spot. I'll pitch my tent\n"
	.string "here.$"

SixIsland_PatternBush_Text_RileyDefeat::
# 118 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Wimped out$"

SixIsland_PatternBush_Text_RileyPostBattle::
# 122 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "I'm going to observe the night sky here.$"

SixIsland_PatternBush_Text_MarcyIntro::
# 126 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Oh, yuck! I think a bug stung me!$"

SixIsland_PatternBush_Text_MarcyDefeat::
# 130 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "It wasn't a bug. I cut my shin on some\n"
	.string "grass.$"

SixIsland_PatternBush_Text_MarcyPostBattle::
# 134 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "A little cut like that A little spit's\n"
	.string "enough to cure it!$"

SixIsland_PatternBush_Text_LaytonIntro::
# 138 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Have you noticed something odd about\n"
	.string "these parts?$"

SixIsland_PatternBush_Text_LaytonDefeat::
# 142 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "Have you taken a good look around your\n"
	.string "feet?$"

SixIsland_PatternBush_Text_LaytonPostBattle::
# 146 "data/maps/SixIsland_PatternBush/scripts.pory"
	.string "There are places here in PATTERN BUSH\n"
	.string "where grass won't grow.\p"
	.string "What could be the cause of such a\n"
	.string "phenomenon?$"
