BlackthornCity_MoveDeletersHouse_MapScripts::
	.byte 0


BlackthornCity_MoveDeletersHouse_EventScript_SmithNPC1::
# 5 "data/maps/BlackthornCity_MoveDeletersHouse/scripts.pory"
	msgbox BlackthornCity_MoveDeletersHouse_Text_SmithNPC1, MSGBOX_NPC
	end


BlackthornCity_MoveDeletersHouse_EventScript_SmithNPC2::
# 14 "data/maps/BlackthornCity_MoveDeletersHouse/scripts.pory"
	msgbox BlackthornCity_MoveDeletersHouse_Text_SmithNPC2, MSGBOX_NPC
	end


BlackthornCity_MoveDeletersHouse_Text_SmithNPC1::
# 9 "data/maps/BlackthornCity_MoveDeletersHouse/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

BlackthornCity_MoveDeletersHouse_Text_SmithNPC2::
# 18 "data/maps/BlackthornCity_MoveDeletersHouse/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
