SilphCo_10F_MapScripts::
# 2 "data/maps/SilphCo_10F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_10F_OnLoad
	.byte 0


SilphCo_10F_Text_GruntIntro::
# 6 "data/maps/SilphCo_10F/scripts.pory"
	.string "Welcome to 10F! So good of you to join\n"
	.string "me!$"

SilphCo_10F_Text_GruntDefeat::
# 10 "data/maps/SilphCo_10F/scripts.pory"
	.string "I'm stunned!$"

SilphCo_10F_Text_GruntPostBattle::
# 14 "data/maps/SilphCo_10F/scripts.pory"
	.string "Nice try, but the boardroom is up one\n"
	.string "more floor.$"

SilphCo_10F_Text_TravisIntro::
# 18 "data/maps/SilphCo_10F/scripts.pory"
	.string "Enough of your silly games!$"

SilphCo_10F_Text_TravisDefeat::
# 22 "data/maps/SilphCo_10F/scripts.pory"
	.string "No continues left!$"

SilphCo_10F_Text_TravisPostBattle::
# 26 "data/maps/SilphCo_10F/scripts.pory"
	.string "Are you satisfied with beating me? Then\n"
	.string "go on home!$"

SilphCo_10F_Text_WaaaImScared::
# 30 "data/maps/SilphCo_10F/scripts.pory"
	.string "Waaaaa! I'm scared!$"

SilphCo_10F_Text_KeepMeCryingASecret::
# 34 "data/maps/SilphCo_10F/scripts.pory"
	.string "About me crying… Please keep it a\n"
	.string "secret.$"

SilphCo_10F_Text_FloorSign::
# 38 "data/maps/SilphCo_10F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 10F$"
