SurvivalArea_MapScripts::
	.byte 0


SurvivalArea_EventScript_Sign1::
# 6 "data/maps/SurvivalArea/scripts.pory"
	msgbox SurvivalArea_Text_Sign1, MSGBOX_SIGN
	end


SurvivalArea_EventScript_SmithNPC1::
# 15 "data/maps/SurvivalArea/scripts.pory"
	msgbox SurvivalArea_Text_SmithNPC1, MSGBOX_NPC
	end


SurvivalArea_EventScript_SmithNPC2::
# 24 "data/maps/SurvivalArea/scripts.pory"
	msgbox SurvivalArea_Text_SmithNPC2, MSGBOX_NPC
	end


SurvivalArea_EventScript_SmithNPC3::
# 33 "data/maps/SurvivalArea/scripts.pory"
	msgbox SurvivalArea_Text_SmithNPC3, MSGBOX_NPC
	end


SurvivalArea_Text_Sign1::
# 10 "data/maps/SurvivalArea/scripts.pory"
	.string "SurvivalArea Sign 1$"

SurvivalArea_Text_SmithNPC1::
# 19 "data/maps/SurvivalArea/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SurvivalArea_Text_SmithNPC2::
# 28 "data/maps/SurvivalArea/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SurvivalArea_Text_SmithNPC3::
# 37 "data/maps/SurvivalArea/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
