JaggedPass_MapScripts::
# 2 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, JaggedPass_OnResume
# 3 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, JaggedPass_OnTransition
# 4 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, JaggedPass_OnLoad
	.byte 0


JaggedPass_MapScripts::
# 8 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, JaggedPass_OnResume
# 9 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, JaggedPass_OnTransition
# 10 "data/maps/JaggedPass/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, JaggedPass_OnLoad
	return


JaggedPass_Text_EricIntro::
# 14 "data/maps/JaggedPass/scripts.pory"
	.string "MT. CHIMNEY's JAGGED PASS…\p"
	.string "Now this is what I've always wanted in a\n"
	.string "mountain.\p"
	.string "This jagged bumpiness… It rocks my\n"
	.string "soul!$"

JaggedPass_Text_EricDefeat::
# 18 "data/maps/JaggedPass/scripts.pory"
	.string "Losing left me bitter!$"

JaggedPass_Text_EricPostBattle::
# 22 "data/maps/JaggedPass/scripts.pory"
	.string "Yes, I did lose at POKéMON…\p"
	.string "But, when it comes to the love of the\n"
	.string "mountains, I have you beat!$"

JaggedPass_Text_DianaIntro::
# 26 "data/maps/JaggedPass/scripts.pory"
	.string "This place isn't your casual hike. It's\n"
	.string "not suited for a picnic.$"

JaggedPass_Text_DianaDefeat::
# 30 "data/maps/JaggedPass/scripts.pory"
	.string "Ohhh, no! The ground is too bumpy…$"

JaggedPass_Text_DianaPostBattle::
# 34 "data/maps/JaggedPass/scripts.pory"
	.string "Did you know?\p"
	.string "Some people cleverly ride their bicycles\n"
	.string "up this horribly bumpy pass.$"

JaggedPass_Text_DianaRegister::
# 38 "data/maps/JaggedPass/scripts.pory"
	.string "Will you ever be back in this area? If\n"
	.string "you do return, I'd like a rematch.$"

JaggedPass_Text_DianaRematchIntro::
# 42 "data/maps/JaggedPass/scripts.pory"
	.string "Picnics are fun wherever you go. Just\n"
	.string "like POKéMON!$"

JaggedPass_Text_DianaRematchDefeat::
# 46 "data/maps/JaggedPass/scripts.pory"
	.string "I only lost because the ground is too\n"
	.string "bumpy!$"

JaggedPass_Text_DianaPostRematch::
# 50 "data/maps/JaggedPass/scripts.pory"
	.string "I'll forget about losing and just enjoy\n"
	.string "this bumpy hike.$"

JaggedPass_Text_EthanIntro::
# 54 "data/maps/JaggedPass/scripts.pory"
	.string "JAGGED PASS is hard to walk on. It's a\n"
	.string "good place for training.$"

JaggedPass_Text_EthanDefeat::
# 58 "data/maps/JaggedPass/scripts.pory"
	.string "It was all over while we were still\n"
	.string "trying to find a good footing…$"

JaggedPass_Text_EthanPostBattle::
# 62 "data/maps/JaggedPass/scripts.pory"
	.string "If I had an ACRO BIKE, I'd be able to\n"
	.string "jump ledges.$"

JaggedPass_Text_EthanRegister::
# 66 "data/maps/JaggedPass/scripts.pory"
	.string "When I get more used to this bumpiness,\n"
	.string "I'll be sure to win!\p"
	.string "Can you register me in your POKéNAV?$"

JaggedPass_Text_EthanRematchIntro::
# 70 "data/maps/JaggedPass/scripts.pory"
	.string "I got used to this bumpiness. I sing\n"
	.string "while I climb now.$"

JaggedPass_Text_EthanRematchDefeat::
# 74 "data/maps/JaggedPass/scripts.pory"
	.string "It's still not easy to battle on this\n"
	.string "bumpy ground…$"

JaggedPass_Text_EthanPostRematch::
# 78 "data/maps/JaggedPass/scripts.pory"
	.string "I should get an ACRO BIKE from RYDEL in\n"
	.string "MAUVILLE CITY…$"

JaggedPass_Text_GruntIntro::
# 82 "data/maps/JaggedPass/scripts.pory"
	.string "Wah! What are you doing here?\p"
	.string "What am I doing in a place like this?\p"
	.string "What business is it of yours?$"

JaggedPass_Text_GruntDefeat::
# 86 "data/maps/JaggedPass/scripts.pory"
	.string "Urrrgh…\p"
	.string "I should've ducked into our HIDEOUT\n"
	.string "right away…$"

JaggedPass_Text_GoWhereverYouWant::
# 90 "data/maps/JaggedPass/scripts.pory"
	.string "Okay, oh-kay! I admit it--you're\n"
	.string "strong!\p"
	.string "Don't worry about me. Go wherever you\n"
	.string "want!$"

JaggedPass_Text_BoulderShakingInResponseToEmblem::
# 94 "data/maps/JaggedPass/scripts.pory"
	.string "Oh! This boulder is shaking in response\n"
	.string "to the MAGMA EMBLEM!$"

JaggedPass_Text_JulioIntro::
# 98 "data/maps/JaggedPass/scripts.pory"
	.string "Aiyeeh! It's awfully scary to shoot\n"
	.string "down the mountain in one go!$"

JaggedPass_Text_JulioDefeat::
# 102 "data/maps/JaggedPass/scripts.pory"
	.string "I feel like I'm falling apart…$"

JaggedPass_Text_JulioPostBattle::
# 106 "data/maps/JaggedPass/scripts.pory"
	.string "My bicycle bounced around so much, my\n"
	.string "rear end's sore…$"

JaggedPass_Text_AutumnIntro::
# 110 "data/maps/JaggedPass/scripts.pory"
	.string "I climb this hill every day. I have\n"
	.string "confidence in my strength!$"

JaggedPass_Text_AutumnDefeat::
# 114 "data/maps/JaggedPass/scripts.pory"
	.string "Hmm… What went wrong?$"

JaggedPass_Text_AutumnPostBattle::
# 118 "data/maps/JaggedPass/scripts.pory"
	.string "What is that odd rock protrusion a\n"
	.string "little up the hill from here?$"
