PetalburgCity_Gym_MapScripts::
# 2 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PetalburgCity_Gym_OnLoad
# 3 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_Gym_OnTransition
# 4 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PetalburgCity_Gym_OnWarp
# 5 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_Gym_OnFrame
	.byte 0


PetalburgCity_Gym_MapScripts::
# 9 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PetalburgCity_Gym_OnLoad
# 10 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PetalburgCity_Gym_OnTransition
# 11 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PetalburgCity_Gym_OnWarp
# 12 "data/maps/PetalburgCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PetalburgCity_Gym_OnFrame
	return


PetalburgCity_Gym_Text_DadYoureHereWithYourPokemon::
# 16 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm?\p"
	.string "Well, if it isn't {PLAYER}! So you're all\n"
	.string "finished moving in?\p"
	.string "I'm surprised that you managed to get\n"
	.string "here by yourself.\p"
	.string "Oh, I see. You're with your POKéMON.\p"
	.string "Hm… Then I guess you're going to become\n"
	.string "a TRAINER like me, {PLAYER}.\p"
	.string "That's great news! I'll be looking\n"
	.string "forward to it!$"

PetalburgCity_Gym_Text_WallyIdLikeAPokemon::
# 20 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Um… I… I'd like to get a POKéMON,\n"
	.string "please…$"

PetalburgCity_Gym_Text_DadOhYoureWallyRight::
# 24 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm? You're… Uh… Oh, right. You're\n"
	.string "WALLY, right?$"

PetalburgCity_Gym_Text_WallyIveNeverCaughtAPokemon::
# 28 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "WALLY: I'm going to go stay with my\n"
	.string "relatives in VERDANTURF TOWN.\p"
	.string "I thought I would be lonely by myself,\n"
	.string "so I wanted to take a POKéMON along.\p"
	.string "But I've never caught a POKéMON before.\n"
	.string "I don't know how…$"

PetalburgCity_Gym_Text_DadHmISee::
# 32 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm. I see.$"

PetalburgCity_Gym_Text_DadPlayerGoWithWally::
# 36 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}, you heard that, right?\p"
	.string "Go with WALLY and make sure that he\n"
	.string "safely catches a POKéMON.$"

PetalburgCity_Gym_Text_IllLoanYouMyZigzagoon::
# 40 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "WALLY, here, I'll loan you my POKéMON.\p"
	.string "WALLY received a ZIGZAGOON!$"

PetalburgCity_Gym_Text_WallyThankYouAndDadGivesPokeBall::
# 44 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "WALLY: Oh, wow! A POKéMON!\p"
	.string "DAD: Hm. I'll give you a POKé BALL, too.\n"
	.string "Go for it!\p"
	.string "WALLY received a POKé BALL!$"

PetalburgCity_Gym_Text_WallyOhWowThankYou::
# 48 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "WALLY: Oh, wow! Thank you!$"

PetalburgCity_Gym_Text_WouldYouReallyComeWithMe::
# 52 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "{PLAYER}… Would you really come with\n"
	.string "me?$"

PetalburgCity_Gym_Text_DadSoDidItWorkOut::
# 56 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: So, did it work out?$"

PetalburgCity_Gym_Text_WallyThankYouBye::
# 60 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "WALLY: Thank you, yes, it did. Here's\n"
	.string "your POKéMON back.\p"
	.string "{PLAYER}, thank you for coming along\n"
	.string "with me.\p"
	.string "You two are why I was able to catch my\n"
	.string "POKéMON.\p"
	.string "I promise I'll take really good care of\n"
	.string "it.\p"
	.string "Oh! My mom's waiting for me, so I have to\n"
	.string "go!\p"
	.string "Bye, {PLAYER}!$"

PetalburgCity_Gym_Text_DadGoCollectBadges::
# 64 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Now…\p"
	.string "{PLAYER}, if you want to become a\n"
	.string "strong TRAINER, here's my advice.\p"
	.string "Head for RUSTBORO CITY beyond this\n"
	.string "town.\p"
	.string "There, you should challenge the GYM\n"
	.string "LEADER, ROXANNE.\p"
	.string "After her, go on to other POKéMON GYMS\n"
	.string "and defeat their LEADERS.\p"
	.string "Collect BADGES from them, understood?\p"
	.string "Of course, I'm a GYM LEADER, too. We'll\n"
	.string "battle one day, {PLAYER}.\p"
	.string "But that's only after you become\n"
	.string "stronger.$"

PetalburgCity_Gym_Text_NormanGoToRustboro::
# 68 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm? Aren't you going to the\n"
	.string "POKéMON GYM in RUSTBORO CITY?\p"
	.string "There's no challenge for me to battle a\n"
	.string "greenhorn TRAINER.\p"
	.string "{PLAYER}, I want you to challenge me\n"
	.string "when you become a lot stronger.\p"
	.string "I'll battle you, {PLAYER}, when you\n"
	.string "can show me four GYM BADGES, okay?$"

PetalburgCity_Gym_Text_NormanGoToDewford::
# 72 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: I see… So, you've beaten the GYM\n"
	.string "LEADER in RUSTBORO CITY.\p"
	.string "But there are many more TRAINERS who\n"
	.string "are stronger than you, {PLAYER}.\p"
	.string "Across the sea in DEWFORD TOWN is a GYM\n"
	.string "LEADER named BRAWLY.\p"
	.string "You should go challenge him.$"

PetalburgCity_Gym_Text_YouHaveGottenStronger::
# 76 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm… {PLAYER}, you have gotten\n"
	.string "stronger.\p"
	.string "I can tell by the number of BADGES that\n"
	.string "you've earned.$"

PetalburgCity_Gym_Text_NormanIntro::
# 80 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm… So, you did get four GYM\n"
	.string "BADGES.\p"
	.string "Fine, as I promised, we will have a\n"
	.string "POKéMON battle.\p"
	.string "{PLAYER}…\p"
	.string "I'm so happy that I can have a real\n"
	.string "battle with my own child.\p"
	.string "But, a battle is a battle!\p"
	.string "I will do everything in my power as a GYM\n"
	.string "LEADER to win.\p"
	.string "{PLAYER}, you'd better give it your\n"
	.string "best shot, too!$"

PetalburgCity_Gym_Text_NormanDefeat::
# 84 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "…\p"
	.string "I… I can't…\p"
	.string "I can't believe it. {PLAYER}…\p"
	.string "I lost to {PLAYER}?\p"
	.string "But, rules are rules! Here, take this.$"

PetalburgCity_Gym_Text_ReceivedBalanceBadge::
# 88 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "{PLAYER} received the BALANCE BADGE\n"
	.string "from DAD!$"

PetalburgCity_Gym_Text_ExplainBalanceBadgeTakeThis::
# 92 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: With that BADGE, the DEFENSE of\n"
	.string "all your POKéMON will increase.\p"
	.string "POKéMON that know the HM move SURF will\n"
	.string "be able to travel over water.\p"
	.string "This is my gift to you. {PLAYER}, I'm\n"
	.string "sure you can use it correctly.$"

PetalburgCity_Gym_Text_ExplainFacade::
# 96 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: TM42 contains FACADE.\p"
	.string "It doubles the power of moves if the\n"
	.string "POKéMON is poisoned, paralyzed,\l"
	.string "or burned.\p"
	.string "It might be able to turn a bad situation\n"
	.string "into an advantage.$"

PetalburgCity_Gym_Text_DadHappyAndSad::
# 100 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: As the GYM LEADER, I can't express\n"
	.string "how upset I am…\p"
	.string "But as a father, it makes me both happy\n"
	.string "and a little sad. It's odd…$"

PetalburgCity_Gym_Text_PleaseComeWithMe::
# 104 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Ah, there you are, {PLAYER}{KUN}!\p"
	.string "Please come with me. I have something I\n"
	.string "want you to have.$"

PetalburgCity_Gym_Text_LetMeBorrowPlayer::
# 108 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "NORMAN, you don't mind, do you?\p"
	.string "Let me borrow your {PLAYER}{KUN} for a\n"
	.string "minute or two.$"

PetalburgCity_Gym_Text_DadGoingToKeepTraining::
# 112 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}, you should go visit\n"
	.string "your mother every so often.\p"
	.string "I'm going to stay here and redouble my\n"
	.string "training.\p"
	.string "It would bother me as a TRAINER to not\n"
	.string "avenge my loss to you, {PLAYER}!$"

PetalburgCity_Gym_Text_DadNoAmountOfTrainingIsEnough::
# 116 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}, how are things going?\p"
	.string "The world of POKéMON is deep.\p"
	.string "I honestly think that no amount of\n"
	.string "training would ever be enough.$"

PetalburgCity_Gym_Text_GymGuideAdvice::
# 120 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Hey, how's it going, CHAMPION- bound\n"
	.string "{PLAYER}?\p"
	.string "The doors in this GYM open when you\n"
	.string "beat the awaiting TRAINERS.\p"
	.string "Whoops! The doors in this room are\n"
	.string "already open, so don't attack me!\p"
	.string "The TRAINERS of PETALBURG GYM use all\n"
	.string "kinds of items.\p"
	.string "The door at the left leads to the SPEED\n"
	.string "ROOM.\p"
	.string "The door at the right leads to the\n"
	.string "ACCURACY ROOM.\p"
	.string "The room's name will be on the door, so\n"
	.string "choose carefully.\p"
	.string "Once you've chosen the door… Well, hey,\n"
	.string "go for it!$"

PetalburgCity_Gym_Text_GymGuidePostVictory::
# 124 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "{PLAYER}! Whoa! You've overcome even\n"
	.string "your own father!\p"
	.string "Like, whoa! What a stunning turn of\n"
	.string "events!$"

PetalburgCity_Gym_Text_RandallIntro::
# 128 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "The ability to attack before the\n"
	.string "opponent…\p"
	.string "Just that alone puts me at a great\n"
	.string "advantage, don't you agree?$"

PetalburgCity_Gym_Text_RandallDefeat::
# 132 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "That was a magnificent battle!$"

PetalburgCity_Gym_Text_RandallPostBattle::
# 136 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Go on to the next room where a new\n"
	.string "challenge awaits you.\p"
	.string "At the left is the CONFUSION ROOM.\p"
	.string "The right door leads to the DEFENSE\n"
	.string "ROOM.$"

PetalburgCity_Gym_Text_RandallPostBadge::
# 140 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Whomever you beat, and whomever you\n"
	.string "may lose to, you never shirk from\l"
	.string "training yourself and your POKéMON.\p"
	.string "That's what I think being a GYM LEADER\n"
	.string "is all about.$"

PetalburgCity_Gym_Text_ParkerIntro::
# 144 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "This is the CONFUSION ROOM.\p"
	.string "Let me see how well bonded you are with\n"
	.string "your POKéMON!$"

PetalburgCity_Gym_Text_ParkerDefeat::
# 148 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I couldn't confuse your team enough…\n"
	.string "You share a strong bond together.$"

PetalburgCity_Gym_Text_ParkerPostBattle::
# 152 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "The next room is the STRENGTH ROOM. Can\n"
	.string "you withstand brute force?$"

PetalburgCity_Gym_Text_ParkerPostBadge::
# 156 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "After you beat our LEADER, the training\n"
	.string "has become a lot tougher.$"

PetalburgCity_Gym_Text_GeorgeIntro::
# 160 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Just when you think you're going to win,\n"
	.string "your opponent restores HP…\p"
	.string "Can you just imagine how awful that\n"
	.string "must feel?\p"
	.string "I'll show you exactly how awful it feels!$"

PetalburgCity_Gym_Text_GeorgeDefeat::
# 164 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I couldn't restore HP enough… What\n"
	.string "ATTACK power…$"

PetalburgCity_Gym_Text_GeorgePostBattle::
# 168 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I should have expected no less from our\n"
	.string "LEADER's kid.\p"
	.string "No, wait! A TRAINER's abilities are\n"
	.string "earned only through effort.\p"
	.string "I lost because my own efforts weren't\n"
	.string "enough.\p"
	.string "Go on! The ONE-HIT KO ROOM is next.$"

PetalburgCity_Gym_Text_GeorgePostBadge::
# 172 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I'm going to keep training at GYMS. One\n"
	.string "day, I'll become a LEADER.$"

PetalburgCity_Gym_Text_BerkeIntro::
# 176 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I'm not going to take it easy just\n"
	.string "because you're our LEADER's kid.\p"
	.string "I'll show you how horrid it is for a\n"
	.string "POKéMON to take a critical hit!$"

PetalburgCity_Gym_Text_BerkeDefeat::
# 180 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Your power… You're the real deal.$"

PetalburgCity_Gym_Text_BerkePostBattle::
# 184 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Your father really is strong. He's a\n"
	.string "TRAINER worth my respect.\p"
	.string "And, I sense the same glow coming from\n"
	.string "you as your father.\p"
	.string "I hope that you'll stage a terrific\n"
	.string "battle with your father!$"

PetalburgCity_Gym_Text_BerkePostBadge::
# 188 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Since your dad became the LEADER, the\n"
	.string "TRAINERS of PETALBURG CITY have\l"
	.string "become a lot tougher.$"

PetalburgCity_Gym_Text_MaryIntro::
# 192 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Giggle… This is the ACCURACY ROOM.\p"
	.string "It's pretty nasty when every attack\n"
	.string "lands without fail.$"

PetalburgCity_Gym_Text_MaryDefeat::
# 196 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "You were a cut above me…$"

PetalburgCity_Gym_Text_MaryPostBattle::
# 200 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "There are some even stronger TRAINERS\n"
	.string "waiting for you.\p"
	.string "The left is the DEFENSE ROOM, and the\n"
	.string "right is the RECOVERY ROOM.\p"
	.string "Your POKéMON's ATTACK power will be on\n"
	.string "trial either way.$"

PetalburgCity_Gym_Text_MaryPostBadge::
# 204 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Do you know what we're trying to\n"
	.string "achieve as TRAINERS?\p"
	.string "We're striving to become soul mates\n"
	.string "with our POKéMON.$"

PetalburgCity_Gym_Text_AlexiaIntro::
# 208 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "The higher the DEFENSE, the more\n"
	.string "reckless I can be in attack.$"

PetalburgCity_Gym_Text_AlexiaDefeat::
# 212 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Our defenses weren't enough…$"

PetalburgCity_Gym_Text_AlexiaPostBattle::
# 216 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I think you've taught me a valuable\n"
	.string "lesson here.\p"
	.string "Now, go on! The left door goes to the\n"
	.string "STRENGTH ROOM.\p"
	.string "The right door opens to the ONE-HIT KO\n"
	.string "ROOM.\p"
	.string "Both of them have TRAINERS who are\n"
	.string "skilled at offense.$"

PetalburgCity_Gym_Text_AlexiaPostBadge::
# 220 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Hi! Have you tried using SURF?$"

PetalburgCity_Gym_Text_JodyIntro::
# 224 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Our GYM LEADER told us to go all out and\n"
	.string "beat you.\p"
	.string "Even if you happen to be the LEADER's\n"
	.string "kid!$"

PetalburgCity_Gym_Text_JodyDefeat::
# 228 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "But… I went all out!$"

PetalburgCity_Gym_Text_JodyPostBattle::
# 232 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "The way you use your POKéMON… It's like\n"
	.string "your father's style.\p"
	.string "Go on through! The GYM LEADER, your\n"
	.string "father, is waiting!$"

PetalburgCity_Gym_Text_JodyPostBadge::
# 236 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Sure, it's fine to make your POKéMON\n"
	.string "stronger.\p"
	.string "But what decides the winner?\p"
	.string "Why, it's the feelings TRAINERS have\n"
	.string "for their POKéMON.$"

PetalburgCity_Gym_Text_DoorAppearsLocked::
# 240 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "This door appears to be locked right\n"
	.string "now…$"

PetalburgCity_Gym_Text_EnterSpeedRoom::
# 244 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“SPEED ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_DoorAppearsLocked2::
# 248 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "This door appears to be locked right\n"
	.string "now…$"

PetalburgCity_Gym_Text_EnterAccuracyRoom::
# 252 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“ACCURACY ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterConfusionRoom::
# 256 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“CONFUSION ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterDefenseRoom::
# 260 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“DEFENSE ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterRecoveryRoom::
# 264 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“RECOVERY ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterStrengthRoom::
# 268 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“STRENGTH ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterOHKORoom::
# 272 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“ONE-HIT KO ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterGymLeadersRoom::
# 276 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“GYM LEADER'S ROOM\p"
	.string "“See for yourself what POKéMON await\n"
	.string "you!” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_GymStatue::
# 280 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM$"

PetalburgCity_Gym_Text_GymStatueCertified::
# 284 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM\p"
	.string "NORMAN'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

PetalburgCity_Gym_Text_NormanPreRematch::
# 288 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}… I had a feeling that\n"
	.string "you would come.\p"
	.string "I would never refuse to accept a\n"
	.string "challenge from you.\p"
	.string "You do understand, don't you?\p"
	.string "Inside a GYM, it doesn't matter that we\n"
	.string "are a parent and child.\p"
	.string "…No, because we are parent and child, we\n"
	.string "owe it to each other to do the best\l"
	.string "we can. Isn't that right, {PLAYER}?$"

PetalburgCity_Gym_Text_NormanRematchDefeat::
# 292 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Uh… Haha… Maybe that was going too\n"
	.string "hard…$"

PetalburgCity_Gym_Text_NormanPostRematch::
# 296 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}… What is your dream?\p"
	.string "My dream… Hahaha…\l"
	.string "It has already come true, actually.$"

PetalburgCity_Gym_Text_NormanRematchNeedTwoMons::
# 300 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}… I had a feeling that\n"
	.string "you would come.\p"
	.string "I would never refuse to accept a\n"
	.string "challenge from you.\p"
	.string "You do understand, don't you?\p"
	.string "Inside a GYM, it doesn't matter that we\n"
	.string "are a parent and child.\p"
	.string "Hm? Wait a second, {PLAYER}.\p"
	.string "Do you only have one POKéMON that is\n"
	.string "capable of battle?\p"
	.string "Sorry, but you'll have to come back with\n"
	.string "at least two POKéMON.$"
