PetalburgCity_Gym_MapScripts::
	.byte 0


PetalburgCity_Gym_EventScript_AccuracyRoomDoor::
# 9 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterAccuracyRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_Alexia::
# 16 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_ALEXIA, PetalburgCity_Gym_Text_AlexiaIntro, PetalburgCity_Gym_Text_AlexiaDefeat, Text_NotEnoughMonsForDoubleBattle
# 17 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_AlexiaPostBattle
	return


PetalburgCity_Gym_EventScript_Berke::
# 21 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_BERKE, PetalburgCity_Gym_Text_BerkeIntro, PetalburgCity_Gym_Text_BerkeDefeat, Text_NotEnoughMonsForDoubleBattle
# 22 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_BerkePostBattle
	return


PetalburgCity_Gym_EventScript_ConfusionRoomDoor::
# 30 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterConfusionRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_George::
# 37 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_GEORGE, PetalburgCity_Gym_Text_GeorgeIntro, PetalburgCity_Gym_Text_GeorgeDefeat, Text_NotEnoughMonsForDoubleBattle
# 38 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_GeorgePostBattle
	return


PetalburgCity_Gym_EventScript_GymGuide::
	end


PetalburgCity_Gym_EventScript_Jody::
# 46 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_JODY, PetalburgCity_Gym_Text_JodyIntro, PetalburgCity_Gym_Text_JodyDefeat, Text_NotEnoughMonsForDoubleBattle
# 47 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_JodyPostBattle
	return


PetalburgCity_Gym_EventScript_LeftDefenseRoomDoor::
# 55 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterDefenseRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_LeftGymLeadersRoomDoor::
# 66 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterGymLeadersRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_LeftGymStatue::
	end


PetalburgCity_Gym_EventScript_LeftOHKORoomDoor::
# 84 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterOHKORoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_LeftStrengthRoomDoor::
# 95 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterStrengthRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_Mary::
# 102 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_MARY, PetalburgCity_Gym_Text_MaryIntro, PetalburgCity_Gym_Text_MaryDefeat, Text_NotEnoughMonsForDoubleBattle
# 103 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_MaryPostBattle
	return


PetalburgCity_Gym_EventScript_Norman::
	end


PetalburgCity_Gym_EventScript_Parker::
# 111 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_PARKER, PetalburgCity_Gym_Text_ParkerIntro, PetalburgCity_Gym_Text_ParkerDefeat, Text_NotEnoughMonsForDoubleBattle
# 112 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_ParkerPostBattle
	return


PetalburgCity_Gym_EventScript_Randall::
# 116 "data/maps/PetalburgCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_RANDALL, PetalburgCity_Gym_Text_RandallIntro, PetalburgCity_Gym_Text_RandallDefeat, Text_NotEnoughMonsForDoubleBattle
# 117 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_RandallPostBattle
	return


PetalburgCity_Gym_EventScript_RecoveryRoomDoor::
# 125 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterRecoveryRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_RightDefenseRoomDoor::
# 136 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterDefenseRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_RightGymLeadersRoomDoor::
# 147 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterGymLeadersRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_RightGymStatue::
	end


PetalburgCity_Gym_EventScript_RightOHKORoomDoor::
# 165 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterOHKORoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_RightStrengthRoomDoor::
# 176 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterStrengthRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_EventScript_SpeedRoomDoor::
# 187 "data/maps/PetalburgCity_Gym/scripts.pory"
	msgbox PetalburgCity_Gym_Text_EnterSpeedRoom, MSGBOX_YESNO
	end


PetalburgCity_Gym_Text_EnterRecoveryRoom::
# 194 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“RECOVERY ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterGymLeadersRoom::
# 198 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“GYM LEADER'S ROOM\p"
	.string "“See for yourself what POKéMON await\n"
	.string "you!” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterOHKORoom::
# 202 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“ONE-HIT KO ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterSpeedRoom::
# 206 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“SPEED ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterAccuracyRoom::
# 210 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“ACCURACY ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterConfusionRoom::
# 214 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“CONFUSION ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterStrengthRoom::
# 218 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“STRENGTH ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_EnterDefenseRoom::
# 222 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "“DEFENSE ROOM,” the sign says.\p"
	.string "Do you want to go through?$"

PetalburgCity_Gym_Text_AlexiaDefeat::
# 227 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_AlexiaDefeat$"

PetalburgCity_Gym_Text_AlexiaIntro::
# 231 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_AlexiaIntro$"

PetalburgCity_Gym_Text_AlexiaPostBattle::
# 235 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_AlexiaPostBattle$"

PetalburgCity_Gym_Text_BerkeDefeat::
# 239 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_BerkeDefeat$"

PetalburgCity_Gym_Text_BerkeIntro::
# 243 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_BerkeIntro$"

PetalburgCity_Gym_Text_BerkePostBattle::
# 247 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_BerkePostBattle$"

PetalburgCity_Gym_Text_GeorgeDefeat::
# 251 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_GeorgeDefeat$"

PetalburgCity_Gym_Text_GeorgeIntro::
# 255 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_GeorgeIntro$"

PetalburgCity_Gym_Text_GeorgePostBattle::
# 259 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_GeorgePostBattle$"

PetalburgCity_Gym_Text_JodyDefeat::
# 263 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_JodyDefeat$"

PetalburgCity_Gym_Text_JodyIntro::
# 267 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_JodyIntro$"

PetalburgCity_Gym_Text_JodyPostBattle::
# 271 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_JodyPostBattle$"

PetalburgCity_Gym_Text_MaryDefeat::
# 275 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_MaryDefeat$"

PetalburgCity_Gym_Text_MaryIntro::
# 279 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_MaryIntro$"

PetalburgCity_Gym_Text_MaryPostBattle::
# 283 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_MaryPostBattle$"

PetalburgCity_Gym_Text_ParkerDefeat::
# 287 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_ParkerDefeat$"

PetalburgCity_Gym_Text_ParkerIntro::
# 291 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_ParkerIntro$"

PetalburgCity_Gym_Text_ParkerPostBattle::
# 295 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_ParkerPostBattle$"

PetalburgCity_Gym_Text_RandallDefeat::
# 299 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_RandallDefeat$"

PetalburgCity_Gym_Text_RandallIntro::
# 303 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_RandallIntro$"

PetalburgCity_Gym_Text_RandallPostBattle::
# 307 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "PetalburgCity_Gym_Text_RandallPostBattle$"

PetalburgCity_Gym_Text_YouHaveGottenStronger::
# 311 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm… {PLAYER}, you have gotten\n"
	.string "stronger.\p"
	.string "I can tell by the number of BADGES\n"
	.string "that you've earned.$"

PetalburgCity_Gym_Text_NormanPostRematch::
# 315 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}…\n"
	.string "What is your dream?\p"
	.string "My dream…\n"
	.string "Hahaha…\l"
	.string "It has already come true, actually.$"

PetalburgCity_Gym_Text_NormanGoToRustboro::
# 319 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm? Aren't you going to the\n"
	.string "POKéMON GYM in RUSTBORO CITY?\p"
	.string "There's no challenge for me to\n"
	.string "battle a greenhorn TRAINER.\p"
	.string "{PLAYER}, I want you to challenge me\n"
	.string "when you become a lot stronger.\p"
	.string "I'll battle you, {PLAYER}, when you\n"
	.string "can show me four GYM BADGES, okay?$"

PetalburgCity_Gym_Text_DoorAppearsLocked::
# 323 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "This door appears to be locked\n"
	.string "right now…$"

PetalburgCity_Gym_Text_GeorgePostBadge::
# 327 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "I'm going to keep training at GYMS.\n"
	.string "One day, I'll become a LEADER.$"

PetalburgCity_Gym_Text_ParkerPostBadge::
# 331 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "After you beat our LEADER, the\n"
	.string "training has become a lot tougher.$"

PetalburgCity_Gym_Text_BerkePostBadge::
# 335 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Since your dad became the LEADER,\n"
	.string "the TRAINERS of PETALBURG CITY have\l"
	.string "become a lot tougher.$"

PetalburgCity_Gym_Text_DadNoAmountOfTrainingIsEnough::
# 339 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: {PLAYER}, how are things going?\p"
	.string "The world of POKéMON is deep.\p"
	.string "I honestly think that no amount of\n"
	.string "training would ever be enough.$"

PetalburgCity_Gym_Text_NormanIntro::
# 343 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: Hm…\n"
	.string "So, you did get four GYM BADGES.\p"
	.string "Fine, as I promised, we will have\n"
	.string "a POKéMON battle.\p"
	.string "{PLAYER}…\p"
	.string "I'm so happy that I can have\n"
	.string "a real battle with my own child.\p"
	.string "But, a battle is a battle!\p"
	.string "I will do everything in my power as\n"
	.string "a GYM LEADER to win.\p"
	.string "{PLAYER}, you'd better give it your\n"
	.string "best shot, too!$"

PetalburgCity_Gym_Text_NormanGoToDewford::
# 347 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: I see… So, you've beaten\n"
	.string "the GYM LEADER in RUSTBORO CITY.\p"
	.string "But there are many more TRAINERS\n"
	.string "who are stronger than you, {PLAYER}.\p"
	.string "Across the sea in DEWFORD TOWN is a\n"
	.string "GYM LEADER named BRAWLY.\p"
	.string "You should go challenge him.$"

PetalburgCity_Gym_Text_MaryPostBadge::
# 351 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Do you know what we're trying to\n"
	.string "achieve as TRAINERS?\p"
	.string "We're striving to become soul mates\n"
	.string "with our POKéMON.$"

PetalburgCity_Gym_Text_GymGuidePostVictory::
# 355 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "{PLAYER}! Whoa! You've overcome even\n"
	.string "your own father!\p"
	.string "Like, whoa!\n"
	.string "What a stunning turn of events!$"

PetalburgCity_Gym_Text_JodyPostBadge::
# 359 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Sure, it's fine to make your POKéMON\n"
	.string "stronger.\p"
	.string "But what decides the winner?\p"
	.string "Why, it's the feelings TRAINERS have\n"
	.string "for their POKéMON.$"

PetalburgCity_Gym_Text_GymStatueCertified::
# 363 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM\p"
	.string "NORMAN'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

PetalburgCity_Gym_Text_AlexiaPostBadge::
# 367 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Hi! Have you tried using SURF?$"

PetalburgCity_Gym_Text_GymStatue::
# 371 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "PETALBURG CITY POKéMON GYM$"

PetalburgCity_Gym_Text_RandallPostBadge::
# 375 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "Whomever you beat, and whomever you\n"
	.string "may lose to, you never shirk from\l"
	.string "training yourself and your POKéMON.\p"
	.string "That's what I think being a\n"
	.string "GYM LEADER is all about.$"

PetalburgCity_Gym_Text_ExplainFacade::
# 379 "data/maps/PetalburgCity_Gym/scripts.pory"
	.string "DAD: TM42 contains FACADE.\p"
	.string "It doubles the power of moves if\n"
	.string "the POKéMON is poisoned, paralyzed,\l"
	.string "or burned.\p"
	.string "It might be able to turn a bad\n"
	.string "situation into an advantage.$"
