Route110_TrickHousePuzzle2_MapScripts::
	.byte 0


Route110_TrickHousePuzzle2_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	msgbox Route110_TrickHousePuzzle2_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle2_EventScript_SmithNPC2::
# 51 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	msgbox Route110_TrickHousePuzzle2_Text_SmithNPC2, MSGBOX_NPC
	end


Route110_TrickHousePuzzle2_Text_GeorgiaDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_GeorgiaDefeat$"

Route110_TrickHousePuzzle2_Text_GeorgiaIntro::
# 9 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_GeorgiaIntro$"

Route110_TrickHousePuzzle2_Text_GeorgiaPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_GeorgiaPostBattle$"

Route110_TrickHousePuzzle2_Text_PaulDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_PaulDefeat$"

Route110_TrickHousePuzzle2_Text_PaulIntro::
# 21 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_PaulIntro$"

Route110_TrickHousePuzzle2_Text_PaulPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_PaulPostBattle$"

Route110_TrickHousePuzzle2_Text_TedDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_TedDefeat$"

Route110_TrickHousePuzzle2_Text_TedIntro::
# 33 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_TedIntro$"

Route110_TrickHousePuzzle2_Text_TedPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle2_Text_TedPostBattle$"

Route110_TrickHousePuzzle2_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Route110_TrickHousePuzzle2_Text_SmithNPC2::
# 55 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
