Route110_TrickHousePuzzle2_MapScripts::
# 2 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route110_TrickHousePuzzle2_OnResume
# 3 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHousePuzzle2_OnTransition
	.byte 0


Route110_TrickHousePuzzle2_MapScripts::
# 7 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route110_TrickHousePuzzle2_OnResume
# 8 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route110_TrickHousePuzzle2_OnTransition
	return


Route110_TrickHousePuzzle2_Text_WroteSecretCodeLockOpened::
# 12 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is smart.” … … … … … … … …\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle2_Text_TedIntro::
# 16 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Which switch closes which hole?$"

Route110_TrickHousePuzzle2_Text_TedDefeat::
# 20 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "After that battle, I'm even more\n"
	.string "confused!$"

Route110_TrickHousePuzzle2_Text_TedPostBattle::
# 24 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Can I get you to push all the buttons\n"
	.string "for me?$"

Route110_TrickHousePuzzle2_Text_PaulIntro::
# 28 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "Oh! You're on your second TRICK HOUSE\n"
	.string "challenge!$"

Route110_TrickHousePuzzle2_Text_PaulDefeat::
# 32 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "You're good at battling too?$"

Route110_TrickHousePuzzle2_Text_PaulPostBattle::
# 36 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "The TRICK MASTER rigged all the tricks\n"
	.string "in this house all by himself.$"

Route110_TrickHousePuzzle2_Text_GeorgiaIntro::
# 40 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "I want to make my own GYM one day. So,\n"
	.string "I'm studying how to set traps.$"

Route110_TrickHousePuzzle2_Text_GeorgiaDefeat::
# 44 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "I didn't study battling enough!$"

Route110_TrickHousePuzzle2_Text_GeorgiaPostBattle::
# 48 "data/maps/Route110_TrickHousePuzzle2/scripts.pory"
	.string "You're strong, aren't you? Maybe even\n"
	.string "enough to be a GYM LEADER!$"
