BattleFrontier_Lounge1_MapScripts::
	.byte 0


BattleFrontier_Lounge1_Text_PokemonBreederIntro::
# 5 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "For 70 years I have raised POKMON! I am\n"
	.string "the man they revere as\l"
	.string "the legendary top POKMON BREEDER!\p"
	.string "If you ever become as seasoned as me,\n"
	.string "you'll see the abilities of POKMON\l"
	.string "at a glance.\p"
	.string "You're a TRAINER. Doesn't it interest\n"
	.string "you to know your own POKMON's\l"
	.string "abilities?\p"
	.string "Here! Let's have a look at your POKMON!$"

BattleFrontier_Lounge1_Text_AverageAbility::
# 9 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Hmm\p"
	.string "This one, overall, I would describe as\n"
	.string "being of average ability.$"

BattleFrontier_Lounge1_Text_BetterThanAverageAbility::
# 13 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Hmm\p"
	.string "This one, overall, I would describe as\n"
	.string "having better-than-average ability.$"

BattleFrontier_Lounge1_Text_ImpressiveAbility::
# 17 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Hmm\p"
	.string "This one, overall, I would say is quite\n"
	.string "impressive in ability!$"

BattleFrontier_Lounge1_Text_OutstandingAbility::
# 21 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Hmm\p"
	.string "This one, overall, I would say is\n"
	.string "wonderfully outstanding in ability!$"

BattleFrontier_Lounge1_Text_BestAspectHP::
# 25 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its HP$"

BattleFrontier_Lounge1_Text_BestAspectAtk::
# 29 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its ATTACK$"

BattleFrontier_Lounge1_Text_BestAspectDef::
# 33 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its DEFENSE$"

BattleFrontier_Lounge1_Text_BestAspectSpAtk::
# 37 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its SPECIAL ATTACK$"

BattleFrontier_Lounge1_Text_BestAspectSpDef::
# 41 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its SPECIAL DEFENSE$"

BattleFrontier_Lounge1_Text_BestAspectSpeed::
# 45 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Incidentally, the best aspect of it, I\n"
	.string "would say, is its SPEED$"

BattleFrontier_Lounge1_Text_StatRelativelyGood::
# 49 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "That stat is relatively good. Hm That's\n"
	.string "how I call it.$"

BattleFrontier_Lounge1_Text_StatImpressive::
# 53 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "That stat is quite impressive. Hm That's\n"
	.string "how I call it.$"

BattleFrontier_Lounge1_Text_StatOutstanding::
# 57 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "That stat is outstanding! Hm That's how\n"
	.string "I call it.$"

BattleFrontier_Lounge1_Text_StatFlawless::
# 61 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "It's flawless! A thing of perfection! Hm\n"
	.string "That's how I call it.$"

BattleFrontier_Lounge1_Text_NoTimeForMyAdvice::
# 65 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "What? You have no time for my advice?\p"
	.string "You should always be eager to learn\n"
	.string "from the experiences of your elders!$"

BattleFrontier_Lounge1_Text_HaveBusinessNeedsTending::
# 69 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Yes, what is it now?\p"
	.string "I have business that needs tending!\n"
	.string "Save it for next time!$"

BattleFrontier_Lounge1_Text_LetsLookAtYourPokemon::
# 73 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "Ah, youngster! Do your POKMON's\n"
	.string "abilities intrigue you?\p"
	.string "Here, here! Let's have a look at your\n"
	.string "POKMON!$"

BattleFrontier_Lounge1_Text_EvenICantTell::
# 77 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "An expert I am, but even I can't tell\n"
	.string "anything about an unhatched POKMON!\p"
	.string "Show me a POKMON! A POKMON is what I\n"
	.string "need to see!$"

BattleFrontier_Lounge1_Text_SaidMyMonIsOutstanding::
# 81 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "He said my POKMON is outstanding! I'm\n"
	.string "glad I raised it carefully!$"

BattleFrontier_Lounge1_Text_DidntDoAnythingSpecialRaisingIt::
# 85 "data/maps/BattleFrontier_Lounge1/scripts.pory"
	.string "He said my POKMON is outstanding! But I\n"
	.string "didn't do anything special\l"
	.string "raising it$"
