SaffronCity_CopycatsHouse_2F_MapScripts::
	.byte 0


SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMale::
# 5 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}: Hi! Do you like POKMON?\p"
	.string "{PLAYER}: Uh, no, I just asked you.\p"
	.string "{PLAYER}: Huh? You're strange!\p"
	.string "COPYCAT: Hmm? Quit mimicking? But,\n"
	.string "that's my favorite hobby!$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemale::
# 9 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}: Hi. You must like POKMON.\p"
	.string "{PLAYER}: No, not me. I asked you.\p"
	.string "{PLAYER}: Pardon? You're weird!\l"
	.string "\l"
	.string "COPYCAT: Hmm? Quit mimicking?\l"
	.string "But that's my favorite hobby!$"

Text_MimicTeach::
# 13 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "Oh wow! A POK DOLL!\p"
	.string "For me? Thank you!\p"
	.string "You know what? I can teach the move\n"
	.string "MIMIC.$"

Text_MimicDeclined::
# 17 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "Don't you like MIMIC?$"

Text_MimicWhichMon::
# 21 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "I really love MIMIC! Who's going to learn\n"
	.string "it?$"

Text_MimicTaughtMale::
# 25 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}: Hi! Thanks for earlier!\p"
	.string "{PLAYER}: Pardon?\p"
	.string "{PLAYER}: Is it that fun to mimic my\n"
	.string "every move?\p"
	.string "COPYCAT: You bet! It's a scream!$"

Text_MimicTaughtFemale::
# 29 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}: Hi! Thanks for what you did\n"
	.string "for us.\p"
	.string "{PLAYER}: Pardon?\p"
	.string "{PLAYER}: Is it really that fun to\n"
	.string "copy what I say and do?\p"
	.string "COPYCAT: You bet! It's a scream!$"

SaffronCity_CopycatsHouse_2F_Text_TooMuchInBag::
# 33 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyMaleJP::
# 37 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}\p"
	.string "{PLAYER}\p"
	.string "{PLAYER}\p"
	.string "\p"
	.string "$"

SaffronCity_CopycatsHouse_2F_Text_MimickingFavoriteHobbyFemaleJP::
# 41 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "{PLAYER}\p"
	.string "{PLAYER}\p"
	.string "{PLAYER}\p"
	.string "\p"
	.string "$"

SaffronCity_CopycatsHouse_2F_Text_Doduo::
# 45 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "DODUO: Giiih!\p"
	.string "PRETTY MIRROR LOOK AT ME, SEE HOW\n"
	.string "PRETTY I CAN BE?$"

SaffronCity_CopycatsHouse_2F_Text_RareMonOnlyDoll::
# 49 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "This is a rare POKMON! Huh? It's only a\n"
	.string "doll!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
# 53 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "A game with MARIO wearing a bucket on\n"
	.string "his head!$"

SaffronCity_CopycatsHouse_2F_Text_MySecrets::
# 57 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "\p"
	.string "My Secrets!\p"
	.string "Skill: Mimicry! Hobby: Collecting dolls!\l"
	.string "Favorite POKMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_HuhCantSee::
# 61 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "$"
