SaffronCity_CopycatsHouse_2F_MapScripts::
	.byte 0


SaffronCity_CopycatsHouse_2F_EventScript_Computer::
# 5 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	msgbox SaffronCity_CopycatsHouse_2F_Text_MySecrets, MSGBOX_SIGN
	end


SaffronCity_CopycatsHouse_2F_EventScript_Copycat::
	end


SaffronCity_CopycatsHouse_2F_EventScript_Doduo::
	end


SaffronCity_CopycatsHouse_2F_EventScript_Doll::
	end


SaffronCity_CopycatsHouse_2F_EventScript_Game::
# 22 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	msgbox SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket, MSGBOX_SIGN
	end


SaffronCity_CopycatsHouse_2F_Text_MySecrets::
# 27 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "…\p"
	.string "My Secrets!\p"
	.string "Skill: Mimicry! Hobby: Collecting dolls!\l"
	.string "Favorite POKéMON: CLEFAIRY!$"

SaffronCity_CopycatsHouse_2F_Text_MarioWearingABucket::
# 31 "data/maps/SaffronCity_CopycatsHouse_2F/scripts.pory"
	.string "A game with MARIO wearing a bucket on\n"
	.string "his head!$"
