DewfordTown_PokemonCenter_1F_MapScripts::
	.byte 0


DewfordTown_PokemonCenter_1F_EventScript_Man::
# 5 "data/maps/DewfordTown_PokemonCenter_1F/scripts.pory"
	msgbox DewfordTown_PokemonCenter_1F_Text_FaintedMonCanUseHM, MSGBOX_NPC
	end


DewfordTown_PokemonCenter_1F_EventScript_Nurse::
	end


DewfordTown_PokemonCenter_1F_EventScript_PokefanF::
# 14 "data/maps/DewfordTown_PokemonCenter_1F/scripts.pory"
	msgbox DewfordTown_PokemonCenter_1F_Text_StoneCavern, MSGBOX_NPC
	end


DewfordTown_PokemonCenter_1F_Text_StoneCavern::
# 18 "data/maps/DewfordTown_PokemonCenter_1F/scripts.pory"
	.string "There's a stone cavern at the edge\n"
	.string "of town.\p"
	.string "I've heard you can find rare stones\n"
	.string "there.$"

DewfordTown_PokemonCenter_1F_Text_FaintedMonCanUseHM::
# 22 "data/maps/DewfordTown_PokemonCenter_1F/scripts.pory"
	.string "Even if a POKéMON faints and can't\n"
	.string "battle, it can still use a move learned\l"
	.string "from a HIDDEN MACHINE (HM).$"
