NavelRock_Down01_MapScripts::
	.byte 0


NavelRock_Down01_EventScript_SmithNPC1::
# 5 "data/maps/NavelRock_Down01/scripts.pory"
	msgbox NavelRock_Down01_Text_SmithNPC1, MSGBOX_NPC
	end


NavelRock_Down01_EventScript_SmithNPC2::
# 14 "data/maps/NavelRock_Down01/scripts.pory"
	msgbox NavelRock_Down01_Text_SmithNPC2, MSGBOX_NPC
	end


NavelRock_Down01_Text_SmithNPC1::
# 9 "data/maps/NavelRock_Down01/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

NavelRock_Down01_Text_SmithNPC2::
# 18 "data/maps/NavelRock_Down01/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
