SSAnne_1F_Room1_MapScripts::
	.byte 0


SSAnne_1F_Room1_EventScript_Gentleman::
# 5 "data/maps/SSAnne_1F_Room1/scripts.pory"
	msgbox SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent, MSGBOX_NPC
	end


SSAnne_1F_Room1_Text_ImAGlobalPoliceAgent::
# 10 "data/maps/SSAnne_1F_Room1/scripts.pory"
	.string "Ssh…!\n"
	.string "I'm a GLOBAL POLICE agent.\p"
	.string "I'm on the trail of TEAM ROCKET.\n"
	.string "They're up to nothing good!$"
