SlateportCity_BattleTentLobby_MapScripts::
# 2 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SlateportCity_BattleTentLobby_OnFrame
# 3 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, SlateportCity_BattleTentLobby_OnWarp
	.byte 0


SlateportCity_BattleTentLobby_Text_CouldntFindMonForMe::
# 7 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	.string "So, like, I couldn't find myself any\n"
	.string "POKéMON that were, like, for me.\p"
	.string "So, I figured, like, hey, I should file a\n"
	.string "complaint to the guy there?\p"
	.string "And he wouldn't hear me out, like, hey!\n"
	.string "So, like, total bummer, man!\p"
	.string "Hey, like, you! Zip it, you know? Just,\n"
	.string "you know, take this!$"

SlateportCity_BattleTentLobby_Text_ExplainTorment::
# 11 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	.string "That's, like, TM41, you know? Hey, it's\n"
	.string "TORMENT, you hearing me?\p"
	.string "Like, it won't let the other guy use the\n"
	.string "same move twice in a row, see?\p"
	.string "Hey, now, you listen here, like, I'm not\n"
	.string "laying a torment on you!$"

SlateportCity_BattleTentLobby_Text_IllTryUsingBugMons::
# 15 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	.string "I don't really like BUG POKéMON, but\n"
	.string "maybe I'll try using some for\l"
	.string "a change of pace.\p"
	.string "Who knows, I might even get to like\n"
	.string "them!$"

SlateportCity_BattleTentLobby_Text_BattleEvenWithoutToughMons::
# 19 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	.string "You can battle all you want here even if\n"
	.string "you don't have any tough POKéMON.$"

SlateportCity_BattleTentLobby_Text_NiceIfMoreSelection::
# 23 "data/maps/SlateportCity_BattleTentLobby/scripts.pory"
	.string "Wouldn't it be nice if they had more of a\n"
	.string "selection?$"
