MossdeepCity_GameCorner_1F_MapScripts::
	.byte 0


MossdeepCity_GameCorner_1F_EventScript_InfoMan::
	end


MossdeepCity_GameCorner_1F_EventScript_OldMan::
	end


RS_MysteryEventsHouse_EventScript_Door::
# 13 "data/maps/MossdeepCity_GameCorner_1F/scripts.pory"
	msgbox RS_MysteryEventsHouse_Text_DoorIsLocked, MSGBOX_SIGN
	end


RS_MysteryEventsHouse_Text_DoorIsLocked::
# 18 "data/maps/MossdeepCity_GameCorner_1F/scripts.pory"
	.string "The door appears to be locked.$"
