DewfordTown_House2_MapScripts::
	.byte 0


DewfordTown_House2_Text_WantYouToHaveSilkScarf::
# 5 "data/maps/DewfordTown_House2/scripts.pory"
	.string "Gorge your eyes on this!\p"
	.string "It's a SILK SCARF. It's right at the\n"
	.string "cutting edge of fashion, yeah!\p"
	.string "Oh, I can see your eyes twinkling! You\n"
	.string "appreciate my dazzling style!\p"
	.string "Oh, you're a delight! Here you go. I want\n"
	.string "you to have it!$"

DewfordTown_House2_Text_NoRoom::
# 9 "data/maps/DewfordTown_House2/scripts.pory"
	.string "Oh, you don't have room?\p"
	.string "Now, listen tight, this SCARF is a must-\n"
	.string "have! Why, I would sell all my items\l"
	.string "in order to get it!$"

DewfordTown_House2_Text_ExplainSilkScarf::
# 13 "data/maps/DewfordTown_House2/scripts.pory"
	.string "The SILK SCARF raises the power of\n"
	.string "NORMAL-type moves.\p"
	.string "It's a marvelous SCARF that will go with\n"
	.string "almost all POKMON!$"

DewfordTown_House2_Text_BrawlySoCool::
# 17 "data/maps/DewfordTown_House2/scripts.pory"
	.string "Wow, you bothered to cross the sea to\n"
	.string "visit DEWFORD?\p"
	.string "Did you maybe come here because you\n"
	.string "heard about BRAWLY?\p"
	.string "He's so cool Everyone idolizes him.$"
