PalletTown_PlayersHouse_1F_MapScripts::
	.byte 0


PalletTown_PlayersHouse_1F_EventScript_Mom::
	end


PalletTown_PlayersHouse_1F_EventScript_TV::
	end


PalletTown_PlayersHouse_1F_EventScript_SmithNPC1::
# 13 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	msgbox PalletTown_PlayersHouse_1F_Text_SmithNPC1, MSGBOX_NPC
	end


PalletTown_PlayersHouse_1F_Text_SmithNPC1::
# 17 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"
