PalletTown_PlayersHouse_1F_MapScripts::
	.byte 0


PalletTown_PlayersHouse_1F_Text_AllBoysLeaveOakLookingForYou::
# 5 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "MOM: Right. All boys leave home someday.\l"
	.string "It said so on TV.\p"
	.string "Oh, yes. PROF. OAK, next door, was\n"
	.string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_AllGirlsLeaveOakLookingForYou::
# 9 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "MOM: Right. All girls dream of traveling.\l"
	.string "It said so on TV.\p"
	.string "Oh, yes. PROF. OAK, next door, was\n"
	.string "looking for you.$"

PalletTown_PlayersHouse_1F_Text_YouShouldTakeQuickRest::
# 13 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "MOM: {PLAYER}! You should take a\n"
	.string "quick rest.$"

PalletTown_PlayersHouse_1F_Text_LookingGreatTakeCare::
# 17 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "MOM: Oh, good! You and your POKMON are\n"
	.string "looking great.\l"
	.string "Take care now!$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVFourBoysOnRailroad::
# 21 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "There's a movie on TV. Four boys are\n"
	.string "walking on railroad\l"
	.string "tracks.\p"
	.string "I better go, too.$"

PalletTown_PlayersHouse_1F_Text_MovieOnTVGirlOnBrickRoad::
# 25 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "There's a movie on TV. A girl with her\n"
	.string "hair in pigtails is\l"
	.string "walking up a brick road.\p"
	.string "I better go, too.$"

PalletTown_PlayersHouse_1F_Text_OopsWrongSide::
# 29 "data/maps/PalletTown_PlayersHouse_1F/scripts.pory"
	.string "Oops, wrong side$"
