LavaridgeTown_PokemonCenter_1F_MapScripts::
# 2 "data/maps/LavaridgeTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LavaridgeTown_PokemonCenter_1F_OnTransition
# 3 "data/maps/LavaridgeTown_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


LavaridgeTown_PokemonCenter_1F_Text_TrainersPokemonSpendTimeTogether::
# 7 "data/maps/LavaridgeTown_PokemonCenter_1F/scripts.pory"
	.string "I think POKMON get closer to their\n"
	.string "TRAINERS if they spend time together.\p"
	.string "The longer the better. That's what I\n"
	.string "think.$"

LavaridgeTown_PokemonCenter_1F_Text_HotSpringCanInvigorate::
# 11 "data/maps/LavaridgeTown_PokemonCenter_1F/scripts.pory"
	.string "It's sort of magical how just sitting in\n"
	.string "a hot-spring pool can invigorate.\p"
	.string "I wish I could let my POKMON soak, too.$"

LavaridgeTown_PokemonCenter_1F_Text_TrainersShouldRestToo::
# 15 "data/maps/LavaridgeTown_PokemonCenter_1F/scripts.pory"
	.string "Hohoho! Hey, kid, you can reach the hot\n"
	.string "springs from here.\p"
	.string "If POKMON are getting rest, so too\n"
	.string "should their TRAINERS.$"
