Route111_OldLadysRestStop_MapScripts::
# 2 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route111_OldLadysRestStop_OnTransition
	.byte 0


Route111_OldLadysRestStop_Text_RestUpHere::
# 6 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Oh, dear, dear. Aren't your POKéMON\n"
	.string "exhausted?\p"
	.string "If you'd like, rest up here. That's a fine\n"
	.string "idea! You should do that.$"

Route111_OldLadysRestStop_Text_TakeYourTimeRestUp::
# 10 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "That's right. Take your time and rest\n"
	.string "up!$"

Route111_OldLadysRestStop_Text_StillTiredTakeAnotherRest::
# 14 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Oh, dear, dear. Are your POKéMON still\n"
	.string "tired?\p"
	.string "You should take another rest here.\n"
	.string "That's a fine idea. You should do that.$"

Route111_OldLadysRestStop_Text_DontNeedToBeShy::
# 18 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Is that so? You don't need to be shy\n"
	.string "about it.$"
