Route111_OldLadysRestStop_MapScripts::
	.byte 0


Route111_OldLadysRestStop_EventScript_OldLady::
# 5 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	msgbox Route111_OldLadysRestStop_Text_RestUpHere, MSGBOX_YESNO
	end


Route111_OldLadysRestStop_Text_DontNeedToBeShy::
# 9 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Is that so?\n"
	.string "You don't need to be shy about it.$"

Route111_OldLadysRestStop_Text_RestUpHere::
# 13 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "Oh, dear, dear.\n"
	.string "Aren't your POKéMON exhausted?\p"
	.string "If you'd like, rest up here.\n"
	.string "That's a fine idea! You should do that.$"

Route111_OldLadysRestStop_Text_TakeYourTimeRestUp::
# 17 "data/maps/Route111_OldLadysRestStop/scripts.pory"
	.string "That's right.\n"
	.string "Take your time and rest up!$"
