CianwoodCity_PhotoStudio_MapScripts::
	.byte 0


CianwoodCity_PhotoStudio_EventScript_SmithNPC1::
# 5 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	msgbox CianwoodCity_PhotoStudio_Text_SmithNPC1, MSGBOX_NPC
	end


CianwoodCity_PhotoStudio_EventScript_SmithNPC2::
# 14 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	msgbox CianwoodCity_PhotoStudio_Text_SmithNPC2, MSGBOX_NPC
	end


CianwoodCity_PhotoStudio_EventScript_SmithNPC3::
# 23 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	msgbox CianwoodCity_PhotoStudio_Text_SmithNPC3, MSGBOX_NPC
	end


CianwoodCity_PhotoStudio_Text_SmithNPC1::
# 9 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

CianwoodCity_PhotoStudio_Text_SmithNPC2::
# 18 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

CianwoodCity_PhotoStudio_Text_SmithNPC3::
# 27 "data/maps/CianwoodCity_PhotoStudio/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
