LavenderTown_House2_MapScripts::
	.byte 0


LavenderTown_House2_Text_WantMeToRateNicknames::
# 5 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Hello, hello! I am the official NAME\n"
	.string "RATER!\p"
	.string "Want me to rate the nicknames of your\n"
	.string "POKéMON?$"

LavenderTown_House2_Text_CritiqueWhichMonsNickname::
# 9 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Which POKéMON's nickname should I\n"
	.string "critique?$"

LavenderTown_House2_Text_GiveItANicerName::
# 13 "data/maps/LavenderTown_House2/scripts.pory"
	.string "{STR_VAR_1}, is it? That is a decent\n"
	.string "nickname!\p"
	.string "But, would you like me to give it a nicer\n"
	.string "name?\p"
	.string "How about it?$"

LavenderTown_House2_Text_WhatShallNewNicknameBe::
# 17 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Ah, good. Then, what shall the new\n"
	.string "nickname be?$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsName::
# 21 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Done! From now on, this POKéMON shall be\n"
	.string "known as {STR_VAR_1}!\p"
	.string "It is a better name than before! How\n"
	.string "fortunate for you!$"

LavenderTown_House2_Text_ISeeComeVisitAgain::
# 25 "data/maps/LavenderTown_House2/scripts.pory"
	.string "I see. Do come visit again.$"

LavenderTown_House2_Text_FromNowOnShallBeKnownAsSameName::
# 29 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Done! From now on, this POKéMON shall be\n"
	.string "known as {STR_VAR_1}!\p"
	.string "It looks no different from before, and\n"
	.string "yet, this is vastly superior!\p"
	.string "How fortunate for you!$"

LavenderTown_House2_Text_TrulyImpeccableName::
# 33 "data/maps/LavenderTown_House2/scripts.pory"
	.string "{STR_VAR_1}, is it? That is a truly\n"
	.string "impeccable name!\p"
	.string "Take good care of {STR_VAR_1}!$"

LavenderTown_House2_Text_ThatIsMerelyAnEgg::
# 37 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Now, now. That is merely an EGG!$"
