LavenderTown_House2_MapScripts::
	.byte 0


LavenderTown_House2_EventScript_NameRater::
# 5 "data/maps/LavenderTown_House2/scripts.pory"
	msgbox LavenderTown_House2_Text_WantMeToRateNicknames, MSGBOX_YESNO
	end


LavenderTown_House2_Text_WantMeToRateNicknames::
# 10 "data/maps/LavenderTown_House2/scripts.pory"
	.string "Hello, hello!\n"
	.string "I am the official NAME RATER!\p"
	.string "Want me to rate the nicknames of\n"
	.string "your POKéMON?$"
