SSAnne_1F_Room3_MapScripts::
	.byte 0


SSAnne_1F_Room3_EventScript_BaldingMan::
# 5 "data/maps/SSAnne_1F_Room3/scripts.pory"
	msgbox SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy, MSGBOX_NPC
	end


SSAnne_1F_Room3_EventScript_LittleGirl::
# 10 "data/maps/SSAnne_1F_Room3/scripts.pory"
	msgbox SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff, MSGBOX_NPC
	end


SSAnne_1F_Room3_EventScript_Wigglytuff::
	end


SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy::
# 19 "data/maps/SSAnne_1F_Room3/scripts.pory"
	.string "A world cruise is so elegant yet\n"
	.string "cozy!$"

SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff::
# 23 "data/maps/SSAnne_1F_Room3/scripts.pory"
	.string "I always travel with WIGGLYTUFF.\n"
	.string "I never leave home without it.$"
