SSAnne_1F_Room3_MapScripts::
	.byte 0


SSAnne_1F_Room3_Text_CruiseIsElegantAndCozy::
# 5 "data/maps/SSAnne_1F_Room3/scripts.pory"
	.string "A world cruise is so elegant yet cozy!$"

SSAnne_1F_Room3_Text_AlwaysTravelWithWigglytuff::
# 9 "data/maps/SSAnne_1F_Room3/scripts.pory"
	.string "I always travel with WIGGLYTUFF. I\n"
	.string "never leave home without it.$"

SSAnne_1F_Room3_Text_Wigglytuff::
# 13 "data/maps/SSAnne_1F_Room3/scripts.pory"
	.string "WIGGLYTUFF: Puup pupuu!$"
