RocketHideout_B3F_MapScripts::
	.byte 0


RocketHideout_B3F_Text_Grunt1Intro::
# 5 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "Stop meddling in TEAM ROCKET's affairs\n"
	.string "or else!$"

RocketHideout_B3F_Text_Grunt1Defeat::
# 9 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "Oof! Taken down!$"

RocketHideout_B3F_Text_Grunt1PostBattle::
# 13 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "SILPH SCOPE? Oh, that machine the BOSS\n"
	.string "stole.\p"
	.string "It's here somewhere.$"

RocketHideout_B3F_Text_Grunt2Intro::
# 17 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "We got word from upstairs that you were\n"
	.string "coming!$"

RocketHideout_B3F_Text_Grunt2Defeat::
# 21 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "What? I lost? No!$"

RocketHideout_B3F_Text_Grunt2PostBattle::
# 25 "data/maps/RocketHideout_B3F/scripts.pory"
	.string "Go ahead and go!\p"
	.string "But you can't run the elevator without\n"
	.string "the LIFT KEY.$"
