SaffronCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SaffronCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


SaffronCity_PokemonCenter_1F_Text_GrowthRatesDifferBySpecies::
# 7 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	.string "POKMON growth rates differ from\n"
	.string "species to species.$"

SaffronCity_PokemonCenter_1F_Text_SilphCoVictimOfFame::
# 11 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	.string "SILPH CO. is widely known to all.\p"
	.string "It's a victim of its own fame - it\n"
	.string "attracted TEAM ROCKET.$"

SaffronCity_PokemonCenter_1F_Text_GreatIfEliteFourCameBeatRockets::
# 15 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	.string "Sigh Wouldn't this be great?\p"
	.string "If the ELITE FOUR came and stomped\n"
	.string "TEAM ROCKET?$"

SaffronCity_PokemonCenter_1F_Text_TeamRocketTookOff::
# 19 "data/maps/SaffronCity_PokemonCenter_1F/scripts.pory"
	.string "TEAM ROCKET took off! We can go out\n"
	.string "safely again!\l"
	.string "That's great!$"
