Route16_House_MapScripts::
	.byte 0


Route16_House_Text_FoundMySecretRetreat::
# 5 "data/maps/Route16_House/scripts.pory"
	.string "Oh, dear. You've found my secret\n"
	.string "retreat.\p"
	.string "Please don't tell anyone I'm here. I'll\n"
	.string "make it up to you with this!$"

Route16_House_Text_ReceivedHM02FromGirl::
# 9 "data/maps/Route16_House/scripts.pory"
	.string "{PLAYER} received HM02 from the girl.$"

Route16_House_Text_ExplainHM02::
# 13 "data/maps/Route16_House/scripts.pory"
	.string "HM02 is FLY. It's a wonderfully\n"
	.string "convenient move.\p"
	.string "Please, put it to good use.$"

Route16_House_Text_DontHaveAnyRoomForThis::
# 17 "data/maps/Route16_House/scripts.pory"
	.string "You don't have any room for this.$"

Route16_House_Text_Fearow::
# 21 "data/maps/Route16_House/scripts.pory"
	.string "FEAROW: Kyueen!$"
