PokemonTower_1F_MapScripts::
# 2 "data/maps/PokemonTower_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PokemonTower_1F_OnTransition
	.byte 0


PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
# 6 "data/maps/PokemonTower_1F/scripts.pory"
	.string "POKéMON TOWER was erected in the\n"
	.string "memory of POKéMON that died.$"

PokemonTower_1F_Text_ComeToPayRespectsSon::
# 10 "data/maps/PokemonTower_1F/scripts.pory"
	.string "Did you come to pay respects?\p"
	.string "Bless your POKéMON-loving heart, son.$"

PokemonTower_1F_Text_ComeToPayRespectsGirl::
# 14 "data/maps/PokemonTower_1F/scripts.pory"
	.string "Did you come to pay respects?\p"
	.string "Bless your POKéMON-loving heart, girl.$"

PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
# 18 "data/maps/PokemonTower_1F/scripts.pory"
	.string "I came to pray for my dearly departed\n"
	.string "CLEFAIRY.\p"
	.string "Sniff! I'm awash in tears…$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
# 22 "data/maps/PokemonTower_1F/scripts.pory"
	.string "My GROWLITHE… Why did you die?$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
# 26 "data/maps/PokemonTower_1F/scripts.pory"
	.string "I am a CHANNELER.\p"
	.string "There are spirits up to mischief. I\n"
	.string "sense them high in the TOWER.$"
