PokemonTower_1F_MapScripts::
	.byte 0


PokemonTower_1F_EventScript_BaldingMan::
# 5 "data/maps/PokemonTower_1F/scripts.pory"
	msgbox PokemonTower_1F_Text_CameToPrayForDepartedClefairy, MSGBOX_NPC
	end


PokemonTower_1F_EventScript_Channeler::
# 10 "data/maps/PokemonTower_1F/scripts.pory"
	msgbox PokemonTower_1F_Text_SenseSpiritsUpToMischief, MSGBOX_NPC
	end


PokemonTower_1F_EventScript_Woman1::
# 15 "data/maps/PokemonTower_1F/scripts.pory"
	msgbox PokemonTower_1F_Text_GrowlitheWhyDidYouDie, MSGBOX_NPC
	end


PokemonTower_1F_EventScript_Woman2::
	end


PokemonTower_1F_EventScript_WorkerF::
# 24 "data/maps/PokemonTower_1F/scripts.pory"
	msgbox PokemonTower_1F_Text_ErectedInMemoryOfDeadMons, MSGBOX_NPC
	end


PokemonTower_1F_Text_CameToPrayForDepartedClefairy::
# 29 "data/maps/PokemonTower_1F/scripts.pory"
	.string "I came to pray for my dearly\n"
	.string "departed CLEFAIRY.\p"
	.string "Sniff!\n"
	.string "I'm awash in tears…$"

PokemonTower_1F_Text_SenseSpiritsUpToMischief::
# 33 "data/maps/PokemonTower_1F/scripts.pory"
	.string "I am a CHANNELER.\p"
	.string "There are spirits up to mischief.\n"
	.string "I sense them high in the TOWER.$"

PokemonTower_1F_Text_GrowlitheWhyDidYouDie::
# 37 "data/maps/PokemonTower_1F/scripts.pory"
	.string "My GROWLITHE…\n"
	.string "Why did you die?$"

PokemonTower_1F_Text_ErectedInMemoryOfDeadMons::
# 41 "data/maps/PokemonTower_1F/scripts.pory"
	.string "POKéMON TOWER was erected in the\n"
	.string "memory of POKéMON that died.$"
