FuchsiaCity_SafariZone_Office_MapScripts::
	.byte 0


FuchsiaCity_SafariZone_Office_EventScript_Worker1::
# 5 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke, MSGBOX_NPC
	end


FuchsiaCity_SafariZone_Office_EventScript_Worker2::
# 10 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable, MSGBOX_NPC
	end


FuchsiaCity_SafariZone_Office_EventScript_Worker3::
# 15 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden, MSGBOX_NPC
	end


FuchsiaCity_SafariZone_Office_EventScript_Worker4::
# 20 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone, MSGBOX_NPC
	end


FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
# 25 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "We nicknamed the WARDEN\n"
	.string "“SLOWPOKE.”\p"
	.string "You know, he has that vacant look\n"
	.string "like a SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
# 29 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE is very\n"
	.string "knowledgeable about POKéMON.\p"
	.string "He even has some fossils of rare,\n"
	.string "extinct POKéMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
# 33 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE came in, but\n"
	.string "I couldn't understand him.\p"
	.string "I think he's got a speech problem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
# 37 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE is running a\n"
	.string "promotion campaign right now.\p"
	.string "Try to get to the farthest corner\n"
	.string "of the SAFARI ZONE.\p"
	.string "If you can make it, you'll win a\n"
	.string "very convenient prize.$"
