FuchsiaCity_SafariZone_Office_MapScripts::
	.byte 0


FuchsiaCity_SafariZone_Office_Text_NicknamedWardenSlowpoke::
# 5 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "We nicknamed the WARDEN SLOWPOKE.\p"
	.string "You know, he has that vacant look like a\n"
	.string "SLOWPOKE.$"

FuchsiaCity_SafariZone_Office_Text_WardenIsVeryKnowledgeable::
# 9 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE is very knowledgeable\n"
	.string "about POKMON.\p"
	.string "He even has some fossils of rare,\n"
	.string "extinct POKMON.$"

FuchsiaCity_SafariZone_Office_Text_CouldntUnderstandWarden::
# 13 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE came in, but I couldn't\n"
	.string "understand him.\p"
	.string "I think he's got a speech problem!$"

FuchsiaCity_SafariZone_Office_Text_PrizeInSafariZone::
# 17 "data/maps/FuchsiaCity_SafariZone_Office/scripts.pory"
	.string "WARDEN SLOWPOKE is running a promotion\n"
	.string "campaign right now.\p"
	.string "Try to get to the farthest corner of\n"
	.string "the SAFARI ZONE.\p"
	.string "If you can make it, you'll win a very\n"
	.string "convenient prize.$"
