VerdanturfTown_FriendshipRatersHouse_MapScripts::
	.byte 0


VerdanturfTown_FriendshipRatersHouse_MapScripts::
	return


VerdanturfTown_FriendshipRatersHouse_Text_SeeHowMuchPokemonLikesYou::
# 8 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "Let me see your POKéMON. I'll check to\n"
	.string "see how much it likes you.\p"
	.string "Oh. Your POKéMON…$"

VerdanturfTown_FriendshipRatersHouse_Text_AdoresYou::
# 12 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It adores you. It can't possibly love\n"
	.string "you any more.\l"
	.string "I even feel happy seeing it.$"

VerdanturfTown_FriendshipRatersHouse_Text_VeryHappy::
# 16 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It seems to be very happy. It obviously\n"
	.string "likes you a whole lot.$"

VerdanturfTown_FriendshipRatersHouse_Text_LikesYouQuiteALot::
# 20 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It likes you quite a lot. It seems to\n"
	.string "want to be babied a little.$"

VerdanturfTown_FriendshipRatersHouse_Text_GettingUsedToYou::
# 24 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It's getting used to you. It seems to\n"
	.string "believe in you.$"

VerdanturfTown_FriendshipRatersHouse_Text_NotUsedToYou::
# 28 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It's not very used to you yet. It\n"
	.string "neither loves nor hates you.$"

VerdanturfTown_FriendshipRatersHouse_Text_VeryWary::
# 32 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "It's very wary. It has scary\n"
	.string "viciousness in its eyes.\l"
	.string "It doesn't like you much at all.$"

VerdanturfTown_FriendshipRatersHouse_Text_DetestsYou::
# 36 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "This is a little hard for me to say…\p"
	.string "Your POKéMON simply detests you.\n"
	.string "Doesn't that make you uncomfortable?$"

VerdanturfTown_FriendshipRatersHouse_Text_Pikachu::
# 40 "data/maps/VerdanturfTown_FriendshipRatersHouse/scripts.pory"
	.string "PIKACHU: Pika pika!$"
