VerdanturfTown_MapScripts::
# 2 "data/maps/VerdanturfTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, VerdanturfTown_OnTransition
	.byte 0


VerdanturfTown_Text_ManTryingToDigTunnel::
# 6 "data/maps/VerdanturfTown/scripts.pory"
	.string "My papa told me.\p"
	.string "He says this tunnel is full of timid\n"
	.string "POKéMON.\p"
	.string "They get all scared of loud noise and\n"
	.string "make a big uproar.\p"
	.string "So they had to stop the big tunnel\n"
	.string "project.\p"
	.string "But there's one man. He's trying to dig\n"
	.string "the tunnel by himself!$"

VerdanturfTown_Text_ManDugTunnelForLove::
# 10 "data/maps/VerdanturfTown/scripts.pory"
	.string "There was a man who dug a tunnel for a\n"
	.string "lady he loved.\p"
	.string "I don't really get it, but hey!$"

VerdanturfTown_Text_AirCleanHere::
# 14 "data/maps/VerdanturfTown/scripts.pory"
	.string "The way the winds blow, volcanic ash is\n"
	.string "never blown in this direction.\p"
	.string "The air is clean and delicious here.\n"
	.string "Living here should do wonders for even\l"
	.string "frail and sickly people.$"

VerdanturfTown_Text_MakeBattleTentDebut::
# 18 "data/maps/VerdanturfTown/scripts.pory"
	.string "My POKéMON and I, we've been riding a\n"
	.string "hot winning streak.\p"
	.string "So I decided to make my BATTLE TENT\n"
	.string "debut in this town.$"

VerdanturfTown_Text_GuyTryingToBustThroughCave::
# 22 "data/maps/VerdanturfTown/scripts.pory"
	.string "Did you see the cave next to the\n"
	.string "POKéMON MART?\p"
	.string "There's a guy in there who's trying to\n"
	.string "bust up boulders so he can bust out\l"
	.string "through to the other side.\p"
	.string "It'd be great if we could go through…\n"
	.string "It'll make it easy to visit RUSTBORO.$"

VerdanturfTown_Text_EasyToGetToRustboroNow::
# 26 "data/maps/VerdanturfTown/scripts.pory"
	.string "That cave next to the POKéMON MART is\n"
	.string "now a tunnel to the other side.\p"
	.string "It's great--it's easy to go shop for\n"
	.string "new DEVON products in RUSTBORO now.$"

VerdanturfTown_Text_TownSign::
# 30 "data/maps/VerdanturfTown/scripts.pory"
	.string "VERDANTURF TOWN\p"
	.string "“The windswept highlands with the\n"
	.string "sweet fragrance of grass.”$"

VerdanturfTown_Text_WandasHouse::
# 34 "data/maps/VerdanturfTown/scripts.pory"
	.string "WANDA'S HOUSE$"

VerdanturfTown_Text_BattleTentSign::
# 38 "data/maps/VerdanturfTown/scripts.pory"
	.string "BATTLE TENT VERDANTURF SITE “Feast\n"
	.string "Your Eyes on Battles!”$"

VerdanturfTown_Text_RusturfTunnelSign::
# 42 "data/maps/VerdanturfTown/scripts.pory"
	.string "RUSTURF TUNNEL “Linking RUSTBORO and\n"
	.string "VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"
