VerdanturfTown_MapScripts::
	.byte 0


VerdanturfTown_EventScript_BattleTentSign::
# 5 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_BattleTentSign, MSGBOX_SIGN
	end


VerdanturfTown_EventScript_Boy::
	end


VerdanturfTown_EventScript_Camper::
# 14 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_MakeBattleTentDebut, MSGBOX_NPC
	end


VerdanturfTown_EventScript_Man::
# 19 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_AirCleanHere, MSGBOX_NPC
	end


VerdanturfTown_EventScript_RusturfTunnelSign::
# 24 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_RusturfTunnelSign, MSGBOX_SIGN
	end


VerdanturfTown_EventScript_TownSign::
# 29 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_TownSign, MSGBOX_SIGN
	end


VerdanturfTown_EventScript_Twin::
	end


VerdanturfTown_EventScript_WandasHouseSign::
# 38 "data/maps/VerdanturfTown/scripts.pory"
	msgbox VerdanturfTown_Text_WandasHouse, MSGBOX_SIGN
	end


VerdanturfTown_Text_WandasHouse::
# 43 "data/maps/VerdanturfTown/scripts.pory"
	.string "WANDA'S HOUSE$"

VerdanturfTown_Text_TownSign::
# 47 "data/maps/VerdanturfTown/scripts.pory"
	.string "VERDANTURF TOWN\p"
	.string "“The windswept highlands with the\n"
	.string "sweet fragrance of grass.”$"

VerdanturfTown_Text_BattleTentSign::
# 51 "data/maps/VerdanturfTown/scripts.pory"
	.string "BATTLE TENT VERDANTURF SITE “Feast\n"
	.string "Your Eyes on Battles!”$"

VerdanturfTown_Text_RusturfTunnelSign::
# 55 "data/maps/VerdanturfTown/scripts.pory"
	.string "RUSTURF TUNNEL “Linking RUSTBORO and\n"
	.string "VERDANTURF\p"
	.string "“The tunnel project has been\n"
	.string "canceled.”$"

VerdanturfTown_Text_AirCleanHere::
# 59 "data/maps/VerdanturfTown/scripts.pory"
	.string "The way the winds blow, volcanic ash\n"
	.string "is never blown in this direction.\p"
	.string "The air is clean and delicious here.\n"
	.string "Living here should do wonders for even\l"
	.string "frail and sickly people.$"

VerdanturfTown_Text_ManDugTunnelForLove::
# 63 "data/maps/VerdanturfTown/scripts.pory"
	.string "There was a man who dug a tunnel for\n"
	.string "a lady he loved.\p"
	.string "I don't really get it, but hey!$"

VerdanturfTown_Text_EasyToGetToRustboroNow::
# 67 "data/maps/VerdanturfTown/scripts.pory"
	.string "That cave next to the POKéMON MART\n"
	.string "is now a tunnel to the other side.\p"
	.string "It's great--it's easy to go shop for\n"
	.string "new DEVON products in RUSTBORO now.$"

VerdanturfTown_Text_MakeBattleTentDebut::
# 71 "data/maps/VerdanturfTown/scripts.pory"
	.string "My POKéMON and I, we've been riding\n"
	.string "a hot winning streak.\p"
	.string "So I decided to make my BATTLE TENT\n"
	.string "debut in this town.$"
