OneIsland_House2_MapScripts::
	.byte 0


OneIsland_House2_EventScript_Lass::
# 5 "data/maps/OneIsland_House2/scripts.pory"
	msgbox OneIsland_House2_Text_IWantToStayHereForever, MSGBOX_NPC
	end


OneIsland_House2_Text_IWantToStayHereForever::
# 10 "data/maps/OneIsland_House2/scripts.pory"
	.string "Young people all want to go off to\n"
	.string "big cities.\p"
	.string "But I want to stay here forever!$"
