Route110_TrickHousePuzzle4_MapScripts::
	.byte 0


Route110_TrickHousePuzzle4_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	msgbox Route110_TrickHousePuzzle4_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle4_Text_CoraDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_CoraDefeat$"

Route110_TrickHousePuzzle4_Text_CoraIntro::
# 9 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_CoraIntro$"

Route110_TrickHousePuzzle4_Text_CoraPostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_CoraPostBattle$"

Route110_TrickHousePuzzle4_Text_PaulaDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_PaulaDefeat$"

Route110_TrickHousePuzzle4_Text_PaulaIntro::
# 21 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_PaulaIntro$"

Route110_TrickHousePuzzle4_Text_PaulaPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_PaulaPostBattle$"

Route110_TrickHousePuzzle4_Text_YujiDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_YujiDefeat$"

Route110_TrickHousePuzzle4_Text_YujiIntro::
# 33 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_YujiIntro$"

Route110_TrickHousePuzzle4_Text_YujiPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle4_Text_YujiPostBattle$"

Route110_TrickHousePuzzle4_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"
