Route110_TrickHousePuzzle4_MapScripts::
	.byte 0


Route110_TrickHousePuzzle4_Text_WroteSecretCodeLockOpened::
# 5 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "TRICK MASTER is cool.\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle4_Text_CoraIntro::
# 9 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "It's too much bother to think this out.\n"
	.string "I only wanted to battle!$"

Route110_TrickHousePuzzle4_Text_CoraDefeat::
# 13 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Even though I lost, I still like battling\n"
	.string "the best!$"

Route110_TrickHousePuzzle4_Text_CoraPostBattle::
# 17 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Wouldn't you agree? You would go\n"
	.string "anywhere if TRAINERS were there.$"

Route110_TrickHousePuzzle4_Text_YujiIntro::
# 21 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Heh! Boulders like this, I can brush\n"
	.string "aside with one finger!$"

Route110_TrickHousePuzzle4_Text_YujiDefeat::
# 25 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "I can push boulders, but I can't solve\n"
	.string "the puzzle$"

Route110_TrickHousePuzzle4_Text_YujiPostBattle::
# 29 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "It's not good enough to be brawny You\n"
	.string "have to use your head. Be brainy!$"

Route110_TrickHousePuzzle4_Text_PaulaIntro::
# 33 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "The TRICK HOUSE is getting trickier,\n"
	.string "isn't it?$"

Route110_TrickHousePuzzle4_Text_PaulaDefeat::
# 37 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Aaak!$"

Route110_TrickHousePuzzle4_Text_PaulaPostBattle::
# 41 "data/maps/Route110_TrickHousePuzzle4/scripts.pory"
	.string "Has anyone made it to the end?$"
