LavaridgeTown_HerbShop_MapScripts::
	.byte 0


LavaridgeTown_HerbShop_EventScript_Clerk::
	end


LavaridgeTown_HerbShop_EventScript_ExpertM::
# 9 "data/maps/LavaridgeTown_HerbShop/scripts.pory"
	msgbox LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike, MSGBOX_NPC
	end


LavaridgeTown_HerbShop_EventScript_OldMan::
	end


LavaridgeTown_HerbShop_Text_HerbalMedicineWorksButMonWillDislike::
# 17 "data/maps/LavaridgeTown_HerbShop/scripts.pory"
	.string "Herbal medicine works impressively well.\n"
	.string "But your POKéMON will dislike you for it.\l"
	.string "It must be horribly bitter!$"

LavaridgeTown_HerbShop_Text_ExplainCharcoal::
# 21 "data/maps/LavaridgeTown_HerbShop/scripts.pory"
	.string "That CHARCOAL I gave you, it's used\n"
	.string "for making herbal medicine.\p"
	.string "It also does wonders when held by\n"
	.string "a POKéMON.\p"
	.string "It intensifies the power of FIRE-type\n"
	.string "moves.$"
