Route10_PokemonCenter_1F_MapScripts::
# 2 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route10_PokemonCenter_1F_OnTransition
# 3 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


Route10_PokemonCenter_1F_Text_EveryTypeStrongerThanOthers::
# 7 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "The types of POKMON match up\n"
	.string "differently with each other.\p"
	.string "Every type is stronger than some types\n"
	.string "and weaker than others.$"

Route10_PokemonCenter_1F_Text_NuggetUselessSoldFor5000::
# 11 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "A NUGGET is totally useless. So I sold it\n"
	.string "for 5000.$"

Route10_PokemonCenter_1F_Text_HeardGhostsHauntLavender::
# 15 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "I heard that ghosts haunt LAVENDER\n"
	.string "TOWN.$"

Route10_PokemonCenter_1F_Text_GiveEverstoneIfCaught20Mons::
# 19 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "Oh {PLAYER}! I've been looking for\n"
	.string "you!\p"
	.string "It's me, one of the ever-present AIDES\n"
	.string "to PROF. OAK.\p"
	.string "If your POKDEX has complete data on\n"
	.string "twenty species, I'm supposed to\l"
	.string "give you a reward from PROF. OAK.\p"
	.string "He entrusted me with this EVERSTONE.\p"
	.string "So, {PLAYER}, let me ask you.\p"
	.string "Have you gathered data on at least\n"
	.string "twenty kinds of POKMON?$"

Route10_PokemonCenter_1F_Text_GreatHereYouGo::
# 23 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "Great! You have caught or owned\n"
	.string "{STR_VAR_3} kinds of POKMON!\p"
	.string "Congratulations! Here you go!$"

Route10_PokemonCenter_1F_Text_ReceivedEverstoneFromAide::
# 27 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "{PLAYER} received the EVERSTONE from\n"
	.string "the AIDE.$"

Route10_PokemonCenter_1F_Text_ExplainEverstone::
# 31 "data/maps/Route10_PokemonCenter_1F/scripts.pory"
	.string "Making POKMON evolve certainly can add\n"
	.string "to the POKDEX.\p"
	.string "However, at times, you may not want a\n"
	.string "certain POKMON to evolve.\p"
	.string "In that case, give the EVERSTONE to\n"
	.string "that POKMON.\p"
	.string "It will prevent evolution according to\n"
	.string "the PROFESSOR.$"
