SixIsland_Mart_MapScripts::
	.byte 0


SixIsland_Mart_Text_AgathaOldestEverEliteFourMember::
# 5 "data/maps/SixIsland_Mart/scripts.pory"
	.string "Play with POKéMON lots and live a long\n"
	.string "life!\p"
	.string "Take AGATHA, for example.\p"
	.string "She set a record for being the\n"
	.string "oldest-ever ELITE FOUR member.\p"
	.string "She spurs me to do bigger things.$"

SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
# 9 "data/maps/SixIsland_Mart/scripts.pory"
	.string "I should buy some MAIL and write him a\n"
	.string "letter…$"
