SixIsland_Mart_MapScripts::
	.byte 0


SixIsland_Mart_EventScript_Clerk::
	end


SixIsland_Mart_EventScript_Picnicker::
# 9 "data/maps/SixIsland_Mart/scripts.pory"
	msgbox SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter, MSGBOX_NPC
	end


SixIsland_Mart_Text_ShouldBuyMailAndWriteLetter::
# 14 "data/maps/SixIsland_Mart/scripts.pory"
	.string "I should buy some MAIL and write\n"
	.string "him a letter…$"
