LakeOfRage_MapScripts::
	.byte 0


LakeOfRage_EventScript_Sign1::
# 6 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_Sign1, MSGBOX_SIGN
	end


LakeOfRage_EventScript_SmithNPC1::
# 15 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_SmithNPC1, MSGBOX_NPC
	end


LakeOfRage_EventScript_SmithNPC2::
# 24 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_SmithNPC2, MSGBOX_NPC
	end


LakeOfRage_EventScript_SmithNPC3::
# 33 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_SmithNPC3, MSGBOX_NPC
	end


LakeOfRage_EventScript_SmithNPC4::
# 42 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_SmithNPC4, MSGBOX_NPC
	end


LakeOfRage_EventScript_SmithNPC5::
# 51 "data/maps/LakeOfRage/scripts.pory"
	msgbox LakeOfRage_Text_SmithNPC5, MSGBOX_NPC
	end


LakeOfRage_Text_Sign1::
# 10 "data/maps/LakeOfRage/scripts.pory"
	.string "LakeOfRage Sign 1$"

LakeOfRage_Text_SmithNPC1::
# 19 "data/maps/LakeOfRage/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

LakeOfRage_Text_SmithNPC2::
# 28 "data/maps/LakeOfRage/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

LakeOfRage_Text_SmithNPC3::
# 37 "data/maps/LakeOfRage/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

LakeOfRage_Text_SmithNPC4::
# 46 "data/maps/LakeOfRage/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

LakeOfRage_Text_SmithNPC5::
# 55 "data/maps/LakeOfRage/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"
