SunyshoreCity_MapScripts::
	.byte 0


SunyshoreCity_EventScript_Sign1::
# 6 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_Sign1, MSGBOX_SIGN
	end


SunyshoreCity_EventScript_Sign2::
# 15 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_Sign2, MSGBOX_SIGN
	end


SunyshoreCity_EventScript_SmithNPC1::
# 24 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC1, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC2::
# 33 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC2, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC3::
# 42 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC3, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC4::
# 51 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC4, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC5::
# 60 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC5, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC6::
# 69 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC6, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC7::
# 78 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC7, MSGBOX_NPC
	end


SunyshoreCity_EventScript_SmithNPC8::
# 87 "data/maps/SunyshoreCity/scripts.pory"
	msgbox SunyshoreCity_Text_SmithNPC8, MSGBOX_NPC
	end


SunyshoreCity_Text_Sign1::
# 10 "data/maps/SunyshoreCity/scripts.pory"
	.string "SunyshoreCity Sign 1$"

SunyshoreCity_Text_Sign2::
# 19 "data/maps/SunyshoreCity/scripts.pory"
	.string "SunyshoreCity Sign 2$"

SunyshoreCity_Text_SmithNPC1::
# 28 "data/maps/SunyshoreCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

SunyshoreCity_Text_SmithNPC2::
# 37 "data/maps/SunyshoreCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

SunyshoreCity_Text_SmithNPC3::
# 46 "data/maps/SunyshoreCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

SunyshoreCity_Text_SmithNPC4::
# 55 "data/maps/SunyshoreCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

SunyshoreCity_Text_SmithNPC5::
# 64 "data/maps/SunyshoreCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

SunyshoreCity_Text_SmithNPC6::
# 73 "data/maps/SunyshoreCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

SunyshoreCity_Text_SmithNPC7::
# 82 "data/maps/SunyshoreCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

SunyshoreCity_Text_SmithNPC8::
# 91 "data/maps/SunyshoreCity/scripts.pory"
	.string "I know kung fu.$"
