MauvilleCity_House2_MapScripts::
	.byte 0


MauvilleCity_House2_EventScript_Woman::
	end


MauvilleCity_House2_Text_IllTradeYouCoinCase::
# 8 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, I'm so happy!\n"
	.string "Okay, I'll trade you a COIN CASE!$"

MauvilleCity_House2_Text_ThatsDisappointing::
# 12 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, that's disappointing.\p"
	.string "A COIN CASE is needed for the\n"
	.string "GAME CORNER.$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner::
# 16 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "That COIN CASE can be used\n"
	.string "at the GAME CORNER.$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase::
# 20 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh! You have HARBOR MAIL?\n"
	.string "Will you trade it for a COIN CASE?$"
