MauvilleCity_House2_MapScripts::
	.byte 0


MauvilleCity_House2_MapScripts::
	return


MauvilleCity_House2_Text_BuyHarborMailAtSlateport::
# 8 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "If I had a BIKE, it'd be easy to cycle to\n"
	.string "SLATEPORT for some shopping.\p"
	.string "I'd be able to buy HARBOR MAIL at the\n"
	.string "POKéMON MART in SLATEPORT…$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase::
# 12 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh! You have HARBOR MAIL? Will you\n"
	.string "trade it for a COIN CASE?$"

MauvilleCity_House2_Text_IllTradeYouCoinCase::
# 16 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, I'm so happy! Okay, I'll trade you a\n"
	.string "COIN CASE!$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner::
# 20 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "That COIN CASE can be used at the GAME\n"
	.string "CORNER.$"

MauvilleCity_House2_Text_ThatsDisappointing::
# 24 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, that's disappointing.\p"
	.string "A COIN CASE is needed for the GAME\n"
	.string "CORNER.$"
