MauvilleCity_House2_MapScripts::
	.byte 0


MauvilleCity_House2_Text_BuyHarborMailAtSlateport::
# 5 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "If I had a BIKE, it'd be easy to cycle to\n"
	.string "SLATEPORT for some shopping.\p"
	.string "I'd be able to buy HARBOR MAIL at the\n"
	.string "POKéMON MART in SLATEPORT…$"

MauvilleCity_House2_Text_TradeHarborMailForCoinCase::
# 9 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh! You have HARBOR MAIL? Will you\n"
	.string "trade it for a COIN CASE?$"

MauvilleCity_House2_Text_IllTradeYouCoinCase::
# 13 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, I'm so happy! Okay, I'll trade you a\n"
	.string "COIN CASE!$"

MauvilleCity_House2_Text_UseCoinCaseAtGameCorner::
# 17 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "That COIN CASE can be used at the GAME\n"
	.string "CORNER.$"

MauvilleCity_House2_Text_ThatsDisappointing::
# 21 "data/maps/MauvilleCity_House2/scripts.pory"
	.string "Oh, that's disappointing.\p"
	.string "A COIN CASE is needed for the GAME\n"
	.string "CORNER.$"
