TwinleafTown_House2_MapScripts::
	.byte 0


TwinleafTown_House2_EventScript_SmithNPC1::
# 5 "data/maps/TwinleafTown_House2/scripts.pory"
	msgbox TwinleafTown_House2_Text_SmithNPC1, MSGBOX_NPC
	end


TwinleafTown_House2_EventScript_SmithNPC2::
# 14 "data/maps/TwinleafTown_House2/scripts.pory"
	msgbox TwinleafTown_House2_Text_SmithNPC2, MSGBOX_NPC
	end


TwinleafTown_House2_Text_SmithNPC1::
# 9 "data/maps/TwinleafTown_House2/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

TwinleafTown_House2_Text_SmithNPC2::
# 18 "data/maps/TwinleafTown_House2/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
