OreburghMine_B2F_MapScripts::
	.byte 0


OreburghMine_B2F_EventScript_SmithNPC1::
# 5 "data/maps/OreburghMine_B2F/scripts.pory"
	msgbox OreburghMine_B2F_Text_SmithNPC1, MSGBOX_NPC
	end


OreburghMine_B2F_EventScript_SmithNPC2::
# 14 "data/maps/OreburghMine_B2F/scripts.pory"
	msgbox OreburghMine_B2F_Text_SmithNPC2, MSGBOX_NPC
	end


OreburghMine_B2F_EventScript_SmithNPC3::
# 23 "data/maps/OreburghMine_B2F/scripts.pory"
	msgbox OreburghMine_B2F_Text_SmithNPC3, MSGBOX_NPC
	end


OreburghMine_B2F_Text_SmithNPC1::
# 9 "data/maps/OreburghMine_B2F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OreburghMine_B2F_Text_SmithNPC2::
# 18 "data/maps/OreburghMine_B2F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

OreburghMine_B2F_Text_SmithNPC3::
# 27 "data/maps/OreburghMine_B2F/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"
