SSAnne_B1F_Room2_MapScripts::
	.byte 0


SSAnne_B1F_Room2_Text_HueyIntro::
# 5 "data/maps/SSAnne_B1F_Room2/scripts.pory"
	.string "Even us sailors have POKMON, too!$"

SSAnne_B1F_Room2_Text_HueyDefeat::
# 9 "data/maps/SSAnne_B1F_Room2/scripts.pory"
	.string "Okay, you're not bad.$"

SSAnne_B1F_Room2_Text_HueyPostBattle::
# 13 "data/maps/SSAnne_B1F_Room2/scripts.pory"
	.string "We caught all our POKMON while we were\n"
	.string "out at sea.$"
