Route110_TrickHousePuzzle1_MapScripts::
# 2 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route110_TrickHousePuzzle1_OnLoad
	.byte 0


Route110_TrickHousePuzzle1_MapScripts::
# 6 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, Route110_TrickHousePuzzle1_OnLoad
	return


Route110_TrickHousePuzzle1_Text_WroteSecretCodeLockOpened::
# 10 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "{PLAYER} wrote down the secret code\n"
	.string "on the door.\p"
	.string "“TRICK MASTER is fabulous.” … … … … … …\n"
	.string "… …\p"
	.string "The lock clicked open!$"

Route110_TrickHousePuzzle1_Text_SallyIntro::
# 14 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I'll hack and slash my way to victory\n"
	.string "with the CUT we just learned!$"

Route110_TrickHousePuzzle1_Text_SallyDefeat::
# 18 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Why are you so serious?$"

Route110_TrickHousePuzzle1_Text_SallyPostBattle::
# 22 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I never get tired of hacking and\n"
	.string "slashing!$"

Route110_TrickHousePuzzle1_Text_EddieIntro::
# 26 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I wandered into this weird house by\n"
	.string "accident…$"

Route110_TrickHousePuzzle1_Text_EddieDefeat::
# 30 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "And now I've lost…$"

Route110_TrickHousePuzzle1_Text_EddiePostBattle::
# 34 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I lost my way, I lost a battle, and I'm\n"
	.string "now even more lost… I can't get out…$"

Route110_TrickHousePuzzle1_Text_RobinIntro::
# 38 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Just who is the TRICK MASTER?$"

Route110_TrickHousePuzzle1_Text_RobinDefeat::
# 42 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I lost while I was lost in thought!$"

Route110_TrickHousePuzzle1_Text_RobinPostBattle::
# 46 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "You're strong! Just who are you?$"
