Route110_TrickHousePuzzle1_MapScripts::
	.byte 0


Route110_TrickHousePuzzle1_EventScript_SmithNPC1::
# 42 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	msgbox Route110_TrickHousePuzzle1_Text_SmithNPC1, MSGBOX_NPC
	end


Route110_TrickHousePuzzle1_Text_EddieDefeat::
# 5 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_EddieDefeat$"

Route110_TrickHousePuzzle1_Text_EddieIntro::
# 9 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_EddieIntro$"

Route110_TrickHousePuzzle1_Text_EddiePostBattle::
# 13 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_EddiePostBattle$"

Route110_TrickHousePuzzle1_Text_RobinDefeat::
# 17 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_RobinDefeat$"

Route110_TrickHousePuzzle1_Text_RobinIntro::
# 21 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_RobinIntro$"

Route110_TrickHousePuzzle1_Text_RobinPostBattle::
# 25 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_RobinPostBattle$"

Route110_TrickHousePuzzle1_Text_SallyDefeat::
# 29 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_SallyDefeat$"

Route110_TrickHousePuzzle1_Text_SallyIntro::
# 33 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_SallyIntro$"

Route110_TrickHousePuzzle1_Text_SallyPostBattle::
# 37 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "Placeholder text for\n"
	.string "Route110_TrickHousePuzzle1_Text_SallyPostBattle$"

Route110_TrickHousePuzzle1_Text_SmithNPC1::
# 46 "data/maps/Route110_TrickHousePuzzle1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"
