CeruleanCity_MapScripts::
# 2 "data/maps/CeruleanCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeruleanCity_OnTransition
	.byte 0


CeruleanCity_Text_RivalIntro::
# 6 "data/maps/CeruleanCity/scripts.pory"
	.string "{RIVAL}: Yo! {PLAYER}!\p"
	.string "You're still struggling along back here?\p"
	.string "I'm doing great! I caught a bunch of\n"
	.string "strong and smart POKéMON!\p"
	.string "Here, let me see what you caught,\n"
	.string "{PLAYER}!$"

CeruleanCity_Text_RivalDefeat::
# 10 "data/maps/CeruleanCity/scripts.pory"
	.string "Hey! Take it easy!\l"
	.string "You won already!$"

CeruleanCity_Text_RivalPostBattle::
# 14 "data/maps/CeruleanCity/scripts.pory"
	.string "{RIVAL}: Hey, guess what?\p"
	.string "I went to BILL's and got him to show me\n"
	.string "his rare POKéMON.\p"
	.string "That added a lot of pages to my\n"
	.string "POKéDEX!\p"
	.string "After all, BILL's world famous as a\n"
	.string "POKéMANIAC.\p"
	.string "He invented the POKéMON Storage\n"
	.string "System on PC, too.\p"
	.string "Since you're using his system, you\n"
	.string "should go thank him.\p"
	.string "Well, I better get rolling! Smell ya\n"
	.string "later!$"

CeruleanCity_Text_OhRightLittlePresentAsFavor::
# 18 "data/maps/CeruleanCity/scripts.pory"
	.string "Oh, yeah, right.\p"
	.string "I feel sorry for you. No, really. You're\n"
	.string "always plodding behind me.\p"
	.string "So here, I'll give you a little present as\n"
	.string "a favor.$"

CeruleanCity_Text_ExplainFameCheckerSmellYa::
# 22 "data/maps/CeruleanCity/scripts.pory"
	.string "A chatty gossip like you… That thing's\n"
	.string "perfect.\p"
	.string "I don't need it because I don't give a\n"
	.string "hoot about others.\p"
	.string "All right, this time I really am gone.\n"
	.string "Smell ya!$"

CeruleanCity_Text_RivalVictory::
# 26 "data/maps/CeruleanCity/scripts.pory"
	.string "なんたって！ おれは　てんさい　だからよ！$"

CeruleanCity_Text_GruntIntro::
# 30 "data/maps/CeruleanCity/scripts.pory"
	.string "Hey! Stay out! It's not your yard!\p"
	.string "…Huh? Me?\p"
	.string "I'm an innocent bystander! Don't you\n"
	.string "believe me?{PLAY_BGM}{MUS_ENCOUNTER_ROCKET}$"

CeruleanCity_Text_GruntDefeat::
# 34 "data/maps/CeruleanCity/scripts.pory"
	.string "GRUNT: Stop! I give up! I'll leave\n"
	.string "quietly!$"

CeruleanCity_Text_OkayIllReturnStolenTM::
# 38 "data/maps/CeruleanCity/scripts.pory"
	.string "…Okay. I'll return the TM I stole.$"

CeruleanCity_Text_RecoveredTM28FromGrunt::
# 42 "data/maps/CeruleanCity/scripts.pory"
	.string "{PLAYER} recovered TM28 from the\n"
	.string "TEAM ROCKET GRUNT.$"

CeruleanCity_Text_BetterGetMovingBye::
# 46 "data/maps/CeruleanCity/scripts.pory"
	.string "I better get moving! Bye!$"

CeruleanCity_Text_MakeRoomForThisCantRun::
# 50 "data/maps/CeruleanCity/scripts.pory"
	.string "Make room for this! I can't run until I\n"
	.string "give it to you!$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
# 54 "data/maps/CeruleanCity/scripts.pory"
	.string "You're a TRAINER, too?\p"
	.string "Collecting, battling… It's a tough life,\n"
	.string "isn't it?$"

CeruleanCity_Text_YouCanCutDownSmallTrees::
# 58 "data/maps/CeruleanCity/scripts.pory"
	.string "Did you know that you can CUT down\n"
	.string "small trees?\p"
	.string "Even that small tree in front of the\n"
	.string "shop can be CUT down.\p"
	.string "I think there's a way around it, though.$"

CeruleanCity_Text_IfSlowbroWasntThereCouldCutTree::
# 62 "data/maps/CeruleanCity/scripts.pory"
	.string "If that SLOWBRO wasn't there, you could\n"
	.string "CUT down the small tree.\p"
	.string "That way, you could get to the other\n"
	.string "side.\p"
	.string "I think there's a way around it, though.$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
# 66 "data/maps/CeruleanCity/scripts.pory"
	.string "You're making an encyclopedia on\n"
	.string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_PeopleHereWereRobbed::
# 70 "data/maps/CeruleanCity/scripts.pory"
	.string "The people here were robbed.\p"
	.string "It's obvious that TEAM ROCKET is behind\n"
	.string "this most heinous crime!\p"
	.string "Even our POLICE FORCE has trouble with\n"
	.string "the ROCKETS!$"

CeruleanCity_Text_SlowbroUseSonicboom::
# 74 "data/maps/CeruleanCity/scripts.pory"
	.string "Okay! SLOWBRO! Use SONICBOOM!$"

CeruleanCity_Text_SlowbroPayAttention::
# 78 "data/maps/CeruleanCity/scripts.pory"
	.string "Come on, SLOWBRO, pay attention!$"

CeruleanCity_Text_SlowbroPunch::
# 82 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO, punch!$"

CeruleanCity_Text_NoYouBlewItAgain::
# 86 "data/maps/CeruleanCity/scripts.pory"
	.string "No! You blew it again!$"

CeruleanCity_Text_SlowbroWithdraw::
# 90 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO, WITHDRAW!$"

CeruleanCity_Text_HardToControlMonsObedience::
# 94 "data/maps/CeruleanCity/scripts.pory"
	.string "No! That's wrong! It's so hard to\n"
	.string "control POKéMON!\p"
	.string "Your POKéMON's obedience depends on\n"
	.string "your abilities as a TRAINER.$"

CeruleanCity_Text_SlowbroTookSnooze::
# 98 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO took a snooze…$"

CeruleanCity_Text_SlowbroLoafingAround::
# 102 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO is loafing around…$"

CeruleanCity_Text_SlowbroTurnedAway::
# 106 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO turned away…$"

CeruleanCity_Text_SlowbroIgnoredOrders::
# 110 "data/maps/CeruleanCity/scripts.pory"
	.string "SLOWBRO ignored orders…$"

CeruleanCity_Text_WantBrightRedBicycle::
# 114 "data/maps/CeruleanCity/scripts.pory"
	.string "I want a bright red bicycle.\p"
	.string "I'll keep it at home, so it won't get\n"
	.string "dirty.$"

CeruleanCity_Text_ThisIsCeruleanCave::
# 118 "data/maps/CeruleanCity/scripts.pory"
	.string "This is CERULEAN CAVE.\p"
	.string "Horribly strong POKéMON live inside\n"
	.string "there.\p"
	.string "It takes a very special TRAINER to be\n"
	.string "allowed inside there.\p"
	.string "You'd have to be strong enough to\n"
	.string "become the POKéMON LEAGUE\l"
	.string "CHAMPION for starters.\p"
	.string "And, you would have to have made a\n"
	.string "great achievement.$"

CeruleanCity_Text_CitySign::
# 122 "data/maps/CeruleanCity/scripts.pory"
	.string "CERULEAN CITY A Mysterious, Blue Aura\n"
	.string "Surrounds\l"
	.string "It$"

CeruleanCity_Text_TrainerTipsHeldItems::
# 126 "data/maps/CeruleanCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "A POKéMON can be made to hold an item.\p"
	.string "Some items can even be used by the\n"
	.string "holding POKéMON in battle.$"

CeruleanCity_Text_BikeShopSign::
# 130 "data/maps/CeruleanCity/scripts.pory"
	.string "Grass and caves handled easily! BIKE\n"
	.string "SHOP$"

CeruleanCity_Text_GymSign::
# 134 "data/maps/CeruleanCity/scripts.pory"
	.string "CERULEAN CITY POKéMON GYM LEADER:\n"
	.string "MISTY\l"
	.string "The Tomboyish Mermaid!$"
