CeruleanCity_MapScripts::
	.byte 0


CeruleanCity_BikeShop_EventScript_Bicycle::
	end


CeruleanCity_EventScript_BaldingMan::
# 9 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_PokemonEncyclopediaAmusing, MSGBOX_NPC
	end


CeruleanCity_EventScript_BikeShopSign::
# 14 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_BikeShopSign, MSGBOX_SIGN
	end


CeruleanCity_EventScript_CeruleanCaveGuard::
# 19 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_ThisIsCeruleanCave, MSGBOX_NPC
	end


CeruleanCity_EventScript_CitySign::
# 24 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_CitySign, MSGBOX_SIGN
	end


CeruleanCity_EventScript_Grunt::
	end


CeruleanCity_EventScript_GruntTriggerBottom::
	end


CeruleanCity_EventScript_GruntTriggerTop::
	end


CeruleanCity_EventScript_GymSign::
# 43 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_GymSign, MSGBOX_SIGN
	end


CeruleanCity_EventScript_Lass::
	end


CeruleanCity_EventScript_LittleBoy::
	end


CeruleanCity_EventScript_Policeman::
	end


CeruleanCity_EventScript_RivalTriggerLeft::
	end


CeruleanCity_EventScript_RivalTriggerMid::
	end


CeruleanCity_EventScript_RivalTriggerRight::
	end


CeruleanCity_EventScript_Slowbro::
	end


CeruleanCity_EventScript_TrainerTips::
# 77 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_TrainerTipsHeldItems, MSGBOX_SIGN
	end


CeruleanCity_EventScript_Woman::
	end


CeruleanCity_EventScript_Youngster::
# 86 "data/maps/CeruleanCity/scripts.pory"
	msgbox CeruleanCity_Text_TrainerLifeIsToughIsntIt, MSGBOX_NPC
	end


CeruleanCity_Text_TrainerTipsHeldItems::
# 90 "data/maps/CeruleanCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "A POKéMON can be made to hold an item.\p"
	.string "Some items can even be used by the\n"
	.string "holding POKéMON in battle.$"

CeruleanCity_Text_GymSign::
# 94 "data/maps/CeruleanCity/scripts.pory"
	.string "CERULEAN CITY POKéMON GYM LEADER:\n"
	.string "MISTY\l"
	.string "The Tomboyish Mermaid!$"

CeruleanCity_Text_CitySign::
# 98 "data/maps/CeruleanCity/scripts.pory"
	.string "CERULEAN CITY A Mysterious, Blue Aura\n"
	.string "Surrounds\l"
	.string "It$"

CeruleanCity_Text_BikeShopSign::
# 102 "data/maps/CeruleanCity/scripts.pory"
	.string "Grass and caves handled easily! BIKE\n"
	.string "SHOP$"

CeruleanCity_Text_PokemonEncyclopediaAmusing::
# 106 "data/maps/CeruleanCity/scripts.pory"
	.string "You're making an encyclopedia on\n"
	.string "POKéMON? That sounds amusing.$"

CeruleanCity_Text_ThisIsCeruleanCave::
# 110 "data/maps/CeruleanCity/scripts.pory"
	.string "This is CERULEAN CAVE.\p"
	.string "Horribly strong POKéMON live inside\n"
	.string "there.\p"
	.string "It takes a very special TRAINER to\n"
	.string "be allowed inside there.\p"
	.string "You'd have to be strong enough to\n"
	.string "become the POKéMON LEAGUE\l"
	.string "CHAMPION for starters.\p"
	.string "And, you would have to have\n"
	.string "made a great achievement.$"

CeruleanCity_Text_TrainerLifeIsToughIsntIt::
# 114 "data/maps/CeruleanCity/scripts.pory"
	.string "You're a TRAINER, too?\p"
	.string "Collecting, battling…\n"
	.string "It's a tough life, isn't it?$"
