CeruleanCity_BikeShop_MapScripts::
	.byte 0


CeruleanCity_BikeShop_Text_WelcomeToBikeShop::
# 5 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "Hi! Welcome to our BIKE SHOP.\p"
	.string "Have we got just the BIKE for you!$"

CeruleanCity_BikeShop_Text_SorryYouCantAffordIt::
# 9 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "Sorry! You can't afford it!$"

CeruleanCity_BikeShop_Text_OhBikeVoucherHereYouGo::
# 13 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "Oh, that's…\p"
	.string "A BIKE VOUCHER!\p"
	.string "Okay! Here you go!$"

CeruleanCity_BikeShop_Text_ExchangedVoucherForBicycle::
# 17 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "{PLAYER} exchanged the BIKE VOUCHER\n"
	.string "for a BICYCLE.$"

CeruleanCity_BikeShop_Text_ThankYouComeAgain::
# 21 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "Thank you! Come back again sometime!$"

CeruleanCity_BikeShop_Text_HowDoYouLikeNewBicycle::
# 25 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "How do you like your new BICYCLE? Do\n"
	.string "you like how it rides?\p"
	.string "You can take it out on CYCLING ROAD and\n"
	.string "even into caves!$"

CeruleanCity_BikeShop_Text_MakeRoomForBicycle::
# 29 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "You better make room for your BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
# 33 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "A plain city bike is good enough for me.\p"
	.string "After all, you can't put a shopping\n"
	.string "basket on a mountain bike.$"

CeruleanCity_BikeShop_Text_BikesCoolButExpensive::
# 37 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "These bikes are cool, but they're way\n"
	.string "expensive!$"

CeruleanCity_BikeShop_Text_WowYourBikeIsCool::
# 41 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "Wow. Your BIKE is really cool!$"

CeruleanCity_BikeShop_Text_GermanFoldableBicyleFinallyOnMarket::
# 45 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "ついに　はつばい！\p"
	.string "ドイツ　せい　さいこうきゅう おりたたみ　じてんしゃ！$"

CeruleanCity_BikeShop_Text_ShinyNewBicycle::
# 49 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "A shiny new BICYCLE!$"
