CeruleanCity_BikeShop_MapScripts::
	.byte 0


CeruleanCity_BikeShop_EventScript_Clerk::
	end


CeruleanCity_BikeShop_EventScript_Woman::
# 10 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	msgbox CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe, MSGBOX_NPC
	end


CeruleanCity_BikeShop_EventScript_Youngster::
	end


CeruleanCity_BikeShop_Text_ShinyNewBicycle::
# 19 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "A shiny new BICYCLE!$"

CeruleanCity_BikeShop_Text_CityBikeGoodEnoughForMe::
# 23 "data/maps/CeruleanCity_BikeShop/scripts.pory"
	.string "A plain city bike is good enough\n"
	.string "for me.\p"
	.string "After all, you can't put a shopping\n"
	.string "basket on a mountain bike.$"
