CaveOfOrigin_UnusedRubySapphireMap2_MapScripts::
# 2 "data/maps/CaveOfOrigin_UnusedRubySapphireMap2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CaveOfOrigin_UnusedRubySapphireMap2_OnTransition
	.byte 0


CaveOfOrigin_UnusedRubySapphireMap2_MapScripts::
# 6 "data/maps/CaveOfOrigin_UnusedRubySapphireMap2/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CaveOfOrigin_UnusedRubySapphireMap2_OnTransition
	return

