Twinleaf_Town_RivalsHouse_F1_MapScripts::
	.byte 0


Twinleaf_Town_RivalsHouse_F1_EventScript_SmithNPC1::
# 5 "data/maps/Twinleaf_Town_RivalsHouse_F1/scripts.pory"
	msgbox Twinleaf_Town_RivalsHouse_F1_Text_SmithNPC1, MSGBOX_NPC
	end


Twinleaf_Town_RivalsHouse_F1_EventScript_SmithNPC2::
# 14 "data/maps/Twinleaf_Town_RivalsHouse_F1/scripts.pory"
	msgbox Twinleaf_Town_RivalsHouse_F1_Text_SmithNPC2, MSGBOX_NPC
	end


Twinleaf_Town_RivalsHouse_F1_Text_SmithNPC1::
# 9 "data/maps/Twinleaf_Town_RivalsHouse_F1/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

Twinleaf_Town_RivalsHouse_F1_Text_SmithNPC2::
# 18 "data/maps/Twinleaf_Town_RivalsHouse_F1/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
