FiveIsland_RocketWarehouse_MapScripts::
# 2 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, FiveIsland_RocketWarehouse_OnLoad
# 3 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FiveIsland_RocketWarehouse_OnTransition
	.byte 0


FiveIsland_RocketWarehouse_Text_ManyMonsLockedInPen::
# 7 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "There are many POKéMON locked away in\n"
	.string "the pen…$"

FiveIsland_RocketWarehouse_Text_PenUnlockedMonsFled::
# 11 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "The pen door is unlocked. The POKéMON\n"
	.string "appear to have fled.$"

FiveIsland_RocketWarehouse_Text_Grunt2Intro::
# 15 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Did you come here knowing it's TEAM\n"
	.string "ROCKET's WAREHOUSE?$"

FiveIsland_RocketWarehouse_Text_Grunt2Defeat::
# 19 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "What do you think you're doing?!$"

FiveIsland_RocketWarehouse_Text_Grunt2PostBattle::
# 23 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "TEAM ROCKET broke up? What planet are\n"
	.string "you from?$"

FiveIsland_RocketWarehouse_Text_Grunt1Intro::
# 27 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Oh, now your POKéMON look strong. You're\n"
	.string "willing to sell them?\p"
	.string "Oh? You wanted to battle?$"

FiveIsland_RocketWarehouse_Text_Grunt1Defeat::
# 31 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Oh, but… Too much!$"

FiveIsland_RocketWarehouse_Text_Grunt1PostBattle::
# 35 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "We can give you a great price. Sell us\n"
	.string "your POKéMON!$"

FiveIsland_RocketWarehouse_Text_Grunt3Intro::
# 39 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "I got word about you from the others.\p"
	.string "But there's no way a kid like you'd know\n"
	.string "our BOSS GIOVANNI!$"

FiveIsland_RocketWarehouse_Text_Grunt3Defeat::
# 43 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Don't…you…dare…laugh…$"

FiveIsland_RocketWarehouse_Text_Grunt3PostBattle::
# 47 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Don't mess in the doings of adults, you\n"
	.string "jumped-up pip-squeak!$"

FiveIsland_RocketWarehouse_Text_Admin1Intro::
# 51 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "I don't know or care if what I'm doing is\n"
	.string "right or wrong…\p"
	.string "I just put my faith in GIOVANNI and do\n"
	.string "as I am told.$"

FiveIsland_RocketWarehouse_Text_Admin1Defeat::
# 55 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "I… I'm shattered…$"

FiveIsland_RocketWarehouse_Text_Admin1PostBattle::
# 59 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "You're doing things according to your\n"
	.string "beliefs and morals.\p"
	.string "I understand now…$"

FiveIsland_RocketWarehouse_Text_MadeItSoYouCanComeBackThrough::
# 63 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "I've made it so you can come back in\n"
	.string "through there.\p"
	.string "Why don't you go get rested and\n"
	.string "refreshed for what lies ahead?\p"
	.string "The ADMIN after me outranks me\n"
	.string "thoroughly as a TRAINER.\p"
	.string "You'd better steel yourself for one\n"
	.string "harsh challenge.$"

FiveIsland_RocketWarehouse_Text_Admin2Intro::
# 67 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "That's quite enough of you playing the\n"
	.string "hero, kid.\p"
	.string "Spreading lies about how TEAM ROCKET\n"
	.string "has disbanded…\p"
	.string "It's such an obvious attempt to cause\n"
	.string "confusion in our ranks.\p"
	.string "Fortunately, we're not so ignorant to\n"
	.string "fall for the lies of a child!\p"
	.string "And now, I'll show you how scary an\n"
	.string "angry adult can be!$"

FiveIsland_RocketWarehouse_Text_Admin2Defeat::
# 71 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Urgh… You were too strong…\p"
	.string "… Th-that's GIOVANNI's BADGE!\p"
	.string "So it's true? TEAM ROCKET really has\n"
	.string "disbanded?$"

FiveIsland_RocketWarehouse_Text_Admin2PostBattle::
# 75 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "We will abandon this WAREHOUSE…\p"
	.string "But don't think this is over. I won't let\n"
	.string "this be the end.\p"
	.string "I will find GIOVANNI. And I will\n"
	.string "resurrect TEAM ROCKET!\l"
	.string "I will…\p"
	.string "Until then, farewell!$"

FiveIsland_RocketWarehouse_Text_ReportWithGraphsAndText::
# 79 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "A report with graphs and text is on the\n"
	.string "PC monitor.\p"
	.string "“The Influence of Magnetic Waves on\n"
	.string "POKéMON Evolution”…\p"
	.string "… … … … … …\p"
	.string "It's too difficult to understand…$"

FiveIsland_RocketWarehouse_Text_GideonIntro::
# 83 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "I almost managed to sell the SAPPHIRE\n"
	.string "for huge money…\p"
	.string "Then, you just had to come along and\n"
	.string "blow the whole deal apart!\p"
	.string "Fufu… Fufufufu… There's no\n"
	.string "forgiveness for you!$"

FiveIsland_RocketWarehouse_Text_GideonDefeat::
# 87 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "Gah! Darn! Darn! Darn!$"

FiveIsland_RocketWarehouse_Text_GideonPostBattle::
# 91 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "If I can't sell it, it's worthless! Go\n"
	.string "ahead, take it!$"

FiveIsland_RocketWarehouse_Text_GetLostLeaveMeBe::
# 95 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "What do you want now? Go on, get lost,\n"
	.string "leave me be.$"

FiveIsland_RocketWarehouse_Text_GiovannisKidHasRedHair::
# 99 "data/maps/FiveIsland_RocketWarehouse/scripts.pory"
	.string "What, you again?\p"
	.string "You… You're not GIOVANNI's kid, are\n"
	.string "you?\p"
	.string "No, that can't be right! GIOVANNI's kid\n"
	.string "has red hair.\p"
	.string "You don't have any reasons for bugging\n"
	.string "me. Leave me alone!$"
