MtSilver_SouthRoom_MapScripts::
	.byte 0


MtSilver_SouthRoom_EventScript_SmithNPC1::
# 5 "data/maps/MtSilver_SouthRoom/scripts.pory"
	msgbox MtSilver_SouthRoom_Text_SmithNPC1, MSGBOX_NPC
	end


MtSilver_SouthRoom_EventScript_SmithNPC2::
# 14 "data/maps/MtSilver_SouthRoom/scripts.pory"
	msgbox MtSilver_SouthRoom_Text_SmithNPC2, MSGBOX_NPC
	end


MtSilver_SouthRoom_Text_SmithNPC1::
# 9 "data/maps/MtSilver_SouthRoom/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

MtSilver_SouthRoom_Text_SmithNPC2::
# 18 "data/maps/MtSilver_SouthRoom/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
