CeruleanCity_House3_MapScripts::
	.byte 0


CeruleanCity_House3_EventScript_Dontae::
	end


CeruleanCity_House3_EventScript_OldWoman::
# 9 "data/maps/CeruleanCity_House3/scripts.pory"
	msgbox CeruleanCity_House3_Text_PleaseTradeWithMyHusband, MSGBOX_NPC
	end


CeruleanCity_House3_Text_PleaseTradeWithMyHusband::
# 14 "data/maps/CeruleanCity_House3/scripts.pory"
	.string "My husband likes trading POKéMON.\p"
	.string "You're collecting POKéMON for your\n"
	.string "POKéDEX, aren't you?\p"
	.string "Would you please trade with him?$"
