CeladonCity_DepartmentStore_1F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_1F_Text_WelcomeToDeptStore::
# 5 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	.string "Hello! Welcome to CELADON DEPT. STORE.\p"
	.string "The board on the right describes the\n"
	.string "store layout.$"

CeladonCity_DepartmentStore_1F_Text_FloorDescriptions::
# 9 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	.string "1F: SERVICE COUNTER\p"
	.string "2F: TRAINER'S MARKET\p"
	.string "3F: TV GAME SHOP\p"
	.string "4F: WISE MAN GIFTS\p"
	.string "5F: DRUGSTORE\p"
	.string "ROOFTOP SQUARE: VENDING MACHINES$"

CeladonCity_DepartmentStore_1F_Text_ServiceCounter::
# 13 "data/maps/CeladonCity_DepartmentStore_1F/scripts.pory"
	.string "1F: SERVICE COUNTER$"
