FiveIsland_Meadow_MapScripts::
# 2 "data/maps/FiveIsland_Meadow/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, FiveIsland_Meadow_OnLoad
	.byte 0


FiveIsland_Meadow_Text_DoorNeedsTwoPasswords::
# 6 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "2$"

FiveIsland_Meadow_Text_EnteredPasswordAnotherNeeded::
# 10 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "{PLAYER} entered a password.\p"
	.string "GOLDEEN need log.\p"
	.string "\p"
	.string "Another password is needed to open the\n"
	.string "door$"

FiveIsland_Meadow_Text_EnteredPasswordDoorOpened::
# 14 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "{PLAYER} entered two passwords.\p"
	.string "GOLDEEN need log. Yes, nah, CHANSEY.\p"
	.string "\p"
	.string "The WAREHOUSE's door opened!$"

FiveIsland_Meadow_Text_WarehouseDoorAlreadyOpen::
# 18 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "The WAREHOUSE's door is already open.$"

FiveIsland_Meadow_Text_Rocket1Intro::
# 22 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "This area's strictly off-limits! Out,\n"
	.string "out!$"

FiveIsland_Meadow_Text_Rocket1Defeat::
# 26 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "Is this for real?$"

FiveIsland_Meadow_Text_Rocket1PostBattle::
# 30 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "You don't have any business here! Go\n"
	.string "home!$"

FiveIsland_Meadow_Text_Rocket2Intro::
# 34 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "There's nothing past here except our\n"
	.string "WAREHOUSE.\p"
	.string "So what brings you here?$"

FiveIsland_Meadow_Text_Rocket2Defeat::
# 38 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "That wasn't supposed to happen$"

FiveIsland_Meadow_Text_Rocket2PostBattle::
# 42 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "You're wanting to know what's inside\n"
	.string "this WAREHOUSE?\p"
	.string "It's better you didn't know. For your\n"
	.string "own sake, I mean.$"

FiveIsland_Meadow_Text_Rocket3Intro::
# 46 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "You'd be wasting time even if you were\n"
	.string "to get by me.$"

FiveIsland_Meadow_Text_Rocket3Defeat::
# 50 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "Oh, that makes me furious!$"

FiveIsland_Meadow_Text_Rocket3PostBattle::
# 54 "data/maps/FiveIsland_Meadow/scripts.pory"
	.string "You won't be able to get in without the\n"
	.string "passwords anyway.$"
