FortreeCity_House3_MapScripts::
	.byte 0


FortreeCity_House3_EventScript_Maniac::
# 5 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_MetStevenHadAmazingPokemon, MSGBOX_NPC
	end


FortreeCity_House3_EventScript_SchoolKidM::
# 10 "data/maps/FortreeCity_House3/scripts.pory"
	msgbox FortreeCity_House3_Text_OhYouHavePokedex, MSGBOX_NPC
	end


FortreeCity_House3_Text_OhYouHavePokedex::
# 14 "data/maps/FortreeCity_House3/scripts.pory"
	.string "What's that thing you have there?\p"
	.string "… … … … … …\p"
	.string "Oh, it's called a POKéDEX?\n"
	.string "It's really awesome!$"

FortreeCity_House3_Text_MetStevenHadAmazingPokemon::
# 18 "data/maps/FortreeCity_House3/scripts.pory"
	.string "While speaking about POKéDEXES,\n"
	.string "I remembered something.\p"
	.string "I met this TRAINER, STEVEN, when\n"
	.string "I was searching for rare stones.\p"
	.string "Hoo, boy, he had some amazing POKéMON\n"
	.string "with him.\p"
	.string "They weren't just rare, they were\n"
	.string "trained to terrifying extremes!\p"
	.string "He might even be stronger than the\n"
	.string "GYM LEADER in this town…$"
