FortreeCity_House3_MapScripts::
	.byte 0


FortreeCity_House3_Text_MetStevenHadAmazingPokemon::
# 5 "data/maps/FortreeCity_House3/scripts.pory"
	.string "While speaking about POKDEXES, I\n"
	.string "remembered something.\p"
	.string "I met this TRAINER, STEVEN, when I was\n"
	.string "searching for rare stones.\p"
	.string "Hoo, boy, he had some amazing POKMON\n"
	.string "with him.\p"
	.string "They weren't just rare, they were\n"
	.string "trained to terrifying extremes!\p"
	.string "He might even be stronger than the GYM\n"
	.string "LEADER in this town$"

FortreeCity_House3_Text_OhYouHavePokedex::
# 9 "data/maps/FortreeCity_House3/scripts.pory"
	.string "What's that thing you have there?\p"
	.string "\p"
	.string "Oh, it's called a POKDEX? It's really\n"
	.string "awesome!$"
