SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0


SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding::
# 5 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Designing a large ship is more like\n"
	.string "making a big building than putting\l"
	.string "together a transportation vehicle.$"

SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy::
# 9 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Don't you think it's strange that a ship\n"
	.string "made of heavy iron floats?\p"
	.string "It floats because of a principle called\n"
	.string "buoyancy.$"
