SlateportCity_SternsShipyard_2F_MapScripts::
	.byte 0


SlateportCity_SternsShipyard_2F_EventScript_Scientist1::
# 5 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding, MSGBOX_NPC
	end


SlateportCity_SternsShipyard_2F_EventScript_Scientist2::
# 10 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	msgbox SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy, MSGBOX_NPC
	end


SlateportCity_SternsShipyard_2F_Text_FloatsBecauseBuoyancy::
# 14 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Don't you think it's strange that\n"
	.string "a ship made of heavy iron floats?\p"
	.string "It floats because of a principle\n"
	.string "called buoyancy.$"

SlateportCity_SternsShipyard_2F_Text_ShipDesignMoreLikeBuilding::
# 18 "data/maps/SlateportCity_SternsShipyard_2F/scripts.pory"
	.string "Designing a large ship is more like\n"
	.string "making a big building than putting\l"
	.string "together a transportation vehicle.$"
