RuinsOfAlph_Outside_MapScripts::
	.byte 0

RuinsOfAlph_Outside_EventScript_ChamberSign::
	msgbox RuinsOfAlph_Outside_Text_ChamberSign, MSGBOX_SIGN
	end

RuinsOfAlph_Outside_EventScript_ResearchCenterSign::
	msgbox RuinsOfAlph_Outside_Text_ResearchCenterSign, MSGBOX_SIGN
	end

RuinsOfAlph_Outside_EventScript_AreaSign::
	msgbox RuinsOfAlph_Outside_Text_AreaSign, MSGBOX_SIGN
	end

RuinsOfAlph_Outside_Text_ChamberSign::
	.string "MYSTERY STONE PANEL CHAMBER$"

RuinsOfAlph_Outside_Text_ResearchCenterSign::
	.string "RUINS OF ALPH RESEARCH CENTER\n"
	.string "The authority on the RUINS OF ALPH$"

RuinsOfAlph_Outside_Text_AreaSign::
	.string "RUINS OF ALPH\n"
	.string "VISITORS WELCOME$"
