FortreeCity_Gym_MapScripts::
	.byte 0


FortreeCity_Gym_EventScript_Ashley::
# 5 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_ASHLEY, FortreeCity_Gym_Text_AshleyIntro, FortreeCity_Gym_Text_AshleyDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_AshleyPostBattle
	return


FortreeCity_Gym_EventScript_Darius::
# 10 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_DARIUS, FortreeCity_Gym_Text_DariusIntro, FortreeCity_Gym_Text_DariusDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_DariusPostBattle
	return


FortreeCity_Gym_EventScript_Edwardo::
# 15 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_EDWARDO, FortreeCity_Gym_Text_EdwardoIntro, FortreeCity_Gym_Text_EdwardoDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_EdwardoPostBattle
	return


FortreeCity_Gym_EventScript_Flint::
# 20 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_FLINT, FortreeCity_Gym_Text_FlintIntro, FortreeCity_Gym_Text_FlintDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_FlintPostBattle
	return


FortreeCity_Gym_EventScript_GymGuide::
	end


FortreeCity_Gym_EventScript_Humberto::
# 29 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_HUMBERTO, FortreeCity_Gym_Text_HumbertoIntro, FortreeCity_Gym_Text_HumbertoDefeat, Text_NotEnoughMonsForDoubleBattle
# 30 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_HumbertoPostBattle
	return


FortreeCity_Gym_EventScript_Jared::
# 34 "data/maps/FortreeCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_JARED, FortreeCity_Gym_Text_JaredIntro, FortreeCity_Gym_Text_JaredDefeat, Text_NotEnoughMonsForDoubleBattle
# 35 "data/maps/FortreeCity_Gym/scripts.pory"
	msgbox FortreeCity_Gym_Text_JaredPostBattle
	return


FortreeCity_Gym_EventScript_LeftGymStatue::
	end


FortreeCity_Gym_EventScript_RightGymStatue::
	end


FortreeCity_Gym_EventScript_Winona::
	end


FortreeCity_Gym_Text_AshleyDefeat::
# 58 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_AshleyDefeat$"

FortreeCity_Gym_Text_AshleyIntro::
# 62 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_AshleyIntro$"

FortreeCity_Gym_Text_AshleyPostBattle::
# 66 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_AshleyPostBattle$"

FortreeCity_Gym_Text_DariusDefeat::
# 70 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_DariusDefeat$"

FortreeCity_Gym_Text_DariusIntro::
# 74 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_DariusIntro$"

FortreeCity_Gym_Text_DariusPostBattle::
# 78 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_DariusPostBattle$"

FortreeCity_Gym_Text_EdwardoDefeat::
# 82 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_EdwardoDefeat$"

FortreeCity_Gym_Text_EdwardoIntro::
# 86 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_EdwardoIntro$"

FortreeCity_Gym_Text_EdwardoPostBattle::
# 90 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_EdwardoPostBattle$"

FortreeCity_Gym_Text_FlintDefeat::
# 94 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_FlintDefeat$"

FortreeCity_Gym_Text_FlintIntro::
# 98 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_FlintIntro$"

FortreeCity_Gym_Text_FlintPostBattle::
# 102 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_FlintPostBattle$"

FortreeCity_Gym_Text_HumbertoDefeat::
# 106 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_HumbertoDefeat$"

FortreeCity_Gym_Text_HumbertoIntro::
# 110 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_HumbertoIntro$"

FortreeCity_Gym_Text_HumbertoPostBattle::
# 114 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_HumbertoPostBattle$"

FortreeCity_Gym_Text_JaredDefeat::
# 118 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_JaredDefeat$"

FortreeCity_Gym_Text_JaredIntro::
# 122 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_JaredIntro$"

FortreeCity_Gym_Text_JaredPostBattle::
# 126 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "FortreeCity_Gym_Text_JaredPostBattle$"

FortreeCity_Gym_Text_GymStatueCertified::
# 130 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "FORTREE CITY POKéMON GYM\p"
	.string "WINONA'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

FortreeCity_Gym_Text_GymGuidePostVictory::
# 134 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You did it!\n"
	.string "You've achieved liftoff!$"

FortreeCity_Gym_Text_WinonaPostRematch::
# 138 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA: Even though I have lost,\n"
	.string "the wings of my heart remain unbroken.\p"
	.string "I can rise and soar again and\n"
	.string "yet again.\p"
	.string "I am convinced of it!$"

FortreeCity_Gym_Text_ExplainAerialAce::
# 142 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "TM40 contains AERIAL ACE.\p"
	.string "Its speed…\n"
	.string "No POKéMON should be able to avoid it.\p"
	.string "… … … … … …$"

FortreeCity_Gym_Text_GymStatue::
# 146 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "FORTREE CITY POKéMON GYM$"
