FortreeCity_Gym_MapScripts::
# 2 "data/maps/FortreeCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_Gym_OnTransition
# 3 "data/maps/FortreeCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FortreeCity_Gym_OnWarp
	.byte 0


FortreeCity_Gym_MapScripts::
# 7 "data/maps/FortreeCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FortreeCity_Gym_OnTransition
# 8 "data/maps/FortreeCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FortreeCity_Gym_OnWarp
	return


FortreeCity_Gym_Text_GymGuideAdvice::
# 12 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Yo, how's it going, CHAMPION- bound\n"
	.string "{PLAYER}?\p"
	.string "FORTREE GYM LEADER WINONA is a master\n"
	.string "of FLYING-type POKéMON.\p"
	.string "She's waiting at the back of this GYM,\n"
	.string "behind the rotating doors.\p"
	.string "She's waiting for new challengers who\n"
	.string "are trying to take wing!\p"
	.string "Okay, go for it!$"

FortreeCity_Gym_Text_GymGuidePostVictory::
# 16 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You did it! You've achieved liftoff!$"

FortreeCity_Gym_Text_JaredIntro::
# 20 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Behold the elegant battle style of BIRD\n"
	.string "POKéMON!$"

FortreeCity_Gym_Text_JaredDefeat::
# 24 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You… You're strong…$"

FortreeCity_Gym_Text_JaredPostBattle::
# 28 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "A TRAINER has to be smart to keep up\n"
	.string "with unexpected turns of events.\p"
	.string "Do you have the smarts to get to our\n"
	.string "LEADER?$"

FortreeCity_Gym_Text_EdwardoIntro::
# 32 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "The lovers of BIRD POKéMON aspire to\n"
	.string "join this GYM.\p"
	.string "As a member of the FORTREE GYM, I'm not\n"
	.string "allowed to lose!$"

FortreeCity_Gym_Text_EdwardoDefeat::
# 36 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "It was too much of a load for me to\n"
	.string "bear…$"

FortreeCity_Gym_Text_EdwardoPostBattle::
# 40 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "The world is huge, and there are\n"
	.string "countless tough TRAINERS.\p"
	.string "I'm going to keep training and make\n"
	.string "myself even stronger.$"

FortreeCity_Gym_Text_FlintIntro::
# 44 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "There's no need for WINONA, our GYM\n"
	.string "LEADER, to deal with you!\p"
	.string "I'm plenty good enough for you!$"

FortreeCity_Gym_Text_FlintDefeat::
# 48 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA, I… I lost!$"

FortreeCity_Gym_Text_FlintPostBattle::
# 52 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA is cute and she's strong. She's\n"
	.string "the ultimate LEADER!\p"
	.string "Blush…$"

FortreeCity_Gym_Text_AshleyIntro::
# 56 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA taught me personally! You can't\n"
	.string "beat me easily!$"

FortreeCity_Gym_Text_AshleyDefeat::
# 60 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "I was beaten…$"

FortreeCity_Gym_Text_AshleyPostBattle::
# 64 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Thanks to WINONA, the people of\n"
	.string "FORTREE can live without fear.$"

FortreeCity_Gym_Text_HumbertoIntro::
# 68 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "When WINONA takes to battle, her face\n"
	.string "shines with beautiful determination…\p"
	.string "I'm not letting you witness that lovely\n"
	.string "sight!$"

FortreeCity_Gym_Text_HumbertoDefeat::
# 72 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Urk! I couldn't stop you.$"

FortreeCity_Gym_Text_HumbertoPostBattle::
# 76 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You'd better watch it! Don't get\n"
	.string "distracted staring at WINONA\l"
	.string "or you'll go crashing down in a heap!$"

FortreeCity_Gym_Text_DariusIntro::
# 80 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You'd better know that there are all\n"
	.string "sorts of FLYING-type POKéMON.\p"
	.string "You do know that, right?$"

FortreeCity_Gym_Text_DariusDefeat::
# 84 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "You seem to know your stuff!$"

FortreeCity_Gym_Text_DariusPostBattle::
# 88 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Sure, you beat me all right. But you'd\n"
	.string "better watch it! Our LEADER\l"
	.string "WINONA's POKéMON are all business.$"

FortreeCity_Gym_Text_WinonaIntro::
# 92 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "I am WINONA. I am the LEADER of the\n"
	.string "FORTREE POKéMON GYM.\p"
	.string "I have become one with BIRD POKéMON\n"
	.string "and have soared the skies…\p"
	.string "However grueling the battle, we have\n"
	.string "triumphed with grace…\p"
	.string "Witness the elegant choreography of\n"
	.string "BIRD POKéMON and I!$"

FortreeCity_Gym_Text_WinonaDefeat::
# 96 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Never before have I seen a TRAINER\n"
	.string "command POKéMON with more grace\l"
	.string "than I…\p"
	.string "In recognition of your prowess, I\n"
	.string "present to you this GYM BADGE.$"

FortreeCity_Gym_Text_ReceivedFeatherBadge::
# 100 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "{PLAYER} received the FEATHER BADGE\n"
	.string "from WINONA.$"

FortreeCity_Gym_Text_ExplainFeatherBadgeTakeThis::
# 104 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "With the FEATHER BADGE, all POKéMON up\n"
	.string "to LV 70, even those received through\l"
	.string "trades, will obey your every command.\p"
	.string "You will also be able to use the HM move\n"
	.string "FLY outside of battle.\p"
	.string "And this… This is a gift from me.$"

FortreeCity_Gym_Text_ExplainAerialAce::
# 108 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "TM40 contains AERIAL ACE.\p"
	.string "Its speed… No POKéMON should be able\n"
	.string "to avoid it.\p"
	.string "… … … … … …$"

FortreeCity_Gym_Text_RegisteredWinona::
# 112 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Registered GYM LEADER WINONA in the\n"
	.string "POKéNAV.$"

FortreeCity_Gym_Text_WinonaPostBattle::
# 116 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "Though I fell to you, I will remain\n"
	.string "devoted to BIRD POKéMON.$"

FortreeCity_Gym_Text_GymStatue::
# 120 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "FORTREE CITY POKéMON GYM$"

FortreeCity_Gym_Text_GymStatueCertified::
# 124 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "FORTREE CITY POKéMON GYM\p"
	.string "WINONA'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

FortreeCity_Gym_Text_WinonaPreRematch::
# 128 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA: We humans can never escape\n"
	.string "gravity's pull on the ground.\p"
	.string "But by striving for excellence, we have\n"
	.string "the power to soar!\p"
	.string "You have scaled the pinnacle as the\n"
	.string "reigning CHAMPION.\p"
	.string "Please, allow me to see your power at\n"
	.string "full flight!$"

FortreeCity_Gym_Text_WinonaRematchDefeat::
# 132 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "I failed to reach your height again…$"

FortreeCity_Gym_Text_WinonaPostRematch::
# 136 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA: Even though I have lost, the\n"
	.string "wings of my heart remain unbroken.\p"
	.string "I can rise and soar again and yet again.\p"
	.string "I am convinced of it!$"

FortreeCity_Gym_Text_WinonaRematchNeedTwoMons::
# 140 "data/maps/FortreeCity_Gym/scripts.pory"
	.string "WINONA: We humans can never escape\n"
	.string "gravity's pull on the ground.\p"
	.string "But by striving for excellence, we have\n"
	.string "the power to soar!\p"
	.string "You have scaled the pinnacle as the\n"
	.string "reigning CHAMPION.\p"
	.string "Please, allow me to see your power at\n"
	.string "full flight!\p"
	.string "Oh, no… Do you have but one POKéMON\n"
	.string "with you?\p"
	.string "Please return with two POKéMON at the\n"
	.string "very least.$"
