SootopolisCity_Gym_B1F_MapScripts::
	.byte 0


SootopolisCity_Gym_B1F_EventScript_Andrea::
# 5 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_ANDREA, SootopolisCity_Gym_B1F_Text_AndreaIntro, SootopolisCity_Gym_B1F_Text_AndreaDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AndreaPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Annika::
# 10 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_ANNIKA, SootopolisCity_Gym_B1F_Text_AnnikaIntro, SootopolisCity_Gym_B1F_Text_AnnikaDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_AnnikaPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Bethany::
# 15 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_BETHANY, SootopolisCity_Gym_B1F_Text_BethanyIntro, SootopolisCity_Gym_B1F_Text_BethanyDefeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BethanyPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Brianna::
# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_BRIANNA, SootopolisCity_Gym_B1F_Text_BriannaIntro, SootopolisCity_Gym_B1F_Text_BriannaDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BriannaPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Bridget::
# 25 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_BRIDGET, SootopolisCity_Gym_B1F_Text_BridgetIntro, SootopolisCity_Gym_B1F_Text_BridgetDefeat, Text_NotEnoughMonsForDoubleBattle
# 26 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_BridgetPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Connie::
# 30 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_CONNIE, SootopolisCity_Gym_B1F_Text_ConnieIntro, SootopolisCity_Gym_B1F_Text_ConnieDefeat, Text_NotEnoughMonsForDoubleBattle
# 31 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_ConniePostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Crissy::
# 35 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_CRISSY, SootopolisCity_Gym_B1F_Text_CrissyIntro, SootopolisCity_Gym_B1F_Text_CrissyDefeat, Text_NotEnoughMonsForDoubleBattle
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_CrissyPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Daphne::
# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_DAPHNE, SootopolisCity_Gym_B1F_Text_DaphneIntro, SootopolisCity_Gym_B1F_Text_DaphneDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_DaphnePostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Olivia::
# 45 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_OLIVIA, SootopolisCity_Gym_B1F_Text_OliviaIntro, SootopolisCity_Gym_B1F_Text_OliviaDefeat, Text_NotEnoughMonsForDoubleBattle
# 46 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_OliviaPostBattle
	return


SootopolisCity_Gym_B1F_EventScript_Tiffany::
# 50 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	trainerbattle_double TRAINER_TIFFANY, SootopolisCity_Gym_B1F_Text_TiffanyIntro, SootopolisCity_Gym_B1F_Text_TiffanyDefeat, Text_NotEnoughMonsForDoubleBattle
# 51 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	msgbox SootopolisCity_Gym_B1F_Text_TiffanyPostBattle
	return


SootopolisCity_Gym_B1F_Text_AndreaDefeat::
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AndreaDefeat$"

SootopolisCity_Gym_B1F_Text_AndreaIntro::
# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AndreaIntro$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle::
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AndreaPostBattle$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat::
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AnnikaDefeat$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro::
# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AnnikaIntro$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle::
# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_AnnikaPostBattle$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat::
# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BethanyDefeat$"

SootopolisCity_Gym_B1F_Text_BethanyIntro::
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BethanyIntro$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle::
# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BethanyPostBattle$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat::
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BriannaDefeat$"

SootopolisCity_Gym_B1F_Text_BriannaIntro::
# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BriannaIntro$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle::
# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BriannaPostBattle$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat::
# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BridgetDefeat$"

SootopolisCity_Gym_B1F_Text_BridgetIntro::
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BridgetIntro$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle::
# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_BridgetPostBattle$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat::
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_ConnieDefeat$"

SootopolisCity_Gym_B1F_Text_ConnieIntro::
# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_ConnieIntro$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle::
# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_ConniePostBattle$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat::
# 128 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_CrissyDefeat$"

SootopolisCity_Gym_B1F_Text_CrissyIntro::
# 132 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_CrissyIntro$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle::
# 136 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_CrissyPostBattle$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat::
# 140 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_DaphneDefeat$"

SootopolisCity_Gym_B1F_Text_DaphneIntro::
# 144 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_DaphneIntro$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle::
# 148 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_DaphnePostBattle$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat::
# 152 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_OliviaDefeat$"

SootopolisCity_Gym_B1F_Text_OliviaIntro::
# 156 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_OliviaIntro$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle::
# 160 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_OliviaPostBattle$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat::
# 164 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_TiffanyDefeat$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro::
# 168 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_TiffanyIntro$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle::
# 172 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Placeholder text for\n"
	.string "SootopolisCity_Gym_B1F_Text_TiffanyPostBattle$"
