SootopolisCity_Gym_B1F_MapScripts::
	.byte 0


SootopolisCity_Gym_B1F_MapScripts::
	return


SootopolisCity_Gym_B1F_Text_AndreaIntro::
# 8 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll show you the sublime techniques I\n"
	.string "learned from our LEADER JUAN!$"

SootopolisCity_Gym_B1F_Text_AndreaDefeat::
# 12 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Please forgive me, JUAN…$"

SootopolisCity_Gym_B1F_Text_AndreaPostBattle::
# 16 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Watch what happens if you crack all the\n"
	.string "floor tiles.$"

SootopolisCity_Gym_B1F_Text_CrissyIntro::
# 20 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You came all the way here, but you won't\n"
	.string "get to see JUAN.\p"
	.string "Not if you lose to me, you won't!$"

SootopolisCity_Gym_B1F_Text_CrissyDefeat::
# 24 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You're strong! I was fooled by your\n"
	.string "cute looks!$"

SootopolisCity_Gym_B1F_Text_CrissyPostBattle::
# 28 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You might be good enough to avoid being\n"
	.string "wiped out in one hit by JUAN.$"

SootopolisCity_Gym_B1F_Text_DaphneIntro::
# 32 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The sight of JUAN conducting a battle…\p"
	.string "The very beauty of it compelled me to\n"
	.string "become a TRAINER.$"

SootopolisCity_Gym_B1F_Text_DaphneDefeat::
# 36 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You battled with more beauty than I\n"
	.string "could muster…$"

SootopolisCity_Gym_B1F_Text_DaphnePostBattle::
# 40 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The grace you bring to battle is\n"
	.string "fabulous.\p"
	.string "Oh… I'm so fortunate to have found\n"
	.string "POKéMON.$"

SootopolisCity_Gym_B1F_Text_ConnieIntro::
# 44 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I should teach you how harsh battles\n"
	.string "can be.$"

SootopolisCity_Gym_B1F_Text_ConnieDefeat::
# 48 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh. You're strong.$"

SootopolisCity_Gym_B1F_Text_ConniePostBattle::
# 52 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I'll tell you something good.\p"
	.string "If you want to reach JUAN, you need to\n"
	.string "walk on each floor tile once.$"

SootopolisCity_Gym_B1F_Text_BridgetIntro::
# 56 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "The POKéMON GYM of the highest level in\n"
	.string "the HOENN region…\p"
	.string "That's the SOOTOPOLIS GYM.$"

SootopolisCity_Gym_B1F_Text_BridgetDefeat::
# 60 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "What a high level you are!$"

SootopolisCity_Gym_B1F_Text_BridgetPostBattle::
# 64 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Rather than being satisfied by being in\n"
	.string "a strong GYM, I imagine training in\l"
	.string "other places will make you stronger.\l"
	.string "But above all, it looks more fun.$"

SootopolisCity_Gym_B1F_Text_OliviaIntro::
# 68 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I train my POKéMON together with JUAN.\p"
	.string "Don't think I'm a pushover.$"

SootopolisCity_Gym_B1F_Text_OliviaDefeat::
# 72 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I was beaten…$"

SootopolisCity_Gym_B1F_Text_OliviaPostBattle::
# 76 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I think you have potential. Why don't\n"
	.string "you stay and train with us?$"

SootopolisCity_Gym_B1F_Text_TiffanyIntro::
# 80 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "A graceful glide across the ice while\n"
	.string "crossing no lines…\p"
	.string "A TRAINER putting on that performance\n"
	.string "would be elegantly beautiful!$"

SootopolisCity_Gym_B1F_Text_TiffanyDefeat::
# 84 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Well, excuse me?!$"

SootopolisCity_Gym_B1F_Text_TiffanyPostBattle::
# 88 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "This is really obvious, but how strong\n"
	.string "you are as a TRAINER has nothing to do\l"
	.string "with how young or old you are.$"

SootopolisCity_Gym_B1F_Text_BethanyIntro::
# 92 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "When I'm with my POKéMON, the time flies\n"
	.string "by before you can say, “Oops!”$"

SootopolisCity_Gym_B1F_Text_BethanyDefeat::
# 96 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oops!$"

SootopolisCity_Gym_B1F_Text_BethanyPostBattle::
# 100 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I wish I could forget about lost causes\n"
	.string "before I can manage an “Oops!”$"

SootopolisCity_Gym_B1F_Text_AnnikaIntro::
# 104 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I can battle with really rare POKéMON if\n"
	.string "you'd like.$"

SootopolisCity_Gym_B1F_Text_AnnikaDefeat::
# 108 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, there now! Did you have a good look\n"
	.string "at my POKéMON?$"

SootopolisCity_Gym_B1F_Text_AnnikaPostBattle::
# 112 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "I came to this GYM because JUAN praised\n"
	.string "me for my darling POKéMON.\p"
	.string "Oh, if only I'd met JUAN years ago when I\n"
	.string "was younger…$"

SootopolisCity_Gym_B1F_Text_BriannaIntro::
# 116 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Giggle… Your grim look is so charming.$"

SootopolisCity_Gym_B1F_Text_BriannaDefeat::
# 120 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "Oh, dear. I went much too easy on you.$"

SootopolisCity_Gym_B1F_Text_BriannaPostBattle::
# 124 "data/maps/SootopolisCity_Gym_B1F/scripts.pory"
	.string "You couldn't lay a finger on JUAN, I'm\n"
	.string "sure. Giggle…$"
