CeladonCity_DepartmentStore_3F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
# 5 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_GBAKid1::
# 10 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_3F_EventScript_GBAKid2::
# 15 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_3F_EventScript_GBAKid3::
# 20 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_3F_EventScript_LittleGirl::
# 25 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_3F_EventScript_Poster::
# 30 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
# 35 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_TV1::
# 40 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_TV2::
# 45 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_TV3::
# 50 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_EventScript_TV4::
# 55 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
# 59 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A puzzle game! Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
# 63 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A sports game! Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
# 67 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A fighting game! Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
# 71 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
# 75 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
# 79 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "An RPG! There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
# 83 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Red and Green! Both are POKéMON!$"

CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
# 87 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Captured POKéMON are registered\n"
	.string "with an ID No. and the OT.\p"
	.string "OT stands for “Original TRAINER” -\n"
	.string "the TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
# 91 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "All right!\p"
	.string "My buddy's going to trade me his\n"
	.string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
# 95 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Come on, HAUNTER!\p"
	.string "I love HAUNTER!\n"
	.string "I collect them!\p"
	.string "Huh?\p"
	.string "HAUNTER turned into a different\n"
	.string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
# 99 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "You can identify POKéMON you get\n"
	.string "in trades by their ID Numbers.$"
