CeladonCity_DepartmentStore_3F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_3F_Text_OTStandsForOriginalTrainer::
# 5 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Captured POKéMON are registered with\n"
	.string "an ID No. and the OT.\p"
	.string "OT stands for “Original TRAINER” - the\n"
	.string "TRAINER that caught it first.$"

CeladonCity_DepartmentStore_3F_Text_BuddyTradingKangaskhanForHaunter::
# 9 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "All right!\p"
	.string "My buddy's going to trade me his\n"
	.string "KANGASKHAN for my HAUNTER!$"

CeladonCity_DepartmentStore_3F_Text_HaunterEvolvedOnTrade::
# 13 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Come on, HAUNTER!\p"
	.string "I love HAUNTER! I collect them!\p"
	.string "Huh?\p"
	.string "HAUNTER turned into a different\n"
	.string "POKéMON while being traded!$"

CeladonCity_DepartmentStore_3F_Text_CanIdentifyTradeMonsByID::
# 17 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "You can identify POKéMON you get in\n"
	.string "trades by their ID Numbers.$"

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
# 21 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
# 25 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "An RPG! There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
# 29 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A sports game! Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
# 33 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A puzzle game! Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
# 37 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "A fighting game! Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
# 41 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
# 45 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Red and Green! Both are POKéMON!$"

Text_CounterTeach::
# 49 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Oh, hi! I finally finished POKéMON.\p"
	.string "Not done yet? How about I teach you a\n"
	.string "good move?\p"
	.string "The move I have in mind is COUNTER.\p"
	.string "Not like the one I'm leaning on, mind\n"
	.string "you!$"

Text_CounterDeclined::
# 53 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "You're not interested? Come see me if\n"
	.string "you change your mind.$"

Text_CounterWhichMon::
# 57 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Which POKéMON should I teach COUNTER\n"
	.string "to?$"

Text_CounterTaught::
# 61 "data/maps/CeladonCity_DepartmentStore_3F/scripts.pory"
	.string "Are you using that COUNTER move I\n"
	.string "taught your POKéMON?$"
