CeladonCity_DepartmentStore_3F_MapScripts::
	.byte 0

CeladonCity_DepartmentStore_3F_EventScript_SuperNES::
	msgbox CeladonCity_DepartmentStore_3F_Text_ItsSuperNES, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV1::
	msgbox CeladonCity_DepartmentStore_3F_Text_AnRPG, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV2::
	msgbox CeladonCity_DepartmentStore_3F_Text_SportsGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV3::
	msgbox CeladonCity_DepartmentStore_3F_Text_PuzzleGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_TV4::
	msgbox CeladonCity_DepartmentStore_3F_Text_FightingGame, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_FloorSign::
	msgbox CeladonCity_DepartmentStore_3F_Text_TVGameShop, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_EventScript_Poster::
	msgbox CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon, MSGBOX_SIGN
	end

CeladonCity_DepartmentStore_3F_Text_ItsSuperNES::
    .string "It's a Super NES.$"

CeladonCity_DepartmentStore_3F_Text_AnRPG::
    .string "An RPG!\n"
    .string "There's no time for that!$"

CeladonCity_DepartmentStore_3F_Text_SportsGame::
    .string "A sports game!\n"
    .string "Dad'll like that!$"

CeladonCity_DepartmentStore_3F_Text_PuzzleGame::
    .string "A puzzle game!\n"
    .string "Looks addictive!$"

CeladonCity_DepartmentStore_3F_Text_FightingGame::
    .string "A fighting game!\n"
    .string "Looks tough!$"

CeladonCity_DepartmentStore_3F_Text_TVGameShop::
    .string "3F: TV GAME SHOP$"

CeladonCity_DepartmentStore_3F_Text_RedGreenBothArePokemon::
    .string "Red and Green!\n"
    .string "Both are POKéMON!$"
