SlateportCity_OceanicMuseum_2F_MapScripts::
	.byte 0


SlateportCity_OceanicMuseum_2F_MapScripts::
	return


SlateportCity_OceanicMuseum_2F_Text_ThankYouForTheParts::
# 8 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Yes? If you're looking for STERN, that\n"
	.string "would be me.\p"
	.string "Ah! Those must be the parts I ordered\n"
	.string "from MR. STONE of DEVON.\p"
	.string "Thank you! That's great! We can prepare\n"
	.string "for our expedition now.$"

SlateportCity_OceanicMuseum_2F_Text_WellTakeThoseParts::
# 12 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Hehehe, hold it! We'll take those parts!$"

SlateportCity_OceanicMuseum_2F_Text_SternWhoAreYou::
# 16 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "CAPT. STERN: Wh-what? Who are you\n"
	.string "people?$"

SlateportCity_OceanicMuseum_2F_Text_WereTeamAqua::
# 20 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "We're TEAM AQUA!\p"
	.string "Our BOSS wants those parts! Shut your\n"
	.string "yap and fork them over!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt1Defeat::
# 24 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Awaaaah! A kid beat me!$"

SlateportCity_OceanicMuseum_2F_Text_BossGoingToBeFurious::
# 28 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Oh, man, what a disaster… The BOSS is\n"
	.string "going to be furious…$"

SlateportCity_OceanicMuseum_2F_Text_LetMeTakeCareOfThis::
# 32 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Humph, sniveling wimp! Let me take care\n"
	.string "of this!$"

SlateportCity_OceanicMuseum_2F_Text_Grunt2Defeat::
# 36 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "What?! I lost, too!$"

SlateportCity_OceanicMuseum_2F_Text_MeddlingKid::
# 40 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Now what? If we don't get the parts,\n"
	.string "we're in for it!\p"
	.string "Arrgh, I didn't count on being meddled\n"
	.string "with by some meddling kid!$"

SlateportCity_OceanicMuseum_2F_Text_CameToSeeWhatsTakingSoLong::
# 44 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "I came to see what was taking so long\n"
	.string "to snatch some parts, and you\l"
	.string "simps are held up by a mere child?$"

SlateportCity_OceanicMuseum_2F_Text_ArchieWarning::
# 48 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "We are TEAM AQUA, and we love the sea!\p"
	.string "And I am TEAM AQUA's leader, ARCHIE!\p"
	.string "What makes you interfere with us?\p"
	.string "…No! You can't be! You're not one of\n"
	.string "TEAM MAGMA?\p"
	.string "Wait, that can't be right. You're not\n"
	.string "dressed for the part.\p"
	.string "… … … … … … … … … … … …\p"
	.string "POKéMON, people… All life depends on\n"
	.string "the sea.\p"
	.string "So, TEAM AQUA is dedicated to the\n"
	.string "expansion of the sea.\p"
	.string "Don't you agree? What we are doing is a\n"
	.string "magnificent undertaking.\p"
	.string "Ah, fine… You're still too young to\n"
	.string "understand\l"
	.string "our noble objective.\p"
	.string "But, I warn you, don't even consider\n"
	.string "interfering with our plans again.\p"
	.string "The consequences will cost you dearly!\p"
	.string "And don't you forget it!$"

SlateportCity_OceanicMuseum_2F_Text_SternThankYouForSavingUs::
# 52 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "CAPT. STERN: You're… Ah, okay, you're\n"
	.string "{PLAYER}{KUN}…\p"
	.string "Anyway, that was a tense situation!\n"
	.string "Thank you for saving us!\p"
	.string "Oh, yes, I almost forgot that you even\n"
	.string "brought the parts from DEVON!$"

SlateportCity_OceanicMuseum_2F_Text_SternIveGotToGo::
# 56 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "CAPT. STERN: Whoops! There's no time to\n"
	.string "lose!\p"
	.string "We have to set out on our ocean-floor\n"
	.string "expedition really soon.\p"
	.string "Thanks again, but now I've got to go!\p"
	.string "Feel free to wander around and check\n"
	.string "out our facilities, though.$"

SlateportCity_OceanicMuseum_2F_Text_RemindsMeOfAbandonedShip::
# 60 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "I saw a model of a ship here.\p"
	.string "It reminded me of the ABANDONED SHIP\n"
	.string "near DEWFORD TOWN…$"

SlateportCity_OceanicMuseum_2F_Text_DontRunInMuseum::
# 64 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Don't you dare run around inside the\n"
	.string "MUSEUM!$"

SlateportCity_OceanicMuseum_2F_Text_WantToRideSubmarine::
# 68 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "Wow, the submarine's awesome! I want to\n"
	.string "go for a ride!$"

SlateportCity_OceanicMuseum_2F_Text_WaterQualitySample1::
# 72 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“WATER QUALITY SAMPLE 1,” the label\n"
	.string "says.\p"
	.string "The sea is all connected, but the water\n"
	.string "seems to differ by region.$"

SlateportCity_OceanicMuseum_2F_Text_WaterQualitySample2::
# 76 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“WATER QUALITY SAMPLE 2,” the label\n"
	.string "says.\p"
	.string "Does the saltiness of seawater differ\n"
	.string "by region, too?$"

SlateportCity_OceanicMuseum_2F_Text_PressureExperiment::
# 80 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "A rubber ball is expanding and\n"
	.string "shrinking.\p"
	.string "“In the sea, the weight of water itself\n"
	.string "exerts pressure.\p"
	.string "“In shallow water, the pressure is not\n"
	.string "very heavy.\p"
	.string "“However, in extremely deep water, the\n"
	.string "pressure can reach even tens of\l"
	.string "thousands of tons on a small area.”$"

SlateportCity_OceanicMuseum_2F_Text_HoennModel::
# 84 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“MODEL OF HOENN REGION”\p"
	.string "It's a miniature diorama of the HOENN\n"
	.string "region.\p"
	.string "Where is LITTLEROOT TOWN on this?$"

SlateportCity_OceanicMuseum_2F_Text_DeepSeawaterDisplay::
# 88 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "It's a display on the flow of seawater.\p"
	.string "“Near the bottom of the sea, water\n"
	.string "flows due to differences in such\l"
	.string "factors as temperature and salinity.”$"

SlateportCity_OceanicMuseum_2F_Text_SurfaceSeawaterDisplay::
# 92 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "It's a display on the flow of seawater.\p"
	.string "“Toward the surface, seawater flows as\n"
	.string "currents driven by the winds.”$"

SlateportCity_OceanicMuseum_2F_Text_SSTidalReplica::
# 96 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“THE FERRY S.S. TIDAL\p"
	.string "“A scale replica of the ship under\n"
	.string "construction at STERN'S SHIPYARD.”$"

SlateportCity_OceanicMuseum_2F_Text_SubmarineReplica::
# 100 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“SUBMARINE EXPLORER 1\p"
	.string "“A replica of the high-performance\n"
	.string "ocean floor exploration submarine.”$"

SlateportCity_OceanicMuseum_2F_Text_SumbersibleReplica::
# 104 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“SUBMERSIBLE POD\p"
	.string "“A replica of a compact, unmanned pod\n"
	.string "for seafloor exploration.”$"

SlateportCity_OceanicMuseum_2F_Text_SSAnneReplica::
# 108 "data/maps/SlateportCity_OceanicMuseum_2F/scripts.pory"
	.string "“S.S. ANNE\p"
	.string "“A replica of the luxury liner that\n"
	.string "circles the globe.”$"
