Route11_EastEntrance_2F_MapScripts::
	.byte 0


Route11_EastEntrance_2F_EventScript_Aide::
	end


Route11_EastEntrance_2F_EventScript_LeftBinoculars::
# 11 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	msgbox Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad, MSGBOX_DEFAULT
	end


Route11_EastEntrance_2F_EventScript_RightBinoculars::
# 17 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	msgbox Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender, MSGBOX_SIGN
	end


Route11_EastEntrance_2F_EventScript_Turner::
	end


Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
# 26 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "To get to LAVENDER TOWN from CERULEAN\n"
	.string "CITY…\p"
	.string "ROCK TUNNEL appears to be a good route\n"
	.string "to take.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
# 30 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show…\p"
	.string "A big POKéMON is asleep on a road!$"
