Route11_EastEntrance_2F_MapScripts::
	.byte 0


Route11_EastEntrance_2F_Text_GiveItemfinderIfCaught30::
# 5 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Hi! Remember me? I'm one of PROF. OAK's\n"
	.string "AIDES.\p"
	.string "If your POKDEX has complete data on\n"
	.string "{STR_VAR_1} species, I'm supposed\l"
	.string "to\l"
	.string "give you a reward.\p"
	.string "PROF. OAK entrusted me with the\n"
	.string "{STR_VAR_2} for you.\p"
	.string "So, {PLAYER}, let me ask you.\p"
	.string "Have you gathered data on at least\n"
	.string "{STR_VAR_1} kinds of POKMON?$"

Route11_EastEntrance_2F_Text_GreatHereYouGo::
# 9 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Great! You have caught or owned\n"
	.string "{STR_VAR_3} kinds of POKMON!\p"
	.string "Congratulations! Here you go!$"

Route11_EastEntrance_2F_Text_ReceivedItemfinderFromAide::
# 13 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "{PLAYER} received the {STR_VAR_2}\n"
	.string "from the AIDE.$"

Route11_EastEntrance_2F_Text_ExplainItemfinder::
# 17 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "There are items on the ground that may\n"
	.string "be hidden from view.\p"
	.string "Use the ITEMFINDER to detect any\n"
	.string "hidden items close to you.\p"
	.string "The machine is a bit limited. It can't\n"
	.string "pinpoint item locations.\p"
	.string "What it does is show the direction\n"
	.string "where the item is.\p"
	.string "Use it to get your bearings, then\n"
	.string "search the suspect area by hand.$"

Route11_EastEntrance_2F_Text_BigMonAsleepOnRoad::
# 21 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "A big POKMON is asleep on a road!$"

Route11_EastEntrance_2F_Text_WhatABreathtakingView::
# 25 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "What a breathtaking view!$"

Route11_EastEntrance_2F_Text_RockTunnelGoodRouteToLavender::
# 29 "data/maps/Route11_EastEntrance_2F/scripts.pory"
	.string "Let's see what the binoculars have to\n"
	.string "show\p"
	.string "To get to LAVENDER TOWN from CERULEAN\n"
	.string "CITY\p"
	.string "ROCK TUNNEL appears to be a good route\n"
	.string "to take.$"
