PewterCity_House1_MapScripts::
	.byte 0


PewterCity_House1_EventScript_BaldingMan::
# 5 "data/maps/PewterCity_House1/scripts.pory"
	msgbox PewterCity_House1_Text_TradeMonsAreFinicky, MSGBOX_NPC
	end


PewterCity_House1_EventScript_LittleBoy::
	end


PewterCity_House1_EventScript_Nidoran::
	end


PewterCity_House1_Text_TradeMonsAreFinicky::
# 18 "data/maps/PewterCity_House1/scripts.pory"
	.string "Our POKéMON's an outsider, so it's\n"
	.string "finicky and hard to handle.\p"
	.string "An outsider is a POKéMON that you\n"
	.string "get in a trade.\p"
	.string "It grows fast, but it may ignore an\n"
	.string "unskilled TRAINER in battle.\p"
	.string "If only we had some BADGES…$"
