PewterCity_House1_MapScripts::
	.byte 0


PewterCity_House1_Text_Nidoran::
# 5 "data/maps/PewterCity_House1/scripts.pory"
	.string "NIDORAN♂: Bowbow!$"

PewterCity_House1_Text_NidoranSit::
# 9 "data/maps/PewterCity_House1/scripts.pory"
	.string "NIDORAN, sit!$"

PewterCity_House1_Text_TradeMonsAreFinicky::
# 13 "data/maps/PewterCity_House1/scripts.pory"
	.string "Our POKéMON's an outsider, so it's\n"
	.string "finicky and hard to handle.\p"
	.string "An outsider is a POKéMON that you get\n"
	.string "in a trade.\p"
	.string "It grows fast, but it may ignore an\n"
	.string "unskilled TRAINER in battle.\p"
	.string "If only we had some BADGES…$"
