PewterCity_Gym_MapScripts::
	.byte 0


PewterCity_Gym_Text_BrockIntro::
# 5 "data/maps/PewterCity_Gym/scripts.pory"
	.string "So, you're here. I'm BROCK. I'm PEWTER's\n"
	.string "GYM LEADER.\p"
	.string "My rock-hard willpower is evident even\n"
	.string "in my POKéMON.\p"
	.string "My POKéMON are all rock hard, and have\n"
	.string "true-grit determination.\p"
	.string "That's right - my POKéMON are all the\n"
	.string "ROCK type!\p"
	.string "Fuhaha! You're going to challenge me\n"
	.string "knowing that you'll lose?\p"
	.string "That's the TRAINER's honor that\n"
	.string "compels you to challenge me.\p"
	.string "Fine, then! Show me your best!{PLAY_BGM}{MUS_RG_GYM}$"

PewterCity_Gym_Text_BrockDefeat::
# 9 "data/maps/PewterCity_Gym/scripts.pory"
	.string "I took you for granted, and so I lost.\p"
	.string "As proof of your victory, I confer on\n"
	.string "you this…the official POKéMON\l"
	.string "LEAGUE BOULDERBADGE.\p"
	.string "{FONT_NORMAL}{PLAYER} received the BOULDERBADGE\n"
	.string "from BROCK!{PAUSE_MUSIC}{PLAY_BGM}{MUS_OBTAIN_BADGE}{PAUSE 0xFE}{PAUSE 0x56}{RESUME_MUSIC}\p"
	.string "{FONT_MALE}Just having the BOULDERBADGE makes\n"
	.string "your POKéMON more powerful.\p"
	.string "It also enables the use of the move\n"
	.string "FLASH outside of battle.\p"
	.string "Of course, a POKéMON must know the\n"
	.string "move FLASH to use it.$"

PewterCity_Gym_Text_TakeThisWithYou::
# 13 "data/maps/PewterCity_Gym/scripts.pory"
	.string "Wait! Take this with you.$"

PewterCity_Gym_Text_ReceivedTM39FromBrock::
# 17 "data/maps/PewterCity_Gym/scripts.pory"
	.string "{PLAYER} received TM39 from BROCK.$"

PewterCity_Gym_Text_ExplainTM39::
# 21 "data/maps/PewterCity_Gym/scripts.pory"
	.string "A TM, Technical Machine, contains a\n"
	.string "technique for POKéMON.\p"
	.string "Using a TM teaches the move it contains\n"
	.string "to a POKéMON.\p"
	.string "A TM is good for only one use.\p"
	.string "So, when you use one, pick the POKéMON\n"
	.string "carefully.\p"
	.string "Anyways… TM39 contains ROCK TOMB.\p"
	.string "It hurls boulders at the foe and lowers\n"
	.string "its SPEED.$"

PewterCity_Gym_Text_BrockPostBattle::
# 25 "data/maps/PewterCity_Gym/scripts.pory"
	.string "There are all kinds of TRAINERS in this\n"
	.string "huge world of ours.\p"
	.string "You appear to be very gifted as a\n"
	.string "POKéMON TRAINER.\p"
	.string "So let me make a suggestion.\p"
	.string "Go to the GYM in CERULEAN and test your\n"
	.string "abilities.$"

PewterCity_Gym_Text_DontHaveRoomForThis::
# 29 "data/maps/PewterCity_Gym/scripts.pory"
	.string "You don't have room for this.$"

PewterCity_Gym_Text_LiamIntro::
# 33 "data/maps/PewterCity_Gym/scripts.pory"
	.string "Stop right there, kid!\p"
	.string "You're ten thousand light-years from\n"
	.string "facing BROCK!$"

PewterCity_Gym_Text_LiamDefeat::
# 37 "data/maps/PewterCity_Gym/scripts.pory"
	.string "Darn!\p"
	.string "Light-years isn't time… It measures\n"
	.string "distance!$"

PewterCity_Gym_Text_LiamPostBattle::
# 41 "data/maps/PewterCity_Gym/scripts.pory"
	.string "You're pretty hot. …But not as hot as\n"
	.string "BROCK!$"

PewterCity_Gym_Text_LetMeTakeYouToTheTop::
# 45 "data/maps/PewterCity_Gym/scripts.pory"
	.string "Hiya! Do you want to dream big?\p"
	.string "Do you dare to dream of becoming the\n"
	.string "POKéMON champ?\p"
	.string "I'm no TRAINER, but I can advise you on\n"
	.string "how to win.\p"
	.string "Let me take you to the top!$"

PewterCity_Gym_Text_LetsGetHappening::
# 49 "data/maps/PewterCity_Gym/scripts.pory"
	.string "All right! Let's get happening!$"

PewterCity_Gym_Text_TryDifferentPartyOrders::
# 53 "data/maps/PewterCity_Gym/scripts.pory"
	.string "The first POKéMON out in a match is at\n"
	.string "the left of the POKéMON LIST.\p"
	.string "By changing the order of POKéMON, you\n"
	.string "may gain an advantage.\p"
	.string "Try different orders to suit your\n"
	.string "opponent's party.$"

PewterCity_Gym_Text_ItsFreeLetsGetHappening::
# 57 "data/maps/PewterCity_Gym/scripts.pory"
	.string "It's a free service! Let's get\n"
	.string "happening!$"

PewterCity_Gym_Text_YoureChampMaterial::
# 61 "data/maps/PewterCity_Gym/scripts.pory"
	.string "Just as I thought! You're POKéMON\n"
	.string "champ material!$"

PewterCity_Gym_Text_GymStatue::
# 65 "data/maps/PewterCity_Gym/scripts.pory"
	.string "PEWTER POKéMON GYM LEADER: BROCK\p"
	.string "WINNING TRAINERS: {RIVAL}$"

PewterCity_Gym_Text_GymStatuePlayerWon::
# 69 "data/maps/PewterCity_Gym/scripts.pory"
	.string "PEWTER POKéMON GYM LEADER: BROCK\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"
