MauvilleCity_House1_MapScripts::
	.byte 0


MauvilleCity_House1_MapScripts::
	return


MauvilleCity_House1_Text_ImRockSmashDudeTakeThis::
# 8 "data/maps/MauvilleCity_House1/scripts.pory"
	.string "Woohoo!\p"
	.string "I hear people call me the ROCK SMASH\n"
	.string "GUY, but I find that sort of degrading.\p"
	.string "I think I deserve a bit more respect,\n"
	.string "like maybe the ROCK SMASH DUDE.\p"
	.string "Woohoo!\p"
	.string "Anyways, your POKéMON look pretty\n"
	.string "strong.\p"
	.string "I like that! Here, take this HIDDEN\n"
	.string "MACHINE!$"

MauvilleCity_House1_Text_ExplainRockSmash::
# 12 "data/maps/MauvilleCity_House1/scripts.pory"
	.string "That HM contains ROCK SMASH.\p"
	.string "If you come across large boulders that\n"
	.string "block your path…\p"
	.string "Well, use that HM move and smash them\n"
	.string "right out of your way!\p"
	.string "Yes, sir! Smash rocks aside, I say!\n"
	.string "Woohoo!$"

MauvilleCity_House1_Text_MonCanFlyOutOfSmashedRock::
# 16 "data/maps/MauvilleCity_House1/scripts.pory"
	.string "Oh, yes, if you smash a rock, a POKéMON\n"
	.string "could come flying out of hiding.\p"
	.string "Woohoo!$"
