DiglettsCave_SouthEntrance_MapScripts::
	.byte 0


DiglettsCave_SouthEntrance_EventScript_OldMan::
# 5 "data/maps/DiglettsCave_SouthEntrance/scripts.pory"
	msgbox DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel, MSGBOX_NPC
	end


DiglettsCave_SouthEntrance_Text_DiglettDugThisTunnel::
# 10 "data/maps/DiglettsCave_SouthEntrance/scripts.pory"
	.string "Well, isn't this a surprise!\n"
	.string "DIGLETT dug this long tunnel!\p"
	.string "It goes right to VIRIDIAN CITY,\n"
	.string "they tell me.$"
