Route13_MapScripts::
	.byte 0


Route13_Text_SebastianIntro::
# 5 "data/maps/Route13/scripts.pory"
	.string "My bird POKéMON want to battle with\n"
	.string "you!$"

Route13_Text_SebastianDefeat::
# 9 "data/maps/Route13/scripts.pory"
	.string "My PIDGEY and PIDGEOTTO combo lost?$"

Route13_Text_SebastianPostBattle::
# 13 "data/maps/Route13/scripts.pory"
	.string "My POKéMON look happy even though they\n"
	.string "lost.$"

Route13_Text_SusieIntro::
# 17 "data/maps/Route13/scripts.pory"
	.string "I'm told I'm good for a kid.$"

Route13_Text_SusieDefeat::
# 21 "data/maps/Route13/scripts.pory"
	.string "Ohh! I lost!$"

Route13_Text_SusiePostBattle::
# 25 "data/maps/Route13/scripts.pory"
	.string "I want to become a good TRAINER. I'll\n"
	.string "train hard, just watch.$"

Route13_Text_ValerieIntro::
# 29 "data/maps/Route13/scripts.pory"
	.string "Wow! Your BADGES are too cool!$"

Route13_Text_ValerieDefeat::
# 33 "data/maps/Route13/scripts.pory"
	.string "Not enough!$"

Route13_Text_ValeriePostBattle::
# 37 "data/maps/Route13/scripts.pory"
	.string "You got those BADGES from GYM LEADERS.\n"
	.string "I know!$"

Route13_Text_GwenIntro::
# 41 "data/maps/Route13/scripts.pory"
	.string "My cute POKéMON wish to make your\n"
	.string "acquaintance.$"

Route13_Text_GwenDefeat::
# 45 "data/maps/Route13/scripts.pory"
	.string "Good going! You totally won!$"

Route13_Text_GwenPostBattle::
# 49 "data/maps/Route13/scripts.pory"
	.string "You have to make POKéMON battle to\n"
	.string "toughen them up.$"

Route13_Text_AlmaIntro::
# 53 "data/maps/Route13/scripts.pory"
	.string "I found CARBOS in a cave once while I\n"
	.string "was spelunking.$"

Route13_Text_AlmaDefeat::
# 57 "data/maps/Route13/scripts.pory"
	.string "Oh, too bad! I just messed up!$"

Route13_Text_AlmaPostBattle::
# 61 "data/maps/Route13/scripts.pory"
	.string "CARBOS boosted the SPEED of my\n"
	.string "POKéMON.$"

Route13_Text_PerryIntro::
# 65 "data/maps/Route13/scripts.pory"
	.string "I'm not going to lose. Not when the\n"
	.string "wind's blowing my way!$"

Route13_Text_PerryDefeat::
# 69 "data/maps/Route13/scripts.pory"
	.string "The wind turned!$"

Route13_Text_PerryPostBattle::
# 73 "data/maps/Route13/scripts.pory"
	.string "I'm beat. I guess I'll FLY home.$"

Route13_Text_LolaIntro::
# 77 "data/maps/Route13/scripts.pory"
	.string "Sure, I'll play with you, sweetie.$"

Route13_Text_LolaDefeat::
# 81 "data/maps/Route13/scripts.pory"
	.string "Oh! You little beast!$"

Route13_Text_LolaPostBattle::
# 85 "data/maps/Route13/scripts.pory"
	.string "I wonder which is stronger, male or\n"
	.string "female POKéMON?$"

Route13_Text_SheilaIntro::
# 89 "data/maps/Route13/scripts.pory"
	.string "Do you want to battle some POKéMON\n"
	.string "with me?$"

Route13_Text_SheilaDefeat::
# 93 "data/maps/Route13/scripts.pory"
	.string "It's over already?$"

Route13_Text_SheilaPostBattle::
# 97 "data/maps/Route13/scripts.pory"
	.string "I don't know anything about POKéMON\n"
	.string "actually.\p"
	.string "The ones I use… I picked them for their\n"
	.string "looks!$"

Route13_Text_JaredIntro::
# 101 "data/maps/Route13/scripts.pory"
	.string "What're you lookin' at?$"

Route13_Text_JaredDefeat::
# 105 "data/maps/Route13/scripts.pory"
	.string "Dang! Stripped gears!$"

Route13_Text_JaredPostBattle::
# 109 "data/maps/Route13/scripts.pory"
	.string "Get lost!$"

Route13_Text_RobertIntro::
# 113 "data/maps/Route13/scripts.pory"
	.string "I always go with bird POKéMON. I've\n"
	.string "dedicated myself to them.$"

Route13_Text_RobertDefeat::
# 117 "data/maps/Route13/scripts.pory"
	.string "Out of power!$"

Route13_Text_RobertPostBattle::
# 121 "data/maps/Route13/scripts.pory"
	.string "I wish I could fly like PIDGEY and\n"
	.string "PIDGEOTTO…$"

Route13_Text_LookToLeftOfThatPost::
# 125 "data/maps/Route13/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Look, look! Look to the left of that\n"
	.string "post!$"

Route13_Text_SelectToSwitchItems::
# 129 "data/maps/Route13/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Use SELECT to switch items in the ITEMS\n"
	.string "window.$"

Route13_Text_RouteSign::
# 133 "data/maps/Route13/scripts.pory"
	.string "ROUTE 13 North to SILENCE BRIDGE$"
