OlivineCity_MapScripts::
	.byte 0


OlivineCity_EventScript_Gym1::
# 6 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_Gym1, MSGBOX_SIGN
	end


OlivineCity_EventScript_Sign2::
# 15 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_Sign2, MSGBOX_SIGN
	end


OlivineCity_EventScript_Sign3::
# 24 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_Sign3, MSGBOX_SIGN
	end


OlivineCity_EventScript_Sign4::
# 33 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_Sign4, MSGBOX_SIGN
	end


OlivineCity_EventScript_Sign5::
# 42 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_Sign5, MSGBOX_SIGN
	end


OlivineCity_EventScript_SmithNPC1::
# 51 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC1, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC2::
# 60 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC2, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC3::
# 69 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC3, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC4::
# 78 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC4, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC5::
# 87 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC5, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC6::
# 96 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC6, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC7::
# 105 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC7, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC8::
# 114 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC8, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC9::
# 123 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC9, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC10::
# 132 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC10, MSGBOX_NPC
	end


OlivineCity_EventScript_SmithNPC11::
# 141 "data/maps/OlivineCity/scripts.pory"
	msgbox OlivineCity_Text_SmithNPC11, MSGBOX_NPC
	end


OlivineCity_Text_Gym1::
# 10 "data/maps/OlivineCity/scripts.pory"
	.string "Olivine Gym$"

OlivineCity_Text_Sign2::
# 19 "data/maps/OlivineCity/scripts.pory"
	.string "OlivineCity Sign 2$"

OlivineCity_Text_Sign3::
# 28 "data/maps/OlivineCity/scripts.pory"
	.string "OlivineCity Sign 3$"

OlivineCity_Text_Sign4::
# 37 "data/maps/OlivineCity/scripts.pory"
	.string "OlivineCity Sign 4$"

OlivineCity_Text_Sign5::
# 46 "data/maps/OlivineCity/scripts.pory"
	.string "OlivineCity Sign 5$"

OlivineCity_Text_SmithNPC1::
# 55 "data/maps/OlivineCity/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

OlivineCity_Text_SmithNPC2::
# 64 "data/maps/OlivineCity/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

OlivineCity_Text_SmithNPC3::
# 73 "data/maps/OlivineCity/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

OlivineCity_Text_SmithNPC4::
# 82 "data/maps/OlivineCity/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

OlivineCity_Text_SmithNPC5::
# 91 "data/maps/OlivineCity/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

OlivineCity_Text_SmithNPC6::
# 100 "data/maps/OlivineCity/scripts.pory"
	.string "It's the question that drives us, Neo.$"

OlivineCity_Text_SmithNPC7::
# 109 "data/maps/OlivineCity/scripts.pory"
	.string "Unfortunately, no one can be told what\n"
	.string "the Matrix is.$"

OlivineCity_Text_SmithNPC8::
# 118 "data/maps/OlivineCity/scripts.pory"
	.string "I know kung fu.$"

OlivineCity_Text_SmithNPC9::
# 127 "data/maps/OlivineCity/scripts.pory"
	.string "Dodge this.$"

OlivineCity_Text_SmithNPC10::
# 136 "data/maps/OlivineCity/scripts.pory"
	.string "Choice is an illusion created between\n"
	.string "those with power and those without.$"

OlivineCity_Text_SmithNPC11::
# 145 "data/maps/OlivineCity/scripts.pory"
	.string "Hope is an illusion, Mr. Anderson.$"
