PacifidlogTown_House2_MapScripts::
	.byte 0


PacifidlogTown_House2_Text_ChairmansYoungerBrotherOnVacation::
# 5 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Er-hem!\p"
	.string "I am the POKMON FAN CLUB's most\n"
	.string "important person, the CHAIRMAN's\l"
	.string "younger brother.\p"
	.string "I'm here enjoying my vacation with\n"
	.string "POKMON, yes, indeed.$"

PacifidlogTown_House2_Text_AhYourPokemon::
# 9 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Ah! Your POKMON$"

PacifidlogTown_House2_Text_AdoringPokemonTakeThis::
# 13 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It clearly likes you very much.\p"
	.string "A POKMON that adoring and adorable\n"
	.string "deserves a TM like this, no?$"

PacifidlogTown_House2_Text_PutInSomeMoreEffort::
# 17 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Hmm It's not bad, but it's also not good.\p"
	.string "You, as the TRAINER, need to put in some\n"
	.string "more effort.$"

PacifidlogTown_House2_Text_ViciousPokemonTakeThis::
# 21 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It has a vicious look to it.\p"
	.string "A frightening POKMON like that\n"
	.string "deserves a TM like this.$"

PacifidlogTown_House2_Text_ExplainReturnFrustration::
# 25 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "If a POKMON likes you a lot, RETURN's\n"
	.string "power is enhanced.\p"
	.string "If it doesn't like you, FRUSTRATION's\n"
	.string "power goes up.$"

PacifidlogTown_House2_Text_GetGoodTMInXDays::
# 29 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Oh, yes. In about {STR_VAR_1} or so\n"
	.string "days, I should be getting a good TM or\l"
	.string "two.\p"
	.string "You should come see me then. I'll give\n"
	.string "you a TM that's suitable for\l"
	.string "your POKMON.$"

PacifidlogTown_House2_Text_Rurii::
# 33 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rurii.$"

PacifidlogTown_House2_Text_VeryFriendlyWithTrainer::
# 37 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It appears to be very friendly with the\n"
	.string "TRAINER.$"

PacifidlogTown_House2_Text_Rururi::
# 41 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rururi!$"

PacifidlogTown_House2_Text_DoesntLikeTrainerVeryMuch::
# 45 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It doesn't appear to like the TRAINER\n"
	.string "very much.$"
