PacifidlogTown_House2_MapScripts::
	.byte 0


PacifidlogTown_House2_MapScripts::
	return


PacifidlogTown_House2_Text_ChairmansYoungerBrotherOnVacation::
# 8 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Er-hem!\p"
	.string "I am the POKéMON FAN CLUB's most\n"
	.string "important person, the CHAIRMAN's\l"
	.string "younger brother.\p"
	.string "I'm here enjoying my vacation with\n"
	.string "POKéMON, yes, indeed.$"

PacifidlogTown_House2_Text_AhYourPokemon::
# 12 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Ah! Your POKéMON…$"

PacifidlogTown_House2_Text_AdoringPokemonTakeThis::
# 16 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It clearly likes you very much.\p"
	.string "A POKéMON that adoring and adorable\n"
	.string "deserves a TM like this, no?$"

PacifidlogTown_House2_Text_PutInSomeMoreEffort::
# 20 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Hmm… It's not bad, but it's also not\n"
	.string "good.\p"
	.string "You, as the TRAINER, need to put in some\n"
	.string "more effort.$"

PacifidlogTown_House2_Text_ViciousPokemonTakeThis::
# 24 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It has a vicious look to it.\p"
	.string "A frightening POKéMON like that\n"
	.string "deserves a TM like this.$"

PacifidlogTown_House2_Text_ExplainReturnFrustration::
# 28 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "If a POKéMON likes you a lot, RETURN's\n"
	.string "power is enhanced.\p"
	.string "If it doesn't like you, FRUSTRATION's\n"
	.string "power goes up.$"

PacifidlogTown_House2_Text_GetGoodTMInXDays::
# 32 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Oh, yes. In about {STR_VAR_1} or so\n"
	.string "days, I should be getting a good TM or\l"
	.string "two.\p"
	.string "You should come see me then. I'll give\n"
	.string "you a TM that's suitable for\l"
	.string "your POKéMON.$"

PacifidlogTown_House2_Text_Rurii::
# 36 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rurii.$"

PacifidlogTown_House2_Text_VeryFriendlyWithTrainer::
# 40 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It appears to be very friendly with the\n"
	.string "TRAINER.$"

PacifidlogTown_House2_Text_Rururi::
# 44 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rururi!$"

PacifidlogTown_House2_Text_DoesntLikeTrainerVeryMuch::
# 48 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It doesn't appear to like the TRAINER\n"
	.string "very much.$"
