PacifidlogTown_House2_MapScripts::
	.byte 0


PacifidlogTown_House2_EventScript_FanClubYoungerBrother::
	end


PacifidlogTown_House2_EventScript_HappyAzurill::
# 9 "data/maps/PacifidlogTown_House2/scripts.pory"
	msgbox PacifidlogTown_House2_Text_Rurii, MSGBOX_DEFAULT
	end


PacifidlogTown_House2_EventScript_UnhappyAzurill::
# 14 "data/maps/PacifidlogTown_House2/scripts.pory"
	msgbox PacifidlogTown_House2_Text_Rururi, MSGBOX_DEFAULT
	end


PacifidlogTown_House2_Text_ChairmansYoungerBrotherOnVacation::
# 18 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Er-hem!\p"
	.string "I am the POKéMON FAN CLUB's most\n"
	.string "important person, the CHAIRMAN's\l"
	.string "younger brother.\p"
	.string "I'm here enjoying my vacation with\n"
	.string "POKéMON, yes, indeed.$"

PacifidlogTown_House2_Text_ViciousPokemonTakeThis::
# 22 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It has a vicious look to it.\p"
	.string "A frightening POKéMON like that\n"
	.string "deserves a TM like this.$"

PacifidlogTown_House2_Text_GetGoodTMInXDays::
# 26 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Oh, yes. In about {STR_VAR_1} or so\n"
	.string "days,\n"
	.string "I should be getting a good TM or two.\p"
	.string "You should come see me then.\n"
	.string "I'll give you a TM that's suitable for\l"
	.string "your POKéMON.$"

PacifidlogTown_House2_Text_AhYourPokemon::
# 30 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Ah!\n"
	.string "Your POKéMON…$"

PacifidlogTown_House2_Text_Rururi::
# 34 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rururi!$"

PacifidlogTown_House2_Text_Rurii::
# 38 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "AZURILL: Rurii.$"

PacifidlogTown_House2_Text_AdoringPokemonTakeThis::
# 42 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "It clearly likes you very much.\p"
	.string "A POKéMON that adoring and adorable\n"
	.string "deserves a TM like this, no?$"

PacifidlogTown_House2_Text_PutInSomeMoreEffort::
# 46 "data/maps/PacifidlogTown_House2/scripts.pory"
	.string "Hmm…\n"
	.string "It's not bad, but it's also not good.\p"
	.string "You, as the TRAINER, need to put in\n"
	.string "some more effort.$"
