VermilionCity_PokemonCenter_1F_MapScripts::
# 2 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, VermilionCity_PokemonCenter_1F_OnTransition
# 3 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


VermilionCity_PokemonCenter_1F_Text_TrainerMonsStrongerThanWild::
# 7 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "Even if they are the same level,\n"
	.string "POKéMON can have very different\l"
	.string "stats and abilities.\p"
	.string "A POKéMON raised by a TRAINER is\n"
	.string "stronger than one in the wild.$"

VermilionCity_PokemonCenter_1F_Text_PoisonedMonFaintedWhileWalking::
# 11 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "My POKéMON was poisoned! It fainted\n"
	.string "while we were walking!$"

VermilionCity_PokemonCenter_1F_Text_AllMonWeakToSpecificTypes::
# 15 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "It is true that a higher-level POKéMON\n"
	.string "will be more powerful…\p"
	.string "But, all POKéMON will have weak points\n"
	.string "against specific types.\p"
	.string "So, there appears to be no universally\n"
	.string "strong POKéMON.$"

VermilionCity_PokemonCenter_1F_Text_UrgeToBattleSomeoneAgain::
# 19 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "The urge to battle with someone you've\n"
	.string "tangled with before…\p"
	.string "Have you ever had that urge? I'm sure\n"
	.string "you have.\p"
	.string "I wanted to battle certain people again\n"
	.string "over and over, too.\p"
	.string "So, I've been giving these away. Please,\n"
	.string "take one!$"

VermilionCity_PokemonCenter_1F_Text_UseDeviceForRematches::
# 23 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "Use that device and you'll find\n"
	.string "TRAINERS looking for a rematch.\p"
	.string "You have to charge its battery to use\n"
	.string "it, though.$"

VermilionCity_PokemonCenter_1F_Text_ExplainVSSeeker::
# 27 "data/maps/VermilionCity_PokemonCenter_1F/scripts.pory"
	.string "How do you use the VS SEEKER? There's\n"
	.string "nothing to it.\p"
	.string "Use it like beep-beep-beep, and\n"
	.string "TRAINERS around you will notice.\p"
	.string "If any TRAINER wants a rematch, it will\n"
	.string "let you know immediately.\p"
	.string "Charge its battery and use it while\n"
	.string "you're on a road.$"
