MossdeepCity_Gym_MapScripts::
# 2 "data/maps/MossdeepCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MossdeepCity_Gym_OnTransition
# 3 "data/maps/MossdeepCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MossdeepCity_Gym_OnLoad
	.byte 0


MossdeepCity_Gym_MapScripts::
# 7 "data/maps/MossdeepCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, MossdeepCity_Gym_OnTransition
# 8 "data/maps/MossdeepCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, MossdeepCity_Gym_OnLoad
	return


MossdeepCity_Gym_Text_GymGuideAdvice::
# 13 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Yo, how's it going, CHAMPION-bound\n"
	.string "{PLAYER}?\p"
	.string "The GYM LEADERS here use PSYCHIC-type\n"
	.string "POKéMON.\p"
	.string "If you go up against them with\n"
	.string "FIGHTING- or POISON-type POKéMON,\l"
	.string "they'll inflict horrible damage!\p"
	.string "Plus, they'll come at you with\n"
	.string "outstanding combination attacks.\p"
	.string "If you want to win, you'll need to show\n"
	.string "them how tight you are with your\l"
	.string "POKéMON. Go for it!$"

MossdeepCity_Gym_Text_GymGuidePostVictory::
# 17 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Wow, you're astounding! You're one\n"
	.string "great TRAINER!$"

MossdeepCity_Gym_Text_PrestonIntro::
# 21 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Battles hinge on the strength of your\n"
	.string "spirit! The weak-spirited will never win!$"

MossdeepCity_Gym_Text_PrestonDefeat::
# 25 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I lost! I must temper my spirit again!$"

MossdeepCity_Gym_Text_PrestonPostBattle::
# 29 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "The indecisive lose. That's my warning\n"
	.string "to you.$"

MossdeepCity_Gym_Text_VirgilIntro::
# 33 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Let me see your talent!$"

MossdeepCity_Gym_Text_VirgilDefeat::
# 37 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "You possess spectacular talent!$"

MossdeepCity_Gym_Text_VirgilPostBattle::
# 41 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "If there are prodigies in the world,\n"
	.string "then our GYM LEADERS are them!\p"
	.string "However, you may be even more talented\n"
	.string "than them…$"

MossdeepCity_Gym_Text_BlakeIntro::
# 45 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Fufufufu… Watch me levitate a POKé\n"
	.string "BALL telekinetically!\p"
	.string "Wrooooooooaaaar! … … … … … … …\p"
	.string "Sometimes, I'm out of sync…$"

MossdeepCity_Gym_Text_BlakeDefeat::
# 49 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "My POKéMON battling skills are out of\n"
	.string "sync, too!$"

MossdeepCity_Gym_Text_BlakePostBattle::
# 53 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "A POKé BALL was too heavy to lift\n"
	.string "psychically. But this dust bunny…\p"
	.string "Whoooooooooooooooh! … … … … … …\p"
	.string "No, I'm not cheating! I didn't blow on it!\n"
	.string "Honestly!$"

MossdeepCity_Gym_Text_HannahIntro::
# 57 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "When you lose to me, don't be too hard\n"
	.string "on yourself.\p"
	.string "It's not that you're weak--I'm just too\n"
	.string "strong!$"

MossdeepCity_Gym_Text_HannahDefeat::
# 61 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "You're just too strong!$"

MossdeepCity_Gym_Text_HannahPostBattle::
# 65 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I'm not going to get down on myself for\n"
	.string "losing. I just need to train harder.\p"
	.string "Positive thinking--that's my strong\n"
	.string "point!$"

MossdeepCity_Gym_Text_SamanthaIntro::
# 69 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I see it… I see your future…\p"
	.string "If you can beat me, I will tell you your\n"
	.string "future!$"

MossdeepCity_Gym_Text_SamanthaDefeat::
# 73 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I surrender!$"

MossdeepCity_Gym_Text_SamanthaPostBattle::
# 77 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "You will wage a terrifically intense\n"
	.string "battle with our GYM LEADERS…\p"
	.string "The result… You won't hear it from me!$"

MossdeepCity_Gym_Text_MauraIntro::
# 81 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "The roads you have traveled… What you\n"
	.string "have experienced…\p"
	.string "Come at me with everything you've\n"
	.string "learned!$"

MossdeepCity_Gym_Text_MauraDefeat::
# 85 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "You've traveled a path of greatness!$"

MossdeepCity_Gym_Text_MauraPostBattle::
# 89 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "A bright future awaits those who have\n"
	.string "worked diligently.\p"
	.string "For those who lazed idly, there is only\n"
	.string "despair at the end.\p"
	.string "What goes around comes around…$"

MossdeepCity_Gym_Text_SylviaIntro::
# 93 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Even at the risk of life, I will win this\n"
	.string "battle!$"

MossdeepCity_Gym_Text_SylviaDefeat::
# 97 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "What you do… It horrifies me…$"

MossdeepCity_Gym_Text_SylviaPostBattle::
# 101 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "How dare you beat me…\p"
	.string "It won't be my fault if something\n"
	.string "horrible befalls you…$"

MossdeepCity_Gym_Text_NateIntro::
# 105 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Hohoho.\p"
	.string "You need me to show you how tenacious\n"
	.string "the PSYCHIC type can be.$"

MossdeepCity_Gym_Text_NateDefeat::
# 109 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Oh! My, my! Your battle style is\n"
	.string "fantastic!$"

MossdeepCity_Gym_Text_NatePostBattle::
# 113 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I… I don't let defeat rattle m-me,\n"
	.string "however b-badly.$"

MossdeepCity_Gym_Text_KathleenIntro::
# 117 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Let me show you a perfectly awful,\n"
	.string "horrifying time!$"

MossdeepCity_Gym_Text_KathleenDefeat::
# 121 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "N-nooooo!$"

MossdeepCity_Gym_Text_KathleenPostBattle::
# 125 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Your vitality is contagious! Get away\n"
	.string "from me quickly!$"

MossdeepCity_Gym_Text_CliffordIntro::
# 129 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "I may be past my prime, but I suggest\n"
	.string "you not patronize me.$"

MossdeepCity_Gym_Text_CliffordDefeat::
# 133 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Ah, you overflow with the power of\n"
	.string "youth!$"

MossdeepCity_Gym_Text_CliffordPostBattle::
# 137 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "It seems that I could not overcome\n"
	.string "your youthful energy.$"

MossdeepCity_Gym_Text_MaceyIntro::
# 141 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "You're not getting through to the end!\n"
	.string "Not if I can help it!$"

MossdeepCity_Gym_Text_MaceyDefeat::
# 145 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "How could you be so ludicrously strong?$"

MossdeepCity_Gym_Text_MaceyPostBattle::
# 149 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Humph! You may be strong, but you're\n"
	.string "not suitable for the PSYCHIC type!\p"
	.string "The way you battle is somehow brutal!$"

MossdeepCity_Gym_Text_NicholasIntro::
# 153 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Wroooar! Have a taste of my super\n"
	.string "POKéMON hard-battling power!$"

MossdeepCity_Gym_Text_NicholasDefeat::
# 157 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Oh! Done in!$"

MossdeepCity_Gym_Text_NicholasPostBattle::
# 161 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "All right! I think I'll develop a special\n"
	.string "invincible POKéMON power next.$"

MossdeepCity_Gym_Text_TateAndLizaIntro::
# 165 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: Hehehe… Were you surprised?\p"
	.string "LIZA: Fufufu… Were you surprised?\p"
	.string "TATE: That there are two GYM LEADERS?\n"
	.string "LIZA: That there are two GYM LEADERS?\p"
	.string "TATE: We're twins! LIZA: We're twins!\p"
	.string "TATE: We don't need to talk because…\n"
	.string "LIZA: We can each determine what…\p"
	.string "TATE: The other is thinking… LIZA: All\n"
	.string "in our minds!\p"
	.string "TATE: This combination of ours… LIZA:\n"
	.string "Can you beat it?$"

MossdeepCity_Gym_Text_TateAndLizaDefeat::
# 169 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: What?! Our combination… LIZA:\n"
	.string "Was shattered!\p"
	.string "TATE: It can't be helped. You've won…\n"
	.string "LIZA: So, in recognition, take this.$"

MossdeepCity_Gym_Text_ReceivedMindBadge::
# 173 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "{PLAYER} received the MIND BADGE\n"
	.string "from TATE and LIZA.$"

MossdeepCity_Gym_Text_ExplainMindBadgeTakeThis::
# 177 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: The MIND BADGE enhances the SP.\n"
	.string "ATK and SP. DEF of POKéMON.\p"
	.string "LIZA: It also lets you use the HM move\n"
	.string "DIVE outside of battle.\p"
	.string "TATE: You should also take this, too.$"

MossdeepCity_Gym_Text_ExplainCalmMind::
# 181 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: That TM04 contains… LIZA: CALM\n"
	.string "MIND!\p"
	.string "TATE: It raises SP. ATK and… LIZA: It\n"
	.string "raises SP. DEF!\p"
	.string "TATE: It's a move that's perfect… LIZA:\n"
	.string "For PSYCHIC POKéMON!\p"
	.string "… … … … … …$"

MossdeepCity_Gym_Text_RegisteredTateAndLiza::
# 185 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Registered GYM LEADERS TATE & LIZA in\n"
	.string "the POKéNAV.$"

MossdeepCity_Gym_Text_TateAndLizaPostBattle::
# 189 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: Looks like the bond between you\n"
	.string "and your POKéMON is far stronger than\l"
	.string "the bond that we share as twins.\p"
	.string "LIZA: You will become even stronger!\n"
	.string "We've battled you, so we know.$"

MossdeepCity_Gym_Text_TateAndLizaNeedTwoMons::
# 193 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: Hehehe… Were you surprised?\p"
	.string "LIZA: That there are two GYM LEADERS?\p"
	.string "TATE: Oops, you have only one… LIZA:\n"
	.string "POKéMON that can battle.\p"
	.string "TATE: We can't battle that way!\p"
	.string "LIZA: If you want to challenge us, bring\n"
	.string "some more POKéMON.$"

MossdeepCity_Gym_Text_GymStatue::
# 197 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "MOSSDEEP CITY POKéMON GYM$"

MossdeepCity_Gym_Text_GymStatueCertified::
# 201 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "MOSSDEEP CITY POKéMON GYM\p"
	.string "LIZA AND TATE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

MossdeepCity_Gym_Text_TateAndLizaPreRematch::
# 205 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: POKéMON… LIZA: POKéMON…\p"
	.string "TATE: By changing the party's mix…\n"
	.string "LIZA: The battle style changes.\p"
	.string "TATE: But me… LIZA: But me…\p"
	.string "TATE: I'll always be with LIZA! LIZA:\n"
	.string "I'll always be with TATE!\p"
	.string "TATE: Our combination… LIZA: We'll show\n"
	.string "you again and again!$"

MossdeepCity_Gym_Text_TateAndLizaRematchDefeat::
# 209 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: You and your POKéMON… LIZA: It's\n"
	.string "as if you were siblings!$"

MossdeepCity_Gym_Text_TateAndLizaPostRematch::
# 213 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: You can knock us down, but we'll\n"
	.string "never stay down!\p"
	.string "LIZA: Because the two of us, we always\n"
	.string "support each other!$"

MossdeepCity_Gym_Text_TateAndLizaRematchNeedTwoMons::
# 217 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: You're back again… LIZA: You're\n"
	.string "back again…\p"
	.string "TATE: To give us a rematch. LIZA: To\n"
	.string "give us a rematch.\p"
	.string "TATE: But… LIZA: For our match…\p"
	.string "TATE: You brought just one POKéMON!\n"
	.string "LIZA: You brought just one POKéMON!\p"
	.string "TATE: We need you to bring at least…\n"
	.string "LIZA: Two POKéMON when you come back.$"
