MossdeepCity_Gym_MapScripts::
	.byte 0


MossdeepCity_Gym_EventScript_Blake::
# 5 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_BLAKE, MossdeepCity_Gym_Text_BlakeIntro, MossdeepCity_Gym_Text_BlakeDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_BlakePostBattle
	return


MossdeepCity_Gym_EventScript_BlueFloorSwitch::
	end


MossdeepCity_Gym_EventScript_Clifford::
# 14 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_CLIFFORD, MossdeepCity_Gym_Text_CliffordIntro, MossdeepCity_Gym_Text_CliffordDefeat, Text_NotEnoughMonsForDoubleBattle
# 15 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_CliffordPostBattle
	return


MossdeepCity_Gym_EventScript_GreenFloorSwitch::
	end


MossdeepCity_Gym_EventScript_GymGuide::
	end


MossdeepCity_Gym_EventScript_Hannah::
# 27 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_HANNAH, MossdeepCity_Gym_Text_HannahIntro, MossdeepCity_Gym_Text_HannahDefeat, Text_NotEnoughMonsForDoubleBattle
# 28 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_HannahPostBattle
	return


MossdeepCity_Gym_EventScript_Kathleen::
# 32 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_KATHLEEN, MossdeepCity_Gym_Text_KathleenIntro, MossdeepCity_Gym_Text_KathleenDefeat, Text_NotEnoughMonsForDoubleBattle
# 33 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_KathleenPostBattle
	return


MossdeepCity_Gym_EventScript_LeftGymStatue::
	end


MossdeepCity_Gym_EventScript_Macey::
# 44 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_MACEY, MossdeepCity_Gym_Text_MaceyIntro, MossdeepCity_Gym_Text_MaceyDefeat, Text_NotEnoughMonsForDoubleBattle
# 45 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_MaceyPostBattle
	return


MossdeepCity_Gym_EventScript_Maura::
# 49 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_MAURA, MossdeepCity_Gym_Text_MauraIntro, MossdeepCity_Gym_Text_MauraDefeat, Text_NotEnoughMonsForDoubleBattle
# 50 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_MauraPostBattle
	return


MossdeepCity_Gym_EventScript_Nate::
# 54 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_NATE, MossdeepCity_Gym_Text_NateIntro, MossdeepCity_Gym_Text_NateDefeat, Text_NotEnoughMonsForDoubleBattle
# 55 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_NatePostBattle
	return


MossdeepCity_Gym_EventScript_Nicholas::
# 59 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_NICHOLAS, MossdeepCity_Gym_Text_NicholasIntro, MossdeepCity_Gym_Text_NicholasDefeat, Text_NotEnoughMonsForDoubleBattle
# 60 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_NicholasPostBattle
	return


MossdeepCity_Gym_EventScript_Preston::
# 64 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_PRESTON, MossdeepCity_Gym_Text_PrestonIntro, MossdeepCity_Gym_Text_PrestonDefeat, Text_NotEnoughMonsForDoubleBattle
# 65 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_PrestonPostBattle
	return


MossdeepCity_Gym_EventScript_PurpleFloorSwitch::
	end


MossdeepCity_Gym_EventScript_RedFloorSwitch::
	end


MossdeepCity_Gym_EventScript_RightGymStatue::
	end


MossdeepCity_Gym_EventScript_Samantha::
# 84 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_SAMANTHA, MossdeepCity_Gym_Text_SamanthaIntro, MossdeepCity_Gym_Text_SamanthaDefeat, Text_NotEnoughMonsForDoubleBattle
# 85 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_SamanthaPostBattle
	return


MossdeepCity_Gym_EventScript_Sylvia::
# 89 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_SYLVIA, MossdeepCity_Gym_Text_SylviaIntro, MossdeepCity_Gym_Text_SylviaDefeat, Text_NotEnoughMonsForDoubleBattle
# 90 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_SylviaPostBattle
	return


MossdeepCity_Gym_EventScript_TateAndLiza::
	end


MossdeepCity_Gym_EventScript_Virgil::
# 98 "data/maps/MossdeepCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_VIRGIL, MossdeepCity_Gym_Text_VirgilIntro, MossdeepCity_Gym_Text_VirgilDefeat, Text_NotEnoughMonsForDoubleBattle
# 99 "data/maps/MossdeepCity_Gym/scripts.pory"
	msgbox MossdeepCity_Gym_Text_VirgilPostBattle
	return


MossdeepCity_Gym_EventScript_WarpToEntrance::
	end


MossdeepCity_Gym_EventScript_YellowFloorSwitch::
	end


MossdeepCity_Gym_Text_BlakeDefeat::
# 112 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_BlakeDefeat$"

MossdeepCity_Gym_Text_BlakeIntro::
# 116 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_BlakeIntro$"

MossdeepCity_Gym_Text_BlakePostBattle::
# 120 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_BlakePostBattle$"

MossdeepCity_Gym_Text_CliffordDefeat::
# 124 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_CliffordDefeat$"

MossdeepCity_Gym_Text_CliffordIntro::
# 128 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_CliffordIntro$"

MossdeepCity_Gym_Text_CliffordPostBattle::
# 132 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_CliffordPostBattle$"

MossdeepCity_Gym_Text_HannahDefeat::
# 136 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_HannahDefeat$"

MossdeepCity_Gym_Text_HannahIntro::
# 140 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_HannahIntro$"

MossdeepCity_Gym_Text_HannahPostBattle::
# 144 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_HannahPostBattle$"

MossdeepCity_Gym_Text_KathleenDefeat::
# 148 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_KathleenDefeat$"

MossdeepCity_Gym_Text_KathleenIntro::
# 152 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_KathleenIntro$"

MossdeepCity_Gym_Text_KathleenPostBattle::
# 156 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_KathleenPostBattle$"

MossdeepCity_Gym_Text_MaceyDefeat::
# 160 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MaceyDefeat$"

MossdeepCity_Gym_Text_MaceyIntro::
# 164 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MaceyIntro$"

MossdeepCity_Gym_Text_MaceyPostBattle::
# 168 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MaceyPostBattle$"

MossdeepCity_Gym_Text_MauraDefeat::
# 172 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MauraDefeat$"

MossdeepCity_Gym_Text_MauraIntro::
# 176 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MauraIntro$"

MossdeepCity_Gym_Text_MauraPostBattle::
# 180 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_MauraPostBattle$"

MossdeepCity_Gym_Text_NateDefeat::
# 184 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NateDefeat$"

MossdeepCity_Gym_Text_NateIntro::
# 188 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NateIntro$"

MossdeepCity_Gym_Text_NatePostBattle::
# 192 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NatePostBattle$"

MossdeepCity_Gym_Text_NicholasDefeat::
# 196 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NicholasDefeat$"

MossdeepCity_Gym_Text_NicholasIntro::
# 200 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NicholasIntro$"

MossdeepCity_Gym_Text_NicholasPostBattle::
# 204 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_NicholasPostBattle$"

MossdeepCity_Gym_Text_PrestonDefeat::
# 208 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_PrestonDefeat$"

MossdeepCity_Gym_Text_PrestonIntro::
# 212 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_PrestonIntro$"

MossdeepCity_Gym_Text_PrestonPostBattle::
# 216 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_PrestonPostBattle$"

MossdeepCity_Gym_Text_SamanthaDefeat::
# 220 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SamanthaDefeat$"

MossdeepCity_Gym_Text_SamanthaIntro::
# 224 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SamanthaIntro$"

MossdeepCity_Gym_Text_SamanthaPostBattle::
# 228 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SamanthaPostBattle$"

MossdeepCity_Gym_Text_SylviaDefeat::
# 232 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SylviaDefeat$"

MossdeepCity_Gym_Text_SylviaIntro::
# 236 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SylviaIntro$"

MossdeepCity_Gym_Text_SylviaPostBattle::
# 240 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_SylviaPostBattle$"

MossdeepCity_Gym_Text_VirgilDefeat::
# 244 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_VirgilDefeat$"

MossdeepCity_Gym_Text_VirgilIntro::
# 248 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_VirgilIntro$"

MossdeepCity_Gym_Text_VirgilPostBattle::
# 252 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "MossdeepCity_Gym_Text_VirgilPostBattle$"

MossdeepCity_Gym_Text_ExplainCalmMind::
# 256 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: That TM04 contains…\n"
	.string "LIZA: CALM MIND!\p"
	.string "TATE: It raises SP. ATK and…\n"
	.string "LIZA: It raises SP. DEF!\p"
	.string "TATE: It's a move that's perfect…\n"
	.string "LIZA: For PSYCHIC POKéMON!\p"
	.string "… … … … … …$"

MossdeepCity_Gym_Text_TateAndLizaPostRematch::
# 260 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "TATE: You can knock us down,\n"
	.string "but we'll never stay down!\p"
	.string "LIZA: Because the two of us,\n"
	.string "we always support each other!$"

MossdeepCity_Gym_Text_GymStatue::
# 264 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "MOSSDEEP CITY POKéMON GYM$"

MossdeepCity_Gym_Text_GymStatueCertified::
# 268 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "MOSSDEEP CITY POKéMON GYM\p"
	.string "LIZA AND TATE'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

MossdeepCity_Gym_Text_GymGuidePostVictory::
# 272 "data/maps/MossdeepCity_Gym/scripts.pory"
	.string "Wow, you're astounding!\n"
	.string "You're one great TRAINER!$"
