Route114_LanettesHouse_MapScripts::
# 2 "data/maps/Route114_LanettesHouse/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route114_LanettesHouse_OnTransition
	.byte 0


Route114_LanettesHouse_Text_EverythingClutteredKeepThis::
# 6 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "LANETTE: Oh! {PLAYER}{KUN}!\p"
	.string "I'm sorry everything is so cluttered\n"
	.string "When I get engrossed in research,\l"
	.string "things end up this way\p"
	.string "This is embarrassing Please keep this a\n"
	.string "secret in exchange for this.$"

Route114_LanettesHouse_Text_OrganizeYourBoxes::
# 10 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "May I offer advice about my POKMON\n"
	.string "Storage System?\p"
	.string "You should organize your BOXES so you\n"
	.string "can tell which POKMON are in them.$"

Route114_LanettesHouse_Text_ResearchNotesPage1::
# 14 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "It's LANETTE's research notes. There's\n"
	.string "information about BOXES.\p"
	.string "Design BOXES to hold 30 POKMON each.\p"
	.string "Each TRAINER should be able to store\n"
	.string "420 POKMON on the PC system.\p"
	.string "Keep reading?$"

Route114_LanettesHouse_Text_ResearchNotesPage2::
# 18 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "A marking system should be added to\n"
	.string "make POKMON easier to organize.\p"
	.string "The name and wallpaper design of each\n"
	.string "BOX will be made changeable to please\l"
	.string "the stored POKMON.\p"
	.string "Keep reading?$"

Route114_LanettesHouse_Text_ResearchNotesPage3::
# 22 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "When storing a POKMON, it should be\n"
	.string "sent to the BOX inspected last.\p"
	.string "If that BOX is full, the received POKMON\n"
	.string "is stored in the next BOX.\p"
	.string "In other words, when a BOX is examined,\n"
	.string "it is automatically selected as the BOX\l"
	.string "to which POKMON are sent.$"

Route114_LanettesHouse_Text_ClosedTheNotebook::
# 26 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "{PLAYER} closed the notebook.$"

Route114_LanettesHouse_Text_EmailFromBill::
# 30 "data/maps/Route114_LanettesHouse/scripts.pory"
	.string "There's an e-mail from someone on the\n"
	.string "PC.\p"
	.string "\p"
	.string "Your Storage System offers more\n"
	.string "convenience than mine.\p"
	.string "It has a lot of user-friendly features\n"
	.string "that make it fun and useful, too.\p"
	.string "It makes me proud that I played a part\n"
	.string "in its development.\p"
	.string "Here's hoping that you'll continue\n"
	.string "research in Storage Systems.\p"
	.string "From BILL$"
