ViridianCity_MapScripts::
# 2 "data/maps/ViridianCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ViridianCity_OnTransition
	.byte 0


ViridianCity_Text_CanCarryMonsAnywhere::
# 6 "data/maps/ViridianCity/scripts.pory"
	.string "Those POKé BALLS at your waist! You\n"
	.string "have POKéMON, don't you?\p"
	.string "It's great that you can carry and use\n"
	.string "POKéMON anytime, anywhere.$"

ViridianCity_Text_GymClosedWonderWhoLeaderIs::
# 10 "data/maps/ViridianCity/scripts.pory"
	.string "This POKéMON GYM is always closed.\p"
	.string "I wonder who the LEADER is?$"

ViridianCity_Text_ViridiansGymLeaderReturned::
# 14 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN GYM's LEADER returned!$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
# 18 "data/maps/ViridianCity/scripts.pory"
	.string "You want to know about the two kinds of\n"
	.string "caterpillar POKéMON?$"

ViridianCity_Text_OhOkayThen::
# 22 "data/maps/ViridianCity/scripts.pory"
	.string "Oh, okay then!$"

ViridianCity_Text_ExplainCaterpieWeedle::
# 26 "data/maps/ViridianCity/scripts.pory"
	.string "CATERPIE has no poison, but WEEDLE\n"
	.string "does.\p"
	.string "Watch that your POKéMON aren't stabbed\n"
	.string "by WEEDLE's POISON STING.$"

ViridianCity_Text_GrandpaHasntHadCoffeeYet::
# 30 "data/maps/ViridianCity/scripts.pory"
	.string "Oh, Grandpa! Don't be so mean!\p"
	.string "I'm so sorry. He hasn't had his coffee\n"
	.string "yet.$"

ViridianCity_Text_GoShoppingInPewterOccasionally::
# 34 "data/maps/ViridianCity/scripts.pory"
	.string "I go shopping in PEWTER CITY\n"
	.string "occasionally.\p"
	.string "I have to take the winding trail in\n"
	.string "VIRIDIAN FOREST when I go.$"

ViridianCity_Text_ThisIsPrivateProperty::
# 38 "data/maps/ViridianCity/scripts.pory"
	.string "I absolutely forbid you from going\n"
	.string "through here!\p"
	.string "This is private property!$"

ViridianCity_Text_ShowYouHowToCatchMons::
# 42 "data/maps/ViridianCity/scripts.pory"
	.string "Well, now, I've had my coffee, and that's\n"
	.string "what I need to get going!\p"
	.string "Hm? What is that red box you have?\p"
	.string "Ah, so you're working on your POKéDEX.\p"
	.string "Then let me give you a word of advice.\p"
	.string "Whenever you catch a POKéMON, the\n"
	.string "POKéDEX automatically updates\l"
	.string "its data.\p"
	.string "…You don't know how to catch a\n"
	.string "POKéMON?\p"
	.string "I suppose I had better show you then!$"

ViridianCity_Text_ThatWasEducationalTakeThis::
# 46 "data/maps/ViridianCity/scripts.pory"
	.string "There! Now tell me, that was\n"
	.string "educational, was it not?\p"
	.string "And here, take this, too.$"

ViridianCity_Text_WatchThatToLearnBasics::
# 50 "data/maps/ViridianCity/scripts.pory"
	.string "If there's something you don't\n"
	.string "understand, watch that.\p"
	.string "It will teach you about the basics of\n"
	.string "being a POKéMON TRAINER.$"

ViridianCity_Text_WeakenMonsFirstToCatch::
# 54 "data/maps/ViridianCity/scripts.pory"
	.string "Well, now, I've had my coffee, and that's\n"
	.string "what I need to get going!\p"
	.string "But I made it too strong. It gave me a\n"
	.string "headache…\p"
	.string "Incidentally, are you filling your\n"
	.string "POKéDEX?\p"
	.string "At first, focus on weakening the\n"
	.string "POKéMON before trying to catch it.$"

ViridianCity_Text_HowsTeachyTVHelping::
# 58 "data/maps/ViridianCity/scripts.pory"
	.string "Well, now, I've had my coffee, and that's\n"
	.string "what I need to get going!\p"
	.string "But I made it too strong. It gave me a\n"
	.string "headache…\p"
	.string "Incidentally, is my old TEACHY TV\n"
	.string "helping you?$"

ViridianCity_Text_MyGrandsonOnTheShow::
# 62 "data/maps/ViridianCity/scripts.pory"
	.string "Wahaha! It's my grandson on the show!\p"
	.string "Since he's the one doing the teaching,\n"
	.string "you're bound to learn.$"

ViridianCity_Text_TooBusyForTeachyTV::
# 66 "data/maps/ViridianCity/scripts.pory"
	.string "Hm… You're too busy to not even have\n"
	.string "the time for TEACHY TV…\p"
	.string "Time is money, and neither should be ill\n"
	.string "spent…$"

ViridianCity_Text_CitySign::
# 70 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN CITY The Eternally Green\n"
	.string "Paradise$"

ViridianCity_Text_CatchMonsForEasierBattles::
# 74 "data/maps/ViridianCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Catch POKéMON and expand your\n"
	.string "collection.\p"
	.string "The more you have, the easier it is to\n"
	.string "battle.$"

ViridianCity_Text_MovesLimitedByPP::
# 78 "data/maps/ViridianCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The battle moves of POKéMON are limited\n"
	.string "by their POWER POINTS, PP.\p"
	.string "To replenish PP, rest your tired\n"
	.string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_GymSign::
# 82 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
# 86 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN GYM's doors are locked…$"
