ViridianCity_MapScripts::
	.byte 0


ViridianCity_EventScript_Boy::
# 5 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_CanCarryMonsAnywhere, MSGBOX_NPC
	end


ViridianCity_EventScript_CitySign::
# 10 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_CitySign, MSGBOX_SIGN
	end


ViridianCity_EventScript_GymDoor::
# 15 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_GymDoorsAreLocked, MSGBOX_SIGN
	end


ViridianCity_EventScript_GymDoorLocked::
	end


ViridianCity_EventScript_GymSign::
# 24 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_GymSign, MSGBOX_SIGN
	end


ViridianCity_EventScript_OldMan::
	end


ViridianCity_EventScript_RoadBlocked::
	end


ViridianCity_EventScript_TrainerTips1::
# 37 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_CatchMonsForEasierBattles, MSGBOX_SIGN
	end


ViridianCity_EventScript_TrainerTips2::
# 42 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_MovesLimitedByPP, MSGBOX_SIGN
	end


ViridianCity_EventScript_TutorialOldMan::
	end


ViridianCity_EventScript_TutorialTriggerLeft::
	end


ViridianCity_EventScript_TutorialTriggerRight::
	end


ViridianCity_EventScript_Woman::
	end


ViridianCity_EventScript_Youngster::
# 63 "data/maps/ViridianCity/scripts.pory"
	msgbox ViridianCity_Text_WantToKnowAboutCaterpillarMons, MSGBOX_YESNO
	end


ViridianCity_Text_CatchMonsForEasierBattles::
# 68 "data/maps/ViridianCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "Catch POKéMON and expand your\n"
	.string "collection.\p"
	.string "The more you have, the easier it is to\n"
	.string "battle.$"

ViridianCity_Text_CitySign::
# 72 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN CITY The Eternally Green\n"
	.string "Paradise$"

ViridianCity_Text_GymSign::
# 76 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN CITY POKéMON GYM$"

ViridianCity_Text_GymDoorsAreLocked::
# 80 "data/maps/ViridianCity/scripts.pory"
	.string "VIRIDIAN GYM's doors are locked…$"

ViridianCity_Text_MovesLimitedByPP::
# 84 "data/maps/ViridianCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "The battle moves of POKéMON are limited\n"
	.string "by their POWER POINTS, PP.\p"
	.string "To replenish PP, rest your tired\n"
	.string "POKéMON at a POKéMON CENTER.$"

ViridianCity_Text_CanCarryMonsAnywhere::
# 88 "data/maps/ViridianCity/scripts.pory"
	.string "Those POKé BALLS at your waist!\n"
	.string "You have POKéMON, don't you?\p"
	.string "It's great that you can carry and\n"
	.string "use POKéMON anytime, anywhere.$"

ViridianCity_Text_WantToKnowAboutCaterpillarMons::
# 92 "data/maps/ViridianCity/scripts.pory"
	.string "You want to know about the two\n"
	.string "kinds of caterpillar POKéMON?$"
