SouthernIsland_Exterior_MapScripts::
	.byte 0


SouthernIsland_Exterior_EventScript_Sailor::
# 5 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox EventTicket_Text_SouthernIslandSailBack, MSGBOX_YESNO
	end


SouthernIsland_Exterior_EventScript_Sign::
# 10 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox SouthernIsland_Exterior_Text_Sign1, MSGBOX_SIGN
	end


SouthernIsland_Exterior_Text_Sign1::
# 14 "data/maps/SouthernIsland_Exterior/scripts.pory"
	.string "Southern Island$"
