Route113_MapScripts::
# 2 "data/maps/Route113/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, Route113_OnResume
# 3 "data/maps/Route113/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, Route113_OnTransition
	.byte 0


Route113_Text_AshCanBeFashionedIntoGlass::
# 7 "data/maps/Route113/scripts.pory"
	.string "Wahahaha! Today's technology is a\n"
	.string "wondrous thing!\p"
	.string "Take this volcanic ash here. It can be\n"
	.string "fashioned into glass.$"

Route113_Text_FunWalkingThroughAsh::
# 11 "data/maps/Route113/scripts.pory"
	.string "It's fun walking through the volcano's\n"
	.string "ashes on the ground and grass.\p"
	.string "You can see where you walked--it's\n"
	.string "really neat!$"

Route113_Text_RouteSign111::
# 15 "data/maps/Route113/scripts.pory"
	.string "ROUTE 113 {RIGHT_ARROW} ROUTE 111$"

Route113_Text_RouteSignFallarbor::
# 19 "data/maps/Route113/scripts.pory"
	.string "ROUTE 113 {LEFT_ARROW} FALLARBOR TOWN$"

Route113_Text_TrainerTipsRegisterKeyItems::
# 23 "data/maps/Route113/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "You may register one of the KEY ITEMS\n"
	.string "in your BAG as SELECT.\p"
	.string "Simply press SELECT to use the\n"
	.string "registered item conveniently.$"

Route113_Text_GlassWorkshopSign::
# 27 "data/maps/Route113/scripts.pory"
	.string "GLASS WORKSHOP “Turning Volcanic Ash\n"
	.string "into Glass Items”$"
