FourIsland_PokemonCenter_1F_MapScripts::
# 2 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_PokemonCenter_1F_OnTransition
# 3 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, CableClub_OnResume
	.byte 0


Text_BodySlamTeach::
# 7 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "Ready? Boing!\p"
	.string "We're having a BODY SLAM match to see\n"
	.string "who wimps out first.\p"
	.string "If you were to join us, you'd be\n"
	.string "squashed like a bug, though\p"
	.string "How about I teach BODY SLAM to a\n"
	.string "POKMON of yours instead?$"

Text_BodySlamDeclined::
# 11 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "Come again! Boing!$"

Text_BodySlamWhichMon::
# 15 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "Which POKMON wants to learn how to BODY\n"
	.string "SLAM?$"

Text_BodySlamTaught::
# 19 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "Boioing!$"

FourIsland_House1_Text_FatMan::
# 23 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "$"

FourIsland_PokemonCenter_1F_Text_RareIceMonsInCave::
# 27 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "There's a rare kind of ICE POKMON that\n"
	.string "lives in the cave.\p"
	.string "We get a lot of visitors hoping to see\n"
	.string "that POKMON.$"

FourIsland_PokemonCenter_1F_Text_DayCarePeopleFoundEggBefore::
# 31 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "Oh? A POKMON EGG? I have no idea.\p"
	.string "Oh, wait. The DAY-CARE people in town\n"
	.string "were saying something.\p"
	.string "They said that they'd found EGGS\n"
	.string "before on their property.$"

FourIsland_PokemonCenter_1F_Text_NewPokemonJournalHasntArrived::
# 35 "data/maps/FourIsland_PokemonCenter_1F/scripts.pory"
	.string "What's this?\p"
	.string "The new POKMON JOURNAL hasn't arrived\n"
	.string "on this island?$"
