CeruleanCity_House4_MapScripts::
	.byte 0


CeruleanCity_House4_Text_NothingEntertaining::
# 5 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "Sigh… Too much time, too little to do…\p"
	.string "Is nothing entertaining happening\n"
	.string "anywhere?$"

CeruleanCity_House4_Text_NewNewsInformativeHaveThis::
# 9 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "Ah! A new news report!\p"
	.string "Hmm…\p"
	.string "I see! That was quite informative!\p"
	.string "I applaud you for taking interest in\n"
	.string "the news at your young age.\p"
	.string "As my thanks for sharing the news with\n"
	.string "me, I want you to have this.$"

CeruleanCity_House4_Text_IncredibleNewsHaveBerries::
# 13 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "Oh, oh! Th-this news report!\p"
	.string "Hmm…\p"
	.string "Amazing! What an incredible piece of\n"
	.string "news!\p"
	.string "I haven't seen a news story this\n"
	.string "incredible in too long a time!\p"
	.string "Thanks for sharing this fantastic news.\n"
	.string "Have a bunch of BERRIES!$"

CeruleanCity_House4_Text_WishCouldShareNewsWithOthers::
# 17 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "It seems such a shame to not share this\n"
	.string "news with other folks…\p"
	.string "I wish I could tell someone… Let others\n"
	.string "know the news…$"

CeruleanCity_House4_Text_ThanksForSpreadingNewsTakeThis::
# 21 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "Ah, you've spread the news for me?\p"
	.string "Good news becomes worthwhile when all\n"
	.string "sorts of people share it.\p"
	.string "As my thanks for your spreading the\n"
	.string "news, take this!$"

CeruleanCity_House4_Text_MagnificentNewsSpreadHaveBerries::
# 25 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "You've spread the news some more?\n"
	.string "Magnificent!\p"
	.string "That piece of news must be delighted to\n"
	.string "be passed around so.\p"
	.string "Yes, indeed!\p"
	.string "Consider this a show of appreciation\n"
	.string "from me and the news.\p"
	.string "I'll give you more BERRIES than I\n"
	.string "usually do.$"

CeruleanCity_House4_Text_EnjoyingMyselfWithAllSortsOfNews::
# 29 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "I'm quite enjoying myself with all sorts\n"
	.string "of news.\p"
	.string "Yes, I am satisfied! I won't be bored for\n"
	.string "a while.$"

CeruleanCity_House4_Text_YourBerryPouchIsFull::
# 33 "data/maps/CeruleanCity_House4/scripts.pory"
	.string "Hm? Your BERRY POUCH is full. My gift\n"
	.string "remains ungiven, then.$"
