ThreeIsland_House3_MapScripts::
	.byte 0


ThreeIsland_House3_EventScript_Beauty::
# 5 "data/maps/ThreeIsland_House3/scripts.pory"
	msgbox ThreeIsland_House3_Text_WantedToLiveSomewhereQuiet, MSGBOX_NPC
	end


ThreeIsland_House3_Text_WantedToLiveSomewhereQuiet::
# 10 "data/maps/ThreeIsland_House3/scripts.pory"
	.string "I bought this house because I\n"
	.string "wanted to live somewhere quiet.\p"
	.string "Today, I think I'll go out fishing.$"
