SlateportCity_Harbor_MapScripts::
# 2 "data/maps/SlateportCity_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SlateportCity_Harbor_OnTransition
	.byte 0


SlateportCity_Harbor_MapScripts::
# 6 "data/maps/SlateportCity_Harbor/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SlateportCity_Harbor_OnTransition
	return


SlateportCity_Harbor_Text_FerryServiceUnavailable::
# 10 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "I beg your pardon? You're looking for a\n"
	.string "ship?\p"
	.string "I'm sorry, the ferry service isn't\n"
	.string "available at present…$"

SlateportCity_Harbor_Text_MayISeeYourTicket::
# 14 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "Hello, are you here for the ferry? May I\n"
	.string "see your TICKET?$"

SlateportCity_Harbor_Text_YouMustHaveTicket::
# 18 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "{PLAYER} doesn't have the TICKET…\p"
	.string "I'm terribly sorry.\p"
	.string "You must have a TICKET to board the\n"
	.string "ferry.$"

SlateportCity_Harbor_Text_FlashedTicketWhereTo::
# 22 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "{PLAYER} flashed the TICKET.\p"
	.string "Perfect! That's all you need!\p"
	.string "And where would you like to go?$"

SlateportCity_Harbor_Text_SailAnotherTime::
# 26 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "Please sail with us another time!$"

SlateportCity_Harbor_Text_LilycoveItIs::
# 30 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "LILYCOVE CITY it is, then!$"

SlateportCity_Harbor_Text_BattleFrontierItIs::
# 34 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "BATTLE FRONTIER it is, then!$"

SlateportCity_Harbor_Text_PleaseBoardFerry::
# 38 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "Please board the ferry and wait for\n"
	.string "departure.$"

SlateportCity_Harbor_Text_WhereWouldYouLikeToGo::
# 42 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "Then, where would you like to go?$"

SlateportCity_Harbor_Text_LoveToGoDeepUnderwaterSomeday::
# 46 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "A journey to the bottom of the sea… I\n"
	.string "wonder what it'd be like?\p"
	.string "I'd love to go deep underwater like that\n"
	.string "someday.$"

SlateportCity_Harbor_Text_AbnormalWeather::
# 50 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "For a ship to sail safely, we need to\n"
	.string "know about the weather!\p"
	.string "Speaking of weather, I heard something\n"
	.string "from a guy at the WEATHER INSTITUTE.\p"
	.string "He was saying abnormal weather has\n"
	.string "been reported all over the place!\p"
	.string "You should visit the WEATHER INSTITUTE\n"
	.string "and ask around!$"

SlateportCity_Harbor_Text_SubTooSmallForMe::
# 54 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "I wanted to go with CAPT. STERN on the\n"
	.string "ocean floor exploration.\p"
	.string "But the sub's too small for me.\p"
	.string "If I squeezed in, there wouldn't be any\n"
	.string "room for the CAPTAIN…$"

SlateportCity_Harbor_Text_SameThugsTriedToRobAtMuseum::
# 58 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Those thugs…\p"
	.string "They're the same lot who tried to rob\n"
	.string "the DEVON GOODS at the MUSEUM.$"

SlateportCity_Harbor_Text_ArchieYouAgainHideoutInLilycove::
# 62 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "ARCHIE: Oh? Not you again…\p"
	.string "You are tenacious to track us here,\n"
	.string "that much I will give you.\p"
	.string "But now… No one can stop us! No one!\p"
	.string "Or, will you follow us back to our\n"
	.string "HIDEOUT in LILYCOVE CITY?\p"
	.string "Fwahahahaha…$"

SlateportCity_Harbor_Text_CaptSternWhyStealMySubmarine::
# 66 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Why…\p"
	.string "Why would TEAM AQUA steal my SUBMARINE\n"
	.string "EXPLORER 1?\p"
	.string "They can't be after the slumbering\n"
	.string "POKéMON at the bottom of the sea…\p"
	.string "But even if I were to chase them, I\n"
	.string "don't stand a chance against them…$"

SlateportCity_Harbor_Text_TeamAquaLeftNeedDive::
# 70 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Oh, {PLAYER}{KUN}…\p"
	.string "Okay… So TEAM AQUA left before you\n"
	.string "could stop them…\p"
	.string "Oh, no, don't blame yourself. You're not\n"
	.string "responsible for this.\p"
	.string "Trying to catch a submarine… It's\n"
	.string "impossible for most people.\p"
	.string "You would need a POKéMON that knows\n"
	.string "how to DIVE…\p"
	.string "Perhaps if you went out to MOSSDEEP\n"
	.string "CITY…\p"
	.string "A lot of divers live out there, so\n"
	.string "someone might teach you…$"

SlateportCity_Harbor_Text_NeedDiveToCatchSub::
# 74 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Trying to catch a\n"
	.string "submarine… It's impossible.\p"
	.string "You would need a POKéMON that knows\n"
	.string "how to DIVE…\p"
	.string "Perhaps if you went out to MOSSDEEP\n"
	.string "CITY…\p"
	.string "A lot of divers live out there, so\n"
	.string "someone might teach you…$"

SlateportCity_Harbor_Text_WontBeLongBeforeWeFinishFerry::
# 78 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Oh, yes. MR. BRINEY came to\n"
	.string "our SHIPYARD.\p"
	.string "It won't be long now before we finish\n"
	.string "making the ferry!$"

SlateportCity_Harbor_Text_FinishedMakingFerry::
# 82 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: {PLAYER}{KUN}!\p"
	.string "We finally finished making the ferry S.S.\n"
	.string "TIDAL!\p"
	.string "We couldn't have done it without your\n"
	.string "friend MR. BRINEY.\p"
	.string "Please go for a short cruise on it!$"

SlateportCity_Harbor_Text_WouldYouTradeScanner::
# 86 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Oh? {PLAYER}{KUN}, that item\n"
	.string "you have…\p"
	.string "That's a SCANNER! That would sure help\n"
	.string "us on our explorations.\p"
	.string "{PLAYER}{KUN}, would you trade your\n"
	.string "SCANNER for something?\p"
	.string "Like, say, a DEEPSEATOOTH or a\n"
	.string "DEEPSEASCALE that I have?$"

SlateportCity_Harbor_Text_IfYouWantToTradeLetMeKnow::
# 90 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Are you certain? It's\n"
	.string "useless to you, {PLAYER}{KUN}…\p"
	.string "Well, okay, then. If you want to trade\n"
	.string "your SCANNER, let me know.$"

SlateportCity_Harbor_Text_TradeForDeepSeaTooth::
# 94 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: So you'll trade it for my\n"
	.string "DEEPSEATOOTH?$"

SlateportCity_Harbor_Text_TradeForDeepSeaScale::
# 98 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: So you'll trade it for my\n"
	.string "DEEPSEASCALE?$"

SlateportCity_Harbor_Text_WhichOneDoYouWant::
# 102 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Which one do you want?$"

SlateportCity_Harbor_Text_HandedScannerToStern::
# 106 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "{PLAYER} handed the SCANNER to CAPT.\n"
	.string "STERN.$"

SlateportCity_Harbor_Text_ThisWillHelpResearch::
# 110 "data/maps/SlateportCity_Harbor/scripts.pory"
	.string "CAPT. STERN: Thanks, {PLAYER}{KUN}! This\n"
	.string "will help our research a lot!$"
