FallarborTown_BattleTentLobby_MapScripts::
# 2 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FallarborTown_BattleTentLobby_OnFrame
# 3 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, FallarborTown_BattleTentLobby_OnWarp
	.byte 0


FallarborTown_BattleTentLobby_Text_MakeThinkImJustKid::
# 7 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	.string "Fufufufufu.\p"
	.string "I'm going to make everyone think I'm\n"
	.string "just a kid and let them play down.\p"
	.string "Then, I'll shock them and grab the title!$"

FallarborTown_BattleTentLobby_Text_FallarborTentMyFavorite::
# 11 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	.string "You know how BATTLE TENTS offer\n"
	.string "different events in different towns?\p"
	.string "My favorite is definitely the BATTLE\n"
	.string "TENT in FALLARBOR TOWN.\p"
	.string "I think it's fantastic how TRAINERS try\n"
	.string "to win with all their faith in\l"
	.string "their POKéMON.$"

FallarborTown_BattleTentLobby_Text_CameToCampOut::
# 15 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	.string "I heard something about some tent, so I\n"
	.string "came to camp out.\p"
	.string "I didn't know that tents these days are\n"
	.string "so luxurious!\p"
	.string "Since I'm here, I may as well try my hand\n"
	.string "at battling!$"

FallarborTown_BattleTentLobby_Text_ScottLookingForSomeone::
# 19 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	.string "SCOTT: Hi, {PLAYER}{KUN}! So you came out\n"
	.string "to this BATTLE TENT!\p"
	.string "The people in these parts tend to be\n"
	.string "easygoing and laid-back.\p"
	.string "But, you see, what I'm looking for are\n"
	.string "people with…\p"
	.string "How should I say this?\p"
	.string "Someone bursting with the desire and\n"
	.string "the drive to win.\p"
	.string "If there were a TRAINER like that, I'd\n"
	.string "immediately…\p"
	.string "Whoops! Never mind! Keep working at it!$"

FallarborTown_BattleTentLobby_Text_ScottMakeChallenge::
# 23 "data/maps/FallarborTown_BattleTentLobby/scripts.pory"
	.string "SCOTT: Instead of wasting your time\n"
	.string "with the likes of me, why not\l"
	.string "make a challenge?$"
