PokemonLeague_AgathasRoom_MapScripts::
# 2 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_AgathasRoom_OnResume
# 3 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_AgathasRoom_OnLoad
# 4 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_AgathasRoom_OnWarp
# 5 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_AgathasRoom_OnFrame
	.byte 0


PokemonLeague_AgathasRoom_Text_Intro::
# 9 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	.string "I am AGATHA of the ELITE FOUR.\p"
	.string "I hear OAK's taken a lot of interest in\n"
	.string "you, child.\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago. He's a shadow\n"
	.string "of his former self.\p"
	.string "Now he just wants to fiddle with his\n"
	.string "POKDEX.\p"
	.string "He's wrong. POKMON are for battling!\p"
	.string "{PLAYER}! I'll show you how a real\n"
	.string "TRAINER battles!{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_AgathasRoom_Text_RematchIntro::
# 13 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	.string "I am AGATHA of the ELITE FOUR.\p"
	.string "You're the child that OAK's taken under\n"
	.string "his wing, aren't you?\p"
	.string "That old duff was once tough and\n"
	.string "handsome.\p"
	.string "But that was decades ago. He's a shadow\n"
	.string "of his former self.\p"
	.string "Now he just wants to fiddle with his\n"
	.string "POKDEX.\p"
	.string "He's wrong. POKMON are for battling!\p"
	.string "{PLAYER}! I'll show you how a real\n"
	.string "TRAINER battles!{PLAY_BGM}{MUS_RG_GYM}$"

PokemonLeague_AgathasRoom_Text_Defeat::
# 17 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	.string "Oh, my! You're something special, child!$"

PokemonLeague_AgathasRoom_Text_PostBattle::
# 21 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	.string "You win!\p"
	.string "I see what the old duff sees in you now.\p"
	.string "I have nothing else to say. Run along\n"
	.string "now, child!$"
