PokemonLeague_AgathasRoom_MapScripts::
# 2 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_AgathasRoom_OnResume
# 3 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_AgathasRoom_OnLoad
# 4 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_AgathasRoom_OnWarp
# 5 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_AgathasRoom_OnFrame
	.byte 0


PokemonLeague_AgathasRoom_MapScripts::
# 9 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, PokemonLeague_AgathasRoom_OnResume
# 10 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, PokemonLeague_AgathasRoom_OnLoad
# 11 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, PokemonLeague_AgathasRoom_OnWarp
# 12 "data/maps/PokemonLeague_AgathasRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PokemonLeague_AgathasRoom_OnFrame
	return

