AquaHideout_B2F_MapScripts::
	.byte 0


AquaHideout_B2F_EventScript_Grunt4::
# 5 "data/maps/AquaHideout_B2F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_4, AquaHideout_B2F_Text_Grunt4Intro, AquaHideout_B2F_Text_Grunt4Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/AquaHideout_B2F/scripts.pory"
	msgbox AquaHideout_B2F_Text_Grunt4PostBattle
	return


AquaHideout_B2F_EventScript_Grunt6::
# 10 "data/maps/AquaHideout_B2F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_6, AquaHideout_B2F_Text_Grunt6Intro, AquaHideout_B2F_Text_Grunt6Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/AquaHideout_B2F/scripts.pory"
	msgbox AquaHideout_B2F_Text_Grunt6PostBattle
	return


AquaHideout_B2F_EventScript_Grunt8::
# 15 "data/maps/AquaHideout_B2F/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_AQUA_HIDEOUT_8, AquaHideout_B2F_Text_Grunt8Intro, AquaHideout_B2F_Text_Grunt8Defeat, Text_NotEnoughMonsForDoubleBattle
# 16 "data/maps/AquaHideout_B2F/scripts.pory"
	msgbox AquaHideout_B2F_Text_Grunt8PostBattle
	return


AquaHideout_B2F_EventScript_Matt::
# 20 "data/maps/AquaHideout_B2F/scripts.pory"
	trainerbattle_double TRAINER_MATT, AquaHideout_B2F_Text_MattIntro, AquaHideout_B2F_Text_MattDefeat, Text_NotEnoughMonsForDoubleBattle
# 21 "data/maps/AquaHideout_B2F/scripts.pory"
	msgbox AquaHideout_B2F_Text_MattPostBattle
	return


AquaHideout_B2F_EventScript_MattNoticePlayer::
	end


AquaHideout_B2F_Text_Grunt4Defeat::
# 29 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt4Defeat$"

AquaHideout_B2F_Text_Grunt4Intro::
# 33 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt4Intro$"

AquaHideout_B2F_Text_Grunt4PostBattle::
# 37 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt4PostBattle$"

AquaHideout_B2F_Text_Grunt6Defeat::
# 41 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt6Defeat$"

AquaHideout_B2F_Text_Grunt6Intro::
# 45 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt6Intro$"

AquaHideout_B2F_Text_Grunt6PostBattle::
# 49 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt6PostBattle$"

AquaHideout_B2F_Text_Grunt8Defeat::
# 53 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt8Defeat$"

AquaHideout_B2F_Text_Grunt8Intro::
# 57 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt8Intro$"

AquaHideout_B2F_Text_Grunt8PostBattle::
# 61 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_Grunt8PostBattle$"

AquaHideout_B2F_Text_MattDefeat::
# 65 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_MattDefeat$"

AquaHideout_B2F_Text_MattIntro::
# 69 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_MattIntro$"

AquaHideout_B2F_Text_MattPostBattle::
# 73 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Placeholder text for\n"
	.string "AquaHideout_B2F_Text_MattPostBattle$"

AquaHideout_B2F_Text_OurBossGotThroughHisPreparations::
# 77 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Hehehe!\p"
	.string "While I was toying with you, our BOSS\n"
	.string "got through his preparations!$"
