AquaHideout_B2F_MapScripts::
# 2 "data/maps/AquaHideout_B2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_B2F_OnTransition
	.byte 0


AquaHideout_B2F_MapScripts::
# 6 "data/maps/AquaHideout_B2F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, AquaHideout_B2F_OnTransition
	return


AquaHideout_B2F_Text_MattIntro::
# 10 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Hehehe…\p"
	.string "Got here already, did you? We\n"
	.string "underestimated you!\p"
	.string "But this is it!\p"
	.string "I'm a cut above the GRUNTS you've seen\n"
	.string "so far.\p"
	.string "I'm not stalling for time. I'm going to\n"
	.string "pulverize you!$"

AquaHideout_B2F_Text_MattDefeat::
# 14 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Hehehe… So, I lost, too…$"

AquaHideout_B2F_Text_OurBossGotThroughHisPreparations::
# 18 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Hehehe!\p"
	.string "While I was toying with you, our BOSS\n"
	.string "got through his preparations!$"

AquaHideout_B2F_Text_MattPostBattle::
# 22 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Hehehe!\p"
	.string "Our BOSS has already gone on his way to\n"
	.string "some cave under the sea!\p"
	.string "If you're going to give chase, you'd\n"
	.string "better search the big, wide sea beyond\l"
	.string "LILYCOVE.\p"
	.string "But will you find it then? Hehehe!$"

AquaHideout_B2F_Text_Grunt4Intro::
# 26 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Wahahah, I grew weary of waiting! You\n"
	.string "owe me a battle, too!$"

AquaHideout_B2F_Text_Grunt4Defeat::
# 30 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Tired of waiting… Lost and dazed…$"

AquaHideout_B2F_Text_Grunt4PostBattle::
# 34 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "BOSS… Is this good enough?$"

AquaHideout_B2F_Text_Grunt6Intro::
# 38 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "Warp panels, the HIDEOUT's pride and\n"
	.string "joy!\p"
	.string "You're clueless about where you are,\n"
	.string "aren't you?\p"
	.string "Fluster and tire out the enemy, then\n"
	.string "lower the boom! That's our plan!$"

AquaHideout_B2F_Text_Grunt6Defeat::
# 42 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "What's wrong with you? You're not tired\n"
	.string "at all!$"

AquaHideout_B2F_Text_Grunt6PostBattle::
# 46 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "That reminds me… I can't remember where\n"
	.string "I put the MASTER BALL.\p"
	.string "If I fail to guard it, our BOSS will chew\n"
	.string "me out…$"

AquaHideout_B2F_Text_Grunt8Intro::
# 50 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "When I joined TEAM AQUA, the first thing\n"
	.string "I had to learn was how these\l"
	.string "warp panels connected.$"

AquaHideout_B2F_Text_Grunt8Defeat::
# 54 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "I was too occupied thinking about the\n"
	.string "warp panels…$"

AquaHideout_B2F_Text_Grunt8PostBattle::
# 58 "data/maps/AquaHideout_B2F/scripts.pory"
	.string "I'll have to learn about how I can\n"
	.string "battle more effectively…$"
