LavaridgeTown_Gym_1F_MapScripts::
# 2 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LavaridgeTown_Gym_1F_OnTransition
	.byte 0


LavaridgeTown_Gym_1F_Text_GymGuideAdvice::
# 6 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Hey, how's it going, CHAMPION- bound\n"
	.string "{PLAYER}?\p"
	.string "LAVARIDGE's GYM LEADER FLANNERY uses\n"
	.string "FIRE-type POKéMON.\p"
	.string "Her passion for POKéMON burns stronger\n"
	.string "and hotter than a volcano.\p"
	.string "Don't get too close to her--you'll burn!\n"
	.string "Hose her down with water and then\l"
	.string "go for it!$"

LavaridgeTown_Gym_1F_Text_GymGuidePostVictory::
# 10 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Yow! That was a scorching-hot battle!$"

LavaridgeTown_Gym_1F_Text_ColeIntro::
# 14 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Owowowowow! Yikes, it's hot!$"

LavaridgeTown_Gym_1F_Text_ColeDefeat::
# 18 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "I'm blinded by sweat in my eyes…$"

LavaridgeTown_Gym_1F_Text_ColePostBattle::
# 22 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Being buried in hot sand promotes\n"
	.string "circulation.\p"
	.string "It's effective for healing pain in your\n"
	.string "joints.$"

LavaridgeTown_Gym_1F_Text_AxleIntro::
# 26 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "I'm trying to relieve my stress. Don't\n"
	.string "come along and stress me out!$"

LavaridgeTown_Gym_1F_Text_AxleDefeat::
# 30 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "I hope FLANNERY flames you good!$"

LavaridgeTown_Gym_1F_Text_AxlePostBattle::
# 34 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Haaah… Whew…\p"
	.string "If you spend too much time buried in\n"
	.string "hot sand, it tuckers you out…$"

LavaridgeTown_Gym_B1F_Text_KeeganIntro::
# 38 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "You must be getting tired by now. You'd\n"
	.string "like to rest in the hot sand,\l"
	.string "wouldn't you?\p"
	.string "But you should know that maintaining\n"
	.string "your willpower is an important ability\l"
	.string "for all TRAINERS.$"

LavaridgeTown_Gym_B1F_Text_KeeganDefeat::
# 42 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Play with fire, and be burned…$"

LavaridgeTown_Gym_B1F_Text_KeeganPostBattle::
# 46 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Your skill is real… But our LEADER\n"
	.string "FLANNERY is strong.\p"
	.string "If you don't watch yourself, you'll be\n"
	.string "burned seriously.$"

LavaridgeTown_Gym_1F_Text_GeraldIntro::
# 50 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Can your POKéMON withstand 392-degree\n"
	.string "heat?$"

LavaridgeTown_Gym_1F_Text_GeraldDefeat::
# 54 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "It didn't burn hotly enough…$"

LavaridgeTown_Gym_1F_Text_GeraldPostBattle::
# 58 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "The temperature of magma is 392\n"
	.string "degrees.\p"
	.string "Your POKéMON beat me, so they should\n"
	.string "easily survive in magma.$"

LavaridgeTown_Gym_1F_Text_DanielleIntro::
# 62 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Um… Okay, I'll battle with you.$"

LavaridgeTown_Gym_1F_Text_DanielleDefeat::
# 66 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Oh, but you're too strong.$"

LavaridgeTown_Gym_1F_Text_DaniellePostBattle::
# 70 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "I'm going to be a pretty and strong\n"
	.string "TRAINER just like FLANNERY.$"

LavaridgeTown_Gym_B1F_Text_JaceIntro::
# 74 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Come on, get with it! Let's go before my\n"
	.string "feelings cool!$"

LavaridgeTown_Gym_B1F_Text_JaceDefeat::
# 78 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "It's so hot, and yet my heart is\n"
	.string "clutched by ice…$"

LavaridgeTown_Gym_B1F_Text_JacePostBattle::
# 82 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "The way the battling spirit burns within\n"
	.string "you, you may stand a chance\l"
	.string "against our LEADER.$"

LavaridgeTown_Gym_B1F_Text_JeffIntro::
# 86 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "See how the flames blaze wildly? They\n"
	.string "flare in anticipation of my win!$"

LavaridgeTown_Gym_B1F_Text_JeffDefeat::
# 90 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Something didn't go right.$"

LavaridgeTown_Gym_B1F_Text_JeffPostBattle::
# 94 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Well, so what? I say so what? I can walk\n"
	.string "on hot coals barefoot!\p"
	.string "…Don't even think about trying it!$"

LavaridgeTown_Gym_B1F_Text_EliIntro::
# 98 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "As much as I love mountains, I\n"
	.string "especially love volcanoes.$"

LavaridgeTown_Gym_B1F_Text_EliDefeat::
# 102 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Well, it seems to me I lost without ever\n"
	.string "being in control.$"

LavaridgeTown_Gym_B1F_Text_EliPostBattle::
# 106 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "I stay here because I became a fan of\n"
	.string "FLANNERY's power.\p"
	.string "Hehehehe.$"

LavaridgeTown_Gym_1F_Text_FlanneryIntro::
# 110 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Welcome… No, wait.\p"
	.string "Puny TRAINER, how good to see you've\n"
	.string "made it here!\p"
	.string "I have been entrusted with the… No,\n"
	.string "wait.\p"
	.string "I am FLANNERY, and I'm the GYM LEADER\n"
	.string "here!\p"
	.string "Uh… Dare not underestimate me, though\l"
	.string "I have been LEADER only a short time!\p"
	.string "With skills inherited from my grand-\n"
	.string "father, I shall, uh…demonstrate the\l"
	.string "hot moves we have honed on this land!$"

LavaridgeTown_Gym_1F_Text_FlanneryDefeat::
# 114 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Oh… I guess I was trying too hard…\p"
	.string "I… I've only recently become a GYM\n"
	.string "LEADER.\p"
	.string "I tried too hard to be someone I'm not.\p"
	.string "I have to do things my natural way. If I\n"
	.string "don't, my POKéMON will be confused.\p"
	.string "Thanks for teaching me that. For that,\n"
	.string "you deserve this.$"

LavaridgeTown_Gym_1F_Text_ReceivedHeatBadge::
# 118 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "{PLAYER} received the HEAT BADGE\n"
	.string "from FLANNERY.$"

LavaridgeTown_Gym_1F_Text_ExplainHeatBadgeTakeThis::
# 122 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "If you have a HEAT BADGE, all POKéMON\n"
	.string "up to Level 50, even those you get in\l"
	.string "trades from other people, will obey\l"
	.string "you completely.\p"
	.string "And, it lets POKéMON use the HM move\n"
	.string "STRENGTH outside of battle.\p"
	.string "This is a token of my appreciation.\n"
	.string "Don't be shy about taking it!$"

LavaridgeTown_Gym_1F_Text_ExplainOverheat::
# 126 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "That TM50 contains OVERHEAT.\p"
	.string "That move inflicts serious damage on\n"
	.string "the opponent.\p"
	.string "But it also sharply cuts the SP. ATK of\n"
	.string "the POKéMON using it. It might not\l"
	.string "be suitable for longer battles.$"

LavaridgeTown_Gym_1F_Text_RegisteredFlannery::
# 130 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Registered GYM LEADER FLANNERY in the\n"
	.string "POKéNAV.$"

LavaridgeTown_Gym_1F_Text_FlanneryPostBattle::
# 134 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Your power reminds me of someone…\p"
	.string "Oh! I know! You battle like NORMAN, the\n"
	.string "GYM LEADER of PETALBURG.$"

LavaridgeTown_Gym_1F_Text_GymStatue::
# 138 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "LAVARIDGE TOWN POKéMON GYM$"

LavaridgeTown_Gym_1F_Text_GymStatueCertified::
# 142 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "LAVARIDGE TOWN POKéMON GYM\p"
	.string "FLANNERY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

LavaridgeTown_Gym_1F_Text_FlanneryPreRematch::
# 146 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "FLANNERY: Losing a battle isn't going\n"
	.string "to deflate me.\p"
	.string "I love POKéMON. I love to battle.\l"
	.string "And… I love this GYM!\p"
	.string "Let's exchange superhot moves in\n"
	.string "another battle!$"

LavaridgeTown_Gym_1F_Text_FlanneryRematchDefeat::
# 150 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "Whew! On the verge of eruption!$"

LavaridgeTown_Gym_1F_Text_FlanneryPostRematch::
# 154 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "FLANNERY: I lost the match, but I'm\n"
	.string "completely satisfied.\p"
	.string "It's not often I get to enjoy a battle\n"
	.string "this heated.\p"
	.string "Let's have another one like this again\n"
	.string "sometime!$"

LavaridgeTown_Gym_1F_Text_FlanneryRematchNeedTwoMons::
# 158 "data/maps/LavaridgeTown_Gym_1F/scripts.pory"
	.string "FLANNERY: Losing a battle isn't going\n"
	.string "to deflate me.\p"
	.string "I love POKéMON. I love to battle.\l"
	.string "And… I love this GYM!\p"
	.string "Let's exchange superhot moves in\n"
	.string "another battle!\p"
	.string "Oh, wait. Do you only have one POKéMON\n"
	.string "that can battle?\p"
	.string "I hate to say this, but when you come\n"
	.string "see me, bring at least two POKéMON.$"
