VermilionCity_House2_MapScripts::
	.byte 0


VermilionCity_House2_Text_DoYouHaveMonWantToTradeForMyMon::
# 5 "data/maps/VermilionCity_House2/scripts.pory"
	.string "Hi! Do you have a {STR_VAR_1}?\p"
	.string "Want to trade it for my {STR_VAR_2}?$"

VermilionCity_House2_Text_ThatsTooBad::
# 9 "data/maps/VermilionCity_House2/scripts.pory"
	.string "That's too bad.$"

VermilionCity_House2_Text_ThisIsNoMon::
# 13 "data/maps/VermilionCity_House2/scripts.pory"
	.string "…This is no {STR_VAR_1}.\p"
	.string "If you get one, please trade it to me!$"

VermilionCity_House2_Text_ThankYou::
# 17 "data/maps/VermilionCity_House2/scripts.pory"
	.string "Thank you!$"

VermilionCity_House2_Text_HowIsMyOldMon::
# 21 "data/maps/VermilionCity_House2/scripts.pory"
	.string "How is my old {STR_VAR_2}?\p"
	.string "My {STR_VAR_1} is doing great!$"
