CeladonCity_MapScripts::
# 2 "data/maps/CeladonCity/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, CeladonCity_OnTransition
	.byte 0


CeladonCity_Text_GotMyKoffingInCinnabar::
# 6 "data/maps/CeladonCity/scripts.pory"
	.string "I got my KOFFING in CINNABAR.\p"
	.string "It's usually nice, but it breathes\n"
	.string "poison when it's angry.$"

CeladonCity_Text_GymIsGreatFullOfWomen::
# 10 "data/maps/CeladonCity/scripts.pory"
	.string "Heheh! This GYM is great! It's full of\n"
	.string "women!$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
# 14 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON takes pride in its efforts to\n"
	.string "keep the city beautiful.\p"
	.string "That's why the new GAME CORNER is bad\n"
	.string "for our city's image.$"

CeladonCity_Text_BlewItAllAtSlots::
# 18 "data/maps/CeladonCity/scripts.pory"
	.string "Moan I blew it all at the slots!\p"
	.string "I knew I should have cashed in my COINS\n"
	.string "for prizes!$"

CeladonCity_Text_MyTrustedPalPoliwrath::
# 22 "data/maps/CeladonCity/scripts.pory"
	.string "This is my trusted pal, POLIWRATH.\p"
	.string "It evolved from a POLIWHIRL when I\n"
	.string "used a WATER STONE.$"

CeladonCity_Text_Poliwrath::
# 26 "data/maps/CeladonCity/scripts.pory"
	.string "POLIWRATH: Ribi ribit!$"

CeladonCity_Text_GetLostOrIllPunchYou::
# 30 "data/maps/CeladonCity/scripts.pory"
	.string "What are you staring at? Get lost, or\n"
	.string "I'll punch you.$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
# 34 "data/maps/CeladonCity/scripts.pory"
	.string "Keep out of TEAM ROCKET's way!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
# 38 "data/maps/CeladonCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "X ACCURACY boosts the accuracy of\n"
	.string "techniques.\p"
	.string "DIRE HIT jacks up the likelihood of\n"
	.string "critical hits.\p"
	.string "Get your items at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_CitySign::
# 42 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON CITY The City of Rainbow\n"
	.string "Dreams$"

CeladonCity_Text_GymSign::
# 46 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON CITY POKMON GYM LEADER: ERIKA\l"
	.string "The Nature-Loving Princess!$"

CeladonCity_Text_MansionSign::
# 50 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON MANSION$"

CeladonCity_Text_DeptStoreSign::
# 54 "data/maps/CeladonCity/scripts.pory"
	.string "Find what you need at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
# 58 "data/maps/CeladonCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "GUARD SPEC. protects POKMON from\n"
	.string "status-reduction moves during\l"
	.string "battle.\p"
	.string "Get your items at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_PrizeExchangeSign::
# 62 "data/maps/CeladonCity/scripts.pory"
	.string "COINS exchanged for prizes! PRIZE\n"
	.string "EXCHANGE$"

CeladonCity_Text_GameCornerSign::
# 66 "data/maps/CeladonCity/scripts.pory"
	.string "ROCKET GAME CORNER The playground for\n"
	.string "grown-ups!$"

CeladonCity_Text_ScaldedTongueOnTea::
# 70 "data/maps/CeladonCity/scripts.pory"
	.string "Aaaagh, ow I scalded my tongue!\p"
	.string "This nice old lady in the MANSION gave\n"
	.string "me some TEA.\p"
	.string "But it was boiling hot! Gotta cool it to\n"
	.string "drink it.$"

Text_SoftboiledTeach::
# 74 "data/maps/CeladonCity/scripts.pory"
	.string "Hello, there!\p"
	.string "I've seen you about, but I never had a\n"
	.string "chance to chat.\p"
	.string "It must be good luck that brought us\n"
	.string "together finally.\p"
	.string "I'd like to celebrate by teaching you\n"
	.string "the move SOFTBOILED.$"

Text_SoftboiledDeclined::
# 78 "data/maps/CeladonCity/scripts.pory"
	.string "I'll always be keeping an eye out for\n"
	.string "you.\p"
	.string "I hope we can chat again.$"

Text_SoftboiledWhichMon::
# 82 "data/maps/CeladonCity/scripts.pory"
	.string "So, who's the POKMON that gets the\n"
	.string "chance to learn SOFTBOILED?$"

Text_SoftboiledTaught::
# 86 "data/maps/CeladonCity/scripts.pory"
	.string "I wish you the best of luck!$"

CeladonCity_Text_SomeoneStoleSilphScope::
# 90 "data/maps/CeladonCity/scripts.pory"
	.string "Oh, what am I to do\p"
	.string "Someone stole our SILPH SCOPE.\p"
	.string "The thief came running this way, I'm\n"
	.string "sure of it.\p"
	.string "But I lost sight of him! Where'd he go?$"
