CeladonCity_MapScripts::
	.byte 0


CeladonCity_EventScript_Boy::
# 5 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_ScaldedTongueOnTea, MSGBOX_NPC
	end


CeladonCity_EventScript_CitySign::
# 10 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_CitySign, MSGBOX_SIGN
	end


CeladonCity_EventScript_DeptStoreSign::
# 15 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_DeptStoreSign, MSGBOX_SIGN
	end


CeladonCity_EventScript_FatMan::
	end


CeladonCity_EventScript_GameCornerSign::
# 24 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GameCornerSign, MSGBOX_SIGN
	end


CeladonCity_EventScript_GymSign::
# 31 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GymSign, MSGBOX_SIGN
	end


CeladonCity_EventScript_LittleGirl::
# 37 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GotMyKoffingInCinnabar, MSGBOX_NPC
	end


CeladonCity_EventScript_MansionSign::
# 42 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_MansionSign, MSGBOX_SIGN
	end


CeladonCity_EventScript_OldMan1::
	end


CeladonCity_EventScript_OldMan2::
# 51 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_BlewItAllAtSlots, MSGBOX_NPC
	end


CeladonCity_EventScript_Poliwrath::
	end


CeladonCity_EventScript_PrizeExchangeSign::
# 60 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_PrizeExchangeSign, MSGBOX_SIGN
	end


CeladonCity_EventScript_RocketGrunt1::
# 65 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_KeepOutOfTeamRocketsWay, MSGBOX_NPC
	end


CeladonCity_EventScript_RocketGrunt2::
# 70 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GetLostOrIllPunchYou, MSGBOX_NPC
	end


CeladonCity_EventScript_SilphCoScientist::
# 75 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_SomeoneStoleSilphScope, MSGBOX_NPC
	end


CeladonCity_EventScript_TrainerTips1::
# 80 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_ExplainXAccuracyDireHit, MSGBOX_SIGN
	end


CeladonCity_EventScript_TrainerTips2::
# 85 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GuardSpecProtectsFromStatus, MSGBOX_SIGN
	end


CeladonCity_EventScript_Woman::
# 90 "data/maps/CeladonCity/scripts.pory"
	msgbox CeladonCity_Text_GameCornerIsBadForCitysImage, MSGBOX_NPC
	end


CeladonCity_Text_DeptStoreSign::
# 94 "data/maps/CeladonCity/scripts.pory"
	.string "Find what you need at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_PrizeExchangeSign::
# 98 "data/maps/CeladonCity/scripts.pory"
	.string "COINS exchanged for prizes! PRIZE\n"
	.string "EXCHANGE$"

CeladonCity_Text_GameCornerSign::
# 102 "data/maps/CeladonCity/scripts.pory"
	.string "ROCKET GAME CORNER The playground for\n"
	.string "grown-ups!$"

CeladonCity_Text_CitySign::
# 106 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON CITY The City of Rainbow\n"
	.string "Dreams$"

CeladonCity_Text_GuardSpecProtectsFromStatus::
# 110 "data/maps/CeladonCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "GUARD SPEC. protects POKéMON from\n"
	.string "status-reduction moves during\l"
	.string "battle.\p"
	.string "Get your items at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_GymSign::
# 114 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON CITY POKéMON GYM LEADER:\n"
	.string "ERIKA\l"
	.string "The Nature-Loving Princess!$"

CeladonCity_Text_ExplainXAccuracyDireHit::
# 118 "data/maps/CeladonCity/scripts.pory"
	.string "TRAINER TIPS\p"
	.string "X ACCURACY boosts the accuracy of\n"
	.string "techniques.\p"
	.string "DIRE HIT jacks up the likelihood of\n"
	.string "critical hits.\p"
	.string "Get your items at the CELADON DEPT.\n"
	.string "STORE!$"

CeladonCity_Text_MansionSign::
# 122 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON MANSION$"

CeladonCity_Text_ScaldedTongueOnTea::
# 126 "data/maps/CeladonCity/scripts.pory"
	.string "Aaaagh, ow…\n"
	.string "I scalded my tongue!\p"
	.string "This nice old lady in the MANSION\n"
	.string "gave me some TEA.\p"
	.string "But it was boiling hot!\n"
	.string "Gotta cool it to drink it.$"

CeladonCity_Text_GotMyKoffingInCinnabar::
# 130 "data/maps/CeladonCity/scripts.pory"
	.string "I got my KOFFING in CINNABAR.\p"
	.string "It's usually nice, but it breathes\n"
	.string "poison when it's angry.$"

CeladonCity_Text_BlewItAllAtSlots::
# 134 "data/maps/CeladonCity/scripts.pory"
	.string "Moan…\n"
	.string "I blew it all at the slots!\p"
	.string "I knew I should have cashed in my\n"
	.string "COINS for prizes!$"

CeladonCity_Text_KeepOutOfTeamRocketsWay::
# 138 "data/maps/CeladonCity/scripts.pory"
	.string "Keep out of TEAM ROCKET's way!$"

CeladonCity_Text_GetLostOrIllPunchYou::
# 142 "data/maps/CeladonCity/scripts.pory"
	.string "What are you staring at?\n"
	.string "Get lost, or I'll punch you.$"

CeladonCity_Text_SomeoneStoleSilphScope::
# 146 "data/maps/CeladonCity/scripts.pory"
	.string "Oh, what am I to do…\p"
	.string "Someone stole our SILPH SCOPE.\p"
	.string "The thief came running this way,\n"
	.string "I'm sure of it.\p"
	.string "But I lost sight of him!\n"
	.string "Where'd he go?$"

CeladonCity_Text_GameCornerIsBadForCitysImage::
# 150 "data/maps/CeladonCity/scripts.pory"
	.string "CELADON takes pride in its efforts\n"
	.string "to keep the city beautiful.\p"
	.string "That's why the new GAME CORNER is\n"
	.string "bad for our city's image.$"
