OldaleTown_Mart_MapScripts::
	.byte 0


OldaleTown_Mart_Text_PokeBallsAreSoldOut::
# 5 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "The clerk says they're all sold out. I\n"
	.string "can't buy any POK BALLS.$"

OldaleTown_Mart_Text_ImGoingToBuyPokeBalls::
# 9 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "I'm going to buy a bunch of POK BALLS\n"
	.string "and catch a bunch of POKMON!$"

OldaleTown_Mart_Text_RestoreHPWithPotion::
# 13 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "If a POKMON gets hurt and loses its HP\n"
	.string "and faints, it won't be able to battle.\p"
	.string "To prevent your POKMON from fainting,\n"
	.string "restore its HP with a POTION.$"
