OldaleTown_Mart_MapScripts::
	.byte 0


OldaleTown_Mart_EventScript_Boy::
# 5 "data/maps/OldaleTown_Mart/scripts.pory"
	msgbox OldaleTown_Mart_Text_RestoreHPWithPotion, MSGBOX_NPC
	end


OldaleTown_Mart_EventScript_Clerk::
	end


OldaleTown_Mart_EventScript_Woman::
	end


OldaleTown_Mart_Text_ImGoingToBuyPokeBalls::
# 17 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "I'm going to buy a bunch of POKé BALLS\n"
	.string "and catch a bunch of POKéMON!$"

OldaleTown_Mart_Text_RestoreHPWithPotion::
# 21 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "If a POKéMON gets hurt and loses its HP\n"
	.string "and faints, it won't be able to battle.\p"
	.string "To prevent your POKéMON from fainting,\n"
	.string "restore its HP with a POTION.$"
