OldaleTown_Mart_MapScripts::
	.byte 0


OldaleTown_Mart_MapScripts::
	return


OldaleTown_Mart_Text_PokeBallsAreSoldOut::
# 8 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "The clerk says they're all sold out. I\n"
	.string "can't buy any POKé BALLS.$"

OldaleTown_Mart_Text_ImGoingToBuyPokeBalls::
# 12 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "I'm going to buy a bunch of POKé BALLS\n"
	.string "and catch a bunch of POKéMON!$"

OldaleTown_Mart_Text_RestoreHPWithPotion::
# 16 "data/maps/OldaleTown_Mart/scripts.pory"
	.string "If a POKéMON gets hurt and loses its HP\n"
	.string "and faints, it won't be able to battle.\p"
	.string "To prevent your POKéMON from fainting,\n"
	.string "restore its HP with a POTION.$"
