ViridianCity_Mart_MapScripts::
# 2 "data/maps/ViridianCity_Mart/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, ViridianCity_Mart_OnLoad
# 3 "data/maps/ViridianCity_Mart/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, ViridianCity_Mart_OnFrame
	.byte 0


ViridianCity_Mart_Text_YouCameFromPallet::
# 7 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "Hey! You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
# 11 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "You know PROF. OAK, right?\p"
	.string "His order came in. Can I get you to take\n"
	.string "it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
# 15 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "{PLAYER} received OAK'S PARCEL from\n"
	.string "the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
# 19 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "Okay, thanks! Please say hi to PROF. OAK\n"
	.string "for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
# 23 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "This shop does good business in\n"
	.string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
# 27 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "I've got to buy some POTIONS.\p"
	.string "You never know when your POKéMON will\n"
	.string "need quick healing.$"
