ViridianCity_Mart_MapScripts::
	.byte 0


ViridianCity_Mart_EventScript_Clerk::
	end


ViridianCity_Mart_EventScript_Woman::
# 9 "data/maps/ViridianCity_Mart/scripts.pory"
	msgbox ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes, MSGBOX_NPC
	end


ViridianCity_Mart_EventScript_Youngster::
# 14 "data/maps/ViridianCity_Mart/scripts.pory"
	msgbox ViridianCity_Mart_Text_GotToBuySomePotions, MSGBOX_NPC
	end


ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
# 19 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "This shop does good business in\n"
	.string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
# 23 "data/maps/ViridianCity_Mart/scripts.pory"
	.string "I've got to buy some POTIONS.\p"
	.string "You never know when your POKéMON\n"
	.string "will need quick healing.$"
