AzaleaTown_MapScripts::
	.byte 0


AzaleaTown_EventScript_Sign1::
# 6 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_Sign1, MSGBOX_SIGN
	end


AzaleaTown_EventScript_Sign2::
# 15 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_Sign2, MSGBOX_SIGN
	end


AzaleaTown_EventScript_Sign3::
# 24 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_Sign3, MSGBOX_SIGN
	end


AzaleaTown_EventScript_Sign4::
# 33 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_Sign4, MSGBOX_SIGN
	end


AzaleaTown_EventScript_Gym5::
# 42 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_Gym5, MSGBOX_SIGN
	end


AzaleaTown_EventScript_SmithNPC1::
# 51 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC1, MSGBOX_NPC
	end


AzaleaTown_EventScript_SmithNPC2::
# 60 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC2, MSGBOX_NPC
	end


AzaleaTown_EventScript_SmithNPC3::
# 69 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC3, MSGBOX_NPC
	end


AzaleaTown_EventScript_SmithNPC4::
# 78 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC4, MSGBOX_NPC
	end


AzaleaTown_EventScript_SmithNPC5::
# 87 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC5, MSGBOX_NPC
	end


AzaleaTown_EventScript_SmithNPC6::
# 96 "data/maps/AzaleaTown/scripts.pory"
	msgbox AzaleaTown_Text_SmithNPC6, MSGBOX_NPC
	end


AzaleaTown_Text_Sign1::
# 10 "data/maps/AzaleaTown/scripts.pory"
	.string "AzaleaTown Sign 1$"

AzaleaTown_Text_Sign2::
# 19 "data/maps/AzaleaTown/scripts.pory"
	.string "AzaleaTown Sign 2$"

AzaleaTown_Text_Sign3::
# 28 "data/maps/AzaleaTown/scripts.pory"
	.string "AzaleaTown Sign 3$"

AzaleaTown_Text_Sign4::
# 37 "data/maps/AzaleaTown/scripts.pory"
	.string "AzaleaTown Sign 4$"

AzaleaTown_Text_Gym5::
# 46 "data/maps/AzaleaTown/scripts.pory"
	.string "Azalea Gym$"

AzaleaTown_Text_SmithNPC1::
# 55 "data/maps/AzaleaTown/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

AzaleaTown_Text_SmithNPC2::
# 64 "data/maps/AzaleaTown/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"

AzaleaTown_Text_SmithNPC3::
# 73 "data/maps/AzaleaTown/scripts.pory"
	.string "Never send a human to do a machine's\n"
	.string "job.$"

AzaleaTown_Text_SmithNPC4::
# 82 "data/maps/AzaleaTown/scripts.pory"
	.string "You hear that, Mr. Anderson? That is the\n"
	.string "sound of inevitability.$"

AzaleaTown_Text_SmithNPC5::
# 91 "data/maps/AzaleaTown/scripts.pory"
	.string "We're not here because we're free; we're\n"
	.string "here because we're not free.$"

AzaleaTown_Text_SmithNPC6::
# 100 "data/maps/AzaleaTown/scripts.pory"
	.string "It's the question that drives us, Neo.$"
