VermilionCity_Gym_MapScripts::
# 2 "data/maps/VermilionCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, VermilionCity_Gym_OnLoad
# 3 "data/maps/VermilionCity_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, VermilionCity_Gym_OnTransition
	.byte 0


VermilionCity_Gym_Text_LtSurgeIntro::
# 7 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Hey, kid! What do you think you're doing\n"
	.string "here?\p"
	.string "You won't live long in combat! Not with\n"
	.string "your puny power!\p"
	.string "I tell you, kid, electric POKMON saved me\n"
	.string "during the war!\p"
	.string "They zapped my enemies into paralysis!\p"
	.string "The same as I'll do to you!{PLAY_BGM}{MUS_RG_GYM}$"

VermilionCity_Gym_Text_LtSurgePostBattle::
# 11 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "A little word of advice, kid!\p"
	.string "Electricity is sure powerful!\p"
	.string "But, it's useless against GROUND- type\n"
	.string "POKMON!$"

VermilionCity_Gym_Text_ExplainThunderBadgeTakeThis::
# 15 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "The THUNDERBADGE cranks up your\n"
	.string "POKMON's SPEED!\p"
	.string "It also lets your POKMON FLY\n"
	.string "lightning-quick anytime, kid!\p"
	.string "You're special, kid! Take this!$"

VermilionCity_Gym_Text_ReceivedTM34FromLtSurge::
# 19 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "{PLAYER} received TM34 from LT.\n"
	.string "SURGE.$"

VermilionCity_Gym_Text_ExplainTM34::
# 23 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "TM34 contains SHOCK WAVE!\p"
	.string "Teach it to an ELECTRIC POKMON!$"

VermilionCity_Gym_Text_MakeRoomInYourBag::
# 27 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Yo, kid, make room in your BAG!$"

VermilionCity_Gym_Text_LtSurgeDefeat::
# 31 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Now that's a shocker!\p"
	.string "You're the real deal, kid!\p"
	.string "Fine, then, take the THUNDERBADGE!$"

VermilionCity_Gym_Text_TuckerIntro::
# 35 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "When I was in the Army, LT. SURGE was my\n"
	.string "strict CO.\p"
	.string "He was a hard taskmaster.$"

VermilionCity_Gym_Text_TuckerDefeat::
# 39 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Stop! You're very good!$"

VermilionCity_Gym_Text_TuckerPostBattle::
# 43 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "It's not easy opening that door.\p"
	.string "LT. SURGE was always famous for his\n"
	.string "cautious nature in the Army.$"

VermilionCity_Gym_Text_BailyIntro::
# 47 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "I'm a lightweight, but I'm good with\n"
	.string "electricity!\p"
	.string "That's why I joined this GYM.$"

VermilionCity_Gym_Text_BailyDefeat::
# 51 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Fried!$"

VermilionCity_Gym_Text_BailyPostBattle::
# 55 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Okay, I'll talk!\p"
	.string "LT. SURGE said he hid door switches\n"
	.string "inside something.$"

VermilionCity_Gym_Text_DwayneIntro::
# 59 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "This is no place for kids! Not even if\n"
	.string "you're good!$"

VermilionCity_Gym_Text_DwayneDefeat::
# 63 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Wow! Surprised me!$"

VermilionCity_Gym_Text_DwaynePostBattle::
# 67 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "LT. SURGE installed the traps in the GYM\n"
	.string "himself.\p"
	.string "He set up double locks everywhere. Let\n"
	.string "me give you a hint.\p"
	.string "When you open the first lock, the\n"
	.string "second lock is right next to it.$"

VermilionCity_Gym_Text_GymGuyAdvice::
# 71 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Yo! Champ in the making!\p"
	.string "LT. SURGE has a nickname.\p"
	.string "People refer to him as the Lightning\n"
	.string "American!\p"
	.string "He's an expert on electric POKMON.\p"
	.string "BIRD/WATER-type POKMON match poorly\n"
	.string "against the ELECTRIC type.\p"
	.string "Beware of paralysis, too.\p"
	.string "LT. SURGE is very cautious.\p"
	.string "He's locked himself in, so it won't be\n"
	.string "easy getting to him.$"

VermilionCity_Gym_Text_GymGuyPostVictory::
# 75 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Whew! That match was electric!$"

VermilionCity_Gym_Text_GymStatue::
# 79 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "VERMILION POKMON GYM LEADER: LT.\n"
	.string "SURGE\p"
	.string "WINNING TRAINERS: {RIVAL}$"

VermilionCity_Gym_Text_GymStatuePlayerWon::
# 83 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "VERMILION POKMON GYM LEADER: LT.\n"
	.string "SURGE\p"
	.string "WINNING TRAINERS: {RIVAL},\n"
	.string "{PLAYER}$"

VermilionCity_Gym_Text_NopeOnlyTrashHere::
# 87 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Nope! There's only trash here.$"

VermilionCity_Gym_Text_SwitchUnderTrashFirstLockOpened::
# 91 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Hey! There's a switch under the trash!\n"
	.string "Turn it on!\p"
	.string "The first electric lock opened!$"

VermilionCity_Gym_Text_AnotherSwitchInTrash::
# 95 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "\l"
	.string "\l"
	.string "$"

VermilionCity_Gym_Text_SecondLockOpened::
# 99 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "The second electric lock opened! The\n"
	.string "motorized door opened!$"

VermilionCity_Gym_Text_OnlyTrashLocksWereReset::
# 103 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Nope! There's only trash here.\p"
	.string "Hey! The electric locks were reset!$"
