VermilionCity_Gym_MapScripts::
	.byte 0


VermilionCity_Gym_EventScript_Baily::
# 5 "data/maps/VermilionCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_ENGINEER_BAILY, VermilionCity_Gym_Text_BailyIntro, VermilionCity_Gym_Text_BailyDefeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/VermilionCity_Gym/scripts.pory"
	msgbox VermilionCity_Gym_Text_BailyPostBattle
	return


VermilionCity_Gym_EventScript_Dwayne::
# 10 "data/maps/VermilionCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_SAILOR_DWAYNE, VermilionCity_Gym_Text_DwayneIntro, VermilionCity_Gym_Text_DwayneDefeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/VermilionCity_Gym/scripts.pory"
	msgbox VermilionCity_Gym_Text_DwaynePostBattle
	return


VermilionCity_Gym_EventScript_GymGuy::
	end


VermilionCity_Gym_EventScript_GymStatue::
# 21 "data/maps/VermilionCity_Gym/scripts.pory"
	msgbox VermilionCity_Gym_Text_GymStatue, MSGBOX_DEFAULT
	end


VermilionCity_Gym_EventScript_LtSurge::
	end


VermilionCity_Gym_EventScript_TrashCan1::
	end


VermilionCity_Gym_EventScript_TrashCan10::
	end


VermilionCity_Gym_EventScript_TrashCan11::
	end


VermilionCity_Gym_EventScript_TrashCan12::
	end


VermilionCity_Gym_EventScript_TrashCan13::
	end


VermilionCity_Gym_EventScript_TrashCan14::
	end


VermilionCity_Gym_EventScript_TrashCan15::
	end


VermilionCity_Gym_EventScript_TrashCan2::
	end


VermilionCity_Gym_EventScript_TrashCan3::
	end


VermilionCity_Gym_EventScript_TrashCan4::
	end


VermilionCity_Gym_EventScript_TrashCan5::
	end


VermilionCity_Gym_EventScript_TrashCan6::
	end


VermilionCity_Gym_EventScript_TrashCan7::
	end


VermilionCity_Gym_EventScript_TrashCan8::
	end


VermilionCity_Gym_EventScript_TrashCan9::
	end


VermilionCity_Gym_EventScript_Tucker::
# 136 "data/maps/VermilionCity_Gym/scripts.pory"
	trainerbattle_double TRAINER_GENTLEMAN_TUCKER, VermilionCity_Gym_Text_TuckerIntro, VermilionCity_Gym_Text_TuckerDefeat, Text_NotEnoughMonsForDoubleBattle
# 137 "data/maps/VermilionCity_Gym/scripts.pory"
	msgbox VermilionCity_Gym_Text_TuckerPostBattle
	return


VermilionCity_Gym_Text_GymStatue::
# 141 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "VERMILION POKéMON GYM LEADER: LT.\n"
	.string "SURGE\p"
	.string "WINNING TRAINERS: {RIVAL}$"

VermilionCity_Gym_Text_BailyDefeat::
# 146 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_BailyDefeat$"

VermilionCity_Gym_Text_BailyIntro::
# 150 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_BailyIntro$"

VermilionCity_Gym_Text_BailyPostBattle::
# 154 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_BailyPostBattle$"

VermilionCity_Gym_Text_DwayneDefeat::
# 158 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_DwayneDefeat$"

VermilionCity_Gym_Text_DwayneIntro::
# 162 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_DwayneIntro$"

VermilionCity_Gym_Text_DwaynePostBattle::
# 166 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_DwaynePostBattle$"

VermilionCity_Gym_Text_TuckerDefeat::
# 170 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_TuckerDefeat$"

VermilionCity_Gym_Text_TuckerIntro::
# 174 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_TuckerIntro$"

VermilionCity_Gym_Text_TuckerPostBattle::
# 178 "data/maps/VermilionCity_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "VermilionCity_Gym_Text_TuckerPostBattle$"
