Route12_NorthEntrance_1F_MapScripts::
	.byte 0


Route12_NorthEntrance_1F_EventScript_Guard::
# 5 "data/maps/Route12_NorthEntrance_1F/scripts.pory"
	msgbox Route12_NorthEntrance_1F_Text_LookoutSpotUpstairs, MSGBOX_NPC
	end


Route12_NorthEntrance_1F_Text_LookoutSpotUpstairs::
# 10 "data/maps/Route12_NorthEntrance_1F/scripts.pory"
	.string "There's a lookout spot upstairs.\n"
	.string "The view is magnificent.$"
