FuchsiaCity_SafariZone_Entrance_MapScripts::
	.byte 0


FuchsiaCity_SafariZone_Entrance_EventScript_EntryTriggerLeft::
	end


FuchsiaCity_SafariZone_Entrance_EventScript_EntryTriggerMid::
	end


FuchsiaCity_SafariZone_Entrance_EventScript_EntryTriggerRight::
	end


FuchsiaCity_SafariZone_Entrance_EventScript_InfoAttendant::
# 17 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	msgbox FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone, MSGBOX_YESNO
	end


FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
# 22 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Hi! Is it your first time here at\n"
	.string "the SAFARI ZONE?$"
