FuchsiaCity_SafariZone_Entrance_MapScripts::
# 2 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FuchsiaCity_SafariZone_Entrance_OnFrame
	.byte 0


FuchsiaCity_SafariZone_Entrance_Text_WelcomeToSafariZone::
# 6 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Welcome to the SAFARI ZONE!$"

FuchsiaCity_SafariZone_Entrance_Text_PlaySafariGameFor500::
# 10 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "For just ¥500, you can play the SAFARI\n"
	.string "GAME.\p"
	.string "You can roam the wide-open safari and\n"
	.string "catch what you like.\p"
	.string "Would you like to play?$"

FuchsiaCity_SafariZone_Entrance_Text_ThatllBe500WeOnlyUseSpecialBalls::
# 14 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "That'll be ¥500, please!\p"
	.string "We only use a special kind of POKé BALLS\n"
	.string "here.$"

FuchsiaCity_SafariZone_Entrance_Text_PlayerReceived30SafariBalls::
# 18 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "{PLAYER} received 30 SAFARI BALLS\n"
	.string "from the attendant.$"

FuchsiaCity_SafariZone_Entrance_Text_CallYouOnPAWhenYouRunOut::
# 22 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "We'll call you on the PA when you run out\n"
	.string "of time or SAFARI BALLS.\p"
	.string "Well, I'll wish you the best of luck!$"

FuchsiaCity_SafariZone_Entrance_Text_OkayPleaseComeAgain::
# 26 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Okay. Please come again!$"

FuchsiaCity_SafariZone_Entrance_Text_OopsNotEnoughMoney::
# 30 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Oops! Not enough money!$"

FuchsiaCity_SafariZone_Entrance_Text_GoingToLeaveSafariZoneEarly::
# 34 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Are you going to leave the SAFARI ZONE\n"
	.string "early?$"

FuchsiaCity_SafariZone_Entrance_Text_PleaseReturnSafariBalls::
# 38 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Please return any SAFARI BALLS you may\n"
	.string "have left.$"

FuchsiaCity_SafariZone_Entrance_Text_GoodLuck::
# 42 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Good luck!$"

FuchsiaCity_SafariZone_Entrance_Text_CatchFairShareComeAgain::
# 46 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Did you catch your fair share? Come\n"
	.string "again!$"

FuchsiaCity_SafariZone_Entrance_Text_FirstTimeAtSafariZone::
# 50 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Hi! Is it your first time here at the\n"
	.string "SAFARI ZONE?$"

FuchsiaCity_SafariZone_Entrance_Text_ExplainSafariZone::
# 54 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "The SAFARI ZONE actually has four\n"
	.string "zones in it.\p"
	.string "Each zone has different kinds of\n"
	.string "POKéMON, even some rare ones.\p"
	.string "Use the supplied SAFARI BALLS to catch\n"
	.string "them.\p"
	.string "You can also throw BAIT or ROCKS\n"
	.string "besides the SAFARI BALLS.\p"
	.string "If you throw BAIT, the POKéMON becomes\n"
	.string "less likely to flee, but\l"
	.string "harder to catch.\p"
	.string "If you throw ROCKS, the POKéMON\n"
	.string "becomes more likely to flee, but\l"
	.string "easier to catch.\p"
	.string "When you run out of time or SAFARI\n"
	.string "BALLS, it's game over for you!$"

FuchsiaCity_SafariZone_Entrance_Text_SorryYoureARegularHere::
# 58 "data/maps/FuchsiaCity_SafariZone_Entrance/scripts.pory"
	.string "Sorry, you're a regular here!$"
