Route2_ViridianForest_SouthEntrance_MapScripts::
	.byte 0


Route2_ViridianForest_SouthEntrance_EventScript_Woman1::
# 5 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze, MSGBOX_NPC
	end


Route2_ViridianForest_SouthEntrance_EventScript_Woman2::
# 10 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	msgbox Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite, MSGBOX_NPC
	end


Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
# 15 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	.string "Are you going to VIRIDIAN FOREST?\n"
	.string "It's a natural maze in there.\l"
	.string "Be careful you don't get lost.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
# 19 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	.string "RATTATA may be small, but don't\n"
	.string "underestimate its wicked bite.\p"
	.string "Have you caught one already?$"
