Route2_ViridianForest_SouthEntrance_MapScripts::
	.byte 0


Route2_ViridianForest_SouthEntrance_Text_ForestIsMaze::
# 5 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	.string "Are you going to VIRIDIAN FOREST? It's\n"
	.string "a natural maze in there.\l"
	.string "Be careful you don't get lost.$"

Route2_ViridianForest_SouthEntrance_Text_RattataHasWickedBite::
# 9 "data/maps/Route2_ViridianForest_SouthEntrance/scripts.pory"
	.string "RATTATA may be small, but don't\n"
	.string "underestimate its wicked bite.\p"
	.string "Have you caught one already?$"
