SaffronCity_PokemonTrainerFanClub_MapScripts::
	.byte 0


SaffronCity_PokemonTrainerFanClub_EventScript_BattleGirl::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_Beauty::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_BlackBelt::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_Gentleman::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_LittleGirl::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_Rocker::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_Woman::
	end


SaffronCity_PokemonTrainerFanClub_EventScript_Youngster::
	end

