SaffronCity_PokemonTrainerFanClub_MapScripts::
# 2 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, SaffronCity_PokemonTrainerFanClub_OnFrame
# 3 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SaffronCity_PokemonTrainerFanClub_OnTransition
	.byte 0


SaffronCity_PokemonTrainerFanClub_Text_HuhYou::
# 7 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Huh? You…$"

SaffronCity_PokemonTrainerFanClub_Text_YourePlayerWereYourFansNow::
# 11 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Are you maybe… … …\p"
	.string "You are! You are {PLAYER}!\p"
	.string "We were just talking about you!\p"
	.string "We were talking about how an incredibly\n"
	.string "good TRAINER appeared.\p"
	.string "And that someone is you! You're so cool!\p"
	.string "So, we decided that we'll become your\n"
	.string "FAN CLUB!\p"
	.string "We all hope you'll keep battling and\n"
	.string "show us how cool you are.\p"
	.string "That way, maybe other people will\n"
	.string "become fans just like me.$"

SaffronCity_PokemonTrainerFanClub_Text_AlwaysCheerForYou::
# 15 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I'll always be cheering for you!\p"
	.string "Go, {PLAYER}, go!$"

SaffronCity_PokemonTrainerFanClub_Text_IllAlwaysBelieveInYou::
# 19 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I'll always believe in you, {PLAYER}.\p"
	.string "Please show the others what you're like\n"
	.string "when you battle seriously.$"

SaffronCity_PokemonTrainerFanClub_Text_WasYourFanNotAnymore::
# 23 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I'm sorry. I was your fan before.\p"
	.string "But now, you seem to have lost the drive\n"
	.string "you had before.\p"
	.string "Lately, I think {STR_VAR_1} has been\n"
	.string "a lot cooler.$"

SaffronCity_PokemonTrainerFanClub_Text_EveryonesYourFanButICantBe::
# 27 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh! {PLAYER}!\p"
	.string "Everyone's been all excited about you\n"
	.string "recently.\p"
	.string "I can understand why. I know that\n"
	.string "you're strong.\p"
	.string "But, do you know what?\p"
	.string "Once I became {STR_VAR_1}'s fan, I\n"
	.string "can't just stop being a fan.$"

SaffronCity_PokemonTrainerFanClub_Text_TrainersCoolWhenBattling::
# 31 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I think TRAINERS are so cool when\n"
	.string "they're battling.\p"
	.string "Don't you think so, too?$"

SaffronCity_PokemonTrainerFanClub_Text_CanYouAutographShorts::
# 35 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh! It's {PLAYER}! Too cool!\p"
	.string "Oh! Oh, yeah!\p"
	.string "Can you autograph something? How\n"
	.string "about my shorts?$"

SaffronCity_PokemonTrainerFanClub_Text_CountingOnYou::
# 39 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "However hot it's been…\p"
	.string "And however cold it may get…\p"
	.string "I've always believed in, and worn,\n"
	.string "shorts!\p"
	.string "I'm counting on you to keep winning!\p"
	.string "I believe in you just as much as I\n"
	.string "believe in shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksMyHero::
# 43 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "BROCK's my hero! He's a man among men!\p"
	.string "Heheh, I got my mom to do something for\n"
	.string "me.\p"
	.string "I got her to embroider “BROCK” on my\n"
	.string "shorts!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksFanToBitterEnd::
# 47 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "… …\p"
	.string "… … I'm BROCK's fan!\p"
	.string "Even if I were his only fan, I swear it\n"
	.string "on my rock-hard will,\l"
	.string "and on my shorts!\p"
	.string "I'll be his fan to the bitter end!$"

SaffronCity_PokemonTrainerFanClub_Text_BrocksLastWordOnCool::
# 51 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "BROCK's the last word on cool, end of\n"
	.string "story!\p"
	.string "Now there's a guy who I want to be like!$"

SaffronCity_PokemonTrainerFanClub_Text_HadPleasureOfWatchingYouBattle::
# 55 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "{PLAYER}, I've had the pleasure of\n"
	.string "watching you battle.\p"
	.string "It brings back sweet memories of my own\n"
	.string "long-lost youth.\p"
	.string "May you continue to find success. You\n"
	.string "have a fan in me!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverSeenTrainerOfYourMagnificence::
# 59 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I have journeyed far and wide across\n"
	.string "the lands.\p"
	.string "But never have I seen a TRAINER of your\n"
	.string "magnificence.\p"
	.string "Take courage in your abilities and keep\n"
	.string "battling on!\p"
	.string "Make that a promise to me, my young\n"
	.string "idol!$"

SaffronCity_PokemonTrainerFanClub_Text_HmmAndYouAre::
# 63 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Hmm… And you are?\p"
	.string "Were you hoping to sign up for a\n"
	.string "membership in our FAN CLUB?$"

SaffronCity_PokemonTrainerFanClub_Text_YouveStillAWaysToGo::
# 67 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Ah, so you are the much- talked-about\n"
	.string "{PLAYER}.\p"
	.string "You certainly do have the look of a\n"
	.string "winner.\p"
	.string "But for me to accept you as a true\n"
	.string "POKéMON great…\p"
	.string "… …\p"
	.string "You've still a ways to go!$"

SaffronCity_PokemonTrainerFanClub_Text_YoullBeTalkedAboutIfYouKeepWinning::
# 71 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "All of us gathered here are fans of\n"
	.string "POKéMON TRAINERS.\p"
	.string "The way they look in battle… They are\n"
	.string "the picture of coolness.\p"
	.string "Perhaps you will be talked about here,\n"
	.string "too, if you keep winning.$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeYouOneDay::
# 75 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "It's {PLAYER}! It's {PLAYER}!\p"
	.string "I want to be like {PLAYER} one day!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneButMeStoppedBeingYourFan::
# 79 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Everyone stopped being {PLAYER}'s\n"
	.string "fan…\p"
	.string "But that means I can have {PLAYER}\n"
	.string "all to myself!\p"
	.string "Yay! Go for it! My one and only\n"
	.string "{PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_WantToBeLikeSabrina::
# 83 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Do you know what? I want to be like\n"
	.string "SABRINA!\p"
	.string "I want to be a psychic girl just like\n"
	.string "her!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingSabrinasFan::
# 87 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Even if I'm the only one, I won't stop\n"
	.string "being SABRINA's fan.\p"
	.string "My dream is to be like SABRINA, cute,\n"
	.string "but cool.\p"
	.string "I want to be a psychic girl just like\n"
	.string "her!$"

SaffronCity_PokemonTrainerFanClub_Text_CanIBecomeCoolTrainerOneDay::
# 91 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I wonder if I can become a cool TRAINER\n"
	.string "one day?$"

SaffronCity_PokemonTrainerFanClub_Text_TheWayYouBattleIsCool::
# 95 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh, man, oh, man! Cool! Too cool!\p"
	.string "…Huh? No, not you.\p"
	.string "Just the way you battle. That's cool.$"

SaffronCity_PokemonTrainerFanClub_Text_ImOnlyOneLeftOfYourFans::
# 99 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Yo, {PLAYER}!\p"
	.string "Looks like I'm the only one left out of\n"
	.string "your fans.\p"
	.string "But, you know, I like being an only fan…\n"
	.string "It's less stressful.\p"
	.string "Keep up and at it!$"

SaffronCity_PokemonTrainerFanClub_Text_LoveWayTrainerTalks::
# 103 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "{STR_VAR_1}'s cool, huh? I love the\n"
	.string "way he talks.\p"
	.string "I'd really relish a chance to meet him in\n"
	.string "person once.$"

SaffronCity_PokemonTrainerFanClub_Text_ImLoneTrainerFan::
# 107 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Huh, can you believe it? Everyone\n"
	.string "turned into your fans.\p"
	.string "So after all we've been through, I'm the\n"
	.string "lone {STR_VAR_1} fan?\p"
	.string "Eh, being the one and only\n"
	.string "{STR_VAR_1} fan's my style, anyway.$"

SaffronCity_PokemonTrainerFanClub_Text_AdoreWayYouBattle::
# 111 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh, my goodness! Is it really you,\n"
	.string "{PLAYER}?\p"
	.string "I have to tell you, I adore the way you\n"
	.string "battle.\p"
	.string "I hope you'll keep at it. I'll be your\n"
	.string "number one fan!$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourNumberOneFan::
# 115 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh, my goodness! If it isn't {PLAYER}!\p"
	.string "It's so disappointing… I realized I'm\n"
	.string "your number-one-and-only fan!\p"
	.string "Well, it can't be helped! Let me cheer\n"
	.string "you on, at least!\p"
	.string "Hurray, hurray, {PLAYER}!$"

SaffronCity_PokemonTrainerFanClub_Text_TrainerHasBeenOnFire::
# 119 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Recently, {STR_VAR_1} has been on\n"
	.string "fire.\p"
	.string "The way he battles… It's just the way\n"
	.string "that I like it!$"

SaffronCity_PokemonTrainerFanClub_Text_EveryoneTalksAboutYou::
# 123 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Oh, hello! If it isn't {PLAYER}!\p"
	.string "Lately, all everyone talks about is you.\p"
	.string "I'm feeling lonesome because I prefer\n"
	.string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YouReallyAreAmazing::
# 127 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Amazing! {PLAYER}, you really are\n"
	.string "amazing!\p"
	.string "Instead of just watching, maybe I\n"
	.string "should become a TRAINER, too.$"

SaffronCity_PokemonTrainerFanClub_Text_ImYourOnlyFan::
# 131 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I'm your only fan… Sigh… This is lonely…\p"
	.string "Can't you try harder and make the\n"
	.string "others take notice of you?$"

SaffronCity_PokemonTrainerFanClub_Text_WhyCantOthersSeeMastersDignity::
# 135 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Master {STR_VAR_1} is so dignified…\n"
	.string "He is so my type.\p"
	.string "Why can't the others see the dignity he\n"
	.string "simply oozes?$"

SaffronCity_PokemonTrainerFanClub_Text_BelieveInMasterWithAllMyHeart::
# 139 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "I believe in Master {STR_VAR_1} with\n"
	.string "all my heart.\p"
	.string "Even if I am the only one to believe in\n"
	.string "him.\p"
	.string "I won't ever feel lonesome, though.\p"
	.string "Not if I keep thinking about Master\n"
	.string "{STR_VAR_1}.$"

SaffronCity_PokemonTrainerFanClub_Text_YourBattleStyleIsEducational::
# 143 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Hiyah!\p"
	.string "Your battling style is most\n"
	.string "educational.\p"
	.string "I hope that you will keep plugging away\n"
	.string "at success, hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_WontStopBeingYourFan::
# 147 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Instead of just watching others\n"
	.string "battle, battle yourself!\p"
	.string "…My DOJO's MASTER chewed me out like\n"
	.string "that…\p"
	.string "But I won't let that stop me from being\n"
	.string "your fan!\p"
	.string "I can't stop being your fan!$"

SaffronCity_PokemonTrainerFanClub_Text_OnlyMasterHasMyRespect::
# 151 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Hiyah! There is but one TRAINER who has\n"
	.string "my respect.\p"
	.string "And that is none other than my MASTER\n"
	.string "at the FIGHTING DOJO.\p"
	.string "You should become a fan of my MASTER\n"
	.string "like me! Hiyah!$"

SaffronCity_PokemonTrainerFanClub_Text_NeverBeFanOfAnyoneButMaster::
# 155 "data/maps/SaffronCity_PokemonTrainerFanClub/scripts.pory"
	.string "Hiyah! I respect my MASTER at the\n"
	.string "FIGHTING DOJO.\p"
	.string "I will never become a fan of anyone\n"
	.string "other than my MASTER!\p"
	.string "I will even sneak out of the DOJO to\n"
	.string "spread word of his greatness.\p"
	.string "Hiyah!$"
