Route8_MapScripts::
	.byte 0


Route8_Text_AidanIntro::
# 5 "data/maps/Route8/scripts.pory"
	.string "You look good at POKMON, but how is your\n"
	.string "chemistry grade?$"

Route8_Text_AidanDefeat::
# 9 "data/maps/Route8/scripts.pory"
	.string "Ow! Meltdown!$"

Route8_Text_AidanPostBattle::
# 13 "data/maps/Route8/scripts.pory"
	.string "I am better at school than this!$"

Route8_Text_StanIntro::
# 17 "data/maps/Route8/scripts.pory"
	.string "All right! Let's play a game!$"

Route8_Text_StanDefeat::
# 21 "data/maps/Route8/scripts.pory"
	.string "Drat! Came up short!$"

Route8_Text_StanPostBattle::
# 25 "data/maps/Route8/scripts.pory"
	.string "Things didn't work today.$"

Route8_Text_GlennIntro::
# 29 "data/maps/Route8/scripts.pory"
	.string "You should be informed. You need\n"
	.string "strategy to win at this!$"

Route8_Text_GlennDefeat::
# 33 "data/maps/Route8/scripts.pory"
	.string "It's not logical!$"

Route8_Text_GlennPostBattle::
# 37 "data/maps/Route8/scripts.pory"
	.string "Go with GRIMER firstand andthen$"

Route8_Text_PaigeIntro::
# 41 "data/maps/Route8/scripts.pory"
	.string "I like NIDORAN, so I collect them!$"

Route8_Text_PaigeDefeat::
# 45 "data/maps/Route8/scripts.pory"
	.string "Why? Why??$"

Route8_Text_PaigePostBattle::
# 49 "data/maps/Route8/scripts.pory"
	.string "When POKMON grow up, they get ugly!\n"
	.string "They shouldn't evolve.$"

Route8_Text_LeslieIntro::
# 53 "data/maps/Route8/scripts.pory"
	.string "School is fun, but so are POKMON.$"

Route8_Text_LeslieDefeat::
# 57 "data/maps/Route8/scripts.pory"
	.string "You made it clear to me that I should\n"
	.string "stick with school.$"

Route8_Text_LesliePostBattle::
# 61 "data/maps/Route8/scripts.pory"
	.string "I was planning on getting some fresh\n"
	.string "air for a change, but\p"
	.string "We're stuck here because of the gates\n"
	.string "at SAFFRON.$"

Route8_Text_AndreaIntro::
# 65 "data/maps/Route8/scripts.pory"
	.string "MEOWTH is so cute, meow, meow, meow!$"

Route8_Text_AndreaDefeat::
# 69 "data/maps/Route8/scripts.pory"
	.string "Meeeeyow!$"

Route8_Text_AndreaPostBattle::
# 73 "data/maps/Route8/scripts.pory"
	.string "I think PIDGEY and RATTATA are cute,\n"
	.string "too!$"

Route8_Text_MeganIntro::
# 77 "data/maps/Route8/scripts.pory"
	.string "We must look silly standing here like\n"
	.string "this.$"

Route8_Text_MeganDefeat::
# 81 "data/maps/Route8/scripts.pory"
	.string "Look what you did to my poor, cute\n"
	.string "POKMON!$"

Route8_Text_MeganPostBattle::
# 85 "data/maps/Route8/scripts.pory"
	.string "SAFFRON's gatekeeper won't let us go\n"
	.string "through.\p"
	.string "I know he's doing his job, but I think\n"
	.string "he's mean.$"

Route8_Text_RichIntro::
# 89 "data/maps/Route8/scripts.pory"
	.string "I'm a rambling, gaming dude!$"

Route8_Text_RichDefeat::
# 93 "data/maps/Route8/scripts.pory"
	.string "Missed the big chance!$"

Route8_Text_RichPostBattle::
# 97 "data/maps/Route8/scripts.pory"
	.string "Playing games and POKMON are like\n"
	.string "eating peanuts! I just can't stop!$"

Route8_Text_JuliaIntro::
# 101 "data/maps/Route8/scripts.pory"
	.string "What's a cute, round, and fluffy\n"
	.string "POKMON?$"

Route8_Text_JuliaDefeat::
# 105 "data/maps/Route8/scripts.pory"
	.string "Stop!\p"
	.string "Don't be so mean to my CLEFAIRY!$"

Route8_Text_JuliaPostBattle::
# 109 "data/maps/Route8/scripts.pory"
	.string "I read that CLEFAIRY evolves when it's\n"
	.string "exposed to a MOON STONE.\p"
	.string "I read that in a POKMON JOURNAL. I\n"
	.string "wonder if it's true?$"

Route8_Text_UndergroundPathSign::
# 113 "data/maps/Route8/scripts.pory"
	.string "UNDERGROUND PATH CELADON CITY -\n"
	.string "LAVENDER TOWN$"

Route8_Text_EliIntro::
# 117 "data/maps/Route8/scripts.pory"
	.string "ELI: Twin power is fantastic. Did you\n"
	.string "know?$"

Route8_Text_EliDefeat::
# 121 "data/maps/Route8/scripts.pory"
	.string "ELI: But We used our twin power$"

Route8_Text_EliPostBattle::
# 125 "data/maps/Route8/scripts.pory"
	.string "ELI: I caught my POKMON with ANNE!$"

Route8_Text_EliNotEnoughMons::
# 129 "data/maps/Route8/scripts.pory"
	.string "ELI: We can't battle if you don't have\n"
	.string "two POKMON.$"

Route8_Text_AnneIntro::
# 133 "data/maps/Route8/scripts.pory"
	.string "ANNE: We'll shock you with our twin\n"
	.string "power!$"

Route8_Text_AnneDefeat::
# 137 "data/maps/Route8/scripts.pory"
	.string "ANNE: Our twin power$"

Route8_Text_AnnePostBattle::
# 141 "data/maps/Route8/scripts.pory"
	.string "ANNE: I'm raising POKMON with ELI.$"

Route8_Text_AnneNotEnoughMons::
# 145 "data/maps/Route8/scripts.pory"
	.string "ANNE: Hi, hi! Let's battle! But bring two\n"
	.string "POKMON.$"

Route8_Text_RicardoIntro::
# 149 "data/maps/Route8/scripts.pory"
	.string "My bike's acting up, man.$"

Route8_Text_RicardoDefeat::
# 153 "data/maps/Route8/scripts.pory"
	.string "Aww, man. I'm not into this.$"

Route8_Text_RicardoPostBattle::
# 157 "data/maps/Route8/scripts.pory"
	.string "I got grass caught up in my spokes, man.$"

Route8_Text_JarenIntro::
# 161 "data/maps/Route8/scripts.pory"
	.string "Clear the way, or I'll run you down!$"

Route8_Text_JarenDefeat::
# 165 "data/maps/Route8/scripts.pory"
	.string "You for real, kid?$"

Route8_Text_JarenPostBattle::
# 169 "data/maps/Route8/scripts.pory"
	.string "Don't think you're all special and all\n"
	.string "just because of this.$"
