MagmaHideout_3F_1R_MapScripts::
	.byte 0


MagmaHideout_3F_1R_Text_Grunt9Intro::
# 5 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "What did I do to deserve this guard\n"
	.string "posting?\p"
	.string "My left ear is burning up!$"

MagmaHideout_3F_1R_Text_Grunt9Defeat::
# 9 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "I'm getting heat exhaustion$"

MagmaHideout_3F_1R_Text_Grunt9PostBattle::
# 13 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Do you think it's odd that we're wearing\n"
	.string "hoods in this magma-filled volcano?$"

MagmaHideout_3F_1R_Text_Grunt16Intro::
# 17 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "We joined so we can help our leader\n"
	.string "achieve his fantastic vision.\p"
	.string "I don't care if you're with TEAM AQUA or\n"
	.string "if you're just some kid passing by.\p"
	.string "No one interferes with us and gets away\n"
	.string "with it!$"

MagmaHideout_3F_1R_Text_Grunt16Defeat::
# 21 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Oh, no! You're not to be trusted at all!$"

MagmaHideout_3F_1R_Text_Grunt16PostBattle::
# 25 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Listen to me. TEAM MAGMA is right!\p"
	.string "Don't listen to TEAM AQUA. Don't believe\n"
	.string "their lies!$"
