MagmaHideout_3F_1R_MapScripts::
	.byte 0


MagmaHideout_3F_1R_EventScript_Grunt16::
# 5 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_16, MagmaHideout_3F_1R_Text_Grunt16Intro, MagmaHideout_3F_1R_Text_Grunt16Defeat, Text_NotEnoughMonsForDoubleBattle
# 6 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt16PostBattle
	return


MagmaHideout_3F_1R_EventScript_Grunt9::
# 10 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	trainerbattle_double TRAINER_GRUNT_MAGMA_HIDEOUT_9, MagmaHideout_3F_1R_Text_Grunt9Intro, MagmaHideout_3F_1R_Text_Grunt9Defeat, Text_NotEnoughMonsForDoubleBattle
# 11 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	msgbox MagmaHideout_3F_1R_Text_Grunt9PostBattle
	return


MagmaHideout_3F_1R_Text_Grunt16Defeat::
# 16 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt16Defeat$"

MagmaHideout_3F_1R_Text_Grunt16Intro::
# 20 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt16Intro$"

MagmaHideout_3F_1R_Text_Grunt16PostBattle::
# 24 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt16PostBattle$"

MagmaHideout_3F_1R_Text_Grunt9Defeat::
# 28 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt9Defeat$"

MagmaHideout_3F_1R_Text_Grunt9Intro::
# 32 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt9Intro$"

MagmaHideout_3F_1R_Text_Grunt9PostBattle::
# 36 "data/maps/MagmaHideout_3F_1R/scripts.pory"
	.string "Placeholder text for\n"
	.string "MagmaHideout_3F_1R_Text_Grunt9PostBattle$"
