FiveIsland_LostCave_Room10_MapScripts::
# 2 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FiveIsland_LostCave_Room10_OnResume
# 3 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FiveIsland_LostCave_Room10_OnFrame
	.byte 0


FiveIsland_LostCave_Room10_MapScripts::
# 7 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FiveIsland_LostCave_Room10_OnResume
# 8 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FiveIsland_LostCave_Room10_OnFrame
	return

