FiveIsland_LostCave_Room10_MapScripts::
# 2 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, FiveIsland_LostCave_Room10_OnResume
# 3 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FiveIsland_LostCave_Room10_OnFrame
	.byte 0


FiveIsland_LostCave_Room10_Text_SelphyIntro::
# 7 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	.string "W-what do you intend to do with me?$"

FiveIsland_LostCave_Room10_Text_SelphyDefeat::
# 11 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	.string "Oh… I was afraid that you meant to harm\n"
	.string "me.$"

FiveIsland_LostCave_Room10_Text_MayIAskYouToTakeMeHome::
# 15 "data/maps/FiveIsland_LostCave_Room10/scripts.pory"
	.string "I am so glad that you happened here.\p"
	.string "I grew rather bored of walking, and I am\n"
	.string "feeling fatigued.\p"
	.string "May I ask you to take me home from\n"
	.string "here?$"
