CeladonCity_DepartmentStore_4F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
# 5 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "I'm getting a present for my girlfriend.\p"
	.string "I guess a POKé DOLL will be it. It's the\n"
	.string "popular thing.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
# 9 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "I heard something useful.\p"
	.string "If a wild POKéMON appears, you can\n"
	.string "distract it with a POKé DOLL.\p"
	.string "You can run away while the wild POKéMON\n"
	.string "is distracted.$"

CeladonCity_DepartmentStore_4F_Text_FloorSign::
# 13 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "Express yourself with gifts! 4F: WISE\n"
	.string "MAN GIFTS\p"
	.string "Evolution Special! Element STONES on\n"
	.string "sale now!$"
