CeladonCity_DepartmentStore_4F_MapScripts::
	.byte 0


CeladonCity_DepartmentStore_4F_EventScript_Clerk::
	end


CeladonCity_DepartmentStore_4F_EventScript_FloorSign::
# 9 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_4F_Text_FloorSign, MSGBOX_SIGN
	end


CeladonCity_DepartmentStore_4F_EventScript_Man::
# 14 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_4F_EventScript_Youngster::
# 19 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	msgbox CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll, MSGBOX_NPC
	end


CeladonCity_DepartmentStore_4F_Text_FloorSign::
# 24 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "Express yourself with gifts! 4F: WISE\n"
	.string "MAN GIFTS\p"
	.string "Evolution Special! Element STONES on\n"
	.string "sale now!$"

CeladonCity_DepartmentStore_4F_Text_GettingPokeDollAsPresent::
# 28 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "I'm getting a present for my\n"
	.string "girlfriend.\p"
	.string "I guess a POKé DOLL will be it.\n"
	.string "It's the popular thing.$"

CeladonCity_DepartmentStore_4F_Text_CanRunAwayWithPokeDoll::
# 32 "data/maps/CeladonCity_DepartmentStore_4F/scripts.pory"
	.string "I heard something useful.\p"
	.string "If a wild POKéMON appears, you can\n"
	.string "distract it with a POKé DOLL.\p"
	.string "You can run away while the wild\n"
	.string "POKéMON is distracted.$"
