ViridianCity_House_MapScripts::
	.byte 0


ViridianCity_House_EventScript_BaldingMan::
# 5 "data/maps/ViridianCity_House/scripts.pory"
	msgbox ViridianCity_House_Text_NicknamingIsFun, MSGBOX_NPC
	end


ViridianCity_House_EventScript_LittleGirl::
# 10 "data/maps/ViridianCity_House/scripts.pory"
	msgbox ViridianCity_House_Text_MyDaddyLovesMonsToo, MSGBOX_NPC
	end


ViridianCity_House_EventScript_NicknameSign::
# 15 "data/maps/ViridianCity_House/scripts.pory"
	msgbox ViridianCity_House_Text_SpearowNameSpeary, MSGBOX_SIGN
	end


ViridianCity_House_EventScript_Speary::
	end


ViridianCity_House_Text_SpearowNameSpeary::
# 24 "data/maps/ViridianCity_House/scripts.pory"
	.string "SPEAROW Name: SPEARY$"

ViridianCity_House_Text_NicknamingIsFun::
# 28 "data/maps/ViridianCity_House/scripts.pory"
	.string "Coming up with nicknames is fun,\n"
	.string "but it's not so easy to do.\p"
	.string "Clever names are nice, but simple\n"
	.string "names are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
# 32 "data/maps/ViridianCity_House/scripts.pory"
	.string "My daddy loves POKéMON, too.$"
