ViridianCity_House_MapScripts::
	.byte 0


ViridianCity_House_Text_NicknamingIsFun::
# 5 "data/maps/ViridianCity_House/scripts.pory"
	.string "Coming up with nicknames is fun, but\n"
	.string "it's not so easy to do.\p"
	.string "Clever names are nice, but simple names\n"
	.string "are easier to remember.$"

ViridianCity_House_Text_MyDaddyLovesMonsToo::
# 9 "data/maps/ViridianCity_House/scripts.pory"
	.string "My daddy loves POKéMON, too.$"

ViridianCity_House_Text_Speary::
# 13 "data/maps/ViridianCity_House/scripts.pory"
	.string "SPEARY: Tetweet!$"

ViridianCity_House_Text_SpearowNameSpeary::
# 17 "data/maps/ViridianCity_House/scripts.pory"
	.string "SPEAROW Name: SPEARY$"
