SilphCo_3F_MapScripts::
# 2 "data/maps/SilphCo_3F/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, SilphCo_3F_OnLoad
	.byte 0


SilphCo_3F_Text_WhatAmIToDo::
# 6 "data/maps/SilphCo_3F/scripts.pory"
	.string "I work for SILPH CO. What am I to do?$"

SilphCo_3F_Text_YouAndYourMonsSavedUs::
# 10 "data/maps/SilphCo_3F/scripts.pory"
	.string "{PLAYER}! You and your POKéMON saved\n"
	.string "us!$"

SilphCo_3F_Text_GruntIntro::
# 14 "data/maps/SilphCo_3F/scripts.pory"
	.string "Quit messing with us, kid!$"

SilphCo_3F_Text_GruntDefeat::
# 18 "data/maps/SilphCo_3F/scripts.pory"
	.string "I give up!$"

SilphCo_3F_Text_GruntPostBattle::
# 22 "data/maps/SilphCo_3F/scripts.pory"
	.string "A hint? You can open doors with a CARD\n"
	.string "KEY!$"

SilphCo_3F_Text_JoseIntro::
# 26 "data/maps/SilphCo_3F/scripts.pory"
	.string "I support TEAM ROCKET more than I\n"
	.string "support SILPH CO.!$"

SilphCo_3F_Text_JoseDefeat::
# 30 "data/maps/SilphCo_3F/scripts.pory"
	.string "You really got me!$"

SilphCo_3F_Text_JosePostBattle::
# 34 "data/maps/SilphCo_3F/scripts.pory"
	.string "Humph…\p"
	.string "TEAM ROCKET said that if I helped them,\n"
	.string "they'd let me study POKéMON.$"

SilphCo_3F_Text_FloorSign::
# 38 "data/maps/SilphCo_3F/scripts.pory"
	.string "SILPH CO. HEAD OFFICE 3F$"
