LilycoveCity_DepartmentStore_2F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_2F_Text_LearnToUseItemsProperly::
# 5 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "Learn to use items properly. That's\n"
	.string "basic, really.$"

LilycoveCity_DepartmentStore_2F_Text_GoodGiftForHusband::
# 9 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "My husband is waiting at home. What\n"
	.string "would make a good gift for him?$"

LilycoveCity_DepartmentStore_2F_Text_StockUpOnItems::
# 13 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "I'm leaving on a long journey soon. I\n"
	.string "need to stock up on items.$"
