LilycoveCity_DepartmentStore_2F_MapScripts::
	.byte 0


LilycoveCity_DepartmentStore_2F_EventScript_ClerkLeft::
	end


LilycoveCity_DepartmentStore_2F_EventScript_ClerkRight::
	end


LilycoveCity_DepartmentStore_2F_EventScript_Cook::
# 13 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_2F_Text_LearnToUseItemsProperly, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_2F_EventScript_PokefanF::
# 18 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_2F_Text_GoodGiftForHusband, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_2F_EventScript_Sailor::
# 23 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	msgbox LilycoveCity_DepartmentStore_2F_Text_StockUpOnItems, MSGBOX_NPC
	end


LilycoveCity_DepartmentStore_2F_Text_LearnToUseItemsProperly::
# 27 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "Learn to use items properly.\n"
	.string "That's basic, really.$"

LilycoveCity_DepartmentStore_2F_Text_GoodGiftForHusband::
# 31 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "My husband is waiting at home.\n"
	.string "What would make a good gift for him?$"

LilycoveCity_DepartmentStore_2F_Text_StockUpOnItems::
# 35 "data/maps/LilycoveCity_DepartmentStore_2F/scripts.pory"
	.string "I'm leaving on a long journey soon.\n"
	.string "I need to stock up on items.$"
