LittlerootTown_MapScripts::
	.byte 0


LittlerootTown_EventScript_BirchsLabSign::
# 5 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_ProfBirchsLab, MSGBOX_SIGN
	end


LittlerootTown_EventScript_Boy::
# 10 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_BirchSpendsDaysInLab, MSGBOX_NPC
	end


LittlerootTown_EventScript_BrendansHouseSign::
	end


LittlerootTown_EventScript_FatMan::
# 24 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanUsePCToStoreItems, MSGBOX_NPC
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger0::
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger1::
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger2::
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger3::
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger4::
	end


LittlerootTown_EventScript_GiveRunningShoesTrigger5::
	end


LittlerootTown_EventScript_GoSaveBirchTrigger::
# 53 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_CanYouGoSeeWhatsHappening, MSGBOX_DEFAULT
	end


LittlerootTown_EventScript_MaysHouseSign::
	end


LittlerootTown_EventScript_Mom::
	end


LittlerootTown_EventScript_NeedPokemonTriggerLeft::
	end


LittlerootTown_EventScript_NeedPokemonTriggerRight::
	end


LittlerootTown_EventScript_TownSign::
# 79 "data/maps/LittlerootTown/scripts.pory"
	msgbox LittlerootTown_Text_TownSign, MSGBOX_SIGN
	end


LittlerootTown_EventScript_Twin::
	end


LittlerootTown_Text_ProfBirchsLab::
# 88 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S POKéMON LAB$"

LittlerootTown_Text_TownSign::
# 92 "data/maps/LittlerootTown/scripts.pory"
	.string "LITTLEROOT TOWN “A town that can't be\n"
	.string "shaded any hue.”$"

LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut::
# 96 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, um, um!\p"
	.string "If you go outside and go in the grass,\n"
	.string "wild POKéMON will jump out!$"

LittlerootTown_Text_WearTheseRunningShoes::
# 100 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
	.string "introduce yourself to PROF. BIRCH?\p"
	.string "Oh! What an adorable POKéMON!\n"
	.string "You got it from PROF. BIRCH. How nice!\p"
	.string "You're your father's child, all right.\n"
	.string "You look good together with POKéMON!\p"
	.string "Here, honey! If you're going out on an\n"
	.string "adventure, wear these RUNNING SHOES.\p"
	.string "They'll put a zip in your step!$"

LittlerootTown_Text_BirchSpendsDaysInLab::
# 104 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out in\l"
	.string "the wild to do more research…\p"
	.string "When does PROF. BIRCH spend time\n"
	.string "at home?$"

LittlerootTown_Text_YouSavedBirch::
# 108 "data/maps/LittlerootTown/scripts.pory"
	.string "You saved PROF. BIRCH!\n"
	.string "I'm so glad!$"

LittlerootTown_Text_CanUsePCToStoreItems::
# 112 "data/maps/LittlerootTown/scripts.pory"
	.string "If you use a PC, you can store items\n"
	.string "and POKéMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_BirchSomethingToShowYouAtLab::
# 116 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH: Well, well, {PLAYER}{KUN}!\n"
	.string "That was good work out there!\p"
	.string "I knew there was something special\n"
	.string "about you when I first saw you,\l"
	.string "but I never expected this.\p"
	.string "Oh, yes. Do you still have the POKéDEX\n"
	.string "I gave you?\p"
	.string "I have something to show you.\n"
	.string "Let's go to my LAB.$"

LittlerootTown_Text_GoodLuckCatchingPokemon::
# 120 "data/maps/LittlerootTown/scripts.pory"
	.string "Are you going to catch POKéMON?\n"
	.string "Good luck!$"

LittlerootTown_Text_ProfBirchsHouse::
# 124 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S HOUSE$"

LittlerootTown_Text_PlayersHouse::
# 128 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s HOUSE$"

LittlerootTown_Text_CanYouGoSeeWhatsHappening::
# 132 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, hi!\p"
	.string "There are scary POKéMON outside!\n"
	.string "I can hear their cries!\p"
	.string "I want to go see what's going on,\n"
	.string "but I don't have any POKéMON…\p"
	.string "Can you go see what's happening\n"
	.string "for me?$"
