LittlerootTown_MapScripts::
# 2 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, LittlerootTown_OnTransition
# 3 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, LittlerootTown_OnFrame
# 4 "data/maps/LittlerootTown/scripts.pory"
	map_script MAP_SCRIPT_ON_WARP_INTO_MAP_TABLE, LittlerootTown_OnWarp
	.byte 0


LittlerootTown_Text_OurNewHomeLetsGoInside::
# 8 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, we're here, honey!\p"
	.string "It must be tiring riding with our things\n"
	.string "in the moving truck.\p"
	.string "Well, this is LITTLEROOT TOWN.\p"
	.string "How do you like it? This is our new home!\p"
	.string "It has a quaint feel, but it seems to be\n"
	.string "an easy place to live, don't you think?\p"
	.string "And, you get your own room, {PLAYER}!\n"
	.string "Let's go inside.$"

LittlerootTown_Text_WaitPlayer::
# 12 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: Wait, {PLAYER}!$"

LittlerootTown_Text_WearTheseRunningShoes::
# 16 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}! {PLAYER}! Did you\n"
	.string "introduce yourself to PROF. BIRCH?\p"
	.string "Oh! What an adorable POKMON! You got it\n"
	.string "from PROF. BIRCH. How nice!\p"
	.string "You're your father's child, all right. You\n"
	.string "look good together with POKMON!\p"
	.string "Here, honey! If you're going out on an\n"
	.string "adventure, wear these RUNNING SHOES.\p"
	.string "They'll put a zip in your step!$"

LittlerootTown_Text_SwitchShoesWithRunningShoes::
# 20 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER} switched shoes with the\n"
	.string "RUNNING SHOES.$"

LittlerootTown_Text_ExplainRunningShoes::
# 24 "data/maps/LittlerootTown/scripts.pory"
	.string "MOM: {PLAYER}, those shoes came with\n"
	.string "instructions.\p"
	.string "Press the B Button while wearing these\n"
	.string "RUNNING SHOES to run extra-fast!\p"
	.string "Slip on these RUNNING SHOES and race in\n"
	.string "the great outdoors!$"

LittlerootTown_Text_ComeHomeIfAnythingHappens::
# 28 "data/maps/LittlerootTown/scripts.pory"
	.string "\p"
	.string "To think that you have your very own\n"
	.string "POKMON now\l"
	.string "Your father will be overjoyed.\p"
	.string "But please be careful. If anything\n"
	.string "happens, you can come home.\p"
	.string "Go on, go get them, honey!$"

LittlerootTown_Text_CanUsePCToStoreItems::
# 32 "data/maps/LittlerootTown/scripts.pory"
	.string "If you use a PC, you can store items and\n"
	.string "POKMON.\p"
	.string "The power of science is staggering!$"

LittlerootTown_Text_BirchSpendsDaysInLab::
# 36 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH spends days in his LAB\n"
	.string "studying, then he'll suddenly go out in\l"
	.string "the wild to do more research\p"
	.string "When does PROF. BIRCH spend time at\n"
	.string "home?$"

LittlerootTown_Text_IfYouGoInGrassPokemonWillJumpOut::
# 40 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, um, um!\p"
	.string "If you go outside and go in the grass,\n"
	.string "wild POKMON will jump out!$"

LittlerootTown_Text_DangerousIfYouDontHavePokemon::
# 44 "data/maps/LittlerootTown/scripts.pory"
	.string "It's dangerous if you don't have your\n"
	.string "own POKMON.$"

LittlerootTown_Text_CanYouGoSeeWhatsHappening::
# 48 "data/maps/LittlerootTown/scripts.pory"
	.string "Um, hi!\p"
	.string "There are scary POKMON outside! I can\n"
	.string "hear their cries!\p"
	.string "I want to go see what's going on, but I\n"
	.string "don't have any POKMON\p"
	.string "Can you go see what's happening for me?$"

LittlerootTown_Text_YouSavedBirch::
# 52 "data/maps/LittlerootTown/scripts.pory"
	.string "You saved PROF. BIRCH! I'm so glad!$"

LittlerootTown_Text_GoodLuckCatchingPokemon::
# 56 "data/maps/LittlerootTown/scripts.pory"
	.string "Are you going to catch POKMON? Good\n"
	.string "luck!$"

LittlerootTown_Text_TownSign::
# 60 "data/maps/LittlerootTown/scripts.pory"
	.string "LITTLEROOT TOWN A town that can't be\n"
	.string "shaded any hue.$"

LittlerootTown_Text_ProfBirchsLab::
# 64 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S POKMON LAB$"

LittlerootTown_Text_PlayersHouse::
# 68 "data/maps/LittlerootTown/scripts.pory"
	.string "{PLAYER}'s HOUSE$"

LittlerootTown_Text_ProfBirchsHouse::
# 72 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH'S HOUSE$"

LittlerootTown_Text_BirchSomethingToShowYouAtLab::
# 76 "data/maps/LittlerootTown/scripts.pory"
	.string "PROF. BIRCH: Well, well, {PLAYER}{KUN}! That\n"
	.string "was good work out there!\p"
	.string "I knew there was something special\n"
	.string "about you when I first saw you,\l"
	.string "but I never expected this.\p"
	.string "Oh, yes. Do you still have the POKDEX I\n"
	.string "gave you?\p"
	.string "I have something to show you. Let's go\n"
	.string "to my LAB.$"
