NavelRock_Base_MapScripts::
# 2 "data/maps/NavelRock_Base/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, NavelRock_Base_OnTransition
# 3 "data/maps/NavelRock_Base/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, NavelRock_Base_OnResume
	.byte 0


NavelRock_Base_MapScripts::
# 7 "data/maps/NavelRock_Base/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, NavelRock_Base_OnTransition
# 8 "data/maps/NavelRock_Base/scripts.pory"
	map_script MAP_SCRIPT_ON_RESUME, NavelRock_Base_OnResume
	return

