PalletTown_MapScripts::
# 2 "data/maps/PalletTown/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, PalletTown_OnTransition
# 3 "data/maps/PalletTown/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, PalletTown_OnFrame
	.byte 0


PalletTown_Text_OakDontGoOut::
# 7 "data/maps/PalletTown/scripts.pory"
	.string "OAK: Hey! Wait! Don't go out!$"

PalletTown_Text_OakGrassUnsafeNeedMon::
# 11 "data/maps/PalletTown/scripts.pory"
	.string "OAK: It's unsafe! Wild POKéMON live in\n"
	.string "tall grass!\p"
	.string "You need your own POKéMON for your\n"
	.string "protection.\p"
	.string "I know! Here, come with me!$"

PalletTown_Text_RaisingMonsToo::
# 15 "data/maps/PalletTown/scripts.pory"
	.string "I'm raising POKéMON, too.\p"
	.string "When they get strong, they can protect\n"
	.string "me.$"

PalletTown_Text_CanStoreItemsAndMonsInPC::
# 19 "data/maps/PalletTown/scripts.pory"
	.string "Technology is incredible!\p"
	.string "You can now store and recall items and\n"
	.string "POKéMON as data via PC.$"

PalletTown_Text_OakPokemonResearchLab::
# 23 "data/maps/PalletTown/scripts.pory"
	.string "OAK POKéMON RESEARCH LAB$"

PalletTown_Text_PlayersHouse::
# 27 "data/maps/PalletTown/scripts.pory"
	.string "{PLAYER}'s house$"

PalletTown_Text_RivalsHouse::
# 31 "data/maps/PalletTown/scripts.pory"
	.string "{RIVAL}'s house$"

PalletTown_Text_TownSign::
# 35 "data/maps/PalletTown/scripts.pory"
	.string "PALLET TOWN Shades of your journey\n"
	.string "await!$"

PalletTown_Text_OakLetMeSeePokedex::
# 39 "data/maps/PalletTown/scripts.pory"
	.string "OAK: Ah, {PLAYER}! You're back, are\n"
	.string "you?\p"
	.string "How much have you filled in your\n"
	.string "POKéDEX?\p"
	.string "May I see it?\p"
	.string "Let's see…$"

PalletTown_Text_CaughtXPuttingInHonestEffort::
# 43 "data/maps/PalletTown/scripts.pory"
	.string "You've caught {STR_VAR_2}…\p"
	.string "Hm, it looks as if you're putting in an\n"
	.string "honest effort.\p"
	.string "When you manage to fill it some more,\n"
	.string "come show me, please.$"

PalletTown_Text_CaughtXImpressiveFollowMe::
# 47 "data/maps/PalletTown/scripts.pory"
	.string "You've caught… {STR_VAR_2}!? Now,\n"
	.string "this is impressive!\p"
	.string "There's something I wanted to ask of\n"
	.string "you, {PLAYER}.\p"
	.string "Come. Follow me.$"

PalletTown_Text_OakYouEnjoyingTraveling::
# 51 "data/maps/PalletTown/scripts.pory"
	.string "OAK: Ah, {PLAYER}! You seem to be\n"
	.string "enjoying traveling.\p"
	.string "Knowing you, {PLAYER}, I can easily\n"
	.string "imagine you going out to even more\l"
	.string "exotic locales.\p"
	.string "Good for you, good for you. Hohoho.$"
