ThreeIsland_BerryForest_MapScripts::
# 2 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, ThreeIsland_BerryForest_OnTransition
	.byte 0


ThreeIsland_BerryForest_Text_HelpScaryPokemon::
# 6 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "LOSTELLE: Whimper Sniff Oh! Please,\n"
	.string "help!\p"
	.string "A scary POKMON appeared there a little\n"
	.string "while ago.\p"
	.string "It kept scaring. It made LOSTELLE\n"
	.string "scared.\p"
	.string "I'm too scared to move! But I want to go\n"
	.string "home$"

ThreeIsland_BerryForest_Text_HereItComesAgain::
# 10 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Oh! Here it comes again! No! Go away!\n"
	.string "It's scaring me!\p"
	.string "Waaaaaaah! I want my daddy!$"

ThreeIsland_BerryForest_Text_ThankYouHaveThis::
# 14 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Ohh! That was so scary! Thank you!\p"
	.string "LOSTELLE came to pick some BERRIES.\p"
	.string "You can have this!$"

ThreeIsland_BerryForest_Text_LetsGoHome::
# 18 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "What's your name?\p"
	.string "LOSTELLE's scared, so can I go with you\n"
	.string "to my daddy's house?\p"
	.string "Okay! Let's go home!$"

ThreeIsland_BerryForest_Text_BerryPouchIsFull::
# 22 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Your BERRY POUCH is full. I guess you\n"
	.string "don't want this.$"

ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
# 26 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Welcome to the BERRY FOREST\p"
	.string "Be friendly and share BERRIES with\n"
	.string "others and POKMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
# 30 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Beware of wild, BERRY-loving POKMON!$"
