ThreeIsland_BerryForest_MapScripts::
	.byte 0


ThreeIsland_BerryForest_EventScript_BewareSign::
# 5 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	msgbox ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons, MSGBOX_SIGN
	end


ThreeIsland_BerryForest_EventScript_Lostelle::
	end


ThreeIsland_BerryForest_EventScript_WelcomeSign::
# 14 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	msgbox ThreeIsland_BerryForest_Text_WelcomeToBerryForest, MSGBOX_SIGN
	end


ThreeIsland_BerryForest_Text_WelcomeToBerryForest::
# 19 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Welcome to the BERRY FOREST\p"
	.string "Be friendly and share BERRIES with\n"
	.string "others and POKéMON.$"

ThreeIsland_BerryForest_Text_BewareWildBerryLovingMons::
# 23 "data/maps/ThreeIsland_BerryForest/scripts.pory"
	.string "Beware of wild, BERRY-loving POKéMON!$"
