LilycoveCity_House4_MapScripts::
	.byte 0


LilycoveCity_House4_EventScript_Man1::
# 5 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_MysteriesAtBottomOfSea, MSGBOX_NPC
	end


LilycoveCity_House4_EventScript_Man2::
# 10 "data/maps/LilycoveCity_House4/scripts.pory"
	msgbox LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis, MSGBOX_NPC
	end


LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis::
# 14 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"

LilycoveCity_House4_Text_MysteriesAtBottomOfSea::
# 18 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "This planet's biggest mysteries are\n"
	.string "at the bottom of the sea.\p"
	.string "Somebody said that, but I don't know…$"
