LilycoveCity_House4_MapScripts::
	.byte 0


LilycoveCity_House4_Text_MysteriesAtBottomOfSea::
# 5 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "This planet's biggest mysteries are at\n"
	.string "the bottom of the sea.\p"
	.string "Somebody said that, but I don't know…$"

LilycoveCity_House4_Text_UnderwaterTrenchMossdeepSootopolis::
# 9 "data/maps/LilycoveCity_House4/scripts.pory"
	.string "There's a deep underwater trench\n"
	.string "between MOSSDEEP and SOOTOPOLIS.\p"
	.string "That's what someone told me, anyway.$"
