CeladonCity_Hotel_MapScripts::
	.byte 0


CeladonCity_Hotel_EventScript_Beauty::
# 5 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend, MSGBOX_NPC
	end


CeladonCity_Hotel_EventScript_BeautyBoyfriend::
# 10 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_WhyDidSheBringBrother, MSGBOX_NPC
	end


CeladonCity_Hotel_EventScript_BeautyBrother::
# 15 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_SisBroughtMeOnVacation, MSGBOX_NPC
	end


CeladonCity_Hotel_EventScript_Receptionist::
# 20 "data/maps/CeladonCity_Hotel/scripts.pory"
	msgbox CeladonCity_Hotel_Text_ThisHotelIsForPeople, MSGBOX_NPC
	end


CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
# 25 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "I'm on vacation with my brother and\n"
	.string "boyfriend.\p"
	.string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
# 29 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "Why?\n"
	.string "Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
# 33 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "Yippee! I'm on vacation!\n"
	.string "My sis brought me along! Awesome!$"

CeladonCity_Hotel_Text_ThisHotelIsForPeople::
# 37 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "POKéMON?\n"
	.string "No, this is a hotel for people.\p"
	.string "We're full up, unfortunately.$"
