CeladonCity_Hotel_MapScripts::
	.byte 0


CeladonCity_Hotel_Text_ThisHotelIsForPeople::
# 5 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "POKMON? No, this is a hotel for people.\p"
	.string "We're full up, unfortunately.$"

CeladonCity_Hotel_Text_OnVacationWithBrotherAndBoyfriend::
# 9 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "I'm on vacation with my brother and\n"
	.string "boyfriend.\p"
	.string "CELADON is such a pretty city!$"

CeladonCity_Hotel_Text_WhyDidSheBringBrother::
# 13 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "Why? Why did she bring her brother?$"

CeladonCity_Hotel_Text_SisBroughtMeOnVacation::
# 17 "data/maps/CeladonCity_Hotel/scripts.pory"
	.string "Yippee! I'm on vacation! My sis brought\n"
	.string "me along! Awesome!$"
