DewfordTown_Gym_MapScripts::
	.byte 0


DewfordTown_Gym_EventScript_Brawly::
	end


DewfordTown_Gym_EventScript_Brenden::
# 9 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_BRENDEN, DewfordTown_Gym_Text_BrendenIntro, DewfordTown_Gym_Text_BrendenDefeat, Text_NotEnoughMonsForDoubleBattle
# 10 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_BrendenPostBattle
	return


DewfordTown_Gym_EventScript_Cristian::
# 14 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_CRISTIAN, DewfordTown_Gym_Text_CristianIntro, DewfordTown_Gym_Text_CristianDefeat, Text_NotEnoughMonsForDoubleBattle
# 15 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_CristianPostBattle
	return


DewfordTown_Gym_EventScript_GymGuide::
	end


DewfordTown_Gym_EventScript_Jocelyn::
# 23 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_JOCELYN, DewfordTown_Gym_Text_JocelynIntro, DewfordTown_Gym_Text_JocelynDefeat, Text_NotEnoughMonsForDoubleBattle
# 24 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_JocelynPostBattle
	return


DewfordTown_Gym_EventScript_Laura::
# 28 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_LAURA, DewfordTown_Gym_Text_LauraIntro, DewfordTown_Gym_Text_LauraDefeat, Text_NotEnoughMonsForDoubleBattle
# 29 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_LauraPostBattle
	return


DewfordTown_Gym_EventScript_LeftGymStatue::
	end


DewfordTown_Gym_EventScript_Lilith::
# 40 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_LILITH, DewfordTown_Gym_Text_LilithIntro, DewfordTown_Gym_Text_LilithDefeat, Text_NotEnoughMonsForDoubleBattle
# 41 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_LilithPostBattle
	return


DewfordTown_Gym_EventScript_RightGymStatue::
	end


DewfordTown_Gym_EventScript_Takao::
# 52 "data/maps/DewfordTown_Gym/scripts.pory"
	trainerbattle_double TRAINER_TAKAO, DewfordTown_Gym_Text_TakaoIntro, DewfordTown_Gym_Text_TakaoDefeat, Text_NotEnoughMonsForDoubleBattle
# 53 "data/maps/DewfordTown_Gym/scripts.pory"
	msgbox DewfordTown_Gym_Text_TakaoPostBattle
	return


DewfordTown_Gym_Text_BrendenDefeat::
# 58 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_BrendenDefeat$"

DewfordTown_Gym_Text_BrendenIntro::
# 62 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_BrendenIntro$"

DewfordTown_Gym_Text_BrendenPostBattle::
# 66 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_BrendenPostBattle$"

DewfordTown_Gym_Text_CristianDefeat::
# 70 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_CristianDefeat$"

DewfordTown_Gym_Text_CristianIntro::
# 74 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_CristianIntro$"

DewfordTown_Gym_Text_CristianPostBattle::
# 78 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_CristianPostBattle$"

DewfordTown_Gym_Text_JocelynDefeat::
# 82 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_JocelynDefeat$"

DewfordTown_Gym_Text_JocelynIntro::
# 86 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_JocelynIntro$"

DewfordTown_Gym_Text_JocelynPostBattle::
# 90 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_JocelynPostBattle$"

DewfordTown_Gym_Text_LauraDefeat::
# 94 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LauraDefeat$"

DewfordTown_Gym_Text_LauraIntro::
# 98 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LauraIntro$"

DewfordTown_Gym_Text_LauraPostBattle::
# 102 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LauraPostBattle$"

DewfordTown_Gym_Text_LilithDefeat::
# 106 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LilithDefeat$"

DewfordTown_Gym_Text_LilithIntro::
# 110 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LilithIntro$"

DewfordTown_Gym_Text_LilithPostBattle::
# 114 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_LilithPostBattle$"

DewfordTown_Gym_Text_TakaoDefeat::
# 118 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_TakaoDefeat$"

DewfordTown_Gym_Text_TakaoIntro::
# 122 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_TakaoIntro$"

DewfordTown_Gym_Text_TakaoPostBattle::
# 126 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Placeholder text for\n"
	.string "DewfordTown_Gym_Text_TakaoPostBattle$"

DewfordTown_Gym_Text_GymGuidePostVictory::
# 130 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Whoah! It's turned too bright in here!\p"
	.string "Your future is bright, too!$"

DewfordTown_Gym_Text_BrawlyPostRematch::
# 134 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "BRAWLY: Battling is vast and it's deep.\n"
	.string "You can't see the bottom.\l"
	.string "It's just like the sea of HOENN!$"

DewfordTown_Gym_Text_ExplainBulkUp::
# 138 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "That TM08 contains BULK UP.\p"
	.string "It's a move that raises both ATTACK\n"
	.string "and DEFENSE stats.\p"
	.string "… … … … … …$"

DewfordTown_Gym_Text_GymStatue::
# 142 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "DEWFORD TOWN POKéMON GYM$"

DewfordTown_Gym_Text_GymStatueCertified::
# 146 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "DEWFORD TOWN POKéMON GYM\p"
	.string "BRAWLY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"
