DewfordTown_Gym_MapScripts::
# 2 "data/maps/DewfordTown_Gym/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, DewfordTown_Gym_OnTransition
	.byte 0


DewfordTown_Gym_Text_GymGuideAdvice::
# 6 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Hey, how's it going, CHAMPION- bound\n"
	.string "{PLAYER}?\p"
	.string "DEWFORD's GYM LEADER BRAWLY commands\n"
	.string "FIGHTING-type POKMON.\p"
	.string "Going against him with NORMAL-type\n"
	.string "POKMON is asking for trouble.\p"
	.string "FIGHTING POKMON will lay a serious\n"
	.string "smack down on NORMAL POKMON,\l"
	.string "so be careful!\p"
	.string "What's worse, the GYM is as dark as the\n"
	.string "ocean floor.\p"
	.string "But it will get brighter after defeating\n"
	.string "the TRAINERS in your way.\p"
	.string "Hey, okay, go for it!$"

DewfordTown_Gym_Text_GymGuidePostVictory::
# 10 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Whoah! It's turned too bright in here!\p"
	.string "Your future is bright, too!$"

DewfordTown_Gym_Text_TakaoIntro::
# 14 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Might is right! Come on!$"

DewfordTown_Gym_Text_TakaoDefeat::
# 18 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Not enough power$"

DewfordTown_Gym_Text_TakaoPostBattle::
# 22 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Your skill overcame my strength! Your\n"
	.string "technique is commendable!$"

DewfordTown_Gym_Text_JocelynIntro::
# 26 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "There's no need for BRAWLY to be\n"
	.string "involved!\p"
	.string "I'll crush you!$"

DewfordTown_Gym_Text_JocelynDefeat::
# 30 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "But How? How could I lose so easily?$"

DewfordTown_Gym_Text_JocelynPostBattle::
# 34 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "I'm not going to waste this loss. I'll\n"
	.string "use it to motivate me to train!\p"
	.string "One day I'll become a GYM LEADER\p"
	.string "No, I'll become the POKMON LEAGUE\n"
	.string "CHAMPION!$"

DewfordTown_Gym_Text_LauraIntro::
# 38 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Don't you dare brush me off! It's not my\n"
	.string "fault if you cry!$"

DewfordTown_Gym_Text_LauraDefeat::
# 42 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Waaaaaaah! I lost!$"

DewfordTown_Gym_Text_LauraPostBattle::
# 46 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "I battle in the dark to make my heart\n"
	.string "stronger.\p"
	.string "But because it's so dark, I can never\n"
	.string "see BRAWLY's face$"

DewfordTown_Gym_Text_LilithIntro::
# 50 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Ufufu Are you stumbling around in the\n"
	.string "dark?$"

DewfordTown_Gym_Text_LilithDefeat::
# 54 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Oh, you I don't want to know you!$"

DewfordTown_Gym_Text_LilithPostBattle::
# 58 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "You deserve to stay lost and end up\n"
	.string "back at the entrance again!$"

DewfordTown_Gym_Text_BrendenIntro::
# 62 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "I'll show you the gumption of a sailing\n"
	.string "man!$"

DewfordTown_Gym_Text_BrendenDefeat::
# 66 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "How'd this happen? It's not like me to\n"
	.string "lose this way!$"

DewfordTown_Gym_Text_BrendenPostBattle::
# 70 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Oh, aye! You're worthy of seeing our GYM\n"
	.string "LEADER.$"

DewfordTown_Gym_Text_CristianIntro::
# 74 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "If you mean to pass, it has to be\n"
	.string "through me!$"

DewfordTown_Gym_Text_CristianDefeat::
# 78 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Grrrrr! Vastly overpowered!$"

DewfordTown_Gym_Text_CristianPostBattle::
# 82 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "You win! Go after that BADGE!$"

DewfordTown_Gym_Text_BrawlyIntro::
# 86 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "I'm BRAWLY! DEWFORD's GYM LEADER!\p"
	.string "I've been churned in the rough waves of\n"
	.string "these parts, and I've grown tough\l"
	.string "in the pitch-black cave!\p"
	.string "So you wanted to challenge me? Let me\n"
	.string "see what you're made of!$"

DewfordTown_Gym_Text_BrawlyDefeat::
# 90 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Whoah, wow! You made a much bigger\n"
	.string "splash than I expected!\p"
	.string "You swamped me!\p"
	.string "Okay, you've got me. Take this GYM\n"
	.string "BADGE!$"

DewfordTown_Gym_Text_ReceivedKnuckleBadge::
# 94 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "{PLAYER} received the KNUCKLE BADGE\n"
	.string "from BRAWLY.$"

DewfordTown_Gym_Text_KnuckleBadgeInfoTakeThis::
# 98 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "The KNUCKLE BADGE makes all POKMON up\n"
	.string "to Level 30, even those you get in\l"
	.string "trades, obey without question.\p"
	.string "And, you'll be able to use the HM move\n"
	.string "FLASH outside of battle.\p"
	.string "If you'd like, use this TECHNICAL\n"
	.string "MACHINE, too.$"

DewfordTown_Gym_Text_ExplainBulkUp::
# 102 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "That TM08 contains BULK UP.\p"
	.string "It's a move that raises both ATTACK and\n"
	.string "DEFENSE stats.\p"
	.string "$"

DewfordTown_Gym_Text_RegisteredBrawly::
# 106 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Registered GYM LEADER BRAWLY in the\n"
	.string "POKNAV.$"

DewfordTown_Gym_Text_BrawlyPostBattle::
# 110 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "I can see your talent becoming a giant\n"
	.string "wave to cause a storm of astonishment\l"
	.string "among TRAINERS one day!$"

DewfordTown_Gym_Text_GymStatue::
# 114 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "DEWFORD TOWN POKMON GYM$"

DewfordTown_Gym_Text_GymStatueCertified::
# 118 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "DEWFORD TOWN POKMON GYM\p"
	.string "BRAWLY'S CERTIFIED TRAINERS:\n"
	.string "{PLAYER}$"

DewfordTown_Gym_Text_BrawlyPreRematch::
# 122 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "BRAWLY: A wave may draw back, but it\n"
	.string "always returns to the shore.\p"
	.string "A giant wave of a talent like you I knew\n"
	.string "you would return!\p"
	.string "Show me how much higher you've gone!$"

DewfordTown_Gym_Text_BrawlyRematchDefeat::
# 126 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "Wow! Swamped again!$"

DewfordTown_Gym_Text_BrawlyPostRematch::
# 130 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "BRAWLY: Battling is vast and it's deep.\n"
	.string "You can't see the bottom.\l"
	.string "It's just like the sea of HOENN!$"

DewfordTown_Gym_Text_BrawlyRematchNeedTwoMons::
# 134 "data/maps/DewfordTown_Gym/scripts.pory"
	.string "BRAWLY: A wave may draw back, but it\n"
	.string "always returns to the shore.\p"
	.string "A giant wave of a talent like you I knew\n"
	.string "you would return!\p"
	.string "Oh? You only have one POKMON that can\n"
	.string "battle.\p"
	.string "I'm sorry, but I'd like you to come back\n"
	.string "with at least two POKMON.$"
