NewBarkTown_PlayersHouse_2F_MapScripts::
	.byte 0


NewBarkTown_PlayersHouse_2F_EventScript_SmithNPC1::
# 5 "data/maps/NewBarkTown_PlayersHouse_2F/scripts.pory"
	msgbox NewBarkTown_PlayersHouse_2F_Text_SmithNPC1, MSGBOX_NPC
	end


NewBarkTown_PlayersHouse_2F_EventScript_SmithNPC2::
# 14 "data/maps/NewBarkTown_PlayersHouse_2F/scripts.pory"
	msgbox NewBarkTown_PlayersHouse_2F_Text_SmithNPC2, MSGBOX_NPC
	end


NewBarkTown_PlayersHouse_2F_Text_SmithNPC1::
# 9 "data/maps/NewBarkTown_PlayersHouse_2F/scripts.pory"
	.string "I've been expecting you, Mr. Anderson.$"

NewBarkTown_PlayersHouse_2F_Text_SmithNPC2::
# 18 "data/maps/NewBarkTown_PlayersHouse_2F/scripts.pory"
	.string "Human beings are a disease; I'm the\n"
	.string "cure.$"
