FourIsland_MapScripts::
	.byte 0


FourIsland_EventScript_DaycareMan::
	end


FourIsland_EventScript_FatMan::
# 9 "data/maps/FourIsland/scripts.pory"
	msgbox FourIsland_Text_MadeSlushieUsingIcefallCaveIce, MSGBOX_NPC
	end


FourIsland_EventScript_IslandSign::
# 14 "data/maps/FourIsland/scripts.pory"
	msgbox FourIsland_Text_IslandSign, MSGBOX_SIGN
	end


FourIsland_EventScript_LittleGirl::
	end


FourIsland_EventScript_LoreleisHouseSign::
# 23 "data/maps/FourIsland/scripts.pory"
	msgbox FourIsland_Text_LoreleisHouse, MSGBOX_SIGN
	end


FourIsland_EventScript_OldWoman::
	end


FourIsland_Text_IslandSign::
# 32 "data/maps/FourIsland/scripts.pory"
	.string "FOUR ISLAND The Warm, Blue, Floe Island$"

FourIsland_Text_LoreleisHouse::
# 36 "data/maps/FourIsland/scripts.pory"
	.string "LORELEI'S HOUSE$"

FourIsland_Text_MadeSlushieUsingIcefallCaveIce::
# 40 "data/maps/FourIsland/scripts.pory"
	.string "Ooh, chilly!\p"
	.string "I made a slushie using ice I\n"
	.string "shaved inside ICEFALL CAVE.\p"
	.string "It's chilly and tasty!$"
