FourIsland_MapScripts::
# 2 "data/maps/FourIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_OnTransition
# 3 "data/maps/FourIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FourIsland_OnFrame
	.byte 0


FourIsland_MapScripts::
# 7 "data/maps/FourIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, FourIsland_OnTransition
# 8 "data/maps/FourIsland/scripts.pory"
	map_script MAP_SCRIPT_ON_FRAME_TABLE, FourIsland_OnFrame
	return

