SSTidalRooms_MapScripts::
	.byte 0


SSTidalRooms_MapScripts::
	return


SSTidalRooms_Text_TakeRestOnBed::
# 8 "data/maps/SSTidalRooms/scripts.pory"
	.string "There's a bed… Let's take a rest.$"

SSTidalRooms_Text_ColtonIntro::
# 12 "data/maps/SSTidalRooms/scripts.pory"
	.string "I often sail to LILYCOVE CITY.\p"
	.string "I enjoy attending CONTESTS, you see.$"

SSTidalRooms_Text_ColtonDefeat::
# 16 "data/maps/SSTidalRooms/scripts.pory"
	.string "That was an enjoyable match!$"

SSTidalRooms_Text_ColtonPostBattle::
# 20 "data/maps/SSTidalRooms/scripts.pory"
	.string "I get so excited imagining what kinds\n"
	.string "of POKéMON I'll get to see in the next\l"
	.string "CONTEST. The anticipation of it thrills!$"

SSTidalRooms_Text_MicahIntro::
# 24 "data/maps/SSTidalRooms/scripts.pory"
	.string "Are your friends strong?$"

SSTidalRooms_Text_MicahDefeat::
# 28 "data/maps/SSTidalRooms/scripts.pory"
	.string "Your friends are, indeed, strong.$"

SSTidalRooms_Text_MicahPostBattle::
# 32 "data/maps/SSTidalRooms/scripts.pory"
	.string "Friends need not be human. For me,\n"
	.string "POKéMON are treasured friends!$"

SSTidalRooms_Text_ThomasIntro::
# 36 "data/maps/SSTidalRooms/scripts.pory"
	.string "Child… Did you knock on the door?$"

SSTidalRooms_Text_ThomasDefeat::
# 40 "data/maps/SSTidalRooms/scripts.pory"
	.string "A loss is to be accepted without haste\n"
	.string "or panic.$"

SSTidalRooms_Text_ThomasPostBattle::
# 44 "data/maps/SSTidalRooms/scripts.pory"
	.string "To be never ruffled in any situation is\n"
	.string "the GENTLEMAN's code of conduct.$"

SSTidalRooms_Text_JedIntro::
# 48 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: I feel a little shy about this, but…\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_JedDefeat::
# 52 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: Sigh…$"

SSTidalRooms_Text_JedPostBattle::
# 56 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: It's the first time that our lovey-\n"
	.string "dovey power couldn't prevail!\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_JedNotEnoughMons::
# 60 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: You only have one POKéMON? Isn't\n"
	.string "that just too lonesome?$"

SSTidalRooms_Text_LeaIntro::
# 64 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I feel a little silly, but… We'll\n"
	.string "show you our lovey-dovey power!$"

SSTidalRooms_Text_LeaDefeat::
# 68 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: Oh, boo!$"

SSTidalRooms_Text_LeaPostBattle::
# 72 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I can't believe it! Our lovey-dovey\n"
	.string "power failed…\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_LeaNotEnoughMons::
# 76 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I wanted to battle… But you don't\n"
	.string "even have two POKéMON…$"

SSTidalRooms_Text_GarretIntro::
# 80 "data/maps/SSTidalRooms/scripts.pory"
	.string "Ah, you've come just in time.\p"
	.string "I'm bored, you see. You may entertain\n"
	.string "me.$"

SSTidalRooms_Text_GarretDefeat::
# 84 "data/maps/SSTidalRooms/scripts.pory"
	.string "…That will do.$"

SSTidalRooms_Text_GarretPostBattle::
# 88 "data/maps/SSTidalRooms/scripts.pory"
	.string "Perhaps I shall get Father to acquire a\n"
	.string "yacht for me.\l"
	.string "A yacht for me and POKéMON!$"

SSTidalRooms_Text_NaomiIntro::
# 92 "data/maps/SSTidalRooms/scripts.pory"
	.string "Oh, you're such an adorable TRAINER.\n"
	.string "Would you like to have tea?\l"
	.string "Or would you rather battle?$"

SSTidalRooms_Text_NaomiDefeat::
# 96 "data/maps/SSTidalRooms/scripts.pory"
	.string "I see. You're the active sort.$"

SSTidalRooms_Text_NaomiPostBattle::
# 100 "data/maps/SSTidalRooms/scripts.pory"
	.string "A world cruise on a luxury liner has its\n"
	.string "charms, I must say…\p"
	.string "But, I will admit there is an appealing\n"
	.string "side to touring HOENN by ferry.$"

SSTidalRooms_Text_NotSuspiciousTakeThis::
# 104 "data/maps/SSTidalRooms/scripts.pory"
	.string "Uh… Hi! I… I'm not acting suspicious!\n"
	.string "Uh… You can have this! For free!\p"
	.string "It… Honestly, I didn't SNATCH it from\n"
	.string "someone! I'd never do such a thing!\l"
	.string "It's clean! You can use it!$"

SSTidalRooms_Text_ExplainSnatch::
# 108 "data/maps/SSTidalRooms/scripts.pory"
	.string "SNATCH steals the beneficial effects\n"
	.string "of certain moves before they can be\l"
	.string "used by a foe or ally.$"
