SSTidalRooms_MapScripts::
	.byte 0


SSTidalRooms_Text_TakeRestOnBed::
# 5 "data/maps/SSTidalRooms/scripts.pory"
	.string "There's a bed Let's take a rest.$"

SSTidalRooms_Text_ColtonIntro::
# 9 "data/maps/SSTidalRooms/scripts.pory"
	.string "I often sail to LILYCOVE CITY.\p"
	.string "I enjoy attending CONTESTS, you see.$"

SSTidalRooms_Text_ColtonDefeat::
# 13 "data/maps/SSTidalRooms/scripts.pory"
	.string "That was an enjoyable match!$"

SSTidalRooms_Text_ColtonPostBattle::
# 17 "data/maps/SSTidalRooms/scripts.pory"
	.string "I get so excited imagining what kinds\n"
	.string "of POKMON I'll get to see in the next\l"
	.string "CONTEST. The anticipation of it thrills!$"

SSTidalRooms_Text_MicahIntro::
# 21 "data/maps/SSTidalRooms/scripts.pory"
	.string "Are your friends strong?$"

SSTidalRooms_Text_MicahDefeat::
# 25 "data/maps/SSTidalRooms/scripts.pory"
	.string "Your friends are, indeed, strong.$"

SSTidalRooms_Text_MicahPostBattle::
# 29 "data/maps/SSTidalRooms/scripts.pory"
	.string "Friends need not be human. For me,\n"
	.string "POKMON are treasured friends!$"

SSTidalRooms_Text_ThomasIntro::
# 33 "data/maps/SSTidalRooms/scripts.pory"
	.string "Child Did you knock on the door?$"

SSTidalRooms_Text_ThomasDefeat::
# 37 "data/maps/SSTidalRooms/scripts.pory"
	.string "A loss is to be accepted without haste\n"
	.string "or panic.$"

SSTidalRooms_Text_ThomasPostBattle::
# 41 "data/maps/SSTidalRooms/scripts.pory"
	.string "To be never ruffled in any situation is\n"
	.string "the GENTLEMAN's code of conduct.$"

SSTidalRooms_Text_JedIntro::
# 45 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: I feel a little shy about this, but\n"
	.string "We'll show you our lovey-dovey power!$"

SSTidalRooms_Text_JedDefeat::
# 49 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: Sigh$"

SSTidalRooms_Text_JedPostBattle::
# 53 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: It's the first time that our lovey-\n"
	.string "dovey power couldn't prevail!\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_JedNotEnoughMons::
# 57 "data/maps/SSTidalRooms/scripts.pory"
	.string "JED: You only have one POKMON? Isn't\n"
	.string "that just too lonesome?$"

SSTidalRooms_Text_LeaIntro::
# 61 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I feel a little silly, but We'll show\n"
	.string "you our lovey-dovey power!$"

SSTidalRooms_Text_LeaDefeat::
# 65 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: Oh, boo!$"

SSTidalRooms_Text_LeaPostBattle::
# 69 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I can't believe it! Our lovey-dovey\n"
	.string "power failed\l"
	.string "You must be an awesome TRAINER!$"

SSTidalRooms_Text_LeaNotEnoughMons::
# 73 "data/maps/SSTidalRooms/scripts.pory"
	.string "LEA: I wanted to battle But you don't\n"
	.string "even have two POKMON$"

SSTidalRooms_Text_GarretIntro::
# 77 "data/maps/SSTidalRooms/scripts.pory"
	.string "Ah, you've come just in time.\p"
	.string "I'm bored, you see. You may entertain\n"
	.string "me.$"

SSTidalRooms_Text_GarretDefeat::
# 81 "data/maps/SSTidalRooms/scripts.pory"
	.string "That will do.$"

SSTidalRooms_Text_GarretPostBattle::
# 85 "data/maps/SSTidalRooms/scripts.pory"
	.string "Perhaps I shall get Father to acquire a\n"
	.string "yacht for me.\l"
	.string "A yacht for me and POKMON!$"

SSTidalRooms_Text_NaomiIntro::
# 89 "data/maps/SSTidalRooms/scripts.pory"
	.string "Oh, you're such an adorable TRAINER.\n"
	.string "Would you like to have tea?\l"
	.string "Or would you rather battle?$"

SSTidalRooms_Text_NaomiDefeat::
# 93 "data/maps/SSTidalRooms/scripts.pory"
	.string "I see. You're the active sort.$"

SSTidalRooms_Text_NaomiPostBattle::
# 97 "data/maps/SSTidalRooms/scripts.pory"
	.string "A world cruise on a luxury liner has its\n"
	.string "charms, I must say\p"
	.string "But, I will admit there is an appealing\n"
	.string "side to touring HOENN by ferry.$"

SSTidalRooms_Text_NotSuspiciousTakeThis::
# 101 "data/maps/SSTidalRooms/scripts.pory"
	.string "Uh Hi! I I'm not acting suspicious! Uh\n"
	.string "You can have this! For free!\p"
	.string "It Honestly, I didn't SNATCH it from\n"
	.string "someone! I'd never do such a thing!\l"
	.string "It's clean! You can use it!$"

SSTidalRooms_Text_ExplainSnatch::
# 105 "data/maps/SSTidalRooms/scripts.pory"
	.string "SNATCH steals the beneficial effects\n"
	.string "of certain moves before they can be\l"
	.string "used by a foe or ally.$"
